### ISSUE TITLE
[Feature request] Upgrade the PPA signing key to 4096 bits size

### ISSUE THREAD

**Issue by jean-christophe-manciot** [teambit/bit#1005]
The current PPA ```59DA D276 B942 642B 1BBD  0EAC A8AA 1FAA 3F05 5C03``` signing key has a 1024 bits size.
Current best practice is to use a 4096 bits RSA key.
I strongly suggest to follow that practice, especially for a software which deals with potentially sensitive data..

**Comment by itaymendel** [comment]
hi @jean-christophe-manciot , do you mean the signing key for the Bit dep package?
I'll have to check it, as we use a 3rd party to manage it.

**Comment by jean-christophe-manciot** [comment]
@itaymendel 
On https://launchpad.net/~bit-team/+archive/ubuntu/stable:

![image](https://user-images.githubusercontent.com/13176858/40598520-6c215038-6248-11e8-9f97-2ba6a692ff1e.png)

**Comment by itaymendel** [comment]
@jean-christophe-manciot , this package is not maintained by us and is not related to this project.
Bit uses jFrog as a repository to our deb packages, [as seen here](https://docs.bitsrc.io/docs/installation.html#debianubuntu-linux).
The package you linked here is was first released in 2013, and the development of Bit started on 2017.

I'm sorry, but I'm closing this issue, you will have to reach out to the maintainers of that package.
