### ISSUE TITLE
Support to extend Bit and use different package managers

### ISSUE THREAD

**Issue by jlarrubiaq** [teambit/bit#1019]
Hi,

is there a way to extend/use/configure Bit to support dependencies from different package managers? In my case, I'm working on a Meteor app which uses the package manager [atmosphere](https://atmospherejs.com/) but Bit is not able to resolve its dependencies and, therefore, create a component from files that use Meteor imports e.g. `import { Match } from 'meteor/check'; `

If not, will there be support for it?

Many thanks

**Comment by davidfirst** [comment]
Hi @jlarrubiaq, from a quick look, it seems like that Atmosphere is a replacement for NPM.
Bit currently doesn't support it. Only NPM.
However, in the upcoming version (will be released in a week), Bit supports 'custom module resolution' (implemented in https://github.com/teambit/bit/pull/980), which might help to resolve the dependencies correctly.
In the case above of `import { Match } from 'meteor/check'`, you'll be able to configure `meteor` as an alias and specify the directory where to look for.

**Comment by josensanchez** [comment]
does anybody find the way to make this working?
I'm setting resolveModules aliases to look for the meteor packages but I got nothing.
here is my bit.json
```
{
    "env": {},
    "dependencies": {},
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "npm",
    "resolveModules": {
      "aliases": {
          "meteor": "~/.meteor/packages/"
      }
    }
}
```
I try relative paths, full paths, symbolic links, etc.

**Comment by itaymendel** [comment]
bit only supports the node package registry specification. at the moment we do not plan to support additional APIs for package managers.

i'm closing this issue and will open it if we decided to try and implement an integration.

**Comment by GiladShoham** [comment]
@maxfi There is no such an option right now. Please open a different ticket for this and we will consider this. 
Thanks.
