### ISSUE TITLE
Components with image imports

### ISSUE THREAD

**Issue by ilyamerman** [teambit/bit#1025]
Hi, first of all: I love the project and was very impressed by it.

I was wondering if there's a way to export bit components that have images as imports, such as
`import SomeImage from './someImage.png`, this is being imported in our project (and in any create-react-app project) using file-loader.
When trying to export such a component, bit logs that the component has a missing dependency which is the image. The image itself can be turned into a component and exported and the dependency issue is solved. Then, when trying to export the component to a scope, an error log is shown: 
`no template was found for SomeImage, because .png extension is not supported`
but the export succeeds.

Then, when trying to npm install the component in another project, npm hangs and eventually shows a 500 internal server error.

We've seen the "Hero project" demo, all the images in it are external, is there a different suggested way to do it (for any image files, pngs, svgs etc.), or  is there a way for it that is being planned?

Thanks you :)

**Comment by itaymendel** [comment]
hi @ilyamerman , we have found an issue where a binary file might get corrupted upon import. the issue is resolved, and will be a part of Bit's next release.
