### ISSUE TITLE
Add files to component with Bit DSL

### ISSUE THREAD

**Issue by TopStar423** [teambit/bit#1037]
Is there any way to add file to existing component regarding the existing component name?
Currently we have {FILE_NAME} to use.
We can use this when we add test file or exclude some files.
But let's suppose we need to add some files which is related to the components.
For example, we have three directories.
components
test
asset

And there are files just like below structure and names.
components
    one.js
    two.js
    three.js
test
    one-test.js
    two-test.js
    three-test.js
asset
    one-asset.js
    two-asset.js
    three-asset.js

In this case we can create each component with tests with below command.
bit add components/*.js --tests 'test/{FILE_NAME}-test.js'
But I can't find any option to add the assets with FILE_NAME
Is there any way to add asset files automatically?

Let's suppose that there are such 100+ files..
Then we need to track all the files manually.
Is there any option to add the files using Bit DSL?
Just like:
bit add components/*.js --include 'asset/{FILE_NAME}.asset.js' --tests 'test/{FILE_NAME}-test.js'

**Comment by itaymendel** [comment]
Sorry for the very long response time. This issue seemed to fall between the cracks.
`add` supports wildcard `*` when tracking files, so you should be fine with using it to add as many files as you need (also nesting dirs with `**`).

**Comment by GiladShoham** [comment]
@itaymendel this won't solve his problem. reopened

**Comment by itaymendel** [comment]
moving away from `add` functionality to `create`. closing this issue as we will not resolve it.
