### ISSUE TITLE
Can we use DSL in --id option for bit add?

### ISSUE THREAD

**Issue by TopStar423** [teambit/bit#1038]
While using bit add, is it possible to use Bit DSL in --id option?
Just like:
bit add src/components/* --id 'src/{FILE_NAME}'

Let's suppose we have such kind of structure.

`A`
  src
      one.js
      two.js
      three.js
      ...
B
   src
       one.js
       two.js
       three.js

To track all the files as independent components in A/src/ and B/src, we can use following commands.
bit add A/src/*
bit add B/src/*

Once we do the first command (bit add A/src/*) it creates bit components as like this
"src/one": {
    "files": [
        {
            "relativePath": "A/src/one.js",
            "test": false,
            "name": "one.js"
        }
    ],
    "mainFile": "A/src/one.js",
    "origin": "AUTHORED"
}

Then when we do the second command (bit add B/src/*) it won't create new components but track the files in the already existing id.

So the component will be:
"src/one": {
    "files": [
        {
            "relativePath": "A/src/one.js",
            "test": false,
            "name": "one.js"
        },
        {
            "relativePath": "B/src/one.js",
            "test": false,
            "name": "one.js"
        }
    ],
    "mainFile": "A/src/one.js",
    "origin": "AUTHORED"
}

This isn't what we want, right?
So to avoid this, we need to set id different so that the components will look like this.
"A/one": {
    "files": [
        {
            "relativePath": "A/src/one.js",
            "test": false,
            "name": "one.js"
        }
     ],
    "mainFile": "A/src/one.js",
    "origin": "AUTHORED"
}
"B/one": {
    "files": [
        {
            "relativePath": "A/src/one.js",
            "test": false,
            "name": "one.js"
        }
     ],
    "mainFile": "A/src/one.js",
    "origin": "AUTHORED"
}

To do this we need to add each components with id manually as like:
bit add A/src/one.js --id A/one
bit add A/src/two.js --id A/two
bit add B/src/one.js --id B/one
bit add B/src/two.js --id B/two

If there are a lot of files with the same name in A and B, it needs us to do a lot of manual work.
To make this easily I want to know it is possible to use DSL in --id option.
If that is possible, we can do this tracking with the following command
bit add A/src/* --id 'A/{FILE_NAME}'
bit add B/src/* --id 'B/{FILE_NAME}'

Can we do this?

**Comment by itaymendel** [comment]
already available.

**Comment by GiladShoham** [comment]
that's not yet available, reopened.
