### ISSUE TITLE
[Feature] bit add - enable adding multiple component files by template

### ISSUE THREAD

**Issue by tomlandau** [teambit/bit#1039]
In many cases there's a single directory with multiple components, each component has multiple files, with a common name:

CloseEvent-impl.js
CloseEvent.webidl
CompositionEvent-impl.js
CompositionEvent.webidl

this is taken from here: https://github.com/jsdom/jsdom/tree/master/lib/jsdom/living/events

I'm not sure about the syntax, but I'd like to be able to add the whole dir in one command. something like:

bit add {id}-impl.js {id}.webidl

Bit will create components out of every two related files, and will also surmise that the component name is {id}.

**Comment by TopStar423** [comment]
This needs to indicate main file with --main option, I think.
And to do this do we need another DSL key for {id} you mentioned?
Once we have the option to add files to existing components or while creating, I think we can do this such following way.
bit add *-impl.js --include {id}.webidl

This is similar to the issue #1037

**Comment by tomlandau** [comment]
Yes, this would require specifying main file as well, of course.

Do you mean Bit would need to recognize {id} besides {PARENT} and {FILE_NAME}? yes, but these are implementation details.

Your syntax suggestion is also possible, we'd need to think what's better. Implementing both would cover more cases, of course.

There are similarties to issue #1037, but that depends on the implementation I guess.
Implementing DSL in the bit add itself and not in one of the flags is different.

**Comment by TopStar423** [comment]
Yes, completely agree.
Here's what you noticed.
bit add {id}-impl.js {id}.webidl

So here, is {id} some special flag similar to *?

**Comment by GiladShoham** [comment]
As a workaround for better granular management, you can use the programmatic API for `addMany`.
[Here](https://github.com/GiladShoham/bit-add-many-example) is a full example

**Comment by itaymendel** [comment]
moving to a single-directory component structure, so this is not relevant. closing.
