### ISSUE TITLE
missing package dependencies when  @import "~*.scss"

### ISSUE THREAD

**Issue by wysoki89** [teambit/bit#1041]
I have just started to use bit and have some problems with importing scss file. 

Folder structure:
![image](https://user-images.githubusercontent.com/17279338/40979236-7fb2326e-68d5-11e8-87ef-10cc6e326680.png)
![image](https://user-images.githubusercontent.com/17279338/40979260-99a5a674-68d5-11e8-8625-40c804725b2d.png)

In form-button.scss i have @import "~styles/settings";
After adding all files in form-button with: 
bit add src/components/common/form-button --main src/components/common/form-button/form-button.js --id form/button

I run bit status and get:
![image](https://user-images.githubusercontent.com/17279338/40979391-f4f99698-68d5-11e8-9198-5c1e9c567084.png)

with  DEBUG=* bit status I get that cabinet could not resolve styles/settings
![image](https://user-images.githubusercontent.com/17279338/40979716-db1f1f94-68d6-11e8-85cb-c69dd8592c17.png)

As I learned from https://github.com/teambit/bit/issues/900 - this is not an issue of not resolving tilde. Could you please, help me with this one ?

## Specifications

  - Bit version: 0.12.13
  - Node version: v8.9.4
  - npm version: 5.6.0
  - Platform: Ubuntu
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by yourownmood** [comment]
Same issue here with resolving a "simple" .scss file importing another .scss file

**Comment by itaymendel** [comment]
hi @wysoki89 @yourownmood , a new version of Bit is finally available, and supports configuring a custom module resolution.

more about it [here](https://docs.bitsrc.io/docs/troubleshooting-isolating.html)

**Comment by devth** [comment]
I'm having this exact same issue trying to import sass files from bulma using `bit 14.4.1`:

```
@import ~bulma/sass/utilities/_all.sass
@import ~bulma/sass/base/_all.sass
```

```
bit tag --all $version
error: issues found with the following component dependencies

devth.github/git-hub-org-cards@0.0.1
missing packages dependencies (use your package manager to make sure all p
ackage dependencies are installed):
     src/components/GitHubOrgCards/styles.sass -> ~bulma
```

And it's in my `package.json`.

**Comment by GiladShoham** [comment]
@devth Have you configured the custom module resolution?
If you did, can you copy your configuration here?

**Comment by devth** [comment]
Nope. Am I supposed to? This is my first time trying bit and I followed the [Bit for React tutorial](https://docs.bit.dev/docs/tutorials/bit-react-tutorial).
