### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by stjepangolemac** [teambit/bit#1042]
## Expected Behavior
`bit tag --all 1.0.0` to pass

## Actual Behavior
`Maximum call stack size exceeded`

## Steps to Reproduce the Problem

  1. clone https://github.com/stjepangolemac/bit-atomic-design
  1. `bit add` all components from `src/components/atoms|molecules|...` 
  1. `bit tag --all 1.0.0`

## Specifications

  - Bit version: 0.12.13
  - Node version: 8.9.3
  - npm / yarn version: 1.3.2 yarn
  - Platform: mac
  - Bit compiler (include version): how to get version?
  - Bit tester (include version): how to get version?

**Comment by GiladShoham** [comment]
Hi @stjepangolemac ,
Thanks for reporting this issue.
This issue is a result of big files (more than 10KB).
This issue is already fixed and merged to master and will be part of the next release.
You can check that it's working on the dev version by installing the dev version:
`npm i -g bit-bin@dev`
Keep in mind that this is still a dev version and not fully stable.

**Comment by stjepangolemac** [comment]
Thanks for the help 😊🍻

**Comment by stjepangolemac** [comment]
Unfortunately I have the same problem even with the dev version 🤔

**Comment by GiladShoham** [comment]
@stjepangolemac Thanks for report back, we will check this

**Comment by davidfirst** [comment]
Hi @stjepangolemac , 
I tried to reproduce the issue with the new code. Here is what I have done:
1. cloned the project.
2. `bit add src/components/atoms/**`
3. `bit tag --all 1.0.0`
I was able to tag with no issues.

output:

> ➜  bit-atomic-design git:(master) ✗ bit tag --all 1.0.0
> 15 components tagged | 15 added, 0 changed, 0 auto-tagged
> added components:  atoms/avatar-image@1.0.0, atoms/hamburger-icon@1.0.0, atoms/icon@1.0.0, atoms/label@1.0.0, atoms/panel@1.0.0, atoms/tool-image@1.0.0, molecules/action-icons@1.0.0, molecules/tool-link@1.0.0, molecules/user-info@1.0.0, organisms/map@1.0.0, organisms/temperature@1.0.0, organisms/tools@1.0.0, templates/header@1.0.0, templates/workspace@1.0.0, pages/home@1.0.0
> ➜  bit-atomic-design git:(master) ✗

Do you mind trying again after `npm i -g bit-bin@dev` and making sure `bit --version` shows `13.0.0-dev.10`.?

**Comment by itaymendel** [comment]
hi @stjepangolemac - i'm closing this issue. please comment here again if this error surfaces yet again, so i'll reopen it.

**Comment by iamhitarth** [comment]
Hi @itaymendel I am still getting this issue on v13.0.4 of Bit. Is that expected?
