### ISSUE TITLE
[Feature] Component checkout wildcards

### ISSUE THREAD

**Issue by mxmzb** [teambit/bit#1044]
## Expected Behavior

Would be great to have a shortcut for `bit checkout <version> <component_ids>`, which allows you to update all components to a specific version or even better to the latest available one per component. Maybe something like `bit checkout latest --all` ?

**Comment by itaymendel** [comment]
@mxmzb - what we plan is to implement an `update` command that will be more of a sugar syntax for combining `import` and `checkout`, and will support something similar to a `--all` flag. It will also include more features around updating using semver flags.

adding a `--all` flag to the `checkout` command will be available as a part of the same update (as Bit will need this API).

**Comment by itaymendel** [comment]
adding support for:

```sh
bit checkout [id] --reset
bit checkout --reset --all
bit checkout [version] [id] // this is already exists
bit checkout latest --all
```

@davidfirst @GiladShoham - please update this issue when on your progress

**Comment by itaymendel** [comment]
PR can be found here -
https://github.com/teambit/bit/pull/1086

**Comment by itaymendel** [comment]
released. closing this issue.
