### ISSUE TITLE
`first` returns null if the first item is falsy

### ISSUE THREAD

**Issue by guilhermehn** [teambit/bit#1069]
## Expected Behavior
`#first()` should return the first value of the array

## Actual Behavior
It returns `null` if `Boolean(value) === false`

## Steps to Reproduce the Problem

  1. pass an array with a falsy value in the first position

```js
console.log(first([false]))
console.log(first(['']))
console.log(first([0]))
```

## Specifications

  - Bit version: 13
  - Node version: 8.11
  - npm / yarn version: 5.6
  - Platform: Ubuntu
  - Bit compiler (include version): 
  - Bit tester (include version):

**Comment by itaymendel** [comment]
hi - the code for these components can be found here - https://github.com/teambit/bit.utils
currently our priortization is to release a new release of Bit, and will not attend to provide with a fix.
you can submit a pull request to the right repo, and i'll simply publish a new version for the component.

i'm closing this issue, as it is not relevant for this repo.

**Comment by guilhermehn** [comment]
Thanks for directing me to the right repo
