### ISSUE TITLE
Support Alias Resolution

### ISSUE THREAD

**Issue by gabaum10** [teambit/bit#1084]
## Expected Behavior
I have a complex dependency tree for the component I'm trying to export and have a root alias set to `@`.  That means, most of the dependent components have `@/utils/something` or `@/store/module` sprinkled throughout.  It's going to be extremely tedious to attempt to convert all those to their absolute paths for bit to parse the tree.  

Perhaps it would be possible to introduce a root alias option for the bit configuration or something?  As it stands now, this could potentially be a non-starter.

## Actual Behavior
Bit is forcing all the aliased imports to be converted to their absolute paths.  For example:
```
missing packages dependencies (use your package manager to make sure all package dependencies are installed):
    src/store/auth/auth-actions.js -> @/api
```

Converting the `@/api` to `./src/api` fixes the problem.

## Steps to Reproduce the Problem

  1. Have a component that references another dep via an alias
  1. Attempt to run a `bit add` on the component

## Specifications

  - Bit version: latest - I just installed it for the first time.
  - Node version: v9.11.1
  - npm / yarn version: yarn 1.7.0
  - Platform: Ubuntu 18.04
  - Bit compiler (include version): latest
  - Bit tester (include version): latest

**Comment by itaymendel** [comment]
Hi, please refer to this docs, it describes how to configure aliases in bit:
https://docs.bitsrc.io/docs/troubleshooting-isolating.html

**Comment by gabaum10** [comment]
Huh. Must have missed that.  Thanks!

**Comment by itaymendel** [comment]
No problem ;) we’ll add better error handling in ‘bit status’ to link to this page, so more devs will be aware of it.

It’s a brand new feature :)

**Comment by cristinallamas** [comment]
Is there a way to add a different alias from '@' let's say 'Atoms' 

`        
"Atoms": "src/components/atoms",
`
to then be able to do 

`
import { Heading, Image, Text } from 'Atoms';
`
