### ISSUE TITLE
After upgrade to 13.0.0, components are not build in bitsrc.io

### ISSUE THREAD

**Issue by rigobauer** [teambit/bit#1089]
## Expected Behavior
After exporting a component to my bitsrc.io scope, it should start a build process and show if it completes it or not.

## Actual Behavior
After upgrade to 13.0.0, the build process is not started. In my  bitsrc.io scope it shows a warning "Note: your component has no build task defined!", but I've imported the react compiler environment and I can build the component locally. I've tried with reset, reset-hard to start again, but same result.

Everything was working great before the upgrade, so I assume I'm missing some new step or there's some kind of problem.

## Steps to Reproduce the Problem

  1. Make some change to the component
  2. Build it, tag it and export it.
  3. Go to my bitsrc.io scope, and the new version is there, but no build process is started.

## Specifications

  - Bit version: 13.0.0
  - Node version: 8.11.1
  - npm / yarn version: 1.6.0 (yarn)
  - Platform: Mac
  - Bit compiler (include version): bit.envs/compilers/react@0.0.13
  - Bit tester (include version): Still not using tests

**Comment by GiladShoham** [comment]
Thanks for reporting this. I'll check it and update you ASAP.

**Comment by GiladShoham** [comment]
@rigobauer Thanks for this.
The issue has been fixed, and we re-run the CI on your scope.
I'm closing the issue. If you still see this issue, please re-open it.

**Comment by rigobauer** [comment]
Great!! Thanks a lot!
