### ISSUE TITLE
bit configuration when behind proxy

### ISSUE THREAD

**Issue by anasameur** [teambit/bit#1092]
## Expected Behavior
im trying to import and set a new environment compiler 
bit import bit.envs/bundlers/vue -c

## Actual Behavior
the request fail with a connect ETIMEDOUT 

## Specifications

  - Bit version: 13.0.0
  - Node version: 8.10.0
  - npm / yarn version: 5.6.0
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
Currently Bit does not have a specific support for it. However, it uses the openssh client found on most *nix systems (and also putty, for windows), so setting up a proxy config in the ~/.ssh/comfig should work. Having said that, I would want to validate it first before saying it can be done.

Additionally, some features (like the ‘bit login’ command, or the anonymous usage analytics) require HTTP/S communication. To enable these features, we would need to implement support for configuring HTTP_PROXY and HTTPS_PROXY variables.

If we go through this process, I think that it’s critical to see if we can support SSH over HTTPS port as well, for proxies that block SSH port.

I will post my findings in the nex couple of days.

**Comment by bflemi3** [comment]
@itaymendel We're you able to verify that the proxy config in `.ssh/config` does indeed work?

**Comment by simgot** [comment]
Same issue behind corporate firewall

**Comment by itaymendel** [comment]
**Update**

We're checking about supporting SSH over port 443, this might help when using Bit behind a corporate firewall.

**Comment by epiccinini-dev** [comment]
Please could you share us how to configure bit in order read ~/.ssh/config file? 
Maybe we've to use https://docs.bit.dev/docs/overrides? Please could you share an example?

Only through this configuration we're able to have ssh tunneling into http request.

Host *.bit.dev
  ProxyCommand connect -H http://proxyIP:proxyPort %h 443

**Comment by aksole** [comment]
Hi. We're also looking into using Bit.dev behind a company proxy. Have you had any progress on this issue?

**Comment by itaymendel** [comment]
We're moving Bit to HTTP/S, so proxy config should be easier to support.

**Comment by nicdford** [comment]
Any new updates on this issue? :)

**Comment by itaymendel** [comment]
supported in v15

`bit config set http_proxy`

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
