### ISSUE TITLE
version latest was not found

### ISSUE THREAD

**Issue by hxuanhung** [teambit/bit#1105]
## Expected Behavior
Can tag the newly added component

## Actual Behavior
Get error `version latest was not found`

## Steps to Reproduce the Problem

  1. I have a file with its content:
```
import { keyframes } from 'styled-components';

const animation = keyframes`
  0%   { opacity: 0; transform: translateY(10px); }
  100% { opacity: 1; transform: translateY(0px); }
`;

const reverseAnimation = keyframes`
  0%   { opacity: 0; transform: translateY(0px); }
  100% { opacity: 1; transform: translateY(10px); }
`;

export const delayEffect = (delay: number = 0, reverse: boolean = true) =>
  `
    animation: ${reverse ? reverseAnimation : animation} 0.3s;
    animation-delay: ${delay}s;
    animation-fill-mode: forwards;
    opacity: 0;
  `;
```
  2. I try to add this file and get notified that it's added successfully.
  3. I try to tag it and get the error.

## Specifications

  - Bit version: 13.0.0
  - Node version: 10.2.1
  - npm / yarn version: 5.6.0
  - Platform: macOS
  - Bit compiler (include version): react-typescript@0.0.5
  - Bit tester (include version):

**Comment by itaymendel** [comment]
what is the output of the `bit status` command, right after adding that component?

**Comment by hxuanhung** [comment]
I updated Bit to `13.0.1` and it works.

**Comment by itaymendel** [comment]
awesome :)
closing the issue
