### ISSUE TITLE
unable to save Version object

### ISSUE THREAD

**Issue by sarawinter** [teambit/bit#1112]
I am getting the following error when trying to run `bit tag --all`
```
unable to save Version object the following files are duplicated src/Components/Search/InputSearch.js, src/components/search/inputsearch.js
This error should have never happened. Please open a new Github issue with the bug details
```

## Specifications

  - Bit version: 13.0.1
  - Node version: ???
  - npm / yarn version:  npm '5.6.0'
  - Platform: Windows 10
  - Bit compiler (include version): Visual Code
  - Bit tester (include version): ???

**Comment by GiladShoham** [comment]
Hi @sarawinter ,
I saw in the error above you have 2 files with a different case.
Do these 2 paths exist in the file system?
Or maybe you renamed from one to another and then run bit add again with the new case?
Can you send me your .bitmap file (should be in the root of your workspace)
(here or privately to gilad@bitsrc.io).

**Comment by sarawinter** [comment]
I think I renamed it or managed to add it twice to bit under the same id but with different caps.
These are the contents of my .bitmap: 

/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "services/search-engine@0.0.4": {
        "files": [
            {
                "relativePath": "src/Services/SearchEngine.js",
                "test": false,
                "name": "SearchEngine.js"
            }
        ],
        "mainFile": "src/Services/SearchEngine.js",
        "origin": "AUTHORED"
    },
    "services/categorymanagement@0.0.2": {
        "files": [
            {
                "relativePath": "src/services/categorymanagement.js",
                "test": false,
                "name": "categorymanagement.js"
            }
        ],
        "mainFile": "src/services/categorymanagement.js",
        "origin": "AUTHORED"
    },
    "templates/gridpageview@0.0.1": {
        "files": [
            {
                "relativePath": "src/Components/Templates/GridPageView.js",
                "test": false,
                "name": "GridPageView.js"
            }
        ],
        "mainFile": "src/Components/Templates/GridPageView.js",
        "origin": "AUTHORED"
    },
    "ui/inputsearch@0.0.2": {
        "files": [
            {
                "relativePath": "src/Components/Search/InputSearch.js",
                "test": false,
                "name": "InputSearch.js"
            },
            {
                "relativePath": "src/components/search/inputsearch.js",
                "test": false,
                "name": "inputsearch.js"
            }
        ],
        "mainFile": "src/Components/Search/InputSearch.js",
        "origin": "AUTHORED"
    },
    "ui/searchresults@0.0.2": {
        "files": [
            {
                "relativePath": "src/Components/Search/SearchResults.js",
                "test": false,
                "name": "SearchResults.js"
            }
        ],
        "mainFile": "src/Components/Search/SearchResults.js",
        "origin": "AUTHORED"
    },
    "version": "13.0.1"
}

**Comment by sarawinter** [comment]
Okay, so I used `bit untrack --all` to get rid of all of the files. Had a lot of problems trying to remove files, both locally and remotely, but I finally managed to do it. When I had removed, untracked, ect. (I don't remember all of the steps I went through) I had to add all of the files again. It worked, but it was a bit arduous.

**Comment by davidfirst** [comment]
@sarawinter in the version v13.0.0 we added a mechanism to prevent adding files with the same names and different cases, so I'm curious how it happened. 
By any chance, you added the files using an older version? maybe v0.12.x?

Also, in this case, I believe that `bit untrack ui/inputsearch` should have done the job, because it's the only invalid component.

**Comment by sarawinter** [comment]
Yes, it is possible that I added it with a previous version. I know that I was prompted at some point to update to a newer version, but I don't know what version I had before this.

**Comment by davidfirst** [comment]
OK, thanks for the update.
I'm closing the issue as it is fixed in the last version.
