### ISSUE TITLE
Additional render platforms support 

### ISSUE THREAD

**Issue by NZX-DeSiGN** [teambit/bit#1116]
Hi,

I just want to know if additional platforms support to render components in bitsrc.io overview is soon expected ?
I've developed many VueJS components and want to share it, but the overview is an essential feature for me !

Thank you

**Comment by itaymendel** [comment]
We're doing major refactoring to the infrastructure of the rendering feature. Once done, it will allow us to support more renderers.

The work on the infra is due until the end of the month. Afterward, we'll be able to prioritize additional renderers.

**Comment by NZX-DeSiGN** [comment]
Awesome, thank you for the information!
I think with the rendering feature is your killer feature to become the interface components Github!
I'll keep an eye on your project and wish you good luck to become essential for front-end developers!

P.S: Where can I suggest you some ideas and not spam you with new issues? (may be a dedicated issue?)

**Comment by itaymendel** [comment]
Rendering is an important discoverability feature. It beats documentation every day of the week!

I think that a single GitHub issue will be best!
We’re working to open a dedicated discourse/spectrum community for Bit which will be a better platform. But until then- let’s keep suggestions here ;)
