### ISSUE TITLE
Warning: React.createElement: type is invalid -- expected a string

### ISSUE THREAD

**Issue by hxuanhung** [teambit/bit#1119]
## Expected Behavior
working with no warning

## Actual Behavior
I get this warning:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

## Steps to Reproduce the Problem

  1. Import this component: https://bitsrc.io/hung-ww/ww-react-ui/components/routing
  2. Run app.
 

## Specifications

  - Bit version: 13.0.1
  - Node version: 10.2.1
  - npm / yarn version: 5.6.0/1.3.2
  - Platform: macOS
  - Bit compiler (include version): "bit.envs/compilers/react-typescript@0.0.5"
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@hxuanhung 
Thanks for reporting this, we will check this and update you.

**Comment by davidfirst** [comment]
@hxuanhung , can you please provide the app to run and also the instructions how to compile it. Thanks.
