### ISSUE TITLE
Getting error "modelComponent.getVersionToAdd is not a function" when trying to tag --all

### ISSUE THREAD

**Issue by sarawinter** [teambit/bit#1121]
I am trying to update a component. I did the following:

1. bit add src/components/mycomponent.js --id ui/mycomponent
2. bit tag --all
3. bit export mynamespace.scope --eject

So far, so good. 
My component got uploaded to bitsrc as it should, but I did get an error message about `--eject` not working because of something (I'm sorry I did not save that error, but as I remember it had something to do with .find???). However, I thought that the error was because I had not used `import` since it was a component I just created. I did not think much more about it, until...

I made some edits in the file and then it was time to upload it again. 

1. bit status ----> showed that everything was ok
2. bit tag --all -----> "modelComponent.getVersionToAdd is not a function" :(

What might I have done wrong?

<img width="262" alt="capture" src="https://user-images.githubusercontent.com/19814400/42377696-a45cb456-8124-11e8-9f47-e8fcd2e6ec5b.PNG">

## Specifications

  - Bit version: 13.0.1
  - Node version:
  - npm / yarn version: npm '5.6.0'
  - Platform: Windows 10
  - Bit compiler (include version): Visual Code
  - Bit tester (include version):

**Comment by sarawinter** [comment]
Okay, thanks for the quick response :)

I had to use `--force` to be able to remove it.
After that making a backup, importing and exporting etc. worked just fine.

**Comment by davidfirst** [comment]
Thanks for the update :)

I wasn't able to reproduce the issue myself, so I can't offer a better error message. I guess, if it happens again, I'll ask for the log to have a better picture of what happened.
Closing for now.
