### ISSUE TITLE
Q: Using compilers for a single component?

### ISSUE THREAD

**Issue by boschr** [teambit/bit#1134]
First of all, sorry for "abusing" GitHub issues for my question(s). But I understand that there is no other place for now (but in a few days there is).

I'm relative new to Bit so i'm struggeling and learning. For me it's not clear how to use the compilers.

My situaties at the moment: I'm using Bit to share small (~1 file) components / snippets of JS or SCSS code between projects. In case of JS snippets it is essential to compile ES6 back to ES2015.

Is it possible to add an compiler (Babel in my case) to an individual component? And how? Or should I add a compiler to a scope?

**Comment by GiladShoham** [comment]
Hi @boschr 

I'll try to explain a little bit about defining a compiler.

A compiler is defined per workspace. This means that when you import a compiler into your workspace, each component created in that workspace will have the same compiler configured.
Imported components, however, are not attached to this compiler. They have their compiler, configured in their bit.json. This means that by default it is not possible to track different components from the same source project and use different compilers for them.  

To achieve what you want, I suggest the following workaround:

Basically what you want is to import the components with the different compiler to the source project, as imported components will override the settings set in the workspace.
You can create the components which need the Babel compiler in a different, temporary, workspace (that uses the babel compiler). Tag and export and import them into your project.

I am aware that this is not a good UX for such flow. This is why I'm currently working on allowing attach/detach component's configuration, thus enabling editing them (so for example - you will be able to set a specific compiler from a component's source project)

Note - all written here is valid for testers, not only for compilers.

**Comment by boschr** [comment]
@GiladShoham Thnx for your reply!

With workspace i guess you mean a "scope"? Maybe (probably) i misusing the whole scope idea.

What i'm doing now is:
1. Folder: `reusable-frontend`, it is not a project, but just a folder with a couple of snippets. This is the folder where i did the `bit init` and here i'm managing my components/snippets (modify, tag, export).
2. `project-a`, this is an existing project where i want to use these snippets. This is not a "bit project". I just installed the components using `yarn add @bit/...`

Maybe its a better solution to create two scopes in subfolders of the `reusable-frontend` folder for `js` and `scss`? Or do I have to adjust `project-a` to a "bit project" (executing `bit init`) and manage component from there? Or ..?

**Comment by GiladShoham** [comment]
Hi @boschr ,

Let's start by explaining the two concepts; Scope and Workspace.

**Workspace** is the working directory tree of your project. It is the directory in which you run `bit init`. It contains a `bit.json`, `.bitmap` file and a `.bit` directory.
The `.bit` directory is the local **Scope**. It contains all the objects Bit needs to operate.
Read more about it here:
https://docs.bitsrc.io/docs/faq-bit-basics.html#what-is-a-bit-scope
https://docs.bitsrc.io/docs/initializing-bit.html#the-contents-of-a-workspace-with-a-bit-scope

Now, back to your question - If you use different compilers for different components, I would recommend creating two subfolders as you suggested, and run `bit init` inside each one of them
(You don't need to run `bit init` outside folder).

As for the project that uses the components - you don't have to run `bit init` inside of it at all. Keep using npm/yarn to install the components.

One of the main advantages of Bit is the ability to modify a component from any project. A popular workflow will be to run `bit init` inside your project and install the components using npm. Once you need to do a modification to a component, you can use `bit import` (inside the project) to source the code of the component (bit will make sure your code will still work without the need to edit your require statements). Change the component, then tag and export with the `--eject` [flag](https://docs.bitsrc.io/tutorial/react-tutorial.html#export-component-new-version). This will remove the source code of the component, and replace it with the npm package.

With this flow, there's no need to move between projects every time, and you don't need to try to reproduce your bug in a different project which doesn't have the original context.
