### ISSUE TITLE
Two running instances of a dependency

### ISSUE THREAD

**Issue by fplgusmao** [teambit/bit#1150]
## Expected Behavior
Resolve duplicate dependencies in imported components to point to original/root dependencies

## Actual Behavior
The project ends up using a depency from the component's `node_modules` and a duplicate from the project's `node_modules`, leading to two running instances of the library

## Further description
I have a `create-react-app` project that uses [`styled-components`](https://www.styled-components.com/) and a group of components that depend on that library too. I've **imported** one of those component to this project and the library has been giving out this warning that several instances are initialized ([library's troubleshooting page](https://s-c.sh/2BAXzed)). Maybe this happened with many other libraries before, but with this one it is causing crucial problems regarding the CSS of the page, and honestly if this problem is not solvable I don't think I will be able to use Bit, since I really need to use `styled-components`. **I had the impression from the docs, however,** that bit solved this dependency issues when doing `bit install` right? Am I missing some step on the whole importing process?

## Steps to Reproduce the Problem

  1. Make a create-react-app with components that use [`styled-components`](https://www.styled-components.com/)
  2. Import a component that uses `styled-components` 
  3. Check the warning in the console saying:
```
It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.

See [https://s-c.sh/2BAXzed](https://s-c.sh/2BAXzed) for more info.
```
 4. Notice how either the imported component or the locally created styled-component don't have the due css

## Specifications

  - Bit version: 13.0.0
  - Node version: 8.0.0
  - npm / yarn version: yarn 0.19.1
  - Platform: MacOS
  - Bit compiler (include version): (not sure how I see this one)
  - Bit tester (include version): (not sure how I see this one)

## Update

I ran the "steps to reproduce" and I can confirm that you can witness the problem by just having an empty project with , thus proving that the cause of the issue is indeed what I had suspected. I think that the conclusion is that there must be a better dependency resolution to avoid these kind of problems

**Comment by fplgusmao** [comment]
Thank you! I'll probably go to solution 1 or 2, I'll let you know if it worked when I have the time to implement it

**Comment by itaymendel** [comment]
i'm closing this issue as it's getting stale. please reopen if any of the suggested workaround failed.
