### ISSUE TITLE
Issue with bit add when a component is requiring package.json

### ISSUE THREAD

**Issue by hpadrick** [teambit/bit#1153]
## Expected Behavior
`bit add backend/api` tracks all files without issues.

## Actual Behavior
`bit add backend/api` contains a module that requires package.json. This results in the following `bit status`

```
     > backend/api ...  issues found
       untracked file dependencies (use "bit add <file>" to track untracked files as components):
          backend/api/server/plugins/pkg.js -> backend/api/package.json
```

Trying to add the package.json file results in the following:

```
▶ bit add backend/api/package.json --id backend/api
warning: no files to add, the following files were ignored: backend/api/package.json
```

## Steps to Reproduce the Problem

  1. Create a component with an index.js that requires package.json
  1. Try to `bit add` the component
  1. View `bit status`

## Specifications

  - Bit version: 13.0.4
  - Node version: v8.11.2
  - npm / yarn version: npm v6.2.0
  - Platform: OSX
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@hpadrick Thanks for your comment.
We are aware of this issue and are working to solve it.
The reason Bit is ignoring “package.json” is because Bit also generated a package.json for the component, and tracking an additional package.json by the user will yield conflicts.
We are currently working on resolving this issue.
I’m keeping this issue open and will post an update as soon as we have one.

**Comment by engineforce** [comment]
The ability for bit to track the original package.json will be very useful, it will fix another issue I am currently having:

```json
// Original package.json
{
  "name": "@engineforce/file-lib",
  "version": "0.0.3",
  "description": "File library",
  "main": "./dist/index.js",
  "scripts": {
    "build": "tsc && poi build",
    "test": "jest"
  },
  "devDependencies": {
    "jest": "^23.5.0"
  },
  "dependencies": {
    "glob": "^7.1.2"
  }
}

// Generated package.json from bit import
{
  "name": "@bit/engineforce.demo.packages.file-lib",
  "version": "1.0.0",
  "homepage": "https://bitsrc.io/engineforce/demo/packages/file-lib",
  "main": "index.js",
  "dependencies": {
    "glob": "7.1.3"
  },
  "devDependencies": {},
  "peerDependencies": {},
  "license": "SEE LICENSE IN LICENSE"
}
```

Notice the "main" property is pointing to the wrong index.js (which is not transpiled).

**Comment by GiladShoham** [comment]
@engineforce we are working on this right now. it will merged to master in a few days. regarding your issue, it won't solve your issue. the correct way to solve your issue is to import a bit compiler and use it to compile your component's source code.

**Comment by engineforce** [comment]
One of major advantage of using lerna is the ability to use different build tools and test tools for different packages. E.g., I can use poi.js for one package, and use parcel.js for another package. One package may use typescript, another  package may use just babel.
Do you have a plan to support this type of monorepo?

**Comment by GiladShoham** [comment]
last comment moved to #1221 the discuession regarding lerna will continue there

**Comment by GiladShoham** [comment]
PR which add support to track package.json is work in progress.
Follow this PR:
https://github.com/teambit/bit/pull/1224

**Comment by itaymendel** [comment]
merged and released.
please try the flow again :)

**Comment by pgYou** [comment]
How should the package.josn file be tracked now? Didn't find anything about this in the docs @GiladShoham

**Comment by GiladShoham** [comment]
@pgYou can you please move the discussion into a new issue?
This one is closed few years ago.
Keeping the discussion here will lead to people miss it.
You can refer to that original issue in the new one.
Thanks
