### ISSUE TITLE
New compilers/testers environments 

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1156]
This issue tracks the required changes in bit in order to support the new set of environments. Contributors/Community are more then welcome to comment. 
 
## Background
Bit uses a special group of extensions in order to test and compile components. Our current set of extensions is developed in [teambit/bit.envs](https://github.com/teambit/bit.envs) and they have provided a vital service. The issue with current toolset is that its configuration is hard coded. This encourages users of Bit to fork the compilers and make very small changes which leads to code duplication. We are in the process to create abstract extensions which will be able to support (hopefully) many if not most use cases. While the main bulk of the work is being done in    [teambit/bit-envs](https://github.com/teambit/bit-envs), this ticket will track extension API changes required in bit. 
 
## What is needed
1.  Every extension API call should get a `context` object with componentDir/workspaceDir. (#1154)
2. API object should have a function `getComponentPackageJson`
3. Consider having an API call to perform relative require. The require function should be called within a file in the componentDir. This is to "hit" the component node_modules first and not the extension. Current implementation assumes bit will ignore `.bitTmp`  folder. This folder will be created in the component directory dynamically and will contain code which will require modules from the component node_modules. Implementing this in bit will also assist in case the extension throws an exception and fails to cleanup after itself. Even without the api `bit status`, `bit diff` etc should ignore changes in this folder.
4. Bit should deduce the explicit (`require`/`import` calls) dependencies from its JS based configuration files.

I will update this issue from time to time until completion.

**Comment by qballer** [comment]
Compiler/Tester init api call will return an Options object which looks as following:
```javascript
{
  write:boolean
}
```
This means that the env needs access to the filesystem of the component.

**Comment by qballer** [comment]
Right now testers will return flatten results, this needs to change in order to support hierarchy of results.  For that Bit needs to changes it's raw expected result.   Relates to https://github.com/teambit/bit-envs/issues/10

**Comment by qballer** [comment]
Still considering it, but for typescript support we will need the original(author) or the component (both?) `package.json` in the `getDynamicPackageDependencies` API to understand the types.

**Comment by qballer** [comment]
1. there is no support to adding files to the component that shouldn't be compiled. This can be supported in bit or that env developers  should copy the file to the right now location. 

2. For typescript support we will need custom dependencies resolution to resolve custom types.

**Comment by qballer** [comment]
Consider adding the extension API the following function 
```typescript
getDefaultConfiguration(): Object;
```
this function should return a default configuration for the compiler entry in bit JSON to populate.  This will allow easy on boarding for envs and save user time.

cc: @GiladShoham

**Comment by PatrickGeyer** [comment]
Hi @qballer, 
Could you update us on progress?
I'm in dire need of outputting definition files so that I can share typescript modules across my projects.
Thanks!

**Comment by GiladShoham** [comment]
This issue refers to a suggested new API for the compilers / testers.
We have extended the scope of the compiler / testers API to a full extensions API.
It will be handled under a new issue.
Closing this, it's not relevant anymore.
