### ISSUE TITLE
Allow dependency ignorance via --git-only command

### ISSUE THREAD

**Issue by notadamking** [teambit/bit#1166]
## Requested feature

The ability to use Bit without the dependency management system. For example, a --git-only option could be added to the import/export commands that ignores the dependencies entirely and only worries about merge conflicts, versioning, etc. This would allow for much faster Bit commands.

## Motivation

We have relatively large components. For speed of development, we've found it makes more sense for us to use a few larger component libraries, rather than many small components. The problem is this comes at a major cost to import/export speed. A typical export takes upwards of 90 seconds and a typical import/checkout can take over 5 minutes if a few libraries have been updated. I've been told this is due to the IO constraints of the dependency management portion of Bit.

We would rather sacrifice dependency management than development speed at this point (obviously sacrificing neither would be ideal), but that is currently not an option. We've currently resorted to going back to git subtrees to manage our shared libraries, but we're missing the solidity of Bit. 

In an ideal world, the --git-only command would allow for *temporary* dependency ignorance. For example, if I export/import with the --git-only command once, it doesn't forever lock me into dependency ignorance. I should be able to run export/import without the --git-only command every so often and get all the wonderful dependency management features. Although, I'm not sure if this would even be possible.

**Comment by janosh** [comment]
I think this is a great suggestion! And as @itaymendel mentioned in #1179, it might not be hard to implement.

**Comment by constantin-v** [comment]
This feature could be really nice, and not only to improve the speed of the import / export.

I have a use case where I need to share a component between multiple projects. 
My projects have the same structure but they are implementing X, Y and Z files differently.
The component I want to share has a dependency on X, Y and Z files but as they are implemented differently on my projects, I don't want to share those files with my component.

So importing my component without dependencies could solve this use case.

**Comment by janosh** [comment]
@constantin-v That's exactly the situation I have.

**Comment by KrzysztofGastolek** [comment]
+1. What I would like is to use bit components like simple txt files. Just check content and version without context (imports, dependancies etc.).

**Comment by davidfirst** [comment]
@notadamking , @janosh , @constantin-v , with the newly released version v14.1.0, it's now possible to manually ignore dependencies per components. It's also possible to use wildcards for all components or some of them.
Read here for more details:
https://docs.bit.dev/docs/component-dependencies.html#override-dependencies-in-workspace-configuration

Please let me know if you have any question or if it doesn't address your use-case.

**Comment by itaymendel** [comment]
Sorry, but we have decided to make Bit more focused on reusing of isolated and usable (node) modules. Support for a 'git submodule' like workflow and exposing such features diverge Bit form its goal and reduce the team's focus.

I'm closing the issue.
