### ISSUE TITLE
[Feature request] Support for `babel-plugin-root-import`

### ISSUE THREAD

**Issue by xurei** [teambit/bit#1168]
I'm using `babel-plugin-root-import` so I can import my file dependencies like this :
```javascript
import { Component } from '/path/to/my/component';
```
Where component.js is located in `src/path/to/my/component`

It's basically the same as an alias in webpack resolve configuration.
However, bit does no seem able to handle that (or I didn't find how).

## Expected Behavior
Handle absolute path as it does with `resolveModules`

## Actual Behavior
Does handle it.

## Steps to Reproduce the Problem
1. .babelrc : 
```json
{
    "plugins": [
        [
            "babel-plugin-root-import",
            {
                "rootPathSuffix": "src",
                "rootPathPrefix": "/"
            }
        ]
    ]
}
```
1. `bit add src/components/*`
1. `bit tag -a`

## Specifications
  - Bit version: 13.0.4
  - Node version: 8.11.3
  - npm / yarn version: 5.6.0
  - Platform: Linux
  - Bit compiler (include version): bit.envs/compilers/react@0.0.14
  - Bit tester (include version): bit.envs/testers/mocha@0.0.12

**Comment by itaymendel** [comment]
Hi @xurei , I think that configuring Bit's Custom Module Resolution will do the trick.

You'll need to configure the aliases and paths in your project's `bit.json` file, as shown [here](https://docs.bitsrc.io/docs/troubleshooting-isolating.html#configuring-custom-module-resolution).

Let me know if the issue still persists. In the meanwhile, I'm closing this issue.

Cheers

**Comment by xurei** [comment]
Hi @itaymendel. Thanks for replying so quickly.

I tried that indeed, but it's not working. Here is the config I tried : 
```json
{
    "resolveModules": {
        "aliases": {
            "/": "src"
        }
    }
}
```

**Comment by itaymendel** [comment]
reopen the issue, I'll try and recreate it locally and see what's going on.

**Comment by itaymendel** [comment]
irrelevant. we're moving away from supporting other `resolveModules` configs for Bit and instead use Bit's module ID for imports.
