### ISSUE TITLE
Can't login: If I specify --suppress-browser-launch bit should ask for the token instead of redirect

### ISSUE THREAD

**Issue by alesanchezr** [teambit/bit#1173]
## Expected Behavior
When doing:
```
$ bit login --suppress-browser-launch
```
bit should behave exactly like the google's
```
$ gcloud auth login --no-launch-browser
```
If I sepecify that flag bitsrc, should show me the login token on the screen for me to copy and paste it on the command line. 

I need that because can't use localhost as my development domain.

## Actual Behavior
Right now bit tries to redirect me to http://127.0.0.1:8085/

## Steps to Reproduce the Problem

1. $ bit login --suppress-browser-launch
2. Login if needed.
3. bit will try to redirect.

## Specifications

  - Bit version: 13.0.3
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
I'll check the gcloud flow and see what's possible for us to implement, and if it can complicate our flow.

To workaround this issue what I suggest one of the following:

1. Run `bit login` from your local machine, where the redirect will not cause a problem, and after a successful login, run `bit config`, and copy the `user.token`. Afterward use `bit config set user.config <key>` on the dev machine, to authenticate Bit.
2. Generate an SSH Key pair and use to authenticate the dev machine with your bitsrc.io account. There's a [short writeup](https://docs.bitsrc.io/docs/setup-authentication.html#authenticating-bit-using-ssh-key-pair) in the docs about it.

Note - on both cases, you will need to authenticate your npm/yarn client and configure it to use `@bit` as a node registry (`bit login` does it automatically). This is configured in the `.npmrc` file. It can be modified manually or via the `npm login` command. You can read a bit about it [here](https://docs.bitsrc.io/docs/install-components.html#npm-or-yarn-throws-package-not-found-when-importing-a-component).

**Comment by alesanchezr** [comment]
Ok thanks, the workaround worked using ssh.
