### ISSUE TITLE
Remove original files after export

### ISSUE THREAD

**Issue by ThomasKientz** [teambit/bit#1175]
Hi, 

I am a new user of Bit, and I am already addicted to it. But I am not sure to fully grasp the workflow.

I have 2 projects with some exact same components. So I init bit. And start to export components :

1- `bit add ...`
2- `bit tag ...`
3- `bit export ...`

Then I want to get rid of my local files and use my new node packages in both projects : 

4- manually delete the original file just exported 
5- re-import the component with `npm i @bit/...`

Finally I checked the bit status : 

6- bit status

But i got the error :
> component files were deleted (use "bit remove [component_id]" to remove the component from your workspace)

**Comment by qballer** [comment]
I recommend against removing the component from the original author environment.  Right now it's easier to maintain the component from it.  Still this can be done with `bit export --eject`

```bash 
$> bit export --help

  Usage: export|e [options] <remote> [id...]

  export components to a remote scope.
  https://docs.bitsrc.io/docs/organizing-components-in-scopes.html

  Options:

    -f, --forget   do not save to bit.json after export
    -e, --eject    once the export is done, remove the exported components locally and install them by the NPM client
    --skip-update  Skips auto updates
    -h, --help     output usage information
```

**Comment by qballer** [comment]
@ThomasKientz  let me know if this solves the issue for you.

**Comment by ThomasKientz** [comment]
@qballer Thanks !

In my case, it doesn't make sens to maintain the component from the original author environment, that's why I am trying to remove it.

Right now we can't eject a file with no change : https://github.com/teambit/bit/issues/1065

**Comment by qballer** [comment]
Touch commit for the win. add an enter/space somewhere which make sense to you.

**Comment by ThomasKientz** [comment]
Same issue.

I edited the component as you mentioned.
I tagged it.
I exported it with `--eject`.
I removed it from my local files.

Still got the error. 

Console logs :
```
pc41:vc thomas$ bit status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > components/mission-infos ... ok
pc41:vc thomas$ bit tag --all
⠄⠀ persisting...(node:38886) [DEP0079] DeprecationWarning: Custom inspection function on Objects via .inspect() is deprecated
1 components tagged | 0 added, 1 changed, 0 auto-tagged
changed components:  thomaskientz.vc/components/mission-infos@1.0.2
pc41:vc thomas$ bit export thomaskientz.vc --eject
added 1 package and audited 9641 packages in 11.468s
found 4 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
successfully ran npm install at /Users/thomas/Documents/Dev/jc/vc 
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.

exported 1 components to scope thomaskientz.vc
pc41:vc thomas$ bit status
your workspace has outdated objects. please use "bit import" to pull the latest objects from the remote scope.

pc41:vc thomas$ bit import
successfully imported 6 components
- up to date thomaskientz.vc/plugins/utils  
- up to date thomaskientz.vc/plugins/rules  
- up to date thomaskientz.vc/components/mission-planning  
- up to date thomaskientz.vc/components/mission-contract  
- up to date thomaskientz.vc/components/mission-postulant  
- added thomaskientz.vc/components/mission-infos new versions: 1.0.0, 1.0.1, 1.0.2, currently used version 1.0.2 

warning - add the following packages to package.json
> vuex: 3.0.1

pc41:vc thomas$ bit status
invalid components
these components were failed to load.

     > thomaskientz.vc/components/mission-infos@1.0.2 ... component files were deleted (use "bit remove [component_id]" to remove the component from your workspace)
```

**Comment by qballer** [comment]
Were the files there when you started this? I'm asking because you deleted them earlier.

**Comment by qballer** [comment]
I've ran through the process with a silly example.  I'm not sure what is the state of your workspace right now.  Can you attach `bit.json`  and `.bitmap` ?

**Comment by ThomasKientz** [comment]
> Were the files there when you started this? I'm asking because you deleted them earlier.

Yes, I put them back. Status was ok. Then I start again with a new component.

.bitmap
```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "thomaskientz.vc/plugins/utils@1.0.0": {
        "files": [
            {
                "relativePath": "plugins/utils.js",
                "test": false,
                "name": "utils.js"
            }
        ],
        "mainFile": "plugins/utils.js",
        "origin": "AUTHORED"
    },
    "thomaskientz.vc/plugins/rules@1.0.0": {
        "files": [
            {
                "relativePath": "plugins/rules.js",
                "test": false,
                "name": "rules.js"
            }
        ],
        "mainFile": "plugins/rules.js",
        "origin": "AUTHORED"
    },
    "thomaskientz.vc/components/mission-planning@1.0.0": {
        "files": [
            {
                "relativePath": "components/mission-planning.vue",
                "test": false,
                "name": "mission-planning.vue"
            }
        ],
        "mainFile": "components/mission-planning.vue",
        "origin": "AUTHORED"
    },
    "thomaskientz.vc/components/mission-contract@1.0.1": {
        "files": [
            {
                "name": "mission-contract.vue",
                "relativePath": "components/mission-contract.vue",
                "test": false
            }
        ],
        "mainFile": "components/mission-contract.vue",
        "origin": "AUTHORED",
        "dependencies": [
            "thomaskientz.vc/plugins/rules@1.0.0"
        ]
    },
    "thomaskientz.vc/components/mission-postulant@1.0.0": {
        "files": [
            {
                "relativePath": "components/mission-postulant.vue",
                "test": false,
                "name": "mission-postulant.vue"
            }
        ],
        "mainFile": "components/mission-postulant.vue",
        "origin": "AUTHORED"
    },
    "thomaskientz.vc/components/mission-infos@1.0.2": {
        "files": [
            {
                "name": "mission-infos.vue",
                "relativePath": "components/mission-infos.vue",
                "test": false
            }
        ],
        "mainFile": "components/mission-infos.vue",
        "origin": "AUTHORED"
    },
    "version": "13.0.4"
}
```
bit.json
```
{
    "env": {},
    "dependencies": {},
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "npm"
}
```

Thanks for your support.

**Comment by qballer** [comment]
Ok. So I think that what happened is that the local objects which describe the component are still there. I would follow the bit cli suggestion and try and run `bit remove components/mission-infos` assuming this is the right component making the issues. 

Please make sure the component is lost so no code will be lost.

**Comment by qballer** [comment]
@ThomasKientz let me know if the issue wasn't resolved. Closing for now.

**Comment by ThomasKientz** [comment]
@qballer Thanks, but it doesn't seem to work as I don't want to remove it from my scope (/ from Bit). Can you describe how to start tracking a component from a project and then remove the component's source files from this project. It's basically what I am trying to achieve.

**Comment by Nuruddinjr** [comment]
I also have the same problem.

I exported my tracked components. Then, I want to change my scope, so 
1. I deleted bitmap file and it gives me `component has invalid state`, then,
2. I deleted `bit.json` and `bit init` again
3. I add components using `bit add `
4. Then run bit status again but it again says it has an invalid state.
here is the full error

```
component components/filters has an invalid state.
           1) it has a model instance so it's not new.
           2) it's not in staged state.
           3) it doesn't have a version in the bitmap file.
           Maybe the component was interrupted during the export and as a result the bitmap file wasn't updated with the new version

```

**Comment by qballer** [comment]
Bit has a local and a remote scope.  What `bit export --eject` is to export remove and `npm install`. In our case the export worked, the eject part fail. So I suggest you will remove the component manually and add via NPM.
