### ISSUE TITLE
Faild to compile SCSS: Invalid CSS after "'": expected 1 selector or at-rule, was "'use strict';"

### ISSUE THREAD

**Issue by alesanchezr** [teambit/bit#1178]
## Expected Behavior
After importing the components on the jobcore.web scope I should be able to import them into another project without issues.

## Actual Behavior
When I run bit import everything runs smoothly but then webpack gives a compilation error when trying to bundle.
![screen shot 2018-08-10 at 5 31 35 pm](https://user-images.githubusercontent.com/426452/43982444-ed8045e8-9cc3-11e8-9fa2-882ca9264afc.png)

## Steps to Reproduce the Problem

1. Import this component into your project: [https://bitsrc.io/jobcore/web/components/dashboard-box](https://bitsrc.io/jobcore/web/components/dashboard-box)
2. import the component into your js file:
```js
import DashboardBox from '@bit/jobcore.web.components.dashboard-box';
```
3. Bundle your application with webpack.

## Specifications

  - Bit version: 13.0.4
  - Node version: v8.11.3
  - npm / yarn version: 6.1.0
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by Neskews** [comment]
Same error here.

It's a bit strange, that nobody reacts to this. Let's me really think about if I should continue using bit.

**Comment by itaymendel** [comment]
@GiladShoham and I will look into the issue and post our results in the next couple of days.
It seems to be related either to the bundler's configuration or to the auto-generated link files.

**Comment by Neskews** [comment]
I was able to fix the problem by using just one single scss file. However, this is not what I want to do most of the time. I prefer sharing some of my scss files, while specific styles should be in a separate file.

**Comment by itaymendel** [comment]
closing this issue, irrelevant.
scss files should be handled by the consuming project's bundler, not the component.
