### ISSUE TITLE
Apply default configuration settings on Bit CLI commands

### ISSUE THREAD

**Issue by amadeogallardo** [teambit/bit#1179]
### Feature Requests

Include additional configuration settings at the `bit.json` file that affect the default behavior for `bit` CLI.

1. `ignore-package-json: true|false`: this setting would enable/disable the addition of `package.json` files on the components folder. Right now this is possible using the CLI, but a bit repetitive to have to use it whenever a new import and/or update is executed. With this setting enabled, the CLI would by default apply it when executing an `import` command.

2. Prevent the addition of the `@bit` dependencies on the root's `package.json` file. I don't think this setting is available on the CLI right now. It would allow for a simpler approach without full dependency management, as suggested on #1166 

3. `import --write`: the documentation mentions a `--write` setting that auto overwrites the physical files, but it doesn't seem to work on the current version. https://docs.bitsrc.io/docs/importing-components.html#fetch-updated-objects-for-a-sourced-component

**Comment by itaymendel** [comment]
sorry for the long response time.

thanks for submitting this feature request. I think that it will help with workflows similar to [this](https://github.com/teambit/bit/issues/1166) as well.

I'll see how we can prioritize it, as it seems like a rather simple feature to implement.

**Comment by janosh** [comment]
@itaymendel Any news on this? I'm particularly interested in the ability to sync React components without any dependency management on `bit`'s part as suggested in #1166.

**Comment by cardiv** [comment]
These missing options are issues I currently have with `bit`. If this is a rather small feature – as @itaymendel mentioned – I hope these options get added soon (at least 1 and 2).

**Comment by davidfirst** [comment]
With the new version, v14.1.0, it's possible now to manually ignore dependencies.
Read here for more details: https://docs.bit.dev/docs/component-dependencies.html#override-dependencies-in-workspace-configuration
