### ISSUE TITLE
bit doesn't track any files

### ISSUE THREAD

**Issue by alexluong** [teambit/bit#1180]
When I run `bit add <file>`, it says that my files are being ignored. I wonder if `.gitignore` and `.npmignore` have anything to do with this. I'm trying to track my files inside `src/components`, and I'm ignoring `src` in `.npmignore`

## Expected Behavior
Components are added and tracked

## Actual Behavior
`warning: no files to add, the following files were ignored: src/lib/components/MyComponent/`

## Steps to Reproduce the Problem

  1. My files structure: `src/lib/components/[Components]/(index.js + Components.js + SubComponents.js + etc)`
  2. In root directory: `bit init`
  3. Then: `bit add src/lib/components/MyComponents`

## Specifications

  - Bit version: `13.0.4`
  - Node version: `v10.7.0`
  - npm / yarn version: `yarn 1.9.2`
  - Platform: `Mac OS High Sierra`
  - Bit compiler (include version): `N/A`
  - Bit tester (include version): `N/A`

**Comment by GiladShoham** [comment]
Hi @alexluong 
Thanks for reporting this.
Bit does read your `.gitignore` file, but not your `.npmignore` file.
You can read about it [here](https://docs.bitsrc.io/docs/faq-bit-basics.html#can-i-use-bit-with-git)
Can you share your .gitignore / .npmignore so I'll try to reproduce it?
(or maybe provide some skelaton repo without any actual code where I can run bit's commands and see the issue)

**Comment by davidfirst** [comment]
@alexluong , if you're still experiencing the issue, please re-open and attach your `.gitignore` file. (you can also send it to me, david@bit.dev and I'll take a look).
