### ISSUE TITLE
No private key password asked

### ISSUE THREAD

**Issue by txgruppi** [teambit/bit#119]
I'm following the Getting started guide and I run in a problem when trying to import babel. It complains about trying to read my encrypted private key without a password but no password was asked.

Running OS X 10.11 (El Capitain) + tmux + zsh

```sh
txgruppi@txgruppi-pro15:~/c/t/b/hello-world$ bit import bit.envs/compilers/babel --compiler --save
Error: Encrypted private key detected, but no passphrase given
    at Client.connect (/usr/local/Cellar/bit/0.5.0/libexec/node_modules/ssh2/lib/client.js:230:15)
    at /usr/local/Cellar/bit/0.5.0/libexec/dist/scope/network/ssh/ssh.js:258:14
    at SSH.connect (/usr/local/Cellar/bit/0.5.0/libexec/dist/scope/network/ssh/ssh.js:253:14)
    at connect (/usr/local/Cellar/bit/0.5.0/libexec/dist/scope/network/network-lib.js:36:96)
    at Remote.connect (/usr/local/Cellar/bit/0.5.0/libexec/dist/remotes/remote.js:66:56)
    at Remote.fetch (/usr/local/Cellar/bit/0.5.0/libexec/dist/remotes/remote.js:107:19)
    at /usr/local/Cellar/bit/0.5.0/libexec/dist/remotes/remotes.js:158:27
```

**Comment by itaymendel** [comment]
Hi,

does Bit points to the correct SSH key? (open terminal and run `bit config get ssh_key_file`).
By default Bit will try to grab what it considers to be the default SSH key (`~/.ssh/id_rsa`). If you store your SSH key elsewhere, you can configure Bit to use it instead (`bit config set ssh_key_file "new/ssh_key/location"`). Sometimes, if Bit tries to use a non-exisiting SSH key can throw this exception.

If this workaround does not solve the problem, can you please provide the following information:
1. which version of Bit do you have installed? (open terminal and run `bit --version`)?
2. does your SSH key requires passphrase?

Cheers

**Comment by txgruppi** [comment]
Hi @itaymendel,

My SSH key requires a password and you can check the output for the commands below:

```sh
txgruppi@txgruppi-pro15:~/c/t/b/hello-world$ bit config get ssh_key_file
/Users/txgruppi/.ssh/id_rsa
txgruppi@txgruppi-pro15:~/c/t/b/hello-world$ file /Users/txgruppi/.ssh/id_rsa
/Users/txgruppi/.ssh/id_rsa: ASCII text
txgruppi@txgruppi-pro15:~/c/t/b/hello-world$ bit --version
0.5.0
```

**Comment by itaymendel** [comment]
thanks @txgruppi, right now Bit does not provide a prompt for entering passphrase for SSH keys.
we are working to resolve it (and provide better error messages instead of stacktraces from unhandled exceptions).

as a temporary workaround you can generate an SSH key without a passphrase, and point Bit to use it - until this issue is resolved.

I will keep you posted on any further development!

**Comment by txgruppi** [comment]
Ok. Thanks @itaymendel.

**Comment by GiladShoham** [comment]
update - passphrase and ssh-agent are now supported (since version 0.11.1).
