### ISSUE TITLE
Extend jest environment to overcome CSS modules

### ISSUE THREAD

**Issue by dzuncoi** [teambit/bit#1191]
## Issue
Currently I'm using CSS module in my codebase with `classnames` library (which will transform className into a unique one) and set 
```javascript
"jest": {
    "moduleNameMapper": {
      "\\.(css|scss)$": "identity-obj-proxy",
    }
  }
```
in `package.json`, as describe here https://github.com/facebook/jest/issues/1347#issuecomment-237164179 (to snapshot unit test purpose )

Now I created a new jest environment at https://bitsrc.io/dzuncoi/uicomponents/jest/tester. It is the same with https://bitsrc.io/bit/envs/testers/jest, just a change in `jest.config.js`:
```javascript
import 'identity-obj-proxy';
module.exports = {
  ...
  moduleNameMapper: {
    "\\.(css|scss)$": "identity-obj-proxy"
  }
};
```
And import this as tester.
## Expected Behavior
I expect running `bit test myComponent` will be executed the same when running Jest in my codebase.
For eg, when creating snapshot from component `<div className={classnames(styles.classValue)} />`, it should create a snapshot with "classValue" as classname

## Actual Behavior
Snapshot is created with a generated classname, not "classValue" anymore. It looks like my new tester environment doesn't work properly and not apply `identity-obj-proxy` to jest config.
Does anyone have any idea about this?

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.9.3
  - npm / yarn version: 5.6.0
  - Platform: MacOS
  - Bit compiler (include version): bit.envs/bundlers/webpack-css-modules@0.0.8
  - Bit tester (include version): dzuncoi.uicomponents/jest/tester@0.0.2

**Comment by dzuncoi** [comment]
Oh I believe I misunderstand something, will get back after confirming the issue

**Comment by dzuncoi** [comment]
I misunderstood between Jest testing environment vs build process. There are some reason
- Normally when in development, we develop -> test -> build. With Bit, we develop -> build -> test (it's reasonable, but I missed it)
- Build process uses `webpack-css-modules` -> it generates className value into hash string, like `className={styles.spinner}` will turn into: 
![image](https://user-images.githubusercontent.com/7270403/44453500-5aaaa880-a623-11e8-8208-6b956486a722.png). 
Then in unit test, normally, without build, we can use
```javascript
const wrapper = shallow(<MyComp {...props} />)
expect(wrapper.find('.spinner').length).toEqual(1) // -> true
```
But Bit run test after building, so we need to import `styles` into test file:
```javascript
const wrapper = shallow(<MyComp {...props} />)
expect(wrapper.find(`.${styles.spinner}`).length).toEqual(1) // -> true
```

The most important part that I missed is the 1st point, Bit builds components first then tests later.

**Comment by itaymendel** [comment]
@dzuncoi  thanks for sharing the solution to your issue.

on a side note - your issue has started a discussion that revolved around allowing more flexibility for a component maintainer by allowing to run tests before build.
I'd like to hear your take on it.

**Comment by dzuncoi** [comment]
@itaymendel Are there any reasons behind testing after building component? Because I do recommend this `allowing more flexibility for a component maintainer by allowing to run tests before build`, it make more sense to test what we develop and deliver well-tested-built one
