### ISSUE TITLE
bit build cannot resolve aliased paths despite resolveModules config

### ISSUE THREAD

**Issue by tony19** [teambit/bit#1195]
## Expected Behavior
`bit build` is able to use `bit.json` config's `resolveModules` to resolve paths with aliases.

## Actual Behavior
`bit build` fails because it cannot resolve paths with aliases.

<details>
<summary>Commands Run</summary>

```shell
➜ bit init
successfully initialized a bit workspace.

➜ bit add src/components/* -t 'src/components/{PARENT}/*.spec.js'
tracking component components/hello-world:
added src/components/HelloWorld/HelloWorld.spec.js
added src/components/HelloWorld/HelloWorld.vue

➜ bit login
already logged in

➜ bit status
new components
(use "bit tag --all [version]" to lock a version with all your changes)

     > components/hello-world ...  issues found
       missing packages dependencies (use your package manager to make sure all package dependencies are installed):
          src/components/HelloWorld/HelloWorld.spec.js -> @/components

see troubleshooting at https://docs.bitsrc.io/docs/troubleshooting-isolating.html
```

After learning the appropriate setup from the [troubleshooting link](https://docs.bitsrc.io/docs/troubleshooting-isolating.html), I updated `bit.json` to include:

    "resolveModules": {
        "aliases": {
            "@": "./src"
        }
    }

*(As an aside, it would be a more pleasant/seamless/convenient developer experience if `bit` automatically picked up the Webpack config for this.)*

And then I tried to pick up where I left off in the setup:

```shell
➜ bit status
new components
(use "bit tag --all [version]" to lock a version with all your changes)

     > components/hello-world ... ok

➜ bit import bit.envs/bundlers/vue --compiler
the following component environments were installed
- bit.envs/bundlers/vue@0.0.3

➜ bit import bit.envs/testers/jest --tester
the following component environments were installed
- bit.envs/testers/jest@0.0.34

➜ bit build
error: bit failed to build components/hello-world with the following exception:
Module not found: Error: Can't resolve '@/components/HelloWorld' in '/Users/tony/src/tmp/bit-issue/src/components/HelloWorld'.
ModuleNotFoundError: Module not found: Error: Can't resolve '@/components/HelloWorld' in '/Users/tony/src/tmp/bit-issue/src/components/HelloWorld'
    at factoryCallback (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/webpack/lib/Compilation.js:282:40)
    at factory (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/webpack/lib/NormalModuleFactory.js:237:20)
    at resolver (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/webpack/lib/NormalModuleFactory.js:60:20)
    at asyncLib.parallel (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/webpack/lib/NormalModuleFactory.js:127:20)
    at /Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/async/dist/async.js:3888:9
    at /Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/async/dist/async.js:1062:13)
    at /Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/async/dist/async.js:969:16
    at /Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/async/dist/async.js:3885:13
    at resolvers.normal.resolve (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/webpack/lib/NormalModuleFactory.js:119:22)
    at onError (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/tony/src/tmp/bit-issue/.git/bit/components/bundlers/vue/bit.envs/0.0.3/node_modules/tapable/lib/Tapable.js:252:11)
```
</details>

## Steps to Reproduce the Problem

 1. Run the following commands:

      ```shell
      git clone https://github.com/tony19-sandbox/bit-issue.git
      cd bit-issue
      bit build
      ```

## Specifications

  - Bit version: 13.0.4
  - Node version: 10.5.0
  - npm / yarn version: 6.1.0
  - Platform: macOS High Sierra 10.13.6
  - Bit compiler (include version): `bit.envs/bundlers/vue@0.0.3`
  - Bit tester (include version): `bit.envs/testers/jest@0.0.34`

See https://github.com/tony19-sandbox/bit-issue

**Comment by tony19** [comment]
Glancing at https://bitsrc.io/bit/envs/bundlers/vue/code, I think this is an issue in `bundlers/vue`. @amitgilad3 Where can I find the github repo for it? Thanks

**Comment by tony19** [comment]
Nevermind. Got an answer on gitter: https://github.com/teambit/bit.envs/tree/master/src/bundlers/vue

**Comment by itaymendel** [comment]
I'd like to add a few notes on this one.
The current implementation of the envs feature does not support passing a config to a component's builder/tester. This forces the build env to have its own configuration (including aliases).
There's an ongoing process to add additional APIs to the envs, to allow passing of configs to an env. This should resolve most of such issues. 
The APIs are already merged to the master branch. We're still running tests and stabilizing it and updating the documentation.

We will be releasing a new set of envs, that by default grab the configs from the standard config files of each tool (for example - .babelrc for Babel). You can see the progress on the envs in this repo - https://github.com/teambit/bit-envs

note - it will be fully backward compatible with the current envs.

**Comment by paulrenshaw-tls** [comment]
Is there a way to deal with this yet? Still getting:

```
error: bit failed to build component-name with the following exception:
Module not found: Error: Can't resolve '@/components/ComponentName' in...
```

**Comment by GiladShoham** [comment]
@paulrenshaw-tls There is no good way to deal with this yet. Once we will release the new envs it will be very easy.
For now you can fork our compiler and modify it to work for your own configuration.

**Comment by tony19** [comment]
@GiladShoham This is still an issue with the envs for Vue (2.6.15). Or were you referring to something else?

**Comment by GiladShoham** [comment]
I was referring to a version that not yet published. A version that allows you to pass configuration to the compiler.

**Comment by tony19** [comment]
When do you expect that to be published? Will it be the same repo as the new [`envs`](https://github.com/teambit/envs)?

**Comment by GiladShoham** [comment]
@tony19 
It will be in the repo you mentioned.
I don't have an ETA about it yet, but we are working on updating all our envs.
But if you can describe the exact issue you have, I might help you solve it, or help you found a workaround until it will be published.
There is a good chance your issue even not related to the new env (or you can solve it easily by forking the Vue compiler)

**Comment by tony19** [comment]
The issue is `bit` doesn't handle path aliases despite the `resolveModules` config in `bit.json` (see original description at the top). As far as I can tell, the cause of the problem is `bit`'s bundler for Vue is ignoring the Webpack config from the Vue project (which would already config the path aliases). To workaround this, I've forked the bundler to correct the problem.

**Comment by GiladShoham** [comment]
@tony19 Thanks for the update.
The resolve modules option for bit, is only used for the auto dependency calculation and resolving bit does.
It's not related to the build process which handled by a bit compiler.
The workaround I want to suggest is indeed to fork the compiler and fix it.
Hopefully, soon, you won't have to fork it as it will read your own configuration.
Keep watching the envs repo to get updates about the compilers and testers.

**Comment by jamiespink** [comment]
Is there any news please? I have the same issue now

**Comment by GiladShoham** [comment]
@jamiespink For now you will have to fork the compiler as well. maybe @tony19 can share his own.
Soon we will introduce a new infrastructure for compilers / testers and extensions, so it will be easier to do.
Also note, that with the new infra we won't support aliases any more, since we come with a better alternative for this.
We will document everything once it will be available.
