### ISSUE TITLE
"compiler is not defined, please define a compiler in bit.json"

### ISSUE THREAD

**Issue by monkeymonk** [teambit/bit#1198]
## Expected Behavior

`bit build foo/bar` should build normally.

## Actual Behavior

`bit build foo/bar` returns "compiler is not defined, please define a compiler in bit.json"

`bit.json` shows a compiler as expected :

```json
{
    "env": {
        "compiler": "bit.envs/compilers/babel@0.0.20",
        "tester": "bit.envs/testers/mocha@0.0.14"
    },
    "dependencies": {
        "monkeymonk.something/foo/bar": "0.0.2"
    },
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "npm"
}
```

Note that `bit test foo/bar` return also an error : "tester for component: foo/bar@0.0.2 is not defined".
But `bit export monkeymonk.something foo.bar` run properly.

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.11.1
  - npm / yarn version: 6.3.0
  - Platform: macOS 10.13.6
  - Bit compiler (include version): bit.envs/compilers/babel@0.0.20
  - Bit tester (include version): bit.envs/testers/mocha@0.0.14

**Comment by monkeymonk** [comment]
Hello @itaymendel , really sorry but I can't give you the answer since I have completely deleted the component to recreate it. Which has fixed my problem.
What I can tell is that the component was created and exported previously without tests (tag 0.0.1). I then created the tests and so added compiler and tester (tag 0.0.2). Then, wanted to export the whole thing... and was stuck on that.

**Comment by itaymendel** [comment]
I wasn't able to recreate the issue according to the flow.
Closing it, for now, if this happens again, please comment and add the additional info/steps to recreate it.

**Comment by Wurielle** [comment]
I still have this issue with any of my components.
Tested with these 2 pieces of code: [optimize-images](https://bitsrc.io/wurielle/pristine/node-scripts/optimize-images/code) & [slugify-files](https://bitsrc.io/wurielle/pristine/node-scripts/slugify-files/code)

 # Steps to reproduce
 In a brand new folder:
1. bit init
2. bit import bit.envs/compilers/babel --compiler 
3. bit import wurielle.pristine/node-scripts/optimize-images
4. bit build node-scripts/optimize-images --> compiler is not defined, please define a compiler in bit.json

# Specifications
- Bit version: 13.0.4
- Node version: 10.11.0
- npm / yarn version: 6.4.1
- Platform: Windows 10 17134.285
- Bit compiler: bit.envs/compilers/babel@0.0.20

# Other Informations
## bit.json after step 3:
```json
{
    "env": {
        "compiler": "bit.envs/compilers/babel@0.0.20"
    },
    "dependencies": {
        "wurielle.pristine/node-scripts/optimize-images": "0.0.3"
    },
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "npm"
}
```
## bit show node-scripts/optimize-images:
```
λ bit show node-scripts/optimize-images
╔══════════════════╤════════════════════════════════════════════════════╗
║ Id               │ node-scripts/optimize-images@0.0.3                 ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Language         │ javascript                                         ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Main File        │ optimize-images.js                                 ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Dependencies     │ bluebird@^3.5.1                                    ║
║                  │ sharp@^0.20.7                                      ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Dev Dependencies │                                                    ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Files            │ optimize-images.js                                 ║
╚══════════════════╧════════════════════════════════════════════════════╝

No documentation found
```

**Comment by itaymendel** [comment]
@Wurielle , to modify a component and add a compiler to it you'll need to manually edit it's `bit.json` file. To do so, include the `--conf` when importing the component. Bill will then generate a `bit.json` file in the directory the component was imported too. Copy the `compiler` configuration to it, and tag a new version.

`bit import <component ID> --conf`

This should solve your problem.
