### ISSUE TITLE
import is not working when remote scope name is the same as local scope name

### ISSUE THREAD

**Issue by alexsmr** [teambit/bit#1200]
## Expected Behavior
import command should work

## Actual Behavior
> bit import -o
error: component "mlui-opd/common/tabs@0.0.1" was not found

## Steps to Reproduce the Problem
I have remote scope "mlui-opd" on ssh server. Number of components that mapped in other git repo to that scope listed in .bitmap In step 5 I just copy these components bitmap from mapped git repo.

  1. mkdir mlui-opd
  2. cd mlui-opd
  3. bit init 
  4. bit remote add ssh://your-remote-ssh-server
  5. cp path-to-bitmap/.bitmap .
  6. bit import -o

This results in error above. If on step 1. you name the folder differently, there will be no problem. Component objects will be properly imported.

This is basic scenario when you clone repo that mapped to remote scope which apparently has the same name as a folder where .bit is initialized.

If the local scope name in scope.json  must be different from remote, then 'remote add' should provide intelligent warning or ask to rename local bit scope. But from my understanding having same name should be ok.

## Specifications

  - Bit version: 13.0.4
  - Node version: v8.11.1
  - npm / yarn version: 5.6.0
  - Platform: mac
  - Bit compiler (include version): NA
  - Bit tester (include version): NA

**Comment by itaymendel** [comment]
Workaround:

1. open the `.git/bit` directory.
1. open the `scope.json` file
1. rename the `scope` property to a different name.

Closing this issue for now.
