### ISSUE TITLE
Workaround for the error "too much open files"

### ISSUE THREAD

**Issue by canercandan** [teambit/bit#1201]
I come up with a setup with more than thousands of tracked files and hundred components and at some point the command `bit status` just stopped working with an error such as `too much open files`.

I googled and found many thinks on internet but the solution depends also on the user system so here is one troubleshooting guide to solve this issue in case anyone else faces the same error.

This could also be content draft we can improve and add under the `Troubleshooting` section in the documentation.

---

In case you get an error such as `too much open files`, in most cases it is because you have a cap on the number of files you can open in your system, therefore the solution is to rather remove this limit or increase it.

You can check this limit by using the command line:

```
ulimit -n
```

You can increase the limit by changing the setting in the `/etc/security/limits.conf` file, and adding those two lines:

```
*     soft    nofile    64000
*     hard    nofile    64000
```

you will also need to add the following line into the `/etc/pam.d/common-session` file:

```
session required        pam_limits.so
```

And I recommend to rather disconnect and reconnect to your session or just reboot your system.

You can check that the new limit has been increased with `ulimit -n`.

If it does not, it could be because you are using `systemd` and in this case `systemd` overwrites those values with default internal values.

However there is a solution for that, you can change the settings in the `systemd` config file by editing the file `/etc/systemd/user.conf` and `/etc/systemd/system.conf` and adding the following line to both files:

```
DefaultLimitNOFILE=64000
```

You should reboot your system and from now on now `ulimit -n` should show you the value correct value `64000`.

**Comment by itaymendel** [comment]
thanks, @canercandan for sharing a solution for the issue.
I'm closing this issue.

For anyone who encounters this issue and is not able to resolve it with this workaround - please post a comment below.

**Comment by farshidinanloo** [comment]
I get this error in windows 10 , how can I increase the limit in windows?
 @canercandan
