### ISSUE TITLE
mockery should be devDependency

### ISSUE THREAD

**Issue by allain** [teambit/bit#121]
mockery is listed as a normal dependency but is only used during testing

**Comment by davidfirst** [comment]
@allain, thanks for your comment. Normally, Mockery is indeed a dev depdencancy, but not in this case.
The file that uses Mockery is "src/specs-runner/worker.js", which responsible for running the tests of bit components (when running "bit test" or "bit export"). In other words, it is part of the product and not the tests.

**Comment by allain** [comment]
Perfect.
