### ISSUE TITLE
Error when using StencilJS

### ISSUE THREAD

**Issue by darthsitthiander** [teambit/bit#1212]
I'm getting errors when trying to track my components made with StencilJS using the DSL method:
`
bit add src/components/* --main src/{PARENT}/{PARENT}.js --tests src/components/{PARENT}/{FILE_NAME}.spec.js --namespace ui
`

Folder structure:
```
src
    └───components
        └───button
            ├───button.scss
            ├───button.spec.ts
            └───button.tsx
```
## Expected Behavior

```
$ bit status
new components
    > ui/button... ok
```

## Actual Behavior
```
+ bit add src/components/* --main src/{PARENT}/{PARENT}.js --tests src/ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParameterBindingException
    + FullyQualifiedErrorId : ParameterSpecifiedAlready
```
```
$ bit status
nothing to tag or export (use "bit add <file...>" to track files or directories as components)
```
## Steps to Reproduce the Problem

  1. Create at least two components with StencilJS
  1. Initialize Bit in StencilJS repository
  1. Try and track the components with DSL using the above specified command

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.10.0
  - npm / yarn version: 5.6.0
  - Platform: StencilJS
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
Any chance you can share a project with these components that will fail the `add` command?

**Comment by darthsitthiander** [comment]
itaymendel unfortunately I am not allowed to share any code and we have moved away from using bit, sorry.

**Comment by FDiskas** [comment]
This worked for me: :arrow_up_small:
```
bit add src/components/* --main src/components/{PARENT}/{FILE_NAME}.tsx --tests src/components/{PARENT}/{FILE_NAME}.spec.tsx
```

**Comment by davidfirst** [comment]
Nothing can be done for now. If someone encounters this issue again, please reopen.

**Comment by jdnichollsc** [comment]
@FDiskas is StencilJS working for you? Do you have any example?

**Comment by FDiskas** [comment]
@jdnichollsc sorry no
