### ISSUE TITLE
Bit imported package doesn't work with AWS SAM CLI

### ISSUE THREAD

**Issue by broom9** [teambit/bit#1222]
## Expected Behavior
After importing a package from bit, it should work when the app folder is mounted into a docker env, like how AWS SAM Local works when running `sam invoke`.

## Actual Behavior
It throws errors when running in docker like `Cannot find module '@bit/fluxwork.flux.util.logger'`. 

I think it's due to the symlink of node_modules/@bit/fluxwork.flux.util.logger is using an absolute path, not relative path. So when the app folder mounted into a Docker, the symlink breaks. It's probably better to create the symlink as a relative path. After I manually do the operations below, it works in SAM:

```
cd node_modules/@bit
rm fluxwork.flux.util.logger
ln -s ../../components/util/logger fluxwork.flux.util.logger
```

## Steps to Reproduce the Problem

  1. Install AWS SAM CLI and Docker https://docs.aws.amazon.com/lambda/latest/dg/sam-cli-requirements.html
  1. Generate a SAM CLI sample app with `sam init`
  1. Import any bit module and require it in the main app.js in the Lambda.
  1. Invoke it with `sam invoke` command.

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.11
  - npm / yarn version: npm 6.4.1
  - Platform: Mac OS X
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@broom9 Thanks for reporting this.
The reason we use absolute links rather than relatives is that sometimes we don't know where npm will put the module.
But in this specific case, it might be irrelevant and we might use relative paths. I'll check this and update you.
Another option that might help you is using `bit link` command which will recreate all the links again (I'm not sure it will work in docker env, but I'll check that as well).
You can read more about it here [link-components](https://docs.bitsrc.io/docs/importing-components.html#link-components)

**Comment by davidfirst** [comment]
For the record, another reason we use absolute paths when symlinking is that we use the package [symlink-or-copy](https://www.npmjs.com/package/symlink-or-copy) to support also Windows and this package creates symlinks with absolute paths.

**Comment by rasmuscnielsen** [comment]
Just spent half a day tracking down why my build failed every time I imported a component, only to come to the same conclusion as the author of this issue: 
The absolute path is found invalid in my docker build container.

Is there any chance it could be added as an option to use relative paths? Either in `bit.json` or as a flag `bit import org.collection/component --relative` ?

**Comment by GiladShoham** [comment]
@rasmuscnielsen Thanks for your suggestion.
I'm not sure a flag to bit import is a good way to deal with it. when importing a component it created a different kinds of links (from root/node_modules to the imported component), from dependant component in the workspace to the imported component, from the imported component node_modules to pre-existing dependencies in the workspace and so on).
I think it might be better to always first try relative links and only on fail fallback to symlink or copy.
@rasmuscnielsen @davidfirst  What do you think?

**Comment by rasmuscnielsen** [comment]
@GiladShoham That would definitely solve the problems I've experienced 👍

**Comment by GiladShoham** [comment]
Ok, we will add it to our pipeline and keep this issue updated.

**Comment by davidfirst** [comment]
@GiladShoham , Sounds good to me.

**Comment by GiladShoham** [comment]
@davidfirst Let's open a dedicated issue about the technical change that required and reference this issue.

**Comment by itaymendel** [comment]
closing this issue. new `bit import` behavior does not create a slew of symlinks and odd dir-structure in the consuming project.
