### ISSUE TITLE
Not able to tag components

### ISSUE THREAD

**Issue by mulraj208** [teambit/bit#1226]
link-generation: failed finding sujayjaju.kaleidoscope/components/module@1.0.6 in the dependencies array of sujayjaju.kaleidoscope/components/layout@1.0.6.
The dependencies array has the following ids: sujayjaju.kaleidoscope/css/layout@0.0.1, sujayjaju.kaleidoscope/components/feed-module@1.0.3, sujayjaju.kaleidoscope/components/cross-fade-image@1.0.3, sujayjaju.kaleidoscope/js/constants@1.0.3, sujayjaju.kaleidosco
pe/components/image-module@1.0.3, sujayjaju.kaleidoscope/components/text-module@1.0.3, sujayjaju.kaleidoscope/components/video-module@1.0.3, sujayjaju.kaleidoscope/components/weather-module@1.0.3, sujayjaju.kaleidoscope/js/utils@1.0.3, sujayjaju.kaleidoscope/co
mponents/module@1.0.3

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.9.4
  - yarn version: 1.9.4
  - Platform: Windows
  - Bit compiler (include version): 
  - Bit tester (include version):

**Comment by shaununderwood** [comment]
reproduction instructions?

**Comment by mulraj208** [comment]
I already had layout, module and other components exported to bit scope

I changed the module component exported that to the scope 

The problem is when i export the Layout Component the dependent Module component is of previous version.

Also i can see that Layout Component dependencies is Module component@1.0.3
Which is the older version of the component.(On bit website)

Because of that i taught let's change the layout component to see if it take's the proper module component and that time this error came

**Comment by mulraj208** [comment]
D:\wamp\www\kaleidoscope-web-client> bit import sujayjaju.kaleidoscope/components/layout

successfully ran npm install at D:\wamp\www\kaleidoscope-web-client\components\components\layout 

successfully imported one component
- added sujayjaju.kaleidoscope/components/layout new versions: 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, currently used version 1.0.6

D:\wamp\www\kaleidoscope-web-client>bit status
nothing to tag or export (use "bit add <file...>" to track files or directories as components)

D:\wamp\www\kaleidoscope-web-client>bit status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > components/layout ... ok

D:\wamp\www\kaleidoscope-web-client>bit tag --all
successfully installed the sujayjaju.kaleidoscope/compilers/react@0.0.16 compiler
1 components tagged | 0 added, 1 changed, 0 auto-tagged
changed components:  sujayjaju.kaleidoscope/components/layout@1.0.7

D:\wamp\www\kaleidoscope-web-client>bit export sujayjaju.kaleidoscope
exported 1 components to scope sujayjaju.kaleidoscope

D:\wamp\www\kaleidoscope-web-client>bit import sujayjaju.kaleidoscope/components/module

successfully ran npm install at D:\wamp\www\kaleidoscope-web-client\components\components\module 

successfully imported one component
- up to date sujayjaju.kaleidoscope/components/module

D:\wamp\www\kaleidoscope-web-client>bit status
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > components/layout ... ok
     > components/module ... ok

D:\wamp\www\kaleidoscope-web-client>bit tag --all
link-generation: failed finding sujayjaju.kaleidoscope/components/module@1.0.6 in the dependencies array of sujayjaju.kaleidoscope/components/layout@1.0.7.
The dependencies array has the following ids: sujayjaju.kaleidoscope/css/layout@0.0.1, sujayjaju.kaleidoscope/components/feed-module@1.0.3, sujayjaju.kaleidoscope/components/cross-fade-image@1.0.3, sujayjaju.kaleidoscope/js/constants@1.0.3, sujayjaju.kaleidosco
pe/components/image-module@1.0.3, sujayjaju.kaleidoscope/components/text-module@1.0.3, sujayjaju.kaleidoscope/components/video-module@1.0.3, sujayjaju.kaleidoscope/components/weather-module@1.0.3, sujayjaju.kaleidoscope/js/utils@1.0.3, sujayjaju.kaleidoscope/co
mponents/module@1.0.3

D:\wamp\www\kaleidoscope-web-client>bit tag --all 1.0.8
link-generation: failed finding sujayjaju.kaleidoscope/components/module@1.0.6 in the dependencies array of sujayjaju.kaleidoscope/components/layout@1.0.7.
The dependencies array has the following ids: sujayjaju.kaleidoscope/css/layout@0.0.1, sujayjaju.kaleidoscope/components/feed-module@1.0.3, sujayjaju.kaleidoscope/components/cross-fade-image@1.0.3, sujayjaju.kaleidoscope/js/constants@1.0.3, sujayjaju.kaleidosco
pe/components/image-module@1.0.3, sujayjaju.kaleidoscope/components/text-module@1.0.3, sujayjaju.kaleidoscope/components/video-module@1.0.3, sujayjaju.kaleidoscope/components/weather-module@1.0.3, sujayjaju.kaleidoscope/js/utils@1.0.3, sujayjaju.kaleidoscope/co
mponents/module@1.0.3

D:\wamp\www\kaleidoscope-web-client>bit diff
------------------------------------------------------------------
showing diff for sujayjaju.kaleidoscope/components/layout
------------------------------------------------------------------

--- Main File (1.0.7 original)
+++ Main File (1.0.7 modified)
- js/components/Layout.js
+ assets/js/components/Layout.js

--- Dependencies (1.0.7 original)
+++ Dependencies (1.0.7 modified)
- [ sujayjaju.kaleidoscope/css/layout@0.0.1, sujayjaju.kaleidoscope/components/module@1.0.3, sujayjaju.kaleidoscope/js/constants@1.0.3, prop-types@^15.6.2, react@^16.4.1 ]
+ [ sujayjaju.kaleidoscope/css/layout@0.0.1, sujayjaju.kaleidoscope/components/module@1.0.6, sujayjaju.kaleidoscope/js/constants@1.0.3, prop-types@^15.6.2, react@^16.4.1 ]


------------------------------------------------------------------
showing diff for sujayjaju.kaleidoscope/components/module
------------------------------------------------------------------
--- assets\js\components\Module\index.js (1.0.6 original)
+++ assets\js\components\Module\index.js (1.0.6 modified)
@@ -72,6 +72,7 @@ class Module extends Component {
   render() {
     const style = this.moduleStyle();
     const { showModal, module } = this.props;
+
     return (
       <div style={style} onClick={() => (module.type !== 5 ? showModal(this.props) : null)} role="presentation">
         {this.renderContent()}

--- Main File (1.0.6 original)
+++ Main File (1.0.6 modified)
- Module/index.js
+ assets/js/components/Module/index.js

**Comment by davidfirst** [comment]
@mulraj208 thanks for posting the issue. I find it hard to reproduce it on my end.
By any chance can you add me as a collaborator to your scope? my email is david@bitsrc.io.

**Comment by mulraj208** [comment]
Hi David,
I'm sorry I can't add you to the scope because the scope is created by the company.
But surely i can replicate these error again.

1. Suppose there is three Component A, B, C
2. A imports B and B imports C
3. Now you export all your component A, B, C to the scope
4. After a while you want to change the component C. So here's what I did 
 a) In new folder ran "bit init"
 b) Imported the component C and made the changes I wanted. The important thing here is that the 
      project only includes C component.
 c) Ran "bit status". So what happens here is that bit shows changes only to the C component. Where 
      as the expected behaviour is that bit recognizes that C is changed which changes the functionality 
      of the B as well as A components and update their dependencies.
 d) So now if you export the C component it's new version is available in the scope but A and B 
      dependencies don't change.
 e) After reading the docs(https://docs.bitsrc.io/docs/faq-component-dependencies.html#auto- 
     tagging-component-versions). I imported all the components.
 f) Made changes to the C component. Run "bit status" command. Bit recognizes C component is 
     changed as well as B component needs to be auto tagged. Good but not the expected behaviour
 g) So in both this cases if C component is exported new version is available.
 h) The link generation error comes when you make changes in the A component and try to tag it .
      And as the error depicts the A component dependencies array is trying to find the new version of 
     the C component.

A is the Layout component
B is the Module component
C is the  ImageModule component

**Comment by davidfirst** [comment]
@mulraj208 , sorry for getting back to you late, I understand all the steps until #4.g.

Here is what I understand:
Project 1)
you created 3 components. component A has a dependency B, component B has a dependency C.
Project 2) 
imported component C, changed and tagged. Now C has a new version that A and B are not aware of.

From here, I didn't get how you proceed. Did you import C to project 1 and tried to tag A or you created a new project "3" and import A, B, and C to that project?

**Comment by mulraj208** [comment]
I created a new project "3" and only imported C component to the project.

**Comment by mulraj208** [comment]
Hi @davidfirst, the new version of bit (14.0.2) solves this problem. Thank you so much.
