### ISSUE TITLE
Docz/mdx support (feature)

### ISSUE THREAD

**Issue by thislogancall** [teambit/bit#1231]
Writing JSDocs or another documentation twice is a pain. I really enjoy bitsrc, but seriously, if you somehow were able to incorporate mdx (https://github.com/pedronauck/docz) it would be a match made in heaven. If you're not aware, mdx allows you to write jsx in markdown, there are also a couple of wrapper components docz provides that allow you to quickly generate a PropsTable of all props of a jsx component.

**Comment by itaymendel** [comment]
Hi @loganfromlogan , sorry for the long response time.

One of the main problems we want to tackle is figuring out a better support for documenting components. Regardless of the type of documentation system you use, Bit should be extendable to support any of them.
So Bit will not support Docz specifically but will allow creating a plugin that will handle component documentation. So on `bit show` (and in bitsrc.io), the documentation generated by the plugin will be presented.

There is no specific ETA on when the additional APIs for the extension system will be released. We are still working on the specs and design of how to extend the extension system in Bit, to support more features and save more types of data.

I'm keeping this issue open for now, will update on the progress.

**Comment by itaymendel** [comment]
Closing the issue. New `docs` format support rendering of React code, so you could use any MDX lib to render an MDX file without built-in support in Bit.
