### ISSUE TITLE
error adding remote scope

### ISSUE THREAD

**Issue by ramigg** [teambit/bit#1236]
## Expected Behavior
followed the instructions [here](https://docs.bitsrc.io/docs/conf-bit-on-the-server.html) to setup a remote scope on my linux machine. 
Expected to be able to add remote scope with bit remote add...

## Actual Behavior
error: remote scope "/opt/bit/my-scope-name" was not found.

But it's there - I created the scope with bit init --bare
Also when I try to `scp bit@my-server-name:/opt/bit/my-scope-name/scope.json .` there is no problem (works fine with the ssh public key).
## Steps to Reproduce the Problem

Follow exactly the instructions on the [doc](https://docs.bitsrc.io/docs/conf-bit-on-the-server.html) to add remote scope on my server and `bit remote add...` on my working machine.
## Specifications

  - Bit version:13.0.4
  - Node version:10.10
  - npm / yarn version:6.4.1
  - Platform: on the server ubuntu 16.04. On my working machine fedora 28
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by ramigg** [comment]
By the way when I try on the remote server where I have the remote scope to create:
`mkdir /opt/bit/test`
`cd /opt/bit/test`
`bit init`
`bit remote add file:///opt/bit/my-remote-scope`
It works fine

**Comment by GiladShoham** [comment]
@ramigg Thanks for reporting this.
I suggest you will look on this repo - https://github.com/teambit/bit-docker
This repo is a docker container you can run and come with a bare scope you can connect to using ssh.
You can use it as is or just take a look on the dockerfile / init.sh script and make the same configuration on your own server.
Let me know if you need more help.

**Comment by prananta** [comment]
I know this issue is closed, but for those who encounter this problem, check the log in `~/Library/Caches/Bit/logs/debug.log`. In my case the log shows

```shell
ssh: failed parsing error as JSON, error: bash: bit: command not found
```

I could ssh to my server and run `bit` command just fine. I installed `bit` using npm but the bin directory is in a custom path which I added to `$PATH` variable in `.bashrc` file. Unfortunately, there's a piece of code at the top of my `.bashrc` file that prevents the path to `bit` to be set. 

```shell
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

Comment those lines or delete and now I can add remote scope.

**Comment by ckken** [comment]
same question

**Comment by ckken** [comment]
got an error from command add <url>: /www/bit_server/react-demo-scope. Error serialized: {"stack":"/www/bit_server/react-demo-scope\n    at /usr/local/lib/node_modules/bit-bin/dist/scope/network/ssh/ssh.js:749:13\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)","isUserError":true,"name":"/www/bit_server/react-demo-scope","code":129}
User gets the following error: error: remote scope "/www/bit_server/react-demo-scope" was not found.
error: remote scope "/www/bit_server/react-demo-scope" was not found.

**Comment by ckken** [comment]
![image](https://user-images.githubusercontent.com/3890513/79831287-b2da1500-83d9-11ea-8793-da0554269ae0.png)

**Comment by GiladShoham** [comment]
@ckken Are you trying to add it on the same machine or another machine?
What did you pass to the `bit remote add` command?
