### ISSUE TITLE
Exporting becomes slower over time

### ISSUE THREAD

**Issue by CiriousJoker** [teambit/bit#1242]
## Expected Behavior
Export times should be solely dependant on file count.

## Actual Behavior
Export times increase each time I export, even if the file count didn't change and the file size is pretty much the same, at worst 1% more in total.

Creating a new project at v0.0.1 fixes this, but it's not practical.

## Steps to Reproduce the Problem

Theoretically, this should be reproducable easily by just creating a bit module, generating 100 files and running a bash script to tag + export over night. However, I have not tried that.

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.11.0
  - npm / yarn version: 6.4.1 / 1.10.1
  - Platform: x64 Arch Linux 4.18.10
  - Bit compiler (include version): no idea where I find this
  - Bit tester (include version): same

**Comment by davidfirst** [comment]
The performance of bit-export has been improved drastically by the following PR:
https://github.com/teambit/bit/pull/1273
https://github.com/teambit/bit/pull/1268
https://github.com/teambit/bit/pull/1265

They were all merged and will be part of the next release.
Closing the task for now. If after trying the new version the export is still slow, please reopen.

**Comment by CiriousJoker** [comment]
Thanks, I'll try it tomorrow

**Comment by davidfirst** [comment]
@CiriousJoker , although it's merged to master, it'd be available only once a new version is released, which is going to be soon.

**Comment by CiriousJoker** [comment]
So, when is "soon" going to be?
I just checked my version and it's still 13.0.4, the same as in the [releases](https://github.com/teambit/bit/releases) tab.

Oct 20 was quite a while ago, did you guys just forget to press the "release button"?
