### ISSUE TITLE
CLI keeps asking for username and password

### ISSUE THREAD

**Issue by realfresh** [teambit/bit#1244]
## Expected Behavior
Be able to import and export components without needing to re-enter username and password every time

## Actual Behavior
Every time I import or export a component, I must provide auth details again. I have already read the guide on auth issues, I've logged in successfully, I've even added private key and set "ssh_key_file" in the bit config settings. I've tried re-logging out and in again to no success.

## Steps to Reproduce the Problem

  1. Install bit
  2. Login 
  3. Export component (happens here)
  4. Import component (happens here)

## Specifications

  - Bit version: 13.0.4
  - Node version: 10.10.0
  - npm / yarn version: 6.4.1 / 1.9.4
  - Platform: Windows 64 bit
  - Bit compiler (include version): ?
  - Bit tester (include version): ?

**Comment by itaymendel** [comment]
hi, i have a few questions:

1. Does your SSH key pair has passphrase defined for it?
2. Can you make sure that the right public key has been uploaded to your user account?
3. What happens if you use `bit login` instead of SSH key pair?

**Comment by realfresh** [comment]
Hi,

1. No passphrase defined on SSH key
2. It is definitely the right public key
3. I've tried bit login to no success, it keeps saying I'm successfully logged in but still requests username and password every time. I can confirm that when looking at bit config, my information is correct. Might just try to uninstall and reinstall it.

One thing I'm not understanding, with the SSH authentication. When I read the guide at https://github.com/teambit/bit-docs/blob/master/content/docs/setup-authentication.md, it only tells you how to add the public key to bit on the website. But how does the bit CLI pickup the private key on Windows?

**Comment by realfresh** [comment]
Just got it to work with bit login. I tried uninstalling it and reinstalling it but that didn't seem to get rid of my existing login configuration. So I uninstalled it again and made sure to delete any leftover config files in windows %AppData% from the npm and yarn caches.

Once I did that and reinstalled it again, I was able to re-login correctly and now it works fine.

**Comment by smccleary** [comment]
Well this doesn't help. Having the same issue

**Comment by smccleary** [comment]
Uninstalled, re-installed still being prompted for password!

**Comment by itaymendel** [comment]
Reopening the issue.

Can you please share bit’s log from all machines?
https://docs.bitsrc.io/docs/logs.html
