### ISSUE TITLE
Typescript compilation not recognising Typescript module paths correctly

### ISSUE THREAD

**Issue by garethbrown82** [teambit/bit#1255]
I'm using Typescript module path resolving in a create react app project so that instead of using `import { ComponentName } from '../ComponentName'`
I can use
`import { ComponentName } from @components/ComponentName'`

So that bit recognises the path I've added the following to the bit.json file:
```
"resolveModules": {
        "aliases": {
            "@components": "src/components"
        }
    }
```
I then have a component I'm exporting to bit `BitTest` that depends on another component `BitBorderTest` and imports it using:
`import { BitBorderTest } from '../BitBorderTest'`
This works fine in the consuming app as I'm using a relative path.

I also have another component which is exactly the same in everyway excepts for the import path, this components is called `BitTest2` and depends on `BitBorderTest2` using:
`import { BitBorderTest2 } from '@components/BitBorderTest2'`
When I'm consuming this component in another app it throws "ReferenceError: exports is not defined" in the browser.

The repository with the two test components BitTest and BitTest2 is here: https://github.com/garethbrown82/demo-bit-components

The repository for the consuming app is here:
https://github.com/garethbrown82/demo-bit-app
Render <BitTest /> and it will work fine but <BitTest2 /> will throw the error. Currently the repo will try to render BitTest2 and throw an error but BitTest can be uncommented in [App.tsx](https://github.com/garethbrown82/demo-bit-app/blob/master/src/App.tsx) to render the working version instead. Just comment out BitTest2.

Both test components can be added fine using `bit add` and are located at the following scope: https://bitsrc.io/garethbrown/bit-test

## Expected Behavior
Bit recognises the correct paths using the resolve modules alias' configuration and builds the components accordingly.

## Actual Behavior
Bit does not resolve alias paths correctly which causes: "ReferenceError: exports is not defined" in the browser

## Steps to Reproduce the Problem
Clone the repo here: https://github.com/garethbrown82/demo-bit-app
Install packages with `npm install`
Run this app using `npm start`
It is set up to try and render the broken BitTest2 component and will render an error

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.11.4
  - npm: 6.4.1
  - Platform: macOs 10.13.6
  - Bit compiler (include version): typescript v0.0.5
  - Bit tester (include version): none

**Comment by davidfirst** [comment]
@garethbrown82 , thanks for taking the time to report the issue with detailed instructions on how to reproduce. 
I was able to reproduce it, and from a quick look, it seems to be a bug with the post-install script Bit generates to create the link for custom-resolved-modules of typescript.

Specifically, in the project above, replacing the content of 
node_modules/@bit/garethbrown.bit-test.components.bit-test2/node_modules/@components/BitBorderTest2/index.js 
with the following code will get the project works.
```
exports.BitBorderTest2 = require('@bit/garethbrown.bit-test.components.bit-border-test2');
module.exports = require('@bit/garethbrown.bit-test.components.bit-border-test2');
```
(it's not a solution, just a proof that the issue is with how the link file 'index.js' was incorrectly generated.)

I'm working to solve this issue so it'll be part of the next release. I'll keep this issue updated.

**Comment by garethbrown82** [comment]
@davidfirst, thanks for the update. Sounds like good news, I look forward to the next release. Cheers!
