### ISSUE TITLE
CSS preprocessor not working when rendering

### ISSUE THREAD

**Issue by Neskews** [teambit/bit#1262]
## Expected Behavior
The component uses scss when rendering on the platform.

## Actual Behavior
![bildschirmfoto 2018-10-09 um 16 31 21](https://user-images.githubusercontent.com/29442471/46676431-cc917e00-cbe0-11e8-9e8e-e32f7d36e0ab.png)

## Steps to Reproduce the Problem

  1. Add a component with scss styles
  2. Add, tag and export to the platform

## Specifications

  - Bit version: 13.04
  - Node version: 8.11.4
  - npm / yarn version: 6.4.1
  - Platform: MacOSX
  - Bit compiler (include version): bit.envs/compilers/react-typescript@0.0.5
  - Bit tester (include version): "tester": "bit.envs/testers/jest@0.0.34"

**Comment by itaymendel** [comment]
hi, can you share the component with me so I can look at it?
there should not be issues with rendering components with scss, so further debugging is required.

**Comment by Neskews** [comment]
Please have a look at 
[https://bitsrc.io/louho/snabcomponents/inputs/text-field](url)

**Comment by GiladShoham** [comment]
Hi,
Just tried it now on the playground with this code
```js
import React from 'react';
import TextField from '@bit/louho.snabcomponents.inputs.text-field'
export default (<TextField isInvalid="true"/>)
```
It worked with the styles as expected.
If you still have problems please re-open.
