### ISSUE TITLE
[Pre-Sale Question] - Bit and Ionic Pro Deploy

### ISSUE THREAD

**Issue by zachlyon** [teambit/bit#1269]
My company is presently developing a small platform that has a web dashboard and a companion mobile app. We leverage a core codebase that is currently in both projects as a git submodule. This has been OK for development, but when we go to use `ionic deploy` (a service of Ionic Pro to deploy www/dist/build changes to live apps, bypassing AppStore review process), we encounter issues because our git submodule is a private github repo.

My question is, will Bit allow us to share code and eliminate the need for submodules, but still keep the code private. And, has anyone here successfully integrated Bit into Ionic/Angular Typescript with Ionic Deploy?

Thanks guys! Bit looks promising!

**Comment by itaymendel** [comment]
hi @zachlyon , I do not have any past experience with Ionic Deploy, so please take it with a grain of salt.

You can use bit with angular to sync source code of components between repos without git-submodules. Bit is capable of exporting/importing only the source code of the components between projects, and keep the synced source code committed to the each of the git projects.
Given that fact, I assume that Ionic will work just fine, as all relevant code that needs to be deployed can be available in a single git-pull command.

The code can remain fully private, as long as you use a private Bit scope to sync the code between the private repos.

**Comment by zachlyon** [comment]
Thanks @itaymendel - We'll give it a shot and post our findings.
