### ISSUE TITLE
on https://bitsrc.io/bit/docs/content/tutorial: link to "Install bit" is broken

### ISSUE THREAD

**Issue by nmrshll** [teambit/bit#1272]
## Actual Behavior
link to "install bit" (https://bitsrc.io/docs/installing-bit.html) is broken

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Bit version:
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
thanks :)

 i fixed it in the docs repo. it will be deployed soon.
closing the issue.
