### ISSUE TITLE
Karma jasmine test runner feature

### ISSUE THREAD

**Issue by chase2981** [teambit/bit#1277]
Will you please create a Karma => Jasmine test-runner so that I can actually use your platform to build and test my Angular components? Angular2+ has always used Karma => Jasmine as its default test running configuration. My software development manager was actually considering moving forward with your services until I notified him you guys didn't have a test-runner for Karma => Jasmine. (I was the employee pushing for using bitsrc.io in the first place due to its convenience among other things btw)

## Expected Behavior

Default Angular6+ application should be able to be tested using one of your publically available test runners out of the box.

## Actual Behavior

Must change all the tests to Karma => Mocha syntax in order to be able to actually use your platform as it was intended.

## Steps to Reproduce the Problem

  1. Generate a new Angular6+ application using @angular/cli@>=6.0.0 (`ng new my-bitsrcio-app`)
  2. `cd my-bitsrcio-app && bit init`
  3. `bit add src/app/app.component.ts src/app/app.module.ts src/app/app.component.spec.ts src/app/app.component.html src/app/app.component.css` or `bit add src/app/*`
  4. `bit login`
  5. `bit import bit.envs/compilers/typescript --compiler`
  6. `bit import bit.envs/testers/karma-jasmine --tester` -- Oh wait, it doesn't exist!! (The closest available typescript-karma tester can be installed via: `bit import bit.envs/testers/karma-mocha --tester`)
  7. Try and run the default Angular6+ Karma => Jasmine specs using `bit test ...` -- Using any of the publically available bitsrc.io testers...
  8. EPIC FAIL!!!!

## Specifications

  - Bit version: 13.0.4
  - Node version: 9.3.0
  - npm / yarn version: 5.5.1
  - Platform: macOS High Sierra Version 10.13.6 (17G65)
  - Bit compiler (include version): bit.envs/compilers/typescript@0.0.5
  - Bit tester (include version): mia

Thank you!!!!

**Comment by itaymendel** [comment]
hi @chase2981 , you are correct in assuming that all test runners publicly available in Bit should work for all frameworks and workflows. We are still working to improve and keep them up to date, to ensure that it does.

However, at the moment there are still some issues specifically around Angular components. At the moment it is impossible to build/test an Angular component without the context of a project. This is a limitation forced by the Angular compiler. We are trying to workaround it and figure out a solution to the problem.

This does not mean that it's not possible to use Bit with Angular. Just that some of BIt's features are not fully supported. It is still possible to sync source code of components between projects and manage their dependencies.

I'm closing this issue with this note for now, and will update it once a proper solution to isolate Angular components is fully working and GA.
