### ISSUE TITLE
 bit status giving error Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1309]
## Expected Behavior
Should show status

## Actual Behavior
Maximum call stack size exceeded

## Steps to Reproduce the Problem

  1. bit status 

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.11.0
  - npm / yarn version: 6.4.1
  - Platform: MAC OSX Mojave
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@mrkhanakia Thanks for reporting this.
This might happen when you have a workspace with a lot of components or with complex dependencies graph between them.
Fortunately, this already been fixed on master and will be part of the next release.
I'll keep this open until the next release, It would be great if you can check it and report back once the next version released.
Thanks.

**Comment by mrkhanakia** [comment]
I only have one single component lol

**Comment by GiladShoham** [comment]
That's weird, is there a chance you can share the project with me?

**Comment by mrkhanakia** [comment]
Hi Gilad,

Steps to clone and check the project are.
1. git clone https://github.com/mrkhanakia/bitcomp.git
2. yarn install
3. bit status 
Then you will get an error Maximum call stack size exceeded

**Comment by mrkhanakia** [comment]
HI,
1. How it will create a cyclic dependency as i am just importing and exporting the button by default in index.js
2. I took the example form your example movie-app created by teambit itself please check the link
https://github.com/teambit/movie-app/tree/master/src/components/hero-button

If that's the case then how it is working in your @teambit/movie-app ?

**Comment by GiladShoham** [comment]
Hi,
In bit's example, we have index.js which require the button, and the button has the code.
in your project, you have an index with the code and the button which requires himself (which creates a cyclic dep - button -> button -> button).
