### ISSUE TITLE
styled-components + bitsrc.io

### ISSUE THREAD

**Issue by viiralt** [teambit/bit#1310]
## Expected Behavior

Render out components properly

## Actual Behavior

I can export everything to the scope just fine and am using their React build environment with annotations described in the docs, the builds are passing, and it seems to be pulling in styled-components dependency correctly, but when viewing the file it hangs on rendering...

scope @ https://bitsrc.io/sixsigma/test/cells/button

## Steps to Reproduce the Problem

  1. init
  1. build
  1. export to scope

## Specifications

  - Bit version: 13.0.4?
  - Node version: 8.9.4
  - npm / yarn version: 6.4.1
  - Platform: os x mojave
  - Bit compiler (include version): bit.envs/compilers/react@0.0.14
  - Bit tester (include version): N/A

**Comment by KutnerUri** [comment]
_styled-components_ are known not to bundle correctly, and will be fixed in the near release.
You will be able to use _styled_ from the web editor directly and play with the styling live.

It is going to be awesome

**Comment by viiralt** [comment]
out of curiosity, bundling on which end - the styled-components library or users of the library that are creating custom components using styled-components? 

in any case, very much looking forward to it. the idea is to create a custom ui library using styled-components and replace storybook with bitsrc to document/share components across the organisation.

**Comment by KutnerUri** [comment]
You could read about it in more detail here - https://blog.bitsrc.io/introducing-the-live-react-component-playground-d8c281352ee7

Currently version we include _styled-components_ inside the component bundle itself.

In the next release, you will have access to ES6 imports.
This means you would be able to import a component and style it live.
In addition we blacklisted _styled-components_ from being added to the bundle, and fetch it in a separate bundle.

**Comment by viiralt** [comment]
thanks for the update, will be looking forward to the next release then.

**Comment by CyrusZei** [comment]
any update on this?

**Comment by alegadpen-iu** [comment]
Do you have an approximate date for the next release? Thanks in advance

**Comment by nsisodiya** [comment]
is it the reason - my component is not rendering - https://bitsrc.io/rivigo/ui/components/avatar

any fix/hack?

**Comment by KutnerBitsrc** [comment]
A solution is coming soon :)

**Comment by guysaar223** [comment]
@viiralt @CyrusZei  @alegadpen-iu  @nsisodiya  @diemate 
https://bitsrc.io/guyssar/styled-components/button?example=5c596dc8482c5b00137ed5db
