### ISSUE TITLE
React - how to use withTheme and withStyle from material-ui

### ISSUE THREAD

**Issue by mi-mazouz** [teambit/bit#1312]
Hello,

I'm trying to use withTheme and withStyle function from material-ui.

I'm looking for a way to use them functions, what I tried is to import my theme in my component's file and use it like this:

```
   import React from 'react'
   import Button from '@material-ui/core/Button'
   import { withStyles, withTheme } from '@material-ui/core'
   import { muiTheme } from '../styles/theme'

   const classes = (theme = muiTheme) => {
        return {
            color: theme.palette.color
        }
   }

   export default withTheme()(withStyles(classes)(({...props}) => (
      <Button {...props} />
    ))
```

I got an error who say that palette is undefined but even if this method works I'm not exciting by this way because I'm importing my theme only for the rendering on bitsrc.io!

Does anybody have a good way to use correctly material-ui theme?

## Specifications

  - Bit version: v13.0.4
  - Node version: v8.11.1
  - npm version: 5.6.0
  - Bit compiler (include version): react@0.0.14

**Comment by KutnerUri** [comment]
I believe you need ThemeProvider to make this work. Sadly, we don't have dynamic imports in the current playground. The next release will have dynamic ES6 import, so it should work :)

**Comment by GiladShoham** [comment]
@mi-mazouz
This should work with the updated version of the playground.
Please re-open if you have any issue.

**Comment by theshashiverma** [comment]
You should use this
export default withStyles(styles)(withTheme(className));
