### ISSUE TITLE
Buffer deprecated warning

### ISSUE THREAD

**Issue by iAziz786** [teambit/bit#1315]
## Expected Behavior
Shold not show deprecated Buffer warning.

## Actual Behavior
I was following the tutorial about sharing React component with Bit, at the step where you **build your component** I run the command `bit build ui/button` after which I started to see deprecated Buffer warning in my terminal. Exact log:

`(node:14709) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

Why are we using so old way of allocating buffer?

## Steps to Reproduce the Problem

 Just follow the tutorial [here](https://docs.bitsrc.io/tutorial/react-tutorial.html)

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.13.0
  - npm / yarn version: 6.4.1 / 1.12.1
  - Platform: Linux (Ubuntu 18)
  - Bit compiler (include version): react@0.0.14

**Comment by itaymendel** [comment]
@iAziz786 , we're in a process of doing a complete rebuilding of Bit's environments and will take care of such issues during this process.
I'm closing this issue, as this is handled as part of the env-refactoring effort here - https://github.com/teambit/bit-envs
