### ISSUE TITLE
Do i need to push .bit directory to git ?

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1320]
## Expected Behavior
I just see bit create .bit directory should i push it to .git or not ?

## Actual Behavior
I just see bit create .bit directory should i push it to .git or not ?

## Steps to Reproduce the Problem

1. bit init

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.11.0
  - npm / yarn version: 6.4.1
  - Platform: OSX
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
It's better not to commit the `.bit` directory to git.
Read more about it [here](https://docs.bitsrc.io/docs/initializing-bit.html#bit-local-scope).

**Comment by mrkhanakia** [comment]
let say if do not push the .bit directory and i want to clone the project in another Computer so how i will  sync the project to bitsrc repo ?
