### ISSUE TITLE
Removed components still showing https://bitsrc.io/mrkhanakia/uxm/components/order

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1321]
## Expected Behavior
Removed component should not show https://bitsrc.io/mrkhanakia/uxm/components/order

## Actual Behavior
I have removed the component and it is still showing on remote but when i try to remove it local again it gives error bit remove mrkhanakia.uxm/components/order --force 
ERROR: missing components: mrkhanakia.uxm/components/order
So it means it has been already removed but then why it is still showing on live bitsrc
https://bitsrc.io/mrkhanakia/uxm/components/order

## Steps to Reproduce the Problem

  1.  bit remove mrkhanakia.uxm/components/order --force
  1. bit tag --all
  1. bit export mrkhanakia.uxm

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.11.0
  - npm / yarn version:
  - Platform: 6.4.1
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
To remove a remote component you need to add the `--remote` flag to the `remove` command. More info [here]https://docs.bitsrc.io/docs/cli-remove.html#remove-a-component-from-its-remote-scope).

I'm closing the issue, please reopen if you still encounter any issue.
