### ISSUE TITLE
having problem creating build environment with component using material-ui theme and flow

### ISSUE THREAD

**Issue by kevinqs** [teambit/bit#1323]
## Expected Behavior
Using either Babel or flow to create a build environment for Component using material-ui and flow should be successful 

## Actual Behavior
Source code attached.
Error with Babel environmnet creation
<img width="944" alt="screen shot 2018-11-11 at 4 26 27 pm" src="https://user-images.githubusercontent.com/1236704/48320400-af304500-e5ce-11e8-9b9b-8a3509ddb457.png">

Error with Flow environmnet creation
<img width="938" alt="screen shot 2018-11-10 at 11 55 33 pm" src="https://user-images.githubusercontent.com/1236704/48310456-3389b600-e544-11e8-8183-861954d1dcfe.png">

<img width="734" alt="screen shot 2018-11-10 at 11 50 59 pm" src="https://user-images.githubusercontent.com/1236704/48310423-cc6c0180-e543-11e8-9d37-b22bda170222.png">

[Checkbox.txt](https://github.com/teambit/bit/files/2569157/Checkbox.txt)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Bit version:
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
Are you using the environments maintained in bitsrc.io/bit/envs ?
if so - these envs contain their own build configuration which probably needs to be modified by you to fit your project's needs.
there's a quick guide [here](https://discourse.bitsrc.io/t/can-i-modify-a-build-test-environments/28) that instructs on how to do just that, as well as additional info on it.

I'm closing the issue for now.
