### ISSUE TITLE
Bitsrc render 500 server error

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1324]
## Expected Behavior
Component should render
https://bitsrc.io/mrkhanakia/jeoga/auth/loginform

## Actual Behavior
![download](https://user-images.githubusercontent.com/2174170/48311905-a63e7400-e5cc-11e8-828b-537c331bf7c8.png)

## Steps to Reproduce the Problem

  1. Go to the link https://bitsrc.io/mrkhanakia/jeoga/auth/loginform

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.11.0
  - npm / yarn version: 6.4.1
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
This is most likely related to https://github.com/teambit/bit/issues/1325
Please try to export the component again after setting the webpack compiler.
Keeping this open for now.
Please post an update.
Thanks.

**Comment by GiladShoham** [comment]
We will check this and update

**Comment by GiladShoham** [comment]
Looking at the component again, I now see this error: `_Invariant Violation: You should not use <Link> outside a <Router>_`
A quick google search returned this [answer](https://stackoverflow.com/questions/48640280/you-should-not-use-link-outside-a-router) from SO.
I'm not sure that it'll work with the playground, but a possible workaround is to wrap the example with a router.
The upcoming release features an improved playground feature which supports such use cases.

**Comment by mrkhanakia** [comment]
Ok but that's stateless component which i am using in my app and i need LINK component to navigate. So how to achieve it then ?

**Comment by itaymendel** [comment]
The updated playground has been up for a while now. However, the component linked to this issue has been removed. Sadly there's no way to reproduce the issue.
I'm closing the issue as the updated PG supports this use case.
