### ISSUE TITLE
NPM Import: File Not Found

### ISSUE THREAD

**Issue by PatrickGeyer** [teambit/bit#1327]
## Expected Behavior

NPM installs the bit package.
Somehow there seems to be an issue with the .staging directory npm creates when installing packages.

## Actual Behavior
NPM install throws error: 
```
npm i @bit/evolut.shared.shared.get-env

npm ERR! path /Users/mac/Desktop/project/bot/node_modules/.staging/@bit/evolut.shared.shared.pubsub-2c25c0ba/node_modules/@google-cloud/paginator
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/Users/mac/Desktop/project/bot/node_modules/.staging/@bit/evolut.shared.shared.pubsub-2c25c0ba/node_modules/@google-cloud/paginator' -> '/Users/mac/Desktop/project/bot/node_modules/.staging/@google-cloud/paginator-0e93ec2b'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2018-11-11T09_53_46_638Z-debug.log
```

## Specifications

  - Bit version: 13.0.4
  - Node version: 11
  - npm / yarn version: 6.4.1
  - Platform: MacOS High Sierra 10.13.6
  - Bit compiler (include version): Custom (Typescript)
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
Hi @PatrickGeyer 
The error seems to be a result of file/directory permissions issues that npm faces when installing the components, as it does work in other projects (and I've tested it locally with the same npm version as yours).

Is it possible that you ran npm using `sudo`? Alternatively, perhaps one of the files/folders has a different permission scheme?
