### ISSUE TITLE
Can not tag component

### ISSUE THREAD

**Issue by Neskews** [teambit/bit#1329]
## Expected Behavior
Tag component

## Actual Behavior
Component is not tagged

## Steps to Reproduce the Problem

  1. Modify an existing component
  2. Try to tag component

<img width="769" alt="bildschirmfoto 2018-11-12 um 14 32 58" src="https://user-images.githubusercontent.com/29442471/48350590-fdede580-e687-11e8-8166-d1fadd7773d6.png">

## Specifications

  - Bit version: 13.04
  - Node version: 8.11.4
  - yarn version: 1.10.1
  - Platform: MacOSX
  - Bit compiler (include version): bit.envs/compilers/react-typescript@0.0.5
  - Bit tester (include version): bit.envs/testers/jest@0.0.34

**Comment by robbchar** [comment]
I just got the same thing to. The difference being that this is a new component. @Neskews did you figure anything out? The command I used was `bit tag components/nav-bar 0.0.1`.

**Comment by Neskews** [comment]
@robbchar no, I was not able to solve the issue. Me and my team freezed using bit at least until someone from teambit reacts to a couple of the issues.

**Comment by robbchar** [comment]
So, I solved my problem. Kind of obvious now but the error message was not helpful so maybe this will help someone. I have two components nav-bar and nav-bar-item, nav-bar-item is stand alone whereas nav-bar depends on nav-bar-item. My problem was trying to add nav-bar before nav-bar-item, apparently bit has a problem adding something with a dependency if it does not know about that dependency. I did nav-bar-item first and now all is good.

**Comment by Neskews** [comment]
Nice! I'll check back if I can apply your solution on my problem, too.

**Comment by davidfirst** [comment]
The error message has been improved to indicate the situation in this PR: https://github.com/teambit/bit/pull/1377 
It's merged to master and will be part of the next release.

**Comment by GiladShoham** [comment]
@Neskews Can you please check again with the new version of bit - 14.0.0 and post an update?

**Comment by davidfirst** [comment]
Probably irrelevant with the new version v14.1.0.
Please reopen if this is still happening.
