### ISSUE TITLE
Login to Bit service to install private package.

### ISSUE THREAD

**Issue by lubomir-chatoryiskyi** [teambit/bit#1330]
Hello!
I'd like to use your great product in my project but, currently, I'm facing an issue with authentication. The main question is how can I install a private module in an isolated environment (e.g. Docker container)?

**Comment by GiladShoham** [comment]
Hi @lubomir-chatoryiskyi 
You can take look here:
https://discourse.bitsrc.io/t/installing-bit-components-during-ci/17/2
If you need any more help let me know.

**Comment by lubomir-chatoryiskyi** [comment]
@GiladShoham Thanks! It's exactly what I was looking for.
