### ISSUE TITLE
github link does not work

### ISSUE THREAD

**Issue by CyrusZei** [teambit/bit#1334]
## Expected Behavior
when I click on the Github link in the doc it shows "we can't find the page you are looking for"
in the Quick Start and then on the "Example Projects" heading, below that heading there is a link that is broken

## Actual Behavior
when you click on that link it should send you to the github page for bit I think

## Steps to Reproduce the Problem

  1. go to https://docs.bitsrc.io/
  2. scroll down to "Example Projects"
  3. click on the Github url

## Specifications

  - Bit version:
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@CyrusZei , Thanks for reporting this.
Please re-open this issue under the bit-docs repo:
https://github.com/teambit/bit-docs
