### ISSUE TITLE
bit component with sass variables from project

### ISSUE THREAD

**Issue by jeremy-habit** [teambit/bit#1335]
Hello,

I'm trying to outsource a component of my react project. I wanna to extract this component with its scss style sheet but this last one use sass variables from my project. I tryed a lot of compiler from envs bit scope but it didn't work as expect.

## Expected Behavior

The exported bit component has to resolve sass variables from project.

## Actual Behavior

The bit component is imported inside the our Team page, when I run dev the react app from the homepage, and then i navigate to ourTeam from the navbar for example, it's working. I think because the react app is ever compiled with all sass variables, and then the exported component is able to resolve variables. Maybe i'm wrong ... ? HOWEVER, if i reload the page OurTeam, it's over, i get the error : 

Unexpected token .
/Users/jeremyhabit/projects/SMART-DEV/upply/node_modules/@bit/majikkusaru.tictac.ui.content-header/dist/_contentHeader.scss:1
(function (exports, require, module, __filename, __dirname) { .content {
                                                              ^
SyntaxError: Unexpected token .

Thank you !

## Specifications

  - Bit version: 13.0.4
  - Node version: v11
  - npm / yarn version: 6.4.1
  - Platform:
  - Bit compiler (include version): react
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@jeremy-habit 
Does your problem appear on bitsrc playground for the component or in a create react app locally?
If you talk about bitsrc issue, we are about to release a new version of bitsrc soon with many major improvements to the playground.
One of them is upgrading the create react app to v2 which natively support css modules.
All you will have to do is to name your scss file with the name [name].module.scss and it will work.
You can see this (our example project) as reference [movie-app](https://github.com/teambit/movie-app/pull/3)
This is a PR we did for testing and works as expected, it will be merged once we will release the new bitsrc version.

**Comment by cristinallamas** [comment]
Having the same issue when using css variables from an extenal referenced (compiled in webpack) scss file

**Comment by GiladShoham** [comment]
@cristinallamas @jeremy-habit
Can you please provide a component with full steps to reproduce?
We have the same case with movie-app (as described in a previous comment), and it works. 
I need some help to reproduce it.

**Comment by itaymendel** [comment]
SASS files should be handled by the consuming project's bundler.

We'd love to help with resolving this issue, but sadly there are not STRs.
Closing the issue for now. If anyone experiences it, please comment and I'll reopen.
