### ISSUE TITLE
[Feature request] Self-hosted solution

### ISSUE THREAD

**Issue by bugs181** [teambit/bit#1337]
## Expected Behavior
Although I can understand how bit makes money using bitsrc.io hosting, similar to Github, npm, etc - there are those of us with special needs for companies that disallow using external code sharing platforms. Several custom Git servers exist and I don't believe it hurts the bottom line value of Github in any way, similar to npm. 

Personally, I would offer my support for purchasing a license to do self-hosted.

## Actual Behavior
Feature does not exist.

## Steps to Reproduce the Problem
Feature does not exist.

## Specifications

  - Bit version: N/A
  - Node version: N/A
  - npm / yarn version: N/A
  - Platform: OSX/Linux
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by yanneves** [comment]
For anyone else here, the link has moved to https://docs.bit.dev/docs/bit-on-the-server.html 👍

**Comment by stefanotto** [comment]
How would one approach updating such a self hosted instance to the latest Bit version?

**Comment by HarshRohila** [comment]
is self-hosting free for companies?
