### ISSUE TITLE
Can't update the version of React

### ISSUE THREAD

**Issue by AsifYtzhak** [teambit/bit#1339]
Hello,
I’m trying to update my Bit components to use React latest version (16.6.3) but for some reason, it keeps using React 16.2.0.
In my ‘package.json’ file, I have a dependency of:
"react": "^16.6.3"
But when I print the react version inside the component’s render function, it always shows 16.2.0, no matter what version I have in ‘package.json’

I also get an error ‘createContext is not a function’ which is solved in version 16.3.0 and above, and the component is not being rendered correctly because of this error.

My question is how can I update the version of React?

![image](https://user-images.githubusercontent.com/33655604/49307743-cb911480-f4de-11e8-8fa5-b7c3713927e5.png)

## Expected Behavior
The component should be built and rendered using the React version which is specified in 'package.json' (16.6.3)

## Actual Behavior
The component is built and rendered using an older React version (16.2.0), which cause some JS errors

## Specifications

  - Bit version: 13.0.4
  - Platform: Mac OSx
  - Bit compiler (include version): React 0.0.14

**Comment by GiladShoham** [comment]
@AsifYtzhak Thanks for reporting this.
The current version of React in the playground in bitsrc is a static version (16.2.0).
We are working on a new playground with a lot of features and APIs. It will allow you to define the React version for each component's playground.
I'm closing this issue, you will get a notification once a new version of bitsrc will be out.

**Comment by AsifYtzhak** [comment]
@GiladShoham Sounds good.
Thanks for the update.

**Comment by coolemur** [comment]
Hi,

Having same problem. Using quickstart from docs, I have created bit project with default component 
```bit create react apps/to-do --scope my-org.tasks-scope```

When using this component in other project:

```
import { ToDo } from '@my-org/tasks-scope.apps.to-do';

export default function Playground() {
  return (
    <>
      <ToDo>test</ToDo>
    </>
  );
}
```

I am getting error "error - TypeError: react_1.default.createContext is not a function".

I assume this is because react in bit project is v17. Tried update it with installing package with yarn and setting new versions in worskpace.jsonc:

```
      "dependencies": {
        "@teambit/eslint-config-bit-react": "~0.0.367",
        "@typescript-eslint/eslint-plugin": "4.29.3",
        "eslint-import-resolver-node": "0.3.6",
        "eslint-plugin-import": "2.22.1",
        "eslint-plugin-jest": "24.4.0",
        "eslint-plugin-jsx-a11y": "6.4.1",
        "eslint-plugin-mdx": "1.15.0",
        "eslint-plugin-react": "7.25.1",
        "react": "18.2.0",
        "react-dom": "18.2.0"
      },
      "peerDependencies": {
        "@testing-library/react": "^12.1.5",
        "react": "18.2.0",
        "react-dom": "18.2.0"
      }
```

But this doesn't seem to work. Any ideas what else can I try ?
