### ISSUE TITLE
NPM audit issue with bit-bin: Prototype Pollution due to the version of lodash

### ISSUE THREAD

**Issue by rj-david** [teambit/bit#1341]
When I installed bit-bin using npm, I got this npm audit report

> ┌──────────────────────────────────────────────────────────────────────────────┐
> │                                Manual Review                                 │
> │            Some vulnerabilities require your attention to resolve            │
> │                                                                              │
> │         Visit https://go.npm.me/audit-guide for additional guidance          │
> └──────────────────────────────────────────────────────────────────────────────┘
> ┌───────────────┬──────────────────────────────────────────────────────────────┐
> │ Low           │ Prototype Pollution                                          │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Package       │ lodash                                                       │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Patched in    │ >=4.17.5                                                     │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Dependency of │ bit-bin [dev]                                                │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ Path          │ bit-bin > bit-javascript > caporal > cli-table2 > lodash     │
> ├───────────────┼──────────────────────────────────────────────────────────────┤
> │ More info     │ https://nodesecurity.io/advisories/577                       │
> └───────────────┴──────────────────────────────────────────────────────────────┘

**Comment by GiladShoham** [comment]
@rj-david Thanks for reporting this.
We will take care of this.

**Comment by GiladShoham** [comment]
Fixed on master (see https://github.com/teambit/bit-javascript/pull/81)
Closing.
