### ISSUE TITLE
Add options to bit test

### ISSUE THREAD

**Issue by dayze** [teambit/bit#1342]
## Expected Behavior
I can use options like 
```
--updateSnapshot
```
 from jest with the command "bit test".

## Actual Behavior

With a command like 
```
bit test namespace/my-component --updateSnapeshot
```
I get
```
error: unknown option `--updateSnapshot'
```
## Steps to Reproduce the Problem

  1. bit test with any options.

## Specifications

  - Bit version: 13.0.4
  - Node version: v11.0.0
  - npm / yarn version: 6.4.1
  - Platform: Mac OS 10.14.1
  - Bit compiler (include version): custom compiler
  - Bit tester (include version): https://bitsrc.io/bit/envs/testers/jest

**Comment by GiladShoham** [comment]
@dayze Thanks for reporting this.
Passing an argument into the tester / compilers is something we are thinking about. 
We are still in the progress of defining the product of how this should work.
We will keep this issue update.

**Comment by GiladShoham** [comment]
It is not supported at the moment.
We plan to create a new API for extension / compilers / testers which allow passing config/args to an extension.
We will handle the progress of the new API in a new issue.
