### ISSUE TITLE
Bit Commit and Bit Export throws "Error: Cannot find module"

### ISSUE THREAD

**Issue by idkjs** [teambit/bit#135]
Sorry for all the overkill. I love the spirit of this project and thought this detailed error report would help. 
[TLDR: Use recommended npm install on mac](<name="#tldr">)(scroll down to #3rd Attempt, cant get this markdown link to work...)

Machine spec via image:
![screen shot 2017-05-01 at 09 28 31](https://cloud.githubusercontent.com/assets/2370391/25574651/9c1faece-2e50-11e7-8b4b-16592ea30008.png)

## 1st Attempt(didn't work)
Bit installed with brew:
![screen shot 2017-05-01 at 09 38 12](https://cloud.githubusercontent.com/assets/2370391/25574832/fa449784-2e51-11e7-9f07-b084a8744336.png)

While following the [walkthrough](https://teambit.github.io/bit/getting-started.html#create-your-first-code-component) I came upon these errors when running the following commands:
`bit commit is-string 'initial commit'` Note that the commit seems to have been executed successfully despite the error.

![screen shot 2017-05-01 at 09 34 23](https://cloud.githubusercontent.com/assets/2370391/25574754/64d3ac26-2e51-11e7-9a40-df761acc12b0.png)

`bit export @this/is-string @scopy` produces  same directory type error:

![screen shot 2017-05-01 at 09 35 16](https://cloud.githubusercontent.com/assets/2370391/25574770/8714a5e2-2e51-11e7-88ac-b55814143d2c.png)

## Second Attempt(didn't work)
I rm -rf the hello-world and scopy directory and tried the steps again only this time i ran npm init -y on the hello-world dir before running npm i -bit-js because without doing the npm i bit-js installed bit-js one level up. This produced the same result up to this point. Screenshots below:

![screen shot 2017-05-01 at 09 38 12](https://cloud.githubusercontent.com/assets/2370391/25575068/f9ecd5c4-2e53-11e7-9188-1f0f847201bc.png)
![screen shot 2017-05-01 at 09 48 37](https://cloud.githubusercontent.com/assets/2370391/25575067/f9ec17c4-2e53-11e7-9685-acef68184f86.png)
![screen shot 2017-05-01 at 09 49 51](https://cloud.githubusercontent.com/assets/2370391/25575069/f9eded42-2e53-11e7-9b53-bd0bc26ea702.png)
 
## 3rd Attempt(Works!)
[## 3rd Attempt(Works!)](#tldr)
Steps: 
1. rm -rf hello-world and scopy directories.
2. brew remove bit
3. Install bit globally with npm.

![screen shot 2017-05-01 at 10 05 05](https://cloud.githubusercontent.com/assets/2370391/25575463/06964df6-2e58-11e7-808d-3a9a3032ab54.png)

4. Follow getting started instructions, successful `bit commit` which failed previously.
![screen shot 2017-05-01 at 10 09 27](https://cloud.githubusercontent.com/assets/2370391/25575436/bbf9f98c-2e57-11e7-85c5-70db630d3edd.png)

5. I run `npm init` on hello-world so `npm i bit` installs in /hello-world dir instead of parent.
Run `npm init`.
![screen shot 2017-05-01 at 10 31 15](https://cloud.githubusercontent.com/assets/2370391/25575655/96f982d6-2e59-11e7-8b38-9ccf48e9d8f9.png)
Run `npm i bit-js`.
![screen shot 2017-05-01 at 10 31 34](https://cloud.githubusercontent.com/assets/2370391/25575654/96f737ec-2e59-11e7-967c-681d4020559d.png)

6. Creating index.js, `bit commit`. Works. `bit show @this/is-string`. Works.
![screen shot 2017-05-01 at 10 31 59](https://cloud.githubusercontent.com/assets/2370391/25575653/96f295f2-2e59-11e7-9dc0-3b5a7bc28748.png)

7. `bit status`. Works.
![screen shot 2017-05-01 at 10 32 17](https://cloud.githubusercontent.com/assets/2370391/25575652/96efaf04-2e59-11e7-8df4-468e6350c2a1.png)

8.  Create scopy dir for remotes, add remotes, export (`bit remote add`, `bit export`)  commands work. `bit remote add file:///Users/devworx/scopy --global`.
![screen shot 2017-05-01 at 10 41 47](https://cloud.githubusercontent.com/assets/2370391/25575857/f576e00a-2e5a-11e7-8a75-48720f1e0a27.png)

**Comment by itaymendel** [comment]
Epic issue breakdown @idkjs :)
So it seems that the release that was pushed to Brew was missing a file.
Anyway, we've published a [new PR](https://github.com/Homebrew/homebrew-core/pull/13104) to Brew that will fix it.

For now, keep using the NPM, and thanks for not giving up!

I'm keeping this issue open until the new version is published to Brew.

**Comment by neutric** [comment]
@itaymendel You can close this, the new version is in Homebrew.

**Comment by itaymendel** [comment]
thanks @neutric

**Comment by idkjs** [comment]
Glad to help in this minor way. Anyone now how to fix the internal markdown link?
