### ISSUE TITLE
Feature request: ability to associate the version of a component with the version of the project

### ISSUE THREAD

**Issue by renewooller** [teambit/bit#1356]
Currently our team has been experiencing some dependency hell and has been trialing various monorepo solutions. 

When I came across bit, it appeared that it would be a viable alternative to monorepos, as it could  sit on top of any code we already have and provide an easy mechanism for sharing that code between the various code bases.

In particular, we have backend microservice projects that publish packages with type interfaces and generated code and schemas for validation and casting, without any of the other backend specific code in the published package. This means any frontend or other backend that wants to talk to the microservice can simply import the package.  

So on the face of it, it seemed that the packages exported from the microservices good candidates for a bit components. However, on trialling bit, I've found that I need to specify the version of the component manually - it does not pickup the version of the host project, ie the version of the microservice that the component relates to. In reverse, when updating the component from the frontend and publishing so that it can be used by the microservice, I've found that after importing I still need to do a git commit, and update microservice project's package version. This means there is the possibility for human error when versioning the component and the host project. 

So what would be nice is a setting where:
1. strongly link a component to the host project's package version. This means: when an update is done to the component from inside the host project, tagging it by default increments both the version of the host project's package and the component. 
1.1 .Similarly for when the component is modified outside, when it is imported into the host project, the package.json of the host project is automatically updated. 

Does this make sense?

**Comment by GiladShoham** [comment]
@renewooller Thanks for this feedback.
few comments:
You can use the `-s | --scope` flag during bit tag which will tag all the components in the local scope with the specified version. You can very easily pipe it with reading the package.json file and fetch the version. something like `cat package.json | jq .version` and input it to the tag command.

another option is to move the tag/export process into your CI machine, which will detect changes in your package.json version and do tag and export if it was changed. This will be more consistent.

For my opinion this process usually makes sense when your repo is a library repo, like bootstrap or lodash, when you usually just export component from this repo and not import into it.

In your case of microservices, you have to think about different cases, for example, if you import a 3rd party component in different version what will happen to your package.json version.
What if you have different components with different versions.
What if you import a component with version lower than your host.

I'm not saying it's not possible but you should probably define a more comprehensive rule system for this.
Probably the best way to do it is to implement a bit extension which registers to post-import and post tag actions (or post-export) and properly set the package.json version.
You can read more about it on [registering-an-action-to-a-hook](https://docs.bitsrc.io/docs/ext-developing-extensions.html#registering-an-action-to-a-hook)
This is a perfect use case for a bit extension which perform all the rules you defined.
(We are going to dramatically improve the extensions API soon, and it might introduce some breaking changes, so keep it in mind)

Would like to hear your feedback about it.
