### ISSUE TITLE
Bit Component w/partial typescript

### ISSUE THREAD

**Issue by michaelryancaputo** [teambit/bit#1360]
## Expected Behavior

I'm slowly going to be implementing Typescript into some of our projects. Currently doing this by adding the `tsx` extension onto files that contain Typescript. I converted one file (not all) in my component's folder to the TSX and am receiving no errors. However, if I export the component into bit using the compiler set up in my `bit.json` file, my non `tsx` files are being compiled the way a React (or other components) that I use.

## Actual Behavior

After adding the Typescript compiler, my "non-typescript" components are not being compiled the way I would expect them to, and thus are causing issues with importing the component into projects.

## Steps to Reproduce the Problem

  1. Create a bitsrc component that includes a `tsx` and regular `js` file
  2. Use the bitsrc typescript compiler
  3. Export the component, and import into a new project via `NPM`
  4. The new project will produce an error: ```You may need an appropriate loader to handle this file type.```

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.11.1
  - npm / yarn version: Yarn 1.12.3
  - Platform: OSX
  - Bit compiler (include version): `bit.envs/compilers/react-typescript@0.0.5`
  - Bit tester (include version): `bit.envs/testers/jest@0.0.32`

**Comment by GiladShoham** [comment]
@michaelryancaputo The react-typescript compiler is deprecated.
Please use https://bitsrc.io/bit/envs/compilers/typescript.
It also supports react / tsx files and it won't compiler .js files.
Let me know if you need more help

**Comment by davidfirst** [comment]
Probably an old bug, it looks fine now.
I created a file with the following:
```
export default () => {
  <svg
    xmlns="http://www.w3.org/2000/svg">
  </svg>
}
```
saved as a new component and built it using `bit.envs/compilers/typescript`, no issues were found.

**Comment by GiladShoham** [comment]
@michaelryancaputo Please note that the [react-typescript](https://bit.dev/bit/envs/compilers/react-typescript) has a newer version (3.0.0) which is not deprecated any more (you will still get the warning about deprecation, that's because we still didn't remove the deprecation label)
