### ISSUE TITLE
 wrong require path to component in dist

### ISSUE THREAD

**Issue by ghost** [teambit/bit#1373]
If I import module by traversing directories like:
```
src
  components
     Button.js
  core
    helper.js
```
And in Button.js component importing helper like so:
```js
import helper from '../../src/core/helper';
```
instead of:
```js
import helper from '../core/helper';
```

## Expected Behavior
should generate dis with require like:
```
var _helper = require('../core/helper');
```

## Actual Behavior
This will generate wrong require path to component:
```
var _helper = require('../../src/core/helper');
```

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.15.0
  - npm / yarn version: 6.4.1 / 1.12.3
  - Platform: Linux (Ubuntu)
  - Bit compiler (include version): bit.envs/compilers/react@0.0.14
  - Bit tester (include version): bit.envs/testers/jest@0.0.35

**Comment by GiladShoham** [comment]
@vyteniskuciauskas-home24 Thanks for reporting this. You are correct. This is a bug and we will address it.

**Comment by vyteniskuciauskas-home24** [comment]
There is no reason just a mistype. In normal situation it's still correct path, but result are wrong. As I understood bit in documentation is missing some page at https://docs.bitsrc.io/docs/faq-component-dependencies.html#custom-module-resolution is pointing to 404 page https://docs.bitsrc.io/docs/docs/troubleshooting-isolating.html#configuring-custom-module-resolution

But using `path.resolve()` would help and it's not a bad idea to change paths to files.

**Comment by itaymendel** [comment]
resolved with v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
