### ISSUE TITLE
SVG are supported?

### ISSUE THREAD

**Issue by zabaala** [teambit/bit#1379]
Hi,

I'm trying start to work with the bit. I've created my components, but one of them import a SVG and when i try import him in another project, the follow error is returned:

```
no template was found for ../../../../../images/svg/rolling.svg, because .svg extension is not supported
```

What's wrong?

**Comment by GiladShoham** [comment]
@zabaala Thanks for reporting.
Currently, on the npm version, you can't make a component with the main file that is SVG.
This issue already been resolved in master, and will be part of the next version.
Meantime you can add an index.js file which exposes this SVG.
