### ISSUE TITLE
Mobile Site - scaling and z-index

### ISSUE THREAD

**Issue by joestrouth1** [teambit/bit#138]
When browsing bit / utils on bitsrc.io, the layout does not properly scale to my viewport. Using an LG V10 with Chrome 57 and Android 6.
The hamburger menu drop down also renders below the cards, obstructing the view of its options. See screenshot: 
![screenshot_2017-05-02-07-22-38](https://cloud.githubusercontent.com/assets/644238/25617639/ebb87200-2f08-11e7-9909-f111cf304f32.png)

**Comment by itaymendel** [comment]
hi @joestrouth1, sorry for the late response.
thanks for letting us know about this issue, and providing all the details needed to recreate it :)

we are currently working on fixing mobile support for the bitsrc.io website across the board.
i will close this issue when scope page is more mobile friendly.

**Comment by itaymendel** [comment]
issue resolved in the last update for the site.
