### ISSUE TITLE
Using components without node_modules and dist folders

### ISSUE THREAD

**Issue by necatiozmen** [teambit/bit#1381]
## Expected Behavior
Using components without node_modules  and dist folders.

## Actual Behavior
Let' s assume that I import LoginPage component from scope to project.
Folder structure look like this after import : 

```
--Components
 --LoginPage
   --dist
   --index.js
   --node_modules
   --package.json 
```
İs there any way to use imported components without including node_modules and dist in LoginPage folder ? 

Should I have to delete the node_modules and dist manually every time if I don't want to have it in LoginPage folder ?

## Specifications

  - Platform: react-typescript
  - Bit compiler (include version): bit.envs/compilers/typescript@0.0.5

**Comment by itaymendel** [comment]
there are a few flags you should use to do just that:

`bit import <component id> --skip-npm-install --ignore-dist`
