### ISSUE TITLE
Is there a way to ignore package import.

### ISSUE THREAD

**Issue by lubomir-chatoryiskyi** [teambit/bit#1382]
Hello
My example: I have a module (Vue component) I'd like to share between my projects. This module has his own CSS styles (I'm using Less, or SASS doesn't matter) with variables and import of this file is included in my styles as alias e.g. `@import '@variables'`. Each project has his own variable's values and I'd like to use them. 
When I tried to run `bit status` I saw a warning `missing packages dependencies` that told me that I must include file with variables in module dependencies. But I want to use a global file.
Is there a way to exclude this import from module dependencies or another way to handle it somehow? 
Thanks in advance.

**Comment by itaymendel** [comment]
You can have Bit ignore untracked dependencies. Use the `--ignore-missing-dependencies` flag in the `bit tag` command.
