### ISSUE TITLE
Tests passed on local but failed to build

### ISSUE THREAD

**Issue by eddeee888** [teambit/bit#1384]
## Context

Is it normal to be able to pass tests on local but when exported? It also mentions [here](https://docs.bitsrc.io/docs/cli-tag.html#tagging-and-tests) that all tests must pass to successfully tag. I have created, tested then exported a simple component but it keeps failing on remote repo

## Expected Behavior

- Testing should be the same for local vs remote scope

## Actual Behavior

- Tests passed on local

<img width="483" alt="screen shot 2019-01-21 at 10 57 37 pm" src="https://user-images.githubusercontent.com/33769523/51473315-2bfe4d00-1dd0-11e9-92bc-9f30ccdad692.png">

- Failed on remote scope

<img width="1247" alt="screen shot 2019-01-21 at 10 58 48 pm" src="https://user-images.githubusercontent.com/33769523/51473329-3587b500-1dd0-11e9-9efd-03b36784cc56.png">

## Steps to Reproduce the Problem

1. Create file + test file
2. Add compiler and test
3. Add component: `bit add src/forms/validations/emailValidation.ts -t 'src/forms/validations/emailValidation.test.ts' --id forms/validations`
4. Tag component: `bit tag forms/validations 0.0.1 --message "Add email validation"`
5. Export component: `bit export <scopename>`

## Files

.bitmap

```
{
    "eddeee888.learnd-utils/forms/validations@0.0.1": {
        "files": [
            {
                "relativePath": "src/forms/validations/emailValidation.test.ts",
                "test": true,
                "name": "emailValidation.test.ts"
            },
            {
                "relativePath": "src/forms/validations/emailValidation.ts",
                "test": false,
                "name": "emailValidation.ts"
            }
        ],
        "mainFile": "src/forms/validations/emailValidation.ts",
        "origin": "AUTHORED"
    },
    "version": "13.0.4"
}
```

bit.json

```
{
    "env": {
        "compiler": "bit.envs/compilers/typescript@0.0.5",
        "tester": "bit.envs/testers/jest@0.0.35"
    },
    "dependencies": {},
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "yarn"
}
```

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.13.0
  - npm / yarn version: 1.9.2
  - Platform: Mac OS 10.14.2 (Mojav)
  - Bit compiler (include version): bit.envs/compilers/typescript@0.0.5
  - Bit tester (include version): bit.envs/testers/jest@0.0.35

**Comment by davidfirst** [comment]
@eddeee888 , thanks for the detailed info.
In most cases, yes, your local and the remote CI should behave the same. However, in the current version the tests you run locally rely on your workspace configuration and not on Bit configuration. 
So, it's possible that the tests pass on your local but fail on the remote. You can also try importing your components on another directory and test them there, it'll fail with the same error you got from the remote.
We are working on a solution to fix this by having the same procedure on the local and on the remote. 

According to your specific error, it seemed to me that the `await` wasn't used correctly. Eliminating entirely the `async/await`, fixes the issue. Probably the function doesn't return a Promise.

Here is the fixed version of the tests:

import email from './emailValidation';
```
describe('emailValidation()', () => {
  const valid = 'abc@gmail.com';
  const invalidWrongFormat = 'asdsadasd';

  it('emailValidation - valid', () => {
    expect(email.validate(valid)).resolves.not.toThrow();
    expect(email.validate(valid)).resolves.toBe(valid);
  });

  it('emailValidation - invalid: wrong email format', () => {
    expect(email.validate(invalidWrongFormat)).rejects.toThrow();
  });

  it('emailValidation - invalid: no email', () => {
    expect(email.validate(undefined)).rejects.toThrow();
  });

  it('emailValidation - invalid: empty string', () => {
    expect(email.validate('')).rejects.toThrow();
  });
});
```

**Comment by eddeee888** [comment]
Thanks for the explanation! 

Eliminating `async/await` passed but it's because the async errors are not caught in jest (version 23.x in this case). In this particular example, if the email passed in is `abcgmail.com`, the test would still pass, which is not what we want.

I went and look again at [how to test promises using async/await](https://jestjs.io/docs/en/23.x/asynchronous#async-await). I can confirm `async/await` does not work on remote as of now. 

So to test promises, we can use the [non async/await syntax](https://jestjs.io/docs/en/23.x/asynchronous#resolves-rejects) like following:

```
import email from './emailValidation';

describe('emailValidation()', () => {
  const valid = 'abc@gmail.com';
  const invalidWrongFormat = 'asdsadasd';

  it('emailValidation - valid', () => {
    expect.assertions(1);

    return expect(email.validate(valid)).resolves.toBe(valid);
  });

  it('emailValidation - invalid: wrong email format', () => {
    expect.assertions(1);

    return expect(email.validate(invalidWrongFormat)).rejects.toThrow();
  });

  it('emailValidation - invalid: no email', () => {
    expect.assertions(1);

    return expect(email.validate(undefined)).rejects.toThrow();
  });

  it('emailValidation - invalid: empty string', () => {
    expect.assertions(1);

    return expect(email.validate('')).rejects.toThrow();
  });
});
```
