### ISSUE TITLE
Custom Alias in bit.json instead of @

### ISSUE THREAD

**Issue by cristinallamas** [teambit/bit#1389]
Is there a way to add a different alias from '@' let's say 'Atoms'

"Atoms": "src/components/atoms",

Which has an index.js importing/exporting components to then be able to do

import { Heading, Image, Text } from 'Atoms';

The documentation is missing info and examples so I'm not sure

## Expected Behavior

```
      "aliases": {
        "Atoms": "src/components/atoms",
        "Molecules": "src/components/molecules",
        "Helpers": "src/components/helpers"
      }
```

## Actual Behavior

```
      "aliases": {
        "@": "src/components",
      }
```

then i get error:

resolve 'Atoms' in 'component-library/src/components/helpers/renderContent'
  Parsed request is a module
  using description file: component-library/package.json (relative path: ./src/components/helpers/renderContent)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      component-library/src/components/helpers/renderContent/node_modules doesn't exist or is not a directory

## Steps to Reproduce the Problem

  1. Add and alias Atoms pointing to a folder with an index.js exporting components
  1. use `import { Heading, Image, Text } from 'Atoms';`
  1. bit tag --all

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.8.0
  - npm / yarn version: 1.9.4
  - Platform: OSX
  - Bit compiler (include version):  webpack@0.0.13
  - Bit tester (include version): jest@0.0.35

**Comment by davidfirst** [comment]
@cristinallamas , you can use `Atoms` as an alias. In the docs, the `@` alias is just an example.

When you create the component in the first place, you have to configure the aliases with your own settings, such as Webpack or Babel resolver plugin.
The configuration for Bit is in addition to what you have already, so then, when consuming your components in a different environment, Bit will know how to mimic your module resolution.
