### ISSUE TITLE
Webpack bundler failed to compile component

### ISSUE THREAD

**Issue by pniedzwiedzinski** [teambit/bit#1390]
## Expected Behavior
I am working on react app with typescript and scss-loader. Everything is wrapped with webpack, so I want webpack bundler to compile component.

## Actual Behavior
Got ModuleNotFoundError, probably because of the fact that I am importing "./Subject" instead of "./Subject.tsx". I am also wondering where is webpack configuration for this bundler? I don't know if I am getting this right, I couldn't anything in documentation.

## Steps to Reproduce the Problem
Here's my component: https://bitsrc.io/pniedzwiedzinski/lesson-plan/components/subject/code#components/Subject/index.ts
  1. `bit import bit.envs/bundlers/webpack -c`
  2. `bit build components/subject` - that works for me, I don't know how you will be doing this

## Specifications

  - Bit version: 13.0.4
  - Node version: 11.7.0
  - npm / yarn version: 6.5.0
  - Platform: MacOS
  - Bit compiler (include version): bit.envs/bundlers/webpack@0.0.13
  - Bit tester (include version): none

**Comment by davidfirst** [comment]
@butterfly-pn , I'm unable to see your component. Is it public? if not, please add me as a collaborator. (david@bitsrc.io).

**Comment by butterfly-pn** [comment]
Should work now 
https://bitsrc.io/pniedzwiedzinski/lesson-plan/components/subject

**Comment by itaymendel** [comment]
issue resolved with v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
