### ISSUE TITLE
"bit init" fails due to missing file "bit-bin/node_modules/fs-extra/lib/index.js" in global .config

### ISSUE THREAD

**Issue by billhannah** [teambit/bit#1391]
## Expected Behavior
bit commands work

## Actual Behavior
calling `bit init` fails with message:
```
ENOENT: no such file or directory, open '/Users/billh/.config/yarn/global/node_modules/bit-bin/node_modules/fs-extra/lib/index.js'
```
calling `ls -a ~/.config/yarn/global/node_modules/bit-bin/node_modules` returns:
```
.	..	.bin	is-glob
``` 

## Steps to Reproduce the Problem

  1. call `yarn global add bit-bin`
  2. cd into project directory
  3. call `bit init`

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.12.0
  - npm / yarn version: yarn v.1.13.0, npm v.6.5.0
  - Platform: MacOS
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by davidfirst** [comment]
I'm unable to reproduce the error. I tried with the same node and Yarn versions.
Maybe it's a local issue. Try to uninstall and reinstall it. (I would make sure that after you uninstall it, `/Users/billh/.config/yarn/global/node_modules/bit-bin` is empty).

**Comment by davidfirst** [comment]
@billhannah , I'm unable to see your component. Is it public? if not, please add me as a collaborator. (david@bitsrc.io).

**Comment by billhannah** [comment]
Today I was reading the docs and tried running `bit clear-cache` - that solved the problem. It's working fine again.
