### ISSUE TITLE
Component not rendering

### ISSUE THREAD

**Issue by nsisodiya** [teambit/bit#1396]
## Expected Behavior
https://bitsrc.io/rivigo/ui/components/avatar
Please check the code, why it is not rendering?

## Specifications

  - Bit version: 13.0.4
  - Node version: v11.7.0
  - npm / yarn version: 6.5.0
  - Platform: MacOS
  - Bit compiler (include version):
  - Bit tester (include version):

```json
{
    "env": {
        "compiler": "bit.envs/compilers/react@0.0.14"
    },
    "dependencies": {},
    "componentsDefaultDirectory": "src/components/{namespace}/{name}",
    "packageManager": "npm"
}
```

**Comment by nsisodiya** [comment]
Is this issue related? https://github.com/teambit/bit/issues/1310

**Comment by vyteniskuciauskas-home24** [comment]
You got an error in your component
```Uncaught TypeError: Object(...) is not a function```

**Comment by GiladShoham** [comment]
@nsisodiya Please try to fix your component as suggested above, then try again with the new version of bitsrc.

**Comment by GiladShoham** [comment]
Closing for in-activity. 
If the issue persists, please re-open.
