### ISSUE TITLE
[Tester] Add tester to existed component  

### ISSUE THREAD

**Issue by diemate** [teambit/bit#1398]
## Component Info

<img width="536" alt="screenshot 2019-01-25 at 14 55 24" src="https://user-images.githubusercontent.com/4847820/51750060-44f94d80-20b1-11e9-8d89-b9460da08925.png">

I already had a component defined and tracked by Bit, but now I've imported a tester 
`bit import bit.envs/testers/jest -t` 
But when I try to execute `bit test` it is shouting because it does not have a tester for my component 
`tester for component: components/header@1.0.2 is not defined`

For the cases where I haven't defined an environment on before hand, how can I update the component to have the tester as it has the compiler? 

Thanks in advance!

**Comment by davidfirst** [comment]
@diemate , I was trying to reproduce your case.
At first, without importing a tester, I got the error `tester for component: jjj/a@0.0.1 is not defined`.
Once I imported the tester, I got a different error `tests are not defined for component: jjj/a@0.0.1`, which indicates that I simply didn't write tests to that component. 
Are you sure you get the first error and not the second?
If so, please run `cat bit.json` from your workspace root and make sure you see your tester there.

**Comment by diemate** [comment]
Hi @davidfirst, thank you very much for your answer. 
Here's my `bit.json`
```
{
    "env": {
        "compiler": "bit.envs/compilers/react@0.0.14",
        "tester": "bit.envs/testers/jest@0.0.35"
    },
    "dependencies": {
        "myScope/components/header": "1.0.4"
    },
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "npm"
}
```
And yes, I'm getting
```
$ bit test components/header
>>> tester for component: components/header@1.0.4 is not defined
```
Should I run anything extra in order to indicate my component it has to use the tester I've imported?

**Comment by diemate** [comment]
Hello, 
I've made some progress but now Jest is failing. Maybe I'm missing something in the conf.
```
➜ $ bit add src/common/components/header/ -t 'src/common/components/header/__tests__/HeaderTest.js' --id header
tracking component global/header:
added src/common/components/header/Header.js
added src/common/components/header/README.md
added src/common/components/header/__tests__/HeaderTest.js
added src/common/components/header/index.js
➜  $ bit test
global/header
tests failed
file: src/common/components/header/HeaderTest.js


❌   Jest failure
    Command failed: "/usr/local/Cellar/node/11.5.0/bin/node" /Users/diego/repos/myProject/.git/bit/components/testers/jest/bit.envs/0.0.35/node_modules/jest/bin/jest.js /Users/diego/repos/myProject/dist/src/common/components/header/HeaderTest.js --rootDir=/Users/diego/repos/myProject/dist/src/common/components/header --config=/Users/diego/repos/myProject/.git/bit/components/testers/jest/bit.envs/0.0.35/dist/jest.config.js --json --outputFile="HeaderTest-results.json"
No tests found
In /Users/diego/repos/myProject/dist/src/common/components/header
  2 files checked.
  testMatch:  - 2 matches
  testPathIgnorePatterns: /node_modules/,/.git/ - 2 matches
  testRegex: (/__tests__/.*|\.(test|spec))\.(ts|tsx|js|jsx)$ - 0 matches
Pattern: /Users/diego/repos/myProject/dist/src/common/components/header/HeaderTest.js - 0 matches
 `"/usr/local/Cellar/node/11.5.0/bin/node" /Users/diego/repos/myProject/.git/bit/components/testers/jest/bit.envs/0.0.35/node_modules/jest/bin/jest.js /Users/diego/repos/myProject/dist/src/common/components/header/HeaderTest.js --rootDir=/Users/diego/repos/myProject/dist/src/common/components/header --config=/Users/diego/repos/myProject/.git/bit/components/testers/jest/bit.envs/0.0.35/dist/jest.config.js --json --outputFile="HeaderTest-results.json"` (exited with error code 1)t/jest.config.js --json --outputFile="HeaderTest-results.json"` (exited with error code 1)

```

It seems like Jest is looking for the __tests__ folder but it doesn't find it although, apparently, everything was added successfully.

**Comment by diemate** [comment]
Ok, I haven't seen this `testRegex: (/__tests__/.*|\.(test|spec))\.(ts|tsx|js|jsx)$ - 0 matches` my bad 😅 

Now my tests are working!
