### ISSUE TITLE
Unable to save Version object, the flattenedDependency __ does not have a version

### ISSUE THREAD

**Issue by cameron-yee** [teambit/bit#1399]
## Expected Behavior
Component should be tagged.

## Actual Behavior
Receiving error message when running: bit tag --all

I have a component that imports a svg component.  I am using the babel-plugin-inline-react-svg plugin for Babel.  This converts imported svg files such as:

```javascript
import React from 'react';
import CloseSVG from './close.svg';
 
const MyComponent = () => <CloseSVG />;
will be transformed into...

import React from 'react';
const CloseSVG = () => <svg>{/* ... */}</svg>;
 
const MyComponent = () => <CloseSVG />;
```

  My .babelrc looks like:

```json
{
  "presets": ["next/babel"],
  "plugins": ["inline-react-svg"]
}
```

I can successfully add the component to be tracked by Bit, but when I try to tag it, I get this error message:

unable to save Version object, the flattenedDependency <[NAMESPACE]/[COMPONENT_NAME]> does not have a version. This error should have never happened. Please open a new Github issue with the bug details

## Steps to Reproduce

1. Set up a Next JS project
2. Initialize a Bit workplace
3. Add a component that imports a svg file
4. Try to tag the component

## Specifications

  - Bit version: 13.0.4
  - Node version: v9.11.1
  - npm / yarn version: 6.5.0
  - Platform: Next JS (v7.0.2)
  - Bit compiler (include version): react (bit.envs/compilers/react@0.0.14)

**Comment by davidfirst** [comment]
This error usually indicates tagging a component without its dependencies, so using `--all` flag should eliminate it, which is not the case in your project.
The SVG file was added to the same component or you have a new component for it? if it's a new component when you run `bit status` do you see both as new components, or only one of them?

**Comment by cameron-yee** [comment]
The SVG file is imported in the component that I'm trying to tag.  The babel plugin converts the SVG file import into a react component.  I ran bit install so all the dependencies should be installed.  When I run bit status I only see the one component, not the SVG file.

**Comment by davidfirst** [comment]
Sounds like a bug, and I would like to look into it, but I'm not sure I follow. 
Before you manually tagged the SVG file, you didn't see the component in `bit status` and I'm wondering why. 
Basically, you should see there all the components you added but not tagged under "new components". So, just to make sure, did you add the SVG file (using `bit add`) as a component? or did you add the SVG file as part of the original component?

**Comment by cameron-yee** [comment]
I added the SVG file as a separate component using bit add.  Then doing bit status, the SVG component didn't show up.  I'm also importing the SVG file as an ES6 import in the original component.  Would that be messing it up?

**Comment by GiladShoham** [comment]
@cameron-yee Please try with the new version of bit (14.0.0). We fixed a lot of issues. An update after trying with the new version will be great. Thanks.

**Comment by cameron-yee** [comment]
Updating to bit 14.0.0 seemed to work.  I ran the same thing and it tagged successfully.
