### ISSUE TITLE
bit init fails in a TypeScript  project

### ISSUE THREAD

**Issue by krszwsk** [teambit/bit#1401]
## Expected Behavior
`bit init` initialises a workspace in a TypeScript project.

## Actual Behavior
`bit init` crashes with:
```
Failed loading the driver for javascript. Got an error from the driver: Error: ENOENT: no such file or directory, open '/Users/<user>/.config/yarn/global/node_modules/typescript-eslint-parser/parser.js'
```

## Steps to Reproduce the Problem

  1. Create a React project that uses typescript.
  2. Run `bit init`

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.11.1
  - yarn version: 1.10.1
  - Platform: macOS 10.14.2 Mojave
  - Bit compiler (include version):
  - Bit tester (include version):

## Solution

`yarn global add typescript-eslint-parser`. This is not ideal, since `typescript-eslint-parser` is deprecated.

**Comment by davidfirst** [comment]
Thanks for opening the issue. 
I created a [PR](https://github.com/teambit/bit-javascript/pull/84) to replace the deprecated `typescript-eslint-parser` with `@typescript-eslint/typescript-estree`.
I'll update once merged.
