### ISSUE TITLE
Protected Components 

### ISSUE THREAD

**Issue by reactiongears** [teambit/bit#1405]
## Expected Behavior
As an administrator, I would like to be able to protect components from `bit remove --remote` so that if developers try to run the command it will fail with a warning message.

## Actual Behavior
Currently, developer roles can run `bit remove --remote` on a component and if it's not a dependency if any other component that component and it's history will be gone forever.

## Steps to Reproduce the Problem

  1. Create a Component
  2. bit tag and export 
  3. bit remove --remote

## Specifications

  - Bit version: 13.0.4
  - Node version: 8.12.0
  - yarn version: 1.13.0
  - Platform: Macbook Pro

**Comment by GiladShoham** [comment]
@reactiongears This is a great feature. Thanks.
We will add it to our backlog.
