### ISSUE TITLE
https://node.bitsrc.io is offline!

### ISSUE THREAD

**Issue by DoubleHub** [teambit/bit#1407]
Title is quite self-explanatory. Since that server is offline, I cannot install my bit dependencies on my Docker image since they rely on that being online.

Can you look onto it? Thank you

**Comment by DoubleHub** [comment]
For now, as a bandaid I'm manually using bit import command so I can have my library files ready offline, but I would actually like to rely on that server instead!

**Comment by itaymendel** [comment]
hi @DoubleHub , the issue was fixed a few minutes ago.
for prod issues, it's better to contact directly via email.
