### ISSUE TITLE
React component and styles

### ISSUE THREAD

**Issue by diemate** [teambit/bit#1409]
Hello,

I've just started to work with Bit but I'm missing some documentation about how the platform renders the components using the @example in the Jsdoc. I've seen some example of components https://bitsrc.io/bit/movie-app/ but I miss some guidelines about what is supported and what is not or how you have to develop your components in order to have them ready for rendering in the platform.

What's style way is recommended for React application in order to see the render example working on the platform? Because I've read at #1310 that styled-components is not supported yet, but I've exported a different component importing my `scss` file into the component, and I don't see the style on the documentation page. 

## Specifications

  - Bit version: 13.0.4
  - Bit compiler (include version): bit.envs/compilers/react@0.0.14
  - Bit tester (include version): bit.envs/testers/jest@0.0.35

**Comment by diemate** [comment]
Hi @GiladShoham 
I've had a look into the new web, and it looks really good! Congratulations. 

But sometimes I have problems with the example compiler. For instance, I'm writing an example for one of my components and sometimes I receive this message `Module not found: You seem to be requiring a package ("@bit/diego.myPrivateScope.components.header") which can't be installed` As you can see, my scope is a private one, but I think it shouldn't be a problem since I'm writing the example from the own component page itself. The problem is that it isn't a constant error, sometimes it works fine. Any ideas?

**Comment by GiladShoham** [comment]
@diemate Thanks for reporting this.
We are aware of this issue, and I'm personally working on this issue as we speak.
This does not relate to the fact that your component is private.
I hope it will be fixed in about a week (along with major performance improvements).

**Comment by GiladShoham** [comment]
@diemate We have updated the playground a few days ago.
Please re-open if the issue still occurs.

**Comment by diemate** [comment]
Thank you for the update @GiladShoham :D 👍
