### ISSUE TITLE
bit add, status and remove does not work as expected?

### ISSUE THREAD

**Issue by jasir** [teambit/bit#1413]
## Expected Behavior

bit status is working, bit remove is working

## Actual Behavior

bit status says

```
invalid components
these components were failed to load.

     > utils/array-utils ... component files were deleted (use "bit remove [component_id]" to remove the component from your workspace)
```

then executing suggested:

`bit remove lib/utils/array-utils`: -> `missing components: lib/utils/array-utils`
or
`bit remove utils/array-utils` -> missing components: utils/array-utils

## Steps to Reproduce the Problem

  1. bit init
  2. bit add --id `'lib/utils/array-utils' ./src/lib/utils/arrayUtils.js --tests './src/lib/utils/__test__/{FILE_NAME}.spec.js'`
  3. bit status -> says removed
  4. bit remove - > component missing

## Specifications

  - Bit version: 13.0.4
  - Node version: v10.14.2
  - npm / yarn version: 6.4.1 / 1.12.3
  - Platform: Windows 10, 64bit
  - Bit compiler (include version): ?
  - Bit tester (include version): ?

**Comment by GiladShoham** [comment]
@jasir Please try again with the new version of bit - 14.0.0.
The correct syntax is `bit remove utils/array-utils`.
Let us know if it still doesn't work.

**Comment by jasir** [comment]
Thanks, worked!
