### ISSUE TITLE
Does the "Overview" tab supports VueJS components?

### ISSUE THREAD

**Issue by lubomir-chatoryiskyi** [teambit/bit#1417]
Hello!
Thanks for the great update, really like a new UI.
A question regarding VueJS components and the "Overview" tab. Do Editor and Preview frame support  VueJS components? Currently, I see an error 
`Invalid DOM property class. Did you mean className?`
As I understand component was parsed as React component...
BTW, Vue was set as component bundler

**Comment by GiladShoham** [comment]
Hi @lubomir-chatoryiskyi 
Right now we bitsrc doesn't support rendering of Vue components. However, with the new architecture of the rendering feature, it is much more simple to support other libraries.
We are working on Vue support and hopefully will be able to release it soon. I don't have an exact timeline right now, but I'll keep this issue updated.

**Comment by itaymendel** [comment]
The updated status for the Vue project is in [this issue](https://github.com/teambit/bit/issues/1152).

**Comment by itaymendel** [comment]
YES it does!
please see updates on the #1152 

closing this one
