### ISSUE TITLE
`bit` version 14.0.0 not available on Homebrew

### ISSUE THREAD

**Issue by michaelryancaputo** [teambit/bit#1420]
## Expected Behavior
I should be able to install the same version of bit as is available on NPM through homebrew

## Actual Behavior
The most up to date version of bit available through homebrew is 13.0.4

## Steps to Reproduce the Problem

  1. type `brew install bit` - version `13.0.4` is installed.

## Specifications

  - Bit version: `13.0.4`
  - Node version: `v10.13.0`
  - npm / yarn version: Yarn `1.12.3`
  - Platform: OSX
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by itaymendel** [comment]
we have created a PR to brew's registry with the updated version.
waiting for it to be approved.

keeping this issue open until brew accepts the PR.

**Comment by itaymendel** [comment]
Bit 14 is available on brew
