### ISSUE TITLE
Bit status suggest to delete not existing components

### ISSUE THREAD

**Issue by JEricaM** [teambit/bit#1422]
## Expected Behavior
I expect that bit status don't suggest me to remove not existing components from my workspace.

## Actual Behavior
The command bit status suggest me to remove a component from my workspace but the components don't exists. 

![senza titolo 2](https://user-images.githubusercontent.com/9347586/52336316-e1521700-2a04-11e9-9e38-96f4f9c306c6.png)

That component is not present on my workspace anymore, neither on my scope. 
Infact if I do like like it's suggested, the CLI tell me that the component it's missing.

![senza titolo 3](https://user-images.githubusercontent.com/9347586/52336462-46a60800-2a05-11e9-9cf9-472a764e1bb9.png)

This happens also with other components that are not anymore in my bit account (because I've deleted the collections or the components).  

Maybe I did not understand how to permanently delete a component...

## Steps to Reproduce the Problem
I don't think that it can be reproduced. In my case happens if I do `bit status`

## Specifications
  - Bit version:  14.0.0
  - Node version: 8.11.3
  - npm / yarn version: 5.6.0
  - Platform: Windows
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by itaymendel** [comment]
I assume that you have removed the local files of the deleted components. However, your local workspace still holds objects that refer to the components which file you have removed.  
To resolve that you need to tell Bit to remove the local objects as well by running `bit remove providers/auth`.

I'm closing the issue, as this is the designed behavior for when deleting local files. Removing local files does not remove the internal Bit objects from the local Bit store.

If you have used `bit remove` to remove the local component and this issue occurs please reopen the issue.
