### ISSUE TITLE
Re-open "Bit status suggest to delete not existing components" 

### ISSUE THREAD

**Issue by JEricaM** [teambit/bit#1423]
I open a new issue that it's linked to my previous one
https://github.com/teambit/bit/issues/1422 

The problem it's the same. As I show in my issue, `bit remove providers/auth` but this don't work because it tells me that the components are missing.

I haven't deleted the local files on my pc, I have deleted all the collection that I have from my bitsrc account using the website.

**Comment by davidfirst** [comment]
Probably happened when the component is not in the scope only in the workspace, which in this case, the correct command to run is `bit untrack` and not `bit remove`. 
The error message has been [fixed](https://github.com/teambit/bit/commit/dcbfbad662d8bf39abade4fe5b29dfd7c7d4cab7) to suggest the above.
