### ISSUE TITLE
Can't build vue components in typescript projects

### ISSUE THREAD

**Issue by Wurielle** [teambit/bit#1425]
## Expected Behavior
Building a vue component in a typescript project with bit.envs/bundlers/vue should compile and build `.vue` files.

## Actual Behavior
With the reproductible steps:
```
error: bit failed to build issue/hello-world with the following exception:
Module build failed: Error: ENOENT: no such file or directory, open 'D:\bit-vue-build\node_modules\loader-utils\node_modules\json5\lib\index.js'
```

With my preferred vue-cli config that I use every day: 
```
error: bit failed to build issue/app with the following exception:
Module build failed: Error: You may be using an old version of webpack; please check you're using at least version 4
```

And if I update webpack to at least webpack 4 inside the compiler's directory I get:
```
error: bit failed to load bit.envs/bundlers/vue@0.0.4 with
the following exception:
Class extends value undefined is not a constructor or null.
TypeError: Class extends value undefined is not a construct
or or null
    at Object.<anonymous> (D:\bit-vue-build\.bit\components\bundlers\vue\bit.envs
\0.0.4\node_modules\webpack\lib\MainTemplate.js:56:45)
```
## Steps to Reproduce the Problem
Using [vue-cli@3.4.0](https://www.npmjs.com/package/@vue/cli) in a CLI
  1. vue create bit-vue-build > Manually select feature > only select Typescript > No > No > In dedicated config files
  1. cd bit-vue-build
  1. bit init
  1. bit import bit.envs/bundlers/vue -c
  1. bit add src/App.vue --id issue/app
  1. bit build

## Specifications

  - Bit version: 14.0.0
  - Node version: 10.11.0
  - npm / yarn version: npm@6.4.1
  - Platform: Windows 10
  - Bit compiler (include version): bit.envs/bundlers/vue@0.0.4
  - Bit tester (include version):

**Comment by Wurielle** [comment]
After some more testing, I've been able to compile a vue component once in a non typescript environment but I can't recall the exact configuration I chose at the time to get there. While trying to reproduce the environment in which it was working in, I still got errors (even with the default vue-cli project setup or with a project setup containing no features) that looked like:
```
error: bit failed to build issue/app with the following exception:
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```
and after updating the compiler's webpack dependency I would get this error again:
```
error: bit failed to load bit.envs/bundlers/vue@0.0.4 with the following exception:
Class extends value undefined is not a constructor or null.
TypeError: Class extends value undefined is not a constructor or null
```
So maybe the issue isn't limited to typescript projects?

**Comment by GiladShoham** [comment]
@Wurielle Thanks for reporting this, we will check it.

**Comment by guysaar223** [comment]
@Wurielle 
Hi, this is an error on the webpack bundler currently [vue compiler](https://bitsrc.io/bit/envs/bundlers/vue) support webpack 3 only, 
you can import it and update the webpack.cofig to support webpack your config

**Comment by GiladShoham** [comment]
As a short term solution, you can modify the Vue compiler as described in [this post](https://discourse.bit.dev/t/can-i-modify-a-build-test-environments/28).
Later we plan to create a new API for extension / compilers / testers which allow passing config to the extension.
We will handle the progress of the new API in a new issue.
