### ISSUE TITLE
Maximum call stack size exceeded since version 14.0.0

### ISSUE THREAD

**Issue by constantin-v** [teambit/bit#1431]
## Expected Behavior

bit status is working well

## Actual Behavior

bit status is giving "Maximum call stack size exceeded" for my component

## Steps to Reproduce the Problem

  0. make sure you have bit-bin version 14.0.0
  1. clone this repo https://github.com/constantin-v/bitsrcbug
  2. npm i
  3. bit init 
  4. bit add src/MyStylesComponent
  5. bit status

## Specifications

  - Bit version: 14.0.0
  - Node version: 10.8.0
  - npm / yarn version: 6.2.0
  - Platform: Windows 10
  - Bit compiler (include version): n/a
  - Bit tester (include version): n/a

## Comments

With version 13.0.5 everything is working fine.
If you're changing the name of the file from "base.scss" to "toto.scss", bit status is working
If you're changing the name of the file from "base.scss" to "_base.scss", bit status is NOT working

**Comment by davidfirst** [comment]
@constantin-v , thanks for reporting the bug and for the clear steps how to reproduce.

The root cause of the issue is a bug with dependency-tree package, which doesn't clear the cache of an object. However, it introduced only with this version because we changed our CSS resolver to use that specific cache mechanism.

It's now fixed.

**Comment by uriking1000** [comment]
Who ate you?
Are you from glitch staff?

**Comment by constantin-v** [comment]
Thanks @davidfirst 
The fix will be available on the next release ?

**Comment by davidfirst** [comment]
@constantin-v , the fix was done on bit-javascript with is a dependency of bit. I released already a new version of that repo, so if you reinstall bit-bin, you should get already the fix.
