### ISSUE TITLE
Rendering components with external CSS

### ISSUE THREAD

**Issue by rich-frost** [teambit/bit#1441]
We are using a global external CSS stylesheet to style our components rather than having styled-components. 

Is it possible to render our component example with this external stylesheet? We don't have the stylesheet as a dependency and isn't imported in the component directly. Ideally we want to just include the external URL, is this possible?

**Comment by JoshK2** [comment]
Hey, yes you can.
create a parameter of link tag with your css link, and then include this parameter in the export method.
you can see an example of how to do this here: https://bitsrc.io/semantic-org/semantic-ui-react/icon?example=5c626278f11056001935ffc9
