### ISSUE TITLE
Can we implement bit with microservice applications build with java?

### ISSUE THREAD

**Issue by thorangSunil** [teambit/bit#1445]
this is just a question.: 
Can we implement bit with microservice applications build with java?

**Comment by itaymendel** [comment]
Hi, while Bit is designed to be language agnostic, at the moment it's APIs and feature set is primarily around the JavaScript eco-system.

In the near future, we plan on extending BIt's extension APIs. This will allow easier implementation of extensions to handle Java dependency graphs and compile pipelines.
