### ISSUE TITLE
Bit website login

### ISSUE THREAD

**Issue by Kogam22** [teambit/bit#1451]
## Expected Behavior
Log me in

## Actual Behavior
Doesn't log me in

## Steps to Reproduce the Problem

  1. Click signup
  2. Authorize Github, says will be redirected back to actual page.
  3. The Bit homepage shows same login button.

## Specifications

  - Bit version:
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
hi, the issue has been fixed and deployed.

i'm closing the issue.
