### ISSUE TITLE
Ability to add screenshots to a component.

### ISSUE THREAD

**Issue by illyax** [teambit/bit#1472]

**Comment by itaymendel** [comment]
hi @illyax , thanks for submitting this request.

While I understand that in some cases this is a logical feature to implement, i don't think that's the case. The meaning of rendering+screenshots in Bit is far greater than for the collection library.
The ability to properly render a component means that the component is truly isolated, and is consumable via a package manager. In addition to that, it allows other developers to play with the component and experiment with it before installing to their project.
Uploading screenshots of components, while a good workaround until more rendering environments are supported might hurt other experiences of the tool.

If we will encounter issues in adding more environments to Bit, I will reopen the issue to reconsider.
