### ISSUE TITLE
Cannot import CSS file that has @font-face declarations when running tests

### ISSUE THREAD

**Issue by manuel-minniti** [teambit/bit#1487]
## Expected Behavior
Expected tests to run and succeed.

## Actual Behavior
Test suite failed to run because of imported css file.

```
@font-face {
^

SyntaxError: Invalid or unexpected token
```

## Steps to Reproduce the Problem

1. Create a component that includes a `.css` file (`import "./fonts.css"`)
2. Run bit tests via `bit test` 

## Specifications

  - Bit version: 14.0.3
  - Node version: v10.15.0
  - npm / yarn version: 6.8.0 (npm)
  - Platform: OSX (native)
  - Bit compiler (include version): bit.envs/compilers/react@0.0.14
  - Bit tester (include version): bit.envs/testers/jest@0.0.35

Related to https://github.com/teambit/bit/issues/1191

**Comment by manuel-minniti** [comment]
Ideally we could pass a custom `jest.config.js` to the bit tester.

**Comment by manuel-minniti** [comment]
Or is the solution to write my own tester?

**Comment by GiladShoham** [comment]
@manuel-minniti We are working on a new extensions architecture and one of the major features is to allow passing configuration files to the compilers/testers.
I don't have an exact date for this.
meantime if you need custom configuration the best path is to import the jest tester, modify it and export to your own scope.
Let us know if you need any help

**Comment by manuel-minniti** [comment]
@GiladShoham Thanks, I was thinking about doing that.
