### ISSUE TITLE
bit.dev domain unreachable

### ISSUE THREAD

**Issue by FDiskas** [teambit/bit#1500]
DNS_PROBE_FINISHED_NXDOMAIN
Server IP address not found
```
ping: bit.dev: Name or service not known
```

**Comment by FDiskas** [comment]
https://bitsrc.io redirects to http://bit.dev and page can't be loaded

**Comment by guysaar223** [comment]
Hi @FDiskas can you try to run `ping get.dev`?

**Comment by FDiskas** [comment]
Sorry this is our network issue. usually *.dev domains are reserved for internal network projects. :loudspeaker:
