### ISSUE TITLE
add input validation when running `bit remote add`

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1506]
## Expected Behavior
when i'm trying to add a remote that is not correct, bit should notify me and fail the process.

## Actual Behavior
bit configured `scope.json` file incorrectly, thus failing my local attempts at exporting components.

## Steps to Reproduce the Problem

  1. create a new dir and init a bare scope `mkdir /tmp/remote && cd /tmp/remote && bit init --bare`
  2. in a workspace run `bit remote add file://tmp/remote`
  3. run `bit remote` and see that the remote is not configured correctly.

the actual error is that I wrote `file://` instead of `file:///` in the path.
Bit should try to see if it can reach the remote scope before configuring it as a remote.

## Specifications

  - Bit version: 14.0.4
  - Platform: macOS

**Comment by GiladShoham** [comment]
fixed and merged
