### ISSUE TITLE
bit init notworking

### ISSUE THREAD

**Issue by lotfikamel** [teambit/bit#1507]
i've tried bit init on my project but it did not work and i get this:

La commande « bit » n'a pas été trouvée, voulez-vous dire :

  commande « bti » du deb bti
  commande « bist » du deb bist
  commande « vit » du deb vit
  commande « wit » du deb wit
  commande « nit » du deb python-nevow
  commande « btt » du deb blktrace
  commande « bat » du deb bacula-console-qt
  commande « bip » du deb bip
  commande « git » du deb git

**Comment by GiladShoham** [comment]
@lotfikamel That looks like a problem with bit installation. It seems that bit binary is not found.
How did you install bit? What is your OS?
can you try run `bit --help` and see if it's working?
If no, I would recommend [re-installing bit](https://docs.bit.dev/docs/installation.html)

**Comment by davidfirst** [comment]
@lotfikamel , please re-open if you're still experiencing the issue.
