### ISSUE TITLE
Getting Error ReferenceError: React is not defined

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1509]
## Expected Behavior
Components Should Render

## Actual Behavior
Getting Error ReferenceError: React is not defined
https://bit.dev/mrkhanakia/knesk/loginform

## Steps to Reproduce the Problem

  I just exported a new component and getting error

## Specifications

- Bit version: 14.0.4
  - Node version: v11.10.1
  - npm / yarn version:6.7.0
  - Platform: 6.4.1
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
hi, the component is no longer available.

the error occurred when rendering the component in the component page, or locally when using the component?

**Comment by mrkhanakia** [comment]
I was getting error on Playground Bit but i figured it out that bitsrc was generating wrong playground code. So i had include the import React from 'react' manually on Playground. Thanks

**Comment by Team-OF** [comment]
@khanakia did you find the solution?

**Comment by khanakia** [comment]
@Team-OF 
I do not remember how i fixed the error. But you can check the code here https://bit.dev/mrkhanakia/jga/auth/loginform/
