### ISSUE TITLE
How to remove all components from remote at once

### ISSUE THREAD

**Issue by mrkhanakia** [teambit/bit#1510]
## Expected Behavior
How to remove all components from remote at once
bit remove all --force --remote not working

## Actual Behavior
bit remove all --force --remote not working

## Steps to Reproduce the Problem
 bit remove all --force --remote not working

## Specifications

- Bit version: 14.0.4
  - Node version: v11.10.1
  - npm / yarn version:6.7.0
  - Platform: 6.4.1
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by GiladShoham** [comment]
@mrkhanakia There is no remove all support right now.
I will add it to our backlog.
But usually, it's easier to just delete the remote collection and re-create it.

**Comment by GiladShoham** [comment]
Let's add supprot for glob patterns in remove command as well.

**Comment by davidfirst** [comment]
This has been implemented already and is available since v14.0.0.
Both remove locally and remove from a remote is supported with wildcards.
Every command that supports wildcards its help indicates that.
