### ISSUE TITLE
Bit export extremely slow with larger component assets

### ISSUE THREAD

**Issue by logan-jobzmall** [teambit/bit#1512]
## Expected Behavior
Upload speed for 3MB+ file should be handled without external memory flags and shouldn't take 30+ minutes

## Actual Behavior
Bit export speed for components files (in our case .wav) over 3MB (only tested at this threshold) that need to be included in the component causes bit export to make node run out of Heap. It needed be started with `NODE_OPTIONS=--max_old_space_size=8096` for it not to crash. Once that hurdle is taken care of, it hangs for very large amounts of time (30+ minutes per export).

## Steps to Reproduce the Problem

  1. Add a decent amount of file to your component (20 files or so), and make sure that a couple of them are 3MB+
  2. Bit add all
  3. Bit tag
  4. Bit export

## Specifications

  - Bit version: 14.0.4
  - Node version: 10.4.1
  - npm / yarn version: 1.13.0
  - Platform: Mac OSX Mojave (10.14.4)

## Extra Information
We need these wav files across our codebases, so we assumed bit could handle a couple slightly larger files like git does with ease. If this is not intended, and if assets like this are supposed to be housed elsewhere in the design of your Bit, please let me know.

**Comment by itaymendel** [comment]
Hi @logan-jobzmall , while Bit can handle binary file formats, we haven't spent too many efforts on optimization of it. I know that the folks behind Git did some work around it and even added an extension to handle versioning of binary files ([git lfs](https://git-lfs.github.com)).

While I don't have an understanding of the specifics of your use case, generally I'd prefer hosting binary files outside of the app and fetch them to the client (from a CDN or any external storage).

I am keeping this issue open. This is a low priority task at the moment, but we will want to handle it in the future.

**Comment by logan-jobzmall** [comment]
@itaymendel - a small followup to this ticket. Let me know if you want me to produce a new ticket or amend this one. I removed all large binary assets from one of our components, but am still having the same outcome when the total amount of files are on the high side. A total of 1.2MB for the entire component (around 200 files) seems to see the same result. I understand 200 files seems like a lot for a component in the general idea of things - but I wouldn't see why this would affect an export like this. As another piece of information I am using `--ignore-missing-dependencies` in my tag prior.

**Comment by itaymendel** [comment]
We've improved Bit's handling for large assets by improving the compression flow. This is available since Bit 14.6.0.
