### ISSUE TITLE
Flow in combination with React

### ISSUE THREAD

**Issue by bbeemster** [teambit/bit#1513]
## Expected Behavior
I can import a compiler like: `bit import bit.envs/compilers/react-flow --compiler`.

## Actual Behavior
I can only import a compiler like `bit import bit.envs/compilers/react --compiler` or `bit import bit.envs/compilers/flow --compiler`

Whenever I use either of these I cannot `bit tag` because it will fail to build hence it will break on either React or Flow syntax.

**Comment by GiladShoham** [comment]
Hi @bbeemster,

Currently, there is no react-flow compiler maintained by bit team.
We are working to create one (I estimate it will be published in about a week)
If you don't want to wait, you can easily create one of your own based on either our flow compiler or react compiler.
(keep in mind that currently the last react compiler is using babel 7 under the hood while the flow is using babel 6. we are also working on new flow compiler version based on babel 7).
For instruction how to create your own you can see here:
https://discourse.bit.dev/t/can-i-modify-a-build-test-environments/28

**Comment by GiladShoham** [comment]
You can open an issue in https://github.com/teambit/bit.envs repo.
