### ISSUE TITLE
Error on "tag" but not on "build" when using some babel plugins

### ISSUE THREAD

**Issue by ruifortes** [teambit/bit#1529]
I'm using some experimental babel plugins and although `bit build` works with `bit tag` I get an this error: `"test.jsx -> Unexpected token (7:17)"`

If I remove the 'import' statement then `bit tag` also works.

The plugins in question are "@babel/plugin-proposal-optional-chaining" and "@babel/plugin-proposal-nullish-coalescing-operator" and the test.jsx file is:

```
import classnames from 'classnames'

export default function Test(props) {
	const {foo, ...rest} = props
	
	const bar = foo?.nested?.something() ?? 'default'
	
	return <div >TEST</div>
}
```

I don't know how Bit is doing it's parsing but since building works shouldn't tagging also work?

**Comment by GiladShoham** [comment]
@ruifortes Thanks for reporting this.
In general, if the build works, the tag should work as well (unless there are failing tests).
I'll check this out.
Can you please specify the compiler / tester you are using?

**Comment by JoshK2** [comment]
Hey @ruifortes , can you post your babel config so I can reproduce this and try to fix it.

**Comment by ruifortes** [comment]
Hi. Just pick this up again.
Could you check the following steps to see if happens the same way there?

``` sh
bit init

npm init -y

npm i -D @babel/core \
@babel/preset-env \
@babel/plugin-proposal-nullish-coalescing-operator \
@babel/plugin-proposal-optional-chaining

echo -e '{
	"presets": [
	"@babel/preset-env"
	],
	"plugins": [
	"@babel/plugin-proposal-nullish-coalescing-operator",
	"@babel/plugin-proposal-optional-chaining"
	]
}' > .babelrc

mkdir src

echo -e 'export default function(p1) {
	let test = p1?.someMethod() ?? "default"
	return test
}' > src/test1.js

bit add src/*

bit tag -a

# Everything's fine, I can tag.
# But after importing the compiler

bit import bit.envs/compilers/react -c

# change something in the file
echo "console.log('aaa')" >> src/test1.js

# and try ti tag again

bit tag -a

#to make it work I need to change the compilers .babelrc
(cd .bit/components/compilers/react/bit.envs/1.0.2/dist/compilers/react \
&& cat .babelrc | jq '.plugins += [
	"@babel/plugin-proposal-nullish-coalescing-operator", 
	"@babel/plugin-proposal-optional-chaining"
]' > tmp && mv tmp .babelrc)

# now it works
bit tag -a

# Is this the way it's supposed to work?
# Shouldn't bit pick up the projects .babelrc?
```

**Comment by ruifortes** [comment]
but even this hack fails with emotionjs:

``` sh

# adding react stuff also seams to work fine

echo -e 'export default function(props) {
	let test = props?.someMethod() ?? "default"
  return <h3>Test2</h3>
}' > src/test2.js

bit add src/* && bit tag -a && bit build

# using emotion via pragma also seams to work

npm i @emotion/core

echo -e '/** @jsx jsx */
import {jsx} from "@emotion/core"
export default function(props) {
	<div
    css={{
      backgroundColor: "hotpink",
      "&:hover": {
        color: "lightgreen"
      }
    }}
  >
    This has a hotpink background.
  </div>
}' > src/test3.js

bit add src/* && bit tag -a && bit build

# but not when using the fancy optional chaining syntax

echo -e '/** @jsx jsx */
import {jsx} from "@emotion/core"
export default function(props) {
	let test = props?.someMethod() ?? "default"
	<div
    css={{
      backgroundColor: "hotpink",
      "&:hover": {
        color: "lightgreen"
      }
    }}
  >
    This has a hotpink background.
  </div>
}' > src/test4.js

bit add src/* && bit status

# status already shows the error

bit tag -a

# and...tag will fail
# and also build

```

**Comment by davidfirst** [comment]
This is the error I got running anything even with the first example:
```
> test1 ...  issues found
       error found while parsing the file (please edit the file and fix the parsing error):
          src/test1.js -> This experimental syntax requires enabling the parser plugin: 'optionalChaining' (2:14)
```
This has been fixed in the commit above (of bit-javascript) by upgrading the node-source-walk package. (see the following [commit](https://github.com/dependents/node-source-walk/commit/3b538ca78fefb36f67d83e7fb45162e5b6c47544) that added the missing plugins to the Babel parser).
I released a new version of bit-javascript, so re-installing Bit, should pick up the new version and it should work already.

As to the build issue where the OP needed to edit the `.babelrc` of React compiler and manually add plugins, it's possible to create a new compiler with the updated `.babelrc`. @GiladShoham , I believe you can share more info about this process.

Lastly, as far as I understand from the last two comments, there is no issue of inconsistency between tag and build. If build passed, tag passed as well. @ruifortes, please let me know if I'm wrong.

**Comment by davidfirst** [comment]
I don't see a good reason to leave it open, the docs have some examples about the compiler and the main issue has been fixed as described.
