### ISSUE TITLE
EPERM: operation not permitted

### ISSUE THREAD

**Issue by igrbesa** [teambit/bit#1536]
## Steps to Reproduce the Problem

  1. bit import of some components
  2. component is modified, bit tag
  3. bit export <component> -f -e
Results in error: The components ** were exported successfully.
    However, the eject operation has failed due to an error: Error: eject operation has installed your components successfully using the NPM client.
however, it failed removing the old components from the filesystem.
please use bit remove command to remove them.

got the following error: EPERM: operation not permitted, lstat 'C:\**\app\components\MyComponent\node_modules'

After this bit status throws error:  EPERM: operation not permitted, scandir 'C:\**\app\components\MyComponent\node_modules'

Also bit remove throws same error.

If I try to delete MyComponent folder from exporer I get Folder Access Denied.

## Specifications

  - Bit version:14.0.5
  - Node version:10.15.0
  - npm / yarn version:6.4.1
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by itaymendel** [comment]
It sounds like the user account you use to run Bit commands with does not have full access permissions on the directory, as it can't remove files from it.
What baffles more is that you can't manually remove them as well. I would suggest looking into the directory permissions. Once you are able to fix them in a way that you can manually delete the files, Bit should be able to delete them as well, as Bit runs with the same permissions that your account has.

**Comment by igrbesa** [comment]
It seems like deleting node_modules takes time where in some cases node_modules are deleted and in others not (in this case when trying to execute bit status I get error
EPERM: operation not permitted, scandir 'C:\**\app\components\MyComponent\node_modules'

**Comment by davidfirst** [comment]
@igrbesa , if you can send me a zip file to david@bit.dev, I'd be happy to look into it. 
Alternatively, if you can provide some steps to reproduce it (you can add me as a collaborator to your collection), it'd be even better.

**Comment by GiladShoham** [comment]
@davidfirst I don't think this would help. It seems like a local issue with FS permissions. I don't think you will be able to reproduce it by using his collection.
(Also notice it's a windows machine, which might also affect in this case).

**Comment by itaymendel** [comment]
It seems like there's some zombie process that holds an open file handler. I don't think there's anything Bit can do with it.
