### ISSUE TITLE
Installing Bit components in GitLab CI

### ISSUE THREAD

**Issue by taylorqj** [teambit/bit#1539]
## Expected Behavior

`npm i` or `yarn` should pull components from bit.dev after setting up the CI's `.npmrc` with a valid token.

## Actual Behavior

Following the documentation here: [CI Docs](https://docs.bit.dev/tutorial/node-tutorial.html#install-components-during-ci)

**4/10/2019 Paste for historical reasons:**

```md
1. Make sure you have a valid token generated for the CI server. To generate a token, run the following command: npm login --registry=https://node.bit.dev --scope=@bit

2. The token will be available for you in your ~/.npmrc file.

3. Set a secret to your CI environment variable called BIT_NODE_TOKEN. This step differs from one CI to another. Console your CI provider’s documentation to understand how to do it. An abstract way of configuring the client is running this command:

echo @bit:registry=https://node.bit.dev\n//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc
```

### Issue 1: The above documentation contains a malformed URL to the bit registry.

**GitLab CI Output**

```shell
Checking out 9d901486 as master-test-build...

Skipping Git submodules setup
Checking cache for default-1...
Downloading cache.zip from https://storage.googleapis.com/gitlab-com-runners-cache/project/1/default-1 
Successfully extracted cache
$ echo "Adding bit.dev to npm registry"
Adding bit.dev to npm registry
$ echo @bit:registry=https://node.bit.dev\n//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc
/bin/bash: eval: line 114: unexpected EOF while looking for matching `"'
ERROR: Job failed: exit code 2
```
As we can see, there's a `"` at the end of the URL. This will report an end of file error. After removing the erroneous `"` and re-building we're presented with another error.

### Issue 2: After fixing the `"` we're presented with another malformed URL

**GitLab CI Output**

```shell
Checking out 7481406b as master-test-build...

Skipping Git submodules setup
Checking cache for default-1...
Downloading cache.zip from https://storage.googleapis.com/gitlab-com-runners-cache/project/3309136/default-1 
Successfully extracted cache
$ echo "Adding bit.dev to npm registry"
Adding bit.dev to npm registry
$ echo @bit:registry=https://node.bit.dev\n//node.bit.dev/:_authToken={$BIT_NODE_TOKEN} >> ~/.npmrc
$ echo "Completed adding bit.dev to npm registry"
Completed adding bit.dev to npm registry
$ npm config ls
; cli configs
metrics-registry = "https://registry.npmjs.org/"
scope = ""
user-agent = "npm/5.6.0 node/v9.10.0 linux x64"

; userconfig /root/.npmrc
@bit:registry = "https://node.bit.devn//node.bit.dev/:_authToken={BIT_NODE_TOKEN}"

; node bin location = /usr/local/bin/node
; cwd = /builds/project
; HOME = /root
; "npm config ls -l" to show all defaults.

$ echo "Show root npmrc"
Show root npmrc
$ cat ~/.npmrc
@bit:registry=https://node.bit.devn//node.bit.dev/:_authToken={BIT_NODE_TOKEN}
$ yarn
yarn install v1.5.1
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://node.bit.devn//node.bit.dev/:_authToken=%REDACTED%7D/@bit%project.components.moduleloader: getaddrinfo ENOTFOUND node.bit.devn node.bit.devn:443".
info If you think this is a bug, please open a bug report with the information provided in "/builds/project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Job failed: exit code 1
```

Per the documentation it's adding the registry url as is.

Ex. `@bit:registry=https://node.bit.devn//node.bit.dev/:_authToken={BIT_NODE_TOKEN}
`

It should be adding a new line in the `.npmrc`.

### Issue 3: Incompatible Node Version

**This is not related to Bit (AFAIK)**. It's relevant to show the complete fix to our specific issue so I'm throwing this in here. Had a failure of building a non-bit-package due to wrong node version. We upgraded from `9.10.0` to `11.10.0`.

### Issue 4: Yarn 401 unauthorized

We use Yarn in our builds and it was throwing a 401 when trying to access the bit repo. In order to use yarn with bit, you may need to `echo "always-auth=true" >> ~/.npmrc`. You can read about this [here](https://docs.npmjs.com/misc/config#always-auth).

## Steps to Reproduce the Problem

  1. Follow CI instructions for adding registry to `.npmrc`
  2. Run a build

## Specifications

  - Bit version: 14.0.5
  - Node version: 11.10.0
  - npm / yarn version: N/A
  - Platform: GitLab CI
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

## :tada: Resolution :tada:

1. Separate the `.npmrc` injection from the `$ echo @bit:registry=https://node.bit.dev\n//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc` to the following:

```shell
$ echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
$ echo "//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc
```

_If you're using yarn, you'll need to add this before the bit registry addition_
```shell
$ echo "always-auth=true" >> ~/.npmrc
```

Here's the full `.gitlab-ci.yml` for those attempting to get Bit working on their GitLab CI builds. You can remove the `npm config ls` and `cat ~/.npmrc` as that was for testing purposes.

```yml
image: node:11.10.0

stages:
  - bit_test

variables:
  DOCKER_DRIVER: overlay

cache:
  paths:
  - node_modules/

bit_test:
  stage: bit_test
  script:
    - echo "Adding bit.dev to npm registry"
    - echo "always-auth=true" >> ~/.npmrc
    - echo "@bit:registry=https://node.bit.dev" >> ~/.npmrc
    - echo "//node.bit.dev/:_authToken={$BIT_NODE_TOKEN}" >> ~/.npmrc
    - echo "Completed adding bit.dev to npm registry"
    - npm config ls
    - echo "Show root npmrc"
    - cat ~/.npmrc
    - yarn
```

Thanks to @itaymendel and @GiladShoham for the support on getting this resolved.

**Comment by GiladShoham** [comment]
@taylorqj Thanks for the detailed explanation of the full process. as well as the kind words.
Closing this as there is nothing left to do here.
