### ISSUE TITLE
process out of memory

### ISSUE THREAD

**Issue by jahglow** [teambit/bit#1544]
## Expected Behavior
I checked out repo that is outsourced as bit components, did `bit login` to init `.git/bit` folder, did `bit import` to import all changes to my components done outside this repo project by other devs. Expected it to refresh components code from bit repos

## Actual Behavior

it failed with the following error
```
bit import
\ importing components
<--- Last few GCs --->

[24168:0000023570F79FF0]    94142 ms: Scavenge 657.2 (758.5) -> 647.3 (762.5) MB, 29.7 / 0.4 ms  allocation failure
[24168:0000023570F79FF0]    94726 ms: Scavenge 660.3 (762.5) -> 649.7 (763.0) MB, 339.0 / 0.4 ms  allocation failure
[24168:0000023570F79FF0]    96011 ms: Scavenge 662.1 (763.0) -> 651.6 (764.0) MB, 1073.3 / 0.4 ms  allocation failure


<--- JS stacktrace --->
Cannot get stack trace in GC.
FATAL ERROR: NewSpace::Rebalance Allocation failed - process out of memory
 1: 00007FF632F4383D
 2: 00007FF633638A15
 3: 00007FF633638968
 4: 00007FF6336A293D
 5: 00007FF633523710
 6: 00007FF633522B3B
 7: 00007FF633521A41
 8: 00007FF6335208F0
 9: 00007FF63322D51C
10: 00007FF6332C67D7
11: 0000005F25F043C1
```

## Specifications

  - Bit version: 14.0.5
  - Node version: 8.11.1
  - npm / yarn version: 5.6.0
  - Platform: win10
  - Bit compiler (include version): bit.envs/compilers/react@0.0.15
  - Bit tester (include version): bit.envs/testers/jest@0.0.35

**Comment by jahglow** [comment]
fixed by running `bit cc` to clean caches... that's weired behavior though, you decide if to close it or investigate... we've got 30+ components.

**Comment by GiladShoham** [comment]
@jahglow Thanks for reporting this.
I'm not sure it is related to the cache since this cache is modules cache and not related to components.
But we will investigate this.
Thanks.

**Comment by fadziljusri** [comment]
I also got the same error after `bit import` on my windows 10, windows 7, and Ubuntu 16.04 LTS. Apparently, my laptop hang after `bit import` execution. I also did `bit cc` but it's not solving this issue. However `bit import` on Mac is not causing this error.

## Specifications
* Bit version: 14.0.5 and 14.0.6
* Node version: 8.9.1
* Npm version: 6.9.0

**Comment by GiladShoham** [comment]
@fadziljusri Is there a chance the components you import are public? if so, can you post the names and I'll try myself?
Thanks.

**Comment by fadziljusri** [comment]
@GiladShoham Unfortunately the components that im working on are not private. However my `bit.json` file consist of 88 total of components in current project.
