### ISSUE TITLE
Web Component Market

### ISSUE THREAD

**Issue by tayambamwanza** [teambit/bit#1550]
Hi, I just discovered Bit, I have to say it's a pretty **awesome** tool.

I had an idea to do something like this and I searched high and low for a tool like this but only stumbled on a post about Bit by a retweet.

I was thinking that maybe you could make it more discoverable by calling it, or at least the component catalogue "The Web Component Market" or something like that, so that it can be more visible and come across as the main place for devs to publish/download web components, kind of like android has the playstore.

It's a really awesome idea but I think discoverability is a problem at the moment even through google search. I hope this tool really takes off so just giving my 2 cents.

![Screenshot from 2019-04-15 22-43-45](https://user-images.githubusercontent.com/11971384/56164088-40697480-5fd0-11e9-8a91-d7f671c1835e.png)

![Screenshot from 2019-04-15 22-47-05](https://user-images.githubusercontent.com/11971384/56164184-71e24000-5fd0-11e9-8396-38eedfba6b34.png)

**Comment by jonisar** [comment]
Hi Taymaba,
Thanks for the warm feedback! It's great to hear people think this way of Bit and its potential. We do share the vision in which developers around the world can easily share, discover and use components to build their apps. Web components are definitely a super-powerful combination with Bit!! (see https://bit.dev/wiredjs/wired-elements). We're excited towards the amazing possibilities for the composition of applications with shared framework-agnostic components. We're exploring names for improving discoverability, so thanks for sharing your ideas! :)
