### ISSUE TITLE
How to export to a different remote?

### ISSUE THREAD

**Issue by ruifortes** [teambit/bit#1553]
Hi.
Is there a way to export to a different remote?
What the proper way to modify a imported component but keep track of upstream changes?
And of course use it by importing from the new remote.
Thanks

**Comment by GiladShoham** [comment]
Hi, @ruifortes

I'll start from the second quesion :) 
Managing component upstream is something that is not available at the moment. I'm working on the specs for this feature as we speak and will publish it soon. this is a very critical feature for us, and has a very high priority.

having said that, you can import a component from one remote and export to another.
```sh
bit import [component-name]
bit tag [component name] # you will have to create a new tag in order to export it
bit export [new-remote] [component-name]
```
A part of the specification of managing component upstream will handle this workflow as well.
