### ISSUE TITLE
Misspelling in Docs for Install

### ISSUE THREAD

**Issue by sammihansen** [teambit/bit#1563]
## Expected Behavior
Code block for example to install bit globally on windows should stay:
```
# When installing Bit on windows, add the --no-optional flag:
```
## Actual Behavior
What it currently says:
```
npm install bit-bin --global

# When installing Bit on windows, add the --no-optional `fag`:
npm install bit-bin --global --no-optional
```

## Steps to Reproduce the Problem
Docs > Getting Started > Installing
__

**Comment by itaymendel** [comment]
resolved and deployed.
