### ISSUE TITLE
Documentation page headings 

### ISSUE THREAD

**Issue by seangates** [teambit/bit#1565]
>**Note:** There is a closed issue (#1304), but it was never addressed. That issue should be re-opened, or this one should replace it. That issue even has a more detailed screen shot of the issue.

## Expected Behavior
I can see the page heading.

## Actual Behavior
I can only see two letters of the heading:

![image](https://user-images.githubusercontent.com/105656/56507355-41256d80-64de-11e9-846a-b7698f16813d.png)

## Steps to Reproduce the Problem

  1. Visit https://docs.bit.dev/whybit/for-libs.html with the page wider than 2000px

## Specifications

  - Bit version: n/a
  - Node version: n/a
  - npm / yarn version: n/a
  - Platform: n/a
  - Bit compiler (include version): n/a
  - Bit tester (include version): n/a

**Comment by GiladShoham** [comment]
@seangates 
Thanks for reporting this.
I was able to reproduce it.
We will check and fix this.

**Comment by GiladShoham** [comment]
Resolved and deployed.
Thanks.
