### ISSUE TITLE
Add machine name flag to bit login command

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1567]
## Expected Behavior
Ability to specify the machine name in the `bit login` command to be able to create a token for a specific machine.
That will prevent a case when someone generates a token in his machine to use in CI system then after some time he re-login and the old token revoked.

**Comment by davidfirst** [comment]
@GiladShoham , so the current URL has these parts `clientId`, `deviceName`, `os.hostname`,  and `os`.
Which one/ones of them should be replaced by the custom machine-name, or should I add a new one?

**Comment by itaymendel** [comment]
@davidfirst `deviceName`

**Comment by davidfirst** [comment]
Implemented.
