### ISSUE TITLE
React Native export components issue

### ISSUE THREAD

**Issue by nadzic** [teambit/bit#1570]
## Expected Behavior

Adding component without any issues

## Actual Behavior

Missing package depedencies, more detailed:

     > loader ...  issues found       
       missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/components/common/Loader.js -> kioskapp

<img width="842" alt="Screenshot 2019-04-24 at 15 50 58" src="https://user-images.githubusercontent.com/6192073/56665396-42a39100-66aa-11e9-85d3-30b51820d1c1.png">

## Steps to Reproduce the Problem

Just after the adding component.

## Specifications

  - Bit version: 14.0.6
  - Node version: v8.6.0
  - npm / yarn version: 6.4.1
  - Platform: Mac Os X
  - Bit compiler (include version): React@1.0.1
  - Bit tester (include version): Jest@0.0.35

**Comment by itaymendel** [comment]
Hi,

It seems that `Loader.js` requires a module named `kioskapp`, and Bit is unable to find it in your project.
Is `kioskapp` is a component you use an absolute path in your `import` statement? If so, you'll need to set up [custome module resolution](https://docs.bit.dev/docs/tracking-dependencies.html#custom-module-resolution) so Bit can parse the `import` statement correctly.
If it's a package, please make sure it is installed correctly.

**Comment by nadzic** [comment]
Yeah, that was the issue - solved before!

Thanks!
