### ISSUE TITLE
improve error message on ejecting modified component

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1583]
## Expected Behavior

When I have local modifications for a component I want to `eject`, Bit should notify me that it stopped the eject process as it will discard local changes.

```bash
stopped the eject process for the following components because they have local changes.

  > [component-id]@[version]
  > [component-id]@[version]
  > [component-id]@[version]

ejecting modified components discards all local, unstaged, changes.
use 'bit diff <component id>' to see the changes and decide if to 'bit tag' them or not.
use the '--force' flag to discard local modifications and proceed with the eject process.
```

## Actual Behavior

I'm getting a red error message about failure in Bit.

```bash
failed to eject the following components
components with local modifications (use --force to ignore): <component id>@<version>
```

## Steps to Reproduce the Problem

  1. import a component
  1. modify and tag changes
  1. modify once again
  1. export with 'eject' flag

## Specifications

  - Bit version: 14.0.5

**Comment by qballer** [comment]
You can skip step 2, it should still happen, before the tag
