### ISSUE TITLE
status showing component as modified but no diff in bit diff

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1584]
## Expected Behavior
Bit diff should show why the component considered modified.
This is very critical since it blocks other operations like import without overrides or eject or remove.

## Actual Behavior
`bit diff` shows nothing

## Steps to Reproduce the Problem

  1. To complete

## Specifications

  - Bit version: 14.0.6
  - Node version: 8.10.0
  - npm / yarn version: 6.8.0
  - Platform: mac
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

![image](https://user-images.githubusercontent.com/3840769/56954041-7f5a0700-6b46-11e9-9183-72bdab26f395.png)

**Comment by GiladShoham** [comment]
Checking further, the modification is a result of dependencies ordering between the versions.
The `bit diff` knows to ignore it while the `bit status` doesn't.
This is probably the reason for this issue as well: https://github.com/teambit/bit/issues/1582

**Comment by GiladShoham** [comment]
This might be a result of the fact that during comparison we run a sort function (https://github.com/teambit/bit/blob/master/src/consumer/consumer.js#L489), which internally uses sortObject (https://github.com/teambit/bit/blob/master/src/utils/object/sort.js)
which is something considered not safe (to rely on object keys order).
One correct way to achieve it is to convert it to an array, see here:
https://stackoverflow.com/a/1069840

**Comment by davidfirst** [comment]
Just a note, it wasn't related to the `sortObject`, which actually does use an array to compare. 
The problem was that the dependencies weren't sorted at all.
I'm unsure how the dependencies order was changed without changing anything else. So, unfortunately, I wasn't able to create a test for this.
