### ISSUE TITLE
[Experimental] Bit Doctor - steps towards release

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1596]
# Bit Doctor

New troubleshooting command that checks the system and workspace for potential problems. Additionally, `doctor` can extract useful information, errors and logs to share with Bit's maintainers when filing an issue.

`doctor` is listed as an experimental feature until we make it more useful by implementing additional checks and dogfooding the APIs. We use this issue to communicate towards the final release of `bit doctor`.

## Checks to implement

Listed below are important checks to implement to Bit. We should use them as use cases for testing the API and decide if it needs any additional improvements.

- [ ] Check that all objects for the workspace exist in the store 
- [ ] Check for orphan objects in the workspace store (objects without refs from `.bitmap`, or bitmap’s comps - recursively)
- [ ] Validate component index
- [ ] [Validate authentication issues](https://docs.bitsrc.io/docs/authentication-issues.html)
- [ ] Validate `.bitmap` syntax
- [ ] Validate `bit` config object (in `package.json` or `bit.json`) syntax
- [ ] Validate object schemas
- [ ] Validate `bit config`
    - [ ] `ssh_key_file` exist if defined
    - [ ] `hub_domain` valid if define 
    - [ ] `registry`
    - [ ] `user.name` `user.email`
- [ ] Validate that all links (created by `bit link`) exist in a workspace
- [x] Validate that git exec found (include git exec path if defined in `bit config`)
- [x] Validate yarn / npm exec found
- [ ] Validate file permissions (`node_modules`, `.bit` dir, default component dir) in a workspace
- [x] Validate that bit is in the latest version
- [ ] Validate that `.npmrc` is configured with @bit correctly
- [x] Check orphan Symlink objects (symlink object that references to a non-exist comp)

## Developing checks

All checks are implemented [here](https://github.com/teambit/bit/tree/master/src/doctor/core-diagnoses).

Each check extends `Diagnosis` and has three properties:

1. `name` - [string], the name of the check. This should be a human readble name.
1.  `description` - [string], human-readable description for the check.
1. `category` - [string], the category of the check. for improved user experience when running checks.

A check should have a function called `_runExamine()` that returns a `Promise<ExamineBareResult>`. the `ExamineBareResult` is an object that contains `valid`, a boolean value that holds the result of the check, and `data`, object value of the raw results.  
It also has two additional APIs. One to handle the print of the results: `_formatSymptoms`, and another to explain how to resolve it - `_formatManualTreat`.

### Mock

Here's a mock check for `bit doctor`:

```js
/** @flow */

export type ExamineBareResult = {
    valid: boolean,
    data?: Object
};

export default class MyDiagnosis extends Diagnosis {
    name = 'some-name';
    description = 'this diagnosis check something';
    category = 'some-category';

    /**
     * Returns a descriptive symptoms message which might include specific data from the examination
     * @param bareResult ExamineBareResult 
     */
    _formatSymptoms(bareResult: ExamineBareResult): string {
        return `you have an issue with "${bareResult.data.extraData}"`;
    }

    /**
     * Returns a descriptive instruction to handle the issue (might include specific data from the examination)
     * @param bareResult ExamineBareResult
     */
    _formatManualTreat(bareResult: ExamineBareResult) {
        return `please delete the following file:\n${bareResult.data.extraData.join('\n')}`;
    }

    /**
     * A function that actually runs the examination
     */
    async _runExamine(): Promise<ExamineBareResult> {
        return {
            valid: true,
            data: {
                extraData: "value"
            }
        };
    }
}
```

**Comment by davidfirst** [comment]
Questions about some of the validations.

>  Check that all objects for the workspace exist in the store

I think that on `bit status` you get already a warning about missing objects and a suggestion to run `bit import`, so not sure it's needed.

> Validate .bitmap syntax

The JSON itself must be valid, otherwise, Bit wouldn't start.
Other validations are done before updating/adding the component into `.bitmap` file.
However, a user might change the file manually, so I guess it could be useful to have this taken care of by the doctor.

> Validate bit config object (in package.json or bit.json) syntax

This is done already when these files are loaded. Bit wouldn't start when there are validation errors there. (See `WorkspaceConfig.validate()` method). I think it's not needed.

>  Validate that all links (created by bit link) exist in a workspace

This check is done during `bit status` and it shows a warning about missing links.
