### ISSUE TITLE
Bit undeprecate

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1600]
## Expected Behavior
We should have a way to undeprecate a component (both local and remote)

## Actual Behavior
There is no way to do it

**Comment by davidfirst** [comment]
Implemented.
@itaymendel , it needs to be added to the main help (`bit -h`). This and `bit deprecated`.
If you can provide the text, I'll add it in another commit. Please let me know what category to put it in.

Also, it needs to be added to the docs.

**Comment by itaymendel** [comment]
I'll add it to the docs as soon as this is deployed. Already got it on another branch ;)

We should add both to `collaborate and share components`.
As for the description, I think that `undeprecates a deprecated a component` should be ok.
