### ISSUE TITLE
imported component doesn't update with webpack hot reloader

### ISSUE THREAD

**Issue by odedre** [teambit/bit#1604]
## Description:
When importing a component, changes to the component's source code weren't being updated in my project. Only after refreshing the server, the changes to the component were rendered.

## Expected Behavior
when importing a component, changes to its source code should be instantly visible. 

## Actual Behavior
changes to the imported component weren't rendered. Changes were only visible after refreshing the server.

## Steps to Reproduce the Problem

  1. npm install a component
  2. Bit import the same component to your project.
  3. run bit watch
  4. Refresh server.
  5. Change code in imported component.
  6. refresh your app and look for changes.

## Specifications

  - Bit version: 14.0.4
  - Node version: 10.15.3
  - yarn version: 1.13.0
  - webpack version: 2.5.1
  - Bit compiler (include version): https://bit.dev/bit/search/ts-compiler?version=0.0.2
  - Bit tester (include version): https://bit.dev/bit/envs/testers/mocha/~code?version=0.0.17

**Comment by itaymendel** [comment]
duplicated issue.
closing this one.
let's keep the conversation going in the [previous issue](https://github.com/teambit/bit/issues/1602)
