### ISSUE TITLE
leftover dependency when tagging component

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1608]
I am trying to re-export ```iframe/communicator``` to a new collection, ```bit/capsule```,  so I could export the new component ```playground-client``` to the same collection.

I imported ```iframe/communicator``` locally, edited and tagged it. ```playground-client``` was also auto tagged.

now when I try to export, I am getting the same security error.

## Expected Behavior
Should export both components

## Actual Behavior
❯ bit status                 
staged components
(use "bit export <remote_scope> to push these components to a remote scope")

     > iframe/communicator. versions: 0.2.5 ... ok
     > playground-client. versions: 0.0.1, 0.0.2 ... ok
                                                                                                                                            
web git/master*  
❯ bit export bit.capsule
error: unable to export components to bit.capsule because they have dependencies on components in bitsrc.ui.
bit does not allow setting dependencies between components in private collections managed by different owners.

## Specifications

  - Bit version: 14.1.0
  - Node version: 11.13.0.
  - npm / yarn version: 1.15.2
  - Platform: MacOS

**Comment by GiladShoham** [comment]
The error of security is by design.
To prevent re-publish private components of a different owner.
The ability to export components with dependencies as new components will be handled under different issue as a feature.

**Comment by KutnerBitsrc** [comment]
ok, I managed to fix it by importing ```iframe/communicator``` locally, modifying it with a whitespace, tagging it, and then exporting it again to ```bit.capsule```.

The major pitfall was that I already tagged ```playground-client``` with the old dependency, so I had to ```bit untag -a```, losing all the tags I created, and then running ```bit tag -a``` again. :(

it is **really annoying** that I am forced to create empty tags just to re-export my components to another Collection. 👎

**Comment by GiladShoham** [comment]
@KutnerBitsrc I understand your frustration, and we do plan to address this issue. But it requires to take different consideration into account, like security issues, experience etc'.
So we plan to design a good product for this. We already started this process but it will take some time.
