### ISSUE TITLE
Bit import is confusing

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1609]
## Expected Behavior
Bit import (or another command) will fetch and merge version if there is no change

## Actual Behavior
if a new tag is created by the consumer environment, the component version are fetched but not merged. 

## Steps to Reproduce the Problem

  1. Create a component.
  2. export the component.
  3. create a new tag in another workspace.
  4. do `bit import`.
  5. version appears and not merged.

## Specifications

  - Bit version: 14.1.0
  - Node version: 10.15.3
  - npm / yarn version: 6.4.1
  - OS: mac os
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by GiladShoham** [comment]
@qballer That's by design. 
I wouldn't expect bit to auto update my all components every import. it might break my entire app.
`bit import`(without any arg) is more like `git fetch` not like `git pull`.
I do agree that we need to add sugar which does fetch and checkout to latest, but it shouldn't be the default of bit import.
This might be a new command like `bit update` or `bit upgrade` or maybe a flag for `bit import`.

**Comment by qballer** [comment]
I understand this is by design, but I feel in many cases `bit pull` is in order

**Comment by davidfirst** [comment]
In addition to what @GiladShoham mentioned, I believe `--merge` flag (of `bit import`) is what you're looking for.

**Comment by qballer** [comment]
`--merge` is the technical part of what I'm looking for, it isn't the product though. Users have a familiar API with git. Something is a sugar for `git fetch; git merge` (git pull). `bit import` is confusing because it is the same command you bring the first version component, and it become fetch afterwards.

This is why I believe something else should provide the mental model

**Comment by GiladShoham** [comment]
It's indeed a bit confusing, but part of the confusion is inherent to the difference between git and bit.
I agree we can make it better of course. 
We should discuss it and hear some options and opinions.
Let's also ask for @itaymendel input here.

**Comment by Tallyb** [comment]
Also worth considering separating extensions from components import, even if the underlying mechanism is the same.
