### ISSUE TITLE
Bit doesn't support import from CDN

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1613]
## Expected Behavior
`import { html, LitElement } from 'https://unpkg.com/lit-element?module'`
should work

## Actual Behavior
unrecognised dependency

## Steps to Reproduce the Problem

  1. create a component which imports es6 module from unpkg
  2. run `bit status`

## Specifications

  - Bit version: 14.1
  - Node version: 10.15.3
  - npm / yarn version: 6.4.1
  - Platform: MacOS 10.14.3
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by GiladShoham** [comment]
We should ignore any import statement that starts with `http://` or `https://` when calculating dependencies.
