### ISSUE TITLE
Support for Polymer project's enviroment are contemplated?

### ISSUE THREAD

**Issue by AlexMtz** [teambit/bit#1620]
We're working on large web applications using polymer components. We have owns components too and we want to publish for other projects.

**Comment by itaymendel** [comment]
Hi,

I appreciate your team's efforts to share components to Bit!
Seeing that we're not experienced in developing for Polymer I suggest that you try and implement such environment. We'll be more than happy to support your such initiative :)

**Comment by itaymendel** [comment]
I'm closing this issue. If OP (or anyone else) want to help by building a compiler for polymer components - we'll gladly assist!

**Comment by GiladShoham** [comment]
If someone wants to help with this. the correct place to do it is on https://github.com/teambit/bit.envs
