### ISSUE TITLE
Remove component from remote scope

### ISSUE THREAD

**Issue by namieluss** [teambit/bit#1622]
## Expected Behavior
Remove component from remote scope

## Actual Behavior
error: unexpected network error has occurred.  original message: error: component <username.export>/dir/component found in the index.json file, however, is missing from the scope.
to get the file rebuild, please delete it at "/tmp/bithub/5c52a36e****d60012916a72/index.json". This error should have never happened.

## Steps to Reproduce the Problem
  1. bit remove <username.export>/dir/component
  2. bit remove <username.export>/dir/component --remote

## Specifications
  - Bit version: 14.1.0
  - Node version: 9.9.0
  - npm / yarn version: npm 6.9.0
  - Platform: mac
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by davidfirst** [comment]
@namieluss , please send the full path you got to amit@bit.dev, so @amitgilad3 , will be able to delete the path from the server.
Regardless, I'm going to work on a long term solution for this issue, so I leave it open until a fix is made.
