### ISSUE TITLE
Should tag only once, for bit tag -a

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1626]
I modified two components:
* playground-client
* iframe/communicator

where _playground-client_ depends on _iframe/communicator_.

Oddly enough, when I ran ```bit tag -a```, _playground-client_ got two versions.
I'm guessing it is one for the dependency update, and another for the modification, but it still weird.

## Expected Behavior
_playground-client_ should have tagged as v0.0.4 only.

## Actual Behavior
iframe/communicator. versions: 0.2.11 ... ok
playground-client. versions: 0.0.4, **0.0.5** ... ok

## Steps to Reproduce the Problem
```
web git/master*  
❯ bit import bit.capsule/iframe/communicator 

successfully ran yarn install at /Users/kutner/Documents/Projects/bitsrc/web/src/bit-components/iframe/communicator 

successfully imported one component
- up to date bit.capsule/iframe/communicator  
                                                                                                                                            
web git/master*  8s
❯ bit status                                 
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > iframe/communicator ... ok
     > playground-client ... ok
                         

staged components
(use "bit export <remote_scope> to push these components to a remote scope")

     > playground-client. versions: 0.0.4 ... ok
                                                                                                                                            
web git/master*  
❯ bit tag -a
⢀⠀ importing components(node:24684) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2 component(s) tagged | 0 added, 2 changed, 0 auto-tagged
changed components:  bit.capsule/playground-client@0.0.5, bit.capsule/iframe/communicator@0.2.11
                                                                                                                                            
web git/master*  6s
❯ bit status
staged components
(use "bit export <remote_scope> to push these components to a remote scope")

     > iframe/communicator. versions: 0.2.11 ... ok
     > playground-client. versions: 0.0.4, 0.0.5 ... ok
                                                                                                                                            
web git/master*  
❯ bit untag --all
2 component(s) were untagged:
bit.capsule/playground-client. version(s): 0.0.4, 0.0.5
bit.capsule/iframe/communicator. version(s): 0.2.11
                                                                                                                                            
web git/master*  
❯ bit tag iframe/communicator
⡀⠀ importing components(node:24811) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2 component(s) tagged | 0 added, 1 changed, 1 auto-tagged
changed components:  bit.capsule/iframe/communicator@0.2.11
auto-tagged components (as a result of tagging their dependencies):  bit.capsule/playground-client@0.0.4
                                                                                                                                            
web git/master*  
❯ bit tag playground-client  
1 component(s) tagged | 0 added, 1 changed, 0 auto-tagged
changed components:  bit.capsule/playground-client@0.0.5
```

## Specifications

  - Bit version: 14.1.0
  - Node version: 11.13.0
  - npm / yarn version: 1.15.2
  - Platform: macOs

**Comment by itaymendel** [comment]
I think that the main confusion point here is that on every `tag` action, Bit runs the `auto-tag` process for all dependent components, to update their dependency graph.

In this case, the component `playground-client` had a staged version (`0.0.4), so the `bit tag -a` created version `0.0.5`.
When the `untag` command ran, it removed all staged versions correctly.
At the end, when you ran the final `bit tag iframe/communicator`, the `auto-tag` mechanism created `playground-client@0.0.4`. The changes tagged in `0.0.4` are in the dependency graph of `playground-client`, not in the implementation (it remains `modified`).

So the final `bit tag playground-client` created version `0.0.5`. This version contains both the new dependency changes and the changes in the implementation of it.

While there is a discussion to be made about the outputs of `bit tag`, and make them more readable - This flow works and operated as designed. I'm closing this issue, as it's a non-issue.

I think that a better approach would be to better explain what happens with a better structured `bit tag` outputs.
