### ISSUE TITLE
bit init always indent package.json to 4 spaces, should respect original formatting

### ISSUE THREAD

**Issue by Bnaya** [teambit/bit#1630]
## Expected Behavior
After bit init, the diff should be:
```diff
diff --git a/package.json b/package.json
index c3c4c05..6223055 100644
--- a/package.json
+++ b/package.json
@@ -5,5 +5,10 @@
   "license": "MIT",
   "devDependencies": {
     "bit-bin": "^14.1.0"
+  },
+  "bit": {
+    "env": {},
+    "componentsDefaultDirectory": "components/{name}",
+    "packageManager": "npm"
   }
 }

```

## Actual Behavior
But diff is:
```diff
diff --git a/package.json b/package.json
index c3c4c05..434da9d 100644
--- a/package.json
+++ b/package.json
@@ -1,9 +1,14 @@
 {
-  "name": "myrepro",
-  "version": "1.0.0",
-  "main": "index.js",
-  "license": "MIT",
-  "devDependencies": {
-    "bit-bin": "^14.1.0"
-  }
-}
+    "name": "myrepro",
+    "version": "1.0.0",
+    "main": "index.js",
+    "license": "MIT",
+    "devDependencies": {
+        "bit-bin": "^14.1.0"
+    },
+    "bit": {
+        "env": {},
+        "componentsDefaultDirectory": "components/{name}",
+        "packageManager": "npm"
+    }
+}
\ No newline at end of file
```

## Steps to Reproduce the Problem
run:
```bash
mkdir myrepro && cd myrepro && yarn init -y && yarn add -D bit-bin && git init && git add package.json yarn.lock && git commit -m "initial commit" && yarn bit init  && git diff
```

## Specifications

  - Bit version: 14.1.0
  - Node version: v8.16.0
  - npm / yarn version: 1.15.2
  - Platform: Mac
  - Bit compiler (include version): ?
  - Bit tester (include version): ?

**Comment by davidfirst** [comment]
Maybe the current indentation should be detected and used for writing.
Seems like that's how it's implemented by NPM in the following commit:
https://github.com/npm/npm/commit/64b67f00

So, if a user has its package.json with 2 spaces, it'll preserve it and not change it to 4, and vice versa. The default I guess should be 2, similar to NPM default.

cc @GiladShoham

**Comment by GiladShoham** [comment]
@davidfirst That's something we just discussed yesterday.
It should respect the original indentation and set the default to two sound reasonable to me.

**Comment by Bnaya** [comment]
Thanks :)
