### ISSUE TITLE
Improved output for the `bit watch` command

### ISSUE THREAD

**Issue by odedre** [teambit/bit#1634]
## Description
when running bit watch on an imported component, the output isn't clear. see screenshot.

## Expected Behavior
I think there should be better separation between component name and files in that component

## Actual Behavior
- it's an object of components with arrays of files
![Screen Shot 2019-05-15 at 5 52 02 PM](https://user-images.githubusercontent.com/15064762/57785319-32775280-773a-11e9-8ab3-7dde0c60a486.png)

## Steps to Reproduce the Problem

  1. import a component
  2. run bit watch
  3. see output

## Specifications

  - Bit version: 14.1.0
  - Node version: 10.12.0
  - npm / yarn version: 1.15.2
  - Platform: macOs
  - Bit compiler (include version): bit.search/ts-compiler@0.0.2
  - Bit tester (include version): bit.envs/testers/mocha@0.0.17

**Comment by itaymendel** [comment]
I totally agree with you on this one. I think that the baseline for a proper `watch` output for Bit should:

* Start with a summary of the workspace
  * Bit version
  * Node version
  * Number of components in WS (list them?)
* For each modification:
  * List the components Bit needs to rebuild
  * For each component list the files that were modified (that caused the re-build)
* When the `build` process finished running:
  * List the rebuilt components
  * For each component list the built files
  * Provide status for each component build (pass/fail)
  * If the build failed - prompt the error message

**Comment by GiladShoham** [comment]
@itaymendel I don't see why bit/node version are necessary for the output.
I would start with something like:
`watching X components`
or
```
watching 
comp 1
comp 2
comp 3
```
about after the build process, I'm not sure if we want to aggregate errors or just show the first we got.
All the other sounds good to me

**Comment by itaymendel** [comment]
The main reason I want versions and stuff is that usually, this command runs from another terminal, and perhaps... for some reason there's an env-var that made the version different for node or bit.

As for aggregate errors or not - I still haven't decided on how the output is structured. Trying to figure out what makes sense as an output for the command. Then we'll decide on the how it is presented :)

**Comment by GiladShoham** [comment]
> The main reason I want versions and stuff is that usually, this command runs from another terminal, and perhaps... for some reason there's an env-var that made the version different for node or bit.

Yes I can understand that. No problem, we can make it.

**Comment by itaymendel** [comment]
```js
bit binary version: <version>
node version: <version>
started watching for component changes to rebuild
running build for <component id>
      <path to dist>.js
      <path to dist>.js
running build for <component id>
      <path to dist>.js
```

@GiladShoham ?

**Comment by GiladShoham** [comment]
@itaymendel We currently have a --verbose flag, we use for output all the files we watch.
Let's add it to the specs. (also with the names of the components)

**Comment by davidfirst** [comment]
The output has been improved by the commit above. PR https://github.com/teambit/bit/pull/1846.
The list of all components and their paths that going to be watched is printed only when `--verbose` is used.
