### ISSUE TITLE
Inconsistency when importing dependency with a different version

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#1638]
Assuming there are two components `is-string` and `is-type`. Both have versions: 0.0.1 and 0.0.2. `is-string` depends on `is-type`. 

### Scenario 1: importing `is-string@0.0.1`, then importing `is-type@0.0.2`
So, the dependency `is-type` is imported with a newer version after the workspace has the dependent.

**installing dependencies as components**
status is modified.
bit-show of `is-string` shows `is-type` dependency as 0.0.2.
Filesystem: is-string uses is-type@0.0.2. (nested is-type@0.0.1 is deleted).

**installing dependencies as NPM packages**
status is modified.
bit-show of `is-string` shows `is-type` dependency as 0.0.2.
Filesystem: is-string uses is-type@0.0.1. (package is-type@0.0.1 is nested inside is-string/node_modules).

This is a bug. It physically uses v0.0.1 from the FS. However, bit-show and bit-status display it as if it uses v0.0.2. (changing package.json of is-string to have is-type@0.0.1 instead of the relative path, fixes it to have them all as 0.0.1).

### Scenario 2: importing `is-type@0.0.2`, then importing `is-string@0.0.1`
**installing dependencies as components**
status is not modified.
bit-show of `is-string` shows `is-type` dependency as 0.0.1.
Filesystem: is-string uses is-type@0.0.1.

**installing dependencies as NPM packages**
status is not modified.
bit-show of `is-string` shows `is-type` dependency as 0.0.1.
Filesystem: is-string uses is-type@0.0.1. (package is-type@0.0.1 is nested inside is-string/node_modules).
is-string package.json has is-type with the version 0.0.1.

### Scenario 3: importing `is-string@0.0.1` and `is-type@0.0.2` at the same time
(e.g. `bit import is-string@0.0.1 is-type@0.0.2`). 
Behavior is exactly the same as scenario 2 for both, local and NPM.
For this scenario, the order doesn't matter. it works the same for `bit import is-type@0.0.2 is-string@0.0.1`

### Conclusion
1. Scenario 1 is not consistent between installing as packages and as components. Installing as packages, it keeps using the older dependency, however, if it installs as components it uses the newly imported dependency.
1. Scenario 1 and scenario 2 are not consistent. It matters whether importing the dependency first then the dependents or the vice versa. It might be fine and desirable but not sure if it's intuitive. 
1. there is a bug in scenario 1, when installing as packages, see there the details.

GiladShoham , itaymendel , it needs your output.

**Comment by GiladShoham** [comment]
@davidfirst Great summery.
We should also check the opposite version behavior.
I mean is-string@0.0.2 and is-type@0.0.1. (for all 3 cases)

**Comment by davidfirst** [comment]
@GiladShoham , I checked all 3 cases and it works exactly the same. 
Meaning, as long as the dependent has one version of the dependency and the dependency imported directly with a different version, you'll get the results of the 3 cases above.
It doesn't matter what version of the dependency is now imported, whether it's a newer version or older version than what the dependent has.

**Comment by GiladShoham** [comment]
@davidfirst Thanks for checking it.
We should discuss it and decide on the desired behavior.

**Comment by itaymendel** [comment]
what ended up implemented - imported versions of components are resolved from workspace.
