### ISSUE TITLE
Article typos

### ISSUE THREAD

**Issue by yairEO** [teambit/bit#1643]
Hi, I have been reading some articles by Bit and had found quite a lot of typos. Just now found some in this article: (I will probably find more)

https://blog.bitsrc.io/how-to-easily-share-and-consume-react-components-using-bit-f53fb9463105

## Typos:

> **When we to also** consume the components and contribute to the components we will use the Bit option.

I suggest: _"When wanting to consume **and** contribute to certain components Bit option should be used."_

-----

> install the component we need directly without pulling **in the whole** components in the react-components library.

I suggest: _"...install a specific component, out of a bunch, without the need to pull the whole react-components library"_

-----

> So the src/components/table/Table.react.js

There is nothing after that line. missing a whole section apparently...

**Comment by jonisar** [comment]
Thanks, Yair, we'll take a look! :) Thanks for the heads up.
