### ISSUE TITLE
requiring component with require @bit syntax gets broken when done by author with shared-dir

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#1647]
## Expected Behavior
Generated link for author inside node_module should point to the component after sharedDir is stripped.

## Actual Behavior
The generated link on node_modules includes the entire path from the root of the workspace.
As a result, when another component requires this component using a module path (require '@bit/module-name/path-to-the-file') and the last component is exported and imported somewhere else, the link is broken. See the steps to reproduce for more info.

## Steps to Reproduce the Problem

  1. Create an empty file `utils/is-string.js`.
  2. tag and export. It'll create a link in `node_modules/remote-scope/utils/is-string.js`
  3. create another file `bar/foo.js` with the content `require('@bit/remote-scope/utils/is-string.js');`
  4. tag and export.
  5. create a new workspace, import `foo` component.
  6. run `bit status`.
You'll get an error:
```
     > foo ...  issues found
       missing components (use "bit import" or your package manager to make sure all components are installed):
          foo.js -> remote-scope/utils/is-string
```

It happens because when importing `foo`, it installs `utils/is-string` as an NPM package, which Bit serves to the registry after isolating it and stripping the shared dir. As a result, in the package, the 'utils' directory is stripped and the `require` statement of `foo` component (`require('@bit/remote-scope/utils/is-string.js');`) is broken.

The solution probably should be to generate the links for the author only after stripping the sharedDir.

## Specifications

  - Bit version: 14.1.1
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

@GiladShoham , makes sense?

**Comment by GiladShoham** [comment]
Yes, that makes sense.
The link should be clean as possible always since we want the same link across workspaces. 
And everything related to the author workspace should not be part of the link.

**Comment by itaymendel** [comment]
omitting the `@bit` prefix from components. closing this issue.
