### ISSUE TITLE
adding compiler to a specific component

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1650]
I wanted to add compiler to a specific component. This is now possible using the new configuration file:
https://docs.bit.dev/docs/conf-files.html#setting-specific-component-configurations

I was wondering, how can I do this using the BIT cli?

**Comment by davidfirst** [comment]
@KutnerBitsrc , you can't achieve this using the CLI as of now.
Not sure if there is such a task in the roadmap. @itaymendel ?

**Comment by KutnerBitsrc** [comment]
I see. Looking forward for this feature. :)

**Comment by itaymendel** [comment]
resolved in the upcoming version for Bit. closing for now.
