### ISSUE TITLE
bit eject doesn't remove the dist folder

### ISSUE THREAD

**Issue by odedre** [teambit/bit#1656]
## Expected Behavior
dist folder should be removed

## Actual Behavior
source folder removed, dist folder was not.

## Steps to Reproduce the Problem

  1. create react app
  2. specify different folder for dist. add the following to your package.json:
      "bit": {
        "env": {},
        "componentsDefaultDirectory": "components/{name}",
        "packageManager": "npm",
        "dist": {
          "entry": "components",
          "target": "src/bit-dist"
        }
      }
  3.bit import open-apis.apis/imdb-api
  4. bit eject imdb-api
  5. `bit-dist` folder stays while `components` stays behind.

## Specifications

  - Bit version:14.1.1
  - Node version:v10.15.3
  - yarn version: 1.13.0
  - Platform: macOs
  - Bit compiler (include version): bit.envs/compilers/typescript@3.0.0
  - Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by davidfirst** [comment]
Fixed. The component directory inside `dist` is now removed.
By the way, this issue happened not only with `eject` command but also with `remove` command. 
(they use the same function to remove the files).
