### ISSUE TITLE
bit ls remote scope doesn't work if bit isn't initialised 

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1657]
## Expected Behavior
 bit ls [owner].[scope] should work with out initialised bit workspace. 

## Actual Behavior
The following error appears.
workspace not found. to initiate a new workspace, please use `bit init`

## Steps to Reproduce the Problem
  1.  run `bit ls qballer.rss-reader` when outside a bit workspace.
  2. get error 

## Specifications

  - Bit version: 14.1.1
  - Node version: 10.11.0
  - npm / yarn version:  6.8.0
  - Platform: MacOS
  - Bit compiler (include version): N/A
  - Bit tester (include version): N/A

**Comment by itaymendel** [comment]
This will be resolved when we merge [this feature](https://github.com/teambit/bit/tree/feature/interactive-init).

**Comment by GiladShoham** [comment]
@itaymendel They are not related. This is a result of the migration step which is done during bit list.
I'll solve this regardless of the interactive init.

**Comment by davidfirst** [comment]
Implemented as part of https://github.com/teambit/bit/issues/1837.
Merged into master.
