### ISSUE TITLE
Enable removing components from remote and local with the same command

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#1678]
## Expected Behavior
An option to remove a component locally and remotely by running one command

## Actual Behavior
Two commands are needed.
`bit remove my-component`
`bit remove my-component --remote`

## Implementation details
Add a flag `--local` to remove components locally. Then, require `remove` command to get either `--local` or `--remove` flag. 
This way, it'll be possible to use both flags to remove from both locally and remotely: `bit remove my-component --local --remote`.

**Comment by itaymendel** [comment]
related to #1655

**Comment by itaymendel** [comment]
resolved and deployed. closing issue.

**Comment by davidfirst** [comment]
@itaymendel , are you sure it has been resolved?

**Comment by itaymendel** [comment]
irrelevant. we changes how remove works completely.
