### ISSUE TITLE
missing declaration for recursive dependencies

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#1680]
Just to make clear: this is happening when I consume the package using npm.
It does not seem to be a problem with _bit-cli_.
I am wondering how I should author the component so this would not happen.

I created a typescript component ```bit/bit.javascript.template.react```, built using env compiler [bit.envs/compilers/typescript](https://bit.dev/bit/envs/compilers/typescript).
When I installed the package using npm, I got this error:

```
TypeScript error in /private/tmp/test02/node_modules/@bit/bit.javascript.template.react/react-template.ts(1,28):
Could not find a declaration file for module '@bit/bit.javascript.default-generator.react'. '/private/tmp/test02/node_modules/@bit/bit.javascript.default-generator.react/dist/react/react-default-code.js' implicitly has an 'any' type.
  Try `npm install @types/bit.javascript.default-generator.react` if it exists or add a new declaration (.d.ts) file containing `declare module '@bit/bit.javascript.default-generator.react';`  TS7016
```

I did some research, and it seems that the Create React App project detects the index.ts file, and use it instead of ```"main": "dist/index.js"``` at the package.json.
I think it is **the type checker that is causing the problem**. It somehow detects the index.ts file and use it to imply types.

I know the Typescript compiler is not generating the .d.ts file it should, so I expected the whole template.react component to fail type checking, and I would have to write a module declaration file.
Instead, Create React App detects types, and throws errors for the _recursive_ modules!

It seems my options are as follows:
  1. Get a decent compiler that generates d.ts files (which will take some time)
  1. Enforce TS and index.ts for all of my components (not going to happen for old components)
  1. Remove "implicit <any>" warning (bad).
  1. Exclude type checking for node_modules (doesn't work :( :( )
  1. Move index.ts to a subfolder.
  1. Remove index.ts altogether :(

I went with removing the index.ts file. :(

## Expected Behavior
types should be included with each packages.
should not get type errors for dependencies I don't directly use.

## Steps to Reproduce the Problem

  1. Create component with index.ts, which depends on components without types. (use bit/bit.javascript.template.react . sorry, it's private) 
  1. Create a Create React App, with **Typescript**
  1. yarn add <package>.
  1. run yarn build
--> should get error
```
TypeScript error in /private/tmp/test02/node_modules/@bit/bit.javascript.template.react/react-template.ts(1,28):
Could not find a declaration file for module '@bit/bit.javascript.default-generator.react'. '/private/tmp/test02/node_modules/@bit/bit.javascript.default-generator.react/dist/react/react-default-code.js' implicitly has an 'any' type.
  Try `npm install @types/bit.javascript.default-generator.react` if it exists or add a new declaration (.d.ts) file containing `declare module '@bit/bit.javascript.default-generator.react';`  TS7016
```

## Specifications

  - Bit version: 14.1.1
  - Node version: 12.1.0
  - npm / yarn version: 1.16.0
  - Platform: mac ox
  - Bit compiler (include version): https://bit.dev/bit/envs/compilers/typescript

**Comment by itaymendel** [comment]
A new version for the TS compilers is due today/tomorrow. It handles generating type definitions.
I'll ping here when it's up so you can try it.
