### ISSUE TITLE
extend compile (feature)

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1687]
As part of developing the typescript compiler in #1663 I need a small API update.
`compile(files, distPath)` will become `compile(files, distPath, extras)` where extras is `{main : <ref to main vinyl>}`. This will allow me to improve performance greatly and emit .d.ts files. There is still a way to go, so that is why I suggest this structure. It will allow us to add more API's if needed.  

Many users can benefit from this.

**Comment by davidfirst** [comment]
@qballer , turns out there is already a third parameter `context` to the `compile` function.
It has the following data:
```
const context: Object = {
        componentObject: component.toObject(),
        rootDistDir,
        componentDir
      };
```
The componentObject has the entire component data including the main file, so all you need is `context.componentObject.main`.

**Comment by qballer** [comment]
That's awesome, I will test it out and close this, if it's a non issue.

**Comment by qballer** [comment]
I've tried the API and it works great, thanks.
