### ISSUE TITLE
Distribute Bit as a binary

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1692]
Bit relies on the installed node version installed on a machine. This forces Bit to keep support alive for node 6 (even though it's no longer maintained), as many projects still use it. However, much of the eco-system has moved passed it, and many of Bit's dependencies no longer support node 6.

By packing a node version as part of Bit, we can control Bit's runtime and upgrade dependencies.

In addition to that, the binary should be available to install on all platforms using their dedicated standard tooling. For example - `apt-get` for Debian distros, `yum` for CentOS/RH, downloadable exec for windows, etc...

**Comment by itaymendel** [comment]
relevant PR https://github.com/teambit/bit/pull/1352

**Comment by GiladShoham** [comment]
Different issues for brew and windows have been created.
see:
https://github.com/teambit/bit/issues/1868
https://github.com/teambit/bit/issues/1869
