### ISSUE TITLE
unable to find path in the dependencies relativePaths

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1696]
## Expected Behavior
Bit status should tell me that I have a missing dependency

## Actual Behavior
Getting an error `unable to find path in the dependencies relativePaths`

## Steps to Reproduce the Problem

  1. clone `https://github.com/teambit/bit.envs`
  1. move to 177f86772b2b92aa97585f912fe5dcd4164301be hash
  1. install everything needed
  1. run `bit status`

This solved by bit adding `components/internal/typescript-base-compiler`

## Specifications

bit version   : 14.1.2-dev.6
  node version  : v8.10.0
  npm version   : 6.8.0
  yarn version  : 1.9.4
  platform      : darwin

**Comment by ranm8** [comment]
@davidfirst @GiladShoham any idea what is the root cause for this issue? trying to figure out what we can do to prevent such issues from happening in the future by design.

**Comment by GiladShoham** [comment]
I'll check this again, it's very old. not sure it's still relevant

**Comment by davidfirst** [comment]
@ranm8 ,  @GiladShoham , this error won't be relevant for Harmony unless `--allow-relative-paths` was used. I wouldn't focus on it.

**Comment by GiladShoham** [comment]
I agree with @davidfirst 
I would even close it @ranm8

**Comment by ranm8** [comment]
OK, closing.
