### ISSUE TITLE
show hidden commands as experimental (feature)

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1697]
It would be nice if hidden commands will be discoverable via the CLI so users (such as myself) will be able to consume them. I know they are hidden with a reason as we don't want to commit ourself to API's we aren't sure, but this will allow me to tap in to new possibilities. 

something along the lines of `bit --help-experiment`.

**Comment by itaymendel** [comment]
I agree that it's a good way to expose commands which are not yet fully stable and potentially not future-proof.
We can include all Bit's remote commands there as well, and rename the flag to `--help-verbose` or something.

**Comment by itaymendel** [comment]
we're already doing it.
see about `bit graph` and `--dependents/dependencies` flags for `bit show` and `bit import`.

this is already an integral part of `bit --help`.
