### ISSUE TITLE
Add StencilJS compiler - Feature request

### ISSUE THREAD

**Issue by jdnichollsc** [teambit/bit#1707]
Hi guys,
This is a feature request to include **stencil.js** 1.0 as compiler

On the other hand, I tried `bit add src/components/* --main src/components/{PARENT}/{FILE_NAME}.tsx --tests src/components/{PARENT}/{FILE_NAME}.spec.tsx` but I have this issue:
```
error: the components index, models does not contain a main file.
please either use --id to group all added files as one component or use our DSL to define the main file dynamical
ly.
see troubleshooting at https://docs.bit.dev/docs/isolating-and-tracking-components.html#define-a-components-main-
file
```
This is my repo => https://github.com/proyecto26/ion-phaser

Let me know,
Juan

**Comment by itaymendel** [comment]
Hi @jdnichollsc , 

Both components in your projects are structured differently. I'm not seeing a way to abstract the way they are structured for a single `bit add` command to work correctly. For example, `ion-phaser`'s main file is `ion-phaser.tsx` and `models`'s is `index.js`. Your `add` syntax will not match both. So it fails all. Additionally, the spec file is named `ion-phaser.e2e.ts` and in your command, you asked Bit to look for a file with `spec`.

For your case, I'd recommend tracking each file separately.

As for stencil support, please open the request in [this](https://github.com/teambit/bit.envs) repo.

**Comment by jdnichollsc** [comment]
Ohh yes, I did that yesterday, thanks! Let me request StencilJS compiler from the other repo 👍
