### ISSUE TITLE
importing entire collection is very slow

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1710]
## Expected Behavior

Importing an entire collection should not feel like its hanging forever.

## Actual Behavior

It seems like the process of getting all the components to import is VERY slow.
After that - the import process is rather fast. But together they are both slow.

## Steps to Reproduce the Problem

  1. `bit import bit.utils/*`

## Specifications

  - Bit version: 14.1.2
  - Node version: 11.10.0
  - npm / yarn version: 6.7.0
  - Platform: macos

**Comment by davidfirst** [comment]
There were two issues.
1. performance. It took 166 seconds to complete. It has been fixed to reduce the round trips to the SSH. Now it takes 80 seconds. Among these 80 seconds, 60 seconds were used to install packages.
2. loader message. It kept showing  'listing remote components', even when it started to import. This has been fixed as well with the commit above.
