### ISSUE TITLE
Support test/spec file conventions

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1715]
When tracking components and files with Bit, the user is forced to use the `--tests` flag to annotate which of their files contains tests. However, in most cases, there are several file name conventions that teams use to distinct the tests from the implementation.

* `*.spec.js|ts|tsx`
* `*.specs.js|ts|tsx`
* `*.test.js|ts|tsx`
* `*.tests.js|ts|tsx`
* `*.e2e.js|ts|tsx`

When a user tracks files, and some of the files fit these naming conventions Bit should add the files as test files. If in the same `add` command the user used the `--tests` flag Bit should not use this strategy.

**Comment by GiladShoham** [comment]
I would remove the e2e case, usually, e2e tests require some external setup which won't work in bit.dev ci.

**Comment by itaymendel** [comment]
But if they are tracked alongside a component and not marked as `devDependencies` they might include a bunch of redundant dependencies to the component and increase its bundle size.
I don't mind the testers not able to run e2e, I just don't want their `devDeps` defined as `deps`.

**Comment by davidfirst** [comment]
@itaymendel , @GiladShoham , this is implemented in the commit above. 
However, before merging it I realized that a user doesn't have an option to opt-out. If for some reason, a component has a non-test file named `foo.spec.js`, the user can't change it back from a test file to a normal file.

This is related to the following two issues:
https://github.com/teambit/bit/issues/1649 => @itaymendel , added some suggestions on how to enable editing component that was added already. 
https://github.com/teambit/bit/issues/1850 => recently opened with the same issue.

I believe we should solve it first before merging this.

**Comment by itaymendel** [comment]
@davidfirst while I don't think it is related to #1580 you are correct.
lets hold this feature from being merged. I would want to spend some more time thinking about it.

**Comment by KutnerUri** [comment]
any progress?

btw, I think we could `chmod`-like syntax, e.g.
```
bit filetype +t ./base-button/button.spec.tsx
```

**Comment by itaymendel** [comment]
implemented in v15
