### ISSUE TITLE
vscode Extension

### ISSUE THREAD

**Issue by williamluke4** [teambit/bit#1717]
Is there any plan on a vs code extension? I been playing around here https://github.com/williamluke4/vscode-bitsrc but I don't know how bit works.. 

Currently, I'm just reading the `.bitmap` file and creating a tree to display the components and their scopes.

Is anyone willing to help me out or point me in the right direction?

**Comment by williamluke4** [comment]
Ideas

- Add the ability to tag and export components using the viewer 
- Display Status of Components
- Add Bit Commands to VSCode Command Pallet

**Comment by itaymendel** [comment]
Hi @williamluke4 , I think that an IDE plugin for Bit can be truly awesome.
We have planned on implementing something like it, but haven't found the time and resources to kickstart such a project.

Bit has a programmatic API, but at the moment it is not documented.
I can try and compile a shortlist of some of the basic APIs for the functionality you have suggested.

**Comment by williamluke4** [comment]
@itaymendel  That would be great thanks. 

> I think that an IDE plugin for Bit can be truly awesome.

Yeah I think that I would really help people get started with **bit**

**Comment by WassimBenzarti** [comment]
I'm happy to announce that I started on working on such extension that does exactly what's stated in this issue. I want to thank @davidfirst who gave me some orientation about the project.

Checkout the repository [here](https://github.com/WassimBenzarti/bitdev-vscode-extension)
