### ISSUE TITLE
Thoughts/Ideas on Figma Plugin

### ISSUE THREAD

**Issue by williamluke4** [teambit/bit#1724]
Blog post on [Figma Plugins](https://www.figma.com/blog/plugins-are-coming-to-figma/?utm_content=buffer4c6db&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer)
## Ideas
1.  Generate React Code and Export to Bit

**Comment by itaymendel** [comment]
Previous (and possibly relevant) work for components in Framer - https://github.com/teambit/bit/issues/1662
