### ISSUE TITLE
bit build shows relative file paths sometime

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1725]
## Expected Behavior
Bit should only show the full paths of the dist files.

## Actual Behavior
Bit show relative paths for d.ts files.

## Steps to Reproduce the Problem

  1. clone https://github.com/atto-byte/mui-daterange
  1. (make sure to set the react-typescript version to 3.0.6)
  1. run bit `build`
  1. see there are correct paths:
```
/private/tmp/mui-daterange/dist/src/date-range/Calendar.js.map
/private/tmp/mui-daterange/dist/src/date-range/Calendar.js
```
  1. and wrong ones: `dist/src/date-range/index.d.ts`

see more background on this issue: https://github.com/teambit/bit/issues/1718
The compiler returns the same file (with the same content and path) few times.
I check all the paths of the duplicate entries returns from the compiler and they are all good.
but it still might be related.

## Specifications

  bit version   : 14.1.4-angular.1
  node version  : v8.10.0
  npm version   : 6.8.0
  yarn version  : 1.9.4
  platform      : darwin

**Comment by davidfirst** [comment]
After some investigations, it happens because the compiler generates the same file index.d.ts multiple times. See below the files I got from the compiler before any other manipulation.
What's happening is that at some point, all dists files are sent to DataToPersist class with the relative paths, and later on, while they're all added to that class, the paths are changed to be absolute. This class doesn't add duplicate files, so only one instance of index.d.ts is actually changed to be absolute. All others are ignored.
Any reason why there are multiple occurrences of the same file?


```
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/Control.js.map
/tmp/mui-daterange/dist/src/select/components/Control.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/Menu.js.map
/tmp/mui-daterange/dist/src/select/components/Menu.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/MultiValue.js.map
/tmp/mui-daterange/dist/src/select/components/MultiValue.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/NoOptionsMessage.js.map
/tmp/mui-daterange/dist/src/select/components/NoOptionsMessage.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/Option.js.map
/tmp/mui-daterange/dist/src/select/components/Option.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/Placeholder.js.map
/tmp/mui-daterange/dist/src/select/components/Placeholder.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/SingleValue.js.map
/tmp/mui-daterange/dist/src/select/components/SingleValue.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/ValueContainer.js.map
/tmp/mui-daterange/dist/src/select/components/ValueContainer.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/index.js.map
/tmp/mui-daterange/dist/src/select/components/index.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/components/inputComponent.js.map
/tmp/mui-daterange/dist/src/select/components/inputComponent.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/index.js.map
/tmp/mui-daterange/dist/src/select/index.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/styles.js.map
/tmp/mui-daterange/dist/src/select/styles.js
/tmp/mui-daterange/dist/src/select/index.d.ts
/tmp/mui-daterange/dist/src/select/README.md
```

**Comment by GiladShoham** [comment]
Maybe @qballer will know to answer why this compiler returns the same files multiple times.
Anyway, we should know to handle it better (ignore the same file also in the outputs)

**Comment by itaymendel** [comment]
resovled in v15
