### ISSUE TITLE
Feature: annotate to import dependencies as components (instead of packages) in the 'bit import' command

### ISSUE THREAD

**Issue by odedre** [teambit/bit#1732]
### Description
I would like a flag that tells bit to import all the dependencies of an imported component.
something like [this](https://docs.bit.dev/docs/conf-bit-json.html#savedependenciesascomponents),  but for a specific component.
### Describe the solution you'd like
component `A` has 3 component dependencies. I want to import `A` along with all the dependencies of `A`.
I would like something like the following command: 
**bit import oded.components/component-name --import-dependencies**

### Describe alternatives you've considered
currently I had to look at my components dependencies and import them one by one.

**Comment by davidfirst** [comment]
@odedre , would you expect to have the dependencies inside `components/.dependencies`, same as with https://docs.bit.dev/docs/conf-bit-json.html#savedependenciesascomponents ? 
Or, would you expect them to be imported directly?

**Comment by itaymendel** [comment]
I think that it should import dependencies to `dependenciesDirectory` (defaults to `components/.dependencies`).
This should allow better debugging for components - as you can easily import all the component's dependency graph and debug an issue locally. Instead of keep importing components as you debug, to figure out in which of the component's dependencies is the one causing an issue.

**Comment by GiladShoham** [comment]
@davidfirst He expects to import them directly.
For this graph
A -> B -> C he would expect the same as running: `bit import A B C`

**Comment by itaymendel** [comment]
@GiladShoham , this is what he is doing right now, as a workaround.
Doing what you suggested will add both `B` and 'C` as dependencies for the project (i.e. they will appear on the `package.json` file).

The flow for importing dependencies as components is usable when you have a bug somewhere in a component, and you are not sure if its in the immediate dependency or somewhere up in the dependency tree. So you want to import the source code of the entire tree and debug it.

**Comment by GiladShoham** [comment]
@itaymendel yes I know, I just tried to explain it to @davidfirst :)
