### ISSUE TITLE
combine bit eject and npm install in one command

### ISSUE THREAD

**Issue by odedre** [teambit/bit#1733]
### Description

I imported a component, fixed it and exported the updated component back to my remote collection. is there a command that replaces the imported component with the npm package?
something that combines `bit eject <component-id>` and `npm install <component-id>`

### Describe the solution you'd like
`bit eject <component-id> --install`

### Describe alternatives you've considered
`bit eject <component-id>`
`npm install <component-id>`

this fixed the issue but it would be nice to have it in a single command

**Comment by davidfirst** [comment]
@odedre , actually that's exactly what `bit eject` does :)
It removes the Bit component from the workspace, adds it as an NPM package and then run `npm install` of the main `package.json`.
Please re-open as a bug if it behaves differently.
