### ISSUE TITLE
Improve output for `add` command

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1739]
The current output of `bit add` does not do a good job in explaining what was added. Additionally, it fails to properly explain the structure of each of the components.

Suggested output:

* Annotate file type (main, test...)
* Suggest additional commands to follow up with
* Allways show full list of components tracked

Example:

```sh
$ bit add src/components/*
2 component(s) added
(use "bit status" to check dependency status)
(use "bit show" to get more information and "bit untrack" to remove components)

button:
  > src/components/button/index.js - main file
  > src/components/button/button.js
  > src/components/button/button.specs.js - test file

dropdown:
  > src/components/dropdown/index.js - main file
  > src/components/dropdown/dropdown.js
  > src/components/dropdown/dropdown-option.js
  > src/components/dropdown/dropdown.specs.js - test file
```

**Comment by GiladShoham** [comment]
I would use colors as well.
For example, colorize the main file. or colorize regular / test files differently.
And maybe I would separate regular / test files with a line
something like
```
dropdown:
  > src/components/dropdown/index.js - main file // colorize green
  > src/components/dropdown/dropdown.js
  > src/components/dropdown/dropdown-option.js
------------------------------------------------------------
  > src/components/dropdown/dropdown.specs.js - test file
```

**Comment by itaymendel** [comment]
I'm not sure about a separator line, but coloring will be a valid addition.
Moreover, perhaps adding some annotations to when I'm adding a file to a component? (ie - rerunning `bit add` with the `--id` flag).

Perhaps when adding a file we'll use `+` and when a file was not changed - `>` (I don't think there's a need to annotate the removal of a file).

```
dropdown:
  + src/components/index.js - main file
  > src/components/dropdown.js
```

**Comment by GiladShoham** [comment]
@itaymendel 
Regarding the coloring we should make sure it's not too colorful, it will heart the eyes.
About changes in components, I would go with 
+ for new
- for removal (or don't mention it)
nothing for unmodified
or
(a) for new
(r/d) for remove / delete
(u) for unmodified
