### ISSUE TITLE
Bit Roadmap

### ISSUE THREAD

**Issue by williamluke4** [teambit/bit#1744]
Is there currently a roadmap hiding somewhere?

**Comment by itaymendel** [comment]
There is no public roadmap for Bit. This will be resolved soon.

I would like to share some of the things we're doing right now (and will be released soon):

1. Isolated component development environment - Creating an isolated environment for components is one of Bit's main features. Until now this environment was managed behind the scenes, as an internal infrastructure for Bit. We're improving it with the goal to provide an actual development environment for each component for developers to use.
1. Extending support for Angular, Vue, Web components, etc.

Afterward, we'll focus on Bit's extendability:

1. Improving Bit's extension APIs - Bit's extension system is lacking many APIs. For example - passing configurations to the build/test environments. 
1. Component pipelines - Developers should be able to define as many pipelines for their components and control which extensions are triggered for each pipeline (for example - lint, build, pre-deploy). 
1. Improving Bit usability - Adding features like #1691 and interactive mode to simplify workflows.

Both the isolated component development environment improvements and an improved extension system facilitate an infrastructure update that will allow the team to start working on implementing a change management feature (similar to Git's pull request).

This is the most info I can give right now. I hope to publish a roadmap in the very near future. I'm keeping the issue open until then.

**Comment by yairEO** [comment]
@itaymendel 

> There is no public roadmap for Bit. This will be resolved soon.

It's been a year since the word "soon" was written... any  update?
