### ISSUE TITLE
Bit does not remove capsules on destroy/post build

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1745]
While testing the component isolation and building many components, my hard-drive is now full of a lot of unused capsules in the `/tmp` dir.

### Steps to Reproduce

1. build Bit from `master` branch and use it
1. track any component
1. run `bit build` and wait for it to finish
1. see that the temp directory of the isolated component is still available

### Expected Behavior

Isolated component directory should be removed after the build is done.

### Specifications

  - Bit version: build from `master`
  - Node version: 11.1
  - npm / yarn version:
  - Platform: macos

**Comment by davidfirst** [comment]
@itaymendel , @qballer , the question is who is responsible for deleting the capsule. 
The compiler creates the capsule, so it might make sense to hold the responsibility to close it. It can be easily done by calling the async `destroy()` method of the capsule. See an example below. 
I do see an advantage removing this burden from the compiler, however, with the extension system we might want to pass the capsule to another extension down the line, so automatically delete it won't be the desired behavior. 

An example:
```
return context.isolate().then(({ capsule, componentWithDependencies }) => {
    // do something with the capsule. 
    // once done, destroy it
    return capsule.destroy().then(() => {
      return files
 ...
```

**Comment by GiladShoham** [comment]
I talked with @itaymendel about it.
1. I agree that if the compiler is creating the capsule, he should destroy it. (I think that originally this bug wasn't about who is responsible but about the fact that destroy had a bug (but maybe the compiler just didn't call it).
2. I see the rationale of letting the compiler creating the capsule from 3 main reasons:
a. maybe he needs a capsule sometime and sometime not, it can be a matter of config or anything else. so creating a capsule always which is expensive operation is not efficient.
b. the compiler might want to create the capsule with different options like - install deps or not, write the packge.json or not etc'. building the capsule in one way in bit won't be flexible enough.
c. A compiler / extension might need more than one capsule for different operations. so we want to provide a way to create as many capsules as he needs.

**Comment by itaymendel** [comment]
I agree the extension should be the one responsible for destroying the capsule.
I'm closing the issue, as it's irrelevant to Bit.
@qballer , please update the extension according to @davidfirst 's note.
