### ISSUE TITLE
extension API should provide completion

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1753]
### Description
I'm trying to consume the capsule API and I need to resort to debugging in order to understand which API I can consume. Another option is to read the code in bit which makes it cumbersome to work with the capsule API.

### Describe the solution you'd like
It would be great if when consuming an extension API in general I would get completions. This would make the work of creating an extension much more discoverable.

**Comment by davidfirst** [comment]
@qballer , as to the Compiler API, I combined the interfaces and the types to one file, you can see it here:
https://github.com/teambit/bit/blob/master/src/extensions/compiler-api.js

**Comment by qballer** [comment]
I want code completions in the IDE. this is nice to read but doesn't help much

**Comment by qballer** [comment]
This isn't only for the capsule API but for all types of extension API. This is unresolved for me.

**Comment by itaymendel** [comment]
resovled in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
