### ISSUE TITLE
Compilers should be able to add keys to component's package.json

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1762]
### Description

Some compilers modify values in the `package.json` file. For example, ng-packagr needs to add the following keys:

```
"module": "...",
"es2015": "...",
"esm5": "...",
"esm2015": "...",
"fesm5": "...",
"fesm2015": "...",
"typings": "...",
"metadata": "..."
```

### Describe the solution you'd like

Bit should provide an API for a compiler to add values to the `package.json` file.  
There are two important things to note:

1. The compiler should modify the `package.json` during the `build` process.
1. When `bit build` runs and a compiler causes a modification to the `package.json` file - The component **must not be modified**.
1. There are several keys that a compiler must not be able to modify/create
    - name
    - version
    - main
    - dependencies
    - devDependencies
    - peerDependencies
    - license
    - bit

**Comment by davidfirst** [comment]
Implemented in https://github.com/teambit/bit/pull/1769.
To add properties to the package.json, just add a new property `packageJson` to the return result.

In the example below, a compiler adds `{ "foo": "bar" }` into the component `package.json`.
```
function compile(files, distPath) {
  const dists = files.map(f => doSomethingWhatever(f));
  return { dists, packageJson: { foo: 'bar' } };
}
```
