### ISSUE TITLE
Override after import all doesn't work for compiler

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1768]
### Describe the bug
I did `bit import qballer.ngx-bootstrap/*` when I overrided a new compiler version bit status was clean. I expected the components needed a build. 

### Steps to Reproduce

  1.` bit import qballer.ngx-bootstrap/*`
  2. Override new compiler version
  3. bit status
  4. output clean

### Expected Behavior
component changed. 

### Specifications

   bit version   : 14.1.4-dev.2
   node version  : v12.3.1
   npm version   : 6.9.0
   yarn version  : 1.16.0
   platform      : linux
  - Bit compiler (include version): "qballer.ng-stage/ng-packagr@0.0.5"
  - Bit tester (include version) :N/A

**Comment by GiladShoham** [comment]
@qballer Please provide the bit entry from package.json and specify where did you override it. in the root's package.json or in component one.

**Comment by GiladShoham** [comment]
if it's an imported component you should change it in the component's package.json

**Comment by qballer** [comment]
that is less then optimal if I just imported a scope. this may be 5000 components.

**Comment by itaymendel** [comment]
Changing the type from `bug` to `feature`.
`overrides` does not support imported components.

The reason we dropped it from the base feature was that this could potentially cause unwanted side effects. Say a project used `overrides` to add a `peerDependency` for all components, and for that, they used `*` as the overrides pattern. Now any time a component is imported to that project - Bit overrides its dependencies and adding a `peerDependency` to the imported component.

**Comment by itaymendel** [comment]
implemented a while ago. closing this issue.
