### ISSUE TITLE
Update dependency link files when bundling them

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1770]
### Description

Compilers like [ng-packagr](https://github.com/ng-packagr/ng-packagr) bundle all component files, including Bit's dependency link files (files that Bit generate to support relative requires - #1684 ) - if they are present.
The problem is that a pre-exported component has a different ID than after its first export (Bit adds the remote collection name to the component ID). This means that when the dist outcome of any pre-export build contains a bundled file that links to a component that will not exist once exported. For example:

Say we have two components, Foo and Bar. Foo requires Bar using a relative path. When Bit isolates the component in a capsule, it creates a dependency file for Bar in the location Foo's code expects it to be (Foo's code will be in the `.dependencies` directory - #1758 ) and its contents will be an import statement to `bar`. When ng-packagr bundles such project, it bundles the dependency link as well.
Now, when `bar` is exported, the actual component ID will be `<remote-name>/bar`, so when installing Foo, the package manager will install `<remote-name>/bar` as a dependency. However, the dependency link tries to import `bar`.

### Describe the solution you'd like

Dependency links are managed and handled by Bit. So it should handle detection and modification for them. This means that Bit should check if any dependency link file is bundled into the component's dist. If it finds any - it should ensure that it links to the correct component ID.

This process is similar to how Bit updates component-dependencies when exporting new components.

### Additional context

Normally, compilers like Babel don't need to bundle all the code and can transpile individual files. The introduction of ng-packager support needs the ability to modify the Bit's dependency files during export.

**Comment by davidfirst** [comment]
Implemented on PR https://github.com/teambit/bit/pull/1786.
