### ISSUE TITLE
install bit.dev in local server

### ISSUE THREAD

**Issue by shakercs** [teambit/bit#1778]
Hi I need to make my bit.dev in local server like https://bit.dev m how can I do this ?

**Comment by itaymendel** [comment]
Hi @shakercs , you can install a Bit remote server and use it to share components between projects. See the docs [here](https://docs.bit.dev/docs/bit-on-the-server.html#setting-up-a-bit-server).

The bit.dev application and its additional features (search engine, rendering, hosting, ci, automation, etc) are not a part of the OSS project.

**Comment by JGJP** [comment]
@itaymendel At this step I am asked to enter a username and password:
`bit remote add ssh://bit-username@bit-server:/opt/bit/first-scope`

What does this correspond to? It seems to fail no matter what I enter

**Comment by GiladShoham** [comment]
@JGJP That looks like something wrong with your setup.
I suggest starting with [bit-docker](https://github.com/teambit/bit-docker).
(It's also available in the [docker-hub](https://hub.docker.com/r/bitteam/bit-docker) )
Also, [this issue](https://github.com/teambit/bit-docker/issues/1) might be helpful for you
