### ISSUE TITLE
bit doesn't recognize dependencies in self reference use case

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1779]
### Describe the bug
When using `ngx-bootstrap` and adding accordion bit doesn't recognize dependencies when resolveModules properties is defined. 
 
### Steps to Reproduce

  1. clone ngx-bootstrap
  2. `npm i &&  npm run build` 
  3. define an alias for ngx-bootstrap to src 
  3. `bit add src/accordion`
  4. bit status 
  5. notice accordion doesn't have dependencies.

```
  "bit": {
    "env": {},
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm",
    "resolveModules": {
      "aliases": {
        "ngx-bootstrap": "src"
      }
    }
  }
```
### Specifications

  bit version   : 14.1.4-dev.6
  node version  : v12.3.1
  npm version   : 6.9.0
  yarn version  : 1.16.0
  platform      : linux

**Comment by davidfirst** [comment]
A little background. In this case, `npm build` writes into node_modules/ngx-bootstrap. 
So, when bit-javascript resolves dependencies, it doesn't use the custom-resolve, it handles it as a regular package.
When `npm build` wasn't running, the `node_modules/ngx-bootstrap` is missing, and then bit uses the custom-resolve logic.

**Comment by qballer** [comment]
I still think this is an issue. lets discuss this off-github and summarize.

**Comment by itaymendel** [comment]
@davidfirst @GiladShoham perhaps Bit should prefer resolving using `resolveModules` when available, instead of resolving via `node_modules`?

I agree with @qballer that we should tackle this issue. As it creates an inconsistent behavior. In this case, if I run `npm build` before `bit status`, Bit resolves dependencies differently.

**Comment by GiladShoham** [comment]
@qballer @itaymendel I agree.
We should resolve from our configuration before we resolve from node_modules FS content.
@davidfirst Let's change the strategy a bit.

**Comment by davidfirst** [comment]
Implemented according to the suggestions above.
