### ISSUE TITLE
Instructions to export component need to be fixed: word Jest should be jest

### ISSUE THREAD

**Issue by cpmech** [teambit/bit#1787]
When creating a new component (Export components from your own project), the example code in the documentation has an incorrect command.

Instead of `bit import bit.envs/testers/Jest --tester`, we should have `bit import bit.envs/testers/jest --tester` I.e. **J => j**

This happens the selecting Typescript and Jest under Choose your project's environment.

Pls see figure below:

![001](https://user-images.githubusercontent.com/9506388/60765829-c2ef6500-a0e3-11e9-96c9-f56b2ebcbef5.png)

**Comment by itaymendel** [comment]
fixed and deployed
