### ISSUE TITLE
peer deps are not installed correctly on isolate via compiler

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1789]
### Describe the bug

when creating a capsule for ngx / accordion - @angular/common is not installed (it's a peer dep) maybe peers are not installed? (*bit*) (edited)

### Steps to Reproduce

  1. running the custom ng-packager compiler on ngx/accordion
  1. look into the capsule

### Expected Behavior

@angular/common should be installed 

### Specifications

  - Bit version: master
  - Node version: 10 
  - Bit compiler (include version): custom

**Comment by davidfirst** [comment]
Problem was that the peerDependencies of the root package.json disappeared once `npm install` is running on that dir. 
It has been fixed by copying the peerDependencies into devDependencies once they got resolved.
