### ISSUE TITLE
components in capsule are copied instead of symlinked to .dependencies folder

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1791]
### Describe the bug

when creating a capsule for ngx accordion - utils and collapse are created under node_modules/@bit (as expected) but they are copies and not links to .dependencies folder

### Steps to Reproduce

  1. running the custom ng-packager compiler on ngx/accordion
  1. look into the capsule

### Expected Behavior

The @bit/[components] should be symlinks to .dependencies, not copies

### Specifications

  - Bit version: master
  - Node version: 10 
  - Bit compiler (include version): custom

**Comment by davidfirst** [comment]
@GiladShoham , I'm unable to reproduce. 
I tried both, creating a capsule by `bit isolate` and creating a capsule using `bit build`, the node_modules/@bit includes the symlinks.
```
➜  my-capsule git:(development) ✗ ll /var/folders/zk/qw7sjckx3gl284cwjmjx57vm0000gn/T/capsule-13125/node_modules/@bit
lrwxr-xr-x  1 davidfirst  staff  28 Jul  9 16:32 [1]  collapse -> ../../.dependencies/collapse
lrwxr-xr-x  1 davidfirst  staff  25 Jul  9 16:32 [2]  utils -> ../../.dependencies/utils
➜  my-capsule git:(development) ✗
```

**Comment by GiladShoham** [comment]
You should use node >= 10.16.0. Our compiler uses node api only available since this version. So you won't have npm that old as well because you will got npm 6.4.1 with this node version.

**Comment by GiladShoham** [comment]
I can't reproduce it as well now. probably fixed by another fix. closing.
