### ISSUE TITLE
dist content in capsule are nested in a [component-name] folder

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1793]
### Describe the bug

when creating capsule for ngx accordion it will nest the dists of the dependencies under [component-name] folder. aka - componentRoot/dist/[component-name]/distFiles
instead of componentRoot/dist/distFiles

### Steps to Reproduce

  1. running the custom ng-packager compiler on ngx/accordion
  1. look into the capsule

### Expected Behavior
The dist files should be under:
`componentRoot/dist/distFiles` rather than `componentRoot/dist/[component-name]/distFiles`

### Specifications

  - Bit version: master
  - Node version: 10 
  - Bit compiler (include version): custom

**Comment by davidfirst** [comment]
@GiladShoham , @qballer , that's another issue of the compiler.
In the example of primenx, I tried to build `accordion`, see below the output I got for the dependency `blockableui`, notice how all files have the prefix of the component name for some reason.

To convince you that it's not an issue with Bit, please search for `should write all dependencies dists into the capsule`, and mark the test as "only". Notice how the dist files in the dependencies don't have the prefix of the component name.
Just a tip, if you want to see the capsule directory during the build/tag, prefix your command with `BIT_LOG=Isolator.getInstance`. e.g. `BIT_LOG=Isolator.getInstance bit build accordion`.

```
blockableui
/Users/davidfirst/Downloads/primeng/dist/blockableui/bit-blockableui.d.ts
/Users/davidfirst/Downloads/primeng/dist/blockableui/bit-blockableui.metadata.json
/Users/davidfirst/Downloads/primeng/dist/blockableui/public_api.d.ts
/Users/davidfirst/Downloads/primeng/dist/blockableui/package.json
/Users/davidfirst/Downloads/primeng/dist/blockableui/bundles/bit-blockableui.umd.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/bundles/bit-blockableui.umd.js.map
/Users/davidfirst/Downloads/primeng/dist/blockableui/bundles/bit-blockableui.umd.min.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/bundles/bit-blockableui.umd.min.js.map
/Users/davidfirst/Downloads/primeng/dist/blockableui/fesm5/bit-blockableui.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/fesm5/bit-blockableui.js.map
/Users/davidfirst/Downloads/primeng/dist/blockableui/fesm2015/bit-blockableui.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/fesm2015/bit-blockableui.js.map
/Users/davidfirst/Downloads/primeng/dist/blockableui/src/app/components/common/blockableui.d.ts
/Users/davidfirst/Downloads/primeng/dist/blockableui/esm2015/bit-blockableui.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/esm2015/public_api.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/esm2015/src/app/components/common/blockableui.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/esm5/public_api.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/esm5/bit-blockableui.js
/Users/davidfirst/Downloads/primeng/dist/blockableui/esm5/src/app/components/common/blockableui.js
```

**Comment by GiladShoham** [comment]
@davidfirst It's indeed a compiler issue.
@qballer Is added this to the dist path inside the compiler. the reason is that otherwise, on the author env he has conflicts between the components. 
Since the dist file names / folders of each component are the same.
For example, each component has a package.json file and bundles, common, esm5, esm2015, fesm5, fesm2015 folders.
And all of them written to the same dist target (./dist)
The way he worked around this is to prefixed it in the compiler.
But this is not a good solution for my opinion, it will pollute the consumer forever.
A better solution will be to support special keys in dist target prop in bit config.
For example:
dist.target: 'dist/{componentName}'

**Comment by GiladShoham** [comment]
This is not a bit issue but compiler one.
A better solution as described in the last comment opened as a different issue - #1808
