### ISSUE TITLE
Major Issue - Component example shows blank screen

### ISSUE THREAD

**Issue by brendan-gunn** [teambit/bit#1794]
### Describe the bug
The component example shows a blank screen, where there should be some code. This is happening across all the components in the current repository and other public repositories.

A clear and concise description of the issue.

### Steps to Reproduce

  1.
  1.
  1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

  - Bit version:
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by KutnerUri** [comment]
hey @brendan-gunn !
it seems to be a cache corruption issue from a deploy today.

please try hard refresh. (ctrl+shift+r, or ⌘+⇧+r)
I will try to solve it from our end as well

**Comment by itaymendel** [comment]
was a caching issue. resolved on the server's end yesterday.

**Comment by brendan-gunn** [comment]
Thanks for the feedback, I figured out that incognito mode worked.

[image: Logo]
Brendan Gunn
Director
mobile: +27 82 389 4414
email: brendan@deepdivedata.co.za
17 Leslie Ave, Fourways
South Africa
The content of this email is confidential and intended for the recipient
specified in message only. It is strictly forbidden to share any part of
this message with any third party, without a written consent of the sender.
If you received this message by mistake, please reply to this message and
follow with its deletion, so that we can ensure such a mistake does not
occur in the future.
