### ISSUE TITLE
public_api files generated with a wrong paths

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1799]
### Describe the bug

**Keep in mind that this might be a bug in the ng compiler and not in bit.**

### Steps to Reproduce

  1. follow the same STR from #1798 
  1. look at `node_modules/@bit/giladshoham.primeng1.accordion/dist/accordion/public_api.d.ts` for example (you can see more wrong paths in other files like: `node_modules/@bit/giladshoham.primeng1.accordion/dist/accordion/esm5/public_api.js`

### Expected Behavior

The file contains the following path:
`export * from './src/app/components/accordion/accordion';` 
which is incorrect.

### Specifications

Bit version: master
Node version: 10.16.0
Bit compiler (include version): custom ng compiler v0.0.13

**Comment by davidfirst** [comment]
@GiladShoham , @qballer , these are all `public_api.ts` files inside the `dist` directory, which means, they were created by the compiler. It doesn't seem to be Bit issue.

**Comment by qballer** [comment]
this seems like a bit issue because when I compile them they seem to be structured well. but when I `npm i` I get a dist structure unlike the one I have in the capsule dist.
