### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by fjckls** [teambit/bit#1802]
### Describe the bug

I have added Global style with styled-components, but my fonts are not loading.
This never resolves: https://dc4ef1d2d55e.capsule.ws/fonts/Rubik-Medium.woff . I always get timeout

### Here fonts are added, but they never load

![Screenshot 2019-07-09 at 13 36 11](https://user-images.githubusercontent.com/2750675/60881756-05818080-a24f-11e9-8d48-f357643f0384.png)

**Comment by fjckls** [comment]
It was related to wrong imports inside my GlobalStyle, I fixed that, but now I'm getting this https://github.com/teambit/bit/issues/1504

**Comment by GiladShoham** [comment]
@fjckls  Thanks for the update.
We will post an update about #1504 soon.
Can we close this one?

**Comment by fjckls** [comment]
> @fjckls Thanks for the update.
> We will post an update about #1504 soon.
> Can we close this one?

Sure! Thanks!
