### ISSUE TITLE
tagging component when compiler change main file - failed

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1804]
### Describe the bug

Trying to tag primeng - shared and got 
`failed validating the component paths with sharedDir, expected path shared.ts, got src/app/components/common/shared.ts`

### Steps to Reproduce

  1. clone primeng
  1. use bitmap from #1803 
  1. `bit tag shared`

### Expected Behavior

Tag will success.
That's something about the fact the compiler returns a new main file. along with capsule and shared dir.
It might be a compiler issue and not bit issue.

### Specifications

Bit version: master
Node version: 10.16.0
Bit compiler (include version): custom ng compiler v0.0.15

**Comment by GiladShoham** [comment]
not relevant with recent fixes. closing for now.

**Comment by luqezman** [comment]
How to fix this?
