### ISSUE TITLE
Having problem while import.

### ISSUE THREAD

**Issue by poriaz** [teambit/bit#1806]
Import not working, Here is the log..

[debug.log](https://github.com/teambit/bit/files/3376141/debug.log)

![Screenshot from 2019-07-10 12-33-07](https://user-images.githubusercontent.com/4321679/60947711-e64a2800-a30e-11e9-8382-1a9737a68fe8.png)

**Comment by itaymendel** [comment]
Hi @poriaz , 
I got a few questions to help figure out the situation:

- was there any change made to the component recently?
- does this error happen on all components or just this one?
- does this error happen when you try to import the component to a completely new and fresh workspace?

**Comment by poriaz** [comment]
was there any change made to the component recently?
> yes, i made the changes yesterday and was able to successfully export with eject. 
even, i imported the same component on the different machine today morning but now same issue occuring on that machine too.
does this error happen on all components or just this one?
> this is happening for all workspace components.
does this error happen when you try to import the component to a completely new and fresh workspace?
> i tried git reset --hard and then removed the components directory also reset the .bitmap file.
still getting the same error.

**Comment by itaymendel** [comment]
Interesting. Can you please give me 'read' permissions to your collection, so I can look at the issue? my account is itay@bit.dev

**Comment by manuel-minniti** [comment]
Added you as Viewer @itaymendel .

**Comment by GiladShoham** [comment]
Hi @manuel-minniti 
The issue has been resolved.
It was a problem in our server as a result of the response size.
We increased the max size and it is working now.
We added a task for a better streaming solution to prevent such a case from happening in the future.
Sorry for this.
Please re-open if it's not working.

**Comment by itaymendel** [comment]
I've removed myself from the collection and organization.

**Comment by manuel-minniti** [comment]
Thanks a lot for the quick fix guys.

**Comment by poriaz** [comment]
Thanks guys.

**Comment by poriaz** [comment]
@itaymendel  facing same problem again. Could you guys please re-open this bug and post updates, thanks.

**Comment by GiladShoham** [comment]
@poriaz 
Sorry about this happened again.
Last time we increased the max size a lot and we were sure it will be enough until we will develop a better solution.
Apparently, it's not.
We are checking again if we can quickly have a better solution.
Please add me (gilad@bit.dev) and my teammate (guy@bit.dev) to your collection.
(We will remove ourselves one it's solved)
@guysaar223 FYI

**Comment by manuel-minniti** [comment]
Added both of you as Viewer (gilad@bit.dev, guy@bit.dev).

**Comment by GiladShoham** [comment]
@manuel-minniti Me and @guysaar223  working on this issue for a few hours.
It looks like a bit different issue than the one before.
We are continuing to investigate it, and we will update soon.

**Comment by GiladShoham** [comment]
@manuel-minniti We deployed a fix which should solve the issue.
Can you please check again and update us?
Thanks.

**Comment by manuel-minniti** [comment]
Thanks guys, I'll have our people do a check and report back.

**Comment by manuel-minniti** [comment]
The fix appears to be working, cheers!
