### ISSUE TITLE
support dynamic dist reference from returned package.json props

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1808]
### Description

When a compiler returns package.json props to add to the component package.json generated by bit he might want to refer to the dist folder. 
However, the dist folder is determined by bit on consuming time (as a function of dist target and entry, whether the component is authored or imported, so on).
The compiler, therefore, can't know in compile time what will be the dist folder.

### Describe the solution you'd like

The compiler json props will support {COMPONENT_DIST_PATH} as a template which will be replaced once bit generates the package.json with the actual value.

**Comment by GiladShoham** [comment]
This is related to #1793

**Comment by davidfirst** [comment]
Implemented on https://github.com/teambit/bit/pull/1823.

**Comment by tahins** [comment]
Looks like this issue is fixed for the react compiler. However, I am still facing it for the typescript and react-typescript compilers.
