### ISSUE TITLE
Separate code from builds on import

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1831]
### Description
The following configuration is available for the workspace:
"dist": {
        "entry": "src",
        "target": "dist"
    },
These definitions should be added manually. 
Without defining this, when a component is imported, its build files and node_modules will be imported directly under the component mixing source code and artifacts. 
However, this definition is relevant only if the imported components are placed under `src` files. 
See https://github.com/teambit/bit/issues/1830 for suggestion on where to default components. 

### Describe the solution you'd like
When initializing a workspace, add this as a default to the configuration. 

### Additional context
With https://github.com/teambit/bit/issues/1830 and this PR a typical project structure folder will look like this: 
```
.
├── dist
│   ├── components
│   │   ├── compA
│   │   └── compB
│   └── imports
│       ├── compC
│       └── compD
├── node_modules
└── src
    ├── components
    │   ├── compA
    │   └── compB
    └── imports
        ├── compC
        └── compD
```

**Comment by itaymendel** [comment]
resolved for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
