### ISSUE TITLE
Webpack bundler build error

### ISSUE THREAD

**Issue by meetromb** [teambit/bit#1833]
When try to import `bit.envs/bundlers/webpack` as compiler, get this error:

<img width="1030" alt="Снимок экрана 2019-07-17 в 20 36 00" src="https://user-images.githubusercontent.com/34175623/61397410-83d6c600-a8d2-11e9-9f13-61b635179213.png">

I know that `node-sass` package need to be installed with npm's `unsafe-perm=true` flag

### Steps to Reproduce

1. Type `sudo bit import bit.env/bundlers/webpack -c`

### Expected Behavior

Imported webpack compiler

### Specifications

- Bit version: 14.1.3
- Node version: v10.16.0
- npm / yarn version: 6.9.0
- Platform: MacOS
- Bit compiler (include version): latest

**Comment by davidfirst** [comment]
@meetromb , just run it without `sudo`.
I tried myself now, I get the same error as you when I prefix the command with `sudo` as shown in your screenshot.

**Comment by meetromb** [comment]
Thx
