### ISSUE TITLE
Allow some remote actions without a bit-workspace

### ISSUE THREAD

**Issue by jonisar** [teambit/bit#1837]
Bit requires a local workspace to run all commands.
Some commands can be defined as 'remote only' commands and should be able to run without a workspace:

- `bit list <remote collection>`
- `bit show <remote component>`
- `bit remove <remote component>`
- `bit deprecate <remote component>`
- `bit undeprecate <remote component>`

There is no reason for these commands not to be able to work without a workspace, so there's no need to force it.

**Comment by davidfirst** [comment]
Implemented in https://github.com/teambit/bit/pull/1884.
Added e2e-tests for all cases.
