### ISSUE TITLE
The presence of a babel config causes bit build to fail

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1840]
### Describe the bug

For some reason, the fact that there's a babel config in the root of a project causes `bit build` to fail.

### Steps to Reproduce

1. clone https://github.com/dajocarter/bit-emotion-babel
1. yarn install
1. bit init
1. bit build spinner (should fail)
1. rm babel.config.js
1. bit build spinner (should pass)

### Expected Behavior

Bit should be able to build the component with the babel config in the root of the project

### Specifications

- Bit version: 14.2.0
- Node version: 10.15.0
- npm / yarn version: 6.4.1
- Platform: macos
- Bit compiler (include version): already configured in project

**Comment by dajocarter** [comment]
For added context, removing [this line](https://github.com/dajocarter/bit-emotion-babel/blob/master/babel.config.js#L5) allows `bit build` to succeed.
I also created this compiler to add `babel-plugin-emotion` and the same build error occurs.
Therefore I don't think this is a problem with having a `babel.config.js` file, but rather having `babel-plugin-emotion` in the `bit build` process.
https://emotion.sh/docs/babel

**Comment by davidfirst** [comment]
Thanks @dajocarter . Before seeing your message, I was actually trying the same thing. I created a new compiler with Emotion plugin and got the same errors even after removing the plugin from `babel.config.js` of the project.
I debugged it for hours yesterday without much luck. 
In general, all the compiler does is running Babel programmatically and passing an array of the plugins, in this case, including `emotion`.
So, this morning I created a simple file that does nothing else, only call Babel programmatically and pass the same options of the project `babel.config.js`. I got an error, see below.
I'm unsure if it's a bug in the programmatic api of Emotion, or is it something with the code in conjunction with the programmatic api. 

Here is the code I placed in a file `run-babel-emotion.js` in the root of this project.
```
const keyframes = require('@emotion/core').keyframes;

const fullSpin = keyframes`
0% {
  transform: rotate(0deg);
}
100% {
  transform: rotate(360deg);
}
`;

const result = require('@babel/core').transform(fullSpin, {
  presets: ['@babel/preset-env', '@babel/preset-react'],
  plugins: ['babel-plugin-emotion']
})
console.log("result", result.code);
```

I got the error below. 
Replacing the `fullSpin` in the argument of `transform` to any text (try "code"), makes it work.

The error I got:
```
➜  bit-emotion-babel git:(master) ✗ node run-babel-emotion.js
/tmp/bit-emotion-babel/node_modules/@babel/core/lib/transformation/normalize-file.js:209
    throw err;
    ^

SyntaxError: unknown: Unexpected token, expected ";" (1:22)

> 1 | _EMO_animation-boi6kv_@keyframes animation-boi6kv{
    |                       ^
  2 | 0% {
  3 |   transform: rotate(0deg);
  4 | }
    at Object.raise (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:6325:17)
    at Object.unexpected (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:7642:16)
    at Object.semicolon (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:7624:40)
    at Object.parseExpressionStatement (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:10364:10)
    at Object.parseStatementContent (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:9963:19)
    at Object.parseStatement (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:9829:17)
    at Object.parseBlockOrModuleBlockBody (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:10405:25)
    at Object.parseBlockBody (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:10392:10)
    at Object.parseTopLevel (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:9758:10)
    at Object.parse (/tmp/bit-emotion-babel/node_modules/@babel/parser/lib/index.js:11270:17)
```

**Comment by GiladShoham** [comment]
@dajocarter I was able to compile a demo file with your own compiler:
```js
import { jsx, css, keyframes } from '@emotion/core'

const bounce = keyframes`  0% {    transform: rotate(0deg);  }  100% {    transform: rotate(360deg);  }`

const fullSpin = keyframes`
0% {
  transform: rotate(0deg);
}
100% {
  transform: rotate(360deg);
}
`;

render(
  <div
    css={css`
      animation: ${bounce} 1s ease infinite;
    `}
  >
    some bouncing text!
  </div>
)
```

**Comment by GiladShoham** [comment]
The issue is something with the @emotion/styled syntax.
removing those lines from your code makes the build to success
```js
const Container = styled.div`
  height: ${({ size }) => size ? `${size}rem` : `100%`};
  width: ${({ size }) => size ? `${size}rem` : `100%`};
  animation: ${fullSpin} 750ms linear infinite;
  margin: 0 auto;
`
```

**Comment by GiladShoham** [comment]
@dajocarter 
Here is a repo with all my findings, and reproduce versions.
https://github.com/GiladShoham/bit-emotion-reproduce
I'll open an issue in the emotion github and reference it here.

Anyway, this issue is not bit related but somewhere between babel-core and the emotion plugin.

**Comment by GiladShoham** [comment]
Here is the issue I've opened in emotion repo:
https://github.com/emotion-js/emotion/issues/1439

**Comment by itaymendel** [comment]
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
