### ISSUE TITLE
how to undo test file

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#1850]
I accidentally added a file as --tests.
how do I make it a normal file again?

<img width="538" alt="Screen Shot 2019-07-24 at 16 15 59" src="https://user-images.githubusercontent.com/5400361/61796718-a74bc480-ae2e-11e9-943e-9cb75c91ba1c.png">

bit version: 14.2.1
OS: macOS 10.14.5
node: 12.1.0

**Comment by itaymendel** [comment]
Running `bit add <file-name> --id <component name>` should work for such case.

**Comment by davidfirst** [comment]
@itaymendel , it doesn't work. I just tried it, the file is still marked as a test.

**Comment by GiladShoham** [comment]
@itaymendel me too.. exactly tested it

**Comment by GiladShoham** [comment]
we should add an edit / modify component command.
To remove files, change main, change tests etc.

**Comment by davidfirst** [comment]
@GiladShoham , we started the discussion about it here: https://github.com/teambit/bit/issues/1649.
This issue actually blocks me from merging https://github.com/teambit/bit/issues/1715.

**Comment by GiladShoham** [comment]
@davidfirst 
Talked with @itaymendel about it.
We will create an issue with a full product about the edit command.
But regardless the edit command, @itaymendel said he expected this to work that way.
So if you re-add a test file as a regular file it should become regular file. 
So we can make what @itaymendel said before to work.

**Comment by davidfirst** [comment]
@GiladShoham , @itaymendel , it's not that simple IMO.
What if a user re-added the directory to an existing id without entering `--tests` flag? 
For example, a user has `bar` directory with `foo.js` (non-test) and `foo.spec.js` (test).
Now, a user is running `bit add bar --id bar`. We have two options:
1. treat it the same as one file. meaning, change `foo.spec.js` to not be a test. However, most probably the user didn't want to touch the test property, only to re-track the directory.
2. leave the test property as-is. However, what if a user wants to remove test property from all files in this directory? there won't be an option to do so. 

I believe that should be a more explicit way to indicate the intention of changing a file/files/directory from test to non-test.

**Comment by GiladShoham** [comment]
@davidfirst Good questions.. we will think about it.
Anyway, we are going to create a more explicit command to do such things.

**Comment by davidfirst** [comment]
It's possible to change a test file by re-adding the component using `--override` flag.
Added an e2e-test to confirm that it works as expected.
