### ISSUE TITLE
typescript compiler generates incomplete d.ts

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#1852]
Typescript compiler only generates d.ts to the **_main file_** of the component.
Since I set index.ts as main file, the the d.ts is practically empty.

<img width="896" alt="Screen Shot 2019-07-24 at 17 40 39" src="https://user-images.githubusercontent.com/5400361/61803533-fc8dd300-ae3a-11e9-8f87-27be313cb494.png">

@qballer  I know you have other tasks but this destroys the playground :( :( :(

Compiler:
bit.env/compilers/typescript @ 3.0.5
bit version: 14.2.1
yarn: 1.16.0
node: 12.1.0

**Comment by qballer** [comment]
Hi Uri, I'm aware of this issue, it stems from a community patch which was applied on typescript compiler. This is in my very short term task list and should be dealt with soon. I will keep this issue open and update on progress when things move along.

**Comment by KutnerUri** [comment]
looking forward to the fix :)

**Comment by GiladShoham** [comment]
@qballer Great:)
@KutnerUri It's better to open issues about envs in the dedicated [bit-envs](https://github.com/teambit/bit-envs) repo

**Comment by qballer** [comment]
issue is fixed in typescript 3.0.15
