### ISSUE TITLE
Symlink for binary files issue

### ISSUE THREAD

**Issue by siffash** [teambit/bit#1857]
### Describe the bug

Some of the components import _png_ and _json_ files. After exporting the components to bit.dev these files are included into the packages as symlinks, but they lead to the same alias file, which obviously makes no sense. When building the react project we get an error: `Cannot find module`.

We found that there was an issue which was fixed in 14.1.0: _fix symlink generation when a binary file is required from another file within the same component using custom resolve module_. But it seems that the issue persists.

### Steps to Reproduce

1. Create a component which imports and uses some binary file (it should be located outside of the component folder).
2. Export that component to bit.dev, as well as that binary file (separately).
3. Go to another project.
4. Install the component from bit.dev.
5. Try to import it to the project and try to build the project.

### Expected Behavior

Binary files to be imported without any issues.

### Screenshots, exceptions and logs

`info => Compiling preview..`
` 70% building 158/171 modules 13 active /tmp/build_fbe5726b883e979d32b75d78f4ab9de8/node_modules/@storybook/react/dist/client/preview/element_check.js`
`ERR! => Failed to build the preview`
`ERR! ./node_modules/@bit/............./components/atoms/Img/stories.tsx`
`ERR! Cannot find module: '../../../images/profile-image-reg.png'. Make sure this package is installed.`

### Specifications

- Bit version: 14.2.2
- Node version: 10.15.3
- npm version: 6.4.1
- Platform: MacOs Mojave 10.14.5
- Bit compiler (include version): bit.envs.compilers.react-typescript 3.0.6

### Additional context

Using storybook in the project to display the bit.dev components.

**Comment by davidfirst** [comment]
@siffash , Not sure I fully understand the case. 
Is it one component that some files require other binary files? or they're two components that one require a binary file from the other component?
Can you add me (david@bit.dev) as a collaborator so I could import the component? it'd be easy to reproduce this way.

**Comment by siffash** [comment]
@davidfirst Thank you for picking up this issue. The problem disappeared after I removed the whole node_modules folder and installed everything from scratch. I guess there was a problem from bit.dev side when I installed the components first time.
