### ISSUE TITLE
Error on excluded files when use bit add command

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1862]
I am trying to export ng-bootstrap project, and get an error when runing `bit add...` on files that are excluded.

### Steps to Reproduce

1. git clone git@github.com:ng-bootstrap/ng-bootstrap.git
1. git checkout tags/5.1.0
1. yarn
4. bit init
5. bit add src/**/ -m 'src/{PARENT}/{PARENT}.ts' -e 'src/datepicker,src/buttons,src/util'

### Screenshots, exceptions and logs
I got an error that main file of datepicker was excluded from the list.
![image](https://user-images.githubusercontent.com/35892475/62005409-7b388800-b13b-11e9-8177-db4dbe52cc63.png)

### Specifications

- Bit version: 14.2.3-dev.1
- Node version: 12.7.0
- yarn version: 1.15.2
- Platform: macOS

**Comment by davidfirst** [comment]
This is going to wait until a new syntax of negating using minimatch is introduced. 
(@GiladShoham , @itaymendel, there is no point working on it as it'll be changed anyway with the new syntax).

**Comment by itaymendel** [comment]
v15 does not support excluding files
closing issue
