### ISSUE TITLE
Exclude components from overrides

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1863]
### Description

When I want to set an override to most of the components in a namespace I am required to list the component IDs I want to override, as if any component in that namespace does not require the value I'm overriding to the other components, there's no way for me to annotate it.

### Describe the solution you'd like

I propose adding an `exclude` feature to the `override` feature by adding an array of the components that the overriding rule will not affect. The array should support glob patterns as well as specific component IDs (line 7).

```js{7}
{
  "bit" : {
    "overrides" : {
      "bit.utils/*" : {
        "dependencies": { /* deps to add here */  },
        "env": { /* envs for override here */  },
        "exclude": [ "bit.utils/array/*", "bit.utils/string/starts-with-one-of" ]
    }
  }
}
```

**Comment by davidfirst** [comment]
@itaymendel , @GiladShoham , the way how it can be done now is by adding the component you want to exclude as a new key to the `overrides`.
In the example above, the following should do the trick:
```
{
  "bit" : {
    "overrides" : {
      "bit.utils/*" : {
        "dependencies": { /* deps to add here */  },
        "env": { /* envs for override here */  }
    },
     "bit.utils/array/*": {},
     "bit.utils/string/starts-with-one-of": {}
  }
}
```
adding the `exclude` is another layer of complexity when figuring out the final rules of a component. I'm not convinced that it's needed.

**Comment by itaymendel** [comment]
@davidfirst , I'm not sure if this is intuitive, especially when taking to account the `propagate` feature. For example, when I do want to use a set of rules and allot propagation - I'm unable to distinct specific components not to get a specific rule.
The only way for me to work around it is to drop the propagation and have a very large set of override rules.

For cases where there is no propagation - you are definitely right, and your solution is probably a better way to go. But if we do use `propagate` - there should be a way to exclude component(s) from being affected by a rule.

**Comment by davidfirst** [comment]
@itaymendel, Thanks for the clarification. That makes sense.
So, in the following example:
```
"overrides" : {
      "*": {
        "devDependencies": { "mocha": "-"}
      },
      "bit.utils/*" : {
        "env": { "compiler": "babel" },
        "propagate": true
      },
      "bit.utils/array/*": { }
    }
```
If `exclude` is not supported and we want `bit.utils/array/*` to have the general `*` rules but not `bit.utils/*` rules, it must be manually copied from `*` to `bit.utils/array/*`.

**Comment by davidfirst** [comment]
Implemented on https://github.com/teambit/bit/pull/1891. Added tests. Merged.
