### ISSUE TITLE
Bit configuration location

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1864]
### Description

Bit configuration is currently located under 

For Mac/Linux - ~/Library/Caches/Bit/Config.
For Windows - %LOCALAPPDATA%/Bit/Config. If %LOCALAPPDATA% is not defined, user profile directory will be used instead of %LOCALAPPDATA%.

The window's location makes sense, but the Mac / Linux does not, as the configuration is stored under caches. 

### Describe the solution you'd like

Potential possible locations for configuration:
~/.bit
~/Library/bit

**Comment by qballer** [comment]
> ~/Library/bit

perhaps ~/.config/bit.json

**Comment by itaymendel** [comment]
I'd go with `~/.bit` (or `~/.bitconfig`) by default, and perhaps have an option for a global file for Bit to use (`/etc/bit/config`) if no config found in user's root.

**Comment by GiladShoham** [comment]
> perhaps ~/.config/bit.json

I think it's confusing.
You put something in the user's root folder which called .config. that sound very general config or root for a lot of other configs, but you use it only for bit.

Keep in mind that when thinking about this, we should also think about other global stuff of bit, like global components / global extensions, etc'.
They might be in a completely different location, but they might be in under the same base path. So worth to consider it as well.

**Comment by Tallyb** [comment]
https://stackoverflow.com/a/410023

**Comment by KutnerUri** [comment]
just ran into this. It is weird to find it here and not at https://docs.bit.dev/docs/conf-config.html

I agree - the config must be moved out of the /caches folder.
