### ISSUE TITLE
Workspace configuration's overrides should include imported components

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1867]
### Description

When using the `overrides` feature in a project, the rules defined in it must apply to imported components as well.

### Describe the solution you'd like

All override rules from the workspace should apply to imported components that fit the glob-pattern (or specific ID). Additionally, Bit should keep supporting the merge strategy for the override rules when taking to account the rule defined for the imported component (which should act as an override rule for a specific-ID in the workspace config).

### Additional context

This feature should only be released when #1863 is ready.

**Comment by davidfirst** [comment]
Completed. Added tests.
