### ISSUE TITLE
Create a brew tap

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1869]
### Description

We should create a tap for brew which installs bit binaries files to prevent issues with an incompatible version of node in the user environment.

### Describe the solution you'd like

Create our own tap which will be in our own hands and allow binary installations.

### Describe alternatives you've considered

updating bit's formula in brew/core to install the binary. (they not agree to merge it. see under additional context)

### Additional context

https://discourse.brew.sh/t/moving-an-installation-from-core-to-cask/5312/7
https://github.com/Homebrew/homebrew-core/pull/42119
https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md
https://github.com/Homebrew/brew/blob/master/docs/Migrating-A-Formula-To-A-Tap.md

**Comment by itaymendel** [comment]
irrelevant with `bvm`
