### ISSUE TITLE
Add option to remove a file from component after it is track

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1870]
When you add a component and you want to remove a file from here after is track, you can't.
The only thing you can do is to untrack it and track it again with exclude option.

It will be nice if this option can be added, like this for example:
`bit remove <comp id>/<name of the file>`

**Comment by itaymendel** [comment]
You can remove a file from a tracked component.
Use the exclude command as shown [here](https://docs.bit.dev/docs/manage-component-files.html#removing-files-from-components)

**Comment by qballer** [comment]
I would like to discuss the product part of it. I don't think it's the most intuitive way of doing it:
`bit add src/hello-world --id src/hello-world --exclude src/hello-world/index.js`
@itaymendel, would you mind reopening the issue?
