### ISSUE TITLE
Bit status doesn't show an alert when "templateUrl" is a missing a file in an Angular component

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1871]
I added components from the ng-lightning repository and the HTML file was missing.
But when I run bit status, nothing happens and the status was correct.

### Steps to Reproduce

1. clone this project https://github.com/ng-lightning/ng-lightning
2. checkout to version 4.8.1
3. run this command:
```
cd projects/ng-lightning 
npm i rxjs
bit init 

bit add src/lib/** -e 'src/lib/util,src/lib/common,src/lib/forms'

bit add src/lib/util/* -t 'src/lib/util/{FILE_NAME}.spec.ts' -n util
bit add src/lib/forms/* -m src/lib/forms/module.ts -i forms

bit add src/lib/common/*.ts -m clickoutside.module.ts -i common/clickoutside
bit add src/lib/common/host/host.service.ts -n common
bit add src/lib/common/notify/*.ts -n common/notify
bit add src/lib/common/overlay/* -m overlay.module.ts -i common/overlay
```
4. run `bit status`

And now you will see that the status os correct, but if you open the accordion component under ng-lightning/projects/ng-lightning/src/lib/accordion in file accordion-item.ts you will see:
```
@Component({
  // tslint:disable-next-line:component-selector
  selector: 'li[nglAccordionItem]',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './accordion-item.html',
})
```

- Bit version: 14.2.3
- Node version: 12.7.0
- yarn version: 1.15.2
- Platform: macOS

**Comment by JoshK2** [comment]
I add the .bitmap if you need
[ng-lightning-bitmap.txt](https://github.com/teambit/bit/files/3441368/ng-lightning-bitmap.txt)

**Comment by davidfirst** [comment]
Bit determines whether a project is an Angular project by having `@angular/core` in their dependencies. This project has it in peerDependencies, that's why Bit didn't call Angular compiler to resolve the template.
I fixed it in a new branch "bug/angular-resolve-template" to consider also the peerDependencies.

However, once Bit calls Angular compiler on this project it gets errors. E.g.
```
 > accordion ...  issues found
       error found while resolving the file dependencies (see the log for the full error):
          src/lib/accordion/accordion-item.ts -> src/lib/ng-lightning.module.ts(113,2): Error during template compile of 'NglModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
```
So, I guess it'd be better to fix the errors before I merge this branch.
cc: @GiladShoham

**Comment by GiladShoham** [comment]
@JoshK2 @qballer Please take a look on this before we merge it.
You can either use @davidfirst branch.
Or locally change the angular/core to be a regular dependency to see the error.

**Comment by davidfirst** [comment]
Waiting for a decision whether we should forgo the Angular compiler entirely and only parse the decorator by ts compiler. 

(pros: not dealing with all these errors, some are not related to the added component. 
cons: unable to extract dependencies from templates, unable to find templateUrls and styleUrls from decorators in case they're variables and not strings).

**Comment by davidfirst** [comment]
Fixed in the PR above. 
The way how to detect templateUrl has changed and is now working via TS parser, so the `@angular/core` in the packages is irrelevant anymore.
