### ISSUE TITLE
deprecate a specific version

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#1872]
I tagged a bad version of a component.
Is there a way to mark this specific version as deprecated? (or delete it?)

**Comment by GiladShoham** [comment]
It's not possible at the moment to deprecate a specific version. deprecation is at the component level.
We might change it. it requires further discussion. I moved this issue to require discussion pipeline. we will update our thoughts here.

**Comment by KutnerUri** [comment]
thanks!
