### ISSUE TITLE
Gitlab CI failing 

### ISSUE THREAD

**Issue by AmitKendler** [teambit/bit#1879]
### Describe the bug
I've exported some of my react project components to bit.
working locally all seems to be fine (yarn install the packages, project works fine).
while trying to deploy to our staging environment using gitlab CI the pipeline fails during the yarn install and i get a wierd error:
> Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"

I'm not sure if the problem is with the CI configuration or in something else that i missed, although i did all the steps specified in the docs.

### Steps to Reproduce

1. Created a new bit account & collection.
2. Exported some of project#1's components to bit.
3. Imported my new bit components in project#2 using yarn add method.
4. Tested  project#2 locally, imported the components, works fine.
5. Configure .gitlab-ci.yml in my project as referred in https://github.com/teambit/bit/issues/1539
6. Run a build.

every attempt a different component from @bit repository seems to be corrupted (so it isn't a specific component).

what am i doing wrong?

### Expected Behavior

Our gitlab CI should work as it works locally 

### Screenshots, exceptions and [logs](url)
![image](https://user-images.githubusercontent.com/7279573/62115455-26bf1500-b2c1-11e9-8514-4c8846f88d5e.png)

### Specifications

- Bit version: 14.2.1
- Node version: 10.15.0
- npm / yarn version: 1.12.3
- Platform: gitlab-runner 12.0.0

**Comment by itaymendel** [comment]
hi @AmitKendler , can you try and run the ci with npm? I've encountered issues sometimes with yarn closing connections.

**Comment by AmitKendler** [comment]
> hi @AmitKendler , can you try and run the ci with npm? I've encountered issues sometimes with yarn closing connections.

Tried that.

now it shows an 404 error. any clues?

![image](https://user-images.githubusercontent.com/7279573/62121028-786c9d00-b2cb-11e9-9e2d-826fa26b6c84.png)

**Comment by itaymendel** [comment]
have you configured your ci as shows in https://github.com/teambit/bit/issues/1539 ?

**Comment by AmitKendler** [comment]
> have you configured your ci as shows in #1539 ?

Yes, as i said - worked but i had to set it in the dockerfile .

anyways moving from npm to yarn did the job - although it was painfull

**Comment by GiladShoham** [comment]
@AmitKendler 
If it works with yarn but not with npm, it might be some cache issue.
Try to clean npm cache and also delete the package-lock.json before the installation. see if it works.

**Comment by itaymendel** [comment]
ci for component has re-implemnted for v15. now it can run on your local setup and not 100% on bit.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
