### ISSUE TITLE
Changing Username

### ISSUE THREAD

**Issue by mateja176** [teambit/bit#1880]
### Description

I would like to be able to change my username.

### Describe the solution you'd like

A simple form where the user may type in their new username and click confirm.
Or even simpler, a `rename` command to run in the terminal.

### Describe alternatives you've considered

I am able to create an organization with the desired name, however it is not exactly the same as having a different username.

**Comment by itaymendel** [comment]
hi @mateja176 , please send an email to support@bit.dev with such requests.
