### ISSUE TITLE
Update/Exclude files after a component is tracked does not work

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1883]
I track a component with bit add command, after that, I want to remove a file from the component and its not working.
I added the component with this command: `bit add sum/* -m sum/a.js -i sum`
and after I try to exclude a file from the component, so I run `bit add sum/* -m sum/a.js -e 'sum/b.js' -i sum` and it does not exclude that file from the component.
So I think that after you track a component, you can't update it with the exclude flag.

You can download this tar to easily reproduce the bug.
[test1.tar.gz](https://github.com/teambit/bit/files/3450847/test1.tar.gz)

### Steps to Reproduce

1. Open the tar file.
2. Run `bit add sum/* -m sum/a.js -e 'sum/b.js' -i sum`

### Specifications

- Bit version: 14.2.4-dev.1
- Node version: v12.7.0

**Comment by GiladShoham** [comment]
Thanks, we will check it and update.

**Comment by joeyparis** [comment]
Is there any update on this issue? I'm experiencing this same issue on 14.7.1

**Comment by joeyparis** [comment]
I've narrowed this down to the `_mergeFilesWithExistingComponentMapFiles` function in `add-component.ts`. It's merging the existing component files (which may include a newly excluded file) with the new set of files which results in the new exclusion files not being excluded. I can make an attempt at solving this tomorrow, although I've never worked directly with Typescript before

**Comment by Oba-One** [comment]
Still having this issue, this is lowkey ridiculous because what bit is meant to be and it can't properly exclude files and it's not clear in the documentation which is minimal in this category.
Glob patterns cause the add command to fail and only a literal filename works for exclusion. I'm using storybook and want to not track those files as they're not needed.

**Comment by bpod** [comment]
Seeing the same issue

**Comment by itaymendel** [comment]
bit v15 autotracks a dir and all changes in it

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
