### ISSUE TITLE
Add Bit Stencil Compiler to bit.dev

### ISSUE THREAD

**Issue by shubhamyadav-coditas** [teambit/bit#1887]
### Description
Please add a Bit Stencil Compiler for web-components into Bit.dev
https://github.com/ionic-team/stencil-site
https://stenciljs.com/

**Comment by arsenx** [comment]
Any updates on this topic?

**Comment by qballer** [comment]
I've recently started working on this area. not ETA at the moment, but it's being done.

**Comment by arsenx** [comment]
Great! Thanks for the update, looking forward to start using bit.
    	
    	

    	
    
  




On Wed, Oct 23, 2019 at 1:14 PM -0400, "Doron Tsur" <notifications@github.com> wrote:












I've recently started working on this area. not ETA at the moment, but it's being done.

**Comment by GiladShoham** [comment]
@shubhamyadav-coditas @arsenx ,
As @qballer mentioned, we are working on this at the moment.
Please, move this discussion to the dedicated envs repo - https://github.com/teambit/envs.
(Feel free to open a new issue there and link it to this one)
Thanks.
