### ISSUE TITLE
Capsule related API should be available in the experimental compiler API. 

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1888]
### Description

During the release of the capsule version we have added a few API's which are related to the capsule. Right now in order to support typescript we need to define custom dependencies to components according to configuration. This means we need all the capsule API's available in the experimental compiler API. (I hope I make sense here) 

### Describe the solution you'd like

Provide capsule API in experimental compiler API.

**Comment by davidfirst** [comment]
@qballer , I made sure that the capsule API works also for the compiler experimental API.
I added e2e-tests to confirm and make sure it won't break.
