### ISSUE TITLE
Rename `bit list --bare` to `bit list --raw`

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1892]
### Description

We use `--bare` for creating a bare scope. Using the same term for a different purpose is misleading. 

### Describe the solution you'd like

Deprecate `--bare` and replace with `--raw | -r`

### Describe alternatives you've considered

Do nothing

**Comment by itaymendel** [comment]
sounds about right.
i don't think that people use that flag, but still - let's hide it, and when someone uses `--bare` they should see a prompt saying its deprecated, and they should use `--raw`.

**Comment by davidfirst** [comment]
Done.
