### ISSUE TITLE
Allow `bit log` to work on remote component with no workspace

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1894]
### Description

`bit log` only works inside a workspace. 

### Describe the solution you'd like

`bit log me.collection/foo/bar` should log the history of the component. 
Logging remote collection's component should work with no workspace.

**Comment by GiladShoham** [comment]
@davidfirst That should be an easy task. let's do it.

**Comment by davidfirst** [comment]
Implemented in the PR above.

**Comment by Tallyb** [comment]
@davidfirst if this command now runs now with no workspace, you should also add the skipWorkspace=true in the command attributes (like the one below). 
https://github.com/teambit/bit/blob/8c55f5429d93b2cf3f5f7be83dd69c6b13a7a901/src/cli/commands/public-cmds/config-cmd.ts#L13
This changes the documentation to be Workspace Only: no, as here: 
https://docs.bit.dev/docs/apis/cli-all#log

**Comment by GiladShoham** [comment]
@davidfirst also adding the `remoteOp = true;` in the same place, so it will add the `--token` flag automatically.

**Comment by davidfirst** [comment]
@Tallyb , Done. https://github.com/teambit/bit/compare/55c85aaefde6...59e3fbf900da
@GiladShoham , this has been added already by you before.
