### ISSUE TITLE
Create a `bit use` command for importing extensions, compilers, testers

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1898]
### Description

Separate the import command for compilers/testers and extensions to a separate `bit use` command. 

### Describe the solution you'd like

`bit use` will be the same as `bit import <id> --compiler | --tester | --extension`

Valid options will be: 

| **Option** | **Alias** | **Description**
|---|---|---|
|`--tester` | `-t` | Import a tester component
|`--compiler` | `-c` | Import a compiler component
|`--extension`  | `-x` | Import an extension component

Seems like all other options are not applicable, and actually might be confusing.  

|`--environment` | `-e` | Install component's compiler and tester during import.
|`--path path` | `-p` | Import components into a specific directory
|`--objects` | `-o` | Import components objects only, don't write the components to the file system. This is the default behavior for import with no id
|`--display-dependencies` | `-d` | Display the imported dependencies
|`--override` | `-O` | Override local changes in the workspace
|`--verbose` | `-v` | Show verbose output
|`--ignore-dist` | | Skip writing the component's build files during import
|`--conf [path]`| | Write the configuration file (bit.json) and the envs configuration files to the path directory or to the default directory if a path was not provided.
|`--skip-npm-install` | | Do not install packages of the imported components.
|`--ignore-package-json` | | Do not generate package.json for the imported component(s). Will also skip npm install and dependencies-as-components //ToDo
|`--merge [strategy]` |`-m` | Merge imported version into the local workspace and apply the git merging strategy: "theirs", "ours", or "manual". Defaulted to manual

**Comment by KutnerUri** [comment]
This is great!
I need a way to set the target, ie:
```bit use <id> --compiler --at <target>``` 
(we could use shorthand ```-a``` = ```--at```, and get ```--all``` as default)

I think it would be better to drop the '--compiler' parameter.
Since this is no longer ```bit import```, there is no ambiguity between _importing_ a compiler and _using_ a compiler.
Worse case, we could use ```--as-compiler``` and free up valuable flags like ```-c | -t | -x```

**Comment by Tallyb** [comment]
we can drop --compiler if the component will know what it does (compiles / tests/ extends)

**Comment by GiladShoham** [comment]
Will be handled by #2778
