### ISSUE TITLE
interactive experience for bit init command

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#1908]
### Description

For a better onboarding process, I want `bit init` command to be interactive.

### Describe the solution you'd like

When I initialized a new workspace I want bit to help me set up everything I need.
This talks about:
* component's directory
* package manager (npm / yarn)
* compiler environment 
* testing environment

The flow should be something like this:
1. Which is your default package manager
* npm
* yarn
2. Select a default imported components directory
* components (default)
* auto complete input based on the project structure
3. setting up a default compiler for all components
* skip
* list of compilers maintained by bit team (list of bit.envs from compilers/bundlers namespaces)
* other 

if the user chooses "other" in the previous question:
4. enter your environment collection name
* user free text input
5. choose your compiler
* list of components from the user's collection

### Configuration
support `interactive` and `interactive.init` in the global config.
Boolean values which determine if to show the interactive or not.

### Additional context

This feature requires first to implement #913

**Comment by Tallyb** [comment]
1. Which package manager you would like to use for installing components?  
2. Where would you like to store imported components? 
3. Which compiler would you like to use for the components? (no compiler, list, another compiler)

On number 4 - I would just prefer pasting a link, and we will fetch the version and specify it. i.e which compiler? 
https://bit.dev/yoobic/design-system/compilers/stencil

**Comment by Tallyb** [comment]
If failed to load compilers list: 
- Could not retrieve compilers list. See full error log in... You can add a compiler later using bit import <compiler name> --import. 

If failed to load a user's compiler: 
- Could not find the requested compiler. See full error log in... You can add a compiler later using bit import <compiler name> --import.

**Comment by GiladShoham** [comment]
@Tallyb A suggestion for a text when there was an error during fetching the bit.envs compilers?
Currently, it's:
'failed fetching components, see the full error in bit.logs. skipping question'
