### ISSUE TITLE
Cannot find module error because incorrect path of module in the capsule - Angular

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1912]
I work on this project - https://github.com/swimlane/ngx-charts
and try to export it to bit, and get an error when I build it.

### Steps to Reproduce

1. clone https://github.com/swimlane/ngx-charts
2. checkout version to 12.0.1
3. npm i
4. bit init
5. edit this file src/common/axes/y-axis-ticks.component.ts:
   change: import { roundedRect } from '../../common/shape.helper';
   to this: import { roundedRect } from '../shape.helper';
6. edit this file src/utils/types.ts
    change: toString.call(value) === '[object Date]';
    to: Object.prototype.toString.call(value) === '[object Date]';
7. run this bit add command:
```
bit add src/*/ -e 'src/{PARENT}/*.spec.ts,src/common,src/models,src/utils' -m 'src/{PARENT}/index.ts'
bit add src/utils/* -n utils 
bit add src/models/* -n models
bit add src/events.ts -n internal

bit add src/common/*/ -n common -e 'src/common/*/*.spec.ts'
bit add src/common/area.component.ts -n common 
bit add src/common/base-chart.component.ts src/common/base-chart.component.scss -m 'base-chart.component.ts' -i common/base-chart
bit add src/common/chart-common.module.ts -n common
bit add src/common/circle-series.component.ts -n common
bit add src/common/circle.component.ts -n common
bit add src/common/color.helper.ts -n common 
bit add src/common/domain.helper.ts -n common
bit add src/common/grid-layout.helper.ts -n common
bit add src/common/grid-panel-series.component.ts -n common
bit add src/common/grid-panel.component.ts -n common
bit add src/common/label.helper.ts -n common 
bit add src/common/shape.helper.ts -n common
bit add src/common/svg-linear-gradient.component.ts -n common
bit add src/common/svg-radial-gradient.component.ts -n common
bit add src/common/tick-format.helper.ts -n common    
bit add src/common/tooltip-area.component.ts -n common
bit add src/common/trim-label.helper.ts -n common
bit add src/common/view-dimensions.helper.ts -n common
```
8.  run bit status (need to be ok)
9. import this compiler `bit import swimlane.envs/compilers/angular@0.1.10`
10. run `NG_DEBUG=true bit build common/chart-commonmodule`

And now you will get this error, its import components from dist folder, but them not exist.
```
error: bit failed to build common/chart-commonmodule with the following exception:
Command failed: node /Users/yoshuakuttler/Documents/bit/testingAngularProjects/ngx-charts-compiler/components/compilers/angular/node_modules/ng-packagr/cli/main.js -p ng-package.json -c tsconfig.json
ERROR: charts/chart.component.ts(1,32): error TS2307: Cannot find module '@bit/common.charts/dist/charts/chart.component'.
axes/axes.module.ts(1,28): error TS2307: Cannot find module '@bit/common.axes/dist/axes/axes.module'.
```

### Specifications

- Bit version: 14.2.3
- Node version: 12.7.0
- npm version: 6.10.2
- Platform: macOS
- Bit compiler (include version):  https://bit.dev/swimlane/envs/compilers/angular?version=0.1.10

**Comment by GiladShoham** [comment]
That's might be an issue with the hardcoded "dist" or [component-name] the ng-packager added to the dist paths.
Along with the fact that the compiled files names are different from the source file names after running ng-packager. So the main file is different, so bit try to point to a specific file rather than the package itself.
So it's something like:
the compiled main file is different name -> bit not recognize it should point to the package -> bit try to point to the exact files -> bit don't know about the hardcoded path changes by the ng-packager compiler -> a wrong path.

It should be resolved by using the dist template in the main file returned from the compiler. It has some bugs so @qballer revert it to hardcoded.

All this info are just a theory, I need further deep check to make sure it's correct.

I think @davidfirst and @qballer should look into it together to solve it.

**Comment by qballer** [comment]
@GiladShoham your theory is sound I think. I will check it out tomorrow and return with results.

**Comment by JoshK2** [comment]
I have the same issue with another project that I tried.
It's this project https://github.com/ngx-fomantic-ui/ngx-fomantic-ui

STP:
1. clone
2. npm i && bit init
3. run this bit add commands:
```
bit add projects/ngx-fomantic-ui/src/modules/accordion -m 'public.ts'
bit add projects/ngx-fomantic-ui/src/modules/collapse -m 'public.ts' 
bit add projects/ngx-fomantic-ui/src/modules/transition -m 'public.ts'
```
4. import the Angular compiler bit import bit.envs/angular -c

Now you can see with bit show that collapse and transition have no components dependencies, and if we try to build them is working.
But accordion component have collapse and transition components in dependencies, and when I tried to build accordion, I get this error:
```
error: bit failed to build accordion with the following exception:
Command failed: node /Users/yoshuakuttler/Documents/bit/testingAngularProjects/ngx-fomantic-ui/.git/bit/components/compilers/angular/bit.envs/0.1.9/node_modules/ng-packagr/cli/main.js -p ng-package.json -c tsconfig.json
ERROR: transition/internal.ts(1,37): error TS2307: Cannot find module '@bit/transition/dist/internal'.
transition/internal.ts(3,28): error TS2307: Cannot find module '@bit/transition/dist/internal'.
transition/internal.ts(5,38): error TS2307: Cannot find module '@bit/transition/dist/internal'.
collapse/internal.ts(1,35): error TS2307: Cannot find module '@bit/collapse/dist/internal'.
```

Bit version: 14.2.4
Node version: 10.16.0
Bit compiler (include version): https://bit.dev/bit/envs/compilers/angular?version=0.1.9

**Comment by JoshK2** [comment]
Happened me again in this project https://github.com/edcarroll/ng2-semantic-ui

**Comment by JoshK2** [comment]
Happened me again in this project https://github.com/NG-ZORRO/ng-zorro-antd/tree/8.2.0

**Comment by davidfirst** [comment]
I tried the first project a week ago and got other errors. Now I tried the second one with `ngx-fomantic-ui` and I got a different error. @qballer , any idea why I get these?

```
➜  ngx-fomantic-ui git:(master) ✗ bit build accordion
error: bit failed to build accordion with the following exception:
error: bit failed to build transition with the following exception:
Command failed: node /Users/davidfirst/temp/projects/github/1912-b/ngx-fomantic-ui/.git/bit/components/angular/bit.envs/0.1.9/node_modules/ng-packagr/cli/main.js -p ng-package.json -c tsconfig.json
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.string', 'es2019.symbol', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint'.


Building Angular Package

Error: Command failed: node /Users/davidfirst/temp/projects/github/1912-b/ngx-fomantic-ui/.git/bit/components/angular/bit.envs/0.1.9/node_modules/ng-packagr/cli/main.js -p ng-package.json -c tsconfig.json
error TS6046: Argument for '--lib' option must be: 'es5', 'es6', 'es2015', 'es7', 'es2016', 'es2017', 'es2018', 'es2019', 'esnext', 'dom', 'dom.iterable', 'webworker', 'webworker.importscripts', 'scripthost', 'es2015.core', 'es2015.collection', 'es2015.generator', 'es2015.iterable', 'es2015.promise', 'es2015.proxy', 'es2015.reflect', 'es2015.symbol', 'es2015.symbol.wellknown', 'es2016.array.include', 'es2017.object', 'es2017.sharedmemory', 'es2017.string', 'es2017.intl', 'es2017.typedarrays', 'es2018.asynciterable', 'es2018.intl', 'es2018.promise', 'es2018.regexp', 'es2019.array', 'es2019.string', 'es2019.symbol', 'esnext.array', 'esnext.symbol', 'esnext.asynciterable', 'esnext.intl', 'esnext.bigint'.


Building Angular Package

    at makeError (/Users/davidfirst/temp/projects/github/1912-b/ngx-fomantic-ui/.git/bit/components/angular/bit.envs/0.1.9/node_modules/execa/index.js:174:9)
    at /Users/davidfirst/temp/projects/github/1912-b/ngx-fomantic-ui/.git/bit/components/angular/bit.envs/0.1.9/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:85:5)

ExternalBuildErrors
    at /Users/davidfirst/teambit/bit/dist/consumer/component-ops/build-component.js:707:19
```

**Comment by JoshK2** [comment]
I checked all the projects, and the bug is fixed!
Thanks!
