### ISSUE TITLE
Error when building on Netlify

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1913]
# Describe the bug

When deploying on Netlify the following error is showing during the build: 

```
8:25:03 AM: (node:1285) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
8:25:03 AM: Cannot read property 'flattenedDependencies' of null
8:25:03 AM: npm
8:25:03 AM:  ERR! code ELIFECYCLE
8:25:03 AM: npm
8:25:03 AM: ERR! errno 1
8:25:03 AM: npm
8:25:03 AM:  ERR! my-new-app@0.1.0 bit-build: `bit build`
8:25:03 AM: npm ERR! Exit status 1
8:25:03 AM: npm ERR!
8:25:03 AM: npm
8:25:03 AM: ERR!
8:25:03 AM:  Failed at the my-new-app@0.1.0 bit-build script.
```

### Steps to Reproduce

(this assumes there is a Netlify account connected to the git repo)

1. Create a React CRA with an import of a bit component
 

2. Create the following script to initialize bit on CI called bit-config.sh. Make sure it has execution privileges (chmod +x): 
```
bit config set analytics_reporting false
bit config set anonymous_reporting false
bit config set user.token ${BIT_TOKEN}
echo @bit:registry=https://node.bit.dev >> .npmrc
echo //node.bit.dev/:_authToken=${BIT_TOKEN} >> .npmrc
```
3. Set BIT_TOKEN as an env variable on Netlify with a valid token. 

4. Create the following npm scripts in the project: 
```bash
    "bit-ci": "./bit-config.sh",
    "bit-build": "bit build",
```

5. Install bit-bin as a local dev dependency on the project. 

 7. Define the build steps on Netlify as following:  
```
npm run bit-ci; npm run bit-build; npm run build
```

8. push the git repository / run a deploy. check the log. 

### Expected Behavior

The build is deployed (happen). 
No errors on the log (errors exist)

### Screenshots, exceptions and logs

- Bit version: 14.2.3
- Node version: v10.16.2 is already installed.
- npm / yarn version: npm 6.9.0
- Platform: Ubuntu Xenial 16.04 
- Bit compiler (include version):  "compiler": "bit.envs/compilers/react@1.0.2" Bit tester (include version):

**Comment by GiladShoham** [comment]
@Tallyb From the error, it looks like it's an issue with a specific component.
Can you share the component you worked with?
