### ISSUE TITLE
How do you create your own remote collection?

### ISSUE THREAD

**Issue by kennethchoe** [teambit/bit#1915]
This sounds like very basic question, but I tried and could not find an answer from my own searching.

https://docs.bit.dev/docs/cli-remote.html implies you can create your own collection and add it as your remote.
https://github.com/teambit/bit-docker seems the one I can use it for that purpose.
https://github.com/teambit/bit says "You can set up a collection on any server, or use Bit’s component hub."

But I have hard time finding exactly how to set up a collection on any server. All documentation I find leads to using bit.dev. Is there a way for me to start this?

Thank you!

**Comment by itaymendel** [comment]
hi @kennethchoe as mentioned here #1337 , you can find this information in [this page](https://docs.bit.dev/docs/bit-on-the-server.html#setting-up-a-bit-server) in the docs.
When you set up your own remote you'll need to use SSH based authentication, just like one would configure for any regular *nix server (creating an SSH key pair and put the public part on the remote server).

**Comment by GiladShoham** [comment]
@kennethchoe You can also use this as a reference:
https://github.com/teambit/bit-docker
(we should update the node version in the docker hub since bit is required node > 8.13.0 now), but you can change it and build it locally.
