### ISSUE TITLE
nothing to build message should not exit with status code 1

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1916]
### Describe the bug
When you run bit build and there is nothing to build we shouldn't fail the process. This is a valid outcome. 

### Steps to Reproduce
bit build on no changes. 

### Expected Behavior
Bit prints out the message and finishes with status code 0. This is for automates processes. 
An options is to make it configurable. 

### Screenshots, exceptions and logs
![nothing-build](https://user-images.githubusercontent.com/1002622/62832501-ee5ff500-bc37-11e9-8c8a-326efc8ffe96.png)

### Specifications

  bit version   : 14.2.3
  node version  : v12.3.1
  npm version   : 6.9.0
  yarn version  : 1.16.0
  platform      : linux

**Comment by GiladShoham** [comment]
you are correct. we will fix it.
