### ISSUE TITLE
Abstract fs api for bit 

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1920]
### Description

Bit internal functions need a files system API to impose general rules on what bit can read/write/del etc in run time. 

### Describe the solution you'd like

Abstract fs module which provides a controlled fs API with the ability to add rules. This will make bit's policy on file access unified across the system. This is useful in terms of safety and security.

**Comment by davidfirst** [comment]
I started implementing it as part of the `capsule` feature. You can check out the [`DataToPersist` class](https://github.com/teambit/bit/blob/a445843b2993cba65f0014e7c6ddfe10c1859e2b/src/consumer/component/sources/data-to-persist.js).
All files writing/removing/symlinks when importing components are going through its interface.

@qballer , mind to elaborate about " This will make bit's policy on file access unified across the system"? what would you expect from such API?

**Comment by GiladShoham** [comment]
@davidfirst It should go to the same place even from other flows like move, remove so on.
The purpose is to make sure there is one place dealing with the actual FS. to prevent cases where bug somewhere in the flow will result in deleting / corrupting / moving wrong files.
This abstraction, for example, will make sure we do nothing for paths outside the workspace dir. 
Or not deleting files which are not in the .bitmap.

**Comment by itaymendel** [comment]
implemented for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
