### ISSUE TITLE
How to re-export component without retagging?

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1923]
I am trying to export my component to two scopes.
```bit export bit.examples typed-react```
```bit export kutner.normal typed-react```

however, I am getting this error:
```component bit.examples/react-typed has been already exported to bit.examples```

this is nice for most cases, but sometimes I just want to export again. Is there a way to do this without retagging the component?

### Context and additional information
bit: 14.2.3
yarn: 1.16.0
node: 12.1.0
os: MacOS 10.14.6

**Comment by GiladShoham** [comment]
@KutnerUri There is no such way to do it now.
But it's a nice feature to have. 
We will prioritize it and add to the roadmap.

**Comment by KutnerBitsrc** [comment]
thanks! :)

**Comment by itaymendel** [comment]
`sync` internal command can resolve this issue.
closing.
