### ISSUE TITLE
build ghost files

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#1924]
When running bit build, I often get unexpected files that stay forever.

See this component as an example:
https://bit.dev/bit/utils/project/config/

even after deleting env-config.ts and env-config.spec.ts, I am still getting this result:
```
❯ bit build project/config
/Users/kutner/Documents/Projects/sandbox-playground/components/project/config/dist/project/config/env-config.d.ts
/Users/kutner/Documents/Projects/sandbox-playground/components/project/config/dist/project/config/env-config.js
/Users/kutner/Documents/Projects/sandbox-playground/components/project/config/dist/project/config/env-config.js.map
/Users/kutner/Documents/Projects/sandbox-playground/components/project/config/dist/project/config/env-config.spec.d.ts
/Users/kutner/Documents/Projects/sandbox-playground/components/project/config/dist/project/config/env-config.spec.js
/Users/kutner/Documents/Projects/sandbox-playground/components/project/config/dist/project/config/env-config.spec.js.map
```

### Steps to Reproduce

1. ```bit import bit.utils/project/config```
1. delete all files from the component
1. run ```bit show project/config``` to verify the component is empty
1. run ```bit build```

expected - nothing should be in the dist folder
actual - still getting non existing files from nowhere

### Specifications

- Bit version: 14.2.3
- Node version: 12.1.0
- yarn version: 1.16.0
- Platform: MacOS (10.14.6)
- Bit compiler (include version): bit.envs/compilers/typescript@3.0.5

**Comment by itaymendel** [comment]
@KutnerUri try and run `bit build --no-cache`. Does it still build the deleted files?

**Comment by KutnerUri** [comment]
yes this is still happening. I think the original file was not correctly removed from the component.

**Comment by davidfirst** [comment]
Fixed by the PR above. 
Problem was that when creating the capsule, it was also writing the dists files stored in the scope. It has been fixed to not write the dists into the capsule when isolating a component during the build process.
