### ISSUE TITLE
templateUrl without relative path not working

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1925]
I have this code:
```
@Component({
  selector: 'clr-button-group',
  templateUrl: 'button-group.html',
  providers: [ButtonInGroupService],
  host: { '[class.btn-group]': 'true' },
})
```
All the file that the component need is alredy include so I run `bit status` and get this error:
```
button-group ...  issues found       
       missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/clr-angular/button/button-group/button-group.ts -> button-group.html
```

I solve this by changing the path of the file like this:
```
@Component({
  selector: 'clr-button-group',
  templateUrl: './button-group.html',
  providers: [ButtonInGroupService],
  host: { '[class.btn-group]': 'true' },
})
```

So the solution is to config a default path to the folder of the file if the user writes just the file name templateUrl.

- Bit version: 14.2.4-dev.7
- Node version: 12.7.0
- npm version: 6.10.2
- Platform: macOS

**Comment by davidfirst** [comment]
Fixed by manually adding `./` for extracted dependencies from Decorators when they're not relative.
