### ISSUE TITLE
Prerelease version is not working in the CI and in the CLI - semver support

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1928]
### Describe the bug

I exported a component with a prerelease version like this: 2.0.0-1
and a few bugs happens:
- tests are not working in the cloud with this error: 
   `error: version "null" was not found.`
- npm install is working but bit import not with this error:
   `getLatestVersionNumber failed to find the id <account>.<collection>/<comp id> within bitIds` 
- after the components are exported, bit status is not working with this error:
   `getLatestVersionNumber failed to find the id <account>.<collection>/<comp id> within bitIds` 

Why install with npm is working and bit import isn't working?
Why bit allows me to tag with prerelease version if is not working in the CI and other bit commands?
I think is very important that bit support semver versioning because many time developers want to release a dev version with a simple flag in the version like 1.0.0-dev.1, please discuss on this and try to find a solution.

### Steps to Reproduce

1. create a simple file to track as a component with bit
2. bit tag 1.0.0-1 or 1.0.0-dev.1
3. bit export to your collection

### Specifications

- Bit version: 14.2.4
- Node version: 10.16.0
- npm version: 6.9.0
- Platform: macOS

**Comment by ruscon** [comment]
The same issue and question... 
Why don't pre-release versions work at all?
How to test your components before creating a working version in another microservice?

**Comment by itaymendel** [comment]
this is going to be a part of the `lanes` feature set
