### ISSUE TITLE
Shared library: nested package.json dependencies aren't being respected

### ISSUE THREAD

**Issue by qballer** [teambit/bit#1933]
### Describe the bug
I'm working on a component library run entirely by bit. I have a `packages` folder witch contains two packages. when I try and add `@types/node` via overrides, I have to install in the root of the 
project (even though it exists on each package) otherwise bit explodes with the following exception: 

```
unable to manually add the dependency "@types/node" into "common/workspace-helper".
it's not an existing component, nor existing package

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```
While using the following overrides 
```
    "overrides": {
      "*": {
        "devDependencies": {
          "@types/node": "+"
        }
      }
    }
```

### Steps to Reproduce

1. clone [envs](https://github.com/teambit/envs)
2. remove @types/node from root `package.json`
3. run `bit s`
4. get error

### Expected Behavior
Bit will be able to resolve from nested package.json, meaning that bit resolve dependencies to node_modules relative to the file up to root. 

### Specifications

  bit version   : 14.2.4
  node version  : v12.3.1
  npm version   : 6.9.0
  yarn version  : 1.16.0
  platform      : linux

**Comment by davidfirst** [comment]
@qballer , any chance you added the `overrides` section above as is into the package.json of the components? If so, it won't work because of the `*`. 
The `*` makes sense only on the workspace config to catch all components. When entering the `overrides` into the component's package.json, it should be as follows:
```
"overrides": {
      "devDependencies": {
        "@types/node": "+"
      }
    }
```

I tried it myself on bit.envs, typescript compiler and once done, `bit diff` shows the following as expected.
```
➜  bit.envs git:(master) ✗ bit diff
-------------------------------------------------------
showing diff for bit.envs/compilers/typescript
-------------------------------------------------------

--- Dev Dependencies (3.0.14 original)
+++ Dev Dependencies (3.0.14 modified)
- [  ]
+ [ @types/node@^12.7.2 ]

--- Overrides Dev Dependencies (3.0.14 original)
+++ Overrides Dev Dependencies (3.0.14 modified)
+ [ @types/node@+ ]

➜  bit.envs git:(master) ✗
```
