### ISSUE TITLE
Cannot untrack / remove components

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1938]
### Describe the bug

Getting an error when trying to remove or untrack newly added components. 

A clear and concise description of the issue.
See bellow. Files were just added. 
$ bit s
new components
(use "bit tag --all [version]" to lock a version with all your changes)

     > button ... ok
     > pop ... ok
     > sass/about-modal ... ok
     > sass/accordion ... ok
     > sass/button ... ok
     > sass/cashmere ... ok
     > sass/charts ... ok
     > sass/checkbox ... ok
     > sass/chip ... ok
     > sass/drawer ... ok
     > sass/error-pages ... ok
     > sass/form-field ... ok
     > sass/icon ... ok
     > sass/input ... ok
     > sass/list ... ok
     > sass/login-page ... ok
     > sass/menu-drawer ... ok
     > sass/modal ... ok
     > sass/navbar ... ok
     > sass/pagination ... ok
     > sass/picklist ... ok
     > sass/picklist-pane ... ok
     > sass/progress-dots ... ok
     > sass/progress-spinner ... ok
     > sass/tables ... ok
     > sass/_breadcrumbs ... ok
     > sass/_cdk-overlay ... ok
     > sass/_code-highlight ... ok
     > sass/_colors ... ok
     > sass/_divider ... ok
     > sass/_functions ... ok
     > sass/_menu ... ok
     > sass/_mixins ... ok
     > sass/_modals ... ok
     > sass/_popover ... ok
     > sass/_radio-group ... ok
     > sass/_reset ... ok
     > sass/_subnav ... ok
     > sass/_tabs ... ok
     > sass/_tile ... ok
     > sass/_toaster ... ok
     > sass/_tooltip ... ok
     > sass/_typography ... ok
     > sass/_variables ... ok
     > util ... ok
➜  FC git:(dev) ✗ bit untrack sass/*
zsh: no matches found: sass/*
➜  FC git:(dev) ✗

### Steps to Reproduce
add components with a name space: 
bit add projects/components/src/lib/sass/* -n sass
add compiler
run build
try and remove

### Expected Behavior
from the help: 
remove a component (local/remote)
  https://docs.bit.dev/docs/removing-components.html
  the id can be used with wildcards (e.g. bit remove "utils/*")

I guess removing or untracking them can be nice. 

### Specifications

- Bit version: 14.2.4
- Node version: 12.6.0
- npm / yarn version: npm 6.10.3
- Platform: OSX
- Bit compiler (include version): Angular 0.19
- Bit tester (include version):

**Comment by davidfirst** [comment]
@Tallyb try to wrap the wildcard in quotes. e.g. `bit untrack "sass/*"`.
Without quotes, the terminal tries to parse the wildcard itself and passes the results to Bit, which might not be related to what you want. 
The help does show the quotes, however, obviously, this is not clear enough and we must make it so. Any idea how to improve it would be great!

**Comment by Tallyb** [comment]
untrack a new component(s)
  https://docs.bit.dev/docs/cli-untrack.html
  the id can be used with wildcards (e.g. bit untrack "utils/*") =>
You can use a pattern for multiple ids, such as bit untrack "utils/*". (Wrap the pattern with quotes to avoid collision with shell commands. )
