### ISSUE TITLE
Remove bit watch and make it a build / test flag

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#1940]
### Description

Bit watch is currently a different command which is watching build and rebuilding. 

### Describe the solution you'd like

The common standard is to have a --watch flag. 
Remove the bit watch and replace it with a bit build --watch. 
Should support also the existing build options: (verbose / clear cache). 
It is acceptable if clear cache will only happen on startup and not with every run. 

Bonus points for bit test --watch. 

### Describe alternatives you've considered

Keep as is.

**Comment by GiladShoham** [comment]
I agree it's better the way you described.
We will prioritize it and add to the roadmap.

**Comment by itaymendel** [comment]
resolved as part of v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
