### ISSUE TITLE
Feature Request: Track components root dir for better CICD workflow

### ISSUE THREAD

**Issue by valdestron** [teambit/bit#1945]
Hi, first of all, great tool and service bit.dev provides and we already using it and battle testing.
The workflow with bit.dev in our company is different than the most common workflows. I tried to search for solutions or most common approaches but didint find any, so we invented our own.
 
### Description

The case:

From developers perspective: we build our components not using bit binary, we just add some javascript files, in src/components/{component} some tests, build it locally with the analogic compiler that exists in bit.dev, and thats it, basically developer does not use bit binary, only bit.dev for components discoverability.

From CICD perspective: once developer approves PR and merges to master, the pipeline triggers. 
In pipeline we have steps like:
- Install bit binary
- Authorize against some account int hub.bit.dev
- Import components that is described in .bitmap (this is good, it finds the differences and shows which components have changed)
- **Identify new components in the src/components root dir.** this is where we do components root directory check versus .bitmap.
- Next we tag it and export components.

### Describe the solution you'd like

I think we could have at least some option like `rootTrackingDir`, and some command like `bit identify-components` where it lists what is the difference between .bitmap and the 'src/components/*', and update .bitmap with the same -t and -n properties when we use 'bit add'.

The flow will be like:
1. I commited new component files `src/components/new-component`
2. Instead of run `bit add ... ` pipeline runner runs `bit identify-components ...`
3. .bitmap gets updated
4. `bit tag ..`, `bit export ...`
5. git commit -m "[skip ci] Components released and .bitmap updated."

### Describe alternatives you've considered

Alternative right now (if you are using bitbucket pipelines) is:
1. I commited new component files `src/components/new-component`
2. Shell script function identifies new folders in components root dir
3. Pipeline runner runs `bit add $new-cmp-dir -t '$new-cmp-dir/**/*/*test.js' -n $COMPONENT_NAMESPACE`
4. .bitmap gets updated
5. `bit tag ..`, `bit export ...`
6. git commit -m "[skip ci] Components released and .bitmap updated."

**Comment by GiladShoham** [comment]
Hi, while it is possible to implement an extension that will do just that, at the moment there are some APIs we will want to add to the `.bitmap` file itself to ease the development of such an extension.
I can definitely help you do just that.
Having said that, I think that rerunning the `bit add src/component/*` command for every CI run will work for you.
Bit already compares the components to track with the current tracked components in the `.bitmap` file. Which is basically what the script you have implemented does.
You can try and use it and see if it fits your needs.

**Comment by valdestron** [comment]
Hmm

The actual thing is that I am adding components like this:
```
for ... loop
bit add $LOCAL_COMPONENTS_DIR/$1/ -t "$LOCAL_COMPONENTS_DIR/$1/**/*.test.js" -n $COMPONENTS_NAMESPACE
done```

which translates to:
```
for ... loop
bit add src/components/my-component-dir/ -t "src/components/my-component-dir/**/*.test.js" -n component-namespace
done```

The problem is if I do this like this:
```
for ... loop
bit add src/components/* -t "src/components/**/*.test.js" -n component-namespace
done```

Test files: `-t "src/components/**/*.test.js"` is messed up or not recognized in the .bitmap, i tried various test patterns but unless I add one by one with test pattern of that component tests is not tracked.

**Comment by GiladShoham** [comment]
ok, I understand.
We start working on a better API for our extension system which will make it easier.
Meantime you might want to do the bit add programmatically. This will allow you to do it all it once with much better performance and more control. since it's programmatically you can do whatever you want.
I made a small example of how to use it. you can see it here:
https://github.com/GiladShoham/bit-add-many-example
In general, it is just sending an array of components (each one contains the relevant paths/dirs and test files) to the addMany function.

**Comment by valdestron** [comment]
Thanks this is really nice approach, and much more robust.

**Comment by itaymendel** [comment]
resolved as part of bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
