### ISSUE TITLE
bit command not found

### ISSUE THREAD

**Issue by steelow** [teambit/bit#1952]
### Describe the bug

`$ bit --version` produces:
C:\Users\Comp\AppData\Roaming\npm/node_modules/node/bin/node: line 1: This: command not found

### Steps to Reproduce

1. Upgrade node installation to the latest version (i.e. 12.9.0) in Windows 10
1. Restart computer
1. Return to CLI and type: `$ bit --version`

### Expected Behavior

I expected to run the bit commands successfully as I was able to do prior to the node upgrade

### Specifications

- Bit version: 14.2.5
- Node version: 12.9.0
- npm yarn version: 6.11.2
- Platform: Windows 10
- Bit compiler (include version): react@1.0.2
- Bit tester (include version): jest@22.4.3

**Comment by steveswork** [comment]
Actually, this scenario occurs for other global npm scripts as well. A new bug request has been opened with the NodeJS team here: [https://github.com/nodejs/node/issues/29287](https://github.com/nodejs/node/issues/29287)

Please feel free to close out this report whenever possible.

**Comment by appsparkler** [comment]
After running `npx @teambit/bvm upgrade` it worked for me :)
