### ISSUE TITLE
Components do not compile on bit.dev

### ISSUE THREAD

**Issue by AmoDinho** [teambit/bit#1958]
### Description

I am trying to view my components at bit.dev after exporting them from my workspace. When I view an individual component I get the following error: `Unexpected token (10:7)`
### Context and additional information

* Bit version: @latest
* Yarn version: v1.6.0
* OS: Windows 10 64-bit

I've attached a screenshot:
![screenshot-bit dev-2019 08 27-12_10_39](https://user-images.githubusercontent.com/19347140/63763072-477c8980-c8c4-11e9-8c8f-e33d9a119e91.png)

**Comment by JoshK2** [comment]
Hey, you did not import a compiler, so your files are not compiled in the playground.
You can fix this by importing the react compiler in your project with this command:
`bit import bit.envs/compilers/react -c`

So just need to import the compiler, run the following commands and it will work:
`bit import bit.envs/compilers/react -c` - to import react compiler
`bit build` - bit build all your component with react compiler
`bit tag -a` - tag your component with a new version
`bit export <YOUR COLLECTION>` - to export your tagged components

**Comment by JoshK2** [comment]
Also, you need to set `react` and `react-dom` as peer dependencies in your project, or just set overrides in bit, so it will work in bit.dev, and also in other projects that will consume your components, because they have already install `react` and `react-dom` as dependencies.

more info: https://docs.bit.dev/docs/conf-files.html#setting-specific-component-configurations

**Comment by AmoDinho** [comment]
Hi @JoshK2 ! 

Thanks for your help!!! 💇‍♂ 

Followed your instructions and it is now working as expected. 💯

**Comment by JoshK2** [comment]
Hey @AmoDinho, I created a pull request to fix the peer dependencies in your project.
https://github.com/pimp-my-book/umqombothi-component-library/pull/30

Also, If your project is only a component library, and will not run alone, you can set the peer dependencies in the package.json like this:
```
...
"dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "3.0.1",
    "styled-components": "^4.3.2"
  },
"peerDependencies": {
          "react": "16.8.6",
          "react-dom": "16.8.6"
 }
...
```
and not in bit objects.

**Comment by JoshK2** [comment]
@AmoDinho, it's better for you to merge this pr:
https://github.com/pimp-my-book/umqombothi-component-library/pull/31
because it's removed unnecessary dependencies in your project and set them as a peer.
And like this, you don't need to use the overrides option in bit.

**Comment by AmoDinho** [comment]
Hi @JoshK2 , I've just merged it. 

Really appreciate the help from the both of you. 🥇

**Comment by JoshK2** [comment]
@AmoDinho with pleasure.
Nice button 😉
![image](https://user-images.githubusercontent.com/35892475/64107433-2d8aed00-cd83-11e9-82e6-b6f6a3b3e34b.png)

**Comment by AmoDinho** [comment]
@JoshK2 Thanks!

Quick question, is there a way to run bit locally similar to Storybook?
