### ISSUE TITLE
Bit build without compiler show wrong warning

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1959]
When I run `bit build` and I don't import a compiler to the project I get this error:
`nothing to build`
but I have few tracked components so the error needs to be something like this:
`no compiler was defined - checkout https://bit.dev/bit/envs`

And the `nothing to build` warning needs to be if I don't track any component, so I have `nothing to build`.

### Steps to Reproduce

1. create an empty project and init bit
2. create and track a component
3. run bit build

### Specifications

- Bit version: 14.2.6-dev.1

**Comment by itaymendel** [comment]
+1

Let's add a note about defining a compiler if there are local components with no compiler defined (when running `bit build`).

```
nothing to build
learn how to build components - https://docs.bit.dev/docs/building-components.html
```
