### ISSUE TITLE
Collection duplication after deletion and recreation under organizational account

### ISSUE THREAD

**Issue by valdestron** [teambit/bit#1960]
If collection is deleted under organizational account and new collection created, it duplicates.

<img width="1388" alt="Screenshot 2019-08-27 at 17 26 02" src="https://user-images.githubusercontent.com/1742062/63780103-46f9e800-c8f0-11e9-8129-59aa15ade330.png">
<img width="1388" alt="Screenshot 2019-08-27 at 17 27 49" src="https://user-images.githubusercontent.com/1742062/63780104-46f9e800-c8f0-11e9-826b-48c930795ea2.png">

**Comment by itaymendel** [comment]
If you run `bit list <collection name>`, do you see a list of the components that where there?
