### ISSUE TITLE
bit for scripts

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#1966]
I am trying to run bit inside a server script, but I am getting the loader and other data into my log:
```
components[2K[1G[36m⠅⠀[39m importing components[2K[1G[36m⢃⠀[39m importing components[2K[1G[36m⡃⠀[39m importing components[2K[1G[36m⠍⠀[39m importing components[2K[1G[36m⢋⠀[39m importing components[2K[1G[36m⡋⠀[39m importing components[2K[1G[36m⠍⠁[39m importing components[2K[1G[36m⢋⠁[39m importing components[2K[1G[36m⡋⠁[39m importing components[2K[1G[36m⠍⠉[39m importing components[2K[1G[36m⠋⠉[39m importing components[2K[1G[36m⠋⠉[39m importing 
```

I am running with ```--json```, but it generates the same result.
This is especially bad when I am running ```bit import```, it fails because of user credentials and awaits for user prompt, jamming my server script

Expected:
A ```--not-interactive``` flag or similar, that will trim all the unessential output.

### Additional context
Bit version: 14.2.5

**Comment by davidfirst** [comment]
With the PR above, I check whether `--json` flag was used (by any command, not only import), and if so, it does the following:
1. turn off the loader. (so you won't see messages like "importing components").
2. turn off console printing. (so, for example, you won't see the NPM messages).

@KutnerBitsrc , I hope it's sufficient. I'm unsure about the user credentials you have mentioned. I guess you can just log the user in before and avoid the interactive prompt of the user/password. (that's how we handle it in the e2e-tests).

**Comment by KutnerBitsrc** [comment]
ok nice! I hope --json would make development easier.

about the prompt:
yes I got around it by pre-configuring the user, but it's a difficult dev experience.
Bit needs to be less opinionated about how the user is going to use it.

**Comment by GiladShoham** [comment]
let's continue the discussion about the user/pass prompts in the dedicated issue #1973
