### ISSUE TITLE
Ability to track local files and sync with a remote component 

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1967]
### Description

When my local workspace, for some reason lost its sync with it’s remotes (for example- bitmap file got corrupted), I want to be re-track the local (authored) components and set them as a pre-existing component, instead of a new one.

Otherwise I’m forced to import the components and loose their ‘authored’ relationship with my project.

### Describe the solution you'd like

There are two possible solutions I can think of:

1. —id flag of bit-add should support remote IDs
2. New flag called —as to explicitly track local files and set them as a pre-existing remote component.

### Describe alternatives you've considered

I can do this flow manually, but it’s not a fun thing to do:

1. Track the files
2. Open bitmap and locate the component
3. Rename the component to fit the remote name
4. Set ‘exported’ to ‘true’
5. Run ‘bit import’

It should work. But worst case i end up with a ‘modified’ component (which is ok).

**Comment by davidfirst** [comment]
Both options sound good. Still, it sounds like lots of manual work to do. 

Theoretically, it's possible to automate it completely, because in the components objects the file paths are exactly the same as the author ones. So, we basically have all the data we need.
Perhaps a flag of `bit import` would import them all with the author paths and save them in .bitmap as `authored`?

**Comment by GiladShoham** [comment]
@davidfirst That's awesome idea.
I would do both of them. (import and add)
for example, the files might be moved in my workspace, so import only won't work in such case. (but we can identify them by the hash if they are not modified once running bit add).
Also, I would go with option 1 in @itaymendel suggestion (support remote on the --id flag).
We can check locally during the bit add if the remote component exists locally and update the bitmap with the version. or if it does not exist locally (new clone) just add the remote to the bitmap and update everything on the next import.
We should think about what we should specify in the version in such a case.

**Comment by itaymendel** [comment]
Bit already handles cases where no version found in bitmap. When setting a remote id, the user can choose to add a version as well...

**Comment by davidfirst** [comment]
So are we talking about a case when .bitmap got corrupted but the objects are still there?
If so, `bit add` works already. I just tried to export some components, deleted my `.bitmap` file, then re-added them. I got them as expected with `"origin": "AUTHORED"` and `"exported": true`.

**Comment by itaymendel** [comment]
We’re not talking about that. I was answering Gilad’s last question.

The issue is when bitmap is corrupted and there are no objects available in the local scope (or is completely removed).

**Comment by davidfirst** [comment]
OK, so in this case, when the objects are not available and `.bitmap` is corrupted, I guess `bit import` would be a better approach than `bit add`.
With `bit add` it'll be hard to mimic the exact files with the exact name and configuration the user originally did. and once done, the user will anyway need to run `bit import` to get the objects.

Instead, adding a new flag to `bit import` for importing as authored, will be easier and less error-prone.

**Comment by itaymendel** [comment]
I think that adding with a remote `--id` is something that we still need to do. I know that the experience is not 100%, but if we implement a `bit import` flag only and any of the files has moved/renamed/deleted locally, the import flow will fail.

As for the `bit import` flag, I suggest `--set-authored` (for now). And if for some reason the process fails, Bit should kill the process, and tell the user to use `bit add` with a remote ID.

**Comment by davidfirst** [comment]
Not needed anymore as the distinction between `Authored` and `Imported` was gone. The .bitmap file doesn't have this property anymore.
