### ISSUE TITLE
Latest react-typescript compiler (3.0.17) discards SCSS files

### ISSUE THREAD

**Issue by fabgallo** [teambit/bit#1970]
We have components importing styles in SCSS files which properly using react-typescript compiler v3.0.1. We tried to upgrade the compiler, so to use the auto generated `d.ts` instead of having to create them ourselves. The SCSS files are not bundled in the distribution anymore.

[Related discussion on Gitter](https://gitter.im/bit-src/Bit?at=5d6d811b5b9a174fdf253c33)

### Steps to Reproduce

1. have a React component importing a SCSS files (e.g. https://bit.dev/fabgallo/tests/issue/scss-styles/~code?version=3.0.1) with the Bit's own react-typescript compiler v3.0.1
1. upgrade the compiler to a later version (e.g. v3.0.17, but also v3.0.2)
1. when tagging/building the component after upgrading the compiler, the SCSS files are not included in the dist

### Expected Behavior

Keep the SCSS files (screenshot with v3.0.1)
![image](https://user-images.githubusercontent.com/2903427/64134275-7bffb200-cdaa-11e9-9712-90d0d41ddfcc.png)

### Actual behavior

The SCSS files are missing (screenshot with v3.0.17)
![image](https://user-images.githubusercontent.com/2903427/64134285-9cc80780-cdaa-11e9-9c96-740c86d0dfa6.png)
It also seems that the JSMAP is missing

### Specifications

`bit doctor` output
```
  bit version   : 14.2.5
  node version  : v10.14.1
  npm version   : 6.4.1
  yarn version  : 1.15.2
  platform      : win32

  bit version   : 14.2.5
  node version  : v10.15.3
  npm version   : 6.11.2
  yarn version  : 1.17.3
  platform      : darwin

╔════════════════════╤═════════════════════════════════╤════════════════════════════════════════════════════════╤════════╗
║ category           │ name                            │ description                                            │ status ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ configuration      │ validate workspace's bit config │ validate workspace configuration object                │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate git exec               │ validate that git executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ internal store     │ check orphan refs               │ checks for empty internal refs in local workspace      │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ local environments │ check environment symlinks      │ validate generated symlinks for workspace environments │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate npm exec               │ validate that npm executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate yarn exec              │ validate that yarn executable found                    │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ core               │ validate bit version            │ validate that bit version is up to date                │ passed ║
╚════════════════════╧═════════════════════════════════╧════════════════════════════════════════════════════════╧════════╝
```

**Comment by fabgallo** [comment]
[You can also see it in the Playground](https://bit.dev/fabgallo/tests/issue/scss-styles?version=3.0.17) that the component fails to render as it is missing `styles.scss`. You can notice in the bottom left corner the preview I created with v3.0.1, which was working properly.

![image](https://user-images.githubusercontent.com/2903427/64134465-23311900-cdac-11e9-91cf-fee2e956deb1.png)

**Comment by qballer** [comment]
Hi fabgallo, our current compiler doesn't copy those files to the dist. I'm going to release a version which copies all files in the component not handled by the compiler to the dist soon. Will update when it's done, it's on my short list.

**Comment by GiladShoham** [comment]
@fabgallo  You can see an issue about it here:
https://github.com/teambit/bit.envs/issues/48
As a workaround, you might use the [override feature](https://docs.bit.dev/docs/conf-files.html#setting-specific-component-configurations) to make your sass components not using the ts compiler but no compiler at all and it should work.
But it will be better to wait for a new version probably.

I'm closing this issue, since it's a bug in the compiler and not in bit's core.
Please continue discussion at the mentioned issue.

**Comment by fabgallo** [comment]
@GiladShoham thanks for the update.
Our components are not just sass, but actual React ones, therefore we need the compiler.

Question (I still post it here, as I don't think it's entirely compiler related): will Bit keep calculating the dependencies properly? In our real components, some of the `.scss` files imports variables from another Bit component (this time a pure sass one). With 3.0.1 that component was correctly listed as a dependency when doing `bit show`, and imported when needed.

**Comment by GiladShoham** [comment]
@fabgallo 
Does the bit show results are changing when you change the compiler version?

**Comment by fabgallo** [comment]
Both versions seem consistent: the external dependency from the SCSS appears in both

```
╔══════════════════╤════════════════════════════════════════════════════╗
║ Id               │ issue/scss-styles@3.0.18                           ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Compiler         │ bit.envs/compilers/react-typescript@3.0.1          ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Language         │ javascript                                         ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Main File        │ components/issue/scss-styles/index.tsx             ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Dependencies     │ upchain.react/global/assets@5.9.180                ║
║                  │ react@^16.7.0                                      ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Dev Dependencies │                                                    ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Files            │ components/issue/scss-styles/index.tsx             ║
║                  │ components/issue/scss-styles/style.scss            ║
╚══════════════════╧════════════════════════════════════════════════════╝

╔══════════════════╤════════════════════════════════════════════════════╗
║ Id               │ issue/scss-styles@3.0.19                           ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Compiler         │ bit.envs/compilers/react-typescript@3.0.17         ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Language         │ javascript                                         ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Main File        │ components/issue/scss-styles/index.tsx             ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Dependencies     │ upchain.react/global/assets@5.9.180                ║
║                  │ react@^16.7.0                                      ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Dev Dependencies │                                                    ║
╟──────────────────┼────────────────────────────────────────────────────╢
║ Files            │ components/issue/scss-styles/index.tsx             ║
║                  │ components/issue/scss-styles/style.scss            ║
╚══════════════════╧════════════════════════════════════════════════════╝
```

**Comment by GiladShoham** [comment]
> Question (I still post it here, as I don't think it's entirely compiler related): will Bit keep calculating the dependencies properly? In our real components, some of the .scss files imports variables from another Bit component (this time a pure sass one). With 3.0.1 that component was correctly listed as a dependency when doing bit show, and imported when needed

I'm not sure I understand you correctly, So I'll rephrase it as how I understand it. Feel free to re-ask if you didn't get the answer you asked for.
As what I understand is you ask based on the bug that scss files are not copied to the dist folder, whether the scss file dependencies will be listed.
The answer is yes. the copy to dist folder is compiler responsibility while the dependencies resolution is bit responsibility done based on the source files not compiled files. So even if there is a bug in the compiler, the dependencies resolution will still be fine.
