### ISSUE TITLE
Running bit test command show an Vue warning

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1977]
### Describe the bug

I have a project that I wrote and when I run bit test command, the command is not running and show me an error of Vue cli:
```
jotils-test git:(master) bit test remove-duplicates-in-array
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
```

### Steps to Reproduce

1. clone this project https://github.com/JoshK2/jotils
2. run `bit status`, then run `bit import` to update the locale components
3. run `bit test remove-duplicates-in-array`

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/35892475/64247418-81c6d600-cf17-11e9-8c52-99bf46cfb47a.png)

### Specifications

- Bit version: 14.2.5
- Node version: 10.16.0
- npm version: 6.9.0
- Platform: macOS
- Bit compiler (include version): bit.envs/compilers/typescript@3.0.12
- Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by JoshK2** [comment]
I have another bug, and I think is the same root cause.
In .bitmap file, the version parameter is set to 14.2.6-dev.3 and when I run `bit status` I expect from bit to update this value and is not.

**Comment by JoshK2** [comment]
I solved this by uninstalling the Vue globally- `npm uninstall vue -g`, and to be sure that is the problem, I install it again in global, and running `bit status` show me this alert:
```
jotils git:(master) ✗ bit s
⢂⠀ fetching statusDownload the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
nothing to tag or export (use "bit add <file...>" to track files or directories as components)
```

**Comment by GiladShoham** [comment]
sound like an issue with the Vue detective.
We might want to use it only if there are Vue files..
