### ISSUE TITLE
Symlink file error - bit test is not working with compiler that work with bit capsule

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1978]
### Describe the bug

Bit test is not working with a compiler that used the capsule.
This is the error I get:
`fatal: trying to write a link file into a symlink file at "/Users/yoshuakuttler/Documents/MyReactProjects/jotils/node_modules/@bit/joshk.jotils.letter-count/src/components/letter-count/index.ts"`

### Steps to Reproduce

1. clone the project https://github.com/JoshK2/jotils and check out to tags 2.0.8
2. run npm install and bit import to be updated with the remote collection.
3. import the compiler https://bit.dev/bit/envs/compilers/typescript
3. run bit test leter-count, and it's not working.

And now if you import a version of the compiler that is not working with the bit capsule, everything is work as expected.
For example use this version: https://bit.dev/bit/envs/compilers/typescript/~code?version=3.0.0

### Specifications

- Bit version: 14.2.6-dev.3
- Node version: 10.16.0
- Platform: macOS
- Bit compiler (include version): typescript 3.0.25 (every compiler with bit capsule)
- Bit tester (include version): mocha 5.0.2

**Comment by davidfirst** [comment]
@qballer , @JoshK2 
After a long debugging session, it turns out the issue is with the compiler `bit.envs/compilers/typescript@3.0.22`. 
It randomly returns a wrong distMainFile. Sometimes `index.js`, sometimes `index.js.map`.

Looking at the compiler code, the issue is with this function:
```
export function findMainFile(context: CompilationContext, dists: Vinyl[]) {
    const getNameOfFile = (val:string, split:string) => val.split(split)[0]
    const sourceFileName = getNameOfFile(context.main, '.ts')
    const res = dists.find((val)=> {
        return  sourceFileName === getNameOfFile(val.basename, '.js')
    })
    return  (res || {relative:''}).relative
}
```
it splits the filename by '.js' and compare to the basename, so both names (index.js and index.js.map) fit the criteria.

**Comment by GiladShoham** [comment]
@davidfirst Nice catch. I read this code yesterday, thought about it might be a problem with d.ts. Conclude it won't be a problem.. but didn't think about map file.

**Comment by GiladShoham** [comment]
This is a ts-compiler bug, opened a new bug in bit.envs about it.
Please follow there.
@JoshK2 if after fixing the compiler it happens again, please re-open.
