### ISSUE TITLE
Adding Aurelia support

### ISSUE THREAD

**Issue by brandonseydel** [teambit/bit#1980]
### Description

I would like to add a new compiler for Aurelia.  

### Describe the solution you'd like

I need to gather information on how to do this.

### Describe alternatives you've considered

N/A
### Additional context

Trying ti get bit support for Aurelia 2 to coincide with our launch.

**Comment by qballer** [comment]
Bit's environments are how we integrate bit with the development tools our users are using. It's a way to extend bit and we are working on a full restructure of this API. This may create issues with rolling an environment of your own (which isn't a basic fork). 
 
Right now you can checkout our new typescript compiler (which I'm actively working on) in this 
repo: https://github.com/teambit/envs. 

Our old API is used by the environments in this repo: https://github.com/teambit/bit.envs

I will personally love that the Aurelia community to be able to work with bit. I suggest we will discuss things directly: My email is doron@bit.dev.
