### ISSUE TITLE
Support multiple lanes of development for components

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#1986]
> **NOTE**
>
> The description of `lanes` is still not finalized. I'm publishing it as a public issue for people to read and comment as we progress with finalizing the design.

`Lanes` is designed to help developers apply and collaborate on changes across multiple components without interfering with the main development course. It lets developers manage cross-component dependency graph changes.  

`Lanes` are highly inspired by Branches, implemented in SCMs such as Git. Imagine a git-branch that can sync changes between different repositories.

## Introduce `bit lane` functionality

bit-lane - List, create or manage lanes.

## Description

Diverge development for all components in a workspace to another lane of development. Each change of a component in the workspace is in-sync with all other changes by creating an object called Lane that syncs changes together.  
The addition of Lanes to a component creates an additional HEAD pointer for each component that points to the latest snapshot of its component. When creating a snapshot for a component, that snapshot is listed as a snapshot in the lane using a global Lane namespace.

### Lane is a pointer

Lane can point to:

- component@version
- component@HEAD (latest snapshot)

Whenever a user snaps/tags a component, Bit adds/updates the Lane pointer accordingly.

### Local/Remote lane

Similar to Git's remote-branch, Bit manages both local and remote Lanes in a workspace. This is to distinguish a workspace current progression and the remote's incoming changes.

### Cross-remote lanes

A Lane can be managed across many collections. This means that upon the creation of a new Lane, Bit generates a unique ID for it, and when components from different collections are diverged into a Lane, and then exported - the Lane object is exported as well.

#### Detached HEAD

When checking out to an old snap/tag Bit should enter a 'detached HEAD' state (meaning - the checkout snap is different from the HEAD of the component in the specific lane). This means that the user can't create a new snap/tag. They are forced to create a new lane and work from there if required to do any modification.

### Synopsis

```sh
$ bit lane [--delete] <lane name>
```

##### `--delete`

Deletes a local lane.

#### create new lane

Creating a `lane` in a workspace makes all component's `snap`s and `tag`s to be in that lane.

```sh
$ bit lane new-auth
created lane 'new-auth'
```

Each component has a HEAD pointer to the last snap in a lane. This is so when checking-out a past snap/tag, Bit'll know if it's in a `detached HEAD` state.

#### show all lanes

Lists all local lanes and mark the currently checked-out one.

```sh
$ bit lane
new auth
* master
```

#### switch between lanes

use `bit checkout` to checkout to a lane. All components that have a HEAD that points to a snap should checkout to their HEAD. If components are modified, merge with it.

This command checkout all components in the lane...

```sh
$ bit checkout new-auth --lane
switched to lane `new-auth`
```

#### snap all changes to the lane

After checking out to a lane, I made the following modifications:

- changed two components in my workspaces.
- override a dependency version.
- replaced one dependency implementation.
- added new dependency to one component.

```sh
$ bit snap --all
```

All changes are in that specific lane. Component HEADs should point to their new snap.

#### merge lane

This command merges all components in a lane.

- Merge order?

check which lane you are on.

```sh
$ bit lane
* new-auth
master
```

move back to master.

```
$ bit checkout master
```

merge the lane into master.

```
$ bit merge new-auth
 // output to be defined
```

how to support squash?
merge conflict types and ways to handle them:

- dependency conflicts (two lanes asking for the same component dependency but with different versions, dep impl. changes)
- source code conflicts

after success:
all components are modified and waiting for a `merge` commit / tag. commit/tag will get both parents.

## Additional commands and flows to consider

- bit reflog' shows all snaps... to be able to recover stuff. (need a way to point a l)
- 'bit reset' to control the HEAD pointer of a lane
- default lane for component
- component rename (diverge to a new component)

**Comment by davidfirst** [comment]
Implemented. See https://github.com/teambit/bit/pull/2754 for more details. (there are still some pending tasks).
