### ISSUE TITLE
Feature: use `defaultScope` for importing component

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#1997]
### Description

In 14.3.0 You have released a new `bit.json` config option `defaultScope`, which is used for simplifying export of a component. It would be nice, if that feature could be used for importing it as well.

### Describe the solution you'd like

Having `defaultScope` set to `bit.envs`, command

`import components/component`
will be the same as
`import bit.envs/components/component`

### Describe alternatives you've considered

Maybe there is some sense to have `defaultExportScope` and `defaultImportScope` options. But in my perspective it seems too verbose.

**Comment by itaymendel** [comment]
at the moment we prefer being specific on what's imported specifically, so i'm closing this one.
