### ISSUE TITLE
flattenedDependencies error when running bit build

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#1999]
### Describe the bug
when I clone a repository that used imported components, like this:
```
"@bit/joshk.<collection>.<component id>": "file:./components/<component id>"
```
I get this error:
```
Cannot read property 'flattenedDependencies' of null
```

To solve this, I just run `bit import` command to import the latest version of all sourced components, and then run again `bit build`.

### Steps to Reproduce
1. clone a repo that used imported components.
2. run `bit build`

### Specifications
- Bit version: 14.2.4
- Node version: 12.7.0

**Comment by davidfirst** [comment]
@JoshK2 , please send me the repo you used. I wasn't able to reproduce it with another repo that has imported components.

**Comment by JoshK2** [comment]
It's a private repo, I added you as a collaborator 
https://github.com/JoshK2/test-with-azure/invitations

**Comment by davidfirst** [comment]
It happened because the component was missing from the scope. The fix above makes sure to not load the component when its objects are missing.
