### ISSUE TITLE
Safe package.json keys overrides

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2000]
Bit let's you override any key in the pacakge.json, apart for the name, version and main file. 
Those keys are defined in the first level of the overrides. e.g: 

```
overrides: {
"someRule/*": {
   "env": {...},
   "devDeps": {},
   "exclude": true,
   "bin": "..."
  }
}
```

However, Bit currently has 2 internal properties that are added at the same level: exclude and propagate. This makes it unsafe, in case NPM / Yarn decide to add a key with the same name. 

To make it safe, there are 2 options: 

1) put all the keys under a designated entry, such as "package". 
2) store Bit internal properties under a designated key, such as "_internal" or "_options".

**Comment by itaymendel** [comment]
@Tallyb , i don't understand option #1. Can you paste a config example of it?

**Comment by Tallyb** [comment]
1) is answering a case that in next release NPM decide to have a key called "exclude". if we will add all keys (probably deps excluded) under package, we can avoid it. 
I think #2 is preferable

**Comment by davidfirst** [comment]
I agree about #2 is preferable and I would add `bit_` prefix instead of just `_`. I think it's safer.

**Comment by GiladShoham** [comment]
what about something like `__bit__myOption` to show it's both bit and something internal (aka not passing to the component package.json)

**Comment by davidfirst** [comment]
Sounds good to me. I think one underscore is enough.  `_bit_exclude`, `_bit_envs`.

**Comment by GiladShoham** [comment]
what about *dependencies should they be _bit_dependenices or just dependencies?
since they are not exactly bit.. but also not exactly override as is (+ and - signs for example)

**Comment by davidfirst** [comment]
A good question. Not sure. I'm good with both options.

**Comment by GiladShoham** [comment]
@Tallyb @itaymendel what do you think?

**Comment by itaymendel** [comment]
I'm good with either...

**Comment by itaymendel** [comment]
available as a part of the `pkg` extension for Bit v15.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
