### ISSUE TITLE
Specify witch files to download in package

### ISSUE THREAD

**Issue by valdestron** [teambit/bit#2005]
Not sure if this is an issue or I am just missing something in configuration/documentation.

<img width="464" alt="Screenshot 2019-09-17 at 16 48 06" src="https://user-images.githubusercontent.com/1742062/65047489-3545b680-d96b-11e9-9649-ce61a831d5a4.png">

In .bitmap, all files within component is tracked, but when installing would be great to not download test files at least.

**Comment by itaymendel** [comment]
Do you mean when running `npm install` for a component?

@GiladShoham we can decide not to package spec files, when packaging components, right?

**Comment by GiladShoham** [comment]
@itaymendel yes we can make it, but it will be globally for all packages unless we provide a way to control it from bit.dev.
Also if we go that way, I wouldn't change already created packages, so only from now on.
