### ISSUE TITLE
Removing a dependency from a remote (using --force), corrupts all dependents

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2006]
### Describe the bug

I created two components, compA depends on compB. Both were tagged and exported. Removing compB from the remote causing the compA to have a non-exist dependency, which then, makes compA to be invalid and not exportable/consumable.

### Steps to Reproduce

1. add two components compA, compB, require/import compB in compA.
2. tag and export.
3. remove compB locally and from the remote using `--force` flag.
4. re-create compB so the require statement of compA would be valid again.
5. tag the changes and try to export.

You'll get an error about compB was not found.

### Expected Behavior

Two options I see here:
1. Disable the `--force` flag. Do not allow to remove dependencies that have dependents. Instead, show the users all affected dependents and ask the user to remove them all.
2. Make a clear message that using the `--force` flag will corrupt all dependents components and make them un-consumable. 

### Specifications

- Bit version: 4.3.0
- Node version: Any
- npm / yarn version: Any
- Platform: Any
- Bit compiler (include version): N/A
- Bit tester (include version): N/A

### Additional context

This happened to a Gitter user who was planning to rename an id of a component. 
Since there is no option to rename an id, he was trying to remove the component (locally+remote) and re-create it with another name.

cc: @GiladShoham , @itaymendel .

**Comment by davidfirst** [comment]
A Gitter user reported that after re-creating the removed component with the same name, and re-tagging and exporting, it did work. After that, the user was able to safely delete the component.
So, that could be a workaround for anyone else getting this issue until it's fixed.

**Comment by davidfirst** [comment]
Discussed with @GiladShoham , he suggested going with option # 2. 
The reason why not # 1 is because, many times the user intention is to re-create the component, in which case, once the component is recreated the dependents should work.
Also, a separate task should be opened about renaming a component id.

**Comment by davidfirst** [comment]
I changed the help of the `--force` flag from:

> force remove (default = false)

to:

> WARNING - it allows removing components even when other components depend on it, it will corrupt those dependents components (see the link above for more info)

cc: @Tallyb , @itaymendel

**Comment by Tallyb** [comment]
WARNING - using force may remove components that other components depend upon. This may corrupt the dependent components (see the link above for more info)

cc: @Tallyb , @itaymendel

**Comment by davidfirst** [comment]
After discussed with Tally, I changed the help of the `--force` flag to the following:
`removes the component from the scope, even if used as a dependency. WARNING: components that depend on this component will corrupt`.
