### ISSUE TITLE
bit import fails when one module resolution alias is a directory of another alias

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2013]
### Describe the bug

Bit fails to import or npm install a component when is using multiple module resolution aliases where one of them is a directory of the other.

### Steps to Reproduce

1. create a component `bar/foo` that consists of the following three files:
src/utils/is-type.js => ''
src/utils/index.js => ''
src/bar/foo => `require('@/utils'); require('@utils/is-type');`
2. add the following configuration into the bit.json: `resolveModules = { aliases: { '@': 'src' } };`
3. tag and export.
4. in another workspace, import the component. You'll get the following error
```
unable to add the file "components/bar/foo/node_modules/@/utils/is-type", because another file "components/bar/foo/node_modules/@/utils" is going to be written.
one of them is a directory of the other one, and is not possible to have them both
```

### Expected Behavior

The import should succeed.  

### Specifications

- Bit version: 14.3.0

### Additional context

Running `bit cmp bar/foo@latest`, shows the following:
```
"customResolvedPaths": [
        {
            "destinationPath": "src/utils/index.js",
            "importSource": "@/utils"
        },
        {
            "destinationPath": "src/utils/is-type.js",
            "importSource": "@/utils/is-type"
        }
    ],
```
Upon import, Bit generates these two link files:
```
@/utils
@/utils/is-type
```
Which is impossible because one is a directory of the other. They can't be both files.

The issue was found by a Gitter user @zeesulehria.

**Comment by zeesulehria** [comment]
Great work!
