### ISSUE TITLE
overrides object on 'bit.json' is written even is empty

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit#2018]
after bit import bit add empty overrides object to bit.json

```json{
    "env": {},
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm",
    "overrides": {
        "guyssar.pr-test/is-string": {}
    }
```

### Steps to Reproduce

1. `$ git clone git@github.com:guysaar223/is-string.git`
2. `$ bit import` 
3. `$ bit import guyssar.pr-test/is-string --skip-npm-install --ignore-dist --json`

### Expected Behavior
should not add overrides is the object is empty

### Specifications

- Bit version: 14.3.0
- Node version: 10.16.0

**Comment by itaymendel** [comment]
irrelevant for v15
