### ISSUE TITLE
Merge of dependant component is removing it's changes

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#2019]
### Describe the bug

When using `bit import {component} --merge` on a component, which is having another imported and changed locally component as dependency results in changes of that component being deleted.

### Steps to Reproduce

1. Create 2 components in a new workspace: comp-a and comp-b. Comp-a should import comp-b and has it as a dependency
1. `bit tag --all`
1. `bit export {scope}`
1. `bit eject comp-a`
1. `bit eject comp-b`
1. import comp-b back to workspace and change something(like adding a line)
1. import comp-a with `bit import {scope}/comp-a --merge`
1. Comp-b has been overridden with it's exported version

### Expected Behavior

Changes in comp-b should be correctly merged without removing lines.
May be there should be an opposite option to `override` like `theirs` and `ours` in `git merge`, so user could have more control over file changes in his workspace.

### Specifications

- Bit version: 14.3.0
- Node version: v10.16.0
- npm version:  6.11.2
- Platform: macOS 10.14.6 
- Bit compiler (include version): -
- Bit tester (include version): -

**Comment by davidfirst** [comment]
As a reference, a similar bug was fixed recently. https://github.com/teambit/bit/issues/1903.

**Comment by davidfirst** [comment]
Fixed by the PR above. Now in case the dependency is in the workspace, it doesn't override it.
