### ISSUE TITLE
Building an imported typescript component doesn't reflect dependency changes

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2024]
### Describe the bug

Bit writes the cached dists files of an imported typescript component although its dependency has changed.
Since typescript compiler uses the dependencies to compile the component, it results in dists files with the old dependencies data.

### Steps to Reproduce

1. Create two components, comp-a requires comp-b, tag, export.
2. Import them both to a new workspace.
3. change comp-b and build comp-a. 

Observe that comp-a doesn't have the changes of comp-b.

### Expected Behavior

Bit should not use the cached dist but re-build the component.

### Specifications

- Bit version: 14.3.0
- Node version: 
- npm / yarn version:
- Platform: Mac
- Bit compiler (include version): bit.envs/compilers/typescript@3.0.30
- Bit tester (include version): N/A

### Additional context

The issue has been reported over Gitter by @DeyLak.

**Comment by GiladShoham** [comment]
This is a very important issue.
However, I'm not completely sure about it.
When importing 2 components, A requires B.
you will get A, where the node_modeuls of B inside A will point to?
An installed copy of B or B in the workspace?
how do you move between the options?
If it points to another instance of B (nested one) it's fine, if it's pointed to the workspace one it's an issue. let's talk about it...

**Comment by davidfirst** [comment]
@GiladShoham , I was under the impression that the issue here is about the dists written into the capsule, but I might be wrong.

@DeyLak, after digging into this in the code, it seems like it works as it should. I also tried to reproduce it by the instructions above and Bit did build the changed dependencies and didn't use their dists from the cache. 
So, the issue might be related to what Gilad mentioned about different versions of the dependency installed in the workspace. You might have the same component imported in the workspace with version 1.0.0 and also installed as a dependency with version 2.0.0.
If you can zip your workspace or suggest how to reproduce it, it'd be great.

**Comment by GiladShoham** [comment]
@davidfirst I just worked with @Tallyb with an angular use case, and we faced the same bug. It doesn't work as expected. me or @Tallyb will help you understand why it should behave differently.

**Comment by davidfirst** [comment]
@GiladShoham , I was wrong in my previous message. I tried a different scenario for some reason.

The original issue is correct and it's the same bug Tally opened https://github.com/teambit/bit/issues/2060.

The solution should be to check whether one of the dependencies has changed and if so, re-build the component (rather than using the cached from the objects).
The thing is that this behavior is only relevant to compilers that generate capsules and use the `shouldBuildDependencies` prop. As such, two issues arise:
1. this prop is used inside a function. We'll probably need a new prop to tell whether rebuild on dependencies changes. That's minor.
2. we have to have the compiler imported in order to check that prop. It'd be a shame to import the compiler only to check for that prop. Because it means that we always have to import the compiler locally no matter what, and only then we can check whether the compiler needs the rebuild process or not. Maybe we'll need to save this data in the objects somehow. Not sure.

**Comment by GiladShoham** [comment]
@davidfirst Yes, I totally understand the issues you raised.
I believe we will have to get it as a prop from the compiler and store it in the component model (maybe it's time to add some object in the version model to store different compiler flags/options like this one, maybe the mainDistFile, packgeJsonNewProps and such).

**Comment by davidfirst** [comment]
@GiladShoham , for now, I've done it as simple as I could, without any hashes.
```
"extensions": [
        {
            "id": "bit.envs/compilers/angular@0.2.0",
            "data": {
                "shouldBuildUponDependenciesChanges": true
            }
        }
    ]
```
It'll be easy to change it later as it's not part of the hash calculations of Version object.

**Comment by DeyLak** [comment]
@davidfirst Does this apply to typescript compiler also?

**Comment by davidfirst** [comment]
@DeyLak , yes. The Typescript compiler is the main reason for this fix. (this issue was actually reported by you and I opened a Github ticket for this).

**Comment by DeyLak** [comment]
@davidfirst I'm not sure, I got how to use it. Do I need to write in my `bit.json` something like this:
```
"extensions": [
        {
            "id": "bit.envs/compilers/typescript@3.0.30",
            "data": {
                "shouldBuildUponDependenciesChanges": true
            }
        }
    ]
```
Should I update my typescript compiler, or should I wait for the next bit release?

**Comment by davidfirst** [comment]
@DeyLak , the `extensions` I posted above is just an internal structure of how things are saved into the objects, disregard this.

The fix is merged and will be available on the next Bit release.
