### ISSUE TITLE
Versions mismatch error message

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2030]
If there is a minor / major version mismatch between workspace and server, a message is shown as 
`Fatal: There is a mismatch between the remote server version - "14.4.0" and your bit version - "14.3.0", please update`
And Bit continues with execution of the command. This leaves confusion, as it is not clear if the command was successful or not. 

If the error is Fatal - Bit should stop. 
Also, consider sending a fatal error only on major mismatch and not on minor.

**Comment by GiladShoham** [comment]
I agree with @Tallyb about both

**Comment by davidfirst** [comment]
For some reason, it was using the "major" error for a minor mismatch. Fixed.
When it's a major mismatch it does throw an error and stop the process.
