### ISSUE TITLE
bit list --outdated cli wrong typing

### ISSUE THREAD

**Issue by rbalet** [teambit/bit#2031]
### Describe the bug

When I type bit list --outdated inside my commande line tool, the char come twice
ex : 
![image](https://user-images.githubusercontent.com/44493964/65608355-61d28180-dfae-11e9-82f7-604382c5b274.png)

### Steps to Reproduce

1. Enter : `bit list --outdated` in an commande line tool (On an windows os)
2. Try to give you user name

### Specifications

- Bit version: 14.4.0
- Node version: 10.13.0
- npm / yarn version: 6.4.1
- Platform: win32 x64
- Bit compiler (include version): angular@0.2.0
- Bit tester (include version):

### Additional context
I've try with the native windows terminal and with the one from [git](https://git-scm.com/)

**Comment by GiladShoham** [comment]
This is not bit list related.
You see the user/pass prompt since the other methods of authenticate you against bit.dev server were failed.
You see it when using `--outdated` since only when using this flag it will go to the remote server.
I saw this chars duplication in the past. it's indeed a bug. 
We will fix it.

**Comment by rbalet** [comment]
@GiladShoham It may help, but I'm using a self hosted server. It's the reason why I'm not logged in.

**Comment by GiladShoham** [comment]
@rbalet It might be an issue with `--outdated` when working with a self-hosted server. I'll check it and update here.

**Comment by GiladShoham** [comment]
Ok, I've tested it and it doesn't look like something related to `--outdated` specifically. (except that this operation is running against a remote).
Do you able to run other operations from the same machine against your remote scope?
like import / export / bit list [remote-scope-name]?
It might be an issue with the ssh keys that are not in the authorized keys.
it worth taking a look at https://github.com/teambit/bit-docker
specifically in the init.sh script which done this adding to the authorized keys.

**Comment by rbalet** [comment]
Like #2049 I forget to add the ssh key, so the error may be related.

Yes, I'm able to run every other operations from the same machine against my remote scope, the ``--outated`` is the only one not working properly.

Even if, after adding the ssh key fix the error, I don't understand why it's makes my cmd work like that.

**Comment by GiladShoham** [comment]
@rbalet This behavior of duplicate characters is indeed a bit of mystery, I saw it long time ago in different cases, but it's very hard to reproduce it on a dev machine, so very hard to fix.
(even if I do not configure the ssh keys on my machine, I got the username prompt, but the duplication are not happening). Once I'll succeed to reproduce it here, I will fix it.

**Comment by itaymendel** [comment]
irrelevant for v15,as we only use https tokens from now. no username/pass combo

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
