### ISSUE TITLE
bit link doesn't generate all custom resolved modules links

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2033]
### Describe the bug

`bit link` generates the missing links of custom-module-resolution.
For example, if an alias was set from `src` to `@foo`, bit link creates `node_modules/@foo` file that links to the 'src' in the imported component.
The issue happens when the following criteria are met:
1. the alias has more than two slashes. e.g. `@/foo/bar`. 
2. a component file refers to multiple aliases with the same prefix.

In case the first link exists but not the second, `bit status` shows as if the first link is missing.
When running `bit link` it's able to generate the missing link.

### Steps to Reproduce

1. create two aliases: `src/bar/foo => @/bar/foo`, `src/bar/baz => @/bar/baz`
2. create a component that require the above two. tag, commit and export.
3. import the component above, manually delete the link of `@/bar/baz`.
run 'bit status' and 'bit link' to see the issues above.

### Specifications

- Bit version: 14.4.0
- Bit compiler (include version): N/A
- Bit tester (include version): N/A

### Additional context

The issue was found by @zeesulehria  and reported via Gitter.

**Comment by davidfirst** [comment]
The commits above fix the `bit link` part to link all the missing links.
The failure to recognize the correct missing links is still due.

**Comment by itaymendel** [comment]
irrelevant with v15
