### ISSUE TITLE
publish package directly into the npm

### ISSUE THREAD

**Issue by smmoosavi** [teambit/bit#2047]
### Description

I want to publish packages directly to my private NPM registry

### Describe the solution you'd like

```bash
bit init
# add some components in src/components
bit add src/components/*
bit tag --all 0.0.1
bit export --npm-only --registry http://npm.some-company.com # publish directly to npm registry without connecting to bit hub or any other ssh server
```

**Comment by gogoyqj** [comment]
any progress？

**Comment by GiladShoham** [comment]
@gogoyqj It's on our roadmap but we didn't start working on this yet. I don't have an eta yet. I'll update this issue on any progress.

**Comment by gogoyqj** [comment]
@GiladShoham bravo

**Comment by smoakey** [comment]
@GiladShoham Looking at the Bit.Server docs it says you would have to do something like is done in this file: https://github.com/teambit/bit/blob/master/e2e/npm-ci-registry.ts

I got this link from: https://docs.bit.dev/docs/bit-server#package-registry

----

The file looks straight forward. How would I hook into Bit in order to run some come like this?

Also what does the config setting "registry" do? Is it related to this?

**Comment by GiladShoham** [comment]
@smoakey We are in the middle of re-write our entire extension system.
Once this is released it should be much easier to achieve something like this. (we might but can't promise) provide an extension for publishing to npm created by the core team.
Also, many of the current extension APIs are about to break (they are internal only right now). so better to wait a bit more for this.
I don't have an exact eta, but it will take probably a few weeks.

**Comment by gogoyqj** [comment]
with a custom extensions worked for me

```ts
function npmPack(cwd: string, outputPath: string, override = false) {
  // pack 之前修改 scope
  modifyPackageJson(cwd, versionModifier);
  fs.writeFileSync(path.join(cwd, '.npmrc'), npmrc, { encoding: 'utf8' });
  return execa('npm', ['pack'], { cwd }).then(result => {
    const stdout = result.stdout;
    const tgzName = stdout.trim();
    const pkgJson = readPackageJson(cwd);
    const tgzOriginPath = path.join(cwd, tgzName);
    const tarPath = path.join(outputPath, tgzName);
    const response = {
      pkgJson,
      tarPath
    };
    if (tgzOriginPath !== tarPath && fs.pathExistsSync(tarPath)) {
      if (override) {
        fs.removeSync(tarPath);
      } else {
        throw new Error('文件已存在，请使用 --override');
      }
    }
    if (tgzOriginPath !== tarPath) {
      return fs.move(tgzOriginPath, tarPath).then(() => response);
    }
    return response;
  });
}

/** 发布到 knpm */
function npmPublish(cwd: string, gzFile: string) {
  return execa('npm', ['publish', gzFile], { cwd });
}

const Pack = {
  init: ({ api }: { api: any }) => {
    api.registerCommand(packCommand);
    loader = api.getLoader();
    createIsolatedEnv = api.createIsolatedEnv;
  }
};

module.exports = Pack;
```

**Comment by GiladShoham** [comment]
```js
const Pack = {
  init: ({ api }: { api: any }) => {
    api.registerCommand(packCommand);
    loader = api.getLoader();
    createIsolatedEnv = api.createIsolatedEnv;
  }
};
```
This part might break.
You might have to register the command in another way.
Also, the api.createIsolatedEnv will be replaced by a new technology called a capsule.
Which provides much better isolation. 
Also the general structure might need a change.
It should look something like this:
see this branch:
https://github.com/teambit/bit/tree/harmony/pack-new-capsule
specifically those files:
https://github.com/teambit/bit/blob/harmony/pack-new-capsule/src/extensions/pack/pack.provider.ts
https://github.com/teambit/bit/blob/fd8fa99fd966d984e19860f7d2dddd17124cf143/src/extensions/pack/pack.cmd.tsx
https://github.com/teambit/bit/blob/fd8fa99fd966d984e19860f7d2dddd17124cf143/src/extensions/pack/pack.tsx

**Comment by itaymendel** [comment]
supported in v15 for bit

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
