### ISSUE TITLE
vue compiler and vuetify components not rendering

### ISSUE THREAD

**Issue by lexicalninja** [teambit/bit#2055]
I am using the vuetify framework for my project and when I upload a component to bit, it builds successfully, but when I look at the preview, it appears to not know the custom vuetify tags and renders incorrectly. 

Here is the component:
```typescript
<template>
  <v-form dark>
    <v-container>
      <v-text-field v-model.trim="email" label="E-mail" required outlined type="email" :error-messages="emailErrors">
      </v-text-field>
      <v-text-field v-model.trim="password" label="Password" required type="password" outlined
                    :error-messages="passwordErrors" @keyup.enter="validate"></v-text-field>
      <v-btn @click="clear()" dark>clear</v-btn>
      <v-btn @click="validate" color="primary" :loading="loading" :disabled="loading">
        submit
        <span slot="loader" class="custom-loader">
        <v-icon light>cached</v-icon>
      </span>
      </v-btn>
    </v-container>
  </v-form>
</template>

<script lang="ts">
  import Component from "vue-class-component"
  import Vue from 'vue'
  import {email, minLength, required} from 'vuelidate/lib/validators'
  import {validationMixin} from "vuelidate"
  import * as firebase from "firebase"
  // //@ts-ignore
  // import {swal} from 'vue-swal/src/index'

  @Component({
    mixins: [validationMixin],
    validations: {
      email: {required, email},
      password: {required, minLength: minLength(8)}
    }
  })
  export default class LoginForm extends Vue {
    private email: string = ''
    private password: string = ''
    private loading: boolean = false

    get emailErrors(): string[] {
      const errors: string[] = []
      if (!this.$v.email.$dirty) return errors
      !this.$v.email.email && errors.push('Must be valid e-mail')
      !this.$v.email.required && errors.push('E-mail is required')
      return errors
    }

    get passwordErrors(): string[] {
      const errors: string[] = []
      if (!this.$v.password.$error) return errors
      !this.$v.password.required && errors.push('Password is required')
      !this.$v.password.minLength && errors.push('Password must be at least 8 characters')
      return errors
    }

    validate() {
      this.$v.$touch()
      if (!this.$v.$invalid) {
        this.login()
      } else {
        this.$emit('validationError')
      }
    }

    clear() {
      this.email = ''
      this.password = ''
      this.$v.$reset()
    }

    login() {
      this.loading = true
      firebase.auth().signInWithEmailAndPassword(this.email, this.password)
      .then(_ => this.$emit('loginSuccess'))
      .catch(e => {
        this.$emit('loginFail')
        // swal('Problem Logging In', e.message)
      })
      .finally(() => this.loading = false)
    }

    private sendResetEmail() {
      // todo: reset password flow
      // pop up with text area
      // get value and send message
      // show response or error message
    }
  }
</script>

<style scoped lang="scss">

</style>
```
All the imports are in dependencies, but when it renders in the preview this is what you see:
![Screen Shot 2019-10-04 at 11 33 31 AM](https://user-images.githubusercontent.com/7376126/66224207-ef8f2a80-e69a-11e9-9073-6723ec01ad20.png)

At first I thought it was a message in bit, but you can see in the component that the rendered words are actually the names of the icons that are supposed to be used for the vuetify tag.

Vuetify is not in the dependencies for the component on bit, so my assumption is that the problem is based on that fact. 

I have made it public for you to take a look at 
~/lexicalninja/code-inversion/login-form

Please let me know if you need any more info. Thanks in advance.

**Comment by JoshK2** [comment]
Hey @lexicalninja, I think you right and maybe it's because you don't import the component from `vuetify` in the component itself.

**Comment by dasbego** [comment]
It took me a while to figure out why that was happening. it turn out that the bit vue compiler doesnt offer support to handle those vuetify custom tags. You would have to download the compiler yourself, fork it and make your own custom vue compile that will satisfy your needs. I recommend you to check the `vuetify-loader` library since the compiler you'll download is just webpack configuration to process your component and output a JS file.

I've been striggling with this for the last couple of days. I can share the compiler I have so far. https://bit.dev/codiks/bundlers
Still, I haven't been able to make it work in the cloud visualizer of Bit, but my components work normally when I install them in a new project.

**Comment by mathiasselleslach** [comment]
Subscribing!

**Comment by Tallyb** [comment]
To support vuetify on the bit.dev playground it is required to have a dedicated webpack config on the playground. We currently do not support different configurations of the playground.
