### ISSUE TITLE
Angular Compiler

### ISSUE THREAD

**Issue by clemishow** [teambit/bit#2057]
### Describe the bug

Impossible to run the code

### Steps to Reproduce

https://bit.dev/clemishow/neocity/neo-button

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/9325482/66256370-6c9acc80-e78d-11e9-9b42-69c44e99046c.png)

### Specifications

- Bit version: 14.4.0
- Node version: 10.16.1
- npm / yarn version: 6.9.0
- Platform: Angular
- Bit compiler (include version): 0.19.0
- Bit tester (include version): None

**Comment by GiladShoham** [comment]
@clemishow Thanks for reporting this.
Please open this issue under https://github.com/teambit/envs and close the one in this repo.
Thanks.
