### ISSUE TITLE
Building components with styles retains old styles

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2060]
When building the button component in the app, the 'violet' color which is the original color remains in the build artifacts, although the new colors do not contain them. 

clone the repo: 
https://github.com/teambit/angular-components-lib
cd components-lib
run npm install
run bit build. 
search for 'violet' in app/components/button/dist

**Comment by davidfirst** [comment]
This is the same issue as https://github.com/teambit/bit/issues/2024. Fixing that issue, will fix this as well.

**Comment by GiladShoham** [comment]
@davidfirst I'm not sure it's exactly the same. it might be solved by the other one, but I'm not sure. I and @Tallyb saw the one you described in #2024 but we notice another issue as well. Anyway, let's verify this one once #2024 is solved

**Comment by davidfirst** [comment]
@Tallyb , @GiladShoham , I made sure that https://github.com/teambit/bit/pull/2074 fixed it.

To check it yourself, you'll have to first make some changes in the 'button' component, tag it, so then it'll save the extension data into the objects, then, change the color file and build button.

I also made sure that once done, there is no "violent" anymore in the dists.
