### ISSUE TITLE
Duplicate dependencies when added both in code and overrides

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2061]
### Describe the bug

Same Bit component is shown twice, once in dependencies and once in the devDependencies

### Steps to Reproduce

1. create a component comp-a that requires another component comp-b
2. configure the workspace `overrides` as follows:
```
"overrides": {
    "comp-a": {
      "devDependencies": {
        "comp-b": "+"
      }
    }
  }
```
3. run `bit show comp-a`.

You'll see the comp-b as a dependency and also as a devDependency.

### Expected Behavior

The exact behavior needs to be discussed. Obviously, it should not duplicate the dependency.

### Specifications

- Bit version: 14.4.1
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

The issue was reported by a user. (support email).

**Comment by davidfirst** [comment]
In the commit above I made sure to throw an error before saving the component in such an invalid state.

@GiladShoham , we need to decide how Bit should react in this case.
I'd say that most likely the user forgot to add the dependency with minus and only added it with a plus, so maybe we should throw an error saying something like, hi, you added that dependency already in your source files, to change the dependency type, please remove it from one and add it to another.
However, what if these settings are set on the workspace level and some components require that dependency in the code and some do not.
Maybe the best option would be to save the dependency with the type the user set in the overrides and ignore it everywhere else, regardless of the code.

**Comment by GiladShoham** [comment]
@davidfirst I understand your logic here, but on the other hand, make a regular dependency a dev one, it's more dangerous than the other way around. It might break the component in production. Maybe we should take the most strict one (in this case regular one).
Or we might just throw an error telling the user to tell us what to do (either add it with '-' in regular or remove it from the overrides.dev).
@itaymendel @ranm8 would like to hear your opinion here.

**Comment by itaymendel** [comment]
reponing the issue.
needs to talk about it a bit more before this issue is closed.

**Comment by amowu** [comment]
I also encountered this duplicated problem:

```json
"overrides": {
      "*": {
        "devDependencies": {
          "@storybook/addon-a11y": "+",
          "@storybook/addon-actions": "+",
          "@storybook/addon-knobs": "+",
          "@storybook/addon-viewport": "+",
          "@storybook/addons": "+",
          "@storybook/react": "+"
        },
        "peerDependencies": {
          "react": "+",
          "react-dom": "+"
        }
      }
    }
```

![CleanShot 2020-08-18 at 12 28 07@2x](https://user-images.githubusercontent.com/559351/90470646-96af7000-e14e-11ea-8428-1e028087d549.png)

**Comment by itaymendel** [comment]
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
