### ISSUE TITLE
Add serve command to CLI

### ISSUE THREAD

**Issue by klarkc** [teambit/bit#2062]
### Description

I am suffering to debug errors in component playground because it has not source maps attached with it. Would be nice to be able to reproduce the playground in my local machine with built files for debugging.

### Describe the solution you'd like

First, the build command should also build sourceMaps. Then CLI `serve` (or similar) should open the browser with a draft and built files.

### Describe alternatives you've considered

I've tried to debug dist files in my browser (manually creating a HTML that uses it), but I think maybe it's not es5 compliant (?) because I received a "require" error.

### Additional context

Nothing relevant

**Comment by GiladShoham** [comment]
@klarkc Thanks for this.
Regarding building source maps, that's a compiler-specific issue. (most compilers already generate source files), but if there are compilers that don't generate them, please open an issue about it under https://github.com/teambit/envs.
Regarding having a way to locally run the playground, I already start working on such an extension to bit. But it will take some time to complete. Anyway, that's definitely on our roadmap, (with a very high priority).

**Comment by itaymendel** [comment]
compilation process for components is updated in v15 and playground has moved to a local feature

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
