### ISSUE TITLE
bit.dev with angular, change imported class name

### ISSUE THREAD

**Issue by rbalet** [teambit/bit#2064]
### Description
Actualy, when publishing an angular component, it auto import the module like that
```ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { AppComponent } from './app.component';
import  ComponentName  from '@bit/name.collection.component';

@NgModule({
	declarations: [
		AppComponent,
	],
	imports: [
		BrowserModule,
		ComponentName
	],
	providers: [],
	bootstrap: [AppComponent]
})
export class AppModule { }
```

### Describe the solution you'd like
Would make more sense to import the module with the following name  

import  **{** ComponentName**Module }** from '@bit/name.collection.component';

since it's an angular standard to name the module like that

**Comment by KutnerUri** [comment]
@rbalet - I don't understand, the Template Generator for Angular seems to already use ```import { UiAwesomeButtonModule } from '@bit/bit.ui.awesome.buttons```.

Can you show a screenshot with some context?

**Comment by rbalet** [comment]
Well, I'll try to explain as good as possible what I'm doing.
1. generating a new component with his module inside shared/vendors/ultrastark.fragments/test (with ng g)  
![image](https://user-images.githubusercontent.com/44493964/67262623-cbf31f00-f4a5-11e9-9788-734d0ba0e8e4.png)

2. exporting the component  
![image](https://user-images.githubusercontent.com/44493964/67262645-dd3c2b80-f4a5-11e9-9269-f93a2585c694.png)

3. Tacking the component with his test file (I'm tracking here, every component inside the ultrastark.fragments folder, even if I have one component, it's juste my snippets that I always use)  
```shell
bit add src/app/shared/vendors/ultrastark.fragments/*/ --main src/app/shared/vendors/ultrastark.fragments/{PARENT}/{PARENT}.module.ts --tests src/app/shared/vendors/ultrastark.fragments/{PARENT}/{PARENT}.component.spec.ts
```
4. tag all component, export it
```shell
bit tag --all
bit export ultrastark.fragments
```

5. Opening the bit.dev website (it's an private scope) and there, I have to change the 
`import Test from '@bit/ultrastark.fragments.test';`
to
`import {TestModule} from '@bit/ultrastark.fragments.test';`
![image](https://user-images.githubusercontent.com/44493964/67262881-9bf84b80-f4a6-11e9-8ba4-46ac3adb7a01.png)

I hope it will help.

**Comment by KutnerUri** [comment]
OK! I reproduced it.
production is still using an old version of the code. :(
Will fix today!

**Comment by KutnerUri** [comment]
updated, please try :)

**Comment by rbalet** [comment]
@KutnerUri I'll try the next time I upload a new component. Thx a lot
