### ISSUE TITLE
Option to skip auto-tag in `bit tag` command

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#2066]
### Description

I suggest to have an option for `bit tag` command, that allows you to tag only the component, you specified, and not tagging components, that depends on this one. 

### Describe the solution you'd like

I think, it could look something like: `bit tag my-component --ignore-dependants` or `bit tag my-component -D`

### Additional context

I found myself running `bit untag` command quite frequently for these auto-tagged dependencies, cause, they might not be in the state I wanted to tag yet.

**Comment by davidfirst** [comment]
@DeyLak , sounds like a legit use-case. In fact, I came across a similar case myself recently.
I suggest `--skip-auto-tag` for this feature. @GiladShoham , @itaymendel ?

**Comment by GiladShoham** [comment]
I and @itaymendel  or @ranm8 spoke about it few weeks ago.
I definitely think we should add this.

**Comment by davidfirst** [comment]
Implemented. The new flag name is `--skip-auto-tag`.

**Comment by itaymendel** [comment]
Hi @DeyLak ,

Can you please describe the workflow that caused you to the `untag` for the auto-tag, and why would you want to skip the auto-tag mechanism?

For now, I suggest we'll introduce the feature as `experimental`, as I would want to try and play with it and see how it feels. I think that a better approach would be to (a) improve control of the component's dependency graph and (b) improve control of component changes.

**Comment by DeyLak** [comment]
@itaymendel My workflow is something like this:
0. I have workspace with components A and B 
1. I'm working on component A
2. Changes in component A requires changes in component B(dependency of component A)
3. I change component B and tag it. This causes component A to be tagged automatically.
4. Interesting behaviour(don't know, if this is intended to work like this) that component A is only tagged with the new version of component B, but not with my code changes, so it is still shown as modified in `bit status`
5. I don't want that in-between version to occur, it might be even broken(if changes in comp B is breaking changes)
6. I untag comp A and continue my work on it
7. I tag comp A, when it's ready

**Comment by GiladShoham** [comment]
@DeyLak Just a side note about number 4 - 
This is by design. The auto tag will only tag the dependency change (the rationale - we don't know if your changes in the source code are related or not, and if they are ready to be tagged or not).
however if they are related and ready, you can tag a and b together (or tag --all), this will result tagging the dependency changes along with the source code changes of A).
(I'll make sure to add something about it in the docs)

**Comment by itaymendel** [comment]
@DeyLak , so you still want Component B to depend on the new version of Component A?

For example, Componet A was in version 1.0.0 and you have tagged a new version - 1.1.0.
In this case - which version of Component A should Component B should depend on?

**Comment by DeyLak** [comment]
@itaymendel Comp B is a dependency of Comp A, not vice versa. 
Here is my example with versions:
1. CompA@1.0.0 depends on CompB@1.0.0
2. Tag CompB@1.1.0 -> auto tag CompA@1.0.1 (with dependency of CompB1.1.0)
3. Untag CompA
4. Work on CompA with dependency of CompB@1.1.0 and tag CompA@1.1.0

**Comment by itaymendel** [comment]
resovled in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
