### ISSUE TITLE
Support react fragments

### ISSUE THREAD

**Issue by elstr** [teambit/bit#2072]
### Description
When using react fragments as `<>` `</>` and running `bit status` you get an `Unexpected token` error. 
After changing all fragments to `div` tags the error is solved. 
I'm using bit version 14.4.1

### Describe the solution you'd like
Would be useful to be able to use the latest react features 😃

**Comment by davidfirst** [comment]
It happened due to an old version of the `module-definition` package required by bit-javascript. This package required babel@6.x, which doesn't support React fragments.
Fixed by updating that package and many more.
