### ISSUE TITLE
The component X does not contain a main file. - .ts files

### ISSUE THREAD

**Issue by patryk-janik** [teambit/bit#2085]
### Describe the bug

1. I'm running `bit add src/components/Alert/ --main index.ts` command to add my new component written in ts.
2.  My file srtucture looks like:
![image](https://user-images.githubusercontent.com/54390399/67472891-144f4000-f652-11e9-92e1-b9f3c50ac882.png)
3. I'm running this command from main directory and get error:
> error: the component alert does not contain a main file.
> please either use --id to group all added files as one component or use our DSL to define the main file dynamically.
> see troubleshooting at https://docs.bit.dev/docs/isolating-and-tracking-components.html#define-a-components-main-file

The strange think is, when I add index.js file everything is working fine for `--main index.js` ...

### Expected Behavior

Adding component with main file even the extension is .ts

### Specifications

- Bit version: 14.4.0
- Node version: 10.13.0
- npm / yarn version:  yarn - 1.15.2
- Platform: Windows (🙃)
- Bit compiler (include version): own compiler
- Bit tester (include version): no tester

### Additional Context ###
Tries also this:
`bit add src/components/Alert/ --main src/components/Alert/index.ts`
or
`bit add src/components/Alert/ --main src/components/{PARENT}/index.ts`
The same result.

**Comment by GiladShoham** [comment]
@patryk-janik Thanks for reporting this.

I have just created the exact same structure and run the first command you mentioned (`bit add src/components/Alert/ --main index.ts`) and it worked just fine.

![image](https://user-images.githubusercontent.com/3840769/67632791-02b7a380-f8b1-11e9-9e52-47f123954bb3.png)

Can you try upgrade bit to the latest version (14.4.2)?
Did you got the error during the `bit add` command or maybe during `bit build`?

If you can help me reproduce it, it will be great.

**Comment by patryk-janik** [comment]
I got errors with bit add. I've solved it by manually removing animation component from .bitmap.

**Comment by GiladShoham** [comment]
If you try now to re-add the animation component, does everything works fine?

**Comment by patryk-janik** [comment]
Now yes, but I had to remove it manually from /bitmap file.

**Comment by GiladShoham** [comment]
@patryk-janik I'm glad to hear it's now working.
Is there any chance you can help me reproduce it? 
Thanks.

**Comment by mykeels** [comment]
I think the error message should be made to reflect the conflict. I also had to remove the changes made to the .bitmap file to get the `bit add ...` command to work.

**Comment by GiladShoham** [comment]
@mykeels what conflict do you mean?

**Comment by mykeels** [comment]
I mean the one described by @patryk-janik 

It seems the error happens when the file is already being tracked in the .bitmap file. 

The error message can reflect that conflict, and suggest to the user, how to proceed

**Comment by GiladShoham** [comment]
@mykeels Is there a chance you changed a file name from a capital case to lower case or something like this (even only one letter in the file name?)?

**Comment by itaymendel** [comment]
flow for tracking components updated for v15, and resolved this issue.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
