### ISSUE TITLE
bit export --all does not export components tagged on another machine

### ISSUE THREAD

**Issue by jeremy-ellis-tech** [teambit/bit#2088]
### Describe the bug

Trying to export a component that was tagged on another machine (but not exported from that machine) as part of our CI with `bit export --all`. However, I'm told there is `nothing to export`.

### Steps to Reproduce
On Machine A
1. Clone a git repo with existing bit component and .bitmap files. For example the bit component is currently tagged at 0.0.1.
1. Make a change to your component
1. `bit tag` your component to 0.0.2 (Without running `bit export` on this machine!)
1. git commit and push your repo, along with your component & .bitmap etc., to your CI (gitlab-ci in our case)

On CI Machine
1. `git clone repo`
1. `bit config set analytics_reporting false`
1. `bit config set error_reporting false`
1. `bit config set user.token "$BIT_TOKEN"`
1. `bit export --all

### Expected Behavior

I expect `bit export --all` on the CI machine to return "exported the following 1 component(s):...". Instead I get a message saying: `nothing to export`.

### Screenshots, exceptions and logs

Not applicable

### Specifications

- Bit version: Both Machines: 14.4.2
- Node version: Machine A: v12.13.0, CI Machine: from node 13.0.1-alpine docker image
- npm / yarn version: Both Machines: v6.12.0
- Platform: Linux (various).
- Bit compiler (include version): Angular 0.2.0
- Bit tester (include version): Angular 0.2.0

### Additional context

None

**Comment by davidfirst** [comment]
Hi @jeremy-ellis-tech ,
You'll probably want to tag on the CI, not locally. 
See the following tutorial for a complete workflow using CI https://docs.bit.dev/docs/tutorials/bit-nodejs-tutorial#bit-ci-automation.

Because you tagged the components locally, from the CI perspective, the components are not staged, they're just modified.  That's why it shows as if there are no components to export.

**Comment by GiladShoham** [comment]
@jeremy-ellis-tech Just some update about this - we are working at the moment on a much better workflow for such cases, it's one of the main focus of our team right now.
At the moment, I would go with @davidfirst suggestion to tag in the CI as described in the link @davidfirst mentioned.

**Comment by jeremy-ellis-tech** [comment]
@davidfirst I understand that the components are not staged, but `bit export --help` tells me: ` -a, --all                   export all components include non-staged`. This would imply the components should be exported on the CI machine with `-a`, despite not being staged on that machine.

@GiladShoham Thanks for the response. Looking forward to the solution your team comes up with.

**Comment by davidfirst** [comment]
@jeremy-ellis-tech , that's correct, however, in your case, the CI doesn't know about your local tag. So, although you used `--all` flag, it sents to the remote server the tags you already exported before, which doesn't help you.
The `--all` flag is helpful when forking components, in which case, you want all components including non-staged ones to be exported to a different collection.

**Comment by jeremy-ellis-tech** [comment]
@davidfirst Thanks for explaining.
