### ISSUE TITLE
bit eject did not replace the component with the npm package

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2090]
### Describe the bug
after importing a component I ejected it and I cant see it in the node_modules

### Steps to Reproduce

1. import a component
2. run `bit eject` on the component
3. when I run the project the component is unresolved
4. running `yarn` did not install the component

### Expected Behavior

bit should switch the imported component with the npm package

### Specifications

- Bit version: 14.4.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos

**Comment by odedre** [comment]
deleting the `yarn.lock` file resolved the issue. I believe that deleting the `node_modules` would've resolved the issue as well

**Comment by GiladShoham** [comment]
A few more notes - Bit added the component into the package.json, then ran Yarn at that folder.
For some reason, Yarn didn't installed the package.
(Running yarn manually didn't install it as well until removing the yarn.lock).
It looks like a bug in Yarn.
