### ISSUE TITLE
Bit test is not showing details about testing

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2091]
### Describe the bug

I have a component tested with Jest, and when I run the test with bit, the test is passed but is not printing details about the tests.

### Steps to Reproduce

1. Import the [component](https://bit.dev/joshk/create-react-components-library/alert).
2. Run `bit test alert`.

### Expected Behavior

I expect to see details about the tests.

### Screenshots, exceptions and logs

This is what I see after the test is running.
![image](https://user-images.githubusercontent.com/35892475/67636563-ad908780-f8da-11e9-899f-004d6033b80a.png)

### Specifications

- Bit version: 14.4.3
- Node version: 12.7.0
- yarn version: 1.15.2
- Platform: macOS
- Bit compiler (include version): bit.envs/compilers/typescript@3.0.35
- Bit tester (include version): bit.envs/testers/jest@22.4.3

**Comment by davidfirst** [comment]
This is probably the same issue as https://github.com/teambit/bit.envs/issues/32.

**Comment by GiladShoham** [comment]
@davidfirst it might be, but I don't think so. it doesn't hang, it just doesn't print the output (by the way if you test it with other components it will pass).

**Comment by davidfirst** [comment]
@GiladShoham , Oh ok, it wasn't clear from the screenshot. So, it's not related.

**Comment by GiladShoham** [comment]
This is a bug in the ts compiler (as well as react-ts / angular)
more here - https://github.com/teambit/envs/issues/10

**Comment by itaymendel** [comment]
resolved as part fo v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
