### ISSUE TITLE
Flexiable distTarget

### ISSUE THREAD

**Issue by qballer** [teambit/bit#2093]
### Description

I'm trying to work in a "mono-repo" mode. All my dist files go the root of the project. Dependencies are nested in project tree, but the running code is up there in the root bubbling up the tree and not down. This works in the consumer environment where the dist and dependencies are at the same layer. 

### Describe the solution you'd like

I would like to determine the distTarget of each component. The goal is to place each component to the appropriate `packages/some-name/dist`

### Describe alternatives you've considered
change the components to imported mode where you can chieve the feature. this is less then optimal because this is the author environment.

### Additional context
https://github.com/teambit/envs

**Comment by ryan-ju** [comment]
Same issue here.  This is still not resolved as bit v14.7.4.

**Comment by davidfirst** [comment]
This is a major issue with the typescript compiler.
With the next major version (no ETA yet), this will be fixed. The dists will be inside the capsules.

**Comment by itaymendel** [comment]
resovled as part of v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
