### ISSUE TITLE
Encoding - Special characters in md files

### ISSUE THREAD

**Issue by dastasoft** [teambit/bit#2094]
The `lang` property of the web app is in `en-US` this may cause encoding errors with special characters even if the md file is set as UTF-8.

Instalación:
![image](https://user-images.githubusercontent.com/45243062/67674141-049a6900-f97c-11e9-9a70-66fface23f49.png)

This may happend too if we try to put documentation in chinese.

**Comment by GiladShoham** [comment]
@KoshiroKun Thanks for reporting this.
Can you share where exactly did you face this issue? Or better a way to reproduce?
Thanks.

**Comment by KoshiroKun** [comment]
Hi @GiladShoham,

In order to reproduce it you must track a `.md` file with special characters. That md will appear on the documentation section of the component.

Try to track a .md file with characters like à ò ì ú é or any character from asian language.

Thanks.

**Comment by GiladShoham** [comment]
Thanks, I'll check this and update.

**Comment by odedre** [comment]
@KoshiroKun can you please share the component?

**Comment by KoshiroKun** [comment]
@odedre https://bit.dev/ancert/my-test-collection/fancy-button

**Comment by stefanlazarevic** [comment]
I am facing same encoding issue with cyrillic alphabet which I want to use in my README.md files to describe components. Unfortunately it is not yet supported and I am getting gibberish output.

**Comment by GiladShoham** [comment]
@guysaar223 This is a backend issue, not frontend one.
This is how the backend send the data.

**Comment by itaymendel** [comment]
resolved already. closing this one.
