### ISSUE TITLE
Expose load/install extension API for extension

### ISSUE THREAD

**Issue by qballer** [teambit/bit#2116]
### Description
There is a need to extend a dev environment via configuration. This means that I would like to extend the environment during run time. The use case is for environment presets where I want the ability to inject a specific set of conflagrations and actions.

### Describe the solution you'd like
Allow a bit extension to consume other extensions via API, more specifically expose load/install extension via terminal API.  

### Describe alternatives you've considered
consume the component via ```npm i``` in runtime. This may be flawed in different use cases.

**Comment by itaymendel** [comment]
irrelevant for v15
