### ISSUE TITLE
Have a dedicated command to show up local-env information

### ISSUE THREAD

**Issue by jamesgeorge007** [teambit/bit#2120]
IMO it would be better to have a dedicated command to show up local-env info which turns out to be helpful while submitting bug reports.

`bit info`

```bash
Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.8.1 - /usr/local/bin/node
    Yarn: 1.17.0-0 - /usr/local/bin/yarn
    npm: 6.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.70
    Firefox: 70.0
  npmGlobalPackages:
    bit: 14.4.4-dev.2
```

**Comment by jamesgeorge007** [comment]
I would be happy to shoot up a PR :+1:

**Comment by GiladShoham** [comment]
You can see most of the relevant data when running `bit doctor`

**Comment by jamesgeorge007** [comment]
`bit doctor` requires to be executed within a bit workspace initialized by `bit init`. Anyways, why reinvent the wheel when there is already an inhouse solution?

**Comment by jamesgeorge007** [comment]
Also, the issue template for bug reports can be updated accordingly. Shall I shoot a PR?

**Comment by GiladShoham** [comment]
> bit doctor requires to be executed within a bit workspace initialized by bit init. Anyways, why reinvent the wheel when there is already an inhouse solution?

We can add a flag that only runs this part of info and print it (which won't require a bit workspace)

> Also, the issue template for bug reports can be updated accordingly. Shall I shoot a PR?

what do you miss in the issue template? 
(we might want to add the compiler / tester info to the doctor output, but it might be a bit complicated since we don't know if the issue is from an imported component with its own compiler/tester or from the workspace itself)

**Comment by itaymendel** [comment]
available as part of v15 with `bit env` command

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
