### ISSUE TITLE
Issue when a test fails during procesing in bit server

### ISSUE THREAD

**Issue by rubenofen** [teambit/bit#2126]
### Description

When a test is failing during the process in bit server, the component appears with red ball as failing...it is OK, but the list of the test show "Skipped" and there aren't a log to know what test is failing or what is the problem.

### Steps to Reproduce

1. Generate a new component with a test file
1. Execute bit test to be sure that the test are working
1. Export the component
1. Check the result in bit.dev

### Expected Behavior

1. the failing test is shown in the test summary
1. In bit.dev there are a log to check the problem with this test

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/18423735/68689459-ac18bd80-0570-11ea-9d93-ed7df3d2a5d9.png)

![image](https://user-images.githubusercontent.com/18423735/68689500-bb980680-0570-11ea-8dab-5bfa7bfcb15d.png)

![image](https://user-images.githubusercontent.com/18423735/68689520-c5216e80-0570-11ea-877e-a3c0c028e837.png)

![image](https://user-images.githubusercontent.com/18423735/68689611-eb470e80-0570-11ea-89be-368d04e5b6a3.png)

### Specifications
bit: 14.4.3
npm: 6.9.0
git: 2.21.0.windows.1
node: 12.1.0

**Comment by GiladShoham** [comment]
We are working on re-structure the entire CI product and implementation.
It will add a lot of new features, and part of this will also provide a clear log and status about what exactly happened.
This issue will be solved as part of this process.
It might take some time, but it's one of our main focuses right now.

**Comment by rubenofen** [comment]
Thank you. I'm glad to hear it.

I love this product :)

**Comment by itaymendel** [comment]
component ci changes in v15 where you can run ci locally and resolve such cases.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
