### ISSUE TITLE
Is there a possibility to turn off component example?

### ISSUE THREAD

**Issue by sarneeh** [teambit/bit#2128]
### Description

I'm mostly using Bit for pure script components, which aren't React components. Unfortunately, Bit is still trying to render it in the playground on the component website. Is there any way to turn it off?

**Comment by itaymendel** [comment]
implemented for bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
