### ISSUE TITLE
Adding ssh remotes tests for circle ci testing

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2131]
Currently, our CI only tests against scope added as an fs remote scopes.
There is a lot of differences in the code between fs remotes and ssh remotes (mostly about serializing data and errors).
The only tests who someway test this are tests against bit.dev server, but they are not enough in terms of coverage.
Also, their purpose are not to test the ssh functionality so they are not optimized for this.
We should have tests run at least nightly (maybe for each PR) that runs all the tests with the ssh remotes.
We already have the option to run tests using this method, but it requires more config in circle to make it work.

**Comment by itaymendel** [comment]
irrelevant for v15 as we moved away from ssh to http
