### ISSUE TITLE
Incorrect update of dependency infos in dependency-resolver.ts

### ISSUE THREAD

**Issue by edmundmaruhn** [teambit/bit#2135]
I stumbled upon this while I was trying to trace back another issue I currently have with dependency resolution. Simply these lines of code are useless this way:

https://github.com/teambit/bit/blob/5a60a41b5db67bba138e107e7c1481a5e3d5a089/src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts#L1130

https://github.com/teambit/bit/blob/5a60a41b5db67bba138e107e7c1481a5e3d5a089/src/consumer/component/dependencies/dependency-resolver/dependencies-resolver.ts#L1135

They have to use `push()` instead of `concat()` like in the updater functions above/below those mentioned above.

You can find this problem directly on the `master` branch.

**Comment by GiladShoham** [comment]
@edmundmaruhn Thanks for reporting this.
You are correct!
Feel free to open a PR for this change.
I believe it should be 
```js
this.issues.missingPackagesDependenciesOnFs[originFile] = this.issues.missingPackagesDependenciesOnFs[originFile].concat(missingPackages); 
```
since push getting a one item and concat get an array.

**Comment by edmundmaruhn** [comment]
@GiladShoham I could also use the spread operator, since it's TypeScript that shouldn't be a problem and also is more elegant:

```TypeScript
this.issues.missingPackagesDependenciesOnFs[originFile].push(...missingPackages);
```

Do you see any reason against this?

**Comment by GiladShoham** [comment]
No, I want to suggest that as well.
