### ISSUE TITLE
link generation breaks when trying to use import X as Y syntax

### ISSUE THREAD

**Issue by qballer** [teambit/bit#2140]
### Describe the bug
Here is a fork for polaris-react - https://github.com/qballer/polaris

The autocomplete component consumes the TextField component and renames TextFiel to BaseTextField. When the compiler runs and isolates it in the capsule the link file is trying to import BaseTextField from TextField - but this export doesn't exist. It's a rename that autocomplete does.

### Steps to Reproduce

0. ```rm -rf /tmp/bit```
1. clone https://github.com/qballer/polaris
2. ```DEBUG=true bit build autocomplete```
----wait---
3. Go over the console.log and find the capsule of autocomplete.
4. go to the capsule folder and you can run tsc directly there to find the faulted link file.

### Expected Behavior
Link generation should export the original exports from the component and not the renamed text.

### Specifications

  bit version   : 14.4.3
  node version  : v12.3.1
  npm version   : 6.12.0
  yarn version  : 1.16.0
  platform      : linux
- Bit compiler (include version): see github repo
- Bit tester (include version): N/A

**Comment by qballer** [comment]
Just to share more context I have the following line of code
```typescript
import { TextField as BaseTextField } from '../../TextField`
```
Which keeps this line in the component and in the import from value creates the following link file
```typescript
import { BaseTextField } from '@bit/TextField`
```
Which breaks. There is no BaseTextField. It was just used by AutoComplete in this way.

**Comment by davidfirst** [comment]
Fixed in bit-javascript, released a new version and pinned it in bit-bin.
