### ISSUE TITLE
After "bit import" of specific component "bit status" gives "unable to find dist/index.js"

### ISSUE THREAD

**Issue by rubenofen** [teambit/bit#2141]
### Description

When a component is imported to a project to change it, it comes with a bug which prevents to change and export it.

This issue could be for this particular component.

### Steps to Reproduce

1. Import aui-icons component
1. do bit status
1. Error message is shown : 
unable to find dist/index.js path in the dependencies relativePaths of ancert.ancert-ui/aui-icons@1.0.9

### Expected Behavior

The component can be changed and exported

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
  bit version   : 14.4.3
  node version  : v12.1.0
  npm version   : 6.9.0
  yarn version  : 1.19.1
  platform      : win32

![image](https://user-images.githubusercontent.com/18423735/69040659-73546a80-09ee-11ea-9d93-0e8902acf95e.png)

**Comment by GiladShoham** [comment]
@rubenofen Can you share the component maybe?
If yes, you can add david@bit.dev and gilad@bit.dev as viewers to the collection.
Thanks.

**Comment by campmedia** [comment]
Any updates on this? I'm getting the same impossible error.

**Comment by campmedia** [comment]
**UPDATE**: So I was able to finally do a `$ bit build` after deleting the dust folder of that component.

**Comment by GiladShoham** [comment]
@campmedia That's a pretty old issue we couldn't reproduce. 
anyway, It shouldn't happen anymore with the new major version that are coming.
