### ISSUE TITLE
impossible to create a component named "version"

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2143]
### Describe the bug

When adding a new component with the name "version", it shows as if the component was added but in fact it was not.

### Steps to Reproduce

1. touch version.js
2. bit add version.js
3. bit status

as you can see, the status doesn't show the component.

### Expected Behavior

Either, we can throw an error upon `bit add`, saying you can't add a component with this name.
Or, a better option, chance the `version` attribute we have on `.bitmap` to something else, like `bit_version` so it won't collide with `version`.

### Specifications

- Bit version: 14.4.4
- Node version: 12
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

It happens because we have a property `version` that saves Bit version.

cc: @GiladShoham

**Comment by GiladShoham** [comment]
yes, I understand why it happens.
But it's a really low priority for now.
