### ISSUE TITLE
bit throws git error  for every command

### ISSUE THREAD

**Issue by amitgilad3** [teambit/bit#2144]
### Describe the bug
after installing bit on my linux  machine every time i run any bit command i get the following error message:
/tmp $ bit init
/bin/sh: git: not found
/bin/sh: git: not found
/bin/sh: git: not found
/bin/sh: git: not found
/bin/sh: git: not found
successfully initialized a bit workspace.
i know the issue is that i don't have git installed but i dont think bit init should be coupled to git 

### Steps to Reproduce

1. install bit on linux machine without git
1. run bit any bit command 
1.

### Expected Behavior
i would expect bit to show maybe a warning if it needs git at installation time or only with commands that need git 

### Screenshots, exceptions and logs

![Screen Shot 2019-11-19 at 11 11 02](https://user-images.githubusercontent.com/7702311/69132840-81bd8780-0abd-11ea-9d0c-bcdea3b470d6.png)

### Specifications

- Bit version: 14.4.3
- Node version: v10.17.0
- npm / yarn version: yarn
- Platform: linux
- Bit compiler (include version):
- Bit tester (include version):

**Comment by jonisar** [comment]
@GiladShoham @davidfirst Is there a status update?

**Comment by davidfirst** [comment]
@jonisar , definitely a bug, but my impression is that it's a low priority. The user will install Git after this error. problem solved. Obviously, we need to throw a descriptive error.

**Comment by GiladShoham** [comment]
yes, it's not very important.
@davidfirst the reason why @amitgilad3 needs it is because he runs bit on a container (capsule), and don't want to install bit which increases the image size by pretty much.

**Comment by davidfirst** [comment]
@GiladShoham , oh , I see, so it's not only about throwing a descriptive error it's also about letting Bit work without Git. 
Just to make sure, in the capsule, no need for "bit diff", "bit checkout", "bit merge", "bit import --merge". correct?

**Comment by GiladShoham** [comment]
Currently no need I think, if they will need it, they will install git as needed:)
