### ISSUE TITLE
Pointing to use different node_modules directory

### ISSUE THREAD

**Issue by patryk-janik** [teambit/bit#2145]
### Describe the bug

I have added `"dependenciesDirectory": "../../node_modules/",` bit option to my package.json to point for additional source of dependencies. I have 2 node_modules directories in my project.
First would be inside of given workspace (normal behavior)
Second is inside of `../../node_modules` - 2 levels above.

### Expected Behavior

I would like to have posibility for pointing where bit should search for additional dependencies.
I don't want to add aliases for about 100 components.

### Screenshots, exceptions and logs

I got such error when using bit status or tag: 

>  missing components (use "bit import" or your package manager to make sure all components are installed):

after adding dependenciesDirectory I got such:

> error: the path "../../node_modules/" of "dependenciesDirectory" in your bit.json or package.json file is invalid.
> please make sure it's not absolute and doesn't contain invalid characters

### Specifications

- Bit version: 14.4.3
- Node version: 10.13.0
- npm / yarn version: 1.15.2 - yarn
- Platform: Windows
- Bit compiler (include version): own (just coppying files)
- Bit tester (include version): no tester used

**Comment by GiladShoham** [comment]
@patryk-janik Thanks for reporting this.
The property you have changed is used for a different purpose. it's about where bit will put dependencies of a component if they are not installed via a package manager. most likely you don't need to have this property at all (it's mostly needed when having your own bit server).
The property you are looking for is the `modulesDirectories` under `resolveModules`
read more about it here - https://docs.bit.dev/docs/conf-bit-json#resolvemodules
I'm not sure you will be able to define there something which is outside your bit workspace.

It will be great if you can share a bit about your project structure so we can learn and improve this use case, and where did you run the `bit init` command, and why not one level up.

**Comment by patryk-janik** [comment]
I have tried `modulesDirectories` too and aliases for single package test. But it is not working properly for path like `../../node_modules`.
Why I need that?
Because I have monorepo with 4 projects inside and 2 bit projects.
4 projects are 4 different applications that have one single configuration and are connected by domain.
2 bit projects are 2 separated bit workspaces.

All it looks like:

-> node_modules
-> packages
  ->  app1
  ->  app2
  ->  app3
  ->  app4 
  ->  bitWorkspace1
  ->  bitWorkspace2

All apps are using common node_modules directory and I would like to point bit to use them too.

**Comment by GiladShoham** [comment]
We have the same structure for our [envs repo](https://github.com/teambit/envs).
We just decide to init bit in the common root.
It might not be a good fit for your case, but I would like to hear why you decided to init bit inside each project rather than outside.
Also, @qballer is the maintainer of the envs repo and might shed some light on his experience.  

@davidfirst @itaymendel I think we should think about a way to support node_modules outside the bit workspace. (maybe only on the same tree, maybe only by turn it on explicitly) what do you think?

**Comment by patryk-janik** [comment]
Because I want to have to separated workspaces for to separated domain purpose.
It means I would like to keep for bitWorkspace1 predefined components type and only those, and also for bitWorkspace2 different type of components.

**Comment by davidfirst** [comment]
@patryk-janik , depends on what you need by this separation. You can keep them somewhat separated by defining different namespaces, then using the `overrides` feature with wildcards.
For example, components that are currently part of bitWorkspace1 will get the namespace workspace1. Effectively, a component `utils/is-array` becomes `workspace1/utils/is-array`. 
Once done, you can configure Bit to use one compiler for `workspace1/*` and another compiler for `workspace2/*`.
Please let us know if this would solve your need for two different Bit workspaces.

**Comment by patryk-janik** [comment]
@davidfirst how would it affect exporting those components to bit registry and displaying those components on bit organization collections?
For now I export them like `bit export organization.collection`. 
And can see those comonents set in a separated collections on bit.dev website.
WillI I have them separated with your approach?

**Comment by patryk-janik** [comment]
Additionally we tag components right now with ignore flag `-i` but our subdependencies are not attached :/

**Comment by GiladShoham** [comment]
@patryk-janik This will not affect the separation on the export. it will be part of the component name actually (which is something you might want or might don't want).
You will be able to export them with glob pattern for example:
`bit export workspace1/* org.collection1`
then
`bit export workspace2/* org.collection2`
if you export all to the same collection, with this approach you will have separation on the could as well.
then you will be able to filter by this namespace on the bit.dev web ui.
You can also import all by namespace:
`bit import org.collection/workspace1/*`
If you export them to different collections, this will make the names a bit longer (which might not be what you want)

**Comment by GiladShoham** [comment]
you can still be able even without the namespace export them to different collection without any problem, but it will be a bit more work since you will have to define the default collection for each component (once). 
if you will have other filtering option (for example one of the projects are all ui components, you will be able to export all of those by name pattern) so it will save some time.

**Comment by pumanitro** [comment]
With namespaces and exporting to a separate collection, I will end up with a component "group" name repeating. E.g. I would have `@bit/organization.collection.namespace.component-name`. Where namespace and collection are the same. But I will use this workaround if I can't tell bit which node_modules it should use.

**Comment by itaymendel** [comment]
import flow updated to be more compatible with node in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
