### ISSUE TITLE
bit eject should keep alphabetized order in package.json

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/bit#2146]
when ejecting a component, the order at package.json changes.
bit writes the entry at the end of package.json,
creating more changes in package.json.

<img width="574" alt="Screen Shot 2019-11-20 at 16 44 10" src="https://user-images.githubusercontent.com/46922515/69248464-0212e400-0bb5-11ea-9982-35c29a7f4ccc.png">

to reproduce:
1. yarn add the component
```yarn add @bit/bit.utils.project.config```
1. ```git stage .```
1. import the component:
```bit import bit.utils/project/config```
1. eject the component:
```bit import bit.utils/project/config```

### expected:
package json should have no changes

### actual:
the dependency for @bit/bit.utils.project.config has moved to the end of the list.

### Specifications:
  bit version   : 14.4.3
  node version  : v12.12.0
  npm version   : 6.11.3
  yarn version  : 1.19.1
  platform      : darwin

**Comment by GiladShoham** [comment]
That correct, we will fix it

**Comment by itaymendel** [comment]
moving away from pakcage.json to workspace.json in v15
