### ISSUE TITLE
getDynamicDependencies returns dependencies which can't be removed

### ISSUE THREAD

**Issue by qballer** [teambit/bit#2147]
## Describe the bug

While using the extension system if a dependency is set by an extension it can't be removed or override. I've tested it before but I guess something broke it. 

### Steps to Reproduce

1. Create a dummy component
1. use react-typescript 3.0.30,  
1. change to typescript 3.1.0, 
4. try and use any feature of bit to remove react as a dependency. 

### Expected Behavior

Overrides should change dependencies. Perhaps changing compilers should change the compiler originating dependencies. This requires further discussion. 

### Specifications

  bit version   : 14.4.3
  node version  : v12.3.1
  npm version   : 6.12.0
  yarn version  : 1.16.0
  platform      : linux

**Comment by davidfirst** [comment]
@qballer , I'm a bit confused, at what step you get `react` as a dependency?
At first, you installed react-typescript as a compiler, not dependency. Then, you switched compiler to typescript. Assuming, you have done it correctly, `bit show` should show the compiler as typescript. No react is in the picture.

**Comment by GiladShoham** [comment]
@davidfirst I saw it also on Amit's component.
I don't think it's really related to the compiler change but I'm not sure.
Anyway, I'll send you in private a workspace to reproduce it easily.
