### ISSUE TITLE
`bit show` on a remote component should show the full name in the component id

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2151]
ran `bit show odedreuveny.example/bla/la -r`
see screenshot for output 

![Screen Shot 2019-11-21 at 4 00 41 PM](https://user-images.githubusercontent.com/15064762/69345317-9cd4f680-0c79-11ea-9b22-5e9fa20042f0.png)

- Bit version: 14.4.3

**Comment by GiladShoham** [comment]
@odedre the full id here is always the same as what you pass to the command..
But I still agree with you.
