### ISSUE TITLE
bit export merge conflict between new component and non existing component with the same name

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2153]
### Steps to Reproduce

1. created component with named  `bla/la`
2. ran `bit export odedreuveny.example`
3. got the following merge conflict:

error: merge conflict occurred when exporting the component(s) odedreuveny.example/bla/la (version(s): 0.0.1) to the remote scope.
to resolve this conflict and merge your remote and local changes, please do the following:
1) bit untag [id] [version]
2) bit import
3) bit checkout [version] [id]
once your changes are merged with the new remote version, please tag and export a new version of the component to the remote scope.

4. component is not visible in the collection in bit.dev
5. bit list does not show the component

### Expected Behavior

should export component

- Bit version: 14.4.3

**Comment by davidfirst** [comment]
It turned out the component does exist. I tagged 2.0.0 and now can import it. It was created on 2019-6-10. The only reason I can see why it didn't show on "bit list" is that the index file was outdated for whatever reason.
@odedre , if you recall what was done to that component back then, maybe we could try to reproduce the issue.

**Comment by GiladShoham** [comment]
The problem is that this is a remote scope on bit.dev. I can't run `bit cc` on a remote scope.
any idea @davidfirst ?

**Comment by davidfirst** [comment]
@GiladShoham , you're right, it's on bit.dev so `bit cc` won't help. It's a good idea to have it as part of `bit list`. 
The only thing is that with `lanes` feature, this index.json file contains not only the components list but also the lanes list, so in case this file is out-of-sync regards the lanes, it won't be intuitive to run it via `bit list`. 
However, I don't have a better idea, so I'm good with `bit list --rebuild-index` or `bit list --ignore-index` or maybe substitute `index` with `cache`. (`--rebuild-cache`).

**Comment by GiladShoham** [comment]
@davidfirst let's hear some other opinions here.
@itaymendel @Tallyb @ranm8 what do you think?
