### ISSUE TITLE
Module not found error when installing component

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2157]
### Describe the bug

I exported `material-ui` to a private collection, and I get the error when installing this component: https://bit.dev/joshk/mtui-t2/button-base/
This is a private collection, I gave permission to @GiladShoham and @davidfirst.

### Steps to Reproduce

Install the component with npm and a flag to ignore scripts:
`npm i @bit/joshk.mtui-t2.button-base --ignore-scripts`

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/35892475/69495860-50d1be00-0ed4-11ea-8304-33ecdbd11a08.png)

### Specifications

- Bit version: 14.5.0
- Node version: 12.7.0
- npm version: 6.10.2
- Platform: macOS

**Comment by GiladShoham** [comment]
This is probably a result of #2158

**Comment by JoshK2** [comment]
The problem was with npm, because I installed the version 0.0.2 of the component and this version is broken.
I install it with the ignore flag and it was saved like this in the package.json, so when I just trying to install with no specific version, it was trying to install the version 0.0.2, and npm clear cache not solved this issue, I solve it by installing with specific version 0.0.3 that is working.
