### ISSUE TITLE
Wrong export member error in React TypeScript project

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2158]
### Describe the bug

I work on `polaris-react` library, and when I build `sheet` component I get an error on wrong export name.
https://github.com/Shopify/polaris-react

### Steps to Reproduce

1. clone the project https://github.com/Shopify/polaris-react and check out to version 4.8.0.
2. init bit and copy the .bitmap file.
[bitmap.txt](https://github.com/teambit/bit/files/3883788/bitmap.txt)
3. past this bit configuration:
```
"bit": {
    "env": {
      "compiler": {
        "bit.envs/compilers/react-typescript@3.1.2": {
          "rawConfig": {
            "tsconfig": {
              "include": [
                "./**/*",
                "./node_modules/@bit/shopify.polaris.polaris-types/react.d.ts"
              ],
              "exclude": [
                "!(node_modules/@bit/shopify.polaris.polaris-types/**/*)",
                ".dependencies",
                "dist"
              ],
              "compilerOptions": {
                "lib": [
                  "dom",
                  "dom.iterable",
                  "es2017",
                  "esnext.asynciterable",
                  "scripthost"
                ]
              }
            }
          }
        }
      }
    },
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm",
    "overrides": {
      "*": {
        "devDependencies": {
          "@types/node": "+",
          "@bit/shopify.polaris.polaris-types": "0.0.1"
        }
      },
      "polaris-types": {
        "env": {
          "compiler": "-"
        },
        "dependencies": {
          "@material-ui/react-transition-group": "^4.2.0",
          "@types/react-transition-group": "^4.2.0"
        }
      }
    }
  }
```
4. import the compiler: `bit import bit.envs/compilers/react-typescript@3.1.2 -c`.
5. run `bit status`, it should be ok.
6. now run `bit isolate` on sheet component to see the wrong name in `components/TrapFocus/index.ts`. Full command: `bit isolate sheet --use-capsule -d /tmp/t1`.
7. You can also run `bit build` with DEBUG flag to see the capsules: `DEBUG=true bit build sheet`.

### Screenshots, exceptions and logs

The error I get:
![image](https://user-images.githubusercontent.com/35892475/69497361-b0d06080-0ee4-11ea-84e1-1e1885df46f1.png)

### Specifications

- Bit version: 14.5.0
- Node version: 12.7.0
- Platform: macOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.2

**Comment by davidfirst** [comment]
@qballer , this is an issue with the ts-compiler. Yet again it returns a different main-dist file randomly.

I worked hours on debugging this, so to not waste your time, please follow these steps:

1. clone the project https://github.com/Shopify/polaris-react 
2. checkout to version v4.8.0.
3. bit init
4. import the compiler: `bit import bit.envs/compilers/react-typescript@3.1.2 -c`
5. copy the .bitmap file attached in steps-to-reproduce above # 2. 
6. paste the bit configuration from steps-to-reproduce above # 3 into the package.json.
7. run `bit status`, it should be ok.
8. optional: put `console.log` in the compiler files to see the main-dist file.
9. run `bit build trap-focus`


Here is a screenshot from my local, see how the first time I got the correct main-dist file `TrapFocus/index.js` but the second time I got the wrong file `Focus/index.js`.


<img width="646" alt="Screen Shot 2019-11-28 at 3 33 51 PM" src="https://user-images.githubusercontent.com/1963573/69830814-84725800-11f4-11ea-8b2d-1f4ad2339164.png">

**Comment by qballer** [comment]
Hey I'm going to publish a compiler which should solve this. The results are random because of two things - bit provides file order in random in conjunction with a bug I have. react-typescript@3.1.11 compiler should solve this.

**Comment by GiladShoham** [comment]
@JoshK2 If the new version solve this issue, please close it

**Comment by JoshK2** [comment]
It's worked.
