### ISSUE TITLE
Env configuration is reset when importing new compiler

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2163]
### Description

I have a special configuration is my env, and when I import a new compiler, all my configuration is reset to default.
My configuration (for example):
```
"compiler": {
        "bit.envs/compilers/react-typescript@3.1.2": {
          "rawConfig": {
            "tsconfig": {
              "compilerOptions": {
                "target": "ES5",
                "module": "CommonJS"
              }
            }
          }
        }
      }
```
After I run bit import on compiler:
`"compiler": "bit.envs/compilers/react-typescript@3.1.6"`

### Describe the solution you'd like

I would like that my configuration will be copied to the new compiler I just imported, maybe only if it's the same compiler ID.

**Comment by GiladShoham** [comment]
Thanks.
That's a bug, I'll fix it

**Comment by patrickcze** [comment]
Also an issue im experiencing which was not a major problem until recently, there is another bug reported that requires importing the compiler twice to get bit build working in our CI. But doing so causes the configuration to be overwritten.
Is there a way to import the compiler without affecting the package.json?

**Comment by GiladShoham** [comment]
This all should be solved in the next major version. 
We don't have an exact ETA at the moment.
As a quick workaround for now, I would recommend import the compiler, then restore the config from git or from local copy
something like
```
copy package.json package.json.backup
import compiler
copy package.json.backup package.json OR restore from git
```

**Comment by JoshK2** [comment]
Hi, it happens when Bit import and run directly the build process and it's happens also on the CI process.
So there is a workaround I use on the CI:
Move your Bit config from “pacakge.sjon” to “bit.json”, and in the CI save the “bit.json” before importing the compiler and then put back the “bit.json”.
```
cp bit.json bit.json.backup
bit import bit.envs/compilers/typescript@3.1.49 -c
cp bit.json.backup bit.json
rm -rf bit.json.backup
```

This is where I use this workaround:
https://github.com/teambit/envs/blob/master/.github/workflows/ci.yaml#L48

**Comment by itaymendel** [comment]
irrelevant for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
