### ISSUE TITLE
Provide dependencies to getDynamicDependencies

### ISSUE THREAD

**Issue by qballer** [teambit/bit#2165]
### Description
I would like to set dependencies according to strategy. This requires I will get the component dependencies in the  getDynamicDependencies funtion. 

### Describe the solution you'd like
Get the components dependencies tree in the getDynamicDependencies, allow the compiler to remove a dependency ( will need feedback on that last part ).

### Describe alternatives you've considered
Read package.json from capsule, but too slow. 
Need to check if I already get this data.  I don't think so.

**Comment by GiladShoham** [comment]
@qballer Thanks.
This won't be an easy change. this changes entirely the extensions life cycle.
The getDynamicDependencies designed originally to be based on the config provided to the extension. that's means, it called during the load phasing of the extension as part of bit load process. It means, that when this function is called there is no actual component at all. that can be changed of course, but it's not an easy one. 
Let's continue to discuss it.
