### ISSUE TITLE
Add *node_modules to gitignore

### ISSUE THREAD

**Issue by rbalet** [teambit/bit#2166]
### Description
on `bit import` the node_module will be taken as added code by my git tool.

### Describe the solution you'd like

Adding an `*node_modules` entry into `.gitignore` if this file exist.  
could be added on a `bit init`

### Describe alternatives you've considered

I add it myself for now

**Comment by GiladShoham** [comment]
@rbalet Thanks for this suggestion.
I'm not sure it's bit responsibility to do this.
What if someone for some reason wants to add node_modules to his git? (maybe node_modules in another place in the project, like fixtures for testing). He won't understand what happened.
Of course, we can provide some configuration to enable / disable this. but in such case I would set the default to not do this. then it's easier to add it to the git ignore than finding about this specific config in bit.

**Comment by rbalet** [comment]
@GiladShoham Thanks for your answer.
Then, maybe the first time a user is running the cli? so we could juste type y/n.  
Because, wanting to have node_module or not are going to be different in every project.

**Comment by GiladShoham** [comment]
we already have an interactive mode for `bit init` (you can try it by running `bit init --interactive`). we might add it there as another step, but I'm not sure it's important enough to add it in such main place.
usually, a user will have it in gitignore already correctly.
in case not, he will notice this pretty fast in the git status after the import and probably know how to fix it easily.
so ask you about it each time it is a bit annoying.

**Comment by itaymendel** [comment]
`node_modules` are an integral part of any javascript project, so when you add Bit to a javascript project there's already a configuration in Git's `.gitignore` file. I don't think that adding Bit to a project should affect such a configuration.

Sorry, but I'm closing this issue, as the decision to track `node_modules` is unrelated to Bit.
I'm afraid that even adding it as a question to `bit init`'s interactive mode might cause more confusion, as usually `node_modules` is already excluded, and I don't think that the introduction of BIt to a project should have any effect on that decision.
