### ISSUE TITLE
Create a docker sample for server

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2168]
Provide a sample for setting up a bit server that is based on a docker.

**Comment by itaymendel** [comment]
something like [this](https://github.com/teambit/bit-docker)?
perhaps it's dated, but it should be easy to fix any issues.

**Comment by Tallyb** [comment]
Gilad need to rework on the dockerfile

**Comment by GiladShoham** [comment]
I have a few small things to do there to make it easier to use

**Comment by itaymendel** [comment]
part of the teambit/bit-docker repo
