### ISSUE TITLE
Bit isolate print [object Object]

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2170]
### Describe the bug

Bit isolate print [object Object] instead of the data he should print.

### Steps to Reproduce

1. Track a component.
2. Run bit isolate `bit isolate sheet --use-capsule -d /tmp/t1`

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.
![image](https://user-images.githubusercontent.com/35892475/70051538-ee667500-15d9-11ea-9b55-3eeb451aaddb.png)

### Specifications

- Bit version: 14.6.0
- Node version: 12.7.0
- Platform: macOS
- Bit compiler (include version): bit.envs/compilers/typescript@3.1.10

**Comment by GiladShoham** [comment]
@JoshK2  It's a small issue, feel free to open a PR about it
