### ISSUE TITLE
bit unable to add a dependency to component using overrides

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2175]
### Describe the bug

While trying to reproduce a bug I encountered an issue where I use `overrides` to add a dependency to a component and Bit fails to do so and prints this error on each interaction:

```
unable to manually add the dependency "react" into "button".
it's not an existing component, nor existing package
```

### Steps to Reproduce

1. clone [this repo](https://github.com/itaymendel/reproduce-overrides-propagate)
1. run `bit init`
1. run `bit status`

### Expected Behavior

The dependencies set in the `overrides`'s `*` section to `button`.

### Specifications

- Bit version: 14.6.0
- Node version: 11.10.0
- npm / yarn version: 6.7.0
- Platform: macos mojave

### Additional context

encountered this issue while trying to reproduce another... so this kindda blocking me from figuring out an issue with `propagate`.

**Comment by GiladShoham** [comment]
This happens when using "+" to add a dependency but this package doesn't exist in the package.json so bit can't resolve the version to add.
