### ISSUE TITLE
Adding propagate causes Bit to say other components that should not be affected are modified.

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2176]
### Describe the bug

When I add `propagate` to a specific component, all components that are affected by the `*` rule gets modified.

### Steps to Reproduce

1. clone [this repo](https://github.com/itaymendel/reproduce-overrides-propagate)
1. `npm i`
1. `bit init`
1. `bit tag -a`
1. Add `"propagate": true` to the specific components `others/tab-navigation` and `utils/datetime`.
1. Run `bit status`
1. see that `button` is modified

### Expected Behavior

only the specific components should be modified.

### Specifications

- Bit version: 14.6.0
- Node version: 11.10.0
- npm / yarn version: 6.7.0
- Platform: macos mojave

**Comment by GiladShoham** [comment]
@itaymendel Thanks, we found the issue, PR will be submitted soon by @davidfirst with e2e tests.

**Comment by davidfirst** [comment]
Thanks @itaymendel for providing easy steps to reproduce!
It's a critical bug that has fixed in the PR above, some more details can be found in the PR.
