### ISSUE TITLE
export a component without a package-lock.json

### ISSUE THREAD

**Issue by gogoyqj** [teambit/bit#2190]
is there a way to export a component without a `package-lock.json`?

usually we don't need a  `package-lock.json` in a npm package.

thank u

**Comment by davidfirst** [comment]
@gogoyqj , not sure I follow. 
`bit export` doesn't exports the `package-lock.json` file. (unless you required this file from your code, which is unlikely).
As part of the `bit import` process, it runs 'npm install', which then NPM generates the `package-lock.json` file. Are you referring to this part?

**Comment by gogoyqj** [comment]
@davidfirst thx
i was mistaken...maybe i should rm `package-lock.json` manually after `bit import`

**Comment by davidfirst** [comment]
@gogoyqj , `npm` has a flag `--no-package-lock` that you can disable writing the `package-lock.json` file.
You can pass this npm flag to bit commands following `--`. 
e.g. `bit import your-component -- --no-package-lock`

**Comment by gogoyqj** [comment]
@davidfirst it works

**Comment by GiladShoham** [comment]
@gogoyqj you can also use the configuration in the workspace config to set this args constantly:
https://docs.bit.dev/docs/conf-bit-json#packagemanagerargs

**Comment by gogoyqj** [comment]
@GiladShoham yeah, that's what i actually did
