### ISSUE TITLE
Command to install all components from a collection

### ISSUE THREAD

**Issue by apollwebservices** [teambit/bit#2193]
Is there a way that we can npm install all the components from a collection instead of having to do this individually?  I read through the documentation and could not find the best practice for how to do this.

We are using the centralized workflow and reuse almost all components in our collection in our projects.  Is the best way to just bit import in the collection and then bit eject them so they are node_modules?

**Comment by GiladShoham** [comment]
@conbracowebservices Hi,
At the moment there is no such option.
It's more complicated than it seems. read more on - https://github.com/teambit/bit/issues/784
I might create a quick bit extension to do this soon. I'll keep you update.
meantime, you can take this script and manipulate it a bit - 
https://gist.github.com/JoshK2/01218140a64de9ed3706e5ea06fcc0b0
you should change the bit import to npm install, and also make some manipulation on the bit ids.
from the bit id - `user.collection/componentName` to the npm id `@bit/user.collection.componentName`.

**Comment by GiladShoham** [comment]
Here, I've created a new version for you that runs npm install.
see it here:
https://gist.github.com/GiladShoham/6955339034fad045b988eeaefb869b8c
