### ISSUE TITLE
wrong resolving component dependency in mono repo structure

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2196]
### Describe the bug

I have a mono repo structure:
```
.
├── bit.json
├── coverage
├── my-comp
│   ├── comp.js
│   ├── node_modules
│   ├── package-lock.json
│   └── package.json
├── node_modules
├── package-lock.json
└── package.json
```
my-comp contains a package.json.
It's an authored component, not an imported one.
similar to - https://github.com/teambit/envs
at the comp.js I'm requiring a component I installed via npm.
at bit status bit, doesn't recognize it and show:
```
> my-comp ...  issues found       
       missing components (use "bit import" or your package manager to make sure all components are installed): 
          my-comp/comp.js -> bit.utils/object/clean
```
This happens both when the component installed and when the component just listed in the package.json inside the component.

### Steps to Reproduce

1. `git clone https://github.com/GiladShoham/missing-comp-bug`
1. `bit status`
1. `cd my-comp && npm i`
1. `bit status`

### Expected Behavior

Resolve the dependency correctly.
I can't add a new dependency.

### Screenshots, exceptions and logs

When the component not installed bit js return it as missing in the tree even though it appears in the package.json so theoretically we can get it from the package.json
(it make some sense since the packaeg.json doesn't contain an exact version necessary, and since it's a bit dep we must have an exact version)
here is the tree in that case:
```
{
    "my-comp/comp.js": {
        "missing": {
            "bits": [
                "@bit/bit.utils.object.clean"
            ]
        }
    },
    "my-comp/package.json": {}
}
```
When it's also installed, bit-js recognize the path correctly, but doesn't resolve the version so it's still appears as missing.

here is the tree:
```
{
    "my-comp/comp.js": {
        "bits": [
            "my-comp/node_modules/@bit/bit.utils.object.clean/dist/src/object/clean.js"
        ]
    },
    "my-comp/package.json": {}
}
```

Install it on the root resolve the issue.

### Specifications

  bit version   : 14.7.1
  node version  : v10.16.0
  npm version   : 6.11.3
  yarn version  : 1.17.3
  platform      : darwin

**Comment by davidfirst** [comment]
Thanks @GiladShoham , for providing easy to reproduce steps :)

When the package is not installed, it makes sense to show it as missing, and that's what happens in general regardless of the mono repo.

The bug was when the package is installed and the reason for the bug is that Bit checks whether the resolved path starts with 'node_modules', which in this case, will always be false as it's a sub-package. The fix above changes this and to check whether 'node_modules' includes in the path.
