### ISSUE TITLE
bit remove should not break by dependencies in bulk mode

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2204]
I have 3 components:
```
ab -> a, b
a
b
```

I want to delete all 3, so I run:
```bit remove --remote kutner.temp/a kutner.temp/b kutner.temp/ab```

and I am getting this error:
```
error: unable to delete kutner.temp/a, because the following components depend on it:
kutner.temp/ab

error: unable to delete kutner.temp/b, because the following components depend on it:
kutner.temp/ab
```

This is weird because the dependency will not longer exist after deleting the components.  
Specifically, this will prevent removal of components that co-depend on each other.

### Possible solutions:
* Make remove operation bulk and atomic.
* Optimize removal to delete dependants first.

### Reference
  bit version   : 14.4.3
  node version  : v12.12.0
  npm version   : 6.13.4
  yarn version  : 1.19.1
  platform      : darwin

**Comment by GiladShoham** [comment]
@KutnerUri You are right, we should handle this.
