### ISSUE TITLE
bit watch stops working if the component gets an exception

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2208]
I have a tsx component that I added using `bit add`.
When I use `bit watch` and get an exception, bit watch stops working and I have to start it again every time I get an exception.

### Steps to Reproduce
I have the following component:
```js
const Animation = (props: AnimationProps) => {
	const { src, className } = props;
	return (
		<video loop controls muted className={className}>
			<source src={src} type="video/mp4"></source>
		</video>
	);
};
```
1. run `bit add` and `bit build`
2. now that the component is built, change the import for this component to `import Animation from @bit/animation`
3. now run `bit watch`.
4. now add the prop `autoplay` to the `video` tag. This throws an error because it should be `autoPlay`.
5. `bit watch` stops working and I have to re-run it in order to continue development.

### Expected Behavior

`bit watch` shouldn't stop working because it encountered an error.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

![Screen Shot 2019-12-19 at 12 18 50 PM](https://user-images.githubusercontent.com/15064762/71165579-c3c32000-2259-11ea-812b-846eb28f50d8.png)
### Specifications

- Bit version: 14.7.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.23

**Comment by GiladShoham** [comment]
@odedre Thanks for reporting this. it's a bug. we will fix it.

**Comment by itaymendel** [comment]
resolved in v15
