### ISSUE TITLE
Allow importing a component by its npm package name (eg. bit import @bit/foo.bar.baz)

### ISSUE THREAD

**Issue by imsnif** [teambit/bit#2209]
This would greatly improve the general workflow, IMO.

**Comment by GiladShoham** [comment]
@imsnif This is a great feature request. It should be pretty easy to implement. we will handle this.
@davidfirst what do you think?

**Comment by davidfirst** [comment]
Definitely doable. If we allow this syntax for import, it'll make sense to allow it for all commands to be consistent.
If we only allow `@bit/` with this syntax it's relatively easy. Otherwise (supporting custom registries) it gets complicated.

**Comment by GiladShoham** [comment]
@davidfirst I don't think we should support other prefixes.
for now for sure.
later, we might think about it.
as for other commands, yes sure, let's do them all:)

**Comment by itaymendel** [comment]
irrelevant for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
