### ISSUE TITLE
Explicitly annotate when 'overrides' should work for 'imported' components.

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2212]
### Description

When setting up a project that I'm exporting components from there are specific setups I must do to sort some basics ground rules for the dependency graphs and tooling. For most of them, I use the 'overrides' features in Bit's configuration. The thing when I'm using it, it also affects the imported components (since the implementation of this feature #1867 ).

Sadly we've made a mistake in the fix to affect imported components, as we didn't think about the possible side-effects. So for me, whenever I have `*` in my `overrides` setup, every component I import gets modified.

We should keep the ability to control all components, but I would also like to define when I only want to affect the components that are still a part of my project (ie - not ejected using `bit eject` or `bit export --eject`).

### Describe the solution you'd like

Implement a different glob pattern key for the `overrides` section to set when Bit should resolve the component ID from the authored components, and when to include the imported components to that list as well.

```js
"overrides": {
    "*": {...},            // override rules for AUTHOTED components (authored)
    "**": {...},           // override rules for ALL components (authored+imported)
    "**/assets/*": {...}  // override rules for ALL 'assets' (authored+imported)
    "*/utils/*": {}        // override rules for the authored utils components
}
```

> **Note** When no prefix is defined, Bit should assume that the component is authored.

**Comment by davidfirst** [comment]
Yes, we definitely need a way to exclude imported components.
I'm not sure though about the syntax. The double asterisk has a different meaning in shell, it recursively includes subdirectories, which is not the case here.
How about adding a property `excludeImported` or something similar?

**Comment by GiladShoham** [comment]
adding a property is a bit annoying since it pollutes the data itself. it's possible but not very elegant.
we can just replace * with another char if we want. but I think the double * is fine. but I understand your concern.

**Comment by davidfirst** [comment]
we have already Bit props, `propagate`, `exclude`, and `env`. we can have them all with a prefix of `_` or `_bit` or something similar.

**Comment by GiladShoham** [comment]
I see your point.
@itaymendel what do you think?

**Comment by davidfirst** [comment]
I started thinking about how to implement this with the double asterisk and I see more issues in addition to what I described previously.
We currently support having the wildcard in any namespace level. So, for example, you can add a rule of `*/utils/*`, which captures `frontend/utils/is-button` and `backend/utils/is-string`.

Now, we are saying that not only the prefix `*` is authored but also the no-prefix is authored. If this is the case, how do I know whether the `*` prefix is there to capture any first-level namespace or to indicate authored only? 
In the example of `*/utils/*` if a user has two components `frontend/utils/is-button` and `utils/is-string` as authored. Which one matches the criteria?

@itaymendel , @GiladShoham .

**Comment by Tallyb** [comment]
@davidfirst  - `frontend/utils/is-button` and `utils/is-string` does `*/utils/*` applies to both? 
My 2 cents, in general `utils/*` => `*/utils/*`. If you want imported + authored you will need to be explicit with `**/utils/*`

**Comment by davidfirst** [comment]
@Tallyb , currently it works as you would expect. `*/utils/*` applies to `frontend/utils/is-button` only, not to `utils/is-string`.

With the suggestion above, the results are unknown.

**Comment by itaymendel** [comment]
Let's go back to the origins of `overrides` for a sec...

It solved two problems for Bit.

1. Ability to override all automated "stuff" (deps, etc) that extensions (or Bit) attach to components.
2. Ability to control the authored components (ie - components that don't have their own `bit.json`) from a single source.

So the rationale behind the `**` is an ability to tell Bit when to **append** the imported components to get affected by the overrides objects in the `bit.json`. I see why there's confusion in the current `**` decision. The first `*` has nothing to do with either imported/authored components (or any `*` for that matter). To simplify it lets simply change it to `!`:

- `*/utils/*` should affect only the authored components.
- `!*/utils/*` affects the authored components and imported.

> **Note** if anyone wants to affect ONLY imported components, they can `ls | grep` all relevant `bit.json` files and edit.

Some examples:

- `*/utils/*` will match `frontend/utils/is-button` only if it's authored.
- `!*/utils/*` will match `frontend/utils/is-button` anyway.
- `*/utils/*` will not match `utils/is-string`.

**Comment by davidfirst** [comment]
OK, `!` is less confusing than `*`. Still not the best solution IMO as it may be confused with negating the glob pattern.

So, just to make sure we're aligned, I'd continue a few more examples similar to the above:

- `utils/*` will match `utils/is-string` for authored only.
- `!utils/*` will match `utils/is-string` for authored and imported.

@itaymendel , is that correct? how about a different, less confusing character? (if we really want to have a character, seems like I'm not able to convince you guys to have it as a prop).

**Comment by GiladShoham** [comment]
That examples are correct.
Any other symbol on your mind?

**Comment by davidfirst** [comment]
@GiladShoham , Honestly, when I'm thinking about it, with any other symbol it looks weird (and unsearchable). 
I do see the point @itaymendel  mentioned about `*` appends the ids selection. However, if we take `*` off the list, maybe there is no point to use a symbol.
