### ISSUE TITLE
Dependencies mess

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2217]
### Describe the bug

Dependencies are not consistent between show and diff
Overrides is not working
more

### Steps to Reproduce

1. import kutner.temp/hook-test 
1. `bit show hook-test`, you will see:
```
react-dom@^16.11.0
react@^16.11.0
@types/react@16.9.11
@types/react-dom@16.9.4
```
1. look at package.json you will see:

```
"overrides": {
      "dependencies": {
        "react": "-"
      },
      "peerDependencies": {
        "react": "^16.9.0",
        "react-dom": "^16.9.0"
      }
    }
```
and
```
"peerDependencies": {
    "react-dom": "^16.11.0",
    "react": "^16.11.0",
    "@types/react": "16.9.11",
    "@types/react-dom": "16.9.4"
  },
```
1. it's imported component, how the peer deps different from the overrides? (first bug)
1. so let's try to figure out what matters. I saw in bit show react 16.11.0 so i guess change the peer deps to 16.11.1 will do the job. change it.
1. run `bit show` and `bit diff` 
1. nothing modified.
1. let's try to change the overrides from 16.9.0 to 16.9.1 
1. yes component is not modified
1. run `bit diff`, getting:
```
--- Overrides Peer Dependencies (0.0.12 original)
+++ Overrides Peer Dependencies (0.0.12 modified)
- [ react@^16.9.0, react-dom@^16.9.0 ]
+ [ react@^16.9.1, react-dom@^16.9.0 ]
```
1. wait, so the real peer dep (on the imported version) is 16.9.0 or 16.11.0? (another bug)
1. let's try to run `bit show hook-test --compare` 
1. getting the same deps in both 0.0.12 and 0.0.12 [file system]. so are we modified or not? (another bug)
1. let's check the real object by `bit cat-component kutner.temp/hook-test@0.0.12`
1. on the peer I see 16.9.0
1. this is a forked component forked by a user component - ofek.catdog/hook-test (in v0.0.11)
1. let's create a new empty folder and import the original component `bit import ofek.catdog/hook-test`
1. run bit status 
1. comonent is modified.. how? I just import it (another bug)
1. run bit diff
1. see 
```
-----------------------------------------------
showing diff for ofek.catdog/hook-test
-----------------------------------------------

--- Dependencies (0.0.11 original)
+++ Dependencies (0.0.11 modified)
- [ @types/react@^16.9.16 ]
+ [  ]
```
1. wait, what happened to my @types/react dep? I changed nothing.. 

### Specifications

bit version   : 14.7.1
  node version  : v10.16.0
  npm version   : 6.11.3
  yarn version  : 1.17.3
  platform      : darwin

**Comment by davidfirst** [comment]
@GiladShoham , I started working on it and stopped somewhere in the middle because I guess the rest are related to the same things.

> it's imported component, how the peer deps different from the overrides? (first bug)

I created a new directory and was running the following:
```
➜   npm i react@^16.9.0 --save
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN bb@1.0.0 No description
npm WARN bb@1.0.0 No repository field.

+ react@16.12.0
added 6 packages from 3 contributors and audited 9 packages in 1.119s
found 0 vulnerabilities

➜   cat package.json
{
  "name": "bb",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^16.12.0"
  }
}
➜  
```
As you can see, installing `^16.9.0` ends up with `^16.12.0` in the `package.json` file.
That's what happens here. The overrides tels you to install react^16.9.0 so you end up in the package.json with `^16.11.0`.

> let's try to change the overrides from 16.9.0 to 16.9.1
> yes component is not modified

It does actually shows as modified:
```
➜  wp bit s
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > hook-test ... ok
➜  wp bit diff hook-test
-----------------------------------------------
showing diff for kutner.temp/hook-test
-----------------------------------------------

--- Overrides Peer Dependencies (0.0.12 original)
+++ Overrides Peer Dependencies (0.0.12 modified)
- [ react@^16.9.0, react-dom@^16.9.0 ]
+ [ react@^16.9.1, react-dom@^16.9.0 ]

➜  wp
```

> wait, so the real peer dep (on the imported version) is 16.9.0 or 16.11.0? (another bug)

It's none. It has a caret. So ^16.9.0 is basically the same as ^16.11.0. both are `^16.*.*`.

I didn't go further, please let me know if I should.

**Comment by itaymendel** [comment]
resolved in v15
