### ISSUE TITLE
add component to package.json when tagging component

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2221]
I am tagging components with bit locally, and sometimes I get this weird message:
```
missing links (use "bit link" to build missing component links): 
          src/playexecute.ts -> kutner.temp/story-types
```

I get why this is happening. At playexecute.ts, I have this dependency:
```tsx
import { ParsedPlayables } from '@bit/kutner.temp.story-types';
```

Since I haven't exported `story-types`, I never added it to the project.
`bit link` solves this by generating link files at `/node_modules/`, pointing to the original folders.
```tsx
//transpiled code
require(@bit/kutner.temp.story-types);
// --> /node_modules/@bit/kutner.temp.story-types
// --> /Users/kutner/Documents/Projects/ilyn/src/components/story-types/index.ts
```

We are doing something similar for `bit import`. It replaces the component version with a `"file: link"`.

```json
 "@bit/kutner.temp.story-types": "file: ./src/components/story-types/index.ts"
```

I think we could do the same when tagging.
* better readability
* complies to yarn and npm.
* might make bit link irrelevant?

### specifications:
  bit version   : 14.7.1
  node version  : v12.12.0
  npm version   : 6.13.4
  yarn version  : 1.19.1
  platform      : darwin

**Comment by GiladShoham** [comment]
This is not exactly about the tag, it's about creating a link for components before the export.
The issue is that we don't know where this component will be exported to, and the scope name is part of the name for the package.
Anyway, it's part of wider produce, we just come up with a design to solve this issue.
It's on the roadmap with high priority, so it should be solved pretty soon.

**Comment by KutnerUri** [comment]
We can use the scopeless name, i.e.
```json
"@bit/story-types": "file: ./src/components/story-types/index.ts"
```

When exporting, bit knows the scope name, so it can be replaced with:
```json
"@bit/kutner.temp.story-types": "file: ./src/components/story-types/index.ts"
```

**Comment by GiladShoham** [comment]
@KutnerUri That's alone is not enough.
What happens to your requires?
you do `require(@bit/story-types)`
Then you export the component and we change it to `@bit/kutner.temp.story-types`
now your require is break
(there are more cases to handle)

**Comment by itaymendel** [comment]
resolved as part of v15
