### ISSUE TITLE
Incorrect link to bit components in the dependencies tab

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2224]
### Describe the bug

I exported a component with dev, peer and normal dependencies added with overrides, and the link is a mix of bit and npm domain, put your mouse on the link to see this.
https://bit.dev/joshk/dev-dep-link-bu/test/~dependencies

As you can see in the screenshot below, dependencies added with overrides are different from dependencies used in the file.

### Expected Behavior

I expect that dependencies added with overrides have a correct link like dependencies used inside the file itself.

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/35892475/71664085-4f5fa500-2d60-11ea-8e12-d1c298824bfd.png)

### Specifications

- Bit version: 14.7.1
- Node version: 12.7.0
- Platform: macOS

**Comment by GiladShoham** [comment]
This issue is because bit treat this as package dep instead of component dep
it should be fixed by - https://github.com/teambit/bit/pull/2222
