### ISSUE TITLE
Give an error or block .exe, .zip, ... files

### ISSUE THREAD

**Issue by rubenofen** [teambit/bit#2229]
### Description

When a .exe is exported inside a component it is exported ok, but since this moment, all depending components and this component gives an error when importing.

The error: "received an invalid response from the remote SSH server."

### Posible solution
When exporting, bit should block or give an error to avoid this kind of error

**Comment by rubenofen** [comment]
Issue related https://github.com/teambit/bit/issues/2199

**Comment by GiladShoham** [comment]
Thanks for reporting this @rubenofen 
We will check it

**Comment by itaymendel** [comment]
import/export improved. it should better support binaries now.
