### ISSUE TITLE
Support for TypeScript version 3.7.x - Optional Chaining error

### ISSUE THREAD

**Issue by CloudPower97** [teambit/bit#2231]
### Describe the bug

I recently moved to `TypeScript` version `3.7.3` mainly because of [`optional chaining operator`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining).

However, it seems that even the `react-typescript` compiler version `3.1.16` released yesterday has some problem with it.

### Steps to Reproduce

1. Install the latest TypeScript version (as of now 3.7.3)
2. Try to use the `optional chaining operator`

### Expected Behavior

It should be possible to use the `optional chaining operator`

### Screenshots, exceptions and logs

```
     > card ...  issues found       
       error found while parsing the file (please edit the file and fix the parsing error): 
          src/components/Card/Filters/index.tsx -> Expression expected.
```
### Specifications

- Bit version: 14.6.0
- Node version: v12.11.1
- yarn version: 1.19.0
- Platform: 5.0.0-37-generic teambit/envs#40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Compiler / Tester (include version): react-typescript@3.1.16 / bit.envs/testers/jest@22.4.3

**Comment by davidfirst** [comment]
Fixed by updating the typescript version of bit-bin and bit-javascript to 3.7.4.
(the reason why typescript dependency is pinned is to avoid the warning 

> WARNING: You are currently running a version of TypeScript which is not officially supported by typescript-eslint-parser

we get from eslint-parser.

Will be part of the next release.
