### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by m-ttriley** [teambit/bit#2236]
### Describe the bug

In attempting to create a Github integration on bit.dev, I'm seeing a typeError in the console and the "Active action" section does not ever load.

### Steps to Reproduce

1. Navigate to your organization's integrations
2. Fill out a Collection / Repository / Target Branch
3. Click "Add"

### Expected Behavior

The new integration populates in the "Active actions" section.

### Screenshots, exceptions and logs

![Screen Shot 2020-01-09 at 4 52 24 PM](https://user-images.githubusercontent.com/11190038/72107965-77bb4680-3300-11ea-8349-8a41acb8bb9f.png)
![Screen Shot 2020-01-09 at 4 52 30 PM](https://user-images.githubusercontent.com/11190038/72107966-77bb4680-3300-11ea-92c1-b4e9d869f6b8.png)

**Comment by GiladShoham** [comment]
Thank @m-ttriley we will check it

**Comment by guysaar223** [comment]
@m-ttriley
Hi sorry for this,  
can you please send me your organization name? 

Guy
guy@bit.dev

**Comment by m-ttriley** [comment]
@guysaar223 just sent you an email with the org name

**Comment by guysaar223** [comment]
fixed :-)
thanks @m-ttriley
