### ISSUE TITLE
should show components when getting permission error

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2237]
I am trying to export a component, but I am getting permission error because of dependency on another account:

```
error: unable to export components to bit.frosting because they have dependencies on components in bitsrc.nodejs.
bit does not allow setting dependencies between components in private collections managed by different owners.
see troubleshooting at https://docs.bit.dev/docs/bit-dev#permissions-for-collections
```

This is an important error, but it does not specify which components have the bad dependency and what components come from another scope.

--> please add specification to the error message, similar to how this is done for `bit status`
Found by odedre

### specifications:
bit version: 14.7.1

**Comment by itaymendel** [comment]
duplicates #2242
