### ISSUE TITLE
bit should recognize scoped npm id's inside @import 

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2239]
### Steps to Reproduce

1. npm install a scss styles file (`npm i @bit/bit.frosting.theme.z-indexes`)
2. import inside a sass file (`@import '~@bit/bit.frosting.theme.z-indexes'`)
3. add sass file to component
4. run bit status

### Expected Behavior

bit should resolve all dependencies

### Screenshots, exceptions and logs
```
missing packages dependencies (use your package manager to make sure all package dependencies are installed): 
          src/components/Theme/floating-container/flavors/flavors.scss -> ~@bit, ~@bit, ~@bit, ~@bit
          src/components/Theme/floating-container/styles.scss -> ~@bit, ~@bit, ~@bit
```
### Specifications

- Bit version: 14.7.1
- Node version: v10.15.3
- npm / yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.frosting/compilers/react-flow

**Comment by GiladShoham** [comment]
@odedre Thanks. it's a bug. we will address it.
