### ISSUE TITLE
it would be nice to get the component id with the error: 'bit doesnt allow dependencies between components in private collections in different owners'

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2242]
### Description
I've tagged a few components, one has a dependency on a private component from a different account than the one I'm exporting to. bit shows an error but doesn't specify which of the components is the problematic one.

```
error: unable to export components to bit.frosting because they have dependencies on components in bitsrc.billing.
bit does not allow setting dependencies between components in private collections managed by different owners.

```

### Describe the solution you'd like
in addition to that error, I would like the id of the problematic component so I dont have to go through all my other components to check

### Describe alternatives you've considered
I looked at the source code and found the issue but it would be really nice if bit could just point you in the right direction

**Comment by GiladShoham** [comment]
the bit.dev server should return this info in order to present it.
@amitgilad3

**Comment by NitsanCohen770** [comment]
Thanks this is resolved now.
