### ISSUE TITLE
React compiler command not working

### ISSUE THREAD

**Issue by roro1000** [teambit/bit#2243]
### Description

I am using bit import bit.envs/compilers/react --compiler using npm but this will not install in my project.

### Specifications

- Bit version: 14.7.2
- Node version:10.15.3
- npm / yarn version:6.4.1
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

Following the tutorial i cannot install the react compiler using the commands stated for npm

bit import bit.envs/compilers/react --compiler

Bit build will not work either

Both commands result in :
Command failed: git config --list
'git' is not recognized as an internal or external command,
operable program or batch file.

**Comment by GiladShoham** [comment]
The git error is a bug we should fix.
Bit loads git during startup to load some configuration.
Just install git on your machine and try again.
