### ISSUE TITLE
Version numbers out of sync

### ISSUE THREAD

**Issue by AlexanderKaran** [teambit/bit#2245]
The version in Bit (bit.dev) for some components is one (0.0.1) increment behind the main version number in the project.

We have recently updated a lot of components in our master project and this has bumped the version number. When you run bit status in our main project you get this:

`
nothing to tag or export (use "bit add <file...>" to track files or directories as components)
`

Now when I go into our new project and update the npm packages to the latest and the run npm install we get issues like this:

```
alexanderkaran@AlexandersMBP2 cc_home_web % npm install
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @bit/climateclever.ui-components.cc-circle-progress-bar@0.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@bit/climateclever.action-overview-page-components.action-costs'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alexanderkaran/.npm/_logs/2020-01-17T03_39_21_673Z-debug.log
alexanderkaran@AlexandersMBP2 cc_home_web % 
```

Doesn't make sense? I go to cc-circle-progress-bar in bit.dev and see the version number is 0.0.2 but when I go back to the main project and check the bit file it reads this:

```
"climateclever.ui-components/cc-circle-progress-bar@0.0.3": {
        "files": [
            {
                "relativePath": "src/components/CCCircleProgressBar/CCCircleProgressBar.css",
                "test": false,
                "name": "CCCircleProgressBar.css"
            },
            {
                "relativePath": "src/components/CCCircleProgressBar/index.js",
                "test": false,
                "name": "index.js"
            }
        ],
        "mainFile": "src/components/CCCircleProgressBar/index.js",
        "trackDir": "src/components/CCCircleProgressBar",
        "origin": "AUTHORED",
        "exported": true
    },
```

No idea how to fix this one and development has stopped on the other two project as I can not run npm install. Is it possible to bump all version numbers in the main project or force all components to export again?

**Comment by AlexanderKaran** [comment]
Running latest version of bit and react compiler

**Comment by GiladShoham** [comment]
That looks like an issue in our side when storing the data for that component for our registry.
Can you please run bit list climateclever.ui-components and see the last version you got there for the progress bar?
If you got 0.0.3 its problem in our side. We will check it anyway.
In case you don't want to wait. You can tag it again (this component only) (you can tag without any changes) and export. This will re-run our sync to have missing versions for the registry and bit.dev.

**Comment by GiladShoham** [comment]
quick update:
Checking it up a bit more, it indeed looks like bit itself has the new version and it's only a sync issue from bit to bit.dev and registry. we will continue checking, and run a re-sync if needed.
We will update the issue accordingingly

**Comment by AlexanderKaran** [comment]
Sorry for the late reply. The issue seems to be for at least 1/3 of our components. Is there a way to tag all components at once with a new version.

**Comment by GiladShoham** [comment]
Update: that was an issue on our side. We still investigating the reason behind this. Meantime we resync your entire collection. Please let us know if you have more issues.

**Comment by AlexanderKaran** [comment]
Could you resync all our collections as there was some issues across more than one?

**Comment by amitgilad3** [comment]
Hi @AlexanderKaran , i resynced all of you collections and started to investigate the reason for your issue. 
i`ll update you once i find the issue.
if you experience this again please let us know

**Comment by AlexanderKaran** [comment]
All our projects are working again now! Thank you.

**Comment by itaymendel** [comment]
@AlexanderKaran , i'm closing the issue, per your last comment.
