### ISSUE TITLE
merge component by recursive strategies

### ISSUE THREAD

**Issue by zeitamin** [teambit/bit#2246]
### Description
I used to share some components between react and react native in a few apps. I used [Git recursive merge strategies](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes#_merge_strategies) to achieve this. first I write a react component that I use. then in other branch, I make it to work in react native too. later, If I make any changes to one of the branch, I'll make a merge to reflect those changes back to other branches too. I need the same effect in Bit to share component in way that two components get updated by new code but be different by usage. 
is there anything similar in Bit? 
example: 
```

$ git checkout -b react
$ echo 'export default props => <span styles={somestyles}>{props.children}</span>' > StyledText.js
$ git checkout -b react-native
$ echo 'export default props => <Text styles={somestyles}>{props.children}</Text>' > StyledText.js

// later I want some new styles to be applied

$ git checkout  react
$ echo 'export default props => <span styles={someNewstyles}>{props.children}</span>' > StyledText.js
$ git merge react-native
$ git checkout react-native
cat StyledText.js
export default props => <Text styles={someNewstyles}>{props.children}</Text>
```

**Comment by GiladShoham** [comment]
Great question.
As a thumb rule, I would recommend to extract the share code into its own component and create 2 other components that are specific to react / react-native and using the shared component.
That's is not directly related to bit, it will probably make your code better and reduce duplications.
The way to do it depends on the actual code of the components.
In some cases, you can create a base component that might not be even a react components, but just exporting some consts (like styles, class names, props etc)
In more complicated cases, I would create a base component which is a react component. that exposes the base functionality and structure.
Then either:
1. create a HIC component that uses the base component and exposes a platform prop and according to the platform modifies the base component. 
Then you can (but not have to) create another 2 comps that just pass an actual platform to the HIC, and expose the other base props. (those are 2 concrete components)
2. Create 2 components, that use the base component and know to modify it according to the platform. 
That is similar to the previous one but without the HIC layer. 
It's 2 components that knows to transform the base into an actual platform.
The downside with this is that the transformation function might have duplicate code between the 2 components (this duplicate code should be in the HIC in the previous example)
the upside is that it will probably be more easy to implement.

I would recommend, asking that kind of question in the [react channel](https://bit-dev-community.slack.com/archives/CNSFZ56UB) in the community slack.
