### ISSUE TITLE
bit does not allow to add a file - warning: no files to add, the following files were ignored:

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2253]
### Description
I wanted to add a file to bit.
I added it and got the following warning:
```
warning: no files to add, the following files were ignored: config/development.js
```

after some checking, I saw that the file could not be added because it was in the .gitignore file.

Please update the error to suggest checking the .gitignore file.

something like: 
```
warning: no files to add, the following files were ignored: config/development.js
try checking the .gitignore to see if this file is ignored on purpose.
```
### Specifications

Bit version: 14.7.2
Node version: v10.15.3
yarn version: 1.13.0
Platform: macos
Bit compiler (include version): bit.web/compilers/react-flow@0.0.5

**Comment by GiladShoham** [comment]
I agree.
@Tallyb can you help me rephrase this error (with a link to - https://docs.bit.dev/docs/add-and-isolate-components.html#ignore-files)

**Comment by Tallyb** [comment]
No files to add. The following files were added but they are ignored by Git and are also ignored by Bit:  <file a><file b>

**Comment by GiladShoham** [comment]
@Tallyb We don't really know if it was ignored by git, or it's part of the default ignored files. or it was excluded in the add command (we can implement this check of course, but I don't think it worth it now. just point the user to a place that explains him what to check)

**Comment by Tallyb** [comment]
what are the possibilities of the file to be excluded?

**Comment by Tallyb** [comment]
Why they can be ignored then?

**Comment by davidfirst** [comment]
@Tallyb , According to the code, seems like the following are ignored:
1. .gitignore.
2. dists of the imported components.
3. "configDir". (this is related to an unused feature where you can set a specific config directory and bit.json will be written into that dir).
4. our constant IGNORE_LIST:
```
export const IGNORE_LIST = [
  '**/.bit.map.json',
  '**/.bitmap',
  '**/.gitignore',
  '**/bit.json',
  '**/bitBindings.js',
  '**/node_modules/**',
  '**/package-lock.json',
  '**/yarn.lock',
  '**/LICENSE'
];
```

**Comment by GiladShoham** [comment]
I think we should add all the list @davidfirst mentioned to the docs.
Then write a message which says something like this (draft) 
```
no files to add, the following files were ignored: config/development.js  
This can be a result of the files ignored by git.  
Read more about ignored files here - link
```
@Tallyb

**Comment by Tallyb** [comment]
no files to add, the following files were ignored: config/development.js .  Read more about ignored files here:  https://docs.bit.dev/docs/add-and-isolate-components#ignore-files

**Comment by itaymendel** [comment]
in v15, adding a file only requires you to create a new file in your component's dir

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
