### ISSUE TITLE
Components with missing packages are treated as modified

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2261]
### Describe the bug
When importing a component without installing its packages, "bit status" shows the component as modified and also shows the issues the component has with the missing packages.
Then, when running `bit tag --all`, it tags the component.
The problem is that the user doesn't expect this imported component to be tagged as there was no changes to the component. 

### Steps to Reproduce
1. import a component with --skip-npm-install
1. run `bit tag -a`
watch the imported component tagged.

### Expected Behavior
The component should not be shown as modified.
As a result, the component won't be tagged when using `--all` flag.

### Specifications
* Bit version: 14.7.2

**Comment by itaymendel** [comment]
no longer relevant. `bit tag` throws the following error in this case:

```
error: issues found with the following components

teambit.design/navigation/content-tabs@0.0.6
       
       missing packages or links from node_modules to the source (run "bit install" to fix both issues. if it's an external package, make sure it's added as a package dependency): 
          content-tabs.spec.tsx -> @testing-library/react
          content-tabs.tsx -> react, @teambit/design.navigation.responsive-navbar
       missing packages that were manually set (run "bit install"): 
          core-js, @types/node, @types/react, @types/react-dom, @types/jest, @babel/runtime, @types/testing-library__jest-dom


to get the list of component-issues names and suggestions how to resolve them, run "bit component-issues".

while highly not recommended, it's possible to ignore issues in two ways:
1) temporarily ignore for this tag/snap command by entering "--ignore-issues" flag, e.g. `bit tag --ignore-issues "MissingPackagesDependenciesOnFs, MissingManuallyConfiguredPackages" `
2) ignore the issue completely by configuring it in the workspace.jsonc file. e.g:
"teambit.component/issues": {
  "ignoreIssues": ["MissingPackagesDependenciesOnFs", "MissingManuallyConfiguredPackages"]
}
```
