### ISSUE TITLE
Librarian does not always install packages

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2263]
When adding packages in the playground, they are not installed. ☹️
I debugged the capsule's log with @amitgilad3, and it seems the Orchestrator correctly detects the packages and calls `lb i`, but the package still seem to be missing under `node_modules`.

Happened here at one of our users components:
https://bit.dev/vendasta/satellites/breakpoints
(add `import '@bit/vendasta.satellites.breakpoints';` at app.module.ts, to trigger install)
```
@import '~@bit/vendasta.satellites.breakpoints';
       ^
      Can't find stylesheet to import.
```

it also happens in our own components: 😢
https://bit.dev/bit/gui/file-explorer
```
./src/App/index.js
Module not found: Can't resolve 'memfs' in '/capsule/src/App'
```

https://bit.dev/bit/gui/tree-viewer
```
./src/App/index.js
Attempted import error: 'DragDropContext' is not exported from 'react-dnd'.
```

@imsnif - please take a look.

**Comment by itaymendel** [comment]
irrelevant
