### ISSUE TITLE
Typo on the bit.dev/pricing

### ISSUE THREAD

**Issue by evancharlton** [teambit/bit#2272]
Hi there!

This isn't really an issue with docs.bit.dev, but I didn't know where else to put it so here we are. Sorry if this is inconvenient 😄 

Steps to reproduce:
1. Go to [bit.dev/pricing](https://bit.dev/pricing)
2. Look at the "Enterprise" card

Observed result:
![image](https://user-images.githubusercontent.com/418560/73495802-8fde2d00-43b7-11ea-9ad1-cf5aba22e2cd.png)

Expected result:
>**Tailor** the right solution, tools and terms for your company

😁

**Comment by itaymendel** [comment]
No no, Taylor **IS** the right solution. No threads and needles here :)

Thanks for the note. Fixed. Will be up on the next build cycle.
