### ISSUE TITLE
segmentation fault after instalation on windows

### ISSUE THREAD

**Issue by edward-arinin-web-dev** [teambit/bit#2274]
Getting error after trying to install bit.exe binary.

### Steps to Reproduce

1. `npm install bit-bin --global`
2. download [bit-bin-win.exe](https://github.com/teambit/bit/releases/download/v14.7.2/bit-bin-win.exe)
3. set PATH variable: `C:\bit`
4. open cli and run any bit command. Example: `bit --version`
5. Error `Segmentation fault` on new line

Any attemps to fix this error via reinstalling node.js [link to stackoverflow](https://stackoverflow.com/a/52115031) but it doesn't work for me.

### Specifications

- Bit version: 14.7.2
- Node version: 12.4.1
- npm / yarn version: 6.13.7
- Platform: windows 10
- Bit compiler (include version): -
- Bit tester (include version): -

let me know if you need more logs to reproduce this issue.

### Solved
by using previous version of [bit-bin-win.exe](https://github.com/teambit/bit/releases/download/v14.7.1/bit-bin-win.exe) binary

**Comment by GiladShoham** [comment]
@edward-arinin-web-dev Thanks for reporting this.
We will check it and let you know.

**Comment by GiladShoham** [comment]
@edward-arinin-web-dev  Can you please check 14.7.3 as well?

**Comment by edward-arinin-web-dev** [comment]
@GiladShoham v14.7.3 version is worked for me.

**Comment by ryuk3t** [comment]
same problem:
https://github.com/teambit/bit/releases/download/v14.8.8/bit-bin-win.exe
```bash
# Git-Bash
$ bit -v
Segmentation fault
```

```shell
# Powershell
PS C:\bit> .\bit.exe
PS C:\bit>
```
environemnt:
Windows10 1709
64-bit operating system, x64-based processor

**Comment by itaymendel** [comment]
moving to a dedicated installer for windows via `bvm` as part of the v15 release

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
