### ISSUE TITLE
when running bit tag, loader starts only after `building components...` message ends

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2277]
### Describe the bug

when running `bit tag -a`, the loader can take about 10 seconds to start and it feels like bit might be stuck

### Steps to Reproduce

1. you need some modified/new components in your workspace
2. run `bit tag -a`
3. you see the `building components...` message for a few seconds
4. then the bit the loader starts
5. after about 1 second the logs start:
```
building component - bit.web/routes/pricing@0.0.22(node:54493) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
✔ building component - bit.web/routes/pricing@0.0.22
✔ building component - bit.web/client/client-root@0.0.10
✔ building component - bit.web/client/index@0.0.27
✔ building component - bit.web/shared/routes@0.0.27
```

### Expected Behavior

the loader should start on the first `building components...` message, before the logs start.

### Screenshots, exceptions and logs
the loader starts in the second `building components...` message. see the following screenshot
![Screen Shot 2020-02-02 at 1 29 06 PM](https://user-images.githubusercontent.com/15064762/73607565-44e33600-45c0-11ea-9142-4ac618373dc8.png)

### Specifications

- Bit version: 14.7.2
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.web/compilers/react-flow@0.0.5

**Comment by GiladShoham** [comment]
@odedre Thanks, we will take a look and improve it.

**Comment by itaymendel** [comment]
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
