### ISSUE TITLE
cant tag component without ` --skip-auto-tag` flag

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2292]
### Describe the bug

when I run `bit tag -a` I get the following exception:
```
⠉⠙ isolating component - concrete/headingcomponents/base-components/heading/index.ts:1:10 - error TS2305: Module '"../../../../../../T/bit/capsule-82827/.dependencies/base/heading/bit.marketing/0.0.1/dist/components/base-components/heading"' has no exported member 'HeadingProps'.

1 import { HeadingProps } from '@bit/bit.marketing.base.heading';
           ~~~~~~~~~~~~


Found 1 error.


error: bit failed to build bit.marketing/concrete/heading@0.0.1 with the following exception:
Command failed with exit code 2 (ENOENT): /Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/typescript/bin/tsc --declaration
Error: Command failed with exit code 2 (ENOENT): /Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/typescript/bin/tsc --declaration
    at makeError (/Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```
there is not direct usage of `HeadingProps` outside of the component, so I have no idea what is the problem.

when I run `bit tag base/heading --skip-auto-tag`, it resolves the issue.

### Steps to Reproduce

1. bit import bit.marketing/base/heading
2. modify component
3. run `bit build` - build passes.
4. run `bit test` - tests pass.
5. run `bit  tag -a` - I get the error described above.

### Expected Behavior

bit tag should run as expected

### Specifications

Bit version: 14.7.2
Node version: v10.15.3
yarn version: 1.13.0
Platform: macos
Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43
- Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by davidfirst** [comment]
@odedre , what happens when you run `bit build bit.marketing/concrete/heading`? Also, I suggest updating Bit to the latest version, it includes a fix for a similar issue.

**Comment by itaymendel** [comment]
irrelevant with v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
