### ISSUE TITLE
bit.dev should show properties of named exports

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2294]
Default exports get automatic jsdocs from code,
but named exports do not seem to show up:
https://bit.dev/bit/examples/theme-selector

Any idea why `ObjectKeys` is missing?

### Specifications

- Bit version: 14.7.2
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by GiladShoham** [comment]
Thanks @KutnerUri 
The docs parser aren't updated for a long time.
You can take a look at the code.
The relevant code can be found here - https://github.com/teambit/bit/tree/master/src/jsdoc
It's pretty easy to run this code alone even without running bit itself.
