### ISSUE TITLE
Missing data when running build when no compiler is imported (Cannot read property 'split' of undefined)

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2297]
### Describe the bug

I have a workspace with tracked components, and my compiler is configured in the bit config object, but not imported yet.
Then I run `bit build` and I expect that bit import the compiler first, and then build the components, but I get errors on data that the compiler not receive.

### Steps to Reproduce

1. create a workspace with one file.
1. init bit and track the file.
1. set the compiler in the config but not import it:
```
{
    "bit": {
        "env": {
            "compiler": "bit.envs/compilers/typescript@[version]"
        }
    }
}
```
1. run `bit build`

### Specifications

- Bit version: 14.7.3
- Node version: 12.7.0
- Platform: macOS
- Bit compiler (include version): bit.envs/compilers/typescript@3.1.38

### Additional context

![image](https://user-images.githubusercontent.com/35892475/73733232-40e02100-4744-11ea-94e6-3a125993b1e9.png)

### Temporary Solution

Import the compiler `bit import COMPILER LINK` before running the `bit build` command.
The disadvantage of this solution: if you have a special configuration in the [rawConfig object](https://github.com/teambit/envs/blob/master/packages/ts-compiler/README.md#configuration-reference), they will be removed when you import the compiler.
You can see a solution I wrote to keep the configuration after the import:
https://github.com/teambit/envs/blob/master/.github/workflows/ci.yaml#L45

**Comment by GiladShoham** [comment]
That works for the second time.
Only if the compiler is installed as part of the build it's not working. looks like a missing reloads for something after importing the compiler.

**Comment by patrickcze** [comment]
I am also experiencing this issue, but specifically mine only occurs when running in a circle-ci pipeline and works fine locally.

**Comment by patrickcze** [comment]
Any suggested work arounds for this issue?

**Comment by JoshK2** [comment]
> Any suggested work arounds for this issue?

I have just written a Temporary Solution in the opening comment.

**Comment by patrickcze** [comment]
Thanks @JoshK2 the solution above does work in our Circle-CI pipeline now.

**Comment by GiladShoham** [comment]
This should be solved as part of the next major version - [harmony](https://github.com/teambit/bit/issues/2280)

**Comment by itaymendel** [comment]
irrelevant for v15
