### ISSUE TITLE
topological sort dependencies error when moving dependencies to be dev

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#2299]
### Describe the bug

I want to move `build-component` to be dev dependencies of the TS compiler, so I use the overrides option, I run `bit show` to check everything is fine, then run build and get this error:
![image](https://user-images.githubusercontent.com/35892475/73752403-9a0e7b80-4769-11ea-93e3-880c5b982e8c.png)

### Steps to Reproduce

1. clone the envs repo
1. run `npm i && npm run postinstall`
1. run `npm run build` it should be ok
1. now change the compilers/typescript overrides:
```
"compilers/typescript": {
        "dependencies": {
          "bit-bin": "-",
          "@bit/bit.envs.common.build-component": "-"
        },
        "devDependencies": {
          "@types/node": "+",
          "@types/mocha": "^5.2.7",
          "bit-bin": "14.6.0",
          "@bit/bit.envs.common.build-component": "0.0.14"
        }
      },
```

### Specifications

- Bit version: 14.7.3
- Node version: 12.7.0
- Platform: macOS

**Comment by davidfirst** [comment]
@JoshK2 , thanks for reporting this, I'm able to reproduce the issue. We'll take a look and update.

**Comment by itaymendel** [comment]
irrelevant for v15
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
