### ISSUE TITLE
bit import of all components hangs forever

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2301]
### Describe the bug

This mostly happens when the components have huge number of versions.
The server throws an error:
```
{"errno":"E2BIG","code":"E2BIG","syscall":"spawn","level":"error"}
```

### Steps to Reproduce

1. Create 100 component, for each one create 200 tags.
2. tag an export over ssh.
3. delete the local objects, or clone the workspace somewhere else.
4. run `bit import`.

### Expected Behavior

The import should complete successfully.

### Specifications

- Bit version: 14.7.3
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

The issue started from v14.2.3, which included the following fix: "[improve performance of importing an entire collection](https://github.com/teambit/bit/pull/1851)".
This fix reduces the round-trips to the ssh server and asks for all components at once. (before, when fetching all components with all versions, it used to go to the remote for each component).
Asking for all of them at once creates a huge string of ids and when passing it as an arg, this creates an issue.

**Comment by GiladShoham** [comment]
@davidfirst Let's make a public collection with those requirements and post a bitmap here via a gist so we can easily reproduce it.

**Comment by itaymendel** [comment]
import performance boost in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Comment by alexandra-c** [comment]
Any news about this issue? I'm having this problem also and it seems like v15 is not out yet. I'm using v14.8.8.
