### ISSUE TITLE
Tracking for outdated bit component dependencies

### ISSUE THREAD

**Issue by Rvkstrauss** [teambit/bit#2302]
### Description
Currently if a component dependency of another component is out of date, I have to manually discover and update component's dependency. Is there a way to do this more efficiently?

### Specifications

- Bit version: latest
- Node version: 10+
- npm / yarn version: npm 6.9.0
- Platform: macOS
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information
Steps to reproduce:
install component A latest version which depends on component Bv2 (latest is v3)
component B updates to v3, breaking component A
to update component A, manual resolution via package-lock is necessary in order to discover and update dependencies
one by one, update and export component A dependents to use component B v3

**Comment by itaymendel** [comment]
What's the output of running `bit list --outdated` ?
This should give you a better understanding of whats going on.
