### ISSUE TITLE
cant untrack a file from a component

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2316]
### Description

I have an exported component from my local env(`theme/theme-provider`). I added a file to it by accident(`heading-margin-definition.module.scss`), now I cant remove it from the component. 

there is nothing specified in the docs about this. I looked [here](https://docs.bit.dev/docs/add-and-isolate-components.html#manage-components-files)

### scenarios I tried:
- `bit untrack theme/theme-provider`
response: 
```
error: unable to untrack bit.marketing/theme/theme-provider, please use the bit remove command.
```
- `bit add src/themes/theme-provider/* -i theme/theme-provider --exclude src/themes/heading-margin-definition.module.scss`
also without the `*`:
`bit add src/themes/theme-provider/ -i theme/theme-provider --exclude src/themes/heading-margin-definition.module.scss`
response:
```
tracking component bit.marketing/theme/theme-provider@0.0.2:
added src/themes/heading-margin-definition.module.scss
added src/themes/theme-provider/index.tsx
added src/themes/theme-provider/theme-provider.tsx
```
the file was not removed from the component.

- `bit add src/themes/heading-margin-definition.module.scss -i theme/heading-margin-definition`
  response:
```
warning: files src/themes/heading-margin-definition.module.scss already used by component: bit.marketing/theme/theme-provider@0.0.2
```

### Specifications

- Bit version: 14.7.4
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by GiladShoham** [comment]
can you try 
`bit add src/themes/theme-provider/ -i bit.marketing/theme/theme-provider --exclude src/themes/heading-margin-definition.module.scss` (full copmonent id)

**Comment by odedre** [comment]
@GiladShoham it didn't work.
I got the following error:
```
error: file or directory "bit.marketing/theme/theme-provider/" was not found.

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

**Comment by davidfirst** [comment]
@odedre , you need the `--override` flag. 
I guess this should be fine:
`bit add src/themes/theme-provider/* -i theme/theme-provider --exclude src/themes/heading-margin-definition.module.scss --override`

**Comment by Orancula** [comment]
I also have the same issue. I have a button component that looks like this:

Button
|--Button.tsx
|--Button.styles.ts
|--Button.stories.tsx

I would like to untrack or remove "Button.stories.tsx". I tried running all the suggestions in this thread but bothing seems to work. The last suggestion by **davidfirst** produces the following error:

error: option `-o, --override <boolean>' argument missing

Bit.dev documentation is very unclear how to remove files from components or exclude them. Seems like quite a common thing to do. Does anyone have any other suggestions to try?

**Comment by itaymendel** [comment]
in v15 a component is a dir, so removed support for such flows

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
