### ISSUE TITLE
Bit adding shared component files and folder separately 

### ISSUE THREAD

**Issue by Mujaddadi** [teambit/bit#2325]
I have a shared component TimePicker in which I have `index.js` file and one folder named `components`. When I do `bit add src/sharedComponents/TimePicker/* —id ui/timepicker`, it just add two ids separately for `index.js` and one for `components` folder instead of creating one shared component id. How can I solve this issue?

Here is the result of bit status

```
$ bit status
- fetching status
new components
(use "bit tag --all [version]" to lock a version with all your changes)

     > components ... ok
     > index ... ok
```
I also tried adding them explicitly but still Bit consider them separate components.

**Comment by Mujaddadi** [comment]
Can anyone please help me fix this issue?

**Comment by davidfirst** [comment]
@Mujaddadi , just omit the `/*`. 
try to run this: `bit add src/sharedComponents/TimePicker —id ui/timepicker`. 
It'll add this dir as one component. 

@Tallyb , this is the second confusion I see today about the same thing (https://github.com/teambit/bit/issues/2332 was the first). Maybe it could be addressed in the docs.

**Comment by Mujaddadi** [comment]
@davidfirst Thanks it worked.
