### ISSUE TITLE
Notify on login if trying to export to bit.dev

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2328]
### Description

If the user is not logged in and is trying to export (or other write commands,  I assume), it will fallback to requesting username and password. 

### Describe the solution you'd like

Instead, show the following message: You are not logged in on this machine. Use bit login to sign into your bit.dev account. 
This should only run if the user is trying to access bit.dev and not a private server. 

### Describe alternatives you've considered

Keep current behavior.

**Comment by davidfirst** [comment]
The username/password strategy is one of the authentication strategies. 
We don't know whether a user has access until we try all strategies one by one including username and password.

I understand that this can confuse new users. so maybe we should eliminate the user/password strategy altogether. Is this really in-use? @itaymendel ?

Other commands. e.g. `bit import`, `bit list` add another strategy - anonymous, and as a result, if the user is not logged-in, it throws `PermissionDenied` error. So these commands already ignore the user/password strategy.
We might want to align all commands with the same strategies. If bit-export behaves the same, this won't be an issue. @GiladShoham .

**Comment by itaymendel** [comment]
@davidfirst , is it possible to know when a user killed the username/password prompt (or failed to authenticate with it)?
If it's possible, Bit can trigger a "help" message telling the user that if they have issues authenticating to their remote scope, they should go to a page in the docs that explains on authentication issues.
With the current suggestion, we only support people that try to use bit.dev, but as you mentioned - there are other possibilities.

**Comment by davidfirst** [comment]
@itaymendel , the user/password is the last strategy used.
We know when the user failed authenticating, so we know for sure that user/pass failed as well. Once the user/pass fails, it shows this message:
```
➜  bar-foo bit export david.tmp3
username:  f
password:
authentication failed. see troubleshooting at https://docs.bit.dev/docs/setup-authentication#autentication-issues.html

The following strategies were failed
[-] user token not defined in bit-config. please run `bit login` to authenticate.
[-] no matching private key found in ssh-agent to authenticate to remote server.
[-] SSH key not found in `~/.ssh/id_rsa` or `ssh_key_file` config in `bit config` either not configured or refers to wrong path.
[-] unable to connect using provided username and password combination.

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```
So, seems like what we have now does explain what happened and suggest visiting the doc.

**Comment by itaymendel** [comment]
I remember we added it.
Let me re-phrase myself.

Can we also catch the case of killing the process (ctrl+c, for example) at that state (waiting on user/pass combo) and prompt with that error?
