### ISSUE TITLE
Cannot compile package within @nestjs/graphql

### ISSUE THREAD

**Issue by lucasmonstro** [teambit/bit#2335]
### Describe the bug

When I try to tag my package(Im using nestjs within typescript) looks like **apollo-server-core** is missing from packages tree.

```sh
$ bit tag tenant
- importing components
- building components
- building component - tenant
node_modules/@nestjs/graphql/dist/graphql.module.d.ts(3,34): error TS2307: Cannot find module 'apollo-server-core'.
node_modules/@nestjs/graphql/dist/interfaces/gql-module-options.interface.d.ts(3,24): error TS2307: Cannot find module 'apollo-server-core'.

error: bit failed to build tenant with the following exception:
Command failed with exit code 2 (Unknown system error -2): C:\Users\joaol\Workspace\brainnit\auth-api\.git\bit\components\compilers\typescript\bit.envs\3.1.39\node_modules\typescript\bin\tsc --declaration
Error: Command failed with exit code 2 (Unknown system error -2): C:\Users\joaol\Workspace\brainnit\auth-api\.git\bit\components\compilers\typescript\bit.envs\3.1.39\node_modules\typescript\bin\tsc --declaration
    at makeError (C:\Users\joaol\Workspace\brainnit\auth-api\.git\bit\components\compilers\typescript\bit.envs\3.1.39\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\joaol\Workspace\brainnit\auth-api\.git\bit\components\compilers\typescript\bit.envs\3.1.39\node_modules\execa\index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

### Steps to Reproduce

1. bit add src/packages/tenant
2. bit tag tenant

### Expected Behavior

I hope everything goes well and my package compiled.

### Specifications

- Bit version: 14.7.4
- Node version: v12.14.1
- yarn version: 1.21.1
- Platform: windows 10 PRO
- Bit compiler (include version): bit.envs/compilers/typescript@3.1.39
- Bit tester (include version):

**Comment by luqezman** [comment]
Any feedback?

**Comment by itaymendel** [comment]
when you run `bit show <component>` do you see `apollo-server-core` as a dependency?
this looks very much like its related to this issue - https://github.com/teambit/envs/issues/92

**Comment by itaymendel** [comment]
bit v15 now fully supports nextjs

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
