### ISSUE TITLE
Bit does not generate documentation for React with TS components

### ISSUE THREAD

**Issue by giteden** [teambit/bit#2337]
### Description

Bit does not generate docs for React TS components.

for example:

https://bit.dev/eden/react-ts-demo

### Specifications

- Bit version: 14.7.4
- Node version: 10.15.3
- npm / yarn version: 6.4.1 / 1.16.0
- Platform: macOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.44 
- Bit tester (include version):

**Comment by davidfirst** [comment]
Interesting.
This is probably the same issue as https://github.com/teambit/bit/issues/2486.
Thanks @giteden  for reporting this, we'll take a look.

**Comment by giteden** [comment]
That issue is now resolved. 

As it turns out, there's a specific syntax for it to work properly.

Simply writing this (see below), will not work:

```
const Button : React.FC<IButtonProps> = ({text, type, action}) => {

}
```

Instead, this works fine:

```
const Button : React.FC<IButtonProps> = ({text, type, action} : IButtonProps) => {

}
```

**Comment by davidfirst** [comment]
Thanks @giteden for the update! 
@KutnerUri , this might help you.
