### ISSUE TITLE
unable to re-export after deleting the components from the remote

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2341]
### Describe the bug
If I recreated my remote collection or removed my remote components but left them locally, then trying to re-export them, here is what happens:
1) `bit export <my-remote>` =>  returns "nothing to export".
2) `bit export <my-remote> <glob>` =>  returns "nothing to export".
3) `bit export <my-remote> <id>` => returns "component X has been already exported to Y".
4) `bit export <my-remote> <glob> --all` => returns "error: component X was not found.".
5) `bit export <my-remote> <glob> --all --all-versions` => succeeded! 

### Steps to Reproduce
1. create and export a component.
1. delete the remote component.
1. export the component using `bit export <remote>`

### Expected Behavior
Currently, to bypass this issue, you have to run `bit export <remote> <component-id-or-glob> --all versions --all`.
the `--all-versions` flag makes sure to export non-staged versions.
the `--all` flag makes sure to export non-staged components.
this is not trivial.

I suggest the following:

1. when using `--all`, it'll enable `--all-versions` flag.
1. when using `--all-versions`, it'll enable `--all` flag.
1. maybe renaming the `--all` to `--include-non-staged`? Tallyb , itaymendel .
1. when not using any flag. along with "nothing to export", we can suggest the user using `--all` flag. Tallyb , itaymendel
1. when exporting one component and it's exported already, it should allow it to be re-exported, same as when using a wildcard.

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 14.7.4

**Comment by Tallyb** [comment]
I am not sure I follow:
1) --all refer to components, i.e. it will export ALL the components in the workspace, including ones that are not in stages. 
2) --all-versions is per component, i.e. for each component export all of its versions, and not just the ones that are not staged. 
Potentially, the -all-versions can be renamed to --full. 
I would not change the defaults on behavior. 
4) sounds good: "Use --all to export components that were previously exported".

**Comment by davidfirst** [comment]
Thanks @Tallyb . 
For the most part, what you've written is correct. Only the `--all` flag doesn't necessarily mean all components. I can use it with ids and it'll export only these ids.
