### ISSUE TITLE
bit link to specific components

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2342]
Currently, `bit link` generates a link for each component in the `bit.json`.
I would like more granularity, something like:

```bash
bit link bit.web/utils/on-props-change bit.web/types/* # ...
```

### specifications
* bit version 14.7.4

**Comment by davidfirst** [comment]
Before implementing this, `bit link` should support wildcards. 

Just to explain the request above. Imagine compA requires compB and compC, the idea is to support linking of compA to compB only but not compC.

@KutnerUri , can you provide a use-case where this can be helpful?

**Comment by KutnerUri** [comment]
I can't remember the use case now. It makes more sense with the pending `--rewire` flag, where this control is very needed.

If I modified only some of the components, re-linking only these components could save time.
