### ISSUE TITLE
bit tag --force does not work

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2344]
### Describe the bug

I have a component that I want to tag, but the compiler says it has an exception. I tried to run `bit tag community-links/github-link --force` but I still got the following compiler error:
```
isolating component - community-links/github-linkcommunity-links/github-link/github-link.tsx:8:21 - error TS2307: Cannot find module '../../../concrete/image'.

8 import {Image} from '../../../concrete/image';
                      ~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.


error: bit failed to build bit.marketing/community-links/github-link@0.0.1 with the following exception:
Command failed with exit code 2 (ENOENT): /Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/typescript/bin/tsc --declaration
Error: Command failed with exit code 2 (ENOENT): /Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/typescript/bin/tsc --declaration
    at makeError (/Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Users/oded/code/base-components/.git/bit/components/compilers/react-typescript/bit.envs/3.1.43/components/.dependencies/compilers/typescript/bit.envs/3.1.38/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I still want to tag this. how do I proceed?
### Steps to Reproduce

1. create component that should require a non existing component.
2. import the react-typescript compiler
3. bit add component
4. bit tag component
5. not that we see that it breaks, try `bit tag --foce`

### Expected Behavior

bit should tag with the `--force` flag

### Specifications

- Bit version: 14.7.4
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by luqezman** [comment]
News?

**Comment by davidfirst** [comment]
The flag `--force` allows tagging when the tests failed. It doesn't do anything regarding the build process.

If we let `--force` skips the build in case of failure it'll result in a component that has compiler set up but no dists, which, as far as I remember we throw an error at some point if this is the case.
Meaning, we expect a component that has a compiler to have dists.

@GiladShoham , your input is welcome here.
