### ISSUE TITLE
Show progress during export

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2353]
### Description

Currently the export is only showing the target collection when the export is finished. 

### Describe the solution you'd like

Show a pre command about the target collection / remote scope prior to execution. 
exporting xxx.yyy to user.collection

### Describe alternatives you've considered

keep current

**Comment by davidfirst** [comment]
Makes sense.
Not sure about showing every component because the actual act of pushing the components to one remote-scope is pretty fast. What takes time is the process until this is done. So I guess the loader should change its status every step and then also for each collection it exports.
