### ISSUE TITLE
TablePagination Css material UI

### ISSUE THREAD

**Issue by eimanhakimy** [teambit/bit#2354]
import React from 'react';
import PropTypes from 'prop-types';

import TablePagination from '@material-ui/core/TablePagination';

import '../table/styling/tablestyle';

  export default function GTablePagination(props){  
      const {count, page, rowsPerPage, parentCallback} = props;

      const handleChangeRowsPerPage = event => {       
        parentCallback("changeRowsPerPage", parseInt(event.target.value, 10));
      };

      const handleChangePage = (event, newValue) => {
          parentCallback("changePage", newValue);
      }
  

      return(
            <TablePagination
                
                component="div"
                count={count}
                rowsPerPage={rowsPerPage}
                rowsPerPageOptions={[3 ,10, 50, { label: 'All', value: -1 }  ]}
                page={page}
                SelectProps = {{
                  inputProps: { 'aria-label': 'rows per page' },
                  native: true,
                }}
                backIconButtonProps={{
                  'aria-label': 'previous page',
                }}
                nextIconButtonProps={{
                  'aria-label': 'next page',
                }}
                onChangePage={handleChangePage}
                onChangeRowsPerPage={handleChangeRowsPerPage}
            />
            
      );
  };
  
  GTablePagination.propTypes = {
      count: PropTypes.number.isRequired,
      rowsPerPage: PropTypes.number.isRequired, 
      page: PropTypes.number.isRequired,   
      parentCallback: PropTypes.func.isRequired
  };

  

can someone help me how do i want to styling this table pagination just like change color or fontsize

**Comment by itaymendel** [comment]
Hi @eimanhakimy , this issue is unrelated to Bit.
Perhaps you should open it here https://github.com/mui-org/material-ui

Closing the issue.
