### ISSUE TITLE
bit checkout error is misleading when you're up to date

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2362]
### Description

I ran the following `bit checkout -a latest` and got the following error.

### Describe the solution you'd like

the error is basically telling me that i'm up to date. I dont think it should be as threatening (see screenshot).

### Additional context
<img width="1145" alt="Screen Shot 2020-02-17 at 9 03 16 PM" src="https://user-images.githubusercontent.com/15064762/74680471-5dab3880-51c9-11ea-8f89-37e32ddac1ea.png">

**Comment by davidfirst** [comment]
@odedre , I see your point :) It should probably be green with a nice message saying you're up to date.

**Comment by itaymendel** [comment]
let's just change output to green :)

**Comment by davidfirst** [comment]
It's more complex that this. The red message is when a component wasn't checked out. It can be due to an error and it could be because it's up to date. 
A suggestion made by Ran is to not output any "up-to-date" components unless `--verbose` flag is used.

**Comment by itaymendel** [comment]
alright, i'm fine with that
