### ISSUE TITLE
bit tag --skip-auto-tag breaks flow

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2364]
### Describe the bug

I tagged using the `--skip-auto-tag` flag and now Im in stuck in a loop.
I tried tagging the components individually and they are being tagged and still appear in the modified section as well.
when I ran bit diff Ican see that every tag changes the dependency version.

I ran `bit tag concrete/cta-button` then `bit diff concrete/cta-button`:
```
base-components git:(master) ✗ bit diff concrete/cta-button
-----------------------------------------------------------
showing diff for bit.marketing/concrete/cta-button
-----------------------------------------------------------

--- Dependencies (0.0.8 original)
+++ Dependencies (0.0.8 modified)
- [ bit.marketing/base/primary-button@0.0.6, classnames@^2.2.6, react@^16.x.x, @types/classnames@^2.2.9, @types/react@^16.x.x ]
+ [ bit.marketing/base/primary-button@0.0.5, classnames@^2.2.6, react@^16.x.x, @types/classnames@^2.2.9, @types/react@^16.x.x ]
```
the  I ran `bit tag concrete/cta-button` then `bit diff concrete/cta-button` again:
```
base-components git:(master) ✗ bit diff concrete/cta-button
-----------------------------------------------------------
showing diff for bit.marketing/concrete/cta-button
-----------------------------------------------------------

--- Dependencies (0.0.10 original)
+++ Dependencies (0.0.10 modified)
- [ bit.marketing/base/primary-button@0.0.6, classnames@^2.2.6, react@^16.x.x, @types/classnames@^2.2.9, @types/react@^16.x.x ]
+ [ bit.marketing/base/primary-button@0.0.5, classnames@^2.2.6, react@^16.x.x, @types/classnames@^2.2.9, @types/react@^16.x.x ]
```
you can see that the dependency version changed back to v0.0.5 for some reason.

### Expected Behavior

bit should not be stuck in this loop.

### Screenshots, exceptions and logs

<img width="921" alt="Screen Shot 2020-02-18 at 1 33 29 PM" src="https://user-images.githubusercontent.com/15064762/74732606-46189200-5253-11ea-9b5c-b95b9bc42349.png">

### Specifications

- Bit version: 14.7.5-dev.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by davidfirst** [comment]
@odedre , when tagging a component, its dependents are automatically set with the new version of that component, so the next time you tag them, they'll have the latest dependencies.

If I understand correctly, for you, this is an issue because you don't want to tag the dependents, only the dependencies. However, because they're modified, when you run "bit tag -a", they're tagged. Correct?

**Comment by GiladShoham** [comment]
@davidfirst you don't understand correctly.
The dependencies are going back and forth between the versions. so you will be modified forever.
It's reasonable that the deponent will be modified after the tagging the dependencies with --skip-auto-tag. but it's not reasonable that after tagging the dependents they will be modified and the change it to restore an older version of the dependency. 
It's a real bug.

**Comment by makeupsomething** [comment]
Im currently stuck in this loop, is there a way out?

**Comment by makeupsomething** [comment]
Just to update I was able to get around the issues by installing the updated dependency as a dev dependency and then running `bit build`. 
After that the components were no longer in a "modified" state.
