### ISSUE TITLE
'bit checkout' creates overrides for all tracked components in package.json

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2367]
### Describe the bug

after running `bit checkout latest` I see all the tracked bit components in the overrides section in the package.json.

### Steps to Reproduce

1. you should have a component in your workspace that is not the latest version 
2. bit checkout latest -a
3. look in package.json - bit has created an override object for every component that  you have in your workspace. 

### Expected Behavior

bit should not create the override object if you are the authored env.

### Screenshots, exceptions and logs

![Screen Shot 2020-02-18 at 3 59 54 PM](https://user-images.githubusercontent.com/15064762/74744213-86cfd580-526a-11ea-8db2-4319f7c550e6.png)

### Specifications

- Bit version: 14.7.5-dev.1
- Node version: v10.15.3
- yarn version: 1.13.0
- Platform: macos
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by davidfirst** [comment]
Thanks @odedre for reporting this.
It seems to be a bug and I bet I can also reproduce it by running `bit import` as an author.
We'll take a look and update here.
