### ISSUE TITLE
Capsule is built differently for Imported and for Authored component

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2372]
I have the following 2 components: 
```
    "tallyb.test/my-component@0.0.1": {
        "files": [
            {
                "name": "my-component.css",
                "relativePath": "components/my-component/my-component.css",
                "test": false
            },
            {
                "name": "my-component.e2e.ts",
                "relativePath": "components/my-component/my-component.e2e.ts",
                "test": true
            },
            {
                "name": "my-component.tsx",
                "relativePath": "components/my-component/my-component.tsx",
                "test": false
            },
            {
                "name": "readme.md",
                "relativePath": "components/my-component/readme.md",
                "test": false
            }
        ],
        "mainFile": "components/my-component/my-component.tsx",
        "rootDir": "components/my-component",
        "origin": "IMPORTED",
        "originallySharedDir": "src"
    },
    "typography": {
        "files": [
            {
                "relativePath": "components/typography/readme.md",
                "test": false,
                "name": "readme.md"
            },
            {
                "relativePath": "components/typography/typography.css",
                "test": false,
                "name": "typography.css"
            },
            {
                "relativePath": "components/typography/typography.tsx",
                "test": false,
                "name": "typography.tsx"
            }
        ],
        "mainFile": "components/typography/typography.tsx",
        "trackDir": "components/typography",
        "origin": "AUTHORED",
        "exported": false
    },
```

When building the capsule I get 2 different structures: 
![Screen Shot 2020-02-19 at 19 00 15](https://user-images.githubusercontent.com/7386255/74855993-15ffea80-534a-11ea-8c7f-54763202fbee.png)

This, of course, causes the compiler to fail. 
The component.mainFile received is showing components/typography/typography.tsx even that the file is not really located there.
Thoughts? Bug?

**Comment by Tallyb** [comment]
In fact, the structure difference is ok, as the local has import from '../../`. 
However, the mainFile received from the capsule is not usable, as it is not how it is built in the capsule.

**Comment by GiladShoham** [comment]
@Tallyb Maybe it worth to test it with the last changes by @davidfirst which make it a bit different

**Comment by davidfirst** [comment]
Once my PR https://github.com/teambit/bit/pull/2440 is merged, the paths on the workspace and on the capsule will be the same.

**Comment by itaymendel** [comment]
resovled for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
