### ISSUE TITLE
Delete Bit Collection from Remote.

### ISSUE THREAD

**Issue by allindeveloper** [teambit/bit#2377]
Is it possible to delete an entire collection from remote.

If Possible, please how can i do that?

**Comment by itaymendel** [comment]
Hi @allindeveloper , do you mean removing a self-hosted remote or delete an entire collection in bit.dev?

If you are self-hosting, it's completely up to you, but if you use bit.dev as a provider, you can open the collection settings (top-right corner of the collection page), and delete it.
