### ISSUE TITLE
How can i use less？

### ISSUE THREAD

**Issue by JHouae** [teambit/bit#2399]
### Description

You may need an appropriate loader to handle this file type. how can i add loader? Thanks

### Specifications

- Bit version: 14.7.6
- Node version: 12.8.1
- npm / yarn version: 6.10.3
- Platform: macos 10.14.6
- Bit compiler (include version): bit.envs/compilers/react@1.0.14
- Bit tester (include version):

**Comment by itaymendel** [comment]
You need to handle Less in the project that consumes the component, as this is the app's bundler's job. This is not relevant to the Bit component.
