### ISSUE TITLE
Id duplication in bit

### ISSUE THREAD

**Issue by VijiRajendran** [teambit/bit#2401]
##I need a private component to be imported in my local project repository and I used to execute the command 
bit import altius.angular-tutorial/product-list

## But i'm getting an issue
 your id altius.angular-tutorial/product-list@0.0.1 is duplicated with altius.altius-middlelayer/product-list@0.0.2
run 'bit doctor' to get detailed workspace diagnosis and issue resolution.

**Comment by itaymendel** [comment]
What's the output of `bit list` and `bit status` in your local workspace directory?
