### ISSUE TITLE
Issue when installing compilers..

### ISSUE THREAD

**Issue by alanmontgomery** [teambit/bit#2404]
### I'm having issues installing compilers

This has been working up until today. I updated NPM around 1 hour ago, and the problem seemed to start since then.

Here's my error output;

```
failed running npm install at /Volumes/Work/Development/mobileframework/.bit/components/compilers/babel/bit.envs/7.0.4 with args: --production
npm ERR! Unexpected end of JSON input while parsing near '...8.11"},"dist":{"shasu'
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/alanmontgomery/.npm/_logs/2020-02-27T15_26_44_512Z-debug.log
```

after running `bit import bit.envs/compilers/babel --compiler`

I can run bit status and bit tag as well as bit export OK, but i need to install babel and react compilers. Any help on this?

Bit Version: 14.7.6
NPM Version: 6.14.1

**Comment by itaymendel** [comment]
Hi! Can you share the full error log from npm?

**Comment by alanmontgomery** [comment]
> Hi! Can you share the full error log from npm?

I've resolved it. One of my packages needed updated following my npm update. I think i totally panicked. I don't know why I did. a simple npm install fixed this whole issue *facepalm*
