### ISSUE TITLE
Authentication method : ssh method for authentication not working

### ISSUE THREAD

**Issue by shailendra0015** [teambit/bit#2408]
I have added ssh key to my account. But when I try to import package through npm registry. It's not able to fetch it . when I log in using the username and password it works fine.
I have to integrate this into CI CD pipeline in bitbucket. So I tried with the password.
But could, not able import package as it prompts for username password in CI-CD pipeline.
how can I use bit without password

**Comment by itaymendel** [comment]
Hi
Have you read through these documents?
https://docs.bit.dev/docs/ci
https://docs.bit.dev/docs/setup-authentication

Basically you need to authenticate your npm client to use npm-install. It does not work over ssh.
