### ISSUE TITLE
"component not found" when bulk exporting 

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2412]
I just finished tagging all my components, and I am now trying to export them.

I am getting this error, how do I even debug this?

<img width="381" alt="Screen Shot 2020-03-01 at 21 14 10" src="https://user-images.githubusercontent.com/5400361/75632125-c9e25f00-5c01-11ea-850c-1604aeadd14d.png">
### Specifications

- Bit version: 14.7.6
- Node version: 12.12.0
- npm / yarn version: 1.22.0
- Platform: MacOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43
- Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by itaymendel** [comment]
Please try to use the `--all-versions` flag with the export command.
does this reproduces?

**Comment by KutnerUri** [comment]
yes, it seems to export correctly with the `--all-versions` flag. Nice catch.
I am guessing this has something to do with newly tracked components.

I think we should keep this issue open as a _bug_? Bit should recognise these edge cases.

**Comment by itaymendel** [comment]
Might need @davidfirst on this one...

**Comment by GiladShoham** [comment]
I think @davidfirst already did something about it a few days ago. is it correct @davidfirst ?

**Comment by davidfirst** [comment]
@GiladShoham , @itaymendel , yes, I fixed this issue recently. It's part of the latest dev release.

**Comment by GiladShoham** [comment]
@davidfirst lets refers to the pr and close this

**Comment by davidfirst** [comment]
This is the PR: https://github.com/teambit/bit/pull/2466 I hope it fixed this issue as well. Closing.
