### ISSUE TITLE
bit should use latest versions in tag -a

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2415]
When tagging with `-a`, bit does not use the latest version of the code.

for example,
```
//A @0.0.1:
export function A(n: number){
    return n + n;
}
```

```
//B @0.0.1:
import { A } from './A';

export function B(n: number){
    return A(n);
}
```

After modifying:
```
//A @0.0.1 (modified):
export function A(n: number, s: string){
    return (n + n) + s;
}
```

```
//B @0.0.1:
import { A } from './A';

export function B(n: number){
    return A(n, 'bbb!');
}
```

run: `bit tag -a`.

#### expected: 
compilation should successfully finish.

#### actual:
typescript compiler fails when compiling `B`,
saying that `A` expects only 1 argument.

I believe the compiler is installing the last build output for `A`, where it should use the files built in the same `tag -a`.

### Workaround: 
It will work when tagging manually:
```
> bit tag --skip-auto-tag A
... tagged 1 component
> bit tag --skip-auto-tag b
... tagged 1 component
```

### Specifications

- Bit version: 14.7.6
- Node version: 12.12.0
- yarn version: 1.22.0
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43

**Comment by davidfirst** [comment]
I remember seeing this issue before with the TS compiler.
With the next version (Harmony), this should not be an issue because it builds the graph from the workspace using the modified components.

**Comment by itaymendel** [comment]
v15 release this week. this is irrelevant
