### ISSUE TITLE
bit doesnt recognize .module.css as a legitimate file ending 

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2416]
### Describe the bug

I added a file with the `.module.css` ending. bit did not recognize it as a valid file ending and added it to the `module` to the component name.

### Steps to Reproduce

1. create a file called `component.module.css`
2. add it to bit with the -n flag
3. the component was named `componentmodule`

### Expected Behavior

bit should recognize that the `.module` part is not a part of the name.
even if bit doesn't recognize it, it should at least be replaced with `-`.

**Comment by davidfirst** [comment]
Thanks @odedre for reporting this.

@Tallyb , @itaymendel , what do you suggest the best experience here?
As described, If I run `bit add component.module.css`, the component name is `componentmodule`. 
According to the code, we replace camelCase with a dash but remove all dots. I guess we should also replace dots with dashes.

**Comment by GiladShoham** [comment]
I agree it should replace dots with dashes.

**Comment by Tallyb** [comment]
@davidfirst @GiladShoham  - this is not a common scenario (adding only module.css file to component). I suggest to freeze it.

**Comment by itaymendel** [comment]
resolved
