### ISSUE TITLE
if support  multiple components as a package

### ISSUE THREAD

**Issue by MoonSeeing** [teambit/bit#2418]
### Description

i have custom a lot of ui  component quantity above 50.Now ,i have  3 project all use those component.I known bit can  support to package every my component  one by one.But  i should import 50 components from the collection of  bit .it will make the package.json file very long  by import so many component.so, if have a good solution can package all component to one  component or  one package . i just only import once ,then get what i need  from the package.
Like this:
 ``` import {
  List,
  Datagrid,
  Filter,
  ShowButton,
} from '@bit/castlery.cowboy.react-admin';
```

### Describe the solution you'd like
Package all component to one component in a good way.

### my try 
 my components is on [https://bit.dev/castlery/cowboy/react-admin](url)
 file structure:
![image](https://user-images.githubusercontent.com/19420622/75842818-65472000-5e0c-11ea-9f1c-0211f6158f86.png)

now i can just only install the  package '@bit/castlery.cowboy.react-admin'  once 
use in file  by
```  import {
  List,
  Datagrid,
  Filter,
  ShowButton,
} from '@bit/castlery.cowboy.react-admin';
```
yes , i can do it like this .In my project  i can use it ,when i run yarn start .but when  i  import it to my local project , use '$ bit import castlery.cowboy/react-admin' then run it will make error .
the error  is ' invalid hook call'.i know two react instance  may cause the error .i  am confuse tha  it can run install it  but can not use in local . if my export component structure make it?somebody can figure out it ?

**Comment by itaymendel** [comment]
There's an old discussion about it here #784 . Gilad [explained in detail](https://github.com/teambit/bit/issues/784#issuecomment-374900517) the issues to implement such a feature.

I agree that this can be useful at times, but it kinda-of removes the value of splitting a large shared component library to individually published components.

You can manually create such a "package" by yourself with another component that import/export any other component as you see fit.
