### ISSUE TITLE
export not working on owner name start with number

### ISSUE THREAD

**Issue by guysaar223** [teambit/bit#2421]
### Describe the bug

export not working on owner name start with number

### Steps to Reproduce

1. create bit.dev owner start with number (1{name}.{collctionName})
1. export component to collection 

- Bit version: 14.7.2
- Node version: 10.16.0
- Platform:
ProductName:	Mac OS X
ProductVersion:	10.15.2

**Comment by itaymendel** [comment]
irrelevant, as account name can't start with a number
