### ISSUE TITLE
Difference between  import   and    install

### ISSUE THREAD

**Issue by LeonYanghaha** [teambit/bit#2424]
I read the document carefully, but I don't understand the difference between  ``` bit import ``` and  ``` bit install ``` do they have any similarities and differences？If the component I use is updated, then locally, I should use that command to make the component consistent with the remote version？ who can tell me ? thank you.

**Comment by Tallyb** [comment]
Bit install is adding the package as a regular NPM package to the node_modules folder. Bit import is adding the component to the components folder (https://docs.bit.dev/docs/conf-bit-json#componentsdefaultdirectory) and tracks editions to it. 
 
When installing a component (bit install / npm install / yarn add), the component is added to the pacakge.json, pointing to the installed version: 
```
"@bit/user.collection.tabs": "0.0.2"
```

When you do an import, you can see that the package.json is being updated to point to the local file: 
```
`"@bit/user.collection.tabs": "file:./components/tabs" `
```
When the component is imported you can update the source code, build and then tag and export (subject to privileges). 

If you eject the component the package.json is updated back to 
```
"@bit/user.collection.tabs": "0.0.3"
```
The version will be the last version used and tagged in your workspace.
