### ISSUE TITLE
Is `npm login` into an account signed up via "Connect with GitHub" supported?

### ISSUE THREAD

**Issue by yuriybelike** [teambit/bit#2434]
### Description

I'm having issues logging in into my account signed up via "Connect with GitHub" with
```bash
npm login --registry=https://node.bit.dev --scope=@bit
```

### Specifications

- Bit version: 14.7.6
- Node version: 10.16.3
- npm / yarn version: 6.9.0
- Platform: Windows 
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
the npm-cli does not support it, so the workaround we implemented is when you use `bit login`. it creates a `.npmrc` file with the authentication token, so you can use npm as you normally would.
you can also take the token from `bit config` and use it.

the docs about setting up a CI with Bit dives into all details - https://docs.bit.dev/docs/ci#config-npmrc-on-ci
