### ISSUE TITLE
typo on https://bit.dev/

### ISSUE THREAD

**Issue by rg3h** [teambit/bit#2437]
### Describe the bug

on https://bit.dev/ the big font hero text says:
Build better UI through indepdenent components

should be "independent"

### Steps to Reproduce

1. go to https://bit.dev/
2. look at the hero text: Build better UI through indepdenent components

### Expected Behavior
should say:  Build better UI through independent components

### Screenshots, exceptions and logs

![bitdev](https://user-images.githubusercontent.com/3879874/76251695-b5572580-6204-11ea-8ee4-9ccebbfde85c.jpg)

### Additional context
on chrome, 8 March 2020

**Comment by rg3h** [comment]
Looks like Itay is pushing a fix. I will close this.

**Comment by itaymendel** [comment]
ohhh a deployment didn't help, it was an a/b test. need to find my credentials to that app and fix it.
