### ISSUE TITLE
Throws 404 Could not found when try to install component

### ISSUE THREAD

**Issue by Poorva17** [teambit/bit#2438]
### Steps to Reproduce
I am trying to install table component from material. I searched it on bit.dev and did 
```npm i @bit/mui-org.material-ui.table```  as suggested on https://bit.dev/mui-org/material-ui/table page. 

### Expected Behavior
It should install component in my react app.

### Actual Behavior
But it is throwing 404 not found error.
I am attaching screenshot for reference.

<img width="1192" alt="Screenshot 2020-03-10 at 6 40 37 PM" src="https://user-images.githubusercontent.com/13188905/76315895-9b4e3d80-62ff-11ea-96c6-d7142b4a45c2.png">

Note: - I also tried installing with `yarn` it is giving same problem. 

Am I missing something here?

**Comment by itaymendel** [comment]
Hi,

Please search in Bit's documentation and existing GitHub issues before submitting new bugs. Anyway, here's the [doc](https://docs.bit.dev/docs/ci#unauthorized-401-when-installing-a-component) you need.

Basically it requires you to configure your `.npmrc` with the `@bit` component registry to be able to install components.

**Comment by Poorva17** [comment]
Hello @itaymendel , Thanks for pointing this out.

I need to run - `npm config set '@bit:registry' https://node.bit.dev` to configure bit in npmrc. This solved my problem.
