### ISSUE TITLE
[docs] Developing extension section went wrong

### ISSUE THREAD

**Issue by miunaliang** [teambit/bit#2447]
I'm working on a custom extension after reading docs, but something is wrong for v14.7.6

```
const triggerHook;

const Pack = {
  getDynamicConfig: (rawConfig, dynamicConfig) => {
    return Object.assign({}, rawConfig, { dynamicConfigKey: 'dynamicConfigVal' })
  },

  init: (rawConfig, dynamicConfig, api) => {
    api.registerActionToHook('post-tag', {name: 'packAction', run: packAction});
    api.registerNewHook('post-pack');
    triggerHook = api.triggerHook;
  }
};

const packAction = (args, headers) => {
  // pack action code here, and then...
  // ...
  // ...
  triggerHook('post-pack', {arg: 'myArgs'});
}
```

in this example, `getDynamicConfig` and `init` function accept 2 - 3 parameters, but in the source code only an Object passes to function, it should have a update

**Comment by davidfirst** [comment]
Thanks @miunaliang , for letting us know.

We're currently working on a much better way to support extension, so this syntax might be deprecated. @GiladShoham , are we going to continue to support this API?

**Comment by GiladShoham** [comment]
I'm not sure if we will support this API or not. and what exactly inside.
Anyway, once we will publish the new version, we will write new comprehensive docs for the new API.
@miunaliang It's better to wait a bit more and use the new API.

**Comment by GiladShoham** [comment]
closing this, since we are not going to update the old API docs.
