### ISSUE TITLE
extension loading process

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2455]
This issue is a task list for many tasks required for proper extensions loading.

This is related to some of the tasks in issue: #2456 

## checklist
below you can find more details for some of the tasks

### implementation 
- [x] Move workspace extensions loading to be part of workspace extension instead of bit extensions
- [x] Load workspace extension according to workspace config
- [ ] Load component extensions during component loading
   - [x] during loading from workspace / fs
   - [ ] during loading from scope
- [x] load extension recursively (if extension added another extension)
- [ ] import missing extensions of a component when importing the component
- [ ] import missing extensions when check out a version of the component
- [ ] import extensions if they are missing during loading (workspace or components)
- [ ] load extension from scope even if they doesn't exist in the workspace

### tests
- [ ] make sure all old tests are pass

## details
- when importing missing extensions they should just be imported to the scope not to the workspace
- load extension recursively - when loading recursively make sure:
  - we load the added config from nested extensions
  - we store dependencies (include extension as dependencies) from nested extensions in models

**Comment by itaymendel** [comment]
irrelevant
