### ISSUE TITLE
component gets modified after bit import

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2465]
I just imported a component to my local scope, and it is immediately modified:
<img width="590" alt="Screen Shot 2020-03-17 at 13 47 52" src="https://user-images.githubusercontent.com/5400361/76853638-5c1b7180-6856-11ea-8aa9-dedfba81e105.png">

I am guessing this is happening because of global overrides at my project.
If that so, I can't explain these anomalies: 
* dependency `bit.web/themes/sizes@0.0.3` is just removed.
* Compiler `bit.envs/compilers/react-typescript@3.1.43` is not applied. (instead, `bit show` says that compiler `bit.web/compilers/react-flow@0.0.5`  is used)
* Weird override for react and react-dom: `[ react@-, react-dom@- ]`.
Then again, they are missing from regular dependencies? `[ classnames@^2.2.5, lodash.debounce@^4.0.8, react-slick@^0.25.2, resize-observer-polyfill@^1.5.1 ]`

```json
"overrides": {
	"*": {
		"dependencies": {
			"react": "-",
			"react-dom": "-"
		},
		"devDependencies": {
			"@types/chai": "^4.2.8",
			"@types/sinon": "^7.5.1",
			"chai": "^4.2.0",
			"eslint-plugin-chai-friendly": "^0.5.0",
			"sinon": "^8.1.1",
			"@types/mocha": "^7.0.1"
		},
		"env": {
			"compiler": {
				"bit.envs/compilers/react-typescript@3.1.43": {
					"rawConfig": {
						"tsconfig": {
							"compilerOptions": {
								"target": "ES5",
								"module": "CommonJS"
							}
						}
					}
				}
			}
		}
	}
}
```

### Specifications

- Bit version: 14.7.6
- Node version: 12.12
- npm / yarn version: 1.22.0
- Platform: macos

**Comment by davidfirst** [comment]
@KutnerUri , is this still an issue? what component should I import to reproduce this?

**Comment by KutnerUri** [comment]
yes still happening. Use this component:
```
bit.web/components/comment-carousel
```

again, I believe it's happening because of global overrides.

**Comment by itaymendel** [comment]
irrelevant for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
