### ISSUE TITLE
bulk operations for bit build

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2472]
Most bit commands support bulk operations. For example:
```
> bit tag atoms/*
```

However this is not available for `bit build`:
```
> bit build atoms/*
error: component "atoms/*" was not found on your local workspace.
```

Please support this feature for build, it is so useful when dealing with a lot (10<) of components

### Additional context
bit version: 14.7.6

**Comment by GiladShoham** [comment]
@qballer will this be supported by the new run command?

**Comment by itaymendel** [comment]
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
