### ISSUE TITLE
incorrect scope in dists before export

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2473]
I'm working on a project with 2 scopes: `bit.base` and `bit.evangelist`.
Components from `bit.evangelist` depend on each other, and on `bit.base`.

```tsx
// at src/pages/hybrid-homepage/hybrid-homepage.tsx
// (bit.evangelist/pages/hybrid-homepage)

...
import { centerColumn, wideColumn } from '../../components/layout/page-frame';
import { AutoDocs } from '../../sections/auto-docs';
```

When building, bit generates links with npm-id between them like so:
```
// at dist/layout/page-frame.js
// ...
var bit_base_layout_page-frame1 = require("@bit/bit.base.layout.page-frame");
exports.centerColumn = bit_base_layout_page-frame1.centerColumn;
exports.wideColumn = bit_base_layout_page-frame1.wideColumn;
```

```
// at dist/sections/auto-docs.js
// ...
var bit_base_sections_auto_docs_1 = require("@bit/bit.base.sections.auto-docs");
exports.AutoDocs = bit_base_sections_auto_docs_1.AutoDocs;
```

(why doesn't it just let exports pass through, like `exports = require("...")`  ?)

I expect the link to `sections/auto-docs` to point to:
`@bit/bit.base.sections.auto-docs`,
while actually it points to:
`@bit/bit.evangelist.sections.auto-docs`

I believe this happens because _build_ and _tag_ happen before _export_. During build time, Bit has no way to know what will be the correct scope for these components, so it uses the `defaultScope` from package.json (what happens when defaultScope is undefined? 🤔)

### solution
It seems that links should be updated on _export_, as this is the only time when the scope name is known.

Actually, we have the `--rewire` flag on bit export.
Currently it's not suitable, since it requires `--include-dependencies` which will export all of _bit.base_ to _bit.evangelist_.

#### Workaround 1:
After exporting all of the components to their correct scopes, I modified all of the components in `bit.evangelist` and then (very slowly) retagged them all. This time links pointed to the correct scope.

I tried to achieve the same results with `bit build --no-cache` and then `bit tag -a --force`, but `-a` only tags modified components. (plus I'm pretty sure that the results of `bit build` are not used when tagging)

#### Workaround 2:
@davidfirst suggested replacing all relative links with npm-id links.
(this kinda means I need to run `bit build` and `bit link` every time I make a change which will take forever).
This will have the same problem, since before exporting components still don't have an npm-id, but should work after first export.

### Specifications

- Bit version: 14.7.6

**Comment by davidfirst** [comment]
@KutnerUri , when you have defaultScope, the links generated in the dists use that scope (which makes sense). If you don't have defaultScope, it'll use the npm id without any scope.
Then, upon export, if you don't use `--rewire`, it'll stop and let you know that your components are not going to work anywhere else.
The `--rewire` flag on export is what you need because only at that point you know what the scope a component belongs to.
I see what you're saying about the `--include-dependencies` flag, which makes sense for a fork, not for a rewire of no-scope to a scope. We might need a new flag here.

**Comment by KutnerUri** [comment]
like `--rewire-no-scope`? and maybe turn it on be default?
maybe `--skip-auto-rewire`

**Comment by itaymendel** [comment]
resolved in v15
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
