### ISSUE TITLE
"Segmentation fault" message after installing on Ubuntu

### ISSUE THREAD

**Issue by fobabs** [teambit/bit#2478]
### Steps to Reproduce

1. Run  `npm install bit-bin --global` in terminal
2. Then input `bit --version`
3. Displays "segmentation fault" message afterwards
4. Also, input any npm command like `npm install` or `npm -v`
5. Displays "segmentation fault" message

I've tried every possible means to fix this but no success. It is currently hindering me from using the `npx` command to install packages for my projects.

### Specifications

- Bit version: 14.7.6
- Node version: 13.11.0
- npm / yarn version: 6.14.2
- Platform: Ubuntu 18.04.4
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

If you need more information, kindly let me know.

**Comment by itaymendel** [comment]
Hi @fobabs if any npm command returns a segmentation fault error, this is not a bit-related issue. perhaps there was an issue in installing nodejs on your ubuntu machine.

**Comment by fobabs** [comment]
I already have node.js installed long before installing bit. I noticed this error after installing bit.

**Comment by fobabs** [comment]
I've actually discovered where the problem is. It's a node version issue.
Node 13.11.0 is still buggy.
