### ISSUE TITLE
"bit test" hangs when tests fail

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2480]
I have a component with failing tests.

`bit tag --skip-auto-tag --verbose atom/eva-button` consistently fails, while `bit test atom/eva-button` just hangs:
(I terminated it with ctrl+c)
<img width="283" alt="Screen Shot 2020-03-22 at 11 42 19" src="https://user-images.githubusercontent.com/5400361/77246782-2b12b680-6c33-11ea-8c3b-04449359385d.png">

Eventually, I got tests to pass with some `bit built ... --no-cache` and `bit link`. But the `bit test` command should be more useful than that.

### Specifications

- Bit version: 14.7.6
- Node version: 12.12
- npm / yarn version: 1.22.0
- Platform: MacOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43
- Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by davidfirst** [comment]
This is probably a result of "stderr" coming from the compiler that for some reason is ignored in bit-bin.
Not sure if it worths looking into it because in Harmony the implementation of the bit-test will be different.

**Comment by itaymendel** [comment]
resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
