### ISSUE TITLE
component found in index.json file, but is missing from the scope

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2482]
I'm getting this error:

> component bit.evangelist/atom/testimonial found in the index.json file, however, is missing from the scope. to get the file rebuild, please delete it at "/Users/kutner/Documents/Projects/pages/eva-homepage/.git/bit/index.json". This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues

I believe it happened when I canceled a `bit export` (using ctrl+c).
Is there any automated way to handle this?

I am going to edit the index.json file an hopefully continue work.
@davidfirst - zip is coming your way!

### Specifications

- Bit version: 14.7.6
- Node version: 12.12
- npm / yarn version: 1.22
- Platform: MacOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43
- Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by KutnerUri** [comment]
editing the index.json didn't work (there were more problematic components)

I ended up running `bit init --reset`  and retagging my components

**Comment by davidfirst** [comment]
The PR above makes sure to delete the `index.json` file in such a case.
