### ISSUE TITLE
error "failed adding or updating a .bitmap record"

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2484]
I am trying to align folder structure of components to their namespaces, so I try to run:

```bash
bit mv src/components/base src/base/atoms
```
and get this error:
> failed adding or updating a .bitmap record of bit.base/atoms/button@1.0.4. a file path src/base/atoms/button/button.module.scss is not in the trackDir src/components/base/button
This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues

🤷‍♂ 

@davidfirst zip coming your way 😄 

### Specifications

- Bit version: 14.7.6
- Node version: 12.122
- npm / yarn version: 1.22.0

**Comment by ranm8** [comment]
@davidfirst any idea re root cause of this issue?

**Comment by davidfirst** [comment]
@ranm8 , once I started working on it I realized that this error is related to the trackDir, which is going to be replaced by rootDir. Please let me know if it makes sense for you to invest time in this task.

**Comment by krislao** [comment]
also encountered this error when aligning folder structure of my components. do we have a resolution or a work-around to fix this?

**Comment by GiladShoham** [comment]
@davidfirst Do we have a workaround for this until harmony is released?

**Comment by davidfirst** [comment]
@GiladShoham , not that I'm aware of.
Also, because of changed the strategy to support `trackDir` for legacy workspace, this needs to be fixed.

**Comment by GiladShoham** [comment]
@davidfirst then let's fix it :)

**Comment by davidfirst** [comment]
@GiladShoham . Sure. I prefer to do it after the release so avoid fixing conflicts between prod and master. Also, the priority is probably not critical as it won't happen on Harmony.

**Comment by GiladShoham** [comment]
Sure. If you want you can fix it only on master to avoid conflicts. No reason to fix it on prod.

**Comment by itaymendel** [comment]
irrelevant for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
