### ISSUE TITLE
how to set language mode in @examples?

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2488]
I have a component with the following jsdocs:

```tsx
/**
 * Provides constant url for images CDN.
 * @example
 * //in ts/js file:
 * <image src={staticStorageUrl + '/some/image.png'}/>
 * @example
 * //in scss file:
 * background-image: url($staticStorageUrl + '/some/image.svg');
 */
```

I want to highlight the second example as scss (or have no highlighting at all) but it automatically shows up as js at bit.dev:
<img width="545" alt="Screen Shot 2020-03-24 at 20 22 52" src="https://user-images.githubusercontent.com/5400361/77462778-420d0080-6e0d-11ea-9e4d-6adeb35af6b4.png">

### Specifications

- Bit version: 14.7.4

**Comment by davidfirst** [comment]
@KutnerUri , In the JSDoc I don't see an option to mark an `@example` as js/ts/scss. I guess this is something that needs to be done on bit.dev side, so maybe you know better about this task :)

**Comment by itaymendel** [comment]
irrelevant for v15, as playground is now local

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
