### ISSUE TITLE
How to realize the authority function of bit

### ISSUE THREAD

**Issue by LeonYanghaha** [teambit/bit#2492]
I use BIT to build my own bit serve. I want to give different users different operation rights, such as Tom import component, which can't be export. Jack can only use a part of the components. I want to achieve this function, but I don't see the relevant documents or demo. Who can give me some guidance or ideas? Thank you

**Comment by itaymendel** [comment]
Hi,

Bit uses SSH as its communication protocol, as it supports authentication and authorization. This means that when you set your Bit server and configuring the users that should be able to connect to it, you can configure them in user-groups, and set read/write permissions to these groups on the Bit directory. This way when they trigger any Bit command, and Bit initiates a connection with the remote server - the SSH daemon will fail the export command in case they don't have permissions.

What we do on bit.dev is set up our own servers that listens on port 22 and supports the SSH protocol, so we do authentication check programmatically on our database, and then issue the command to the remote Bit server.

**Comment by LeonYanghaha** [comment]
Your answer is great. Thank you very much.
