### ISSUE TITLE
bulk operations for bit eject

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2495]
Hey, I'm trying to eject some of the components in my repository, but the command does not seem to support wildcards:

```
❯ bit eject bit.gui/* --force          
error: component "bit.gui/*" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)
```

please support bulk operations for `bit eject` :smiley:

**Comment by davidfirst** [comment]
That's correct. This command doesn't support wildcards. We'll implement it.

**Comment by itaymendel** [comment]
implemented.
