### ISSUE TITLE
error on 'pretty-format' when building

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2498]
I am getting this error while building.
Since I don't use prettyFormat, I'm guessing this is a compiler / bit issue.

Any idea what it is? 

```
❯ bit tag --skip-auto-tag -v atom/static-image 
⢀⠀ importing components
writing config files to /Users/kutner/Documents/Projects/pages/eva-homepage/src/components/concrete/image/.bitTmp
⢋⠠ isolating component - atom/static-imagenode_modules/pretty-format/build/index.d.ts:7:13 - error TS1005: '=' expected.

7 import type * as PrettyFormat from './types';
              ~

node_modules/pretty-format/build/index.d.ts:7:18 - error TS1005: ';' expected.

7 import type * as PrettyFormat from './types';
                   ~~~~~~~~~~~~

node_modules/pretty-format/build/index.d.ts:7:31 - error TS1005: ';' expected.

7 import type * as PrettyFormat from './types';
                                ~~~~

node_modules/pretty-format/build/index.d.ts:7:36 - error TS1005: ';' expected.

7 import type * as PrettyFormat from './types';
                                     ~~~~~~~~~


Found 4 errors.
```

### Specifications

- Bit version: 14.7.6
- Node version: 12.12
- npm / yarn version: 1.22.0
- Platform: MacOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.43
- Bit tester (include version): bit.envs/testers/mocha@5.0.2

**Comment by KutnerUri** [comment]
Going to plow through or around it.

Just in case, here is a zip of the workdir: [snapshots](https://drive.google.com/open?id=1z9GgBOEafZ2QpJUtmJg4CQlr9R43hLG_)
See snapshot '26.03'

good thing it is open source project 😁

**Comment by GiladShoham** [comment]
We will check it. thanks.

**Comment by erichochhalter** [comment]
I encountered exactly this error in my project as well.

FWIW, I found relief by carefully peeling out files and lines of code until the component build worked, then slowly building the component's files back together to its original state, with tweaks to keep it building. I got my components building again. I don't feel I got to fully understanding the problem, though.

In my project, the problem had to do with module imports. 
If I had imports in one order, it worked; if in a different order, it would not build and gave the error above (TS1005, node_modules/pretty-format).

My project uses Styled Components and Jest and (React) Testing Library.
The import lines that seemed to matter were these:
```
import React from "react";
import { prettyDOM, render, screen } from "@testing-library/react";
import "@testing-library/jest-dom/extend-expect";
import "jest-styled-components";
```
They had to be in **this order**. If Testing Library appeared below `jest-styled-components`, it would not build, for example.
…perhaps it has something to do with the two non-named imports? Wild guess.

If I learn anything more, I'll chime in again.

Bit version: 14.8.8
Node version: 12.13.1
npm / yarn version: 1.22.4
Platform: MacOS
Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.40
Bit tester (include version): bit.envs/testers/jest@22.4.3

tsconfig in package.json:
```
"tsconfig": {
  "compilerOptions": {
    "target": "ES5",
    "module": "CommonJS",
    "types": ["jest", "node"]
  }
}
```

**Comment by jackguoAtJogg** [comment]
I found this error has to do with jest, if you are running jest this error would show up. I got rid off test files and jest dependencies and everything built fine.

**Comment by itaymendel** [comment]
resolved with v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Comment by yuanalexwu** [comment]
Solved by adding this in `package.json`:

```json
{
  "resolutions": {
    "**/pretty-format": "25.1.0"
  }
}
```

**Comment by shvkumar7777** [comment]
this is not resolving my problem, here is how I have done 

 ,
  "resolutions": {
    "**/pretty-format": "25.1.0"
  }
