### ISSUE TITLE
 bit remote add SSH....  didn't respond after running the command

### ISSUE THREAD

**Issue by LeonYanghaha** [teambit/bit#2499]
I have built my bit serve, created user bit and bit-global.  Add public SSH key to the authorized_keys list of the user bit and bit-global，Now I can use bit to import / export operations. Everything is OK, but when I execute the command ``` bit remote add SSH: / / bit-global @ 123.**.*: / opt / bit / global```, the terminal never moves, just like the screenshot. Then I went to the home directory of bit-global and looked at the log. There was nothing in files ```debug.log```and ``` exceptions.log```.I don't know what's wrong. Who can tell me? Thank you.

- Bit version:14.7.6
- Node version:10.16.0
- npm  version:6.9.0
- bit serve Platform: Ubuntu 16.04.6 LTS
- bit client Platform: macOS

**Comment by LeonYanghaha** [comment]
Why can't my picture upload, oh. Too bad

**Comment by itaymendel** [comment]
v15 is moving away from ssh to https, so closing this issue

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
