### ISSUE TITLE
error: scope was not found ..

### ISSUE THREAD

**Issue by LeonYanghaha** [teambit/bit#2502]
In my bit server, I created a scope with the account bit, and then import / export is OK, but when I execute the command  ``` bit remote add ssh://root@123******:/opt/bit/scope``` with the account root, there is an error ``` error: remote scope "/opt/bit/scope" was not found. ``` Why? Account authority? How should I solve this problem? Who can tell me, thank you

**Comment by davidfirst** [comment]
@LeonYanghaha , did you run `bit init --bare` on `/opt/bit/scope`?

**Comment by LeonYanghaha** [comment]
It's OK to run the init command and use the account bit to link, but an error occurs when using the account root @davidfirst

**Comment by GiladShoham** [comment]
@LeonYanghaha when running the `bit init --bare` on the server you can try using 
`-s, --shared <groupname>                     add group write permissions to a scope properly`
to make sure you have proper permissions.
That sounds like some Linux permission issue.

**Comment by personaaleatoria** [comment]
Having the same issue. I have run `$ bit init --bare -s <linux_user_groupname bitdev>` but the client still fails to add remote:

```
$ bit remote add ssh://bitdev@<server_ip>:<ssh_port>:/opt/bit/first-scope
error: remote scope "/opt/bit/first-scope" was not found.
```

Directory permissions in the server are (/opt/bit/first-scope):

```
drwxrwxr-x 5 bitdev bitdev 4096 sept. 10 12:54 .
drwxrwxr-x 3 bitdev bitdev 4096 sept. 10 12:54 ..
drwxrwxr-x 2 bitdev bitdev 4096 sept. 10 12:54 components
drwxrwxr-x 2 bitdev bitdev 4096 sept. 10 12:54 objects
-rw-rw-r-- 1 bitdev bitdev   73 sept. 10 12:54 scope.json
drwxrwxr-x 2 bitdev bitdev 4096 sept. 10 12:54 tmp
```

**Comment by itaymendel** [comment]
v15 is moving from ssh to https, closing this issue

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
