### ISSUE TITLE
.bitmap is rewritten in different order but should be idempotent

### ISSUE THREAD

**Issue by stephan-devop** [teambit/bit#2503]
I use [takelage-cli](https://github.com/geospin-takelage/takelage-cli) to *tau copy* (*bit add*, *bit tag* and *bit export*), *tau paste* (*bit import*), *tau push* (*bit export*) and *tau pull* (*bit import*) directories. When I *tau copy* a directory and directly afterwards *tau pull* then the order in the .bitmap file changes and the git worktree is dirty.

The command *bit import --skip-update --ignore-package-json -m manual* should be idempotent.

I am using Bit version: 14.7.6

Please tell me if I should create a minimal bit-only example to reproduce the bug.

Here is the problem as a git diff output:

```bash
$ git diff
diff --git a/.bitmap b/.bitmap
index f9f290d..888a3c2 100644
--- a/.bitmap
+++ b/.bitmap
@@ -4,14 +4,14 @@
     "takelage.rake/rake/meta@0.0.1": {
         "files": [
             {
+                "name": "README.bit",
                 "relativePath": "rake/meta/README.bit",
-                "test": false,
-                "name": "README.bit"
+                "test": false
             },
             {
+                "name": "Rakefile",
                 "relativePath": "rake/meta/Rakefile",
-                "test": false,
-                "name": "Rakefile"
+                "test": false
             }
         ],
         "mainFile": "rake/meta/README.bit",
```

**Comment by davidfirst** [comment]
@stephan-geospin , thanks for reporting the issue. No need to provide an example. 
In a matter of fact, I have noticed this issue myself. We'll look into this and update the issue accordingly.

**Comment by JGJP** [comment]
Has there been progress on this issue? When a project has a lot of bit components it's quite tedious to check the .bitmap file diff

**Comment by davidfirst** [comment]
@JGJP , not yet. I'm sorry for the inconvenience. I hope to get into this soon.
