### ISSUE TITLE
Default component-module names

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2506]
While when tracking a new component, Bit sets an `id` for each of them, the ID is lacking the remote name, so it is impossible to require and use it prior to `export`. This makes the experience of starting using a new component to an incomplete and inconsistent one.

### Forcing `defaultScope`

Normally the full component-ID is defined only after the initial component export. There's another option of using the `defaultScope` optional workspace configuration key. So as an initial change, Bit should make this parameter to be mandatory when creating a new workspace.

> It is still possible to use `bit export <socpe> [<component>...]` to export a component to the non-default scope.

### Removing `@bit/` scope name

In Bit, each component is scoped with `@bit`. This is not a proper scope for teams' components, as it does not have any business value and is only there to distinguish Bit-components from any other package. While at the beginning we thought it to be a proper solution, we see that forcing developers to `import '@bit/...` makes little sense.

### Scoped Owners (bit.dev)

For projects aimed to share components to bit.dev we should use the account-name as the scope-name, as all components are logically grouped together this way. This way teams also get a single scoped-registry for all components, similar to GitHub's implementation of their node package registry.

To allow Bit to generate the component module name properly, Bit should support an optional `owner` property in the workspace configuration. If this is defined, new components will have this

> **Note** - this should be supported in bit.dev's component-registry as well.

### Component module name and link generation

Bit should generate links to non-exported components according to their `defaultScope` and `owner`.

- If both not defined, prompt an error asking user to define a `defaultScope` on `bit add`.
- If `defaultScope` defined, use it as a link prefix - `@<defaultScope>/<component>`.
- If `defaultScope` and `owner` defined, both as a prefix - `@<owner>/<defaultScope>.<component>`.

### npmrc management

Given that it's likely that users have components from different owners, so we need to have better `.npmrc` management, to ease the life of users that keep using npm/yarn to install components.

Given that npm concats all `.npmrc` files, we can use it to split the authentication part and the definition part of the scoped-registry configuration.

Bit should keep a `.npmrc` file in the workspace with all the scoped registries it needs:

```
@owner1:registry=https://owner1.node.bit.dev/
@owner2:registry=https://owner2.node.bit.dev/
@owner3:registry=https://owner3.node.bit.dev/
```

Then it'll keep a configuration in the user's `.npmrc` file with the correlating tokens:

```
owner1.node.bit.dev/:_authToken=<token does here>
owner2.node.bit.dev/:_authToken=<token does here>
owner3.node.bit.dev/:_authToken=<token does here>
```

> Another option is to use [npm's env vars]( https://docs.npmjs.com/misc/config#environment-variables) and configure `NPM_CONFIG_BIT_TOKEN` while running `bit login`, and tell npm to use it in the workspace `.npmrc` file.

### Installing Components

- When Bit runs `import` or `install` it should update the workspace `.npmrc` file, to make sure that next time when a user runs an `npm` or `yarn` command, they'll get the most correct data.
- `bit install` should work when there's no `.npmrc` file for the project at all, as it can get the information from Bit's database.
- `bit install` should try and fetch components from the Bit scoped owners before looking for the dependencies in npmjs.org.

**Comment by GiladShoham** [comment]
@itaymendel I think the registry urls can be just node.bit.dev for all owners. No need to prefixed with the owner name.
So owner:registry=node.bit.dev should be enough I think.

**Comment by davidfirst** [comment]
One more good reason to force the `defaultScope`:
Say, you want to create a new compiler. You configure your workspace with `compiler: { compile: my-compiler }`, this id won't be valid after export. The valid id is now scope/my-compiler.

Currently, that `defaultScope` is not enforced and so upon export Bit changes all dependencies from no-scope to the new scope. However, with extensions, it's more complex. We don't know what to change because we can't predict where 3rd party extensions place other extension-ids.

**Comment by itaymendel** [comment]
implemented for v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
