### ISSUE TITLE
`bit new` command to create a new Bit project based workspace

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2509]
`bit-new` - Generate a Bit workspace.

The `bit new` command creates a new workspace as a boilerplate for a component-based project. A simple workspace looks like this:

```sh
.
├── README.md
├── bit.jsonc
├── components
│   └── hello-world
│       ├── hello-world.ts
│       └── index.js
└── package.json
```

## Using templates for projects

Bit should support `templates` for different projects. When generating a workspace using a template, the template should either ask questions or have sane defaults. This way it will generate the proper configuration for the `bit.json` and `package.json` files, alongside compiler configuration or any other extension.
Additionally, Bit inits a new Git repository for the workspace and generates the initial commit, with the base contents of the generated workspace.

### Example template for a React Component Library template

```sh
? Check the type system for your project: (use arrow keys)
> TypeScript
  Flow
  None

? Which stylesheet format would you like to use? (Use arrow keys)
> CSS
  SCSS
  Sass
  Less
  Stylus
  StyledComponents
  Emotion

? Check the linter / formatter for your project: (use arrow keys)
> ES-lint
  Prettier
  None

# If es-lint selected
? Pick a linter config
> Airbnb config
  Standart config

? Check the testing system for your project: (use arrow keys)
> Jest
  Mocha
  Karma
  None
```

## README.md for new projects

To simplify the onboarding process for Bit, a new project should have a through `README.md` file autogenerated according to the template. This way it will be much easier for developers onboarding to Bit to learn how to operate and which commands they should start using.

## Output for generating a new Bit workspace

```
Creating Bit workspace in <path to project + / + project name>
Initializing git repository and hooks
Configuring dependencies, peerDependencies, and devDependencies
Generating README.md.
Generating base components <theme>, <button> and <...>
Installing dependencies and plugins. This might take a while...

# output for npm-i / yarn-i

Created git commit.
Successfully created project <project name>
Inside <project name> directory, you can run several commands:

  - bit start
      Starts the development server.

  - bit create <component>
      Scaffold a new component for the library.

  - bit tag
      Tag a new version for modified components.

  - bit export
      Publish components to a remote Bit server

See the Getting Started guide for the here:
<link>
```

## Synopsis

```bash
$ bit new <workspace name> [--template | -t = <path to template>] [--force | -f] [--help | -h] [--package-manager | -p] [--skip-git | -g] [--skip-install] [--skip-readme] [--verbose | -v] [--default-scope | -d] [--dry-run] [--commit | -c] [--owner | -o]
```

#### `workspace name`

The name of the new workspace and initial project. Should be defined as the `defaultScope`, if not defined.

#### `--template`

Set a workspace according to a template using a template's component ID.

#### `--force`

When true, forces overwriting of existing files.

#### `--package-manager`

The package manager used to install dependencies.

#### `--skip-git`

When true, does not initialize a git repository.

#### `--skip-readme`

When true, does not initialize a git repository.

#### `--skip-install`

When true, does not install dependencies.

#### `--default-scope`

The remote scope name used to export components.

#### `--owner`

Owner name in bit.dev to configure `owner`.

#### `--dry-run`

When true, runs through and reports activity without writing out results on the disk.

#### `--commit`

Initial git repository commit content.

**Comment by ranm8** [comment]
thanks @itaymendel, I believe we need the interactive flow as well. Means prompting lists of of options for each option: e.g. TS vs Babel, Mocha vs Jest, etc.

**Comment by itaymendel** [comment]
I don’t this it’s part of the ‘new’ command, but rather a part of the template, no?

**Comment by ranm8** [comment]
I think the `new` command infrastructure should provide an API to allow the experience for templates. 
Can we design an API for that?

**Comment by itaymendel** [comment]
need to rethinkg for v15

closing for now
