### ISSUE TITLE
autodocs should show relevant data only

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2510]
When tagging a component, it seems that the first props with JSdocs get used as documentation.

You can see it in this component,  [Highlghter@2.0.0](https://bit.dev/bit/evangelist/atom/component-highlighter?version=2.0.0):
<img width="1018" alt="Screen Shot 2020-03-29 at 12 30 00" src="https://user-images.githubusercontent.com/5400361/77845629-11d0b380-71b9-11ea-8711-7b346e3bae3a.png">

The component is built like so:
```bash
index.ts
component-highlighter.tsx
content-type.ts

# sub components: 
ref-tooltip/
overlay-border/
component-label/
```

I am expecting to see the props and docs from `component-highlighter.tsx` (active, versionMap, blacklist), but instead I'm getting the props of `component-label.tsx` (bitId, versionOverride).

It seems automatic docs present the first `type`/jsdocs they find, leaving little control to the user.

Ideally, I would like to:
* See **all of the exports** from the component, and all their types.
* **Avoid 'private'** code, ie. code not exported from the index file.
* Improve **support for names**. (should appear at bit.dev)
* Some way to **control the grouping and order** of the docs.
* Show docs from current file, before showing dependencies. (BFS?)

For example, I expect this:
```tsx
type catProps = {
  /**
   * name of the cat
   */
  bob: string;
}

/**
 * First docs section.
 * 
 * Sed a risus id arcu fermentum malesuada.
 * Mauris bibendum risus id feugiat porta. Mauris et massa 
 */ 
export function Cat(props: catProps){
  return <div>tail <Purr/> head</div>
}

type dogProps = {
  /** 
   * Something the dog could do
   */
  trick: string;
}

/**
 * Much component, good for owner
 */
export function Dog(props: dogProps) {
  return <button>do the {props.trick}</button>
}

/**
 * x this function is not public, so should not be documented!
 */
function Purr() {
  return <div>meeoww</div>
}
```

to be documented as:
```markdown
## Cat `function`
First docs section.
 
Sed a risus id arcu fermentum malesuada.
Mauris bibendum risus id feugiat porta. Mauris et massa 

Properties:
---|---|---
bob|string|name of the cat

## Dog `function`
Much component, good for owner

Properties:
---|---|---
trick|string|Something the dog could do
```

### Specifications

- Bit version: 14.7.6
- Node version: 12.12

**Comment by davidfirst** [comment]
@KutnerUri , about the first two:

> See all of the exports from the component, and all their types

I guess this is about React. If so, I believe the latest dev version supports it already.


> Avoid 'private' code, ie. code not exported from the index file

I didn't check, but there is a good chance that you can get the same result by adding `@private` or `@access: private` in the JSDocs. (at least, it gets parsed in bit-bin and it can be used on bit.dev).

**Comment by KutnerUri** [comment]
I'm trying to debug react-docgen. No success with `@ignore`, `@private`, `@access: private` and `@access private`. In fact, it seems react-docgen ignores all `@` operators.
Huh, I see we even have a `extractDataRegex()` method specifically for `@example`.

Maybe we should apply the same logic for all properties, and drop properties with `@ignore`?

I do see these useful options: 
* **Filename** (under options). Docgen will detect the ts suffix and parse the file with Typescript instead of flowType. This should at least solve the errors about `private`, and maybe even `interface`.  
_Note_ (!) that details will be outputted as `tsType`, instead of `flowType`.
* **Resolvers**. I think we should use the `findAllExportedComponentDefinitions` resolver, which allows multi-export but at leasts skips the local components.
* No recursive option. At `_getDocsForFiles()`, we simply run docsgen per file in the component, so I don't see a way to tell which exports are internal.  😞

**Comment by KutnerUri** [comment]
OK, what I see in the API is that docs are groupped by exports, and properties come in a single group:
```json
"properties": [
	{
		"name": "className",
		"description": "",
		"required": true,
		"type": "literal"
	},
	{
		"name": "clause",
		"description": "",
		"required": true,
		"type": "literal"
	}
],
"docs": [
	{
		"filePath": "src/comp/comp.tsx",
		"name": "CoolCat",
		"description": "A cat which is cool",
		"access": "public",
		"examples": [
			{
				"raw": "<div>\n<div>\n<Bob/>\n</div>\n<CoolCat/>\n</div>",
				"code": "<div>\n<div>\n<Bob/>\n</div>\n<CoolCat/>\n</div>"
			}
		]
	},
	{
		"filePath": "src/comp/sub-comp.tsx",
		"name": "BobCat",
		"description": "A cat which is cool",
		"access": "public",
		"examples": [
			{
				"raw": "<div>hello world</div>",
				"code": "<div>hello world</div>"
			}
		]
	}
],
```

Actually, `bit show --json` already splits props correctly:
```json
"docs": [
    {
      "filePath": "src/comp/comp.tsx",
      "name": "CoolCat",
      "description": "A cat which is cool",
      "properties": [
        {
          "name": "className",
          "description": "",
          "required": true,
          "type": "literal"
        }
      ],
      "access": "public",
      "methods": [],
      "args": [],
      "examples": [
        {
          "raw": "<div>\n<div>\n<Bob/>\n</div>\n<CoolCat/>\n</div>",
          "code": "<div>\n<div>\n<Bob/>\n</div>\n<CoolCat/>\n</div>"
        }
      ]
    },
    {
      "filePath": "src/comp/sub-comp.tsx",
      "name": "BobCat",
      "description": "A cat which is cool",
      "properties": [
        {
          "name": "clause",
          "description": "",
          "required": true,
          "type": "literal"
        }
      ],
      "access": "public",
      "methods": [],
      "args": [],
      "examples": [
        {
          "raw": "<div>hello world</div>",
          "code": "<div>hello world</div>"
        }
      ]
    }
  ],
```

Why doesn't this comes through the API?

**Comment by GiladShoham** [comment]
@KutnerUri regarding the API, it's an issue for the backend @amitgilad3 or @guysaar223 are the address.
regarding private, it's currently hardcoded I see. If you can make it work with the [react-docgen playground ](https://reactcommunity.org/react-docgen/) we can make it work in bit.
just post here a working example.

**Comment by KutnerUri** [comment]
@GiladShoham - it's not an API problem, I managed to reproduce it locally: https://bit.dev/kutner/temp/docstest

do you want me to open a PR with findAllExportedComponentDefinitions and filename?

**Comment by GiladShoham** [comment]
What does bit show -j show for this component and what it should?
What do you mean by this pr?

**Comment by davidfirst** [comment]
@KutnerUri , I already fixed the `findAllExportedComponentDefinitions` option.
On the latest dev version, it's already working this way.

**Comment by KutnerUri** [comment]
@GiladShoham it shows:
```
"examples": [
  {
    "raw": "<div>\n<div>\n<Bob/>\n</div>\n<CoolCat/>\n</div>",
    "code": "<div>\n<div>\n<Bob/>\n</div>\n<CoolCat/>\n</div>"
  }
]
```
where it should show:

```
"examples": [
  {
    "raw": "<div>\n  <div>\n    <Bob/>\n  </div>\n  <CoolCat/>\n</div>",
    "code": "<div>\n  <div>\n    <Bob/>\n  </div>\n  <CoolCat/>\n</div>"
  }
]
```

**Comment by KutnerUri** [comment]
@davidfirst - did you add this to reactDocs options?
```tsx
filename: filePath // should we use pathNormalizeToLinux(filePath) ?
```

+ tsType to formatProperties:
```
type: stringifyType(type || flowType || tsType),
```

I also added `if(!prop) return '?';` to `stringifyType()`, not sure if its needed.

**Comment by GiladShoham** [comment]
@KutnerUri The tabs yes its bit. 
I'm talking about the split props

**Comment by davidfirst** [comment]
> @davidfirst - did you add this to reactDocs options?

Not sure I'm following. All I did is changing the react-docgen default resolver.
By default it's `findExportedComponentDefinition`. I changed it to `findAllComponentDefinitions`.

**Comment by GiladShoham** [comment]
@KutnerUri please verify with the latest prod branch

**Comment by GiladShoham** [comment]
resolved by #2690

**Comment by KutnerUri** [comment]
verified with prod branch. :)
@GiladShoham - can we publish a new version / dev version with this fix?

**Comment by GiladShoham** [comment]
There is dev version with this, ijust published it few hours ago. Can you check @KutnerUri ?
