### ISSUE TITLE
autodocs should keep indentation in @example

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#2512]
See: https://bit.dev/kutner/temp/atom/eva-icon-font?version=1.0.0

When exporting a component, the `@example` loses its indentation.

### Example in jsdocs:
```tsx
/**
 * @example
 * <html>
 *   <head>
 *     <EvaIconFont query='aqq93z' />
 *   <head>
 * </html>
 */
```

### Example from API
(https://api.bit.dev/component/kutner/temp/atom/eva-icon-font?version=1.0.0)
```
"raw": "<html>\n<head>\n<EvaIconFont query='aqq93z' />\n<head>\n</html>",
```

I expect the API example to keep the same linebreaks and indentation as the source code.

In addition, we need to specify language `@example`.
A couple of times I wanted to show scss usage, but I always got .tsx highlight.

### Specifications

- Bit version: 14.7.6
- Node version: 12.12
- npm / yarn version: 1.22
- Platform: MacOS

**Comment by davidfirst** [comment]
@KutnerUri , isn't an issue in bit.dev? I just created a component with the example below and ran `bit show`, I can see the example correctly with indentations. 

<img width="347" alt="Screen Shot 2020-04-10 at 10 23 05 PM" src="https://user-images.githubusercontent.com/1963573/79033160-e61ad980-7b79-11ea-8dda-9dc7e09594b4.png">

**Comment by KutnerUri** [comment]
I am getting it without spaces from the API.. @amitgilad3, is it possible you are trimming the examples in the back end?

**Comment by KutnerUri** [comment]
I'm still getting it without spaces, and 95% sure it's happening in the CLI.
I can't explain why or when it is happening. Some components get spaces, some don't.
Doesn't seem to matter if it's tabs or spaces.

Now it is happening in this component:
https://bit.dev/bit/evangelist/marketing/comment-carousel (should have tabs before the objects)

**Comment by GiladShoham** [comment]
@davidfirst I've imported the component @KutnerUri mentioned (https://bit.dev/bit/evangelist/marketing/comment-carousel)
it seems like the tabs have lost. (using `bit cat-object`)
```
"examples": [
        {
          "raw": "const bitTestimonials = [\n{ name: 'Barbra', description: 'head of barbering', content: 'Great scissors!', avatar: '...', }\n{ name: 'Roberto', description: 'Robber of Bertos', content: 'Easy to carry.', avatar: '...', }\n];\n\n<CommentCarousel content={bitTestimonials} />",
          "code": "const bitTestimonials = [\n{ name: 'Barbra', description: 'head of barbering', content: 'Great scissors!', avatar: '...', }\n{ name: 'Roberto', description: 'Robber of Bertos', content: 'Easy to carry.', avatar: '...', }\n];\n<CommentCarousel content={bitTestimonials} />"
        }
      ]
```
it might be during the export / import?
It's weird

**Comment by davidfirst** [comment]
I found the issue.
For non-react components, it was working. 
For react components, the data passed to docgen was different (without the asterisks), and as such, it should have worked with `unwrap: false`. See the PR above for the complete fix.
