### ISSUE TITLE
Collision between typescript components when name is the same

### ISSUE THREAD

**Issue by Tallyb** [teambit/bit#2513]
### Describe the bug

When building typescript components that have the same name, e.g. index.ts it will override components that have the same name. 

### Steps to Reproduce

1. clone this repo: https://bit.dev/bit/envs/compilers/vue
1. Run `bit build`
1. The dist/index.js file generated last (for B) is overriding the file for A. If you run `bit build component-a`, the dist/index.js is generated for A. 

### Expected Behavior

A unique path that can be relied on.

### Specifications

- Bit version: 14.7.6
- Node version: 12.6.1
- npm / yarn version: 6.14.4
- Platform: Mac Catalina
- Bit compiler (include version): bit.envs/compilers/typescript@3.1.40
- Bit tester (include version):

### Additional context

cc: @ranm8

**Comment by davidfirst** [comment]
This is similar to the issue: https://github.com/teambit/bit/issues/2093.
It'll be fixed in the next major version (Harmony).

**Comment by itaymendel** [comment]
irrelevant for v15
