### ISSUE TITLE
Workspace structure

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2516]
## Abstract
This issue's purpose is to have a discussion about the workspace structure and the logical and physical relation between different parts of the workspace: components, dists files, node_modeuls, package.json etc'.

**This issue isn't talking about users who are not upgrading their bit client version. We assume everybody is upgrading. we can have more discussion about old bit versions**.

## Terms:
- Bit project - a project built only from bit components. This project doesn't contain files that are not bit components.
- Mixed project - Project contains both components and files which are not components but require/uses components.
- New compiler - compiler created after harmony and uses the flows extension and capsules to build the component.
- Old compiler - Compiler created pre harmony and uses bit build command to build components. it might use capsule or not.
- Component folder - The component folder in the workspace
- Component capsule - The capsule that represent the component
- Dists - Compiled files of a component
- Extensions - harmony extensions 
- Workspace config - A bit.jsonc file in the workspace.
- Legacy workspace config - old config format in the bit.json file or the package.json file.

## Main product requirements 
- Someone who works with a mixed project should be able to continue working, as usual, using components with old compilers. He should be able to modify components, build them, require them and run the project (**using his own external bundler**).
- Someone who works with a mixed project should be able to use (require) components with new compilers
- Someone who works with bit project should be able to use both components with old compilers and components with new compilers. He should be able to modify components, require them and run the project.
- User should be able to migrate components from old format to new format (irreversible)
- Dev experience - when using a component in the workspace, the developer should have types and auto-complete in his IDE (typescript base).

## Nice to have product requirements
- The ability for someone who works with the legacy config to modify components with extensions / new compilers and re-build it. (is this a must or nice to have?)

## Main relations to discuss:
- Where are the dists file written (this include both root dist folder in the workspace/component folder and the internal structure (full paths, short paths))
  - In bit project
  - in mixed project 
  - for old components using individual files, aliases, relative requires.
  - authored vs imported (the author components might not have folder)
- which of the assets we write in the component folder
  - Package.json 
  - dists
  - node_modules
  - immutable components tree? (bit components)
  - .dependencies
 - do we have a difference between old/new components? or between mixed / bit projects?
- where are the links in node_modules point to in a workspace (is there a difference between bit / mixed project)
- What is the package.json main key value? (main source file? main dist file?)
- How a package.json of the workspace looks like? (do we write components or something else inside?)

## Thoughts to consider
- in a mixed project, an external file might require a component. when bundling the project, it should somehow have access to the dists for this. (he might use relative require or mode path require, or even an alias)
- when using module path requires, the dists are written with short paths in the workspace dists folder, so they might (and in action in production) override each other. if we nest them, a dist file from the project (which is not component) can't find them, so you can't run the project.
- We want to remove the package.json / dists / node_modules from a component folder in bit project, but in such case, what we will have in the link in the workspace node_modules? symlink to the component folder? now that it doesn't have package.json and index node can't resolve it, so we won't get autocomplete / types in the workspace.
- in case different components in my workspace use the same external dependency in a different version. since we don't have node_modules in the component folder, how we will get different completion/types for them? we can only have one version in the workspace root.
- How to handle dists for special components like the component with png only

## Solution structure
I suggest building a few projects (for mixed and bit projects). with different components. 
Build them by hand, with all links, node_modules, configs and make sure we can run them.
Make sure we have the autocomplete in IDE.
Make sure we can use components, assets, styling, and others.

**Comment by Tallyb** [comment]
The behavior defined below is applicable for authored and imported components (but not for installed components). 
- Components pacakge.json and dist files reside only in the capsules created for each component. 
- The components are linked from within the node_modules folder to the capsule. (capsules reside completely outside the workspace).
- Bit link crates the links. The links are in the following format: @GiladShoham 
- Components do not appear in the package.json. Doing a normal "npm install" requires re-running bit link to recreate the links. 
Open issues: 
1. Since capsules are now persistent and not transient, it is worth identifying their complete lifecycle and the events that affect them. (created, updated, linked to, destroyed etc.)
2. How do inter-dependent components are linked between capsules: i.e. if capsule A requires component B (that is also in the workspace) - what is linked in the capsule of A and how it is updated.
