### ISSUE TITLE
bit.dev: LICENSE file is not removed when license is reverted to "none"

### ISSUE THREAD

**Issue by stephan-devop** [teambit/bit#2530]
When I choose an open-source license for a component from the drop-down menu at bit.dev then a LICENSE file is added to the component. When I revert the license to "none" then the LICENSE file is not removed from the component.

**Comment by davidfirst** [comment]
@stephan-geospin , thanks for reporting the issue.

@GiladShoham , I don't remember having any implementation of changing the License file and saving it into the same version. Is there a bit-dev feature that creates a new version?

**Comment by GiladShoham** [comment]
@davidfirst indeed there is no implementation for this.
I think @itaymendel wants to make some changes about the license.
Am I right?

**Comment by itaymendel** [comment]
we'll be reimplementing license feature after bit v15 is out this week. closing this issue.
