### ISSUE TITLE
add prefix to extensions in configs instead of nesting them under extensions key

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2536]
The rational is to easily distinguish between a prop I want to add to my package.json and an extension
Today in order to configure an extension you should do something like:
```js
"my-comp": {
      "extensions": {
        "my-ext-name": {}
      }
},
```
We should change it to be something like
```js
"my-comp": {
     "{prefix}my-ext-name": {}
},
```

**Comment by GiladShoham** [comment]
@ranm8 @itaymendel @Tallyb 
Please suggest a prefix.

**Comment by ranm8** [comment]
how about checking if the given key is a valid package name, including a scope since we are changing our modules paths to be compatible with npm. See @itaymendel spec re #2506

**Comment by Tallyb** [comment]
@ranm8  - searching for valid path names can lead to confusion about why it is not found. 
It is common to have standard names for packages that include expansions: 
some of them go with suffix (xxx-webpack-plugin) and some with prefix (gulp-xxx or cordova-plugin-xxx). 
I would suggest a prefix: bit-extension-xxxx.

**Comment by itaymendel** [comment]
I think I agree with @ranm8 . Usually, plugin/extension names are very descriptive, and Bit will be able to use the name to figure out the right extension and where to resolve it from.

How should this config help determine the version of the extension to use?

**Comment by GiladShoham** [comment]
@itaymendel 
Few issues:
1. my-key is also a valid component name (I might add a new component called my-key and defined it as an extension). 
2. This parsing for loading extension happens in the very beginning of the process, I can't access bit's internals (and don't want to), start checking my bitmap, my local scope, remote scopes. this will really slow down the process of loading bit for any command. it must be parsing that doesn't require any access to store stuff like bitmap or scopes.

**Comment by itaymendel** [comment]
The valid name, according to the suggestion is `@<default-scope>/<component-id>`, not just `any-key`. I'm not sure you need to actually look for it, just parse and see if it fits the structure.

**Comment by GiladShoham** [comment]
@itaymendel 
this means you can't add props that contains "/" in the key.
If it's @owner.scope/comp-id its more reasonable, but only scope/comp-id I'm not sure it's enough unique.

**Comment by itaymendel** [comment]
Perhaps you miss-read the example. I think that the regex is pretty unique, as it starts with `@`, like any other component-id.

I don't think any prop in `package.json` ever starts with a `@`.

**Comment by GiladShoham** [comment]
not a formal prop, but I won't block the option to use @ in custom prop.
If we go with @owner.scope/name it's fine. (anyway this would be the valid component name). but it requires the implementation of the @owner.

**Comment by davidfirst** [comment]
How about having this ability to add props into package.json a new extension by itself. A "package-json" extension. This way, no need to nest the "extension" and the props that need to be added/changed will be nested under the package-json extension as with any other extension.

I think it's a more consistent approach. 
No need to distinguish between the keys and no need to parse them.

**Comment by GiladShoham** [comment]
@davidfirst That's interesting. 
I need to think about it.
@itaymendel @Tallyb @ranm8 what do you think?

**Comment by davidfirst** [comment]
@GiladShoham , I guess we ended up with a similar approach to my suggestion here, right? if so, we close this.

**Comment by GiladShoham** [comment]
Everything is now extension.. So no need to nest. We can close this. I'll soon
