### ISSUE TITLE
write merged config into capsule's package.json

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2537]
This task contains few technical pre-requisites

- [ ] implement a new component config generic merge strategy
- [ ] implement special fields strategies
  - [ ] dependencies / dev deps
  - [ ] overridden deps / dev deps 
  - [ ] extensions
- [ ] write an updated config into the components package.json in a capsule (#2552)
  - [x] write simple configs added by extensions into the components package.json in a capsule (#2552)
  - [ ] write special fields merged into the components package.json in a capsule

- implement a new component config strategy - the strategies are as follows (top is the stronger)
  - user overrides (props user write in the component package.json)
  - user overrides in workspace config (the old propagation rules in case of multiple matching stay the same)
  - config provided by extensions (there is no order guarantee, an extension might override another extension config)
 - implement special fields strategies (the core is actually the same is extension since it's built from extensions, but the extension run later, so they will override) this include calculation from both fs and models
the merge will be done based on a top-level property similar to do something like `object.assign(bit config, extension config, workspace config, component package.json)`
But some of the props will have special merge strategies:
for example, dependencies (all types - runtime / dev and peer) can be overridden completely by the user if he specify those props in the package.json (this will eliminate completely the automatic dependency definition by bit)
but there are special props (exact names TBD) - dependenciesOverrides.(runtime,dev,peer), values from there will be merged into the dependencies instead of compleltly override them. those props also support the "+" and "-" symbols to add/remove dependencies). for example if an extension wants to add react in v16.0.0 he will return:
```
{ 
  dependenciesOverrides: {
    runtime: {
      "react": "16.0.0"
    }
  }
}

```
- write an updated config into the components package.json in a capsule - when creating a capsule for a component we should write it's package.json after merging all the configs. this will create different package.json in the capsule and in the component folder in the workspace. they do not represent the same thing anymore. the package.json in the workspace component folder represents a way to modify specific configuration. while in the capsule it represents the final configuration for consuming / running.

Related to #2456

**Comment by Tallyb** [comment]
I would suggest the following: 
For bit config, extension config, workspace config, component package.json -> all fields are mergeable. (use deepmerge - it seems to do a good job). 
Then the "hard" overrides will be in a separated configuration. 
Then the logic is pretty straight forward: 
let merged = deepmerge(<all configurations>). 
Object.assign(merged, hardAssigned). 
It is less obvious when you have different strategies inside the same configuration, and then the same one from a different configuration.

**Comment by GiladShoham** [comment]
done
