### ISSUE TITLE
Flows: outputs and log reports

### ISSUE THREAD

**Issue by ranm8** [teambit/bit#2545]
After a discussion with Aram I think this might be a better idea for the flows command to be written with the logger while [Ink might be relevant for other commands](https://github.com/teambit/bit/issues/2544). 
We need to discuss how to log flow events and how to output them into the user screen on both CI and local machine. I believe we can achieve something effective quickly using @imsnif reporter.

I thought of the following format:
- Use the Logger extension to report all logs fired from the different flows.
- How do I know when a flow is completed?
- Decide on three level of progress bars: Obtaining capsules inc. dependency resolution, component task execution.
- Which logs to leave behind? errors? warnings?

Let me know your thoughts.

**Comment by qballer** [comment]
> * Use the Logger extension to report all logs fired from the different flows.
We need to make sure printing to screen and return logs are separated so command writer can control the output.  > * Use the Logger extension to report all logs fired from the different flows.
We need to make sure printing to screen and return logs are separated so command writer can control the output.  
> * How do I know when a flow is completed?
You get a message on an rx stream with `type:'flow:result` and `id:<bit_id>`

> * Decide on three level of progress bars: Obtaining capsules inc. dependency resolution, component task execution.
This sounds like a great idea. Can we make capsule/creation return the log stream (rx prefered) instead of printing to screen ? 
> * Which logs to leave behind? errors? warnings?
By default I want to leave out stdout and show stderr. in `verbose` mode I would like to show stdout as well. I would like to hide all the npm warning by default, if possible as they pollute screen and provide little value.
By default all logs we don't show on screen they should go to the log files as if all options were available. 

> Let me know your thoughts.
CC: @itaymendel 
> * How do I know when a flow is completed?
You get a message on an rx stream with `type:'flow:result` and `id:<bit_id>`

> * Decide on three level of progress bars: Obtaining capsules inc. dependency resolution, component task execution.
This sounds like a great idea. Can we make capsule/creation return the log stream (rx prefered) instead of printing to screen ? 
> * Which logs to leave behind? errors? warnings?
By default I want to leave out stdout and show stderr. in `verbose` mode I would like to show stdout as well. I would like to hide all the npm warning by default, if possible as they pollute screen and provide little value.
By default all logs we don't show on screen they should go to the log files as if all options were available. 

> Let me know your thoughts.
CC: @itaymendel

**Comment by davidfirst** [comment]
@qballer , a reminder. 
[ ] Please stream the errors coming from Flow. They're currently ignored. (in the flow.ts file, only `data.type === 'task:result'` case is handled).

[ ] Also, these strings ('task:result'`, task:stderr') are better off be constants. 

[ ] One last thing, the current prod logger must be integrated with all this logging mechanism. It needs to be written to the debug.log file.

**Comment by qballer** [comment]
> Please stream the errors coming from Flow. They're currently ignored. (in the flow.ts file, only `data.type === 'task:result'` case is handled).

They are already streamed and shouldn't be handled in that level. Per our discussion last night. I'm using a ReplaySubject of rxjs, you can subscribe to all events sent on the stream from "beginning of time" or execution of bit.
 
> Also, these strings ('task:result'`, task:stderr') are better off be constants.

It's already planned. Better yet is have the `ReplaySubject<any>` to `ReplaySubject<SomeType|SomeOtherType...>`

> One last thing, the current prod logger must be integrated with all this logging mechanism. It needs to be written to the debug.log file.

Yea, still need to look at the code in that aspect.

**Comment by davidfirst** [comment]
> They are already streamed and shouldn't be handled in that level. Per our discussion last night. I'm using a ReplaySubject of rxjs, you can subscribe to all events sent on the stream from "beginning of time" or execution of bit.

@qballer , I can take care of that in `bit compile`, but just to make sure you handle this issue in Flows.
Meaning, when running `bit run build` and there is an error/stderr along the road, it doesn't get ignored. This is something that you take care of, correct?
Once you do that, I'll check what you did and implement it (or re-use it) in the compile extension. I just don't have deep knowledge of how Flows/Reporter work to do it quickly.

**Comment by itaymendel** [comment]
I noted down the general outputs Bit should print for running `flows`. These outputs assume the reporter with a dynamic console input line in the terminal.

- This example does not use 'raw' mode (tty).
- In the future, `flows` will also support 'raw' when `tty` is available.

## "Rolling" outputs of `flows`

Seeing that `flows` is a process with several major steps, Bit should have a "rolling" output, depending on the current step. Additionally, the input line should provide additional information as "things" happen in the background.

Below listed the few "parts" of the outputs and try to mimic the "interactivity" of the terminal's console input line. The console input line is marked with a dollar (`$`) sign (this should probably be replaced by an animation in the terminal).

> **Note** - Outputs from extensions during `flows`
>
> For each line an extension prints, the reported to print it to the terminal while keeping the console-input line in it's "processing" state.
> This "rolling flow" does not show these print-lines, but see below for a complete example.

### Generic output "headline"

(should probably be a generic part for any command output)

```sh
Bit - Build, distribute and collaborate on reusable components <version> (<"latest", if latest>)
Node.js version is <version>
<pacakge manager> version is <version>

Starting "<command/flow name>"
```

### Setting up components for execution

The first step is figuring out the network of connected Capsules (isolated component environments with dependency links between them).

```sh
Setting up component execution
$ Resolving components from the workspace ([counter])... [iterate through component names]
```

Next print a summary for component resolution and figure out the dependency graph to determine the execution order of `flows`

```sh
Setting up component execution
V 56 Components resolved from workspace
$ Building dependency graph to determine flow execution order
```

After the execution order is determined, Bit needs to figure out the extensions to run.

```sh
Setting up component execution
V 56 Components resolved
V Flow execution order defined according to the workspace dependency graph
```

Now the flow is ready to run on all components.

> **Note** - missing setup steps
>
> It's possible that I missed some setup steps. If so, we'll need to add them, as it is important to explain what's happening in the background.

### Executing the flow

First, we need to tell the user that Bit is about to run the flow and indicate the number of processes it'll use for it.

```sh
Started component isolation and running "build" flow

Executing a maximum of <number of concurrent processes> concurrent processes
```

Executing extensions:

- Print a line whenever a component starts running.
- When an extension prints to the console, Bit should pipe it and add a prefix annotating the component name, extension name, and log level.
- When a component is done executing, print a line. include duration, status, and its index.
- The input line should indicate how many components remaining and the names of components currently being executed.

```sh
[component1] - started
[component2] - started
[component1] - [extenion name] WARN [some random warning from extension]
[component1] - [extenion name] ERR [some random warning from extension]
[component1] - completed successfully in 2 seconds (1 of 56)
[...]
$ N components remaining. Running: [list components being processed right now]
```

### Summary

The summary should list all success, fail and total time.

```sh
Success ([total success]):
==========================
  - button
  - header
  - [...]

Failed ([total failed]):
========================
  - [...]

Finished <flow name>. (2 minutes)
```

## Final log

Below an example of the end result of running flow on a workspace without the "dynamic" reporter in the console input line.

```sh
Bit - Build, distribute and collaborate on reusable components <version> (<"latest", if latest>)
Node.js version is <version>
<pacakge manager> version is <version>

Starting "<command/flow name>"

Setting up component execution
V 56 Components resolved
V Flow execution order defined according to the workspace dependency graph

Starting component isolation and running "<flow>"

Executing a maximum of <number of concurrent processes> concurrent processes

[component1] - started
[component2] - started
[component1] - [extenion name] WARN [some random warning from extension]
[component1] - [extenion name] ERR [some random warning from extension]
[component1] - completed successfully in 2 seconds (1 of 56)
[...]

Success ([total success]):
==========================
  - button
  - header
  - [...]

Failed ([total failed]):
========================
  - [...]

Finished <flow name>. (2 minutes)
```
