### ISSUE TITLE
Bit login url is incomplete

### ISSUE THREAD

**Issue by kegi** [teambit/bit#2551]
### Describe the bug

When running `bit login` the url displayed on the terminal is ok but the url sent to the browser is incomplete, which result in a blank screen.

### Steps to Reproduce

`bit login`

### Expected Behavior

The complete url should be sent to the browser

### Screenshots, exceptions and logs

`> bit login`
`Your browser has been opened to visit:`
`https://bit.dev/bit-login?port=8085&clientId=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&responseType=token&deviceName=DEVICE_NAME&os=linux`

The url sent to the browser : **https://bit.dev/bit-login?port=8085**
Everything after the "**&**" is removed

The page is blank with a console error :
`uncaught exception: Object`

### Specifications

- Bit version: **14.7.6**
- Node version: **13.12.0**
- yarn version: **1.9.4**
- Platform: **Windows 10 using WSL (Ubuntu 18.04)**
- Browser: **Firefox 74.0.1**

**Comment by itaymendel** [comment]
This is odd. We'll probably need to set up a similar setup to yours to see this behavior.
Is there any chance you have a FF extension that tries to clear URL params?

**Comment by kegi** [comment]
I sent a PR. The problem was not coming from my browser, it was coming from WSL.
