### ISSUE TITLE
Auto tag should have an option to use latest components changes

### ISSUE THREAD

**Issue by DeyLak** [teambit/bit#2581]
### Description
Imagine, I have compA and compB, both are changed and combB is a dependency of compA:
`compA -> compB`
If I run `bit tag compB`, compA will be tagged also, but the only change that will be tagged is the new version of compB. Other changes will still be displayed as `modified`. I want an opportunity to tell Bit, that I want to tag compB and auto-tag it's dependants, taking into account their changes too. Otherwise, I should use `--skip-auto-tag` and tag these components separately, or untag compA and tag it again with all changes. 

### Describe the solution you'd like
I'm thinking about smth like: `bit tag {component} --auto-tag-modified`

**Comment by GiladShoham** [comment]
If you will use tag -a it will tag compA code changes and the bump of b inside together

**Comment by DeyLak** [comment]
@GiladShoham Yes, I understand that, but I may have other modified components, that I don't want to tag yet(maybe a workflow issue, making some hot fix for somebody, who is also using these components). Or I may want to use different semver flag for tagging them. Overall, I think, that `-a` option is not giving me that much control over tagging process.

**Comment by GiladShoham** [comment]
That correct. We should give the option to tag many specific components or support glob patterns on tag. It's something we planned to do long time ago.

**Comment by GiladShoham** [comment]
@itaymendel  @Tallyb What do you think? 
Any suggestion for a syntax to do this?

**Comment by Tallyb** [comment]
Add multiple instances (tag a b c d ) + glob patterns (tag "utils/*") on tag should do the trick.

**Comment by DeyLak** [comment]
@Tallyb That's not exactly, what I'm asking for, though it would be great addition, but I'll be glad, if you also add this auto-tag-modified feature, cause auto-tag is a very convenient feature itself and I don't want to lose opportunity to let bit decide, which components versions should be bumped.

**Comment by GiladShoham** [comment]
Thanks for the feedback @DeyLak 
We will think about it.
@itaymendel @ranm8 Ideas for a syntax?

**Comment by itaymendel** [comment]
resolved in v15, as changes fetched from workspace

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
