### ISSUE TITLE
fix split e2e tests on circle by timing on windows

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2586]
Currently, if look at the windows_e2e tests on circle under the `write e2e files` step, you will see this warning:
```
Error autodetecting timing type, falling back to weighting by name. Autodetect no matching filename or classname.  If file names are used, double check paths for absolute vs relative.
Example input file: "e2e\\api\\add-many.e2e.1.ts"
Example file from timings: "C:\\Users\\******ci\\project\\bit\\bit\\e2e\\commands\\eject.e2e.1.ts"
```
This might be a result of the next line of how we run them.
We might try to make it the same as in the Linux e2e.
This might require to run it under bash.exe instead of under powershell.
It requires more investigation.

reference - https://circleci.com/docs/2.0/parallelism-faster-jobs/#using-the-circleci-cli-to-split-tests

**Comment by davidfirst** [comment]
I investigated this issue, which occurred also on Linux a while ago. 
I tried many reporters, many formats, none of them was recognized by Circle timing detection.
I ended up using the file-size strategy (`circleci tests split --split-by=filesize`).
