### ISSUE TITLE
Bit component too heavy

### ISSUE THREAD

**Issue by nvthuong1996** [teambit/bit#2588]
i am newbie
i flow tutorial bit for vue at
https://docs.bit.dev/docs/tutorials/bit-vue-tutorial

i try build prodcut-list component and import it into nuxt app
#####  i try build nuxt with two option
1. import  component from nomal
`import Logo from "@bit/<username>.vue-tutorial.product-list";`
after i build analyze `nuxt build --analyze`
result: ![enter image description here](https://www.upsieutoc.com/images/2020/04/15/Screen-Shot-2020-04-15-at-11.04.50-AM.png)

2. import compoent direct folder after use 'bit import ...'
`import Logo from "@/components/product-list/ProductList";`
this is result ![enter image description here](https://www.upsieutoc.com/images/2020/04/15/Screen-Shot-2020-04-15-at-10.49.48-AM.png)

#### import file size from bits 9 times larger than import direct
That made me think about if I split my project, the project size will increase a lot.

**Comment by Tallyb** [comment]
The component was built in development mode, and I think this is why it was larger. 
It was changed to production, so if you use the latest version of the compilers/vue, you should get a smaller bundle size.

**Comment by nvthuong1996** [comment]
i use bit.envs/compilers/vue@0.0.16. i thank it is latest version. i try run command 'bit build -h' but i can't get any help about option build 'develop','product'

**Comment by nvthuong1996** [comment]
The problem has been resolved

**Comment by nvthuong1996** [comment]
I upgrade compilers  bit.envs/compilers/vue@0.1.2. The problem has been resolved. size component down 2.44kb. thank you
