### ISSUE TITLE
Updating self hosted bit server

### ISSUE THREAD

**Issue by stefanotto** [teambit/bit#2598]
How would one approach updating a self hosted instance to the latest Bit version?

I was asking myself that question after fiddling around with it and noticed the Bit version in `scope.json`

```
{
    "name": "scope",
    "remotes": {},
    "version": "14.7.6"
}
```

**Comment by itaymendel** [comment]
To update a self-hosted Bit server you need to update the binary on the server. So depending on your installation method, either `npm i` or `apt-get`...

As for the version number in `scope.json`. Bit manages it. Technically it's the version of the Bit binary Bit used the last time it did any operation on the data in the internal scope database. While we try to keep Bit as backward compatible as possible, this is a safety measure so by mistake you'll not have an older version try to work with updated data structures.
