### ISSUE TITLE
review bit help

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2603]
The main bit help should be reviewed in the following aspects:
- [ ] make sure all core commands have a group
- [ ] make sure all core commands have a proper short description (might be configured via the description itself if it fits)
- [ ] letter casing for commands descriptions
- [ ] groups order
- [ ] groups upper / lower case
- [ ] groups descriptions

**Comment by ranm8** [comment]
Thanks @GiladShoham 
@itaymendel can you help with that? I believe everything should be lower cased as we discussed before and decide on all groups and CLI reference. Let's decide on the guidelines for building a CLI command and apply on all.
