### ISSUE TITLE
Angular material on Bit.dev

### ISSUE THREAD

**Issue by halocu** [teambit/bit#2605]
### Description
Hi,

I created simple page with Angular then I added Angular Material component;

"< mat-toolbar color="primary">"
 "< span>Hello</span>  "
 "< span class="example-fill-remaining-space"></span>"
  "< span>Right Text</span>"
"< /mat-toolbar>"

When I export this component to the Bit I get a below warning;

vendor-es2015.js:117621 Could not find Angular Material core theme. Most Material components may not work as expected. For more info refer to the theming guide: https://material.angular.io/guide/theming

I am newbie in Angular and Bit, could you help me ?
Thank you,
Halil

### Specifications

- Bit version: 14.7.6
- Node version: 12.16.1
- npm / yarn version: 6.13.4
- Platform: 
- Bit compiler (include version): "bit.envs/compilers/angular@0.2.0"
- Bit tester (include version):

### Context and additional information

topbar.css
-------------------------
@import '~@angular/material/prebuilt-themes/deeppurple-amber.css';

.toolbar{
  background: cornflowerblue;
}
.example-fill-remaining-space {
  /* This fills the remaining space, by using flexbox.
     Every toolbar row uses a flexbox row layout. */
  flex: 1 1 auto;
}

topbar.component.html
-----------------------------
<mat-toolbar color="primary">
  <span>Hello</span>
  <span class="example-fill-remaining-space"></span>
  <span>Right Text</span>
</mat-toolbar>

topbar.component.ts
-----------------------------
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-topbar',
  templateUrl: './topbar.component.html',
  styleUrls: ['./topbar.component.css']
})
export class TopbarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

topbar.module.ts
-----------------------------
import {NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';
import {MatIconModule, MatToolbarModule} from '@angular/material';
import {TopbarComponent} from './topbar.component';

@NgModule({
  declarations: [TopbarComponent],
  imports: [
    CommonModule,
    MatToolbarModule,
    MatIconModule
  ], exports: [
    TopbarComponent
  ]
})
export class TopbarModule {
}

**Comment by itaymendel** [comment]
To build and run Angular code, Bit uses Angular's `ngc`. This means that all errors that are not bit-specific issues are prompted by Angular. It seems that the warning you get is something to do with the code you implemented.
Does this warning occurs when you build your code specifically with Bit, or does it happen when you run `ng` commands as well?

I'd like to check if this is a Bit-related issue. Can you please share the project with its configuration to a public github repository?
