### ISSUE TITLE
Vue dynamic component is not loading

### ISSUE THREAD

**Issue by udhaya0000** [teambit/bit#2606]
I'm loading a child component from a wrapper component based on the property passed to the parent component using async/dynamic component, and it works fine when I import my local component. When I build and export it to bit cloud it either works in bit playground neither if I import it from bit and use it in my project.

instead of javascript the app-icon.common.0.js returning html code
![image](https://user-images.githubusercontent.com/18388014/79779852-ab265c00-8358-11ea-90a7-940e5d849f71.png)

Error I got in bit cloud playground
```
[Vue warn]: Failed to resolve async component: () => __webpack_require__("./ lazy recursive ^.*\\/.*$")(`${this.dir}/${this.name}`)
Reason: ChunkLoadError: Loading chunk 0 failed.
(missing: https://va75d39fb7444.capsule.ws/ui/app-icon.common.0.js)

```
### Specifications

- Bit version: 14.7.6
- Node version: 12.16.1
- yarn version: 1.22.4 
- Platform: Macos
- Bit compiler (include version): vue@0.0.16

**Comment by itaymendel** [comment]
Just to clarify, as I don't fully understand it from the issue.
The component works when you import/install it to another project and fails only on the bit.dev cloud playground?

**Comment by udhaya0000** [comment]
actually the component didn't through any error while I did bit build and bit tag. The component worked fine before moving it to bit, after I converted it as bit component, it didn't load in the playground here https://bit.dev/udhaya0000/test/ui/app-icon also when I import it using 

`import AppIcon from '@bit/udhaya0000.test.ui.app-icon';
`
it didn't work

**Comment by udhaya0000** [comment]
also the error screenshot attached it taken from the bit.dev playground console

**Comment by udhaya0000** [comment]
@itaymendel any luck?

**Comment by IlyaShkurenko** [comment]
@udhaya0000 were you able to fix it? I have same issue
