### ISSUE TITLE
bit import - success, but process hangs forever

### ISSUE THREAD

**Issue by gdagundaridze** [teambit/bit#2623]
### Describe the bug

Found this: https://github.com/teambit/bit/issues/2301. But as discussed with @itaymendel opening new one since this seems to be different.

Hangs indefinitely when running:
`bit import`

Or even if importing only 1 component like:
`bit import castingnetwork.blocs/blocs/profile-edit`

Import itself is done fine. There are logs that component's were imported successfully. Digged a bit and found out that process is not exiting because of this part of the code:
```
 exitAfterFlush(code = 0, commandName) {
    var _this = this;

    return (0, _bluebird().coroutine)(function* () {
      yield _analytics().Analytics.sendData();
      let level;
      let msg;

      if (code === 0) {
        level = 'info';
        msg = `[*] the command ${commandName} has been completed successfully`;
      } else {
        level = 'error';
        msg = `[*] the command ${commandName} has been terminated with an error code ${code}`;
      }

      _this.logger[level](msg);

      yield waitForLogger();
      process.exit(code);
    })();
  }
```

`yield waitForLogger()` is called, and after that `process.exit(code)` never gets called.

### Steps to Reproduce

Not sure what are the exact requirements. But currently we have 2 collections with 100 / 11 component's inside respectively. Each having around 100 versions.

### Expected Behavior

Process exists when import is finished successfully

### Screenshots, exceptions and logs
<img width="1615" alt="Screen Shot 2020-04-26 at 8 16 25 PM" src="https://user-images.githubusercontent.com/10912388/80313250-d0a0e300-87fa-11ea-8398-e3a15f24d489.png">

### Specifications

- Bit version: 14.7.6
- Node version: 12.16.2
- npm / yarn version: 1.17.3
- Platform: MacOS Catalina 10.15.2
- Bit compiler (include version): N/A
- Bit tester (include version): N/A

**Comment by itaymendel** [comment]
This also happens when you try to import a specific component from any of your collections, right?

**Comment by guramidev** [comment]
Yes, exactly, updated the ticket.

**Comment by GiladShoham** [comment]
@guramidev could you please check this on some other machine and let us know if it happens as well?
Thanks!
