### ISSUE TITLE
Can't install extension of bit

### ISSUE THREAD

**Issue by nvthuong1996** [teambit/bit#2630]
### I try install extension of bit in project
`bit import bit.extensions/npm/pack --extension`
### result
`the following component environments were installed`
`- bit.extensions/npm/pack@2.0.2 
`
### I try pack compoennt
`bit pack logo-share `
But error appear:
`warning: 'pack' is not a valid command.`
`see 'bit --help' for additional information.`

### Specifications

- Bit version:14.7.6
- Node version:v12.16.1
- npm / yarn version:6.13.4
- Platform:darwin
- Bit compiler (include version):none
- Bit tester (include version):none

**Comment by GiladShoham** [comment]
try `bit npm-pack` instead of `bit pack`

**Comment by nvthuong1996** [comment]
I tried. but it not working

**Comment by nvthuong1996** [comment]
![enter image description here](https://www.upsieutoc.com/images/2020/04/28/Screen-Shot-2020-04-28-at-7.00.31-PM.png)

**Comment by GiladShoham** [comment]
did you get `npm-pack is not a valid command` error or another error?
Can you check in `bit --help` if you see `npm-pack` at the end of the list?
