### ISSUE TITLE
How to export react component that requires a less file

### ISSUE THREAD

**Issue by Codyooo** [teambit/bit#2633]
### Description
I want to share a react component on bit server, the component is written in typescript and it requires a less file. I don't know how to solve the .less file issue. 
https://bit.dev/codyooo/rc-demo/switch/~code 

### Specifications

- Bit version: 14.76
- Node version: 13.12.0
- npm / yarn version: 6.41
- Platform: mac
- Bit compiler (include version): bit.envs/compilers/react-typescript
- Bit tester (include version): none

**Comment by itaymendel** [comment]
I don't fully understand what do you mean by the issue you are getting.
Can you please describe what is the issue you are facing and when does this occurs?

**Comment by huangxiaolu** [comment]
I think I have a similar problem. I have a component folder with a `index.tsx` and a `index.less`. When I run `bit build` with react-typescript compiler, it throw the following error:

```
error TS2307: Cannot find module './index.less'.
import styles from "./index.less";
                     ~~~~~~~~~~~~~~
```

I already included a typings.d.ts file in the `env.compiler.bit.envs/compilers/react-typescript@3.1.45.rawConfig.tsconfig.include` config, which has the following declaration

```
  declare module '*.less' {
    const classes: { readonly [key: string]: string };
    export default classes;
  }
```

However, It seems like that the compiler doesn't respect that config.

**Comment by itaymendel** [comment]
bit v15 natively support less.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
