### ISSUE TITLE
Flows extension, bugs and improvement requests

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2643]
- [x] While running "bit tag" the process exits unexpectedly. See #2642  for instructions on how to reproduce the issue.

- [ ] Types are missing from public methods. Especially `flows.run()` method. (actually the entire file doesn't have return types)>
- [x] `handleNetworkError(seed: string, graph: Graph, visitedCache: Cache, err: Error)` the `err` is not `Error`, it's a custom object, so it needs to be fixed. 
- [ ] In case of an error from a task, (use the PR from the first point here to reproduce) `flows.runMultiple` only shows the `code` as 1, but doesn't have the actual error.
- [x] in network.getSeeders, this part `.slice(0, Math.max(5 - amount, 1))` is not clear. Why 5 and why subtracting the amount.
- [ ] `!!~Object.entries` not very clear.
- [x] `zip(zip(seeders, flows).pipe(map(([seed, flow]) => flow.execute(visitedCache[seed].capsule))), seeders)` not very clear.
- [ ] since this is a complex extension. It could be great to have some kind of explanation (maybe in the readme of in the Flows class) of what's going on.
- [ ] `runToPromise` method doesn't catch errors, the promise in that method never gets resolved nor rejected. Instead, the process just exists without any indication of what happened. I created a reproducible e2e-test in a new branch "harmony/flow-miss-errors".

**Comment by qballer** [comment]
Thanks for the e2e. I'm going to look in to it!
