### ISSUE TITLE
override owner and default scope for specific component

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2648]
We should decide where is this data stored (as part of which extension).
Currently we configure the default owner / scope in the workspace extension. 
but those are defaults for the entire workspace. what if I want to override it for specific component?
It's not longer should called default owner / scope, but owner / scope.
And it can't be configured under the workspace extension for specific component (it doesn't make any sense)

**Comment by itaymendel** [comment]
available via variants

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
