### ISSUE TITLE
Bit build should build dependency tree

### ISSUE THREAD

**Issue by marcusfroling** [teambit/bit#2652]
### Description

Bit build should also build dependency tree. When working on multiple components, it is now necessary to build all components manually. E.g, say you have 3 components A,B and C. When modifying component A which has dependencies A->B->C, it is necessary to also manually build component B in order to have these changes in component C. 

### Describe the solution you'd like

When working on multiple components, running bit build <id> should also build all components that are depending. This could be done by default or by having a flag, e.g --build-dependencies

**Comment by GiladShoham** [comment]
@marcusfroling Thanks.
Right now it's in the compiler writer hand. 
There is a flag the compiler can specify to tell bit to do this.
In the upcoming version, this build chain will be much smarter. we call it a network of components and we will provide many APIs to make the proper network build.

**Comment by marcusfroling** [comment]
Thanks for the reply @GiladShoham , good to know you are working on improving the build chain.
Is there any date set for this version release? Also, is there any documentation on available flags for compilers?

**Comment by GiladShoham** [comment]
There is no exact date.
You can track progress here - https://github.com/teambit/bit/issues/2280
and here - https://github.com/teambit/bit/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22harmony+release+v1.0%22

If you want a sneak peek about the new way you can read more here - 
https://github.com/teambit/bit/blob/harmony/main/src/extensions/flows/README.md
keep in mind that this is not yet finalized.

**Comment by itaymendel** [comment]
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
