### ISSUE TITLE
Incorrect use of harmony code in the legacy code

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2672]
Harmony (new extensions system) should use the legacy code.
The legacy code should not use Harmony code.

There are a few occurrences of legacy code imports from harmony. This breaks the dogfooding process because in the dogfooding branch, `src/extensions` is gone and instead, the code moves to "extensions" and compiled through the capsules. 

**High Priority - a blocker of the dogfooding task**
- [x] `import { PaperError } from '../extensions/paper/exceptions';` in src/cli/default-error-handler.ts. Assigned to @qballer .
- [ ] Capsule. Assigned to @imsnif . 
Occurrences of Capsule:
src/consumer/component-ops/build-component.ts: `import { Capsule } from '../../extensions/isolator/capsule';`
src/consumer/component/consumer-component.ts: `import { Capsule } from '../../extensions/isolator/capsule';`
src/consumer/component/sources/data-to-persist.ts: `import { Capsule } from '../../../extensions/isolator/capsule'`
src/environment/capsule-factory.ts: `import { Capsule, FsContainer } from '../extensions/isolator/capsule'`
src/environment/isolator.ts: `import { Capsule } from '../extensions/isolator/capsule'`
src/legacy-extensions/extension-isolate-result.ts: `import { Capsule } from '../extensions/isolator/capsule'`

**Low Priority - Not a blocker of the dogfooding task**
- [ ] src/api has the following: `export { Workspace } from './extensions/workspace'`, `export { Bit } from './extensions/bit'`, `export { ComponentFactoryExt, ComponentFactory } from './extensions/component'`. Assigned to @qballer .
- [ ] src/cli/commands/public-cmds/capsule-cmd.ts: this command works with Harmony code, it should be part of the extensions. Assigned to @imsnif .

**Comment by imsnif** [comment]
Hey, so the `Capsule` and `FsContainer` no longer exist in the legacy code. I think a lot of these commands are things we already do with the new code (eg. build). Question is: what would we like to do about this? Copy/paste the classes from the new code and place them in the legacy code (a little eh and might not work, but we can try) or try to migrate these commands? @davidfirst @ranm8

**Comment by davidfirst** [comment]
Thanks for checking this @imsnif . 
One of the occurrences is the `src/consumer/component/sources/data-to-persist.ts` file, which is used in several legacy commands that are not feasible to move, so I guess we'll need an alternative.

I think the best way would be to move `Capsule` and `FsContainer` to the legacy code and use them in the new code. 
In general, that's the strategy we use elsewhere. Only the new code uses the old one, not the vice versa.
