### ISSUE TITLE
Ejecting a folder like: `bit eject <path/to/components>/*`

### ISSUE THREAD

**Issue by remo1** [teambit/bit#2675]
### Describe the bug

you cant eject a folder containing bits with a command: `bit eject <path/to/components>/*`

### Steps to Reproduce

1. import more than one bit
2. use command: `bit eject <path/to/components>/*`
3. you get -> error: component "src/bits/badge" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)

### Expected Behavior

Should eject the whole folder with multiple bits inside

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 14.7.6
- Node version: v12.16.1
- npm / yarn version: 6.13.4
- Platform: macOS
- Bit compiler (include version):  https://bit.dev/boclips/compilers/compiler@2.0.0

**Comment by GiladShoham** [comment]
@remo1 Thanks for reporting this. we will take care of it.

**Comment by drakonkat** [comment]
I think it's necessary function when you have multiple imported component where are you working with
