### ISSUE TITLE
new bit compile - configuration issues

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2680]
This is a summary of the configuration issues that I added workarounds for during the Compile extension development.

- [x] extensions are not loaded for imported components. Their configuration is shown correctly, but the instance can't be received from `harmony.get`. (That's because the extensions are loaded as part of the `ComponentConfig.load` that calls `this.recursivelyRunOnLoadEvent`, which doesn't happen on imported).

- [x] in the config, the extensions are written as package-names. e.g. `{ compiler: "@bit/bit.core.typescript" }`. However, in Harmony, they're saved as BitId strings, e.g. `bit.core/typescript@0.0.1`. There is no easy way to convert between the two, so it's hard to find the extension in Harmony. There are two challenges when trying to convert. 1) the binding-prefix is needed. 2) the version is needed. to get an extension from Harmony, the exact string is needed including the version.

- [x] currently, to load the exact compiler, it's not enough to configure the compile extension with `{ compile: { compiler: "@bit/bit.core.typescript" } }`, it's also needed to add the specific compiler extension by itself as an extension. (this may be fixed already and I might be missing some info about it).

**Comment by GiladShoham** [comment]
@davidfirst The issue with imported are when loading an imported component during the import? or also after the import is done (as part of new process like compiling imported component)

**Comment by davidfirst** [comment]
@GiladShoham , after the import. 
It happens during the load of the component's extensions.

**Comment by davidfirst** [comment]
All were taken care of a while ago.
