### ISSUE TITLE
bit import breaks because of an unmet dependency of an old version

### ISSUE THREAD

**Issue by odedre** [teambit/bit#2685]
### Describe the bug

when importing a component, the one of the old versions of the component has unmet dependencies.

see error below.

### Steps to Reproduce

1. run `bit init`
2. import an entire collection `bit import "bit.evangelist/*"`
3. I get an error on a deprecated component `bit.evangelist/atom/component-highlighter` that has a missing dependency in one of it's old versions from a deleted collection.

### Expected Behavior

bit should show a warning that one of the earlier versions has unmet dependencies but allow the import to continue.

***this part is more like a feature request than a bug:***
consider a step that asks you if you want to import deprecated components as well when you import an entire collection.

### Screenshots, exceptions and logs

```
failed running npm install at /Users/oded/code/evangelist-components/components/content/components-highlight-dictionary   
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://node.bit.dev/@bit%2fbit.base.theme.colors
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/oded/.npm/_logs/2020-05-19T15_15_52_363Z-debug.log

see troubleshooting at https://docs.bit.dev/docs/installing-components

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

### Specifications
  bit version   : 14.7.5-dev.1
  node version  : v10.15.3
  yarn version  : 1.13.0
- Platform: macOs
- Bit compiler (include version): bit.envs.compilers.react-typescript@3.1.52

**Comment by odedre** [comment]
it turns out it wasnt an old version that had a missing dependency, but the latest version (of component `a`) that had a dependency on another bit component (`b`) in an old version, and that version of `b` was using a component (`c`) from a deleted collection.

I removed the problematic component (`a`), so there are no components that use the old version of `b` in the latest version.
I tried to run `bit import "bit.evangelist/*"` again and now I get another error:

```
error: unable to export components to bit.evangelist because they have dependencies on components in bit.base.
bit does not allow setting dependencies between components in private collections managed by different owners.

see troubleshooting at https://docs.bit.dev/docs/bit-dev#permissions-for-collections
```

`bit.base` is the deleted collection that had component `c` in it.
so it looks like this error occurs is because an old version of some of the components have unmet dependencies on the deleted collection.

I can import specific components but I need to do it for the entire collection. how can I continue importing all the components without importing one by one?

**Comment by odedre** [comment]
the error is problematic as well.
- I was importing, not exporting
- the error and link to docs are regarding a permissions issue. the collection `bit.base` was deleted, and Im an admin in bit org so there shouldn't be collections I don't have access to.

**Comment by odedre** [comment]
I also tried adding the `saveDependenciesAsComponents` in `bit.json` and `package.json` but got the same error as before
```
error: unable to export components to bit.evangelist because they have dependencies on components in bit.base.
bit does not allow setting dependencies between components in private collections managed by different owners.

see troubleshooting at https://docs.bit.dev/docs/bit-dev#permissions-for-collections
```

**Comment by itaymendel** [comment]
irrelevant for v15
