### ISSUE TITLE
After Building Components images not Found

### ISSUE THREAD

**Issue by qingxin2016** [teambit/bit#2697]
### Description

I have builded the component successfully and export it to bit.dev
But i found some images used in the scss for background are not found.
some images were transformed base64 image,some not,why?

### Specifications

- Bit version: 14.7.6
- Node version: 10.15.3
- npm / yarn version:  6.4.1
- Platform: windows 10
- Bit compiler (include version): "bit.envs/compilers/vue@0.1.4"
- Bit tester (include version):

**Comment by GiladShoham** [comment]
@qingxin2016 Can you share your component or some way to reproduce this issue?
