### ISSUE TITLE
Bit server always ask for username and password after pushing public ssh key to server

### ISSUE THREAD

**Issue by mcuking** [teambit/bit#2703]
### Describe the bug

I deployed an bit server on my linux server (Centos 7)，and generate ssh key pair on my mac, then push the public key to my linux server. But when I use bit cmd (such as bit ls scope, bit import, bit export...). It always ask for username and password.

### Steps to Reproduce

1. Server: create new user (bit) 
https://www.digitalocean.com/community/tutorials/how-to-create-a-sudo-user-on-centos-quickstart

2. Mac: create ssh key pair and push public key to server
ssh-keygen -t rsa
ssh-copy-id bit@xxx.xx.xxx.xxx
https://phoenixnap.com/kb/how-to-generate-ssh-key-centos-7

3. Server: su - bit

4. Server: install nvm and node, then install bit-bin global

5. Server: 
cd /opt
mkdir bit
cd bit
mkdir mcuking
cd mcuking
bit init --bare

6. Mac: create a front-end project and bit init

7. Mac: bit remote add ssh://bit@xxx.xx.1xx.1xx:/opt/bit/mcuking
It asks for password and username when  i exec bit import/export/ls scope ....

### Expected Behavior

No ask for password and username

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/22924912/83526955-bb198a00-a519-11ea-96d8-3e5b21690fb7.png)

### Specifications

- Bit version: 14.7.6
- Node version: v14.0.0
- npm version: 6.14.4
- Server: CentOS7

**Comment by GiladShoham** [comment]
@mcuking That looks like something wrong with your setup.
I suggest starting with [bit-docker](https://github.com/teambit/bit-docker).
(It's also available in the [docker-hub](https://hub.docker.com/r/bitteam/bit-docker) )
Also, [this issue](https://github.com/teambit/bit-docker/issues/1) might be helpful for you
