### ISSUE TITLE
Unable to access the collection

### ISSUE THREAD

**Issue by rajeshbhatks** [teambit/bit#2711]
Me and my team are having an issue wherein if we go to bit.dev and log in, we see the collections and we can also see the components within our collections. But as soon as I try to click on any one of them, it throws a 404. It is not limited to a specific collection and is across different collections as well.
It is a high priority issue currently as all our builds are failing at this point. Also, there aren't any logs within bit.dev so as to figure out exactly what is going on. None of our pipelines are able to completely run and resulting in our failures. 
This is a high priority issue for us and any immediate help is hugely welcomed.

**Comment by GiladShoham** [comment]
@rajeshbhatks Thanks for reporting this.
Please send your account details to support@bit.dev and we will handle it there.
It's better to write account issues to the support team.
