### ISSUE TITLE
"soft" tags

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2712]
In order to streamline component publishing and allow for better automation practices with Bit the system should provide a way to construct a workflow to allow developers to define the changes they want to apply on components, have them reviewed, so when merged - can be used to automate component publishing.

To do this we'll modify the current behavior of `bit tag` by supporting a new default mode that does not persist the new versions, but instead creates a `changes` file to commit and run the actual tag on a remote machine.

## Create `changes` file when running `bit tag`

When running `bit tag`, instead of setting a new version Bit will create a JSON file with the required information to version each component on a remote machine:

- component ID.
- next version bump (minor, major, patch) / specific version.
- message.
- hash for implementation+deps+config

This will be the default behavior of `bit tag`.

## `--changes-file [file-name]` option

Ability to set the target changes file to create/use when `persist`ing

## `--persist` option

Add `--persist` flag to `bit tag`. This option looks for a `changes.json` file in the project's root dir (or gets a location of the file), it validates the JSON is valid and runs `tag` for all components in the file with the noted version-bump and message.

- when the tag is applied, remove the `changes` file from the workspace.

## `--dry-run` option

Add the ability to do a `dry-run` that validates that the `tag` can actually persist the version bumps as noted in the `changes.json` file.

> should do `bit import` and fetch remote changes to see that there's no collision.

## `bit status` for "soft-tagged" components

All components that are "soft tagged" (ie - logged in the changefile) should have a status "Components set to be tagged" when running `bit status`.

> workspace UI should mention it as well.

## Rerun `bit tag` when there's a changefile

There are two cases here

### adding a new component to be tagged

If there's a changefile and a modified component not logged to the file and i run `bit tag`, add the component to the same changefile.

### 'taggged' component is set to 'tag' once more

If I have a component "soft tagged" in my changefile, and it is modified (ie - the calculated hash differs from what's logged in the changefile), tell the user that the "soft tagged" version has been updated to include the current modifications.

**Comment by GiladShoham** [comment]
few comments:
1. the timestamp make it hard to use it as an input for the `bit tag` command and also for the overwrite checking. I would put the timestamp inside the change file as metadata (maybe also the branch name)
2. if not implement number 1, we might want to consider add a flag `--name` to give the change file a custom name.
3. > Target branch is not up-to-date with remote changes.
Please pull and merge changes before you set components to be published

I would make it a warning and give you the option to continue, it might be unrelated changes I'll merge manually later. it also enforce me to have network connection for this local operation.

4. > If remote versions found prompt this message and stop the process

Again, I might be ok with this. maybe there is v2.0.0 of a component and I wan't to generate 1.0.1 hotfix. My branch might be originated from an old tag in git and not from the tip of master.
Let me decide about it.

5. auto tag should have similar process of selecting a version (it's an old issue we have, we used to decide it always a patch version but it might be wrong. maybe I'm a proxy for one of my dependency, so once it get major, I should get one as well.
About messages for auto tag, we can give this option but it not must (we can just show you the default message of `patch version updated due to dependency...` and let you override it if you want. but we can live without this feature.

6. I would make the commit back and push optional (default true or false is up to you). sometimes this enforce me to configure my ci to have git push permission.

**Comment by itaymendel** [comment]
1. fine.
1. can add it as well, but if we agree on #1 its not as relevant.
1. it might cause issues in the future. i really think we want to ensure people are working on the tip of the branch.
1. my bad, forgot to delete the "and stop the process". it should be just a warning. you are correct.
1. I thought about it as well, the fact that we're creating a change-file means that a developer can go and modify it... so they can update the "next-version" as well as the "message". Regardless, this can be improved and we can loop through all auto-tags OR give a summary and let user decide if they want to override.
1. commit-back is not a bit-feature, just an example for what can be done by each team.

**Comment by GiladShoham** [comment]
@itaymendel 
2. agree, if we do 1, this becomes nice to have and low priority
3. let's make it the default, and add a flag to skip / suppress (make it a warning only)
5. There is a file, but it's bad ux to pass you through this flow for each component, then for auto tag ask you to edit the file manually. let's add them to the flow (with the option to hit enter enter enter for defaults, or a first question that asks you if you want to loop through the auto tags - and explaining you what is the default and that you will be able to edit it later manually) and hint you in the end anyway that you can edit this file manually
6. ok great:)

**Comment by itaymendel** [comment]
@GiladShoham I'm also considering another change, perhaps instead of supporting changefile in tag/export we add a new command dedicated for this flow - `bit publish`? This will simplify a lot for developers that want to automate stuff (sugar syntax mostly, but also will consider tag+export as a single task that can fail, as with the suggested flow either of them might fail).

**Comment by GiladShoham** [comment]
@itaymendel I'll think about it. a bit afraid to use `bit publish` for this, since we might want it for something else in the future. 
maybe `bit apply`?

**Comment by davidfirst** [comment]
@itaymendel , looks good!!
The only thing I'm missing in the Synopsis is the component-id(s). For users that prefer to skip the prompt, it'd be easier to specify the component-id, which should support wildcards.

**Comment by itaymendel** [comment]
The way I was looking at it is that this command manages the change-file. Perhaps we can replace the `--all` flag with something that will allow me to define glob-patterns (or change the entire command so the argument is a glob-pattern and the change file is an option?).

**Comment by davidfirst** [comment]
> (or change the entire command so the argument is a glob-pattern and the change file is an option?)

Yes, that makes more sense to me.

> The way I was looking at it is that this command manages the change-file

I guess we'll need an option for users to run one command to create this file. 
It's cumbersome to go through the prompt questions when normally using the same settings (say, `--all --patch`).

**Comment by itaymendel** [comment]
@davidfirst @GiladShoham i've updated everything per the inputs. also added the `bit apply` command to provide better ux when publishing components.

**Comment by davidfirst** [comment]
Discussed with @itaymendel and @ranm8 . Agreed on the following changes:
1. The hash will be in a later phase. For now, the changes file won't contain the hash and whatever changes pushed to git, they'll be tagged and exported.
2. the soft-tagged components will be in the modified status for now. However, to not confuse the users, we'll add `(soft tagged)` note next to these components.

**Comment by davidfirst** [comment]
Implemented with the changes described above. 
The `--dry-run` was not implemented as it's less crucial and can wait for phase2.
A new flag `--persisted` was added for `bit untag`, so it's possible to remove actual tags. Without the flag, it only removes soft-tags.
This feature wasn't tested thoroughly just yet.
