### ISSUE TITLE
Keep symlinks of src files on node_module in sync 

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2729]
With Harmony, the compiler is running on the symlinks in node_modules that are linked to the actual source files.
The problem is that if a file is added, there is no process that symlinks it to node_module. Same when a file is removed, it needs to be removed from node_modules as well.

GiladShoham , ranm8 , suggestions are welcome.
Keep in mind that this sync needs to happen on `bit watch` as well, so it must be fast.

**Comment by GiladShoham** [comment]
Good point.
We might need to add our own watcher on the src dir, and try to configure it to only listen to add/remove or at least only react to add/remove.
chokidar has these events: add, unlink, addDir, unlinkDir

**Comment by davidfirst** [comment]
@GiladShoham , correct, we actually use `chokidar` for `bit watch`, and we monitor all these changes, so we can unlink/symlink when a file is removed/added before compiling. The performance will be fine.
However, when running `bit compile`, there is no easy way to know whether a file was added or removed. Running "bit link" on all components does have a performance hit.

**Comment by GiladShoham** [comment]
1. I don't think it will be so dramatic performance wise in bit compile. We already do much more expensive operations like checking the component status (we might check links only for modified components)
2. That's fine that compile will be slower than watch.
But we still need to see how impactfull it is.

**Comment by GiladShoham** [comment]
@davidfirst Is this still relevant after the changes to the links we did a month ago?

**Comment by davidfirst** [comment]
@GiladShoham , yes. This part is not implemented yet. It's less important then before, because now we show a warning in `bit status` when using a non-main file. 
This is still relevant though for files such as `.scss` and `.json`, which we don't show the warning and users need to import them.
