### ISSUE TITLE
CLI: user input not preserved while executing

### ISSUE THREAD

**Issue by JGJP** [teambit/bit#2743]
### Describe the bug

While a bit command is executing, such as when `bit status` is fetching from the server, any user input is not preserved. It's standard behavior across CLIs that when a command is executing you can start typing the next command you want to execute such as:
```
git add -A
git commit -m wow
git push
```
I don't have to wait for the `add` command to finish before typing `git commit`

### Steps to Reproduce

1. execute `bit status`
2. continue typing anything in shell
3. input is lost upon command completion

### Specifications

- Bit version: 4.7.6
- Node version: 12.16.2
- npm / yarn version: 1.22.4
- Platform: macOS 10.15.5
- Shell: Fish 3.1.0, Bash 3.2.57(1)-release

**Comment by itaymendel** [comment]
i think this might be an issue with commander. @GiladShoham , will yargs help us resolve this?

**Comment by davidfirst** [comment]
This might be related to the issues we were having with Ora. (see https://github.com/teambit/bit/pull/3760).
I just tried to reproduce it (`bit status` and while it was processing, `bit add`) and it seems to work fine.
