### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by amitmankotia** [teambit/bit#2758]
### Description

Module not found: Can't resolve '@bit/component' in '/capsule/src/App'

### Specifications

- Bit version:6.4.1
- Node version: 8.12.0
- npm version:6.4.1
- Platform:macOS
- Bit compiler (include version): react@1.0.18
- Bit tester (include version): NA

### Context and additional information

I am able to use sidebar component in my local project using npm module but not here in the overview. It says can't resolve filename.

![image](https://user-images.githubusercontent.com/26850050/85079183-c9d39280-b1e3-11ea-84a2-35357e88d49e.png)

**Comment by fcisio** [comment]
Hey, I'm having the same issue.
I basically want to import a "theme" which I currently have as a component. It's not a dependency and should not be.

In the playground, I basically use a ThemeProvider in which I want to add my theme.

My collection is private, could it be causing the issue.
Thanks

**Comment by itaymendel** [comment]
playground feature has been re-implemented and now works as a local setup as well, giving more control for such cases. this way you can add theme-context as a dependency just for the playground and see that it is working properly before publishing


We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
