### ISSUE TITLE
I cannot tag a component that uses AsyncSelect(which is taken from "react-select/async")

### ISSUE THREAD

**Issue by VCuzmin** [teambit/bit#2760]
I cannot tag a component that uses AsyncSelect(which is taken from "react-select/async")

I have a component that I'd like to export to my own collection. It has the following import:

`import AsyncSelect from "react-select/async";
`
But when I want to tag the component, Bit throws an exception:
![image](https://user-images.githubusercontent.com/40390118/85263226-86915200-b477-11ea-82e5-5c63f5c1b7dd.png)

The only way in which I can get the AsyncSelect is as above, no other ways.

The company which I'm working for bought the business license(200/month) and it could give up the license if this problem won't be fixed.

What can I do in order to fix this issue?
Thanks a bunch!

**Comment by JoshK2** [comment]
Hi, the first thing you need to check is if the package `react-select/async` is installed in your project and appears in the `package.json` file.

**Comment by VCuzmin** [comment]
Thanks for your answer but I have react-select package installed. I cannot install react-select/async package on its own.

**Comment by VCuzmin** [comment]
What can I do in this case?

**Comment by JoshK2** [comment]
Please join us on [Slack](https://join.slack.com/t/bit-dev-community/shared_invite/enQtNzM2NzQ3MTQzMTg3LWI2YmFmZjQwMTkxNmFmNTVkYzU2MGI2YjgwMmJlZDdkNWVhOGIzZDFlYjg4MGRmOTM4ODAxNTIxMTMwNWVhMzg)

And contact me in private: Josh Kuttler, I'll help you with this.

**Comment by JoshK2** [comment]
For now, I try to reproduce the error.

**Comment by VCuzmin** [comment]
Ok. Thank a lot! See you on Slack!

**Comment by GiladShoham** [comment]
@VCuzmin Just tried to create some mock component:
```js
import React from "react";
import ReactDom from "react-dom";
import AsyncSelect from "react-select/async";

console.log(AsyncSelect)
```
`bit status` is work as expected
```
new components
(use "bit tag --all [version]" to lock a version with all your changes)

     > comp ... ok
```

**Comment by VCuzmin** [comment]
Try to tag it

**Comment by GiladShoham** [comment]
@VCuzmin 
Tagged it without any issue.
You closed the issue, so I guess you figured it out.

**Comment by VCuzmin** [comment]
Yes. Thx

Trimis din Outlook Mobile<https://aka.ms/blhgte>

________________________________
