### ISSUE TITLE
Adding an extension to a workspace

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#2778]
Adding an extension to a workspace should be a simple and straight forward process handled by a dedicated command.

## Adding a new extension

```
$ bit use <extension>
```

> by default extension is configured to the workspace

### Specify to which `variant` an extension should be installed to

```
$ bit use <extension> --variant <variant-name>
```

> Should support an array of variants

### Add an extension to a `variant` and the workspace

```
$ bit use <extension> --variant <variant-name> --workspace
```

### Set configuration key-value pairs when adding an extension

```
$ bit use <extension> --set <key>=<value> --set <key2>=<value2>
```

**Comment by GiladShoham** [comment]
This command should also import the extension objects into the scope if it missing

**Comment by GiladShoham** [comment]
@itaymendel we should define what happens when i already have the extension configured.
Nothing? Warning about it?
Update extension version?
Override config?

**Comment by GiladShoham** [comment]
we should also make sure that when we re-write the workspace.jsonc during this process we won't delete existing comments from the file.
