### ISSUE TITLE
Angular Bit Compiler doesn't expose service & component in public_api.ts

### ISSUE THREAD

**Issue by kikz816** [teambit/bit#2782]
### Describe the bug

When executing "ng build <component>" the generated public_api.ts includes the service, component, & module. But when executing "bit build <component>" the BIT generated public_api.ts only has exposed the module and as a result I can't use the service in my component in another application coz it is throwing me the error below:

```
Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
```

### Steps to Reproduce

1. Create angular library. 
2. Bit init
3. Bit add <component>
4. Bit build <component>

### Expected Behavior

The generated public_api.ts after executing bit build <component> should expose the service, component, & module
![image](https://user-images.githubusercontent.com/67641180/86177974-1b700b80-bb5a-11ea-87d1-d150d9685e50.png)

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/67641180/86177947-0e531c80-bb5a-11ea-9dc8-3cca29775d6d.png)

### Specifications

- Bit version: 14.8.1
- Node version: 12.5.0
- npm version: 6.14.5
- Platform: Angular 9.1.0
- Bit compiler (include version): bit.envs/compilers/angular@9.0.17
- Bit tester (include version): NA

**Comment by GiladShoham** [comment]
@kikz816 Thanks for reporting this.
We will check this and update you.
We should check if it's a bug in bit or in bit angular compiler.
@JoshK2 let's check it.
