### ISSUE TITLE
is "bit publish" component to private registry ready ?

### ISSUE THREAD

**Issue by nvthuong1996** [teambit/bit#2783]
Bit has a new version. But I have yet to find the document guide publish component to private registry.

**Comment by GiladShoham** [comment]
The publish to private registry is not yet production-ready.
It will be part of the next major release.

**Comment by nvthuong1996** [comment]
Bao lâu cho đến khi phiên bản này được phát hành

**Comment by GiladShoham** [comment]
I believe it will be out for beta in a few weeks, and few weeks later for production.

**Comment by nvthuong1996** [comment]
thank you

**Comment by itaymendel** [comment]
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
