### ISSUE TITLE
Add support for more licenses

### ISSUE THREAD

**Issue by noah-friedman** [teambit/bit#2792]
### Description
There are few available licenses for component collections, and users might want to mark their components as licensed while using alternate licenses.

### Describe the solution you'd like
Add a wider variety of licenses available for component collections on [bit.dev](https://bit.dev).

*NOTE: I'm quite to new to opening issues, so I apologize if I haven't provided proper information in this post.*

**Comment by benjgil** [comment]
Hi @noah-friedman - do you have a list of alternative licenses that you think could be valuable for the Bit community?

(not promising we'll provide for all of them

**Comment by noah-friedman** [comment]
I'd recommend adding [the Unlicense](https://unlicense.org/) (or something like it), as well as the [Eclipse Public License](https://www.eclipse.org/legal/epl-2.0/), versions [1](https://www.eclipse.org/org/documents/epl-v10.html) and [2](https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html).
