### ISSUE TITLE
Harmony - backward compatibility & migration (wip/discussion)

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#2795]
Harmony is the next major version.
There should not be any breaking changes for existing (legacy) projects.

The way how a workspace is determined to be legacy or Harmony is by the workspace config file. Legacy workspaces use `bit.json` or the `bit` prop in `package.json`. Harmony workspaces use the new `workspace.jsonc` file.

The way how a component is determined to be legacy or Harmony is by the `schema` field. Legacy components don't have this field. Harmony components have it with the value `1.0.0`.

Tagging components on Harmony, regardless of whether they were legacy before, make them Harmony components.
However, Harmony blocks a component from tagging unless the following conditions are met:

- The component doesn't require another component using relative paths. Only module paths are allowed. (to automatically convert the import/require statements from relative paths to module paths, run `bit link --rewire`.)
- As authored, the component needs to be added as an entire directory and not individual files.
- custom-module-resolutions (a.k.a. aliases) can't be used.

Some consequences:
- the originally shared-dir is not stripped anymore, so if the component was added from `src/component/ui/button` and imported as `button`, after tagging, it'll be imported with the entire path: `src/component/ui/button`.
- the legacy compilers/testers can't be used. 
- `wrapDir` which helps components to track package.json is not supported anymore.

Currently, when importing a legacy component into Harmony, it preserved the old directory structure, which means, the "dists" and "package.json" are in the component dir. For Harmony components, they're saved inside the node_modules of the component package.

### Backward Compatibility

1. Legacy components imported into Harmony workspace.
2. Harmony components imported into legacy workspace. Should we support this?
Needs to be tested.

### Migration
To re-start a workspace as Harmony, run `bit migrate --harmony`. This command does the following:
* if a legacy `bit.json` exists, it renames it `bit.json.legacy`.
* if a legacy "bit" prop in package.json exists, it renames the prop to "bit-legacy".
*  it converts all "trackDir" in .bitmap to "rootDir".

The next step is to run `bit status`. It shows all the problems that need to be fixed for Harmony and a suggestion as to how to fix them. (relative-paths/individual-files).

As a side note, running `bit init --harmony` doesn't create workspace.jsonc. The feature "harmony" needs to be set and old bit.json or "bit" prop in the package.json needs to be removed. Also, the .bitmap needs to be removed. This command is to start fresh, not to migrate an existing workspace.

Todo
- [ ] Once the .bitmap changes of the files are ready, remove all files from .bitmap. (@GiladShoham ).
- [ ] change the .bitmap schema to be 1.0.0 (@GiladShoham ).

**Comment by itaymendel** [comment]
we'll not going to handle migration from legacy to harmony. closing this ticket.
