### ISSUE TITLE
How to import dependencies from node_modules in scss file?

### ISSUE THREAD

**Issue by ziven27** [teambit/bit#2801]
### Description

```SASS
// works fine
@import "@_nu/css-acss";

// missing packages dependencies
@import "~@_nu/css-acss";
```
How to import dependencies from node_modules in scss file?

I knonw `"@": "src"` is for src ,

```JSON
    "aliases": {
      "@": "src",
      "~@": "src"
    }
```
but how to aliases  a dir start from `node_modules`?
I try `"~":"node_modules"`, `"~@_nu":"node_modules/@_nu"` but it dose not work.

### Specifications

- bit version   : 14.7.6
- node version  : v12.16.3
- npm version   : 6.14.4
- yarn version  : 1.17.0
- platform      : darwin

**Comment by noah-friedman** [comment]
Don't know if this helps at all, but when I import bootstrap from node_modules I have to use the path `~bootstrap/scss/bootstrap` to specify where to look for the actual scss source file.

**Comment by itaymendel** [comment]
this is unrelated to bit
