### ISSUE TITLE
bit test gives error for async tests

### ISSUE THREAD

**Issue by manishiitg** [teambit/bit#2804]
### Describe the bug

A clear and concise description of the issue.

### Steps to Reproduce

i have an empty test defined 

```
test("userlist click calls api shows error message properly", async () => {

    

})
```

but if i add the async keyword i get the error below

### Screenshots, exceptions and logs
```
 ● Test suite failed to run

    ReferenceError: regeneratorRuntime is not defined

       95 |   expect(container.querySelectorAll("table > tbody > tr").length).toBe(0); // we have empty table
       96 | });
    >  97 | test("userlist click calls api and shows loading", /*#__PURE__*/_asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee() {
          |                                                                                                 ^
       98 |   var _render2, container, getByText, queryByText, button;
       99 | 
      100 |   return regeneratorRuntime.wrap(function _callee$(_context) {

      at Object.<anonymous> (userlist.test.js:97:97)
### Specifications

```
- Bit version: latest
- Node version: 14
- npm / yarn version:
- Platform: windows wsl 2.0
- Bit compiler (include version): react
- Bit tester (include version): jest

**Comment by GiladShoham** [comment]
Will be solved in the next major (harmony) version

**Comment by itaymendel** [comment]
entire jest flow has been updated in bit v15 to support such cases

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
