### ISSUE TITLE
UI for components, is bit.dev designs for viewing components like storybook?

### ISSUE THREAD

**Issue by manishiitg** [teambit/bit#2805]
### Description

I have a question, i am using bootstrap is my project for my designs. 
This is plan bootstrap i.e included via <script> tag

Now if i share by component on bit.dev can i even include bootstrap library so that proper design shows up.
I can do the same when i use storybook but can i do this in bit.dev

Is bit.dev even designed to achieve this? or is it just to be able package your component and share them?

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
you can do just that. but bit can be used to share far more than just basic design-system components. you can share hooks, widgets and even pages as components.
