### ISSUE TITLE
compatibility problem between 14.7.* and 14.8.6

### ISSUE THREAD

**Issue by gogoyqj** [teambit/bit#2806]
### Describe the bug

with a bit.json

```json
{
  "extentions": {}
}
```

with bit version @14.8.6(update from @14.7.0)

### Steps to Reproduce

run `bit status` or any other command throws `_this$extensions.toObject is not a function`

**Comment by davidfirst** [comment]
@GiladShoham , I fixed locally this error, but then I got another error:
```
failed to load an extension for component bit.envs/compilers/stencil@0.0.25, error is:
error: component "bit.extensions/defaults/webhooks@0.2.1" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)
the error has been ignored
```

Which lead me to think that now Bit refers to the legacy extensions as if they were new regardless of whether the workspace is new or legacy. I know that this legacy extensions feature was never intended for production and we warned that it could be changed anytime. So, just to make sure, from this point, we are not supporting this old extensions?

**Comment by suxin2017** [comment]
version 14.8.8 is the same

```js
_this$extensions.toObject is not a function
```

Is it no longer supported to expand？

**Comment by davidfirst** [comment]
@suxin2017 , correct. This type of extension is no longer supported. A new extension system is under rapid development and will be part of the next major release.

**Comment by itaymendel** [comment]
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
