### ISSUE TITLE
bit init --standalone doesn't work

### ISSUE THREAD

**Issue by remo1** [teambit/bit#2807]
### Describe the bug

bit init --standalone is not working. Even if I initialise the bit with standalone flag, bit continues to write the scope/compilers/etc in .git/.bit

### Steps to Reproduce

1. run bit init --standalone
2. import components
3. check where the bit init is saved

### Expected Behavior

bit saved the bit data in .bit instead of .git/.bit

**Comment by davidfirst** [comment]
@remo1 , I'm not able to reproduce the issue. I followed your steps and all bit data was saved into `.bit` dir and not in `.git/bit`.
Can you please specify the bit-bin version you're working on, and the OS?

**Comment by remo1** [comment]
the version is 14.8.6, it's macOS

**Comment by davidfirst** [comment]
@remo1 , that's odd, I tried with the same version and I have the same OS.
Can you try again with the exact same steps you described above?

**Comment by GiladShoham** [comment]
@davidfirst did you have .git folder prior to the init command?

**Comment by GiladShoham** [comment]
@remo1 I tried as well without be able to reproduce it.
Any chance you already initialized bit without standalone? then tried re-init with standalone?
in that case, it won't work, you should first delete the scope from the git folder, then run the init again. 
or you can just move it outside and add `.` in the beginning `bit` to `.bit`
