### ISSUE TITLE
Bit doesn't tag or build

### ISSUE THREAD

**Issue by noah-friedman** [teambit/bit#2809]
### Describe the bug
Can't tag or build components after updating from 14.8.4 to 14.8.6.

### Steps to Reproduce

1. Install bit@14.8.4 via yarn
2. Update to bit@14.8.6
3. Attempt to tag or build component
4. Bit will hang on "isolating component..."

### Expected Behavior

Components should build, but instead the process hangs.

### Specifications

- Bit version: 14.8.6
- Node version: 14.5.0
- npm / yarn version: Yarn 1.22.4
- Platform: Mac OS 10.15.5
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.54
- Bit tester (include version): noah-friedman.envs/testers/jest@24.9.1

**Comment by davidfirst** [comment]
@noah-friedman , could you please add me as a collaborator (david@bit.dev) so I could import the component to reproduce the issue?
In general, I'm able to tag/build typescript components using the compiler above with this 14.8.6 version.

**Comment by noah-friedman** [comment]
If you mean the component I'm trying to tag, I have been unsuccessful at tagging it initially, so it's not yet on bit.dev. If you mean the tester, I'm adding you as a collaborator now.

**Comment by GiladShoham** [comment]
@davidfirst please share your findings.. If we have a regression we will release a hotfix

**Comment by davidfirst** [comment]
@noah-friedman , can you zip the component you're trying to tag and send it? (it'd be best if you could send it to both of us me and Gilad: david@bit.dev and gilad@bit.dev we work on different timezones so it'd be faster to fix).

**Comment by noah-friedman** [comment]
@davidfirst I've emailed the zip to you and @GiladShoham, thank you both for taking the time to help me out.
If it's any help, I was able to run `bit tag` with a debugger and have attached a file with the contents of the debug console (too long to add inline in the comment). If there's any more information you need, let me know.

[log.txt](https://github.com/teambit/bit/files/4881765/log.txt)

**Comment by juanpamv** [comment]
Hi I'm having the same issue, last week it starting to show me this error when I try to tag or build: error: version "latest" was not found. So I updated to latest version, if I run bit -v it show the latest one, but still seeing the same error when I try to tag a component: "error: version "latest" was not found."

**Comment by davidfirst** [comment]
@juanpamv , I don't think this is the same issue. In the above case, it hangs without showing any error, in your case you get an error. I'd suggest opening a new issue.

**Comment by davidfirst** [comment]
@noah-friedman , thanks for sending the files! I was able to reproduce the issue and I fixed it in the PR above. 
I'm planning to release a new "dev" version today so it won't block you.

**Comment by davidfirst** [comment]
@noah-friedman , I released a new version with the fix. If you still experiencing issue with this version, please re-open.

`npm install bit-bin@14.8.7-dev.1`

**Comment by juztinlazaro** [comment]
im having a same issue in version `14.8.8`
