### ISSUE TITLE
Bit tag is erasing my components code...

### ISSUE THREAD

**Issue by solarstar101** [teambit/bit#2822]
### Describe the bug
Attempting to tag a component 
component is tagged successfully however  when I go into my components src code it has been replaced with this 

/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

module.exports = require('../../../../../../../dist/Toggle');

A clear and concise description of the issue.

### Steps to Reproduce

1.Tag component after making changes
2.thats it

### Expected Behavior
for my component to be tagged and the code to not be removed..

### Specifications

- Bit version:14.8.6
- Node version:12.18
- npm / yarn version:6.14
- Platform:
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.54   
- Bit tester (include version):

**Comment by solarstar101** [comment]
no idea how ended up just adding the code back....just ctrl z...

1) did a bit export of the component
2) ctrl z back the code that was erased..
3). checked on bit.dev code appears to be present and component appears to be building fine.


ive been having weird issues with bit and we're considering using it for our company to house all our components I am hoping this is not a persistent trend but will keep updating

**Comment by seonghyeonkimm** [comment]
@solarstar101 You solved this problem?

**Comment by davidfirst** [comment]
@seonghyeonkimm , any idea how to reproduce it?

**Comment by s97712** [comment]
+1
