### ISSUE TITLE
bit login on WSL2

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#2848]
How do I log in to bit with WSL2?

**Comment by GiladShoham** [comment]
Bit login work by creating a local HTTP server for the login process, then get the token to the terminal from the browser after successful login.
WSL by default creating a NAT (a virtual network) which means the browser has no access to the terminal.
To work around you can do a few things:
1. configure the WSL2 to bridge mode (you can find some explanation here - https://github.com/microsoft/WSL/issues/4150)
2. since bit login is usually one-time process, I would recommend to just run it without WSL (on the host machine itself from cmd / powershell, or any other temp machine, you can even run it on a friend machine, take the token and logout). this will create your token, then you can grab it by running `bit config get user.token` and set it on the WSL2 bit instance via `bit config set user.token [your token]`

**Comment by ianef** [comment]
As a newbie to bit I can't help thinking that both these methods are pretty poor. In 1 you expecting users to totally reconfigure how  networking works in WSL thus probably wrecking every other network related function that they currently have working. In 2 you expect that users need to install Bit outside of WSL 2, even on a friends machine, and copy the token, what if things don't work out, constantly switching machines (virtual or not), visiting friends, copying, pasting, copying, pasting. I think not, is this 2021, it feels more like 1990!

At some point during my Bit initiation it did ask me for my credentials in order to export my test components. Can we not do the same during *bit login* with maybe an *--interactive* flag and automatically store the token.

The current approaches are less than third rate and you are seriously underestimating the number of WSL and VSCode users out there.

**Comment by ianef** [comment]
This gets worse! The windows bit.exe does nothing!

So I've tried to install Bit in Windows. Well that's a laugh from the word download! Download the exe, copy and paste it elsewhere, then rename it. Well we are in familiar territory here aren't we!

Guess what! it doesn't work, bit does nothing, no response, no errors, nothing!

I'll open a ticket for this but seriously guys, this is total crap!

**Comment by ianef** [comment]
Trying to use *bit login* on a headless Linux system also fails as it tries to open a browser for logging it, same problem as in WSL.

**Comment by PaulPCIO** [comment]
I agree @ianef that this process is really broken. Also having the same issue.

**Comment by benjgil** [comment]
Hi @ianef 

Sorry to hear your experience of bit hasn't been great so far.

Re: downloading bit to Windows, what version of Bit are you using?

The most current version of Bit, Harmony, uses a Bit Version Manager tool with which there should be no need to copy paste any files anywhere. You may need to set a path value, but that's pretty standard for tool installation.

Please see installation instructions for the latest version here:
https://harmony-docs.bit.dev/getting-started/installing-bit

**Comment by GiladShoham** [comment]
First I really sorry about your experience.
@ianef How did you install bit? we really recommend using bvm for [installing bit](https://harmony-docs.bit.dev/getting-started/installing-bit)
If you need the legacy version, I would recommend using npm - `npm i -g bit-bin`

about your interactive suggestion, we thought about it, however, it will be also not a great solution, as many users use github / sso to login to bit. in that case they don't have a user/pass to enter to the interactive shell. they need a browser.

One possible solution is to login from a regular cmd instead of via wsl, I'm not a windows expert, but I believe it should be possible to run a regular cmd or powershell on the same machine you are using with wsl. in that case, it will configure your bit token and you then can continue using the wsl.

Another option is to add an option to generate a token from the UI, then you can just put it in the bit config in the terminal.
@itaymendel what do you think?

**Comment by PaulPCIO** [comment]
I just started exploring bit this week to possibly implement it in our org, I installed it following that [guide](https://harmony-docs.bit.dev/getting-started/installing-bit/). So It was a fresh install without any legacy environment(s).

So yea the only solution was to:
1. Install bit on my `windows environment` using _`powershell`_
2. Install bit on my `wsl2 environment` using _`bash`_
3. Log in to bit on my windows environment.
4. Grab the token from the logged-in session: `bit config get user.token`.
5. Go back to my `wsl2` environment and configure that token `bit config set user.token [your token]`.

@GiladShoham I think a better solution/fix should be investigated,  The [`vercel cli`](https://vercel.com/cli) works fine on `wsl2` and I believe they are using quite the same method as the `bit cli`?

**Comment by AlexandroPerez** [comment]
@PaulPCIO  So while in the middle of trying to install bit directly on windows, I noticed that the token that we need to configure in `bit config set user.token`, is part of the url we get back from the unreachable localhost:

*`http://127.0.0.1:8085/?clientId=...&redirectUri=https...`***`&token=e83*****-****-****-****-************`***`&username=...`*

So all I did was copy that token from the url as soon as I got it back, went to the `wsl` terminal, and entered
```
bit config set user.token [token from url]
```

And I was set to go. Now `bit login` works.

**Comment by KutnerUri** [comment]
yes, `bit login` only automates getting the token from the site. We modeled it after gcloud's login command.
Maybe we could make a manual version of this process for these cases. (copy `clientId` from CLI, create token, and copy back to CLI) @itaymendel - what do you think?

Also, you could log in with SSH key pair instead. The regular login worked smoothly so I haven't used it in a couple of years.
Check it out at your personal authentication settings:
https://bit.dev/settings/authentication

**Comment by MarcoMacedoP** [comment]
Why is this issue closed?
I've just face it today. Thankfully, the solution by @AlexandroPerez worked fine.

**Comment by tfsousa** [comment]
Bump, still facing this issue. @AlexandroPerez method still works surprisingly.

**Comment by KutnerUri** [comment]
@GiladShoham - just make a manual (copy and paste) version of the command.
The problem is the browser trying to forward the key to the terminal.
