### ISSUE TITLE
Can't add a Readme.md file to remote repository

### ISSUE THREAD

**Issue by gersonj13** [teambit/bit#2849]
## Expected Behavior
I want to add a readme.md file to my component

## Actual Behavior
I'm working with Quasar. So I've tried to add a Readme.md to my component, but when I try to Tag it, this error is shown

![image](https://user-images.githubusercontent.com/1985198/87708525-e1655300-c770-11ea-84ef-aa5492c9be44.png)

## Steps to Reproduce the Problem

  1. add file to a new component component
  2. use bit tag --all
  3. error uploading (image attached before)

## Specifications

  - Bit version: 14.8.8
  - Node version: 12.16.3
  - npm / yarn version: npm: 6.14.4   yarn: 1.22.4
  - Platform: quasar/vue
  - Bit compiler (include version): https://bit.dev/bit/envs/bundlers/vue 2.6.21

**### I've also installed a .md loader for vue and added to quasar config**

**_vue-markdown-loader_**

**### My quasar config:**

// Configuration for your app

module.exports = function(ctx) {
  return {
    // app boot file (/src/boot)
    // --> boot files are part of "main.js"
    boot: [
      'apollo',
      'axios',
      'google-maps',
      'i18n',
      'vee-validate',
    ],

    css: [
      'app.styl'
    ],

    extras: [
      'roboto-font',
      'material-icons', // optional, you are not bound to it
      'ionicons-v4',
      // 'mdi-v3',
      'fontawesome-v5'
      // 'eva-icons'
    ],

    framework: {
      // all: true, // --- includes everything; for dev only!

      components: [
        'QAvatar',
        'QBar',
        'QBtn',
        'QBtnDropdown',
        'QBreadcrumbs',
        'QBreadcrumbsEl',
        'QBtnGroup',
        'QCard',
        'QCardActions',
        'QCardSection',
        'QChip',
        'QDrawer',
        'QExpansionItem',
        'QFab',
        'QFabAction',
        'QFooter',
        'QHeader',
        'QImg',
        'QDate',
        'QLayout',
        'QHeader',
        'QPageContainer',
        'QPage',
        'QPopupProxy',
        'QToolbarTitle',
        'QIcon',
        'QInput',
        'QList',
        'QItem',
        'QItemSection',
        'QItemLabel',
        'QInput',
        'QLayout',
        'QPageSticky',
        'QPageScroller',
        'QPageContainer',
        'QPage',
        'QPopupProxy',
        'QSelect',
        'QScrollArea',
        'QSpace',
        'QToolbar',
        'QRadio',
        'QCardSection',
        'QCardActions',
        'QImg',
        'QExpansionItem',
        'QSelect',
        'QSplitter',
        'QResizeObserver',
        'QTable',
        'QTh',
        'QTr',
        'QTd',
        'QTabs',
        'QTab',
        'QTimeline',
        'QTimelineEntry',
        'QRouteTab',
        'QDialog',
        'QSeparator',
        'QStepper',
        'QStep',
        'QSlider',
        'QStepperNavigation',
        'QTabPanel',
        'QCheckbox',
        'QOptionGroup',
        'QBtnToggle',
        'QScrollObserver',
        'QTabPanels',
        'QTabPanel',
        'QTooltip',
        'QToggle',
        'QPopupEdit',
      ],

      directives: [
        'Ripple',
        'ClosePopup'
      ],

      // Quasar plugins
      plugins: [
        'Notify',
        'Dialog',
        'Loading',
        'Meta',
        'LoadingBar'
      ],
      config: {
        loadingBar:{
        color: "green-9"
        }
      },
      // iconSet: 'ionicons-v4'
      lang: 'es', // Quasar language
    },

    supportIE: true,

    build: {
      scopeHoisting: true,
      // vueRouterMode: 'history',
      // vueCompiler: true,
      // gzip: true,
      // analyze: true,
      // extractCSS: false,
      extendWebpack(cfg) {
        cfg.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /node_modules/,
          options: {
            fix: true
          }
        })
		 cfg.module.rules.push({
      test: /\.md$/,
      loader: 'vue-markdown-loader'
    })
      }
    },

    devServer: {
      // https: true,
      // port: 8080,
      open: true // opens browser window automatically
    },

    // animations: 'all', // --- includes all animations
    animations: [],

    ssr: {
      pwa: false
    },

    pwa: {
      // workboxPluginMode: 'InjectManifest',
      // workboxOptions: {}, // only for NON InjectManifest
      manifest: {
        // name: 'Quasar App',
        // short_name: 'Quasar-PWA',
        // description: 'Best PWA App in town!',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#ffffff',
        theme_color: '#027be3',
        icons: [{
            'src': 'statics/icons/icon-128x128.png',
            'sizes': '128x128',
            'type': 'image/png'
          },
          {
            'src': 'statics/icons/icon-192x192.png',
            'sizes': '192x192',
            'type': 'image/png'
          },
          {
            'src': 'statics/icons/icon-256x256.png',
            'sizes': '256x256',
            'type': 'image/png'
          },
          {
            'src': 'statics/icons/icon-384x384.png',
            'sizes': '384x384',
            'type': 'image/png'
          },
          {
            'src': 'statics/icons/icon-512x512.png',
            'sizes': '512x512',
            'type': 'image/png'
          }
        ]
      }
    },

    cordova: {
      // id: 'org.cordova.quasar.app'
      // noIosLegacyBuildFlag: true // uncomment only if you know what you are doing
    },

    electron: {
      // bundler: 'builder', // or 'packager'

      extendWebpack(cfg) {
        
      },

      packager: {
        // https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#options

        // OS X / Mac App Store
        // appBundleId: '',
        // appCategoryType: '',
        // osxSign: '',
        // protocol: 'myapp://path',

        // Window only
        // win32metadata: { ... }
      },

      builder: {
        // https://www.electron.build/configuration/configuration

        // appId: 'quasar-app'
      }
    }
  }
}

**### and mi bit config included in package.json:**

{
  "name": "workflow-cliente",
  "version": "0.0.1",
  "description": "Modulo de atencion al cliente de Workflow",
  "productName": "Quasar App",
  "cordovaId": "org.cordova.quasar.app",
  "author": "German germanbeta@gmail.com",
  "private": true,
  "scripts": {
    "lint": "eslint --ext .js,.vue src",
    "test": "echo \"No test specified\" && exit 0"
  },
  "dependencies": {
    "@bit/pangeacd.componentes-cd.cliente-http": "^1.0.0",
    "@bit/pangeacd.componentes-cd.notificacion": "^1.0.0",
    "@bit/pangeacd.componentes-cd.settings": "^1.0.0",
    "@quasar/extras": "^1.5.1",
    "@riophae/vue-treeselect": "^0.4.0",
    "apollo-cache-inmemory": "^1.6.3",
    "apollo-client": "^2.6.4",
    "apollo-link": "^1.2.13",
    "apollo-link-context": "^1.0.19",
    "apollo-link-error": "^1.1.12",
    "apollo-link-http": "^1.5.16",
    "axios": "^0.18.0",
    "cropperjs": "^1.5.5",
    "file-saver": "^2.0.2",
    "graphql": "^14.5.7",
    "graphql-tag": "^2.10.1",
    "jszip": "^3.2.2",
    "jszip-utils": "^0.1.0",
    "money": "^0.2.0",
    "node-fetch": "^2.6.0",
    "quasar": "^1.9.1",
    "v-money": "^0.8.1",
    "vee-validate": "^2.2.11",
    "vue-apollo": "^3.0.0-rc.6",
    "vue-i18n": "^7.3.3",
    "vue2-google-maps": "^0.10.6",
    "vuex-persist": "2.0.1",
    "@bit/pangeacd.componentes-cd.condiciones-mensajes": "1.0.5"
  },
  "devDependencies": {
    "@quasar/app": "^1.0.4",
    "@vue/eslint-config-standard": "^4.0.0",
    "babel-eslint": "^10.0.1",
    "eslint": "^5.10.0",
    "eslint-loader": "^2.1.1",
    "eslint-plugin-vue": "^5.0.0",
    "quasar-app-extension-qdecimal": "^1.0.0-beta.1",
    "vue-markdown-loader": "^2.4.1"
  },
  "engines": {
    "node": ">= 8.9.0",
    "npm": ">= 5.6.0",
    "yarn": ">= 1.6.0"
  },
  "browserslist": [
    "last 1 version, not dead, ie >= 11"
  ],
  "bit": {
    "env": {
      "compiler": "bit.envs/bundlers/vue@2.6.21"
    },
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "npm"
  }
}

**Comment by itaymendel** [comment]
issue resolved in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
