### ISSUE TITLE
Fails in separate worktree

### ISSUE THREAD

**Issue by JGJP** [teambit/bit#2853]
Describe the bug

bit seems to be not working properly when using another git worktree via the git worktree add command.

Steps to Reproduce

git worktree add ../test
cd ../test
bit status

error output is ENOTDIR: not a directory, mkdir '/Users/jgjp/_dev/test/.git/bit/components'

Expected Behavior

Should be able to run bit commands on separate worktree

Specifications

Bit version: 4.7.6
Node version: 12.16.2
npm / yarn version: 1.22.4
Platform: macOS 10.15.5
Shell: Fish 3.1.0, Bash 3.2.57(1)-release

**Comment by benjgil** [comment]
Hi @JGJP, 

Thanks for logging your issue and apologies for the length of time it's taken to get to this.

From what you've written, it just seems like you've created a new worktree, but that it's directory is now outside the Bit workspace, so bit commands arent recognised there.

Can you try re-creating the new git worktree but this time assign it to a path which is inside your current Bit workspace?

**Comment by JGJP** [comment]
<img width="620" alt="Screen Shot 2020-10-27 at 10 29 29" src="https://user-images.githubusercontent.com/3692190/97245864-51d74200-183f-11eb-8798-a6a5f0455e3f.png">
Bit commands seem to be being recognised, otherwise I wouldn't be seeing all these warnings that I always see (separate issue).

I think you have some misunderstanding of the git worktree commands, because the whole point is to create another directory parallel to the current repo, not nested inside of it, you can check the official git documentation or any guide online, they all do it the same way.

**Comment by JGJP** [comment]
@itaymendel Is this resolved in the new version?

**Comment by itaymendel** [comment]
oh, forgot to post my comment, and instead clicked on the close-issue. apologies !

Bit expects to be initialized in the root of the workspace, as it stores content in the `.git/bit` directory by default. you can use `bit init --standalone`, which creates a `.bit` dir in your project root.

sadly Bit does not support a git-worktree workflow, you can potentially create an automation to support this flow, but i'm unsure about the specifics of how git keeps data in such cases, and bit is to orchestrate a sync (or should it?) between the diff worktrees.

**Comment by itaymendel** [comment]
at this point we are not looking to support git-subtree, as this will require a lot of heavy lifting to get bitmap in-sync with such strucutre
