### ISSUE TITLE
Your "movie-app" tutorial failed

### ISSUE THREAD

**Issue by PaPa31** [teambit/bit#2862]
### Description

After exporting, I get stripped down components in my [bit.dev](https://bit.dev/babel-mine/movie-app/hero). "Import" is missing. 

![Screenshot at 2020-07-18 17-32-49](https://user-images.githubusercontent.com/3861402/87852604-c5061980-c91c-11ea-8335-f7f5a5a4957f.png)

I did:
```
bit add src/global.css --id style/global
```
and

```
bit add src/global.css --namespace styles
``` 
But unsuccessfully.

Another one tutorial: [Bit for React](https://docs.bit.dev/docs/tutorials/bit-react-tutorial) in my scope
looks [good](https://bit.dev/babel-mine/react-tutorial/product-list).

![Screenshot at 2020-07-18 17-34-33](https://user-images.githubusercontent.com/3861402/87852623-026aa700-c91d-11ea-897a-2e1150cf6512.png)

Why so? 

And the mocha-karma test always fails.

![Screenshot at 2020-07-18 18-49-22](https://user-images.githubusercontent.com/3861402/87853909-701bd080-c927-11ea-90ec-f5d6385b83d2.png)

But the mocha test is good.

### Specifications

- Bit version: 14.8.8
- Node version: 12.14.0
- npm / yarn version: 6.14.5 / 1.22.4
- Platform: Linux/Ubuntu mate 19.10
- Bit compiler (include version): 1.0.20
- Bit tester (include version): 5.0.2

**Comment by itaymendel** [comment]
movie app is deprecated. new toturials available on docs.bit.dev
