### ISSUE TITLE
import Image from '@bit/react-bootstrap.react-bootstrap.image';

### ISSUE THREAD

**Issue by nihelboujelben** [teambit/bit#2871]
when i import Image from '@bit/react-bootstrap.react-bootstrap.image'; i have an error

**Comment by benjgil** [comment]
Hi @nihelboujelben 

Thanks for logging your issue and apologies for the time it's taken to respond.

Can you please provide more data for what you tried to do?
e.g.
What command exactly you ran to import the image?
What's the error?

Thanks
