### ISSUE TITLE
remote bit scope hosted on self-host server couldn't get any infomation about the exporter

### ISSUE THREAD

**Issue by mcuking** [teambit/bit#2877]
## Description

Hello, I host a remote bit scope on my own server, and other person could export their components to the remote bit scope. But there are two problems:

1. There is no infomation about the person who export component.
2. If person A exports a component to the remote bit scope, and personB also could export component with the same id. And it will lead to the last one will cover previous.

By the way, the article below indicates that when the user.name / user.email is configed, and name / email will be saved on the component history. But I could find any infomation in the remote bit scope. And I don't know where is the error.

https://docs.bit.dev/docs/conf-config#username

Hoping for reply.:joy:

**Comment by mcuking** [comment]
There is no infomation about who exported the component in .bit/index.json

![image](https://user-images.githubusercontent.com/22924912/88038779-45c15180-cb79-11ea-9670-2860e5cd5f70.png)

**Comment by davidfirst** [comment]
@mcuking , the index.json has nothing to do with it, it's just a caching mechanism for the scope.
About your questions:
1. correct. Only on tag Bit saves the info you described (name, email), you can run `bit log` to see this info.
2. it won't be overridden. Instead, in that case, that last one will get a conflict error and will be asked to untag, import and re-tag.

**Comment by mcuking** [comment]
> @mcuking , the index.json has nothing to do with it, it's just a caching mechanism for the scope.
> About your questions:
> 
> 1. correct. Only on tag Bit saves the info you described (name, email), you can run `bit log` to see this info.
> 2. it won't be overridden. Instead, in that case, that last one will get a conflict error and will be asked to untag, import and re-tag.

Thanks for your reply very much. I solved the problem by your advice. And I have one more question:

How can I get the downloaded times of a component?  Would Bit record the infomation in the component object or anywhere?

**Comment by davidfirst** [comment]
> How can I get the downloaded times of a component? Would Bit record the infomation in the component object or anywhere?

Nope. This data is not recorded.

**Comment by mcuking** [comment]
> > How can I get the downloaded times of a component? Would Bit record the infomation in the component object or anywhere?
> 
> Nope. This data is not recorded.

After reading the source code of bit（bit log part）, I transfered the buffers object in the .bit fileholder to string / object. Some are source code, some are component infomation or version information...  There is really nothing about download times.

But I see the download times in the bit.dev. How do you make that? Send a request in the bit-cli when execuating `bit import xxx`?
