### ISSUE TITLE
@thibaultchazal , The new version v14.8.4 has been released.

### ISSUE THREAD

**Issue by viniciuspsilvas** [teambit/bit#2888]
@thibaultchazal , The new version v14.8.4 has been released. 
Please re-open if the issue still happens with the new version.

_Originally posted by @davidfirst in https://github.com/teambit/bit/issues/2789#issuecomment-652994690_

**Comment by davidfirst** [comment]
@viniciuspsilvas , did you experience the same issue on the new version? if so, I'll close this one and re-open 2789.
