### ISSUE TITLE
Angular tutorial failed on "Install component in another project" step.

### ISSUE THREAD

**Issue by Adriiad** [teambit/bit#2913]
### Describe the bug

I correctly followed the angular tutorial. During the stage [Install component in another project](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial#install-component-in-another-project), `my-new-app` doesn't recognize `app-product-list` component.

### Steps to Reproduce

1. Follow the tutorial and do the [Install component in another project](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial#install-component-in-another-project) step.

### Expected Behavior

`my-new-app` application should recognize `app-product-list` component as a known element and build without problem.

### Screenshots, exceptions and logs

Console :
![image](https://user-images.githubusercontent.com/40627664/88776619-837c3680-d186-11ea-9c30-06a0e25bca23.png)

app.module.ts (from `my-new-app`)
![image](https://user-images.githubusercontent.com/40627664/88778050-49139900-d188-11ea-89c8-cdb699434e47.png)

app.component.html (from `my-new-app`)
![image](https://user-images.githubusercontent.com/40627664/88778124-65afd100-d188-11ea-99c4-31e99d8894c6.png)

### Specifications

- Bit version: 14.8.8
- Node version: 10.16.3
- npm version: 6.9.0
- Platform: Ubuntu 18.04.3 LTS
- Bit compiler (include version): bit.envs/compilers/angular@9.0.21

### Additional context

`bit-angular-tutorial` app is in Angular 9.0.6
`my-new-app` app is in Angular 10.0.5.

I tried to setup "my-new-app" in the same Angular's version as `bit-angular-tutorial`, but the problem is still here. 

However, the component works perfectly on the bit playground.

**Comment by JoshK2** [comment]
Hi, thanks for reporting this issue, I'll check that with the new major version of Bit that we gonna release within a few weeks and I'll update here after that.

**Comment by mure** [comment]
Ran into this same problem. Did you find a workaround @Adriiad?

**Comment by pablorsk** [comment]
[Tutorial](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial) works great on Angular 9, like I reproduce on #3175 after `product-list upgrade`. But, on the moment when you upgrade to Angular 10, `ng build` or `ng start` fails.

Thanks a lot for your work @JoshK2. :clap:

**Comment by JoshK2** [comment]
@Adriiad , after I updated the component like @pablorsk  says, the tutorial work.
Please update here if you still experiencing this issue.

**Comment by JoshK2** [comment]
@pablorsk I'll update the compiler to Angular 10, and I think it should work.

**Comment by JoshK2** [comment]
@pablorsk I published a new version with Angular 10.
So I think it will work for you, and also this issue can be closed because I solved it earlier here:
https://github.com/teambit/bit/issues/3175
