### ISSUE TITLE
exporting to first-scope 

### ISSUE THREAD

**Issue by Zaigham-Javed** [teambit/bit#2920]
### Description

create a bit server and setup the remote scope successfully but i am facing issue while exporting to remote scope
when i try to export my files i get the following error:

`error: unexpected network error has occurred.  original message: EACCES: permission denied, open '/home/bitdev/Library/Caches/Bit/config/global-remotes.json`

and I sshed into the server and couldn’t find the global-remotes.json file. is it not created automatic by bit? and if i have to create this file then what should be the content?

### Specifications

- Bit version: 14.8.8
- Node version: v12.18.2
- npm / yarn version: 6.14.5
- Platform: Ubuntu

**Comment by itaymendel** [comment]
bit v15 is moving away from ssh to https. later this week we'll be stating an open beta, so closing the issue.
