### ISSUE TITLE
Importing Bit component in nuxt results in *document is not defined*

### ISSUE THREAD

**Issue by haexhub** [teambit/bit#2930]
### Description

Hi,

I build a bit component out of a nuxt application and tried to import it in an other nuxt project, but everytime I try this, I get the error message: **document is not defined**

### Specifications

- Bit version: 14.8.8
- Node version: 14.5.0
- yarn version: 1.22.4
- Platform: Manjaro
- Bit compiler (include version): bit.envs/compilers/vue@0.1.10
- Bit tester (include version): -

### Context and additional information
The component is exported to bit.dev.
Does someone has any idea, what I'm doing wrong

PS: In the tutorial for bit vue the compiler bit.envs/compilers/vue is used, but on the git project for [bit/envs](https://github.com/teambit/envs) bit import bit.envs/bundlers/vue -c is advised. Which one is right?

**Comment by itaymendel** [comment]
at the moment bit does not support nuxt due to SSR issues.
after bit v15 is released later this week, we'll be revisiting vue support in bit and resolve these issues

**Comment by LeonardoRick** [comment]
How is the support nowadays?
