### ISSUE TITLE
Hanging on persisting...

### ISSUE THREAD

**Issue by AlexanderKaran** [teambit/bit#2932]
### Describe the bug

After I tag my components it starts to persist however it has been hanging on persist now for 30 mins.

I have tried clearing my cache, making sure all components are imported and Bit doctor is throwing no issues.

### Steps to Reproduce

1. Make some changes
1.  bit tag -all

  bit version   : 14.8.8
  node version  : v12.18.3
  npm version   : 6.14.6
  yarn version  : NA
  platform      : darwin

**Comment by GiladShoham** [comment]
@AlexanderKaran 
Can you please send your debug.log file to support@bit.dev?

Thanks.
Gilad.

**Comment by AlexanderKaran** [comment]
Will do that now. It just finished tagging but it took 45 mins. Should I leave this bug open for long tag time or close it?

**Comment by AlexanderKaran** [comment]
Closing issue as slow export time is a different issue. Hanging on persisting is not an issue anymore
