### ISSUE TITLE
Bit source code missing libraries 

### ISSUE THREAD

**Issue by ingpconci** [teambit/bit#2991]
### Describe the bug

npm ERR! 404  '@teambit/utils-temp.utils.sub-paths@0.0.1' is not in the npm registry.

### Steps to Reproduce

1. Git clone https://github.com/teambit/bit.git
2. npm i 
........
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@teambit/utils-temp.utils.sub-paths/-/utils-temp.utils.sub-paths-0.0.1.tgz
npm ERR! 404
npm ERR! 404  '@teambit/utils-temp.utils.sub-paths@0.0.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'bit'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### Expected Behavior

Complete installation of the required libraries

### Specifications

- Bit version: 14.8.9-dev.1
- Node version: v12.13.0
- npm / yarn version: npm 6.12.0
- Platform:Win10
- Bit compiler (include version):
- Bit tester (include version):

**Comment by davidfirst** [comment]
@ingpconci , this is going to be fixed very soon. These packages are currently "private" only to make it easier to remove them. (as you can see the name has "temp" in it). We're close to finalize the work on these packages and make them public.

**Comment by itaymendel** [comment]
pacakges already public
