### ISSUE TITLE
problem with bit export component

### ISSUE THREAD

**Issue by rizdaputra** [teambit/bit#2993]
### Description

I have several problems:
1. We published some latest version of our components, it is reflected in bitmap and in bit website but cannot install it cause the version does not exist
2. Keep getting to update the same component again and again even though there were no changes at all

### Specifications

- Bit version: 14.4.3
- Node version: v12.14.0
- npm / yarn version: 6.13.4
- Platform: ubuntu 18.04
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

This is problem 2, tried 3 times
![Screenshot from 2020-08-18 18-06-43](https://user-images.githubusercontent.com/11706006/90505914-a1cdc480-e17d-11ea-8cd3-1d3e7a4928e3.png)

This is for problem number 1
![Screenshot from 2020-08-18 18-08-27](https://user-images.githubusercontent.com/11706006/90506037-da6d9e00-e17d-11ea-8cd4-6b75c1743a38.png)
![Screenshot from 2020-08-18 18-07-45](https://user-images.githubusercontent.com/11706006/90506043-db9ecb00-e17d-11ea-8338-b3dc110236c5.png)

**Comment by davidfirst** [comment]
@rizdaputra , please run `bit diff` and paste the results. It'll give us a hint about why these components are modified after the tag.
