### ISSUE TITLE
How to transpile bit modules to IE11

### ISSUE THREAD

**Issue by hubagaspar91** [teambit/bit#2994]
#2254 # Description

I had a project recently, where I had to support IE11. I ran into a problem, where the modules compiled by bit were not transpiled properly, therefore ended up using the entry source file from the package folder, and transpiled it as a dependency.

I am using vue-cli and what I did was

Changed the import from 

```
import VuexWizard from '@bit/cleverclip.cleverclip-vue-components.navigation.vuex-wizard/dist/navigation/vuex-wizard.umd'
```

To

```
import VuexWizard from '@bit/cleverclip.cleverclip-vue-components.navigation.vuex-wizard/VuexWizard/index.js'
```

And added the following in my vue.config.js

```
transpileDependencies: [
    /@bit/
  ],
```

I wonder, if there's a better way to do it, preferably to have the module created by bit transpiled by default.
### Specifications

- Bit version: 14.8.8
- Node version: v14.4.0
- npm / yarn version: npm@6.14.5
- Platform: OSX 10.15.5
- Bit compiler (include version): "bit.envs/compilers/vue@0.1.10"

**Comment by itaymendel** [comment]
this is already available for bit v15 for react components.
with vue support you will be able to set compilation targets as yo urequire for vue as well.

update vue support is gonna be its own epic, so i'm closing this ticket
