### ISSUE TITLE
Bit untrack removed component bug

### ISSUE THREAD

**Issue by Mujaddadi** [teambit/bit#3003]
When we remove component from remote, bit sometimes doesn't recognize that change locally. I tried using `bit remove` it says `missing components (try to bit untrack them instead):`. When I try `bit untrack` it says `error: unable to untrack userName/ui/label, please use the bit remove command.` So like some other bugs with bit I encountered, I am stuck in a loop. I try removing them manually from .bitmap, which I understand not a good idea, but it didn't work either.

### Specifications

- Bit version: 14.8.8
- Node version: 12.18.3
- npm / yarn version: 6.14.6
- Platform: Windows 10

**Comment by Mujaddadi** [comment]
Never mind. I tried with the versions number like this `bit untrack username.lib/ui/label@0.0.1` and it worked. Closing the issue

**Comment by Mujaddadi** [comment]
I reopened the issue because `bit status` is still giving this message `your workspace has outdated objects. please use "bit import" to pull the latest objects from the remote scope.`

**Comment by itaymendel** [comment]
issue resolved in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
