### ISSUE TITLE
screenshots.imgix.net is crush 

### ISSUE THREAD

**Issue by ziven27** [teambit/bit#3005]
### Describe the bug

![image](https://user-images.githubusercontent.com/7261176/90980476-31181500-e58e-11ea-9d78-1690f825c7c7.png)

screenshots.imgix.net is crush 
I can see none of preview img in home page

### Steps to Reproduce

1.
1.
1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by guysaar223** [comment]
Hi, @ziven27, 
the problem has been fixed can you tell me, if it's working for you now? 

 
Guy :)

**Comment by ziven27** [comment]
thanks a lot I can see the preview image
