### ISSUE TITLE
Error: unexpected network error has occurred

### ISSUE THREAD

**Issue by AlexanderKaran** [teambit/bit#3008]
### Describe the bug

I have one tagged component but every time I go to export it to a collection I get the following error:

```
error: unexpected network error has occurred.  original message: error: version ^0.0.5 is not a valid semantic version. learn more: https://semver.org

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

### Specifications

bit version   : 14.8.8
node version  : v12.18.3
npm version   : 6.14.6
 yarn version  : NA
 platform      : darwin

### Additional context

My Bit Doctor records no issues. We are pushing a new build today and this error is preventing me from doing so.

**Comment by GiladShoham** [comment]
@AlexanderKaran 
Bit doesn't support ranges between components.
Do you know where this range came from?

**Comment by AlexanderKaran** [comment]
What is a ranges? Never heard that before, sorry if that is a silly question

**Comment by davidfirst** [comment]
@AlexanderKaran , Gilad is talking about the version `^0.0.5`, which has a caret range. (the ^ prefix).
Bit components can be exact versions only, the question is where the caret came from, it can be from the package.json. From the log, it's probably easy to see the version source.

**Comment by AlexanderKaran** [comment]
Thanks @davidfirst I will remove any ^ from my packjson and see if that fixes it

**Comment by AlexanderKaran** [comment]
That worked @davidfirst
