### ISSUE TITLE
Using Tailwind and PostCSS inside of a Vue component.

### ISSUE THREAD

**Issue by splurtcake** [teambit/bit#3010]
### Description

I would like to add Tailwind styles to my Vue component that are scoped to the component file.

How do I get PostCSS to run when importing the tailwind.css file into a component?

tailwind.css
```
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Button.vue
```
<template>
  <button class="button">
    {{ label }}
  </button>
</template>

<script>
import "../../css/tailwind.css";

export default {
  props: {
    label: {
      type: String,
      required: true
    }
  },
}
</script>
<style scoped>
.button {
  @apply tw-p-10 tw-bg-black tw-text-white;
}
</style>
```

postcss.config.js
```
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('tailwindcss')
  ],
}
```
tailwind.config.js
```
const designSystemConfig = require('@xxxx/design-system-configuration');
const { mainTheme } = designSystemConfig.themes;

module.exports = {
  theme: {
    ...mainTheme,
  },
  corePlugins: {
    preflight: false,
  },
};
```

### Specifications

- Bit version: 14.8.8
- Node version: 10.19.0
- npm / yarn version: 6.13.4
- Platform: MacOS
- Bit compiler (include version): vue@0.1.10
- Bit tester (include version): n/a

**Comment by themojilla** [comment]
@splurtcake Did you manage to solve the problem?

**Comment by itaymendel** [comment]
currently bit v14 can't support tailwind. this will be unlocked in v15 as we remodeled the entire workflow
