### ISSUE TITLE
Infer default packageManager from lock file if already present

### ISSUE THREAD

**Issue by rramaa** [teambit/bit#3015]
### Description

Bit should infer the package manager on init

### Describe the solution you'd like

Bit can detect the lock file present in the project, through which it should be able to smartly fill the packageManager field in configuration
`yarn.lock` --> `yarn`
`package-lock.json` --> `npm`

### Additional context
This is helpful when using `bit init` command

**Comment by itaymendel** [comment]
this is rather complicated, as there are potential several lock files available.
