### ISSUE TITLE
Pipeline operator is not understood by Bit CLI

### ISSUE THREAD

**Issue by VCuzmin** [teambit/bit#3028]
Hello. I have a problem: I have a component which uses the new pipeline operator (|>). This operator works if only I do some configuration in the project: first off, you have to install the pipeline operator plugin and then create a file called config-overrides.js with some configuration related to this operator. If I track this component, Bit cannot understand this operator.

This is the operator:
![image](https://user-images.githubusercontent.com/40390118/91544551-8c4c5d80-e928-11ea-907c-8e8ded2e821d.png)

This is the error of parsing the file during bit tracking:

![image](https://user-images.githubusercontent.com/40390118/91544468-776fca00-e928-11ea-865d-9c993c0c3a81.png)

What can I do in order to fix this issue? Thx

**Comment by benjgil** [comment]
Hi @VCuzmin - thanks for logging the issue and apologies for the time it's taken to respond.

As well as adding the pipeline operator into the project, please ensure that you have added it specifically for the component you are using the operator in.

Bit isolates all components, so any operators that are required for a specific components must be configured specifically on that component.

**Comment by itaymendel** [comment]
issue resovled in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
