### ISSUE TITLE
Typescript Component Not Compiling - Module parse failed: The keyword 'interface' is reserved

### ISSUE THREAD

**Issue by LorsK** [teambit/bit#3030]
### Description
https://bit.dev/hiride/atoms/card
Error after exporting simple typescript component

```
./node_modules/@bit/hiride.atoms.card/dist/index.tsx 4:0
Module parse failed: The keyword 'interface' is reserved (4:0)
You may need an appropriate loader to handle this file type.
| import {View, StyleSheet} from 'react-native';
| 
> interface IProps {
|   children: any;
|   style?: {[key: string]: any};
```

### Specifications

- Bit version   : 14.8.8
- Node version  : v13.14.0
- npm version   : 6.14.6
- yarn version  : 1.22.4
-  platform      : darwin
- Bit compiler: bit.envs/compilers/react-native@1.0.21  

### Context and additional information

This is a react native project using typescript.

**Comment by JoshK2** [comment]
Hi, the current React-Native compiler does not support TS, you can see the opened issue about it here:
https://github.com/teambit/envs/issues/57

**Comment by LorsK** [comment]
That makes sense what I have done to work around this now is convert the file to `.js` and add a `.d.ts` file to declare any types the component may have.
