### ISSUE TITLE
Compiled component points to non-existent directory

### ISSUE THREAD

**Issue by noah-friedman** [teambit/bit#3034]
### Describe the bug

After building a component, the compiled file points to a non-existent directory.

### Steps to Reproduce

1. Create component called "LoadingAnimation".
2. Create another dependent component with a test.
3. On attempting to run the test, the tester complains that it cannot find the source file.

### Expected Behavior

Bit CLI should link the files properly.

### Screenshots, exceptions and logs
<img width="1440" alt="Screen Shot 2020-08-30 at 10 50 22 AM" src="https://user-images.githubusercontent.com/44714422/91662315-a49ab480-eaaf-11ea-897e-e30b2d4c41b1.png">
<img width="1552" alt="Screen Shot 2020-08-30 at 10 55 59 AM" src="https://user-images.githubusercontent.com/44714422/91662319-b0867680-eaaf-11ea-87c8-45644578d5c3.png">

### Specifications

- Bit version: 14.8.8
- Node version: 14.5.0
- npm / yarn version: NPM 6.14.6, Yarn 1.22.4
- Platform: Mac OS
- Bit compiler (include version): noahfriedman-ca.envs/compilers/react-typescript@3.1.58
- Bit tester (include version): noahfriedman-ca.envs/testers/jest@24.9.2

### Additional context

Current workaround: copy source files from `dist` directory to the correct location in `node_modules`.

**Comment by GiladShoham** [comment]
Did you run bit build before running the app?

**Comment by noah-friedman** [comment]
Running `bit build` on the component outputs files to the project `dist` directory, but not the directory in the `node_modules` folder. The file referenced by the tested component is `dist/LoadingAnimation/LoadingAnimation.js` which only points to the `node_modules` folder.

**Comment by itaymendel** [comment]
resolved in bit v15, entire compilation pipe was refactored.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
