### ISSUE TITLE
 bit status show: component.scss -> Selector is expected

### ISSUE THREAD

**Issue by AnteaterKit** [teambit/bit#3040]
### Description

Can't build bit component from Angular, when using .scss styles.

### Specifications

- Bit version: 14.8.8
- Node version: v12.14.1
- npm / yarn version: npm@6.13.4
- Platform: windows 10, angular 10
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

![bit](https://user-images.githubusercontent.com/5115677/91826285-068d2280-ec46-11ea-8882-8753b3804baa.PNG)

**Comment by benjgil** [comment]
Hi @AnteaterKit - thanks for posting your issue and apologies for the time it's taken to get back to you.

I guess it's difficult now to post the actual contents of the scss file, but in general Bit does support scss files so without knowing the contents of your file it's hard to know what the issue could be. 

One option is if you used a tool to convert regular css (or some other syntax) into scss, as that can often be a source of vexxing, and rather silly, parsing errors.
