### ISSUE TITLE
Bit components "Processing" for days

### ISSUE THREAD

**Issue by noah-friedman** [teambit/bit#3043]
### Describe the bug

Exported some components a couple days ago. Initial version processed and turned green, but now many components have been stuck on "Processing" for about two days.

### Steps to Reproduce

1. Export some components.
2. Not really sure how to reproduce because I don't know why it's happening. I can give more detailed descriptions of components/environment if necessary.

### Expected Behavior

Expected components to finish processing within a couple minutes as usual.

### Screenshots, exceptions and logs

<img width="651" alt="Screen Shot 2020-09-01 at 1 46 58 PM" src="https://user-images.githubusercontent.com/44714422/91888246-fc751f00-ec59-11ea-9e94-e3625936a3c4.png">
<img width="1552" alt="Screen Shot 2020-09-01 at 1 47 27 PM" src="https://user-images.githubusercontent.com/44714422/91888253-fed77900-ec59-11ea-93a4-bd7461ace716.png">

### Specifications

- Bit version: 14.8.8
- Node version: 14.5.0
- npm / yarn version: 6.14.6, 1.22.4
- Platform: Mac OS
- Bit compiler (include version): noahfriedman-ca.envs/compilers/react-typescript@3.1.58
- Bit tester (include version): noahfriedman-ca.envs/testers/jest@24.9.3

### Additional context

Attempting to resolve by rewriting components and exporting them to a different collection. Not too invested in fixing this issue for these components specifically, but this seemed like something worth reporting.

**Comment by davidfirst** [comment]
@noah-friedman , this is related to an issue with node v14 & ssh packages. See https://github.com/teambit/bit/issues/2844 for more info.

For now, the workaround is to downgrade to a node version < v14.1.0.

**Comment by noah-friedman** [comment]
Thanks so much!

**Comment by noah-friedman** [comment]
@davidfirst I downgraded to node 12.18.3, I'm still facing the issue. Not sure what to do, maybe I'm missing something?

**Comment by noah-friedman** [comment]
Update: components have started passing again.
