### ISSUE TITLE
How to remove dependencies between components？

### ISSUE THREAD

**Issue by ziven27** [teambit/bit#3048]
### Description

I wanna remove a component, but it tell me 

```
error: unable to delete webnovel.read-ui/icons, because the following components depend on it:
webnovel.read-ui/dialog
webnovel.read-ui/dialog-drop-list
webnovel.read-ui/dialog-stick
webnovel.read-ui/dialog-img
webnovel.read-ui/loading
webnovel.read-ui/form
```

But I have already remove all the import code from the components below,  
but is still have the Dependencies error.
How to remove the dependencies?

### Specifications

- Bit version: 14.8.8
- Node version: v12.16.3
- npm / yarn version: 1.17.0
- Platform: Mac os
- Bit compiler (include version):
- Bit tester (include version):

**Comment by davidfirst** [comment]
@ziven27 , this is because the tagged component has these dependencies. There is no way to remove previous versions of a component, you can only remove the entire component. 
You can try removing the dependencies components if you don't need them.
