### ISSUE TITLE
add `export { default }` while creating index.ts[x]

### ISSUE THREAD

**Issue by gogoyqj** [teambit/bit#3071]
### Description

while using `bit import --ignore-package-json` to import a component with source `Demo.tsx`, bit will auto-create a `index.tsx` resides in a same directory with `Demo.tsx`:

index.tsx
```ts
export * from './Demo';
```

missing:
```
export { default } from './Demo';
```

### Specifications

- Bit version: 14.8.8
- Node version: v10.15.3
- npm: 6.4.1
- Platform: Mac
- Bit compiler (include version): none
- Bit tester (include version): none

**Comment by gogoyqj** [comment]
https://github.com/gogoyqj/bit/commit/24d904520242fb269ec0bf3eb93a716eec233a51

**Comment by itaymendel** [comment]
component templating is in our roadmap, i expect the work on it will start in just a few weeks.
