### ISSUE TITLE
bit login - error: you do not have permissions to access 'undefined', were you running bit, npm or git as root?

### ISSUE THREAD

**Issue by levox** [teambit/bit#3079]
Hi everyone,

I'm having some troubles to use bit-cli in my work-environment and hope you could point me into the right direction. 
I tried the same procedure (based on the tutorial page: https://docs.bit.dev/docs/tutorials/bit-react-tutorial) on my personal/private PC and it worked instantly. A colleague tried it on his work-PC an it worked aswell. So it must relate to my machine. Do you have and idea what can cause this issue on Windows?

Thank you so much in advance!

### Description

I try to login into my bit.dev account to utilize bits features. But bit throws an exception when i try to login into my account. I found references to this error message (https://github.com/teambit/bit/commit/bb1b8ed43cd01ce8b7dca2edd21d1859978c1b0a and https://github.com/teambit/bit/issues/1774), but i can't figure out where "undefined" is coming from. 

*The error after `bit login`*
`error: you do not have permissions to access 'undefined', were you running bit, npm or git as root?`

I'm pretty sure it relates to some access permission problems, but where does the undefined come from?

I tried to excute the command in Administrator Command Prompt, regular Command Prompt and in the Visual Studio Code cmd line. Furthermore I uninstalled node, npm and bit and reinstalled it. I tried different versions of npm and node. None of these approaches achieved something.

### Specifications

- Bit version: 14.8.8
- Node version: 12.18.3
- npm version: 6.14.8
- Platform: Windows 10 (64bit)
- Bit compiler (include version): -
- Bit tester (include version): -

### Context and additional information
Since the error occurs when i try to login, there are no projectenvironment constraints. I have admin permissions on this PC. I installed bit with the no-optional flag as suggested for Windows: `npm install bit-bin --global --no-optional`

**Comment by itaymendel** [comment]
we're moving away from the normal installation to a dedicated installer for bit v15. this should resolve such cases.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
