### ISSUE TITLE
Replace the .babelrc file with babel.config.json for compiler

### ISSUE THREAD

**Issue by VCuzmin** [teambit/bit#3095]
Hello. How can I replace the .babelrc file config with the babel.config.json file for the compiler?
I have already followed the following steps to change some configurations in the .babelrc file: https://discourse.bit.dev/t/can-i-modify-a-build-test-environments/28  but I want to replace this file with babel.config.json file!
Thanks a lot!

**Comment by itaymendel** [comment]
more customization for compilation is available as part of bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
