### ISSUE TITLE
Stencil compiler issue: maybe due to compatibility issue with StencilJS 2.0.3?

### ISSUE THREAD

**Issue by tomokat** [teambit/bit#3103]
### Describe the bug

[Stencil compiler 0.0.35](https://bit.dev/bit/envs/compilers/stencil) throws error - could be due to incompatibility issue with recent Stencil (2.0.3) but error sounds like potential dependency issue?

### Steps to Reproduce

1. create StencilJS component project (`npm init stencil` and then select ->Component)
1. add simple component (or probably default my-component is good enough)
1. add bit to this project `bit init` and then add stencil compiler with `bit import bit.envs/compilers/stencil -c`
1. run `bit build` and it complains about missing dependency '@stencil/sass` even though it is part of package.json from the stencil compiler (I currently didn't use sass yet but just in case, I added to my root project, no luck)

**OR** you can also checkout my project (branch) here -
https://github.com/tomokat/cat-components/tree/experiment-with-bit-dev
assuming you have bit-bin and right node/npm, you should be able to just do `npm install` and then `bit build` to reproduce issue.

The strange part of this error is, it complains about:
`Command failed with exit code 1: /home/user/git/cat-components/node_modules/@stencil/core/bin/stencil build --log`
but if I were to copy that command and run, it run clean (or I can use "npm run build" - same thing, run clean, no issue)

### Expected Behavior

`bit build` should not failed - or at least provide better error so that I know how to troubleshoot this problem

### Screenshots, exceptions and logs
here is a screenshot of the error I'm talking about:
![bit-stencil-compiler-failed](https://user-images.githubusercontent.com/3937246/93121216-79f55200-f692-11ea-8b0c-29d58ba7dfe1.PNG)

### Specifications

- Bit version: 14.8.8
- Node version:14.0.1 --> downgraded to 12.18.3 (export was stuck with 14)
- npm / yarn version:6.14.8
- Platform: Linux VM (Ubuntu 18.04)

**Comment by tomokat** [comment]
looks like `bit build` creates capsule under `/tmp/bit/capsule-#####/stencil.config.ts` and there, I can see it is trying to import @stencil/sass, which I believe is what it is complaining about - or here is what is generated under capsule:

```
import { Config } from '@stencil/core';
import { sass } '@stencil/sass';
export const config: Config  = {
    "namespace": "cat-list",
    "hashFileNames": false,
    "outputTargets": [
        {
            "type": "dist",
            "esmLoaderPath": "loader"
        },
        {
            "type": "docs-readme"
        },
        {
            "type": "www",
            "serviceWorker": null
        }
    ]
,"plugins": [sass()]}
```



I tried to go into `components/compilers/stencil/stencil/src/index.ts` and remove text where within stencilConfigText which seem to construct import statement and also remove reference to sass() inside plugin but `bit build` maybe loading this from somewhere, as it keep complaining about the same thing (also generated capsule still have import and using `sass()` inside plugins)

**Comment by tomokat** [comment]
Also if I cd into `/tmp/bit/capsule-#####/` and then manually add @stencil/sass with `npm i @stencil/sass --save-dev` and then execute `node_modules/@stencil/core/bin/stencil build`, it seem to work fine so could it be just a matter of adding @stencil/sass as dependency to the stencil compiler? (I tried this locally but it doesn't seem to take any affect - really strange as project package.json seem to reference it as file, make me believe that it is using local files ...
`"@bit/bit.envs.compilers.stencil": "file:./components/compilers/stencil",`
(this is what I have inside my package.json)

**Comment by tomokat** [comment]
Found a workaround for now - [looking at documentation here](https://docs.bit.dev/docs/building-components), I tell compiler to use my local fork by changing env within package.json from:
```
https://docs.bit.dev/docs/building-components
```
to
```
"compiler": {
  "bit.envs/compilers/stencil@0.0.35": {
    "options": {
      "file": "./components/compilers/stencil"
    }
  }
}
```

**Comment by tomokat** [comment]
Locally it seem to be fine with workaround but now when I try to export it, it seem to be stuck at
`exporting components`

it also give me grey text paragraph:
```
bit is about to fork the following components and export them to teamcat.catcomponents.
	bit.envs/compilers/stencil
also, if they're staged, bit will not change their status to exported unless '--set-current-scope' flag is used.

there are additional flags for the 'export' command to specifically handle forking components:
1. '--include-dependencies' exports all dependencies to the destination alongside the component.
2. '--set-current-scope' sets your workspace to use the destination scope as the main remote for the component.
3. '--rewire' changes all dependencies to point to the new destination.

would you like to proceed with forking the components? (yes/no):
```

I type yes and hit enter but seem to be stuck now ... (I'll leave this for few more minutes just in case CLI need this much time to export component - I highly doubt it)

**Comment by tomokat** [comment]
I notice warning and [by quick google](https://github.com/facebook/docusaurus/issues/2648) looks like issue might be due to node 14 so I downgrade to 12 and w00t, finally export works and I can see updated version and code!

However component code is still not working inside bit.dev (not sure if this supposed to work, as I don't see any option to render it as web component?)

**Comment by tomokat** [comment]
**Yes, I got it working!!!**
After some searching, [I found this example](https://bit.dev/sachingutte/demo/dialogbox) and by looking at stencilJS documentation on how to integrate with React, here is what I did in order to render stencilJS component

```
import React from 'react';

import {
	applyPolyfills,
	defineCustomElements as catListElement
} from '@bit/teamcat.catcomponents.cat-list/dist/loader';

applyPolyfills().then(() => {
	catListElement(window);
});

export default (
	<cat-list></cat-list>
)
```

and [here is link to running example](https://bit.dev/teamcat/catcomponents/cat-list?example=5f60bc974d4cb90019e65318)

**Comment by tomokat** [comment]
Not sure if anyone cares, but here are my current assessment of bit.dev with stencilJS

- looks like bit.dev doesn't have integration/renderer for web component, hopefully it is on their roadmap as all we need is probably just a way to load HTML (for most part we just need to import ESM or JS and reference it inside html)
- I understand why but Stencil doesn't require explicit import of inter component dependencies and therefore it won't be picked up as dependency (but even if I do, I don't think compiler is taking it to consideration?)
- I might be doing something wrong, but the only way for me to make it work inside bit.dev is to manually load each components and then call `defineCustomElements` which means we need to keep track of component dependency ourselves?

here is what I mean by manually keeping track of it - in order for my `random-cat` component (which is a simple/pure wrapper for `cat-list` component to test out inner component dependency) to render, I have to then do:

```
import {
	defineCustomElements as catListElement
} from '@bit/teamcat.catcomponents.cat-list/dist/loader';

import {
	applyPolyfills,
	defineCustomElements as randomCatsElement
} from '@bit/teamcat.catcomponents.random-cats/dist/loader';

applyPolyfills().then(() => {
	catListElement(window);
	randomCatsElement(window);
});

export default (
	<random-cats></random-cats>
)
```
one major drawback of this approach is, version of `cat-list` component loaded seem to be tied with what ever exist at `@bit/teamcat.catcomponents.cat-list` (in this case, it is latest) so I can't seem to find a way to tell `random-cat` to depend on specific version of `cat-list`

**Comment by itaymendel** [comment]
hi thanks for the extremely deep dive into stencil support in bit
most of these issues are due to issues with how stencil is currently implemented.

we'll be revisiting the implementation after bit v15 is published this week.

your notes and insights are super valuable, but i would like to sort a proper epic for the implementation. my team will look into it when we write specification. if we need any help, we might try to reach out!
