### ISSUE TITLE
Self-hosted BIT Ui

### ISSUE THREAD

**Issue by theguriev** [teambit/bit#3119]
Hey guys 👋🏻
I heard somewhere that you preparing a self-hosted bit ui. Is it true? Can I try it somehow?

**Comment by itaymendel** [comment]
Hi @gcofficial !
this is something we are working on right now and will be available as part of the next major release, alongside other improvements for teams that decide to host their own Bit-servers.

**Comment by gcofficial** [comment]
Thx a lot for your answer. Can't wait to test it 😇

**Comment by DylanCulfogienis** [comment]
Also interested in this, I'd like to introduce my company to Bit or a similar component sharing tool, but I know leadership won't bite unless it's self-hosted.

**Comment by itaymendel** [comment]
this will be available on bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
