### ISSUE TITLE
link module without package.json cause npm i failed with package-lock.json

### ISSUE THREAD

**Issue by gogoyqj** [teambit/bit#3126]
### Describe the bug?

just not quite sure this is a bug

bit import will auto create a fake module link to support alias just like pic below

![image](https://user-images.githubusercontent.com/1776278/93570394-84328b80-f9c5-11ea-94b6-3c2ce571134f.png)

well if `@bit/ef-cp-design.basic.input` is saved to project root package.json and there is a package-lock.json then run `npm i` will throw:

```
npm ERR! enoent ENOENT: no such file or directory, open 'IconFont/package.json'
```

since there must a package-lock.json， so we can't run `npm i --no-package-lock`

maybe some available solutions：

A: bit auto create a `package.json` for such link module

B: a way to prevent `@bit/...` saving into root package.json while `bit import/checkout/merge` just like `npm i --no-save`

### Specifications

- Bit version: 14.8.8
- Node version: 10
- npm version: 6.4.1
- Platform: Mac
- Bit compiler (include version): none
- Bit tester (include version): none

**Comment by gogoyqj** [comment]
Plan B:
ManyComponentsWriter addToRootPackageJson

`bit import src/consumer/component-ops/import-components.ts`
`bit checkout  src/consumer/versions-ops/checkout-version.ts`

**Comment by itaymendel** [comment]
issue resolved in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
