### ISSUE TITLE
No provider for PlatformLocation

### ISSUE THREAD

**Issue by Albejr** [teambit/bit#3143]
### Description
[https://bit.dev/albejr/ngx/ngx-timeline-albe](https://bit.dev/albejr/ngx/ngx-timeline-albe)

Compiled successfully, but the component is not displayed due to the error:
```
NullInjectorError: StaticInjectorError(AppModule)[Location -> PlatformLocation]: 
  StaticInjectorError(Platform: core)[Location -> PlatformLocation]: 
    NullInjectorError: No provider for PlatformLocation!
```

### Specifications
Version of:
- Bit: 14.8.8
- Node:12.16.3
- npm: 6.14.4
- Platform:  angula/core@10.1.2
- Bit compiler: bit.envs/compilers/angular@9.0.23

### Context and additional information

I use in the component:
```
  constructor(@Inject(LOCALE_ID) protected localeID: string) {
  }
```

**Comment by JoshK2** [comment]
Hi, the component example work if you test it on a clean Angular project and install this component with npm/yarn ?

**Comment by Albejr** [comment]
Yes it works.
[github](https://github.com/Albejr/ngx-timeline)
[stackblitz](https://ngx-timeline-albe.stackblitz.io)

**Comment by GiladShoham** [comment]
I think it's because you should set your angular dependencies as peer deps.
read more [here](https://docs.bit.dev/docs/angular-guidelines#add-angular-libraries-as-peer-dependencies-with-relaxed-versions)
