### ISSUE TITLE
Cannot Tag Components

### ISSUE THREAD

**Issue by 17gcolestock** [teambit/bit#3155]
## Expected Behavior
Able to tag a number of new components when first setting up a bit workspace and preparing to export. 

## Actual Behavior
After compiling all components, fails with error message
`unable to save Version object, the env.name has an invalid Bit id
`
## Steps to Reproduce the Problem

  1. Add components.
  2. Bit status reports ok for all components
  3. run `bit tag --all 1.0.0`.

## Specifications

  - Bit version: 14.8.8
  - Node version: v10.17.0
  - npm / yarn version:
  - Platform: 1.22.4
  - Bit compiler (include version): custom
  - Bit tester (include version):

**Comment by JoshK2** [comment]
Hi, I tried to reproduce the issue, but without success.
Can you share with me your bit config? Maybe it will help me to reproduce this.
Also, if you can share your custom compiler, it will be great.

**Comment by 17gcolestock** [comment]
Howdy- afraid the issue was with how I formatted the custom compiler name. Thank you for reaching out

--
Grant Colestock
grant@colestock.net
(763)-234-2419

**Comment by JoshK2** [comment]
@17gcolestock  so everything is ok.
I close the issue.
