### ISSUE TITLE
Linaria css-in-js - Component compilation error

### ISSUE THREAD

**Issue by hazratgs** [teambit/bit#3163]
Hi everyone!
I added bit.dev to my project
We use linaria css-in-js solution and it needs to be compiled beforehand
Here is the actual question of how to solve this problem?

### Describe the bug
text error:
Error: Using the "css" tag in runtime is not supported. Make sure you have set up the Babel plugin correctly.

Our craco.config.js uses craco-linaria plugin to compile css-in-js to regular js, how do we solve this problem?

- Bit version: 14.7.6
- Node version: 12.12.0
- yarn version: 1.19.1
- Platform: Mac OS
- Bit compiler (include version): react-typescript@3.1.57
- Bit tester (include version):

**Comment by JoshK2** [comment]
Hi, I think maybe this problem can be solved by improving the compiler to run craco plugin.
Can you please share a component example that uses this and also links to docs on how to use this library?

**Comment by hazratgs** [comment]
> Hi, I think maybe this problem can be solved by improving the compiler to run craco plugin.
> Can you please share a component example that uses this and also links to docs on how to use this library?
> 
> Also, if you have JS components that use this, please tell me because the solution for them can be very quick.

[linaria](https://github.com/callstack/linaria), it needs to pre-compile css-in-js into a static .css file, how can this be done in the bit.dev compiler? is there a webpack plugin how to use it? and is it real at all?

**Comment by JoshK2** [comment]
@hazratgs 
The current version of Bit does not provide an option to configure webpack plugin. This option will be available in the next version that we will release very soon.
At the moment, you can configure Babel and TSconfig in the current version of the compilers.

Maybe I can find a temporary solution for this to work, but I need more information, such babel config or TSconfig you are using, and also an example of a complete component.
