### ISSUE TITLE
Support for the experimental syntax 'jsx' isn't currently enabled

### ISSUE THREAD

**Issue by osequi** [teambit/bit#3166]
### Describe the bug

After adding `import H1 from "@bit/osequi.test.h1";` to my code I've got the following error message in the console:

```
Failed to compile.

./node_modules/@bit/osequi.test.h1/H1/H1.js
SyntaxError: /home/cs/osequi/react-classical-typography/node_modules/@bit/osequi.test.h1/H1/H1.js: Support for the experimental syntax 'jsx' isn't currently enabled (27:10):

  25 |  */
  26 | const H1 = (props) => {
> 27 |   return <Headings {...props} />;
     |          ^
  28 | };
  29 | 
  30 | H1.propTypes = propTypes;

Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.
```

### Steps to Reproduce

1. Install the component: `yarn add @bit/osequi.test.h1`
2. Import the component: `import H1 from "@bit/osequi.test.h1`

### Expected Behavior

The import should work without an error message in the console.

### Specifications

The result of `bit doctor`:

```
bit version   : 14.6.0
  node version  : v10.16.3
  npm version   : 6.13.1
  yarn version  : 1.9.4
  platform      : linux
Error report
validate bit version
  symptoms
  bit is not up to date.
    your version: 14.6.0
// @ts-ignore AUTO-ADDED-AFTER-MIGRATION-PLEASE-FIX!
    latest version: 14.8.8
  cure
  please upgrade your bit version
```

**Comment by JoshK2** [comment]
Hi, you need to import the React compiler and tag the components before exporting them.
https://bit.dev/bit/envs/compilers/react

Also, I recommend you to add React as peerDep in the package.json of your project because now React is a dependency of your component and is bad for the component size.
You can read more about it here: https://docs.bit.dev/docs/dependencies

After that, install again your component and run the project, everything should work.

**Comment by osequi** [comment]
I’ve added the React compiler and published successfuly the package. This error came up after trying to publish a new version of the package several days later.

---
cs@osequi.com
https://osequi.com

**Comment by JoshK2** [comment]
I checked again and you have not added the compiler (components can be published without a compiler), you can see it in the status of the component, that is "None".
And also, in the tab code, you can see that no compiler is attached, you can see the difference here:
https://bit.dev/bit/evangelist/elements/button/~code

**Comment by osequi** [comment]
Ok, thanks a lot, I'll figure out the rest. The bug can be closed but and I'll have to learn Bit.dev. :+1:

**Comment by nsebhastian** [comment]
Hi @JoshK2 I encountered the same error when importing a styled component and running `bit start` command on Bit Harmony. The error is as follows:

```
./node_modules/@my-scope/ui.button/dist/button.js
SyntaxError: /Users/nsebhastian/Desktop/Sandbox/bit-demo/node_modules/@my-scope/ui.button/dist/button.js: Support for the experimental syntax 'jsx' isn't currently enabled (26:3):

  24 |   children
  25 | }) => (
> 26 |   <BaseButton 
     |   ^
  27 |     variant={variant} 
  28 |     disabled={disabled}>{children}</BaseButton>
  29 | )

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
```

Bit version: 0.0.337

I applied React environment in `workspace.jsonc` config:
```
"teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      /**
       * uncomment to apply the react environment on all components.
       **/
      "teambit.react/react": {}
    }
  }
```

Could you help me figure out what's wrong? Thank you
