### ISSUE TITLE
bit login doesn't work in Windows WSL

### ISSUE THREAD

**Issue by scotthwsnyder** [teambit/bit#3188]
### Describe the bug
bit login command line doesn't work in Windows WSL because the browser is unable to redirect to the 127.0.0.1 address.  To workaround, use proxy IP that can be found with ifconfig

### Steps to Reproduce

1. Be working in WSL environment
2. run `bit login`
3. Browser redirects to http://127.0.0.1:8085... but is unable to load the page.  Failed to respond error.

My rationale: 
See below for workaround

### Expected Behavior

Browser successfully opens to a confirmation page at http://127.0.0.1:8085...

### Specifications
- Bit version: 14.8.8
- Node version: 12.18.3
- npm / yarn version: 1.22.4
- Platform: Windows WSL Ubuntu-18.04

### Additional context

Workaround:
1. While `bit login` is running, open another terminal and run `ifconfig`
2. In the results you'll see an ip address next to the word "inet"  mine was 172.xx.xx.149
3. Go back to the browser tab that failed to redirect, replace 127.0.0.1 with this IP address
4. Load the page successfully

Note: simply replacing 127.0.0.1 with "localhost" did not work for me

**Comment by JoshK2** [comment]
Hi, please see here the solution:
https://github.com/teambit/bit/issues/2848
It's should work.

**Comment by scotthwsnyder** [comment]
Ahh yes thank you @JoshK2. Could I recommend that something about this be added to the Getting Started documentation? I struggled with it for a long time and couldn’t find any help, but if there was a note for WSL users that pointed to that original GH issue, I would have worked around it quickly.

**Comment by JoshK2** [comment]
Hi @scotthwsnyder , you right, we should add this to the docs, I'll send this to the right person.
