### ISSUE TITLE
Bit Import: error: received an invalid response from the remote SSH server.

### ISSUE THREAD

**Issue by rdforte** [teambit/bit#3206]
### Description

When running a bit import I am getting the following error message:

error: received an invalid response from the remote SSH server.
to see the invalid response, have a look at the log, located at /Users/ryanforte/Library/Caches/Bit/logs/debug.log

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.

### Specifications

- Bit version: 14.8.8
- Node version: 12.18.3
- npm / yarn version: 6.14.6
- Platform: React
- Bit compiler (include version): react@1.0.20, react-typescript@3.1.57

### Context and additional information

Recently We just removed a whole heap of components from the repo and re added them. Everything seemed to be running well though now when I run a bit import I am getting an error and not to sure how to go about this one. Any help would be much appreciated.
I have access to the logs as well if you would like to see them.

**Comment by davidfirst** [comment]
It might be a result of importing a large volume of content. There is a pending issue about this in the ssh2 lib.
You can verify whether this is the issue by trying to import individual components or by using namespaces (e.g. `bit import collection/namespace/* --objects` ).

**Comment by gogoyqj** [comment]
@davidfirst seems there' max length limit of `str` at about 380 thousands?

```ts
  return this.exec(`_fetch ${options}`, idsStr, context).then((str: string) => {
      const parseResponse = () => {
        try {
          const results = JSON.parse(str);
          return results;
        } catch (err) {
          throw new SSHInvalidResponse(str);
        }
      };
```

**Comment by davidfirst** [comment]
@gogoyqj , makes senes, some node versions throw out-of-memory when JSON.parse() gets a large string.
This issue is fixed in the upcoming release (no ETA yet). It is changed to not serialize to JSON but to stream it directly to an HTTP server.

**Comment by itaymendel** [comment]
this is resolved in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
