### ISSUE TITLE
Angular tutorial failed on "Modify the Component > Update the Code" step

### ISSUE THREAD

**Issue by atropo** [teambit/bit#3225]
### Describe the bug

I follow the tutorial, for Angular and everything works fine until I reach the step where I have to import the component in another project to edit it.
After I edit it and I compile it I get an error.

### Steps to Reproduce

1. Create a angular project with `npx --package @angular/cli ng new my-new-app`
2. Initialize `bit`, import the component and add it to the application [Import the Component](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial#import-the-component)
3. Update the code as in the section of the tutorial [Update the code](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial#update-the-code)

4. Compile the changes with `bit build`, the app gets reloaded but I cannot see the changes
5. Stop the server and restart it with `ng serve`

### Expected Behavior

I expect to see the updated component in the application.

### Screenshots, exceptions and logs
I get `error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class.`

![image](https://user-images.githubusercontent.com/2064939/96165013-59801800-0f1c-11eb-8959-dcdf37d90233.png)

### Specifications
* `bit version 14.8.8`
* `node version v12.16.1`
![image](https://user-images.githubusercontent.com/2064939/96165245-a8c64880-0f1c-11eb-8d46-8d68b757860a.png)

**Comment by matusbielik** [comment]
Well written and I am facing the very same bug, following the tutorial (except now using Angular 11).
I've tried this numerous times, reinstalled / rebuilt everything I could. This problem occurs right after the second `bit build`.

@atropo did you learn anything about this since?

**Comment by itaymendel** [comment]
bit doesn't support these versions of angular at the moment. we'll be revisiting angualr support after bit v15 is released later this week.
