### ISSUE TITLE
Bit Unable to read Absolute Paths or Aliases

### ISSUE THREAD

**Issue by ahmadawais** [teambit/bit#3241]
Hi folks,

Have a couple of enterprise clients looking at Bit as a potential integration for their React projects. Sadly, Next.js absolute paths and aliases are not understood by Bit which makes it hard for me to recommend it to them.

Here's a bit of a context on what I mean:

https://nextjs.org/docs/advanced-features/module-path-aliases

This allows me to do stuff like this https://on.awais.dev/9ZuBR0yb

![](https://on.awais.dev/9ZuBR0yb)

E.g. 
import { urlNoTrailingSlash } from 'utils/config';
import { GlobalContext } from 'utils/GlobalContext';

Now, `utils` exist in the root folder as suggested by the `jsconfig.js` file that currently has this

{
	"compilerOptions": {
		"baseUrl": "."
	}
}

So, the baseUrl as you see is considered the root dir.

But when I run `bit status` I end up with missing pkg deps https://on.awais.dev/9ZuBR04N

![](https://on.awais.dev/9ZuBR04N)

```sh
bar ...  issues found
       missing packages dependencies (use `bit install` to make sure all package dependencies are installed):
          components/Bar.js -> components, components, utils, utils, utils, utils
```

It's unable to read any files from the components or utils folder due to the absence of relative paths since all the import paths are absolute or aliases.

It feels like that there will be a super easy fix for this, reading the jsconfig.js file.

I hope you can solve this one quickly.

Looking forward!

**Comment by ahmadawais** [comment]
[This section](https://docs.bit.dev/docs/add-and-isolate-components#missing-package-dependencies) has a link to custom paths resolution which is broken, had it been open-source I could have sent a PR just saying ;)

I believe the right link is https://docs.bit.dev/docs/dependencies#custom-paths

**Comment by JoshK2** [comment]
Hi @ahmadawais 
We support the option to configure custom paths:
https://docs.bit.dev/docs/dependencies#custom-paths (the same link as you sent)

And for doing this, you need to add the resolve modules option in the Bit config object, and use the `aliases` option:
https://docs.bit.dev/docs/conf-bit-json#resolvemodules

It's important to know that we'll not support this in the next major version.
In the next version, we'll recommend using only the Bit package name between components, and not relative links.
The Bit package name is created after a component is exported or it can be created before, using `bit link` and `defaultScope`: 
https://docs.bit.dev/docs/apis/cli-all#link
https://docs.bit.dev/docs/conf-bit-json.html#defaultscope
In the next version, it will be created automatically before so it will be possible to use it before exporting the components.

And about the Docs, it's open-source and I fixed it:
https://github.com/teambit/docs

Thanks

**Comment by ahmadawais** [comment]
Thanks for sharing that. I will dig in. The problem is, I do want to use bit for components but initially, all the components are local. Hence the absolute path aliases like that. I believe that not supporting this would be a bad idea. Like e.g. even VSCode supports them — it's a simple feature that has a great benefit. Or you can provide a codemod to help this (which would be hard to write, and instead just supporting an alias via jsconfig.json file is a better idea).

**Comment by ahmadawais** [comment]
>The Bit package name is created after a component is exported or it can be created before, using bit link and defaultScope:

Problem is that I can't export components due to the ` missing packages dependencies ` issue.

>And about the Docs, it's open-source and I fixed it:

I don't see a link to edit docs inside the docs site (that'd help get improvements/PRs for stuff like this)

**Comment by ahmadawais** [comment]
**UPDATE**: The following code fixed it.

```json

"bit": {
		"env": {
			"compiler": "bit.envs/compilers/react@1.0.21"
		},
		"componentsDefaultDirectory": "components/{name}",
		"packageManager": "npm",
		"resolveModules": {
			"modulesDirectories": [
				"."
			]
		}
	},
```

**Comment by benjgil** [comment]
Hi @ahmadawais - glad to hear you fixed the issue. It looks like the solution in the docs @JoshK2 sent on, did they help then?

With regards editing the docs, in the top right corner of every page there's an 'edit' button, which leads you to an edit page of the docs which are indeed OSS. Please feel free to suggest any updates you feel will make them clearer and more helpful to Bit users.

**Comment by benjgil** [comment]
@ahmadawais and regards your comment about dropping support for aliases in future.

We will be doing this as instead of needing to use aliases, all Bit components, even those which are only local, will have a compiled version placed in the projects node_modules folder (after running `bit compile`), so you will always import a Bit component as a node_module import and not a relative import so a place in the filesystem.

This should only improve the dev experience, as now instead of having to go back once you've completed the dev work to change all the relative/aliased imports to node_modules packages, they are already imported like that even during the dev process and no need for any changes.

I hope that's clear, please let me know if clarification is needed.

**Comment by kdonovan** [comment]
I may be misunderstanding, but it sounds like under the new system all files inside the bit component that currently reference other files _in the same component_ with convenient aliases (from `jsconfig.json` - e.g. `@me/foo`) will now have to import from `@some-long/unpleasant.to.type.name` w/ the explicit full package name.

This feels like such a step backwards for the dev experience that, after considering downgrading bit to the version that supports resolveModules above, I eventually decided to keep my components managed manually for now. :/

**Comment by davidfirst** [comment]
@kdonovan , files within one component refer to each other via relative path, no need for the full package-name. Only when one component requires/imports another component, then the package-name is needed.

**Comment by hyoretsu** [comment]
The old docs link really should redirect to the new one. It's a mess, specially when it's already hard to find answers searching for "Bit" on Google

**Comment by awatson31911** [comment]
> Hi @ahmadawais We support the option to configure custom paths: https://docs.bit.dev/docs/dependencies#custom-paths (the same link as you sent)
> 
> And for doing this, you need to add the resolve modules option in the Bit config object, and use the `aliases` option: https://docs.bit.dev/docs/conf-bit-json#resolvemodules
> 
> It's important to know that we'll not support this in the next major version. In the next version, we'll recommend using only the Bit package name between components, and not relative links. The Bit package name is created after a component is exported or it can be created before, using `bit link` and `defaultScope`: https://docs.bit.dev/docs/apis/cli-all#link https://docs.bit.dev/docs/conf-bit-json.html#defaultscope In the next version, it will be created automatically.
> 
> And about the Docs, it's open-source and I fixed it: https://github.com/teambit/docs
> 
> Thanks

Hi! All of these links redirect to the same page: https://bit.dev/docs/quick-start/hello-world

Are you able to provide updated links please?

**Comment by benjgil** [comment]
All the links, and information in that answer, are very outdated and refer to an old version of bit which we no longer support.

As myself and David answered above, there is now no support for aliases as they are not portable and when you consume your components outside of the workspace the aliases are defined in the consuming project will give an error as it wont know about those aliases.

Instead, for local development all components are treated by bit as standalone entities, and have a node_modules package as soon as they are created, so components can refer to each other by their package name, even if the component consumed only exists locally.

And files in the same component should of course just use relative paths, e.g. `import { somethingInThisComponent } from './other-folder/in-this-componen'`
(if you're not referencing a file that's in the current component, do not use relative paths, for the same reason you shouldn't use aliases).
