### ISSUE TITLE
Bit export: component was not found

### ISSUE THREAD

**Issue by lirwin3007** [teambit/bit#3254]
### Description

I'm taking my first steps with bit, but am running into issues with the `bit export` command.
I am following the steps at https://docs.bit.dev/docs/tutorials/bit-vue-tutorial with my own Vue project.

Replications steps:
```
  $ git clone https://github.com/lirwin3007/bit-error-repo.git
    ...

  $ cd bit-error-repo/

  $ bit init
    successfully initialized a bit workspace.

  $ bit add src/components/user/Pie.vue --id pie
    tracking component pie:
    added src/components/user/Pie.vue

  $ bit status
    new components
    (use "bit tag --all [version]" to lock a version with all your changes)

         > pie ... ok

  $ bit import bit.envs/compilers/vue --compiler
    the following component environments were installed
    - bit.envs/compilers/vue@0.1.13

  $ bit build
    ...
    ✔ isolating component - pie
    pie
    / ... /bit-error-repo/dist/demo.html
    / ... /bit-error-repo/dist/pie.common.js
    / ... /bit-error-repo/dist/pie.umd.js
    / ... /bit-error-repo/dist/pie.umd.min.js

  $ bit tag --all 0.0.1
    ✔ isolating component - pie
    1 component(s) tagged
    (use "bit export [collection]" to push these components to a remote")
    (use "bit untag" to unstage versions)

    new components
    (first version for components)
         > pie@0.0.1

  $ bit status
    staged components
    (use "bit export <remote_scope> to push these components to a remote scope")

         > pie. versions: 0.0.1 ... ok

  $ bit export username.collection
    error: component "5f920c4b1fc0160013431d83/pie@0.0.1" was not found
```

(I've omitted my username and collection name from that last command)

I've searched for previous issues and found #2171, but that seems to be closed, and the solutions proposed in there don't seem to work for me...

### Specifications

- Bit version: 14.8.8
- Node version: 10.19.0
- npm / yarn version: npm 6.14.4
- Platform: Ubuntu 20.04.1 LTS
- Bit compiler (include version): bit.envs/compilers/vue@0.1.13
- Bit tester (include version): N/A

### Context and additional information

Hopefully the linked repo will be all the context required :+1:
The repo is a redacted extract from a commercial project, so the component itself probably wont make much sense out of context, but it provides enough of a component to replicate this issue.

**Comment by GloriaCHL** [comment]
The same problem happening to me, and I use react. Wait for help ~~~~(>_<)~~~~

**Comment by GloriaCHL** [comment]
I found that I can export to old collection which create at few months ago. But if export to collection that create at right now will get      the `component not found` error.

**Comment by mistre83** [comment]
Hi, same problem here. I'm trying to follow the tutorial and when i try to export i got the error "error: component ABC was not found.

I tried with the tag `--all-versions` too but the error is the same

**Comment by lirwin3007** [comment]
Looks like it is a common issue then. Hopefully the replication steps here should be a big help for someone more experienced on the project to help with 👍

**Comment by GiladShoham** [comment]
Thanks all, we will check it

**Comment by GiladShoham** [comment]
This should be fixed already. Please check again

**Comment by lirwin3007** [comment]
I'm sorry, do you mean that it is already fixed in the version of bit that I'm using? (14.8.8)
If so, have you been able to follow the steps that I outlined using that version and not receive the error? Because I'm still recieving an error when I follow the steps

**Comment by GiladShoham** [comment]
It was an error on our server. It should be fine now if you follow the steps again.
Please make sure to use new clone as you might have some cache in your folder. And better to delete and recreate the collection on bit.dev

**Comment by lirwin3007** [comment]
Ah that's great, thanks! I'll give it another go and let you know how I get on!

**Comment by lirwin3007** [comment]
That's worked now :+1: Cheers!
