### ISSUE TITLE
Allow component directory to be added that uses package.json instead of index.js

### ISSUE THREAD

**Issue by storrdev** [teambit/bit#329]
The component style adopted by my team requires a component to adhere to the following file structure:

```
ComponentName/
   - ComponentName.js
   - package.json
```

Currently when adding a component, I receive this error:

```
fatal: the main file index.[js, ts, css, scss, less, sass, jsx, tsx] was not found in the files list src/components/Input/Input.js, src/components/Input/Input.scss, src/components/Input/package.json
```

I am requesting that the requirements for adding a component be expanded to include components organized in the manner above.

**Comment by GiladShoham** [comment]
Thank for your feedback @storrdev 
bit already support this kind of structure all you have to do is specify the main file during the add.
in your case for example:
`bit add ComponentName -m ComponentName/ComponentName.js`

If you are trying to add multiple directories at once (each folder represent a component) and the main file name is same as the folder/component name you can use dynamic args in the main file name.
for example for this structure:
![structure](https://image.prntscr.com/image/8dF-x5bSTXGm0-SpG5wO7g.png)
you can use the following bit add command:
`bit add */ -m {PARENT_FOLDER}/{PARENT_FOLDER}.js`
and then when you run bit status:
![status](https://image.prntscr.com/image/NCH-2yVpT8CG1uDdBvCKoQ.png)

If you need more help, let us know.
have a good day.

Gilad
