### ISSUE TITLE
Question around the use of bit components in npm packages

### ISSUE THREAD

**Issue by Fgerthoffert** [teambit/bit#3295]
### Description

This is not an urgent question, the objective is to better understand bit and I feel this could also be useful to others.

Over the past few months, I've been building a set of simple Open-Source re-usable components (https://bit.dev/zencrepes/zindexer/) and I find it super convenient to share bits of code (types, small data ingesters, some schemas) between various node microservices.

It has all been working perfectly fine, but recently I wanted to import one of those small components in another CLI tool (built with OCLIF), remotely related (not same org, not same CI/CD) and aimed at being installed locally (i.e. `npm install -g anApp` and run). 

At that point I for that error when installing the published package:
```
 ~ % npm install -g anApp
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bit%2fzencrepes.zindexer.testing-states - Not found
npm ERR! 404 
npm ERR! 404  '@bit/zencrepes.zindexer.testing-states@^0.0.3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'anApp'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-10-30T00_50_07_369Z-debug.log
```
All probably went fine locally since I had bit setup on my machine.

I understand running `npm config set @bit:registry https://node.bit.dev` would fix it, but not something necessarily easy for someone just wanting to install that cli tool.

Anyway, the root of what is unclear to me is why I haven't faced it earlier on the small services I mentioned earlier (and their docker build via GitHub actions). I see in the docs https://docs.bit.dev/docs/ci#bit-installed-components that for GitHub actions there's a need to declare the registry.

But for example on this one: https://github.com/zencrepes/zqueue is using 12 components, using GitHub Actions, running yarn is perfectly fine, building the docker images fine (check out the logs if curious). But without declaring the bit registry anywhere.

Or could it be that GitHub actions already have the bit registry setup globally?

### Specifications

- Bit version: 14.8.8
- Node version: 12.16.2 
- npm / yarn version: 1.22.4
- Platform: MacOS (and GitHub Actions)
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

Everything should be in the description.

**Comment by davidfirst** [comment]
Interesting!
Github action pobably don't have bit configured in the registery. The only option I could think of why Yarn doesn't fail without configuring `@bit` scope in the .npmrc is that it resolves the final URL from the lock file. 
For example, you have this:

```

"@bit/zencrepes.zindexer.config@0.0.17":
--
328 | version "0.0.17"
329 | resolved "https://node.bit.dev/zencrepes.zindexer.config/-/zencrepes.zindexer.config-0.0.17.tgz#bde38df4bd451d59bbe2d46014aa92e8625c5107"

```
in your yarn.lock file.
