### ISSUE TITLE
Exporting components with --all flag stuck

### ISSUE THREAD

**Issue by virat21** [teambit/bit#3296]
### Description

I've around 30+ component tagged and ready to export but each time when I try to export with `--all` and wait for a while around 3-4 hr. I'm having a pretty good internet connection. looks like the process was stuck. so I just kill it and try to export one by one. then it works. but we are using CI/CD in workflow and exporting one by one is not a good solution

### Specifications

- Bit version: bit 14.8.8
- Node version: node v14.8.0
- npm / yarn version: yarn 1.22.4
- Platform: macOS 
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.57
- Bit tester (include version): -

**Comment by davidfirst** [comment]
@virat21 , the issue is a combination of a bug in ssh2 package and node >= v14.1.0. See more details here: https://github.com/teambit/bit/issues/2844.

The workaround for now is to downgrade to node <=v14.0.0
