### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by wesselvdv** [teambit/bit#3304]
### Describe the bug

When adding a component that contains an index.js and index.d.ts it's sometimes error'ing on the index.d.ts with `Cannot read property 'map' of undefined`

### Steps to Reproduce

**index.js**
```javascript
!function(e,r){for(var t in r)e[t]=r[t];r.__esModule&&Object.defineProperty(e,"__esModule",{value:!0})}(exports,(()=>{"use strict";var e={1635:(e,r)=>{Object.defineProperty(r,"__esModule",{value:!0}),r.entries=void 0,r.entries=function(e){return Object.entries(e)}}},r={};return function t(n){if(r[n])return r[n].exports;var o=r[n]={exports:{}};return e[n](o,o.exports,t),o.exports}(1635)})());
```

**index.d.ts**
```typescript
declare type Entries<T> = {
  [K in keyof T]: [K, T[K]];
}[keyof T][];
export declare function entries<TObject>(obj: TObject): Entries<TObject>;
export {};
```

1. npx bit add index.js --id test/index
2. npx bit add index.d.ts --id test/index
3. npx bit tag test/index 1.0.0

### Expected Behavior

It should successfully tag, and allow me to export it.

### Screenshots, exceptions and logs

```
error found while parsing the file (edit the file and fix the parsing error):
index.d.ts -> Cannot read property 'map' of undefined
```

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 14.8.8
- Node version: 14.15.1
- pnpm version: 5.10.2 
- Platform: Arch Linux
- Bit compiler (include version): N/A 
- Bit tester (include version): N/A

**Comment by itaymendel** [comment]
TS workflow significantly improved in v15, and this issue should be resolved.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
