### ISSUE TITLE
typescript import compiler error

### ISSUE THREAD

**Issue by jony89** [teambit/bit#3329]
### Describe the bug

A clear and concise description of the issue.

### Steps to Reproduce

run `bit import bit.envs/compilers/typescript` 

### Screenshots, exceptions and logs

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@bit%2fbit.envs.common.compiler-types - Not found
npm ERR! 404 
npm ERR! 404  '@bit/bit.envs.common.compiler-types@0.0.11' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'typescript'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ariel/.npm/_logs/2020-11-04T16_43_54_960Z-debug.log
```

### Specifications

bit -v: 14.8.8
node -v: v12.13.1
npm -v: 6.13.4

**Comment by itaymendel** [comment]
TS workflow buffed significantly in bit v15.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
