### ISSUE TITLE
Bit fails to isolate component when being a dependent. 

### ISSUE THREAD

**Issue by Idono87** [teambit/bit#3335]
### Description
I've got a problem where Bit fails to isolate a dependency. Basically I've got two components A and B. Component B depends on A. 

Component A is successfully built, tested and published on it's own. But when trying to build component B, the isolation of component A fails. 

I get the following error when isolating component A.
> error TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
> export { WrapperProps };

This failure is odd because i do re-export all my types with "export type". Isolation works when testing component A and when the entire project gets compiled with "tsc". 

### Specifications

- Bit version: 14.8.8
- Node version: 14.15.0
- npm / yarn version: npm 16.13.3
- Platform: Windows
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.61
- Bit tester (include version): bit.envs/testers/mocha@8.1.3
 
### Context and additional information

The project is a basic React-Typescript project.

**Comment by itaymendel** [comment]
issue resolved in v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
