### ISSUE TITLE
Bit import in subfolder

### ISSUE THREAD

**Issue by deeep** [teambit/bit#3337]
Hi!

bit import:

" ... Update the **workspace top level package.json** to include the new component as a dependency ..."

" ... Create a symlink between the **top level node_modules in the workspace** and the location of the installed component ... "

Is there way to put this dependency to the  **current folder package.json**, that is a subfolder?
(and create the symlink in the node_modules of this folder)

### Specifications

- Bit version: 14.8.8
- Node version: 15.0.1
- npm / yarn version: 7.0.8
- Platform: Linux

**Comment by itaymendel** [comment]
this flow is updated in v15, and now bit is working in a similar way to what you suggested.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
