### ISSUE TITLE
Compiler dependencies fail to install with node 15+ npm 7+

### ISSUE THREAD

**Issue by paulnorthup** [teambit/bit#3341]
### Describe the bug

Bit cannot build dependencies for react compilers (and maybe others, only tested with react) using node 15.1.0 and npm 7.0.8

### Steps to Reproduce

1. use npx to build a clean Create React App
2. ensure using node 15.1.0 and npm 7.0.8
3. ensure yarn 1.22.10 and use `yarn` as bit package manager
4. ensure using bit 14.8.8
4. `bit init` and `bit import bit.envs/compilers/react --compiler`

### Expected Behavior

"Ensuring package dependencies" should hang for a while and then return an error:

`failed parsing the output of npm list due to an error: Unexpected token { in JSON...`

The error should be coming from https://github.com/teambit/bit/blob/76f1f058f65b43c818b17a9c017cd7661291d921/src/npm-client/npm-client.ts#L236

and 

### Screenshots, exceptions and logs

By changing the output of the built npm-client.js to print the `str` that `parseNpmListJsonGracefully` receives as an argument should produce: 

```
{
  "version": "1.0.21",
  "name": "@bit/bit.envs.compilers.react",
  "problems": [
    "missing: @types/mocha@^7.0.2, required by @bit/bit.envs.compilers.react@1.0.21",
    "missing: @types/node@^12.7.4, required by @bit/bit.envs.compilers.react@1.0.21",
    "missing: @types/vinyl@^2.0.3, required by @bit/bit.envs.compilers.react@1.0.21",
    "missing: bit-bin@14.7.6, required by @bit/bit.envs.compilers.react@1.0.21"
  ],
...
}
```

### Specifications

- Bit version: 14.8.8
- Node version: 15.1.0
- npm version: 7.0.8
- yarn version: 1.22.10
- Platform: OS X 10.15.7
- Bit compiler (include version): react 1.0.20 and 1.0.21 both fail
- Bit tester (include version): N/A

### Additional context

Slack discussion: https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1604636241228400

**Comment by rlveiga** [comment]
Have you been able to solve this issue yet?

**Comment by paulnorthup** [comment]
Downgrading to node 14 via nvm solves the problem for me. I'm not sure what the specific issue is around node 15 but that's as close as I could get to putting my finger on the problem.

**Comment by tylerthecoder** [comment]
I am experiencing this problem as well but I am not using node 15
bit 14.8.8
node 14.15.1
npm 7.0.7
yarn 1.2..10

**Comment by tylerthecoder** [comment]
Changing node version to 14.5.0 seems to have fixed the issue for me.

**Comment by paulnorthup** [comment]
Just hit this problem as well with 14.15.1 -- downgrading to 14.5 also worked for me, thanks @tylerthecoder.

I don't know what's different in each of these versions of node but something wonky is happening. I don't have the time to dig deeper at the moment.

**Comment by itaymendel** [comment]
issue was resolved in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Comment by harshlele** [comment]
whens v15 going to be released on npm? i get this error even on nodejs 14.5.0
