### ISSUE TITLE
Issue with bit export scope and ssh

### ISSUE THREAD

**Issue by puffstream** [teambit/bit#339]
Hey guys,

love the work, but running into issue with ssh on exporting to my scope.

Heres the error:

Error: Encrypted private key detected, but no passphrase given

I followed everything on getting started, using a Mac as well. I already had my own SSH already set up on my machine so using that. And works well with Github and other services.

Any ideas would be appreciated, thanks!

**Comment by GiladShoham** [comment]
Hi @puffstream 
Thanks for your feedback.
bit is currently not supported ssh keys with a passphrase.
you can see more details in this issue: https://github.com/teambit/bit/issues/119
You can generate a new ssh key without passphrase and use this command to tell bit to use it
 `bit config set ssh_key_file {path to the ssh file}`
If you need more help with the new ssh key, just let us know.

**Comment by puffstream** [comment]
@GiladShoham Okay, thanks. Got it!

Might have a go trying to set up x2 ssh keys

**Comment by puffstream** [comment]
Okay, just removed the passphrase. Much easier :smile

**Comment by GiladShoham** [comment]
@puffstream I'm closing this issue since we already have one for supporting passphrase.
If you need any more help just open a new one.
you can also reach us on [gitter](https://gitter.im/bit-src/Bit) anytime.
