### ISSUE TITLE
How to limit ssh user who could only use the SSH connection to push and pull but can’t shell onto the machine like git

### ISSUE THREAD

**Issue by mcuking** [teambit/bit#3440]
Hello, I deployed bit server on my own server recently. And other person could use bit cli to push and pull code from remote repo on my server, because their ssh public key is in the authorized_keys file on my server.

But other person also could login my server via terminal and even could delete the code on the server. So I want to limit user who could only use the SSH connection to push and pull but can’t shell onto the machine like git. Like the link below:

[Git-on-the-Server-Setting-Up-the-Server](https://git-scm.com/book/en/v2/Git-on-the-Server-Setting-Up-the-Server)

If specify git-shell instead of bash or csh for that account’s login shell, user could only push and pull code from git repo.

Is there any helpful information about bit?

**Comment by gogoyqj** [comment]
same issue

**Comment by itaymendel** [comment]
Bit-OSS does not support permission management. you can use regular file permissions in unix, as ssh will fail read/write according to them.
