### ISSUE TITLE
How to build a typescript react component which import less ?

### ISSUE THREAD

**Issue by GloriaCHL** [teambit/bit#3461]
### Description

I have a typescript react component, which import a less file inside. Like this:

![image](https://user-images.githubusercontent.com/10557315/100855176-dc593400-34c4-11eb-843c-a333140c3e11.png)

And use complier: `bit.envs/compilers/react-typescript@3.1.61`

But when I run `bit build`, I get Error like this:

![image](https://user-images.githubusercontent.com/10557315/100855655-61dce400-34c5-11eb-8dfb-cec102b88367.png)

### Specifications

- Bit version: 14.8.8
- Node version: v14.15.0
- yarn version: 1.22.10
- Platform: Mac OS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.61
- Bit tester (include version):-

### Context and additional information

How can I build a typescript react component which contain less modules?

**Comment by GloriaCHL** [comment]
And I try css file like this:

![image](https://user-images.githubusercontent.com/10557315/100958122-b8463300-3556-11eb-9fc5-5e6290f5337e.png)

Use like this:

![image](https://user-images.githubusercontent.com/10557315/100958241-f3e0fd00-3556-11eb-9a6d-e94366cb1ee4.png)

The component can build and export to bit.dev. But when I install this component I found that component css not work.

**Comment by itaymendel** [comment]
bit v15 has native support for less.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
