### ISSUE TITLE
Modify dependency from import not reflect are new version installed

### ISSUE THREAD

**Issue by roshanshrestha01** [teambit/bit#3514]
### Description
I have Component A as below:

    import * as api from '../../api/index.js`
    
    class ComponentA extends React.Component {
      componentDidMount() {
        api.get()
      }
    
      render () {
        return (
            <h1>test </h1>
          )
       }
    }index.js as:```export function get() {
  console.log('get here in project A")
}

    
    Two components are added with `bit add`.
    
    I want to modify index.js in consume side with different code.
    
    I have done `bit import @bit/<username>.<collection>/index.js`. Modified code base example
    export function get() {
  console.log('get here in project B')
}
```

and run `bit build`. It runs fine.

But when I update `@bit/<username>/<collection>/ComponentA` in first project such as below code export with `bit export` after tagging and run `npm i @bit/<username>/<collection>/ComponentA` in consumes. Component A refers to old console.log with `get here in project A` not referring to modified version from import from local workspace.

    import * as api from '../../api/index.js`
    
    class ComponentA extends React.Component {
      componentDidMount() {
        api.get()
      }
    
      render () {
        return (
            <h1>modified</h1>
          )
       }
    }<!-- A clear and concise description of what you are trying to achieve -->### Specifications* Bit version: 14.8.8
* Node version: 10.23.0
* npm / yarn version: 6.14.8
* Platform: ubuntu 18.04
* Bit compiler (include version):
* Bit tester (include version):

### Context and additional information
<!-- A clear and concise description of the type of project and environment. Anything that will help others get a better understanding of your use case. -->

**Comment by itaymendel** [comment]
i don't think i fully understand what you are aiming to build here.
can you please try and give some additional context for the overall issue you want to resolve with this workflow?

**Comment by roshanshrestha01** [comment]
I want to override the function `api.get` with in the exported component which is Component A in above example.

When we create component to export we need to add their dependencies. I want to modify logic in dependency in project that consumes that component.
