### ISSUE TITLE
Bit.dev: Sort by Popularity

### ISSUE THREAD

**Issue by johnrichardrinehart** [teambit/bit#3535]
Forgive me for not using the issue template and/or if this is the wrong place to post this. I think the issue template is not necessary, here.

Most large ecosystems of software projects support some notion of popularity useful for ranking projects. `Bit.dev` seems not to support querying by numDownloads/activity/stars/etc. Are there plans to support this?

**Comment by itaymendel** [comment]
hi @johnrichardrinehart 
sorry for the late response.

yes, at the moment we're focused on local dev-workflows. when this effort is done, we'll improve component discoverability.

**Comment by johnrichardrinehart** [comment]
No worries. Thanks, @itaymendel .
