### ISSUE TITLE
Login in windows using github failed

### ISSUE THREAD

**Issue by ghena** [teambit/bit#3614]
Login via cli commandline open a page and redirect after login to:

http://127.0.0.1:8085/?clientId=xxx4&redirectUri=https%3A%2F%2Fbit.dev%2Fbit-login-success&tokenyyyy&username=ghena

but i get:
{"error":{"code":999,"message":"Not Found","description":"The requested resource could not be found at this uri"}}

### Specifications

- Bit version: 14.8.8
- Node version :v12.9.1
- npm / yarn version: 6.13.7
- Platform: windows 10

**Comment by itaymendel** [comment]
`bit login` flow reimplemented in bit v15

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
