### ISSUE TITLE
Typescript React Project Throwing TS1205, Bit import fails to obey --isolatedModules flag in tsconfig.json

### ISSUE THREAD

**Issue by jasperhuangg** [teambit/bit#3633]
### Describe the bug

Auto-generated dependency files for imported source components do not obey the `--isolatedModules` flag in tsconfig.json when importing and exporting types.

This flag is enforced by any CRA projects, and it set to true every time you run `react-scripts start`.

Get `TS1205: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.` in line 2:
```
import { Elementable } from '@bit/xxx.xxx;
export { Elementable }; // <= throws error during build time
```

### Steps to Reproduce

1. Import a source component with `bit import`.
2. Run `yarn start` to run the React project locally.

### Expected Behavior
The Typescript compiler shouldn't complain about this flag not being obeyed.

### Actual Behavior
The Typescript compiler complains about this and doesn't compile.

### Specifications

- Bit version: 14.8.8
- Node version: 14.11.0
- npm / yarn version: yarn 1.22.5
- Platform: macOS Big Sur (11.0.1)
- Bit compiler (include version): react-typescript@3.1.64

**Comment by itaymendel** [comment]
Hi @jasperhuangg 
sorry for the late reply.

Bit v15 has a reimplemented solution for React-TS support and workflow that solves such issues, and let you better control TS configs.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
