### ISSUE TITLE
React is not defined when install one exported component on bit.dev

### ISSUE THREAD

**Issue by shinaBR2** [teambit/bit#3655]
### Describe the bug

Can not use the exported component in another project due to above error on runtime.

### Steps to Reproduce

1. Follow [Bit for React tutorial](https://docs.bit.dev/docs/tutorials/bit-react-tutorial) and export some component successfully at [here](https://bit.dev/vibe/react-admin-components/action-buttons)
2. Install component in another project with this syntax: `import ActionButtons from '@bit/vibe.react-admin-components.components';`
3. Run and see error in console

### Expected Behavior

Exported component should be run without any error.

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/8222892/104599855-dd2bdb00-56aa-11eb-87ca-9d03140028aa.png)
Error example when runtime

### Specifications

- Bit version: 14.8.8
- Node version: 10.17.0
- npm version: 6.11.3
- Platform: Windows
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

I have asked on stackoverflow: https://stackoverflow.com/questions/65720246/react-is-not-defined-when-install-one-exported-component-on-bit-dev

Any help will be appreciated! Thanks.

**Comment by THANHDNV** [comment]
You're missing import React from 'react' in your component

**Comment by JoshK2** [comment]
Hi @shinaBR2 thanks for opening the issue.
I responded to you in Stackoverflow.
The error was because the compiler not supported React 17, I published a new version of it and now it supports React 17. 
 please use the new version and re-export your component. https://bit.dev/bit/envs/compilers/react?version=1.0.23
