### ISSUE TITLE
NPM not working

### ISSUE THREAD

**Issue by diogopereira5** [teambit/bit#3674]
### Describe the bug

A clear and concise description of the issue.

### Steps to Reproduce

1.
1.
1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by Shwetang550** [comment]
After cloning the repo folow these simple steps to run npm:
1. Go to the cloned-repo location . Eg- cd ...location
2. run - npm install
   This will install all the dependencies attached to the project
3. Now you can run npm commands on the project.

**Comment by itaymendel** [comment]
hi, you need to make sure you are authenticated to Bit by running `bit login`. this way it can fetch your bit-dependencies.
