### ISSUE TITLE
Missing node_modules when referencing from one component to another component?

### ISSUE THREAD

**Issue by victormoove-wc** [teambit/bit#3677]
### Description

While following the guidelines for [Best Practices](https://docs.bit.dev/docs/best-practices#handling-assets), I would like to create one asset component to be shared by all components. In particular, I would like to share bootstrap, along with some other custom scss and img files, among all the components. 

I have done `npm install bootstrap@latest --save`, and in **components/assets/index.js**:
```
import 'bootstrap';
export * from './styles/app.scss';
```
and in **components/assets/styles/assets.scss**:
```
//...
@import "~bootstrap/scss/functions";
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/mixins";
//...
```

Everything seems to be good here, but when I added this dependency in another bit component,
**components/myOtherComponent/package.json**:
`"dependencies" : {
  "@bit.X.Y.assets": "^X.Y.Z"
}`
**components/myOtherComponent/App.scss**:
`@import '~@bit/X.Y.assets/node_modules/bootstrap/scss/_functions';`

I would like to import only the relevant bootstrap files in myOtherComponent, but it fails because,

in a new React app that is utilizing this component it is having errors because **node_modules/@bit/X.Y.myOtherComponent/node_modules/@bit/X.Y.assets/_node_modules/bootstrap_** is missing.

I can't seem to figure out why _node_modules/bootstrap_ exists when building assets Component by itself but is missing when build as a dependency of myOtherComponent, if it's because of the Webpack compiler or...

### Specifications

- Bit version: 14.8.8
- Node version: 14.10.0
- npm / yarn version: 6.14.10
- Platform: Windows
- Bit compiler (include version): Webpack 4.0.1
- Bit tester (include version):

### Context and additional information

In the assets component, the reason I am trying to use webpack as a compiler is because the preview is failing. It is failing because the **components/assets/styles/assets.scss** references **node_modules/bootstrap/...**, so to fix the preview, I used sass-loader with webpack. This works when building by itself, but when included as another component, that's when node_modules does not get created.

In the myOtherComponent component, it seems to work if you import both assets and myOtherComponent together into the same workspace, but I'm trying to get myOtherComponent to work by itself because the preview is failing, and I'm assuming if it works by itself, the preview should work.

**Comment by itaymendel** [comment]
components should not try to run post-css or any other actions on css.
in v15 we refactored playground to be a local workflow feature, so you can experiment with it there and bundle deps just for the preview itself. this makes this issue irrelevant, as it was resolved for v15.

We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
