### ISSUE TITLE
Playground never loads, stays on 'connecting' - No errors in console.

### ISSUE THREAD

**Issue by Lietsaki** [teambit/bit#3682]
### Description

The playground is not loading for my components. It was working perfectly two days ago, and since yesterday it says 'connecting' but never actually connects or shows any errors. Please see this [screenshot](https://prnt.sc/xgbu8o)
The components' state is 'passing' and the build was successful.

I am trying to make it work, but haven't been able to find any errors or other users reporting this problem.

### Specifications

- Bit version: 14.8.8
- Node version: 12.13.0
- npm / yarn version: npm 6.14.8 - Yarn is not installed.
- Platform: Windows 10 Pro
- Bit compiler (include version): react@1.0.21
- Bit tester (include version): jest@22.4.3

### Context and additional information

The project is a React components library, I started making two buttons to learn how Bit.dev works, haven't done anything crazy.

**Comment by itaymendel** [comment]
Hi,

sorry for the late response.
we had a few scaling issues for generating enough playground containers. a major upgrade has made to the backend infra to sustain the new load of teams/devs using Bit.
