### ISSUE TITLE
Bit Vue compiler output development distribution instead of production

### ISSUE THREAD

**Issue by azrulamir** [teambit/bit#3683]
### Description

The output that the default vue [compiler ](https://bit.dev/bit/envs/compilers/vue) generated is producing distribution for development mode. This has caused many of our projects unable to use those components that was compiled by it producing _`require statement as undefined error`_. Moreover we need the UMD generated format for some of our use cases.

This reported and solved [issue](https://github.com/vuejs/vue-cli/issues/4245) here stating that the mode supposed to be used for building should be production instead. I had tested compiling directly from vue with the mode set to production and it does seems to work and looking at the vue compiler itself, it is hardcoding the mode as development directly.

### Describe the solution you'd like

I think as for general rule, components compiled and stored at bit.dev should be production ready. Or atleast users should be able to provide parameters to the build commands as to which env it should be outputing.

### Describe alternatives you've considered

There's the bundler compiler option for vue which is usable but this will require us to recompile the UMD format manually everytime whereas the compiler version should have done this in the first place.

**Comment by itaymendel** [comment]
technically we don't even want dev bundle as well. the goal is to have a vue component compiled to a dist and not a bundle, so the consumer's bundler handles all these aspects of the workflow.
the current implementation of vue support in bit doesn't allow it. we'll be revisiting vue integration after bit v15 is released later this week.

however, i'm afraid this will take some time to introduce. i'm closing this issue, as the updated vue support will be it's own epic.
