### ISSUE TITLE
Multiple authToken 

### ISSUE THREAD

**Issue by shadeven** [teambit/bit#3703]
### Description
We have 4 machines running `npm install` which pulls components from a private registry on Bit.dev. Each machine is configured with authToken using `npm login` and `.npmrc` is stored at project level. We notice when the second machine starts running, it revokes the authToken from the first machine. It seems Bit.dev only allows one valid authToken at a time. Please confirm if this is the expected behavior.

How to allow multiple authTokens accessing Bit.dev at the same time with revoking each other? We are in free tier and if we upgrade to paid tier, will it solve the problem?

### Specifications

- Bit version: 14.8.8
- Node version: v14.15.4
- npm / yarn version: 6.14.10
- Platform: Fedora 33
- Bit compiler (include version): n/a
- Bit tester (include version): n/a

### Context and additional information
This is the command we use to generate authToken:
`npm-cli-login -u username -p password -e company@dev.com -r https://node.bit.dev -s @bit`

**Comment by itaymendel** [comment]
Hi,

You should generate the token for Bit using Bit, as node.bit.dev is a separate mechanism.
Run the `bit login` command for Bit to generate and set a token.
