### ISSUE TITLE
Bit hangs indefinately when adding a remote

### ISSUE THREAD

**Issue by vkavoun** [teambit/bit#3705]
### Description

Adding a remote scope for a private server

### Specifications

- Bit version: 14.8.8
- Node version: 14.15.4
- npm / yarn version: 6.14.11
- Platform: WSL ubuntu 20.04
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

I've created a private server on our cloud. I've created a user that I can ssh with and i run command ``bit remote add ssh://<user>@<ip>:/opt/bit/tru`` I have ssh-agent connected. When I run this command bit hangs

**Comment by itaymendel** [comment]
hi @vkavoun , we're moving away from the ssh implementation and use https.
i'm closing this topic.
