### ISSUE TITLE
Console error when installing "npm install bit-bin --global --no-optional"

### ISSUE THREAD

**Issue by Rezvitsky** [teambit/bit#3708]
Hey! When I install bit with the command "npm install bit-bin --global --no-optional", errors appear in the console.
![Screenshot_2](https://user-images.githubusercontent.com/24964186/106377013-81f92880-63cc-11eb-9243-4acca853f8c5.png)

**Comment by xiaolee55** [comment]
maybe you could run sudo npm install bit-bin --global --no-optional

**Comment by Rezvitsky** [comment]
> maybe you could run sudo npm install bit-bin --global --no-optional

I solved the given problem. This was due to the fact that I am using the ubuntu shell for the console, it was possible to install via cmd
