### ISSUE TITLE
vue component report core-js/modules/es6.regexp.replace errors

### ISSUE THREAD

**Issue by cmdfas** [teambit/bit#3723]
### Describe the bug

my vue component report `core-js/modules/es6.regexp.replace` errors

```
 ERROR  Failed to compile with 1 errors          5:28:14 AM

This dependency was not found:

* core-js/modules/es6.regexp.replace in ./node_modules/@bit/cmdfas.vue-demo-app.todo-list/dist/TodoList.js

To install it, you can run: npm install --save core-js/modules/es6.regexp.replace
```

### Steps to Reproduce

1.bit init 
2.bit add src/components/*
3.bit import bit.envs/bundlers/vue --compiler
4.bit tag --all 1.0.0
5.bit export cmdfas.vue-demo-app

### Expected Behavior

Components that can be used.

### Screenshots, exceptions and logs

**Error vue components:**

https://bit.dev/cmdfas/vue-demo-app/todo-list
https://bit.dev/cmdfas/vue-demo-app/todo-input-controls

<img width="1791" alt="WX20210202-141309@2x" src="https://user-images.githubusercontent.com/19399732/106559739-d0d7c700-6560-11eb-8156-f643daa69126.png">

**Right vue components:**
https://bit.dev/cmdfas/vue-demo-app/h1
https://bit.dev/cmdfas/vue-demo-app/todo-list-item

### Specifications

- Bit version:14.8.8
- Node version:v15.0.1
- npm / yarn version:npm6.14.10
- Platform:mac os big sur 11.11(MacBook Pro (16-inch, 2019))
- Bit compiler (include version):bit.envs/bundlers/vue v2.6.21
- Bit tester (include version):

### Additional context

```
I change core-js@3.x.x to core-js@2.6.5 is usable。
```

**Comment by itaymendel** [comment]
sadly vue support is still under development. after the release of v15 later this week we'll dive vue support.
