### ISSUE TITLE
Compiler error on component preview page 'react/jsx-runtime'

### ISSUE THREAD

**Issue by EdwardBock** [teambit/bit#3729]
### Describe the bug

I've done the tutorial for react components and tried to use the component example page. https://bit.dev/public-function/tutorial/product-list . I do not get any preview but an error message.

### Steps to Reproduce

1. Do the react tutorial https://docs.bit.dev/docs/tutorials/bit-react-tutorial
1. Use npm instead of yarn (if this is important)
1. Goto component example page

### Expected Behavior

I would expect a preview to appear with no compilation error.

### Screenshots, exceptions and logs

<img width="522" alt="Bildschirmfoto 2021-02-03 um 07 52 50" src="https://user-images.githubusercontent.com/3862417/106709456-d8e14680-65f4-11eb-82a9-9379d928036b.png">

```
./node_modules/@bit/public-function.tutorial.product-list/dist/index.js
Module not found: Can't resolve 'react/jsx-runtime' in '/capsule/node_modules/@bit/public-function.tutorial.product-list/dist'
```

### Specifications

- Bit version: 14.8.8
- Node version: v14.15.4
- npm version: 6.14.10
- Platform: MacOS Catalina
- Bit compiler: bit.envs/compilers/react@1.0.23

**Comment by EdwardBock** [comment]
Seems to work again.

**Comment by virajvchavan** [comment]
I had the same problem. Is there a known fix for this @EdwardBock ?
