### ISSUE TITLE
Error: EPERM: operation not permitted MacOS

### ISSUE THREAD

**Issue by Bastorx** [teambit/bit#3765]
Hi,

I get an error each time I try to use `bit build` or `build tag` command :

```
Warning: running bit as root might cause permission issues later
error: bit failed to build tabs with the following exception:
Command failed with exit code 1 (EPERM): npm install --no-save
Error: Command failed with exit code 1 (EPERM): npm install --no-save
    at makeError (/usr/local/lib/node_modules/bit-bin/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

### Specifications

- Bit version: 14.8.8
- Node version: 15.8.0
- npm version: 7.5.3
- Platform: MacOS 11.1
- Bit compiler: bit.envs/compilers/react-typescript@3.1.64
- Bit tester: none

### Context and additional information

I tried many things, re-install node, re-install bit-bin (with npm -g), npm clean cache -f, I even disable crsutil, chown /usr/local and run bit with sudo... Still have this error...

Could you help me?

**Comment by Bastorx** [comment]
Hi, I did a rollback to 6.14.x and it works. Seems that it doesn't work with the last version of npm..

**Comment by dmi3y** [comment]
Hi folks, I have same issue with npm 6.14.6

```
  bit version   : 14.8.8
  node version  : v12.18.3
  npm version   : 6.14.6
  yarn version  : 1.22.0
  platform      : MacOS Big Sur 11.2.1 (20D74)
```

**Comment by jimisaacs** [comment]
I found this bug to be a red herring. It kept croping up as the result of bad dependencies, circular dependencies, etc., etc. The best suggestion I got was try to build with `DEBUG=true bit build`. It gives you the location of the isolated build. `cd` to it, and try to `npm i` there. Even look at the `package.json` that's there.

**Comment by jimisaacs** [comment]
Basically `bit-bin` error messaging leaves a lot to be desired.

**Comment by jimisaacs** [comment]
OMG, I just tried something out of the blue where I had a private package, and I scoped the registry like this in `~/.npmrc`

Changed this:
```
registry= https://registry.mycompany.com/npm-registry

# bit stuff here
```
to this:
```
registry= https://registry.mycompany.com/npm-registry
@mypackagescope:registry= https://registry.mycompany.com/npm-registry

# bit stuff here
```

And where I was fight with this very error, went away like magic.

**Comment by itaymendel** [comment]
Hi,

We're rolling out a dedicated installer for Bit that does not couple the installation of Bit to be via npm. It's a part of the upcoming release of Bit v15 later this week.

Please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Comment by alejandrombc** [comment]
I updated to Bit 15, and can confirm than the error disappear. 

BUT, I got an error when exporting to the scope (because my scope is a legacy one), does this mean that my only chance is to upload all the components to a new scope for this to work?
