### ISSUE TITLE
Module not found: Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by GiovanniGiampaolo** [teambit/bit#3771]
### Description

Hi Guys I'm trying to export a component with but after several attempts, I always get this error on the preview of the component and importing the component I always get error.

`Module not found: Can't resolve 'react/jsx-runtime' in '/capsule/node_modules/@bit/giovannigiampaolo.testCollection.button/dist'`

In a very simple way I'm exporting a button from material ui, nothing special apparently.

[Here ](https://bit.dev/giovannigiampaolo/winner-components/button/~code)the code.

### Specifications

- Bit version: 14.8.8
- Node version: 14.15.3
- npm / yarn version: npm 6.14.9 yarn 1.22.5
- Platform: windows
- Bit compiler (include version): "bit.envs/compilers/react@2.0.0"
- Bit tester (include version): none

**Comment by effinrich** [comment]
Hi,
I'm getting the same error:
`module not found: Can't resolve 'react/jsx-runtime'`

React: 17.0.1

Is there a workaround?  Appears to have started over a week ago.

**Comment by GiovanniGiampaolo** [comment]
> Hi,
> I'm getting the same error:
> `module not found: Can't resolve 'react/jsx-runtime'`
> 
> **Specs:**
> 
> * bit version   : 14.8.8
> * node version  : v14.5.0
> * npm version   : 6.14.5
> * yarn version  : 1.22.10
> * platform      : darwin
> * React: 17.0.1
> 
> Is there a workaround? Appears to have started over a week ago.

I tried to use the downgrade to "react": "^16.8.6".
I read somewhere that it is recommended to use react <17 and typescript <4.0.1.
But for me, nothing changed anyway =(

**Comment by effinrich** [comment]
> > Hi,
> > I'm getting the same error:
> > `module not found: Can't resolve 'react/jsx-runtime'`
> > **Specs:**
> > 
> > * bit version   : 14.8.8
> > * node version  : v14.5.0
> > * npm version   : 6.14.5
> > * yarn version  : 1.22.10
> > * platform      : darwin
> > * React: 17.0.1
> > 
> > Is there a workaround? Appears to have started over a week ago.
> 
> I tried to use the downgrade to "react": "^16.8.6".
> I read somewhere that it is recommended to use react <17 and typescript <4.0.1.
> But for me, nothing changed anyway =(

Yes, I tried the same, but first I deleted my build directory, ran `bit reset`.  No change at all.  Quite frustrating.

**Comment by GiovanniGiampaolo** [comment]
@effinrich Yes frustrating :(
The speech is that I have tried with their basic react guide and I have the same problem even with product list.
This [one](https://docs.bit.dev/docs/tutorials/bit-react-tutorial) I mean
I also tried with a component with ZERO external dependencies but still the same problem.

**Comment by effinrich** [comment]
@GiovanniGiampaolo Yes, same here.  Tried the dumbest, simplest component.  Got the same error.  I have a component in another collection I made in December, which is working and is more complex than this one throwing the error.  The working component is React 16.9.0.

**Comment by stevepepple** [comment]
I'm getting the same issue here, when coping the React tutorial example: 
https://bit.dev/vibemap/components/project-list

**Comment by GiovanniGiampaolo** [comment]
@stevepepple Hear this thing is reassuring, the fact is that I can not understand what may be the problem because crando also other components I always have different problems.

**Comment by effinrich** [comment]
@stevepepple @GiovanniGiampaolo I just built a fresh CRA then reverted react-scripts to 3.4.1 and react to 16.9.  I went thru the quick start steps exactly, exported to bit.dev.  Same errors for all 4 demo components, so it's not the react version.  It just seems broken across the board and there are tickets 8 days old with zero response, so I'm moving on I think.  That's always a bad sign when critical bugs aren't addressed even to state to us they are aware of the issue.  Maybe they are a very small team with a huge application, which is definitely feasible.

**Comment by littlefinger42** [comment]
This is a critical bug which seems to stop all new component development

**Comment by tahins** [comment]
Downgrading the React compiler for Bit from version `2.0.0` to `1.0.30` worked for me.

**Comment by itaymendel** [comment]
Hi !

Sorry for the late response here, I see that many devs face this issue with their React components. This, and other react-workflow issues have been fixed in Bit v15.
We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

**Comment by effinrich** [comment]
> Hi !
> 
> Sorry for the late response here, I see that many devs face this issue with their React components. This, and other react-workflow issues have been fixed in Bit v15.
> We'll start rolling out v15 of Bit this week, please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.

That’s great news and thanks for the thorough response!  I’ll hit you up on slack in a bit (no pun, I promise).
