### ISSUE TITLE
what does `bit start` do, and bit now support http over ssh?

### ISSUE THREAD

**Issue by ginobilee** [teambit/bit#3780]
### Description

I see there is a `bit start` command which is not in docs. So what does it do, will it start a http server to support `import/export` instead of ssh? If so, is there any more infos about this?

will bit support http over ssh ? If so, do you guys have a plan for it?

bit is a great tool, thank you guys!

**Comment by davidfirst** [comment]
@ginobilee , Yes! this will be available soon (no ETA yet) as part of the `Harmony` release. And yes, it supports import/export via HTTP.

**Comment by ginobilee** [comment]
Great!

**Comment by ginobilee** [comment]
@davidfirst seems `bit start` must be executed in workspace/component level , do you guys have plan to support multi workspace support?

**Comment by davidfirst** [comment]
Not sure I follow. `bit start` can be running on a workspace or a scope (.git/bit) directory.
As soon as Harmony is released, the docs will make it clear.

**Comment by ginobilee** [comment]
thanks!
