### ISSUE TITLE
linked shape should match published/exported shape

### ISSUE THREAD

**Issue by jimisaacs** [teambit/bit#3849]
### Describe the bug

A clear and concise description of the issue.

`bit link` should match the published/exported shape of the component package. Though currently it only links the main entry point as far as I can tell. Then, when you export it's very different. This makes it difficult to deal with components that are large collections, such as icons. It's difficult to make them separate components, because then it takes an hour (actually more) to build without any parallelization on the build / compilation process. So the next best thing is to just make it a single component, but then npm link breaks things locally. So finally, I am forced to simply publish the component, and rely on that version rather than the link. This is all very cumbersome.

Also, FYI, I would also like to just use an already built package of the icon library outside of bit, but it's a private package, and I haven't figured out how to allow bit components to depend on private packages outside of bit. I don't think you can, and I thought it was by design. Though please correct me if I'm wrong.

### Steps to Reproduce

1. Create a component with many files (an icon library)
1. run bit link, and try to use the icons without importing the entire library of icons
1. then publish and install the same component and see the difference in behavior

### Expected Behavior

I expect `bit link` to create the same component locally.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 14.8.8
- Node version: 14.15.5
- npm / yarn version: 7.5.4 / 1.22.10
- Platform: macos
- Bit compiler (include version): react-typescript@4.0.0
- Bit tester (include version): jest@22.4.3

**Comment by itaymendel** [comment]
hi @jimisaacs 
sorry for the late respond,

`link` has been fixed in the upcoming release in Bit. we'll start rolling it out during this week. please reach out to me privately on the [public slack community](https://join.slack.com/t/bit-dev-community/shared_invite/zt-9egg85xv-trr_QBkWr1XcVgtrgCvtfQ) for a sneak peek and getting early access to it.
