### ISSUE TITLE
13k stars

### ISSUE THREAD

**Issue by bl-ue** [teambit/bit#3865]
Hello!  I just stared this wonderful project, when I noticed that the stars just became 13,000!  🌟

I wanted to tell you just for fun :wink:

<img width="161" alt="Screen Shot 2021-02-26 at 3 35 10 PM" src="https://user-images.githubusercontent.com/54780737/109352071-44ab7d80-7848-11eb-85de-90dc89a1309f.png">

**Comment by itaymendel** [comment]
thanks @bl-ue  for the star and appreciation !
