### ISSUE TITLE
Can't add ed25519 key

### ISSUE THREAD

**Issue by lucas-rapid** [teambit/bit#3893]
### Describe the bug

When I try adding a ed25519 public key, I get an "Invalid key" error

### Steps to Reproduce

1. Go to https://bit.dev/settings/authentication
2. Paste in a valid ed25519 key (generated with `ssh-keygen -t ed25519 -C "example@key.net`)
3. Click Add

### Expected Behavior

The key should be added to my account which will bypass the username/pass login when I export components.

### Screenshots, exceptions and logs

This is a public key specifically generated for the purpose of creating this screenshot.
![image](https://user-images.githubusercontent.com/75637072/110027945-7bb9dd00-7ce7-11eb-9887-f7aee3276ed7.png)

### Specifications

N/A

### Additional context

N/A

**Comment by itaymendel** [comment]
Hi @lucas-rapid 

there's no need to generate an ssh-key when using Bit. You can simply use the `bbit login` command that automates the process.

At any case, the key does seem like an invalid public key. please follow [these steps](https://docs.bit.dev/docs/setup-authentication#authenticate-with-ssh) to generate a valid key.

**Comment by lucas-rapid** [comment]
P.s. if I don't add a key to my profile, executing `bit export` continues to ask for login details, even after executing `bit login` (which is why I tried adding my public key to my profile)

**Comment by itaymendel** [comment]
Oh, i see. I'll ask my team to fix the placeholder for mitigate that.
as for the rest, please see if you can `ssh hub.bit.dev`, does it hang or process allows you to continue?
