### ISSUE TITLE
Generate a .gitignore file

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#3902]
### Description
No .gitignore file exists

### Describe the solution you'd like
When initialising a new workspace a .gitignore file should be generated with basic things that should be ignored

```
node_modules
.bit
dist
.DS_Store
public
```

### Describe alternatives you've considered
If we can't generate one we should at least document what should be ignored to make it easier for users to create this file and know what needs to be ignored.

**Comment by itaymendel** [comment]
thanks for the suggestion.

I think we should look at it differently, as in some cases the workspace may already have a `.gitignore` file. What I suggest is to have a list of files/dirs to append by default:

```
.bit
<default public dir location>
```

The `default public dir location` may change according to the workspace config, so i'd like this to be a variable.

another thing to note - if any of these entries are already in `.gitignore` i don't want them to be duplicated...

**Comment by GiladShoham** [comment]
we should add a command that outputs a list of paths to add to the gitignore with option to append it automatically to existing gitignore (or create and add it)

**Comment by itaymendel** [comment]
added `.gitignore` to the base workspace template when running `bit new`. closing the issue.
