### ISSUE TITLE
generate types for styles

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#3903]
### Description
VSCode always gives errors for css/scss import files due to missing types

### Describe the solution you'd like
Generate this file or add these types somewhere so that users don't get this error in VSCode and waste time trying to solve it.

types/style.d.ts

```
declare module '*.module.css' {
  const classes: { readonly [key: string]: string };
  export default classes;
}
declare module '*.module.scss' {
  const classes: { readonly [key: string]: string };
  export default classes;
}
declare module '*.module.sass' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.module.less' {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module '*.less' {
  const classes: { readonly [key: string]: string };
  export default classes;
}
```

### Describe alternatives you've considered
If we can't create/generate this then we should at least document it so users know how to manually resolve this.

**Comment by GiladShoham** [comment]
I'm not sure bit should handle it. it's not really bit related. we might want to add it to the bit vscode extension to create such file.

**Comment by wkylin** [comment]
Cannot find module './index.module.less' or its corresponding type declarations.
how to solve？

**Comment by itaymendel** [comment]
this is available in new iteration of react env. please use from here https://bit.cloud/teambit/react/react-env
