### ISSUE TITLE
Genearte component

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#3904]
### Description

Generate new component so we don't lose so much time copy and pasting or creating files again and again

### Describe the solution you'd like

bit new component
This command should generate all files needed to create a basic component.
It should ask you where you want to the component to be created
It should also ask if you want a React component or in future Vue, Angular etc (default React)
It should ask if you want typescript or JSX (default TypeScript)

**Comment by itaymendel** [comment]
closing this issue as this will be handled in #3940
