### ISSUE TITLE
Ask about Environment on project init

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#3905]
### Description

When initialising a project ask which Environment you want to work in.

Project configuration and adding this to only certain scopes should be an advanced feature and not something new users should have to do when they first get started with Bit. 

### Describe the solution you'd like

Instead of this being a manual task of uncommenting so it becomes a react environment this should be asked at project init.

```
 /**
       * uncomment to apply the react environment on all components.
       **/
      "teambit.react/react": {}
```
**Command on init:**
Choose environment: React, node, etc

### Describe alternatives you've considered

The default environment is Node so change it to React as that is what most people would be working with. However once vue and angular is added then this might not work so well.

**Comment by itaymendel** [comment]
should be implemented as part of a **workspace templating** feature via the `bit new` command. proposed syntax is:

```sh
bit new my-new-project -e teambit.react/react
```

**Comment by itaymendel** [comment]
closing this task, as it's a part of `bit new` capability.
