### ISSUE TITLE
bit starts on port 3000 even if 3000 is not available

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#3915]
### Describe the bug
when port 3000 is busy bit doesn't care and just opens in port 3000 meaning you have to restart your react app in another port to have both open

--port flag is also not working 

### Steps to Reproduce
1. open a react app and run start command so app is on port 3000
1. bbit start in another app

### Expected Behavior
bit should go to port 3001 

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: Harmony 0.0.313
* Node version: v15.10.0
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
When running `bit start --port 3004` I'm getting this error:

```sh
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Unknown UI root: "3004". Available ui roots are: [teambit.scope/scope, teambit.workspace/workspace]
** unhandled rejection found, please make sure the promise is resolved/rejected correctly! **
Unknown UI root: "3004". Available ui roots are: [teambit.scope/scope, teambit.workspace/workspace]
(node:22499) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
(Use `node --trace-warnings ...` to show where the warning was created)
```

At any case, to change port configuration for your workspace add this to the `workspace.jsonc` file.

```js
/**
  * Configuration for the UI server (i.e. bbit start)
  **/
    "teambit.ui-foundation/ui": {
    "port": 3000,
    "portRange": [3000, 3100],
    "host": "localhost",
    "publicDir": "public/bit"
  }
```

**Note** - these are the default values, whatever you keep unmodified will stay as default.

**Comment by petrogad** [comment]
Note, I just hit this with a fresh install, however I was told the app was fired up and on 3100, but after a `Cannot GET /` i tried refreshing a few components and found that it was actually running at 3001.
