### ISSUE TITLE
Does Self Hosting Bit Scope have harmony like bit start?

### ISSUE THREAD

**Issue by hqwuzhaoyi** [teambit/bit#3920]
### Description
Hey guys,
I try to build a Self Hosting Scope  with Harmony Beta.
When local bit run `bit export` to my server, everything is well, 
```
prajna@bt-client:~/bit-getting-started$ bit export  --all-versions
exported the following 3 component(s):
first-scope/ui/elements/app-bar
first-scope/hooks/use-jokes
first-scope/ui/elements/button
```
but server  run `bit status`, nothing happend. just like this
```
nothing to tag or export (use "bit add <file...>" to track files or directories as components)
```
So, I want to ask, Can `bit init --bare` with `--harmony`

### Specifications

- Bit version: Harmony
- Node version: v14
- npm / yarn version: latest

```json
"policy": {
      "dependencies": {
        "@teambit/ui.test-loader": "0.0.300",
        "@testing-library/react": "11.2.5"
      },
      "peerDependencies": {
        "react": "16.13.1",
        "react-dom": "16.13.1",
        "classnames": "2.2.6",
        "@types/node": "14.14.33",
        "@testing-library/jest-dom": "4.2.4"
      }
    },
```

**Comment by itaymendel** [comment]
hi,

yes, Bit now supports the full UI on a remote server. There's no cross-server search capabilities, as this is bit.dev proprietary feature.
you can check out this branch on the bit-docker repo
https://github.com/teambit/bit-docker/tree/harmony-docker

**Comment by moshekrup** [comment]
Hi,
I've tried using docker-harmony and seems like it doesn't work 
https://github.com/teambit/bit-docker/issues/4
Also, I can't find any docs on how to run a Bit harmony version with a self-hosting remote, is it supported?
Thanks
