### ISSUE TITLE
bit out of memory when having circular env structure

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#3928]
I have two components:

* teambit.symphony/envs/symphony-react (env)
* teambit.scopes/ui/contexts/symphony-client

`symphony-client` is using in `symphony-react`,
and `symphony-react` is the env for `symphony-client`.

When running any bit command, it freezes until getting an out of memory error.

It makes sense that Bit cannot handle it,
but it should gracefully block it by checking this scenario in advanced.

### Steps to Reproduce
1. Create env (`reactEnvA`), and another component (`compB`)
1. set `ReactEnvA` as default env for the entire workspace (including `compB`)
1. Import `compB` in of `reactEnvA`'s files
1. Run `bbit status`

--> bit stalls for a long time, until showing `out of memory error`.

### Expected Behavior
Bit should show an error, saying that a circular dependency is detected in env `reactEnvA`

### Specifications
* Bit version: 0.0.319 (@teambit/legacy: 1.0.31)
* Node version: v12.19.0
* Platform: MacOS

**Comment by itaymendel** [comment]
@GiladShoham @davidfirst 
I assume @KutnerUri is right on this one, as this setup should not work when env+comp are in the workspace.
This case can potentially happen when new devs onboard themselves to Bit and just had a bad setup for their project.

**Comment by GiladShoham** [comment]
@davidfirst 
We don't want to really support this usecase, only to show a proper error.
