### ISSUE TITLE
`bit create` for component templating

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#3940]
# Component templating

To simplify developer workflow, Bit should automate the process of creating new components.

## Using a template

When using a template to generate a component, Bit should create a new component in the workspace.

### Component location

Component location in the workspace directory tree is defined with the `bit create` command (see below). For example, a component named `ShoppingCart` created in the `acme.shopper` and the namespace `ui` will be generated in the following directory:

```
acme.shopper/ui/shopping-cart
```

### Component name

When using templates Bit will use CamelCasing for passing the component-name to the template, but generated file structure should be in kebab-case, for better cross-operating-system compatibility of the component.

### Automatically `add` component

Bit should automatically register the new component to the `.bitmap` file with a symmetrical name to the component-location in the workspace.

## Register a template
Any aspect (include envs) can register templates. Each template should have a name and a list of files. Each file has a relative-path to the component-dir and template content.

* Component name should be available as a param for the file-content-template.
* TBD: An environment must have a default template (if not set, use first template in array?).

To register a template, use the Generator API: `registerComponentTemplate(templates: ComponentTemplate[])`.

To make the templates of an aspect available on a workspace, they need to be added to the workspace.jsonc. For example:
```json
"teambit.generator/generator": {
    "aspects": [
      "teambit.harmony/aspect"
    ]
  },
```
In the example above, the aspect `teambit.harmony/aspect` is configured to be available for the generator.

## Show all available templates

Introduce a new command `bit templates`, which groups all available templates by aspects.

## Generate a template from Workspace UI

Introduce new CTA for "create component" above component-tree
<img width="293" alt="image" src="https://user-images.githubusercontent.com/4623056/111223707-2da9b100-85e6-11eb-8842-587b37235280.png">

When clicked, open a modal window with the following items:

* **Component name** - free form text box for deciding component name. Must only accept Aa-Zz,0-9. Mandatory.
* **Scope** - Drop down list of available scopes in the workspace and an ability to define a new Scope. Mandatory, default value = `defaultScope`.
* **Namespace** - Dropdown list of all available namespaces in chosen Scope and an ability to define a new namespace. Optional, default value = empty.
* **Template** - Dropdown that aggregates all available templates in the workspace with an ability to filter by typing. Mandatory, default value default-template of default-env.

## Generate a template from CLI

Introduce a `create` command to use templates.

```sh
bit create <template-name> <component-name...> [--scope | -s] [--namespace | -n] [--aspect | -a]
```

#### `<component name>`

Name of the component to create. Will be used as the component's dir name and fed to the component template.

**generated file structure should use kebab-case, while the template itself be in camel case**.

#### `[--scope | -s]`

Sets the component's scope and base directory. If not defined, use the `defaultScope` from `teambit.workspace/workspace` config.

#### `[--namespace | -n]`

Sets the component's namespace and nested dirs inside the scope. If not define, use empty string.

#### `[--aspect | -a]`

Aspect ID that registered this template, required only if there are two templates with the same name from several aspects in the workspace.

**Comment by davidfirst** [comment]
I discussed with @itaymendel , and he suggested to let the user the option to add the namespace and the scope as part of the component-id. For example `teambit.design/base/button`.  We can parse the name entered by the user and if it has a slash, we know it includes the namespace, and in this case, ignore the `--namespace` flag. 

This can work for the namespace. For the scope it's more complex because the namespace can have multiple slashes, so we don't know whether it's a long namespace or it's a namespace+scope.
For scopes hosted on bit.dev we probably can check whether the name has a dot in it. Self hosted scopes don't have dots. So, it's risky to rely on it.

@GiladShoham and @ranm8  your feedback is welcome.

**Comment by GiladShoham** [comment]
I think we should add `--dir` argument, and make the default as you mentioned `scope-name/namespace/name`.
I'm not sure about adding another default dir prop to the ws.jsonc. what we can do, is look on the default root dir in the ws.json and in case it has both scope placeholder and name placeholder, we can just use it as the default dir for create as well. (I think this is pretty good behavior)

**Comment by davidfirst** [comment]
Implemented in https://github.com/teambit/bit/pull/3978.
