### ISSUE TITLE
bit harmony docs seem out of sync with feature set (or possibly regression) 

### ISSUE THREAD

**Issue by drkstr101** [teambit/bit#3941]
I was going through harmony tutorial without issue up to within hours ago. After starting again in a fresh workspace, I seem to have have lost the `bit install` command.

➜  try-bit git:(main) bit --version && bit install

```
0.0.319 (@teambit/legacy: 1.0.31)
warning: 'install' is not a valid command.
see 'bit --help' for additional information
``` 

➜  try-bit git:(main) bit --help | grep install

_(no results)_

Any ideas what I did wrong this time around? Possibly relevant; i did the clean install because the in-browser login flow was returning 404. I am still able to login to the bit npm registry just find however. Dev environment is VSCode on remote Ubuntu 20.04.

Cheers, and thank you for all your hard work! I am super excited for Harmony!

**Comment by itaymendel** [comment]
hi @drkstr101 
thanks for taking the time to experiment with the beta!

I have a few questions for you:

* do you have a part version of Bit installed?
* did you use `@teambit/bvm` to install the public beta?
* which command you use to initialize the workspace?

**Comment by drkstr101** [comment]
Ahh I see. https://harmony-docs.bit.dev/introduction/try-bit Should be updated to show `bit init` prior to `bit install`.

It works as expected after this.

**Comment by itaymendel** [comment]
@giteden please see @drkstr101 comment. I guess there's a slight update we need to introduce to the docs.

**Comment by drkstr101** [comment]
Cheers all! :+1:

**Comment by drkstr101** [comment]
@itaymendel PS: This may be a bit to environment-specific to mention in the tutorial, but I was able to fix my login flow issues by ssh forwarding port `8085` to localhost. It could possibly be worth mentioning in the [troubleshooting guide](https://harmony-docs.bit.dev/troubleshooting/installation-troubleshooting) however.

**Comment by itaymendel** [comment]
v15 doesn't use ssh (moved everything to https). can you please elaborate on the issue you hit and how exactly you resolved it?

**Comment by drkstr101** [comment]
I meant to say that I'm working on a remote host through ssh tunnel (VSCode
Remote). Usually my environment will detect and forward these ports
automatically but for some reason it didn't do this when I fired up the bit
server.

I think it was mostly just an issue of confusion on my part about what I
should be expecting after I ran the `bit login` command at that point in
the tutorial. My browser would get launched through ssh  tunnel, as it does
with legacy bit, but this time the page it took me to was 404. it was clear
to me what I should do next once I realized this was actually linking me to
localhost and not bit.dev (add a forwarding rule for the port shown in 404
url).

You probably already have this and I just overlooked it, but I think a
brief mention in the troubleshooting guide on port `8085` being routable
may keep a few dummies like me from wasting any more of your time. 😉

**Comment by itaymendel** [comment]
haha no worries!
well, login in v15 works just the same. you can run it from your local, and generate a Bit authentication token (see it when you run `bit config`) and run `bit config set user.token <TOKEN>` on your remote, so authenticate it.
