### ISSUE TITLE
Bit CLI unusable after adding component with an invalid name

### ISSUE THREAD

**Issue by j-ochs** [teambit/bit#3943]
### Describe the bug
I attempted to add a folder of files with a namespace id, using the following CLI command: `bit add /folder/path/* --id test/namespace`. Unknown to me, inside the `/folder/path/` directory the was a file with spaces in its name. After executing the CLI command, I get the error 
```
error: "file with spaces in filename" is invalid, component names can only contain alphanumeric, lowercase characters, and the following ["-", "_", "$", "!", "/"]
```
This seems to crash the Bit CLI, as any/all subsequent bit CLI commands will show this error and will not execute.

### Steps to Reproduce

1. Add a folder of files that contain at least one file with spaces in it's filename: `bit add /folder/path/* --id test/namespace`
1. Run any other `bit CLI` command - it will not work.

### Expected Behavior

The Bit CLI should still be usable and allow the developer to fix the shown error.

### Specifications

- Bit version: 14.8.8
- Node version: 14.16.0
- npm / yarn version: 6.14.11
- Platform: MacOS
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.0.0
- Bit tester (include version): N/A

### Additional context
Running `bit clear-cache` does not fix the problem. Uninstalling/reinstalling `bit-bin` as a global NPM module does not fix the problem. 
This bug has rendered `bit` completely unusable for me - please advise.

**Comment by davidfirst** [comment]
This has been fixed recently in https://github.com/teambit/bit/pull/3798 and available on Harmony version.
The only option I can see for the previous version is to edit the `.bitmap` manually and remove the problematic entry.
Closing because it has been fixed. Please re-open if you're unable to resolve the issue after editing the `.bitmap` file.

**Comment by j-ochs** [comment]
@davidfirst thank you, removing the bad entry from the `.bitmap` fixed it.
