### ISSUE TITLE
How can I upgrade my bit version?

### ISSUE THREAD

**Issue by gvinson** [teambit/bit#3950]
### Description

I am trying to run `bit export` but am getting an error:
```
unexpected network error has occurred.
server responded with: "Please update your Bit client.
For additional information: https://docs.bit.dev/docs/installation#latest-version"

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

`bit doctor` returns
```
validate bit version
  symptoms
  bit is not up to date.
    your version: 1.0.32
// @ts-ignore AUTO-ADDED-AFTER-MIGRATION-PLEASE-FIX!
    latest version: 1.0.33
  cure
  please upgrade your bit version
```

How can I upgrade this version? I've ran through the help doc in the error message with no success.

### Specifications
- bit version   : 1.0.32
  node version  : v14.15.1
  npm version   : 6.14.8
  platform      : darwin
- Bit compiler (include version): bit.envs/compilers/vue@0.1.13
- Bit tester (include version):

**Comment by itaymendel** [comment]
Hi,

This realy depends on how you installed Bit in the first place. If you used `npm` please run `npm i -g bit-bin`, if you use `yarn` use the yarn syntax for updating global deps.

**Comment by alvin883** [comment]
Hi, I am getting the same error when trying to run `bit import`, I think mine is already up-to-date, I use `bvm` to install Bit in my machine.
And when I run `bit doctor` it didn't show anything about outdated Bit version, here's the output when I run `bit doctor`:
```
  bit version   : 1.0.42
  node version  : v15.12.0
  npm version   : 7.6.3
  yarn version  : 1.21.1
  platform      : win32
  ```
  
and `bit -v` returns:
  ```
  0.0.330 (@teambit/legacy: 1.0.42)
  ```
Perhaps it's a bug or is there some step that I missed?
Thanks in advance!

**Comment by enes-get-local** [comment]
> Hi,
> 
> This realy depends on how you installed Bit in the first place. If you used `npm` please run `npm i -g bit-bin`, if you use `yarn` use the yarn syntax for updating global deps.

I m getting the same error when try to tag components :

```
unexpected network error has occurred during fetching scopes: bit.envs
server responded with the following error messages:
bit.envs - Please update your Bit client
```

I try to all ways and `npm i -g bit-bin` command. It looks like installed bit-bin@14.8.8 but get same error

![image](https://user-images.githubusercontent.com/70728456/112735992-73f4fd80-8f60-11eb-98aa-d03cb6b4e1cc.png)

**Comment by davidfirst** [comment]
Are you guys still having the issue? It's possible that if the scope created on bit.dev wasn't of "harmony" type and your version is legacy (v14.x) or the vice versa this could happen. 
If you're using Harmony, make sure to update to the latest version (>= 0.0.340 as of now) and selecting "Start with Harmony" when creating the scope on bit.dev.

**Comment by tataihono** [comment]
@davidfirst I am getting a similar issue. I wanted to create a test case and ran the commands as follows:
![Screen Shot 2021-04-01 at 10 07 47 AM](https://user-images.githubusercontent.com/802117/113211560-1e0eb580-92d2-11eb-86b7-56eda6b622ce.png)

Steps to reproduce:
```
bvm upgrade
mkdir bit test
cd bit-test
git init
bit init --harmony
bit import bit.envs/testers/jest -t
```

**Comment by leslie555** [comment]
just need to execute ```bvm upgrade```, then the version of bit displayed in `bit doctor` will auto update
