### ISSUE TITLE
[Harmony]: HMR is broken

### ISSUE THREAD

**Issue by fcisio** [teambit/bit#3951]
### Describe the bug

HMR is broken when changes are made to components.

> Works when editing compositions

### Steps to Reproduce

1. `git clone https://github.com/teambit/getting-started-result.git try-bit`
2. `bit install`
3. `bit start`
4. Go to a component "compositions" view (on Workspace UI)
5. Apply a change to `button.composition.tsx` (HMR should work)
6. Apply a change to `button.tsx` (HMR should break)

### Expected Behavior

HMR should work in both use cases.

### Screenshots, exceptions, and logs

<img width="730" alt="ScreenShot 2021-03-16 at 6 16 45 PM" src="https://user-images.githubusercontent.com/46095852/111387489-2c2ec600-8684-11eb-9853-aedc69c36816.png">

### Specifications

- Bit version: 0.0.321
- Node version: 14.15.4
- npm / yarn version: 6.14.10 / 1.22.10
- Platform: MacOs Big Sur

ALSO: 
I noticed that the compiling is pretty long. About 2-3 seconds on my end. Not optimal for developing components from inside the bit workspace. 
Any idea if this will be addressed in the future of this beta?

**Comment by itaymendel** [comment]
Hi! thanks for reporting it.
I set up my environment to fit yours, and I can't reproduce the issue. Perhaps the simple text changes I apply on the code are not similar to what you are doing?
While this HMR issue is happening, do you have any errors prompted in browser's js-console or Bit's terminal outputs?


Regarding compilation time - you refer to the time it takes from saving a file to see changed applied in UI? Bit enables **Fast Refresh** by default, so this should work much faster than the 2-3 seconds you experience. This is rather odd.
The team is actively working on dev-server configuration right now. I don't have time estimations for the current tasks, but a smooth dev-experience is a critical feature for the beta. 
I can share that these are the two major goals right now:

* Improve performance
* Upgrade to Webpack 5

Once these are implemented we'll be looking into integrate Module Federation by default.

**Comment by fcisio** [comment]
Your change should trigger the issue. On my end, I just change the button `children` to a string.

The only relevant error I get in the console is this:
![ScreenShot 2021-03-17 at 11 17 21 AM](https://user-images.githubusercontent.com/46095852/111493590-149f1e00-8714-11eb-8fa8-782ff9127c46.png)
Outputs: `{"h":"2dcda9f21a12bb505878","c":{"main":true}}`

Upon inspection, if I edit the compositions, HMR works, but is very long and also logs the same error as above `XML Parsing Error: not well-formed`

---

Could be an issue with my environment not using the global dependencies. I opened this issue regarding possible global mishaps.
[Missing dependencies and configuration issues](https://github.com/teambit/getting-started/issues/1)

**Comment by itaymendel** [comment]
@giteden i think you were able to reproduce this issue, can you please add your STR?

**Comment by giteden** [comment]
@fcisio thanks again for your feedback. It seems HMR does not work with 'require' statements.

Require' statements were used to eliminate TS type warnings when importing SCSS modules (e.g, 'Cannot find module './button.module.scss' or its corresponding type declarations.)

All 'require' statements have now been replaced with 'import' statements.
