### ISSUE TITLE
Example project - movie app does not compile and it is outdated

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#3955]
### Describe the bug

![Screenshot 2021-03-17 at 17 33 39](https://user-images.githubusercontent.com/17653648/111503326-f1419680-8746-11eb-86f8-052c3d4babfe.png)

https://github.com/teambit/movie-app

There are two main problems with this project.
1. It does not compile when using node > 10. This is because the version of `node-sass` in `package.json` is outdated. You can check the compatibility here: https://github.com/sass/node-sass#node-version-support-policy
2. This project is completely outdated. Someone should take care of it, i.e.
- replace node-sass with sass
- update react, react-scripts and other stuff to the latest version
- convert class components to function components

### Expected Behavior

Example project should compile and should be up to date.

### Specifications

- Bit version: 14.8.8
- Node version: v14.15.5
- npm / yarn version: npm 7.5.4
- Platform: MacOS 11.2.2

**Comment by itaymendel** [comment]
Hi, we're moving away from these past versions to a new an much more improved version of Bit (and updated deps).
please see [this example](https://harmony-docs.bit.dev/introduction/try-bit).

all old projects will be marked as deprecated soon.
