### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by Uyarn** [teambit/bit#3958]
Does bit team have any plan to translate the docs into other languages?

**Comment by itaymendel** [comment]
Hi,

First of all - definitely! Having Bit accessible for more developers around the world is one of our main goals!

We're in a process of rewriting docs and sorting them to fit the new version of Bit which is just released as an open beta.
So as it stands I don't want to start looking into translations, as there are just too many changes on a daily basis.
When docs stabilizes I'd be happy to start collaborating with more devs on translations.

Closing the issue for now, as I can't even estimate when we can start such project.
