### ISSUE TITLE
Module not found: Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#3961]
### Describe the bug

I have created a simple app using Create React App and then added a simple React component. After publishing it to Bit Cloud, I receive an error in the playground.

```
./node_modules/@bit/some-org-org.bit-test.base-button/dist/BaseButton.js
Module not found: Can't resolve 'react/jsx-runtime' in '/capsule/node_modules/@bit/some-org.bit-test.base-button/dist'
```

### Steps to Reproduce

1. Download this project: [bit-test.zip](https://github.com/teambit/bit/files/6164603/bit-test.zip)
2. Run these commands:
```
bit add components/*
bit import bit.envs/compilers/react-typescript --compiler
bit tag --all 1.0.0
bit export org.collection
```

### Expected Behavior

Project in the playground should compile.

### Screenshots, exceptions and logs

You can see the error here:
https://bit.dev/miwasnie-org/bit-test/base-button

### Specifications

- Bit version: 14.8.8
- Node version: v14.15.5
- npm / yarn version: yarn 1.22.10
- Platform: MacOS 11.2.2
- Bit compiler (include version): bit.envs/compilers/react-typescript@4.0.0
- Bit tester (include version): n/a

### Additional context

This is critical bug which prevents developing React components.

**Comment by GiladShoham** [comment]
please read duplicate issue comments https://github.com/teambit/bit/issues/3771
The public beta already published and it fixes this issue.
Feel free to play with it.
