### ISSUE TITLE
no preview for newly added components when dev server is already running

### ISSUE THREAD

**Issue by giteden** [teambit/bit#3971]
### Describe the bug
no preview ('overview'/'compositions') for newly-added components in a workspace UI that started running with an empty workspace

### Steps to Reproduce
1. bit init --harmony
1. bit start
1. bit add <first-component-to-be-tracked>

### Expected Behavior
Should have shown the component's docs/compositions once it's been added

### Screenshots, exceptions and logs
{"message":"preview failed to get a component object, url /api/demo-org.demo-scope/ui/elements/app-bar/~aspect/preview/","error":{"status":500}}

### Specifications
* Bit version: 0.0.328
* Node version: v12.16.3
* npm version: 6.14.8
* Platform: Mac OS 10.15.6
* Bit Env (include version): teambit/react@0.0.328

**Comment by GiladShoham** [comment]
This is not an easy fix. I checked it deeply. I'll fix it in the future.

**Comment by jimmi-joensson** [comment]
Same issue I believe for newly created components.

1. Starting dev server with `bbit start`
2. Creating new component with `bbit create <template> my-component`, the workspace UI is updated accordantly.
3. Adding **my-component.compositions.tsx** breakes the server
4. Restarting the server solves the error

### Error
```Module parse failed: Unexpected token (6:7)
File was processed with these loaders:
 * ../../.bvm/versions/0.0.416/bit-0.0.416/node_modules/@pmmmwh/react-refresh-webpac
k-plugin/loader/index.js
 * ../../.bvm/versions/0.0.416/bit-0.0.416/node_modules/@teambit/react/node_modules/
babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import * as React from 'react';
| import { StyleSheet, View, ViewProps, ViewStyle } from 'react-native';
> export interface MyComponentProps extends ViewProps {}
| 
| const MyComponent = ({ ...props
ModuleParseError: Module parse failed: Unexpected token (6:7)
File was processed with these loaders:
 * ../../.bvm/versions/0.0.416/bit-0.0.416/node_modules/@pmmmwh/react-refresh-webpac
k-plugin/loader/index.js
 * ../../.bvm/versions/0.0.416/bit-0.0.416/node_modules/@teambit/react/node_modules/
babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| import * as React from 'react';
| import { StyleSheet, View, ViewProps, ViewStyle } from 'react-native';
> export interface MyComponentProps extends ViewProps {}
| 
| const MyComponent = ({ ...props
    at handleParseError (/Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_
modules/webpack/lib/NormalModule.js:891:19)
    at /Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_modules/webpack/li
b/NormalModule.js:992:5
    at processResult (/Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_mod
ules/webpack/lib/NormalModule.js:718:11)
    at /Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_modules/webpack/li
b/NormalModule.js:778:5
    at /Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_modules/loader-run
ner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders (/Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/n
ode_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at iterateNormalLoaders (/Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/n
ode_modules/loader-runner/lib/LoaderRunner.js:239:10)
    at /Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_modules/loader-run
ner/lib/LoaderRunner.js:254:3
    at context.callback (/Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_
modules/loader-runner/lib/LoaderRunner.js:124:13)
    at /Users/jimmijonsson/.bvm/versions/0.0.416/bit-0.0.416/node_modules/@pmmmwh/re
act-refresh-webpack-plugin/loader/index.js:96:7
```

### Specifications
Bit version: 0.0.416
Node version: v14.16.1
npm version: 6.14.12
Platform: Mac OS 11.2.3
Bit Env (include version): @teambit/react-native@0.0.415

**Comment by KutnerUri** [comment]
@jimmi-joensson - I'm seeing it, and I'm debugging it.
At least it's only happening for new files.

**Comment by KutnerUri** [comment]
Managed to reproduce it. It happens when adding a component to an env that had no components before,
so for example it should happen when adding the first component in a new workspace.

I will try to fix it...

![Screen Shot 2021-07-12 at 18 50 39](https://user-images.githubusercontent.com/5400361/125318654-b6d9b600-e342-11eb-978b-60db1918f78f.png)

**Comment by itaymendel** [comment]
resolved
