### ISSUE TITLE
Yarn doesn't use .yarnrc registry

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#3975]
### Describe the bug
Yarn doesn't use .yarnrc registry, but it uses .npmrc at least.

### Steps to Reproduce
1. Define private registry in .yarnrc
1. Use `"packageManager": "teambit.dependencies/yarn"`
1. Run `bbit install`
1. See 404 errors for private packages from registry defined in .yarnrc

### Expected Behavior
1. No http errors, e.g. 404.
1. All packages available in private registry are installed.

### Screenshots, exceptions and logs
```
YN0001: │ HTTPError: @company/graphql-api@npm:1.5.0: Response code 404 (Not Found)
    at Request.<anonymous> (/Users/user/.bvm/versions/0.0.331/bit-0.0.331/node_modules/got/dist/source/as-promise/index.js:117:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

### Specifications
* Bit version: 0.0.331
* Node version: v12.16.2
* npm / yarn version: 6.14.4 / 1.22.5
* Platform: MacOS Darwin Kernel Version 19.6.0

**Comment by itaymendel** [comment]
if anyone hits this issue and its not resolved yet - using npmrc is a temp workaround for this issue

**Comment by GiladShoham** [comment]
it's not implemented. I will implement it in the future.

**Comment by itaymendel** [comment]
resolved per latest release of bit. please run `bvm install`.
