### ISSUE TITLE
Yarn does not find cache packages

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#3979]
### Describe the bug
Any packages installation leads to request remote registry, it does not use yarn cache.

### Steps to Reproduce
1. Add any components
1. Use "packageManager": "teambit.dependencies/yarn"
1. Run bbit tag
1. See `can't be found in the cache` errors

### Expected Behavior
Yarn manager uses cache.

### Screenshots, exceptions and logs
```
➤ YN0013: │ xtend@npm:4.0.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ y18n@npm:4.0.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yaml@npm:1.10.2 can't be found in the cache and will be fetched from the remote registry
```

### Specifications
* Bit version: 0.0.331
* Node version: v12.16.2
* npm / yarn version: 6.14.4 / 1.22.5
* Platform: MacOS Darwin Kernel Version 19.6.0

**Comment by itaymendel** [comment]
this keep happening when you repeat the action?
behind the scenes bit uses yarn2, and if you are using yarn1 - there may be a different location for cache, which means that `bit build` uses another cache that needs to be warmed up.

@GiladShoham your thoughts?

**Comment by ivansky** [comment]
@itaymendel Yes, it doesn't make any difference how many times I do install or it use yarn installation during other commands.

**Comment by GiladShoham** [comment]
I'll look into it

**Comment by itaymendel** [comment]
resolved for latest stable version of bit. please run `bvm install`.
