### ISSUE TITLE
Process bit commands both when '@' is and isn't included in the component-id

### ISSUE THREAD

**Issue by benjgil** [teambit/bit#3982]
### Description

When running bit CLI commands, such as `bit remove <component_id>, bit does not manage to process the command if the '@' at the beginning of the component's organisation was included. Various errors are thrown, each one indicating that bit hasn't found the required component, because the @ was not expected

### Describe the solution you'd like

Bit should be able to process the '@' prefix as an option prefix to a component-id field, and then process the command in the same way whether @ was prefixed or not

### Describe alternatives you've considered

Advise the user that when a component-id is required for a bit CLI command it should not include the @ prefix

**Comment by itaymendel** [comment]
@davidfirst @GiladShoham 
in commands that expect `component id` as an input, can we add input validation on a valid component-id? we have a component that does that, no?

**Comment by benjgil** [comment]
I would guess it's a bit more than just input validation - the component-id will currently be expected to be passed to functions without the '@' so will need to process the input a tad

**Comment by davidfirst** [comment]
@itaymendel , yes, the standard error in this case is:
```
error: "@teambit/compiler" is invalid, component names can only contain alphanumeric, lowercase characters, and the following ["-", "_", "$", "!", "/"]
```
Specifically in `bit remove` (and maybe with some more command), it didn't show this error and instead search for it in the bit-map before. 
I fixed it in the commit above and also checked whether the id starts with `@` to throw a more specific error about using the component-id instead of package-name.
