### ISSUE TITLE
I cannot even run the bbit tag, because of this errors

### ISSUE THREAD

**Issue by iamrommel** [teambit/bit#3992]
### Description

Something is missing on the babel/react-preset? Check the error, i don't know where to go and fix. I cannot find any documentation or know how to contact support.

### Specifications

- Bit version: harmony
- Node version: 14
- npm / yarn version: 7
- Platform: Apple M1 Bigsur
- Bit compiler (include version): 
- Bit tester (include version):

### Context and additional information

```
Ran all test suites.
✔ env "teambit.react/react", task "teambit.defender/tester:TestComponents" has completed successfully in 1s
✔ env "teambit.react/react", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 18μs
✔ env "teambit.react/react", task "teambit.pkg/pkg:PublishDryRun" has completed successfully in 702ms
✖ env: teambit.react/react, task "teambit.preview/preview:GeneratePreview" has failed
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 6 tasks (completed in 27s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react"
component: ztech.panelpunches/hooks/use-jokes@0.1.0
/Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.composition.js
Module build failed (from /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/react/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.composition.js: Support for the experimental syntax 'jsx' isn't currently enabled (5:12):

  3 |
  4 | export const DefaultLayout = () => {
> 5 |     return <AppBar/>
    |            ^
  6 | }
  7 |
  8 | export const WithLogo = () => {

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Parser.raiseWithData (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Parser.expectOnePlugin (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/util.js:179:18)
    at Parser.parseExprAtom (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:1202:18)
    at Parser.parseExprSubscripts (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:611:23)
    at Parser.parseUpdate (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:591:21)
    at Parser.parseMaybeUnary (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:558:23)
    at Parser.parseExprOps (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:366:23)
    at Parser.parseMaybeConditional (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:331:23)
    at Parser.parseMaybeAssign (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:286:21)
    at Parser.parseExpressionBase (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:206:23)
    at callback (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:199:39)
    at Parser.allowInAnd (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:2606:12)
    at Parser.parseExpression (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:199:17)
    at Parser.parseReturnStatement (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/statement.js:587:28)
    at Parser.parseStatementContent (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/statement.js:209:21)
 @ multi /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.docs.mdx /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/teambit.react__react-preview/__overview-1616636550337.js /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/react/dist/docs/index.js /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.composition.js /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/teambit.react__react-preview/__compositions-1616636550337.js /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/react/dist/mount.js /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/ui/dist/preview.root1b960bbdf46fcf6e26af6b24bd238976a66ec97e.js main[3]
/Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.js
Module build failed (from /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/react/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.js: Support for the experimental syntax 'jsx' isn't currently enabled (7:9):

   5 | export const AppBar = ({children, bgColor="red"}) => {
   6 |     return (
>  7 |         <React.Fragment>
     |         ^
   8 |             <div className={styles.appBar} title="message-content" style={{backgroundColor:bgColor}}>
   9 |                 <ul>
  10 |                     <li>Home</li>

Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
    at Parser._raise (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/error.js:97:45)
    at Parser.raiseWithData (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/error.js:92:17)
    at Parser.expectOnePlugin (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/util.js:179:18)
    at Parser.parseExprAtom (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:1202:18)
    at Parser.parseExprSubscripts (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:611:23)
    at Parser.parseUpdate (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:591:21)
    at Parser.parseMaybeUnary (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:558:23)
    at Parser.parseExprOps (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:366:23)
    at Parser.parseMaybeConditional (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:331:23)
    at Parser.parseMaybeAssign (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:286:21)
    at callback (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:241:12)
    at Parser.allowInAnd (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:2606:12)
    at Parser.parseMaybeAssignAllowIn (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:240:17)
    at Parser.parseParenAndDistinguishExpression (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:1437:16)
    at Parser.parseExprAtom (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:1081:21)
    at Parser.parseExprSubscripts (/Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@babel/parser/src/parser/expression.js:611:23)
 @ /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.docs.mdx 14:0-34 26:14-20
 @ multi /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.docs.mdx /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/teambit.react__react-preview/__overview-1616636550337.js /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/react/dist/docs/index.js /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/ztech.panelpunches_web-ui_elements_app-bar@0.1.0/dist/AppBar.composition.js /Users/iamrommel/Library/Caches/Bit/capsules/3182e4aef75c952d0a0a1cfbbf1206cdd93e41a9/teambit.react__react-preview/__compositions-1616636550337.js /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/react/dist/mount.js /Users/iamrommel/.bvm/versions/0.0.331/bit-0.0.331/node_modules/@teambit/ui/dist/preview.root1b960bbdf46fcf6e26af6b24bd238976a66ec97e.js
```

**Comment by itaymendel** [comment]
hi! 
can you share a code snippet that reproduces the error?

**Comment by iamrommel** [comment]
I just used also the same demo tutorial project from the harmony docs and it does even able me to run bbit test and bbit tag.. This is very frustrating for me, even a simple demo does not work for me getting the impression that this bit is too hard to start with still immature project. :(

**Comment by Marlarn** [comment]
Running into the same problem when importing my own React component (not TypeScript) to another component in my scope. Using the same demo example as basis, but succeeded finishing the tutorial itself without errors. Only occuring when adding new React components and importing these:

After $ bbit tag ui/elements/aera-button

" (...) aera-button.composition.jsx: Support for the experimental syntax 'jsx' isn't currently enabled (5:12): (...)"

Example in components/ui/elements :
```

//index.js
export { AeraButton } from './aera-button'

```


```
// aera-button.js
import React from 'react'

export const AeraButton = ({children}) => {
    return (
        <button>{children}</button>
    )
}

```


```
// aera-button.composition.jsx
import React from 'react'
import { AeraButton } from "@marilofthusarnesen/demo-scope.ui.elements.aera-button";

export const PrimaryButton = () => {
    return <AeraButton>Click me!</AeraButton>
}

```

Tagging button without composition file works well. After adding composition, Babel JSX error occurs here as well.

  bit version   : 1.0.44
  node version  : v14.16.0
  npm version   : 6.14.11
  yarn version  : 1.22.10
  platform      : darwin

Environment for all components under "teambit.workspace/variants" in workspace.jsonc:
"teambit.react/react": {}

Something missing from babel in react environment used? 
_"Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing."_

Or something wrong with the installation?:

// in .zshrc
export PATH=$HOME/bin:$PATH

$ bbit --version
0.0.335
$ bit --version
14.8.8
$ bvm --version
0.0.19

$ which bbit
/Users/marilofthusarnesen/bin/bbit
$ which bit
/usr/local/bin/bit
$ which bvm 
/usr/local/bin/bvm

(Do not know why bit version says 1.0.44)

**Comment by itaymendel** [comment]
thanks for the detailed steps, we'll try and reproduce the issue and resolve it. i will ping you here if there's i need to reproduce.

**Comment by jonnyasmar** [comment]
Also running into this issue.

`bit compile` works just fine. Thought it might be filetype related, but experiencing it with both `js` and `jsx` files and basic components (vanilla button element wrapped in JSX).

**Comment by davidfirst** [comment]
@jonnyasmar , `bit compile` emits files into the `node_modules/package-name/dist` dir. It doesn't do any type checking, only transpiles the files, probably that's why you don't get there error then.

**Comment by jonnyasmar** [comment]
> thanks for the detailed steps, we'll try and reproduce the issue and resolve it. i will ping you here if there's i need to reproduce.

Any progress on this by chance? Are you guys at least able to repro on your end?

**Comment by Marlarn** [comment]
> @jonnyasmar , `bit compile` emits files into the `node_modules/package-name/dist` dir. It doesn't do any type checking, only transpiles the files, probably that's why you don't get there error then.
> 
> @Marlarn, any chance that your component doesn't use the `react` env? Try running `bit env <your-component-name>` and post the results.


@davidfirst looks like it does.
Running $ bbit env ui/elements/aera-button gives me this:

Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <Text>. See https://fb.me/react-warning-keys for more information.
    in Text
**_Environment: teambit.react/react_**
teambit.pipelines/builder

total 6 tasks are configured to be executed in the following order
1. teambit.harmony/aspect:CoreExporter
2. teambit.compilation/compiler:MultiCompiler
3. teambit.defender/tester:TestComponents
4. teambit.pkg/pkg:PreparePackages
5. teambit.pkg/pkg:PublishDryRun
6. teambit.preview/preview:GeneratePreview

teambit.compilation/compiler

**_configured compiler: teambit.typescript/typescript (TypeScript @ 4.1.5)_**
compiler config:
{
  "compilerOptions": {
    "lib": [
      "es2019",
      "DOM",
      "ES6",
      "DOM.Iterable"
    ],
    "target": "es2015",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  },
  "exclude": [
    "dist"
  ]
}
teambit.defender/tester

configured tester: teambit.defender/jest (Jest @ 26.6.3)
tester config:
"use strict";

module.exports = {
  // "roots": [
  //   "<rootDir>/src"
  // ],
  // "collectCoverageFrom": [
  //   "src/**/*.{js,jsx,ts,tsx}",
  //   "!src/**/*.d.ts"
  // ],
  setupFiles: [require.resolve('react-app-polyfill/jsdom')],
  setupFilesAfterEnv: [require.resolve('./setupTests.js')],
  // "testMatch": [
  // "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
  // "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
  // ],
  testEnvironment: require.resolve('jest-environment-jsdom-fourteen'),
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': require.resolve('./transformer'),
    '^.+\\.css$': require.resolve('./css-transform.js'),
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': require.resolve('./file-transform.js')
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
  modulePaths: [],
  moduleNameMapper: {
    '^react-native$': require.resolve('react-native-web'),
    '^.+\\.module\\.(css|sass|scss)$': require.resolve('identity-obj-proxy')
  },
  moduleFileExtensions: ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'] // watchPlugins: [require.resolve('jest-watch-typeahead/filename'), 
require.resolve('jest-watch-typeahead/testname')],

};

//# sourceMappingURL=jest/jest.config.js.map
Environment: teambit.react/react
teambit.pipelines/builder

total 6 tasks are configured to be executed in the following order
1. teambit.harmony/aspect:CoreExporter
2. teambit.compilation/compiler:MultiCompiler
3. teambit.defender/tester:TestComponents
4. teambit.pkg/pkg:PreparePackages
5. teambit.pkg/pkg:PublishDryRun
6. teambit.preview/preview:GeneratePreview

teambit.compilation/compiler

configured compiler: teambit.typescript/typescript (TypeScript @ 4.1.5)
compiler config:
{
  "compilerOptions": {
    "lib": [
      "es2019",
      "DOM",
      "ES6",
      "DOM.Iterable"
    ],
    "target": "es2015",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "esModuleInterop": true
  },
  "exclude": [
    "dist"
  ]
}
teambit.defender/tester

configured tester: teambit.defender/jest (Jest @ 26.6.3)
tester config:
"use strict";

module.exports = {
  // "roots": [
  //   "<rootDir>/src"
  // ],
  // "collectCoverageFrom": [
  //   "src/**/*.{js,jsx,ts,tsx}",
  //   "!src/**/*.d.ts"
  // ],
  setupFiles: [require.resolve('react-app-polyfill/jsdom')],
  setupFilesAfterEnv: [require.resolve('./setupTests.js')],
  // "testMatch": [
  // "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}",
  // "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"
  // ],
  testEnvironment: require.resolve('jest-environment-jsdom-fourteen'),
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': require.resolve('./transformer'),
    '^.+\\.css$': require.resolve('./css-transform.js'),
    '^(?!.*\\.(js|jsx|ts|tsx|css|json)$)': require.resolve('./file-transform.js')
  },
  transformIgnorePatterns: ['[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$', '^.+\\.module\\.(css|sass|scss)$'],
  modulePaths: [],
  moduleNameMapper: {
    '^react-native$': require.resolve('react-native-web'),
    '^.+\\.module\\.(css|sass|scss)$': require.resolve('identity-obj-proxy')
  },
  moduleFileExtensions: ['web.js', 'js', 'web.ts', 'ts', 'web.tsx', 'tsx', 'json', 'web.jsx', 'jsx', 'node'] // watchPlugins: [require.resolve('jest-watch-typeahead/filename'), 
require.resolve('jest-watch-typeahead/testname')],

};

//# sourceMappingURL=jest/jest.config.js.map

If i'm not wrong, build is a step in the tagging process, so it also fails with
$ bbit build ui/elements/aera-button (same error)

**Comment by davidfirst** [comment]
@Marlarn , thanks, I'm able to reproduce the issue. I'll keep you posted.

**Comment by davidfirst** [comment]
@Marlarn , a new version has been released with a fix to this issue.

**Comment by enesozturk** [comment]
I am still getting this issue with `v0.0.762`.  I'm ok with some bit commands like `bit compile` but when I try to run `bit tag [comp-name]`, I got the following error.

<details>
<summary>Stack Trace</summary>

```sh
The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "showtime.universal/extensions/react-native-web@0.0.6"
component: showtime.universal/dropdown-menu@0.0.2
message: Module build failed (from ../../../../../.bvm/versions/0.0.761/bit-0.0.761/node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/enesozturk/Library/Caches/Bit/capsules/26db09c3a935643634ab8eac5e534fe88314092c/showtime.universal_dropdown-menu@0.0.2/dist/index.js: Support for the experimental syntax 'jsx' isn't currently enabled (9:62):

   7 | const DropdownMenuGroup = DropdownMenu.Group;
   8 | const DropdownMenuTrigger = DropdownMenu.Trigger;
>  9 | const DropdownMenuContent = DropdownMenu.menuify((props) => (<DropdownMenu.Content {...props} style={tailwind.style(props.tw)}/>), "Content");
     |                                                              ^
  10 | const DropdownItemFocusRing = ({ isFocused, }) => {
  11 |     // TODO moti should provide this
  12 |     const state = useDerivedValue(() => {

Add @babel/preset-react (https://github.com/babel/babel/tree/main/packages/babel-preset-react) to the 'presets' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-jsx) to the 'plugins' section to enable parsing.
```

</details>

You can also check our [workspace configs](https://github.com/showtime-xyz/showtime-frontend/blob/staging/workspace.jsonc) or components in [/packages/design-system](https://github.com/showtime-xyz/showtime-frontend/tree/staging/packages/design-system). Any comment or help is much appreciated.

@davidfirst

**Comment by davidfirst** [comment]
@enesozturk , please make sure that your env has the correct tsconfig with the `jsx` for build. You can run `bit env get <component-id>` to see the tsconfig. 
If that's not the issue, it might be related to Webpack. @GiladShoham  might be able to help with it.
