### ISSUE TITLE
Links to @teambit packages gets broken after bvm upgrade

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#3998]
### Describe the bug

I upgraded bit from 0.0.331 to 0.0.333, removed previous 0.0.331 version. 
And links got broken even after using link command.
Doctor doesn't show any problems.

### Steps to Reproduce

1. `bvm upgrade`
1. `bvm remove 0.0.331`
1. `bbit link` leads to `Linked N components and 0 core aspects to node_modules for workspace`

### Expected Behavior

`bit-link` or/and `bit-doctor` checks the links are still valid
or let `bit-link` re-create it immediately

### Screenshots, exceptions and logs

```
$ bit link
  Linking components and core aspects to node_modules for workspaces: 'company'
✔ linking components
Linked 4 components and 0 core aspects to node_modules for workspace: company
No core aspects were linked
```

```
$ bit tag custom-react 0.0.5
error: issues found with the following component dependencies

custom-react@0.0.4

       missing packages dependencies (make sure you've added it to the package dependencies, and use `bit install` to make sure all package dependencies are installed):
          custom-react.aspect.ts -> @teambit/harmony
          custom-react.extension.ts -> @teambit/envs, @teambit/react
          custom-react.preview.ts -> @teambit/preview, @teambit/react
```
### Specifications

- Bit version: 0.0.333
- Node version: v12.16.2
- npm / yarn version: 6.14.4 / 1.22.5
- Platform: darwin

**Comment by GiladShoham** [comment]
That's a bug. I'll fix it soon

**Comment by davidfirst** [comment]
@ivansky , a new version has been released with a fix to this issue.
