### ISSUE TITLE
Specifying semantic version only applies to modified components, not their dependencies

### ISSUE THREAD

**Issue by rlveiga** [teambit/bit#4001]
### Description

When running `bit tag --all --minor`, for example, bit will only tag accordingly for modified components, not their dependencies. 

### Describe the solution you'd like

I would like there to be an option where both the modified component and it's dependencies get upgraded to the specified semantic version.

Current behavior:
```
modified components
    component-a (current version 0.0.1, gets upgraded to 0.1.0)

components pending to be tagged automatically (when their dependencies are tagged)
    component-b (current version 0.0.1, gets upgraded to 0.0.2)
```

Desired behavior:
```
modified components
    component-a (current version 0.0.1, gets upgraded to 0.1.0)

components pending to be tagged automatically (when their dependencies are tagged)
    component-b (current version 0.0.1, gets upgraded to 0.1.0)
```
### Describe alternatives you've considered

I thought I had what I needed after looking at the documentation, but there doesn't seem to be a way.

**Comment by davidfirst** [comment]
@itaymendel , please let me know if you have an input here.
We apply the `--minor`, `--major` flags of `bit tag` on the modified only not on the auto-tags components, which are always bumped by a patch. Should we change this behavior or should we add another flag and preserver the current one?

**Comment by itaymendel** [comment]
if you want to tag everything with the same version, you can use `--scope`, no?
in which case you want to promote dependents by minor when the change is only in their dependencies? this is breaking semver rules, no?

**Comment by davidfirst** [comment]
> if you want to tag everything with the same version, you can use --scope, no?

Correct, but this flag tags **all** components, including non-modified and non-auto-tags.

> in which case you want to promote dependents by minor when the change is only in their dependencies? this is breaking semver rules, no?

Not sure. I guess that in most cases, because you didn't modify the code of the dependent but only change its dependencies, the change wasn't API breaking. So, not a major. Most likely it's a bug fix - patch. But I guess it could be in theory a new feature introduced by the dependency that is supported now by a dependent.

Anyway, I see your point. It's probably not a priority.

**Comment by davidfirst** [comment]
@lalybar , found the opposite issue. She expected the auto-tagged to be bumped as patch and not get the version specified in the `bit tag` command.
I started fixing it here: https://github.com/teambit/bit/pull/4211.
However, once done, some of the e2e-tests failed. Here is what I found:
1. In the legacy (and Harmony), `--minor`, `--major` flags do effect the auto-tagged. The auto-tagged bumped by minor/major.
2. in Harmony, another change was introduced and when tagging with a specific version, that version goes also to the auto-tagged. (on legacy, in this case, the auto-tagged bumped as patch).

The question is what do we want to do. Should we ALWAYS bump auto-tag as patch, or let the user decide. 
@GiladShoham , @itaymendel .

**Comment by GiladShoham** [comment]
The auto tag should be always bumped as a patch. 
We can add in the future new flag something like `--auto-tag` that know to get patch/minor/major (or even exact version) and apply it on all the auto-tagged components

**Comment by davidfirst** [comment]
Implemented as Itay and Gilad suggested (without the extra-flag of --auto-tag for now) in the PR above.

**Comment by rlveiga** [comment]
Hey guys, I know I am very late to be returning to this discussion but my issue still persists. 

> The auto tag should be always bumped as a patch.

Why though? Suppose I have updated a component that now depends on a new external method, so I would like to bump it up a `minor` version. However, there are other components which depend on this updated one. I think it makes sense that they should also be updated by a `minor` version as they would also require this new method to be added. 

If this issue could somehow be avoided and resolved on my side, please let me know!

**Comment by davidfirst** [comment]
@rlveiga you can manually specify each id the version you want, or specifying them all including the auto-tag and then use the new `--ver` flag.
However, there is no option to bump by minor/major only the auto-tagged. For this, we'll need to implement a new flag.
