### ISSUE TITLE
Issues with importing components from Vue3+TS project using compiler @bit/bit.envs.compilers.vue

### ISSUE THREAD

**Issue by DileepSArjun** [teambit/bit#4003]
### Description
Vue3+TS project, trying to build Single File Components using bit vue compiler @bit/bit.envs.compilers.vue version v0.1.13.
After 'bit add' of components and its dependencies. When trying to build the components using 'bit build', getting error for components who have imported TS files as its dependencies. .vue files with out TS files as dependency is working good.
Following is the error:
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export interface ObjectLiterals {
|   [key: string]: string;
| }

I assume its an issue with specifying the webpack loader for loading TS files. But I didn't find any documentation on bit.dev to configure this.

How can I solve this issue ?.

### Specifications

- Bit version: 14.8.8
- Node version: v12.16.3
- npm version: 6.14.1
- Platform: Windows
- Bit compiler (include version): bit.envs/compilers/vue@0.1.13
- Bit tester (include version): 

### Context and additional information

This is for an exploration to cherry pick the right tooling for an organization works with Vue3 + TS environment.

**Comment by itaymendel** [comment]
hi,

sadly bit doesn't support vue3 at the moment. we'll be re-implementing vue support for bit v15 when angular support is shipped.
