### ISSUE TITLE
Error during tag/build when using testing-library/jest-dom matchers

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4004]
### Describe the bug

I receive the following error when running `bbit tag` or `bbit build`

```
✖ /Users/someuser/Library/Caches/Bit/capsules/0b03fbda727426b9600433bee84d17eff31d0b2a/my-org.custom-environment-test_controls_fancy-input@0.0.1/FancyInput.test.tsx:9:19 - error TS2339: Property 'toHaveValue' does not exist on type 'JestMatchersShape<Matchers<void, HTMLElement>, Matchers<Promise<void>, HTMLElement>>'.
9     expect(input).toHaveValue("test value");
```

### Steps to Reproduce

1. Open this project:
[custom-env-test.zip](https://github.com/teambit/bit/files/6211772/custom-env-test.zip)
2. Run the following commands:
```
yarn
bbit link
bbit build
```

### Expected Behavior

`bbit build` should run successfully

### Specifications

- Bit version: 0.0.331 (@teambit/legacy: 1.0.42)
- Node version: v14.15.5
- yarn version: 1.22.10
- Platform: macOS 11.2.3

### Additional context

I have found a workaround for this problem. Here it is:
1. Add this line `import '@testing-library/jest-dom';` at the top of `FancyInput.test.tsx`.
2. Change package manager to `yarn` in `workspace.jsonc`.

Now `bbit build` runs successfully.

**Comment by davidfirst** [comment]
@Mikilll94 , seems like the `toHaveValue` is not supported by Jest, only by `@testing-library/jest-dom`, which is not included in the react-env by default (we might change it soon). 
Adding the import statement is one way to go. An alternative is to create your own env (a composition over react-env) and add it as a dev-dependency in the dependency-resolver policy.

**Comment by Mikilll94** [comment]
@davidfirst 
Thanks for your answer. However, now I have two question:
1. Why is it working only for yarn and not for pnpm? Adding this import statement works only for yarn, not for pnpm. That's strange.
2. Are you sure that `@testing-library/jest-dom` is not part of the react env? Take a look at this file: https://bit.dev/teambit/react/react/~code/jest/setupTests.js

**Comment by davidfirst** [comment]
Oh I haven't noticed. Yes, it did use it and `bit show react` (on bit-bin repo) does show this as a package dependency.
@GiladShoham , should we add the `@testing-library/jest-dom` to the `getDependencies()` inside react-env? If not, there is an issue with the dependency resolution of this package.

**Comment by GiladShoham** [comment]
I'm going to fix this soon
