### ISSUE TITLE
bit init --harmony don't create files/folders

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4013]
Here is my steps basically:

Download Bit executable Windows .exe file and saved enviroment variables.
npm i -g @teambit/bvm
bvm install
run command `bit init --harmony` at root of project => Only .bitmap file is created after run this command

.bit folder and workspace.jsonc is not created. (i been authorized). So i created this folder and file. It is happen some error or problem for future ?

- Bit version: 0.0.337
- Node version: v12.18.3
- npm version: 6.14.6
- Platform: Windows WSL2 Ubuntu
- Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.53
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi!
did the project already had a bit-v14 workspace in the past?

**Comment by enes-get-local** [comment]
> hi!
> did the project already had a bit-v14 workspace in the past?

No that was first one

**Comment by davidfirst** [comment]
@enes-get-local , is it possible that it has a parent directory with bit installed?
Please try to create a new directory on `/tmp` cd into it and run `bit init --harmony`, then run `ls -lah` and paste the output here.

**Comment by s97712** [comment]
+1

**Comment by s97712** [comment]
I remove bit config from package.json, now it can create these files/folders.
