### ISSUE TITLE
bad error message when component files are missing.

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4015]
I got this warning message:
```
bit-bin git/master*  
❯ bbit s                    
directory "scopes/preview/cli/use-preview-server" is empty, no files to add
```

It happened because I was switching between branches, and the component files at `scopes/preview/cli/use-preview-server` were deleted.

This warning stops all bit activity, and any workspace command fails (like `install`, `import`)

### Steps to Reproduce

1. Open a workspace
1. Delete component files, ie  
```
rm -f scopes/preview/cli/use-preview-server/*  
```
1. Run any bit command, e.g. `bit install`

### Expected Behavior

I'd expect a more clear error message, like:
```
Component 'team.bit/cli/use-preview-server' is missing its main file, 
  at './scopes/preview/cli/use-preview-server'
```

or even the regular error message:
```
error: component in path "/Users/kutner/projects/bit-bin/scopes/preview/cli/use-preview-server" was not found
```

Another option is to show this a regular error in `bit status`.
explain your problem.

### Specifications

- Bit version: 0.0.334 (harmony)
- Node version: 12.19.0

**Comment by stepanjakl** [comment]
Hi,

I have a similar issue here.

`directory "bit-components/button" is empty, no files to add`

It exclusively started occurring, once I put the component folder inside the .gitignore file.

So, there goes one potential remedy.
