### ISSUE TITLE
component generator override

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#4016]
### Description

At the moment running the component generator for create react-component card will override any component that already exists which can be quite dangerous.

### Describe the solution you'd like

message something similar to below: 
this component already exits, choose a different scope for your component by adding the --namespace followed by the scope name. eg --namespace ui 

If you would like to override the component use the --override flag. Warning this will override all existing files in that component.

**Comment by itaymendel** [comment]
i feel that "override" might be complicated when the overridden component was already exported (and/or other components depend on the overridden component).

I know this can make the feature slightly frustrating, but I'm leaning towards not allowing the ability to override.

@davidfirst @GiladShoham what do you say?

**Comment by debs-obrien** [comment]
good point @itaymendel , didn't think about that. I'm ok with not overriding, the feature I want is basically that it doesn't auto override component which is what is happening right now

**Comment by davidfirst** [comment]
I'm good either way. I won't implement the `--override` then. I'll just show the message above without the override part.
