### ISSUE TITLE
Can not use exported bit component into another component

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4018]
Bit version: 0.0.337
Node version: v12.18.3
npm version: 6.14.6
Platform: Windows WSL2 Ubuntu
Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.53
Bit tester (include version):

I m using bit harmony workspace and i had exported hooks functions. I can use them into any component but i can't tag any component that use exported functions.

I have exported component that is stored collection, It's name is  `useMeasure`  
![image](https://user-images.githubusercontent.com/70728456/112863156-3a86d400-90bf-11eb-813e-b79c2ac3c45a.png)

I want to use it into another component. And also will export this new component to collection. This component name is `useResponsiveSize`

Imported useMeasure component like this `import { useMeasureWithRef } from '@local/local-harmony.utils.use-measure';`

```
import React, { useCallback, useRef } from 'react';
import { useMeasureWithRef } from '@local/local-harmony.utils.use-measure';

const useResponsiveSize: () => ResponsiveSize = () => {
  const getCurrentSize: (width: number) => ResponsiveSize = useCallback((width) => {
    if (width > 1216) {
      return 'desktop';
    } else if (width > 768) {
      return 'tablet';
    } else {
      return 'phone';
    }
  }, []);

  const ref = useRef(document.body);
  const { width } = useMeasureWithRef(ref, false);

  return getCurrentSize(width);
};

export default useResponsiveSize;
```

I added `useResponsiveSize` successfuly with bit add utils/useResponsiveSize.........

```
But i get error when try to tag this component:
Cannot find module '@local/local-harmony.utils.use-measure' or its corresponding type declarations.
```

![image](https://user-images.githubusercontent.com/70728456/112863641-baad3980-90bf-11eb-8b64-7de5892d9f7c.png)

Any suggestion ?

**Comment by itaymendel** [comment]
Hi!

Can you please run `bit status` and post the outputs?
