### ISSUE TITLE
Cannot find documentation about absolute path for  harmony 

### ISSUE THREAD

**Issue by jvvcn** [teambit/bit#4019]
How to use absolute path with the harmony version? Is there any kind of documentation/example?

**Comment by davidfirst** [comment]
@jvvcn , we're missing some context here. Where do you want to use absolute-path, in what command?

**Comment by jvvcn** [comment]
@davidfirst I wanna build the component, while building I get an error about path resolution.

**Comment by davidfirst** [comment]
@jvvcn , please attach the error you got.

**Comment by itaymendel** [comment]
closing the issue due to in-activity and no STRs for debugging the issue.
