### ISSUE TITLE
Bit Harmony - postcss and tailwindcss

### ISSUE THREAD

**Issue by robrichardson13** [teambit/bit#4020]
### Description

Does anyone know of a way to implement `tailwindcss` (ideally as a `postcss` plugin)? I have tried a couple of methods and have gotten close, but have been blocked somehow each time.

### Specifications

- Bit version: 0.0.338
- Node version: v15.5.1
- npm / yarn version: npm - 7.3.0
- Platform: macos
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

**Custom CSS Compiler** - When trying this approach to compile my CSS file(s), I was blocked by the actual `@teambit/compiler` because `transpileFile()` function inside of `workspace-compiler.ts` is synchronous and the `postcss().process()` function needs to be async in order work. (I couldnt find a sync function to transpile the file)

**Custom Build Task** - I was able to get this to work and actually write the compiled css file, but that would only work for publishing it up. I want this to work for my preview dev server, dev server, and potentially a production environment.

**Custom Env Extension** - If I extend the react compiler to pass in my own `webpack.config` file to take care of the `css` files. I set it up with `postcss-loader` but this seems to fail because of an `unknown word error` around the `var` imports.

Im not sure what the best approach would be to get this into my workflow, but any help would be appreciated.

Also - I tried joining the slack, but it seems to be closed and you have to be invited by a workspace admin.

**Comment by itaymendel** [comment]
I would like to take a swing at it @robrichardson13 
any chance you have a base repo for a Bit component that uses TW and has an extension configured with the webpack loader for TW?

**Comment by robrichardson13** [comment]
Hi @itaymendel I threw together a repo to show a half-working solution. I have this scenario working on dev (by running `bit start`), but when you try to build or tag the components, you get an error. I'm in the slack channel if you want more context on any of this.

https://github.com/robrichardson13/bit-harmony-tailwindcss

**Comment by GiladShoham** [comment]
This is not working with the new webpack API
see example here -https://github.com/teambit/react-tailwind-env
worth see the live coding to implement it - https://www.twitch.tv/debs_obrien/v/1011007644

**Comment by ShivamJoker** [comment]
@GiladShoham the twitch link is unavailable. Can you please refer to some docs or guides on setting this up with JIT ?

**Comment by lucaswalter** [comment]
Is there a live link the video?
