### ISSUE TITLE
Can not find module or its type declarations

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4031]
Bit version: 0.0.337
Node version: v12.18.3
npm version: 6.14.6
Platform: Windows WSL2 Ubuntu
Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.53
Bit tester (include version):

I have really serious issue that i can't solve so i can't import any ui component. I m blocked now ca't keep going. Please help me about that
I m using baseweb design framework ([https://baseweb.design/](https://baseweb.design/)) . Baseweb is using styletron-react in components. See below code it is simple Block component:

```
import React from 'react';
import { Block } from 'baseui/block';
import { Property } from 'csstype';
import { overRevealZIndex } from '@local/local-harmony.utils.z-index';
interface Props {
  key?: any;
  children: any;
  style?: any;
  backgroundColor?: string;
  onClick?: Function;
  cursor?: Property.Cursor;
  className?: string;
  width?: Property.Width;
  height?: Property.Height;
  id?: string;
}
const IconWrapper: React.FC<Props> = ({
  key,
  children,
  style,
  backgroundColor,
  onClick,
  cursor,
  className,
  width,
  id,
  height,
}) => {
  return (
    <Block
      //@ts-ignore
      id={id}
      key={key}
      className={className}
      display={'flex'}
      justifyContent={'center'}
      flexDirection={'row'}
      alignItems={'center'}
      width={width}
      height={height}
      //@ts-ignore
      onClick={() => onClick()}
      $style={{
        cursor,
        background: backgroundColor,
        zIndex: overRevealZIndex,
        ...style,
        pointerEvents: 'all',
      }}
    >
      {children}
    </Block>
  );
};
export default IconWrapper;
IconWrapper.defaultProps = {
  backgroundColor: 'transparent',
  cursor: 'default',
  height: '100%',
  onClick: () => {},
  style: {},
  width: '100%',
};
export const id = 'com.local.componentTemplate.IconWrapper';
```
I m using Block component here so that is all. But i get this error when tag this component see screenshot :

![image](https://user-images.githubusercontent.com/70728456/113125904-c4e64980-921f-11eb-84da-d14f8aa32b6c.png)

Also i added package.json here you can check it.
[package.json.txt](https://github.com/teambit/bit/files/6235627/package.json.txt)

**Comment by antonioberetini** [comment]
Guys we are waiting on this... we can't proceed without this issue being addressed.

**Comment by davidfirst** [comment]
Here is the problem. You're using `baseui`, which has in its root dir `overrides.ts` file with the following line:
```
import {StyleObject} from 'styletron-react';
```
If you take a look into the package.json of this package, it has `styletron-react` as a dev-dependency for some reason.

What you can do is manually add this package as a dependency. See here an example:
https://harmony-docs.bit.dev/aspects/dependency-resolver#auto-registered-dependency-version-and-type

**Comment by enes-get-local** [comment]
> Here is the problem. You're using `baseui`, which has in its root dir `overrides.ts` file with the following line:
> 
> ```
> import {StyleObject} from 'styletron-react';
> ```
> 
> If you take a look into the package.json of this package, it has `styletron-react` as a dev-dependency for some reason.
> 
> What you can do is manually add this package as a dependency. See here an example:
> https://harmony-docs.bit.dev/aspects/dependency-resolver#auto-registered-dependency-version-and-type

```
{
    "teambit.workspace/workspace": {
      "defaultScope": "local.demo"
    },
    "teambit.dependencies/dependency-resolver": {
      "policy": {
        "dependencies": {
          "styletron-react": "^5.2.7"
        }
      }
    }
  }
```
@davidfirst  this is my workspace.jsonc file. It is correct ? I get still same error

**Comment by enes-get-local** [comment]
@davidfirst 

```
{
    "teambit.workspace/workspace": {
      "defaultScope": "local.demo"
    },
    "teambit.workspace/variants": {
        "*": {
          "teambit.dependencies/dependency-resolver": {
            "policy": {
              "devDependencies": {
                "styletron-react": "5.2.7"
              }
            }
          }
        }
      }
  }
```

That works !
