### ISSUE TITLE
Delete component files by `bit untrack` command

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#4051]
### Description

With `bit create`, users create components quickly and might want to remove them not only from the .bitmap file but also from the filesystem. 

### Describe the solution you'd like

Provide a flag to delete the files. Or delete them by default and provide a flag to keep them.
Ideally, remove the `bit untrack` altogether and use `bit remove` instead.

### Additional context

Currently, `bit untrack` doesn't delete from the filesystem. In the legacy it made sense because in you would track existing code as bit component. With Harmony and especially with `bit create`, it makes sense to allow deleting files.

@itaymendel , I'll leave the decisions here for you.

**Comment by itaymendel** [comment]
as this is an irreversible command for new/modified components, my main concern is that Bit has no idea if the component was added via `bit add` or created with `bit create` nor does it knows if there's any important code there.

here's my suggestion:

* `bit remove` should support removing `new` components.
* `-d` flag behavior should be `delete component files (applied for new/modified/staged components only. others are always deleted)`
* Mark `bit untrack` as deprecated.

**Comment by GiladShoham** [comment]
In general, I agree with @itaymendel 
But since we already have a confirmation about bit remove we can also add a question about removing files (and adding flags to quite delete/do not delete to be able to skip the confirmation)

**Comment by davidfirst** [comment]
@debs-obrien , you asked for this change. It's merged as per Itay's suggestion. 
@GiladShoham , I forgot about your comment. Please let me know if you want to make changes. See the PR above for more details.
