### ISSUE TITLE
New version of bit export error

### ISSUE THREAD

**Issue by s97712** [teambit/bit#4053]
when I try to exprot my components, I get the below error
```bash
$ bbit export 
unexpected network error has occurred.
server responded with: "failed to push objects to scope "json.bit".
the remote scope "json.bit" responded with an error "invalid json response body at http://scope-proxy-internal.scopes/diy1ymo/v1/api/scope/put reason: Unexpected token < in JSON at position 0""
```
What is the http://scope-proxy-internal.scopes?

### Steps to Reproduce

1.
1.
1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by guysaar223** [comment]
Hi @s97712 
it's a bug in our bit.dev cloud, I'll check it.
can you try re-export and let me know if it still happens, 
Guy :)

**Comment by s97712** [comment]
Still have the same problem.

**Comment by guysaar223** [comment]
Hi, i checked it, you are try to export to from harmony workspace to legacy workspace, you need to remove your scope and re-create a new harmony scope:
https://harmony-docs.bit.dev/getting-started/remote-scope/#create-a-remote-scope

**Comment by GiladShoham** [comment]
@s97712 
We will add a descriptive error during the export in that case.
