### ISSUE TITLE
`bit new` to generate workspaces/projects

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#4056]
# Workspace templating
To simplify developer workflow, Bit should automate the process of creating new workspaces.

## Using a template
When using a template to generate a workspace, Bit should create a new root directory for a project, set configs, generate a list of components, generate a `README.md` and init a Git repo.

### Load a template
When running `bit new` there's no `workspace.json`. this is a problem, as workspace-tempaltes are in aspects Bit needs to load.
`bit config` should have a list of default-aspects the user can decide to load. This way they can set their own aspects and have their tempaltes available by default.

### Aspect links and dependencies
Rn `bit install` after generating the workspace to set aspect-links and install dependneices.

### Repository init
* Bit should init a new Git repository and keep scope in that directory.
* Create `.gitignore` as well.

## Register a template
Any aspect (include envs) can register templates. Each template should have a name, workspace.json and an array of components.

## Show all available templates
When running `bit templates` when not in a workspace, show a list of all available workspace-templates.

* When not in a workspace, show only workspace-templates

## Generate a workspace from CLI
Introduce a `new` command to use templates.

```sh
bit new <template-name> <workspace-name> [--aspect | -a] [--owner | --o] [--standalone | -T]
```

#### `<template> name>`
Name of the template to use. Will be used as the root directory create for the workpsace as well as local scope name.

#### `<workspace name>`
Name of the project to create. Will be used as the root directory create for the workpsace as well as local scope name.

#### `[--aspect | -a]`
Where to fetch the template from. Can be a remote aspect..

#### `[--owner | --o]`
Append a `${owner}.` to any of the `defaultScope` in the `workspace.jsonc` template.

#### `[--standalone | -T]`
Skip generation of Git repository.

**Comment by GiladShoham** [comment]
That's great.
Few comments:
1. I would not set default aspects via the bit config, but rather in another global config for this. we already support global file called - `.bitrc.jsonc` that does exactly this. (we might want when implementing `bit use` to support put aspects there.
2. I think maybe the template should contain a folder structure or can contain folder structure for the workspace (empty dirs in different places)
3. we should add a description for the template
4. I'm not sure about having an array of components inside the template. we can make the sugar with `--import` flag that after the init import some specific components. but I'm not sure about it.

**Comment by itaymendel** [comment]
1. sure, i think that `bit config` provides a cleaner ux, as i can use it to simply get/set global config wherever i am on the system. but we can start with what's available
2. instead of a folder strcuture i want it to be components in different places to show functionality etc.
3. yes
4. "array of components" - meaning a set of `new` components to start as s baseline. imagine a `bit create blog ...` or `bit create design-system ....` where the template contains code as well, so you can get started.

**Comment by davidfirst** [comment]
While this command is still experimental. It's fully implemented. 
Users are able to generate new workspace by core template and can create their own aspects with templates.
