### ISSUE TITLE
bit harmony can not auto add @types/* dependency

### ISSUE THREAD

**Issue by s97712** [teambit/bit#4058]
Such as `delay` module, bit harmony only add the `delay` dependency, but not the `@types/delay` dependency.

**Comment by itaymendel** [comment]
Hi @s97712 

Dependency resolution uses static code analysis to find all `import` statements and use them to build the dependency graph.
Right now the way to add these deps is by setting a dependency-policy for your components and adding these `@types/...`.

@GiladShoham , potentially we can try and find all `@type/[module-name]` and use it to further improve the process. What do you think?

**Comment by GiladShoham** [comment]
We do have such mechanism to add @types automatically for a long time.
So in surprised it didn't catch it.
It might be some bug in specific case.
If you can add exact steps to reproduce (like a github repo with files and workspace.jsonc)

**Comment by s97712** [comment]
> We do have such mechanism to add @types automatically for a long time.
> So in surprised it didn't catch it.
> It might be some bug in specific case.
> If you can add exact steps to reproduce (like a github repo with files and workspace.jsonc)

https://github.com/s97712/test_bit

**Comment by GiladShoham** [comment]
@s97712 found the issue, it's fixed as part of https://github.com/teambit/bit/pull/4069, it will be merged soon.
