### ISSUE TITLE
bit install: error: you do not have permissions to access '/mnt/d/workspace/wjapi/node_modules/rxjs', were you running bit, npm or git as root?

### ISSUE THREAD

**Issue by s97712** [teambit/bit#4059]
```bash
$ bit install
  Resolving component dependencies for workspace: 'my-workspace-name'
✔ import 1 components with their dependencies (if missing)
  installing dependencies in workspace using teambit.dependencies/pnpm
✔ running pre install subscribers
✔ deduping dependencies for installation
 WARN  Moving rxjs that was installed by a different package manager to "node_modules/.ignored
error: you do not have permissions to access '/mnt/d/workspace/wjapi/node_modules/rxjs', were you running bit, npm or git as root?
```

A clear and concise description of the issue.

### Steps to Reproduce

1.
1.
1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by zementeshome** [comment]
@s97712 how did you resolve this error? i'm running into this error when i run bit install and bit start.
