### ISSUE TITLE
bit show: dev files showing under regular files

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4060]
![](https://user-images.githubusercontent.com/5400361/113515291-40c3f700-957c-11eb-87c0-ddd09f5584bb.png)

### Steps to Reproduce
1. Go to any component with dev files. For example, input/checkbox/label, at harmony-base-ui.
1. run bit show:

```
❯ bit show input/checkbox/label
```

output shows: 

```
├─────────────┼─────────────────────────────────────────────────────────┤
 │ files       │ checkbox-label.docs.mdx                                 │
 │             │ checkbox-label.tsx                                      │
 │             │ checkbox.compositions.tsx                               │
 │             │ index.ts                                                │
 ├─────────────┼─────────────────────────────────────────────────────────┤
 │ dev files   │ checkbox-label.docs.mdx (teambit.docs/docs)             │
 │             │ checkbox.compositions.tsx                               │
 │             │ (teambit.compositions/compositions)                     │
 ├─────────────┼─────────────────────────────────────────────────────────┤
```

### Specifications
* Bit version: 0.0.334 (Harmony)

**Comment by GiladShoham** [comment]
This is a result of the files computed by the component aspect, which doesn't have access to the dev-files aspect.
Therefore it doesn't know what is a dev file and what not.

**Comment by KutnerUri** [comment]
the component aspect reports component files, and dev aspect reports dev files?
