### ISSUE TITLE
Support for the experimental error at compositions.jsx file

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4064]
Bit version: 0.0.337
Node version: v12.18.3
npm version: 6.14.6
Platform: Windows WSL2 Ubuntu
Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.53
Bit tester (include version):

I try to tag and export my component but i get error at compositions.jsx file :

`Icons.compositions.jsx
`
```
import React from 'react';
import * as Icons from '.';

export const IconsComp = () => {
  return (
    <div>
      <Icons.Peoples />
      <Icons.Location />
      <Icons.Marketing />
      <Icons.Logo />
      <Icons.Pages />
      <Icons.Product />
    </div>
  );
};
```
This error raised when try to tag it :

![image](https://user-images.githubusercontent.com/70728456/113575339-61e12200-9626-11eb-88a9-832c7d422f93.png)

attached my package.json file you can see

And also here is my workspace.jsonc 

```
{
  "teambit.workspace/workspace": {
    "defaultScope": "local.local-harmony"
  },
  "teambit.workspace/variants": {
    "*": {
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "devDependencies": {
            "styletron-react": "5.2.7",
            "react":"16.13.1"
          }
        }
      }
    },
    "react/themes/local.common": {
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "dependencies": {
            "@types/node": "^14.14.37",
            "react":"16.13.1",
            "svg-react-loader": "^0.4.6"
          }
        }
      }
    },
    "react/components/common/background": {
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "devDependencies": {
            "styletron-standard": "^2.0.1"
          }
        }
      }
    },
    "react/components/common/clearAll": {
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "devDependencies": {
            "styletron-standard": "^2.0.1"
          }
        }
      }
    }
  }
}
```

[package.json .txt](https://github.com/teambit/bit/files/6258200/package.json.txt)

**Comment by davidfirst** [comment]
@enes-get-local , this is probably the same issue I fixed 3 days ago. https://github.com/teambit/bit/issues/3992.
Please upgrade to the latest version and check.

**Comment by enes-get-local** [comment]
> @enes-get-local , this is probably the same issue I fixed 3 days ago. #3992.
> Please upgrade to the latest version and check.

Yes it works 0.0.344 version. just run `bvm upgrade` @davidfirst thanks
