### ISSUE TITLE
Can not use svg react component

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4065]
Bit version: 0.0.337
Node version: v12.18.3
npm version: 6.14.6
Platform: Windows WSL2 Ubuntu
Bit compiler (include version): bit.envs/compilers/react-typescript@3.1.53
Bit tester (include version):

i get errors when works with svg files.

Basically, i m using react-svgr @svgr/cli to transform svg files to react component. So i have a folder name is icons and all icon components placed here. And export all of them from index.js file. So i exported this my collection and try to use it as npm package. i get error when start my app (see ss)

![image](https://user-images.githubusercontent.com/70728456/113607562-00cf4380-9652-11eb-90cc-4d03224df4fc.png)

```
-icons
    -icon1.js
    -icon2.js
     index.js
```

```
import React from 'react'
import * as Icons from '@local/local-harmony.icons.icons';

export const LocalInput = () => {
  return (
    <div>
      
    </div>
  )
}
```

**Comment by enes-get-local** [comment]
@davidfirst is there a solution? I can't use svg with anyways nothing works

**Comment by GiladShoham** [comment]
Is this a harmony workspace or a legacy workspace?

**Comment by enes-get-local** [comment]
> Is this a harmony workspace or a legacy workspace?

Harmony legacy

**Comment by enes-get-local** [comment]
> > Is this a harmony workspace or a legacy workspace?
> 
> @GiladShoham it is Harmony workspace

**Comment by itaymendel** [comment]
you probably missing a webpack loader to handle SVGs.
see here on how to extend the base React config and apply your own webpack loaders https://harmony-docs.bit.dev/aspects/react#customize-environment

**Comment by itaymendel** [comment]
Hi,

So in your app you use svgr as part of your build process, but i guess that in Bit this process does not run, meaning that behind the scenes what you export is a dir full of SVGs. So when consuming them your app complains that it needs a webpack loader to handle SVG files.

**Comment by enes-get-local** [comment]
i m using next.js framework so problem is next don't transpile node_modules packages. I needed to configure it manually. Solution is get bunled file of component with webpack,babel and export created bundled js file to bit collection.
