### ISSUE TITLE
use alias

### ISSUE THREAD

**Issue by uyarn** [teambit/bit#4068]
There are some many directories with the same name within the source code of bit, such as `consumer`vs `api/consumer`, `extensions` vs `scope/extensions`. 
While import modules from other directories, always need to use long relative path to describe it, like the code below, which makes the source code become difficult to read and understand, why not use `babel-plugin-module-resolver` and config the paths to `tsconfig` to use the alias of the path, such as `@/consumer` to represent the `src/consumer`
![image](https://user-images.githubusercontent.com/26377630/113664244-feb2c680-96dd-11eb-8f8e-d2d43ce050b0.png)

**Comment by itaymendel** [comment]
Hi @uyarn 

I guess that in this case you refer to the Bit codebase?
First of all, thanks for caring about the dev-experience in the Bit-codebase. I'd like to share some insights about the codebase itself so you can better understand the situation and why you see these relative-paths.

The codebase contains 2 projects:

1. Bit v14 (legacy) - starts in `src` dir
2. Bit v15 (harmony) - starts in `scopes` dir

We are in a transition period to move all functionality to v15.
The v15 codebase starts at the `scopes` directory and we use Bit to manage 100% of the code there, including absolute modules and imports. These module-names are managed by Bit as a core-feature. [See it in action](https://github.com/teambit/bit/blob/master/scopes/envs/envs/environments.main.runtime.ts).

The legacy codebase (`src`) is a very complex monolithic app. All new code is implemented in the `scopes` directory and we slowly move features from `src` to `scopes`. This is why we will not refactor the relative paths to absolute ones. Instead we aim to transfer implementation to Bit v15 (in the `scope` dir).
Right now we need the `src` codebase as `scopes` uses many of its modules as APIs for functionality that hasn't been migrated to `scopes`.

In the long run we aim to use this to distribute the codebase and split it, as Bit gives us this flexibility (ie - stop using a single repository for the entire Bit codebase).

**Comment by uyarn** [comment]
@itaymendel exactly, I am using the v14(legacy) version.
