### ISSUE TITLE
better diff outputs for dependencies

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4076]
When using `bit diff`, things get really messy for dependencies:
![Screen Shot 2021-04-06 at 19 44 09](https://user-images.githubusercontent.com/5400361/113748378-18b9cc80-9711-11eb-92b6-731f08bdfee6.png)

1. It is confusing to see a separate section for Overrides. I'd rather have a total diff, and then explanation about overrides.
2. I'd like to see a clear "dependencies added: [....]", "decencies removed [...]", "dependencies modified [...]" and maybe "moved to peer [...]", "moved to dev [...]"
3. a vertical list might be clearer?
4. diff should be compact (because we also need to show diff for many components)

Maybe we can so a concise deps diff in regular `bit diff`, and maybe a table when running `bit diff dependencies` or `bit dependencies diff` (the new command).

Results should still be compact (so we could show diff for many components without 

dev deps
| package  | version before | version after |
| ------------- | ------------- |-------------|
| @types/react-native | ^0.63.2 | ^0.63.0 |
|react-native-web| 0.14.8 | -|
|...|...|...|

peer deps
| package  | version before | version after |
| ------------- | ------------- |-------------|
| react-dom | - | ^16.8.0 |
|...|...|...|

**Comment by GiladShoham** [comment]
Try bit show --legacy --compare and let me know what you think

**Comment by itaymendel** [comment]
what about such output?

```
dependencies
        name           diff     before          after
      > lodash         remove     12.3.5          ----
      > ...            upgrade     ...             ...
      > ...            add          ...             ...
      > ...            downgrade    ...             ...


devDependencies
        name           diff     before          after
      > @types/react   remove      12.3.5      ----
      > ...            upgrade     ...             ...
      > ...            add          ...             ...
      > ...            downgrade    ...             ...

peerDependencies
        name           diff     before          after
      > react          remove      12.3.5      ----
      > ...            upgrade     ...             ...
      > ...            add          ...             ...
      > ...            downgrade    ...             ...
```

1. no tables
2. when dep is was not found in before/after we mark `---`
3. show diff according to semver rules (+add/remove)

**Comment by KutnerUri** [comment]
yes I also dislike the cli table. Would prefer a tab table.

**Comment by GiladShoham** [comment]
@itaymendel We can make something like this..

**Comment by davidfirst** [comment]
I ended up with a "compact table" (no horizontal borders) because I didn't find a good way to keep the column aligned without using the cli-table `borderStyle: none` option, which looks bad. 

<img width="548" alt="Screen Shot 2021-04-13 at 6 05 01 PM" src="https://user-images.githubusercontent.com/1963573/114627295-0bf22700-9c83-11eb-9518-36eb57c85c27.png">
