### ISSUE TITLE
defaultScope breaks workspace when user adds a slash

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#4078]
### Describe the bug

If a user changes the defaultScope and adds a slash there such as
`"defaultScope": "debbie/test"`
User will get docs half rendered, no compositions. test work but dependencies give a 503 server error.

### Steps to Reproduce

1.`"defaultScope": "debbie/test"`
1. add a component and run bit start

### Expected Behavior

User should be warned that they cannot use a slash, we should detect this and if they do use a slash somehow in the workspace it should tell user so they are not seeing weird stuff and have no idea what they have done wrong.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
@GiladShoham please add a validation to `defaultScope` and print an error if the string is invalid.

**Comment by davidfirst** [comment]
Fixed by https://github.com/teambit/bit/pull/4243.
