### ISSUE TITLE
Improve output when scope access denied

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4085]
I got this error:

```
harmony-evangelist git/master*  
❯ bbit install
  Resolving component dependencies for workspace: 'harmony-evangelist'
kutner.harmony-temp: access denied
```

scope `kutner.harmony-temp` indeed does not exist. but can we improve the text?

### Steps to Reproduce
1. import component from a non existing scope, i.e.

`bit import kutner.harmony-temp/input/button`

### Expected Behavior
something like this

```
error accessing scope 'kutner.harmony-temp': access denied
```

### Specifications
* Bit version: 0.0.349 (harmony)

**Comment by davidfirst** [comment]
@KutnerUri , it's not that simple. The test you see in the current error "access denied" can be anything else that has nothing to do with access. It can be merge-conflict for example. 
Please let me know if you have a suggestion that covers all cases.

**Comment by KutnerUri** [comment]
oh. Then maybe the backend needs to improve it's output? It seems weird to get "access denied" on merge conflict
