### ISSUE TITLE
Can't export to private collection

### ISSUE THREAD

**Issue by SC7639** [teambit/bit#4091]
### Describe the bug

When trying to export component to a private collection in organization I get the following error `error: component "5f92c2b23bb98000130dbbd2/date-format@0.0.1" was not found`

### Steps to Reproduce

1. Add a component with `bit add [src]/[file/folder]`
2. Tag component with `bit tag [component id]`
3. Set default scope using `defaultScop` in `package.json` under the `bit`  key
4. Export component using `bit export`

### Expected Behavior

Exports with no issues to bit.dev collection

### Screenshots, exceptions and logs

```bash
bit export
error: component "5f92c2b23bb98000130dbbd2/date-format@1.0.2" was not found.
```

### Specifications

- Bit version: 14.8.8
- Node version: v14.0.0
- npm / yarn version: npm: v6.14.4
- Platform: linux

### Additional context

I created a public collection under the same organization and it exported there with no issues

**Comment by SC7639** [comment]
I've tried to debug the issue and I'm not sure if it helps. I tried with another component got the same issue exporting and now I am getting 
```bash
bit export skiddle.web contexts
error: merge conflict occurred when exporting the component(s) 5f92c2b23bb98000130dbbd2/contexts (version(s): 0.0.1) to the remote scope.
to resolve this conflict and merge your remote and local changes, please do the following:
1) bit untag [id] [version]
2) bit import
3) bit checkout [version] [id]
once your changes are merged with the new remote version, please tag and export a new version of the component to the remote scope.

bit import skiddle.web/contexts
error: unable to export components to 5f92c2b23bb98000130dbbd2 because they have dependencies on components in skiddle.web.
bit does not allow setting dependencies between components in private collections managed by different owners.

see troubleshooting at https://docs.bit.dev/docs/bit-dev#permissions-for-collections
```

**Comment by SC7639** [comment]
Another thing I am confused by is what is the hex number `5f92c2b23bb98000130dbbd2`

**Comment by davidfirst** [comment]
This has been settled in Slack. 
@SC7639 , if this is anything else needed for this issue, please re-open.
