### ISSUE TITLE
Deprecating components does not work at all

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4095]
### Describe the bug

Deprecating components in the Bit Cloud does not work at all.

### Steps to Reproduce

1. Export a component to the remote scope. (`bit export`)
2. Run: `bbit deprecate your-org.your-scope/namespace/your-component --remote`
3. You should see in the console:
`deprecated components: your-org.your-scope/namespace/your-component`
4. Go to the Bit.dev and check your component. You should see that nothing has changed. The component is not marked as deprecated.

5. Install your "deprecated" component from the `npm` into some project. You should see that the component is installed successfully without any warnings.

### Expected Behavior

- Deprecated component should have an indication an Bit.dev.
- Deprecated component should display a warning when installing it from npm.

### Specifications

- Bit version: 0.0.353
- Node version: 14.15.5
- yarn version: 1.22.10
- Platform: macOS 11.2.3

### Additional context

I was following the docs here:
https://harmony-docs.bit.dev/building-with-bit/removing-components/#deprecate-a-component-in-a-remote-scope

**Comment by davidfirst** [comment]
@JoshK2 , is this the same issue you mentioned about `bit deprecate`?

**Comment by davidfirst** [comment]
@Mikilll94 , this should be fixed now when you deprecate/undeprecate new components. 
Please re-open otherwise.
