### ISSUE TITLE
webpack config optimization

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#4096]
This issue meant to list different webpack config possible optimization as a result of moving to webpack5.
This are relevant only after merging https://github.com/teambit/bit/pull/3673 (webpack5 upgrade)

### webpack.config.preview
* [x] remove `file-loader` and use `type: 'asset/resource'` instead

### webpack.config.preview.dev
* [x] replace `style-loader` with `MiniCssExtractPlugin`

## webpack.base.config
* [x] remove `file-loader` and use `type: 'asset/resource'` instead

## webpack.dev.config
* [x] replace `style-loader` with `MiniCssExtractPlugin`

**Comment by ScriptedAlchemy** [comment]
Will look at updating this sunday

**Comment by GiladShoham** [comment]
done as part of https://github.com/teambit/bit/pull/4433
