### ISSUE TITLE
Disable `bit export <scope>` for Harmony

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#4098]
I should only be able to set target scope for components via configs (workspace/component). This was a feature in legacy, but we must block this for harmony, as the result will be a broken component.

**Comment by itaymendel** [comment]
i see there's already a PR for it? https://github.com/teambit/bit/pull/3669

**Comment by davidfirst** [comment]
@itaymendel , yes, I started working on it back then, but it turned out to have some complexity. Things changed since then, so I'll get back to that again.

**Comment by davidfirst** [comment]
Done in the PR above.
