### ISSUE TITLE
must have a '[Symbol.iterator]()' method that returns an iterator error

### ISSUE THREAD

**Issue by enes-get-local** [teambit/bit#4100]
I have a ts react component that use react-spring. It raise many ts error with useSpring hook when try to tag it

![image](https://user-images.githubusercontent.com/70728456/114319336-ae8e9680-9b19-11eb-87bd-a3bc1da74390.png)
 
It is Harmony version. Any help ?

**Comment by GiladShoham** [comment]
can you please provide steps to reproduce? or a project tar file / repo will be even better. 
Thanks.

**Comment by itaymendel** [comment]
hi, sadly no STRs, so we can't reproduce the issue.
closing it. please reopen with STRs so we can have a look.
