### ISSUE TITLE
`bit export {scope}` want to change scope of auto-updated component

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4102]
### Describe the bug

I updated a component, tag it, and tried to export it to remote.

### Steps to Reproduce

1. Have two components A and B, B depends on A, but they are in different scopes.
2. Update component A
3. Tag component A
4. Try to `bit export {scopeOfA}`

### Expected Behavior

It exports only components that are in `{scopeOfA}`, and does not try to change scope of B component to that is used scope in command.

### Screenshots, exceptions and logs

```
$ bit tag custom-node
... 
2 component(s) tagged
(use "bit export [collection]" to push these components to a remote")
(use "bit untag" to unstage versions)

changed components
(components that got a version bump)
     > abc.bit-extensions/custom-node@0.0.2
       auto-tagged dependents:
            abc.constants/constants@0.0.2
```

```
$ bit export abc.bit-extensions

bit is about to fork the following components and export them to abc.bit-extensions.
	abc.constants/constants
also, if they're staged, bit will not change their status to exported unless '--set-current-scope' flag is used.

there are additional flags for the 'export' command to specifically handle forking components:
1. '--include-dependencies' exports all dependencies to the destination alongside the component.
2. '--set-current-scope' sets your workspace to use the destination scope as the main remote for the component.
3. '--rewire' changes all dependencies to point to the new destination.
```

```
$ bit s
modified components
(use "bit tag --all [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > types ... ok

staged components
(use "bit export <remote_scope> to push these components to a remote scope")

     > custom-node. versions: 0.0.2 ... ok
     > constants. versions: 0.0.2 ... ok
```

| Component        | Env  |
| ------------- |:-------------|
| abc.bit-extensions/config/jest@0.0.1 | teambit.harmony/node |
| abc.constants/constants@0.0.2 | abc.bit-extensions/custom-node@0.0.2 |
| abc.graphql/contexts@0.0.1 | teambit.react/react |
| abc.bit-extensions/custom-node@0.0.2 | teambit.harmony/aspect |
| abc.bit-extensions/custom-react@0.0.1 | teambit.harmony/aspect |
| abc.graphql/types@0.0.1 | teambit.react/react |

### Specifications

- Bit version: 0.0.354
- Node version: v14.16.0
- npm / yarn version: 6.14.11 / 1.22.5
- Platform: macos

**Comment by ivansky** [comment]
It looks #4098 is related to this issue, but then how to export only one component within a single scope?

**Comment by davidfirst** [comment]
@ivansky , yes, it is related. You shouldn't enter the scope-name anymore. Instead, configure your workspace.jsonc file with the `defaultScope` per rule. Then just run `bit export` and it'll export each component to its default-scope.

**Comment by ivansky** [comment]
@davidfirst How to export only one scope without auto-updated components then?

**Comment by davidfirst** [comment]
@ivansky , not sure I follow. You have compA from scopeA with a dependency compB from scopeB. 
Why would you want to export only compA and not compB? anyone else who import this compA will get an error about missing dependency compB.

**Comment by ivansky** [comment]
@davidfirst  
`<B>` depends on `<A>`, 
after `<A>` is updated then the`<B>` gets auto-update as well,
then there is no way to ignore `B.scope` and export only `A.scope`

**Comment by davidfirst** [comment]
@ivansky , correct. Why would you want to ignore B.scope? why not exporting it?

**Comment by ivansky** [comment]
@davidfirst it's because the intention was to update and export only A. 
It's just weird that the all dependants tree will be updated and in the result exported to the system.
For now it's not that critical to have 1 little dependant component that will be also processed.
Imagine you updates your low-level component that is in dependencies of 1000 other components, 
why would I want them to be auto-updated?

**Comment by davidfirst** [comment]
@ivansky , because otherwise you will need to update these 1,000 dependencies manually one by one :)

In the majority of the use cases when you update a dependency, you want the dependents to be updated to take advantage of your changes. Doing these updates manually is a tedious process.
Again, you can always opt out by running `bit tag compA --skip-auto-tag`, this way, only compA is tagged and as a result, it's the only one that will be exported.

**Comment by ivansky** [comment]
@davidfirst Then would be great to have possibility to check and update components that might be updated due to their dependencies have a new version.

**Comment by davidfirst** [comment]
@ivansky , it's actually the same feature. If you run bit tag with the `--skip-auto-tag` flag, then all the dependents will be shown as modified. This way, the next time you tag with `--all` flag they'll be tagged.

**Comment by ivansky** [comment]
Thanks for explanation!
