### ISSUE TITLE
Argument `skipTests` does not work 

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4104]
### Describe the bug

I am trying to skip tests.
Have not found a way to fix Jest issue with modern timers.

```
Test suite failed to run

    TypeError: Cannot read property 'useFakeTimers' of undefined

      at jasmine2 (../../../../../.bvm/versions/0.0.354/bit-0.0.354/node_modules/jest-jasmine2/build/index.js:134:34)
          at runMicrotasks (<anonymous>)
```

### Steps to Reproduce

1. Have components with `.test.ts` files
2. Have jest config with `timers: 'modern'`
3. Run `bit tag {component}` or `bit tag --skip-tests {component}`

### Expected Behavior

Jasmine2 does not throw TypeError exceptions or if it has `--skip-tests` it should skip them.

### Screenshots, exceptions and logs

```
$ bit tag --skip-tests -f utils

 FAIL  ../../Library/Caches/Bit/capsules/84302ec3719b31c4f41871f00f41ad0ebb199b17/abc.libs_utils@0.0.1/dist/strings.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'useFakeTimers' of undefined

      at jasmine2 (../../../../../.bvm/versions/0.0.354/bit-0.0.354/node_modules/jest-jasmine2/build/index.js:134:34)
          at runMicrotasks (<anonymous>)
  ...

✖ teambit.pipelines/builder, running build pipe for 4 environments, total 25 tasks (completed in 2m)

The following errors were found while running the build pipeline
Failed task 1: "teambit.defender/tester:TestComponents" of env "abc.bit-extensions/custom-node@0.0.2"
component: abc.libs/utils@0.0.1
  ● Test suite failed to run

    TypeError: Cannot read property 'useFakeTimers' of undefined

      at jasmine2 (../../../../../.bvm/versions/0.0.354/bit-0.0.354/node_modules/jest-jasmine2/build/index.js:134:34)
          at runMicrotasks (<anonymous>)
```

### Specifications

- Bit version: 0.0.354
- Node version: 14
- yarn version: 1.2
- Platform: Macos

### Additional context

It seems `skipTests` argument is not even used anywhere.

https://github.com/teambit/bit/blob/master/src/cli/commands/public-cmds/tag-cmd.ts#L117
https://github.com/teambit/bit/blob/master/src/api/consumer/lib/tag.ts#L65

**Comment by davidfirst** [comment]
@ivansky , that's correct. `--skip-tests` doesn't work on Harmony project. 
@itaymendel , do we want to re-use this flag? or maybe we want a general flag to skip certain tasks?

**Comment by davidfirst** [comment]
Discussed with Itay, the answer to the question above is "yes", we should re-use the skip-tests flag.
The PR above fixes it.
