### ISSUE TITLE
Cannot edit profile on Bit.dev website. CORS error

### ISSUE THREAD

**Issue by davidmendezph** [teambit/bit#4116]
### Describe the bug

When trying to edit my profile on bit.dev website, requests fail with CORS errors

### Steps to Reproduce

1. Login on https://bit.dev
2. Go to your profile homepage https://bit.dev/username
3. Try to change anything, your name, homepage, etc...
4. BUG: Request fails with CORS errors: `MissingAllowOriginHeader`.

### Expected Behavior

Profile changes should be updated and stored.

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/78892649/114612481-6aa5a980-9c5f-11eb-9d65-70e7615aa033.png)

### Additional context

Possible issue with the API.

**Comment by guysaar223** [comment]
Hi, @davidmendezph 
sorry for that, fixed.
