### ISSUE TITLE
How to use bit inside a Docker build?

### ISSUE THREAD

**Issue by alexmirkhaydarov** [teambit/bit#4121]
I got a project that uses bit to manage components. I would like to automate this process and deploy the project using cicd to a Kubernetes cluster. How does one be able to use bit inside a docker build process? I have been reading the docs around the bit cli but it uses a browser to authenticate to bit.dev. Is there any work in the pipeline to bring this feature to the bit cli where no user interaction required?

**Comment by GiladShoham** [comment]
We use bit ourselves from our ci.
You can take a look at our config to better understand.
I would start by reading this doc - https://harmony-docs.bit.dev/reference/ci-cd
If you are talking about bit authentication, you can do it by `bit config set user.token <token>`
see it in our own config here - https://github.com/teambit/bit/blob/master/.circleci/config.yml#L93
If you have any more questions, let us know.

**Comment by alexmirkhaydarov** [comment]
@GiladShoham, thank you! I followed your instructions and manage to build it now 👍🏽
