### ISSUE TITLE
FLAGS MISMATCH

### ISSUE THREAD

**Issue by brusand** [teambit/bit#4122]
### Describe the bug

on mac os, i have an angular 7 project, and i try add my first component with bit build and i have the issue 

### Steps to Reproduce

1. have an angular 7 project
2. bit add src/app/cms --main cms.module.ts
3. bit build

### Expected Behavior

the component built.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.
bit build
⢀⠀ loading componentsPkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
⡀⠀ loading componentsPkg: FLAGS_MISMATCH
Pkg: FLAGS_MISMATCH
### Specifications

- Bit version: 14.7.6
- Node version: 10.16.0
- npm / yarn version:
- Platform: mac os
- Bit compiler (include version): angular
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi,

sadly bit doesn't support angular7. we're working on a refactored angular support, but this is not likely to support anything pre-ivy.
