### ISSUE TITLE
process.env.NODE_ENV is not set to 'test' when running `bit test`

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4123]
### Describe the bug
When running `bbit test` , the `process.env.NODE_ENV` variable is not set to "test".

Create-React-App and Next.js set this variable and also many libraries use it, i.e. Material UI
https://github.com/mui-org/material-ui/blob/13138c834bed8ee3843ad29df345cd71d2834daf/packages/material-ui/src/Popper/Popper.js#L106

### Steps to Reproduce
1. Place this line somewhere in the test:

```
        console.log("PROCESS ENV", process.env.NODE_ENV);
```

1. Run `bbit test`
1. It logs `undefined`

### Expected Behavior
It should log `test`

### Specifications
* Bit version: 0.0.361
* Node version: v14.15.5
* yarn version: 1.22.10
* Platform: macOS 11.2.3

### Additional context
Here is the info from the CRA about the `process.env.NODE_ENV` variable:
https://create-react-app.dev/docs/adding-custom-environment-variables/

**Comment by GiladShoham** [comment]
@davidfirst let's make it happen

**Comment by davidfirst** [comment]
@GiladShoham , @Mikilll94 it's easy to set it for `bit test`, but what about `bit build` which running not only test-task but also compile and other tasks? we probably don't want to set it to a specific ENV, as other tasks may expect something else.

**Comment by GiladShoham** [comment]
Bit build is indeed interesting case.
Maybe let the task somehow to control it?

**Comment by davidfirst** [comment]
Users tasks or future core tasks may rely on this env variable. Changing it during the process will make it hard to debug. 
What's the reason to change it to 'test'? what happens if it is not changed?
I'm also concern about CIs. They normally set their env to `ci` and other processes rely on it. Not sure what are the consequences of changing it during the command.

**Comment by Mikilll94** [comment]
@davidfirst 
This is a common convention in React, Vue (and probably also Angular) projects to set `NODE_ENV` variable to `development`, `test` or `production` based on the webpack build type.

CRA and Next.js follow this convention:
https://create-react-app.dev/docs/adding-custom-environment-variables/
![Screenshot 2021-05-05 at 11 13 39](https://user-images.githubusercontent.com/17653648/117119890-f4deba80-ad92-11eb-85fd-e15f547a0ad6.png)
https://nextjs.org/docs/basic-features/environment-variables#test-environment-variables

About your CI concerns:
CI tools do not change `NODE_ENV` variable. Instead they often add their own variable `CI` and i.e. CRA relies on this behavior:
https://create-react-app.dev/docs/running-tests/#continuous-integration

**Comment by davidfirst** [comment]
@Mikilll94 , sounds good. 
In my mind, this NODE_ENV helps to run different things for `development`, `staging` and `production` and changing this manually during the script can cause issues, but I might be wrong. 
@GiladShoham , do you want to just change it for `bit test` now? it's an easy change obviously.

**Comment by Mikilll94** [comment]
@davidfirst 
> In my mind, this NODE_ENV helps to run different things for development, staging and production

This is not true. The `NODE_ENV` variable tells you in what Webpack mode you are (and it is set by Webpack). In most cases you have only three Webpack modes: `development`, `test`, `production`. This variable is NOT used for some CI purposes like differentiating between `staging` and `production` build.
