### ISSUE TITLE
Cors Issue on bit.dev website

### ISSUE THREAD

**Issue by lokinder1** [teambit/bit#4127]
**when I try to use forgot password** following error comes on console

```
Access to XMLHttpRequest at 'https://api.bit.dev/user/password/forgot' from origin 'https://bit.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.bit.dev/user/password/forgot:1 Failed to load resource: net::ERR_FAILED

```
I can't even able to use 
`**bit login**`  command
by the terminal as I think the same issue is there also

**Comment by ocombe** [comment]
I can confirm the same bug when using signup, only on Firefox though, it works fine on Chrome (which could be a temporary workaround for you, if you're in fact using Firefox).

**Comment by guysaar223** [comment]
do you still have this error?

**Comment by lokinder1** [comment]
> I can confirm the same bug when using signup, only on Firefox though, it works fine on Chrome (which could be a temporary workaround for you, if you're in fact using Firefox).

for me, it was also on google chrome

**Comment by lokinder1** [comment]
> do you still have this error?

No, it's working fine now.
kudos to the team bit to solve it so fast

**Comment by ocombe** [comment]
Works fine for me now on Firefox too

**Comment by davidfirst** [comment]
Thanks for the update @ocombe , I'm closing the issue. 
@lokinder1 , please reopen if needed.
