### ISSUE TITLE
Can't create a component from a template

### ISSUE THREAD

**Issue by lcdss** [teambit/bit#4139]
### Description

The command `bit create react-component ui/card` is not working as expected on my system. It always display the error:

```
⠅⠀ loading bit...DateToPersist, paths-to-write:
/home/lcss/Projects/bit.dev-test/my-scope/ui/card/index.ts
/home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.tsx
/home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.composition.tsx
/home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.docs.mdx
/home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.spec.tsx
⢃⠀ running command create <templateName> <componentNames...>...writing a file to the file-system at /home/lcss/Projects/bit.dev-test/my-scope/ui/card/index.ts, force: true
writing a file to the file-system at /home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.tsx, force: true
writing a file to the file-system at /home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.composition.tsx, force: true
writing a file to the file-system at /home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.docs.mdx, force: true
writing a file to the file-system at /home/lcss/Projects/bit.dev-test/my-scope/ui/card/card.spec.tsx, force: true
got an error from command create <templateName> <componentNames...>: NoFiles
NoFiles
    at AddComponents.add (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/legacy/dist/consumer/component-ops/add-components/add-components.js:1030:15)
    at async Workspace.track (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/workspace/dist/workspace.js:872:20)
    at async ComponentGenerator.generateOneComponent (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/generator/dist/component-generator.js:143:24)
    at async /home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/generator/dist/component-generator.js:104:16
    at async pMapSeries (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/p-map-series/index.js:9:15)
    at async ComponentGenerator.generate (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/generator/dist/component-generator.js:95:29)
    at async CreateCmd.report (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/generator/dist/create.cmd.js:47:21)
    at async CommandRunner.runReportHandler (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/legacy/dist/cli/command-runner.js:169:20)
    at async CommandRunner.runCommand (/home/lcss/.bvm/versions/0.0.366/bit-0.0.366/node_modules/@teambit/legacy/dist/cli/command-runner.js:110:16)
user gets the following error: warning: no files to add, the following files were ignored: my-scope/ui/card
warning: no files to add, the following files were ignored: my-scope/ui/card
[*] the command create <templateName> <componentNames...> has been terminated with an error code 1
```
All I did was create the `bit.dev-test` directory, run `git init` and `bit init --harmony`.

### Specifications

- Bit version: 0.0.366
- Node version: 14.15.0

**Comment by davidfirst** [comment]
@lcdss , any chance you have `my-scope` in your `.gitignore` files?
I tried to reproduce the same steps, but it worked for me.

**Comment by lcdss** [comment]
@davidfirst I don't even have a .gitignore file. I also tried to use a different node version using `asdf` in a clean bit scope and got the same error.

**Comment by GiladShoham** [comment]
Which operating system and which terminal are you using?

**Comment by lcdss** [comment]
> Which operating system and which terminal are you using?

My OS is `Arch Linux`, the shell is `zsh` with `ohmyzsh` and `starship` and the nodejs was installed using `asdf`.

**Comment by davidfirst** [comment]
@lcdss , did it create the files?
If so, what happens when you run `bit add <created-dir>` ?

**Comment by lcdss** [comment]
@davidfirst It didn't create the files, only the directories (`myscope/ui`). I tried to use the add before and got the same `NoFiles` error with a different message.

I tried the [react tutorial](https://docs.bit.dev/docs/tutorials/bit-react-tutorial) and adapt it to use the harmony version, and it worked fine. After comparing the differences between the `bit.dev-test` and `bit-react-tutorial` I tried copying some files until it worked and the culprit was the .gitignore file (it could even be empty). If I delete it, the error returns.

**Comment by lcdss** [comment]
> @lcdss , so if you have the .gitignore file, even when it's empty, it works. Once you remove the file, you get the error of NoFiles.
> This is very odd. I'm trying to reproduce it again and again, with no luck.
> The only thing I can think of is that you have another .gitignore file upwards in the filesystem.
> Please try to create a new directory on `/tmp` and run the same steps there. I'm really curious if you could reproduce the issue there.

Yes, I do have a .gitignore file on my home directory that ignores everything except some specific files. The mystery is now finally solved.

**Comment by davidfirst** [comment]
The mystery is solved indeed :) @lcdss , thanks for the update.

For anyone else who visit this issue in the future, keep in mind that if you don't have .gitignore in your directory, it propagates upwards until the root and search for .gitignore file. (similar resolution algorithm of node-modules).
