### ISSUE TITLE
when adding a path in the variants in the workspace.jsonc with `"scopename/*":` it should throw an exception

### ISSUE THREAD

**Issue by odedre** [teambit/bit#4142]
### Describe the bug
I aded the following to the `ws.jsonc`

```
"teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "skeletons/*": {
      /**
       * uncomment to apply the react environment on all components.
       **/
      "teambit.react/react": {},
      }
    },
```

and it didnt work. the issue is that bit didnt throw an exception, just let me continue on my way.

### Steps to Reproduce
1. add a variant to the ws.jsonc with the format `"folderName/*":`
1. add a `defaultScope` to the section to the variant which is different than the default scope you have above 
1. in the folderName, create a component and run `bit add`
1. run bit show and see that it didnt override the scope name

### Expected Behavior
bit should throw and error telling me that its the wrong syntax

**Comment by GiladShoham** [comment]
I'll take care of this

**Comment by itaymendel** [comment]
stepping away from variants to better templates and programmatic apis instead of variants.
