### ISSUE TITLE
Bit fails to import my own private component

### ISSUE THREAD

**Issue by arghorashy** [teambit/bit#4144]
### Description

I'm trying to import my own private component, but I get an error message I'm not sure how to fix:
```
$ bit import arghorashy.shared/tooltip-manager --override

successfully ran npm install at /home/myname/sandbox/coding/project/components/tooltip-manager 

failed to link a component arghorashy.shared/replace-dom-children@0.1.0.
         Symlink (or maybe copy for Windows) from: /home/myname/sandbox/coding/project/src/replaceDOMChildren.ts, to: /home/afsheen/sandbox/coding/project/node_modules/@bit/arghorashy.shared.replace-dom-children/src/replaceDOMChildren.ts was failed.
         Original error: Error: ENOENT: no such file or directory, lstat '/home/myname/sandbox/coding/fieguthCache/src/replaceDOMChildren.ts'

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```
I tried running `bit doctor` as suggested, but it only suggests that I install yarn. I did this (`sudo apt-install yarn`; `npm install yarn`), but this doesn't change anything. I continue to get the error message above and subsequent runs of the doctor yield the same suggestion.

### Specifications

- Bit version: 14.8.8
- Node version: 13.12.0
- npm / yarn version: npm - 6.14.4
- Platform: Ubuntu

**Comment by GiladShoham** [comment]
Is there a chance you changed the case of the filename? Even one letter.
@davidfirst take a look. (keep in mind that this is v14)

**Comment by arghorashy** [comment]
I didn't change any file names, but maybe it's worth noting that my module names are camelCase. They always have been though. :/

**Comment by GiladShoham** [comment]
@davidfirst I saw this error happens for @ScriptedAlchemy as well sometime ago (with harmony). let's take a look and see what can cause this.

**Comment by davidfirst** [comment]
@GiladShoham , We made a huge change with the symlinks/hard-links recently, so not sure if this is reproducible on Harmony.

**Comment by GiladShoham** [comment]
unable to reproduce this issue.
If you can provide STR, please add them and re-open
