### ISSUE TITLE
babel/runtime/helpers/interopRequireDefault required when creating a custom Node environment

### ISSUE THREAD

**Issue by deleteman** [teambit/bit#4147]
### Describe the bug

When creating a customer Node environment and assigning it to a new component, the following package "babel/runtime/helpers/interopRequireDefault" seems to be missing. 
A manual installation fixes it, but it looks like an internal dependency that shouldn't be the responsibility of the user to fix.

### Steps to Reproduce

1. Create an empty folder
2.
```
git init
bbit init --harmony
bbit create node-env extensions/custom-node //extension gets created inside 'my-scope/extensions/custom-node'
```
3. 
//edit the workspace.jsonc file
```
//....
 "teambit.workspace/variants": {
    "my-scope/extensions/custom-node": {
      "teambit.harmony/aspect": {}
    },
  }
//....
```
4. Create an empty component inside 'my-scope/components/X' with main file being `index.ts`
5. Update `workspace.jsonc`:
```
  "teambit.workspace/variants": {
    "my-scope/extensions/custom-node": {
      "teambit.harmony/aspect": {}
    },

    "my-scope/components/validations": {
      "my-scope/extensions/custom-node": {}
    }
  }
```
6. Run `bbit env` 

### Expected Behavior
The list of components is shown with the correct environments configured.

### Screenshots, exceptions and logs
I get the following error:

```
Error: Cannot find module '@babel/runtime/helpers/interopRequireDefault'
    Require stack:
    - /Users/fernando.doglio/workspace/personal/writing/bits/bit-custom-env/custom-node1/node_modules/@my-scope/extensions.custom-node/dist/custom-node.extension.js
    - /Users/fernando.doglio/workspace/personal/writing/bits/bit-custom-env/custom-node1/node_modules/@my-scope/extensions.custom-node/dist/index.js
    - /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/workspace/dist/workspace.js
    - /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/workspace/dist/workspace.provider.js
    - /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/workspace/dist/workspace.main.runtime.js
    - /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/bit/dist/load-bit.js
    - /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/bit/dist/app.js
    - /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/bit/bin/bit
```

This error can be fixed running:

```
bbit install @babel/runtime/helpers/interopRequireDefault
```

### Specifications

- Bit version: 0.0.367
- Node version: v15.2.1
- npm / yarn version: npm 7.0.8
- Platform: osX 10.15.7
- Bit compiler (include version):
- Bit tester (include version):

**Comment by GiladShoham** [comment]
Can you please check if the error is gone if you run 
`bit install`
`bit compile`
`bit install`

Anyway I'll look into it

**Comment by deleteman** [comment]
@GiladShoham not gone, still happens after that

**Comment by AlexEBall** [comment]
I did a `bit install @babel/runtime` and that worked for me
