### ISSUE TITLE
Provide a better API to access build pipeline for node environments

### ISSUE THREAD

**Issue by deleteman** [teambit/bit#4148]
### Description
Currently, customer node environments don't have access to the `getBuildPipeline` method directly from the `NodeMain` class.  Instead, the `ReactEnv` and `ReactMain` dependencies need to be added to the custom node environment to access the list of build tasks.
This method is required to add a task to the build pipeline without overwriting the whole thing.

### Describe the solution you'd like
The following code should be valid:

```
export class CustomNodeExtension {
  constructor(private node: NodeMain) {}

  static dependencies: any = [EnvsAspect, NodeAspect]

  static async provider([envs, node ]: [EnvsMain, NodeMain]) {
    const pipeline = node.env.getBuildPipe()
    
    const tasks = [
      ...pipeline,
      new PrintCmpNameTask('extensions/custom-node', 'PrintCmpNameTask')
    ]

    const CustomNodeEnv = node.compose([
      node.overrideBuildPipe(tasks)
    ])
    envs.registerEnv(CustomNodeEnv)

    return new CustomNodeExtension(node)
  }
}
```

### Describe alternatives you've considered
However, right now we need to add the `ReactAspect` as dependency to our Node environment and use it to access the build pipeline. 

```
export class CustomNodeExtension {
  constructor(private node: NodeMain) {}

  static dependencies: any = [EnvsAspect, NodeAspect, ReactAspect]

  static async provider([envs, node, react]: [EnvsMain, NodeMain, ReactMain]) {
    const reactPipe = react.env.getBuildPipe()
    
    const tasks = [
      ...reactPipe,
      new PrintCmpNameTask('extensions/custom-react', 'PrintCmpNameTask')
    ]

    const CustomNodeEnv = node.compose([
      node.overrideBuildPipe(tasks)
    ])
    envs.registerEnv(CustomNodeEnv)

    return new CustomNodeExtension(node)
  }
}
```

**Comment by davidfirst** [comment]
@deleteman , I haven't tried it, but I don't see a reason why this: `const pipeline = node.env.getBuildPipe()` won't work.
The node env is a composition over React and it gets the same build-pipeline. 
Not sure if typescript won't complain, but I think the code supposed to work. 
Try to `console.log` the pipeline you get from node-env and paste it here.

**Comment by deleteman** [comment]
> @deleteman , I haven't tried it, but I don't see a reason why this: `const pipeline = node.env.getBuildPipe()` won't work.
> The node env is a composition over React and it gets the same build-pipeline.
> Not sure if typescript won't complain, but I think the code supposed to work.
> Try to `console.log` the pipeline you get from node-env and paste it here.

This is what I get if I try to do that:

```

The following errors were found while running the build pipeline
Failed task 1: "teambit.compilation/compiler:TypescriptCompiler" of env "teambit.harmony/aspect"
component: my-scope/extensions/custom-node
/Users/fernando.doglio/Library/Caches/Bit/capsules/b78513eefadefa0ad25e4d8bec58ca626a5a214a/my-scope_extensions_custom-node/custom-node.extension.ts:24:26 - error TS2551: Property 'env' does not exist on type 'NodeMain'. Did you mean 'envs'?

24     const pipeline= node.env.getBuildPipe()
                            ~~~

  /Users/fernando.doglio/.bvm/versions/0.0.367/bit-0.0.367/node_modules/@teambit/node/dist/node.main.runtime.d.ts:11:13
    11     private envs;
                   ~~~~
    'envs' is declared here.


Found 1 errors in 1 components


✖ Total 12 tasks. 3 succeeded. 1 failed. 8 skipped. Total errors: 1.
```

**Comment by davidfirst** [comment]
@deleteman , you need the `nodeEnv` prop, not `envs`.
So, it should be something like: `const pipeline= node.nodeEnv.getBuildPipe()`.
Unfortunately, there is no typescript completion for this because it's a manual composition. 
@GiladShoham , we should see how to fix it. Take a look into `node.env.ts` file, it has only one method `getDependencies`. Other methods are being copied during the composition from ReactEnv, so Typescript doesn't aware of them. 
If you try to use the `getBuildPipe()`, typescript complains that it doesn't exist.

**Comment by GiladShoham** [comment]
@davidfirst I think we can solve it by merging @ocombe interfaces for the envs somehow.

**Comment by itaymendel** [comment]
irrelevant with the introduction of new node env api here https://bit.cloud/teambit/node/node
