### ISSUE TITLE
playground is forever loading

### ISSUE THREAD

**Issue by conrado** [teambit/bit#4154]
### Describe the bug

When viewing a component the playground will not complete loading

### Steps to Reproduce

1. Pick any component to view details from on the page. eg. https://bit.dev/feathericons/react-feather/circle
1. Notice that the playground never finishes loading

### Expected Behavior

Expect to view a rendered demo of the component

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/77191/115394915-ac7fa400-a1b9-11eb-9078-0696b9fb3318.png)

### Specifications

tried this on Mac with Chrome and Safari

**Comment by GiladShoham** [comment]
fixed
