### ISSUE TITLE
Any attempt to export or remove components from my bit.dev collection results in a network error

### ISSUE THREAD

**Issue by tomssd** [teambit/bit#4160]
I receive this error when I try to export or remove anything from my collection:
**unexpected network error has occurred.  original message: this.index.filter is not a function**

Here is an example of my remove attempt:
bit remove ssd.synergy/my-comp --remote

**Comment by rozaorenda** [comment]
I have the same error  **this.index.filter is not a function** in many bit commands **'bit status'** **'bit comment'**  **'bit export'**. My bit version is 14.8.8

**Comment by tomssd** [comment]
I'm on bit version 14.8.8.

Initially, I composed/published a few components using Bit Harmony.  
There were compiler issues bringing these into new projects so I switched to legacy.

I have high hopes for moving my team onto this product but it has been a time killer.

**Comment by tomssd** [comment]
After attempting to remove the components using both legacy and Harmony, I was able to remove one of them.  I have 3 that I cannot remove by using any version.

**bit remove ssd.synergy/dynamic-form --remote**

ERROR: missing components (try to `bit untrack` them instead): ssd.synergy/dynamic-form

**Comment by rozaorenda** [comment]
I've also used bit harmony first and then switched to bit legacy. Maybe that is the reason we are getting 'this.index.filter is not a function' error.

**Comment by tomssd** [comment]
**BUG: Exporting a mix of legacy and Harmony components corrupts the bit.dev collection**

**I cannot export anything and I cannot remove 3 components 
(I have tried w/Harmony and Legacy)**

**Comment by rozaorenda** [comment]
I've asked on Bit.dev Slack channel, they said `try deleting the file in .git/bit/index.json (might be in .bit/index.json ) if it's not a git repo` Now some of my commands work, but` bit export ` still doesn't work. You may try deleting the file, maybe it will work for you.

**Comment by tomssd** [comment]
Thanks, rozaorenda - all of my testing on this is being done on small test React projects.  

I just made a fresh create-react-app project and built a new test component and I still can't export it. 

I'm stuck on the this.index.find... error.

**Comment by tomssd** [comment]
FWIW - here is my last attempt, w/bit doctor:
<img width="1068" alt="Screen Shot 2021-04-22 at 12 41 19 PM" src="https://user-images.githubusercontent.com/4312363/115752488-23f33600-a368-11eb-913d-a09004756245.png">

**Comment by itaymendel** [comment]
hi,

working with v14 and v15 on the same workspace is not supported. this might be the cause for these errors.
i would recommend using v15. if you have any compilation issues and need to change the base config to fit your requirements, please read more about [component development environments](https://harmony-docs.bit.dev/building-with-bit/environments).
