### ISSUE TITLE
Add command for uninstalling a dependency

### ISSUE THREAD

**Issue by tskovlund** [teambit/bit#4161]
### Description

bit lacks a command for uninstalling a dependency – the inverse of `bit install`.

### Describe the solution you'd like

`bit uninstall`. Running `bit install <package-name>` followed by `bit uninstall <package-name>` should leave the workspace and `node_modules` in the same state as not running any of the commands.

**Comment by sbland** [comment]
Is there any suggested workaround for this? What is the impact of running `npm uninstall <package_name>` ?

**Comment by tskovlund** [comment]
> Is there any suggested workaround for this? What is the impact of running `npm uninstall <package_name>` ?

Last time I checked, the workaround was

1. deleting `node_modules`, 
2. manually removing the dependency from `workspace.jsonc`, and
3. rerunning `bit install`. 

But it's been a while. Maybe @GiladShoham  should confirm.

**Comment by GiladShoham** [comment]
@zkochan is going to implement the uninstall command soon.

**Comment by zkochan** [comment]
`bit uninstall` was implemented via this PR: https://github.com/teambit/bit/pull/5091

For future improvements, I created this issue: https://github.com/teambit/bit/issues/5104
