### ISSUE TITLE
Error: Invalid ident

### ISSUE THREAD

**Issue by stevepepple** [teambit/bit#4172]
### Describe the bug

When running tag and other commands using bit Harmony, I see an issue like this: 

`Invalid ident (@design-system/components/card)`

I'm able to create and remove components without issue. 
The status for all components says "ok"
The `bit doctor ` command says everything is "ok"

A clear and concise description of the issue.

### Steps to Reproduce

1. Create workspace
1. Create or add component
1. Tag component

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 0.0.370
- Node version: v14.15.1
- npm / yarn version: yarn@1.22.10
- Platform: OSX
- Bit compiler (include version): `teambit.react/react` ? 
- Bit tester (include version):

**Comment by GiladShoham** [comment]
I don't think these steps to reproduce are really enough for reproducing it.
If you can check specific dependencies that cause this, and attach a workspace.jsonc for example.
Or even some tar file with a pre-made project that will be great.

**Comment by stevepepple** [comment]
I did a clean build and initialization of bit in the project with Yarn as the package manager, and this issue went away. I'm not sure what the problem was, but will provide greater detail if it happens again.

**Comment by itaymendel** [comment]
hi,

i'm closing the issue for now. if the error re-surfaces, please reopen.
i would recommend updating your local bit version, as we're constantly fixing issues :)
