### ISSUE TITLE
Type definition files are missing during component compilation

### ISSUE THREAD

**Issue by Boto1** [teambit/bit#4173]
### Describe the bug
During the compilation of two components, when component `A` uses component `B` for composition file and component `B` contains type definition file that is used for library interface augmentation, component `A` throws errors indicating that interfaces are not overrided in `A` composition file.

If to duplicate definition files into component `A`, it compiles without errors.
[project.zip](https://github.com/teambit/bit/files/6363065/project.zip)

### Steps to Reproduce
1. `bit install`
1. `bit compile`
1. `bit build`

### Expected Behavior
Errors should not be thrown

### Specifications
* Bit version: 1.0.50
* Node version: 14.16.1
* yarn version: 1.22.5
* Platform: linux
* Bit compiler (include version): 
* Bit tester (include version):

**Comment by GiladShoham** [comment]
@davidfirst We should look into it. we might need to fine tune the tsconfig

**Comment by itaymendel** [comment]
`bit compile` does not do `type-check` as this will slow down compilation a lot. either use `bit check-types` or have your IDE apply the configs from your env for its language services (for example `bit write-tsconfig`).
