### ISSUE TITLE
Add support for configuring automatic dependency range behaviour (save-prefix in npm lingo) of bit install

### ISSUE THREAD

**Issue by benjgil** [teambit/bit#4175]
### Description
When running `bit install`, current behaviour is to add the dependency to the dependencies list in workspace.json as a specific version number, e.g. "classnames": "2.2.6".

Often it is more useful to be able to define that the default entry will be with a version prefix, e.g. '^'.
With npm this is done via its config -> `save-prefix = "^"`. 

### Describe the solution you'd like
Allow a similar config for Bit's `dependency-resolver` extension, whereby a default prefix can be configured. 
Suggestion - use the same `save-prefix` config variable as with npm.

Bonus: Fetch that setting, where it exists, from the user's npm config in order to determine the user's default preference. This would then be overriden by any additional config for this variable inside the workspace.jsonc

### Describe alternatives you've considered
None

**Comment by GiladShoham** [comment]
@itaymendel any suggestion for the prop name?
