### ISSUE TITLE
Component created by using MDX template is not displayed correctly in "Overview" tab

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4192]
### Describe the bug
Component created using MDX template is not displayed correctly in "Overview" tab. In the "Compositions" tab it is displayed fine.

### Steps to Reproduce
1. Create a new component using `mdx-component` template.
1. Run `bit start`
1. Check how the component is displayed in the "Overview" tab.

![Screenshot 2021-04-27 at 18 22 11](https://user-images.githubusercontent.com/17653648/116292101-9e232080-a795-11eb-9270-dbf3068a6343.png)

As you can see, it is displayed incorrectly.

### Expected Behavior
Component should look like this:
![Screenshot 2021-04-27 at 18 24 24](https://user-images.githubusercontent.com/17653648/116292191-b4c97780-a795-11eb-8c5c-85f365fe0653.png)

### Specifications
* Bit version: 0.0.375
* Node version: v14.15.5
* yarn version: 1.22.10
* Platform: macOS 11.2.3

**Comment by KutnerUri** [comment]
triage:

The compositions is showing the default styles: the browser build-in styles for `h1`, `h2`, etc.

In the docs, we use `css-reset` to undo the browser styles, so the `h1` is not bold, etc.
--> We should find a less aggressive `css-normalizer` that will not reset the browser defaults.

as for the centering, we use `display: flex` on the composition card to center it.
mdx components seems to start with a `React.fragment`, so it is flattened by the flex.
--> We could fix it by adding a <div> when children is an array / fragment.

**Comment by debs-obrien** [comment]
In the compositions tab it is styled correctly only if there is one composition. If you add another composition it loses its styling altogether and you end up with an ugly looking composition and it means it is not consistent as when you add a new composition it seems like you broke the first composition.

<img width="342" alt="CleanShot 2021-04-28 at 16 21 46@2x" src="https://user-images.githubusercontent.com/13063165/116419985-daaa5700-a83d-11eb-88e6-cf26f9e2f885.png">

**Comment by ranm8** [comment]
@KutnerUri can we somehow make sure reset.css is not applied there? why do we need this?

**Comment by KutnerUri** [comment]
@ranm8 we added it to get rid of the browser default styles. I would like to remove it and replace it with the less aggressive `css-normalizer`.

We would have to check it on some MDX examples to make sure we don't break existing previews.
I think @odedre has a couple of examples ready.

**Comment by KutnerUri** [comment]
Closed by #4506.
- Removed reset-css in docs and compositions (might add `css-normalizer` if needed)
- Centered compositions without applying flex.
- Same centering in live playground :)

@Mikilll94 - FYI
