### ISSUE TITLE
Material-ui Theme not being picked up by installed components

### ISSUE THREAD

**Issue by SC7639** [teambit/bit#4203]
### Describe the bug
Components that are dependencies of imported components and installed don't pick up on the custom theme via the material ui `ThemeProvider`. The components in the original project they were exported from work with the custom theme and the theme was exported as a component as well and is installed.

A clear and concise description of the issue.

### Steps to Reproduce

1. Export a component that depends on other exported components
2. Import the component
3. Try to apply a custom theme using material ui's `ThemeProvider`

### Expected Behavior

Both sets of components should have the theme applied

### Screenshots, exceptions and logs

Image 1 is the new project and image 2 is the component with the same theme in the composition that was added in the original project using the same exported theme component
![image](https://user-images.githubusercontent.com/6049560/116582804-a1411c80-a90d-11eb-82f5-5a7aa3d00296.png)
![image](https://user-images.githubusercontent.com/6049560/116582835-a69e6700-a90d-11eb-9916-abc81923b4a5.png)

### Specifications

- Bit version:  1.0.68 (bit doctor) / 0.0.376 (`bit -v`)
- Node version: 14.15.2
- npm version: 6.14.9
- Platform: linux

**Comment by SC7639** [comment]
Another piece of the puzzle that lead me to my solution was:
I think I may have found something that would explain it https://stackoverflow.com/a/59822428/1315571 tldr; if a component isn't using the same @material-ui instance then it won't get the theme. From what I can see in the node_modules/.pnpm it looks like it has its own version, is it possible to tell those components to import from the @metarial-ui used in the node_modules folder?

**Comment by SC7639** [comment]
I already found a solution and @GiladShoham asked me to open a github issue with the problem and solution.
The solution I came up with is to use the `customize-cra` package and alias `@material-ui` to `node_modules/@material-ui`  using the below in `config-overrides.js` file.

```js
const {
    override,
    addWebpackAlias,
} = require("customize-cra");
const path = require("path")
​
module.exports = override(
    (config) => {
        return addWebpackAlias({
            '@material-ui': path.resolve("./node_modules/@material-ui")
        })(config);
    },
)
```

**Comment by itaymendel** [comment]
awesome !
closing this issue. see [this note](https://github.com/teambit/bit/issues/4203#issuecomment-829378380) for resolving the issue.

**Comment by SC7639** [comment]
Another note for this issue if you are using react ssr with material ui, you need to do a similar thing with babel build of components. I fixed it with `module-resolver` plugin (see the below example of `.babelrc`.

```json
{
    "presets": [
        "@babel/reset-react"
    ],
    "plugins": [
        [
            "module-resolver",
            {
                "alias": {
                    "@material-ui": "/app/node_modules/@material-ui"
                }
            }
        ]
    ]
}
```

Then you need to run something similar to the below for your bit components in node_modules
```sh
npx babel node_modules/@{organization}/ --out-dir node_modules/@{organization}/ --config-file {.babrc} --extensions ".js"
```
