### ISSUE TITLE
Using CRA works fine with yarn start but fails on build. (Playing around with Harmony)

### ISSUE THREAD

**Issue by trentis** [teambit/bit#4207]
### Description
You can find the repository I am currently using here https://github.com/vorteil/direktiv-ui under the branch 'use-bit'.

When running with yarn start everything seems to work fine and run properly. But when attempting to make a production build I end up getting the following errors.

```sh
Attempted import error: '@vorteil/direktiv-ui.dashboard-page' does not contain a default export (imported as 'DashboardPage').
```

I feel like it has something to do with webpack as I can change the import to @vorteil/direktiv-ui.dashboard-page/index and it seems to pick it up fine. The other solution is overriding the config file like so

```js
//config-override.js
const webpack = require('webpack')
const path = require('path')
const { babelInclude, override, addExternalBabelPlugins, addWebpackPlugin, addBabelPresets, addWE } = require("customize-cra");
    
// handle importing from bit.dev
module.exports = override(
    babelInclude([
        path.resolve("src"),
        path.resolve("node_modules/@vorteil")
    ]),
    ...addBabelPresets(
        [
            "@babel/preset-env", {modules: "commonjs", loose: true}
        ],
    ),
    ...addExternalBabelPlugins(
        "@babel/plugin-syntax-jsx",
        "add-module-exports",
        "syntax-dynamic-import"
    ),
    addWebpackPlugin(
        new webpack.ProvidePlugin({
            "React": "react",
         }),
    )
);
```

Will build a production build fine but it obviously doubles the size of my bundle. So I'm wondering if I am configuring the bit compiler wrong for webpack to intepret. 

Sorry if this seems a bit to all over the show, like they say I have my coding brain on right now. I have a feeling its nothing to do with Harmony and Im just misusing other things to try get what I want. But hopefully you have some ideas.

### Specifications
* Bit version: 0.0.377
* Node version: v16.0.0
* npm / yarn version:  v1.22.10
* Platform: Ubuntu
* Bit compiler (include version): Using the default react thing from the workspace.jsonc
* Bit tester (include version): no testing yet

### Context and additional information
A simple webapp that I want to reuse components for in a different project.

**Comment by GiladShoham** [comment]
Try changing the import to import * as DashboardPage from...

**Comment by trentis** [comment]
I changed it to the following.

```javascript
import * as DashboardPage from '@vorteil/direktiv-ui.dashboard-page'
import * as EventsPage from '@vorteil/direktiv-ui.events-page'
import * as InstancePage from '@vorteil/direktiv-ui.instance-page'
import * as JQPlaygroundPage from '@vorteil/direktiv-ui.jqplayground'
import * as SettingsPage from '@vorteil/direktiv-ui.settings-page'
import * as WorkflowsPage from '@vorteil/direktiv-ui.workflows-page'
import * as WorkflowPage from '@vorteil/direktiv-ui.workflow-page'
```

But I still need to provide the route component with a default which can be done like so 

```js
 <Route exact path="/:namespace" component={DashboardPage.default} />
```

But then I end up in the same problem again unfortunately. Shouldn't it work the way I previously had it? Especially if I'm exporting default.

**Comment by trentis** [comment]
I downgraded back to legacy it seems to run fine now. But thats basically because im not forced to import in this repository. Feel free to close or I can help debug later on. There is a slight issue where the bundle size is still double when importing bit components and I'm trying to work out why in the legacy version.

**Comment by GiladShoham** [comment]
If you can provide a minimal repo/branch with only 1-2 components I would take a look on this.

**Comment by trentis** [comment]
Sorry, I must've missed this message been busy working away. Ill try to come up with something on the weekend to with minimal components and easy to reproduce.

**Comment by GiladShoham** [comment]
@trentis 
do we have a minimal steps to reproduce this?

**Comment by itaymendel** [comment]
stale issue. closing. if we can reproduce, lets reopen.
