### ISSUE TITLE
Harmony version with self-hosting remote

### ISSUE THREAD

**Issue by moshekrup** [teambit/bit#4213]
### Description

Hi,

I try to use harmony version with self-hosting remote and I can't find any doc about it, is it supported?

Thanks

### Specifications

- Bit version: 0.0.377
- Node version: v12.20.0
- Yarn 1.22.10

**Comment by itaymendel** [comment]
hi,

Yes it does.
Please see the dockerfile and instructions here - https://github.com/teambit/bit-docker
