### ISSUE TITLE
Yarn add won't install package

### ISSUE THREAD

**Issue by enoent4400** [teambit/bit#4229]
### Describe the bug

When running ```yarn add @bit/mui-org.material-ui.slider``` as per docs I get following error ```yarn add v1.22.10
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@bit%2fmui-org.material-ui.slider: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/filip/Projects/web-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.```

### Steps to Reproduce

1. GOTO https://bit.dev/mui-org/material-ui/slider (I also tried with different packages - ex. https://bit.dev/primefaces/primereact/slider) 
2. Run installation command via yarn in your project
3. Watch the result

### Expected Behavior

Component should be added inside my project.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 14.8.8
- Node version: v14.16.1
- npm / yarn version:1.22.10
- Platform:MacOS

**Comment by itaymendel** [comment]
hi, you need to set bit.dev as a package registry in your npmrc.
see reference here - https://docs.bit.dev/docs/installing-components#configuring-bit-registry
