### ISSUE TITLE
Bit Harmony: Composition break for React Native components having uses of react-native-svg

### ISSUE THREAD

**Issue by yarahemant** [teambit/bit#4230]
### Description

**I am using bit harmony.**

I created one component in react native that basically accept svg images path and render corresponding svg image in UI. I name it for eg: Icon. Now the same component I am using in my button component to show the icon in button. I created composition for my Icon component but it break. Here is the error log:

`ERROR in ./node_modules/react-native/Libraries/Image/resolveAssetSource.js 18:12
Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const AssetSourceResolver = require('./AssetSourceResolver');
|
> import type {ResolvedAssetSource} from './AssetSourceResolver';
|
| let _customSourceTransformer, _serverURL, _scriptURL;
 @ ./node_modules/react-native-svg/lib/module/LocalSvg.js 1:1802-1860
 @ ./node_modules/react-native-svg/lib/module/ReactNativeSVG.js 1:8462-8483
 @ ./node_modules/react-native-svg/lib/module/index.js 1:317-344
 @ ./src/components/Icon/Icon.tsx 12:0-35 176:46-49
 @ ./src/components/Icon/Icon.composition.tsx 8:0-38 10:42-50
 @ ./node_modules/.cache/bit/teambit.preview/preview/teambit.react/react-native/__compositions-1620206154874.js 6:19-130
webpack compiled with 1 error
Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
See https://webpack.js.org/concepts#loaders
| const AssetSourceResolver = require('./AssetSourceResolver');
|
> import type {ResolvedAssetSource} from './AssetSourceResolver';
|
| let _customSourceTransformer, _serverURL, _scriptURL;
ModuleParseError: Module parse failed: Unexpected token (18:12)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
See https://webpack.js.org/concepts#loaders
| const AssetSourceResolver = require('./AssetSourceResolver');
|
> import type {ResolvedAssetSource} from './AssetSourceResolver';
|
| let _customSourceTransformer, _serverURL, _scriptURL;
    at handleParseError
(/Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/webpack/lib/NormalModule.js:891:19)
    at /Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/webpack/lib/NormalModule.js:992:5
    at processResult
(/Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/webpack/lib/NormalModule.js:718:11)
    at /Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/webpack/lib/NormalModule.js:778:5
    at /Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/loader-runner/lib/LoaderRunner.js:406:3
    at iterateNormalLoaders
(/Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/loader-runner/lib/LoaderRunner.js:232:10)
    at Array.<anonymous>
(/Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/loader-runner/lib/LoaderRunner.js:223:4)
    at runCallbacks (/Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/webpack/node_modules/enhanced-res
olve/lib/CachedInputFileSystem.js:27:15)
    at /Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/webpack/node_modules/enhanced-resolve/lib/Cache
dInputFileSystem.js:200:4
    at /Users/hemant_sain/.bvm/versions/0.0.376/bit-0.0.376/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)`

### Specifications

- Bit version:
```
current (used) bvm version: 0.0.20
latest available bvm version: 0.0.20

current (used) bit version: 0.0.376
latest installed bit version: 0.0.376
latest available bit version: 0.0.379
```

- Node version: v14.11.0
- npm / yarn version: [npm: 6.14.8, yarn: 1.22.5]
- Platform: MacOs

**Comment by JoshK2** [comment]
Hi @yarahemant , I remember that I solved this issue on Slack in our channel, but I'll write the solution again.

The issue is with the component compositions and not with the component itself, because you use “react-native-svg” library in your component and then you try to render it via a composition file.
The issue is because this library use native API's, so components that are using this library cannot be rendered on the web, because the Native API's are unavailable.
One way to solve it is to see if the library have a support for Web and update your code to be also Web compatible.
The second way to solve this is to search for a parallel library with Web support and make a Webpack aliases in a Bit React Native extension inside your project, and then configure this extension to make Webpack alises. 
 
If for some reason a library don’t have it’s parallel library for the web and don’t have a built in support, you can’t make the preview working on the local Bit dev server.

In this case I found “react-native-svg-web”, so after I [created a React Native extension](https://harmony-docs.bit.dev/aspects/teambit.react/react-native/react-native/#create-an-extension), I make a Webpack aliases like this:
```
//webpack/webpack-transformer.ts
import {
  WebpackConfigTransformer,
  WebpackConfigMutator,
  WebpackConfigTransformContext,
} from '@teambit/webpack';

/**
 * Transformation to apply for both preview and dev server
 * @param config
 * @param _context
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function commonTransformation(
  config: WebpackConfigMutator,
  _context: WebpackConfigTransformContext,
) {
  // Merge config with the webpack.config.js file - adding handlebars support
  // config.merge([webpackConfig]);
  config.addAliases({
    'react-native-svg': require.resolve('react-native-svg-web'),
    'react-native-web': require.resolve('react-native-web'),
  });
  return config;
}

/**
 * Transformation for the preview only
 * @param config
 * @param context
 * @returns
 */
export const previewConfigTransformer: WebpackConfigTransformer = (
  config: WebpackConfigMutator,
  context: WebpackConfigTransformContext,
) => {
  const newConfig = commonTransformation(config, context);
  return newConfig;
};

/**
 * Transformation for the dev server only
 * @param config
 * @param context
 * @returns
 */
export const devServerConfigTransformer: WebpackConfigTransformer = (
  config: WebpackConfigMutator,
  context: WebpackConfigTransformContext,
) => {
  const newConfig = commonTransformation(config, context);
  return newConfig;
};
```

And then import it in the main file of the extension:
```
//react-native.extension.ts
import {EnvsMain, EnvsAspect} from '@teambit/envs';
import {ReactNativeAspect, ReactNativeMain} from '@teambit/react-native';
import {
  previewConfigTransformer,
  devServerConfigTransformer,
} from './webpack/webpack-transformers';

export class CustomReactNativeExtension {
  constructor(private reactNative: ReactNativeMain) {}

  static dependencies: any = [EnvsAspect, ReactNativeAspect];

  static async provider([envs, reactNative]: [EnvsMain, ReactNativeMain]) {
    const CustomReactNativeEnv = reactNative.compose([
      /*
        Use any of the "reactNative.override..." transformers to
      */
      reactNative.useWebpack({
        previewConfig: [previewConfigTransformer],
        devServerConfig: [devServerConfigTransformer],
      }),
    ]);

    envs.registerEnv(CustomReactNativeEnv);

    return new CustomReactNativeExtension(reactNative);
  }
}
```

The last thing is to update the `workspace.jsonc` to use the extension and also to have the dependencies of the parallel library I used, in this case the following dependencies are needed for `react-native-svg-web`:
```
//workspace.jsonc
"teambit.workspace/variants": {
    "*": {
      "NAME.SCOPE/extensions/custom-react-native": {}
    },
    "extensions/custom-react-native": {
      "teambit.harmony/aspect": {},
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "dependencies": {
            "react-native-svg-web": "1.0.9",
            "react-native-web": "0.16.2",
            "prop-types": "15.7.2"
          }
        }
      }
    }
  }
``` 

I hope this will help other users.
