### ISSUE TITLE
bit checkout doesn't work for some files ("overridden")

### ISSUE THREAD

**Issue by JGJP** [teambit/bit#4236]
### Describe the bug

sometimes when checking out component changes with `bit checkout` some files don't get updated, and then show up as modified when executing `bit status`

### Steps to Reproduce

1. unclear, seems to be random, but when rerunning the command after an instance of this error, the same files seem to be affected. It seems to be regardless of file type or directory.

### Expected Behavior

All files are properly updated

### Screenshots, exceptions and logs

<img width="158" alt="Screen Shot 2021-05-06 at 15 19 46" src="https://user-images.githubusercontent.com/3692190/117250948-f08fcb80-ae7e-11eb-9c3e-b55750d9cd02.png">

### Specifications

- Bit version: 14.8.8
- Node version: 14.15.5
- yarn version: 1.22.4
- Platform: MacOS

**Comment by davidfirst** [comment]
@JGJP , not sure if you're working also with Harmony version, but many things were changed in how files are overridden during `bit checkout`. 
This is probably not going to be fixed the legacy version. If you get the same issue on Harmony, please update here.

**Comment by JGJP** [comment]
@davidfirst thanks for your reply. A few points:

1. was there supposed to be some kind of notification for this Harmony release? I have not received any email and can't see anything on this repo regarding legacy status
2. I'm not able to migrate ever, as Harmony seems to force component files to all be in one directory. Also I don't really know how to reproduce the error
3. I was hoping for at least some background on what this "overridden" dynamic is for, and why it might be appearing here
4. as a paid service, dropping support with no advance notification and not even a (non-beta) successor is quite a bad look, IMO
5. if Harmony is so different, I think it should be in a different repo, so at least users who can't or don't want to migrate can submit PRs here

**Comment by itaymendel** [comment]
I'd like to provide some context regarding Bit v14 and v15.

First of all, regardless of the version used, we'll need some steps to reproduce, to look into it. Bit v14 is still supported for bug-fixes etc, but not for new features.
If not steps to reproduce, can you share more information/logs/workflow so we can look into it?

There is still ongoing support for v14. v15 is not yet published on mailing lists etc, as there are some APIs missing and features left to implement (mainly angular/vue support). However, as it stands, for React/Node developers, its a far superior product, as we got to change some of the decisions we made 4-5 years ago in the design of Bit.
