### ISSUE TITLE
Unable to export component from a react project

### ISSUE THREAD

**Issue by amol9372** [teambit/bit#4263]
### Description

I am trying to export a component from an **existing react project** after updating the code. I tagged the component. When I tried to export the project it is giving me the below error
 
codeit@purgatory:~/react/radio-reactive/counter-app$ bbit export

**failed finding an object file required by Version object, originated from Component amol9372.reactuicomponents/ui/button
path: /home/codeit/react/radio-reactive/counter-app/.bit/objects/4d/9586bf5e2267b010ebdffd54203be5945f9113**

I guess this is something to do with version

Note : I am able to export it from a react-workspace ( **bit new react-workspace <my-project-name>** )

### Specifications

- Bit version: 0.0.386
- Node version:  v14.16.1
- npm / yarn version: 7.12.0
- Platform:  WSL 2
- Bit compiler (include version): react
- Bit tester (include version): 

### Context and additional information

These are the commands i ran in the existing react project:

-  bbit import amol9372.reactuicomponents/ui/components
-  bbit export  amol9372.reactuicomponents
-  bbit export 

I tried will all combinations of bbit export, it is not working

**Comment by davidfirst** [comment]
@amol9372 , what do you mean by

>  I guess this is something to do with version
 
Is it possible to attach a reproducible project?

**Comment by amol9372** [comment]
> @amol9372 , what do you mean by
> 
> > I guess this is something to do with version
> 
> Is it possible to attach a reproducible project?

@davidfirst This is my sample [project](https://github.com/amol9372/radio-reactive/tree/master/counter-app)  where i tried it and it did not work

**Comment by davidfirst** [comment]
@amol9372 , you mentioned that your bit version is 0.0.386, but this project seems to be legacy. Are you trying to migrate from the legacy to Harmony by any chance?

Regarding the error you get, it's related the objects in your `.bit` directory, which I don't have.
I ran `bit import` and got version 0.0.1, which doesn't include the missing object in the error message above, which lead me to think that it was a local tag 0.0.2. 
Not sure what went wrong with this local 0.0.2 tag. My suggestion is to delete the objects (`.bit` dir), edit the `.bitmap` file and change the version to 0.0.1. Then run `bit import` to get the objects back. 
Once done, try to re-tag and export.

**Comment by amol9372** [comment]
@davidfirst thanks a lot man
I was using `bit init` on my react workspace where I was importing the component but `bit init --harmony` was required since my bit.dev component worspace was also initialized with harmony
