### ISSUE TITLE
vue3 issues

### ISSUE THREAD

**Issue by jerryliang613** [teambit/bit#4265]
### Specifications
* Bit version: 14.8.8
* Node version: 16
* npm / yarn version: 7.10
* Platform: windows
* Bit compiler (include version): vue@0.1.13
* Bit tester (include version): 

### Context and additional information
Hi there,
I start to try bit on my vue3 project recently. I followed the tutorial on bit website. And got error message as follows:

Vue packages version mismatch:

* vue@3.0.11 (C:\Users\Jerry\AppData\Roaming\npm\node_modules\vue\index.js)
* vue-template-compiler@2.6.12 (C:\Users\Jerry\AppData\Roaming\npm\node_modules\bit-bin\node_modules\vue-template-compiler\package.json)

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

Really appreciate if you can provide some advice. cheers

**Comment by itaymendel** [comment]
vue3 is not supported at the moment.
sadly we do not have eta for its availability.

closing the issue.
