### ISSUE TITLE
Bit not respecting authToken in .npmrc

### ISSUE THREAD

**Issue by jayjetley** [teambit/bit#4276]
### Describe the bug
When an _authToken is set in the .npmrc file this is not respected by the bit install/bit tag commands.

### Steps to Reproduce
1. Publish private package to npm
1. Add token to .npmrc to access token. ```//registry.npmjs.org/:_authToken=${NPM_TOKEN}```
1. Use yarn or npm to install the private package - this should work as expected
1. type bit install to install all of the bit dependencies - this will fail with 404 error on the private package.

### Expected Behavior
Should install the package from npm

### Specifications
* Bit version:  0.0.389
* Node version: 14.15.1
* yarn version: 1.22.10
* Platform: OSX

**Comment by GiladShoham** [comment]
This is a result of when using bit install, once bit see the default registry is npmjs it will send the request to node.bit.dev and then proxy from there to npmjs.
In order to support private bit components, bit will use bit token for this request (taken from @bit in npmrc or from the bit global config under user.token)
So when coming to npmjs it will come with the bit token instead of npmjs token.
to solve this, we need to send the npm original token in a separate header in the request, and once proxing to npmjs use this token.

**Comment by GiladShoham** [comment]
@itaymendel we should discuss the product for this.
In general, I would like a way to set a token for my org/user for each scoped registry in bit.dev UI.

**Comment by itaymendel** [comment]
i don't fully understand why you'd want that @GiladShoham 
`npmrc` already supports managing multiple registries as a client. i know that by default bit-install does does everything via node.bit.dev. can we add a config to bit-install that as a client it can use multiple registries?

**Comment by jayjetley** [comment]
@itaymendel the use case for this is migrating from NPM to Bit. We have components that we are moving to Bit but are reliant on other components that are currently in a private NPM repo. Whilst we will ultimate move everything over to Bit it will make the project more difficult and also more like a big bang release rather than an iterative process. In non-bit projects you are correct but it is the bit component libraries that are causing the issue.

**Comment by GiladShoham** [comment]
Also if not moving all to bit eventually, it's a valid use case to have private npm packages on npmjs (like fortawesome) so you need a way when proxying from bit.dev registry to npmjs registry to provide a token

**Comment by oconnorjoseph** [comment]
> Also if not moving all to bit eventually, it's a valid use case to have private npm packages on npmjs (like fortawesome) so you need a way when proxying from bit.dev registry to npmjs registry to provide a token
^ This. My company wants use the same private dependencies in Bit that we use elsewhere in our codebase.

**Comment by seisenreich** [comment]
So, has anybody found a workaround for this? 
It could take a while for bit to implement this if they even consider implementing this requested feature.

I'm currently moving many components we want to share between multiple projects to a bit workspace, but we widely use fontawesome pro.
All components using this dependency can't be added to our bit scope at the moment. 
That's a big deal.

**Comment by itaymendel** [comment]
npmrc supports a single main "registry", but you get to use "scoped registries".
with this in mind, what we suggest is using this capability and have npm resolve bit componetns form a scoped registry, and that's it.
besides that, if you have fortawesome, they have their own scoped-registry settings, which means this will be supported, as npm (and bit) will resolve deps from there.

as for self-hosted solutions like artifactory and others, you can use them to cache/proxy for bit components, as shows here https://jfrog.com/blog/artifactory-your-npm-registry-for-bit/
