### ISSUE TITLE
need help, when run bit export, computer memory comusmed another 9G, it is werid

### ISSUE THREAD

**Issue by nelsonkent** [teambit/bit#4286]
### Describe the bug
when run bit export, computer memory comusmed another 9G, it is werid
I have put two mainly files below, thanks for your support.

### Specifications

    Bit version: 14.8.8
    Node version: 14.16.0
    npm / yarn version: 6.14.11
    Platform: mac
    Bit compiler (include version): bit.envs/compilers/react@2.0.0
    Bit tester (include version):

### Screenshots, exceptions and logs
package.json
`
{
  "name": "map-web-library",
  "version": "1.3.20",
  "description": "export react components for website managed by cms",
  "author": "china team",
  "license": "MIT",
  "repository": "china team/map-web-library",
  "main": "dist/components/index.js",
  "module": "dist/components/index.js",
  "source": "components/index.js",
  "engines": {
    "node": ">=10"
  },
  "scripts": {
    "build": "microbundle-crl --no-compress --format modern,esm",
    "start": "microbundle-crl watch --no-compress --format modern,esm",
    "prepare": "run-s build",
    "test": "run-s test:unit test:lint test:build",
    "test:build": "run-s build",
    "test:lint": "eslint .",
    "test:unit": "cross-env CI=1 react-scripts test --env=jsdom",
    "test:watch": "react-scripts test --env=jsdom",
    "predeploy": "cd example && yarn install && yarn run build",
    "deploy": "gh-pages -d example/build"
  },
  "peerDependencies": {
    "axios": "^0.19.0",
    "react-redux": "^7.2.2",
    "@emotion/react": "^11",
    "@emotion/styled": "^11",
    "@material-ui/core": "^4.11.3",
    "lodash": "^4.17.20",
    "react": "^16.10.1",
    "react-dom": "^16.10.1",
    "react-router-dom": "^5.2.0",
    "styled-components": "^5.2.1"
  },
  "dependencies": {
    "@bit/mik-technology.core.button": "^1.0.5",
    "@bit/mik-technology.core.centered-wrapper": "^1.0.0",
    "@bit/mik-technology.core.heading": "^1.0.0",
    "@bit/mik-technology.core.text": "^1.0.3",
    "@bit/mik-technology.core.theme": "^1.0.0",
    "@chakra-ui/react": "^1.5.0",
    "@emotion/react": "^11"
  },
  "devDependencies": {
    "@ant-design/icons": "^4.4.0",
    "@babel/core": "^7.13.10",
    "@babel/plugin-syntax-jsx": "^7.12.13",
    "@babel/preset-react": "^7.12.13",
    "@paciolan/remote-component": "^2.11.0",
    "@reduxjs/toolkit": "^1.5.0",
    "@tabler/icons": "^1.39.1",
    "@tinymce/tinymce-react": "^3.10.4",
    "animate.css": "^3.7.2",
    "array-move": "^3.0.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.13.3",
    "braft-editor": "^2.3.8",
    "co-busboy": "^1.4.1",
    "cross-env": "^7.0.3",
    "customize-cra": "^0.8.0",
    "device-uuid": "^1.0.4",
    "echarts": "^4.4.0",
    "framer-motion": "^3.3.0",
    "fs": "^0.0.1-security",
    "gh-pages": "^3.1.0",
    "husky": "^3.0.9",
    "js-cookie": "^2.2.1",
    "less": "^4.1.1",
    "less-loader": "5.0.0",
    "lint-staged": "^9.4.2",
    "microbundle": "^0.13.0",
    "microbundle-crl": "^0.13.11",
    "moment": "^2.29.1",
    "node-sass": "^4.13.0",
    "npm-run-all": "^4.1.5",
    "nprogress": "^0.2.0",
    "prettier": "^2.2.1",
    "prettier-eslint": "^12.0.0",
    "public-ip": "4.0.3",
    "react-app-rewired": "^2.1.8",
    "react-beautiful-dnd": "^13.0.0",
    "react-device-detect": "1.15.0",
    "react-draggable": "^4.4.3",
    "react-dropzone-uploader": "^2.11.0",
    "react-highlight-words": "^0.17.0",
    "react-loadable": "^5.5.0",
    "react-lz-editor": "^0.12.1",
    "react-rnd": "^10.2.4",
    "react-scripts": "^3.2.0",
    "react-slick": "^0.28.0",
    "react-sortable-hoc": "^1.11.0",
    "screenfull": "^5.0.0",
    "shortid": "^2.2.16"
  },
  "files": [
    "dist"
  ],
  "bit": {
    "env": {
      "compiler": "bit.envs/compilers/react@2.0.0"
    },
    "componentsDefaultDirectory": "components/{name}",
    "packageManager": "yarn"
  }
}

`

entrance index.js
`
import './index.css';
import ServiceContent from './pub/ServiceContent/ServiceContent';
import CategoryBanner from './pub/CategoryBanner/CategoryBanner';
import Inspirations from './pub/Inspirations/Inspirations';
import MakerSpotlight from './pub/MakerSpotlight/MakerSpotlight';
import MichaelsFamily from './pub/MichaelsFamily/MichaelsFamily';
import Name from './pub/Name/Name';
import NormalCards from './pub/NormalCards/NormalCards';
import PixleeWidget from './pub/PixleeWidget/PixleeWidget';
import Product from './pub/Product/Product';
import RecentlyViewed from './pub/RecentlyViewed/RecentlyViewed';
import Project from './pub/Project/Project';
import Sliders from './pub/SliderMichaels/SliderMichaels'
import TrendingNow from './pub/TrendingNow/TrendingNow'
import BannerAds from './pub/BannerAds/BannerAds'
import Btn from './pub/Btn/Btn'
import CategoryPage from './pub/CategoryPage/CategoryPage'
import CategorySetting from './pub/CategorySetting/CategorySetting'
import ClassesAndEvents from './pub/classesAndEvents/ClassesAndEvents'
import DragAndDrop from './pub/DragAndDrop/DragAndDrop'
import EABanner from './pub/EABanner/EABanner'
import FirstFigure from './pub/firstFigure/FirstFigure'
import GetInspired from './pub/getInspired/GetInspired'
import HalfPictureAndWord from './pub/halfPictureAndWord/HalfPictureAndWord'
import MakerExperience from './pub/MakerExperience/MakerExperience'
import MarketPlaceBanner
  from './pub/MarketplaceBanner/MarketplaceBanner'
import TextDialog from './pub/TextDialog/TextDialog'
import VideoCard from './pub/VideoCard/VideoCard'
import Word from './pub/Word/Word'
import Card from './pub/Card/Card';
import GridComponent from './pub/Grid/Grid';
import FeaturedProjects from './pub/FeaturedProjects/FeaturedProjects';
import FAQ from './pub/FAQ/FAQ';
import Coupon from './pub/Coupon/Coupon';
import MarketplaceBanner from './pub/MarketplaceBanner/MarketplaceBanner';
import SearchBar from './pub/SearchBar/SearchBar';
import SearchProject from './pub/SearchProject/SearchProject';

const components = {
  CategoryBanner: CategoryBanner,
  Inspirations: Inspirations,
  MakerSpotlight: MakerSpotlight,
  MichaelsFamily: MichaelsFamily,
  Name: Name,
  NormalCards: NormalCards,
  PixleeWidget: PixleeWidget,
  Product: Product,
  RecentlyViewed: RecentlyViewed,
  Project: Project,
  Service: ServiceContent,
  Sliders: Sliders,
  TrendingNow: TrendingNow,
  BannerAds: BannerAds,
  BtnComponent: Btn,
  CategoryPage: CategoryPage,
  CategorySetting: CategorySetting,
  ClassesAndEvents: ClassesAndEvents,
  DragAndDrop: DragAndDrop,
  EABanner: EABanner,
  FirstFigure: FirstFigure,
  GetInspired: GetInspired,
  HalfPictureAndWord: HalfPictureAndWord,
  MakerExperience: MakerExperience,
  MarketPlaceBanner: MarketPlaceBanner,
  TextDialog: TextDialog,
  VideoCard: VideoCard,
  WordComponent: Word,
  Card: Card,
  Coupon: Coupon,
  MarketplaceBanner: MarketplaceBanner,
  SearchBar: SearchBar,
  SearchProject: SearchProject,
  FAQ: FAQ,
  Grid: GridComponent,
  FeaturedProjects: FeaturedProjects,
};
export default components;

`

**Comment by davidfirst** [comment]
@nelsonkent , about the two files, not sure I'm following. Did you add those two files to one component? 
I saw that you opened another issue: https://github.com/teambit/bit/issues/4285 did you get that error with this export after it consumed 9GB ?

**Comment by nelsonkent** [comment]
tks, I do think these might be related, but when i run into JavaScript heap out of memory, i set NODE_OPTIONS=--max_old_space_size=9000 , it works for about three times before the error #4285 occurred
