### ISSUE TITLE
"Properties" table displays props for nested React components

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4292]
### Describe the bug
The "Properties" table displays props for nested React components.

Let's imagine a scenario that your Bit component called X contains another React component Y. In this case the "Properties" table will display props for component Y. This is wrong behavior. It should display props for component X.

### Steps to Reproduce
1. Create a Bit component X which contains React component Y.
1. Add some props to component Y.
1. Start Bit local server.
1. Look at the "Properties" table. It displays props for component Y.

### Expected Behavior
In the "Properties" table only props for the root component in the workspace should be displayed.

### Screenshots, exceptions and logs
Here is a repro project:
[bit-repro.zip](https://github.com/teambit/bit/files/6488915/bit-repro.zip)

After downloading project, run:

```
bit install
bit start
```

In the "Properties" table, you should see this:
![Screenshot 2021-05-16 at 10 46 09](https://user-images.githubusercontent.com/17653648/118391308-ee263200-b633-11eb-91c0-4dc91d0a1f28.png)

which is wrong. Instead "someProp" from `TestComponent.tsx` file should be displayed.

### Specifications
* Bit version: 0.0.394
* Node version: v14.15.5
* npm / yarn version: n/a
* Platform: macOS 11.2.3

**Comment by itaymendel** [comment]
sadly react-docgen does not support it. we've added an "api-ref" tab for components with this capability.
please re-export your components to have bit build that new api ref for your components.
