### ISSUE TITLE
Cannot find module 'react' when running tests

### ISSUE THREAD

**Issue by Mikilll94** [teambit/bit#4293]
### Describe the bug
After running `bit install` , React package is not present inside node_modules although it is listed in the peer dependencies when running `bit show`. This causes unit tests to crash.

![Screenshot 2021-05-16 at 12 47 40](https://user-images.githubusercontent.com/17653648/118395530-3270fc80-b64b-11eb-9cc0-0d4e48114aaf.png)

### Steps to Reproduce
1. Download this repro project:
[bit-repro.zip](https://github.com/teambit/bit/files/6489125/bit-repro.zip)
1. Run

```
bit install
bit start
```

1. Check the "Tests" tab for "my-comp" component

### Expected Behavior
There should be no error in tests.

### Specifications
* Bit version: 0.0.394
* Node version: v14.15.5
* Platform: macOS 11.2.3

**Comment by isoadro** [comment]
I had the same issue. Ended up needing to use the `bit` CLI to install `react` and `react-dom` as peer dependencies. Honestly not sure if this is the "correct" way to fix this issue, but it did help me.

```
bit install react --type peer
bit install react-dom --type peer
```

**Comment by GiladShoham** [comment]
I'm aware of this issue.
It's a result of the way we resolve the dependencies provided by the env.
I'm going to rewrite this entire layer soon, in a completely different way.
As part of this refactor I will solve this issue as well.

Something else that is coming and kind of address this issue in some way is the `bit new` command which give you a way to create workspaces from templates. then we will have a template for react apps, which will already have those deps configured in the workspace.jsonc as part of the template.

**Comment by itaymendel** [comment]
part of #5349 work. closing this issue
