### ISSUE TITLE
import package from scope to another local scope while modifying it's scope name and source code

### ISSUE THREAD

**Issue by bdei** [teambit/bit#4321]
### Description
let say I have a bit workspace and 2 local scopes defined within in, in scope 1 I'm creating base components, in scope 2 which is 
business specific app, I want to be able import component A from scope 1 to this more specific scope (2), then change newly imported component (package) scope to scope of 2, modify it's source code to my needs then, can export it as new modified component under name of scope 2, and use it inside scope 2, or export it as scope 2 component, ,
is this possible ? 

### Specifications
* Bit version: 14.8.8
* Node version: 14
* npm / yarn version: 14
* Platform: windows
* Bit compiler (include version): 
* Bit tester (include version):

**Comment by itaymendel** [comment]
you can't have two instances of an imported component in the same app.
if you want, you can `bit rename` or `bit fork` when you want to move components between scopes.
