### ISSUE TITLE
Components are not built in bit.dev

### ISSUE THREAD

**Issue by Pareder** [teambit/bit#4339]
### Description
Following your [React tutorial](https://docs.bit.dev/docs/tutorials/bit-react-tutorial) some bug with build task in [bit.dev](https://bit.dev/) appeared. It shows a warning "Note: your component has no build task defined!", but I have imported the react compiler and I can build the component locally. Also it is worth to mention that after importing this component to some other project it has `dist` folder with built bundle.

### Specifications
* Bit version: 14.8.8
* Node version: 14.15.4
* npm / yarn version: 1.22.10 (yarn)
* Platform: Ubuntu 18.04
* Bit compiler (include version): bit.envs/compilers/react@1.0.30
* Bit tester (include version): -

### Context and additional information
React version in this example is 16.8.6, that's why I chose 1.0.30 version of compiler.
No other steps were produced, only tutorial steps.

**Comment by rubenofen** [comment]
Same here

**Comment by nicolas-rohricht** [comment]
The same happened to me.
is there any solution?

**Comment by itaymendel** [comment]
hi, please follow the updated docs / tutorial here - https://harmony-docs.bit.dev

**Comment by legendar** [comment]
@itaymendel 
is there any roadmap for harmony version?  we plan to use bit for react and vue components. but harmony only supports react for now.
so need to understand when harmony will suports vue?

**Comment by afanan** [comment]
Same too, did you solve it?

**Comment by Pareder** [comment]
Hi, @afanan. I don't know whether it is solved on Bit side, but I switched to Harmony version, it works good.

If you were planning to use one Bit collection for React and Vue components, for example, it is better to create two separate collections: Harmony for React and Legacy for Vue.
