### ISSUE TITLE
bit for Angular - Module not found

### ISSUE THREAD

**Issue by YihongGao** [teambit/bit#4352]
### Description
I follow[ tutorials for bit for angular](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial), and upload to bit.dev, But I got an error message like below.
`ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@bit/yihonggao.angular-tutorial-v2.product-list' in '/capsule/src/app'
ℹ ｢wdm｣: Failed to compile.` 

I tried few solution, But I not got lucky. also got same error message.

### Specifications
* Bit version: 14.8.8
* Node version: v15.14.0
* npm / yarn version: 7.7.6
* Platform: Mac M1, Windows 10
* Bit compiler (include version): bit.envs/compilers/angular@9.0.11 or LTS
* Bit tester (include version):
* bit.dev componet Link: [product-list](https://bit.dev/yihonggao/angular-tutorial-v2/product-list)
* Angular CLI: 11.0.6
* @angular-devkit/architect          0.1100.6
* @angular-devkit/build-angular      0.1100.6
* @angular-devkit/build-ng-packagr   0.1002.0
* @angular-devkit/core               11.0.6
* @angular-devkit/schematics         11.0.6
* @angular/cli                       11.0.6
* @schematics/angular                11.0.6
* @schematics/update                 0.1100.6
* rxjs                               6.6.3
* typescript                         4.1.3`
### Tried:
1. Did tutorials on Windows 10 and Mac M1
1. Use diff version bit.envs/compilers/angular
1. Use other tutorials project from google search

### Repo:
[Gitlab](https://gitlab.com/testlab26/bit-angular-tutorial)

**Comment by YihongGao** [comment]
If my question lost the any important information, tell me pls

**Comment by solangeDev** [comment]
I have this error, is there a solution?

**Comment by TomTronchet** [comment]
Hello,
I just started to use bit.dev with angular, and I was getting the same error.
The reason was siple for me, I created the collection in bit.dev but by default it use 'Bit Harmony open beta' type collection, but my local bit version is v14 and bit harmony does not support angular.

So try to remove and create your collection and clicking Bit 14 Legacy then follow the tutorial it should be working.

**Comment by ocombe** [comment]
bit harmony does support angular now with https://github.com/teambit/bit-angular/, it's still in beta though (but bit harmony as well)

**Comment by Jeremias-Nater** [comment]
just searched for file upload with angular on bit, all of the 5 results have errors like "Module not found: Error: Can't resolve '@bit/". Definetely not gonna use bit but i reccommend you to fix this

**Comment by GiladShoham** [comment]
@Jeremias-Nater 
I'm really sorry you feel this way.
And I really recommend using the new harmony version.
The legacy version is 2 years old and does not get the same attention as the harmony one.
I'm sure that using harmony you will get a much better experience, and much more features and stability.

**Comment by SaadFarhanIdress** [comment]
I am experiencing this problem with React.
Here is the [scope](https://bit.dev/saadfarhanidress/react-tutorial).

**Comment by itaymendel** [comment]
closing this issue.
for using bit-harmony with angular, please follow this link - https://github.com/teambit/bit-angular/
the issue at the top refers to legacy version of Bit. we rewrote the bit-angular flow.
