### ISSUE TITLE
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react-native"

### ISSUE THREAD

**Issue by EtheveDamien** [teambit/bit#4357]
It looks like this [issue](https://github.com/teambit/bit/issues/4261)

### Description
I using a react-native component into another react-native component. When I add a `*.docs.mdx` or `*.composition.tsx` file, it causes this error when I tried to build or tag :

```bash
✖ env: teambit.react/react-native, task "teambit.preview/preview:GeneratePreview" has failed
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 6 tasks (completed in 5s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react-native"
component: my-scope/ui/item
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-native' in '/home/${my_name}/Library/Caches/Bit/capsules/2ff4ba9a7ec3d44d8839b8821f3dd38a6b39267b/my-scope_ui_item-list/dist'
```

#### Setup the workspace
1. Create an empty folder 
1. Inside the folder use your terminal to run `bit init --harmony`
1. In the generated workspace.jsonc uncomment `"teambit.react/react": {}` and rename it as `"teambit.react/react-native": {}`. Make sure to save file.

```json
"teambit.workspace/variants": {
    "*": {
      "teambit.react/react-native": {}
    }
  }
```

#### Create basic react-native components
1. create my-scope/ui/item component 

```ts
// index.ts
export { Item } from './item';
```

```tsx
// item.tsx
import React from 'react';
import { View, Text } from 'react-native';

type Props = {
    text?: string;
};
  
export const Item = ({text}: Props) => {
    return (
        <View>
            <Text>{text}</Text>
        </View>
    );
};

Item.defaultProps = {
    text : "hello item"
}
```

At this point if you run :

* `bbit add my-scope/ui/item --namespace ui`
* `bbit install`
* `bbit compile`
* `bbit build` or `bbit tag --all 0.0.1`  (it works)

1. create my-scope/ui/item-list component 

```ts
// index.ts
export { ItemList } from './item-list';
```

```tsx
// item-list.tsx
import React from 'react';
import {FlatList} from 'react-native';
import {Item} from '../item';

type ItemListProps = {
  data: Array<object>;
};

export const ItemList = ({data}: ItemListProps) => {
  const renderItem = ({item}) => {
    return <Item text={item.name} />;
  };

  return <FlatList data={data} renderItem={renderItem} />;
};

ItemList.defaultProps = {
  data: [
    {
        id: '1',
        name: 'first',
    },
    {
        id: '2',
        name: 'Bob',
    },
    {
        id: '3',
        name: 'marie',
    },
    {
        id: '4',
        name: 'Foo',
    },
  ]
}
```

At this point if you run :

* `bbit add my-scope/ui/item-list --namespace ui`
*  `bbit status` > say to run `bbit link --rewire` so run it.
* `bbit compile`
* `bbit build` or `bbit tag --all 0.0.1`  (it works)

#### The problem
Now create the ui/item/item.docs.mdx and import the Item component.

```
---
labels: ['extension', 'react-native', 'env', 'environment']
description: 'A customized extension for React environment.'
---

import {Item} from './item'; // this line make it failed ! 

This is a customized extension for ReactNative, based of the [ReactNative Aspect](https://bit.dev/teambit/react/react-native).

Explain here the modified configurations and tools applied.

```
Try to run `bbit build`. It will fail and give the following error.

note that it will make the same error if I put a composition file.

### Screenshots, exceptions and logs
This is the `bbit build` output
![image](https://user-images.githubusercontent.com/25502363/120181959-d0092600-c21e-11eb-8bca-bcb396f5150b.png)

This is `bbit env` output
![image](https://user-images.githubusercontent.com/25502363/120182854-02675300-c220-11eb-9a8a-39d21c9578e3.png)

This is `bbit show ui/item` output
![image](https://user-images.githubusercontent.com/25502363/120182996-29be2000-c220-11eb-9dd0-8cb39e94f6e5.png)

This is `bbit show ui/item-list` output
![image](https://user-images.githubusercontent.com/25502363/120183056-3f334a00-c220-11eb-8c6f-6ebc271cdd25.png)

### Expected Behavior
`bbit build` and `bbit tag` should works to allow me to export my interrelated react-native components.

### Specifications
* Bit version: 0.0.408
* Workspace type: harmony
* Node version: v14.17.0
* npm version: 6.14.13
* yarn version: 1.22.10
* Platform: Ubuntu 18.04.2 LTS

Thanks for any help !

**Comment by excelerator-doe** [comment]
I have the same error

**Comment by JoshK2** [comment]
Hi, I tried to reproduce the issue, and everything is working good.
I made only one change, replace this:
`import {Item} from '../item';`
with this:
`import { Item } from '@my-scope/ui.item';` 
This is the module path, it's based on the `defaultScope` param in the workspace.jsonc file.

All the commands run with success, and also `bit build`:
![image](https://user-images.githubusercontent.com/35892475/136022503-eae420ff-88bd-48f7-b61c-a18a8bb6f24f.png)

But the error you get is related to missing dependencies, so it's not related to the change I make.
Your error was probably fixed in a higher version from what you're using.
Please try again with the newest version, the one that I used for this is `0.0.518`.
You can upgrade your Bit version using bvm:
https://harmony-docs.bit.dev/getting-started/installing-bit#upgrading-bit
