### ISSUE TITLE
Can I start the BIT project locally and debug the whole process

### ISSUE THREAD

**Issue by 273403986** [teambit/bit#4371]

**Comment by GiladShoham** [comment]
Yes. Definitely.
But let us know which exact part you want to debug so we can better guide you.
There is local workspace, bits client and remote scope (bit server).

**Comment by 273403986** [comment]
Can the functionality of the online IDE be debugged

**Comment by 273403986** [comment]
Or how is the component preview done on bit.dev, and does this process exist in the bit source code

**Comment by davidfirst** [comment]
You can run `bit start` on your workspace or your local scope and see the components in the browser.
During the tag command the preview files are generated and saved into the objects. You can try debugging this process by adding some breakpoints inside the preview.task.ts file and running `bit build` or `bit tag`.
