### ISSUE TITLE
Bit component not embedding images correctly.

### ISSUE THREAD

**Issue by jayjetley** [teambit/bit#4372]
### Describe the bug
When embedding an image in a React component the image (png or jpeg) is not available to the rendered component. The can be seen when using compositions in the bit.dev portal, although interestingly it does work with SVGs.

This is on the Harmony platform.

### Steps to Reproduce
1. Add a png or jpeg to an assets folder in the component
1. import the image in to the component using standard React format ```import myImage from './assets/my-image.png';```
1. Use the imported image ```<img src={myImage} />```
1. Export the component

### Expected Behavior
The image should render within the component.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/6815220/120606932-9b2be780-c447-11eb-941d-8d98607c1c75.png)

### Specifications
* Bit version: 0.0.404
* Workspace type: harmony
* Node version: 14.15.1
* yarn version: 1.22.10
* Platform: OSX

### Additional context
I have added a small repo the replicates the issue (it is private so let me know if you need access)

https://github.com/jayjetley/bit-component-with-image

**Comment by GiladShoham** [comment]
Please give me permission to the  repo. Also is this happening during bit start as well or only after export on the remote scope?

**Comment by jayjetley** [comment]
@GiladShoham when running locally it fails on the SVG with a no loaders error. I have given you access to the repo.

**Comment by jayjetley** [comment]
@GiladShoham this still seems to be broken when deploying to the remote site (we are using bit.dev hosting). Locally it now works correctly but the deployed version is still showing a broken image.
