### ISSUE TITLE
Following the Harmony tutorial results in errors

### ISSUE THREAD

**Issue by Znert** [teambit/bit#4378]
## Expected Behavior
Following the tutorial at https://harmony-docs.bit.dev/ on a clean machine should work.

## Actual Behavior
Starting the application with `bit start` results in compile errors:

```
Module parse failed: Unexpected token (5:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| export const BasicButton = () => (
>   <Button text="hello from Button" />
| );
| 
```

```
Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
| description: 'A Button component.'
| labels: ['label1', 'label2', 'label3']
ModuleParseError: Module parse failed: Assigning to rvalue (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> ---
```

## Steps to Reproduce the Problem
1. Start a docker container with node installed. I used VS Code Remote Container to try bit. This step may be optional.
1. Follow the steps in the tutorial:
    1. Download `bvm`: `npm i -g @teambit/bvm`
    1. Install bit: `bvm install`
    1. Add to $PATH: `echo 'export PATH=$HOME/bin:$PATH' >> ~/.bashrc && source ~/.bashrc`
    1. Create a new workspace:  `bit new react-workspace bit-of-luck && cd bit-of-luck`
    1. Install: `bit install`
    1. Create components: `bit create react-component ui/button` (And install dependencies from tutorial: `bit install @testing-library/react`
    1. Start bit: `bit start`
1. The build will fail with the aforementioned errors.

It seems like something is missing, some webpack configuration or similar. I tried to solve the issue following an older issue https://github.com/teambit/bit/issues/1225, but the solution may be outdated. Calling `bit import bit.envs/compilers/webpack --compiler` tells me that I should update bit, but everything is up to date.

On a side note: I noticed that calling `bit doctor` results in a failed validation (all other pass): 

```
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ core               │ validate bit version            │ validate that bit version is up to date                │ failed ║
╚════════════════════╧═════════════════════════════════╧════════════════════════════════════════════════════════╧════════╝
```

## Specifications
* Bit version: 0.0.409 according to `bit --version`
* Node version: v16.0.0
* npm / yarn version: 7.10.0
* Platform: linux/Docker
* Bit compiler (include version): How do I check?
* Bit tester (include version): How do I check?

**Comment by debs-obrien** [comment]
Hi @Znert Thank you for the detailed issue. Very helpful. I just ran as per what you have above and it all works perfect on my computer ;)

Can you try with a lower node version. I am using v14.16.0
Always best to use LTS of Node rather than current. Can you please check if downgrading Node helps and let me know.

thanks so much

**Comment by Znert** [comment]
I changed to version 14, but still get the same error. 

But since it is working for you, it might has something to do with the Docker environment? Or maybe a global library missing?

I used the default NodeJS setup as preconfigured by VS Code. Can you try to do the same? The steps to do should be roughly as follows:
1. Install VS Code & open an empty folder (to create all Docker related files in)
2. Install the Remote Development extension: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack (see also https://code.visualstudio.com/docs/remote/containers)
3. Press Ctrl+Shift+p and search for "reopen in container"
4. Select NodeJS, then the version you want to try
5. Now follow the tutorial

**Comment by dspacejs** [comment]
This worked for me:

```sh
rm -rf node_modules
bit install
```

Not sure what the problem was. I just had to reinstall the dependencies.

**Comment by benjgil** [comment]
For anyone seeing this - please ensure you have run `bit compile` at least once on new components before trying to run the dev server (`bit start`)
