### ISSUE TITLE
Wanting to customise Eslintrc

### ISSUE THREAD

**Issue by LiamWalshWeb** [teambit/bit#4382]
We're new adopters of the Bit.dev Harmony platform and getting our teeth stuck into building stuff using this great platform. We were following the instructions for setting up a custom React env and noticed that customising the `.eslintrc` has not been implemented yet.

Is there a timeline on when this is likely to be implemented? If it's unlikely to happen in the short term is there a recommended workaround? Forking and building out the functionality ourselves is an option but unsure about how to distribute the `bit` cli based on that fork our local dev environment.

https://github.com/teambit/bit/blob/ae841872817b55d54b9fba9b054551a6133d233c/scopes/react/react/react.main.runtime.ts#L251

**Comment by GiladShoham** [comment]
I'll try to put it in my list for next week. can't promise but I'll do my best to push it.

**Comment by LiamWalshWeb** [comment]
@GiladShoham thanks so much for the reply. I'm trying to setup to contribute locally as well 👍

**Comment by LiamWalshWeb** [comment]
@GiladShoham I've been having trouble setting up the repository locally myself to work on this. Has there been any movement on this ticket?

**Comment by davidfirst** [comment]
@LiamWalshWeb , did you try following the setup described here: https://github.com/teambit/bit/blob/master/CONTRIBUTING.md ? 
If so, at what step did you get stuck?

**Comment by LiamWalshWeb** [comment]
@GiladShoham yeah I was following the Contributing docs but simply can't get past the `npm run full-setup`. I get this error log:
![image](https://user-images.githubusercontent.com/4707277/122188771-33828d00-ce88-11eb-9c2b-c1afc398ec4e.png)

I have Yarn installed locally so not sure what the problem is? I have the Bit cli command installed will that be causing problems maybe?

**Comment by GiladShoham** [comment]
Interesting,that was a bug we faced few days ago as a result of wine interal dependencies updated by yarn.
You shouldn't get it anymore.
Anyway, 
@davidfirst lets add full-setup:bit which is same as full-setup:bbit but with bit.
And instruct people to first install bvm and install bit using it  then run the full-setup:bit

**Comment by davidfirst** [comment]
Done. https://github.com/teambit/bit/pull/4437.

**Comment by LiamWalshWeb** [comment]
> Done (the full-setup:bit). Merged. #4437.

That's fixed the local setup for me 👍 thank you

**Comment by LiamWalshWeb** [comment]
A question on this one @davidfirst and @GiladShoham with a custom React environment setup for development, how can we tie in our VSCode/code editor settings so that when we're writing code our preferences are automatically applied on format save etc? Most extensions tend to just pickup config files at the root of the project but if they're further down the tree we don't get that benefit.

I can't see anywhere in the docs regarding this. We want to improve the general linting/testing/dev experience 👍

**Comment by GiladShoham** [comment]
There is no very good way to do it.
I think the best way to do it is to put eslint config on the root and only say it extends the one from the custom env.
There are some drawbacks with this for example if you have components with other envs which means with other rules you will have to add eslint config inside those components folders which extends the correct one.
But it should cover most of the cases.
I plan to check if the vscode extensions api has a way to do it everything programmatically so you won't have to deal with it. But it will take some time for me to get into it

**Comment by GiladShoham** [comment]
Also if you need any help with the implementation, both me and david are highly available on the community slack. Feel free to ask questions.
Thanks!

**Comment by LiamWalshWeb** [comment]
Just an update on this one @GiladShoham I've been struggling to get the environment to work fully locally and I haven't been able to prioritise this as an item in our workload to get done. Would you be able to carry this on?

**Comment by GiladShoham** [comment]
@LiamWalshWeb 
Just implement this :)
See this pr - https://github.com/teambit/bit/pull/4575
Example project - https://github.com/teambit/custom-eslint-config

It should be merged in about an hour, and will be part of the next version (in 15 hours, or less)

**Comment by FNLuzko** [comment]
> There is no very good way to do it. I think the best way to do it is to put eslint config on the root and only say it extends the one from the custom env. There are some drawbacks with this for example if you have components with other envs which means with other rules you will have to add eslint config inside those components folders which extends the correct one. But it should cover most of the cases. I plan to check if the vscode extensions api has a way to do it everything programmatically so you won't have to deal with it. But it will take some time for me to get into it

Hello, how can i achieve this?
i want to to have my custom eslintrc file and import it, in order to be able to configure vscode format on save, aligned with what `bit lint` command is throwing
