### ISSUE TITLE
Bit on Windows is unresponsive

### ISSUE THREAD

**Issue by ianef** [teambit/bit#4390]
### Describe the bug
After downloading Bit for Windows, copying it to C:\bit, renaming the file to bit.exe, adding the folder path to the PATH variable, starting a new command prompt, verifying that the path exists, and trying to run _bit_ it does nothing.

### Steps to Reproduce
1. Download Bit for Windows.
1.  Copy it to C:\bit, renaming the file to bit.exe.
1. Add the folder path to the PATH variable.
1. Start a new command prompt, verifying that the path exists, and trying to run _bit_, it does nothing.

### Expected Behavior
Some output to verify it's working, say _bit --version_

### Screenshots, exceptions and logs
Here is a log of absolutely no response from bit, bit is the last entry in the path:

```
C:\Users\Ian>echo %path%
C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Git\cmd;C:\Program Files\PuTTY\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\Azure Data Studio\bin;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Users\Ian\AppData\Local\Microsoft\WindowsApps;C:\Users\Ian\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Azure Data Studio\bin;C:\Users\Ian\.dotnet\tools;C:\bit;

C:\Users\Ian>bit --version

C:\Users\Ian>bit are-you-there

C:\Users\Ian>bit do-you-exist

C:\Users\Ian>echo Clearly NOT!
Clearly NOT!

C:\Users\Ian>bit

C:\Users\Ian>ren C:\bit bit-x

C:\Users\Ian>bit
'bit' is not recognized as an internal or external command,
operable program or batch file.

```

Just to prove that bit.exe was running I renamed the folder to force an error.

### Specifications
* Bit version:
* Workspace type: (harmony/legacy)
* Node version:
* npm / yarn version:
* Platform:

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
I would like to reference my rant regarding using Bit on WSL2, this is a total mess and you seriously need to address the Windows and WSL issues if you want developers to use this technology.
https://github.com/teambit/bit/issues/2848

**Comment by itaymendel** [comment]
hi @ianef ,
first of all, i see you are frustrated, but use a more productive title. there are many teams that use Bit on windows for building and sharing components. if you have specific issues, make sure to have the title of your issue descriptive.

i don't understand where you seen these install instructions for Bit.

[follow this guide to install bit on your system.](https://harmony-docs.bit.dev/getting-started/installing-bit)

**Comment by ianef** [comment]
Hi @itaymendel, many thanks for responding and yes I'm deeply frustrated with what potentially could be a very useful service.

I have changed the title although I did think it was very appropriate, it is useless!

The installation methods are from your online documentation: [](https://docs.bit.dev/docs/installation#windows)
BTW I've also tried running it as *Administrator* and it is still useless.

**Comment by itaymendel** [comment]
yes, you are correct. vue is not yet supported in v15, i had no idea this was the case.
sadly vue support in v14 is also somewhat lacking, as there's no support for vue3 yet and there are issues with the SSR mechanism for Nuxt based apps.

I'm trying to reproduce your issue on a windows machine. Can you please share some details on the windows/node versions? i see this is missing in the original post.

**Comment by ianef** [comment]
Hi @itaymendel, I hadn't originally installed node as I don't need it in Windows, all my development is carried out in WSL, hence using the Windows exe download.

Yesterday I installed node and npm and then ran through the bit login and bit config get process and it worked.

This is however a painful process as I didn't need node or npm in Windows, in fact the only reason I needed it was to get the token because bit login does not work on a headless system. You need to fix this! You already have the ability to login when exporting components so why should we have to through all of this to download what we uploaded earlier using a login?

So after all this pain I could eventually download and test out my components to complete the cycle. Guess what? they didn't work! Your Vue compiler is doing something weird and webpack creates a different loading pattern for them compared to all the other node modules I use. It then crashes because the export function it expects to be there is undefined. See here: [](https://app.slack.com/client/TCC321BHR/CCDHG0TPY)

Sadly I think I'm going to have to abandon using bit, with Vue it is just too painful and buggy.
