### ISSUE TITLE
Add --nojs flag

### ISSUE THREAD

**Issue by stephan-devop** [teambit/bit#4399]
### Description
We are using the bit command line tool (and bit.dev repos) but we are not using it for JavaScript code. But bit assumes we are using JavaScript code and does a lot of "housekeeping" (like creating node_modules directory and index.bit and package.json files). Some of the actions can be prevented with command line flags but there are a lot of those flags and still not all of the "JavaScript" behavior can be disabled.

### Describe the solution you'd like
Add a --nojs flag which disables all JavaScript related features.

### Describe alternatives you've considered
We have written (_porcelain_) wrapper functions (see [takelage documentation](https://github.com/geospin-takelage/takelage-doc/blob/main/doc/tau/bit.md)) but of course we have to use the (_plumbing_) bit commands often. Especially to enter the merge hell.

### Additional context
This is only about the open-source bit command line tool. We do not ask you to remove any features just to add a way to disable the JavaScript related features easily. We know that bit is mostly a JavaScript tool and we do not want to change that. But there is more to bit and we ask you to make it easier to access the full potential for people outside the JavaScript world. There's a bit more to it.

**Comment by itaymendel** [comment]
at this point bit is aimed at the js/ts eco system. in the future we aim to support additional platforms.
closing this issue.
