### ISSUE TITLE
error "React.CSSProperties is incompatible" when building in capsule

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4401]
I'm seeing type errors like this for our link and nav-link components.

```
Type 'React.CSSProperties | undefined' is not assignable to type
'import("/home/circleci/bit/bit/node_modules/@types/react-router/node_modules/@types/react/index").CSSProperties | undefined'.
...
Types of property 'rubyPosition' are incompatible.
```

I think it's a conflict between the types of `react` and `react-router`/`react-router-dom`.
`@types/react-router-dom` is already latest (5.1.7), so I don't see a quickfix.

I'm seeing that `@types/react-router-dom` has a dependency on `"@types/react": "*"`.
I'm suspecting Bit is incorrectly handling `"*"` as semver, and therefor installs another instance of `@types/react`.
is it possible?

For now I added `@ts-ignore` to these two components.

### Specifications
* Bit version: 0.0.413
* Workspace type: harmony
* npm / yarn version: Yarn
* Platform: MacOS

**Comment by itaymendel** [comment]
can't reproduce.
