### ISSUE TITLE
bit install / compile needs to be run twice because of envs

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4407]
When running `bit install`, install doesn't run correctly in the first install when workspace contains envs.

This is because the env itself effects the install process. So, as bit tries to load them during the first install, we get this error:

```
symphony-bbit git/master
❯ rm -rf node_modules yarn.lock

symphony-bbit git/master  23s
❯ bit install
✖ error: unable to load the extension "teambit.symphony/envs/node@0.0.5", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.symphony/envs/node@0.0.5", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.symphony/envs/aspect@0.0.8", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.symphony/envs/node@0.0.5", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.symphony/envs/symphony-react@0.0.12", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.symphony/envs/aspect@0.0.8", please use the '--log' flag for the full error.
  Resolving component dependencies for workspace: 'symphony'
✔ all objects were processed and written to the filesystem successfully
  installing dependencies in workspace using teambit.dependencies/pnpm
```

This also happens during `bit compile`. To work around this, I use this script:

```bash
bit install &&	# install without the envs
bit compile &&	# compile the envs
bit compile &&	# compile all components
bit install &&	# install with the envs, node_modules are updated
bit compile		# compile all correctly
```

It's long and cumbersome, but it works correctly.
Can we get a more direct solution?

### Specifications
* Bit version: 0.0.413
* Workspace type: harmony
* npm / yarn version: yarn
* Platform: MacOS

**Comment by davidfirst** [comment]
@KutnerUri , are you sure you need to run `bit compile` twice? I remember fixing it. When bit is loaded it checks whether an env is not loaded and if so, it tries to compile it.
About `bit install`, I see your point. @GiladShoham , maybe we can check whether the components have the "missing-dist" issue and if so run the compilation for them. 
Seems like we're getting more and more requests of auto-compile the components in many scenarios, maybe we should think about different approaches here.

**Comment by KutnerUri** [comment]
no, I'm getting the `unable to load extension` error when I run `bit compile`:
```
symphony git/master*  211s
❯ bit compile
✖ error: unable to load the extension "teambit.accounts/aspects/accounts-service@0.0.34", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.scopes/aspects/exporter@0.0.77", please use the '--log' flag for the full error.
✖ error: unable to load the extension "teambit.scopes/aspects/scope-graph@0.0.17", please use the '--log' flag for the full error.

...
```

**Comment by GiladShoham** [comment]
@davidfirst @KutnerUri Yes i'm aware of this issue.
It's mostly a result of the fact that the env is adding dependencies via the get dependencies, but if the env couldn't be loaded because it's not compiler, we are not aware of this dependencies needed to be installed.
And if we still didn't install first time, we can't yet compile the env as we are missing stuff required for the compilation itself.
Let's discuss it.

**Comment by KutnerUri** [comment]
maybe we should not calculate packages to install on the fly?
I understand it's convenient to automatically detect all the dependencies from all of the components in the project, but it makes the install much slower and less predictable.

I think it makes sense to install based on the `workspace.jsonc`. If the user is still missing a package, he should install it manually, no?

**Comment by itaymendel** [comment]
resolved.
