### ISSUE TITLE
EPRM error while doing tag

### ISSUE THREAD

**Issue by cedricve** [teambit/bit#4421]
I'm getting a EPRM error while doing `sudo  bit tag ui/profile-bar --message "first version"`

I353408C02FJ3D1MD6T ui % bit doctor

  bit version   : 1.0.88
  node version  : v15.5.0
  npm version   : 7.3.0
  yarn version  : 1.22.10
  platform      : darwin
  user details  : xxx<cedric@xxxx>

I353408C02FJ3D1MD6T ui % sudo  bit tag ui/profile-bar --message "first version"
⢀⠀ loading bit...Warning: running bit as root might cause permission issues later
✔ running pre install subscribers
✔ deduping dependencies for installation
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 1s 777ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ react-is@npm:17.0.2::__archiveUrl=https%3A%2F%2Fregistry.npmjs.org%
➤ YN0013: │ react@npm:17.0.2::__archiveUrl=https%3A%2F%2Fregistry.npmjs.org%2Fr
➤ YN0013: │ regenerator-runtime@npm:0.13.8::__archiveUrl=https%3A%2F%2Fregistry
➤ YN0013: │ scheduler@npm:0.20.2::__archiveUrl=https%3A%2F%2Fregistry.npmjs.org
➤ YN0013: │ supports-color@npm:7.2.0::__archiveUrl=https%3A%2F%2Fregistry.npmjs
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ core-js@npm:3.14.0::__archiveUrl=https%3A%2F%2Fregistry.npmjs.org%2Fcore-js%2F-%2Fcore-js-3.14.0.tgz must be built because it never did before or the last one failed
➤ YN0000: └ Completed in 3s 366ms
➤ YN0000: Done in 5s 350ms
✔ installing dependencies
✔ running post install subscribers
✔ linking components
✔ teambit.component/isolator, create capsules network (completed in 7s)
  running build pipe for 1 environments, total 6 tasks
✔ teambit.component/isolator, create capsules network (completed in 11ms)
  generated graph for env "teambit.react/react", seeders total: 2, graph total: 2
✔ executing pre-build for all tasks
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 349μs
⢀⠀ teambit.typescript/typescript, compile typescript components (completed in 2s✔ env "teambit.react/react", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 2s
✔ env "teambit.react/react", task "teambit.defender/tester:TestComponents" has completed successfully in 3ms
✔ env "teambit.react/react", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 111μs
✔ env "teambit.react/react", task "teambit.pkg/pkg:PublishDryRun" has completed successfully in 3s
✔ env "teambit.react/react", task "teambit.preview/preview:GeneratePreview" has completed successfully in 38s
⢀⠀ executing post-build for all tasksuncaughtException Error: kill EPERM
    at ChildProcess.kill (node:internal/child_process:504:26)
    at ChildProcessWorker.forceExit (/Users/I353408/.bvm/versions/0.0.401/bit-0.0.401/node_modules/jest-worker/build/workers/ChildProcessWorker.js:307:17)
    at Timeout._onTimeout (/Users/I353408/.bvm/versions/0.0.401/bit-0.0.401/node_modules/jest-worker/build/base/BaseWorkerPool.js:188:16)
    at listOnTimeout (node:internal/timers:556:17)
    at processTimers (node:internal/timers:499:7) {
  errno: -1,
  code: 'EPERM',
  syscall: 'kill'
}

**Comment by cedricve** [comment]
Issue persist after doing `bvm upgrade`

  bit version   : 1.0.98
  node version  : v15.5.0
  npm version   : 7.3.0
  yarn version  : 1.22.10
  platform      : darwin

**Comment by cedricve** [comment]
See entire process here:  https://asciinema.org/connect/3a3f6cd9-35de-4f5c-b96d-4a7dfa39515a

**Comment by itaymendel** [comment]
hi,
this may be a result of running the Bit CLI with sudo permissions.
have you installed Bit with BVM?

**Comment by benjgil** [comment]
Hi @cedricve 
Is this issue still relevant? 

Thanks
Benjamin
