### ISSUE TITLE
"teambit.workspace/workspace" was not found on your local workspace.

### ISSUE THREAD

**Issue by ssengalanto** [teambit/bit#4427]
### Describe the bug
The bit repo I created is not working on other machine, when trying to install dependencies using bit install this error shows up "component "teambit.workspace/workspace" was not found on your local workspace.", I've added the workspace.jsonc and .bitmap in git.

### Steps to Reproduce
1. Clone the Repo
1. Run bit install
1. Error shows "component "teambit.workspace/workspace" was not found on your local workspace"

### Expected Behavior
It should work fine with another machine.

### Screenshots, exceptions and logs
![MicrosoftTeams-image](https://user-images.githubusercontent.com/47241598/122090851-c7c60300-ce3a-11eb-9895-4fa3672bff97.png)

### Specifications
* Bit version: 1.0.84
* Workspace type: harmony
* Node version: 14.15.1
* npm / yarn version: 1.22.0 (yarn) | 6.14.8 (npm)
* Platform: Windows 10

_for harmony workspace_

* relevant env - none
* relevant aspects -

```
// webpack.config.js
module.exports = {
  resolve: {
    alias: {
      '@material-ui/styled-engine': '@material-ui/styled-engine-sc',
    },
  },
};
```

```
// custom-react.extension.ts
import { EnvsMain, EnvsAspect } from '@teambit/envs';
import { ReactAspect, ReactMain } from '@teambit/react';

const webpackConfig = require('./webpack/webpack.config');

export class CustomReactExtension {
  constructor(private react: ReactMain) {}

  static dependencies: any = [EnvsAspect, ReactAspect];

  static async provider([envs, react]: [EnvsMain, ReactMain]) {
    const CustomReactEnv = react.compose([
      react.overridePreviewConfig(webpackConfig),
      react.overrideDevServerConfig(webpackConfig),
    ]);

    envs.registerEnv(CustomReactEnv);

    return new CustomReactExtension(react);
  }
}

```

**Comment by GiladShoham** [comment]
can you please attach the debug.log?
