### ISSUE TITLE
`bbit start` can't resolve module `bufferutil`

### ISSUE THREAD

**Issue by inlet** [teambit/bit#4432]
### Describe the bug
When I try to run a newly created bit (harmony) project with `bbit start` and I navigate to a component, I get this error:

https://gist.github.com/inlet/79470508e22404c65a00b6face510f98

### Steps to Reproduce
1. create new project `bit new react-workspace my-app`
1. `cd my-app && bbit install`
1. create a component `bit create react-component ui/button`
1. `bbit start` and navigate to the component in browser

### Expected Behavior
To show the docs of the component without any errors

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/232559/122207039-f925e980-cea1-11eb-9e57-67337631a4a5.png)

### Specifications
* Bit version: 0.0.421
* Workspace type: harmony
* Node version: v16.1.0
* npm / yarn version: npm: 7.11.2, yarn: 1.22.10
* Platform: MacBook Air Silicon M1

_for harmony workspace_

* relevant env: react
* relevant aspects: just using the steps from docs

Thanks for the help!

**Comment by inlet** [comment]
If I start a clean it works, but it seems that it might interfere with my existing codebase

**Comment by GiladShoham** [comment]
This usually happens when you import into your bundle something which is not browser compatible. 
I need to see the real code to be able to help you with this.

**Comment by inlet** [comment]
I'm afraid I cannot share the code at the moment, I solved this by creating another repo and starting with a clean slate.

Thanks for all the great work!
