### ISSUE TITLE
How to run bit playground at localhost when run 'bit start'

### ISSUE THREAD

**Issue by snake89322** [teambit/bit#4442]
playground at localhost when run 'bit start', is supported?

**Comment by GiladShoham** [comment]
Yes definitely. For harmony workspace only.

**Comment by snake89322** [comment]
> Yes definitely. For harmony workspace only.

I mean this layout setting~ localhost is supported？

![image](https://user-images.githubusercontent.com/10811862/122542086-e3a8ef00-d05c-11eb-9f0d-c71a99677fec.png)

**Comment by GiladShoham** [comment]
This is the legacy playground, there is no way to run it locally.
But the compositions and the js live replacing it.
For harmony scopes, this playground does not exist even in the cloud.
Any reason you want this specific layout?

**Comment by itaymendel** [comment]
hi, to generate a playground use this feature in harmony
https://harmony-docs.bit.dev/building-with-bit/documenting-components#live-examples

**Comment by snake89322** [comment]
> This is the legacy playground, there is no way to run it locally.
> But the compositions and the js live replacing it.
> For harmony scopes, this playground does not exist even in the cloud.
> Any reason you want this specific layout?

Because it can use 'import'，very convenience for show some demo and without compile in local. Just in web.
