### ISSUE TITLE
Not able to import/use third party components in react-bit

### ISSUE THREAD

**Issue by atharvkulkarni1998** [teambit/bit#4443]
After installing a third party library using bit install command there is an error thrown while we are tagging the component to get it exported.

Steps to reproduce the issue:
Create a bit project to implement line chart using plotly.js package as below:

1. bit install react-plotly.js plotly.js
1. import the package (import Plot from 'react-plotly.js') in the project and implement any basic code for it.
1. run "bit compile".
1. check status of component using "bit status"
1. use "bit login" to connect to bit server
1. use "bit link" to link to the collection where the component needs to be stored.
1. run "bit tag --all". Here is the error thrown by compiler.

Please find the attached screen shot of the error.
![image](https://user-images.githubusercontent.com/47672353/122552617-2b774880-d054-11eb-806f-8370e89c6af9.png)

**Comment by GiladShoham** [comment]
I was able to run it successfully 
![image](https://user-images.githubusercontent.com/3840769/122687084-421ccb80-d21d-11eb-9046-b0ef3f02fa68.png)
The `plotly.js` dependency should be a peer dependency.
so when you install it do it like this:
```bash
bit install react-plotly.js
bit install plotly.js --type peer
```
If you already installed it, just go to the dependency resolver policy config in the `workspace.jsonc` and move it from the dependencies to peerDependencies.

If you still have problems, re-open it

**Comment by atharvkulkarni1998** [comment]
@GiladShoham I tried using this the above solution but could not find a way out.
Could you please help with further steps.

Please find the attached screenshot for the dependencies and peer-dependencies section from workspace.jsonc.
![image](https://user-images.githubusercontent.com/47672353/122740941-1859b800-d2a2-11eb-989d-fac5a51d8933.png)
