### ISSUE TITLE
harmony - Bit install removed ^ after updating with -u flag

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#4456]
### Describe the bug
When I install a new version of a component with the `-u` flag, bit install will remove the ^ if it exist.
For example, this is what I have before running the command:
`"@teambit/base-ui.input.checkbox.label": "^1.0.0"`
and after running the update command:
`"@teambit/base-ui.input.checkbox.label": "1.0.1"`

### Steps to Reproduce
1. Add ^ to a component version in the `workspace.jsonc` file.
1. Installing the latest version of this component.

### Expected Behavior
I expect to have this after running the command:
`"@teambit/base-ui.input.checkbox.label": "^1.0.1"`

### Specifications
* Bit version: 0.0.425
* Workspace type: harmony

**Comment by ociewfk10** [comment]
gogo

**Comment by itaymendel** [comment]
we now support an update flow (`bit update`)
