### ISSUE TITLE
bit does not install correct version according to dependency-resolver policy

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4461]
I'm getting an old version of a component (`0.1.0`), even though it does not fit the policy in my `workspace.jsonc`.

```jsonc
"teambit.dependencies/dependency-resolver": {
	"packageManager": "teambit.dependencies/pnpm",
	"policy": {
		"dependencies": {
			// ...
			"@teambit/base-ui.theme.accent-color": "^1.0.0",
		}
	}
}
```

Version `1.1.0` is available from npm: https://registry.npmjs.org/@teambit/base-ui.theme.accent-color
and from our internal registry: https://node.bit.dev/@teambit/base-ui.theme.accent-color

```
"dist-tags": {
	"latest": "1.1.0"
},
"versions": {
	"0.1.0": {},
	"0.1.1": {},
	"1.0.0": {},
	"1.1.0": {},
},
```

### Steps to Reproduce
1. Clone design scope.
1. Checkout master, commit `c29df96664eca1a08e636bb4536d15124b13b89c`
1. `bit install`
1. see incorrect version (and also `bit status` shows no diff)

### Expected Behavior
Expected `@teambit/base-ui.theme.accent-color` to be installed with version `1.1.0`

### Actual
```
+ @teambit/base-ui.theme.accent-color 0.1.0 (1.0.0 is available)
```

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/5400361/123075618-0d796180-d421-11eb-9e8d-f6afee27faca.png)

### Specifications
* Bit version: 0.0.428
* Workspace type: harmony
* Node version: 12.19.0
* npm / yarn version: 6.6.2 (?)
* Platform: MacOS

_for harmony workspace_

* relevant env: `teambit.design/envs/react@1.0.1`

**Comment by KutnerUri** [comment]
workaround - I convinced bit to install by adding a variant configuration:

```
"src/ui/icon-button": {
	"teambit.dependencies/dependency-resolver": {
		"policy": {
			"devDependencies": {
				"@teambit/base-ui.theme.accent-color": "1.1.0"
			}
		}
	}
},
```

after install and tag, I could remove the override.

**Comment by itaymendel** [comment]
irrelevant. resolved a while back, wasn't closed.
