### ISSUE TITLE
Unable to remove component as bit incorrectly indicates another component depends on it

### ISSUE THREAD

**Issue by rlveiga** [teambit/bit#4484]
I am cleaning up my project removing some unused components. First I removed all references to this component (call it component-a), now I want to remove it from bit but can't seem to do so, as I get an error message saying another component depends on the one I am trying to remove. I ran `bit show` on the component that supposedly depends on this first one, and it does not show on the list of dependencies. I also searched my entire project for my component name and the only occurrence seems to be on my .bitmap file. Any ideas? Could this be a cache issue? 

## Expected Behavior
Attempting to run `bit remove <component-b>` should remove the component since I removed all references to it in my project

## Actual Behavior
Bit returns the error message `error: unable to delete <component-b>, because the following components depend on it: <component-a>`

## Steps to Reproduce the Problem
On my workspace:
  1. Run `bit show <component-a>` indicates component-a in fact does not use component-b
  1. Run `bit remove <component-b>`
  1. Get the error message indicated above

## Specifications

  - Bit version: 14.8.8
  - Node version: v15.9.0
  - npm / yarn version: yarn 1.22.10
  - Platform: Mac OS X
  - Bit compiler (include version): `bit.envs/compilers/react-native@1.0.25`
  - Bit tester (include version):

**Comment by davidfirst** [comment]
@rlveiga , probably you have previous versions of these components and in these versions they are depend on each other.
To verify it, you can run `bit cat-component component-a@previous-version` and inspect the dependencies filed.

**Comment by sbland** [comment]
Is there a suggested way to clean up old dependencies in this case?
