### ISSUE TITLE
ENOENT: no such file or directory, open 'tmp/scope-f/objects/...'

### ISSUE THREAD

**Issue by ssengalanto** [teambit/bit#4502]
### Describe the bug
Remote scope suddenly becomes unavailable.

### Steps to Reproduce
1. just running bit install

### Expected Behavior
It should work as usual, and see the components in bit.dev collection

### Screenshots, exceptions and logs
If I visit our bit remote workspace, this happens.
![](https://user-images.githubusercontent.com/47241598/124081433-223ba200-da7e-11eb-8cc6-e2358a0bdc8a.png)

### Specifications
* Bit version: 0.0.394
* Workspace type: harmony
* Node version: 14.15.1
* npm / yarn version: 1.22.10 (yarn)
* Platform: MacOS Catalina

_for harmony workspace_
None

**Comment by ssengalanto** [comment]
@guysaar223 working now thanks!!

**Comment by yassaasalib** [comment]
Hi.

We are having this issue also (within 5 minutes)...

```
remote interface-agency.internal responded with the following error:
ENOENT: no such file or directory, open '/tmp/scope-fs/objects/a7/9eaf46e1ec3d79aa51f5e4369eb99a075d2f20'
```

Also getting a weird output from "bit list" > where the scope reference versions are showing up as "<new>"
