### ISSUE TITLE
Multiline import in mdx file

### ISSUE THREAD

**Issue by jbred** [teambit/bit#4505]
### Steps to Reproduce
1. Create a component with a storybook mdx file inside the component directory. In the mdx file write a multiline import statement like the following:

`import {`
`   a,`
`   b,`
`   c`
`} from '@username/scope.component'`

1. run bit tag for that component

### Expected Behavior
component gets tagged

### Actual Behavior
`missing packages or links from node_modules to the source (run "bit install" to fix both issues. if it's an external package, make sure it's added as a package dependency):`

running bit install does not fix the error

### Specifications
* Bit version: 0.0.439
* Workspace type: harmony
* Node version: 12.18.0
* npm / yarn version: yarn 1.17.3.
* Platform: macOS 11.4

### Additional context
The issue seems to be caused by the multiline import in mdx. Importing in a single line won't cause any errors.
`import { a, b, c } from '@username/scope.component'`

**Comment by GiladShoham** [comment]
thanks for reporting this
