### ISSUE TITLE
Module not found: Error: Can't resolve **/**/teambit.react/reat v0.0.443

### ISSUE THREAD

**Issue by xiaotiandada** [teambit/bit#4522]
### Bit start error
1. install current latest v0.0.443
1. bit start

log:

```bash
// ...
Module not found: Error: Can't resolve **/**/teambit.react/reat.....
// ...
```

### Steps to Reproduce
1. new workspace or clone [harmony-base-ui](https://github.com/teambit/harmony-base-ui)
1. bit start

### Temporary solution
down version to v0.0.427 （no error)

**Comment by GiladShoham** [comment]
You should run bit compile prior to bit start.
We are going to automate it soon

**Comment by rubenofen** [comment]
> You should run bit compile prior to bit start.
> We are going to automate it soon

It is not working for me, the error is still present.

  bit version   : 1.0.116
  node version  : v16.2.0
  npm version   : 7.13.0
  yarn version  : 1.22.10
  platform      : darwin
  user details  : Rub-nannyfy<ruben.sahagun@nannyfy.com>


╔════════════════════╤═════════════════════════════════╤════════════════════════════════════════════════════════╤════════╗
║ category           │ name                            │ description                                            │ status ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ configuration      │ validate workspace's bit config │ validate workspace configuration object                │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate git exec               │ validate that git executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ internal store     │ check orphan refs               │ checks for empty internal refs in local workspace      │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ local environments │ check environment symlinks      │ validate generated symlinks for workspace environments │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate npm exec               │ validate that npm executable found                     │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ vendors            │ validate yarn exec              │ validate that yarn executable found                    │ passed ║
╟────────────────────┼─────────────────────────────────┼────────────────────────────────────────────────────────┼────────╢
║ core               │ validate bit version            │ validate that bit version is up to date                │ passed ║
╚════════════════════╧═════════════════════════════════╧════════════════════════════════════════════════════════╧════════╝

**Comment by rubenofen** [comment]
> You should run bit compile prior to bit start.
> We are going to automate it soon

It is not working for me, the error is still present.

`    at eval (eval at create (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/neo-async/async.js:6883:13
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)

Module not found: Error: Can't resolve 'styled-components' in '/Users/rubensahagun/Development/nannyfy-ui/node_modules/@nannyfy/nannyfy.ui.fancy-text/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'styled-components' in '/Users/rubensahagun/Development/nannyfy-ui/node_modules/@nannyfy/nannyfy.ui.fancy-text/dist'
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/Compilation.js:1765:28
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:730:13
    at eval (eval at create (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:273:22
    at eval (eval at create (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:402:22
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:117:11
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:646:24
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:800:8
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:920:5
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/neo-async/async.js:6883:13
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/lib/NormalModuleFactory.js:903:45
    at finishWithoutResolve (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/rubensahagun/.bvm/versions/0.0.445/bit-0.0.445/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)



You can now view 'nan-ui' components in the browser.
Bit server is running on http://localhost:3000%                                                                                                                                                       
➜  
➜  nannyfy-ui git:(master) ✗ 
➜  nannyfy-ui git:(master) ✗ bbit doctor

  bit version   : 1.0.116
  node version  : v16.2.0
  npm version   : 7.13.0
  yarn version  : 1.22.10
  platform      : darwin`
