### ISSUE TITLE
How to use `npm` to set my bit workspace！

### ISSUE THREAD

**Issue by snake89322** [teambit/bit#4538]
I find API in `teambit.dependencies/dependency-resolver` and set `packageManager` just  2 options:

```
teambit.dependencies/yarn
teambit.dependencies/pnpm
```

so how to set packageManager to use npm?
There is no  `teambit.dependencies/npm`, or  I delete  `packageManager`, then lint `Missing property "packageManager".`

**Comment by GiladShoham** [comment]
There is no support for npm at the moment.
I plan to add it soon.
Once I'll finish I'll close this issue.

**Comment by itaymendel** [comment]
duplicate...
