### ISSUE TITLE
unable to export the following lanes master. they don't exist or are empty

### ISSUE THREAD

**Issue by dstoyanoff** [teambit/bit#4539]
### Describe the bug
The following error is shown when trying to export:
```unable to export the following lanes master. they don't exist or are empty```

The issue started happening today. Everything was ok yesterday.

### Specifications
* Bit version: 1.0.117
* Workspace type: harmony
* Node version: 14.17.0
* yarn version: 1.22.10
* Platform: darwin

_for harmony workspace_

* relevant env typescript-react

In addition, some other issues are happening today that didn't happen yesterday. For example after adding a component I get an error that the .mdx file is not found, which is only fixed with `bit compile`. Yesterday running `bit start` was enough..

**Comment by DStoyanoff** [comment]
It seems to work when downgrading to 0.0.439 `bvm install 0.0.439`. What I've noticed with the newest version is that on new components, the "latest" version is being added in the .bitmap file, which I didn't remember happening before.

**Comment by GiladShoham** [comment]
@davidfirst can you please check this?

**Comment by davidfirst** [comment]
Fixed by https://github.com/teambit/bit/pull/4542.
A new version has been released with the fix.
