### ISSUE TITLE
Cannot find module 'react/jsx-runtime' from ....

### ISSUE THREAD

**Issue by nbhector** [teambit/bit#4561]
### Describe the bug
I installed nivo/core and nivo/line to create a line chart in Bit.  I made sure to use bit install instead of other package managers.  The code seems to work as the line chart composition is rendering.  However, I get this error in the Tests: 

![image](https://user-images.githubusercontent.com/86064236/125342288-8fb2c280-e309-11eb-9e93-b14737a915e2.png)
 Not sure what the problem is, but it could possibly be the JS library nivo.

### Steps to Reproduce
1. bit new react-workspace <workspace=name>
1. bit install
1.  bit create react-component-js ui/line
1. bit install @testing-library/react
1. bit install nivo/toolbar
1.  Code to reproduce problem: https://gist.github.com/nbhector/83da650d238bd4ffc31b42960243ecee

You may get another dependency error on proto-types or something.  I just bit-installed the dependency to fix the problem.

### Expected Behavior
I expected to get an error on the text not matching with a specific string in the test cases rather than get the error of `Cannot find module 'react/jsx-runtime' from 'node_modules/.pnpm/registry.npmjs.org/@nivo/tooltip@0.72.0_7edbc78e2659a229d22960203a896f88/node_modules/@nivo/tooltip/dist/nivo-tooltip.cjs.js'`

### Specifications
* Bit version:
* Workspace type: harmony
* Node version: 15.13.0
* yarn version: 1.22.10 
* OS: Ubuntu 18.04

**Comment by itaymendel** [comment]
irrelevant. please use new react env here https://bit.cloud/teambit/react/react-env
