### ISSUE TITLE
Bit Lint for Harmony not Recgonising Import

### ISSUE THREAD

**Issue by LiamWalshWeb** [teambit/bit#4574]
### Bit lint for Harmony React Components failing at the first hurdle
Simply running `bit lint` with Bit React Components out of the box is throwing an error at the very first `import` keyword

### Steps to Reproduce
1. Start up a new Bit Harmony setup
1. Scaffold a new React component with Typescript
1. Run the `bit lint` command

### Expected Behavior
Linting should just recognise the file is Typescript

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/4707277/125604366-2d848a70-3df4-4dac-8a7c-bc5ee9707e4e.png)

### Specifications
* Bit version: 0.0.424
* Workspace type: harmony
* Node version: v14.16.1
* npm / yarn version: 6.14.12
* Platform: macOS Big Sur

_for harmony workspace_

* teambit.react/react

**Comment by GiladShoham** [comment]
can you please check it again with the latest version of bit?
I'm pretty sure it's already solved

**Comment by itaymendel** [comment]
lint support for bit has been re-implemetned.
