### ISSUE TITLE
Add css/scss/sass module type declarations for TypeScript

### ISSUE THREAD

**Issue by AlexandroPerez** [teambit/bit#4592]
### Description
As of  **bvm v0.0.25** and **bit v0.0.458** when using VS Code editor, and perhaps other editors as well, css/scss/sass modules type declarations can't be found by TypeScript, resulting in an error given by the editor:

![VS Code error](https://raw.githubusercontent.com/AlexandroPerez/temp-bit-workspace/main/assets/scss-module-unresolved.png)

### Describe the solution you'd like
As I previously discussed in Slack, it's possible to use a `d.ts` file to provide TypeScript with the necessary declarations. Create-React-App does this by adding `"types"` into their `package.json`, then having a react application that uses TypeScript reference those types in a local `d.ts` file. 

I've noticed bit has various packages, so this type declarations can be placed on any of them. For the sake of experimentation I modified my local `node_modules/@teambit/bit` package as follows to make it work just like create-react-app does:

#### ./package.json
```
{
  "name": "@teambit/bit",
  ...
  "types": "./lib/bit-env.d.ts",
  ...
}
```

#### ./lib/bit-env.d.ts
```typescript
declare module "*.module.css" {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module "*.module.scss" {
  const classes: { readonly [key: string]: string };
  export default classes;
}

declare module "*.module.sass" {
  const classes: { readonly [key: string]: string };
  export default classes;
}
```

Then I created a local `bit-env-d.ts` file in the root of my workspace (name can be anything, really) and referenced the above type declarations there:

```typecript
/// <reference types="@teambit/bit" />
```

And VS Code, or rather the TypeScript provided by it, no longer complains about not finding type declarations.

> Note that is also feasible to add other type declarations here as well.

### Describe alternatives you've considered
It's also possible to have `bit new` or `bit init` add a local `d.ts` file with the above declarations there, but it may be harder to update them in future version of bit this way.

### Additional context
https://github.com/AlexandroPerez/temp-bit-workspace can be cloned to get a workspace that reproduces the problem.

**Comment by itaymendel** [comment]
added as part of upgrade to react-env. please use https://bit.cloud/teambit/react/react-env
