### ISSUE TITLE
Tailwind custom theme settings not working as expected

### ISSUE THREAD

**Issue by nachten** [teambit/bit#4594]
### Describe the bug
Custom theme settings inside the `tailwind.config.js` not working using the example project https://github.com/teambit/react-tailwind-env 

### Steps to Reproduce
I've created an example:  https://github.com/nachten/bit-tailwind
Inside the example there is an `simple-test` component, which has an className with the value p-16 which would give it an padding of `1.6rem` as configured inside of the `tailwind.config.js` but it has the value `4rem` which is the default of tailwind.

### Specifications
* Bit version: 0.0.459
* Workspace type: harmony
* Node version: v12.22.3
* npm / yarn version: npm
* Platform: Macos Big Sur 11.4

**Comment by DaveHudson** [comment]
I hit a similar problem yesterday. I had to put `tailwind.config.js` in the root folder (where `workspace.jsonc` is) and then it picked up my Tailwind customisations instead of using the default config file

**Comment by nachten** [comment]
> I hit a similar problem yesterday. I had to put `tailwind.config.js` in the root folder (where `workspace.jsonc` is) and then it picked up my Tailwind customisations instead of using the default config file

This does indeed solve the problem ... but it does not solve the real issue here I think :) 

@GiladShoham is this a direction you can look at ?

**Comment by GiladShoham** [comment]
@nachten As you said, this doesn't really solve the issue.
As it won't be available when using the component on another worksapce/machine.
The solution should come from the bit internal or at least the env internal.
Hope to have some time to look into it soon

**Comment by dspacejs** [comment]
@nachten I'm running into a similar issue with Bit/Tailwind. Do you have a repo somewhere I can take a look at? I'd like to see what you've done, if you don't mind. Cheers

**Comment by dspacejs** [comment]
@DaveHudson putting `tailwind.config.js` in the root didn't work for me. How did you get it to use your custom configuration? 

Because if that workaround works, `tailwind.config.js` in the root directory could just import the contents of `tailwind.config.js` from the Bit component. This could work until a proper fix is made for this issue.

**Comment by nachten** [comment]
> @DaveHudson putting `tailwind.config.js` in the root didn't work for me. How did you get it to use your custom configuration?
> 
> Because if that workaround works, `tailwind.config.js` in the root directory could just import the contents of `tailwind.config.js` from the Bit component. This could work until a proper fix is made for this issue.

This worked for me ... can you show me your `tailwind.config.js` and are you sure you placed it in the root ? And use the following repository as an starting project: https://github.com/teambit/react-tailwind-env

**Comment by GiladShoham** [comment]
@nachten @dspacejs 
See the attached PR.
The example repo has been updated with examples and necessary code to make it work with a custom theme.
If you see any issue, please re-open
