### ISSUE TITLE
ability to set the height of component preview section

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4597]
see the attachment below
![image (4)](https://user-images.githubusercontent.com/40735433/126097731-528b97b6-3879-494d-a7b4-ee516975aca2.png)

**Comment by KutnerUri** [comment]
@leslie555 - react live playground will grow to match the size of the component inside it. (to a max height of 450px, and I might add padding).
Please explain what is the problem and what is the solution / syntax you'd like to see. :)

**Comment by leslie555** [comment]
in some cases, we write a component with popover, modal, or some others pop window, it will not stretch. I didn't have a good idea about how to set

**Comment by KutnerUri** [comment]
how about wrapping the component with a div?
you can set its height and width, like so:
```tsx
<div style={{ height: 400 }}>
  <Loading .../>
</div>
```

I could have something like this syntax:
````markdown
```tsx live=true height=400px
<Loading .../>
```
````
But this could break in the future (if we switch markdown engine, etc) and I'm worried about inventing custom md syntax. 😕 

@itaymendel @odedre  - what do you guys think?

**Comment by leslie555** [comment]
> how about wrapping the component with a div?
> you can set its height and width, like so:
> 
> ```tsx
> <div style={{ height: 400 }}>
>   <Loading .../>
> </div>
> ```

it looks good and quite easy

**Comment by KutnerUri** [comment]
great. can I close the issue? :)
