### ISSUE TITLE
variants not picking up folders with glob patterns

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#4608]
### Describe the bug
should be able to do do `directory/**` and set the env

### Steps to Reproduce
1. `"teambit.workspace/variants": {
    "react/**": {
      "teambit.react/react": {}
    }
  }`
1. run `bit envs`

### Expected Behavior
Should show react env 

### Screenshots, exceptions and logs
it just defaults to node env. we found that removing the glob pattern works but with glob pattern it doesn't work. this should also be mentioned in the comments of the workspace.json to make it clearer as right now I thought you always put brackets as per example in this page but in fact for directories it works with no brackets.

### Specifications
* Bit version: 0.0.462
* Workspace type: (harmony/legacy) harmony
* Node version:
* npm / yarn version:
* Platform:

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
This is by design.
At the moment, the `**` is only supported for the namespace syntax.
For folders, you should just mention the folder, and it will always include all the subfolders below without the need to specify `**`
I'll add an error about it.
