### ISSUE TITLE
Unable to load external aspect dependencies

### ISSUE THREAD

**Issue by ocombe** [teambit/bit#4616]
### Describe the bug
When using an external aspect, if it's not listed in the root of workspace.jsonc, it doesn't receive external aspect dependencies (they are null). Bit aspect dependencies work fine.

### Steps to Reproduce
1. checkout https://github.com/teambit/bit-angular
1. edit workspace.jsonc and comment the line ~85: `"teambit.angular/angular-v12": {},`
1. run `bit add examples\demo-lib-v12`
1. run `bit compile demo-lib-v12`

### Expected Behavior
no error

**Comment by GiladShoham** [comment]
fixed
