### ISSUE TITLE
how to un-`eject-conf`

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4626]
I've tried running `bit eject-conf` on one of my components.
Bit created a new `component.json` file in the component filesystem.

How do I undo this operation? Do I just delete the file? are there any side effects I should run?
Basically I'm missing a `bit undo eject-config` command or something similar.

### Specifications
* Bit version: 0.0.463

**Comment by GiladShoham** [comment]
For now you can just delete it. (of course it will remove any changes you did unless you tagged the component first).
We have an `inject-conf` cmd which is kind of the opposite, but we need to make it work for harmony.

**Comment by KutnerUri** [comment]
OK
