### ISSUE TITLE
Importing from dependency results in "is not a function" error

### ISSUE THREAD

**Issue by RyKilleen** [teambit/bit#4634]
### Description
Cannot import a function from dependency as expected

### Specifications
Bit Doctor info:

```
  bit version   : 1.0.127
  node version  : v15.8.0
  npm version   : 7.5.1
  yarn version  : 1.22.10
  platform      : linux
  user details  : RyKilleen<rykilleen@gmail.com>
```

### Context and additional information
I am attempting to update StichesJS. Previously, I exported Stitches config as a package with bit.dev. This worked really well! 

Now, I'm attempting update from Alpha to Beta. Updating packages seemed fairly straight-forward, but now I receive the following error in the Bit local environment, when running `bit start`, `bit test`, or attempting to tag/export with `bit`:

```
  TypeError: (0 , _react.createCss) is not a function

      123 | }
      124 |
    > 125 | const { styled, css } = createCss(config)
```

It's important to note that when I lift this config out and use it directly in my project, it works as expected.

**Comment by GiladShoham** [comment]
can you share the code? or some steps to reproduce it?
Maybe even a simple workspace that demonstrates the issue.
it will be very hard for us to check it with no further details.

**Comment by RyKilleen** [comment]
Here his my `workspace.jsonc` file

<details><summary>Workspace file</summary>


```
{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  "teambit.workspace/workspace": {
    "name": "component-library",
    "icon": "https://static.bit.dev/bit-logo.svg",
    "defaultDirectory": "{scope}/{name}",
    "defaultScope": "nsg.common"
  },
  "teambit.dependencies/dependency-resolver": {
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@stitches/core": "0.2.2",
        "@stitches/react": "0.2.2",
        "@types/react": "17.0.14",
        "react": "17.0.2",
        "react-dom": "17.0.2"
      },
      "peerDependencies": {
        "react": "17.0.2",
        "react-dom": "17.0.2"
      }
    },
    "packageManagerArgs": [],
    "devFilePatterns": ["**/*.spec.ts"],
    "strictPeerDependencies": true,
    "installFromBitDevRegistry": true,
    "savePrefix": ""
  },
  "teambit.workspace/variants": {
    "*": {
      "teambit.react/react": {}
    }
  }
}
```

</details>
