### ISSUE TITLE
Bit Legacy with Angular isn't working

### ISSUE THREAD

**Issue by LucasMenchi** [teambit/bit#4635]
### Describe the bug
I cannot import the compiler in the Angular Tutorial. Also, we have an operational project where we can't update our components because the builds are failing.

### Steps to Reproduce
1. Follow the Angular Tutorial for Bit (https://docs.bit.dev/docs/tutorials/bit-angular-tutorial)
1. It fails at the install of the angular compiler (https://docs.bit.dev/docs/tutorials/bit-angular-tutorial#install-angular-compiler). 

### Expected Behavior
* Works.

### Screenshots, exceptions and logs
`
bit import bit.envs/compilers/angular --compiler
failed running npm install at /usr/local/src/ca-components-desktop/mobile/angular-lucas/.bit/components/compilers/angular/bit.envs/10.1.7 with args: --production

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @bit/bit.envs.compilers.angular@10.1.7
npm ERR! Found: typescript@4.0.3
npm ERR! node_modules/typescript
npm ERR!   typescript@"4.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer typescript@">=3.0.0 <4.0" from @bazel/typescript@2.3.0
npm ERR! node_modules/bazel/typescript
npm ERR!   @bazel/typescript@"2.3.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/lucas/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas/.npm/_logs/2021-07-26T20_24_42_149Z-debug.log

see troubleshooting at https://docs.bit.dev/docs/installing-components

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
`

### Specifications
* Bit version: 14.8.8
* Workspace type: legacy
* Node version: 14.17.2
* npm / yarn version: 7.19.1
* Platform: Linux

_for leagacy_

* Bit compiler (include version): bit.envs/compilers/angular@10.1.7
* Bit tester (include version):

### Additional context
- In stackoverflow there is an issue with the same problem: https://stackoverflow.com/questions/68252277/importing-angular-compiler-to-bit-results-in-dependency-tree-issues/68535668

**Comment by itaymendel** [comment]
have you updated npm version lately? perhaps i'm not sure we evaluated this flow with npm-7.
by the way, you can checkout the revised implementation for angular support here - https://github.com/teambit/bit-angular

**Comment by LucasMenchi** [comment]
I'll check that, thanks

**Comment by LucasMenchi** [comment]
**Update on this:** The compiler installs fine with npm 6, but now the components aren't being published on the node registry. 

![image](https://user-images.githubusercontent.com/19753160/127161049-fad612b2-3a38-441d-a0cc-a469a3e70f63.png)

The collection is public so it shouldn't be a problem to install the components in other projects, nevertheless:

`
npm i @bit/consorcioabierto.angular-lucas.product-list
npm ERR! code E404
npm ERR! 404 Not Found - GET https://node.bit.dev/@bit%2fconsorcioabierto.angular-lucas.product-list - Not found
npm ERR! 404 
npm ERR! 404  '@bit/consorcioabierto.angular-lucas.product-list@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas/.npm/_logs/2021-07-27T13_17_09_900Z-debug.log
`

**Comment by itaymendel** [comment]
do you see this on the web? when running `bit show` or `bit list` you see the new version?

**Comment by LucasMenchi** [comment]
Yes! 
![image](https://user-images.githubusercontent.com/19753160/127323522-0e179613-993e-42c3-a6c0-a1755227aa11.png)

**Comment by LucasMenchi** [comment]
Any update on this? 
Here's a caption of the web preview, maybe it helps to understand:

![image](https://user-images.githubusercontent.com/19753160/127560342-91325403-aea0-4649-8721-beb6f96dbddd.png)

**Comment by alejandrombc** [comment]
Same here, the new versions of my components are not built on bit.dev, what can we do to fix this? :/

**Comment by alejandrombc** [comment]
Any news about this?

**Comment by thisisforeagle** [comment]
Following tutorial after sign-up and seeing the same error as reported above.
Tutorial step:
https://docs.bit.dev/docs/tutorials/bit-angular-tutorial#:~:text=bit%20import%20bit.envs/compilers/angular%20%2D%2Dcompiler

**Comment by itaymendel** [comment]
for using bit with angular, please refer to this project - https://github.com/teambit/bit-angular
