### ISSUE TITLE
bit support <sub> command

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#4637]
This is a suggestion to make support for bit easier.

we will add `bit support <sub>` commands. 
for example:

`bit support logs`

* will tar all the logs and send them.
`bit support workspace` - will tar the workspace and send it. different flags for example: `--include-node-modules`, `--bitmap-only`, `--worspace-config-only`
`bit support github` - will open an interactive shell that eventually will open a github issue in the relevant repo (bit,docs etc)

There will be a new global config, similar to the scope resolver, which lets you point to a function that's got the data (the logs tar, the workspace tar) and return a string (id).
Then even companies that are working without bit cloud, can implement this function to send the files for example to the infra team. so bit as a company won't even be aware of this at all.
The same will be able to set up for the GitHub repos, or you can disable this feature.

By default if not disabled, files will be sent to the bit team, and the user will get an id back so he can use this id to communicate with the bit team.

**Comment by itaymendel** [comment]
irrelevant. if needed we'll ship it with an external aspect, i don't see a reason to keep this in the issue list.
