### ISSUE TITLE
React Native Conditional Component Rendering Doesn't Compile

### ISSUE THREAD

**Issue by jennifer-elyse** [teambit/bit#4648]
### Describe the bug
The tagging is failing on this code. Full component code is included:
const ComponentContainer = onPress ? TouchableOpacity : View;
return (
		<ComponentContainer />
            );

### Steps to Reproduce
1. try to tag the component

### Expected Behavior
The component should tag and allow me to export.

### Screenshots, exceptions and logs
The following errors were found while running the build pipeline
Failed task 1: "teambit.compilation/compiler:TSCompiler" of env "teambit.react/react-native"
component: jennifer.demo-scope/ui/card@0.0.1
/Users/jkirchne/Library/Caches/Bit/capsules/3d26797eaffdfb056e428b78e5739d29586e2fbf/jennifer.demo-scope_ui_card@0.0.1/card.tsx:54:4 - error TS2604: JSX element type 'ComponentContainer' does not have any construct or call signatures.

54  	<ComponentContainer
    	 ~~~~~~~~~~~~~~~~~~

Found 1 errors in 1 components

✖ Total 6 tasks. 1 succeeded. 1 failed. 4 skipped. Total errors: 1.

### Specifications

bit version : 1.0.128
node version : v14.17.3
npm version : 6.14.13
yarn version : 1.22.10
platform : darwin
user details : <>

Platform: OSX
Bit compiler (include version): 0.0.25
Bit tester (include version): ?

### Additional context
import React, { useState } from 'react';
import {
	StyleSheet,
	View,
	TouchableOpacity
} from 'react-native';

export default function Card(props) {
	const {
		borderRadius,
		width,
		height,
		elevation,
		onPress,
		cardColor
	} = props;

```
const ComponentContainer = onPress ? TouchableOpacity : View;
```

```
const viewStyle = {
	color: cardColor,
	...props.style
};
```

```
const container = {
	width: width,
	height: height,
	overflow: 'visible',
	borderRadius: borderRadius
};
```

```
function elevationStyle() {
	const {elevation} = props;
	return {elevation: elevation || 2};
}
```

```
function shadowStyle() {
	return styles.containerShadow;
}
```

```
function backgroundStyle() {
	const {enableBlur, backgroundColor = '#ffffff'} = props;
```

```
	if (enableBlur) {
		return {backgroundColor: 'rgba(cardColor, 0.85)'};
	} else {
		return {backgroundColor};
	}
}
```

```
return (
	<ComponentContainer
		style={[
			container,
			{borderRadius},
			viewStyle,
			{ elevation },
			shadowStyle(),
			backgroundStyle()
		]}
		onPress={onPress}>
			{props.children}
	</ComponentContainer>);
```

}

const styles = StyleSheet.create({
	containerShadow: {
		shadowColor: '#333',
		shadowOpacity: 0.25,
		shadowRadius: 12,
		shadowOffset: {height: 5, width: 0}
	}
});

**Comment by JoshK2** [comment]
Hi @jennifer-elyse, this error is a typescript error and not related to Bit build process.
You need to a type to `ComponentContainer`, I added `any` just for testing and it's working:
`const ComponentContainer: any = onPress ? TouchableOpacity : View;`
![image](https://user-images.githubusercontent.com/35892475/136010311-e50e18b3-f206-4342-a13f-0847dc15aff9.png)
