### ISSUE TITLE
Enable SSL on bit start

### ISSUE THREAD

**Issue by wesdollar** [teambit/bit#4650]
### Description
Need the ability to launch bit with SSL "enabled". The purpose of this is for communicating with outside resources that require SSL, such as REST APIs, etc. Non-SSL requests are blocked when requested from a secure resource. 

### Describe the solution you'd like
Ideally, this would be done by passing a flag into `bit start`, such as `bit start --ssl` or similar. 

### Describe alternatives you've considered
Launch bit via ngrok such that SSL happens out of the box.

**Comment by nachten** [comment]
Why not place an NGINX with LetsEncrypt in front of it ?
