### ISSUE TITLE
unexpected network error has occurred. server responded with: "Forbidden: my.scope"

### ISSUE THREAD

**Issue by robyn-57blocks** [teambit/bit#4652]
### Description

`bit export `

the result has below:

**unexpected network error has occurred.**
**server responded with: "Forbidden:  my.scope"**

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
`bit doctor`

* bit version   : 1.0.129
* node version  : v14.17.1
* npm version   : 6.14.13
* yarn version  : 1.22.10
* platform      : darwin

why I can't export my component to `bit.dez`?

**Comment by itaymendel** [comment]
hi, can you please add additional info on the issue:

1. you created a scope on bit.dev?
2. have you configured the scope correctly in `workspace.jsonc`?

**Comment by robyn-57blocks** [comment]
I'm glad about your reply.
I have created a scope on bit.dev and already set the default scope in workspace.jsonc.
Other scopes I export are OK. only this scope is not ok. The only difference is that the scope is private.
Maybe I haven't the permission.
I am in the bit organization.  

![image](https://user-images.githubusercontent.com/87001542/127303820-c39db0ad-75a9-432d-aa07-193e856785f3.png)

**Comment by robyn-57blocks** [comment]
In fact, this scope is my co-worker created, I will call him to confirm.

**unexpected network error has occurred.
server responded with: "Forbidden: my.scope"**

Does the above error mean that I don't have permission?

**Comment by robyn-57blocks** [comment]
@davidfirst  thank you so much. I have found the reason and the export component to bit.dev is successful.
My colleague didn't give me permission. haha
