### ISSUE TITLE
Cannot have same component name in different collections

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#4656]
### Describe the bug
Let's imagine `org.components/theme` component, it looks in `.bitmap` like:

```json
{
   "theme": {
        "scope": "org.components",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "components/theme"
    }
}
```

then

```sh
bit add lib/theme
```

it looks in `.bitmap` like:

```json
{
   "lib/theme": {
        "scope": "org.lib",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "lib/theme"
    }
}
```

### Steps to Reproduce
1. `bit add components/theme`
1. `bit add lib/theme`
1. `bit show lib/theme`

### Expected Behavior
Collections behave as root namespaces, and components names do not intersect with each other.
It would be great to have accent in the property name `org.lib__theme` or `theme#org.lib`

```json
{
   "org.lib__theme": {
        "scope": "org.lib",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "lib/theme"
    }
}
```

### Specifications
* Bit version: 0.0.468
* Workspace type: harmony
* Node version: 14 lts
* yarn version: 1
* Platform: mac m1

**Comment by bingtsingw** [comment]
the same issue here, it's common that different scope have components with the same name

**Comment by sbland** [comment]
This makes it very difficult to deal with multiple scopes.
