### ISSUE TITLE
unable to export the following lanes main. they don't exist or are empty

### ISSUE THREAD

**Issue by nbhector** [teambit/bit#4658]
### Description
I am trying to export all my components to my collection in bit.dev, however I am getting this error: 

```
unable to export the following lanes main. they don't exist or are empty
```

What does this exactly mean?

### Specifications
* Bit version: 0.0.429
* Node version: v15.13.0
* Platform: Ubuntu 18.04
* Bit compiler (include version): N/A
* Bit tester (include version): N/A

### Context and additional information
I made sure that all components passed the test and even changed the defaultScope name to the collection.

**Comment by davidfirst** [comment]
@nbhector , this issue was fixed a while ago. Updating to the latest version should help here.

**Comment by nbhector** [comment]
That worked.  Thank you!
