### ISSUE TITLE
Move Component Props to Top

### ISSUE THREAD

**Issue by wesdollar** [teambit/bit#4660]
### Description
I'm finding that the properties for components get lost since they are at the very bottom of the page. People simply aren't scrolling far enough to see them.

### Describe the solution you'd like
Either move the properties block to the top or provide a hyperlink, either in the toolbar or near the header/description/labels that scrolls the user to the properties block.

**Comment by wesdollar** [comment]
I'm happy to contribute this if there's buy-in.

**Comment by GiladShoham** [comment]
Adding a link to the props on the top sound good to me.
@itaymendel @erezbit

**Comment by itaymendel** [comment]
you can control your own setup of component-docs now.
create a custom env and modify the template...
