### ISSUE TITLE
Block comments in proptypes and files break Properties Table

### ISSUE THREAD

**Issue by blankenshipd001** [teambit/bit#4662]
### Describe the bug
When using block comments in the propTypes or within other files in the component the Properties table fails to show up.

`/** this is a valid comment in propTypes  */`

```
/**
  * This style of comment breaks the Properties table
  */ 
```

We have a components file outside of the main component and using block comments on the function also broke the table.

### Steps to Reproduce
1. Add block comments to the propTypes
1. Look for the Properties Table
1. Add block comment to an additional file (helper component) on the exported function1.
1. Look for the Properties Table

### Expected Behavior
Properties table should display even when using block comments.

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.469
* Workspace type: harmony
* Node version: 4.17.3
* npm / yarn version: npm: 6.14.13
* Platform: Mac

_for harmony workspace_

* relevant env : react
* relevant aspects

**Comment by itaymendel** [comment]
This has been resolved in the new component-schema feature that drives the api-ref documentation page.
closing the issue, as its irrelevant.
