### ISSUE TITLE
Can't install/add/import the react-native compiler

### ISSUE THREAD

**Issue by jennifer-elyse** [teambit/bit#4663]
### Describe the bug
I get errors trying to install/add/import the react-native compiler

### Steps to Reproduce
1.`**bit import bit.envs/compilers/react-native -c**`
unexpected network error has occurred.
server responded with: "Please update your Bit client.
For additional information: https://docs.bit.dev/docs/installation#latest-version"

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.

1. `**yarn add bit.envs/compilers/react-native -c**`
yarn add v1.22.10
warning package.json: No license field
warning No license field
[1/4] :mag:  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/bit.envs%2fcompilers/react-native: Request \"https://registry.yarnpkg.com/bit.envs%2fcompilers/react-native\" returned a 405".
info If you think this is a bug, please open a bug report with the information provided in "/Users/{user}/node_projects/{project}/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
1.  `**npm install bit.envs/compilers/react-native -c**`
npm ERR! code ENOLOCAL
npm ERR! Could not install from "bit.envs/compilers/react-native" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{user}/.npm/_logs/2021-07-30T03_58_25_167Z-debug.log

### Expected Behavior
I might know if it worked

### Screenshots, exceptions and logs
Debug Log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   'bit.envs/compilers/react-native',
1 verbose cli   '-c'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.3
4 verbose npm-session b0c1370a056c4be5
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for file:bit.envs/compilers/react-native Could not install from "bit.envs/compilers/react-native" as it does not contain a package.json file.
8 timing stage:rollbackFailedOptional Completed in 0ms
9 timing stage:runTopLevelLifecycles Completed in 2682ms
10 verbose stack Error: ENOENT: no such file or directory, open '/Users/{username}/node_projects/{project}/bit.envs/compilers/react-native/package.json'
11 verbose cwd /Users/{username}/node_projects/{project}
12 verbose Darwin 20.6.0
13 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "bit.envs/compilers/react-native" "-c"
14 verbose node v14.17.3
15 verbose npm  v6.14.13
16 error code ENOLOCAL
17 error Could not install from "bit.envs/compilers/react-native" as it does not contain a package.json file.
18 verbose exit [ 1, true ]

### Specifications
![image](https://user-images.githubusercontent.com/1098916/127599916-08ae8d5b-8864-435c-b059-5e2c18257b2f.png)

* Bit version:bit version   : 1.0.129
  node version  : v14.17.3
  npm version   : 6.14.13
  yarn version  : 1.22.10
  platform      : darwin
  user details  : <>
* Workspace type: (**harmony**/legacy)
* Platform: OSX Big Sur 11.5

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
I really recommend using the harmony version

**Comment by jennifer-elyse** [comment]
can you point me to that version? or is it integrated with harmony?

**Comment by itaymendel** [comment]
seems like you are using the wrong version of Bit.
please get started with these docs - https://harmony-docs.bit.dev
