### ISSUE TITLE
add bit variants data to bit show

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#4678]
when running bit show for a given component, add its resolved configuration from variants.
(workspace feature only)

It will show all the variants rules that were applied on the component, sort by specificity (including the specificity number).
it will show for each variant which config was taken from it.
It will show for each variant which config wasn't taken from it (with strikethrough or red or some other UI way)

consider show also data taken from the component.json if exist.
consider show also data taken/merged from a previous version (models)

Add a flag for bit show to show/hide this data

**Comment by itaymendel** [comment]
ability to see where a dep was set from is already available via `bit deps blame`, etc.
