### ISSUE TITLE
bit-vue-tutorial - "Note: your component has no build task defined!"

### ISSUE THREAD

**Issue by ChrisLang** [teambit/bit#4698]
Hi,

Hope someone can assist me, I have been following the [bit-vue-tutorial](https://docs.bit.dev/docs/tutorials/bit-vue-tutorial) and I am trying to view my component at bit.dev after exporting it from my workspace. When I try view the component I get the following (see screenshot below). We're busy looking into Bit to use along side our storybook setup. Thanks

![image](https://user-images.githubusercontent.com/2931581/128475725-ca006492-d060-4b51-a783-4c5acdb5b2fb.png)

You can also view my Bit here https://bit.dev/chrislang/vue-tutorial/product-list?example=610ce7c93f1e210019bce385&version=0.0.4

Context and additional information
Bit version: latest
node version: 12.22.1
npm version: 6.14.12
OS: Windows 10 64-bit

**Comment by itaymendel** [comment]
prior to exporting the component, you need to have a `compiler` defined in your `bit` object.
regardless, bit-legacy workflow with vue is not stable. we're working to refactor it as part of bit-harmony.
