### ISSUE TITLE
Images with svg as url not working after upgrading bit

### ISSUE THREAD

**Issue by p-l-l** [teambit/bit#4700]
### Describe the bug
After upgrading bit from 0.0.471 to 0.0476, the svgs rendered by an ![]({svgPath} ... /) in
a component are not working anymore. They output this error on the browser.
![image](https://user-images.githubusercontent.com/23360637/128383149-52f2b607-ff67-4650-b26d-cb1e22ac895c.png)

### Steps to Reproduce
1. Create a component, add a folder "images" to it and add a .svg file
1. `import leSvg from './images/leSvg,svg';`
1. For Typescript I have this .d.ts on my src folder
![image](https://user-images.githubusercontent.com/23360637/128384413-de686c34-3dfa-4bec-8671-40bd3bf74e14.png)

### Expected Behavior
The ![](undefined) renders the .svg correctly in both Overview and Composition tab.

### Screenshots, exceptions and logs
`<img style="width: 100%;" alt="alt text" src="http://localhost:3000/preview/teambit.react/react/85bc092ce4082f5c1edc.svg">`
![image](https://user-images.githubusercontent.com/23360637/128383810-22971db9-7dba-442c-b460-f8574cd07c85.png)

### Specifications
* Bit version: 0.0.477
* Workspace type: harmony
* Node version: 14.16.0
* npm / yarn version: 1.22.10
* Platform: Windows 10

Workspace is using "teambit.react/react": {}

### Additional context
Here is an example of request on bit  0.0.471 (working)
![image](https://user-images.githubusercontent.com/23360637/128384050-bde5b42b-e6a8-4f72-ae8e-44036d8bfc48.png)

VS 0.0477 (not working)
![image](https://user-images.githubusercontent.com/23360637/128384123-202b1b36-a28e-4cd3-9d00-c9abbd5e4b39.png)

**Comment by GiladShoham** [comment]
@KutnKutner can you please check this?
Maybe something related to the hot reload changes?

**Comment by KutnerUri** [comment]
yup I'm on it. Got it reproduced locally and all.

**Comment by KutnerUri** [comment]
found it - react-refresh is somehow applied to .svg files.
<img width="598" alt="Screen Shot 2021-08-09 at 16 03 33" src="https://user-images.githubusercontent.com/5400361/128710590-4df901d5-c632-4618-aa1e-ca72a5a95341.png">

**Comment by KutnerUri** [comment]
@p-l-l fixed in `0.0.483`. can you verify?
