### ISSUE TITLE
bit doesn't know it should render which files' propTypes if a component includes several `.jsx ` and an `index.js`

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4702]
if a component includes an index.js and more than one jsx file, there is no method to mark which files' propTypes should be rendered on the overview page.
what's more, sometimes bit does not render the Properties table on overview page

**Comment by leslie555** [comment]
I have found a way to solve this problem, I put others(children) components into a dir which named `component`

**Comment by KutnerUri** [comment]
Yes, the automatic prop docs are less than desired. It has a hard time handling multiple files and doesn't understand inheritance / type-extensions. 

We are currently using `react-docgen` / `react-docgen-typescript`, and AFAIK we are looking to hire a dedicated person for that.

@davidfirst - any thoughts?

**Comment by itaymendel** [comment]
bit moved to support full api-schema.
