### ISSUE TITLE
Cannot find module 'workbox-build/build/options/schema/webpack-generate-sw'

### ISSUE THREAD

**Issue by priteshkadiwala** [teambit/bit#4706]
### Describe the bug
When I try to run `bit start` after the installation, it gives me this bug.

### Steps to Reproduce
1. Just run `bit start` after completing the installation process

### Expected Behavior
Suppose to open localhost after a successful run command

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/12538126/128594520-682048a3-ff90-43d5-947e-2fcb23b61857.png)

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.478
* Workspace type: harmony
* Node version: v14.15.4
* npm / yarn version: 7.5.2
* Platform: MacOS

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by yiearth** [comment]
Downgrading bit to 0.0.477 worked for me.
https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1628251372244600?thread_ts=1628241489.243300&cid=CCDHG0TPY

**Comment by KutnerUri** [comment]
I looks like a secondary dependency got a breaking - `workbox-webpack-plugin` ver `6.1.5` relying on `workbox-build` ver `^6.1.5`. I'm investigating.

**Comment by KutnerUri** [comment]
yup. https://github.com/GoogleChrome/workbox/issues/2904
I'm removing version 478 from .bvm, and I'm going to try and update workbox-webpack-plugin and see if it fixes it

**Comment by KutnerUri** [comment]
merged, I will verify when the new version comes out.

**Comment by KutnerUri** [comment]
verified v0.0.479 working ✅
