### ISSUE TITLE
Unable to match IDE/bit lint linting configurations

### ISSUE THREAD

**Issue by tylerwellswork** [teambit/bit#4712]
It appears that plugins may not work in custom linting configurations. I want to configure a custom linting environment identical to my local .eslintrc, so that linting is the same in both my IDE and `bit lint`. I also don't see a way to add a parser or parserOptions to custom environment's linting configuration, and ultimately I get different linting errors in bit lint versus my IDE.

When I attempt to replicate plugins and parsers within my custom environment to match my .elistrc, I encounter errors like this
```
✖ service linter env myOrg/custom-lint has failed. Invalid Options:
- Unknown options: extends
```

Relevant .eslintrc:

```
    "extends": [
        "plugin:@typescript-eslint/recommended",
        "plugin:react/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
        "ecmaVersion": 2018,
        "sourceType": "module"
      },
    "plugins": ["import", "jest", "@typescript-eslint"],
```

Relevant custom environment:

```
      react.useEslint({
        transformers: [
          (config) => {
            config.addExtends([
              'plugin:@typescript-eslint/recommended',
              'plugin:react/recommended',
            ]);
            config.addPlugins(['jest', 'import', '@typescript-eslint'])

            return config;
          },
        ],
      }),
```

Would appreciate any guidance as to how I can use the same configuration in both .eslintrc and my custom environment file for bit lint.

**Comment by GiladShoham** [comment]
You can just change the config.raw directly in your transformer.
Print it first to see its structure then you can change everything inside.

**Comment by jbiskur** [comment]
is it possible to extract the finished configuration after all envs have been applied ? that way we can create a config that is based on the standard envs that we use, and extend with bit's environments.

The same is the case with tsconfig and prettier. Webstorm for example has a tough time keeping up as it does not know what to look at.

**Comment by GiladShoham** [comment]
I can make a command that does exactly this.
This is one of the solutions I came up with when thinking about the bit<>ide lint issue

**Comment by GiladShoham** [comment]
This also related to a feature I requested from the vscode team - https://github.com/microsoft/vscode-eslint/issues/1286

**Comment by jbiskur** [comment]
One way this could be done was to simply output the .eslintrc, tsconfig.json and .prettierrc files to each component's dir based on their settings. normally IDE's eslint and prettier as well as typescript "plugins" find the nearest config files to the opened files if set to automatic.

Another way is to do the same as for example [nrwl's nx workspace](https://nx.dev/) and create a "base" config in the root, and then in each component extend the base. And then add these generated files to .gitignore and don't include them in the component when building it, that way they don't "pollute" the component.

Just my two cents :)

**Comment by jbiskur** [comment]
the "bit env <comp id>" does provide the configuration for that component :)

**Comment by GiladShoham** [comment]
At the moment I'm thinking as you suggested to have it on each one of the components.
The main issue is that it will make a mess in your fs. having prettier, eslint, tsconfig on each one of your components.
Making a base in the root then one extend it on each component is pretty hard calculation.
I might try to hoist the most common config to the root. so only components that use other configs will need it inside the component folder.

**Comment by jbiskur** [comment]
makes sense, that will allow for the most compatibility for IDE's

**Comment by FNLuzko** [comment]
@tylerwellswork were you able to make this approach work? i'm stuck at the same place. It's any official recommendation for this? @GiladShoham

**Comment by 4ndh4k** [comment]
We've been trying to figure this out as well. For tsconfig there is the ```bit write-tsconfig``` command, I imagine an equivalent for eslint and prettier would go a long way. Meanwhile, while creating custom envs, we came up with this slightly hacky workaround: 
 - in our custom env component we include the "real" eslintrc.js and prettierrc.js files, and use the above mentioned config.raw, like: 
 ```ts
       node.useEslint({
        transformers: [
          (config) => {
            config.raw = eslint; // this it the imported eslintrc.js
            return config;
          },
        ],
      }),
```
 - in the workspace, each custom env is applied in a namespace using variants
 ```json
  "teambit.workspace/variants": {
     "{nestjs/*}": {
          "envs/nestjs-env": { }
    },
```
 - in each corresponding namespace dir we create a symbolic link to the env's "raw" file, e.g ```ln -s .eslintrc.js ../envs/nestjs-env/eslint/eslintrc.js```  and similar for prettier. 

 This, together with the written tsconfig.json, keeps the IDE happy enough and we don't have to keep multiple source of truths...

**Comment by itaymendel** [comment]
solved with the new `bit ws-config` command that syncs all tooling configs between your IDE and Bit components.
the `bit write-tsconfig` was a way for us to pilot this approach.
