### ISSUE TITLE
Type error when running bit tag

### ISSUE THREAD

**Issue by olivialeachclark** [teambit/bit#4715]
### Describe the bug
Specifying `latest` in a workspace variant teambit.dependencies/dependency-resolver rule throws an error with subsequent updates to that package.

### Steps to Reproduce
This is a pretty specific use case.

1. Define a workspace variant with a dependency rule specifying the latest version of a bit component. E.g.:

```
  "teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      "teambit.react/react": {}
    },
    "src/@buoy, !src/@buoy/buoy-theme, buoyhealth/test-utils": {
      "buoyhealth.extensions/buoy-react-env": {},
      "teambit.dependencies/dependency-resolver": {
        "policy": {
          "peerDependencies": {
            "@buoyhealth/common.buoy-theme": "latest"
          },
          "dependencies": {
            "@buoyhealth/common.buoy-theme": "-"
          },
          "devDependencies": {
            "@buoyhealth/common.buoy-theme": "-"
          }
        }
      }
    },
    "src/@buoy/buoy-theme": {
      "buoyhealth.extensions/custom-react-env": {}
    },
    "buoyhealth/extensions/": {
      "teambit.harmony/aspect": {},
      "defaultScope": "buoyhealth.extensions"
    }
  }
```

1. check that this rule is being applied correctly by inspecting a relevant component with `bit show` :white_check_mark:

```
├───────────────────┼───────────────────────────────────────────────────────────────────────────────────┤
│ peer dependencies │ @buoyhealth/common.buoy-theme@latest- (package)                                   │
│                   │ react-dom@^16.8.0 || ^17.0.0--------- (package)                                   │
│                   │ react@^16.8.0 || ^17.0.0------------- (package)                                   │
└───────────────────┴───────────────────────────────────────────────────────────────────────────────────┘
```

1. tag and export component(s) with this rule :white_check_mark: 
1. make an update to the module specified in the workspace dependency rule (in this case `buoy-theme`).
1. attempt to tag and export this update with `bit tag --all`.
1. note error:

```
✔ running pre install subscribers
Cannot read property '1' of null
```

this is stemming from the `hoist-dependencies.js` script (`groupByRangeOrVersion`, line 451).

1. Change the workspace variant rule from `latest` to a different version rule, e.g. `^0.0.2`
1. Run `bit tag --all` again
1. Tagging proceeds without error.

### Expected Behavior
Specifying `latest` as a dependency rule allows for subsequent updates to that module.

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.
[debug.log](https://github.com/teambit/bit/files/6956624/debug.log)

### Specifications
* Bit version: 0.0.479
* Workspace type: harmony
* Node version: 16.5.0
* npm / yarn version: 7.19.1
* Platform: mac

_for harmony workspace_

* relevant env: n/a
* relevant aspects: n/a

_for legacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
N/A

**Comment by itaymendel** [comment]
hi, instead of `latest`, please use `*`.

**Comment by olivialeachclark** [comment]
thanks @itaymendel - I just tried that, but it results in the same `Cannot read property '1' of null` error.

**Comment by olivialeachclark** [comment]
the `parseRange` function in semver-intersect.js is getting passed `*`, which leads to the error on the `var version` line

```
var regex = {
    condition: /^([<=>]+)?/,
    majorVersion: /\d+/,
    minMax: /^>=([\d]+\.[\d]+\.[\d]+(?:-[\w.]+)?) <=?([\d]+\.[\d]+\.[\d]+)$/,
    version: /([\d]+\.[\d]+\.[\d]+(?:-[\w.]+)?)$/,
    whitespace: /\s+/
};

function parseRange(range) {
    var condition = regex.condition.exec(range)[1] || '=';
    var version = regex.version.exec(range)[1];
    var prerelease = semver.prerelease(version);
    return { condition, prerelease, version };
}
```

**Comment by ivansky** [comment]
Hi all, I have the same issue, it somewhat related to packages that are imported as local components, and the items have `runtime` lifecycleType.

![screenshot_2021-11-24_at_15 28 04](https://user-images.githubusercontent.com/3938372/143231370-6b7099d6-6f02-4d49-9e8a-26b056eeea23.png)

**Comment by itaymendel** [comment]
env and build pipeline refactored. this is no longer relevant.
