### ISSUE TITLE
Bit.dev Installation in Shared Jenkins

### ISSUE THREAD

**Issue by pr447e** [teambit/bit#4720]
Hello,
       I am trying to install bit.dev in the shared jenkins pipeline and I am facing errors. It is saying BVM not found
![bvm not found](https://user-images.githubusercontent.com/86318477/128937655-a92e36eb-ced2-45ad-bd31-e0cc0de9cb55.PNG)

### Specifications
* Bit version:
* Node version:
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
Hi,

Please see this guide about how to set up BVM on your system - https://harmony-docs.bit.dev/reference/using-bvm especially the part about what to do if BVM is not recognized after installation.

**Comment by pr447e** [comment]
Hi, I have tried giving the path but I am trying to install bit.dev in shared Jenkins pipeline. I have used below script.
{
stage('bit.dev-export') {
steps {

sh 
npm i @teambit/bvm
PATH=$HOME/bin:$PATH
bvm install
bit config set anonymous_reporting false
bit config set analytics_reporting false
bit config set user.token 61acf220-025a-416f-8ab4-58a0b0924510
bit config del https_proxy 
bit add libs\bit-components\src\lib\*
bit s
bit compile
bit tag --all
bit config set https_proxy http://sub.proxy.att.com:8888
bit export
}
}

**Comment by benjgil** [comment]
hi @pr447e 
Is this issue still relevant?
If not can you please post what the eventual issue was and the resolution steps?
