### ISSUE TITLE
Module parse failed: Assigning to rvalue

### ISSUE THREAD

**Issue by PRO100Spike** [teambit/bit#4728]
### Description
i am getting the following error when I start 'bbit start'

```
Module parse failed: Assigning to rvalue (4:2)
File was processed with these loaders:
 * ../../.bvm/versions/0.0.481/bit-0.0.481/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
You may need an additional loader to handle the result of these loaders.
| $RefreshSetup$(module.id);
| 
> ---
| description: 'A Button component.'
| ---
```

### Specifications
* Bit version: 0.0.26
* Node version: v14.17.0
* npm / yarn version: 6.14.13
* Platform: Linux Mint 19.3 (Tricia)
* Bit compiler (include version):
* Bit tester (include version):

### Context and additional information
this error occurs when parsing .mdx files

**Comment by YacheLee** [comment]
Same issue here

**Comment by YacheLee** [comment]
Ok...It's my bad. I have solved it

@PRO100Spike Please use `bbit status` to show your bit component status.

After resolving all the issues, you can enjoy writing your document.

**Comment by pkhodaveissi** [comment]
Happens with YARN but not PNPM
