### ISSUE TITLE
bit how to install nested components

### ISSUE THREAD

**Issue by zhdxcz** [teambit/bit#4732]
### Description
for example ,I imported a bit component nested other bit components.
the nested  bit component in .dependencies  folder, because i usually dont change the nested  bit components ,so i dont push their to git remote ,so there will be a situation where other people can’t run the project after pulling the code in my project. 
In this case, I want to download the nested bit components separately, which command do I need to use?
By the way, i use mine private bit server.

### Specifications
* Bit version:14.8.8
* Node version:11.15.0
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
you can use the `--dependencies` option for `bit import`, which will brind all dependencies to your workspace.

**Comment by zhdxcz** [comment]
> you can use the `--dependencies` option for `bit import`, which will brind all dependencies to your workspace.



thank you for your reply.

This command will place all the nested components into my components folder(componentsDefaultDirectory), and I hope these nested components are still in the .dependencies(dependenciesDirectory) folder.
Because I generally don’t modify these nested components, I expect that these files will not be pushed in the gitlab repository.

So I hope another developer pulls the code and executes a command to directly install the nested components that the Bit component depends on, and place them in the specific dependenciesDirectory directory. like node_modules
