### ISSUE TITLE
Unable to install components from private registry during `bit tag --persist`

### ISSUE THREAD

**Issue by flyboarder** [teambit/bit#4735]
### Describe the bug
From slack dspacejs :

> my team is having trouble deploying our component library. we are running bit tag --persist, however it's throwing errors trying to import our fortawesome icons:
> component: base/ui/tabs@0.0.1
> ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/home/daniel/Library/Caches/Bit/capsules/ec485f8a915bf25eeb84d81852287b6d7dffac6b/node_modules/@fortawesome/react-fontawesome'
> ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/home/daniel/Library/Caches/Bit/capsules/ec485f8a915bf25eeb84d81852287b6d7dffac6b/node_modules/@fortawesome/react-fontawesome'
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/Compilation.js:1765:28
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:730:13
>     at eval (eval at create (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:273:22
>     at eval (eval at create (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:402:22
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:117:11
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:646:24
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:800:8
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:920:5
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/neo-async/async.js:6883:13
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:903:45
>     at finishWithoutResolve (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
>     at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
>     at eval (eval at create (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
> 
> Found 25 errors in 25 components
> 
> 
> ✖ Total 25 tasks. 23 succeeded. 2 failed. 0 skipped. Total errors: 37.
> I suspect the issue is because we are using premium icons. they're not free and have a private NPM registry in .npmrc:
> @fortawesome:registry=https://npm.fontawesome.com/
> //npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
> when we run bit install and work with these icons during development, it works fine. however, I suspect bit tag --persist isn't using the .npmrc credentials for some reason, so it doesn't know how to download these dependencies (and therefore throws the error saying the module doesn't exist)
> how can this be fixed? (edited) 

### Steps to Reproduce
1. Add Font Awesome private registry via `.npmrc` file in project root.
1. `bit install` -> working
1. `bit tag --soft` -> working
1. `bit tag --persist` -> fails with unable to resolve any fortawesome module

### Expected Behavior
Resolves registry using npmrc file

### Specifications
* Bit version:  0.0.481
* Workspace type: harmony
* Node version: 14.x
* npm / yarn version: 
* Platform: MacOS

**Comment by itaymendel** [comment]
If you configure `.npmrc` in your user-home directory the issue persists?

**Comment by Johnhong9527** [comment]
We set our own private bit sever address in .npmrc, but it cannot be downloaded during yarn install. What should we do?

**Comment by lhassis** [comment]
> 
> ### Describe the bug
> 
> From slack dspacejs :
> 
> > my team is having trouble deploying our component library. we are running bit tag --persist, however it's throwing errors trying to import our fortawesome icons:
> > component: base/ui/tabs@0.0.1
> > ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/home/daniel/Library/Caches/Bit/capsules/ec485f8a915bf25eeb84d81852287b6d7dffac6b/node_modules/@fortawesome/react-fontawesome'
> > ModuleNotFoundError: Module not found: Error: Can't resolve '@fortawesome/fontawesome-svg-core' in '/home/daniel/Library/Caches/Bit/capsules/ec485f8a915bf25eeb84d81852287b6d7dffac6b/node_modules/@fortawesome/react-fontawesome'
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/Compilation.js:1765:28
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:730:13
> > at eval (eval at create (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/tapable/lib/HookCodeFactory.js:33:10), :10:1)
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:273:22
> > at eval (eval at create (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/tapable/lib/HookCodeFactory.js:33:10), :9:1)
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:402:22
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:117:11
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:646:24
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:800:8
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:920:5
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/neo-async/async.js:6883:13
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/lib/NormalModuleFactory.js:903:45
> > at finishWithoutResolve (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:296:11)
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
> > at /home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
> > at eval (eval at create (/home/daniel/.bvm/versions/0.0.481/bit-0.0.481/node_modules/tapable/lib/HookCodeFactory.js:33:10), :15:1)
> > Found 25 errors in 25 components
> > ✖ Total 25 tasks. 23 succeeded. 2 failed. 0 skipped. Total errors: 37.
> > I suspect the issue is because we are using premium icons. they're not free and have a private NPM registry in .npmrc:
> > @FortAwesome:registry=https://npm.fontawesome.com/
> > //npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
> > when we run bit install and work with these icons during development, it works fine. however, I suspect bit tag --persist isn't using the .npmrc credentials for some reason, so it doesn't know how to download these dependencies (and therefore throws the error saying the module doesn't exist)
> > how can this be fixed? (edited)
> 
> ### Steps to Reproduce
> 
>     1. Add Font Awesome private registry via `.npmrc` file in project root.
> 
>     2. `bit install` -> working
> 
>     3. `bit tag --soft` -> working
> 
>     4. `bit tag --persist` -> fails with unable to resolve any fortawesome module
> 
> 
> ### Expected Behavior
> 
> Resolves registry using npmrc file
> ### Specifications
> 
>     * Bit version:  0.0.481
> 
>     * Workspace type: harmony
> 
>     * Node version: 14.x
> 
>     * npm / yarn version:
> 
>     * Platform: MacOS

In my case not even the install command works. I'm getting an unauthorized error and my registry is at the Azure Devops. Did you do some additional setup in order to work the install command?

**Comment by itaymendel** [comment]
you need to setup the yarnrc / npmrc on the CI server that installs the dependencies. not on the bit-scope.
