### ISSUE TITLE
how to test the functional react hook components?

### ISSUE THREAD

**Issue by robyn-57blocks** [teambit/bit#4737]
### Description
 I use a functional react component, which is useful for `react hook`.

my question is why `bit test` and `bit start` can pass the test and `bit tag` will report an error?

below is my code repo:
https://codesandbox.io/s/flamboyant-currying-nlze4?file=/src/App.js

### Specifications
![image](https://user-images.githubusercontent.com/87001542/129336298-8166b2fa-ccdf-4bc8-aa6f-674ed40e9de5.png)

![image](https://user-images.githubusercontent.com/87001542/129336466-935122b5-128e-450c-96b1-45c0fb6bbdef.png)

* bit version   : 1.0.133
* node version  : v14.17.1
* npm version   : 6.14.13
* yarn version  : 1.22.10
* platform: darwin

 how do you usually test functional react hook components?

**Comment by KutnerUri** [comment]
there are a lot of methods to test react hooks.

The most common is to ***test a react component using the hook***. (ie. write a wrapper for testing)

You can also look up the many articles explaining how to test hook. This looks promising:
https://github.com/testing-library/react-hooks-testing-library
