### ISSUE TITLE
ESlint on extended environments, useEslint (custom-node)

### ISSUE THREAD

**Issue by jbiskur** [teambit/bit#4738]
### Description
When trying to create a custom-node extension for example, I want to change the quotes to double quotes rather than single quotes. So I created a custom-node environment following the documentation for customizing node using Harmony.

`node.useEslint({
        transformers: [
          (config) => {
            config.addExtensionTypes(["_.ts","_.spec.ts"]);
            config.setRule("quotes", ["error","double"]);
            return config;
          },
        ]
      })`

adding the following in the node.compose I get errors when linting for both, single quotes and double quotes in the file when running `bit lint component` that is using the new environment.

So how can I solve this, as I do not see any documentation on using useEslint and usePrettier.

### Specifications
* Bit version: 0.0.483 (Harmony v15)
* Node version: v14.15.0
* npm / yarn version:  (npm 6.14.9, yarn v1.22.10)
* Platform: darwin

### Context and additional information
Started from empty repo and started following the tutorial on https://harmony-docs.bit.dev/getting-started/installing-bit

**Comment by GiladShoham** [comment]
you should also change the `@typescript-eslint/quotes` rule
for example:
in this case I disabled the default `quotes` rule, but you can also change them both, so you can replace
`config.setRule("quotes", "off");` with `config.setRule("quotes", ["error", "double"]);`
```js
node.useEslint({
        transformers: [
          (config) => {
            config.addExtensionTypes(["_.ts", "_.spec.ts"]);
            config.setRule("quotes", "off");
            config.setRule("@typescript-eslint/quotes", ["error", "double"]);
            return config;
          },
        ],
      }),
```
