### ISSUE TITLE
bit remove not removing multiple components after setting up with bit new

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#4739]
### Describe the bug
trying to remove a full folder structure with bit remove but get error message saying component was not found on the local workspace and need to track the component using bit add

### Steps to Reproduce
1. bit new react my-workspace
1. bit remove templates/* -d

### Expected Behavior
Should remove all components in a specific dir/namespace. Instead you have to do it one by one

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/13063165/129366945-25df49c1-ae2b-4e51-9909-c85d83e4e44e.png)

Bitmap is as follows
![](https://user-images.githubusercontent.com/13063165/129366980-a229243e-9c6f-4806-9335-db7431a32717.png)

### Specifications
* Bit version: latest
* Workspace type: (harmony/legacy) harmony
* Node version:
* npm / yarn version:
* Platform:

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
run `bit remove templates/** -d`

**Comment by davidfirst** [comment]
It's confusing, but when you use wildcards, you must wrap it with quotes `bit remove 'templates/*' -d`.
When you run the help command (bit remove -h) it mentions this.

**Comment by debs-obrien** [comment]
ohhh I see. We need to make that message more visible. My eyes went straight to the green and I didn't read the part in yellow.
