### ISSUE TITLE
Can not bind the volumes for bit-server from docker container

### ISSUE THREAD

**Issue by YacheLee** [teambit/bit#4741]
### Describe the bug
Can not bind the volumes for bit-server from docker container

### Steps to Reproduce
```sudo docker run -it -v /home/scott/remote-scope:/root/remote-scope -p 5000:3000 bitcli/bit-server:latest```

### Expected Behavior
Should be able to start the server with persistent volumes

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/8147977/129445687-941551c8-9f49-49af-a023-137bfa878155.png)

### Specifications
* Workspace type: harmony
* Platform: Ubuntu 20.04.2 LTS

**Comment by GiladShoham** [comment]
@guysaar223 and me will check it and update here

**Comment by itaymendel** [comment]
see solution here - #4965
