### ISSUE TITLE
line wrap feature for composition components on the overview page

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4743]
I think this feature can add **legibility**  to our component.
for example, there is a button component, and I want to display different types in a different line.
![image](https://user-images.githubusercontent.com/40735433/129523161-6919fbb8-2708-44d0-888f-2d327b43a2b5.png)

**Comment by KutnerUri** [comment]
ok, how do you suggest the syntax would look like?

**Comment by leslie555** [comment]
I think we can use a special component to achieve this function.  Or some other easy way for you to achieve
```
<div>
  <Comp1 /> 
  <Comp2 /> 
  <Comp3 /> 
  <LineWrappper />
  <Comp4 /> 
  <Comp5 /> 
  <Comp6 />
</div>
```

**Comment by KutnerUri** [comment]
yes, I can use a `<br/>` to make a new line, haha.
how would a developer indicate that some compositions would go into a separate line?

I guess we could have something like
```
export const Comp1 = () => {...}
export const Comp2 = () => {...}
export const Comp3 = () => {...}

export const Comp4 = () => {...}
Comp4.group = 'primary';
export const Comp5 = () => {...}
Comp5.group = 'primary';
export const Comp6 = () => {...}
Comp6.group = 'primary';
```

if we go with this syntax, we should probably follow the Story format and put it in a dedicated property, like:
```
// CSF -
Comp8.story = {
  group: 'secondary'
}
// supposedly our bit equivalent. too long though
Comp8.composition = {
  group: 'secondary'
}
```

**Comment by leslie555** [comment]
it's friendly for people who use SB in the past. There you go

**Comment by KutnerUri** [comment]
@itaymendel - what do you think?

**Comment by leslie555** [comment]
I have seen your solution, in `welcome.composition.tsx`, we can import a react component.
```
import React from 'react';
import { Welcome } from './welcome';

export const WelcomePage = () => <Welcome />;
```

**Comment by itaymendel** [comment]
we have decided not to intorduce this capability to the component-gallery.
with new envs you can essentially build your own docs template and support this feature for your componets.
