### ISSUE TITLE
Display issues in gallery Properties when using enums in propTypes

### ISSUE THREAD

**Issue by tylerwellswork** [teambit/bit#4752]
### Describe the bug
The bit.dev gallery has issues displaying enum types used as propTypes

### Steps to Reproduce
1. Have an enum type
1. Assign those enums to a propType

Example type

```js
export enum TypographyVariants {
    Headline1 = 'headline-1',
    Headline2 = 'headline-2',
}
```

Example component propTypes

```tsx
variant: oneOf([
    TypographyVariants.Headline1,
    TypographyVariants.Headline2,
])
```

On a full-screen window, the gallery will look like this:
![image](https://user-images.githubusercontent.com/88671860/129761836-5712d82b-b62c-45a5-94e9-3547c97ffdcf.png)

On a small window, it looks good:
![image](https://user-images.githubusercontent.com/88671860/129762928-7e24dbbb-547e-4392-b4d9-e88e2536e75a.png)

### Expected Behavior
I expect to see the full type on a wide screen, not truncated, without needing to horizontally scroll the TYPE column.

**Comment by odedre** [comment]
fixed and merged. should be deployed in the upcoming days
