### ISSUE TITLE
Autotagged & build dependencies

### ISSUE THREAD

**Issue by enrtama** [teambit/bit#4766]
### Description
Let's say that I have a  component called **Button** and I modify it and tag it. Another component **ButtonGroup** is  using this **<Button />** and therefore, it is also autotagged & build (this last one I see it happening).

My question is that when I use **ButtonGroup** in my frontend application, it does not have the latest **Button** component unless I specifically build it.

I thought autotagging meant that dependants components are autotagged & built and therefore they will pick up the latest versions.

### Specifications
* Bit version: 14.8.8
* Node version: 12.19.0
* npm / yarn version: 6.14.8
* Platform: linux
* Bit compiler (include version): bit.envs/compilers/vue@0.1.13
* Bit tester (include version): bit.envs/testers/jest@22.4.3

**Comment by GiladShoham** [comment]
It should use the latest button in your case.
Does your frontend is the same workspace as the one you tagged button and button group?
Or it's another workspace where you just install button group?
If you install button group in an empty folder what do you see in the dependencies in package.json?

**Comment by enrtama** [comment]
First of all thanks for the quick reply.

They are indeed in the same workspace.

When I install **button group** I see the latest version of **button** but it looks like the **dist** of **button group** contains an outdated build which is weird because when I autotag **button group** it also builds so I really do not know why the build is not correct.

**Comment by enrtama** [comment]
Solved by using out own compiler
