### ISSUE TITLE
how to write unit test when a component imported another bit component

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4767]
```
...
import Button, { ButtonGroup } from '@vungle/creativebuilder.ui.vun-button';

...
return (
   <ButtonGroup>
        <Button
          styles={styles}
          onClick={this.handleBold}
          type={isBold && 'primary'}
        >
          B
        </Button>
        <Button
          styles={styles}
          onClick={this.handleItalic}
          type={isItalic && 'primary'}
        >
          I
        </Button>
     </ButtonGroup>
)
...
```

when I `shallow` or `Mount` this component,  an error occurred
![image](https://user-images.githubusercontent.com/40735433/130170041-9a271022-9759-4e3e-83d8-87c7691b467c.png)

**Comment by GiladShoham** [comment]
When running bit show button-group do you see button in the dependencies?

**Comment by leslie555** [comment]
I have updated some info

**Comment by GiladShoham** [comment]
Yes but bit should have been handle this during compilation phase. What is your bit env?

**Comment by leslie555** [comment]
![image](https://user-images.githubusercontent.com/40735433/130379151-0595ec52-36e3-43d4-a035-172bb78e8903.png)
`vungle.creativebuilder/env/vun-react@0.0.17` is a plugin to enhance function so that we have the ability to access the global CSS. But I think it's not the plugins' business in there.

**Comment by GiladShoham** [comment]
can you please share your env code?

**Comment by leslie555** [comment]
@GiladShoham please click this link: https://drive.google.com/file/d/14r_VUaIHIqH4jc7O9k2t3giSwUtV7qmV/view?usp=sharing

**Comment by leslie555** [comment]
@GiladShoham any progress?

**Comment by itaymendel** [comment]
can't reproduce the issue.
