### ISSUE TITLE
in homepage of organization , there still display components  that I have removed

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4774]
if I click the component which I have removed, the new redirect page will show page not found
![image](https://user-images.githubusercontent.com/40735433/130171621-b5d75723-048b-423d-a39a-d76f7c3a9c2a.png)
![image](https://user-images.githubusercontent.com/40735433/130171863-cd29eec2-10b4-46b7-8786-bee944090c11.png)

**Comment by guysaar223** [comment]
fixed

**Comment by leslie555** [comment]
still have the problem @guysaar223

**Comment by guysaar223** [comment]
run this query to remove the components ids metadata:

https://symphony.bit.dev/graphql?variables=%7B%0A%20%20%22reportImport%22%3A%20%7B%0A%20%20%20%20%22componentsId%22%3A%20%5B%0A%20%20%20%20%20%20%22teambit.base-ui%2Finput%2Fbutton%22%0A%20%20%20%20%5D%0A%20%20%7D%0A%7D&query=mutation%20%7B%0A%20%20deleteComponents(ids%3A%22vungle.creativebuilder%2Fui%2Fvun-select%22)%0A%7D

@leslie555
