### ISSUE TITLE
bit faild to build with some Typescript Errors

### ISSUE THREAD

**Issue by morning-nuts** [teambit/bit#4775]
### Description
Trying to bit build for components, but it stopped when isolating components.
Errors in node modules. it worked well before..

### Specifications
* Bit version: 14.8.8
* Node version: 12.16.3
* npm / yarn version: npm 6.14.4
* Platform: Mac

### Context and additional information

```
node_modules/@apollo/client/core/types.d.ts:38:1 - error TS1128: Declaration or statement expected.

38 export type { QueryOptions as PureQueryOptions };

node_modules/@apollo/client/core/types.d.ts:38:13 - error TS1005: ';' expected.

38 export type { QueryOptions as PureQueryOptions };

node_modules/@apollo/client/react/types/types.d.ts:9:1 - error TS1128: Declaration or statement expected.

9 export type { DefaultContext as Context } from "../../core";

node_modules/@apollo/client/react/types/types.d.ts:9:13 - error TS1005: ';' expected.

9 export type { DefaultContext as Context } from "../../core";

node_modules/@apollo/client/react/types/types.d.ts:9:48 - error TS1005: ';' expected.

9 export type { DefaultContext as Context } from "../../core";

node_modules/@apollo/client/utilities/observables/Observable.d.ts:3:1 - error TS1128: Declaration or statement expected.

3 export type { Observer, ObservableSubscription, Subscriber, };

node_modules/@apollo/client/utilities/observables/Observable.d.ts:3:13 - error TS1005: ';' expected.

3 export type { Observer, ObservableSubscription, Subscriber, };

node_modules/@apollo/client/utilities/observables/Observable.d.ts:3:61 - error TS1109: Expression expected.

3 export type { Observer, ObservableSubscription, Subscriber, };
```

**Comment by KutnerUri** [comment]
can you provide more context? reproduction zip, etc.

> Bit version: 14.8.8
Is this happening in the legacy version of bit?

**Comment by morning-nuts** [comment]
I used bit-bin
https://www.npmjs.com/package/bit-bin

it worked well.. but suddenly it failed..

**Comment by KutnerUri** [comment]
I see. Consider upgrading to the new **Harmony** version of Bit. It's will probably support TS better, and it's a LOT faster.
https://harmony-docs.bit.dev/getting-started/installing-bit/
if you are using React, it should be pretty straightforward.

As for the types error, we haven't changed 14.x.x in a while.
Maybe `@apollo/client` released a version using new features of TS? In this case, you can try reverting to an older version, and see what happens.

**Comment by morning-nuts** [comment]
thank you! It was apollo/client version problem.
