### ISSUE TITLE
bit envs doesnt show all envs on a component

### ISSUE THREAD

**Issue by odedre** [teambit/bit#4787]
### Describe the bug
when running `bit status` I get the following output about a conflict in the component's envs:

```
 multiple envs (remove the old envs by setting them with "-" sign in the variants. see https://harmony-docs.bit.dev/aspects/variants#removing-aspects ): 
          teambit.symphony/envs/symphony-react@0.0.13, teambit.symphony/envs/node@0.0.6
```

but when I run `bit envs` or `bit envs <componentName>` I dont see any info about this conflict.

### Expected Behavior
I would expect these commands to show further info about the issue and possibly add suggestions on how to solve it.

### Specifications
* Bit version: 0.0.492
* Workspace type: harmony
* Node version: v12.18.2
* Platform: macos

**Comment by itaymendel** [comment]
irrelevant with recent changes to `bit env` command.
