### ISSUE TITLE
error TS2307: Cannot find module '@bit/rgautam.angular-tutorial.product-list'.

### ISSUE THREAD

**Issue by gautamshub** [teambit/bit#4790]
### Cannot find module Error
We are getting the following error on the [bit](https://bit.dev/rgautam/angular-tutorial/product-list).

**error TS2307: Cannot find module '@bit/rgautam.angular-tutorial.product-list'.**

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 14.8.8
* Workspace type: (harmony)
* Node version: 12.21.0
* npm version: 6.14.11
* Platform: Windows

Following the steps mentioned in the [tutorial](https://docs.bit.dev/docs/tutorials/bit-angular-tutorial) resulted in this error. After exporting the sample component on the BIT we are getting this error on the BIT console.

Kindly let me know if there is anything we are missing.

**Comment by GiladShoham** [comment]
I really recommend using the new Harmony version of bit, then using the new Angular integration - https://github.com/teambit/bit-angular

**Comment by gautamshub** [comment]
@GiladShoham - I'm getting the following error when I run the command `bit create ng-lib ui/my-button`.

error: component "teambit.angular/angular-v11@0.0.20" was not found on your local workspace.
please specify a valid component ID or track the component using 'bit add' (see 'bit add --help' for more information)

Kindly find the workspace.jsonc below and let me know if there are any issues.

`/**
 * this is the main configuration file of your bit workspace.
 * for full documentation, please see: https://docs.bit.dev/configuration
**/{
		"$schema": "",
		"teambit.angular/angular-v11@0.0.20": {},
		"teambit.workspace/variants": {
		  "*": {
			"teambit.angular/angular-v11@0.0.20": { }
		  }
		},
		"teambit.generator/generator": {
		  "aspects": [
			"teambit.angular/angular-v11"
		  ]
		},
	  
	  /**
	   * main configuration for component dependency resolution.
	  **/
	  "@teambit/dependency-resolver": {
		/**
		 * choose the package manager for Bit to use. you can choose between 'npm', 'yarn', 'pnpm'
		*/
		"packageManager": "npm",
		/**
		* If true, then Bit will add the "--strict-peer-dependencies" option when invoking package managers.
		* This causes "bit install" to fail if there are unsatisfied peer dependencies, which is
		* an invalid state that can cause build failures or incompatible dependency versions.
		* (For historical reasons, JavaScript package managers generally do not treat this invalid
		* state as an error.)
		*
		* The default value is false to avoid legacy compatibility issues.
		* It is strongly recommended to set strictPeerDependencies=true.
		*/
		"strictPeerDependencies": true,
		/**
		 * map of extra arguments to pass to the configured package manager upon the installation
		 * of dependencies.
		*/
		"extraArgs": []
	  },
	  
	  /**
	   * automate Bit workflow with Git.
	  */
	  // "@teambit/git": {
	  /**
		 * fetch dependency and component updates on `git pull`.
		**/
	  // "dependencyUpdateOnPull": true
	  // }
}`

**Comment by GiladShoham** [comment]
@ocombe Can you help with Angular here?

**Comment by itaymendel** [comment]
we've done much stability work around bit-angular.

the error in yoru workspace.json, you set `"packageManager": "npm",`. please reset it to how it was in the autogenerated teamplate. npm is not supported. this means that bit didn't know how to set the correct dependencies in place.
