### ISSUE TITLE
error "iframe must have src" (Chrome ext poper block)

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#4791]
A developer got this error, when opening the scope page.
The error prevents the scope page from loading, showing only the skeleton.

```
Iframe must have src or srcdoc property defined
```

After a short debug, we found it's happening because of this chrome extension: [Pop up blocker for chromeTm - poper block](https://chrome.google.com/webstore/detail/pop-up-blocker-for-chrome/bkkbcggnhapdmkeljlodobbkopceiche)

Disabling it or allowlisting bit.dev mitigates it.

TODO

* [ ] investigate why this is happening
* [ ] prevent browser from crushing when it happens

**Comment by LarsOlt** [comment]
Issue still exists

**Comment by KutnerUri** [comment]
I'm having trouble reproducing it, do you have any special configuration?

![Screen Shot 2022-01-10 at 13 55 37](https://user-images.githubusercontent.com/5400361/148762427-4da11b59-8991-4f24-9df6-6c06182ca9d3.png)

I'm thinking - the problem happens because the scope fails updating the main site, so there is no trigger to stop the skeletons. Maybe we can also stop them after 30 seconds? (or similar)

**Comment by LarsOlt** [comment]
> I'm having trouble reproducing it, do you have any special configuration?
> 
> ![Screen Shot 2022-01-10 at 13 55 37](https://user-images.githubusercontent.com/5400361/148762427-4da11b59-8991-4f24-9df6-6c06182ca9d3.png)
> 
> I'm thinking - the problem happens because the scope fails updating the main site, so there is no trigger to stop the skeletons. Maybe we can also stop them after 30 seconds? (or similar)

No special configuration on my end

**Comment by KutnerUri** [comment]
maybe it's happening in a combination of another extension?

**Comment by itaymendel** [comment]
bit moved away from this iframe structure, the issue is no longer relevant.
