### ISSUE TITLE
bit add shows a confusing error message when adding a component with the same name

### ISSUE THREAD

**Issue by odedre** [teambit/bit#4792]
### Describe the bug
when running bit add, I get the following error:

```
unable to add individual files outside the root dir (component/graph/ui/component-node) of ui/graph/component-node.
you can add the directory these files are located at and it'll change the root dir of the component accordingly
```

**the issue is that I have a component with a same name in a different scope.**

### Steps to Reproduce
1. in a multi scope workspace, copy a folder you previously tagged as a component
1. paste the folder in a different location that is being exported to a different scope
1. add the component with the same namespace as the original component

### Expected Behavior
you already have a component with the same name in a different scope. please choose a different name

**Comment by johnjspiteri** [comment]
Also getting this error... 

"unable to add individual files outside the root dir (source/application/shared/interfaces/auu/identity) of automotive/used-car-dealer/identity. you can add the directory these files are located at and it'll change the root dir of the component accordingly"

Which is forcing us to use hacky naming conventions as a workaround...

This interface and NGRX store package (attempting to use) are using the same namespace = "automotive/used-car-dealer"... with different scopes "interface-agency.interface" and "interface-agency.store"

"interface-agency.interface/automotive/used-car-dealer/identity"
"interface-agency.store/automotive/used-car-dealer/identity"

**Comment by sbland** [comment]
Related issue: https://github.com/teambit/bit/issues/4656

**Comment by sbland** [comment]
This was closed but doesn't seem to be resolved. @NitsanCohen770 is this not possible to fix?
