### ISSUE TITLE
syntax error when install and use my bit component in my none bit workspace project

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4804]
![image](https://user-images.githubusercontent.com/40735433/130755718-a5f95580-f0fb-4af1-a55e-02625f369a7d.png)
`dropdown`  is a bit component, onDocumentClick is an arrow function in this class component. I added a parser for it in .eslintrc like this `parser: 'babel-eslint'` in bit workspace. although this parser is deprecated, but it works. 

When I use this component as a 3rd-party component, It gave me an error like the pic.

**Comment by GiladShoham** [comment]
the babel-eslint has [babel loader as a peer dependnecy](https://github.com/babel/babel-eslint/blob/master/package.json#L32)
the host app should install it

**Comment by leslie555** [comment]
I resolved this problem by config babel in craco.config.js with ` ['@babel/plugin-proposal-class-properties', { loose: true }]`
```
  babel: {
    plugins: [
      '@babel/plugin-proposal-logical-assignment-operators',
      '@babel/plugin-proposal-nullish-coalescing-operator',
      ['@babel/plugin-proposal-class-properties', { loose: true }]
    ]
  }
```
