### ISSUE TITLE
Component file naming in PascalCase

### ISSUE THREAD

**Issue by pulkitvyas08** [teambit/bit#4813]
### Description
Bit requires the component file names to be in lowercase but I generally use PascalCase for the same. Is there any workaround to this?

### Specifications
* Bit version: 0.0.496
* Node version: 14.11.0
* npm / yarn version: 6.14.8
* Platform: Windows 10
* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
Another option is to use `bit move` command after create to move it to a folder with pascal name. 
about the file names inside the folder, you can just change them after the bit create if you want.
I don't think something here will be changed, so I'm closing this issue.

**Comment by davidfirst** [comment]
@pulkitvyas08 , the PR above changes the `--path` flag, as I described before.

**Comment by pulkitvyas08** [comment]
Got it. Thanks a lot 😄
