### ISSUE TITLE
Cant handle multiple line command / or line breaks in package.json command  with bit 0.0.491 (and ongoing)

### ISSUE THREAD

**Issue by Alphavader** [teambit/bit#4817]
### Describe the bug
The issue occures when you run `bit install` on version 0.0.491 (and ongoing)
Bit fails on Linking peer depdencies (compile). 
In my case "  react-spring@npm:9.2.4 "  failes to Link. (fails to build successfully)

When you look at the package json from react-spring/core you see the command:

`"scripts": {
    "postinstall": "node -e \"console.log('\\u001b[35m\\u001b[1mEnjoy react-spring? You can now donate to our open collective:\\u001b[22m\\u001b[39m\\n > \\u001b[34mhttps://opencollective.com/react-spring/donate\\u001b[0m')\""
  },`

  **When you remove the line-break "\\n"  - or the entire console,log - it does work with the 0.0496 and ongoing. 
  I cant tell why this issue occures, but it seems that (maybe under windows) - bit cant handle linebreaks on commands.** 

### Steps to Reproduce (maybe this works)
1. Install bit 0.0.491 (or newer)
1. install something with a peer depdency / dependency 
1. do a line break on a package.json command

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.491
* Workspace type: (harmony/legacy)  - harmony
* Node version: 16.7.0
* npm / yarn version: 7.20.3   yarn=  1.22.5
* Platform: Windows 10

_for harmony workspace_

* relevant env  = dev
* relevant aspects (react environment)

**Comment by GiladShoham** [comment]
can be reproduced by using
`bit install @react-spring/core`
The relevant breaking line script it [here](https://github.com/pmndrs/react-spring/blob/master/packages/core/package.json#L30)
This only happens with yarn, not with pnpm.
But seems that using yarn cli (v3.0.1 not via bit) it is working.
So need to see where exactly it's crash.
Some yarn logs when using bit install
```
# This file contains the result of Yarn building a package (@react-spring/core@virtual:32b57a8d93372a582cb2c3a35f17d39682d927a738a3ddd0cbd3de16cd438e588d6fc384135c88133c01988b368149937903fadac28ad8340d2ea7d15db5163b#npm:9.2.4::__archiveUrl=https%3A%2F%2Fregistry.npmjs.org%2F%40react-spring%2Fcore%2F-%2Fcore-9.2.4.tgz)
# Script name: postinstall

[eval]:1
console.log('[35m[1mEnjoy react-spring? You can now donate to our open collective:[22m[39m
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:84:7)
    at createScript (vm.js:258:10)
    at Object.runInThisContext (vm.js:306:10)
    at Object.<anonymous> ([eval]-wrapper:9:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at evalScript (internal/process/execution.js:80:25)
    at internal/main/eval_string.js:23:3
```

**Comment by Alphavader** [comment]
Yes - this was also my observation. Yarn install is working fine - bit install (with yarn) not. 
I dont have the old logs anymore. 

The state was "linking components"...
Then it goes over to react-spring/core@npm9.2.4  - failed when build.
Then the excact line where this console log is. (See react-spring / core - package.json) ( "postinstall" )

**Comment by JasonKleban** [comment]
Always good when a solicitation for donations breaks the users' whole environment.

**Comment by Alphavader** [comment]
> can be reproduced by using
> `bit install @react-spring/core`
> The relevant breaking line script it [here](https://github.com/pmndrs/react-spring/blob/master/packages/core/package.json#L30)
> This only happens with yarn, not with pnpm.
> But seems that using yarn cli (v3.0.1 not via bit) it is working.
> So need to see where exactly it's crash.
> Some yarn logs when using bit install
> 
> ```
> # This file contains the result of Yarn building a package (@react-spring/core@virtual:32b57a8d93372a582cb2c3a35f17d39682d927a738a3ddd0cbd3de16cd438e588d6fc384135c88133c01988b368149937903fadac28ad8340d2ea7d15db5163b#npm:9.2.4::__archiveUrl=https%3A%2F%2Fregistry.npmjs.org%2F%40react-spring%2Fcore%2F-%2Fcore-9.2.4.tgz)
> # Script name: postinstall
> 
> [eval]:1
> console.log('�[35m�[1mEnjoy react-spring? You can now donate to our open collective:�[22m�[39m
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
> SyntaxError: Invalid or unexpected token
>     at new Script (vm.js:84:7)
>     at createScript (vm.js:258:10)
>     at Object.runInThisContext (vm.js:306:10)
>     at Object.<anonymous> ([eval]-wrapper:9:26)
>     at Module._compile (internal/modules/cjs/loader.js:955:30)
>     at evalScript (internal/process/execution.js:80:25)
>     at internal/main/eval_string.js:23:3
> ```

Hey - any news? Can you reproduce this bug? Can I help with something?

**Comment by GiladShoham** [comment]
I'm pretty sure it's some bug with yarn programmatic api.
If you can reproduce it with yarn programmatic api without bit and open an issue in yarn repo (linked to here) that will be a huge help

**Comment by kapildeyyara2** [comment]
i am facing similar issue.. `bit install` is failing in `@react-spring/core`.
however if i do yarn add react-spring , then there is no problem. 

due to this, we are not able to export bit components as `bit install` fails everytime.

My current bit version is **v0.0.507**  
This issue **does not** occur in  **v0.0.435**


![image](https://user-images.githubusercontent.com/82197861/133722224-4abf69be-2804-40ae-9f63-d66492c9edbc.png)

**Comment by Alphavader** [comment]
> I'm pretty sure it's some bug with yarn programmatic api.
> If you can reproduce it with yarn programmatic api without bit and open an issue in yarn repo (linked to here) that will be a huge help

The problem here is, that `yarn` does work very well - but `bit install` not. 
Bit install uses yarn ?! So why does yarn fail then? 
What i want to encourage is that it does has to be a react-spring problem. You might reporduce the problem, when you break a line with "\\n" and it will fail then.

**Comment by zkochan** [comment]
Updating the Yarn packages in our dependencies fixes the issue: https://github.com/teambit/bit/pull/5132

**Comment by Alphavader** [comment]
Thanks - will try that one out!
