### ISSUE TITLE
TS4023 Exported variable '...' has or is using name '...' from external module 

### ISSUE THREAD

**Issue by dspacejs** [teambit/bit#4838]
### Description
This is my code:

```ts
import React from "react";
import { createNotificationContext } from "react-notification-provider";

interface Notification {
  children: React.ReactNode;
  title: string;
}

export const {
  NotificationProvider,
  useNotificationQueue,
  createMockNotificationQueue,
} = createNotificationContext<Notification>();
```

I'm getting the following error when running `bit tag`:

```
The following errors were found while running the build pipeline
Failed task 1: "teambit.compilation/compiler:TSCompiler" of env "teambit.harmony/node"
component: shohamgilad.tailwind-test/utils/notification@0.0.1
/home/daniel/Library/Caches/Bit/capsules/b183ddd8d8d678d1fb0f66a09312bd7a0c17e614/shohamgilad.tailwind-test_utils_notification@0.0.1/utils.ts:10:3 - error TS4023: Exported variable 'NotificationProvider' has or is using name 'ProviderProps' from external module "/home/daniel/Library/Caches/Bit/capsules/b183ddd8d8d678d1fb0f66a09312bd7a0c17e614/node_modules/.pnpm/registry.npmjs.org/react-notification-provider@0.6.0_react@17.0.2/node_modules/react-notification-provider/dist/index" but cannot be named.

10   NotificationProvider,
     ~~~~~~~~~~~~~~~~~~~~


Found 1 errors in 1 components
```

It works during testing/development, but not during the build. I can't see any errors with my syntax or anything, it should just work.

### Specifications
* Bit version: 0.0.499
* Node version: v14.17.1
* yarn version: 1.22.5
* Platform: Ubuntu 20.04.1 LTS

### Context and additional information
You can find reproducible code for this component here: https://github.com/dspacejs/react-tailwind-env/tree/main/tailwind-test/utils/notification

**Comment by davidfirst** [comment]
I checked it and it seems to be an issue with the react-notification-provider d.ts file, see my comment here: https://github.com/anthonyshort/react-notification-provider/issues/20#issuecomment-912545553
