### ISSUE TITLE
Command "new" is no available

### ISSUE THREAD

**Issue by Alcore97** [teambit/bit#4840]
Hey, i'm working on micro front end's technologies and i find Bit. I'm totaly newbie in this technology. I'm following the first tutorial and i found a few things that it shoudn't had to be. I attach some errors that i found. The first one is that i don't found the ""teambit.workspace/variants" in "workspace.jsonc" file. Later i found the things that u are seeing in the attatched image. Does anyone knows something? Thanks! 

PS: I posted the same issue in Slack on this link: [https://app.slack.com/client/TCC321BHR/CCBF6L9KJ/thread/CCBF6L9KJ-1629974793.004400](url). 

Thanks for helping me.

**Comment by davidfirst** [comment]
@Alcore97 , this URL doesn't point to anything. You're probably using the legacy version of Bit (did you install from npm?) which doesn't have the `bit new` command. If this is the case, you should install the Harmony version. 
See [this](https://harmony-docs.bit.dev/getting-started/installing-bit) for installation instructions.
