### ISSUE TITLE
eslint-plugin-import not working with Bit

### ISSUE THREAD

**Issue by debs-obrien** [teambit/bit#4844]
### Discussed in https://github.com/teambit/bit/discussions/4636
<div type='discussions-op-text'>

<sup>Originally posted by **dspacejs** July 27, 2021</sup>
I use `eslint-plugin-import` to verify packages I'm importing exist/are correct. It checks `package.json` to see if a dependency exists. See [this rule](https://github.com/konraddroeske/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md) for details.

However, because I'm installing dependencies with `bit install`, it means dependencies aren't populated in `package.json`. Therefore I can't use `eslint-plugin-import`. I don't want to disable it just so I can use Bit.

Is there a way to get this to work with Bit? </div>

**Comment by itaymendel** [comment]
we've looked into it. this lint rule is looking into `package.json` specifically. for this to work the rule itself needs to be updated with support for `workspace.jsonc`.

Regardless, i'm not sure how critical it is for Bit, as in Bit if a component does not import a package Bit will not list it as a dependency. I do think we need to have a proper flow for figuring our how to prune `workspace.jsonc` from unwanted/unused deps, but I don't think a lint rule is the way to go on this one.

**Comment by GiladShoham** [comment]
see also my comments [here](https://github.com/import-js/eslint-plugin-import/issues/2096#issuecomment-909058777)

**Comment by ljharb** [comment]
https://github.com/import-js/eslint-plugin-import/issues/2096#issuecomment-916261919
> the pattern you describe will break all tooling in the ecosystem that expects package.json to be present - in other words, you can only lint a node project, and it's not a node project unless there's a package.json.
> 
> The best option is to fix bit to follow node conventions instead of radically deviating from them.

I understand if this recommendation is too difficult for the project to accept, but while blunt it's still the truth.

**Comment by itaymendel** [comment]
sadly i don't see this issue getting resolved. i appreciate the hard work @ljharb is doing for keeping the `eslint-plugin-import` up and running.
we understand why `eslint-plugin-import` chose to use `package.json` as a dependency. while it is possible to use that tool in a Bit workspace, developers will loose the features and flexibility allowed by having their dependency managed in `workspace.jsonc`.

the only way this can be resolved is when/if we can find time to collaborate with the project maintainer and potentially find a way to pass a `dependencies` object to the plugin to use (a suggested solution, i'm unsure if it is relevant to the design/roadmap of `eslint-plugin-import`). however, this is a discussion which we should initiate with the plugin maintainers, not as part of this project.
