### ISSUE TITLE
Issue with bit add command

### ISSUE THREAD

**Issue by binitgutka** [teambit/bit#4854]
### Description
When I am trying to run the command `bit add libs/bit-components/src/lib/*`

I am getting following error

```
+ bit add libs/bit-components/src/lib/test-component libs/bit-components/src/lib/testComponent
error: component ID is invalid, please use the following format: [scope]/<name>

```

### Specifications
using inside the docker image 

https://hub.docker.com/r/bitteam/bit-docker

**Comment by itaymendel** [comment]
Hi,

I don't think you should be using that docker image locally for onboarding your componetns to Bit.

- this image is for running a remote bit server
- this image is running the old version of bit

please follow the instructions from this doc to setup your project - https://harmony-docs.bit.dev
and then run `bit add` for your components.

**Comment by binitgutka** [comment]
Hi, 
Sorry I forgot to mention, I am not working on the local, its on the jenkins pipeline I am writing the code to add and export the component.

**Comment by davidfirst** [comment]
In addition to what @itaymendel mentioned, you should add quotes around the path with the wildcard:
```
bit add 'libs/bit-components/src/lib/*'
```
otherwise, you let the shell interpret the wildcard and pass wrong values to Bit.
