### ISSUE TITLE
bit tag --persist doesn't work on GH action (when using npm registry for publishing)

### ISSUE THREAD

**Issue by ia3andy** [teambit/bit#4866]
### Describe the bug
`bit tag --persist` won't find existing version of other components on CI (**when using npm registry for publishing**: https://github.com/quarkusio/code.quarkus.io/blob/main/library/workspace.jsonc#L48-L65).

It works if I am doing the `bit tag --persist` on the same machine that did the `bit tag --soft`.
Also doing the `bit tag --soft` on the CI is starting back from 0.0.1.

It looks like the local machine is storing something regarding the published components that is not in the CI.

CI file:
https://github.com/quarkusio/code.quarkus.io/blob/main/.github/workflows/code-quarkus-library-publish-actions.yml

bitmap that was supposed to be persisted by the CI:
https://github.com/quarkusio/code.quarkus.io/blob/89f46462ba0faaf118acb714edf23bbad7b96af9/library/.bitmap

CI errors not finding other components:
https://github.com/quarkusio/code.quarkus.io/runs/3535105606?check_suite_focus=true

bitmap after doing the tagging locally:
https://github.com/quarkusio/code.quarkus.io/blob/main/library/.bitmap

**Comment by ia3andy** [comment]
cc @itaymendel

**Comment by itaymendel** [comment]
(logging here additional info from the slack conversation)

The CI setup in this thread does not `export` the tagged versions of components to a remote Bit server. Bit does create a version history for each component that is stored in a remote Bit server. When Bit finds a `.bitmap` file that requires a specific version of a component it will try to `import` it from a remote Bit server. In this case, as there is none, the process fails.

If using Bit for local component management there's no need for `tag` at all. When wanting to publish components to a registry you can use the `bit publish` command directly. However, I would recommend setting up remote Bit server to be able to sync component history, get visual discoverability of components and see each component changelog (this will not affect consumers, as they just fetch from your registry).

**Comment by itaymendel** [comment]
we will not solve this issue, as package-version is tied to component-version from bit.
set up a remote bit-scope to export components, to you use Bit's versioning feature.
this is the only way bit knows what was a past version of a component, so it's the way for it to determine the modified components and only version them.
