### ISSUE TITLE
Compositions tab says "no compositions"

### ISSUE THREAD

**Issue by MikaelColliander** [teambit/bit#4873]
### Describe the bug

Component has a composition-file but Compositions tab in the workspace ui says: "There are no compositions for this Component. Learn how to add compositions:"

Yet the compositions can be seen on the Overview tab and are available in Compositions full screen mode.

There is no preview available from the component card.

### Steps to Reproduce

1. Add a <component>.composition.tsx file, containing rendering code for the component, to component folder.
1.
1.

### Expected Behavior

Composition should be available in Compositions-tab content. In attached screenshot the compositions can be seen on the Overview tab.

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/2895442/132944149-e54e8367-45bb-4c30-92bb-3907439d0e96.png)

### Specifications

- Bit version: 0.0.506
- Workspace type: harmony
- Node version: 14.17.0
- npm / yarn version: npm v 7.20.5
- Platform: OSX

*for harmony workspace*
- teambit.react/react
- harmony

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by KutnerUri** [comment]
can you share a reproduction of the bug? just zip your workspace

**Comment by MikaelColliander** [comment]
Apparently the problem had to do with importing parts of a Storybook story to the compositions file. When putting the code straight in the composition file it works as expected.
