### ISSUE TITLE
Remote build fail on export

### ISSUE THREAD

**Issue by luk492** [teambit/bit#4877]
### Description

I ran into an issue where my remote version of the component is failing because I removed a file which it imports(by mistake). Now when I want to export(the fix to remove that import) I can't because my export command fails because the remote component has that import error.
How can I get out of this never-ending loop? Thank you 

### Specifications
Bit compiler: 3.1.70

* Bit version:
* Node version:
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
@davidfirst can you please help here?

**Comment by davidfirst** [comment]
>  I removed a file which it imports

Do you mean that you removed a component? Or you removed a file inside the same component?

In general, when you remove a component, which is a dependency of another component, the dependent won't work (and you get a warning before you remove saying so. you even required to use `--force` flag to do it). If this is the case, the only way is to re-create the dependent. It can't be fixed.

**Comment by luk492** [comment]
The file which is imported by this failing component is a tracked file from another component.

So I have a "constants" component, which has N number of enum files and I removed that enum file which was being imported in that second component which is now failing. 

It also came to my mind to recreate that missing file, but the problem is I can't run the export command because of that failing component on the remote.

**Comment by davidfirst** [comment]
@luk492 , maybe you can import that component to a new workspace/directory, re-create that file and export.

**Comment by luk492** [comment]
Could you please share some more detailed steps on how to do this?
Just want to make it clear, the component which is failing is the one on the remote. So whatever I do locally, I can't export because of that error

**Comment by luk492** [comment]
This is the error I'm getting when I try to export, tag, build...

isolating component - component1.dependencies/domain/customNamespace/0.12.1/dist/constants/Enum1.d.ts:1:15 - error TS2307: Cannot find module '@bit/customNamespace.constants/dist/Enum1' or its corresponding type declarations.

1 export * from '@bit/customNamespace.constants/dist/Enum1';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

.dependencies/domain/customNamespace/0.12.1/dist/domain/index.d.ts:10:10 - error TS2305: Module '"../constants/Enum1"' has no exported member 'Enum1'.

10 export { Enum1, Enum1DisplayNames } from '../constants/Enum1';
            ~~~~~~~~~~~~~~~~~~

.dependencies/domain/customNamespace/0.12.1/dist/domain/index.d.ts:10:30 - error TS2305: Module '"../constants/Enum1"' has no exported member 'Enum1DisplayNames'.

10 export { Enum1, Enum1DisplayNames } from '../constants/Enum1';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors.

**Comment by davidfirst** [comment]
@luk492 , what Bit version are you using?

**Comment by luk492** [comment]
14.8.8

**Comment by luk492** [comment]
Just an fyi, I didn’t tun any command with a force flag

**Comment by davidfirst** [comment]
@luk492 , ok, I see.

Are you able to create a new workspace and import the constant component, or you're getting an error doing so?
If you're able to import, try to add the missing file there, tag and export. Once done, go to your original workspace and update the constant component.

**Comment by luk492** [comment]
You mean to run “bit init” inside a new folder -> setup the config so it points to my remote(namespace) repo on bitdev and import just the “constants” component -> add the missing file -> tag -> export. And if that passes go back to original workspace and do a fresh “bit import” or “bit checkout latest —all”?

**Comment by davidfirst** [comment]
Exactly. Except you don't need to setup the config to point to your remote. Once you ran `bit init`, you can just import your remote component.

**Comment by luk492** [comment]
We weren't able to fix this like you said, so we ended up re-initializing  our bitdev workspace. It was a pretty tedious journey since we had to remove one component at a time from our remote bitdev repo(maybe it would be good to have a remove all option for the remote component. Or there is?) and then added all components one by one to the newly created bitmap in the workspace...

**Comment by davidfirst** [comment]
@luk492 , I'm sorry you had this experience. 
Just to keep in mind, if you ever need to do the same process, there is an option on bit.dev to delete the entire collection.
You can also use the CLi to delete components with wildcards and you have the option to delete the remote with `--remote` flag. (e.g. `bit remove my-scope/my-namespace/* --remote`).

About the .bitmap file, with the new version (Harmony) you can do `bit new --reset-new` which "reset .bitmap file as if the components were newly added and remove all model data (objects)".

**Comment by lukakajtes** [comment]
Thanks for the info. Didn’t try the wild card option. As for harmony, maybe we’ll upgade to that version because thats a pretty usefull option.

**Comment by luk492** [comment]
Thanks for the info. Didn’t try the wild card option. As for harmony, maybe we’ll upgade to that version because thats a pretty usefull option.
