### ISSUE TITLE
Built-in bundler support for html env rendering in bit

### ISSUE THREAD

**Issue by benjgil** [teambit/bit#4878]
### Description
Currently, anyone wanting to use the html env (teambit.html/html) needs to also add a config for the teambit.compilation/bundler in order for the html env's render to work in the local dev server
e.g. 
`
{
  "teambit.compilation/bundler": {
    "dedicatedEnvDevServers": ["teambit.html/html"]
  }
}
`

This is both unwieldy and can lead to frustration - the html env's docs do outline the requirement, but it's a core aspect in bit so we should take care of it natively.

### Describe the solution you'd like
Built-in support for this so that the html env dev has a dedicated dev server whenever it's used in a bit workspace.

**Comment by itaymendel** [comment]
spoke with benjy, this is no longer relevant
