### ISSUE TITLE
How do I declare typings.d.ts for ts compiler?

### ISSUE THREAD

**Issue by MikaelColliander** [teambit/bit#4881]
### Description
I want to be able to build/tag components that depend on font files - woff, woff2, ttf. Currently I get a lot of instances of this type of error when building:

![image](https://user-images.githubusercontent.com/2895442/133336057-ff22ea07-2102-4b1d-b4f6-269467873fbf.png)

I'm overriding tsconfig but I have no way of telling wether the configfile I'm trying to provide makes prolonged use of typings.d.ts that I've placed in the same folder. I can't get it working.

### Specifications
* Bit version: 0.0.506
* Node version: 14.17.0
* npm / yarn version:  7.20.5 / 1.22.11
* Platform: OSX
* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
See the usage of the useTypescript api here 

https://github.com/teambit/bit-lit
You can see it adds a d.ts files with declare modules

**Comment by MikaelColliander** [comment]
Thanks @GiladShoham. Your pointer helped me solve some problems as ts compiler aslo had problems finding name SvgrComponent (ts2304 Cannot find name), d.ts incorporation took care of that one. The font file problems (ts2307 Cannot find module), however, persist and might not be Bit related at all, although I have a npm build configuration that was setup earlier that work with the same typings.

**Comment by MikaelColliander** [comment]
I forgot to assign my env extension to the relevant components. Since I did that it all works.
