### ISSUE TITLE
missing space in bit-start output

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#4883]
when i run `bit start` i get this output:

```
ENVIRONMENT NAME                                    URL                                                 STATUS
teambit.harmony/aspect on behalf                    http://localhost:3300                               RUNNING
ofteambit.harmony/aspect, 
company.scope/envs/my-react
```

notice that it says `on behalf ofteambit.harmony/aspect`
there's a missing ` ` between "on behalf of" and the env name.

**Comment by KutnerUri** [comment]
I'm getting a different text, including the space 🤔  
<img width="712" alt="Screen Shot 2021-10-05 at 13 24 37" src="https://user-images.githubusercontent.com/5400361/136006023-be54026c-b175-4122-9592-e5d46337ec1c.png">

Which project are you getting this on?
It will be easy to fix once I find it
