### ISSUE TITLE
Missing (unwanted) dependencies when tagging

### ISSUE THREAD

**Issue by MikaelColliander** [teambit/bit#4894]
When I run `tag --all` Bit throws an error regarding missing dependencies `@storybook/addons`. Ideally I'd like a way to just exclude files that import `@storybook/addons` from a component, they are all `.stories.tsx` or `.stories.mdx`. This way i would imagine i'd also get rid of `@storybook/addon-<addon>` as a dependency for each of my components. How can I achieve this and still keep my file structure? 

![image](https://user-images.githubusercontent.com/2895442/134301643-3be2934e-dc15-4274-9d71-6906b2982e1b.png)

### Specifications
* Bit version: 0.0.511
* Node version: 14.17.0
* npm / yarn version: npm 7.20.5 / Yarn 1.22.11
* Platform: OSX

**Comment by MikaelColliander** [comment]
Adding the `*.stories.tsx` to `.gitignore` excludes the story-files from the `tag` process but I don't want to ignore them from version control only from Bit. Is there a .bitignore or any equivalent?

**Comment by itaymendel** [comment]
hi, Bit tracks all dependencies from all files so it can recreate a complete working environment for each component (for ci, `bit import` and other features).
dependencies from `stories` are marked as `dev-dependencies`, so it should not affect the consumption of your components.

you can see this by running `bit show` on your components.

**Comment by MikaelColliander** [comment]
From a demo provided by Teambit `bit-storybook` this is what I get form running `bit show my-component`. I added

`import { text, select } from "@storybook/addon-knobs";` to `my-component.stories.tsx`

![image](https://user-images.githubusercontent.com/2895442/134479990-115db4cd-a5b5-498c-b8cd-10d6b4ba3c3f.png)

**Comment by MikaelColliander** [comment]
Also, if you look at the original error output, what the webpack process fails to resolve is `@storybook/addons`. As far as I understand this package is solely used by Storybook for loading addons to Storybook. From Storybook Addons readme:

"Storybook Addons is a node module which is used to load custom addons to storybook.

It stores addon loaders, communication channel and other resources which can be used by storybook implementations where required."

Now, if I were to import my-component and it had a story, importing a specific Storybook Addon, I'm assuming that my Storybook configuration would have to load the addon at hand to be able to make use of it. I fail to see how it's inclusion would be helpful in a component Bit distribution.

**Comment by MikaelColliander** [comment]
I managed to shed some light on my problem. If I comment out these lines form `.storybook/manager.js` tagging of components runs its course:

```
import addons from '@storybook/addons';
import theme from "./sj-storybook-theme";

addons.setConfig({
  theme,
  showRoots: true,
});
```

This is the only reference to `@storybook/addons` in my entire project and it breaks `bit tag` command.

As I pointed out earlier, components with stories making use of `@storybook/addon-knobs` have that package listed as a dependency, not a devdependency.

**Comment by itaymendel** [comment]
> As I pointed out earlier, components with stories making use of @storybook/addon-knobs have that package listed as a dependency, not a devdependency.

Ok, here's a critical issue we should resolve. This should not be the case for how dependencies are calculated.

**Comment by MikaelColliander** [comment]
And also the reference to @storybook/addons seems irrelevant, when tagging, as it's an internal storybook configuaration module only.

**Comment by itaymendel** [comment]
use this example when using bit and storybook
https://github.com/bit-demos/bit-storybook
it shows how to handle dependencies
