### ISSUE TITLE
bit build error cause of component having the same version but different dependency's versions

### ISSUE THREAD

**Issue by chaddoy** [teambit/bit#4895]
### Description

Hi guys! I'm having issues with `bit build`. It will return the error message below and won't let me `npm install`

```
error: bit failed to build company.micro/carousel@0.0.19 with the following exception:
Command failed with exit code 1 (EPERM): npm install --no-save
Error: Command failed with exit code 1 (EPERM): npm install --no-save
    at makeError (/usr/local/lib/node_modules/bit-bin/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/bit-bin/node_modules/execa/index.js:112:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

I found out the issue is that one of my component's (carousel's) dependencies don't match but they're on the same version.

```
## showing diff for company.micro/carousel
--- Dependencies (0.0.19 original)
+++ Dependencies (0.0.19 modified)

* [ company.micro/carousel-arrow@0.0.10, company.micro/carousel-navs@0.0.11, company.micro/carousel-tip@0.0.11, company.packages/portal-theme@0.0.5, lodash@4.17.21, csstype@3.0.7 ]
* [ company.micro/carousel-arrow@0.0.10, company.micro/carousel-navs@0.0.11, company.micro/carousel-tip@0.0.11, company.packages/portal-theme@0.0.5, lodash@4.17.21, csstype@3.0.9 ]
```

Is there a way where I can select which dependencies (original or modified) to use?

Thank you in advance! :bow:

### Specifications
* Bit version: 14.8.8
* Node version: v14.16.0
* npm / yarn version: 6.14.11
* Platform: OSX
* Bit compiler (include version): bit.envs/compilers/react-typescript@4.0.0
* Bit tester (include version): bit.envs/testers/jest@22.4.3

**Comment by davidfirst** [comment]
You might be able to achieve what you need with `overrides`. Check this for more info: https://docs.bit.dev/docs/overrides
