### ISSUE TITLE
Where is Bit's custom path resolution configuration

### ISSUE THREAD

**Issue by yuanzhhh** [teambit/bit#4900]
### Description
Where is Bit's v15 custom path resolution configuration?

I tried to add configuration in package.json, but it did not take effect.
![](https://user-images.githubusercontent.com/9876819/134798178-48f2867b-9061-4096-b913-6125cf9fb4e4.png)
![截屏2021-09-26 下午3 28 16](https://user-images.githubusercontent.com/9876819/134798189-0b43ad91-8771-45f5-9800-11c262ac6777.png)

### Specifications
* Bit version: 0.0.511
* Node version: v14.17.3
* npm / yarn version: 6.14.13

**Comment by GiladShoham** [comment]
This is not supported any more in v15.
It's because any component in v15 is available with a package name (even before export).
So it's better to use the package name so it will be consistent in different projects/workspaces etc.

**Comment by yuanzhhh** [comment]
> This is not supported any more in v15.
> It's because any component in v15 is available with a package name (even before export).
> So it's better to use the package name so it will be consistent in different projects/workspaces etc.

I configured an alias in the webpack configuration, how is this compatible in bit?

![20210926170152](https://user-images.githubusercontent.com/9876819/134801140-c7bed915-2285-4dba-ae32-05de55a9ffde.jpg)

**Comment by GiladShoham** [comment]
you can configure a webpack alias in v15.
But this won't be enough to make bit really support it.
Bit won't recognize these dependencies, it will block you from tagging probably.
This kind of dependency won't work if you import your component into another project.

**Comment by yuanzhhh** [comment]
> you can configure a webpack alias in v15.
> But this won't be enough to make bit really support it.
> Bit won't recognize these dependencies, it will block you from tagging probably.
> This kind of dependency won't work if you import your component into another project.

Thank you for your reply, I understand what you mean

**Comment by hyoretsu** [comment]
@GiladShoham so it's purposefully not supported to enable anyone to download our components? I'm looking to use Bit with TypeScript aliases and Next.js (so I can't nest components or place assets in the same folder)
