### ISSUE TITLE
make capsule commands work on bare scope

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#4901]
I want to see capsules created for bare scopes using the capsule list command.
I think we should move the capsule commands out of the workspace into the isolator.
And use the component host instead of workspace directly.

**Comment by davidfirst** [comment]
@GiladShoham , I started implementing it in `capsule-cmd-isolator` branch. But there is an issue.
How do I get the scope path from the component-host? If my host is the workspace, how to do I get the scope instance?

**Comment by GiladShoham** [comment]
@davidfirst you can just use host.path to get it. 
if it's a workspace, why do you need the scope, it's like now? 
also you can get it from the workspace.scope

**Comment by NitsanCohen770** [comment]
This is now [implemented](https://github.com/teambit/bit/blob/master/scopes/component/isolator/capsule-list.ts).
