### ISSUE TITLE
can not display icon when export component to bit 

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#4906]
code ```<i className={`vun vun-${icon}`} />```

when I use version 0.0.4xx, it can display this icon correctly. But now just show a square, the current version is 0.0.507.
![image](https://user-images.githubusercontent.com/40735433/135247017-c85e79e0-3517-4c81-acdc-f5a48df20df5.png)

![image](https://user-images.githubusercontent.com/40735433/135246274-efcee13c-ba18-401a-92ac-1f6f2adaf716.png)

**Local env is ok， no matter which version**
![image](https://user-images.githubusercontent.com/40735433/135246888-b6c14394-d0a7-4b51-8199-196166d12c3a.png)

![image](https://user-images.githubusercontent.com/40735433/135246485-8fc6d6b2-c5bd-4752-81b9-f5b8d7421776.png)

**Comment by KutnerUri** [comment]
@leslie555 
are you saying it is broken in the scope, after tagging and exporting?

Can you share a reproduction?

**Comment by leslie555** [comment]
[wcp-temp.zip](https://github.com/teambit/bit/files/7334500/wcp-temp.zip)

path： ds/ui/vun-button
