### ISSUE TITLE
Bit start errors

### ISSUE THREAD

**Issue by conye9980** [teambit/bit#4910]
### Description
Having creating a new directory, I run `bit init --harmony` where I return that bit has initialised.
I then run  `yarn global add bit-bin `
then
`bit start`

And receive the following error. 

Cannot find module '@pmmmwh/react-refresh-webpack-plugin'
Require stack:

* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/extensions/ui/webpack/webpack.config.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/extensions/ui/ui.extension.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/extensions/ui/index.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/extensions/bit/manifests.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/extensions/bit/bit.manifest.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/extensions/bit/index.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/dist/app.js
* /Users/me/.config/yarn/global/node_modules/bit-bin/bin/bit.js`

-BVM Version - 0.0.26

* Bit version: 0.0.512
* Node version: 16.8.0
* yarn version: 1.13.0
* Platform: Mac OSx
* Bit compiler (include version): 
* Bit tester (include version):

**Comment by GiladShoham** [comment]
Why did you yarn add bit-bin?
This is the old version of bit.
You don't need it.
Also please run bit install inside bit workspace instead of yarn add/ npm install.
For now I would remove the bit-bin then remove node_modules and do only bit install.
You can start with bit new react my-workspace-name

**Comment by itaymendel** [comment]
please use the docs to get started with bit. bit-bin should not be a dependency for your project.
harmony-docs.bit.dev
