### ISSUE TITLE
Small error in Kitty example

### ISSUE THREAD

**Issue by jimmi-joensson** [teambit/bit#4913]
### Describe the bug
When visiting the Kitty example the image doesn't render

### Steps to Reproduce
1. Go to [Kitty](https://bit.dev/bit/examples/kitty?example=5df107a635c5d500126d8a8b)
1. See example

### Expected Behavior
Was expecting to see the cutest kitty.. 

### Additional context
Changing the import to `import * as image from '@bit/bit.examples.kitty'` fixed it for me

**Comment by GiladShoham** [comment]
fixed.
Thanks
