### ISSUE TITLE
Extend bit tag/versioning with Conventional Commit specification

### ISSUE THREAD

**Issue by pgangwani** [teambit/bit#4917]
### Description
As discussed over chat and exploration of bit, currently only limited options are available the way we release semantic versioned components in bit. I, as a developer, would like to see some automated versioning based on changes in component folders based on conventional commit.

What we do today is:

```
bit tag ---all 
```

```
bit tag compA --minor 
```

### Describe the solution you'd like
As practitioner of [conventional commit](https://www.conventionalcommits.org/) versioning in the projects and team, I would like to see the same in `bit tag` options for workspace so that developer should not guess if its minor or major or path but go with commit format and release version is automatically determined.
There is always a suggestion to pre-release before graduate the version to stable versions.
[Lerna's](https://www.conventionalcommits.org/) options are really I am fond in the practical SDLC.

What can we do tomorrow:

```
# by default all components so if --conventional-commits present --all can be optional
bit tag --conventional-commits --all

# pre release
bit tag --conventional-commits --conventional-prerelease

# graduate pre releases
bit tag --conventional-commits --conventional-graduate
```

### Describe alternatives you've considered
Currently I am still exploring to build sh utility myself before calling bit tag but not sustainable solution to hack the bitmap content.

### Additional context
By default, all components/folders should be scanned for the changes. And one command 

```
# pre release
bit tag --conventional-commits --conventional-prerelease

# graduate pre releases
bit tag --conventional-commits --conventional-graduate
```

Additionally, we can think of adding similar features as in [lerna options](https://github.com/lerna/lerna/blob/main/commands/version/README.md#--conventional-commits)

I would also like to see configuration to limit the tag from certain branches like [lerna branch glob](https://github.com/lerna/lerna/blob/main/commands/version/README.md#--allow-branch-glob)

**Comment by itaymendel** [comment]
A Git commit may affect many components and at the same time, affect each component differently.
this means that perhaps your commit was a "feature" but for one component it was just a patch.
when thinking about component-workfow you need to think about a per-component problem.

i don't see a solid way to integration conventional commits to bit at this time.
however, recently we have added complete schema-extraction support for components which we do plan on using for audomated semver analysis.

closing the issue, as i don't see this moving further.
