### ISSUE TITLE
bit server start issue in self hosted docker in kubernetes cluster (any load balancer setup)

### ISSUE THREAD

**Issue by pgangwani** [teambit/bit#4923]
### Describe the bug
While deploying self hosted bit-server in kubernetes env (GCP), ui doesnt work as static/* points to root of the load-balancer always.

### Steps to Reproduce
Access the README.md of https://github.com/pgangwani/bit-server-static-public-path-issue

### Expected Behavior
Server should be up and the respective static folder path should be either relative point to the same public as index.html or there should be runtime method to override:

```
PUBLIC_URL=/bit-dev bit start
```

### Screenshots, exceptions and logs
![Static assets goes 404](https://github.com/pgangwani/bit-server-static-public-path-issue/raw/main/Issue.png)

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.513
* Workspace type: (harmony/legacy) harmony (bit init --bare)
* Node version: 12.22.6
* npm / yarn version: npm
* Platform: mac os 

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

### Additional context
**[Update] 10/5**
Worked with @KutnerUri  on testing the suggested `ASSET_PATH` in `webpack.browser.config.ts` , which worked for setting publicpath for `static/`but got new cascaded issue into attention where `/graphql` gives 404

![Partially working](https://github.com/pgangwani/bit-server-static-public-path-issue/raw/main/Partially_working.png)
![Issue 2](https://github.com/pgangwani/bit-server-static-public-path-issue/raw/main/Issue_2.png)

### Related Pull Request
#4958

**Comment by KutnerUri** [comment]
We should probably use `process.env.ASSET_PATH`, it seems to be the default recommended by webpack:
https://webpack.js.org/guides/public-path/.

They also have the option of `publicPath: 'auto'`, it seems relevant.

**Comment by pgangwani** [comment]
> We should probably use `process.env.ASSET_PATH`, it seems to be the default recommended by webpack: https://webpack.js.org/guides/public-path/.
> 
> They also have the option of `publicPath: 'auto'`, it seems relevant.

`process.env.ASSET_PATH` didnt work when I did `ASSET_PATH=/bit-dev bit start`
We definitely need this override when deploying assets in cdn but if its deployed on same server, we can have relative path for  `static/*` but now it goes to root route (/) there is problem especially setup with load balancers or proxies.

**Comment by KutnerUri** [comment]
yes, the code needs some tweaking.
Do you want to try it locally and maybe make a PR? It will be much faster for you to test it locally with your setup, and we will handle it sooner.

I believe the relevant code is here -
https://github.com/teambit/bit/blob/1a66368a5e6bc34d62a766f1559c6f9fcab17e28/scopes/ui-foundation/ui/webpack/webpack.browser.config.ts#L34

I _think_ you can just replace it with:
```ts
publicPath: process.env.ASSET_PATH || '/';
```

setup might be as simple as
```bash
git clone https://github.com/teambit/bit.git
cd bit
rm -rf node_modules public/bit
bit install # this might take a long time
bit compile

# probably not needed:
# npm run build
# npm run build:types 
## OR
# npm run build:windows 

npm run dev-link bd
# OR
npm run dev-link:windows bd

# you will then be able to run:
bd -v
# output will be "last-tag 0.0.516"
# (unlike bit -v, which outputs "0.0.516"
```

**Comment by pgangwani** [comment]
@KutnerUri : I scratched my head already by trying few things with above steps by setting cmd link as `bit-local` , might be in other webpack files at the same place of `publicPath` . I wish I have deep knowledge of bit building blocks . I would just love to contribute. Believe me. May be you can help me later ?
For now, trying exactly the steps as you said and update here.

**Comment by afanan** [comment]
I pulled the latest bitcli/bit version: 0.0.555, but I still have the same problem. Is it resolved?

**Comment by KutnerUri** [comment]
This feature is too complicated. We tried to make it work with Pgangwani's PR, but it's not working in all edge cases. :/

**Comment by itaymendel** [comment]
unfornunatily, at this point we are not looking support this type of structure.
