### ISSUE TITLE
support npm as a package manager

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#4925]
At the moment only yarn and pnpm are supported.We should add npm support.

Commits on Nov 21, 2021
fix: update pnpm (#5081)

zkochan     committed   2 days ago

feat: add non-interactive update command (#5042)

zkochan     committed   2 days ago

sue by Unito

**Comment by itaymendel** [comment]
not prioritized for now. if we ever support npm, we will re-add this. no need to track this topic as its own issue.
also, haven't really got feedbacks of people wanting npm support.
