### ISSUE TITLE
EslintConfigMutator methods throw Invalid Options error

### ISSUE THREAD

**Issue by p-l-l** [teambit/bit#4939]
### Describe the bug
Some of the EslintConfigMutator methods are throwing Invalid Options error (see Screenshots section below for an example).
I was also not able to have `bit lint` command take into account the specified configurations when this error occurs.

I had this kind of error with the following methods so far:
`addPlugins`
`addOverrides `

### Steps to Reproduce
1. [Create a component](https://harmony-docs.bit.dev/getting-started/creating-components#quick-guide) for testing eslint config
1. [Create a custom environment](https://harmony-docs.bit.dev/aspects/react#create-an-extension)
1. In the main.runtime file of the custom environment, use the following snippet

```
react.useEslint({
  transformers: [
    (config) => {
       config.addPlugins(['react-hooks']);
       config.setRule('react-hooks/rules-of-hooks', 'error');
       config.setRule('react-hooks/exhaustive-deps', 'warn');

       return config;
    },
  ],
}),
```

1. I used this example to test invalid hook in ui/button

```
if (text !== '') {
  useEffect(() => {
    localStorage.setItem('formData', text);
  });
}
```

1. Run `bit compile` and `bit lint`

### Expected Behavior
The methods should pass specified values accordingly to the related eslint config properties, and
the `bit lint` command should work according to these specified values, and throw an error for
the rule `react-hooks/rules-of-hooks`

### Screenshots, exceptions and logs
Here is an example.
![image](https://user-images.githubusercontent.com/23360637/136462513-648ec8d1-1423-440a-9ecc-3e620d8db5a0.png)

### Specifications
* Bit version: 0.0.513
* Workspace type: harmony
* Node version: 16.9.1
* npm / yarn version: 7.24.0 / 1.22.10
* Platform: Windows 10
* relevant env => React
* relevant aspects => "teambit.harmony/aspect"

### Workaround
I can currently work around the problem when passing configs to the config.raw here is an example:

```
config.raw.config.overrideConfig.plugins = [
  'react-hooks'
];
```

**Comment by itaymendel** [comment]
you can set your own lint config when building your own react-env.
follow the link from here - https://bit.cloud/teambit/react/react-env
