### ISSUE TITLE
Adding imported component

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#495]
During bit add we should check if a folder path is a root dir of a component, if yes we should add the new files to this component and not as new component

**Comment by amitgilad3** [comment]
@itaymendel - can you please send me output for the following cases:
1. add to imported  component without specifying id
2. add to imported  component without specifying correct id

**Comment by itaymendel** [comment]
1. error - unable to add new files to the imported component [component ID] without specifying '--id'.
2. error - unable to add new files from the root directory of the imported component [imported component ID] to [component ID].
