### ISSUE TITLE
pre-released component installation fails with "Request failed '404 Not Found'" error

### ISSUE THREAD

**Issue by morteza-jamali** [teambit/bit#4964]
### Describe the bug
I tagged a react component with `--pre-release` option and exported it. I have already set the registry config to `@morajlab`. when i want to install the component in another project using yarn or npm, i get the following error:

```text
yarn install v1.22.11
info No lockfile found.
[1/4] Resolving packages...
warning @morajlab/ui-dev.react.util.style > glamor > fbjs > core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
warning react-cosmos > socket.io > debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
warning react-cosmos > @skidding/webpack-hot-middleware > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[2/4] Fetching packages...
error An unexpected error occurred: "https://node.bit.dev/@morajlab/ui-dev.react.util.style/-/@morajlab-ui-dev.react.util.style-0.0.1-0.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/vagrant/mytime/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I also executed the following commands:

```bash
yarn cache clean --force
rm -rf node_modules
rm yarn.lock
```

Other components(released) install successfully but pre-release doesn't.

### Steps to Reproduce
1. tag a component with `--pre-release` option
1. export it 
1. configure `@morajlab` as a scoped registry.
1. try to install the component with yarn or npm

### Expected Behavior
yarn or npm should install the component successfully.

### Specifications
* Bit version: 0.0.513
* Workspace type: harmony
* Node version: 14.17.6
* npm / yarn version: npm -> 6.14.15 , yarn -> 1.22.11
* Platform: ubuntu-focal

_for harmony workspace_

* relevant env
* relevant aspects

**Comment by itaymendel** [comment]
issue with pre-released fixed on our backend a while ago. closing the issue, as its no longer relevant.

**Comment by diakonos** [comment]
Hello, I am experiencing this issue as well. Release versions install fine, but pre-release versions fail with a 404 when downloading the tarball. Is there possibly a regression here?
