### ISSUE TITLE
got remote SSH server error instead of merge conflict

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#497]
after upgrading to production version of bit, exported to remote scope and got a merge conflict in the server, but I got only the generic ssh server error:
fatal: received an invalid response from the remote SSH server

STR:
1. download + extract [https://app.zenhub.com/files/79723839/755c8997-9f97-4866-bd82-24320875a763/download](https://app.zenhub.com/files/79723839/755c8997-9f97-4866-bd82-24320875a763/download)
2. yarn
3. bit export odedreuveny.r

**Comment by amitgilad3** [comment]
@GiladShoham - i created a remote scope on a remote vm and tried to reproduce this issue but was unsuccessful.
i will move this issue to the backlog until we deploy a new version of bit to bitsrc

**Comment by GiladShoham** [comment]
fixed on bitsrc side @davidfirst  @amitgilad3
