### ISSUE TITLE
How do I build bit I forked?

### ISSUE THREAD

**Issue by ZyJoey** [teambit/bit#4978]
### Description
Hello!
I forked bit and modified the source code. Now I want to build and publish it as a npm package on our own registry. But I don't know how to build it. I know install bit-harmony by BVM. I've researched the process that BVM install bit, however it too complicated. Is there an easier way to build it? 

### Specifications
* Bit version: 0.0.529
* Node version:  16.11.1
* npm / yarn version:  8.0.0
* Platform: mac os
* Bit compiler (include version): -
* Bit tester (include version): -

**Comment by itaymendel** [comment]
months ago we moved away from using npm as a way to install `@teambit/bit`, as the setting this up caused a lot of inconsistencies of sub-dependencies. to have full control over the flow, we opted to bundle an installation and ship it via a dedicated tool. this reduced a lot of inconsistencies and stability issues, and also improved the installation performance.
at this point in time, figuring out how to "revert" that and make bit publish-able (and install-able) from a registry is a complex task which we don't aim to solve.

you are allowed to make your changes for Bit as much as you need.
we built bit to be extendible, so you don't have to figure out building bit and re-publishing it. bit is using aspect-oriented-dev so you can essentially plugin and extend any part of bit with your own code.
this is similar to how we build the bit-angular setup - https://github.com/teambit/bit-angular 
when your extension is done, you essentially set it up in the `workspace.jsonc` (or `scope.jsonc`) file, and bit will load it to memory.
we are working on a guide for how to extend bit and customize it better for your needs.

if you are looking to have a modified version of bit, and not use bit's built-in extension system, you will need to build the installation package and build bvm to fetch your asset.
