### ISSUE TITLE
How to use custom tsconfig.json for TypeScript compiler?

### ISSUE THREAD

**Issue by Mishelles** [teambit/bit#4990]
### Description

I'm using Bit for create a component with a module for NestJS application. My component is written in TypeScript and has some decorators. I need to set `"experimentalDecorators": "true"` in the compilerOptions section of tsconfig file, because during compilation I'm getting this error:

```
error TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.

```

I have tsconfig.json in the root of my workspace:

```
{
    "compilerOptions": {
        "lib": [
            "es2019", "DOM", "ES6"
        ],
        "target": "es2015",
        "module": "commonjs",
        "declaration": true,
        "sourceMap": true,
        "skipLibCheck": true,
        "rootDir": ".",
        "esModuleInterop": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "strictPropertyInitialization": false,
        "noEmit": true,
        "strict": true,
        "moduleResolution": "node",
        "noImplicitAny": false,
        "removeComments": true,
        "preserveConstEnums": true,
        "resolveJsonModule": true
    },
    "exclude": [
        "dist"
    ]
}
```

But when I try to debug my env configuration, I see the following:

```
teambit.compilation/compiler

configured compiler: teambit.typescript/typescript (TypeScript @ 4.4.2)
compiler config:
{
  "compilerOptions": {
    "lib": [
      "es2019",
      "DOM",
      "ES6",
      "DOM.Iterable"
    ],
    "target": "es2015",
    "module": "commonjs",
    "jsx": "react",
    "declaration": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "outDir": "dist"
  },
  "exclude": [
    "dist"
  ]
}

```

The question is: can I somehow edit config for the TypeScript compiler? I suppose I should modify my worspace.jsonc for this, but have no idea how. Reading the docs didn't make it clear.

### Specifications
* Bit version: 15 
* Node version: 14.18.1
* npm / yarn version: 1.22.10
* Platform: Linux
* Bit compiler (include version):
* Bit tester (include version):

**Comment by elohmrow** [comment]
Hi @GiladShoham If you want a full example, I got to the same error at the `bit build` step here: https://docs.bit.dev/docs/tutorials/bit-angular-tutorial.  Changing tsconfig, changing vscode settings - neither has an effect, and `bit  env ...` shows default, as above.

**Comment by Mishelles** [comment]
Hi, after some research I ended up with this working solution. Now my extension is the following:
```
import { EnvsMain, EnvsAspect } from '@teambit/envs'
import { NodeAspect, NodeMain } from '@teambit/node'

const tsconfig = require('./tsconfig.json');

export class CustomNodeExtension {
  constructor(private node: NodeMain) {}

  static dependencies: any = [EnvsAspect, NodeAspect];

  static async provider([envs, node]: [EnvsMain, NodeMain]) {
    const customNodeEnv = node.compose([
      node.overrideTsConfig(tsconfig),
      node.overrideBuildTsConfig(tsconfig)
    ]);

    envs.registerEnv(customNodeEnv);

    return new CustomNodeExtension(node);
  }
}
```
I posted this example above but it didn't work for some reason because there was a wrong path to the tsconfig.json.
Workspace.jsonc remained the same:
```
"teambit.workspace/variants": {
    "my-scope/extensions/custom-node": {
           "teambit.harmony/aspect": {}
     },
    "components/": {
      "my-scope/extensions/custom-node": {},
    }
  }

```
@GiladShoham thank you for your help anyway.

P.S. @elohmrow could you post your custom node extension and workspace.jsonc?

**Comment by GiladShoham** [comment]
I still recommend using the `useTypescript` API, as the override one is deprecated.
Also in your case you don't need the merge with the tsconfig, you can just change whatever you want directly. it will be easier.
