### ISSUE TITLE
"require is not defined" with vue-virtual-scroll-list

### ISSUE THREAD

**Issue by marioesuc** [teambit/bit#5007]
### Description
I have a Vue component called `CategorySelect` that renders a huge list of labels in a scrollview, this caused the component to render extremely slow, so I used a library called [vue-virtual-scroll-list](https://github.com/tangbc/vue-virtual-scroll-list) which used to work perfectly, until I started using Bit to compile it (among other components of my library which work perfectly).

I can tag (and therefore build) and export the component with no issues, but it's when I import it into my client app that I'm getting the following:
![image](https://user-images.githubusercontent.com/17274178/139034299-65601f46-0508-4ad7-bca1-e3495253712b.png)

I did some test in my component removing the VirtualList part from the template and then it'll work fine, but I do need it. I've read this is caused because JS doesn't understand the `require()` function since it's only available in Node envs, so I'm guessing maybe there's something not being compiled correctly?

### Specifications
* Bit version: 14.8.8
* Node version: v14.17.3
* npm / yarn version: npm v6.14.13
* Platform: Linux
* Bit compiler (include version): bit.envs/compilers/vue@0.1.13
* Bit tester (include version): bit.envs/testers/jest@22.4.3

**Comment by itaymendel** [comment]
bit-legacy support for vue is being deprecated. we'll be re-writing vue support for bit-harmony later this year.
i'm closing this issue, as we can't provide support for this use case at the moment.
