### ISSUE TITLE
Sass - @use dependencies not being correctly identified

### ISSUE THREAD

**Issue by benjgil** [teambit/bit#5038]
### Describe the bug

Bit's import detection algorithm isn't managing to parse @use statements to identify the package being used, and fails on any imports which aren't purely the package name. 

For instance, when @use-ing a scss file from a bit component, whose package name is `@org/namespace.compA`, adding a use statement of `@org/namespace.compA/scss/someScssFile` produces a missing dependency error:
`
missing packages or links from node_modules to the source (run "bit install" to fix both issues. if it's an external package, make sure it's added as a package dependency):
          button.styles.scss -> ~@org/namespace.compA/scss/someScssFile
`

This also happens when @use-ing built-in sass modules such as sass:math or sass:color, presumably for the same reason that the algorithm identifies sass:math as a separate package, for which there's no installed node_modules.

### Steps to Reproduce
1. Ensure sass is installed to the workspace 
1. Add a scss file in a component, and add use "sass:math" at the top of the file
1. bit status or bit tag
1. missing dependency error should appear

### Expected Behavior
bit should understand when a use statement references a component sub-file or built-in module in sass files, and not throw a missing dependency error

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/67269267/140741340-911f0c00-8b78-4fe1-a803-c7e814520fed.png)

### Specifications
* Bit version: 0.0.555
* Workspace type: harmony
* Node version:
* npm / yarn version:
* Platform:

_for harmony workspace_

* relevant env
* relevant aspects

**Comment by itaymendel** [comment]
fixed. closing the issue.
