### ISSUE TITLE
Efficiency improvement - run commands only for components in ws that have been modified 

### ISSUE THREAD

**Issue by benjgil** [teambit/bit#5050]
### Description
Currently, when we run commands such as `bit build` in a bit workspace, the command is run against all bit components in the current workspace, without regard for whether they have changed since the last time they were built. 

This introduces redundant re-builds (or whatever the command is -> re-compilations for `bit compile` for example), and the time it takes to run on all components in the ws can be start to be debilitating for workflows of workspaces with larger (say >20) components.

### Describe the solution you'd like
Run the command only on components in the ws that have been modified.

* As a first stage, this can be a simple 'modified since last export'. If a component hasnt been modified, there's no need to re-build/compile/test/ etc.
* Second stage, if this doesnt add too much complexity to bit, is to check per command if the component has changed since the last time it was run. For instance, a component which _has_ been modified since it's last export, but _hasn't_ been modified since the last time `bit test` was run still doesnt need to be tested again. 

**NOTE:** it should be clear that "modified" here means that either the component itself _or any of its dependencies_ have been modified, as a dependency modification can certainly change the behaviour of a component itself.
This should essentially rely on the same 'modified' check made when running commands such as `bit status` or `bit tag`.

**Comment by itaymendel** [comment]
issue resolved and pushed. `bit build` is FAR faster and more efficient now :)
