### ISSUE TITLE
Info alert takes a long time to show after creating new component

### ISSUE THREAD

**Issue by JoshK2** [teambit/bit#5063]
### Describe the bug
When Bit server is running and you delete a component you get this info alert immediately:

![image (5)](https://user-images.githubusercontent.com/35892475/141794430-b4eb3414-2d7e-4410-8255-55c94e345b73.png)

But when you create a new component you get the alert after a long time, like 2 minutes:

![image](https://user-images.githubusercontent.com/35892475/141794579-287be686-4aeb-4ece-acb6-e05bd5884fa9.png)

### Steps to Reproduce
1. create a new workspace.
1. start bit server.
1. create a new component.

### Specifications
* Bit version: 0.0.561
* Workspace type: (harmony/legacy): harmony
* Node version: 12.22.0
* Platform: macos

_for harmony workspace_

* relevant env: teambit.react

**Comment by KutnerUri** [comment]
This is happening in larger projects, like https://github.com/teambit/bit-dev. The server takes a long time to update the browser (so the new component does not appear at all in the browser)

**Comment by JoshK2** [comment]
@KutnerUri I don't think bit-dev is a really big project. (Bit is a big project)
