### ISSUE TITLE
page can't work exactly while executing `bit start --dev`

### ISSUE THREAD

**Issue by mihuartuanr** [teambit/bit#5064]
### description
`bit start` & `bit start --dev` work on CLI，flag `--dev`  can't display well and show 

```
ReferenceError
exports is not defined
```

in browser.

others, page doesn't update while changing code to add new Tab following  "Extending Bit" section by executing `bit start` .Only delete `public` ,  execute `bit start` , new content displays.

how to hot update?

**Comment by itaymendel** [comment]
we had past issues with HMR for running bit in dev-mode. issue has been resolved in a separate task. closing this one, as its no longer relevant.

please update your Bit installation.
