### ISSUE TITLE
Test suite failed to run. Cannot find module 'react' from 'organization.login_ui_text-field@0.0.2/dist/text-field.spec.js'

### ISSUE THREAD

**Issue by codermaen** [teambit/bit#5070]
### Specifications
* Bit version: 0.0.547
* Node version: 16.13.0
* yarn version: 1.22.17
* Platform: mac os 12.0.1
* Bit compiler (include version): Default
* Bit tester (include version): Default

### Context and additional information
 
I used 'teambit.react/react' as the variant.
I created components with `'bit new'` command.
The `bit compile` is successful and the `bit link` is also successfull.
But when I try do '`bit tag --all --message "my messsage"`'

This error occures

✔ running pre install subscribers
✔ deduping dependencies for installation
...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 1...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 5...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 7...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 1...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 1...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 2...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 3...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 3...7eb26b40ea997e06bf9e397178213de5d5b07 |  WARN  @testing-library/react@12.1.2 requires a peer of react@* but none was installed.
...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 3...7eb26b40ea997e06bf9e397178213de5d5b07 |  WARN  @testing-library/react@12.1.2 requires a peer of react-dom@* but none was installed.
...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 3...7eb26b40ea997e06bf9e397178213de5d5b07 |  +50 +++++
...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 3...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 5Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/arundev/.pnpm-store
  Virtual store is at:             ../../../../Library/Caches/Bit/capsules/07c7eb26b40ea997e06bf9e397178213de5d5b07/node_modules/.pnpm
...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 5...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 5../../../../Library/Caches/Bit/capsules/07c7eb26b40ea997e06bf9e397178213de5d5b07/node_modules/.pnpm/registry.npmjs.org+core-js@3.19.1/node_modules/core-js: Running postinstall script...
...7eb26b40ea997e06bf9e397178213de5d5b07 | Progress: resolved 5../../../../Library/Caches/Bit/capsules/07c7eb26b40ea997e06bf9e397178213de5d5b07/node_modules/.pnpm/registry.npmjs.org+core-js@3.19.1/node_modules/core-js: Running postinstall script, done in 38ms

- - -
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
✔ teambit.component/isolator, create capsules network (completed in 3s)
  running build pipe for 1 environments, total 5 tasks         ✔ teambit.component/isolator, create capsules network (completed in 3ms)
  generated graph for env "teambit.react/react", seeders total: 3, graph total: 3
✔ executing pre-build for all tasks
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 363μs
✔ env "teambit.react/react", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 851ms
⠉⠙ teambit.pipelines/builder, running tasks (3/5). env "teambit.react/react", task "teambit.defender/tester:TestComponents"Det FAIL  ../../../../Library/Caches/Bit/capsules/07c7eb26b40ea997e06bf9e397178213de5d5b07/zero-pixels.login_ui_button@0.0.2/dist/button.spec.js
  ● Test suite failed to run

```
Cannot find module 'react' from 'zero-pixels.login_ui_button@0.0.2/dist/button.spec.js'
```

```
> 1 | import React from 'react';
    | ^
  2 | import { render } from '@testing-library/react';
  3 | import { BasicButton } from './button.composition';
  4 |
```

```
  at Resolver.resolveModule (../../../../../.bvm/versions/0.0.547/bit-0.0.547/node_modules/jest-resolve/build/index.js:306:11)
  at Object.<anonymous> (zero-pixels.login_ui_button@0.0.2/button.spec.tsx:1:1)
      at runMicrotasks (<anonymous>)
```

 FAIL  ../../../../Library/Caches/Bit/capsules/07c7eb26b40ea997e06bf9e397178213de5d5b07/zero-pixels.login_ui_login-form@0.0.1/dist/login-form.spec.js
  ● Test suite failed to run

```
Cannot find module 'react' from 'zero-pixels.login_ui_login-form@0.0.1/dist/login-form.spec.js'
```

```
> 1 | import React from 'react';
    | ^
  2 | import { render } from '@testing-library/react';
  3 | import { BasicLoginForm } from './login-form.composition';
  4 |
```

```
  at Resolver.resolveModule (../../../../../.bvm/versions/0.0.547/bit-0.0.547/node_modules/jest-resolve/build/index.js:306:11)
  at Object.<anonymous> (zero-pixels.login_ui_login-form@0.0.1/login-form.spec.tsx:1:1)
      at runMicrotasks (<anonymous>)
```

 FAIL  ../../../../Library/Caches/Bit/capsules/07c7eb26b40ea997e06bf9e397178213de5d5b07/zero-pixels.login_ui_text-field@0.0.2/dist/text-field.spec.js
  ● Test suite failed to run

```
Cannot find module 'react' from 'zero-pixels.login_ui_text-field@0.0.2/dist/text-field.spec.js'
```

```
> 1 | import React from 'react';
    | ^
  2 | import { render } from '@testing-library/react';
  3 | import { BasicTextField } from './text-field.composition';
  4 |
```

```
  at Resolver.resolveModule (../../../../../.bvm/versions/0.0.547/bit-0.0.547/node_modules/jest-resolve/build/index.js:306:11)
  at Object.<anonymous> (zero-pixels.login_ui_text-field@0.0.2/text-field.spec.tsx:1:1)
      at runMicrotasks (<anonymous>)
```

Test Suites: 3 failed, 3 total
Tests:       0 total
Snapshots:   0 total
Time:        1.041 s
✖ env: teambit.react/react, task "teambit.defender/tester:TestComponents" has failed
✔ env "teambit.react/react", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 48μs
⢂⠀ teambit.webpack/webpack, running Webpack bundler (1/1). zero-pixels.login/ui/login-form@0.0.1, zero-pixels.login/ui/button@0.0.2, zero-pixels.login/ui/text-field@0.0.2(node:6480) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /Users/arundev/.bvm/versions/0.0.547/bit-0.0.547/node_modules/@teambit/react/node_modules/postcss/package.json.
Update this package.json to use a subpath pattern like "./*".
✔ env "teambit.react/react", task "teambit.preview/preview:GeneratePreview" has completed successfully in 16s                 ✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running build pipe for 1 environments, total 5 tasks (completed in 44s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.defender/tester:TestComponents" of env "teambit.react/react"
component: zero-pixels.login/ui/login-form@0.0.1
  ● Test suite failed to run

```
Cannot find module 'react' from 'zero-pixels.login_ui_login-form@0.0.1/dist/login-form.spec.js'
```

```
> 1 | import React from 'react';
    | ^
  2 | import { render } from '@testing-library/react';
  3 | import { BasicLoginForm } from './login-form.composition';
  4 |
```

```
  at Resolver.resolveModule (../../../../../.bvm/versions/0.0.547/bit-0.0.547/node_modules/jest-resolve/build/index.js:306:11)
  at Object.<anonymous> (zero-pixels.login_ui_login-form@0.0.1/login-form.spec.tsx:1:1)
      at runMicrotasks (<anonymous>)
```

component: zero-pixels.login/ui/button@0.0.2
  ● Test suite failed to run

```
Cannot find module 'react' from 'zero-pixels.login_ui_button@0.0.2/dist/button.spec.js'
```

```
> 1 | import React from 'react';
    | ^
  2 | import { render } from '@testing-library/react';
  3 | import { BasicButton } from './button.composition';
  4 |
```

```
  at Resolver.resolveModule (../../../../../.bvm/versions/0.0.547/bit-0.0.547/node_modules/jest-resolve/build/index.js:306:11)
  at Object.<anonymous> (zero-pixels.login_ui_button@0.0.2/button.spec.tsx:1:1)
      at runMicrotasks (<anonymous>)
```

component: zero-pixels.login/ui/text-field@0.0.2
  ● Test suite failed to run

```
Cannot find module 'react' from 'zero-pixels.login_ui_text-field@0.0.2/dist/text-field.spec.js'
```

```
> 1 | import React from 'react';
    | ^
  2 | import { render } from '@testing-library/react';
  3 | import { BasicTextField } from './text-field.composition';
  4 |
```

```
  at Resolver.resolveModule (../../../../../.bvm/versions/0.0.547/bit-0.0.547/node_modules/jest-resolve/build/index.js:306:11)
  at Object.<anonymous> (zero-pixels.login_ui_text-field@0.0.2/text-field.spec.tsx:1:1)
      at runMicrotasks (<anonymous>)
```

Found 3 errors in 3 components

✖ Total 5 tasks. 4 succeeded. 1 failed. 0 skipped. Total errors: 3.

**Comment by itaymendel** [comment]
you need to set react as a `peerDep` for your project.
anyway, i also see that here you are using an old version of the base react setup. please use https://bit.cloud/teambit/react/react-env
