### ISSUE TITLE
Cannot  execute any bit command successfully

### ISSUE THREAD

**Issue by leslie555** [teambit/bit#5083]
Any command starting with bit is not working, bvm is working fine.
error info when executing bit command: `runtime: 'main' was not defined by any aspect`.
**OS: windows
bit version: I have tried 0.0.541, 0.0.565, 0.0.567**
![image](https://user-images.githubusercontent.com/40735433/142826805-8728826b-15dc-4508-9c22-4679245a8a9d.png)

**Comment by itaymendel** [comment]
Hi,

Which version of Bit you have installed, and what is the command you ran?

**Comment by leslie555** [comment]
I have updated some info

**Comment by leslie555** [comment]
It seems I can't use it every time you upgrade bit version. Then I have to upgrade my bit

**Comment by GiladShoham** [comment]
can you attach your debug.log file please?

**Comment by leslie555** [comment]
@GiladShoham Could you please tell me how to get the log or the path? Because the error info didn't provide any useful info.

**Comment by GiladShoham** [comment]
For Windows - %LOCALAPPDATA%/Bit/logs. If %LOCALAPPDATA% is not defined, user profile directory will be used instead of %LOCALAPPDATA%

**Comment by leslie555** [comment]
@GiladShoham Thanks, this is the log fil
[debug.log](https://github.com/teambit/bit/files/7605734/debug.log)
e.

**Comment by davidfirst** [comment]
@leslie555 , not sure why you get this error. Can you try creating a new dir in a different location, preferably on root C or D and then try `bit init` there?
Also, please open this file: `C:\Users\57block\AppData\Local\.bvm\versions\0.0.573\bit-0.0.573\node_modules\@teambit\harmony\package.json` and tell me what version it has.

**Comment by leslie555** [comment]
@davidfirst Now I have upgraded to` 0.0574`, and the version is `0.2.11` in the package.json file.

**Comment by davidfirst** [comment]
OK. The version is fine. Did you try running `bit init` on a new dir on the root C?

**Comment by leslie555** [comment]
Of course, I did. And somehow bit works fine currently

**Comment by GiladShoham** [comment]
@leslie555 might be that you had the legacy version installed before?
If everything works fine, can we close the issue?

**Comment by leslie555** [comment]
I never install the legacy version.  But I can close it currently.
