### ISSUE TITLE
when importing an environment without the -t/-c flag It doesn't get imported and I get  a weird error

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#509]
If I import an environment and then import it as a component, I get an error that bit looks for it in the bit.map file.

STR:
1. bit init
2. bit import bit.envs/compilers/react -c
3. bit import bit.envs/compilers/react 

* I got the following error:
fatal: the component bit.envs/testers/mocha-react@latest was not found in the bit.map file

**Comment by amitgilad3** [comment]
this issue is fixed on master branch 
closing issue

**Comment by amitgilad3** [comment]
this issue is fixed on master branch 
closing issue
