### ISSUE TITLE
bvm installation with yarn global doesn't work and doesn't add bvm to the commands.

### ISSUE THREAD

**Issue by its4zahoor** [teambit/bit#5090]
### Describe the bug
Installing `bvm` with yarn on Ubuntu (Linux) doesn't add `bvm` to the commands. 

```
yarn global add @teambit/bvm       // after completion, running bvm install will throw
```

Installing with `npm` works fine.

```
npm i -g @teambit/bvm             // after completion, running bvm install will work
```

`npm` creates a `/home/user/.bvm` directory which is necessary to run `bvm [commands]`

### Steps to Reproduce
1. Remove existing bvm, bit installation or start fresh Ubuntu installation
1. Install bvm with `yarn global add @teambit/bvm`
1. Run `bvm install` to install bit, it will throw `bvm is not a command | zsh: command not found: bvm`

### Expected Behavior
`npm` & `yarn` are personal preferences and alternatives, Installing with `yarn` shall work the same way as `npm` does. 

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/24554084/142996418-1f819540-c96c-482d-8943-62cf42828574.png)

### Specifications
* Bit version: N/A
* Workspace type: (harmony/legacy) N/A
* Node version: v15.7.0
* yarn version: 1.22.15
* Platform: 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```

### Additional context
The default terminal is `zsh`, it may be specific to zsh.

**Comment by GiladShoham** [comment]
Thanks for the issue.
This is not related to the `.bvm` folder. 
it's not even related to bvm or bit in anyway.
It's more about how you installed yarn, and whether yarn's global bin folder is in your path or not.
You probably need to add yarn's global bin folder to your path. something like add `export PATH="$PATH:$(yarn global bin)"` to your `~/.bash_profile`
read more about it here - https://stackoverflow.com/questions/40317578/yarn-global-command-not-working

**Comment by its4zahoor** [comment]
Thanks, @GiladShoham. I am not sure if it is specific to Ubuntu that I have to add to the path. Earlier I was using Windows 10, don't remember adding it to the PATH. I will add to PATH and check.
