### ISSUE TITLE
too many requests are being made (which causes very bad performance)

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#510]
this is related to 'getManyWithAllVersions' method, which as I understand from Ran we might won't need it.

The reason I implemented it back then was to resolve a case where you import v2 of a component, make changes and then export it to a new scope.
If you don't have all versions, you're going to get an error when exporting it to this new scope. (which makes sense, as the component is not complete, and a future user might want v1 of that component).

The 4 requests made above is because there are two scopes, and it goes twice per scope. (one for the specified version and second for all other versions).

**Comment by itaymendel** [comment]
irrelevant
