### ISSUE TITLE
Error while Tagging the component with typescript

### ISSUE THREAD

**Issue by uttam23** [teambit/bit#5106]
### Describe the bug
While trying to run the bit tag --all command for the first version of the component ,getting the following error .

⠀ **teambit.typescript/typescript, compile typescript components (1/1). base-ui/typography@0.0.1
✖ /Users/uttam/Library/Caches/Bit/capsules/346cf4e76103ef106c4d9d60dc6f8edc73d0edfe/base-ui_typography@0.0.1/styles.ts:13:14 - error TS2742: The inferred type of 'cssStyle' cannot be named without a reference to '.pnpm/registry.npmjs.org+jss@10.8.2/node_modules/jss'. This is likely not portable. A type annotation is necessary.
 export const cssStyle = createUseStyles({

});**

### Steps to Reproduce
1.using react-jss for css 
`import { variantConstants } from "./constants";
import { createUseStyles } from "react-jss";

const commonProperties = (...values) => {
  const [fontSize, fontWeight, lineHeight, letterSpacing] = values;
  return {
    fontSize,
    fontWeight,
    lineHeight: `${lineHeight}px`,
    letterSpacing,
  };
};
export const cssStyle = createUseStyles({
  /* Styles applied to the root element. */
  root: {
    margin: 0,
  },

  /* Styles applied to the root element if `variant="h1"`. */
  [variantConstants.H1]: commonProperties(42, 500, 56, "normal"),

});`

### Expected Behavior
This error should not be coming and components should be tagged .

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
![](https://user-images.githubusercontent.com/6542709/144059104-77d38763-2a6a-4b37-8c6b-d48b2e3ba4ff.png)

* Bit version: 0.0.562
* Workspace type: (harmony/legacy) : harmony
* Node version: v16.3.0
* npm / yarn version: 7.19.1
* Platform:  reactjs

_for harmony workspace_

* relevant env : teambit.react/react
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by ivansky** [comment]
I've just upgraded to latest bit
```
upgraded from version 0.0.559
current is now linked to version 0.0.577
```


and on both versions I have the same error. I didn't expect the issue to be created by someone else 20 hours ago,
so it looks like general typescript issue in bit.dev configuration.

Maybe it relates to https://github.com/microsoft/TypeScript/issues/29808#issuecomment-720910806

![Screenshot 2021-12-01 at 13 38 11](https://user-images.githubusercontent.com/3938372/144211220-997594ee-3ab0-4899-8182-cbf347bc0dc7.png)
![Screenshot 2021-12-01 at 13 42 33](https://user-images.githubusercontent.com/3938372/144211124-b154a6d8-2ed0-4f2b-87f4-30516362644e.png)

**Comment by ivansky** [comment]
I would imagine an example, but I am **not sure** if it's the reason.

module A
```ts
export function fnA() {
  return {
    anything: 'abc'
  }
}

// inferring type from implementation that does not come to declaration file
export const a = new ClassA<ReturnType<fnA>>;
```

module B
```ts
import { fnA } from 'moduleA';

export const b = fnA();
```

**Comment by GiladShoham** [comment]
We faced this issue as well, and we need to look into it.
Meantime, something that might work is to change from pnpm to yarn in the `workspae.jsonc` under 
```
"teambit.dependencies/dependency-resolver": {
    "packageManager": "teambit.dependencies/yarn",
```
It will be great if you can post here back if it solves the issue. so we can have more info about it.
Thanks.

**Comment by ivansky** [comment]
Hi @GiladShoham it does not help, it's already configured to yarn package manager from the very start.
It might be related to the structure of capsule packages, it's not flat.

**Comment by zkochan** [comment]
This looks like a node_modules folder created by pnpm though:

![image](https://user-images.githubusercontent.com/1927579/144224442-dad18410-1b7e-45c0-a212-db45e4bb5ced.png)

[The issue that you referenced](https://github.com/microsoft/TypeScript/issues/29808#issuecomment-720910806) is related to symlinks. pnpm uses symlinks to reference dependencies of packages. With Yarn I assume no symlinks will be created in the capsule.

**Comment by GiladShoham** [comment]
@zkochan I believe these are the symlinks created by bit link (between capsules of components from the workspace)

**Comment by GiladShoham** [comment]
I'm wondering if the case of @uttam23 yarn will solve the issue.
because in his case the types are from an external package and not from a component.

**Comment by GiladShoham** [comment]
@ivansky If you can help us create a small repo with mock code that reproduces your issue, it will be very helpful for us.

**Comment by GiladShoham** [comment]
Thanks, we will look into it soon.

**Comment by uttam23** [comment]
> "packageManager": "teambit.dependencies/yarn",

This worked out nicely . Able to build the component .Thanks

**Comment by GiladShoham** [comment]
Thanks for the update @uttam23 , appreciate it.
That indeed confirms my suspicions around it, which is related to the issue @ivansky referenced.
We will continue looking into it, see how what we can do about it, but it might not be an easy one.

**Comment by ivansky** [comment]
They look like different issues, first was just pnpm issue and the second one is about types are missing for some reason even with yarn.

**Comment by davidfirst** [comment]
I don't have a solution for this. I'm able to reproduce it with the repo provided by @ivansky . 
I'm unsure though that it's Bit's issues. Seems like it's happening in other monorepos. see here: 
https://github.com/microsoft/TypeScript/issues/42873
(btw, I tried adding `"baseUrl": "."` to the tsconfig.json as suggested in one of the comments, but it didn't help).

I don't think it's related to `import type`. It happens also when I remove the `type`. You can see the issue easily in vscode when you open the capsules root dir. (run `bit capsule list` to get the dir).
