### ISSUE TITLE
error "path already exist" when using bit create

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5107]
Getting this error:

```
harmony-evangelist git:master*  
❯ bit create react some/new-component
unable to create a component at "src/components", this path already exist
```

Technically the folder does exist, I just fails because it's empty.

```
harmony-evangelist git:master*  
❯ tree ./src 
./src
├── base-components.md
├── components
├── content
│   ├── bit-testimonials
│   │   ├── bit-testimonials.tsx
│   │   └── index.ts
```

### Expected Behavior
Should create new component without failing.

### Specifications
* Bit version:  0.0.572
* Workspace type: harmony
* Platform: MacOS

**Comment by itaymendel** [comment]
we prefer bit to fail in such cases. not pass/success.
