### ISSUE TITLE
`bit install` doesn't run the prepare and postinstall scripts from `package.json`

### ISSUE THREAD

**Issue by zkochan** [teambit/bit#5114]
### Steps to Reproduce
1. clone https://github.com/dtothefp/bit-exporter
1. run `bit install`

### Expected Behavior
The preinstall and postinstall scripts from package.json are executed

**Comment by itaymendel** [comment]
lets put this on hold at the moment and discuss it before implementing anything regarding package.json scripts.

**Comment by murat-getlocal** [comment]
I have also same issue. bit install doesn't run my prepare script in package.json
Note: The module is added from github. Prepare command should make dist folder but when I checked there is not.

**Comment by KutnerUri** [comment]
@zkochan - make sure to respect the `--ignore-scripts` flag, and also the following config (or Bit's equivalent for it)
```
npm config set ignore-scripts true
```
