### ISSUE TITLE
Calling bit build <component> --tasks runs 0 tasks

### ISSUE THREAD

**Issue by sbland** [teambit/bit#5118]
### Describe the bug
Attempting to run a single build task with CLI described here: https://harmony-docs.bit.dev/reference/cli-reference/#build doesn't seem to work.

### Steps to Reproduce
1. Run `bit build --list-tasks` returns:

```
Build Pipeline Tasks:
teambit.harmony/aspect:CoreExporter
teambit.compilation/compiler:TSCompiler
teambit.defender/tester:TestComponents
teambit.pkg/pkg:PreparePackages
teambit.preview/preview:GeneratePreview

Tag Pipeline Tasks:
teambit.harmony/application:build_ui_application
teambit.pkg/pkg:PackComponents
teambit.pkg/pkg:PublishComponents

Snap Pipeline Tasks:
teambit.pkg/pkg:PackComponents
```

1. Run `bit build--task teambit.harmony/aspect:CoreExporter` outputs:

```
✔ running pre install subscribers
✔ deduping dependencies for installation
...afc2b463e0d3534230a7e05ff29591d289c99 | +140 ++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /.pnpm-store
  Virtual store is at:             ../../../../Library/Caches/Bit/capsules/f4cafc2b463e0d3534230a7e05ff29591d289c99/node_modules/.pnpm
...afc2b463e0d3534230a7e05ff29591d289c99 | Progress: resolved 140, reused 139, downloaded 0, added 0
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
...afc2b463e0d3534230a7e05ff29591d289c99 | Progress: resolved 140, reused 140, downloaded 0, added 140, done
✔ teambit.component/isolator, create capsules network (completed in 2s)
  running build pipe for 1 environments, total 0 tasks
✔ teambit.component/isolator, create capsules network (completed in 12ms)
  generated graph for env "teambit.harmony/node", seeders total: 4, graph total: 4
✔ executing pre-build for all tasks
✔ executing post-build for all tasks
✔ teambit.pipelines/builder, running build pipe for 1 environments, total 0 tasks (completed in 17ms)
✔ teambit.pipelines/builder, build (completed in 2s)
the build has been completed. total: 0 tasks
```

I also tried `bit build --tasks Compile`  and `bit build--task teambit.harmony/CoreExporter`

### Expected Behavior
Should run the specified build task.

### Specifications
* Bit version:0.0.557
* Workspace type: harmony

**Comment by GiladShoham** [comment]
The core exporter is a special task only affects aspects in the bit repo itself.
Try with something else like GeneratePreview.
You also don't need to specify the aspect id

**Comment by sbland** [comment]
Thanks @GiladShoham that worked.
It did come up with another issue though. 
Running `bit build` fails on one of my tests(Another issue). I assume this is during the `TestComponents` step.
However running:
```
bit build --tasks CoreExporter
bit build --tasks TScompiler
bit build --tasks TestComponents
```
Gives the warning `No tests found, exiting with code 1`.

Is there anything I'm missing here in the build steps?
Thanks!

**Comment by davidfirst** [comment]
@sbland , maybe it's because it builds only new and modified components by default. Try with `--all` flag or enter the component-id you want to run the tests for.
