### ISSUE TITLE
Publish to Private NPM through bit-server

### ISSUE THREAD

**Issue by ReptoxX** [teambit/bit#5144]
### Description
It would be nice if the self-hosted bit server is able to automatically publish to an private npm registry.
So that people can use bit eject even on self hosted bit servers when setup correctly.

### Describe alternatives you've considered
I tried using teambit.pkg/pkg but its unintuitive and not usable across multiple projects, where people should be able to import and eject dependencies after making changes.

**Comment by itaymendel** [comment]
no looking to implement this feature for scopes. you can potentially use `bit sign` to run your entire pipeline on a scope-server, which will publish it as well. not as a separate flow.
