### ISSUE TITLE
How to ignore files? (.eslintignore)

### ISSUE THREAD

**Issue by LucasCaixeta** [teambit/bit#5145]
### Description
I created an extension to have the eslint config and added the config (https://harmony-docs.bit.dev/aspects/react/#create-an-extension):

```
react.useEslint({
        transformers: [
          (config) => {
            config.setRule('no-console', ['error']);
            config.setRule('react/jsx-props-no-spreading', 'off');
            config.setRule('max-len', [
              'error',
              {
                code: 120,
                ignoreUrls: true,
              },
            ]);
            return config;
          },
        ],
      }),
```

And I added in the workspace the variant:

```
  "teambit.workspace/variants": {
    "*": {
      "my.design-system/extensions/custom-react":{}
    }
  }
```

Now I have some folders that I want to ignore when I do `bit lint`
I created the .eslintignore with the files + folders but did not work.

Where can I add my files or folders to be ignored?

### Specifications
* Bit version: 0.0.582
* Node version: v14.18.1
* npm / yarn version: 8.1.1
* Platform: Mac

### Context and additional information
 --

**Comment by GiladShoham** [comment]
If I remember correctly the api at the moment supports ignoring specific file types but not specifif files / folders.
But I'll have to check it in the code.
What stuff do you want to ignore for example?

**Comment by LucasCaixeta** [comment]
For example, mdx files, or all files from this folder "custom-react"
![image](https://user-images.githubusercontent.com/408965/146055627-83500dcd-7c2a-4e3e-b130-5e8159f6909e.png)

And another thing is, in the file custom-react.main.runtime.ts, the " // react.overrideTsConfig(tsconfig),"  is not working, the overrideTsConfig is deprecated and is not documented there how to use the other option "useTypescript()"

![image](https://user-images.githubusercontent.com/408965/146055879-04c4f5e5-c2f2-4b9e-9965-3105ca0760b6.png)

**Comment by itaymendel** [comment]
the update eslint plugin support passing array of extensions to lint.
