### ISSUE TITLE
`bit sign` on the workspace for all un-built components

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#5147]
Currently, `bit sign` requires ids to sign. It was built to be used on a scope.
It can be useful though to run this command on the workspace and to find all components that were not built yet and run the build process for them.
This way, it's easy to snap/tag without the build process locally and let the CI run `bit sign` to complete the build process.

**Comment by itaymendel** [comment]
decided to keep `bit sign` a scope-only command. for workspace we'll implement a `bit ci` functionality.
