### ISSUE TITLE
support "bit create --env" to assign the env in the bitmap#config

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#5149]
It should work similar to `bit create --scope`, where the defaultScope is saved during the create process and then used later on.
In this case, it'll be saved in the new `config` section added to the .bitmap file, inside the envs aspect.

If this component has already another env configured in the workspace.jsonc#variants, then, it'll be added with a minus key to explicitly remove it. So then the user won't get two envs unexpectedly.

**Comment by itaymendel** [comment]
implemented.
