### ISSUE TITLE
bit start command failed throw error out of memory

### ISSUE THREAD

**Issue by chhpt** [teambit/bit#5150]
### Describe the bug
When init bit workspace in a project with lots of files, and run bit start command. It fails with the error: JS heap out of memory

![image](https://user-images.githubusercontent.com/19288423/145991298-00c1e707-fab9-41b8-a6c1-c6779419980f.png)

### Steps to Reproduce
1. bit start

### Expected Behavior
bit start successfully

### Specifications
* Bit version: 0.0.588
* Workspace type: harmony
* Node version: v12.22.7
* pnpm 6.15.0
* Platform: macOS Montery

_for harmony workspace_

* relevant env: no
* relevant aspects: teambit.react/react

**Comment by itaymendel** [comment]
author abandoned and never replied
