### ISSUE TITLE
Required label in properties section does not appear if the props has default value

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#5157]
### Describe the bug
If the props component are required and they have a default value, in properties section from Overview table, required label for properties doesn't appear. 

### Steps to Reproduce
1. Clone this repository [https://github.com/osstotalsoft/rocket-ui](url)
1. Start local server
1. Navigate to ExpandigText component and see property **title** and **showLessText** in the properties section. Title doesn't have a default values so the required label appears in UI, but for the showLessText prop which is required and also has a default values the required labe; isn't present in the UI

### Expected Behavior
Required label to be shown in Properties section for props which has default values

### Specifications
* Bit version: 0.0.588
* Workspace type: harmony
* Node version: 16.13.1
* npm  version: 8.1.2
* Platform: windows 10

**Comment by itaymendel** [comment]
irrelevant, as new api-ref tab is not affected with this issue.
closing the issue.
