### ISSUE TITLE
Properties section from Overview is missing when component directory contain a d.ts file

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#5158]
### Describe the bug
If component directory contains a d.ts file, the Properties section from Overview doesn't appear anymore. Only in local development. I have a javascript project and I want to have the d.ts file for IntelliSense

### Steps to Reproduce
1. Clone this repository [https://github.com/osstotalsoft/rocket-ui](url)
2. Start local server 
3. Check Button component which contains a d.ts file
4. Go to cloud server and notice the properties sections isn't visible for Button component https://bit.cloud/totalsoft_oss/rocket-ui/components/buttons/button

### Expected Behavior
Properties section to be shown when a d.ts file is present in the component directory.

### Specifications
* Bit version: 0.0.794
* Workspace type: harmony
* Node version: 16.13.1
* npm version: 8.1.2
* Platform: windows 10

**Comment by DCosti** [comment]
Hi! Do you have any updates on this issue? Thanks!

**Comment by itaymendel** [comment]
hi, we're moving the automated documentation flow to run with a schema extractor. you can already see this in the ui.
the flow you commented on is soon to be deprecated, so i'm closing the issue.
