### ISSUE TITLE
New bug with storybook and react typescript when building the components

### ISSUE THREAD

**Issue by Blazsoul** [teambit/bit#5169]
### Description
In this past week i am facing a new bug when building the components.
all the components i build that includes react failing to build with this react-router typescript error:

    node_modules/react-router/index.d.ts:151:74 - error TS1110: Type expected.
    
    151 declare type ParamParseSegment<Segment extends string> = Segment extends `${infer LeftSegment}/${infer RightSegment}` ? ParamParseSegment<LeftSegment> extends infer LeftResult ? ParamParseSegment<RightSegment> extends infer RightResult ? LeftResult extends string ? RightResult extends string ? LeftResult | RightResult : LeftResult : RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : ParamParseSegment<RightSegment> extends infer RightResult ? RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : Segment extends `:${infer Remaining}` ? Remaining : ParamParseFailed;
                                                                                 ~~~
    
    node_modules/react-router/index.d.ts:151:83 - error TS1005: '}' expected.
    
    151 declare type ParamParseSegment<Segment extends string> = Segment extends `${infer LeftSegment}/${infer RightSegment}` ? ParamParseSegment<LeftSegment> extends infer LeftResult ? ParamParseSegment<RightSegment> extends infer RightResult ? LeftResult extends string ? RightResult extends string ? LeftResult | RightResult : LeftResult : RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : ParamParseSegment<RightSegment> extends infer RightResult ? RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : Segment extends `:${infer Remaining}` ? Remaining : ParamParseFailed;
                                                                                          ~~~~~~~~~~~
    
    node_modules/react-router/index.d.ts:151:94 - error TS1128: Declaration or statement expected.
    
    151 declare type ParamParseSegment<Segment extends string> = Segment extends `${infer LeftSegment}/${infer RightSegment}` ? ParamParseSegment<LeftSegment> extends infer LeftResult ? ParamParseSegment<RightSegment> extends infer RightResult ? LeftResult extends string ? RightResult extends string ? LeftResult | RightResult : LeftResult : RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : ParamParseSegment<RightSegment> extends infer RightResult ? RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : Segment extends `:${infer Remaining}` ? Remaining : ParamParseFailed;
                                                                                                     ~
    
    node_modules/react-router/index.d.ts:151:96 - error TS1161: Unterminated regular expression literal.
    
    151 declare type ParamParseSegment<Segment extends string> = Segment extends `${infer LeftSegment}/${infer RightSegment}` ? ParamParseSegment<LeftSegment> extends infer LeftResult ? ParamParseSegment<RightSegment> extends infer RightResult ? LeftResult extends string ? RightResult extends string ? LeftResult | RightResult : LeftResult : RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : ParamParseSegment<RightSegment> extends infer RightResult ? RightResult extends string ? RightResult : ParamParseFailed : ParamParseFailed : Segment extends `:${infer Remaining}` ? Remaining : ParamParseFailed;
                                                                                                       
    Found 4 errors.

### Specifications 
* Bit version: 14.8.8
* Node version: 14.16.0
* yarn version: 1.22.10
* Platform: Storybook
* Bit react typescript (include version): 3.1.7(i tried 4 as well but it didnt help)

### Context and additional information
People suggests to update the typescript version in order to fix this issue, didn't work for me:
https://stackoverflow.com/questions/70395584/after-doing-npx-sb-init-react-storybook-node-modules-react-router-index-d-t

Much thanks

**Comment by itaymendel** [comment]
Hi, typescript support for legacy bit (14.8) is very limited. I suggest looking into migrating your components to the new version, as there's better support for it, as well as for easier storybook setup https://github.com/bit-demos/bit-storybook

**Comment by Blazsoul** [comment]
So basically your suggestion is to migrate to bit Harmony? 
is it going to affect the compiler it self? 
Right now i am kinda stuck because of this building bug. If there was a way to build it with no ts-check, it could save me in a situations like this.

Thanks

**Comment by LukeGarrigan** [comment]
Getting this issue, did you make any progress @Blazsoul

**Comment by Blazsoul** [comment]
I ended up moving to the harmony version and it fixed it, much less typescript errors there.
But the migration might take some time if you have a good amount of components

**Comment by LukeGarrigan** [comment]
My solution was to upgrade Typescript, moved from version ~3.9.3 to ~4.2.4
