### ISSUE TITLE
bit link issues typescript scss

### ISSUE THREAD

**Issue by GimpMaster** [teambit/bit#5180]
### Describe the bug
I'm having an issue where I have a repo with all my bit.dev components. In that same folder structure I have a create-react-app, almost like a simplified storybook that uses the components. Each component uses absolute bit/component imports to use another component instead of relative path as described in documentation.

For me to properly use these in my simple CRA I used bit link. However I also use scss files.

bit link creates the links through additional require (and sometimes import ) statements it seems.

For example some of my .scss file looks like this...

```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

@import '../../../../../../../src/components/chip/icon/style.scss';
```

While other scss files look like this

```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

module.exports = require('../../../../../../../dist/Label');
```

Also other issues I find is if a component has an index.ts file for all the exports from components, the link command doesn't seem to work very well either. For example if the index.ts file is like this

```
import View from './view/View';
import Page from './page/Page';
import Router, { RouteDetails as RouteDetails_, RouterConfig as RouteConfig_ } from './Router';
import Popup, { PopupProps as PopupProps_ } from './popup/Popup';
import Tabs from './tabs/Tabs';
import Tab from './tab/Tab';
import popupController from './popupController';
import Link from './link/Link';
import Box from './box/Box';

export type RouteDetails = RouteDetails_;
export type RouteConfig = RouteConfig_;
export type PopupProps = PopupProps_;
export { View, Page, Router, popupController, Popup, Tabs, Tab, Link, Box };
```

### Expected Behavior
It would be great if the bit link did a true symbol link instead of adding an extra layer of require / imports.

### Specifications
* Bit version: 0.0.595
* Workspace type: harmony (and legacy, i tried switching to harmony to fix this)
* Node version: 14.15.4
* npm / yarn version: yarn 1.22.5
* Platform: Windows

**Comment by GimpMaster** [comment]
Ok, I solved the reason why some (really just one) of my components had the an issue with .scss files using require() instead of import. That component had it's "mainFile": set as the .scss file instead of the .tsx file. Changing this fixed that issue.

I think right now my biggest issue is that all require() statements look inside a dist folder. Where some of my component's main files are index.ts you get a name clashing in the dist folder.

So two or three of them will be looking in `module.exports = require('../../../../../../../dist/index');`

**Comment by GimpMaster** [comment]
This is the other error i typically get

```
'index.tsx' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.  TS1208

    1 | /* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
    2 | 
  > 3 | module.exports = require('../../../../../../dist/index');
      | ^
```

**Comment by KutnerUri** [comment]
it seems you got to the solution by yourself.
To reiterate:

* only use absolute links (`import ... from '@teambit/base-ui.input.button`)
* only use exports via the main index.ts/js file.  
  (`import { popupController } from '@yourorg/scope.namepsace.component'`)
* css/scss doesn't work as main file 😢 
* if you use internal files, you will have troubles with dists, which is not fun.

for css - you have a couple of options:
1 - global styles via index file:
```ts
// index.ts
import 'global-styles.css'; // would also work for scss, less, etc
export {}
``` 

2 - style module via index file:
```ts
// index.ts
import styles from 'button.module.css'; // would also work for scss, less, etc

// explicitly export class name, for typescript validation
export const buttonClass = styles.button;
``` 

3 - scss variables from internal files:
Because scss is not compiled (yet) and all it's variables are static, it's ok to access the internal files directly.
⚠️ **Make sure** to use the `~` prefix, or else sass will look for relative path.
```scss
@import '~@teambit/base-ui.theme.colors/colors.module.scss';
// actual code that we use.
// all scss variables from colors.module.scss are now available in this file

// ...
```

**Comment by KutnerUri** [comment]
let me know if this answers your question, and re-open the issue if you still have problems. :)
