### ISSUE TITLE
my bit server Docker is  404

### ISSUE THREAD

**Issue by wugaoliang1116** [teambit/bit#5185]
![image](https://user-images.githubusercontent.com/24740506/147463561-32a95ac7-d012-4a40-9d23-6fa7669441b6.png)
![image](https://user-images.githubusercontent.com/24740506/147463640-2049d97a-57f7-4592-934a-7347cb7db99b.png)
![image](https://user-images.githubusercontent.com/24740506/147463651-d7021b74-1e3d-405c-8c53-8ea1bf0843cf.png)

**Comment by itaymendel** [comment]
ensure docker forwards the port correctly
