### ISSUE TITLE
Newly created react-components fail tests out of the box

### ISSUE THREAD

**Issue by patrickehansen** [teambit/bit#5191]
### Describe the bug
Any newly created react components with `bit create react-component` fail the only unit test it has right out of the box due to a mismatch between the template .spec file and the template composition.

### Steps to Reproduce
1. `bit init`
1. `bit install --type=peer react react-dom @testing-library/react`
1. `bit create react-component test/box`
1. `bit build`

### Expected Behavior
Unit tests in build should pass when we first create the component.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/33469379/147598531-07d4724c-47cb-455e-9c15-f1f982299fbd.png)

### Specifications
* Bit version: 0.0.595
* Workspace type: harmony
* Node version: 14.18.2
* npm / yarn version: 6.14.15
* Platform: win10

**Comment by debs-obrien** [comment]
Hi @patrickehansen , I just tested this on an already created project and the tests are working just fine. Can you make sure you have the correct env for the component.
`bit show test/box`

Try running `bit compile` and restarting the dev server `bit start` to see if that fixes it.

**Comment by patrickehansen** [comment]
![image](https://user-images.githubusercontent.com/33469379/147836947-85c1bb6a-612e-4600-aff8-be2f53fdc0b2.png)

`bit start` starts up the explorer just fine. 

box.spec specifies
```
  const { getByText } = render(<BasicBox />);
  const rendered = getByText('hello from Box');
  expect(rendered).toBeTruthy();
 ```

whereas the composition provides
`<Box>hello world!</Box>`

This happens for every component I create, regardless of workspace.
