### ISSUE TITLE
Having trouble using react-native-vector-icons, please help.

### ISSUE THREAD

**Issue by treasure616** [teambit/bit#5193]
### Description
Having trouble using react-native-vector-icons using bit harmony

### Specifications
* Bit version: 0.0.595
* Node version: v16.13.1
* npm / yarn version: 8.1.2
* Platform: Ubuntu
* Bit compiler (include version):
* Bit tester (include version):

### Context and additional information
```
ERROR in ./node_modules/.pnpm/registry.npmjs.org+react-native-vector-icons@9.0.0/node_modules/react-native-vector-icons/lib/create-icon-set.js 91:8
Module parse failed: Unexpected token (91:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|       return (
>         <Text {...props}>
|           {glyph}
|           {children}
 @ ./node_modules/.pnpm/registry.npmjs.org+react-native-vector-icons@9.0.0/node_modules/react-native-vector-icons/MaterialCommunityIcons.js 6:0-50 9:16-29

```

**Comment by arundevkv** [comment]
Same issue here. Any update?

**Comment by arundevkv** [comment]
Refer this. 
[https://harmony-docs.bit.dev/aspects/react-native/#compositions-issues](https://harmony-docs.bit.dev/aspects/react-native/#compositions-issues)
I think the third party libraries with Native code can't run by bit environment

**Comment by Saikedo** [comment]
Any news on this? This will end up posing huge limits if we cannot use 3rd party react-native libraries.

**Comment by benjgil** [comment]
Hi all,
this has now been resolved (since around feb'22) so you should be able to use react-native-vector-icons, as well as any other react-native-xyz packages, with the default react-native env
