### ISSUE TITLE
Help, how can i drop a version in remote scope

### ISSUE THREAD

**Issue by nelsonkent** [teambit/bit#5203]
### Description
I have exported a component version with the code from another component, which bit command should i use to delete this version?

### Specifications
* Bit version:14.8.8
* Node version:14.16.0
* npm / yarn version: yarn 1.22.10
* Platform: mac
* Bit compiler (include version): 2.0
* Bit tester (include version):

**Comment by itaymendel** [comment]
bit does not have a command to delete a version of a component. you may delete the entire component with `bit remove`.
