### ISSUE TITLE
Change links of imported component when its dependency is directly imported

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#521]
For example, a component is-string depends on is-type.
The component is-type is already imported and now a user would like to import is-string.

Currently, when importing is-string, it installs is-type as an npm package and links is-string to the package is-type.
We want is-string to be linked to the directly imported is-type component, so then changes of is-type will be reflected on is-string immediately.

**Comment by davidfirst** [comment]
There are two cases here:
1. when importing dependencies as bit-components.
The PR https://github.com/teambit/bit/pull/557 makes sure it works.
2. when importing dependencies as packages.
The solution is to write into the package.json of is-string the relative path of is-type (instead of the version), this way it won't install is-type as a package. 
The implementation would be similar to https://github.com/teambit/bit/issues/515

**Comment by GiladShoham** [comment]
@davidfirst  we also need to rewrite the symlink after it.
