### ISSUE TITLE
BVM Install fails with reason: unable to get local issuer certificate

### ISSUE THREAD

**Issue by chethanbr25** [teambit/bit#5213]
**BVM Installation fails with unable to get local issuer certificate**

Details of the error log
request to https://bvm.bit.dev/versions/dev/Windows_NT/0.0.595/bit-0.0.595.tar.gz failed, reason: unable to get local issuer certificate
FetchError: request to https://bvm.bit.dev/versions/dev/Windows_NT/0.0.595/bit-0.0.595.tar.gz failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (C:\Users\****\AppData\Roaming\npm\node_modules\@teambit\bvm\node_modules\node-fetch\lib\index.js:1461:11)
    at ClientRequest.emit (node:events:390:28)
    at TLSSocket.socketErrorListener (node:_http_client:447:9)
    at TLSSocket.emit (node:events:402:35)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by iamshrivishnu** [comment]
The issue is due to the certificate of [bvm.bit.dev](https://bvm.bit.dev/). The site uses certificate issue for [CDN](1275798196.rsc.cdn77.org) with alias as bvm.bit.dev. If the system is behind firewall and the firewall creates certificate (example would ZScalar as it would create a local certificate for each site accessed from the system protected from ZScaler). To resolve the issue the team can get the certificate for bvm.bit.com with CDN as the alias.

**Comment by fateeand** [comment]
> The issue is due to the certificate of [bvm.bit.dev](https://bvm.bit.dev/). The site uses certificate issue for [CDN](1275798196.rsc.cdn77.org) with alias as bvm.bit.dev. If the system is behind firewall and the firewall creates certificate (example would ZScalar as it would create a local certificate for each site accessed from the system protected from ZScaler). To resolve the issue the team can get the certificate for bvm.bit.com with CDN as the alias.

Can you please specify the details how to do it?
I have exactly the same case you mentioned (ZScaler).

**Comment by itaymendel** [comment]
set `bvm config set strict-ssl false` to resolve this issue

**Comment by GuySurname** [comment]
> set `bvm config set strict-ssl false` to resolve this issue

Setting this results in `request to https://api.v2.bit.cloud/graphql failed, reason: getaddrinfo ENOTFOUND api.v2.bit.cloud`

Is there another recommended solution for this use case?
