### ISSUE TITLE
bit init -d flag isn't working correctly

### ISSUE THREAD

**Issue by h3nk42** [teambit/bit#5224]
### Describe the bug
running following command in an empty directory:
 `bit init -d bit/{scope}/{name}`
 with any string as argument is generating a workspace.jsonc file that does not have a the top-level defaultScope entry

### Specifications
* Bit version: 0.0.595
* Workspace type: harmony
* Platform: macos

**Comment by itaymendel** [comment]
the `-d` flag is not relevant for `defaultScope`, this is for `defaultDirectory`.
