### ISSUE TITLE
Bit isn't able to track files beginning with a dot

### ISSUE THREAD

**Issue by h3nk42** [teambit/bit#5235]
### Describe the bug
For our Bit components we want to track .editorconfig files, so that import settings are getting overwritten just inside of the Bit component folder. The issue is that even inside a non git directory ( no .gitignore file existent ) bit doesnt track files that begin with a dot ( .xx ) 

davidfirst wrote this:
https://github.com/mrmlnc/fast-glob#dot
by default, the glob package that Bit is using, doesn't return files that start with dot.

### Steps to Reproduce
1.  create directory for a component with .editorconfig file inside
1. track component via bit
1. bit show <comp id> 
1. youll see bit wont track the file

### Expected Behavior
bit tracks files like .editorconfig

### Specifications
* Bit version: 0.0.595
* Workspace type: harmony
* Platform: macOs

**Comment by davidfirst** [comment]
@GiladShoham , @itaymendel , any rejections about tracking files that start with dot? by default we don't track them.

For my reference, here is the change needed for it:
```
--- a/src/consumer/component-ops/add-components/add-components.ts
+++ b/src/consumer/component-ops/add-components/add-components.ts
@@ -962,6 +962,7 @@ function validateNoDuplicateIds(addComponents: Record<string, any>[]) {
 export async function getFilesByDir(dir: string, consumerPath: string, gitIgnore: any): Promise<ComponentMapFile[]> {
   const matches = await globby(dir, {
     cwd: consumerPath,
+    dot: true,
     onlyFiles: true,
   });
```

**Comment by GiladShoham** [comment]
No rejection from my side

**Comment by davidfirst** [comment]
Implemented in the PR above.
