### ISSUE TITLE
Lanes issue: failed adding or updating a .bitmap record due to duplicate file

### ISSUE THREAD

**Issue by sunil-sandhu** [teambit/bit#5238]
### Describe the bug
Received the following error: 

```
sunny@192 comp-ext % bbit switch sunil
failed adding or updating a .bitmap record of teambit.blog-content/component-extendability@2198b68e0ecfead506b1283d08aa27bdea611386. the following files are duplicated sunil-notes.mdx, sunil-notes.mdx
This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues
```

I believe this occurred because I was working on a separate 'sunil' lane and had created a file. Then I switched back to the 'main' lane, but the file I had created remained. Then when I switched back to the 'sunil' lane, I received the aforementioned error. I tried deleting the file (while in the 'main' lane), and was - then - able to switch back to the 'sunil' lane with no issue.

### Steps to Reproduce
1. Open up a workspace
1. Create new lane
1. Create file
1. Switch to 'main' lane
1. Switch to whatever your new lane is called

### Expected Behavior
If while working on lane A, I switch to lane B and create a new file, when I switch back to lane A, I would not expect to see the new file.

### Screenshots, exceptions and logs
```
sunny@192 comp-ext % bbit switch sunil
failed adding or updating a .bitmap record of teambit.blog-content/component-extendability@2198b68e0ecfead506b1283d08aa27bdea611386. the following files are duplicated sunil-notes.mdx, sunil-notes.mdx
```

### Notes
I was working in a fresh workspace that only had this package imported: https://bit.dev/teambit/blog-content/component-extendability. There were two lanes: 'main', 'sunil'.

### Specifications
* Bit version: 0.0.595
* Workspace type: Harmony
* Node version: 16.13.1
* npm / yarn version: 8.1.2
* Platform: Mac Catalina 10.15.7

**Comment by luvkapur** [comment]
Fixed in https://github.com/teambit/bit/pull/5226
