### ISSUE TITLE
Cannot install npm dependencies with bit in enterprise network

### ISSUE THREAD

**Issue by guy2002k** [teambit/bit#5248]
## Expected Behavior
`bit install` will install the dependencies from the private registry in enterprise network.

.npmrc

```
registry=https://my-private-registry/...
strict-ssl=false
```

## Actual Behavior
* Yarn package manager error: self signed certificate in certificate chain at ClientRequest.<anonymus>(C:\users\my-user\AppData\Roaming\npm\node_modules\@teambit\bit\node_modules\got\dist\source\core\index.js;962:111)
 
* Pnpm package manager error: Get https://my-private-registry/.../@testing-library/react: request to https://my-private-registry/.../@testing-library/react failed, reason: self signed certificate in certificate chain

## Steps to Reproduce the Problem
1. Have an internal network with a private registry
1. Make a basic component in bit
1. Create a .npmrc file, and set the npm registry to your private registry, and set strict-ssl to false.

.npmrc

```
registry=https://my-private-registry/...
strict-ssl=false
```

1. Run the command: `bit install`

## Specifications
* Bit version: 0.0.595
* Node version: 16.5.0
* npm / yarn version: npm - 7.19.1 / yarn - 1.22.10
* Platform: Windows 10
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
this is likely due to a firewall or vpn settings.
you can either set the proxy settings for Bit or configure your in-house package registry to cache/proxy components (you can reference to [this guide](https://jfrog.com/blog/artifactory-your-npm-registry-for-bit/)).

to set up a proxy for bit:

```
bit config set proxy http://proxy.example.com:8080
bit config set https_proxy https://proxy.example.com:8080
```

there are a bunch more settings:

```
PROXY_CA
PROXY_STRICT_SSL
PROXY_CERT
PROXY_KEY
PROXY_NO_PROXY
```

**Comment by tomaxsas** [comment]
workaround is to set NODE_EXTRA_CA_CERTS=/etc/ssl/certs/ca-certificates.crt variable. but again this is issue with when using custom npm registry, with own CA. even if CA is trusted in system, using proxy it wont be trusted. without proxy, bit takes into account system CA store, but when using proxy it default to node CA files for some reason.

**Comment by itaymendel** [comment]
#7062 solves the above issue
