### ISSUE TITLE
Add pre-publish hook to support case of dist outside the component dir

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#525]
intro:
This case is a case when I'm a package publisher using bit components and I want to publish my package.

when the dist is outside of the component dir (aka dist.target defined in bit.json) the dist will include a lot of links which won't' work after I publish my project (not a component but project) as a package.
This problem won't happen in case the dists are inside the component dir, so we need to create some code which kind of remove the dist.target, run build, publish, then restore the original state.
maybe pre-publish and post-publish hooks.
This is not an extension for bit.

**Comment by itaymendel** [comment]
resolved
