### ISSUE TITLE
Custom JSON Component Generator Broken package.json main Reference

### ISSUE THREAD

**Issue by johnjspiteri** [teambit/bit#5257]
### Describe the bug
We created a custom JSON component generator, that outputs a single file.

```
generator.registerComponentTemplate([
	{
		name: 'json',
		description: 'json source',
		generateFiles: (context: ComponentContext) => {
			return [
				{
					relativePath: 'index.json',
					isMain: true,
					content: '{}',
				},
			];
		},
	},
]);
```

After tagging and exporting the package, the "package.json" main reference always points to a ".js" file extension

```
"main": "dist/index.js",

```

### Steps to Reproduce
1. Using the custom workspace generator "@interface-agency/generators.workspace.json"
1. Using the custom component generator "@interface-agency/generators.component.json"
1. Tagging package
1. Exporting package

### Expected Behavior
The reference should be 

```
"main": "dist/index.json",

```

### Specifications
* Bit version: 0.0.588
* Workspace type: harmony
* Node version:  16.10.0
* npm / yarn version: 7.24.0
* Platform: MacOS 11.6

* relevant env
* relevant aspects: "@interface-agency/generators.component.json"

**Comment by itaymendel** [comment]
at this point, node still does not support `json` only components.
you must have an `index` file that exports a module as part of your component.
once you add this to your template, you will be ok to move forward with it.
