### ISSUE TITLE
skipping link files algorithm should be recursive

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#526]
For example, a file is-string.js requires a variable isType from is-type/is-type.js via a link file 'is-type/index.js.
The index.js file is not a real dependency, it only requires another file, hence we call it a 'link file' and not considering it as a dependency in the model.
Currently, this logic knows how to deal with only one link file, but not with link file that requires another link file.

**Comment by itaymendel** [comment]
irrelevant
