### ISSUE TITLE
Dev files not tracked properly as dev files

### ISSUE THREAD

**Issue by smn-snkl** [teambit/bit#5261]
## Expected Behavior
When adding new dev file patterns to the `workspace.jsonc` the dev files matching those rules should show up as `dev files` in `bit show`.

## Actual Behavior
Files matching custom dev file patterns are not tracked as dev files. For example, with the following `devFilePattern` definition, the files `test.dev.md` or `dev/test.md` are not showing up as `dev files` in `bit show`:

```
"*": {
  "teambit.component/dev-files": {
    "devFilePatterns": [
      ".dev.*",
      "**/dev"
    ]
  }
}
```

## Steps to Reproduce the Problem

1. Add the `devFilePatterns` from above to your `workspace.jsonc`
1. Create the following dummy dev files to the root folder of your component `test.dev.md` and `dev/test.md`
1. Run `bit show <component-id>` to display tracked files
1. The two files will show up in `files` section, but not in `dev files` (see screenshot below)

## Specifications
* Bit version: 0.0.613
* Node version: v16.7.0
* npm / yarn version: 1.22.11
* Platform: Mac OS
* Bit compiler (include version): unknown
* Bit tester (include version): unknown

![Screen Shot 2022-01-11 at 6 24 37 PM](https://user-images.githubusercontent.com/11544327/148991324-ba7c61c1-9b3e-40ec-9599-78f14745110b.png)

**Comment by itaymendel** [comment]
hi,

please follow the config from here - https://github.com/bit-demos/bit-storybook/blob/main/workspace.jsonc#L70

**Comment by smn-snkl** [comment]
Hi @itaymendel,

thanks for the hint. So the issue is the pattern definition. I followed the guide here: https://harmony-docs.bit.dev/aspects/dependency-resolver/#register-file-patterns-to-be-considered-as-dev-files

In the docs, it says you can "add your own list of file extensions" with the following example:
```
"devFilePatterns": [".spec.ts"]
```
So we tried
```
"devFilePatterns": [".dev.md"]
```
which doesn't work. However
```
"devFilePatterns": ["*.dev.md"]
```
does work. So instead of specifying file extensions, you need to specify rules that (regex) match the entire file path, correct?
