### ISSUE TITLE
Library inner dependencies are not installed with bit install? How to properly install third party npm packages for use within my components?

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5279]
### Describe the bug
I cannot seem to find in the documentation how to install normal npm packages for use in my components. The only way I have figured out how to install them would be through "bit install styled-components". It seems to install the package into node_modules however it does not seem to install any of the inner dependencies that module declares. So for instance when I install the styled-components npm package and try to use it, I get an error saying "react-is" is not installed. It is declared in the package.json of the library but I do not see it under node_modules.

Am I installing third party libraries correctly?

### Steps to Reproduce
1. bit install styled-components
1. import and use
1. bit start

### Screenshots, exceptions and logs
```
Module not found: Error: Can't resolve 'react-is' in 'C:\Users\test\Documents\Projects\FRNT\ui-elements\node_modules\.pnpm\registry.npmjs.org+styled-components@5.3.3_react-dom@17.0.2+react@17.0.2\node_modules\styled-components\dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in 'C:\Users\test\Documents\Projects\FRNT\ui-elements\node_modules\.pnpm\registry.npmjs.org+styled-components@5.3.3_react-dom@17.0.2+react@17.0.2\node_modules\styled-components\dist'
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\Compilation.js:1773:28
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:811:13
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:286:22
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:442:22
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:124:11
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:673:25
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:882:8
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:1002:5
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\neo-async\async.js:6883:13
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\lib\NormalModuleFactory.js:985:45
    at finishWithoutResolve (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:296:11)
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:362:15
    at C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:410:5
    at eval (eval at create (C:\Users\test\AppData\Local\.bvm\versions\0.0.617\bit-0.0.617\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:16:1)
```

### Specifications
Bit version: 0.0.617
Workspace type: (harmony/legacy) harmony
Node version: v14.16.0
npm / yarn version: 6.14.11
Platform: Windows
for harmony workspace

relevant env: react

**Comment by GiladShoham** [comment]
react-is is incorrectly defined as peer dependency of styled components. So you should add it to your peer dependencies in your workspace.jsonc

**Comment by brandoncollins7** [comment]
Ok but I am also having this issue with other projects like: 

 https://www.npmjs.com/package/rmwc. I've had to add all the dependencies manually as well as tslib.

**Comment by itaymendel** [comment]
there are some packages out there that mis-configured their dependencies. this causes some complications with Bit, as Bit is more sensitive to proper dependency graph management. this is because bit automatically parse dependencies for components according to import statements. this means that if you use a dependency that has peerDeps (which are typically not imported by your code), bit may not find them and list them as dependencies for your component (run `bit show` for your component). the way to resolve it is to manually adding these dependencies to your project.

also, devDependencies is set automatically in Bit. you can read about it here - https://github.com/teambit/bit/discussions/5059
