### ISSUE TITLE
Remove the scope name from the component

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#528]
(the issue has been opened originally by @GiladShoham ).
Currently, components under local scope don't contain the scope name, only after exporting to another scope they contain the new scope name.
This makes some problems:
1. There is diff between local and remote scopes which leads to issues like you can't import from a .bit dir because the component not found
2. This creates coupling between component and scope which is bad design and leads to other problems such as:
3. If we want to support scope rename, we need currently to change all the components instead change only the scope metadata (scope.json)

**Comment by itaymendel** [comment]
irrelevant
