### ISSUE TITLE
After importing my component into an existing react project, receiving error: To import Sass files, you first need to install node-sass.

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5287]
### Describe the bug
Have created a published a component to bit dev. The component loads fine in the local workspace app and displays correctly on the bit.dev component browser. After importing it into my existing react project it fails to load with the error above. Shouldn't this already be included as part of the built component?

### Expected Behavior
Component should work as published

### Screenshots, exceptions and logs
    ./node_modules/@app/base-ui.themes.material/dist/material.module.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-6-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-6-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-6-4!./node_modules/@app/base-ui.themes.material/dist/material.module.scss)
    To import Sass files, you first need to install node-sass.
    Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
    Require stack:
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\sass-loader\dist\getDefaultSassImplementation.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\sass-loader\dist\getSassImplementation.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\sass-loader\dist\index.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\sass-loader\dist\cjs.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\loader-runner\lib\loadLoader.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\loader-runner\lib\LoaderRunner.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\webpack\lib\NormalModule.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\webpack\lib\NormalModuleFactory.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\webpack\lib\Compiler.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\webpack\lib\webpack.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\offline-plugin\lib\misc\get-minification-plugin.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\offline-plugin\lib\service-worker.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\offline-plugin\lib\index.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\config-overrides.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\react-app-rewired\config-overrides.js
    - C:\Users\test\Documents\Projects\app\app-microservices-submodules\frontends\app-backoffice-webapp\node_modules\react-app-rewired\scripts\start.js### Specifications
Bit version: 0.0.617
Workspace type: (harmony/legacy) harmony
Node version: v14.16.0
npm / yarn version: 6.14.11
Platform: Windows
for harmony workspace

relevant env: react

**Comment by itaymendel** [comment]
this is because bit does not compile the scss files in your component. you need to have your webpack config deal with scss.
