### ISSUE TITLE
bit test doesn't return exit code 1 when failing

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5291]
when running bit test with failing test, I expect it to return exit code 1 (indicating error),
but instead it's returning exit code 0 (all's good).
This prevents me from using it in automated tests.

We could add this behavior under the `--strict` flag, like we do for `bit check-types --all --strict`, so it won't fail code pipelines when not needed.

![](https://user-images.githubusercontent.com/5400361/149965585-6b153a33-7362-4559-bf41-0d03ac5505d5.png)

Bit version: 0.0.623

**Comment by itaymendel** [comment]
`bit build` is the intended commadn to run for pipelines, not `bit test`, as it runs all tests in complete isolation.
