### ISSUE TITLE
A documentation page is showing 404 not found

### ISSUE THREAD

**Issue by adityabohra007** [teambit/bit#5305]
https://harmony-docs.bit.dev/getting-started/initializing-workspace/creating-components
Please make it work
I was trying to learn bit but this error occured

**Comment by jonatankBIT** [comment]
Hi! @adityabohra007

- Can you post the page that you got the link from?

You are probably trying to reach:
https://harmony-docs.bit.dev/getting-started/creating-components

**Comment by evelant** [comment]
@jonatankBIT I've just discovered Bit and I'm finding that there are a lot of broken links in the docs. Perhaps you might be able to use Bit itself to automatically validate all links in the docs at build time?

* https://bit.dev/docs/apps/application-types links to https://bit.dev/docs/docs/apps/app-plugins <-- 404
* https://bit.dev/docs/getting-started/composing/create-apps links to https://bit.dev/docs/dev-services/generator/generator-overview <-- 404
* The interactive table at the bottom of this page https://bit.dev/docs/getting-started/composing/creating-components/?component_type=1 links to https://bit.dev/docs/dependencies/dependencies-overview/ <-- 404

That isn't all of them I've encountered, there are a lot more broken links floating around. All the broken links give a bad impression and reduce confidence in adopting Bit.

**Comment by itaymendel** [comment]
this is from the old-docs portal.
irrelevant.
