### ISSUE TITLE
Using user certificate & key for remote

### ISSUE THREAD

**Issue by TNick** [teambit/bit#5307]
### Description
How should I provide the certificate and key for a remote?

### Specifications
* Bit version: 0.0.629
* Node version: 0.0.629
* npm version: 8.1.3
* Platform: Windows 11
* Bit compiler (include version): where do you get this version from?
* Bit tester (include version): where do you get this version from?

### Context and additional information
I have created a self-hosted registry behind a reverse proxy (nginx). 
The nginx checks the certificate then forwards the request to a container where bit server is running. 
I cannot add this remote because I found no way of providing the certificate and key.

A hackish way of doing this is to edit `C:\Users\%USER%\AppData\Local\.bvm\versions\0.0.629\bit-0.0.629\node_modules\@teambit\toolbox.network.agent\dist\agent.js` and edit the properties to `HttpsAgent`.

**Comment by itaymendel** [comment]
oss version of bit needs to be hosted behind nginx to get ssl (from nginx).
bit doesn't have this as a "feature".
