### ISSUE TITLE
Multiple scopes in self-hosted remote

### ISSUE THREAD

**Issue by TNick** [teambit/bit#5308]
### Description
[Self-hosted Bit Scope](https://harmony-docs.bit.dev/reference/bit-oss-server) instructions allows us to self-host a single scope.
How would you go about hosting multiple scopes?

### Specifications
* Bit version: 0.0.629
* Node version: 0.0.629
* npm  version: 8.1.3
* Platform: Windows 11
* Bit compiler (include version): where do you get this version from?
* Bit tester (include version): where do you get this version from?

### Context and additional information
I want to put private bit components in a self-hosted repository of bit components and separate them not only into namespaces but also under scopes (say one scope for fooling around and testing stuff, other for production components).

Creating one container for each scope doesn't seem to work from an UI perspective (with a reverse proxy in front, something like https://example.com/scope1, https://example.com/scope2) because the links will stop working (a `baseUrl` setting may help with that).

**Comment by aweiu** [comment]
need it too!

**Comment by itaymendel** [comment]
hosting multiple scopes and the over-arching discoverability for them is currently a part of the cloud-hosting solution and not a part of the open source implementation.
we do not intend to build support for managing multiple scopes, as this requires setting up multiple containers and goes beyond the scope of the project. from a technical standpoint, this has to be done from the "outside" of a scope.

for comparison, hosting a bit-scope is similar to hosting a git-repo in that that a scope (or a repo) only deals with its own concerns. ie, there's a need to "wrap" a set of scopes (or repos) with an overall set of features. in git-world, this is similar to this https://gitolite.com/gitolite/index.html

i'm closing the issue, as we do not aim to solve this problem in the scope of this project.
