### ISSUE TITLE
Couldn't find package "@teambit/react.instructions.react-native.adding-tests@0.0.1"

### ISSUE THREAD

**Issue by aweiu** [teambit/bit#5327]
### Describe the bug
when install bit without bvm:

```
yarn add @teambit/bit
```

you will get the error: `Couldn't find package "@teambit/react.instructions.react-native.adding-tests@0.0.1"`

**Comment by itaymendel** [comment]
hi, we do not support installing bit from npmjs as some of the dependencies are managed in bit and not available in the npmjs.org registry.

this is why we built bvm, so we can properly use Bit and not worry about publishing all our components to npm.
