### ISSUE TITLE
auto-tagging should continue tag the impacted components  

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#534]
For example, is-string@0.0.1 depends on is-type@0.0.1. When tagging is-type to 0.0.2, the is-string is automatically tagged to have the updated version of is-type.

Say, we have another component "foo", which uses is-string@0.0.1 as a dependency.
This 'foo' component should be updated as well to include the updated version of is-string.

**Comment by GiladShoham** [comment]
@davidfirst we should make it recursive while only auto tag components which imported directly / authored.
means:
a -> b -> c -> d -> e
i import a, c, d, e but not b
made a change in e. 
it will auto tag d and c but b and a will keep untouched.

**Comment by GiladShoham** [comment]
see #740

**Comment by davidfirst** [comment]
It was eventually fixed and merged by https://github.com/teambit/bit/pull/1199
