### ISSUE TITLE
Instructions for creating your own scoped bit-server do not work

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5352]
### Describe the bug
Following the instructions on the docker build page do not make sense. It asks you to run the command:

docker run -it -v {scope-path-on-host}:/root/custom-remote-scope -build-arg SCOPE_PATH=/root/custom-remote-scope -p {host-port}:3000 bitcli/bit-server:latest

but the parameter -build-arg does not apply to "docker run".

### Steps to Reproduce
1. Run the command above.
1. See the error: "unknown shorthand flag: 'b' in -build-arg See 'docker run --help'."

### Expected Behavior
Should run with custom scope

**Comment by ohhoney1** [comment]
--build-arg is for docker build command

**Comment by GreenJimmy** [comment]
Documents should be updated then: https://github.com/teambit/bit/blob/master/scripts/docker-teambit-bit/README.md#combining-scope-volume-with-scope-namelocation
