### ISSUE TITLE
After deploying to a bit.dev scope, it is not possible to export to another self hosted scope?

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5353]
### Describe the bug
I have pushed some components to my online bit.dev scope and now I am trying to push them to a local self hosted scope using the instructions here: https://harmony-docs.bit.dev/reference/bit-oss-server.

However after adding my remote and changing my default scope, I run bit export and all I see is "nothing to export"

### Steps to Reproduce
1. Export components to bit.dev account
1. Start self hosted server
1. Add local remote
1. Change default scope
1. run 'bit export'

### Expected Behavior
Components should deploy to local server

**Comment by ChristopherHawkes** [comment]
Running into the same problem.   After a scope is declared, changing default scope in the workspace.jsonc file is not recognized, it's using the scope that was declared previously.   Where is this data field coming from?

**Comment by itaymendel** [comment]
hi,

changing a scope for a component is a complex topic as it may break dependents and component history.
if you want to "start fresh" and just move all component to a new scope you need to run `bit init --reset-new` which turns all components to be `new`.
if you want to "move" a component to a new scope, use the `bit rename` command.

**Comment by brandoncollins7** [comment]
So it is not possible for a developer to publish to test by publishing to a local self hosted development scope and then eventually  publish to bit.dev later? This seems like a rather large limitation.

**Comment by brandoncollins7** [comment]
I am still confused about this. Let's say we have published some components to bit.dev. Now we have a developer who would like to make some changes locally, and test those changes in a locally developed application without publishing to bit.dev (because they haven't tested it properly and do not wish to deploy it yet). This developer is no longer able to push the components to a local dev component server to import into their other app. What is supposed to be the correct development flow here?

**Comment by blacktail** [comment]
can we try to

bit export <component-id> --all-versions

**Comment by rub-sky** [comment]
@brandoncollins7 if you want to test a component locally you can use the [bit pack](https://bit.dev/reference/packages/packing-components#generate-packages) and put them into a directory of your choice. The generated file is a `.tgz`.
```
bit pack <component> -d <directory to save to>
```

For Angular components, you can manually install the component using the generated `.tgz` file by referencing the file the `bit pack` command created.
```
npm i --save <directory of tgz>
```

**Comment by southerncross** [comment]
> can we try to
> 
> bit export --all-versions

+1

Our self-hosted scope got messed up, and we found we can not reset the remote scope and export components to it.
