### ISSUE TITLE
output from tagging imported components duplicates the same npm install output 3 times

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#536]
STR:
1. bit-dev import odedreuveny.example/utils/left-pad
2. modify component
3. bit-dev tag -a
the same output from installing the dependency packages shows 3 times. not a bug but might confuse users. to see the output I got you can refer to the attached screenshot

![image](https://user-images.githubusercontent.com/3840769/34480047-c534f868-efb2-11e7-8a42-15464a56ecb3.png)

**Comment by davidfirst** [comment]
It doesn't happen anymore, we changed the output of the npm installation to show the installation path instead of the packages.
I tried with the component above, and got only one line of "successfully ran npm install".
