### ISSUE TITLE
Cannot find module '@babel/runtime/helpers/interopRequireDefault' in tests of tutorial button

### ISSUE THREAD

**Issue by devblazer** [teambit/bit#5409]
### Describe the bug

I followed the docs getting started guide, all very straight forward and created the ui/button they show there.  Running the bit server and browsing to the button, all seems fine.  But when I switch to the 'tests' tab of the component, the default (unmodified) test fails with:
```Cannot find module '@babel/runtime/helpers/interopRequireDefault'```

### Steps to Reproduce

1. npm i -g @teambit/bvm
2. bvm install
3. bit init --harmony
3. setup workspace for react: ```"*": { "teambit.react/react": { } }```
4. bit install react --type peer
5. bit install react-dom --type peer
6. bit create react-component-js ui/button
7. bit install @testing-library/react
8. bit compile
9. bit start
10. Browse the server ui to the button and click on the 'test' tab.  
11. At this point I see the error.

### Expected Behavior

There should be a passing test, it is the default provided for the component after all..

### Screenshots, exceptions and logs

![test-failing](https://user-images.githubusercontent.com/2198192/154266072-3f2aebcc-ad7a-445f-a366-0c64ebd4ad9a.jpg)

### Specifications

- Bit version: 0.0.651
- Workspace type: harmony
- Node version: 14.16.1
- npm / yarn version: npm@6.14.12
- Platform: Windows 10

*for harmony workspace*
- relevant env: react
- relevant aspects: no-typescript

### Additional context

**Comment by jonatankBIT** [comment]
Hi @devblazer! Thanks for reporting. I reproduced the steps mentioned and didn't encountered that behavior.

I would suggest the following:

### Reinstalling dependencies
- Remove the `node_modules` folder
- run `bit cc`
- `bit install`
- `bit compile`
- `bit start`

### Adding @babel/runtime
Try to add the missing dependency manually.
- `bit install @babel/runtime`

**Comment by sbland** [comment]
I also had this from a new project. Bit version `0.0.744`. @jonatankBIT suggested resolved the issue.

**Comment by reallyely** [comment]
Also happened for me from a new project and following the tutorial. Perhaps something can be done so the getting started guide doesn't have this wrinkle?
