### ISSUE TITLE
remote scope locked how to fix

### ISSUE THREAD

**Issue by lcz1543812491** [teambit/bit#5446]
lczSCMLLEO31 mik-ui % bit export utils@0.0.1
unexpected network error has occurred.
server responded with: "scope "mik-technology.mik-ui". error: fatal: the server is busy exporting from other clients. total clients (including yours) in the queue: 2,
the current export-id in queue is "1645437636578".
if the last export was failed during the persist stage and left the remotes locked, you have the following options:

1. if the failure occurred on your local, just re-run the export command with "--resume <id>".
1. run "bit persist <id> <remotes...>", you will need to list all the remote scopes you want the persist to take place.
"

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.

**Comment by itaymendel** [comment]
Hi,

please rerun the same command and add the `--resume` flag.

**Comment by lcz1543812491** [comment]
![image](https://user-images.githubusercontent.com/31276544/155438674-fa8fe4a6-6385-4420-a322-487ba0c0c15d.png)。 maybe. need to put a export-id. but how can i know zhe last export-id

**Comment by dmkorb** [comment]
I'm having the same issue.

`bbit export`
```
unexpected network error has occurred.
server responded with: "scope "sudo.shared-ff". error: fatal: the server is busy exporting from other clients. total clients (including yours) in the queue: 2,
the current export-id in queue is "1646681758856".
if the last export was failed during the persist stage and left the remotes locked, you have the following options:
1. if the failure occurred on your local, just re-run the export command with "--resume <id>".
2. run "bit persist <id> <remotes...>", you will need to list all the remote scopes you want the persist to take place.
"
```

Then if I try `bbit export --resume 1646681758856` I get:
```
failed persisting to the following scopes: sudo.shared-ff
errors:
sudo.shared-ff - EACCES: permission denied, open '/tmp/scope-fs/objects/f3/7d63e296884cc543a9a33389b061696acfb26d'

the remote bit.dev will try to re-persist the data for the failed scopes.
```

---
bit doctor:
```
bit version   : 0.0.671
  node version  : v16.13.0
  npm version   : 8.1.0
  yarn version  : 1.22.17
  platform      : darwin
```

**Comment by itaymendel** [comment]
issue was resolved on the bit.cloud backend.
if anyone hits this issue, please send a note to support@bit.cloud

**Comment by suwu150** [comment]
I also encountered the same problem, unable to export the code,
The email has been sent for some time, but there is no effective response. Please pay attention

@itaymendel

**Comment by suwu150** [comment]
> issue was resolved on the bit.cloud backend.
> if anyone hits this issue, please send a note to [support@bit.cloud](mailto:support@bit.cloud)

issue was resolved on the bit.cloud backend.
if anyone hits this issue, please send a note to [support@bit.cloud](mailto:support@bit.cloud)

**Comment by wanpingwua** [comment]
按照上边操作报这个错误，如何解决![121702469138_ pic](https://github.com/teambit/bit/assets/122012747/3afce5b9-3942-4dce-a5b4-89692bc4b5eb)
