### ISSUE TITLE
bit remove after importing component gives out the error: Cannot read property 'files' of null

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#545]
STR:
1. git clone https://github.com/ramda/ramda.git
2. bit-dev init
3. bit-dev add source/internal/_aperture.js -i a/b 
4. bit-dev import odedreuveny.example/utils/left-pad
5. modify imported component
6. bit-dev tag -a
7. bit-dev remove a/b
 
I got the error: Cannot read property 'files' of null

*after these steps you cannot remove any component(local/remote/non-existing component). you only get the same error described above

**Comment by amitgilad3** [comment]
@GiladShoham -  i ran the same steps and couldn't reproduce this issue.
will check again after deploy to bitsrc

**Comment by itaymendel** [comment]
resolved

**Comment by solarstar101** [comment]
how was this resolved? having same issue

**Comment by davidfirst** [comment]
@solarstar101 any chance to get a zip of the workspace so I could reproduce (david@bit.dev)? this is an old issue that was fixed long ago.
