### ISSUE TITLE
error - failed connecting to child iframe

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5457]
this error pops up once in a while:

```
[Pubsub.ui] – failed connecting to child iframe
```

It happens when `penpal`, (a postmessage library) tries to connect and handshake an iframe inside the page.
In certain edge cases, like switching quickly between pages, child iframes might not load in time, failing the handshake.

This is ok, but we need to clear the warning.

**Comment by itaymendel** [comment]
resolved #5466
