### ISSUE TITLE
How to test components in a locally developed app without first publishing to bit.dev (for a project that has already first been deployed to bit.dev)?

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5463]
So it seems that you cannot easily change your scope from the bit.dev account after deploying your components to bit.dev. So I am trying to understand how a developer would locally change a particular component and then test it inside a locally developed application without first publishing it to bit.dev. 

What is supposed to be the general workflow for a locally developed app to test locally changed components, without first deploying those components (as they may not be ready for deployment until a few integrations of local tests?)

**Comment by itaymendel** [comment]
you can change a scope for a component with the `bit rename` command, or if you want, reset it to a new component and start as fresh.

you can use the `bit link --target` option from a Bit workspace to a target project, this will create symlinks for all components in the target project. Also, run Bit in `watch` mode to keep updating the compiled outputs.

```
cd BIT-WORKSPACE
bit link --target ../PATH/TO/PROJECT
bit watch
```

**Comment by brandoncollins7** [comment]
But what if I wish to test the bit components in a not bit project? But I also don't want to reset the components as once we are happy with the component we would then want to easily push the next version back to bit.dev.

**Comment by itaymendel** [comment]
this is all about testing components in a non-bit-project. the option will set the links in your project's node_modules dir.
you do all modifications in the original project, in the same system. this is why `watch` is needed, as it updates the dist.

if you are looking for a way to get the `import` working on a local non-bit project without exporting to a scope, this is not available. bit components are more like small git repositories, so you need a remote to sync a component between two projects (imagine having two clones of the same git repo on your system, and sync a change between them).

**Comment by linfordbacon-ngenius** [comment]
Hi @itaymendel,

Thanks for your response. Just to clarify, are you saying that there is no way for a project to reference the local development version of a component?

In my workflow, the development of a component typically happens alongside the development of a larger application that will use one or more bit components.

Ideally, I would be able to import a component into my local workspace, make edits to that component and then see those edits working in the context of the main application.

When I'm happy that the edits to the component are correct then I can export the components to the remote scope.

Is this not a supported workflow? Do components need to be exported/imported before they can be referenced in my app?

I've tried using `watch` but I'm not really sure what it's doing and it certainly isn't allowing my main app to have reference to the development version of my components.

**Comment by itaymendel** [comment]
bit now supports `bit link --target` which allows you to have a symlink to component builds from the local workflow to any other root directory of any other node project.

**Comment by brandoncollins7** [comment]
Was this recently changed? Bit link wasn't working when I tried it before.
