### ISSUE TITLE
when receiving errors from bit some actually throw exceptions and others are just outputs to the user

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#547]
examples:

the following commands throw errors:
1. bit add <filePath> -n 
*this throws an error for missing namespace:
"error: option `-n, --namespace <namespace>' argument missing"
2. bit add <filePath> -i 
*this throws an error for missing ID:
"error: option `-i, --id <name>' argument missing"
3. bit add <filePath> -i Bar/Foo
*this throws an error for invalid ID:
'invalid id part in "Bar/Foo", id part can have only alphanumeric, lowercase characters, and the following ["-", "_", "$", "!", "."]'

the following commands return an output that looks like an error(they appear in red color in the terminal and use "fatal" and "error" at the beginning of the message), but are just an output of running the function:

1. untracking a non existing component
*this returns an output for non existing component: 
"fatal: component <componentName> did not match any component."

2. untracking a tagged component 
*this returns the message: 
"error: unable to untrack bar/foo, please use the bit remove command."

**Comment by itaymendel** [comment]
resolved
