### ISSUE TITLE
improve error when tagging components before their dependencies

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#548]
consider the following:
component A depends on component B.
If I run bit tag A I get the following error:
error: Dependency "B" not found.
we should make this error more informative. at the moment the user might think that B component doesn't exist instead of understanding that B should be added before A.

STR:
1.git clone https://github.com/digiaonline/react-foundation.git
2.bit init
3.bit add src/enums.js src/utils.js
4. bit tag -m "utils" src/utils

**Comment by itaymendel** [comment]
resolved
