### ISSUE TITLE
list after import specific version bring the last version

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#549]
str
bit import bitsrc.nodejs/bucket/file-exists@0.0.2
bit list
show version 0.0.3
This might also prevent the --outdated from working

This is because we bring all the models during import, but we don't have a good way to know which version the user really use right now.
It is similar case to multi-branch case.

We need to define what list, showing exactly - my last version in the scope, or my used version

**Comment by itaymendel** [comment]
irrelevant
