### ISSUE TITLE
bit tag modified component to lower version doesn't work properly 

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#550]
I modified a tagged component that is currently in version 1.0.0 and tried to tag it to version 0.8.0.

-first time it outputs a success message for the greatest version of the component:

1 components tagged | 0 added, 1 changed, 0 auto-tagged
changed components:  src/enums@1.0.0 

-if I try to tag it again to the same version, the message output is:
the version 0.8.0 already exists for src/enums

we should return the current version that the component is on and not the version we are trying to set it to. 
STR:
1. git clone https://github.com/digiaonline/react-foundation.git
2.bit init
3.bit add src/enums.js
4.bit tag src/enums 1.0.0
5. modify the component
6. bit tag src/enums 0.8.0

**Comment by itaymendel** [comment]
resolved
