### ISSUE TITLE
Dependency Issue with material 5 .

### ISSUE THREAD

**Issue by uttam23** [teambit/bit#5505]
### Describe the bug
Trying to Use Material ui version 5. which needs emotion library.
Used the following command
bit install mui/material emotion/react emotion/styled
With Bit start , it is working fine in local.
When I am trying to build ,getting the error.
`    **Cannot find module '@emotion/styled' from 'node_modules/.pnpm/registry.npmjs.org+@mui+styled-engine@5.4.4_react@17.0.2/node_modules/@mui/styled-engine/node/index.js'**`

### Steps to Reproduce
1.bit install mui/material emotion/react emotion/styled
2.Bit build

### Expected Behaviour
It should handle dependency of emotion on material ui . As of now it is throwing error 

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/6542709/156732472-08bbb73b-3879-4f56-b45b-abd69917ba92.png)

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.585
* Workspace type: (harmony/legacy) : harmony 
* Node version: 0.0.585
* npm / yarn version: 7.19.1
* Platform: 

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
you need to set MUI and emotion as peerDeps.
for a complete solution, please see this repository - https://github.com/bit-demos/ui-library-wrappers
