### ISSUE TITLE
Sync vscode with Bit eslint

### ISSUE THREAD

**Issue by FNLuzko** [teambit/bit#5507]
### Description
I'm trying to sync the vscode formatter (for example trigger it on save), with the actual Bit's internal Eslint configuration.
How can achieve this?
using harmony version 0.0.668

**Comment by itaymendel** [comment]
eslint settings for components is found in an internal dependency for Bit, or as part of your custom development environment.
if you want to sync your IDE to it, add `eslintrc.js` file at the root of your IDE and do something like this:

```
module.exports = {
  extends: ['./node_modules/@teambit/react.eslint-config-bit-react', 'prettier'],
};
```

this way your IDE will use the same configs as Bit.

**Comment by FNLuzko** [comment]
@itaymendel that package is not located at the node_modules, so it's failing when trying to import, any solution or can i import something else?

**Comment by arturo-akido** [comment]
> @itaymendel that package is not located at the node_modules, so it's failing when trying to import, any solution or can i import something else?

You can directly install the config as a package from `@teambit/eslint-config-bit-react` and import it in your `.eslintrc.js` file, that's what we ended up doing

```js
module.exports = {
  extends: ['@teambit/eslint-config-bit-react'],
  parserOptions: {
    project: './tsconfig.json'
  },
}
```
