### ISSUE TITLE
Need to use UI Library (Antd, Material, Semantic) in a react component library

### ISSUE THREAD

**Issue by agustinpardolp** [teambit/bit#5516]
### Description
Hello!
I'm working on a react component library, using Bit and Antd Design, and basically changing the styles.
I need to import not only each Antd component (eg input, button, table, etc), but also the **andt/dist/antd.css** file, which contains all the Antd CSS classes. In a common React project, that file is usually imported into the main index.js.
But in this case, I only have a scope/ui/XXXX.tsx
I managed to apply the Antd style importing **andt/dist/antd.css** in each component... but I can't use my own style.scss (Eg table.module.scss) **to modify those Antd classes**... nothing happens. It's like antd.css is out of scope and I don't know what to do or what am I doing wrong.

Sorry for my English guys!

I attach images with my folders

### Specifications
* Bit version: 0.0.667
* Node version: 14.19.0
* npm / yarn version: 6.14.16
* Platform:
* Bit compiler (include version): 
* Bit tester (include version):

### Context and additional information

![](https://user-images.githubusercontent.com/44348917/157285309-52bbee88-6fc5-4fe9-8788-1fed74cea2e2.png)
![](https://user-images.githubusercontent.com/44348917/157287290-e7e3ecdb-cb8e-4a0a-be78-65593a449e16.png)
![](https://user-images.githubusercontent.com/44348917/157287316-3497a3b5-d618-49ee-9e62-74548ae7dd95.png)

**Comment by itaymendel** [comment]
if you need to load all of the css for each component, is a similar way to how a consuming app will - please use the `mount` function of the environment, when rendering the preview.
