### ISSUE TITLE
when running `bit create ng-module ...` it creates a component with the `aspect` env

### ISSUE THREAD

**Issue by odedre** [teambit/bit#5518]
### Steps to Reproduce
1. run `bit create ng-module bla`
1. creates a component with the content of ng-module but with the `aspect`  env.

### Expected Behavior
should create a component with the correct env

### Specifications
* Bit version: 0.0.670
* Workspace type: harmony
* Node version:
* npm / yarn version:
* Platform:

**Comment by ocombe** [comment]
Fixed in https://github.com/teambit/bit-angular/commit/0668ef762ea5ed8264390cbb798086fc930613a6
