### ISSUE TITLE
when `bit env set` fails, it changes the env to `teambit.harmony/node`

### ISSUE THREAD

**Issue by odedre** [teambit/bit#5519]
### Steps to Reproduce
1. create a component with the aspect env
1. `bit env set <componentName> teambit.angular/angular-v13`
1.  I get the response `added teambit.angular/angular-v13 env to the following component(s)`
1. when running `bit envs` it shows that the component's env was changed to `teambit.harmony/node` 

### Expected Behavior
if it fails, the env should not change

**Comment by itaymendel** [comment]
with `"resolveEnvsFromRoots": true` this is resolved. the feature was added by default to all new workspaces. closing the issue.
