### ISSUE TITLE
`bit create react <componentName>` creates a component with the `teambit.harmony/node` aspect

### ISSUE THREAD

**Issue by odedre** [teambit/bit#5520]
### Steps to Reproduce
1. run `bit create react <componentName>`
1. run `bit envs`
1. see that the component has the `teambit.harmony/node` env

### Expected Behavior
should have the `teambit.react/react` env

**Comment by albodhi** [comment]
If anyone is looking for a temporary fix while waiting for this issue to be resolved, you can run a Bit command to set your component's environment manually.

<br /><br />

```bit env set acme.demo/welcome teambit.react/react  # define the component the pre-built react env.```

<br /><br />

Replace ```acme.demo/welcome``` with your component ID, which should look something like ```scope/namespace/.../component```.

<br /><br />

Doing this fixed some Bit testing issues I was facing.

<br /><br />

You can read a little bit more about Bit environments here.
https://bit.dev/docs/envs/envs-overview

**Comment by itaymendel** [comment]
resolved.
