### ISSUE TITLE
"ReferenceError: FontFace is not defined" during test runs

### ISSUE THREAD

**Issue by zach-thrivetribe** [teambit/bit#5546]
### Describe the bug
Running `bit test` throws a `ReferenceError: FontFace is not defined` error when testing a component that uses the CSS Font Loading API. 

### Steps to Reproduce
1. run bit test on a component that uses the font loading API

### Expected Behavior
Successful run of the unit tests

### Screenshots, exceptions and logs
` ReferenceError: FontFace is not defined

      1 | export const loadBebasNeueFont = () => {
    > 2 |   var bebasNeue = new FontFace("Bebas Neue", "url(https://fonts.gstatic.com/s/bebasneue/v8/JTUSjIg69CK48gW7PXoo9Wlhyw.woff2)", {weight: "400"});
        |                   ^
      3 |
      4 |   bebasNeue
      5 |     .load()`### Specifications* Bit version: 0.0.603
* Workspace type: harmony
* Node version: 14.17.3
* npm / yarn version: 6.14.13
* Platform: windows 10

```
"teambit.dependencies/dependency-resolver": {
    /**
     * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
     */
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@testing-library/dom": "8.11.3",
        "@testing-library/react": "12.1.3",
        "@testing-library/user-event": "13.5.0",
```

**Comment by zach-thrivetribe** [comment]
Forgot to mention that the Font Loading API works perfectly fine outside of the tests, I am able to tag and export components that use it just fine, but when put in the tests it throws those errors.

**Comment by NitsanCohen770** [comment]
resolved in new envs api

**Comment by manuschillernordlb** [comment]
@emersonthis 
you can do it like this:

```font-face-mock.ts
class FontFaceMock {
  family: string
  source: string
  descriptors: unknown

  constructor(family: string, source: string, descriptors?: unknown) {
    this.family = family
    this.source = source
    this.descriptors = descriptors
  }

  load(): Promise<FontFaceMock> {
    return Promise.resolve(this)
  }
}

globalThis.FontFace = FontFaceMock as never
```

then reference the file in your `vite.config.ts`:

```typescript
export default defineConfig({
  test: {
    globals: true,
    environment: 'happy-dom',
    exclude: [...configDefaults.exclude],
    setupFiles: ['dotenv/config', './src/__test__/font-face-polyfill.ts']
  },
```

**Comment by emersonthis** [comment]
Thanks for the tip!

In case someone else finds their way to issue via Google, we were able to sidestep this problem by using Vitetest's new [browser mode](https://vitest.dev/guide/browser/) which runs the tests in a full headless browser with all the APIs defined.
