### ISSUE TITLE
Impossible to tag any component since bit 0.0.653

### ISSUE THREAD

**Issue by na-ji** [teambit/bit#5548]
### Describe the bug
Since bit v0.0.653, I can no longer tag my component. I followed the migration steps on #5439, but the tagging of my custom environment fails on the generate preview build task.

### Steps to Reproduce
1. Update to bit >= 0.0.653
1. Run `bit tag`

### Expected Behaviour
I expect the bit tag command to work.

### Screenshots, exceptions and logs
```
✖ env: algoan-front-end.deep-dive/envs/default@2.5.2, task "teambit.preview/preview:GeneratePreview" has failed
- teambit.pipelines/builder, running tasks (15/22). env "teambit.harmony/aspect", task "teambit.harmony/application:build_application"
✔ env "teambit.harmony/aspect", task "teambit.harmony/application:build_application" has completed successfully in 75μs
- teambit.pipelines/builder, running tasks (16/22). env "teambit.harmony/aspect", task "teambit.pkg/pkg:PreparePackages"
✔ env "teambit.harmony/aspect", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 12ms
- teambit.pipelines/builder, running tasks (17/22). env "teambit.harmony/aspect", task "teambit.preview/preview:GenerateEnvTemplate"
- teambit.workspace/workspace, loading components (total: 2)
- teambit.workspace/workspace, loading components (1/2). algoan-front-end.deep-dive/envs/default@2.5.2
- teambit.workspace/workspace, loading components (2/2). algoan-front-end.deep-dive/envs/default@2.5.2
- teambit.workspace/workspace, loading components (completed in 2ms)
- teambit.webpack/webpack, running Webpack bundler (total: 1)
- teambit.webpack/webpack, running Webpack bundler (1/1). algoan-front-end.deep-dive/envs/default@2.5.2
- teambit.webpack/webpack, running Webpack bundler (completed in 1s)
✖ env: teambit.harmony/aspect, task "teambit.preview/preview:GenerateEnvTemplate" has failed
- teambit.pipelines/builder, running tasks (18/22). env "teambit.harmony/aspect", task "teambit.preview/preview:GeneratePreview"
- teambit.webpack/webpack, running Webpack bundler (total: 1)
- teambit.webpack/webpack, running Webpack bundler (1/1). algoan-front-end.deep-dive/envs/default@2.5.2
- teambit.webpack/webpack, running Webpack bundler (completed in 3s)
✔ env "teambit.harmony/aspect", task "teambit.preview/preview:GeneratePreview" has completed successfully in 3s
- teambit.pipelines/builder, running tasks (19/22). env "teambit.harmony/node", task "teambit.harmony/application:build_application"
✔ env "teambit.harmony/node", task "teambit.harmony/application:build_application" has completed successfully in 308μs
- teambit.pipelines/builder, running tasks (20/22). env "teambit.harmony/node", task "teambit.pkg/pkg:PreparePackages"
✔ env "teambit.harmony/node", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 731μs
- teambit.pipelines/builder, running tasks (21/22). env "teambit.harmony/node", task "teambit.preview/preview:GenerateEnvTemplate"
✔ env "teambit.harmony/node", task "teambit.preview/preview:GenerateEnvTemplate" has completed successfully in 346μs
- teambit.pipelines/builder, running tasks (22/22). env "teambit.harmony/node", task "teambit.preview/preview:GeneratePreview"
- teambit.webpack/webpack, running Webpack bundler (total: 1)
- teambit.webpack/webpack, running Webpack bundler (1/1). algoan-front-end.deep-dive/theme/theme@4.5.1
- teambit.webpack/webpack, running Webpack bundler (completed in 3s)
✔ env "teambit.harmony/node", task "teambit.preview/preview:GeneratePreview" has completed successfully in 3s
- teambit.pipelines/builder, running tasks (completed in 55s)
- executing post-build for all tasks
✔ executing post-build for all tasks
- teambit.pipelines/builder, running build pipe for 3 environments, total 22 tasks (completed in 55s)
✖ teambit.pipelines/builder, running build pipe for 3 environments, total 22 tasks (completed in 55s)

The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "algoan-front-end.deep-dive/envs/default@2.5.2"
component: algoan-front-end.deep-dive/atomic-components/algoan-button@4.5.2
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/test-utils' in '/home/runner/work/deep-dive/deep-dive/node_modules/.pnpm/registry.npmjs.org+@testing-library+react@12.1.2_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/@testing-library'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/test-utils' in '/home/runner/work/deep-dive/deep-dive/node_modules/.pnpm/registry.npmjs.org+@testing-library+react@12.1.2_react-dom@17.0.2+react@17.0.2/node_modules/@testing-library/react/dist/@testing-library'
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/Compilation.js:1773:28
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:811:13
    at eval (eval at create (/home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:286:22
    at eval (eval at create (/home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:442:22
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:673:25
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:882:8
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:1002:5
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/neo-async/async.js:6883:13
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/lib/NormalModuleFactory.js:985:45
    at finishWithoutResolve (/home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/home/runner/.bvm/versions/0.0.677/bit-0.0.677/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

I get this error for every component depending on the environment.

### Specifications
* Bit version: 0.0.677
* Workspace type: harmony
* Node version: 14.x
* npm / yarn version: 8.x
* Platform: ubuntu/osx

_for harmony workspace_

* relevant aspects: none
* relevant env: custom environment with those dependencies:

```
react.overrideDependencies({
        dependencies: {
          react: '-',
          'react-dom': '-',
          '@testing-library/react': '-',
          '@testing-library/react-hooks': '-',
          'styled-components': '-',
          'react-intl': '-',
          '@yelloan/deep-dive.theme.theme': '-',
        },
        devDependencies: {
          react: '-',
          'react-dom': '-',
          '@testing-library/react': '-',
          '@testing-library/react-hooks': '-',
          'styled-components': '-',
          'react-intl': '-',
          '@yelloan/deep-dive.theme.theme': '-',
        },
        peerDependencies: {
          react: {
            version: '^17',
            resolveFromEnv: true,
          },
          'react-dom': {
            version: '^17',
            resolveFromEnv: true,
          },
          '@testing-library/react': {
            version: '^12',
            resolveFromEnv: true,
          },
          '@testing-library/react-hooks': {
            version: '^7',
            resolveFromEnv: true,
          },
          'styled-components': {
            version: '^5',
            resolveFromEnv: true,
          },
          'react-intl': {
            version: '^5',
            resolveFromEnv: true,
          },
          '@yelloan/deep-dive.theme.theme': {
            version: 'latest',
            resolveFromEnv: true,
          },
        },
      }),
```

### Additional context
I tried to force the tagging/export of the components, but I still got this error when tagging afterward. 
CF the slack thread: https://bit-dev-community.slack.com/archives/CCDHG0TPY/p1647266130175089

**Comment by benjgil** [comment]
Just updating this one
In the end it was due to the @testing-library/* dependencies being in the workspace.jsonc's regular deps section and not the peerDeps section.

**Comment by benjgil** [comment]
(re-opening after updated info from @na-ji that after some confusion this wasn't solved in the end)

**Comment by GiladShoham** [comment]
can you please attach your workspace.jsonc?

**Comment by na-ji** [comment]
> can you please attach your workspace.jsonc?

Sorry, I forgot to add it again in the GitHub issues. Here it is. 

```
/**
 * this is the main configuration file of your bit workspace.
 * for full documentation, please see: https://harmony-docs.bit.dev/workspace/configurations
 **/ {
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  /**
   * main configuration of the Bit workspace.
   **/
  "teambit.workspace/workspace": {
    /**
     * the name of the component workspace. used for development purposes.
     **/
    "name": "deep-dive",
    /**
     * set the icon to be shown on the Bit server.
     **/
    "icon": "https://www.algoan.com/wp-content/themes/algoan/assets/images/favicon.png",
    /**
     * default directory to place a component during `bit import` and `bit create`.
     * the following placeholders are available:
     * name - component name includes namespace, e.g. 'ui/button'.
     * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
     * scope - scope name only, e.g. 'compilation'.
     * owner - owner name in bit.dev, e.g. 'teambit'.
     **/
    "defaultDirectory": "{scope}/{name}",
    /**
     * default scope for all components in workspace.
     **/
    "defaultScope": "algoan-front-end.deep-dive"
  },
  /**
   * main configuration for component dependency resolution.
   **/
  "teambit.dependencies/dependency-resolver": {
    /**
     * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
     */
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@algoan/eslint-config-react": "2.4.0",
        "@commitlint/cli": "16.1.0",
        "@commitlint/config-conventional": "16.0.0",
        "@teambit/harmony": "0.2.11",
        "@types/lodash": "4.14.178",
        "@types/react-transition-group": "4.4.4",
        "@types/styled-components": "5.1.14",
        "@typescript-eslint/eslint-plugin": "4.29.3",
        "@typescript-eslint/parser": "5.7.0",
        "commitizen": "4.2.4",
        "core-js": "3.20.0",
        "cz-conventional-changelog": "3.3.0",
        "eslint": "7",
        "eslint-config-prettier": "8.3.0",
        "eslint-import-resolver-node": "0.3.6",
        "eslint-plugin-import": "2.25.4",
        "eslint-plugin-jest": "26.1.0",
        "eslint-plugin-jsx-a11y": "6.5.1",
        "eslint-plugin-mdx": "1.16.0",
        "eslint-plugin-prettier": "4.0.0",
        "eslint-plugin-react": "7.28.0",
        "eslint-plugin-react-hooks": "4.3.0",
        "husky": "7.0.4",
        "jest": "27.4.5",
        "lint-staged": "12.3.3",
        "lodash": "4.17.21",
        "prettier": "2.5.1",
        "react-intl": "5.20.12",
        "react-tooltip": "4.2.21",
        "react-transition-group": "4.4.2",
        "styled-components": "5.3.3",
        "typescript": "4.5.4"
      },
      "peerDependencies": {
        "@testing-library/dom": "8.7.2",
        "@testing-library/jest-dom": "5.16.2",
        "@testing-library/react": "12.1.2",
        "@testing-library/react-hooks": "7.0.2",
        "@testing-library/user-event": "13.5.0",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-is": "17.0.2"
      }
    },
    "packageManagerArgs": [],
    "devFilePatterns": ["**/*.spec.ts"],
    "strictPeerDependencies": true,
    "installFromBitDevRegistry": true,
    "savePrefix": ""
  },
  /**
   * workspace variants allow to set different subsets of configuration for components in your
   * workspace. this is extremely useful for upgrading, aligning and building components with a new
   * set of dependencies. a rule can be a directory or a component-id/namespace, in which case,
   * wrap the rule with curly brackets (e.g. `"{ui/*}": {}`)
   * see https://harmony-docs.bit.dev/aspects/variants for more info.
   **/
  "teambit.workspace/variants": {
    "{*-components/**}, {icons/**}, {hooks/**}, {utils/**}": {
      // uses the custom env
      "algoan-front-end.deep-dive/envs/default": {
        "teambit.harmony/aspect": {}
      }
      // uncomment the line below if you remove the custom env and remove the line above
      // "teambit.react/react": {},
    },
    "{envs/**}": {
      "teambit.harmony/aspect": {}
    },
    "{utils/**}": {
      "teambit.harmony/aspect": "-"
    },
    "{**}, !{envs/**}": {
      "teambit.pkg/pkg": {
        "packageManagerPublishArgs": ["--access restricted"],
        "packageJson": {
          "name": "@algoan/{scope}.{name}",
          "author": "Algoan",
          "license": "ISC",
          "bugs": {
            "url": "https://github.com/algoan/deep-dive/issues"
          },
          "repository": {
            "type": "git",
            "url": "git+https://github.com/algoan/deep-dive.git"
          },
          "publishConfig": {
            "scope": "@algoan",
            "registry": "https://npm.pkg.github.com/"
          }
        }
      }
    }
  }
}

```

**Comment by GiladShoham** [comment]
can you try in your env to remove all the `resolveFromEnv` and change the value to be just the version (not as an object)

**Comment by na-ji** [comment]
> can you try in your env to remove all the `resolveFromEnv` and change the value to be just the version (not as an object)

Ok I made the changes, so now my overrideDependencies looks like this:
```
      react.overrideDependencies({
        dependencies: {
          react: '-',
          'react-dom': '-',
          '@testing-library/react': '-',
          '@testing-library/react-hooks': '-',
          'styled-components': '-',
          'react-intl': '-',
          '@algoan/deep-dive.theme.theme': '-',
        },
        devDependencies: {
          react: '-',
          'react-dom': '-',
          '@testing-library/react': '-',
          '@testing-library/react-hooks': '-',
          'styled-components': '-',
          'react-intl': '-',
          '@algoan/deep-dive.theme.theme': '-',
        },
        peerDependencies: {
          react: '^17',
          'react-dom': '^17',
          '@testing-library/react': '^12',
          '@testing-library/react-hooks': '^7',
          'styled-components': '^5',
          'react-intl': '^5',
          '@algoan/deep-dive.theme.theme': 'latest',
        },
      }),
```

However, the issue is still present. I tried to export my components with bit 693.

**Comment by benjgil** [comment]
@na-ji 
I'm not sure whether this could be part of the issue, but you have a strange config in your first variant, where you consume your custom env.
You have added teambit.harmony/aspect as the config for your env, which doesnt have any positive effect and could create unintended side-effects. Please remove that and re-run `bit compile` twice to see if that 

One more thing is that I would add looser version rules to your peerDependency settings, so that they're not a specific version but a set, e.g. ^17.0.2

**Comment by na-ji** [comment]
> @na-ji I'm not sure whether this could be part of the issue, but you have a strange config in your first variant, where you consume your custom env. You have added teambit.harmony/aspect as the config for your env, which doesnt have any positive effect and could create unintended side-effects. Please remove that and re-run `bit compile` twice to see if that
> 
> One more thing is that I would add looser version rules to your peerDependency settings, so that they're not a specific version but a set, e.g. ^17.0.2

Thank you for your feedback. Concerning the variant, I don't even know from where this configuration came from. I probably got it from the documentation. So, if I understand correctly, I should have something like this:
```jsonc
  "teambit.workspace/variants": {
    "{*-components/**}, {icons/**}, {hooks/**}, {utils/**}": {
      // uses the custom env
      "algoan-front-end.deep-dive/envs/default": {}
    },
  }
```
I did this change, but as you said, it did not solve the issue. Also, I loosened the peerDependency versions as per your advice.

**Comment by Tommoore96** [comment]
I also have this problem and I have a similar setup to @na-ji.  By that I mean I have a provider component containing a styled-components ThemeProvider along with themes.  I'm importing that provider into the env and using it on my other components.  

This has caused me a few issues which I won't go into now but has led me to having this dependency override setup:
```js
    if (process.env['ENV'] !== 'local') {
      overrides.push(
        react.overrideDependencies({
          peerDependencies: {
            'styled-components': {
              version: '5.3.3',
              resolveFromEnv: true,
            },
            '@testing-library/react': {
              version: '^12.0.0',
              resolveFromEnv: true,
            },
          },
        })
      );
    }
```

My workspace.jsonc is:
```json
{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  "teambit.workspace/workspace": {
    "name": "SPIKE-bit-ui",
    "icon": "https://static.bit.dev/bit-logo.svg",
    "defaultDirectory": "{scope}/{name}",
    "defaultScope": "koodoo.koomeleon"
  },
  "teambit.dependencies/dependency-resolver": {
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@teambit/design.ui.external-link": "0.0.344",
        "@teambit/documenter.theme.theme-compositions": "4.1.1",
        "@teambit/documenter.ui.copy-box": "4.1.1",
        "@teambit/eslint-config-bit-react": "~0.0.367",
        "@types/styled-components": "5.1.23",
        "@typescript-eslint/eslint-plugin": "4.29.3",
        "eslint-import-resolver-node": "0.3.6",
        "eslint-plugin-import": "2.22.1",
        "eslint-plugin-jest": "24.4.0",
        "eslint-plugin-jsx-a11y": "6.4.1",
        "eslint-plugin-mdx": "1.15.0",
        "eslint-plugin-react": "7.25.1",
        "jest-styled-components": "7.0.8",
        "react-is": "17.0.2",
        "sass": "1.43.4",
        "styled-components": "5.3.3",
        "uuid": "8.3.2"
      },
      "peerDependencies": {
        "@testing-library/dom": "8.11.1",
        "@testing-library/react": "12.0.0",
        "@testing-library/user-event": "13.5.0",
        "jest-styled-components": "7.0.8",
        "react": "17.0.2",
        "react-dom": "17.0.2",
        "react-is": "17.0.2",
        "styled-components": "5.3.3"
      }
    },
    "packageManagerArgs": [],
    "devFilePatterns": ["**/*.spec.ts"],
    "strictPeerDependencies": true,
    "installFromBitDevRegistry": true,
    "savePrefix": ""
  },
  "teambit.workspace/variants": {
    "{ui/**}, !{ui/theme-provider}": {
      "koodoo.koomeleon/extensions/react-env": {}
    },
    "{ui/theme-provider}": {
      "teambit.react/react": {}
    },
    "{content/**}": {
      "teambit.mdx/mdx": {}
    },
    "{theming/**}": {
      "defaultScope": "koodoo.koomeleon"
    },
    "{extensions/**}, {aspects/**}, {apps/**}": {
      "teambit.harmony/aspect": {}
    }
  },
  "teambit.generator/generator": {
    "aspects": ["tommoore96.bit-spike/generator/theme-json"]
  },
  "tommoore96.bit-spike/generator/theme-json": {}
}
```

I've tried your recommended changes but none of them work either.

**Comment by jenmak-tangelo** [comment]
> Hi @na-ji 

I see you have commitlint and husky installed. Where did you put your configuration files to get these to work with Bit?

Thank you

> > can you please attach your workspace.jsonc?
> 
> Sorry, I forgot to add it again on the GitHub issues. Here it is.
> 
> ```
> /**
>  * this is the main configuration file of your bit workspace.
>  * for full documentation, please see: https://harmony-docs.bit.dev/workspace/configurations
>  **/ {
>   "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
>   /**
>    * main configuration of the Bit workspace.
>    **/
>   "teambit.workspace/workspace": {
>     /**
>      * the name of the component workspace. used for development purposes.
>      **/
>     "name": "deep-dive",
>     /**
>      * set the icon to be shown on the Bit server.
>      **/
>     "icon": "https://www.algoan.com/wp-content/themes/algoan/assets/images/favicon.png",
>     /**
>      * default directory to place a component during `bit import` and `bit create`.
>      * the following placeholders are available:
>      * name - component name includes namespace, e.g. 'ui/button'.
>      * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
>      * scope - scope name only, e.g. 'compilation'.
>      * owner - owner name in bit.dev, e.g. 'teambit'.
>      **/
>     "defaultDirectory": "{scope}/{name}",
>     /**
>      * default scope for all components in workspace.
>      **/
>     "defaultScope": "algoan-front-end.deep-dive"
>   },
>   /**
>    * main configuration for component dependency resolution.
>    **/
>   "teambit.dependencies/dependency-resolver": {
>     /**
>      * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
>      */
>     "packageManager": "teambit.dependencies/pnpm",
>     "policy": {
>       "dependencies": {
>         "@algoan/eslint-config-react": "2.4.0",
>         "@commitlint/cli": "16.1.0",
>         "@commitlint/config-conventional": "16.0.0",
>         "@teambit/harmony": "0.2.11",
>         "@types/lodash": "4.14.178",
>         "@types/react-transition-group": "4.4.4",
>         "@types/styled-components": "5.1.14",
>         "@typescript-eslint/eslint-plugin": "4.29.3",
>         "@typescript-eslint/parser": "5.7.0",
>         "commitizen": "4.2.4",
>         "core-js": "3.20.0",
>         "cz-conventional-changelog": "3.3.0",
>         "eslint": "7",
>         "eslint-config-prettier": "8.3.0",
>         "eslint-import-resolver-node": "0.3.6",
>         "eslint-plugin-import": "2.25.4",
>         "eslint-plugin-jest": "26.1.0",
>         "eslint-plugin-jsx-a11y": "6.5.1",
>         "eslint-plugin-mdx": "1.16.0",
>         "eslint-plugin-prettier": "4.0.0",
>         "eslint-plugin-react": "7.28.0",
>         "eslint-plugin-react-hooks": "4.3.0",
>         "husky": "7.0.4",
>         "jest": "27.4.5",
>         "lint-staged": "12.3.3",
>         "lodash": "4.17.21",
>         "prettier": "2.5.1",
>         "react-intl": "5.20.12",
>         "react-tooltip": "4.2.21",
>         "react-transition-group": "4.4.2",
>         "styled-components": "5.3.3",
>         "typescript": "4.5.4"
>       },
>       "peerDependencies": {
>         "@testing-library/dom": "8.7.2",
>         "@testing-library/jest-dom": "5.16.2",
>         "@testing-library/react": "12.1.2",
>         "@testing-library/react-hooks": "7.0.2",
>         "@testing-library/user-event": "13.5.0",
>         "react": "17.0.2",
>         "react-dom": "17.0.2",
>         "react-is": "17.0.2"
>       }
>     },
>     "packageManagerArgs": [],
>     "devFilePatterns": ["**/*.spec.ts"],
>     "strictPeerDependencies": true,
>     "installFromBitDevRegistry": true,
>     "savePrefix": ""
>   },
>   /**
>    * workspace variants allow to set different subsets of configuration for components in your
>    * workspace. this is extremely useful for upgrading, aligning and building components with a new
>    * set of dependencies. a rule can be a directory or a component-id/namespace, in which case,
>    * wrap the rule with curly brackets (e.g. `"{ui/*}": {}`)
>    * see https://harmony-docs.bit.dev/aspects/variants for more info.
>    **/
>   "teambit.workspace/variants": {
>     "{*-components/**}, {icons/**}, {hooks/**}, {utils/**}": {
>       // uses the custom env
>       "algoan-front-end.deep-dive/envs/default": {
>         "teambit.harmony/aspect": {}
>       }
>       // uncomment the line below if you remove the custom env and remove the line above
>       // "teambit.react/react": {},
>     },
>     "{envs/**}": {
>       "teambit.harmony/aspect": {}
>     },
>     "{utils/**}": {
>       "teambit.harmony/aspect": "-"
>     },
>     "{**}, !{envs/**}": {
>       "teambit.pkg/pkg": {
>         "packageManagerPublishArgs": ["--access restricted"],
>         "packageJson": {
>           "name": "@algoan/{scope}.{name}",
>           "author": "Algoan",
>           "license": "ISC",
>           "publishConfig": {
>             "scope": "@algoan",
>             "registry": "https://npm.pkg.github.com/"
>           }
>         }
>       }
>     }
>   }
> }
> ```

**Comment by na-ji** [comment]
> Hi @na-ji
> 
> I see you have commitlint and husky installed. Where did you put your configuration files to get these to work with Bit?
> 
> Thank you

Hi! I've just put their config on the root of the repository (same level as `workspace.jsonc`). Once installed and configured, they just work as is.
