### ISSUE TITLE
rename parent folder to parent in bit add dsl's

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#555]

**Comment by amitgilad3** [comment]
ווווווווווווווווווווווווווווומממייחממממממצחחחויחויחחחחחחמחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחחצממממממחחחוחחחח חחח מ"מ חחחח צצצצחצצצצצצצחחןחצלוווחןןןןןווחצןןווחחחחחחחחחחח
