### ISSUE TITLE
No preview available in bit.dev using lit aspect

### ISSUE THREAD

**Issue by marcelpanse** [teambit/bit#5551]
### Describe the bug
When running locally the previews are showing fine for the components, but after a tag and export to bit.dev the previews won't show. Instead a message shows "no preview available" and a 404 error in the network requests tab of the chrome debugger.

### Steps to Reproduce
1. Go to https://bit.dev/unless/component-library/element/header
1. Happens in all the other components in the same scope as well

### Expected Behavior
It should show the rendered component

### Screenshots, exceptions and logs
Screenshot bit.dev: https://share.getcloudapp.com/JruOXgER
Screenshot local: https://share.getcloudapp.com/NQuNd1n1

### Specifications
* Bit version: 0.0.667
* Workspace type: harmony
* Node version: v14.18.3
* npm / yarn version: 6.14.15
* Platform: OSX

_for harmony workspace_

* relevant env: unless.component-library
* relevant aspects: teambit.web-components/lit@0.0.17

**Comment by GiladShoham** [comment]
Thanks for reporting this, I've just exported a new version of the lit env (0.0.20), please upgrade the lit env version for you component, and try to tag and export again.
@benjgil FYI

**Comment by marcelpanse** [comment]
@GiladShoham I updated to 0.0.20 and it now works, thanks!
