### ISSUE TITLE
How long will support vue to harmony beat 

### ISSUE THREAD

**Issue by xiaolee55** [teambit/bit#5560]
our team is using vue but not react,when we could use it

**Comment by didamaran** [comment]
yeah, we too. tried to test some very basic components on the 'previous bit' but they're failing. seems that vue support in the old bit version is not really production ready

**Comment by xiaolee55** [comment]
@didamaran maybe we could maintain the vue feature by community(if bit's team has no plan to advance vue's support😄

**Comment by gregg-cbs** [comment]
I found bit 2 or 3 years ago and vue support was being promised back then :/
If no vue support what else do we have that is similar to bit.dev

**Comment by didamaran** [comment]
unfortunately there seems to be no comparable service, at least as far as I know.
I tried to install and import a github repo but wasn't able to figure it out how you need to prepare your repo and imports to make it it work

**Comment by gregg-cbs** [comment]
I found webpacks Module Federation.
That suits my projects better than bit.

Have a look.

**Comment by didamaran** [comment]
looks great, thanks for the tipp! webpack 5 though, which means no vite if i understand it right

**Comment by xiaolee55** [comment]
> for now I'm sticking to installing my components from a common repo of mine via `npm i github:username/myrepository`

what's mean

**Comment by didamaran** [comment]
you can install any repo from github by username and reponame and then import the components of that repo via `import comp from '../node_modules/reponame/src/components/comp.vue' `

**Comment by Cyclodex** [comment]
I have read years ago about having vue support and improving it, now I tested bit.dev and I don't get it working at all, is vue still not supported, not even the V2 ?

I am not able to import the vue env as described (`bit import bit.envs/bundlers/vue`) as of https://bit.cloud/bit/envs/bundlers/vue

**Comment by mrillusion** [comment]
Please bring Vue support @itaymendel

**Comment by NexZhu** [comment]
Voting+1
I think it's a huge potential user space.

**Comment by fateeand** [comment]
+1

**Comment by boygiandi** [comment]
+1 
Still waiting

**Comment by loloncar** [comment]
+1

**Comment by itaymendel** [comment]
you can follow vue support progress here - https://bit.cloud/teambit/vue
i trust there are a few more weeks until this will be 100% done and in the main documentation portal as well.
