### ISSUE TITLE
Error following Angular guide

### ISSUE THREAD

**Issue by twentyonesquared** [teambit/bit#5575]
## Expected Behavior
The simple my-button component compiles and can be view as described in the guide.

## Actual Behavior
Following instructions and running **bit start** result in the following error:
 _C:\dev\bit\buttontest\node_modules\@company\scope.ui.my-button\my-button.composition.ts is missing from the TypeScript compilation....._

## Steps to Reproduce the Problem
Follow the guide at https://github.com/teambit/bit-angular

**Comment by itaymendel** [comment]
fixed here - https://github.com/teambit/bit/pull/5569
please upgrade Bit and run the steps again.
