### ISSUE TITLE
devDependcies not articulated correctly in package.json of component from test files

### ISSUE THREAD

**Issue by kumargauravin** [teambit/bit#5581]
## Expected Behavior
If an external package is added in test spec files, it should be added to devDependencies of that bit component.
bit compile should fail.

## Actual Behavior
bit show and bit install ignore this dependency (from the test.spec file).
bit compile successfully compiles
bit status shows the missing dependency

## Steps to Reproduce the Problem
1. Add a Test File Manually to a component
1. Have an external package import in test file like react-test-renderer which should not be dependency in a project
1. bit install and inspect node_modules, package is not available.
1. bit compile, it passes
1. bit status, shows the missing dependency

## Specifications
* Bit version: 0.0.684
* Node version: 14.6
* npm / yarn version: 1.22.17
* Platform: Windows
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
Hi,

Did you ran `bit install ...` for the dependency?
Bit does not automatically installs dependencies, it automatically _resolves_ dependencies according to `import` statements and what's available in `node_modules`.

**Comment by kumargauravin** [comment]
Yes, so my question was say some dependency is only required in test.spec file.
If you add that dependency in devDependencies of workspac.jsonc and do bit install, it does not loads that dependency to node_modules. Only peerDeps or Deps getting installed.

**Comment by itaymendel** [comment]
`workspace.jsonc` does not support `devDependnecies`. you just add them as dependencies for the workspace, then Bit will contextually set them as dev for components that use them as dev-deps.
