### ISSUE TITLE
Unified Host Context

### ISSUE THREAD

**Issue by luvkapur** [teambit/bit#5584]
### Description
Currently when running bit on a workspace or a scope, the UI receives the list of components either from the Scope Context or the Workspace Context, depending on the host. 

The current implementation forces the consumer to know the host and explicitly query the component data from the relevant context

### Describe the solution you'd like
Proposing a single unified host context that is hydrated with the components from the relevant host on app start

```
{
  components: ComponentDescriptor[],
  displayName: string
}
```

**Comment by NitsanCohen770** [comment]
@luvkapur any updated on this one?

**Comment by luvkapur** [comment]
@NitsanCohen770 this can be closed. It was more of an issue when we were serving both workspace and scope with the same Bit UI. 

Now with the new Bit Cloud, this is just a nice to have to make our life a bit easier when developing from the workspace, which we can address later.
