### ISSUE TITLE
Bit reads form .npmrc while using yarn

### ISSUE THREAD

**Issue by shepitchakpavlo** [teambit/bit#5624]
### Describe the bug
Even though Bit uses yarn v3 as a package manager, it continues reading from .npmrc instead of .yarnrc.yml

In my company we use artifactory as an npm registry. It's specified in .yarnrc.yml but ignored during the `bit install` command.
If I specify registry in .npmrc, it works.
Sounds like a workaround, but there are other options specified in .yarnrc.yml like unsafeHttpWhitelist that don't have support in .npmrc

I was going to be fixed by https://github.com/teambit/bit/pull/5500. But the issues is not resolved.

### Steps to Reproduce
1. configure custom npm registry in .yarnrc.yml
1. run 'bit install', it fails
1. configure custom npm registry in .npmrc
1. run 'bit install', it works

### Expected Behavior
Bit should use .yarnrc.yml during install and ignore .npmrc

### Specifications
* Bit version:0.0.695
* Workspace type: harmony
* Node version: 14.18.0
* npm / yarn version: yarn v3.2
* Platform: MacOS Monterey

_for harmony workspace_

* relevant env: custom env with only 1 new webpack loader
* relevant aspects

UPDATE:
this issue `bit install` can not be reproduced in 100%, but can be always be reproduced during the `bit tag` command.

**Comment by zkochan** [comment]
I don't think this is related to the changes in #5500. I just rechecked, the changes in that PR are working.

How do you configure the registry in `.yarnrc.yml`? When you use `.npmrc` do you put it at the root of your workspace? How do you configure the registry via `.npmrc`?
