### ISSUE TITLE
Need some helps update "postcss-preset-env": "6.7.0" to latest verion `7.4.3` in `@teambit/react` to resolve error TypeError: Cannot read property 'raws' of undefined

### ISSUE THREAD

**Issue by kimthangatm** [teambit/bit#5627]
Expected: Need to update "postcss-preset-env": "6.7.0" to latest verion `7.4.3` in `@teambit/react`

So, can I do it in bit config workspace or waiting teambit upgrade? Thanks.

### Description
Currently I use antd and these file less is: https://github.com/ant-design/ant-design/blob/master/components/style/themes/variable.less#L33

It will compile to `node_modules/antd/dist/antd.variable.css` and you can see the line 25: `  --ant-primary-color-deprecated-pure: ;`

![Screenshot from 2022-03-31 09-27-33](https://user-images.githubusercontent.com/7090588/160992419-e6d406d9-800b-48a3-8a8b-e57f968fb423.png)

When I import these file and bit compile throw error: `TypeError: Cannot read property 'raws' of undefined`

> Module build failed (from ../../../../../../home/mi/.bvm/versions/0.0.687/bit-0.0.687/node_modules/@teambit/react/node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'raws' of undefined
    at Parser.space (/home/mi/.bvm/versions/0.0.687/bit-0.0.687/node_modules/postcss-values-parser/lib/parser.js:387:25)

I try to use `postcss cli` to compile antd css with `postcss-preset-env: 7.4.3` and everything worked. So I want to upgrade to `@teambit/react`.

Example

```
yarn postcss node_modules/antd/dist/antd.variable.css -o ./output.css
```

### Specifications
* Bit version: 0.0.687
* Node version: v12.22.5
* npm / yarn version: 1.22.11
* Platform: Ubuntu
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
we have re-done the react-env for bit. now you have full control over the webpack and other configs.
pelase follow this - https://bit.cloud/teambit/react/react-env
