### ISSUE TITLE
'bvm' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by miliko0022** [teambit/bit#5638]
I have installed `npx @teambit/bvm install`.  After that I want to check bvm and bit. bit working, and bvm throws an error 

>bvm : The term 'bvm' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a 
path was included, verify that the path is correct and try again.
At line:1 char:1
> bvm -v 

![image](https://user-images.githubusercontent.com/32756313/161401482-e3cb6245-aa28-46d7-ae48-7fc40c4e166e.png)

**Comment by itaymendel** [comment]
hi, please see this section in the docs, might be that the env var is not set correctly?
https://bit.dev/docs/reference/using-bvm#global-bit-install-location-was-not-found

**Comment by miliko0022** [comment]
I think the path is right

![image](https://user-images.githubusercontent.com/32756313/161437401-3052bdf3-5492-4178-8be4-727c8147419a.png)

**Comment by clairefields15** [comment]
I'm also seeing the same error as @DCosti . I ran all three suggested setx commands below and [in the docs](https://harmony-docs.bit.dev/reference/using-bvm/) and still seeing that error.  Tried these commands in powershell and in powershell as an administrator. 
```
setx path "%path%;%AppData%\npm"
setx path "%path%;C:\Users\USER\AppData\Local\.bvm"
setx path "%path%;%LocalAppData%\.bvm"
```

**Comment by SABERGLOW** [comment]
Experiencing same issues as @clairefields15  and @DCosti . tried all the fixes mentioned in the docs, nothing works :(

**Comment by DCosti** [comment]
I managed somehow to install bvm on a different machine but then when I tried to use one of bit's commands, for example `bit status` and encounter the same error but for bit this time. 
![image](https://user-images.githubusercontent.com/41594981/167101750-34d98319-cbc1-4109-82fb-80523352b391.png)
But, as you can see from image bellow, I have bit installed 
![image](https://user-images.githubusercontent.com/41594981/167101909-de4d06d1-b345-43d6-b3f2-27f1fd7a2243.png)

**Comment by benjgil** [comment]
For anyone experiencing this issue - there are known issues with powershell and working with env variables.
Please try this with another shell and see if that solves the issue

**Comment by DCosti** [comment]
Hi! It worked for me using CMD. Appreciate your help @benjgil

**Comment by sukhchand24** [comment]
Hi, 
I am still facing the same issue "'bvm' is not recognized as an internal or external command,operable program or batch file." after setting up the environment variables.
