### ISSUE TITLE
Skip packages installation of imported bit components

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#564]
Once https://github.com/teambit/bit/issues/506 is implemented, a package.json may contain relative paths of imported components. 
As part of the import process, it runs 'npm/yarn install', which might copy the local component into the node_modules directory of its dependent.
Since we don't need this copy, and we remove that folder anyway afterward in the linking process, it'd be better (performance wise) to not install it in the first place.
A solution would be to have a copy of the package.json file without local components, and then once the 'npm/yarn install' is finished, copy the original package.json back.

**Comment by itaymendel** [comment]
added a flag to allow such feature
