### ISSUE TITLE
(Lit, Web)-component preview issue

### ISSUE THREAD

**Issue by ArmanSarkisov** [teambit/bit#5672]
I have created 2 components and exported them, one of them was created via React another one via Lit. and in the bit.cloud I can see only components created via React, the other one I saw is "No preview available". I added the Lit component into another project (yarn add …) and it works. can you help me with that

### Steps to Reproduce
1. bit new lit my-lit-workspace --aspect teambit.web-components/lit
1. bit create lit my-component
1. bit link
1. bit compile
1. bit tag
1. bit export

### Screenshots
![](https://user-images.githubusercontent.com/51702553/162432593-3ae6044d-cee3-4974-b359-de33abb307d3.png)
![](https://user-images.githubusercontent.com/51702553/162432607-9925588c-1b0c-4b7e-9786-941d8a7dd02a.png)

### Specifications
* Bit version: 0.0.703
* Workspace type: (harmony/legacy) harmony
* Node version: 14.18.2
* npm / yarn version: 6.14.15
* Platform: macOS

**Comment by matteoquintero-aflore** [comment]
To contribute, it seems that it is due to a duplication in the call of some library.

`Uncaught DOMException: CustomElementRegistry.define: 'p' is not a valid custom element name`

![bug](https://user-images.githubusercontent.com/87438107/174147621-df540638-e09d-4773-a4f3-d2dc6fb9c879.png)

**Comment by itaymendel** [comment]
hi,

refactored version for lit is now available - https://bit.cloud/teambit/web-components/lit
