### ISSUE TITLE
Cannot install or import @teambit components

### ISSUE THREAD

**Issue by elliottye** [teambit/bit#5694]
### Describe the bug
When running `bit import` or `bit install`, packages of teambit components would fail to install with the following error message:
`GET https://registry.yarnpkg.com/@teambit%2Fbase-ui.button: Not Found - 404`.

The `@teambit/base-ui.button` is available on yarnpkg registry, but it always returns a 404. There's no such behavior exhibited when installing other more common deps with `bit install` though, eg. `bit install rxjs` would just be fine.

### Steps to Reproduce
1. Initialize a bit workspace with `bit init`
1. Typing `bit install @teambit/base-ui.button`
1. You'd get `GET https://registry.yarnpkg.com/@teambit%2Fbase-ui.button: Not Found - 404` as the error message

### Expected Behavior
Successful install of a teambit component

### Specifications
* Bit version: 0.0.710
* Workspace type: (harmony/legacy)
* Node version: 14.18.0
* npm / yarn version: 1.22.15
* Platform: MacOS Catalina

**Comment by itaymendel** [comment]
To install components from bit.cloud you need to add scoped registry to your npmrc/yarnrc file.
for example - 

```
@teambit:registry=https://node.bit.cloud
```

**Comment by elliottye** [comment]
> To install components from bit.cloud you need to add scoped registry to your npmrc/yarnrc file. for example -
> 
> ```
> @teambit:registry=https://node.bit.cloud
> ```

And after that, the error becomes `GET https://node.bit.cloud/@teambit%2Fbase-ui.button: Not Found - 404`. Any idea why?
