### ISSUE TITLE
Migrate bit-bin and bit-javascript to monorepo

### ISSUE THREAD

**Issue by davidfirst** [teambit/bit#570]
Consider using Lerna and yarn workspaces.

With the current approach of having two separate git repos, it makes it hard to test bit-javascript, and updating bit-javascript code is time-consuming.

**Comment by GiladShoham** [comment]
Instead of migrate to mono repo we just make sure the CI is using bit-javascript from github.
see: https://github.com/teambit/bit/pull/772
