### ISSUE TITLE
fatal: unable to connect to a remote legacy SSH server from Harmony client

### ISSUE THREAD

**Issue by elliottye** [teambit/bit#5706]
Hello,

I was trying to install the Stencil compiler with `bit import bit.envs/compilers/stencil`. After a few seconds the CLI gave up and printed this error message:

`fatal: unable to connect to a remote legacy SSH server from Harmony client`

I tried to attach a `-c` option (seemingly deprecated) as given by the bit.envs repo but to no avail. Is there anything I can do to make the import work? Thanks.

P.S. I already have `@teambit` npm registry point to `https://node.bit.cloud` but I hardly think it's relevant.

**Comment by itaymendel** [comment]
hi,

the stencil compiler is a leftover from past experimentation with bit-legacy.
the new bit-client does not support using legacy plugins.
at the moment we do not have a plugin to support stencil.


if you are looking for web-components support, we have implemented support for Lit. please see the new doc portal here - https://bit.dev and search for lit.

**Comment by chujain-fang** [comment]
hello elliottye，have u solveld this problem？ I have met the same question。thans for ur time！
