### ISSUE TITLE
Unable to use 'bvm' : "bash: bvm: command not found"

### ISSUE THREAD

**Issue by writam-roy** [teambit/bit#5730]
### Describe the bug
A clear and concise description of the issue.

### Steps to Reproduce
1.Using the onboarding document of bvm , I installed bvm (harmony-docs.bit.dev/reference/using-bvm/) using the following command  : yarn global add teambit/bvm

1. After this I am constantly getting the following error : "bash: bvm: command not found" upon trying to use any bvm command like bvm upgrade and so on ( Note : All the steps mentioned to setting path has been tested but nothing works for me, I have manually added bvm path in my system  - C:\Users\myname\AppData\Local\.bvm as an additional try,even this doesn't work)

### Expected Behavior
I should be able to use bvm commands

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/84510770/164740967-ece5e036-ddef-4596-84f7-e05250543ff4.png)

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.641
* Workspace type: (harmony/legacy) - legacy
* Node version: 14.16.0
* npm / yarn version: 1.21.1
* Platform: Windows

_for harmony workspace_

* relevant env 
* relevant aspects

_for leagacy_

* Bit compiler (include version): unable to find the right command
* Bit tester (include version): unable to find the right command

**Comment by GiladShoham** [comment]
please see here - https://bit.dev/docs/reference/using-bvm#bvm-is-not-recognized-in-your-terminal

**Comment by webmatth** [comment]
> please see here - https://bit.dev/docs/reference/using-bvm#bvm-is-not-recognized-in-your-terminal

link now point to a 404 page 😞
