### ISSUE TITLE
type errors from transition to react 18

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5746]
This is a reference github issue so we can track all the errors related to the switch to React 18.

I'm seeing two major sources for errors:

1. Using ReactNode when ComponentType is needed. 
1. Using FC without props with children

## ReactNode vs ComponentType
For some reason, this was allowed in React17 types:

```tsx
const someNode: ReactNode = ( ) => <div>hello world</div>
```

Some libraries mistakenly used type `ReactNode` because of this. This problem will be resolved once they fixed their type.

## FC without children
A breaking change in React18 types is the omission of `children` from component props by default.

For example:

```tsx
const Childrenless: FC = () => <div>hello world</div>;

function App() {
  return <Childrenless>
    will show error here.
  </Childrenless>
}
```

This will be resolved once the package maintainer will fix the type to be `FC<PropsWithChildren<{}>>`

**Comment by itaymendel** [comment]
irrelevant.
use https://bit.cloud/teambit/react/react-env
