### ISSUE TITLE
React18 for Bit UI

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5751]
## IMPORTNAT
This is **NOT** about how to have React18 for your components. This is aoubt migrating Bit's UI to react18.
follow this to get react18 components - https://bit.cloud/teambit/react/react-env

In this issue I will track the milestones needed to switch from React 17 to React 18.

### Breaking changes:
* new render method (see below)
* ~~not supported by react native (!)~~
* new `@types/react` that breaks if there are v17 and v18 in the same project. (should be resolved by #5750.)
  * these type errors have disappeared. It's possible the facebook team and the eco system solved this issue.
* otherwise pretty safe. :)

### Stability
v18 is rather stable, but is still getting quick fixes.
The type changes are now rippling through the community, so it might take a while to get all the types fixed.

## Suggested path
* [x] wait for #5443
* [ ] upgrade `@teambit/react` to React 18 (easy)
* [x] make sure React Native works with React 18 (easy, but not released yet)
  --> Released, v0.69.0
* [ ] create `@teatbit/react.env-17` as an escape hatch for developer who still want to use react 17.
  * [ ] this env will keep using an older version of docs-app still using the old `ReactDOM.render()` method

details:

* [ ] Upgrade package version to `^18.0.0`, for `react`, `react/dom`, `@types/react` `@types/react-dom`
* [ ] Upgrade `@testing-library/react` to `^13.0.0`
* [ ] Use the new syntax for ReactDOM.render 
* [x] Handle any type errors (will be resolved by #5750 and #5749)

**Comment by KutnerUri** [comment]
thanks. The biggest blocker is waiting for #5443

**Comment by rishabh-ti** [comment]
How much time more till we can use React 18 in BIT?

**Comment by xencodes** [comment]
any update regarding react 18?

**Comment by boehlke** [comment]
https://github.com/teambit/bit/pull/5443 is merged, seems like we have another check! With that merge, why is "create @teatbit/react.env-17 as an escape hatch for developer who still want to use react 17." needed any more? Did I misunderstand?

**Comment by hyoretsu** [comment]
Come on, I want to use components in a React 18 project without getting warned by peer dependencies.

**Comment by acrodemocide** [comment]
Are there any status updates on the progress of this issue? My project is using React 18, so whenever I import a component from Bit, I get warnings about peer dependencies. I've tried creating a custom environment using React 18 and the latest @testing-library/react, but the tests fail because it's still running in React 17. 

We're using Bit to share components across multiple teams, but it's a real challenge when all of our components in Bit are limited to React 17.

**Comment by antizhyk** [comment]
Has anyone solved the problem yet?

**Comment by DmacMcgreg** [comment]
This is a massive blocker for our team to use blitz... Many libraries are now only being built for React 18, and theres no way we're going to invest so much time into making components in bit that rely on outdated libraries for React 17.

**Comment by itaymendel** [comment]
hi,

this issue is unrelated to react-18 support for bit.
this is for runnign bit with react18,
