### ISSUE TITLE
`bit tag --persist` not working on CI

### ISSUE THREAD

**Issue by elliottye** [teambit/bit#5765]
Hi,

I was trying to publish my components to our private Artifactory registry via CircleCI jobs. All the other steps in the only build job work fine but it got stuck on `bit tag` with the following error:

`fatal: "components/basics/header@0.0.1" has a dependency "envs/custom-react-env".
this dependency was not included in the tag command.`

Here's the folder structures of my workspace:

* components
      basics
          header
      ..
* envs
      custom-react-env

The local custom React env component is for customizing Jest and other tools, and it's applied to all components under `components/**` by `bit env set "components/**/*" envs/custom-react-env`. And it looks fine when running `bit env`.

But I still can't publish the components with `bit tag --persist` on my CI after I've done `bit tag --soft` locally. It's strange that `bit tag --persist` works just fine on my local machine. Any idea why?

You know I've tried `bit tag envs/custom-react-env "components/**/*" --persist --ignore-issues --unmodified`, literally all the combinations of options because I thought it might have something to do with the custom React env component. But still to no avail. Please help!

### Specifications
* Bit version: 0.0.724
* Workspace type: (harmony/legacy) harmony
* Node version: 14.18.0
* npm / yarn version: NPM 6.14.15
* Platform: MacOS Catalina and CircleCI

**Comment by itaymendel** [comment]
when running `bit tag`, it's recommended not to set specific components, as often you may end up with dep-management problems.
i'd recommend moving to latest release of bit, as many of these items were resolved.
