### ISSUE TITLE
Bit tag fails with webpack error

### ISSUE THREAD

**Issue by NiklasMoss** [teambit/bit#5772]
### Description
I don't know if this is a bug in bit or an issue with the local setup of the developer machine. A developer in my team running Windows is having issues running `bit tag`. Whenever she runs it, she gets the following error.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/90253831/166440391-dadbacc3-0f9c-41b3-b7cd-64d9885205c5.png)

I run `bit tag` on the same codebase without any issues on my M1 Mac. I had a similar issue and updated bvm to version 0.0.37 after reading that support for Apple's new architecture wasn't added until bvm 0.0.37. She's running bvm version 0.0.36.

We've taken all steps to ensure that the code and environment on her computer is equal to mine. We've deleted the repo folder, recloned it, imported from bit and run bit install. 

### Specifications
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/90253831/166440658-5c5921c3-fd67-484c-be36-267edb6f6941.png)

### Context and additional information
She's been able to run `bit tag` successfully once. It seems that after the same components were modified on my machine, she is no longer able to run the command successfully but instead gets the above error.

From my research, it seems to somehow be related to Webpack. As you can see from the error message, we are using the default teambit react configuration, so we haven't been setting up any funky custom Webpack stuff.

I have a nagging suspicion that it might be related to me running on an M1 ARM architecture and her being on a x86_64 Intel based machine, in particular since I was having the issue, fixed it on my side, tagged and exported and now she's having issues on her side.

**Comment by itaymendel** [comment]
please update to latest version of bvm and install bit, to get pre-build bundles for your respected systems
```
npm i -g @teambit/bvm
bvm install
```
