### ISSUE TITLE
Missing dependencies for bit run app

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5787]
Getting these errors when running bit app:

```
Error: Cannot find module 'webpack'
...
ERROR in ./node_modules/.pnpm/registry.npmjs.org+graphql-tag@2.12.6/node_modules/graphql-tag/lib/index.js 2:0-32
Module not found: Error: Can't resolve 'graphql' in '/Users/kutner/projects/bit-uis/blog/node_modules/.pnpm/registry.npmjs.org+graphql-tag@2.12.6/node_modules/graphql-tag/lib'
resolve 'graphql' in '/Users/kutner/projects/bit-uis/blog/node_modules/.pnpm/registry.npmjs.org+graphql-tag@2.12.6/node_modules/graphql-tag/lib'
...
Error: Can't resolve 'subscriptions-transport-ws' in '/Users/kutner/projects/bit-uis/blog/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.6.2_react@17.0.2/node_modules/@apollo/client/link/ws'
resolve 'subscriptions-transport-ws' in '/Users/kutner/projects/bit-uis/blog/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.6.2_react@17.0.2/node_modules/@apollo/client/link/ws'
  Parsed request is a module
  using description file: /Users/kutner/projects/bit-uis/blog/node_modules/.pnpm/registry.npmjs.org+@apollo+client@3.6.2_react@17.0.2/node_modules/@apollo/client/link/ws/package.json
```

Some of these make sense - they are indirect peer dependencies of the code, like webpack and graphql.

However `subscriptions-transport-ws` is a dependency of bit, and should not appear here.

### Steps to Reproduce
1. `bit import teambit.cloud/apps/bit-cloud`
1. `bit install webpack` (or the process won't even start)
1. `bit run bit-cloud-blog`
1. wait for it..
1. --> getting the errors

### Expected Behavior
Should install or warn about the missing the dependencies.

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/5400361/167301688-9fc83650-5bdc-4c13-8bd3-a3a9c11fd63e.png)

### Specifications
* Bit version: 726
* Workspace type: harmony
* Node version: 12.22.10
* Platform: MacOS

**Comment by KutnerUri** [comment]
might be fixed by #6003

**Comment by efengx** [comment]
Same mistake.

bit version:
![image](https://user-images.githubusercontent.com/25926678/177939523-46845d52-7c1e-481a-9330-7f01e3d4e42f.png)

bit list:
![image](https://user-images.githubusercontent.com/25926678/177939632-bb11a197-5fbf-40c5-a23b-a2bad1b36b61.png)

**Comment by itaymendel** [comment]
this is a resolve of a missing peerDep, which was defined for in the env.
to get these deps auto-installed, set `rootComponents:true` in `workspace.jsonc`.
