### ISSUE TITLE
Error when trying to build some components

### ISSUE THREAD

**Issue by samuelrcm2** [teambit/bit#5804]
### Error in webpack cache when trying to build some specific components
When trying to build the component general/icon in the repro below, I get the following error:

`The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "my-scope/envs/plasma-ui-react"
component: my-scope/general/icon
message: Couldn't find configuration for either precaching or runtime caching. Please ensure that the various glob options are set to match one or more files, and/or configure the runtimeCaching option.`

### Steps to Reproduce
1.clone the repository
1.Run bit install && bit compile && bit build general/icon

### Expected Behavior
To build the component successfully

### Screenshots, exceptions, and logs
I've tried building using the bit standard react env and the error is still happening. I also tried running bit init --reset-new.
If I try to build the component display/grid the build runs successfully and their dependencies are very similar.

![image](https://user-images.githubusercontent.com/55411951/168143140-c6f12e7b-0f70-4b6b-9fc3-f9490bd15005.png)
![image](https://user-images.githubusercontent.com/55411951/168143253-4851f521-2c61-41fa-9e2f-af66c2fe9c33.png)

### Specifications
* Bit version: 0.0.731 || 0.0.695 || 0.0.694
* Workspace type: harmony
* Node version: 16.14.0
* npm / yarn version: 8.6.0
* Platform:
* relevant env: plasma-ui-react
* relevant aspects

### Additional context
A [repro repository](https://github.com/samuelrcm2/bit-repro)

**Comment by GerkinDev** [comment]
Related to https://github.com/teambit/bit/issues/5653

**Comment by itaymendel** [comment]
hi,

please use the updated version of the react-plugin as suggested here - https://bit.cloud/teambit/react/react-env
