### ISSUE TITLE
Publish to npm when a OTC code is required for 2FA

### ISSUE THREAD

**Issue by sbland** [teambit/bit#5812]
I have a workflow from here: https://github.com/teambit/bit/discussions/4707
This can successfully publish to npm but only if I set the `--otp` value in the "packageManagerPublishArgs". I have to manually update this each time I run `bit tag`. Is it possible to supply this as an argument to `bit tag` instead of needing to include it in the `workspace.jsonc` file? 
Note: I have 2FA enabled in npm.

`workspace.jsonc teambit.workspace/variants`

```
  "teambit.workspace/variants": {
    "{mycomponent}: {
      "teambit.react/react": {},
      "teambit.pkg/pkg": {
        "packageManagerPublishArgs": [
          "--access public",
          "--otp=123456"
        ],
        "packageJson": {
          "name": "@{scope}/{name}",
          "private": false,
          "publishConfig": {
            "scope": "@myscope",
            "registry": "https://registry.npmjs.org/"
          }
        }
      }
    }
  }
```

### Specifications
* Bit version: 0.0.726

**Comment by itaymendel** [comment]
hi, resolved here - https://github.com/teambit/bit/pull/7035
