### ISSUE TITLE
Support for node version 18

### ISSUE THREAD

**Issue by linfordbacon-ngenius** [teambit/bit#5814]
### Description
The latest version of node is now 18.1.0 but bit apparently requires node versions <17.0.0

### Solution
Update dependencies and test with the latest version of node

### Alternatives
Provide/document an override that lets users work with node 18

**Comment by itaymendel** [comment]
Bit comes with its own node instance now. please ensure to update bvm and re-install bit:
```
npm i -g @teambit/bvm
bvm install
```
