### ISSUE TITLE
Trying to understand how bit playground uses bit link to successful load components with third level dependencies, yet fails in nextjs project. [sample project]

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5842]
Hi, I have been having a discussion in the slack channel regarding this and was asked to make a post here. I am trying to figure out how I can use bit link to test components developed in a bit dev project, inside of another nextjs project, without first publishing to bit cloud. 

I appreciate that this may not be a specifically supported feature of bit but this is a contentious issue on our team when it comes to deciding if we are going to move forward with bitdev on our new project or not. Personally I would very much like to move forward using bit and being able to come up with a solution to this will solve a bit of an argument on our team and allow us to move forward so I would very much like to gain an understanding of how bit playground was able to solve this issue so I can maybe figure out how I could apply the same technology to our nextjs project.

Here is a link to a sample project: https://github.com/frntfinancial/BitLinkDemo

# BitLinkDemo
### OPEN TERMINAL
cd nextjs

bit install

cd ../base-ui

bit install

bit link --target ../nextjs

bit watch

### NEW TERMINAL
cd nextjs

npm run dev

OPEN localhost:3000

see error: 'TypeError: Cannot read property 'useContext' of null'. Why is this occurring? There seems to be an issue
when a component reference third layer dependencies, as this appears to work fine in the node js application if I just wish to render a simple component with no third layer dependencies.

Now stop the nodejs application and instead run "bit start". Observe the playground loads correctly, nextjs
components are rendered correctly along with their bit linked children.

When you run "bit start" from the nextjs application, the bit playground is able to start up and load all external 
dependencies successfully. I can browse the nextjs app components and the bit linked components perfectly. 
Even if I make a change to the component in base-ui, hot reloading works perfectly in the bit playground.
How is bit solving this problem and how I can apply it so that it works in the running nextjs application as well so
that I could test components in the nextjs project and also have changes reflected with hot reload?

If bit playground can do this, nextjs app should also be able to do this. Where is the disconnect here? Please help:(

**Comment by itaymendel** [comment]
i'd recommend using `bit import` instead.
generally with `bit link --target` deps of your components are resolved from `target` as well. so if you depend on react, you may see that your component resolves for another instance of react (from the bit-worksapce).
this is an issue with `npm link` as well, and not specifically related to the `bit link` implementatin.

looking at the error, it seems like this is the root cause here.

when using `bit import`, you have the component locally in a project, so this removes the issue.

`bit link --target` is very basic. it simply creates symlinks to the component's `node-modules` in a target location.

**Comment by nmitic** [comment]
How does one use bit import or even bit link --target to "import" local bit component to test changes before exporting them to remote?
