### ISSUE TITLE
Not able to hot reload nextjs app when modifying second level bit component

### ISSUE THREAD

**Issue by brandoncollins7** [teambit/bit#5854]
Please see my demo project here: https://github.com/brandoncollins7/NextJsHotReloadDemo

# HotReloadDemo
### OPEN TERMINAL
bit install

bit compile

bit start

### NEW TERMINAL
npm run dev

Note that if you make a change to Screen1 component internal text, save. both bit playground and the nextjs app will hot reload the text.
Now, make a change to the Component1 component internal text, save. bit playground hot reloads but nextjs app does not.

A clear and concise description of the issue.

### Expected Behavior
Hot reloading should work for components part of a project

**Comment by itaymendel** [comment]
when using bit in a repo with other apps that need to depend on components, use `bit watch` to rebuild node-modules. this should get nextjs HMR engine running.
