### ISSUE TITLE
Adding "read only" flagging to packages

### ISSUE THREAD

**Issue by johnjspiteri** [teambit/bit#5864]
We are using Bit to share code between our online application (read only required) and our products (where development takes place)...

Packages are installed as files instead of packages in node_modules for easier reference and simple "checkout latest --all" (100+ packages being updated regularly).

Is there a current way of flagging a package in "workspace.jsonc" to be read only? and ignored by the tagging/exporting handling.

Thank you  - Bit has been priceless to our project, amazing work :clap:

**Comment by itaymendel** [comment]
sadly this is not a feature we are looking to implement.
