### ISSUE TITLE
Having error Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react-native"

### ISSUE THREAD

**Issue by RiteshJariwala** [teambit/bit#5870]
### Describe the bug
I created a charting component for react-native using the victory-native package.  I also done process of webpack stuff mentioned in the documentation for the react-native. I can compile the component fine. While taging component for exporting i am getting follwoing error:

The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react-native"

### Steps to Reproduce
1. Created component and compiled component
2, Tagging component gives the error:

### Expected Behavior
It suppose to tag component just fine without any error.

### Screenshots, exceptions and logs
The following errors were found while running the build pipeline
Failed task 1: "teambit.preview/preview:GeneratePreview" of env "teambit.react/react-native"
component:myscope.mobile/ui/bar-chart@0.0.1
ModuleNotFoundError: Module not found: Error: Can't resolve 'readline' in 'C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\ora'
ModuleNotFoundError: Module not found: Error: Can't resolve 'readline' in 'C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\ora'
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\Compilation.js:1773:28
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:811:13
    at eval (eval at create (C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:286:22
    at eval (eval at create (C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:442:22
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:124:11
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:673:25
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:882:8
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:1002:5
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\neo-async\async.js:6883:13    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\lib\NormalModuleFactory.js:985:45
    at finishWithoutResolve (C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:312:11)
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:386:15
    at C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:435:5
    at eval (eval at create (C:\Users\Administrator\AppData\Local\.bvm\versions\0.0.744\bit-0.0.744\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:15:1)

Found 1 errors in 1 components

✖ Total 7 tasks. 6 succeeded. 1 failed. 0 skipped. Total errors: 1.

### Specifications
* Bit version: 0.0.744
* Workspace type: (harmony/legacy)
* Node version: v16.14.2
* npm version: 8.5.0
* Platform: Windows

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
react-native was completely refactored. please consul the docs to use the up-to-date plugin.
