### ISSUE TITLE
Bit install cmd fail

### ISSUE THREAD

**Issue by MikulasLebowski** [teambit/bit#5871]
'bit install' fails, with error:
`'Failed to install: MissingBitMapComponent'`

That's it, no more info.

I tried a lot of stuff to fix this, including hard reset of the workplace, nothing so far helped. Other than this, bit seems to work ok.
Any idea how can I fix this? Or at the very least, how to debug this? Is there some detailed error log somewhere?

**Comment by itaymendel** [comment]
run `bit init`. very likely you don't have a `.bitmap` file in the project.
