### ISSUE TITLE
Eslint not working in VSCode

### ISSUE THREAD

**Issue by sbland** [teambit/bit#5894]
### Describe the bug
Following basic Bit setup instructions Vscode not running eslint.

Related issues:
https://github.com/teambit/bit/issues/4712
https://github.com/teambit/bit/issues/5507

### Steps to Reproduce
Following the instructions here: https://bit.dev/docs/getting-started/installing-bit/start-bit-workspace

Run `bit new react my-workspace --default-scope bitorg.experience`
Create a new component `bit create react ui/button`.
Copy the following to the component (containing a clear linting error): 

```js
const foo = () => {
    const a = "hello" // missing semi-colon
    return a;
}
```

Run `bit lint`
This will return ...

    dmeo.demo/ui/button
    
    my-workspace/demo/ui/button/button.composition.tsx
      4:34  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
      8:2   error  Missing semicolon                                                                                      @typescript-eslint/semi
    
    my-workspace/demo/ui/button/button.tsx
      14:7   error  'foo' is assigned a value but never used  @typescript-eslint/no-unused-vars
      15:13  error  Strings must use singlequote              @typescript-eslint/quotes
      16:11  error  Missing semicolon                         @typescript-eslint/semi
      17:10  error  Strings must use singlequote              @typescript-eslint/quotes
      17:14  error  Missing semicolon                         @typescript-eslint/semi
    
    ✖ 7 problems (7 errors, 0 warnings)
      6 errors and 0 warnings potentially fixable with the `--fix` option.I tried running `bit install eslint` the `restart ESlint server` from vscode. This resulted in the following error in the eslint output console:```
[Info  - 17:50:49] ESLint library loaded from: /PATH_TO_PROJECT/my-workspace/node_modules/.pnpm/registry.npmjs.org+eslint@8.16.0/node_modules/eslint/lib/api.js
Uncaught exception received.
TypeError: Failed to load plugin 'jest' declared in '.eslintrc.js » @teambit/eslint-config-bit-react': Class extends value undefined is not a constructor or null
Referenced from: /PATH_TO_PROJECT/my-workspace/node_modules/.pnpm/registry.npmjs.org+@teambit+eslint-config-bit-react@0.0.367_5516725c7493270bc11bbf0f5ebfc719/node_modules/@teambit/eslint-config-bit-react/dist/index.js
    at Object.<anonymous> (/PATH_TO_PROJECT/my-workspace/node_modules/.pnpm/registry.npmjs.org+@typescript-eslint+experimental-utils@4.33.0_eslint@8.16.0/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1216:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1059:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/PATH_TO_PROJECT/my-workspace/node_modules/.pnpm/registry.npmjs.org+@typescript-eslint+experimental-utils@4.33.0_eslint@8.16.0/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
    at Module._compile (node:internal/modules/cjs/loader:1163:14)
Uncaught exception received.
```

.eslintrc (in root dir)

```js
module.exports = {
  extends: ['@teambit/eslint-config-bit-react',
],
  parserOptions: {
    project: './tsconfig.json'
  },
}
```

### Expected Behavior
Should show linting errors inline or in problems panel.

### Screenshots, exceptions and logs
Output of Eslint In VScode: 

```
[Info  - 17:43:31] ESLint server is starting
[Info  - 17:43:31] ESLint server running in node v16.13.0
[Info  - 17:43:31] ESLint server is running.
```

### Specifications
* Bit version:0.0.744
* Workspace type: harmony
* Node version: v10.19.0
* npm / yarn version: v8.1.0
* Platform: Ubuntu
* Vscode: 1.67.2

### Additional Info
I haven't installed eslint globally assuming this is already with bit. I couldn't find the callable eslint file to run manually in the command line.

**Comment by markvp** [comment]
+1

**Comment by itaymendel** [comment]
`bit lint` re-implemetned.
