### ISSUE TITLE
Wrong env tag for angular-v12

### ISSUE THREAD

**Issue by stefanoschrs** [teambit/bit#5900]
### Describe the bug
Wrong env tag for angular-v12

### Steps to Reproduce
Following the [Getting Started](https://bit.dev/docs/frameworks/angular/angular-overview#getting-started)

```
bit new ng-workspace bitangular12 -a teambit.angular/angular-v12
cd bitangular12
bit create ng-module ui/my-button
bit install
bit build
```

### Expected Behavior
To work

### Screenshots, exceptions and logs
```
$ bit build
✔ found 1 components to build
✔ running pre install subscribers
✔ deduping dependencies for installation
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @teambit/angular-v12@npm:0.0.69: No candidates found
    at startDescriptorResolution (/home/xxx/.bvm/versions/0.0.750/bit-0.0.750/node_modules/@yarnpkg/core/lib/Project.js:563:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
➤ YN0000: └ Completed in 1s 322ms
➤ YN0000: Failed with errors in 1s 327ms
```

### Specifications
* Bit version: 0.0.750
* Workspace type: harmony
* Node version: v14.18.3
* yarn version: 1.22.17

### Additional context
When you check on [npm](https://npm.io/package/@teambit/angular-v12) the 0.0.69 tag does not exist.

### Fix
Change the `0.0.69` to an existing tag e.g `0.0.68` in `workspace.jsonc`

**Comment by itaymendel** [comment]
Hi, sadly the getting-started needs some update. please follow these instructions https://bit.cloud/teambit/angular/angular
