### ISSUE TITLE
Allow enforcing minimum supported Bit CLI version

### ISSUE THREAD

**Issue by sachinahya** [teambit/bit#5928]
### Description
As new fixes and features are introduced in the Bit CLI, we'd like to make sure all users are working with a recent version that aligns with the version used in our CI/CD. We've found recently that some of our users forget to update regularly and recently would be on versions as old as 0.0.656. This means they don't get the best experience when working locally, and sometimes stuff they're doing locally won't work in CI.

### Describe the solution you'd like
A config parameter in the workspace allowing us to specify a version (e.g. 0.0.742) that we want to enforce. If any Bit commands are executed in the workspace on a version less than this, an error should be thrown prompting the user to upgrade via `bvm`. A similar feature exists with Node via `engines`/`engineStrict` options.

**Comment by GiladShoham** [comment]
Thanks, a few users already asked for this feature. we are going to implement it soon.
@davidfirst FI

**Comment by davidfirst** [comment]
Implemented. See the PR above for more details how to set it up.
Will be released probably tonight.
