### ISSUE TITLE
npm i @teambit/bit does not work

### ISSUE THREAD

**Issue by vbargl** [teambit/bit#5948]
### Describe the bug
I'm trying to install bit via `npm i @teambit/bit` and it fails with error message

```
Invalid tag name ">=^16.0.0" of package "react@>=^16.0.0": Tags may not have any characters that encodeURIComponent encodes.
```

### Steps to Reproduce
1. Obtain node and npm
1. Run `npm i @teambit/bit`

### Expected Behavior
Package is successfully installed.

### Screenshots, exceptions and logs
[2022-06-11T07_43_23_320Z-debug-0.log](https://github.com/teambit/bit/files/8883478/2022-06-11T07_43_23_320Z-debug-0.log)

### Specifications
* Node version: 18.2.0
* npm version: 8.11.0
* Platform: Linux

**Comment by GiladShoham** [comment]
Pleaae install bit using bvm instead of npm.
Also bit doesn't support node >=17 at the moment.

**Comment by amirhosseinfarahmand** [comment]
> 
hi
whats about 16.15?
Cannot read properties of undefined (reading 'filter')
TypeError: Cannot read properties of undefined (reading 'filter')
have a this error and idk why

**Comment by itaymendel** [comment]
we're moving away from depending on the local version of node.

also, please use `teambit/bvm` to install bit, as stated in the docs. not `teambit/bit`.
