### ISSUE TITLE
how to fix ServerIsBusy error

### ISSUE THREAD

**Issue by Youjingyu** [teambit/bit#5949]
### Specifications
* Bit version: 0.0.716
* Node version: v12.22.9
* npm / yarn version: 6.14.15
* Platform: linux
* Bit compiler (include version):
* Bit tester (include version):

### Context and additional information
we use self hosted server to persist bit components

an error was reported while run `bit export componenet-id` locally:
`server responded with: "url: https://xxx/api/scope/action. status: 504. text: Gateway Time-out"`

self hosted server logs report:

```bash
express.errorHandle, url /api/scope/action, error:
    ServerIsBusy: fatal: the server is busy exporting from other clients. total clients (including yours) in the queue: 4,
    the current export-id in queue is "1654923563334".
    if the last export was failed during the persist stage and left the remotes locked, you have the following options:
    1. if the failure occurred on your local, just re-run the export command with "--resume <id>".
    2. run "bit persist <id> <remotes...>", you will need to list all the remote scopes you want the persist to take place.
```

when i  run `bit persist <id> <remotes...>`, it logs:
`'persist' is not a valid command`

when i rerun bit export with "--resume <id>", it's not working too

how can i find out which  clients is in the queue,  and  how can i fix this?

**Comment by johnjspiteri** [comment]
Have the same issue:

```
unexpected network error has occurred.
server responded with: "scope "interface-agency.internal". error: fatal: the server is busy exporting from other clients. total clients (including yours) in the queue: 2,
the current export-id in queue is "1655018735142".
if the last export was failed during the persist stage and left the remotes locked, you have the following options:
1. if the failure occurred on your local, just re-run the export command with "--resume <id>".
2. run "bit persist <id> <remotes...>", you will need to list all the remote scopes you want the persist to take place.
"
```

Option 1: Did not throw any errors
Option 2: The command has been depreciated

**Comment by johnjspiteri** [comment]
@Youjingyu, thought I would share a quick fix - clear the scope from the CLI, and re-export the packages...

**Comment by suwu150** [comment]
I also encountered the same problem, unable to export the code,
The email has been sent for some time, but there is no effective response. Please pay attention

@itaymendel
