### ISSUE TITLE
getting merge conflict on second export

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#596]
STR
create new scope
export a component
tag a new version of the component
try to export again
you will get an error:
`fatal: received an invalid response from the remote SSH server`
The real error is merge conflict (saw in the server logs).
About the fact that we got the wrong error there is another issue #497
So this issue is about why we getting a conflict at all

**Comment by davidfirst** [comment]
For future reference, the bug was related to https://github.com/teambit/bit/issues/593 and https://github.com/teambit/bit/issues/595, which were fixed by https://github.com/teambit/bit/pull/597.
