### ISSUE TITLE
bit should follow package.json overrides

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#5964]
When installing with pnpm, overrides are respected, and for example in this case, `pnpm install` will result in react v17.0.2:

```json
  "dependencies": {
    "react": "^16.0.0"
  },
  "pnpm": {
    "overrides": {
      "react": "^17.0.0"
    }
  },
```

however, when installing with `bit install`, we get v16.14.0.
This is because bit respects existing `package.json` files (which is great, makes use compatible with industry standards), but doesn't check pnpm specific properties.

In fact, why not support the standard top level [overrides spec](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)?

```json
  "dependencies": {
    "react": "^16.0.0"
  },
  "overrides": {
    "react": "^17.0.0"
  }
```

### Steps to Reproduce
1. download reproduction: [overrides-scenario.zip](https://github.com/teambit/bit/files/8898454/overrides-scenario.zip)
1. `cd install-with-pnpm && pnpm i` (installs react 17.0.2)
1. `cd ../install-with-bit/ && bit install` (installs react 16.14.0)

### Expected Behavior
should behave the same as pnpm (and the same as npm)

### Specifications
* Bit version: 0.0.762

**Comment by zkochan** [comment]
Is this `package.json` in the root of the workspace?

**Comment by KutnerUri** [comment]
yes. at the same level as the `workspace.jsonc`. All of the dependencies are written exclusively in the `package.json`

**Comment by GiladShoham** [comment]
it's kind of a missing feature, but not a very high priority.
most people who are using bit install, using workspace.jsonc.
if they use package.json they usually install using package manager directly, then only do bit link

**Comment by itaymendel** [comment]
if using package.json to manage dependencies you should not be using bit-install.
the different overrides may collide and create very dramatic side effects.

i think it's safer to close this issue rather than add this functionality...

**Comment by KutnerUri** [comment]
it is true that we should not encourage users to install with other clients (as bit adds additional links on top of regular installation), but I think we should compatibility whenever possible
