### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by matteoquintero-aflore** [teambit/bit#5986]
### Describe the bug
Happens when creating a workspace with lit

### Steps to Reproduce
1.bit new lit my-lit-workspace --aspect teambit.web-components/lit
2.bit create lit my-component
3.bit start

### Expected Behavior
The idea is that the test that is by default comes out when creating the component

### Screenshots, exceptions and logs
![test](https://user-images.githubusercontent.com/87438107/174317037-5aebe1bf-61e1-49f7-96d7-c4013ca3a7d5.png)

### Specifications
Last versions

**Comment by LeoInNash** [comment]
Having same issue

**Comment by GiladShoham** [comment]
@benjgil can you try tagging the lit env with the latest version of bit and see if it's still an issue?

**Comment by benjgil** [comment]
@matteoquintero-aflore @LeoInNash 
This should now be resolved with the latest version of the Lit environment.
Please update to the latest version and try again
