### ISSUE TITLE
How to run a post install script after run bit install

### ISSUE THREAD

**Issue by blacktail** [teambit/bit#5996]
### Specifications
* Bit version: 0.0.763
* Node version: v14.17.4
* npm / yarn version: 6.14.14
* Platform: Mac
* Bit compiler (include version):
* Bit tester (include version):

### Context and additional information
I want to run a post install script after bit install, how should i do to achieve this? is it possible? Thanks!

**Comment by NitsanCohen770** [comment]
You can create an aspect that registers itself to the postInstall slot
  registerPostInstall(fn: PostInstall) {
    this.postInstallSlot.register(fn);
  }
