### ISSUE TITLE
How get different versions of package in existing project with package.json

### ISSUE THREAD

**Issue by KelvinOm** [teambit/bit#6055]
### Description
I have existing project with `package.json` and React 15. I want to use Bit workspace with React 18. I tried to use variant for this but after `bit install` i got only 18.2.0 version in root node_modules. 

![2022-07-01!UNITO-UNDERSCORE!08-53-14](https://user-images.githubusercontent.com/11555074/176822446-27fcae75-9a8e-4c06-b4ea-f4767295b458.png)

Could you help me to get `node_modules` with react 18 in components folder?

* Bit version: 0.0.777
* Node version: 16.15.1
* Platform: MacOs

### Context and additional information
Repo for reproduce
https://github.com/KelvinOm/bit

**Comment by GiladShoham** [comment]
Do you want to use both react 15 and 18 in the same workspace?

**Comment by KelvinOm** [comment]
@GiladShoham Yes. I want migrate my old codebase step by step to new React with components and old app have to work on React 15 without any changes. How can I achieve this?
