### ISSUE TITLE
In default React env test doesn't work

### ISSUE THREAD

**Issue by KelvinOm** [teambit/bit#6061]
### Describe the bug
When using the default React environment for component, I can't run tests because there is no @testing-library/react.

### Steps to Reproduce
1.  bit create react some-cmp
1.  bit install && bit compile
1. bit test 

### Expected Behavior
Tests run successfully.

### Screenshots, exceptions and logs
![2022-07-04!UNITO-UNDERSCORE!10-32-08](https://user-images.githubusercontent.com/11555074/177089194-d9fb82ea-9b99-4b29-95ed-cf3b9dd0127a.png)
![2022-07-04!UNITO-UNDERSCORE!10-31-54](https://user-images.githubusercontent.com/11555074/177089196-f8d44f8c-21aa-448c-9236-cc3b9a0a7230.png)

### Specifications
* Bit version: 0.0.780
* Node version: v16.15.1
* Platform: MacOs

_for harmony workspace_

* relevant env `teambit.react/react`

**Comment by GiladShoham** [comment]
please run `bit install @testing-library/react@^12   --type peer`
We are working to solve it
