### ISSUE TITLE
Unable to import self hosted fonts

### ISSUE THREAD

**Issue by sourabhchotiads** [teambit/bit#6066]
### Describe the bug
I am trying to import self hosted font family in the theme provider component, which works fine on the development mode but when i try to make a build or tag the component it throws an error (please see screen shhot)

![image](https://user-images.githubusercontent.com/86597939/177130197-230c5f97-e371-429c-b63d-02e36ea34842.png)

I have created a custom env to pass the additional type definition but this is not working either

Please check this repository to reproduce the issue
https://github.com/sourabhchotiads/bit-cloud-fonts

### Expected Behavior
It should let me build my component with self hosted font family import

* Bit version: 0.0.763
* Workspace type: (harmony/legacy): legacy
* Node version: 16.15.1
* npm / yarn version: npm-8.13.2
* Platform: linux

**Comment by itaymendel** [comment]
react environment has been refcatored and now contain references for types for fonts by default.
closing the issue
