### ISSUE TITLE
Cann't find documentation for integrating bit.dev with CI/CD 

### ISSUE THREAD

**Issue by rollymaduk** [teambit/bit#6076]
Previously I could find your wiki documentation on using bit with CI like git actions, gitlabs e.t.c, but that seems to have disappeared. Wondering why, or is there something I could be missing

**Comment by giteden** [comment]
@rollymaduk  thanks for letting us know. it was removed by mistake. now back again.
https://bit.dev/docs/getting-started/collaborate/setup-ci
