### ISSUE TITLE
Pipe operator doesn't work

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#6077]
### Describe the bug
I have some components that uses pipe operator which is not yet fully supported but there is a babel plugin that I used in my projects to make this work. I tried to add the plugin in my custom env but doesn't seems to do the work.

When I run `bit compile` I get this error:
![image](https://user-images.githubusercontent.com/41594981/177507334-d0f40b1a-e566-4d7b-a45a-42dbcc3c6b31.png)

And running `big test` result in this error:
![image](https://user-images.githubusercontent.com/41594981/177507806-9fa229e2-a861-4032-b2ce-f2531e78c425.png)

Where should I add this plugin in order to make it work for both cases? I don't know exactly where babel config resides.

### Steps to Reproduce
1. Clone this project  https://github.com/osstotalsoft/rocket-ui and run any of the above commands

### Specifications
* Bit version: 0.0.780
* Workspace type: harmony
* Node version: 16.14.2
* npm / yarn version: 8.5.0
* Platform: windows 10

_for harmony workspace_

* relevant env: custom env https://bit.cloud/totalsoft_oss/rocket-ui/envs/my-env

**Comment by itaymendel** [comment]
please refer to the docs for this topic - https://bit.dev/reference/jest/jest-config
