### ISSUE TITLE
should set component as env, when it is not an env

### ISSUE THREAD

**Issue by KutnerUri** [teambit/bit#6089]
Today we can set any component as another component's env.

for example:

```
cd /tmp
bit new react exp05
cd exp05
bit create react-env envs/some-env --env teambit.harmony/aspect
bit create react some-comp --env envs/some-env

--> created some-comp with env: envs/some-env
```

As a side effect, non-env components don't generate an env template as part of their build process, resulting in this error for their  components:
![Screen Shot 2022-07-07 at 16 43 19](https://user-images.githubusercontent.com/5400361/177788746-69a8548b-3fdc-428b-bc57-6fb3ee8dbaff.png)

For this, we should only allow components with env `teambit.envs/env` as environments.
We should show a warning for all others, and in the future make it an error.

Env warning:

```
component "envs/wrong-env" is used as an env, though its own env should be "teambit.envs/env"
```

Consumer warning:

```
component "some-comp" has "envs/wrong-env" as environment, but "envs/wrong-env" own env is not of "teambit.envs/env"
```

Should appear at:

* bit envs set (when setting envs/wrong-env)
* bit status
* bit tag (for both components)

reproduction:
[check-aspect-env.zip](https://github.com/teambit/bit/files/9064314/check-aspect-env.zip)

**Comment by davidfirst** [comment]
Implemented a bit differently. See the PR above for more info. Closing it fr now.
