### ISSUE TITLE
Typescript support for JSX in .mdx files

### ISSUE THREAD

**Issue by jonahfuller** [teambit/bit#6092]
### Description
It would be great if the typescript config could support using JSX in the .docs.mdx files for a component. Adding this code currently breaks the default `bit lint` command. A good use case for this is using the `<FigmaEmbed />` component from the `@teambit/design.embeds.figma` package, which allows developers to easily see the design file reference when viewing a component.

### Describe the solution you'd like
It is difficult or unclear how to modify the `tsconfig.json` file to add support for this in a project, so if this can be added to the default teambit react tsconfig file that would be ideal.

### Describe alternatives you've considered
I've tried the following:

1. adding an `mdx.d.ts` definition to the `/types` folder with:

```
declare module '*.mdx' {
  let MDXComponent: (props) => JSX.Element;
  export default MDXComponent;
}
```

1. adding the `@types/mdx package` to the project, and adding `"types": ["mdx"]` to the `"compilerOptions"` section in the root `tsconfig.json` file:

```
...
  "compilerOptions": {
    ...,
    "types": ["mdx"]
  },
...
```

1. adding `"**/*.mdx"` to the `"exclude"` array in the root `tsconfig.json` file (just to see if I could exclude this file type entirely):

```
...
  "exclude": [
    ...
    "**/*.mdx"
  ]
```

### Additional context
A quick example can be replicated by spinning up a brand new bit project, creating a new component, adding the Figma Embed package, and editing the component .docs.mdx file to include the embed:

1. create new project `bit new react figma-example`
1. switch into directory `cd figma-example`
1. install figma dependency `bit install @teambit/design.embeds.figma`
1. create a component `bit create react figma/example`
1. edit and save `.../figma/example/example.docs.mdx`:

```
import { FigmaEmbed } from '@teambit/design.embeds.figma';

## Figma Embed
<FigmaEmbed src="" />
```

1.  run `bit lint`, you will see the output:

```
.../figma/example/example.docs.mdx
4:13  error  Parsing error: '>' expected
```

**Comment by itaymendel** [comment]
in the updated implementation of the env you now have direct control over the tsconfig for your environment, so this can be solved for your specific case.
