### ISSUE TITLE
Preview and composition doesn't work on cloud

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#6093]
### Describe the bug
Preview and composition doesn't work on cloud although on local everything works fine. Is just one component where the compositions and preview doesn't work anymore but I didn't change the code in days and everything worked fine until yesterday.

### Steps to Reproduce
1. Go to https://bit.cloud/totalsoft_oss/rocket-ui/themes?version=0.0.10
1.  The source code is at https://github.com/osstotalsoft/rocket-ui

### Screenshots, exceptions and logs
This is what I get in the console 
![image](https://user-images.githubusercontent.com/41594981/177964291-b45ccf6a-b9ba-4ef9-a2c1-e543fdf18d39.png)

### Specifications
* Bit version: 0.0.785
* Workspace type: harmony
* Node version: 16.14.2
* npm version: 8.5.0
* Platform: windows 10

_for harmony workspace_

* relevant env: custom env https://bit.cloud/totalsoft_oss/rocket-ui/envs/my-env

**Comment by KutnerUri** [comment]
Your scope is out of date. (it can happen from time to time because we don't immediately update scopes)
We've updated it and now it's working :)

**Comment by DCosti** [comment]
Thanks!
