### ISSUE TITLE
cant find a dependency of a dependency. bit should know to fallback when version is not found in npm.

### ISSUE THREAD

**Issue by odedre** [teambit/bit#6102]
### Describe the bug
I'm trying to import a component but getting the following error:

```
failed installing the packages, consider running the command with "--skip-dependency-installation" flag.
error from the package-manager: No matching version found for @teambit/design.typography.text@0.0.7.
please use the '--log=error' flag for the full error.
```

the issue is that the publish of `@teambit/design.typography.text` to npm started at version `0.0.9` as can be seen here https://www.npmjs.com/package/@teambit/design.typography.text.

### Steps to Reproduce
1. `bit import teambit.community/apps/bit-dev`

### Expected Behavior
bit should know how to fallback to the bit registry that I have configured in my .npmrc

### Specifications
* Bit version: 0.0.787
* Workspace type: (harmony)
* Node version: v16.15.1
* Platform: macos

**Comment by itaymendel** [comment]
i think this is an npm issue, so this is "upstream" for us.
