### ISSUE TITLE
Self hosting bit with permissions

### ISSUE THREAD

**Issue by jonparkdev** [teambit/bit#6104]
> the core OSS feature set does not have permissions built in. you can run this server behind an nginx or something to validate permissions.
> 
> _Originally posted by itaymendel in https://github.com/teambit/bit/discussions/4707#discussioncomment-1486852_

When self-hosting bit, could the maintainers elaborate more about setting up permissions so that users can't just visit the url of the scope or `bit export` on a local machine? As much as bit.cloud is convenient, I would need to run this on-prem at my company.

**Comment by itaymendel** [comment]
hi, i added a reply on the thread.
permission management is not a part of the OSS tool. what you can do is set up nginx or another server to be "in front" of the scope and have it tunnel requests and validate access control.
