### ISSUE TITLE
add bundle analysis artefact in Bit UI (source-map-explorer or other)

### ISSUE THREAD

**Issue by antoine-durand** [teambit/bit#6118]
### Description
would love to be able to check what's in any component build from the Bit UI.

### Describe the solution you'd like
Add a tab in Component View of Bit UI to display a result of bundle analyser as source-map-explorer.

**Comment by itaymendel** [comment]
you can add your own bundle analysis for components. if bit woudl run it by default this would cost a lot of time on ci. so by default bit will not do it.
