### ISSUE TITLE
Declaration emit for this file requires using private name

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#6136]
### Describe the bug
When trying to tag a component I get the following error:
![image](https://user-images.githubusercontent.com/41594981/178924285-7c1685d6-e93b-4240-b135-fa3784a47a4d.png)
It worked fine until this component and I don't know if it's something wrong with my component or is it a bit related issue.

### Specifications
* Bit version: 0.0.791
* Workspace type: harmony
* Node version: 16.14.2
* npm  version:  8.5.0
* Platform: windows 10

_for harmony workspace_

* relevant env: custom env https://bit.cloud/totalsoft_oss/rocket-ui/envs/my-env

**Comment by NitsanCohen770** [comment]
solved with the new envs api
