### ISSUE TITLE
Command fail creates folder

### ISSUE THREAD

**Issue by jonatankBIT** [teambit/bit#6150]
### Creates folder on failed command
Running a command of creating a react hook with a typo, shows the proper error message 

### Steps to Reproduce
1. Run a command with a typo like : 
`bit create react-hoooook -n hooks useOpen`
1. You will get an error like:
error: "hooks/useOpen" is invalid, component names can only contain alphanumeric, lowercase characters, and the following ["-", "_", "$", "!", "/"]
1. Check your folders. You will see that the hooks folder (passed on the namespace flag) was effectively created.

### Expected Behavior
I would expect the `hooks` folder not to be created if the command failed.

### Specifications
* Bit version: 0.0.791
* Workspace type: (harmony/legacy): Harmony
* Node version: 16.14.0
* npm / yarn version: pnpm
* Platform: MacOs

**Comment by davidfirst** [comment]
This has been fixed a while ago. I doubled check, ran the above command and verified that no component was created.
