### ISSUE TITLE
Components that start with vowels should have the proper article on the templates

### ISSUE THREAD

**Issue by jonatankBIT** [teambit/bit#6151]
### Steps to Reproduce
1. Create a react component starting with a vowel, for example Accordion.
1. Open the .mdx file. Give a look to the description, it will have written `description: A Accordion component`

### Expected Behavior
description: An Accordion component`

### Specifications
* Bit version: 0.791
* Workspace type: Harmony
* Node version: 16.14
* npm / yarn version:
* Platform: MacOs
* Template: React

**Comment by itaymendel** [comment]
we removed the default mdx template from base templats. this is no longer relevant.
