### ISSUE TITLE
Improper white space handling on .mdx header crashes the build

### ISSUE THREAD

**Issue by jonatankBIT** [teambit/bit#6152]
On .mdx files, forgetting a space between `labels:` and the array, crashes the build.
For example: `labels: ['demo', 'accordion']` will work, but `labels:['demo', 'accordion']` will crash it due to the lack of whitespace.

### Steps to Reproduce
1. Create a react component
1. Assign the following label:

```
---
description: An Accordion component.
labels:['demo', 'accordion']
---
```

1. Compile. 

### Expected Behavior
To recognize the start of the array immediately at the `[` character without caring about white spaces.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/97826324/179402165-20d6feb2-7d80-43d2-b5a3-338ea108b7e2.png)

![image](https://user-images.githubusercontent.com/97826324/179402189-e71a574c-5ac3-4f44-bf91-b953598be7d2.png)

### Specifications
* Bit version: 0.791
* Workspace type: Harmony
* Node version: 16.14
* npm / yarn version: pnpm
* Platform: MacOs

**Comment by GiladShoham** [comment]
Interesting, we will check it

**Comment by davidfirst** [comment]
It's kind of expected behavior. `bit status` shows the same error, see screenshot attached.

As the error says, this is coming from Yaml lib when it tries to parse the front-matter. 
@GiladShoham , what will be the expected behavior? 

<img width="1084" alt="Screen Shot 2022-07-20 at 3 46 03 PM" src="https://user-images.githubusercontent.com/1963573/180068600-22166b54-b66e-4f71-b8b3-65a16177ebbb.png">

**Comment by GiladShoham** [comment]
We can remove the line and column for now (or if we really want to re-calc them) but having the line printed is much better dx. Otherwise I would never know what it where I should change something

**Comment by davidfirst** [comment]
I ended up mentioning in the message to disregard the line/column.

<img width="1474" alt="Screen Shot 2022-07-20 at 5 20 52 PM" src="https://user-images.githubusercontent.com/1963573/180084281-6ecc14c0-43ae-437a-ac12-fd05a9322eb4.png">
