### ISSUE TITLE
Cannot checkout if main file is changed

### ISSUE THREAD

**Issue by ivansky** [teambit/bit#6155]
### Describe the bug & Steps to Reproduce
The component was changed in different branches and its time to merge it.
The component main file was removed and replaced by `index.ts`

```
$ bit checkout --skip-dependency-installation latest --manual "--all"

failed adding or updating a .bitmap record of org.libs/something@0.0.38. mainFile serverSidePipe.ts is not in the files list.
if you renamed the mainFile, please re-add the component with the "--main" flag pointing to the correct main-file
This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues
```

tried to re-add component with a different main file

```
$ bit add lib/something --main index.ts

unable to add individual files outside the root dir (lib/something) of org.libs/something@0.0.36.
you can add the directory these files are located at and it'll change the root dir of the component accordingly
```

why index.ts is outside?

lets try to do that relative to project dir and explicitly set id

```
$ bit add lib/something --id=something --main=lib/something/index.ts

tracking component org.libs/something@0.0.36:
added index.ts
added serverUnit.ts
```

it does look good, let try to checkout again, remember you cannot add version to it before checkout

```
$ bit checkout --skip-dependency-installation latest --manual "--all"

failed adding or updating a .bitmap record of org.libs/something@0.0.38. mainFile serverSidePipe.ts is not in the files list.
if you renamed the mainFile, please re-add the component with the "--main" flag pointing to the correct main-file
This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues
```

All over again :( 

### Expected Behavior
Successfully merged

### Specifications
* Bit version: 0.0.781
* Workspace type: (harmony/legacy) harmony
* Node version: 16.15.1
* npm / yarn version: yarn 1
* Platform: mac m1

**Comment by itaymendel** [comment]
you need to `bit checkout latest`, and then all other params...
please consul the `bit checkout --help` to get the correct syntax.
