### ISSUE TITLE
Path reference issue

### ISSUE THREAD

**Issue by PiTiLeZarD** [teambit/bit#6156]
### Describe the bug
I created a workspace in a local folder F (imagine F is /Users/me/Workspaces/F), the defaultScope is "O.S". On bit.cloud I mirror that with O being my org and S the scope. Everything works well on bit start, I'm ready to tag/export component P/X (which is located in F/S/P/X again imagine /Users/me/Workspaces/F/S/ui/my-component)

```
bit tag --ver 1.0.0 -m "First" P/X
bit export
```

everything works great, I can see it properly on bit.cloud, naming is correct, I'm happy as larry.

now, nothing works on my local machine anymore as there is a weird reference to F ¯\_(ツ)_/¯ 

```
bit start
```

And I get:

```
failed loading component F/S/P/X, see full error in debug.log file
```

No "debug.log" file anywhere.

### Steps to Reproduce
Not sure if it's reproducible, but I expressed exactly what I've done up there, and that's the situation I'm in

### Expected Behavior
I'm not quite sure but I surely didn't expect the main folder name to appear anywhere. It could literally be anything, and probably will be depending on who git pull this.

### Specifications
* Bit version: 0.0.789
* Workspace type: (harmony/legacy) probably harmony?
* Node version: 16.15.0
* npm / yarn version: (it's using the pnpm bundled with it I assume, I didn't install pnpm myself)
* Platform: osx 12.3.1 M1

_for harmony workspace_
I've created a custom env (and I imagine an aspect but I can't find an answer to what these things actually are so I'm rolling with it) to handle a ThemeProvider from mui. All my components in ui/* use that env and it has a Wrapper and all. I'm not even sure why I'm mentioning this since none of anything I've done mentions the original root folder name which is now linked in all exported components for some reason.

### Additional context
Look, I'm new to this thing and it's probably a misunderstanding on what org/scope/path/aspect/env/anything is. But that doc of yours sure assumes I know everything already aye! 

I've done a

```
git clone git@bitbucket.org:bitbucketorg/nameofproject.git somethingorother
cd somethingorother
bit install
```

And I get  `failed loading component somethingorother/S/P/X, see full error in debug.log file` I must be missing something easy here! Am I?

Anyway, any feedback will be gratefully received, sorry in advance if I've wasted your time!
```

**Comment by GiladShoham** [comment]
try running `bit compile` before your bit start and see if it solves your issue

**Comment by PiTiLeZarD** [comment]
Finally I figured that one out. And I'd appreciate any pointers towards why wasn't that clear (or why I can't find it clearly in the doc)

in my workspace.jsonc
```
    "teambit.workspace/variants": {
        "{ui/**}": {
            "myorg.myscope/envs/mui": {}
        },
        "myscope/envs/mui": {
            "teambit.dependencies/dependency-resolver": {
                "policy": {
                    "dependencies": {
                       // env deps here
                    }
                }
            }
        },

```

In the ui section I wrote the same as I wrote for the variant "myscope/envs/mui" and that was tripping it off. I just added "myorg." before that and it works. 

Ok I casually wasted a day to figure out that variants are folder matching and under that it's package matching. I hope it can be useful to other people ;)

Again sorry for wasting anyone else's time on this.
