### ISSUE TITLE
Compositions and previews aren't working on cloud

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#6157]
### Describe the bug
Compositions and previews aren't rendered on bit.cloud although on local everything works fine and also I tagged my custom env and export it.

### Steps to Reproduce
1. Go to https://bit.cloud/totalsoft_oss/rocket-ui

### Expected Behavior
All compositions and previews to work on cloud.

### Screenshots, exceptions and logs
This is what I get in the console 
![image](https://user-images.githubusercontent.com/41594981/179502910-82e53369-2650-4bac-892f-efc3d48dbe91.png)

### Specifications
* Bit version: 0.0.792
* Workspace type: harmony
* Node version: 14.14.2
* npm version: 8.5.0
* Platform: windows 10

_for harmony workspace_

* relevant env: https://bit.cloud/totalsoft_oss/rocket-ui/envs/my-env

**Comment by DCosti** [comment]
I don't know if you guys did something or is just that I exported my env several times but now the previews and compositions are working on cloud. 
Thanks!

**Comment by benjgil** [comment]
:) great to hear.
Could be anything from a rogue dependency (if you didnt refresh your node_modules after updating bit versions) to your remote scope not having been updated yet (it sometimes takes some time for our bit version updates to make it to all the remote scopes).
