### ISSUE TITLE
Bit Dev Forbidden Error

### ISSUE THREAD

**Issue by Laurentiu17** [teambit/bit#6164]
Hello! When I'm trying to export a component to remote, I'm recieving 

{ 
unexpected network error has occurred.
server responded with: "Forbidden: repo.components"
}

This is an organisation scope and I'm a member, I pushed one week ago tho, 2 components, what could be the problem?

**Comment by GiladShoham** [comment]
try `bit logout` and `bit login` again

**Comment by jeffreycwitt** [comment]
I'm having the same issue, except my response says: 

{
unexpected network error has occurred.
server responded with: "Forbidden: username.defaultScope"
}

 Logging in and out doesn't seem to make a difference.

**Comment by RobAtRAC** [comment]
I have a team member with this issue too. We've tried log out/in, creating a new account, clearing everything out and starting again, still no luck

**Comment by lamvananh** [comment]
Same issue with me, i am Admin but can not export my component.
 In the past, i have been successfully exported a component. 
Then i change my bit cloud scope from private to public.
After that, i can't export any component . I tried logout and re login but it's still not working
a piece of my log:
Http.pushToCentralHub, started. url: https://symphony.bit.cloud/exporter/api/put. total objects 35
⠦ teambit.workspace/workspace, loading components (completed in 3ms)Http.pushToCentralHub, completed. url: https://symphony.bit.cloud/exporter/api/put, status 200 statusText OK
http, msg from central-hub: start processing the exported data
⠧ start processing the exported datahttp, msg from central-hub: Forbidden: my-org.tasks-scope
got an error from command export: UnexpectedNetworkError: Forbidden: my-org.tasks-scope
UnexpectedNetworkError: Forbidden: my-org.tasks-scope
    at Http.pushToCentralHub (C:\Users\anhlv6\AppData\Local\.bvm\versions\0.0.888\bit-0.0.888\node_modules\@teambit\legacy\dist\scope\network\http\http.js:310:13)

**Comment by itaymendel** [comment]
for exporting issues with bit.cloud reach out to support@bit.cloud
