### ISSUE TITLE
50849114

### ISSUE THREAD

**Issue by dimitrigeier1** [teambit/bit#6172]
### Describe the bug
error in console during preview

docs.preview.runtime.js:70 Uncaught (in promise) TypeError: modules.mainModule.default is not a function
    at DocsPreview.render (docs.preview.runtime.js:70:1)
    at PreviewPreview.render (preview.preview.runtime.js:205:1)

code with the error
 if (!isObject) {
        const docsPropsArray = [NoopProvider, componentId.toString(), docsModule, compositions, context];
        modules.mainModule.default(...docsPropsArray);
        return;
      }

### Expected Behavior
preview suddenly stopped working in the library app

### Specifications
current (used) bvm version: 0.1.5
current (used) bit version: 0.0.795

* Workspace type: (harmony)
* Node version:
* npm / yarn version:
* Platform: osx

_for harmony workspace_

* relevant env standard
* relevant aspects standard

**Comment by front-end-captain** [comment]
Hi, I also maat this problem, and you can check you package.json whether  has "type": "module" field, remove it, everything worked
