### ISSUE TITLE
preview bundle contains both cjs and esm build of the same dependency package

### ISSUE THREAD

**Issue by antoineDemiurge** [teambit/bit#6175]
### Describe the bug
for some dependencies, the bundle built and used by the preview UI (bit start) contains both **commonjs** and **esm** build, so that there are multiples instances of the same package in the bundle.
it happens when a dependency is used by a component (resulting in addition of the **commonjs** build in the bundle) AND by another dependency (resulting in the addition of the **esm** build in the bundle).

### Steps to Reproduce
in this exemple, **three** (3d library) is used directly in the component and also inside **@react-three/drei** and **@react-three/fiber** packages, resulting in **three** being bundled two times.

1. `bit new react test-workspace --default-scope xxxxxxx.test`
1. `cd test-workspace`
1. `bit install three@0.137 @types/three@0.137 @react-three/fiber@7.0.27 @react-three/drei@8.20.2`
1. `bit create react test`
1. edit **test/test/test.tsx** 

```
import React from 'react';

// INDIRECT use of three package from the component
import { Canvas } from '@react-three/fiber'
import { PerspectiveCamera as PerspectiveCameraDrei } from '@react-three/drei'

// DIRECT use of three package from the component
import { Vector3 } from 'three';
const v = new Vector3()

const PerspectiveCamera: any = PerspectiveCameraDrei


export function Test({ children }: any) {
    return (
        <div style={{ width: '100%', height: '100%', background: '#555' }}>
            <Canvas>

                <PerspectiveCamera
                    makeDefault
                    position={[0, 0, 50]}
                    zoom={1}
                    up={[0, 0, 1]}
                    far={10000} />

                <directionalLight
                    position={[-3, 3, 100]}
                    intensity={1.5} />

                <mesh rotation={[Math.PI / 4, Math.PI / 4, 0]} scale={[5, 5, 5]}>
                    <boxGeometry />
                    <meshStandardMaterial color={'#ffa500'} />
                </mesh>

            </Canvas >
        </div>
    );
}

```

1. `bit start`
1. look at javascript console: three package auto detect multiple instances: `WARNING: Multiple instances of Three.js being imported.`
1. check the bundle content **(http:// localhost:3000/preview/teambit.react/react/static/js/main.bundle.js)**, we find both:

`/* harmony import */ var three__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! three */ "./node_modules/.pnpm/registry.npmjs.org+three@0.137.0/node_modules/three/build/three.module.js");`

**AND**

`const three_1 = __webpack_require__(/*! three */ "./node_modules/.pnpm/registry.npmjs.org+three@0.137.0/node_modules/three/build/three.cjs");`

**this is the same package, twice:**
./node_modules/.pnpm/registry.npmjs.org+three@0.137.0/node_modules/three/build/**three.module.js**
./node_modules/.pnpm/registry.npmjs.org+three@0.137.0/node_modules/three/build/**three.cjs**

### Expected Behavior
only one Three package instance must be bundled

### Screenshots, exceptions and logs
![bit dev-issue](https://user-images.githubusercontent.com/102366929/180238494-f609e25a-1705-425b-9e60-0296be92507a.png)

### Specifications
* Bit version: 0.0.794
* Workspace type: (harmony/legacy)
* Node version: 16.14.0
* npm / yarn version: 
* Platform: Windows 11

_for harmony workspace_

* relevant env: teambit.react/react
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
try putting it in the peers of getDependencies of your custom react env (and remove the custom webpack)

**Comment by antoineDemiurge** [comment]
No, it does'nt work.

But this custom webpack config in my custom react env actually solved the problem,
(not sure if it's to be considered as a workaround or a fix as I don't understand why three package was bundled 2 times in the first place)

```
const confOverride = {
        resolve: {
            alias: {
                three$: "three/build/three.module.js"
            }
        }
    }
config.merge([confOverride]);
```

**Comment by GiladShoham** [comment]
how did you added it as peer from your env?
as for every peer from your env, we are adding that alias automatically, so it should have been work

**Comment by antoineDemiurge** [comment]
**three** package is set as peer in workspace.jsonc : 
```
"teambit.dependencies/dependency-resolver": {
    "policy": {
      "peerDependencies": {
        ...
        "three": "0.137.0"
      }
   }
}
```

before webpack config override from my env, webpack config is indeed:
```
resolve: {
    alias: {
      ...
      three: 'C:\\Users\\antoine\\workspace\\demiurge\\bit\\bit-workspace\\node_modules\\.pnpm\\registry.npmjs.org+three@0.137.0\\node_modules\\three',
      ...
    },
}
```

and after config override: 
```
resolve: {
    alias: {
      ...
      three: 'C:\\Users\\antoine\\workspace\\demiurge\\bit\\bit-workspace\\node_modules\\.pnpm\\registry.npmjs.org+three@0.137.0\\node_modules\\three',
      ...
      'three$': 'three/build/three.module.js'
    },
}
```

My config aims at forcing use three as module, because **three** package expose both a module and cjs build 
three.js package.json:
```
{
  "name": "three",
  "version": "0.141.0",
  "description": "JavaScript 3D library",
  "type": "module",
  "main": "./build/three.js",
  "module": "./build/three.module.js",
  "exports": {
    ".": {
      "import": "./build/three.module.js",
      "require": "./build/three.cjs"
    },
    ...
}
```

And by default (without my config override), bit uses: 
- the cjs ("build/three.cjs") when resolving import from my component's code
- and the module ("build/three.module.js") when resolving import from my component's other dependencies.
so bundle contains both.

**Comment by GiladShoham** [comment]
you need to set it as peer from the env not from the workspace.

**Comment by antoineDemiurge** [comment]
I previously tried from my env as you said, like this: 
```
react.overrideDependencies({
    devDependencies: {
    }
    peerDependencies: {
        ...
        "three": "0.137.0"
    },
})
```
but it didn't change the dual bundling issue.



My only question is why the same **import { _whatever_ } from "three"** can be resolve differently inside the same bundle ?
I'm not sure is has anything to do with the package being a peerDependency or not ?

the [webpack _resolve_ config](https://webpack.js.org/configuration/resolve/) is quite confusing, it may have to do with one of those config field: 
- resolve.mainFields
- resolve.importsFields
- or even resolve.byDependency

**Comment by antoineDemiurge** [comment]
### This is a webpack issue actually.

It seems to be the normal webpack behaviour to resolve a package using the cjs build when resolving _require_ FROM a cjs package, and resolve the same package using module build when resolving _import_ from an esm package. 

So it's a normal ending to get a package (that expose _module_ and _cjs_ builds) bundled two times, when imported from multiple dependencies of different types.

It is still problematic ! but not specifically related to bit.
This is the first time I work with a tool that output cjs package, so I though it was a problem with bit.

Thanks for your help.
