### ISSUE TITLE
use bit component from next.js App failed if component import css files

### ISSUE THREAD

**Issue by antoineDemiurge** [teambit/bit#6196]
Next.js refuse to import css file from node_modules package, 
the bit.dev react-env does not convert css file into js, so components can't be used from next.js project.
How to convert css file into js during the component build in bit ?

**Comment by struckm** [comment]
@antoineDemiurge I ran into the same issue. A quick fix is to use the npm modules next-transpile-modules and next-compose-plugins. Below is the next.config.js configuration that worked for me:

`const withPlugins = require('next-compose-plugins');
const withTM = require('next-transpile-modules')([
'bit-component1',
'bit-component2'
]);

module.exports = withPlugins([withTM], {
...your existing custom configuration
})
`

Mark
