### ISSUE TITLE
remove mention of `untrack` from `bit remove -h` output

### ISSUE THREAD

**Issue by odedre** [teambit/bit#6200]
now that `bit untrack` is no longer supported, there shouldnt be a mention of it in `bit remove -h`.
see screenshot in the description of `--keep-files`.

* Bit version: 870
![Screen Shot 2022-07-26 at 22 05 27](https://user-images.githubusercontent.com/15064762/181092002-5c86f05e-9604-49ef-8d1e-4fb063084076.png)

**Comment by GiladShoham** [comment]
This doesn't mention the `bit untrack` command. it treat untrack as a verb
