### ISSUE TITLE
How can I use my custom workspace generator from self-hosted scope

### ISSUE THREAD

**Issue by front-end-captain** [teambit/bit#6204]
### Description
I write a  workspace generator and exported to my self-hosted scope, but when use it

```
bit new dp-example-workspace bit-workspace-test --aspect dp-design/my-workspace-generator --default-scope dp-design
```

then get error:

```
cannot find scope 'dp-design'. if you are targeting a self-hosted scope, please ensure the scope is configured in your remotes (via "bit remote" command) and that the scope name is correct.if this is a scope on bit.cloud please add the organization name before the scope (yourOrg.some-scope-name)
```

### Specifications
* Bit version: 0.0.791
* Node version: 16.14.2
* npm / yarn version: 7.24.2/1.22.18
* Platform:mac os
* Bit compiler (include version):
* Bit tester (include version):

**Comment by jonatankBIT** [comment]
Did you add your remote scoped to be tracked?
```
bit remote add <my_remote_scope>
```

**Comment by front-end-captain** [comment]
I try execute `bit remote`, but `bit remote` must used inside a workspace

**Comment by jonatankBIT** [comment]
In that case:
1. Create your workspace without the `--default-scope` flag.
2. Run `bit remote add <my_remote_scope>`
3. Update your `defaultScope` in your `workspace.jsonc`

**Comment by front-end-captain** [comment]
@jonatankBIT 
I get this error

<img width="1672" alt="image" src="https://user-images.githubusercontent.com/25813333/181186101-ebdc49d7-f8a2-4131-8daa-b79ccf43f034.png">

**Comment by jonatankBIT** [comment]
After `bit new ....` cd into `bit-workspace-test` afterwards:

```
bit new dp-example-workspace bit-workspace-test --aspect dp-design/my-workspace-generator
cd  bit-workspace-test
bit remote add http://10.248.142.3:3000
// update scope on `dafaultScope`
```

Does it still persist?

**Comment by front-end-captain** [comment]
@jonatankBIT emmmm... An error reported in the first step, so it was impossible to create a workspace

**Comment by front-end-captain** [comment]
@jonatankBIT Can this problem still be solved？

**Comment by front-end-captain** [comment]
@jonatankBIT I found a solution. 

```
cd ~/Library/Caches/Bit/scope
bit remote add <my_self_remote_scope_url>
```

and then
```
cd -
bit new dp-example-workspace bit-workspace-test --aspect dp-design/my-workspace-generator --default-scope dp-design
```

success. and new question: how can I add global remote scope?
