### ISSUE TITLE
teambit.defender/tester:TestComponents fails on first run with env teambit.react/react-native

### ISSUE THREAD

**Issue by jonatankBIT** [teambit/bit#6205]
### Describe the bug
When setting up a react-native workspace, the build will fail even with the demo ui/text component.

### Steps to Reproduce
1. bit new react-native my-new-workspace
1. bit install && bit compile
1. bit test will pass all the tests.
1. bit build => fails.

### Expected Behavior
To have the build process completed.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/97826324/181174170-a5034edf-9115-49dc-94a7-fbf044f54622.png)

### Specifications
* Bit version:0.0.801
* Workspace type: (harmony/legacy): harmony
* Node version: 16.14.0
* npm / yarn version: 1.22.118
* Platform: MacOs

_for harmony workspace_

* relevant env: teambit.react/react-native
* relevant aspects

**Comment by abhi-zorro** [comment]
the same happens when the env is teambit.react/react
![image](https://user-images.githubusercontent.com/102013964/188324902-1d8ea2dd-f20c-43bc-a730-09c2e0da952e.png)

**Comment by filipamarta** [comment]
![Screenshot 2023-01-10 at 13 40 29](https://user-images.githubusercontent.com/19548808/211586928-51094cf7-ec3e-49e0-951f-defd07194738.png)

In my case it's the same. Can someone help?

Bit version: 0.0.945
Node version: v16.14.0
yarn version: 1.22.19
npm version: 8.3.1
Platform: MacOs

**Comment by itaymendel** [comment]
react-native has been re-written from 0. please use up-to-date plugin.
