### ISSUE TITLE
when running `bit reset` it resets the envs as well

### ISSUE THREAD

**Issue by odedre** [teambit/bit#6207]
### Describe the bug
ran `bit reset` to untag a few components and saw that their envs were reset as well 

### Steps to Reproduce
1. create a few components
1. set their envs to community-react `bit env replace teambit.harmony/node teambit.community/envs/community-react@2.1.5`
1. `bit tag`
1. `bit reset -a`
1. run `bit envs`
1. see that the envs were all changed back to `teambit.harmony/node`

### Expected Behavior
should keep the envs the same, just untag the components

* Bit version: 800
* Node version: v16.15.1

**Comment by davidfirst** [comment]
Here it is:
https://github.com/teambit/bit/discussions/5074#discussioncomment-1738413

**Comment by itaymendel** [comment]
no longer relevant. issue resolved already.
