### ISSUE TITLE
Components are never staged

### ISSUE THREAD

**Issue by ingveldur** [teambit/bit#6233]
### Description
I'm following the Angular tutorial from you guys (https://bit.cloud/teambit/angular/angular), and everything seems to be working alright, apart from a few warnings in console.

What I'm trying to do is to **export an Angular component to a remote scope**. When I run `bit status` my components shows up ok.

```
% bit status                         
new components
(use "bit tag --all [version]" to lock a version with all your changes)

     > ui/my-button ... ok
```

I tag the component, which runs successfully (**although teambit.defender/tester:TestComponents throws an error** ?) and an Angular Package is built. 

## Building entry point '@werkr/buttons.ui.my-button'
✔ Compiling with Angular sources in Ivy partial compilation mode.
✔ Writing FESM bundles
✔ Copying assets
ℹ Removing devDependencies section in package.json.
✔ Writing package manifest
✔ Built @werkr/buttons.ui.my-button

- - -
Built Angular Package

* from: /Users/inga/Library/Caches/Bit/capsules/1bf6f590a4ba054767327882509fe862f30b8aba/werkr.buttons_ui_my-button@0.0.1
* to:   /Users/inga/Library/Caches/Bit/capsules/1bf6f590a4ba054767327882509fe862f30b8aba/werkr.buttons_ui_my-button@0.0.1/dist
------------------------------------------------------------------------------

Build at: 2022-07-31T23:54:44.301Z - Time: 3515ms

✔ env "teambit.angular/angular@1.2.3", task "teambit.compilation/compiler:NgPackagrCompiler (compile components for artifact dist)" has completed successfully in 6s
✖ env: teambit.angular/angular@1.2.3, task "teambit.defender/tester:TestComponents" threw an error
● Validation Error:

  Preset jest-preset-angular not found.

  Configuration Documentation:
  https://jestjs.io/docs/configuration

     However, when I run the `bit status` command again _there are no staged components_ and when I run `bit export` I get `nothing to export` message, so thats as far as I can go. 
        
    I tried following the quick start tutorial with React as well (https://bit.dev/docs/quick-start/) but the same thing happens, there are no staged components...
    inga@MAC-IST001234 my-wiki % bit tag wiki/apps/wiki --ver 1.0.0 --message "my first version"
✔ running pre install subscribers
✔ deduping dependencies for installation
(node:90256) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./src/" in the "exports" field module resolution of the package at /Users/inga/.bvm/versions/0.0.805/bit-0.0.805/node_modules/ramda/package.json.
Update this package.json to use a subpath pattern like "./src/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
...b8e4a132cab45821b7be2c1e6175a8435ea3c |  +53 +++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/inga/.pnpm-store/v3
  Virtual store is at:             ../../Library/Caches/Bit/capsules/e8fb8e4a132cab45821b7be2c1e6175a8435ea3c/node_modules/.pnpm
...b8e4a132cab45821b7be2c1e6175a8435ea3c | Progress: resolved 59, reused 53, downloaded 0, added 47

- - -
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
  running build pipe for 1 environments, total 7 tasks
  generated graph for env "teambit.react/react", originalSeedersOfThisEnv: 1, graphOfThisEnv: 1, graph total: 1
✔ executing pre-build for all tasks
✔ env "teambit.react/react", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 204μs
✔ env "teambit.react/react", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 1s
✖ env: teambit.react/react, task "teambit.defender/tester:TestComponents" threw an error
Cannot find module 'jest'
Require stack:

* /Users/inga/.bvm/versions/0.0.805/bit-0.0.805/node_modules/@teambit/react/dist/react.env.js
* /Users/inga/.bvm/versions/0.0.805/bit-0.0.805/node_modules/@teambit/react/dist/react.main.runtime.js
* /Users/inga/.bvm/versions/0.0.805/bit-0.0.805/node_modules/@teambit/bit/dist/load-bit.js
* /Users/inga/.bvm/versions/0.0.805/bit-0.0.805/node_modules/@teambit/bit/dist/app.js
* /Users/inga/.bvm/versions/0.0.805/bit-0.0.805/node_modules/teambit/bit/bin/bit

inga@MAC-IST001234 my-wiki % bit status
new components
(use "bit tag --all [version]" to lock a version with all your changes)

```
 > apps/wiki ... ok
```

inga@MAC-IST001234 my-wiki % bit export
nothing to export
```

Any idea what could be wrong? Thanks in advance.

### Specifications
* Bit version: 0.0.805
* Node version: v16.14.2
* npm: 8.5.0
* Platform: macos

**Comment by morwalz** [comment]
I am also getting same issue. did you find any solution ?

**Comment by itaymendel** [comment]
angular support has been re-factored. issue is no longer relevant.
please consult with the docs on the latest usage and commands.
