### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by kaluohena** [teambit/bit#6245]
### Describe the bug
Run `bit test component/some-component` cause `ReferenceError: React is not defined`.
I have added the following babel config on the compiler in my react env by following [this doc.](https://bit.dev/docs/dev-services/compiler/using-a-compiler)

```
{
  "presets": [
    "@babel/preset-env",
    [
      "@babel/preset-react",
      {
        "runtime": "automatic"
      }
    ]
  ]
}

```

### Steps to Reproduce
1. bit compile
1. bit test component/some-component

### Expected Behavior
There will be no `ReferenceError: React is not defined` error when the test file and component source code doesn't contain the line `import React from 'react'`.

### Specifications
* Bit version: 0.0.779
* Workspace type: harmony
* Node version: 14.17.3
* npm / yarn version: 1.22.10
* Platform: Mac OS

### Additional context
React version 17.0.2

**Comment by GiladShoham** [comment]
Bit test has its own babel config.
You need to add it there as well

**Comment by sunnypatel** [comment]
I'm having the same issue but when I run `bit tag` 

Trying to export two Bit components which I've created using the Bit cli but keep getting different dependency errors. 

After running `bit tag --message "init sample components"` 
I get this error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '@emotion/react' in '/Users/spatel2/Library/Caches/Bit/capsules/df42a56200d482df346c1f9a7c357b358401c661/node_modules/@paypalcorp/pp-react-accordion/dist/@paypalcorp'
ModuleNotFoundError: Module not found: Error: Can't resolve '@emotion/react' in '/Users/spatel2/Library/Caches/Bit/capsules/df42a56200d482df346c1f9a7c357b358401c661/node

Found 2 errors in 2 components
✖ Total 7 tasks. 5 succeeded. 2 failed. 0 skipped. Total errors: 4.
```

Here is my `workspace.jsonc` 
```javascript
/**
 * this is the main configuration file of your bit workspace.
 * for full documentation, please see: https://bit.dev/docs/workspace/workspace-configuration
 **/{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  /**
   * main configuration of the Bit workspace.
   **/
  "teambit.workspace/workspace": {
    "name": "Checkout - Web Platform ",
    "icon": "https://www.paypalobjects.com/paypal-ui/logos/svg/paypal-wordmark-color.svg",
    "defaultDirectory": "{scope}/{name}",
    "defaultScope": "shared"
  },
  /**
   * main configuration for component dependency resolution.
   **/
  "teambit.dependencies/dependency-resolver": {
    "packageManager": "teambit.dependencies/yarn",
    "policy": {
      "dependencies": {
        "@emotion/react": "11.10.0",
        "@paypalcorp/pp-react": "7.0.0",
        "@testing-library/react-hooks": "8.0.1",
        "react-dom": "18.2.0"
      },
      "peerDependencies": {
        "react": "18.2.0"
      }
    }
  },
  "teambit.workspace/variants": {
    /**
     * "*" is a special rule which applied on all components in the workspace.
     **/
    "*": {
      /**
       * uncomment to apply the chosen environment on all components.
       **/
      //"teambit.react/react": {}
    }
  }
}
```

I've already tried installing the missing pkg using `bit install -u @emotion/react --type peer` but still getting same error.

Bit version: `0.0.796` 

Node version: `14.19.0`

**Comment by kaluohena** [comment]
@GiladShoham Thanks for your answer. I solve this issue by creating a new transformer base on the  `cjs-transformer.js` in `@teambit/react/jest` and add the babel config there, then pass it to the `transform` in `jest.config.js`.

**Comment by benjgil** [comment]
@sunnypatel yours is a separate issue - but move @emotion packages to the peerDependencies and this should resolve the issue
