### ISSUE TITLE
Error: bit component was not found inside another bit component

### ISSUE THREAD

**Issue by angeltrevinov** [teambit/bit#6252]
### Description
I was trying to use my private bit component inside a new bit component I'm creating, but every time I run `bit status` or `bit snap` it shows the following error 

`error: component <my private component> was not found
consider running "bit dependents <my private component> to understand why this component was needed
`
running `bit dependents` only shows this 

`Dependents originated from workspace

Dependents Details
╔══════════════╤═══════╤══════════════════════╤════════════════╗
║ Dependent ID │ Depth │ Immediate Dependency │ Dependent type ║
╟──────────────┼───────┼──────────────────────┼────────────────╢
║ ui/carousel  │ 1     │ <self>               │ prod           ║
╚══════════════╧═══════╧══════════════════════╧════════════════╝

Dependents originated from scope
<none>
`

I already added to my dependency policy and also to my peerDependencies but nothing changes, I can locally run `bit start` and everything is working fine. 

I also edited my .npmrc file to include my key and the registry but nothing changes. 

### Specifications
* Bit version: 0.0.807
* Node version: v16.15.0
* npm / yarn version: npm 8.5.5
* Platform: WSL2 ubuntu

### Context and additional information
Using React js templates for my components, not if it has to do with the private setting of my scope.

**Comment by itaymendel** [comment]
please provider STRs.
closing the issue for now. if still relevant, i'll reopen.
