### ISSUE TITLE
Bit lit failed to start

### ISSUE THREAD

**Issue by khanh-le-otsv** [teambit/bit#6266]
### Describe the bug
Bit lit-elements failed to start.

### Steps to Reproduce
1. Run `bit new lit my-lit-workspace --aspect teambit.web-components/lit` and `cd` to it
1. Run `bit create lit icons`, `bit install` and `bit start`

### Expected Behavior
bit should start successfully

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/85324726/182752855-38ca571f-c694-49bb-901d-15d3b4f94118.png)

### Specifications
* Bit version: 0.0.807
* Workspace type: harmony
* Node version: 16.14.2
* npm / yarn version: 8.15.0
* Platform: MacOS

_for harmony workspace_

* relevant env: lit
* relevant aspects: teambit.web-components/lit

### Additional context
N/A

**Comment by GiladShoham** [comment]
i'm checking it

**Comment by GiladShoham** [comment]
please try with the new version of lit 0.0.22.
If it's still not working, you might need to wait for this https://github.com/teambit/bit/pull/6268
(it should be merged today, and released in the next nightly hopefully)

**Comment by khanh-le-otsv** [comment]
Updating to 0.0.22 fixed the problem, thank you so much for the quick fix.
