### ISSUE TITLE
new command:  bit start map="ui/card"

### ISSUE THREAD

**Issue by qld-cf** [teambit/bit#6271]
### Description
Suggest:

1. my .bitmap already has many components, every time run `bit start` or hot-reload will take long long time;
1. so hope bit could support new command, like `bit start map="ui/card"` to run corresponding components
1. thanks, hope to get recover soon~

```
"ui/card": {
        "scope": "myscope.base-ui",
        "version": "0.0.18",
        "mainFile": "index.ts",
        "rootDir": "ui/card"
    },
"ui/xxxxxxxx": {
        "scope": "myscope.base-ui",
        "version": "0.0.11",
        "mainFile": "index.ts",
        "rootDir": "ui/xxxxxxxx"
    },
....
```

**Comment by itaymendel** [comment]
not looking to build that feature.
regardless, there's an effort to improve performacne for bit-start.

closing the issue.
