### ISSUE TITLE
Bit Component does not exist on bit.cloud

### ISSUE THREAD

**Issue by Mvrs** [teambit/bit#6297]
### Describe the bug
Currently, my component shows it exists under the scope `fullcourt` but now I'm unable to run to fetch the metadata from the hosted cloud environment `bit.cloud`. It shows my package available to install, but sadly unable to do so. I even scoped the registry (could have done it wrong).

when I run: 

* yarn add `@50four-ui/fullcourt.button` - **Installing module to new project**
  *  Results in the following error:

![](https://user-images.githubusercontent.com/5723692/184090345-134ee899-0781-42b5-b5cc-7e735789dca3.png)

when publishing the component separately into a npm-registry:

* Results in the following error: 
![](https://user-images.githubusercontent.com/5723692/184090668-24a458b2-5fee-4559-953b-61db09a1e58a.png)

My .npmrc file: 

```
@50four:registry=https://node.bit.cloud
@teambit:registry=https://node.bit.cloud
//node.bit.cloud/:_authToken=<USER_TOKEN>
```

From the `node.bit.cloud` endpoint

* Results in the package returning a `404`

![](https://user-images.githubusercontent.com/5723692/184091061-0e8791c9-3d8b-408a-bee0-8e0e7fc33c8a.png)

Last but not least my `workspace.jsonc` file: 

    /**
     * this is the main configuration file of your bit workspace.
     * for full documentation, please see: https://bit.dev/docs/workspace/workspace-configuration
     **/ {
      "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
      /**
       * main configuration of the Bit workspace.
       **/
      "teambit.workspace/workspace": {
        /**
         * the name of the component workspace. used for development purposes.
         **/
        "name": "50four",
        /**
         * set the icon to be shown on the Bit server.
         **/
        "icon": "https://static.bit.dev/bit-logo.svg",
        /**
         * default directory to place a component during `bit import` and `bit create`.
         * the following placeholders are available:
         * name - component name includes namespace, e.g. 'ui/button'.
         * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
         * scope - scope name only, e.g. 'compilation'.
         * owner - owner name in bit.dev, e.g. 'teambit'.
         **/
        "defaultDirectory": "src/components/{name}",
        /**
         * default scope for all components in workspace.
         **/
        "defaultScope": "50four.fullcourt-ui"
      },
      /**
       * main configuration for component dependency resolution.
       **/
      "teambit.dependencies/dependency-resolver": {
        /**
         * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
         */
        "packageManager": "teambit.dependencies/pnpm",
        "policy": {
          "dependencies": {
            "@babel/plugin-syntax-jsx": "7.18.6",
            "@babel/preset-react": "7.18.6",
            "@teambit/babel": "0.0.812",
            "@teambit/harmony": "0.3.3"
          },
          "peerDependencies": {
            "react-native-gesture-handler": ">=2.0.0",
            "react-native-reanimated": ">=2.0.0"
          }
        }
      },
      /**
       * workspace variants allow to set different subsets of configuration for components in your
       * workspace. this is extremely useful for upgrading, aligning and building components with a new
       * set of dependencies. a rule can be a directory or a component-id/namespace, in which case,
       * wrap the rule with curly brackets (e.g. `"{ui/*}": {}`)
       * see https://bit.dev/docs/workspace/variants for more info.
       **/
      "teambit.workspace/variants": {
        /**
         * "*" is a special rule which applied on all components in the workspace.
         **/
        "*": {
          /**
           * uncomment to apply the chosen environment on all components.
           **/
          "teambit.pkg/pkg": {
            "packageManagerPublishArgs": ["--access public"],
            "packageJson": {
              "private": false,
              "name": "@50four-ui/{scope}.{name}"
              // "publishConfig": {
              //   "scope": "@50four",
              //   "registry": "https://node.bit.cloud"
              // }
            }
            // "packageJsonProps": {
            //   "files": ["dist"]
            // }
          },
          "50four.fullcourt/extensions/react-native-web": {}
        },
        "extensions/react-native-web": {
          "teambit.harmony/aspect": {},
          "teambit.dependencies/dependency-resolver": {
            "policy": {
              "dependencies": {
                "@babel/core": "^7.18.5",
                "@babel/runtime": "^7.18.3",
                "@babel/preset-react": "^7.17.12",
                "@babel/preset-env": "^7.18.2",
                "@babel/preset-typescript": "^7.17.12",
                "@babel/plugin-proposal-class-properties": "^7.17.12"
              },
              "peerDependencies": {}
            }
          }
        },
        "button": {
          "teambit.harmony/aspect": {},
          "teambit.dependencies/dependency-resolver": {
            "policy": {
              "dependencies": {
                "@babel/core": "^7.18.5",
                "@babel/runtime": "^7.18.3",
                "@babel/preset-react": "^7.17.12",
                "@babel/preset-env": "^7.18.2",
                "@babel/preset-typescript": "^7.17.12",
                "@babel/plugin-syntax-jsx": "^7.18.6",
                "@babel/plugin-proposal-class-properties": "^7.17.12"
              },
              "peerDependencies": {}
            }
          }
        }
      }
    }

### Steps to Reproduce
1.  yarn add `@50four-ui/fullcourt.button`
2. Head to the component URL source [node.bit.cloud](https://node.bit.cloud/@50four-ui%2Ffullcourt.button)

### Expected Behavior
I expected to view my package in the cloud and it's hosted so I can install it into any other project.

### Specifications
* Bit version: `0.0.814`
* Workspace type: (harmony/legacy)
* Node version: `v16.15.1`
* npm / yarn version: `1.22.19`
* Platform: OSX 12.4 `Monterey` **M1**

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version): `0.1.10`
* Bit tester (include version): `N/A`

### Additional context
Appreciate the help in the advance :)

**Comment by GiladShoham** [comment]
do you want to publish it to a custom registry or to bit.cloud registry?
if you want to use our registry, you shouldn't use bit publish.
It will be published automatically once you export your component

**Comment by Mvrs** [comment]
> do you want to publish it to a custom registry or to bit.cloud registry?
> 
> if you want to use our registry, you shouldn't use bit publish.
> 
> It will be published automatically once you export your component

I want to use the bit.cloud registry, but it didn't publish and I've exported my component.

**Comment by Mvrs** [comment]
@GiladShoham So I initial tried to publish it by exporting the components but after successfully exporting them to my scope they never publish into the bit.cloud so when I try to download the module via yarn or npm it says the yarn registry doesn't exist giving me a 404 error. Do I possibly have to start over?

**Comment by GiladShoham** [comment]
Is it a public component?
I want to have a look on this.
Any chance you tagged the component then change its scope and tagged again?

**Comment by GiladShoham** [comment]
Also if it's a private component, maybe you are trying to install it from another machine without authenticating?

**Comment by Mvrs** [comment]
> Is it a public component?
> I want to have a look on this.
> Any chance you tagged the component then change its scope and tagged again?

Hey here is the public [scope](https://bit.cloud/50four)

There might be a possibility I might have changed the scope and tagged it again 😅.

**Comment by Mvrs** [comment]
Is there a way to know what scope your component is attached to? Also, is there a way to re-scope my company to what's in the bit.cloud?


Because it makes no sense why it's published on the cloud but it's inaccessible.

@GiladShoham

**Comment by Mvrs** [comment]
So I probably don't have permission to registry the components because when I first created my scope the intentions was for my team. I chose the scope to be private at first then make it public. I only tried changing the scope after tagging because I couldn't install my components

**Comment by Mvrs** [comment]
I also just noticed my organization `50four` shows `This organization has no scopes` when clicking on the **Scope Graph** which I found odd. 

Screenshot below:
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/5723692/184547722-bacdb223-3b40-40c2-854b-cff1c5a59e1c.png">


Also, trying to use Bit:

<img width="784" alt="image" src="https://user-images.githubusercontent.com/5723692/184547769-bc4a2bd5-1bf7-4d08-a53d-ddea47ea9635.png">

**Comment by Mvrs** [comment]
@GiladShoham what does this mean? Please!

```
ui on  test-new-scope [$!?] is 📦 v0.1.0 via ⬢ v16.15.1 via 🅒 base took 31s
⇣9% ➜ bit tag --ver 0.0.2 --message "new prop"
✔ running pre install subscribers
✔ deduping dependencies for installation
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated stable@0.1.8
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated source-map-resolve@0.5.3
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated chokidar@2.1.8
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated querystring@0.2.0
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated uglify-es@3.3.9
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated resolve-url@0.2.1
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated source-map-url@0.4.1
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated urix@0.1.0
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated fsevents@1.2.13
...c73836d2b5971875933520ca0731ae57bb681 |  WARN  deprecated uuid@3.4.0
...c73836d2b5971875933520ca0731ae57bb681 |    +1451 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /Users/mvrs/.pnpm-store/v3
  Virtual store is at:             ../../Library/Caches/Bit/capsules/b44c73836d2b5971875933520ca0731ae57bb681/node_modules/.pnpm
...c73836d2b5971875933520ca0731ae57bb681 | Progress: resolved 1361, reused 1361, downloaded 0, added 1451, done
  -------------------------
✔ installing dependencies using pnpm
✔ running post install subscribers
✔ linking components
  running build pipe for 1 environments, total 7 tasks
  generated graph for env "teambit.harmony/node", originalSeedersOfThisEnv: 1, graphOfThisEnv: 1, graph total: 1
✔ executing pre-build for all tasks
✔ env "teambit.harmony/node", task "teambit.harmony/aspect:CoreExporter (export all core aspects via the main aspects)" has completed successfully in 115μs
✔ env "teambit.harmony/node", task "teambit.compilation/compiler:TSCompiler (compile components for artifact dist)" has completed successfully in 870ms
✔ env "teambit.harmony/node", task "teambit.defender/tester:TestComponents" has completed successfully in 2ms
✔ env "teambit.harmony/node", task "teambit.pkg/pkg:PreparePackages" has completed successfully in 1ms
✔ env "teambit.harmony/node", task "teambit.harmony/application:build_application" has completed successfully in 251μs
✔ env "teambit.harmony/node", task "teambit.preview/preview:GenerateEnvTemplate" has completed successfully in 4ms
✔ env "teambit.harmony/node", task "teambit.preview/preview:GeneratePreview" has completed successfully in 943ms
✔ executing post-build for all tasks
✔ teambit.pipelines/builder, running build pipe for 1 environments, total 7 tasks (completed in 2s)
  running tag pipe for 1 environments, total 3 tasks
  generated graph for env "teambit.harmony/node", originalSeedersOfThisEnv: 1, graphOfThisEnv: 1, graph total: 1
✔ executing pre-build for all tasks
✔ env "teambit.harmony/node", task "teambit.pkg/pkg:PackComponents" has completed successfully in 231ms
✖ env: teambit.harmony/node, task "teambit.pkg/pkg:PublishComponents" has failed
✔ env "teambit.harmony/node", task "teambit.harmony/application:deploy_application" has completed successfully in 383μs
✔ executing post-build for all tasks
✖ teambit.pipelines/builder, running tag pipe for 1 environments, total 3 tasks (completed in 627ms)

The following errors were found while running the build pipeline
Failed task 1: "teambit.pkg/pkg:PublishComponents" of env "teambit.harmony/node"
component: 50four.fullcourt/button@0.0.2
failed running npm publish --access public at /Users/mvrs/Library/Caches/Bit/capsules/b44c73836d2b5971875933520ca0731ae57bb681/50four.fullcourt_button@0.0.2
npm notice
npm notice 📦  @50four/fullcourt.button@0.0.2
npm notice === Tarball Contents ===
npm notice 703B  button.stories.tsx
npm notice 2.8kB button.tsx
npm notice 1.2kB dist/button.d.ts
npm notice 3.2kB dist/button.js
npm notice 1.8kB dist/button.js.map
npm notice 465B  dist/button.stories.d.ts
npm notice 1.1kB dist/button.stories.js
npm notice 677B  dist/button.stories.js.map
npm notice 35B   dist/index.d.ts
npm notice 281B  dist/index.js
npm notice 135B  dist/index.js.map
npm notice 686B  dist/tsconfig.json
npm notice 35B   index.tsx
npm notice 4.7kB package-tar/50four-fullcourt.button-0.0.2.tgz
npm notice 697B  package.json
npm notice 65B   preview-1660906523427.js
npm notice 569B  tsconfig.json
npm notice 569B  types/asset.d.ts
npm notice 967B  types/style.d.ts
npm notice === Tarball Details ===
npm notice name:          @50four/fullcourt.button
npm notice version:       0.0.2
npm notice filename:      @50four/fullcourt.button-0.0.2.tgz
npm notice package size:  9.9 kB
npm notice unpacked size: 20.6 kB
npm notice shasum:        883108af9436dc8192f3d1ea0250a2799304888c
npm notice integrity:     sha512-nwKNh85jPiqvH[...]FGIqkamLAQNtA==
npm notice total files:   19
npm notice
npm notice Publishing to https://node.bit.cloud
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://node.bit.cloud/@50four%2ffullcourt.button
npm ERR! 404
npm ERR! 404  '@50four/fullcourt.button@0.0.2' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mvrs/.npm/_logs/2022-08-19T10_55_43_248Z-debug-0.log

Found 1 errors in 1 components


✖ Total 3 tasks. 2 succeeded. 1 failed. 0 skipped. Total errors: 1.
(
```

**Comment by Mvrs** [comment]
It's been Resolved!

My `.npmrc` file was corrupted. I've successfully published my first component and will do many more. Thanks, Bit for creating an awesome tool/product!

**Comment by GiladShoham** [comment]
Glad to hear that :)
