### ISSUE TITLE
Command/flag to add specs to already implemented component

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#63]
if i want to add a set of tests to an already implemented component, i need to create the spec file manually.
the CLI tool should allow me to append a spec file to a component.

**Comment by ran-y** [comment]
What do you say about `bit add-spec <component-id>` ?

We will also need `bit add-config <component-id>` / `bit add-json <component-id>` / `bit add-bit.json <component-id>` for creating a bit.json after the component has been created.

**Comment by ran-y** [comment]
For now we can just use the create command to generate specs - 2ea6d31

**Comment by itaymendel** [comment]
thanks, seems to be working
