### ISSUE TITLE
Can't build when using `config.addEntry` in custom react env

### ISSUE THREAD

**Issue by ferrybrouwer** [teambit/bit#6303]
### Describe the bug
When using a custom react env, we can add entries to the existing webpack configuration by using the `webpack-transformers`. 
When adding an entry using the `WebpackConfigMutator` config API `addEntry`, you can not build your components anymore. 

The error will throw:

```
✖ env: organisation.scope/my-custom-react-env, task "teambit.preview/preview:GeneratePreview" threw an error
can't add an entry to a function type raw entry
```

The issue is discussed via Slack:

Benjamin Gilbert via Slack: 

> "we need to update the `addEntry` function, which currently checks if the entry is an array, but it’s an object now…"

https://bit-dev-community.slack.com/archives/CNSFZ56UB/p1660239808997439?thread_ts=1660208115.824559&cid=CNSFZ56UB

### Steps to Reproduce
1. create and install a bit workspace

  ```sh
  bit new react sample-workspace --defaultScope my-organisation.my-scope && \
    cd sample-workspace && bit install
  ```

2. Create a custom environment _(to extend webpack configuration)_

  ```sh
  bit create react-env my-custom-react-env
  ```

3. Create a files which will be added to the entry of the webpack config within this custom env

  ```sh
  echo "console.log('a')" > ./my-scope/my-custom-react-env/a.js;
  ```

4. Add the created file as entry to the webpack config by edit  `./my-scope/my-custom-react-env/webpack/webpack-transformer.ts`

  ```typescript
    function commonTransformation(
      config: WebpackConfigMutator,
      _context: WebpackConfigTransformContext
    ) {
      config.addEntry(require.resolve('../a.js')); // <-- this will throw the error when run `bit build --dev` or `bit export`
      return config;
    }
  ```

5. Compile the react environment

  ```sh
  bit compile my-custom-react-env
  ```

6. Add a react component using the custom env

  ```sh
  bit create react ui/button --env my-organisation.my-scope/my-custom-react-env
  ```

7. Make sure the `ui/button` is using this custom react env by edit the `teambit.workspace/variants` within `workspace.jsonc`

  ```json
  "teambit.workspace/variants": {
    "{**/ui}": {
      "my-organisation.my-scope/my-custom-react-env": {}
    }
  }
  ```

8. Try to build

  ```sh
  bit build --dev
  ```

9. You should see this error in the console

  ```sh
✖ env: my-organisation.my-scope/my-custom-react-env, task "teambit.preview/preview:GeneratePreview" threw an error
can't add an entry to a function type raw entry
  ```

### Expected Behavior
I would expect the the component can be build by bit and the entry can be added via preview and dev server without errors.

### Screenshots, exceptions and logs

When errored the config looks like (using `bit build --dev`):
![Screenshot 2022-08-11 at 19 09 27](https://user-images.githubusercontent.com/4455679/184210944-57c2f3cd-64e3-447d-b301-2f3ddeed3370.png)

When starting the development server (using `bit start`) there's no error and everything works fine:
![Screenshot 2022-08-11 at 19 16 29](https://user-images.githubusercontent.com/4455679/184211122-430d8e08-604f-47d6-b7f7-7a778c341272.png)

> Note the different type of `entry`; when it's an object the error will be thrown

### Specifications
* Bit version: 0.0.815 _(happens in all versions except 0.0.651 and lower)_
* Workspace type: harmony
* Node version: 16.14.2
* npm / yarn version: yarn 1.22.18
* Platform: MacOS

_for harmony workspace_

* relevant env See above in reproducable steps
* relevant aspects (custom aspect based on react-env)

**Comment by NitsanCohen770** [comment]
this is resolved with the envs api
