### ISSUE TITLE
Internal server error react-design-system template

### ISSUE THREAD

**Issue by AlkenD** [teambit/bit#6312]
### Describe the bug
When i use the react-design-system template to setup a workspace it does open up the ui server on port but unusable as it shows internal server message. This happens on new setup of the workspace without creating any components within. The workspace is initialised without any errors the error occurs only on 'bit start' command. I did notice that the default workspace.jsonc had some missing dependencies missing so i had installed them and then i faced another issue stating 'artifacts is not iterable'

### Steps to Reproduce
1. bit new react-design-system task-workspace --default-scope my-org.tasks-scope
1. cd task-workspace
1. install the missing dependencies 
```@teambit/design.themes.theme-toggler``` 
```@teambit/design.themes.dark-theme```
```@teambit/design.themes.light-theme```
```@teambit/design.ui.cards.card```
```@teambit/design.themes.base-theme``` 
```@teambit/design.ui.heading```
1. bit start

### Expected Behavior
The workspace should be up and running without any issues but instead is unusable

### Screenshots, exceptions and logs
![](https://user-images.githubusercontent.com/96910178/184586004-963122ad-c1d7-4033-ad1f-bdca8bf89447.png)

### Specifications
* Bit version: 0.0.818
* Workspace type: harmony
* Node version: v16.16.0
* npm / yarn version: 8.11.0
* Platform: macOS

_for harmony workspace_

* relevant env
* relevant aspects

[Note]: I'm new to bit and its my first time using it and the docs were a lil tough to figure our stuff until i read everything in depth :sweat_smile:

**Comment by itaymendel** [comment]
all templates were re-implemetned. this issue is no longer relevant.
