### ISSUE TITLE
Slack link no longer active

### ISSUE THREAD

**Issue by hollyos** [teambit/bit#6323]
The url for joining Slack is no longer active. Need to update the Slack link everywhere to let new people join the community.

![Screen Shot 2022-08-16 at 2 46 07 PM](https://user-images.githubusercontent.com/4097509/184971081-8ff0fe4e-7095-4731-b5d6-8d9df35f2876.png)

* [This repo](https://github.com/teambit/bit/search?q=join.slack)
* [Discussions](https://github.com/teambit/bit/discussions/4449)

**Comment by JoshK2** [comment]
Thanks for letting up know, I fixed it in this pr #6327.
