### ISSUE TITLE
bit create express-app [name] results in warning: no files to add

### ISSUE THREAD

**Issue by juni0r** [teambit/bit#6326]
### Describe the bug
Following the [blog post on microservices](https://bit.cloud/blog/component-driven-microservices-with-nodejs-and-bit-l64shurc) I get an error from `bit create express-app status-service`

```
$ bit create express-app status-service
warning: no files to add, the following files were ignored: testbit/status-service
```

### Steps to Reproduce
1. `mkdir status-service-ws`
1. `cd status-service-ws`
1. `bit init`
1. `bit create express-app status-service`
warning: no files to add, the following files were ignored: testbit/status-service

### Expected Behavior
Creates the `status-service` component.

### Specifications
* Bit version: 0.0.821
* Workspace type: harmony
* Node version: 16.13.1
* npm / yarn version: pnpm 6.32.3
* Platform: macOS

### Additional context
`workspace.jsonc`

```json
{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  "teambit.workspace/workspace": {
    "name": "status-service-ws",
    "defaultDirectory": "{scope}/{name}",
    "defaultScope": "juni0r.testbit"
  }
}
```

**Comment by juni0r** [comment]
My bad. I didn't `git init` and there was a `.gitignore` file misplaced in the parent dir. Found the hint by looking at the code. Maybe modify the [error message](https://github.com/teambit/bit/blob/85e4f893a14dc02c4bf68c61d682353070df0506/src/cli/default-error-handler.ts#L335-L340) to make it clearer, that this is an issue with SCM ignore config? I initially figured it was some sort of Bit related ignore setting and started looking in all the wrong places.

**Comment by GiladShoham** [comment]
Thanks for the feedback, we will improve the error message.
@davidfirst FYI
