### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by Jiyp** [teambit/bit#6339]
### Description

I fork the bit source code locally. When I configure the local development environment according to the development guidelines, I always prompt failure when executing bit install; There are two reasons, one of which is connect etimedout. Due to network reasons, can you set the timeout time longer, or whether there are other methods to enable me to install normally

### Specifications
* Bit version: 0.0.820
* Node version: 16.14.0
* npm / yarn version: 8.5.3
* Platform: macOS Monterey 12.5
* Bit compiler (include version):
* Bit tester (include version):

### Context and additional information

fetching 322 components from 29 remotes. delta-only: 0, all-history: 322.getScope has failed
    message: "request to https://symphony.bit.cloud/graphql failed, reason: connect ETIMEDOUT 104.18.31.180:443"
    type: "system"
    errno: "ETIMEDOUT"
    code: "ETIMEDOUT"
    stack: "FetchError: request to https://symphony.bit.cloud/graphql failed, reason: connect ETIMEDOUT 104.18.31.180:443\n    at ClientRequest.
got an error from command install: Error: teambit.component: unknown error.

**Comment by davidfirst** [comment]
@Jiyp , can you try again? I believe it was a one off.

**Comment by Seventysevendays** [comment]
+1

**Comment by gosone** [comment]
@Jiyp , do you resolve this problem? I had the same problem.

**Comment by itaymendel** [comment]
when setting up bit in a self-hosted env, you need to set up cross-publish to artifactory or any other self-hosted package registery. from the looks of the error, you havne't done that part of the tutorial.
