### ISSUE TITLE
Unable to tag components

### ISSUE THREAD

**Issue by satyampakker** [teambit/bit#6360]
### Description

I am trying to tag a component to create a new versions and running to build errors. 

**The following errors were found while running the build pipeline
Failed task 1: "teambit.harmony/application:build_application" of env "teambit.harmony/aspect"
component: spakker.demo/my-app@0.0.1
BitError: message: [prerender-spa-plugin] Unable to prerender all routes!
BitError: message: Could not find expected browser (chrome) locally. Run `npm install` to download the correct Chromium revision (982053).**

/**

* this is the main configuration file of your bit workspace.
* for full documentation, please see: https://bit.dev/docs/workspace/workspace-configuration
 **/{
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  /**
* main configuration of the Bit workspace.
   **/
  "teambit.workspace/workspace": {
    /**
  * the name of the component workspace. used for development purposes.
     **/
    "name": "another-project",
    /**
  * set the icon to be shown on the Bit server.
     **/
    "icon": "https://static.bit.dev/bit-logo.svg",
    /**
  * default directory to place a component during `bit import` and `bit create`.
  * the following placeholders are available:
  * name - component name includes namespace, e.g. 'ui/button'.
  * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
  * scope - scope name only, e.g. 'compilation'.
  * owner - owner name in bit.dev, e.g. 'teambit'.
     **/
    "defaultDirectory": "{scope}/{name}",
    /**
  * default scope for all components in workspace.
     **/
    "defaultScope": "spakker.demo"
  },
  /**
* main configuration for component dependency resolution.
   **/
  "teambit.dependencies/dependency-resolver": {
    /**
  * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
     */
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@teambit/builder": "0.0.826",
        "@teambit/eslint-config-bit-react": "~0.0.367",
        "@typescript-eslint/eslint-plugin": "4.29.3",
        "eslint-import-resolver-node": "0.3.6",
        "eslint-plugin-import": "2.22.1",
        "eslint-plugin-jest": "24.4.0",
        "eslint-plugin-jsx-a11y": "6.4.1",
        "eslint-plugin-mdx": "1.15.0",
        "eslint-plugin-react": "7.25.1",
        "react-router-dom": "6.3.0"
      },
      "peerDependencies": {
        "@testing-library/react": "^12.0.0",
        "react": "17.0.2",
        "react-dom": "17.0.2"
      }
    },
    "linkCoreAspects": true
  },
  /**
* workspace variants allow to set different subsets of configuration for components in your
* workspace. this is extremely useful for upgrading, aligning and building components with a new
* set of dependencies. a rule can be a directory or a component-id/namespace, in which case,
* wrap the rule with curly brackets (e.g. `"{ui/*}": {}`)
* see https://bit.dev/docs/workspace/variants for more info.
   **/
  "teambit.workspace/variants": {},
  "spakker.demo/my-app": {}
}

### Specifications
* Bit version: 0.0.827
* Node version: 16.17
* npm / yarn version: 8.15.0
* Platform: Amazon Linux 2
* Bit compiler (include version): 0.1.10
* Bit tester (include version):

### Context and additional information
I am working on this example: https://www.youtube.com/watch?v=9vS86xgG3ak

**Comment by NitsanCohen770** [comment]
It seems that the prerender plugin is unable to render the routes you passed to it (since it is unable to load the headless browser)
Can you please copy the content of your my-app.react-app.ts file?
Also, try adding this line to your zshrc (or bash) file
export PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

See here:
https://stackoverflow.com/questions/57305779/pupeteer-how-to-specify-chromium-path-on-linux
