### ISSUE TITLE
Bit install is not a valid command 

### ISSUE THREAD

**Issue by staizen-jose-macalla** [teambit/bit#6364]
### Describe the bug
`bit install` is not a valid command
BVM version `0.0.829`
Using windows environment
VSCode latest version (as of today) (2022)

A clear and concise description of the issue.

### Steps to Reproduce
1. installed bvm thru  `npm i -g @teambit/bvm`
1. bvm was not found so i set the path `setx path "%path%;%AppData%\npm"`
1. set the path for global bit `setx path "%path%;%LocalAppData%\.bvm"`
1. set the DEFAULT_LINK for bvm config to `bbit`
1. then `bvm install`
1. then checked `bit --version` i get `v14.8.8`
1. when i do `bit install` it doesn't recognize it.

### Expected Behavior
`bit install` works

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/84562204/186837706-df5f6632-7b32-440d-92a1-d46e7b8f42de.png)

### Specifications
* Bit version: 14.8.8
* Workspace type: (harmony/legacy)
* Node version: v16.13.1
* npm / yarn version: v8.1.2
* Platform: Windows 10

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
1. You have the legacy version (14.8.8) installed, so the harmony version is probably under bbit command. Try bbit -v
2. Bit install is only valid within a bit workspace. Run bbit init first.

**Comment by staizen-jose-macalla** [comment]
thanks a lot! @GiladShoham you just saved my entire day, it works now.  appreciate the quick response.
have a nice day!
