### ISSUE TITLE
"Uncaught (in promise) ReferenceError: process is not defined" when running bit start

### ISSUE THREAD

**Issue by kimkwanka** [teambit/bit#6365]
### Describe the bug
When trying to follow the "Getting started" guide I encountered the following problem:
When opening `http://localhost:3000` in the browser after running `bit start` the page is blank as it errors out on `Uncaught (in promise) ReferenceError: process is not defined`.

The same thing also happens when running `bit start` in an existing project after initializing via `bit init `.

### Steps to Reproduce
1. Install bit via `npx @teambit/bvm install`
1. Run `bit new react tasks-workspace --default-scope my-org.tasks-scope`
1. cd `tasks-workspace`
1. `bit start`

### Expected Behavior
Seeing the workspace UI.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/13664983/186881565-a92249be-641c-4cd2-9a5e-29b5444ac251.png)
![image](https://user-images.githubusercontent.com/13664983/186881597-9e085644-0bfd-4678-8ec1-8d2c1495e264.png)
![image](https://user-images.githubusercontent.com/13664983/186881762-438a45ad-ed92-496e-bd1f-1867d1a122dc.png)

![image](https://user-images.githubusercontent.com/13664983/186880646-f23ce702-06ad-48cf-9884-4b577fc57e5b.png)

### Specifications
* Bit version: 0.0.829
* Workspace type: harmony(?)
* Node version: v16.13.2
* npm / yarn version: 8.3.1 / 1.22.19
* Platform: Apple M1 Pro MacOS Monterey 12.5.1

**Comment by speculees** [comment]
same issue

**Comment by adrianojdesouza** [comment]
Same here.

**Specifications**

- Bit version: 0.0.829
- Workspace type: nvm
- Node version: v18.8.0
- npm: 8.18.0
- Platform: Ubuntu 22.04

**Comment by GiladShoham** [comment]
It was a regression that should be fixed by the latest version.

**Comment by kimkwanka** [comment]
> It was a regression that should be fixed by the latest version.

Can confirm that it seems to be working now (Bit version: 0.0.831)
