### ISSUE TITLE
overview was not found

### ISSUE THREAD

**Issue by fakership** [teambit/bit#6377]
![image](https://user-images.githubusercontent.com/16553183/187371008-29a1dfa6-a79f-425c-8e23-9a250a2b7384.png)

### Description
there is an error in console, and the related docs can not disappear.

it just disappear in tsx component, not ts component

**Comment by fakership** [comment]
anyone help!

**Comment by GiladShoham** [comment]
Is this a public component? if yes can you please attach the url?
if no, can you please create a simple public component that reproduce the issue?
