### ISSUE TITLE
`bit rename` doesnt change the scope name

### ISSUE THREAD

**Issue by odedre** [teambit/bit#6388]
### Describe the bug
trying to change a local component's scope name

I forked a component, renamed its name, changed it's env and then renamed the scope. it stays on the original scope it was forked to. in this case `base-react`

### Steps to Reproduce
1. `bit fork teambit.base-ui/text/text-separator text/text-separator -s teambit.base-react`
1. `bit rename text/text-separator separators/text-separator`
1. `bit rename separators/text-separator separators/text-separator -s teambit.design`
1.  scope stays `base-react`

*see tar below.

[Uploading cant-rename.tar.gz…]()

### Expected Behavior
should change scope name

![Screen Shot 2022-09-01 at 14 43 57](https://user-images.githubusercontent.com/15064762/187906099-fa8630fa-1a83-4ce5-8148-09ed0e5c471d.png)

### Specifications
* Bit version: 0.0.831
* Workspace type: (harmony)
* Node version:
* npm / yarn version:
* Platform: macos

**Comment by davidfirst** [comment]
@odedre , thanks, it looks like a bug in the output. It should not allow it. To rename scope, use `bit scope` command.
In your case: `bit scope set teambit.design separators/text-separator`
