### ISSUE TITLE
Incorrect url when creating a Docs issue in this repo

### ISSUE THREAD

**Issue by rickykenny** [teambit/bit#6398]
When creating a "Docs Issue Report" in this repo, the report is prefilled with the following comment:

```
Please file any Docs issues at: https://github.com/teambit/bit-docs
```

This url returns a github 404 error. Perhaps it should be https://github.com/teambit/docs?

**Comment by GiladShoham** [comment]
@giteden please take care of this

**Comment by giteden** [comment]
@rickykenny thanks for letting us know. that's fixed now.
