### ISSUE TITLE
How to use bit in ci/cd

### ISSUE THREAD

**Issue by Khuzha** [teambit/bit#6426]
How can I login without using browser in UI?

Perfectly I'd define environment variables and use them for authentication, but didn't find anything about it in documentation

### Specifications
* Bit version: 0.0.824
* Platform: linux

**Comment by itaymendel** [comment]
Hi,

There are snippets on how to authenticate for you ci here.
https://bit.dev/docs/getting-started/collaborate/setup-ci#examples
use `bit config set user.token ...` from the env var.

**Comment by Khuzha** [comment]
@itaymendel thanks so much!
