### ISSUE TITLE
Is this project still going strong?

### ISSUE THREAD

**Issue by nolan-m** [teambit/bit#6445]
I see there has been recent activity such as PRs being merged, but the last release was over 2 years ago.  I'm curious why there hasn't been any new versions released if people are still working on this project and if this project is still recommended to use in production.

I followed the guide to setup a project, but ran into issues with the component preview.  The page showed "No Preview Found".  The tests didn't render in the tab either.  It didn't give me confidence to use this library for a new initiative.

**Comment by GiladShoham** [comment]
There is new release everyday. (At least. Sometime even more than one)
It is just not managed via github releases.

**Comment by GiladShoham** [comment]
Please refer to the docs
Https://bit.dev/docs for installation/getting started

**Comment by nolan-m** [comment]
@GiladShoham Do you have a link to the versions and release notes?  I could not find anything on this.  I will open a new ticket for my issues with getting started.
