### ISSUE TITLE
Component & docs preview doesn't work on Bit.cloud but works on local enviroment.

### ISSUE THREAD

**Issue by Zonalds** [teambit/bit#6453]
### Describe the bug
Preview & docs doesn't show on bit.cloud but shows on my local environment. I saw a similar closed bug report, but I am on latest version which seem to work the closed issue.

### Steps to Reproduce
1. Export  a test component from the docs

### Expected Behavior
Show exactly as in the development environment, including showing the docs.

### Screenshots, exceptions and logs
Dev: https://share.getcloudapp.com/p9uQG7lW
Bit.cloud: https://share.getcloudapp.com/4gue9y5q

### Specifications
  bit version   : 0.0.855
  node version  : v16.16.0
  npm version   : 8.11.0
  yarn version  : 1.22.17
  platform      : darwin

**Comment by MilesNorton** [comment]
Seems like the same issue here as well: https://github.com/teambit/bit/issues/6449

**Comment by GiladShoham** [comment]
The image for bit.cloud is not available anymore
can you also please attach the full component id / url of it in bit cloud?

**Comment by GiladShoham** [comment]
images are not working anymore.
Is this still relevant?
