### ISSUE TITLE
How to set TypeScript path aliases

### ISSUE THREAD

**Issue by hyoretsu** [teambit/bit#6454]
### Description
I'm trying to migrate my Next.js project to Bit, but it keeps nagging at my aliases for assets and styles. (which can't be in the same folder as components)

### Specifications
* Bit version: v0.0.819
* Node version: v16.16.0
* pnpm version: v7.11.0
* Platform: Linux

**Comment by hyoretsu** [comment]
Bump, these kinds of things should be documented. I really wanna use Bit to continue my personal project.

**Comment by itaymendel** [comment]
bit does not support ts path aliases, as this couples components to a specific worksapce structure.
