### ISSUE TITLE
How to inline .svg imports in components

### ISSUE THREAD

**Issue by hyoretsu** [teambit/bit#6484]
### Description
I like the idea of having a separate file for SVG because it remains editable and organizes things, assets don't get mixed with code.

### Specifications
* Bit version: v0.0.819
* Node version: v16.16.0
* pnpm version: v7.11.0
* Platform: Linux

**Comment by NitsanCohen770** [comment]
You can use SVG imports in components that use the new env. It is supported out of the box.
