### ISSUE TITLE
Properties section does not appear when using JSDoc

### ISSUE THREAD

**Issue by leosdad** [teambit/bit#6487]
### Describe the bug
When using JSDoc comments do describe a composition, the corresponding Properties section (and the Properties sub-tab in the Compositions tab) does not appear.

### Steps to Reproduce
1. Create a component.
1. Create a JSDoc description anywhere in the composition file.
1. The corresponding Properties section is not generated.

### Expected Behavior
The corresponding Properties section should be generated.

### Screenshots, exceptions and logs
I expect to see something like this:

https://user-images.githubusercontent.com/27972790/145064139-e6f38d0d-b2c4-455e-bf05-8e5397c9d659.png

(example taken from [a similar bug](https://github.com/teambit/bit/issues/5128))

### Specifications
* Bit version: 0.0.864
* Workspace type: harmony
* Node version: 16.16.0
* npm / yarn version: 1.22.19
* Platform: Windows

**Comment by GiladShoham** [comment]
We are working right now to re-build this entire feature from scratch with many more capabilities.

**Comment by leosdad** [comment]
Great news, I look forward to it.

**Comment by itaymendel** [comment]
new api-ref tab is available
