### ISSUE TITLE
Bit install is not updating packages to the version referenced in the workspace

### ISSUE THREAD

**Issue by johnjspiteri** [teambit/bit#6492]
Bit install is not updating a package ("@interface-agency/product-automotive-used-car-dealer.store.about": "0.0.7") to the version referenced in the workspace, it is stuck on version 0.0.6. 

This is an Angular package where all the dependencies are "peerDependencies".

### Steps to Reproduce
1. Clone repository "https://github.com/interface-agency/product-automotive-used-car-dealer-components-class-about"
1. Run "yarn cache clean"
1. Run "bit capsule delete --all && rm -rf node_modules/ yarn.lock .yarn && bit clear-cache && bit install -u"

### Expected Behavior
The "@interface-agency/product-automotive-used-car-dealer.store.about" package will update to version 0.0.7.

### Specifications
* Bit version: 0.0.859
* Workspace type: Harmony
* Node version: 16.10.0
* npm / yarn version: 1.22.17
* Platform: MacOS 11.6

_for harmony workspace_

* relevant env: 
* relevant aspects: "teambit.angular/angular@1.2.8"

**Comment by sbland** [comment]
Have you tried running `bit install -u <package_name` .

**Comment by johnjspiteri** [comment]
I have tried running `bit install -u @interface-agency/product-automotive-used-car-dealer.store.about`, and the version is still stuck at "0.0.6".

When running `bit install -u @interface-agency/product-automotive-used-car-dealer.store.about@0.0.7`, the version does get updated and a "dependencies" entry in workspace.jsonc gets added.

If I remove the "dependencies" entry for `@interface-agency/product-automotive-used-car-dealer.store.about` (leaving the "peerDependencies" entry at "0.0.7"), and run `bit install` or `bit install -u`, the version reverts to "0.0.6".

**Comment by sbland** [comment]
In my setup I can only update the version of a package by specifying the exact version number in the workspace.json file.

The following does not work (Assuming updating from version `0.0.1` to `0.0.2`
- In `workspace.json` set `"dependencies: {"package_name": "^0.0.1"...`
- In `workspace.json` set `"dependencies: {"package_name": "*"...`
- Run `bit install -u package_name` with either workspace setup
- Run `bit install -u package_name@0.0.2` with either workspace setup

The only thing that works is In `workspace.json` set `"dependencies: {"package_name": "^0.0.2"...` then run `bit install -u package_name`

**Comment by sbland** [comment]
I'm not sure how I had not come across it before but `bit update` provides a useful interactive update cli. This mostly solves my issue.
