### ISSUE TITLE
SolidJS Support

### ISSUE THREAD

**Issue by MatthewCushing** [teambit/bit#6518]
### Description
Support for the SolidJS framework

### Describe the solution you'd like
I came across Bit.dev recently thinking it was just a monorepo tool only to find out how incredible this tool really is. I leaped into it and was extremely stoked to adopt it as a standard, especially when I saw its claim to be platform and language agnostic while only currently supporting TypeScript. My current client has a NestJS backend but I’m working with SolidJS on the frontend, so I was a bit disappointed to find out that it was limited by the frameworks. My argument for jumping in to support SolidJS is that you already have support for React and SolidJS uses JSX as its primary language. Second, the library doesn't have near the complexity as a framework like React or Vue while also having a lot of media attention right now and is on the cusp of some major growth with the completion of their solid-start repo which is the equivalent of NextJS and Remix based off the SolidJS framework. I’m ignorant on how this all works, so I may be wrong in assuming that SolidJS would be an easy framework to support as I’ve heard that they compile their JSX differently. Either way, you all have done some incredible work and have a great and unique idea. I hope it goes far.

### Describe alternatives you've considered
Looked more into envs as I thought it was only a template I needed to make in order to support the framework until I saw there was a Bit.dev React module being imported and would take quite a bit more effort to implement support myself and I’ve unfortunately got a deadline I have to meet that I can’t sidetrack that far. Definitely something that I'm interested in contributing to once I finish this contract with my client.

### Additional context
Add SolidJS support and then contact their devs to get your library added to their website on the ecosystem page.

**Comment by itaymendel** [comment]
hi @MatthewCushing , we have recently updated the entire system for building envs.
i recommend you look into the implementation of Lit or Stencil to learn more https://bit.cloud/teambit/web-components/lit https://bit.cloud/teambit/web-components/stancil

for now we don't know if we'll build support for SolidJS ourselves. if you are looking to maintain such env, please let us know and we can assist you in your efforts.

**Comment by NitsanCohen770** [comment]
Should be fairly easy to implement by extending the [new react env](https://bit.cloud/teambit/react/react-env) and using a package such as this:
https://github.com/Sawtaytoes/reactjs-solidjs-bridge
