### ISSUE TITLE
how to add a login screen in self hosted instance of bit

### ISSUE THREAD

**Issue by hamza-maqsood** [teambit/bit#6529]
### Description
I've a self hosted instance of bit and is hosted on Cloud Run for Anthos. Now anyone with the url can access the dashboard. There's no security.

So what I need to is to have a login screen which would only authorized users to access the dashboard.

### Specifications
using the latest bit docker image from docker hub.

**Comment by Java-http** [comment]
I have this problem too, do you have a solution?

**Comment by hamza-maqsood** [comment]
no, we ditched bit for this very reason

**Comment by itaymendel** [comment]
hi, you will need to wrap bit with yoru own custom ui/server.
