### ISSUE TITLE
Example component doesn't show live preview or tests

### ISSUE THREAD

**Issue by BCerki** [teambit/bit#6536]
### Describe the bug
When working through the tutorials in the docs, live preview is not available after creating the example component.

### Steps to Reproduce
1. Install bit: https://bit.dev/docs/getting-started/installing-bit/installing-bit
1. Initialize a workspace and start a new project: https://bit.dev/docs/getting-started/installing-bit/start-bit-workspace?new_existing_project=0
1. Create the example to-do component: https://bit.dev/docs/getting-started/composing/creating-components
1. Attempt to view the workspace on `http://localhost:3000/`. No live preview is available.

### Expected Behavior
I expect `http://localhost:3000/` to show the live preview and tests.

### Screenshots, exceptions and logs
https://www.loom.com/share/8da558646992497bb9ab323047ea3b2f

### Specifications
* Bit version: 0.0.867
* Workspace type: (harmony/legacy) whatever the docs say
* Node version: v14.17.6
* npm / yarn version: 1.22.10
* Platform: Pop OS

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
@giteden please validate this tutorial

**Comment by josh-kiwi** [comment]
Bumping this as I am having the same issue with a new installation of Bit where live preview is showing up blank for any new component I create.

**Comment by wkylin** [comment]
try cli :  bit link bit copile bit install

**Comment by alissa-asimov** [comment]
> try cli : bit link bit copile bit install

fixed a typo: bit link bit compile bit install

**Comment by raffidahmad** [comment]
same issue
