### ISSUE TITLE
teambit.pkg/pkg homepage 404

### ISSUE THREAD

**Issue by wkylin** [teambit/bit#6592]
### Description
teambit.pkg/pkg set "homepage": "http://localhost:3000/{name}" 
 http://localhost:3000/bit-com.say-hello   404

hosting server 
http://localhost:3000/bit-com/say-hello

### Specifications
* Bit version:
* Node version:
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by wkylin** [comment]
NPM: https://www.npmjs.com/package/@wbit/apps.ui.to-do

Npm Homehage: https://bit.cloud/wbit/wui/apps.ui.to-do

bit component name:  apps.ui.to-do
Bit cloud: https://bit.cloud/wbit/wui/apps/ui/to-do

**Comment by wkylin** [comment]
bit link  nodel_moudle package.json homepage  domain https://bit.dev/   
How do I customize a domain name?

**Comment by itaymendel** [comment]
new envs provide an api to control package.json for components.
