### ISSUE TITLE
TypeError: Reflect.metadata is not a function

### ISSUE THREAD

**Issue by aidan-casey** [teambit/bit#6599]
### Describe the bug
On a brand new install of the Lit workspace tests fail when adding TypeScript typings to a property.

### Steps to Reproduce
1. Run `bit new lit my-lit-workspace --aspect teambit.web-components/lit && cd my-lit-workspace && bit install` 
1. Run `bit create lit a-button`.
1. In `scope/a-button/a-button.tsx` update `name = "Somebody";` to `name: String = "Somebody";`
1. Run `bit test`.

### Expected Behavior
Tests should run successfully.

### Specifications
* Bit version: 0.0.867
* Workspace type: harmony
* Node version: v16.18.0
* npm / yarn version: v8.19.2
* Platform: M1 Mac (Ventura)

### Additional context
Running `bit install reflect-metadata` and then adding `import "reflect-metadata";` to the top of the specification file does resolve the issue. Obviously this is not a permanent fix as it is a dev dependency. Seems like perhaps the Lit workspace is not importing it correctly during testing?

**Comment by itaymendel** [comment]
lit has been re-implemented.
please upgrade to latest version.
