### ISSUE TITLE
error: remote scope protocol is not supported, please use: `ssh://`, `file://` or `bit://`

### ISSUE THREAD

**Issue by Seventysevendays** [teambit/bit#6614]
### Describe the bug
bit remote add http://127.0.0.1:80, got error: remote scope protocol is not supported, please use: `ssh://`, `file://` or `bit://`

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version:14.8.8
* Workspace type: (harmony/legacy)
* Node version: 16.16.0
* npm / yarn version:8.11.0

**Comment by altovoy-hellobuild** [comment]
Hello @Seventysevendays 
How did you manage to solve the problem?
I have the same problem and I have not been able to do it
