### ISSUE TITLE
warning: 'new' is not a valid command.

### ISSUE THREAD

**Issue by Seventysevendays** [teambit/bit#6615]
bit new react tasks-workspace --default-scope log warning: 'new' is not a valid command.

### Specifications
* Bit version: 14.8.8
* Node version: 16.16.0
* npm / yarn version:8.11.0

**Comment by daijinru** [comment]
how to solve this problem?

**Comment by fateeand** [comment]
Same issue. Why is no one responding?
You specify this command everywhere in the manuals, even though it does not exist.

warning: 'update' is not a valid command.
see 'bit --help' for additional information

usage: bit [--version] [--help] <command> [<args>] 
 bit documentation: https://docs.bit.dev
start a working area
  init               Create or reinitialize an empty Bit scope or reinitialize an existing one

Develop components
  tag                Record component changes and lock versions.
  status             Show the working area component(s) status.
  add                Add any subset of files to be tracked as a component(s).
  untrack            Untrack a new component(s).
  untag              Revert versions tagged for component(s).
  move               Move a component to a different filesystem path.
  checkout           Switch between component versions.
  merge              Merge changes of different component versions.
  diff               Show diff between components files.

Collaborate on components
  import             import components into your current working area.
  export             export components to a remote scope.
  remote             Manage set of tracked bit scope(s).
  link               Generate symlinks for imported components absolute path resolution.
  remove             Remove component(s) from your working area, or a remote scope.
  deprecate          Deprecate a component
  undeprecate        Undeprecate a deprecated component
  eject              Replaces the components from the local scope with the corresponding packages.
  pack               Create tar for npm publish

Explore components
  list               list components on a local or a remote scope.
  graph              EXPERIMENTAL. generate an image file with the dependencies graph.

Workspace commands
  config             global config management
  clear-cache        clears Bit's cache from current working machine
  scope-config       local scope config management
  login              log the CLI into bit.dev
  logout             log the CLI out of bit.dev
  doctor             diagnose a bit workspace

View components
  show               show component overview.
  log                show components(s) version history.

component environment operations
  test               test any set of components with configured tester (component tester or as defined in bit.json)
  build              build any set of components with configured compiler (component compiler or as defined in bit.json)
  watch              watch a set of components

**Comment by clarastar** [comment]
how to solve this problem?

**Comment by clarastar** [comment]
@Seventysevendays did you solve the problem?
