### ISSUE TITLE
can I disabled code preview in host scope?

### ISSUE THREAD

**Issue by Seventysevendays** [teambit/bit#6622]
### Description
![image](https://user-images.githubusercontent.com/37206679/199144982-9ce3022d-5fec-4dcf-9a6e-737c3015d56c.png)

### Specifications
* Bit version: 14.8.8
* Node version: 16.16.0
* npm / yarn version:
* Platform:
* Bit compiler (include version):
* Bit tester (include version):

**Comment by itaymendel** [comment]
component code is critical for understanding on how to use components.
also, code is available as part of component, so even if not visible, consumers can get it by running `bit import`.
