### ISSUE TITLE
bit start error 

### ISSUE THREAD

**Issue by Seventysevendays** [teambit/bit#6626]
my remote hosting scope is a self scope, location start with  'http'，
when I bit start local to preview, bit request this

const graphQlUrl = `https://${symphonyUrl}/graphql`;

by default to https://symphony.bit.cloud, of cause got NOTFOUND  error
I can bit set CFG_SYMPHONY_URL_KEY to change it alias to my self-scope, but I cant set 'https' to 'http' , so I still cant bit start normally, what can I do to fix this 

### Specifications
* Bit version: 0.0.867
* Node version: 16.16.0
* npm / yarn version: 8.11.0

**Comment by GiladShoham** [comment]
did you configure your hosted scope via `bit remote add` command?
I don't think you should get into this code for a self-hosted scope. right @davidfirst ?

**Comment by Seventysevendays** [comment]
> did you configure your hosted scope via `bit remote add` command? I don't think you should get into this code for a self-hosted scope. right @davidfirst ?

yes, I did add remote add , it works,  I can export component to self-scoped remote, but when I run 'bit start' locally for a preview overview , log:

getScope has failed
    message: "request to https://symphony.bit.cloud/graphql failed, reason: getaddrinfo ENOTFOUND symphony.bit.cloud"
    type: "system"
    errno: "ENOTFOUND"
    code: "ENOTFOUND"
    stack: "FetchError: request to https://symphony.bit.cloud/graphql failed, reason: getaddrinfo ENOTFOUND symphony.bit.cloud\n    at ClientRequest.<anonymous> (/Users/xuxiang/.bvm/versions/0.0.867/bit-0.0.867/node_modules/node-fetch/lib/index.js:1491:11)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:539:35)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
getScope has failed
    message: "request to https://symphony.bit.cloud/graphql failed, reason: getaddrinfo ENOTFOUND symphony.bit.cloud"
    type: "system"
    errno: "ENOTFOUND"
    code: "ENOTFOUND"
    stack: "FetchError: request to https://symphony.bit.cloud/graphql failed, reason: getaddrinfo ENOTFOUND symphony.bit.cloud\n    at ClientRequest.<anonymous> (/Users/xuxiang/.bvm/versions/0.0.867/bit-0.0.867/node_modules/node-fetch/lib/index.js:1491:11)\n    at ClientRequest.emit (node:events:527:28)\n    at TLSSocket.socketErrorListener (node:_http_client:454:9)\n    at TLSSocket.emit (node:events:539:35)\n    at emitErrorNT (node:internal/streams/destroy:157:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
teambit.harmony/graphql, graphql got an error during running the following query:
    query: "query workspace {\n  workspace {\n    name\n    path\n    icon\n    components {\n      ...wcComponentFields\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment wcComponentFields on Component {\n  id {\n    name\n    version\n    scope\n    __typename\n  }\n  compositions {\n    identifier\n    __typename\n  }\n  description\n  issuesCount\n  status {\n    isOutdated\n    isNew\n    isInScope\n    isStaged\n    modifyInfo {\n      hasModifiedFiles\n      hasModifiedDependencies\n      __typename\n    }\n    isDeleted\n    __typename\n  }\n  preview {\n    isScaling\n    __typename\n  }\n  deprecation {\n    isDeprecate\n    newId\n    __typename\n  }\n  server {\n    env\n    url\n    __typename\n  }\n  env {\n    id\n    icon\n    __typename\n  }\n  __typename\n}\n"
    variables: {}
    operationName: "workspace"
    raw: false

**Comment by GiladShoham** [comment]
can you please attach your debug.log?
