### ISSUE TITLE
Is it possible for self-managed bit to customize the UI

### ISSUE THREAD

**Issue by quguoliang** [teambit/bit#6635]
### Description
I want to adjust the bit UI hosted by the team and ask how to do it. Hope to get your help.

### Specifications
* Bit version:  0.0867
* Node version: 16.18.0
* npm / yarn version: 8.19.2
* Platform:  Lix
* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
Everything you see in the ui in a self hosted is open source. So you can customize everything.
There are parts which are easier to customize as we already made APIs to customize them easily.
Soon it will be even easier.

**Comment by quguoliang** [comment]
Thank you for your reply，But I don't seem to find relevant content in the documentation. Is it implemented through aspects?

**Comment by NitsanCohen770** [comment]
This should be a good starting point for you to extend Bit:
https://bit.dev/reference/extending-bit/aspect-overview/
