### ISSUE TITLE
bit watch is not available

### ISSUE THREAD

**Issue by prceasar** [teambit/bit#6645]
### Describe the bug

I am trying to compile bit components in watch mode.

### Steps to Reproduce

1. run. `bit watch`
2. See the following output:

```shell
warning: 'watch' is not a valid command.
see 'bit help' for additional information
```

### Expected Behavior

I expect this command to work, as I have seen it mentioned in issues and discussions

### Screenshots, exceptions and logs

n/a

### Specifications

- Bit version: 0.0.888
- Workspace type: harmony
- Node version: 16.16.0
- npm / yarn version: yarn 1.22.19
- Platform: mac OS Intel

*for harmony workspace*
- relevant env: react
- relevant aspects: ?

### Additional context

I have tried using bvm to switch to an older version of bit  (0.0.867) and had the same issue

**Comment by GiladShoham** [comment]
maybe you have the legacy version installed as well?
or maybe you were outside of a workspace?

**Comment by prceasar** [comment]
@GiladShoham Yes, you are correct, I had opened a new terminal window and was running it from a different directory than the one my workspace was in. Thanks!

**Comment by GiladShoham** [comment]
@davidfirst  we need to show the normal not in a workspace error
