### ISSUE TITLE
invalid json response body at xxx reason: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by wkylin** [teambit/bit#6653]
### Describe the bug

A clear and concise description of the issue.
invalid json response body at xxx reason: Unexpected token < in JSON at position 0
### Steps to Reproduce

1.
1.
1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Workspace type: (harmony/legacy)
- Node version:
- npm / yarn version:
- Platform:

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by benjgil** [comment]
hi @wkylin 
Please add some more details to the bug report - commands you've run, expected output and actual output, bit version etc.

Without those details we'll have to close this issue

**Comment by itaymendel** [comment]
closing the issue as there's no way to reproduce and author abandoned it.
