### ISSUE TITLE
Support for Svelte/SvelteKit

### ISSUE THREAD

**Issue by bitcrshr** [teambit/bit#6664]
### Description
Our company uses SvelteKit for our web development, and we have a great interest in using Bit. As SvelteKit approaches a stable 1.0 release, and given its popularity already, I think it would be an amazing addition.

### Describe the solution you'd like
Any support at all for using Bit with SvelteKit would be awesome. I am aware that there are guides floating around for how to create your own compiler to get Svelte components into Bit, but something 1st-party would be ideal (even if that means just writing your own guide for this without offering full-fledged support).

### Describe alternatives you've considered
Writing a custom compiler does seem tempting, but for large, complicated projects, it seems far preferable to have official guidance from the Bit team.

**Comment by Visual-Dawg** [comment]
Just dropping in here to show my support for this feature

**Comment by jorcail** [comment]
Yep, it would be a very nice feature!

**Comment by benjgil** [comment]
Hi All, 
Just to note we're building svelte support right now (in fact there's a teambit.svelte/svelte env you can already use, we just haven't had the chance to document svelte with bit so it's not published yet).

Coming very soon...

**Comment by Lucasmiguelmac** [comment]
Couldn't quite grasp how to use the "teambit.svelte/svelte" env @benjgil is mentioning. Would love to know more if possible

**Comment by itaymendel** [comment]
https://bit.cloud/bitdev/svelte

**Comment by christophsturm** [comment]
so what happened to svelte support? the mentioned link is dead and the docs also do not mention svelte.

**Comment by sdserage** [comment]
This was closed last year but it doesn't look like it was actually resolved.

**Comment by mmailaender** [comment]
It's now available here https://bit.cloud/frontend/svelte

I hope it will also appear soon in the docs, because they bypassed already Svelte component version 1.0.0

**Comment by kristianmandrup** [comment]
@mmailaender Do you know if it also works with SvelteKit? I would think so, as SvelteKit is just a full-stack wrapper around Svelte.
