### ISSUE TITLE
bit.cloud react-native compnent compositions "Failed to render"

### ISSUE THREAD

**Issue by Akronae** [teambit/bit#6670]
### Describe the bug
My very simple react-native component does not render on bit.cloud, it shows "Failed to render".

### Steps to Reproduce
1. Go there https://bit.cloud/akronae/syn/text

### Expected Behavior
The component to render correctly

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/17302866/202273596-97a17e38-dc4a-487c-9193-6acc14c8ec53.png)

### Specifications
* Bit version: 0.0.888
* Workspace type: harmony
* Node version: 16.17.1
* pnpm version: 7.16.0
* Platform: Ubuntu

**Comment by gosone** [comment]
I met the same problem.  When I run the project in local, it's fine. But after I export my component and go https://tife-bit.bytedance.net/tr-component/help-icon, it failed to render.

**Comment by gosone** [comment]
> ### Describe the bug
> My very simple react-native component does not render on bit.cloud, it shows "Failed to render".
> 
> ### Steps to Reproduce
> 1. Go there https://bit.cloud/akronae/syn/text
> 
> ### Expected Behavior
> The component to render correctly
> 
> ### Screenshots, exceptions and logs
> ![image](https://user-images.githubusercontent.com/17302866/202273596-97a17e38-dc4a-487c-9193-6acc14c8ec53.png)
> 
> ### Specifications
> * Bit version: 0.0.888
> * Workspace type: harmony
> * Node version: 16.17.1
> * pnpm version: 7.16.0
> * Platform: Ubuntu

Hi, I met the same problem. Did you solve it?

**Comment by Akronae** [comment]
@gosone no it was too buggy for my usage, I ended up using Git subtrees

**Comment by itaymendel** [comment]
react-native plugin for bit has been completely refactored. new version and docs are available singe mid May-2023.
this solves the issue outlined in this topic
