### ISSUE TITLE
antd 5.0.0 bit tag error

### ISSUE THREAD

**Issue by wkylin** [teambit/bit#6689]
### Describe the bug
/Users/administrator/Library/Caches/Bit/capsules/11eb3de932db4f600ca4d7d954f7065edc1720cf/node_modules/.pnpm/antd@5.0.0_sfoxds7t5ydpegc3knd667wn6m/node_modules/antd/es/form/index.d.ts:5:21 - error TS1005: ',' expected.

5 import Item, { type FormItemProps } from './FormItem';

### Steps to Reproduce
1. bit install antd 5.0.0
1. bit tag --message 'antd 5.0.0'
error:
/Users/administrator/Library/Caches/Bit/capsules/11eb3de932db4f600ca4d7d954f7065edc1720cf/node_modules/.pnpm/antd@5.0.0_sfoxds7t5ydpegc3knd667wn6m/node_modules/antd/es/form/index.d.ts:5:21 - error TS1005: ',' expected.

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version:
* Workspace type: (harmony/legacy)
* Node version:
* npm / yarn version:
* Platform:

_for harmony workspace_

* relevant env
* relevant aspects

_for leagacy_

* Bit compiler (include version):
* Bit tester (include version):

**Comment by lamvananh** [comment]
same issue :(

**Comment by benjgil** [comment]
Hi @wkylin 
Can you be more specific about your setup?
What framework and version are you using? react? version?

This looks like an issue with typescript version (the `export {type someType}` syntax with type inside the brackets is relatively new) so you may just need a custom antd-compatible bit env with typescript version overriden.

We're about to release an entirely new API for customising env's, including an easy way to select your ts version, but for now the way to do this would be to make sure you have the version of ts you want to use installed in your worksapce, then fork [this env ](https://bit.cloud/learnbit-react/envs/react-with-diff-ts-ver/) (or extract the ts override lines from the .env.ts and main.runtime files) and then use this as the env for components using antd

**Comment by lamvananh** [comment]
i have used custom env like your guideline and the error gone away.
 But when i run build my app by command 
`bit build my-react-app`, the error still appear.
Is there any place that i need  add config to build my app success?

**Comment by wkylin** [comment]
update "antd": "5.1.2",  "typescript": "4.9.4", bit: "0.0.945"

**Comment by benjgil** [comment]
I'm not sure what that update is - with those values this now works?

**Comment by itaymendel** [comment]
closing the issue, not answer from the folks who requested it.
