### ISSUE TITLE
Allow importing list of components

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#67]
if i want to import a list of component, i should be able to do it in a single command.
for example: `bit import <compo_id> <comp_id>`

**Comment by ran-y** [comment]
<img width="724" alt="screen shot 2017-03-13 at 17 52 59" src="https://cloud.githubusercontent.com/assets/11733036/23862540/ee6018ba-0815-11e7-9d64-8c0f32bcf2c8.png">

Fixed on version [0.2.3](https://github.com/teambit/bit/blob/master/CHANGELOG.md#023)
