### ISSUE TITLE
`bit export` Forbidden error on bit.cloud

### ISSUE THREAD

**Issue by elliottye** [teambit/bit#6700]
### Description

I have a remote scope on bit.cloud and created an organization. And I invited 3 coworkers in my company to collaborate. They're all under the "Member" category while I am "Admin". So one of my collaborator can `bit login` and `bit import` but he can't `bit export` after successfully tagging the components. Bit keeps returning with the `unexpected network error has occurred.
server responded with: "Forbidden: <my_scope>`.  Is there anything else we should do to make it work? Thanks.

### Specifications

- Bit version: 0.0.859
- Node version: 19.0.1
- npm / yarn version: 8.19.2
- Platform: Mac OS

**Comment by benjgil** [comment]
Hi @elliottye 
In order to export you need to either be `developer` level on the scope itself, or be an org-level admin.
So `members` that haven't been upgraded to `developer` wont have the required permissions

**Comment by elliottye** [comment]
Hi @benjgil
There's no option of `developer` in the Settings page, only `Member` and `Billing Manager`. Is this due to that we're still on a free plan? What can I do to have developers in our organization? Thanks.

**Comment by benjgil** [comment]
Hi @elliottye 
You're looking at the org-level settings page. 
On each scope there's a settings page as well (visible only to admins of the scope or org-level admins) where you can set permissions level for the scopes themselves

**Comment by elliottye** [comment]
Hi @benjgil It works. Thanks for the support!
