### ISSUE TITLE
Can not use Bit with react 18

### ISSUE THREAD

**Issue by DimaTrollFace** [teambit/bit#6731]
### Description

Hi. I have an application written on react 18.
Each time I run `bit install` I have the react 17 in my **node_modules**

### Expected Behavior

I expect to have the react 18 in my **node_modules**

### Specifications

- Bit version: `0.0.888`
- Workspace type: harmony
- Node version: `16.15.1`
- npm / yarn version: `1.22.19`
- Platform: Mac OS

<img width="794" alt="image" src="https://user-images.githubusercontent.com/36362418/205111647-addfa913-a5fd-413d-8b08-3e9592e35371.png">

**Comment by benjgil** [comment]
Hi there,
Please delete your lock file and try again. 
You are also likely using our react17 base react env (or composing on top of it) which sets react17 as a dependency for components - this will also be taken into account when bit resolves the final version to install.
We are soon going to be supplying a proper react18 env, but for now you can try this one, which only overrides dependencies:
https://bit.cloud/bit-foundations/react/react-version-envs/react-18-env

**Comment by YacheLee** [comment]
@benjgil Any update here?

**Comment by YacheLee** [comment]
```
"peerDependencies": {
    "react-dom": "^16.8.0 || ^17.0.0",
    "react": "^16.8.0 || ^17.0.0"
  },
```
Could it be set to 18 version by default?

**Comment by DimaTrollFace** [comment]
> Hi there, Please delete your lock file and try again. You are also likely using our react17 base react env (or composing on top of it) which sets react17 as a dependency for components - this will also be taken into account when bit resolves the final version to install. We are soon going to be supplying a proper react18 env, but for now you can try this one, which only overrides dependencies: https://bit.cloud/bit-foundations/react/react-version-envs/react-18-env

You are right. It works. Thanks!
