### ISSUE TITLE
Support for other non-web related languages

### ISSUE THREAD

**Issue by ganson2021** [teambit/bit#6737]
### Description
This Bit thing is all find an dandy for web-based development however it would be great if it could be used with other development environments

### Describe the solution you'd like
Support C, C++, Rust, Go, Python, and other languages

### Describe alternatives you've considered
None

**Comment by benjgil** [comment]
In it's core bit is designed to be language agnostic - as in, bit could have support for any language added to it.
But for now it only supports web-related languages as there is still work to do to provide the ultimate (and we mean ultimate) componentisation development experience and feature set. 

Once that's delivered, bit will likely branch out, but that's unlikely to be before 12-18 months' time
