### ISSUE TITLE
How can I migrate all components from A scope to B scope

### ISSUE THREAD

**Issue by front-end-captain** [teambit/bit#6743]

**Comment by benjgil** [comment]
Hi there
I'm afraid you cant just 'move' components between scopes, as the scope is part of the component's id. So moving scope is essentially creating a new component.

You have a few options if you want to port over components from one scope to another. 
1) You can fork the components over - which will create a new component, with some data on where it was forked from.
`bit fork <old-component-with-scope> <new-forked-component-name-without-scope> --scope <org.new-scope-name>`
e.g. `bit fork my-org.my-scope/ui/button ui/button --scope my-org.new-scope`
This will leave the existing component as it is - you can then run `bit delete` on the old component once you're sure the new one looks as it should.

Or you can rename the existing components:
`bit rename <old-component-no-scope> <new-forked-component-no-scope> --scope <org.new-scope-name>`
This will also **deprecate** the old component, so it doesnt appear by default on remote scopes. NOTE: this deprecation is done locally, and you'll then need to export the 'deprecation' by tagging and exporting the old component before the deprecate will take hold.

Unfortunately these commands can only currently be run on a single component at a time, so you will need to port them over one-by-one
