### ISSUE TITLE
create a workspace starter

### ISSUE THREAD

**Issue by bumi001** [teambit/bit#6744]
Hi, the following command from https://bit.dev/reference/starters/create-starter:

$ bit create workspace-generator my-workspace

produces this output

workspace not found. to initiate a new workspace, please use `bit init`

I am guessing it is not finding workspace-generator. bit init doesn't produce the same set of files shown in the above web page. I am not sure how to resolve this?

**Comment by GiladShoham** [comment]
the template of workspace-generator is a component template so you need to run it inside a workspace.
you should create an empty folder, run `bit init` then use the `bit create workspace-generator <generator-name>`
then for testing it you can go to another empty folder and run `bit new --load-from <first-workspace-path> --aspect <generator-component-id>`
