### ISSUE TITLE
Unable to install private NPM package

### ISSUE THREAD

**Issue by jonasivy** [teambit/bit#6764]
### Describe the bug
Unable to install private NPM package although I have the correct auth at .npmrc

### Steps to Reproduce
1. Create a private npm package registered to https://registry.npmjs.org/
2. npm login, input credentials.
3. bit install @organization/package

### Expected Behavior
Should be able to install the package since it's working when trying to install npm and yarn.

### Screenshots, exceptions and logs
I also tried using yarn install to add the package just to check if I have the right access and it works.
![image](https://user-images.githubusercontent.com/11424530/206141653-0216fa37-bbbd-4190-9d96-51c1b17e0b5d.png)

Here's the screenshot of the error encountering when installing.
![image](https://user-images.githubusercontent.com/11424530/206141698-5d8f373e-8559-4b4c-b657-1c36df172142.png)

### Specifications

- Bit version: 0.0.888
- Workspace type: (harmony/legacy)
- Node version: v16.16.0
- npm / yarn version: 8.11.0 / 1.22.19

**Comment by chungweileong94** [comment]
@GiladShoham Was trying out bit.dev today, and I happen to hit this issue. I tried to follow the step from the [doc](https://bit.dev/docs/components/installing-components). Basically what I did was:

1.  `bit login`
2. Add my own organization registry to `.npmrc`
3. Then try to install the component

**Comment by jonasivy** [comment]
Will be closing this issue here, this issue is due to a conflict of organization and was advise to rename either of the two to avoid conflict of registry.

**Comment by chungweileong94** [comment]
@benjgil 
Hmm, for some reason if I try to use `@cw` instead of `@bit` it always says that the package is not found, even though I already set the scope in `.npmrc`. Am I missing something?

**Comment by chungweileong94** [comment]
@benjgil So I was creating the scope under personal (not team), and it adds the `@cw` as my organization for whatever reason.
However, it I create a team and create a scope within the team, it works as expected.
