### ISSUE TITLE
type and description for component variables in jsx

### ISSUE THREAD

**Issue by miladaghamohamadnia** [teambit/bit#6768]
I am using create a new bit with react-js option which creates a jsx workspace rather than the default typescript. after running the bit start command an looking at the preview page, all the variable types are set as '?' and their descriptions are missing. I understand thats what comes with typescript but how can we still be able to set the type and description of component's props with JSX?

**Comment by itaymendel** [comment]
Bit uses `react-docgen` for that feature (https://github.com/reactjs/react-docgen). So whatever passes it will work.
I think you just need to add js-docs annotations over your prop-types and that's it.

However, i'd urge you to use ts for your components. Bit adds a lot of automations over components docs and other features, when using ts (as with js they are impossible).
