### ISSUE TITLE
Cannot `bit install/update/status/clear-cache/-h...` due to component not found error

### ISSUE THREAD

**Issue by sqwxl** [teambit/bit#6770]
### Description

I was having a strange issue with bit refusing to run `install` or `update` because it was searching for a local `@myscope` component on npm registry and not finding anything. I couldn't figure out why it was trying to search there anyway, but I wasn't having any success. Frustrated, I ended up commiting all my changes (to git) and re-cloning everything fresh. In hindsight, I should have cloned somewhere else and kept a copy of the broken repo because the now things are even worse.

I no longer see any error related to npm registries, rather nearly all `bit` commands fail with the same error. e.g.:

```
> bit install
  Resolving component dependencies for workspace: 'my-workspace'
error: component "my-scope/path/to/a/component@0.0.3" was not found
```

I've tried all sorts of things from all manner of `bit checkout` variations to fiddling with version numbers in `.bitmap`, to `bit remove --keep-files` on the problem components. Nothing has worked so far.

### Specifications
* Bit version: 0.0.888
* Node version: 18.12.0
* npm version: 8.19.2
* Platform: Ubuntu 22.04.1 LTS (WSL2)
* Bit compiler (include version): ?
* Bit tester (include version): ?

### Context and additional information
I can change to my repo's main branch and `bit checkout reset --all` to recover a workable environment, but I would like to recover the work done in my feature branch...

**Comment by southerncross** [comment]
I met a similar "Component not found" problem, after debugging for some time, I found that bit thrown the error when it tried to import local component:

![image](https://user-images.githubusercontent.com/3861465/221093437-d5d31f5f-666a-4021-a7a3-7df0819f07af.png)

bit could not find local component:
![image](https://user-images.githubusercontent.com/3861465/221093634-14704211-dad4-4a96-a4c6-304d47af5498.png)

![image](https://user-images.githubusercontent.com/3861465/221093856-b121eb68-d73e-40ee-aed6-578b51859089.png)

The "objectPath" in above pic is something like: `'YOUR_PROJECT_PATH/.git/bit/objects/f0/870fd1eccd93cf88b7b96be18800b0bf2de1d3'`

And the hash string is computed by sha1 of the component's name:
![image](https://user-images.githubusercontent.com/3861465/221094273-c5d1b668-b987-4808-99de-49d93b8b4677.png)

![image](https://user-images.githubusercontent.com/3861465/221094806-4dff4a3a-c89b-4917-9ccc-8edd4e8a08c6.png)

And the file did not exist:
![image](https://user-images.githubusercontent.com/3861465/221094933-fc360964-0b41-4bd4-b7eb-04beb7999caf.png)

But I'm still finding solution how to recover now...

**Comment by southerncross** [comment]
> I met a similar "Component not found" problem, after debugging for some time, I found that bit thrown the error when it tried to import local component:
> 
> ![image](https://user-images.githubusercontent.com/3861465/221093437-d5d31f5f-666a-4021-a7a3-7df0819f07af.png)
> 
> bit could not find local component: ![image](https://user-images.githubusercontent.com/3861465/221093634-14704211-dad4-4a96-a4c6-304d47af5498.png)
> 
> ![image](https://user-images.githubusercontent.com/3861465/221093856-b121eb68-d73e-40ee-aed6-578b51859089.png)
> 
> The "objectPath" in above pic is something like: `'YOUR_PROJECT_PATH/.git/bit/objects/f0/870fd1eccd93cf88b7b96be18800b0bf2de1d3'`
> 
> And the hash string is computed by sha1 of the component's name: ![image](https://user-images.githubusercontent.com/3861465/221094273-c5d1b668-b987-4808-99de-49d93b8b4677.png)
> 
> ![image](https://user-images.githubusercontent.com/3861465/221094806-4dff4a3a-c89b-4917-9ccc-8edd4e8a08c6.png)
> 
> And the file did not exist: ![image](https://user-images.githubusercontent.com/3861465/221094933-fc360964-0b41-4bd4-b7eb-04beb7999caf.png)
> 
> But I'm still finding solution how to recover now...

Oh by the way, components that bit is trying to import are come from the .bitmap file under you project root directory.

**Comment by sbland** [comment]
Removing from `.bitmap` would probably fix it. Also do a search of your code base for `my-scope/path/to/a/component` and `@my-scope.path.to.a.component`

**Comment by itaymendel** [comment]
it is also possible you ran many `tag`s that created weren't exported, but they are still in your local scope. a `bit init --reset-scope` can sort that out.
