### ISSUE TITLE
How to fix "please make sure to either apply the aspect environment or a composition of the aspect environment for the aspect to load" error

### ISSUE THREAD

**Issue by nilueps** [teambit/bit#6813]
### Description

I'm trying to create a react app using the components i've written. I couldn't find any documentation on how to do this so I copied the structure of the ["perfume-store"](https://bit.cloud/learn-bit-react/perfume-store/apps/perfume-store/~code/index.ts) app. But after adding the app component's ID to `workspace.json` bit's cli has become completely unusable, with every command printing the same error message:

```
"<my-component-id>" is configured in workspace.json, but using the "teambit.react/react" environment, which is type "react".
please make sure to either apply the aspect environment or a composition of the aspect environment for the aspect to load.
```

How can I "apply" the aspect environment? and what aspect environment is it referring to?

I've tried adding the `teambit.react/react` aspect to various spots in `workspace.json` but i'm basically groping in the dark at this point. 

### Specifications
* Bit version: 0.0.888
* Node version: 18.12.0
* npm version: 8.19.2
* Platform: Ubuntu 22.04.1 LTS (WSL2)
* Bit compiler (include version): ?
* Bit tester (include version): ?

**Comment by benjgil** [comment]
please update to the latest version of bit (currently 0.0.945), this should be resolved

**Comment by itaymendel** [comment]
closing the issue as there's no way to reproduce and author abandoned it.
