### ISSUE TITLE
Fonts not loading on remote

### ISSUE THREAD

**Issue by FIIFE** [teambit/bit#6820]
### Describe the bug
Fonts are not being loaded on remote scope. They work fine locally.

### Steps to Reproduce
go to https://bit.cloud/fifi/fonts-not-found-on-remote/theme/typography

### Expected Behavior
Fonts are being loaded on remote preview

### Screenshots, exceptions and logs
Errors can be found in devtools upon visiting [this remote scope](https://bit.cloud/fifi/fonts-not-found-on-remote/theme/typography)
I've also published a [reproduction repository](https://github.com/FIIFE/fonts-not-found-on-remote) from which the component was exported

### Specifications
* Bit version: 0.0.697
* Workspace type: (harmony/legacy) i think harmony but I don't know what this is or how to check it
* Node version: v16.18.1
* npm / yarn version: 8.19.2
* Platform: WSL 2
* Bit compiler (include version): 0.0.695
* Bit tester (include version): 0.0.695

### Additional info
I've tried it on 0.0.888 version but with no luck. Same thing happens

**Comment by benjgil** [comment]
You'll need to update to 0.0.888 or even 0.0.945, re-tag your custom env and then re-tag your components.
Then the preview should render as expected

And in general, make sure to not stay too far behind the latest version of bit, we've moved to a stable release pattern so you should be able to keep using the latest versions without fear of things breaking

**Comment by FIIFE** [comment]
Thanks for the answer @benjgil.
Updating to 0.0.945 seem to have solved the issue.
But unfortunately now I'm stuck with [this one](https://github.com/teambit/bit/issues/6771) which was the reason for downgrading in the first place.
