### ISSUE TITLE
Unable to create React 18 components despite creating a custom react env for react 18

### ISSUE THREAD

**Issue by acrodemocide** [teambit/bit#6830]
I'm still new to Bit, so apologies if this is just user error.

### Describe the bug
I'm trying to create React components using React 18. I have created a custom react environment, and overridden the dependencies for React 18. I'm updating the custom environment file: my-react.main.runtime.ts with the following:

`react.overrideDependencies({
    devDependencies: {
        'react': '^18.2.0',
        'react-dom': '^18.2.0',
        '@types/react': '^18.0.26'
        '@types/react-dom': '^18.0.9'
    }
})`

When I run bit install, it still installs react 17.x.x and react-dom 17.x.x. I've run bit compile, then bit install again, but still, it always is react 17.x.x and react-dom 17.x.x. I was under the impression I could create a custom environment to allow me to use react 18.

### Steps to Reproduce
1. Create a custom environment, and override devDependencies as described above for React 18.
1. Run bit install
1. react 17.x.x and react-dom 17.x.x are installed instead of 18. (Also can be verified by looking in the resulting node_modules directory).

### Expected Behavior
When overriding the react versions, bit install should install react 18 instead of 17.

### Screenshots, exceptions and logs
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications
* Bit version: 0.0.888
* Workspace type: harmony
* Node version: 16.18.0
* npm / yarn version: npm 8.19.2
* Platform: Windows

_for harmony workspace_

* relevant env: react-env
* relevant aspects: not sure

_for leagacy_

* Bit compiler (include version): N/A
* Bit tester (include version): N/A

**Comment by GiladShoham** [comment]
You should put react and react-dom as peers.
@benjgil can provide some examples

**Comment by benjgil** [comment]
See our example react-18 env for how to configure this
Specifically see the main.runtime file 
https://bit.cloud/bit-foundations/react/react-version-envs/react-18-env/~code

**Comment by mhamel** [comment]
Hi!  @benjgil !

I have the same issue and little explanation would be great. 

For my project, I'm using:
- bit link and bit watch locally to reuse some hooks within projects locally
- reactjs 18.0.2

I see the exemple but steps would be great like:
1 - install x package ...
2 - update workspace.jsonc ..
3 - run y command ...

Also the peer dependencies from workspace file look like:
    "peerDependencies": {
        "@testing-library/react": "^12.1.5",
        "react": "^18.2.0",
        "react-dom": "^18.2.0"
      }

Thank you!

**Comment by DmacMcgreg** [comment]
@benjgil @GiladShoham 

Any updates on this? 
The examples either do not work or are not clear enough.

**Comment by GiladShoham** [comment]
A new react env maintained by us (with a full api rewrite) is coming out really soon.
It will have react18 and esm by default.

**Comment by mhamel** [comment]
The problem was not with bit.dev.  The thing is that when we use "bit link" a duplicated react break the thing.  I don't know how I would do it with bit.dev but I ended up with basic npm link and the most important thing is to do a npm link on child package and link this package within the parent.  Something like that.

cd d:\mylibrary\node_modules\react
npm link

cd d:\mylibrary
npm link 

cd d:\myapp
npm link react mylibrary

It should work with bit.dev too.

**Comment by itaymendel** [comment]
hi, we have pushed an update to base react env that support react18 by default. please use it - https://bit.cloud/teambit/react/react-env
