### ISSUE TITLE
react-native: Cannot destructure property 'config' of 'options' as it is undefined

### ISSUE THREAD

**Issue by benjgil** [teambit/bit#6841]
Getting the following error when running `bit test` for any react-native components.
`✖ service "tester" of env "teambit.react/react-native" has failed. error: Cannot destructure property 'config' of 'options' as it is undefined.`

### Steps to Reproduce
1. create a new react-native workspace with the bit template (`bit new react-native my-rn-workspace`)
1. create a new react-native component `bit create react-native my-comp` in the workspace
1. `bit compile` then `bit test`

### Expected Behavior
tests will run without initial error preventing tests from running

### Specifications
* Bit version: 0.0.888 and 0.0.945
* Workspace type: (harmony)

### Additional context
NOTE: this issue is because of this issue with running jest v27 with version 0.66.4 of react-native, see [here](https://github.com/callstack/react-native-testing-library/issues/743).

**Comment by benjgil** [comment]
Workaround for now (until the react-native env rn version is updated to 0.70.6 or above):
Set any jest-related packages in the workspace.jsonc file to version 27, and add the following overrides to the `teambit.dependencies.dependency-resolver` config in workspace.jsonc:
`
"overrides": {
      "@jest/create-cache-key-function": "^27.0.1"
    },
`

**Comment by Zhao-Hansi** [comment]
thanks
