### ISSUE TITLE
Local only project, 2 CRAs with shared components

### ISSUE THREAD

**Issue by itekhi** [teambit/bit#6844]
### Description
So I'm working on a project right now, which looks like this:

```
- backend/
  - [backend stuff]
- admin/
  - [first CRA]
  - src/
  - public/
  - [etc...]
- client/
  - [second CRA]
  - src/
  - public/
  - [etc...]
```

So what I want to achieve is a `ui/` folder at the root with react components in it, and then use them in `admin/` and `client/`.

I can't find anything related to local projects with CRAs in them.

I did understand that there's `bit`'s way of react apps with `bit create react-app ...`. But is there a way to do this with an existing project?
I tried `bit link --target ../` in the `admin/` folder, but it doesn't link the components in `node_modules/`, so I think I'm missing something here.

Its my first time using bit, and I love it! I wanted something like this for years!

### Specifications
* Bit version: `0.0.945`
* Node version: `16.14.2`
* npm / yarn version: `npm 8.13.1`
* Platform: `MacOS 12.4`
* Bit compiler (include version):
* Bit tester (include version):

**Comment by GiladShoham** [comment]
In general, you can do:
- create react app
- init bit in the root folder of cra folder
- use bit create to create components where ever you want (bit doesn't care on your file/folder structure)
- run bit watch so bit will compile your bit components (I would exclude the bit componensts from other compilers)
- in your app (which in your case won't be a bit component), you can just import the components like they are installed packages. bit will create them on your node_modules, so in the eye of cra they are just regular packages.

**Comment by itekhi** [comment]
Oh, thanks!
Do I need to `bit init --bare` or just `bit init` in CRAs?
And how do I exclude bit components from compilers? 😅

**Comment by Thomas-Boi** [comment]
I don't know if this helps but I've been following this [guide](https://bit.dev/docs/workspace/creating-workspaces?new_existing_project=1). I just run `bit init` for me and it's working fine so far

**Comment by itaymendel** [comment]
closing the issue as there's no way to reproduce and author abandoned it.
