### ISSUE TITLE
 component docs patterns spelling mistakes

### ISSUE THREAD

**Issue by front-end-captain** [teambit/bit#6868]
I found the docs config interface example has a spelling mistakes:
![image](https://user-images.githubusercontent.com/25813333/210475657-6e88da53-7682-448d-9ab5-b46d95966ddc.png)

it should be "patterns" not "pattern". docs link: https://bit.dev/reference/docs/docs-overview#loading-the-component-docs

**Comment by GiladShoham** [comment]
that's correct, we will fix it.
@giteden FYI

**Comment by NitsanCohen770** [comment]
That's probably because @giteden doesn't like patterns :> 
@front-end-captain can you open a lane with this fix?
```
bit new bit-dev fix-pattern-typo --aspect teambit.community/starters/bit-dev
bit import teambit.docs/content/docs-overview
bit lane create fix-pattern-typo --scope [your-scope]
```
modify the mdx file
```
bit snap -m "fix a typo on the page"
bit export
```
Send us the lane we will handle it from there :)
