### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by hyoretsu** [teambit/bit#6880]
### Description

Next.js is pretty big in the React space, but since Bit isn't able to create components inside of other components for its `pages` structure, you can't create a Next app with only Bit. Lack of docs (a serious problem that you have) also doesn't help.

### Describe the solution you'd like

Create a way to nest components and recognize that they're a different thing and not part of the father component. Also create a next.js starter.

**Comment by GiladShoham** [comment]
We do plan to add a next starter by @giteden soon.
Why do you need nested components to work with next and bit?

**Comment by hyoretsu** [comment]
`pages/index.ts` and `pages/api/index.ts` cannot co-exist as bit components. Unless the idea is having a single pages ""component"" that has all the routes.

**Comment by itaymendel** [comment]
In Bit each component is contained in it's own "code container", ie - it's a self-contained module.

think about it like that - while in a specific nextjs page you may need a set of features/apis/ui/routes/whatever, a different nextjs app may want to have a similar, but different composition of capabilities on its own page.
Having a specific coupling for components to a nested structure may fit only one of the apps. With Bit Components we try to think about "how can we make this page more composable". In this case, the implementation may be getting a specific internal implementation of a page/route/feature as a separate component, and just `import` it to both nextjs apps (or just the one app, maybe the second one will be built later). this makes the business functionality "independent" from the specific app and available for other apps.

this way you decouple the implementation of a business requirement from the current structure of an app, so later you can move it around or put it in more apps. in a case where Bit Components were nested, this means a specific Bit Component would not be portable.

I am closing the issue, as nested-components is not something we plan to build "core" support for.
