### ISSUE TITLE
dev packages are being detected as regular package dependencies

### ISSUE THREAD

**Issue by GiladShoham** [teambit/bit#690]
## Expected Behavior
Chai will be recognized as dev package dependency

## Actual Behavior
Chai is recognized as **regular** package dependency

## Steps to Reproduce the Problem

1. extract
1. bit show string/pad-left

## Specifications

  - Version: 0.12.4-dev.1
  - Platform: all

**Comment by GiladShoham** [comment]
A full explanation is under https://github.com/teambit/bit/issues/635

**Comment by davidfirst** [comment]
@GiladShoham, is this the same as https://github.com/teambit/bit/issues/690?

**Comment by davidfirst** [comment]
@GiladShoham, I believe this is fixed. Please reopen if not.
