### ISSUE TITLE
Broken links offered by bit cli

### ISSUE THREAD

**Issue by evelant** [teambit/bit#6907]
### Describe the bug

When using `bit add` on a directory without a main file:

```
please either use --id to group all added files as one component or use our DSL to define the main file dynamically.
see troubleshooting at https://bit.dev/docs/components/component-main-file 
```

The link in the help message is a 404. IIRC there are a couple other cli messages I've run into that also have bad links but I don't remember exactly which ones.

### Steps to Reproduce

1. run bit add on a directory without a main file
1.
1.

### Expected Behavior

help links should work

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 0.0.945
- Workspace type: harmony
- Node version: 16.17.0
- npm / yarn version: pnpm 7.22.0
- Platform: macos

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by GiladShoham** [comment]
@giteden fyi
