### ISSUE TITLE
Can't use/install React v18 for Next.js

### ISSUE THREAD

**Issue by hyoretsu** [teambit/bit#6916]
### Description
I'm trying to switch my project to Bit, and it uses Next.js. After everything's ported, I tried to run Next and I got the message that I needed React `>=18.2.0`. I tried adding that to package.json, using `bit install`, using the apparently official [React v18 env](https://bit.cloud/bit-foundations/react/react-version-envs/react-18-env) (which I have no idea why isn't the default yet, it's been almost a year) but none of the solutions installed, let alone replace, React 18 alongside 17. I could do with official React v17 env for my components and a custom React 18 env for Next, but I simply can't.

### Specifications
* Bit version: 0.0.945
* Node version: 16.16.0
* pnpm version: 7.18.0
* Platform: Ubuntu v22
* Bit compiler (include version):
* Bit tester (include version):

**Comment by hyoretsu** [comment]
Bump, just faced this again when setting up a new project.

**Comment by woosade** [comment]
I have exaclty the same problem.
Using "bit update" and selecting all doesn't update because of this I can't use react-dom/client.

**Comment by woosade** [comment]
You can use this if you need to upgrade to react 18: https://github.com/teambit/bit/issues/6830#issuecomment-1364570494

**Comment by itaymendel** [comment]
use this as a base for react18 components - https://bit.cloud/teambit/react/react-env
