### ISSUE TITLE
I am unable to export component using bit remote add

### ISSUE THREAD

**Issue by darshandung** [teambit/bit#6921]
### Discussed in https://github.com/teambit/bit/discussions/6920
<div type='discussions-op-text'>

<sup>Originally posted by **darshandung** January 16, 2023</sup>
Hi Team,

I pull bitcli/bit-server from docker hub and trying to host own server. i am running through this command docker run -it -p 5000:3000 bitcli/bit-server:latest.
I can see bit.dev ui on http://localhost:5000. now i am trying to add **bit remote add http://localhost:5000** but it's giving me error

bit remote add http://localhost:5000/
{
  "response": {
    "error": "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST //graphql</pre>\n</body>\n</html>\n",
    "status": 404
  },
  "request": {
    "query": "\n      {\n        scope {\n          name\n        }\n      }\n    "
  }
}

Can someone please help me , i want to export component on http://localhost:5000/</div>

**Comment by GiladShoham** [comment]
I'll check this
it should work

**Comment by darshandung** [comment]
> I'll check this it should work

Can you please help ?

**Comment by GiladShoham** [comment]
I did the exact same flow and it worked just fine
![image](https://user-images.githubusercontent.com/3840769/214011561-d5ba1a4d-f6a7-44bd-be79-5a8590579a71.png)

**Comment by olga232323** [comment]
> ### Discussed in #6920
> Originally posted by **darshandung** January 16, 2023 Hi Team,
> 
> I pull bitcli/bit-server from docker hub and trying to host own server. i am running through this command docker run -it -p 5000:3000 bitcli/bit-server:latest. I can see bit.dev ui on http://localhost:5000. now i am trying to add **bit remote add http://localhost:5000** but it's giving me error
> 
> bit remote add http://localhost:5000/ { "response": { "error": "\n<html lang="en">\n\n<meta charset="utf-8">\n<title>Error</title>\n\n\n
> 
> Cannot POST //graphql
> \n\n\n",
> "status": 404
> },
> "request": {
> "query": "\n {\n scope {\n name\n }\n }\n "
> }
> }
> Can someone please help me , i want to export component on http://localhost:5000/

Do not use "/" at the end of the bit remote add http://localhost:5000/ command, is: bit remote add http://localhost:5000
