### ISSUE TITLE
add standard short commands to CLI

### ISSUE THREAD

**Issue by amir-arad** [teambit/bit#695]
## Expected Behavior
`bit -v` should return the version number,  the same way `bit -h` displays help info

## Actual Behavior
```
$ bit -v
warning: no command named '-v' was found...
see 'bit --help' for additional information.
``

## Steps to Reproduce the Problem

  1. `$ bit -v`

## Specifications

  - Version: 0.12.4
  - Platform: OSX

**Comment by GiladShoham** [comment]
@amir-arad you can use `bit -V` (capital V) to display the version number

**Comment by amir-arad** [comment]
`-v` is what I expected to work, though. like `node -v`, `npm -v`, `docker -v` etc.
