### ISSUE TITLE
Dependency resolver ignores pnpmfile.cjs

### ISSUE THREAD

**Issue by arekdigitaltoucan** [teambit/bit#6954]
### Description

When doing `bit install` the `.pnpmfile.cjs` is ignored, it contains a readPackage hook which allows me to force a specific version of a transitive dependency. One of the dependencies I have to use (@atlaskit/editor-core) has a strict dependence on `prosemirror-model: 1.14.3` but also on `prosemirror-state: 1.3.4` which in turn has a dependency on `prosemirror-model: 1.16.1`, even though they are same major version, I get runtime errors about versions mismatch.

I managed to solve this issue using pnpm directly by enforcing `prosemirror-model: 1.16.1` with a readPackage hook, but it has no effect when doing `bit install` (I do have `teambit.dependencies/pnpm` configured as a packageManager). I tried to set a dependency policy at the root level to use a specific version but it doesn't solve the issue (even with `"preserve": true`), I still get two versions and runtime errors. Possibly a dependency-resolver does this only for direct dependencies of the bit components?

Anyway, is there a way for me to enforce a specific version of a transitive dependency? Or is there a way to make dependency-resolver respect `.pnpmfile.cjs`?

I tried doing a fallback to `pnpm install && bit import && bit link && bit compile` and it compiled with webpack and was running fine in the browser, but then, when doing `bit start` I got a lot of bit related errors and zero compositions loaded properly - is such a fallback still possible? 

### Specifications

- Bit version: tried on 0.0.888 and 0.0.945
- Node version: v16.18.1
- npm / yarn version: -
- Platform: osx, apple m1
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

I can't move away from the editor-core (weeks of work) and I can't stay on the current version either. When bumping to the newest it doesn't work because of a version mismatch of `prosemirror-model`. Any help or suggestions will be appreciated.

**Comment by zkochan** [comment]
You don't need. a `.pnpmfile.cjs` to this. Just use overrides. Overrides example:

```json
{
  "@teambit.dependencies/dependency-resolver": {
    "overrides": {
      "foo": "^1.0.0",
      "quux": "npm:@myorg/quux@^1.0.0",
      "bar@^2.1.0": "3.0.0",
      "qar@1>zoo": "2"
    }
  }
}
```

**Comment by arekdigitaltoucan** [comment]
Thank you @zkochan it solved the problem. I somehow overlooked this option when reading dependency-resolver docs (would be best if this information made it to the bit.dev/docs).

Appreciate the work you do with Bit and pnpm, great work 🥇

**Comment by GiladShoham** [comment]
@arekdigitaltoucan 
A new docs are coming soon.
We will make sure it will be there.
@giteden
