### ISSUE TITLE
bit.cloud is unusable if page is loaded direct to source code (cannot click any links)

### ISSUE THREAD

**Issue by evelant** [teambit/bit#6959]
### Describe the bug

If you open a link to some source code on bit.cloud it becomes impossible to navigate using any of the links on the page.

### Steps to Reproduce

1. Open https://bit.cloud/teambit/react/react-native/~code/jest/jest.config.js
1. Observe and none of the links do anything, page is unusable
1.

### Expected Behavior

Links should work

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: N/A
- Workspace type: (harmony/legacy)
- Node version: N/A
- npm / yarn version: N/A
- Platform: N/A

*for harmony workspace*
- relevant env
- N/A
- relevant aspects
- N/A

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

N/A

**Comment by itaymendel** [comment]
this issue is unrelated to the OSS version of Bit. removing it from GH.
Will be resolved in the near future on bit.cloud.
