### ISSUE TITLE
Unable to use `bit` in M1 Mac Docker containers

### ISSUE THREAD

**Issue by surgeboris** [teambit/bit#6967]
Some Docker containers on M1 Mac have an `os: linux`, but `arch: arm64`.
Bit cannot be installed in these environments: running `npx @temabit/bvm install` prints
```
unsupported arch: arm64 for os: linux. fallback to x64
version 0.0.945 is not installed 
```

[This PR](https://github.com/teambit/bit/pull/5632/files) already added support for `darwin-arm64`, which makes me think that adding support for `linux-arm64` should be an even easier endeavor (as you can just re-use parts of the `darwin-arm64` pipeline configuration).

Can you please add support for `linux-arm64`?

**Comment by surgeboris** [comment]
@guysaar223 @GiladShoham @davidfirst Sorry for the ping, but I really think that this issue is important. It prevents users from being able to use `bit` in Docker on M1.

There don't seem to be any workarounds (as `bvm` is the only way to install `bit`, trying `npm i -g @teambit/bit` fails with an error of some packages missing).

And it seems like it should be easy to solve this problem. IIUC the solution will be heavily based on [this PR](https://github.com/teambit/bit/pull/5632/files). I would've opened a PR myself, but I don't have an access to upload a new `esbuild` version to your GCloud bucket.

**Comment by GiladShoham** [comment]
the first part is done on this pr - https://github.com/teambit/bit/pull/6994
this is about generating the new version type.
there is also a change in bvm required in order to let bvm know where to search for that version

**Comment by GiladShoham** [comment]
done.
Supported from bvm [v0.2.10](https://github.com/teambit/bvm/releases/tag/v0.2.10) 
Only exists since v0.0977 of bit (which is a nightly version at the moment of this message)
