### ISSUE TITLE
Documentation page height does not fit the entire content for large tables of properties

### ISSUE THREAD

**Issue by lhassis** [teambit/bit#6978]
### Documentation page height does not fit the entire content
When using a self hosted scope and exporting the components into it, all components' Overview pages have can not be enough to show the entire content.

### Steps to Reproduce
1. Create a self hosted scope by following: https://github.com/teambit/bit/tree/master/scripts/docker-teambit-bit
1. Create components that have a large table of properties and export to the self hosted scope
1. Open the components' Overview page and scroll down the documentation. 
1. Check that the content is cut and you can't scroll down after a limit height.

### Expected Behavior
All documentation content should be displayed on the screen.

### Screenshots, exceptions and logs
See on attached image that scroll is finished and the content is cut.
![image](https://user-images.githubusercontent.com/49009472/215560557-401a4305-3272-4541-a470-949d604b86c6.png)

### Specifications
* Bit version: 0.0.967
* Workspace type: harmony
* Node version: 16.16.0
* npm / yarn version: 8.11.0
* Platform: win

_for harmony workspace_

* relevant env: teambit/react
* relevant aspects

_for leagacy_

* Bit compiler (include version): NA
* Bit tester (include version): NA

### Additional context
Inspecting the page I saw that the iframe has a scrolling="no" property. Enabling the scroll, you can scroll inside the content and see the remaining parts of the table, but, of course, this is not the desired behavior.

![image](https://user-images.githubusercontent.com/49009472/215561421-68774549-bb21-4296-ad43-dbe62b3ce726.png)

**Comment by GiladShoham** [comment]
@luvkapur can you have a look?

**Comment by luvkapur** [comment]
Can't repro it. The iframe here calculates the height correctly for 25+ rows in the Properties Table. `scrolling=no` is set to `false` because we want the iframe to the render the content to its fullHeight and allow the parent page to manage the scrolling.  
 
https://user-images.githubusercontent.com/8999604/215585474-0e980ac7-d2cd-4776-8939-c31e4b25bcf6.mov

**Comment by cabral2** [comment]
I'm having this issue at version 0.0.992 as well.

I have a component with ~50 properties but only 32 of them are displayed on the documentation.

When running my scope localy the Iframe doesn't have the scrolling property set to "no".

**Comment by NitsanCohen770** [comment]
Look much better on the new cloud site, doesn't it? :)
https://new.bit.cloud/teambit/harmony/harmony/~api-reference?selectedAPI=Aspect
