### ISSUE TITLE
Can not upgrade to React 18

### ISSUE THREAD

**Issue by DCosti** [teambit/bit#6995]
### Describe the bug
I have  a collection of components that uses React v17. I made the changes to upgrade to React v18 as follows:
- upgraded packages
- copy the `overrideDependecies` content in my custom env main.runtime file as stated [here](https://bit.cloud/bit-foundations/react/react-version-envs/react-18-env). I have a custom env so I thought that just copying the  `overrideDependecies` content it will work.
But every time I run `bit install` I get React v17.

### Steps to Reproduce

1. Clone this [repo](https://github.com/osstotalsoft/rocket-ui) and run `bit install`

### Expected Behavior

After bit install to have version 18 of React

### Screenshots, exceptions and logs
As you can see in the image above, first is installing react v18 but not react-dom v18 (which is odd):
![image](https://user-images.githubusercontent.com/41594981/216647977-a91275d5-921c-4100-bf93-02ca750fdec5.png)
But then is uninstalling react v18 and installs react v17.0.2:
![image](https://user-images.githubusercontent.com/41594981/216648132-e76a3e06-1a11-471c-ba8b-38f7c99d877e.png)
This is how my `overrideDependencies` from `env.main.runtime` file looks like:
![image](https://user-images.githubusercontent.com/41594981/216648401-a1b3774e-89de-4fc6-ab07-e0dc6cab29c1.png)
And this is how my `workspace.jsonc` file looks:
![image](https://user-images.githubusercontent.com/41594981/216648540-e79dbafe-fe81-4bc9-83e2-11095de26c59.png)

### Specifications

- Bit version: 0.0.945
- Workspace type: harmony
- Node version: v18.12.1
- npm / yarn version: 8.19.2
- Platform: Windows 11

*for harmony workspace*
- relevant env: https://bit.cloud/totalsoft_oss/rocket-ui/envs/my-env
- relevant aspects: https://bit.cloud/totalsoft_oss/rocket-ui/generator/component-templates

Thanks for your help!

**Comment by DCosti** [comment]
The problem was that I was using the `react.overrideDependencies` and the `envs.override`. After merging them, it worked upgrading to React v18. Thanks @benjgil for your support!

**Comment by DmacMcgreg** [comment]
@DCosti are you able to provide an example of what all the files in your workspace look like that are required to get this working?
I'm currently unable to get React18 and I'm running into the following error:
TypeError: (0 , import_react2.useSyncExternalStore) is not a function

**Comment by DCosti** [comment]
Sure. Here is my library https://github.com/osstotalsoft/rocket-ui .Hope it helps!:)
