### ISSUE TITLE
How exclude dir when bit tag?   exclude react native native assets's  js files when bit compile and bit tag

### ISSUE THREAD

**Issue by disanweidu** [teambit/bit#7018]
My files structure like below image ；  I could not find any  way to exclude  android/src/main/assets/pdfreader files  when bit tag.  I get a error   when bit tag  as image two

![image](https://user-images.githubusercontent.com/117299623/217742259-3e6fa05c-ae95-495b-a4a0-1cc67a4b5707.png)

![image](https://user-images.githubusercontent.com/117299623/217743598-7e97af18-2df6-436d-b8cd-ad76f2c048ba.png)

the pdf.js is a cdn release file
![image](https://user-images.githubusercontent.com/117299623/217743769-49f31f83-9572-417c-a292-f1a4abac12b0.png)

**Comment by benjgil** [comment]
Hi there
I would highly recommend upgrading to our new envs format, in which it's very easy to define separate tsconfigs for local vs production compilation, and there you can add the relevant exclude patterns to the production tsconfig
https://bit.dev/blog/introducing-react-component-development-environment-lfhd699k/
