### ISSUE TITLE
Ability to test all locally available components without requiring id

### ISSUE THREAD

**Issue by renoirb** [teambit/bit#704]
Assuming we have a local SCM managed repository of bit components.

That we can list all components, and we can manually declare which component to test.

It would be nice we could run `bit test` on a scope name

Request:
* At `bit test`, ability to tell scope or what components their scope/namespace/id starts with

## Expected Behavior

Ability to run tests by selecting of some sort

## Actual Behavior

We can't, we have to be explicit of the ID, not a list

## Steps to Reproduce the Problem

To do this, [I've created a repository of components](https://github.com/renoirb/bits), and a build pipeline, we'll use this.

**NOTE** Make sure you have [jq](https://stedolan.github.io/jq/) and [make](https://www.gnu.org/software/make/) installed, though.

You'll notice [I achieved to produce a desirable output](https://github.com/renoirb/bits/commit/1215caeed7e9b6b3ff5f53137c43cf9b86b20e47), maybe it'll be better done differently though;

  1. `git clone https://github.com/renoirb/bits.git; cd bits`
  1. `make`
  1. `make test`

<img width="1129" alt="screenshot 2018-02-02 12 17 55" src="https://user-images.githubusercontent.com/296940/35745794-83a65914-0812-11e8-9795-98df6f2519e4.png">

At the moment, the script also supports configurable test run using shell variable

<img width="964" alt="screenshot 2018-02-02 13 08 15" src="https://user-images.githubusercontent.com/296940/35747802-ae67f1ce-0819-11e8-8c9e-78d2af0d7c00.png">

**Comment by GiladShoham** [comment]
@renoirb Thanks for this suggestion, we put it in our backlog and we will implement it soon.
I'll keep this issue updated.

**Comment by itaymendel** [comment]
closing this one, as its released.
