### ISSUE TITLE
Running `bit tag` doesn't take workspace .npmrc into account

### ISSUE THREAD

**Issue by candiii-lin** [teambit/bit#7098]
### Describe the bug
Using `bit tag` to publish a component to a private repository has an authentication error at `npm publish`.

### Steps to Reproduce
1. Create a component and set up npmrc with private repo auth information
1. Set up workspace.json to publish to private repo
1. run `bit tag` 

you will see and EAUTH error

### Expected Behavior
Should publish.

### Screenshots, exceptions and logs
When I add the corresponding config using `npm config set`, the tag is able to publish and proceed accordingly. So my guess is that when you pack the components in capsules, it's missing the `.npmrc` in the packaged location, where `npm publish` is ran from

### Specifications
* Bit version: 0.0.945
* Workspace type: harmony
* Node version:
* npm / yarn version: 
* Platform: MacOS

**Comment by GiladShoham** [comment]
@zkochailch we do this programmatically with pnpm?

**Comment by itaymendel** [comment]
resolved. bit respects npmrc from workspace, user-home or global.
