### ISSUE TITLE
Missing license in @teambit/base-ui.text.heading

### ISSUE THREAD

**Issue by anuraggo** [teambit/bit#7104]
License file missing in package @teambit/base-ui.text.heading
Link ref - https://www.npmjs.com/package/@teambit/base-ui.text.heading
This is blocking our security scan and causing security vulnerabilities due to missing license.

Please add the license in @teambit/base-ui.text.heading

**Comment by itaymendel** [comment]
hi, you may treat any package under the `@teambit` scope as apache2 license.
sadly we are not propagating our license from the repo to all sub-components.

**Comment by anuraggo** [comment]
Great, Thank you for the reply.
