### ISSUE TITLE
Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by joshua1** [teambit/bit#712]
running a ``` bit export ``` or a ```bit import ```  command works ok (i hope) but returns the below ```Cannot read property 'endsWith' of undefined``` or ```Path must be a string. Received null``` . I wonder what it means . Also after doing a ``` bit import``` root files and folders where imported BUT, the imported root files were empty and the root folders contained no files .The bitmap file generated also only has version property. In bitsrc though, all files were imported successfully and i could see the code

**Comment by itaymendel** [comment]
hi @joshua1 
can you please include details about your environment? which operating system you are running, which version of Bit you have installed, was the scope hosted on bitsrc.io?  
additionally, please include the log files (` ~/Library/Caches/Bit/logs/debug.log` on linux/mac or `%APPDATA%\Local\Bit\logs\debug.log` on windows) from Bit, the `.bitmat` and `bit.json` files.

i need more information in order to properly recreate the issue and debug it.

**Comment by davidfirst** [comment]
As far as I can see, the model representation of this component doesn't have the 'mainFile' attribute.
Not sure how it happened originally, but I was able to reproduce it easily by tagging a component after deleting the mainFile from .bitmap file.

The fix I just committed doesn't solve this specific case but prevents this issue from happening again.
In case of missing mainFile, it won't let the user tagging the component.

**Comment by joshua1** [comment]
@itaymendel To answer your questions
1. Environment : Mac OS (High Sierra)
2.Bit version 0.12.5
3. Scope is hosted on bitsrc.io , private , (https://bitsrc.io/blujosi/shared/shared/ubus)
4. see attached
5.```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "shared/ubus": {
        "files": [
            {
                "relativePath": "gun-logic/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "gun-logic/test-logic.ts",
                "test": false,
                "name": "test-logic.ts"
            },
            {
                "relativePath": "gun-logic/user-logic.ts",
                "test": false,
                "name": "user-logic.ts"
            },
            {
                "relativePath": "gun-model/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "gun-model/user.ts",
                "test": false,
                "name": "user.ts"
            },
            {
                "relativePath": "gun.ts",
                "test": false,
                "name": "gun.ts"
            },
            {
                "relativePath": "index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "model/enums.ts",
                "test": false,
                "name": "enums.ts"
            },
            {
                "relativePath": "model/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "model/user.ts",
                "test": false,
                "name": "user.ts"
            }
        ],
        "origin": "AUTHORED"
    },
    "version": "0.12.5"
}
```
[bit_log.txt](https://github.com/teambit/bit/files/1702609/bit_log.txt)


6. ```
{
    "env": {
        "compiler": "none",
        "tester": "none"
    },
    "dependencies": {},
    "componentsDefaultDirectory": "components/{namespace}/{name}",
    "packageManager": "npm"
}
```

**Comment by joshua1** [comment]
This is sorted now. i had to specify --main ./index.ts to get it working. The documentation should be updated to indicate the importance of the specifying the main file
