### ISSUE TITLE
Unable to create a new workspace with Lit

### ISSUE THREAD

**Issue by amoreaulemay** [teambit/bit#7127]
### Describe the bug
When creating a new Lit workspace, or trying to add `teambit.web-components/lit` to an existing workspace I get the following error:

```
bit new lit nd-components --env teambit.web-components/lit
✖ couldn't load one of the following extensions teambit.web-components/lit@1.0.2, due to an error "Cannot find module '@babel/runtime/helpers/interopRequireDefault'", please use the '--log=error' flag for the full error.
Cannot find module '@babel/runtime/helpers/interopRequireDefault'
Require stack:
- /Users/amoreaulemay/Library/Caches/Bit/capsules/fb7dc15136acca2ba1774d86c8c0df5a8032f8f1/teambit.web-components_lit@1.0.2/dist/lit.bit-env.js
- /Users/amoreaulemay/.bvm/versions/0.0.1000/bit-0.0.1000/node_modules/@teambit/aspect-loader/dist/plugin.js
- /Users/amoreaulemay/.bvm/versions/0.0.1000/bit-0.0.1000/node_modules/@teambit/aspect-loader/dist/plugins.js
- /Users/amoreaulemay/.bvm/versions/0.0.1000/bit-0.0.1000/node_modules/@teambit/aspect-loader/dist/aspect-loader.main.runtime.js
- /Users/amoreaulemay/.bvm/versions/0.0.1000/bit-0.0.1000/node_modules/@teambit/bit/dist/load-bit.js
- /Users/amoreaulemay/.bvm/versions/0.0.1000/bit-0.0.1000/node_modules/@teambit/bit/dist/app.js
- /Users/amoreaulemay/.bvm/versions/0.0.1000/bit-0.0.1000/node_modules/@teambit/bit/bin/bit
```

I discussed this issue with itaymendel on Slack, a sort of way to resolve the issue is the following:

1. Instead of doing `bit new` create the new directory and run:

```
git init
bit init
```

1. Copy this in the `workspace.jsonc` file:

    /**
     * this is the main configuration file of your bit workspace.
     * for full documentation, please see: https://bit.dev/docs/workspace/workspace-configuration
     **/{
      "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
      /**
       * main configuration of the Bit workspace.
       **/
      "teambit.workspace/workspace": {
        /**
         * the name of the component workspace. used for development purposes.
         **/
        "name": "my-lit-workspace",
        /**
         * set the icon to be shown on the Bit server.
         **/
        "icon": "https://static.bit.dev/bit-logo.svg",
        /**
         * default directory to place a component during `bit import` and `bit create`.
         * the following placeholders are available:
         * name - component name includes namespace, e.g. 'ui/button'.
         * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
         * scope - scope name only, e.g. 'compilation'.
         * owner - owner name in bit.dev, e.g. 'teambit'.
         **/
        "defaultDirectory": "{scope}/{name}",
        /**
         * default scope for all components in workspace.
         **/
        "defaultScope": "company.scope"
      },
      /**
       * main configuration for component dependency resolution.
       **/
      "teambit.dependencies/dependency-resolver": {
        /**
         * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
         */
        "packageManager": "teambit.dependencies/pnpm",
        "policy": {
          "dependencies": {
            "@open-wc/testing-helpers": "^1.8.12",
            "@teambit/defender.eslint-linter": "^0.0.7",
            "@teambit/defender.jest-tester": "^0.0.8",
            "@teambit/defender.prettier-formatter": "^0.0.4",
            "@teambit/dependencies.modules.packages-excluder": "^0.0.70",
            "@teambit/html.docs.docs-template": "^1.0.0",
            "@teambit/html.mounter": "^1.0.0",
            "@teambit/preview.react-preview": "^0.0.20",
            "@teambit/react.react-env": "^0.0.42",
            "@teambit/typescript.typescript-compiler": "^0.0.6",
            "@teambit/web-components.lit": "^1.0.0",
            "core-js": "^3.29.0",
            "react": "^18.2.0",
            "react-dom": "^18.2.0"
          },
          "peerDependencies": {}
        },
        "linkCoreAspects": true,
        "rootComponents": true
      },
      "teambit.generator/generator": {
        "envs": [
          "teambit.web-components/lit"
        ]
      }
    }1. Then it will still not work directly. If you do `bit template` at this point, lit template still is not found and `bit install` will also fail.
1. itaymendel encountered a similar edge case and when he added two envs it worked. For example:

```
"teambit.generator/generator": {
    "envs": [
      "teambit.web-components/lit",
      "teambit.react/react-env"
    ]
  }
```

**However, while that works for a new workspace, trying to upgrade an existing workspace using `@teambit.web-components/lit@0.0.25` to v1.0.2 fails.**

### Expected Behavior
* `bit create new lit [workspace] --env teambit.web-component/lit` should work
* Should be able to upgrade the `@teambit.web-components/lit` to latest version in an existing workspace.

### Specifications
* Bit version: 0.0.1000
* Workspace type: harmony
* Node version: 16.17.0
* pnpm version: 7.11.0
* Platform: MacOS arm64
* relevant env: teambit.web-components/lit

**Comment by benjgil** [comment]
A better workaround for this would be to use the original command, and then run the following:
`bit capsule delete --scope-aspects`

Run `bit compile && bit install` again after the above and it should now work.

This error is due to a bug in how environments are loaded in some situations. The above will reset the loading and any command after this should re-load the envs/aspects capsule and resolve the issue as a workaround.
We're working to resolve the underlying bug, hopefully within the next few days

**Comment by amoreaulemay** [comment]
Okay thanks, I will wait for the underlying bug to be fixed

**Comment by amoreaulemay** [comment]
@benjgil any updates on this issue?

**Comment by itaymendel** [comment]
the underline issue is a more internal topic and unrelated to Lit.
we are moving all `bit new` templates to be static, which means we do not need capsules for them anymore.
