### ISSUE TITLE
I can't perform a "bit tag" to my NextJS applications

### ISSUE THREAD

**Issue by Adrilene** [teambit/bit#7131]
I'm trying to use bit to integrate my NextJs applications. However, when I try to run "bit tag" it returns the error: 

```
unable to save Version object of "footer@0.0.1", the mainFile src\pages\index.js is invalid
This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.
```

And when I run bit doctor, I have the following result: 
![image](https://user-images.githubusercontent.com/19615841/223778105-f71c6597-3bf4-4843-a527-5b3318f181fe.png)

I've already tried to install npm and yarn but it ends up on the same error. What can I do to fix this problem?

**Comment by itaymendel** [comment]
hi, it seems you tried to wrap the entire app or git-repo as a nextjs app. is this so?

**Comment by itaymendel** [comment]
closing the issue as we get no comment from original author.
