### ISSUE TITLE
Name clash when creating two components with the same name but different scopes

### ISSUE THREAD

**Issue by sbland** [teambit/bit#7142]
### Describe the bug

Creating two component  using the same name (e.g. `ui/button`) but with different scopes causes a conflict in the .bitmap file and cli error.

### Steps to Reproduce

1. `bit create react ui/button -s org.scope`
2. `bit create react ui/button -s org.scope2`

### Expected Behavior

Should be able to handle the same component name from different scopes.

### Specifications

- Bit version: 0.0.865
- Workspace type:harmony

**Comment by itaymendel** [comment]
duplicated #4656
