### ISSUE TITLE
The custom react env is unable to retrieve the dependencies graph. The GraphQL query response shows an "unknown error" for teambit.harmony.

### ISSUE THREAD

**Issue by anilpixel** [teambit/bit#7155]
### Describe the bug

I created a custom react env by running `bit create react-env envs/my-react-env`. Then, I exported it to my self-hosted scope, which was successful. However, when I visit the dependencies page at the route `/envs/my-react-env/~dependencies`, the service throws an error:

```json
{
  "errors": [
    {
      "message": "teambit.harmony: unknown error. please use the '--log' flag for the full error.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "graph"
      ],
      "ERR_CODE": "Error"
    }
  ],
  "data": {
    "graph": null
  }
}
```

run the command `bit show envs/my-react-env`, it will print the following snapshot:
![image](https://user-images.githubusercontent.com/7484425/225200575-45256492-a0e5-40e4-b80b-f0286b9ec58b.png)

export a component without custom react env, it work correctly:

![image](https://user-images.githubusercontent.com/7484425/225202470-42a48574-b1eb-4907-8a83-e26e88b15e4b.png)

### Steps to Reproduce

1. Run `bit create react-env envs/my-react-env` to create a react env
1. Export the env to self-hosted scope
1. Visit the dependencies page 

### Expected Behavior

After completing the steps mentioned above, I should be able to see the dependencies graph.

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/7484425/225199096-cb9927ed-6356-44db-a189-fb078a4f3445.png)

### Specifications

- Bit version: 0.1.0
- Workspace type: harmony
- Node version: v17.9.1
- npm / yarn version: v8.11.0
- Platform: centos

*for harmony workspace*
- teambit.envs/env

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

**Comment by anilpixel** [comment]
I appreciate all the hard work that has gone into this project. May I ask for an update on this issue?

**Comment by itaymendel** [comment]
this is likely a result of your self-hosted scope not able to fetch all dependencies for the reeact-env from bit.cloud.
notice how locally the react-env depends on many plugins from `@teambit`. you need these plugins available on your local.
it's possible that the quickest way to get there is by forking the env and all its dependency graph, and taking this internally.

another option, if your self hosted server has network access to the internet, is use the "scope network" feature to add all relevant remote scopes from bit.cloud - https://bit.dev/reference/scope/remote-scopes/#network-of-scopes
this way your scope will be able to fetch data on dependencies.
