### ISSUE TITLE
template "react" was not found

### ISSUE THREAD

**Issue by sbland** [teambit/bit#7158]
### Describe the bug

Running the new workspace command from here: https://bit.dev/docs/getting-started/installing-bit/start-bit-workspace.
`bit new react tasks-workspace --aspect teambit.react/react-env --default-scope my-org.tasks-scope`
I get the following error `template "react" was not found` but running `bit templates --show-all` returns....
```
The following template(s) are available with the command bit new: 
Example - bit new <template-name> <workspace-name>
teambit.react/react
    react (React workspace with demo components)
    react-app (EXPERIMENTAL. react workspace for an app)
    react-lib (EXPERIMENTAL. react workspace for a component library)
    react-workspace (React workspace with demo components)
    react-design-system (React workspace with components for a Design System)
    react-wiki (React workspace with components for a Wiki)
    react-analytics (React workspace with components for an Analytics Application)
    react-data-fetching (React workspace with components to show data fetching)
    react-blog (React workspace with components for a Blog)

teambit.react/react-native
    react-native (React workspace with demo components)
```

I can get around this by not defining the aspect and instead running
`bit new react tasks-workspace --default-scope my-org.tasks-scope`

### Expected Behavior

Should create a new bit workspace

### Specifications

- Bit version: 0.0.867
- Workspace type: harmony

**Comment by itaymendel** [comment]
Hi,

Please update bit to latest version.
also, is this happening when you try to create a new workspace? please provides steps to reproduce.
