### ISSUE TITLE
Plans to support Component Manager UI on self-hosted scope?

### ISSUE THREAD

**Issue by limsammy** [teambit/bit#716]
Are there any plans to add the ability to host your own frontend component viewer/search (like that which is available when hosting a scope on bitsrc)?

**Comment by itaymendel** [comment]
hi @limsammy 
right now we do not have such plans. all development efforts are focused on features related to development-workflows.

**Comment by svenbatistasteinbach** [comment]
Any updates?

**Comment by anukriti6** [comment]
Any updates ?
