### ISSUE TITLE
Bit missing dependencies and commands after installing via `npx @teambit/bvm install `

### ISSUE THREAD

**Issue by Thomas-Boi** [teambit/bit#7166]
### Describe the bug

Hello,

A team member of my dev team cannot use `bit` after running `npx @teambit/bvm install `. Everybody else who installed a month ago has bit running ok on their machines. 

Yesterday, he installed `bit` successfully but when he tried to run `bit login` and `bit --version`, they yield the following error:

![Screenshot 2023-03-15 at 11 58 33 AM](https://user-images.githubusercontent.com/43018778/225735298-becc9297-c7e8-4f2a-94da-96384c0daec9.png)

![bug_report](https://user-images.githubusercontent.com/43018778/225733519-f8481177-4fd0-4d13-b00b-454d2cc941b8.PNG)

![Screenshot 2023-03-15 at 11 45 18 AM](https://user-images.githubusercontent.com/43018778/225734871-75306379-6004-411b-92dd-7728d72ab53c.png)

Today, we checked again and we now have these errors:
![Screenshot 2023-03-16 at 12 19 08 PM](https://user-images.githubusercontent.com/43018778/225735653-71edb7c2-4800-48a8-9207-eff847d8684f.png)

![Screenshot 2023-03-16 at 12 21 22 PM](https://user-images.githubusercontent.com/43018778/225735667-3306c864-e137-43ad-8af8-8a1563b0a6af.png)

We aren't sure why this is failing specifically on his machine. Any help would be much appreciated.

### Steps to Reproduce

1. Install bit using `npx @teambit/bvm install`
2. Try to run `bit --version`.

### Expected Behavior

Can utilize bit commands like `bit login`.

### Screenshots, exceptions and logs

See above.

### Specifications

- Bit version: 0.1.4
- Workspace type: harmony
- Node version:  v18.15.0
- npm / yarn version: v9.5.0
- Platform: Mac OS Ventura 13.2.1 (22D68), M1 Chip

### Additional context

He tried to install this week and it fails. Everyone else on the team installed about a month ago and things work fine. I'm not sure what could have caused this bug.

**Comment by GiladShoham** [comment]
It seems like there is another bin file called bit in this machine (which is not our bit).
So you can either delete the other bit bin, or change our bit bin name by bvm config set DEFAULT_LINK <new-name> 
Where new name can be for example bbit.
Then run bvm link 
Then bbit -v and bbit login

**Comment by Thomas-Boi** [comment]
> It seems like there is another bin file called bit in this machine (which is not our bit). So you can either delete the other bit bin, or change our bit bin name by bvm config set DEFAULT_LINK Where new name can be for example bbit. Then run bvm link Then bbit -v and bbit login

Thanks @GiladShoham! That answer worked for us. I'll close this issue now.
