### ISSUE TITLE
Not able to install bit in my system

### ISSUE THREAD

**Issue by ramathilagam598** [teambit/bit#7169]
### Description

I am trying to install bit using this command - npx @teambit/bvm install
But it is throwing the below error.

**Node.js version 16.16.0 is not installed. Try to reinstall the wanted bit CLI version with the --override option**

I have node js 16.16.0 installed in my system.

### Specifications

- Node version: 16.16.0
- npm / yarn version: 9.6.2
- Platform: Windows 10

**Comment by GiladShoham** [comment]
Try installing bvm globally.
Npm i -g @teambit/bvm
Then run 
bvm install --override
