### ISSUE TITLE
Bit and Angular: Missing package dependency: app

### ISSUE THREAD

**Issue by limsammy** [teambit/bit#717]
## Expected Behavior
My Angular components consist of an html, scss, and ts file. Adding the component using `bit add src/app/shared/view/image-viewer.component.html src/app/shared/view/image-viewer.component.scss src/app/shared/view/image-viewer.component.ts --main src/app/shared/view/image-viewer.component.ts --id component/image-viewer` should work.

## Actual Behavior
When running bit status after adding the component, it says `missing packages dependencies: app`. Is there an Angular bit guide? I see there's a React guide, but not angular. How do I fix this dependency error? Can I just export the component with the missing dependency?

**Comment by GiladShoham** [comment]
Hi @limsammy 
Maybe you can share the requires / import statements of all the files?

**Comment by limsammy** [comment]
@GiladShoham Sure thing.

image-viewer.component.ts:

```javascript
import {Component} from '@angular/core';
import {MdDialogRef} from '@angular/material';
import {Media} from '../../models/media.model';
```

media.model.ts:

```javascript
import {Thumbnail} from 'app/models/thumbnail.model';
import {NeonImageGridContent} from './neon-image-grid-content';
```

neon-image-grid-content.ts:

```javascript
import {Media} from './media.model';
```

**Comment by brunobertechini** [comment]
The same occurs with a custom module for angular. For example: I have abp-ng2-module installed in my angular-cli app.

Then my component uses it 
import { UtilsService } from 'abp-ng2-module/src/utils/utils.service';

if I add my component bit complains about :
```
missing packages dependencies:
          src\shared\component1\component1.ts -> abp-ng2-module/src/utils/utils.service
```

And bit does not list abp-ng2-module as a npm dependency:
bit show
```
Dependencies     │ @angular/common@5.2.5                              ║
║                  │ @angular/core@5.2.5 
```

I would expect abp-ng2-module to be in the dependencies list as well
like 

abp-ng2-module@2.0.0

**Comment by itaymendel** [comment]
module resolution has been implemented (yay) and is available for over a month.
https://docs.bitsrc.io/docs/conf-bit-json.html#resolvemodules--object

I do still think that some issues with Angular might occur, as we failed in implementing a proper compiler. going to wait for Ivy to properly support ang.

for now, i'm closing this issue.
