### ISSUE TITLE
bit hello world is too slow

### ISSUE THREAD

**Issue by airtonix** [teambit/bit#7187]
it took ten minutes to setup the hellow world example...

i didn't bother after that.

I had high hopes for bit.dev, but really guys? npm instead of yarn3 or pnpm?

**Comment by GiladShoham** [comment]
@benjgil I think he meant by 

> I had high hopes for bit.dev, but really guys? npm instead of yarn3 or pnpm?

That bit is using npm when he expects it to use yarn or pnpm.

@airtonix bit is using pnpm by default (@zkochan the maintainer of pnpm is working on bit)
It also uses yarn3 if you prefer.
(Actually, bit is not using npm at all) 
So if you see npm, maybe you are using a very old version of bit?

**Comment by airtonix** [comment]
yeah it might be that. 

I'll try again, because the value proposition of bit.dev seems incredible.

**Comment by HectorOsborneRodriguez** [comment]
I'm just going through the Hello World, and it's extremely slow. 
Creating Environment (slow)
Tagging (slow)
Importing (slow)
exporting (slow)

I have definitively spent more than 10mins just trying the Hello World, I'm about to call it quits.

**Comment by GiladShoham** [comment]
We have found out that installing `puppeteer` when your pnpm store is empty takes most of the time. As puppeteer bring and compile some binaries.
I'm going to remove puppeteer from being part of the default templates and add it as an opt-in plugin.
This should reduce the hello world time a lot (i think at least 50%).
Also still note that this slowness is only on the first hello world as all pnpm cache and store is empty in most cases.
If you try the hello world again on a new folder you will see that it's much much faster.

**Comment by sbland** [comment]
Just set up a new workspace and it took a few minutes to run `bit status` the first time with the logs below:

```
(base) sam@sam-ubu:~/work/sbland/web/tmpd/tasks-workspace$ bit status
✔ linking components
✔ deduping dependencies for installation
✔ running pre install subscribers
.../teambit.react_react-env@0.0.48       |  WARN  deprecated prerender-spa-plugin-next@4.2.3
.../teambit.react_react-env@0.0.48       |  WARN  deprecated puppeteer@13.7.0
.../teambit.react_react-env@0.0.48       |  WARN  deprecated date-format@0.0.2
.../teambit.react_react-env@0.0.48       |  WARN  deprecated querystring@0.2.0
.../teambit.react_react-env@0.0.48       |  WARN  deprecated puppeteer@1.20.0
.../teambit.react_react-env@0.0.48       |  WARN  deprecated stable@0.1.8
.../teambit.react_react-env@0.0.48       |  WARN  deprecated core-js@1.2.7
.../teambit.react_react-env@0.0.48       |  WARN  deprecated source-map-resolve@0.5.3
.../teambit.react_react-env@0.0.48       |  WARN  deprecated sourcemap-codec@1.4.8
.../teambit.react_react-env@0.0.48       |  WARN  deprecated source-map-url@0.4.1
.../teambit.react_react-env@0.0.48       |  WARN  deprecated resolve-url@0.2.1
.../teambit.react_react-env@0.0.48       |  WARN  deprecated urix@0.1.0
.../teambit.react_react-env@0.0.48       |    +1759 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Packages are hard linked from the content-addressable store to the virtual store.
  Content-addressable store is at: /home/sam/.local/share/pnpm/store/v3
  Virtual store is at:             ../../../../../Library/Caches/Bit/capsules/6319ab2201a35710426182a7362e8c555eb30a94/teambit.react_react-env@0.0.48/node_modules/.pnpm
.../teambit.react_react-env@0.0.48       | Progress: resolved 1676, reused 1656, downloaded 0, added 1759, done
```
I didn't think it was excessive and after that it runs instantly but thought I'd add my logs and version for info.
```
  bit version   : 0.1.11
  node version  : v16.16.0
  npm version   : 8.1.0
  yarn version  : 1.22.5
  platform      : linux
```

**Comment by HectorOsborneRodriguez** [comment]
It took 1min to run a ` bit status ` (I use my stop watch) for 2 components + base theme.

Every command seems to stale after you call it. 
Even `bit --help` takes about 20secs to respond (about 5X times slower than any other --help command)
Not sure I can consider that fast

```
bit version  : 0.1.7
node version : v18.15.0
npm version. : 9.5.0
yarn version : 1.22.19
platform.    : macOS
MacBook Pro 2.6GHz i7 / 16GB RAM
```

```
> bit status
new components
(use "bit tag [version]" to lock a version with all your changes)

     > xxx.yyy/breadcrumbs ... ok
     > xxx.yyy/themes/base-theme ... ok
     > xxx.yyy/themes/theme-provider ... ok


modified components
(use "bit tag [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > xxx.yyy/inputs/button ... ok

```

**Comment by GiladShoham** [comment]
On the first `bit status` or almost any bit command, we are fetching and installing the required bit envs for the components.
This also populates pnpm global cache and more. (@sbland this is the output you saw in the bit status)
But we are going to
1. improve the dev experience and the outputs around it so it will be more clear what is going on (I'm working on it right now)
2. remove some long-time dependencies like puppeteer (we already have a PR but still under testing)
 
 About general slowness (like the bit help) we are working on it all the time to improve it.
 Bit is a pluggable system, you can attach custom aspects that register new commands, so these calculations takes some time. but of course, we have more room to improve there, and we are constantly improving it.
 Anyway `bit -h` shouldn't take 20 seconds, and I'll look into it.
 
 @HectorOsborneRodriguez what is the timing you get if you run `bit status` on the second time right away on the same workspace?

**Comment by HectorOsborneRodriguez** [comment]
It took 23seconds to run `bit status` 
I used `time` this time to measure the response and have no bias.


``` 
time bit status
new components
(use "bit tag [version]" to lock a version with all your changes)

     > accenturesong.a11y-comp-lib/breadcrumbs ... ok
     > accenturesong.a11y-comp-lib/themes/base-theme ... ok
     > accenturesong.a11y-comp-lib/themes/theme-provider ... ok


modified components
(use "bit tag [version]" to lock a version with all your changes)
(use "bit diff" to compare changes)

     > accenturesong.a11y-comp-lib/inputs/button ... ok
bit status  4.26s user 1.63s system 24% cpu 23.657 total

**Comment by ggros-septeo** [comment]
Hi everyone,

I'm experiencing the same slownesses than @HectorOsborneRodriguez. Every bit command is slow to run and seems to stale
```
bit version  : 0.1.142
node version : v16.20.0
npm version. : 8.19.4
platform : Windows 11
Intel(R) Core(TM) i7-8565U CPU @ 2.0GHz / 16GB RAM
```

A few capture of some measurement

![image](https://github.com/teambit/bit/assets/134306187/e7cfc3a2-6f07-4764-b39b-1ba09c5524f7)

![image](https://github.com/teambit/bit/assets/134306187/b7a66981-fa48-4613-bb09-2e0d0afe7b97)

I'm in a "professionnal" context with a relatively strict security context (anti-virus, proxy...) not sure if this could be the cause. I'll test at home and let you know if this is the same.

**Comment by benjgil** [comment]
HI @ggros-septeo 
Thanks for your input, it would be interesting indeed to see how these times compare to running at home. Please do add a 'home run' (mind the pun) so we can get some more useful data points for this

**Comment by ggros-septeo** [comment]
Hi,

After some tests at home, it is definitely something on my professional laptop. Everything is running pretty fast and smooth on my personal desktop system.

**Comment by NitsanCohen770** [comment]
Performance has been improved and will continue to improve with the Vite development server.
