### ISSUE TITLE
bit tag command doesn't tag when running inside GitHubAction

### ISSUE THREAD

**Issue by pcperera** [teambit/bit#7191]
Following `bit tag` command is running from GHA. It doesn't update the tags. Is there a way to always bump versions of the components when running the GHA ?

![image](https://user-images.githubusercontent.com/15628990/227498515-87cc070c-27a8-4892-8dd0-69826bd387e4.png)

**Comment by itaymendel** [comment]
Hi,

Please follow the instructions per docs site, as you need to `bit tag --soft` on local to set up all required changes to be tagged.
