### ISSUE TITLE
react-env impossible to alter or disable linting step/config

### ISSUE THREAD

**Issue by PiTiLeZarD** [teambit/bit#7217]
### Describe the bug

I encounter an issue where using the new react-env forces an eslint config and I can't alter it. I've created a new workspace with an env, altered the env to have a composition using a component with one prop defined as typescript. Bit lint will show you an error:

```
linting total of 1 component(s) in workspace 'bitwayup4'

thiswayup.twu/envs/my-react-env

/Users/me/path/to/bitwayup4/twu/envs/my-react-env/scr/test.tsx
  9:39  error  'title' is missing in props validation  react/prop-types

✖ 1 problem (1 error, 0 warnings)


linted 1 components in 98.655 seconds
total of 1 Errors (from 1 components)
```

So I tweaked the eslint config file and nothing does it, I even tried to disable the step completely to no avail.

### Steps to Reproduce

Get the workspace here: https://drive.google.com/file/d/1OAG8zsDOFiPdLrzaivTJXHKDURXJvcII/view?usp=sharing
1. tar -zxf bitwayup4 && cd bitwayup4
1. bit install
1. bit lint

### Expected Behavior

I expect the rules put in the config to be applied during the linting process

### Screenshots, exceptions and logs

Please see file attached

### Specifications

  bit version   : 0.1.11
  node version  : v16.16.0
  npm version   : 8.19.3
  yarn version  : 1.22.18
  platform      : darwin

**Comment by benjgil** [comment]
@GiladShoham FYI

**Comment by PiTiLeZarD** [comment]
Thanks for answering @GiladShoham this has cleared out a couple of things for me. 

Just pointing out that in your scenario, taking that project, adding the component, doing bit start would result in errors with no description file found in node_module/.bit_roots, should I open a new one for this?

**Comment by GiladShoham** [comment]
Try running bit install again.
We are working on that issue right now.
I've just merged a pr couple of hours ago which I hope will fix it

**Comment by PiTiLeZarD** [comment]
Just to keep you posted, running install once leads to an error, running it twice runs fine. But bit start now has tons of issues:
 - Critical dependency: the request of a dependency is an expression
 - Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

and others, previews don't load up anymore. I don't want to add noise to that convo, if an update is coming, I'll wait for that. Just so I know, is it a bit update, a react-env update or something else?

**Comment by GiladShoham** [comment]
@PiTiLeZarD please open a different issue about the bit start, I want to look into it, but it's irrelevant to the current issue.
Also it's already closed, so I might miss comments here
