### ISSUE TITLE
All props shows required in api-ref tab

### ISSUE THREAD

**Issue by mingenesis** [teambit/bit#7230]
https://bit.cloud/teambit/harmony/node/~api-reference?_gl=1*1h5ta3j*_ga*MTk3NjA4MDgwNC4xNjc2ODkyMjk5*_ga_C0T2GH2G99*MTY3NzU3NzMyNy4yMS4xLjE2Nzc1Nzg1NjQuNDcuMC4w&selectedAPI=NodeAppOptions

On this page, it can be seen that portRange should be optional. However, in the Properties table below, it is indicated as required after portRange.

**Comment by benjgil** [comment]
@luvkapur

**Comment by mingenesis** [comment]
Thank you @luvkapur ,
I updated bit to version 0.1.27, and the issue seems to be fixed on my local workspace. However, when I exported it to Bit Cloud, the problem of all properties displaying as required still exists. Can you help me identify the reason for this?
