### ISSUE TITLE
change env to teambit.react/react-env@0.0.50  tag eslint error

### ISSUE THREAD

**Issue by lcz1543812491** [teambit/bit#7241]
### Description

when i change component env from teambit.react/react  to eambit.react/react-env@0.0.50

eslint error 

![WechatIMG25](https://user-images.githubusercontent.com/31276544/229750805-c71508e0-9da2-4b8d-8ac2-d0a5fdaf69d8.jpeg)

how can i  overwrite  the eslint rules

### Specifications

- Bit version: 0.1.11
- Node version:  v16.19.1
- npm / yarn version:  npm : 8.19.3,   yarn: 1.22.19
- Platform: macos
- Bit compiler (include version):
- Bit tester (include version):

**Comment by GiladShoham** [comment]
That's expected
In the core react we didn't have the lint task as part of the pipeline, while with the new one, it's part of it.
If you want to change rules you need to create a custom env see here - https://bit.dev/docs/react-env/set-up-your-env
Then see here how to change the eslint config
https://bit.dev/docs/react-env/dev-tool-config
(the sentence there says "jest" but the link is correct, I'll make sure to fix the sentence later)

**Comment by giuliano-abinbev** [comment]
I have created a custom react env and disabled one of the rules, but still getting the error. 

I tried with

```
bit clear-cache
bit ws-config write
bit lint
```

but still getting it

![Screenshot 2023-11-08 at 20 24 48](https://github.com/teambit/bit/assets/144352874/345d8467-b0dc-48de-bda6-ee173e51e958)

![Screenshot 2023-11-08 at 20 25 04](https://github.com/teambit/bit/assets/144352874/33fa9b40-67f6-46d4-9cf2-7d29452c9d68)

![Screenshot 2023-11-08 at 20 25 13](https://github.com/teambit/bit/assets/144352874/101e3362-93bd-4bda-960c-58466eaada9f)
