### ISSUE TITLE
Cannot install private npm package as dependency

### ISSUE THREAD

**Issue by Azrt** [teambit/bit#7256]
### Description

I've switched from `0.0.697` version of Bit and want to test the newest one, but i'm having an issue with my private npm package. Credentials are set in `.npmrc` correctly (previous version of Bit builds as expected), but after `bit install` I get 404 error:

```
GET https://gitlab.com/api/v4/projects/xxxx: Not Found - 404

No authorization header was set for the request.
```

### Specifications

- Bit version: 0.1.11
- Node version:  v16.18.1
- npm / yarn version: 1.22.17
- Platform: macOS 13.2
- Bit compiler (include version): 
- Bit tester (include version):

### Context and additional information

Maybe there was a breaking change somewhere between versions `0.0.827` and `0.0.1000`, because first one is executing `bit install` command as expected, while second one throws same error.

**Comment by GiladShoham** [comment]
Can you share your npmrc file (token stripped)
@zkochan fyi

**Comment by Azrt** [comment]
Sure :) 
![Zrzut ekranu 2023-04-7 o 18 33 37](https://user-images.githubusercontent.com/6348177/230647078-0ac13783-c83d-4b31-ba66-6aeee75da80d.jpeg)

**Comment by itaymendel** [comment]
Which component you are not able to install? the 404 you shared does not tell much.
Ideally we should be able to figure out, from your error, which package or component is not resolving correctly.

**Comment by Azrt** [comment]
Ok soooo:
- i am using private npm package stored in gitlab which is installed as dependency in `workspace.jsonc`
- After switching to one of newer versions of `bit` i'm getting error below during `bit install` command:

<img width="492" alt="Zrzut ekranu 2023-04-10 o 11 40 36" src="https://user-images.githubusercontent.com/6348177/230877814-7dfb3984-5ae4-4f5a-a87d-32cc21f0f2af.png">

- But, moving back to, for example version `bvm use 0.0.827`, everything is passing correctly :)

<img width="486" alt="Zrzut ekranu 2023-04-10 o 11 45 08" src="https://user-images.githubusercontent.com/6348177/230877997-3f532fbf-709e-49a9-8b38-2bf198b25e57.png">

**Comment by itaymendel** [comment]
please see this ticket on gitlab

https://gitlab.com/gitlab-org/gitlab/-/issues/352962

also, please delete your lockfile

**Comment by zkochan** [comment]
Does it help if you add the token like this in `.npmrc`?

```
//gitlab.com/api/v4/projects/:_authToken=${GITLAB_NPM_TOKEN}
```

source: https://github.com/npm/cli/issues/3134#issuecomment-825812301

**Comment by itaymendel** [comment]
closing the issue as the original author stopped responding and several solution been suggested.
