### ISSUE TITLE
Getting Error: 403 Message: Forbidden 

### ISSUE THREAD

**Issue by Abhishek-microcosmworks** [teambit/bit#7260]
Getting an error: 403 message: forbidden when I clicked on the scope it show 404 not found checked for the access I do have the access for that particular scope still getting this error
![Screenshot from 2023-04-11 15-01-03](https://user-images.githubusercontent.com/114899259/231118010-472d476d-e888-4f45-b52e-444542fec45b.png)

**Comment by GiladShoham** [comment]
please email support@bit.dev

**Comment by itaymendel** [comment]
this is likely a result of a subscription issue. please reach out to support as suggested by @GiladShoham and provide relevant information on the account at hand.
i'm closing this topic, as this is unrelated to the oss product.

**Comment by Abhishek-microcosmworks** [comment]
Thank you for the response it was subscription issue now it is resolved.
