### ISSUE TITLE
How to output packages in ESM format

### ISSUE THREAD

**Issue by jerry-mengjie** [teambit/bit#7265]
The default output package is commonjs format, How to output packages in ESM format

### Specifications

- Bit version:  0.1.11
- Node version: v16.17.0
- npm / yarn version:
- Platform:  Apple M1 Pro 
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
Bit outputs ESM outputs by default.
for example - run `bit new react my-workspace --env teambit.react/react-env --default-scope my-org.my-scope` and any component you create, will be ESM.
