### ISSUE TITLE
React Native Typescript Debugging Issue - Breakpoints Not Hit

### ISSUE THREAD

**Issue by cloudprogrammer** [teambit/bit#7268]
### Description

I'm using bit with a react native project in typescript and am having trouble debugging my bit components. I'm using webstorm/phpstorm and when I attach the debugger I can see that the components are included under node_modules but only the `.js` files under the dist folder, so my breakpoints inside the .tsx files aren't hit but if i breakpoint the compiled js files they are hit. 

### Specifications

- Bit version: 0.0.1000
- Node version: v14.16.1
- npm / yarn version: 7.13.0
- Platform: Mac
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

Funnily enough, if I import components directly eg `import x from '../ra1n-components/ui/text-view'` the ts breakpoints are hit is that a viable workaround? I know we're not supposed to use direct imports but I'm at my wits end.

![Screen Shot 2023-04-14 at 12 21 08 am](https://user-images.githubusercontent.com/7554320/231789462-c5a68ec5-7e54-4da8-8e06-6f3ea038e8b3.png)

I've messed around with metro.config.js with: 
```
watchFolders: [`${path.resolve(__dirname)}/ra1n-components/`, `${path.resolve(__dirname)}/node_modules/@ra1n-components`]
```
and the root tsconfig.json
```
"sourceRoot": "/ra1n-components",
    "preserveSymlinks": true,
  },
  "include": ["./ra1n-components"]
``` 
But nothing seems to work apart from the direct imports, any help is appreciated, thanks in advance!

**Comment by NitsanCohen770** [comment]
Please use the latest [react native env](https://bit.cloud/teambit/react/react-native-env) this should be resolved.
