### ISSUE TITLE
Err: while initializing default workspace

### ISSUE THREAD

**Issue by iamayushdas-acc** [teambit/bit#7288]
### Describe the bug

While initializing a new react workspace i am getting errors and deprecation warnings.

### Steps to Reproduce

1. Just hit this stated command to CLI - bit new react tasks-workspace --aspect teambit.react/react-env --default-scope jukebox-again.components.
2. on a very first line it gives the following error

### Expected Behavior

It should create a react workspace with no errors

### Screenshots, exceptions and logs

<img width="723" alt="image" src="https://user-images.githubusercontent.com/130970626/233370927-eafa5b23-9187-47c0-8806-8265c7fc1eb3.png">

### Specifications

- Bit version:  0.0.945
- Workspace type: (harmony/legacy)
- Node version: 16.17.1
- npm / yarn version: 9.3.1
- Platform: windows

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi, seems like you are using a very old version of bit. please update your local installation with `bvm install` and try again.

**Comment by iamayushdas-acc** [comment]
Hey! even  after adding new version of bit  i.e; 0.1.11 its giving the following error.

<img width="749" alt="image" src="https://user-images.githubusercontent.com/130970626/233380600-0d51b4ac-6425-4b1f-8956-493a86f0e39d.png">

**Comment by iamayushdas-acc** [comment]
> solved by - #7286 will be part of next stable release

when can we expect next stable release?

**Comment by GiladShoham** [comment]
hopefully on Sunday, but it's not finalize yet.
