### ISSUE TITLE
Compatibility issues with NextJS 13 

### ISSUE THREAD

**Issue by iamayushdas-acc** [teambit/bit#7289]
### Description

while using the deployed the bit react component in NextJs its giving errors. 
React/React-dom version in my NextJs is 18.2.0, but by default in bit its 17.0.2.

### Specifications

- Bit version: 0.0.945
- Node version: 16.17.1
- npm : 9.3.1
- Platform: windows
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
Hi, we moved defaults to react18.
i recommend updating bit and looking into the new environment options for React.
you can read more on this here:
https://bit.dev/blog/migrate-to-new-component-development-environments-lfhd699k/
https://bit.dev/blog/introducing-react-component-development-environment-lfhd699k/

**Comment by iamayushdas-acc** [comment]
creating new workspace command is not working, tried it multiple times

<img width="719" alt="image" src="https://user-images.githubusercontent.com/130970626/233533468-9bddbd79-076f-47f3-a734-6512736b7730.png">
