### ISSUE TITLE
Command/flag to add bit.json to a component i just created

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#73]
when i issue a `bit create` command, it only create a implementation file. sometimes, while coding, i understand that i need some additional dependencies for the component, which are managed in it's bit.json. however, i haven't added the -j flag when creating the component. this means that the only possible way to add a bit.json file, is to manually add it.
i suggest re-reunning the `bit create` command, on the same componentID, with the additional -j flag, will simply add a bit.json file.

**Comment by ran-y** [comment]
solved on 2ea6d31
