### ISSUE TITLE
URL imports feature bit dev

### ISSUE THREAD

**Issue by renhiyama** [teambit/bit#7308]
### Description

Allow importing components directly from public bit.dev into project via URL imports. 
### Describe the solution you'd like
Provide documentation and ready to copy urls that let me import the components

### Describe alternatives you've considered
Publishing components to npm, and using a service like esm.sh to provide URL importing of npm modules.

**Comment by itaymendel** [comment]
hi, bit.cloud/dev is not meant for read-time (production) imports for your app. the system is not build for that.
you can add a build task to deploy your components to a CDN and achieve this solution. as it stands, this is not a core feature we aim to support.

we may support it in the future.

**Comment by renhiyama** [comment]
Hi @itaymendel, URL imports are not only for browsers. Infact that you can serve jsx files and it can be used by deno also opens an area of possibility.

**Comment by itaymendel** [comment]
i'm not against it. however, this is a separate discussion from bit.dev as an oss tool and bit.cloud as a hosting provider for components and the features it provides.
