### ISSUE TITLE
using bit component in nextjs is giving error.

### ISSUE THREAD

**Issue by prabhupadaswain** [teambit/bit#7321]
Importing a bit component in nextjs project. I am getting "SyntaxError: Unexpected token 'export'

Server Error
SyntaxError: Unexpected token 'export'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
/Users/prabhupada.swain/Documents/neeNextproject/jukebox/node_modules/ (jukebox-assets/ecommerce-components.organisms.header/dist/index.js (1)

**Comment by itaymendel** [comment]
i'm unsure on the error, can you please share a complete context and how to reproduce this?
Sadly without it's hard for me to understand what is holding you back.
From the looks of it, it seems like NextJS needs this configuration:
https://nextjs.org/docs/advanced-features/compiler#module-transpilation
However, I can't be sure of that.
Can you please provide additional information?
- how the component was installed
- how you use the component in the code
- how does package.json looks like
- how does next.js configuration looks like
- complete error

**Comment by trongbinh15** [comment]
I got the same issue. 
Here is my components:
https://bit.cloud/trongbinh15/lfw/hooks/use-dark-mode
https://bit.cloud/trongbinh15/lfw/components/market-common-chart

I have attempted to add `type: module` (package.json) in the custom envs, the hook  is working but the chart is not

next.js configuration is the same

Appreciate any help

**Comment by sbland** [comment]
@trongbinh15 did you resolve this? I get this issue for a node js environment component. Oddly it seems to only effect my component when I also install `"@teambit/preview.react-preview": "^1.0.23"` which is required by a different environment.
