### ISSUE TITLE
not npm package

### ISSUE THREAD

**Issue by xiaofeifei112** [teambit/bit#7323]
### Describe the bug

@teambit/defender.fs.global-bit-temp-dir
@teambit/node.deps-detectors.detective-es6
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/25787762/234530813-de527841-d592-4c1a-8f7e-bf71f55e29ba.png">

A clear and concise description of the issue.

### Steps to Reproduce

1.
1.
1.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Workspace type: (harmony/legacy)
- Node version:
- npm / yarn version:
- Platform:

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
Hi,

Components are available to be installed via `node.bit.cloud` registry, as suggested on each component's page.
Run the following command to configure your `.npmrc` file.
```
npm config set '@teambit:registry' https://node.bit.cloud
```
