### ISSUE TITLE
bit start runs a blank page + loading indicator with teambit.envs/env

### ISSUE THREAD

**Issue by anguyen118** [teambit/bit#7356]
### Describe the bug

I just start to try out bit and run into this issue when following this docs
https://bit.dev/docs/react-env/set-up-your-env/#create-a-react-env

### Steps to Reproduce

1. run `bit new react my-workspace --env teambit.react/react-env --default-scope my-org.my-scope`
2. cd my-workspace 
3. run `bit install @teambit/react.react-env`
4. run `bit start`

### Expected Behavior

The browser should display the preview page properly

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/19172729/236139600-90ad39db-7c54-4532-a211-af61d1c251ca.png)

![image](https://user-images.githubusercontent.com/19172729/236139679-05b5e8b8-e05b-47bb-be2d-f206cc49e120.png)

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 0.1.27
- Workspace type: harmony
- Node version: 18.15.0
- pnpm version: 8.4.0
- Platform: window

*for harmony workspace*
- relevant env: teambit.envs/env
- relevant aspects

**Comment by GiladShoham** [comment]
Thanks for reporting this, solved by - https://github.com/teambit/bit/pull/7357
