### ISSUE TITLE
[Performance] scope loads 20s before a flicker-free experience begins

### ISSUE THREAD

**Issue by mmailaender** [teambit/bit#7372]
### Describe the bug

Loading our scope `dechea/hes` takes 20 seconds, to interact without flicker. 
It loads almost 50 seconds to load also the preview images that I use as orientation for what component I want to select (If I'm in the discovery mode)

### Steps to Reproduce

1. Load https://bit.cloud/dechea/hes
1.
1.

### Expected Behavior

Flicker-free experience should start after max. 1-2 seconds.
The preview pictures for the first 10 pictures should be visible after max. 3-4 seconds.

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/87228994/236764608-576cfe2e-2d16-4878-aa13-3ba645cac8d7.png)
![image](https://user-images.githubusercontent.com/87228994/236764693-a83a83d7-d9c7-4e04-828b-b5cda0e3db1f.png)

### Specifications

- Browser: Chrome Version 112.0.5615.138
- Workspace type: harmony

*for harmony workspace*
- relevant env
- relevant aspects

**Comment by itaymendel** [comment]
hi,

there's a massive refactor deployed soon to completely re-do the scope system. this significantly improved timings.
we'll send a global notice for all once available.

as for the previews - these are not pictures, they are actually scaled rendering of the component previews. so loading them is also slightly different approach (iframes, etc).

as this is unrelated to the Bit open source, but rather a part of the proprietary bit.cloud service, i'm closing this issue. i expect the upgraded experience for bit.cloud to be available in the next 4 weeks. if you want early access, reach out directly to bit.cloud .
