### ISSUE TITLE
Shell not detected - Ubuntu 22.04

### ISSUE THREAD

**Issue by mmailaender** [teambit/bit#7373]
### Describe the bug

Trying to install Bit on [Gitpod](https://www.gitpod.io/) (Ubuntu 22.04). It fails, because the SHELL is not getting detected.

![image](https://user-images.githubusercontent.com/87228994/236766479-bc0bbed9-9c8e-4937-8fe9-310ef06e7883.png)

### Steps to Reproduce

1. Start https://gitpod.io/#https://github.com/mmailaender/Components/tree/main
2. Wait until the error appears in the terminal (The command `npx @teambit/bvm install` will be executed automatically during start)

### Expected Behavior

Bit should detect the Shell of Ubuntu 22.04 automatically.

### Specifications

- Bit version:
- Workspace type: harmony
- Node version: v18.16.0
- pnpm version: 8.3.1
- Platform: Ubuntu 22.04 (Gitpod)

**Comment by GiladShoham** [comment]
The installation doesn't really fail, it's just the automatic setting the path that is failing.
(many times it's not even required)
@zkochan can we recognize this shell?

**Comment by zkochan** [comment]
Looks like this works on gitpod to detect the shell: `cat /proc/$$/cmdline`

**Comment by mmailaender** [comment]
Works! Thx :) - For the case that you're creating a Gitpod starter template in the future, this could be included there ;)
