### ISSUE TITLE
[Docs] Search bar on mobile

### ISSUE THREAD

**Issue by mmailaender** [teambit/bit#7394]
### Description

On mobile there is no search bar to search the docs. 
![Screenshot_20230511-125923](https://github.com/teambit/bit/assets/87228994/c16e2762-a214-4d8c-9a07-e15c76ee7021)

### Describe the solution you'd like

Having a search bar to search for specific terms. 

### Describe alternatives you've considered

Using Google - unfortunately the search result are not every time helpful, because "bit" is an ambigous word (bit is used almost everywhere like "a little bit").

**Comment by GiladShoham** [comment]
@giteden FYI

**Comment by NitsanCohen770** [comment]
fixed on this CR: https://new.bit.cloud/teambit/community/~change-requests/add-search-mobile
@giteden please merge
