### ISSUE TITLE
bit tag publishes tgz with a tgz inside doubling the component size

### ISSUE THREAD

**Issue by athospg** [teambit/bit#7400]
### Describe the bug

When a component is published it contains itself in the generated tgz, making it double the size.

### Steps to Reproduce

1. Create a component
2. Publish it
3. Check the file send to the server

### Expected Behavior

Do not include the folder "package-tar"

### Screenshots, exceptions and logs

![image](https://github.com/teambit/bit/assets/6840773/f1709b2b-2a3d-4f58-ad6a-574b7b4eaea8)

### Specifications

- Bit version: 0.1.11
- Node version: v16.16.0
- npm version: 8.19.1
- Platform: Windows 11

**Comment by GiladShoham** [comment]
Thanks we will check it.
Do you have any special config for the pkg aspect?

**Comment by GiladShoham** [comment]
This was resolved some time ago.
I wasn't able to reproduce it.
But anyway to ensure it's never come back I've added this to npm ignore always.
See

https://github.com/teambit/bit/pull/7817
