### ISSUE TITLE
Issue: Environment not found

### ISSUE THREAD

**Issue by iamayushdas-acc** [teambit/bit#7405]
### Description

Cannot find the environment with id: xxxx

### Specifications

- Bit version:0.1.11
- Node version:16
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

### Context and additional information

![MicrosoftTeams-image (8)](https://github.com/teambit/bit/assets/130970626/6caaf8c6-c025-4b3d-996b-97d0d94d1d27)

**Comment by GiladShoham** [comment]
Is this environment part of your workspace (in bitmap) or not?

**Comment by prabhupadaswain** [comment]
Yes, environment is added in bitmap. 
<img width="1075" alt="Screenshot 2023-05-15 at 5 54 19 PM" src="https://github.com/teambit/bit/assets/130156910/1549ddd0-e3aa-4538-b14c-1d0f426030ef">

**Comment by itaymendel** [comment]
issue resolved on a different private thread
