### ISSUE TITLE
fatal: unable to connect to a remote legacy SSH server from Harmony client

### ISSUE THREAD

**Issue by chujain-fang** [teambit/bit#7433]
when I   run bit import bit.envs/bundlers/vue
it occured.
when i run others  command。such as  bit import teambit.vue/examples/my-vue-env。it worked well
I am confused。can U give me some advice，thanks for Ur time！！！

**Comment by GiladShoham** [comment]
you shouldn't use `bit.envs/bundlers/vue`
this is a very old version which is not maintained for a couple of years.
it was built for the old version of bit and it's not supported any more.
you should use the `teambit.vue` scope.

this is not a bug, it's by design.
