### ISSUE TITLE
Bit received an error loading teambit.react/react-env@0.0.63

### ISSUE THREAD

**Issue by Mistrain-y-y** [teambit/bit#7442]
I am trying creating a new workspace:
> $ bit new react tasks-workspace --aspect teambit.react/react-env --default-scope my-org.tasks-scope

bit 0.1.48
macOS 12.3

Why I get this error:
<img width="568" alt="image" src="https://github.com/teambit/bit/assets/72647648/c4f43818-8a9c-41b1-8210-48523850d7d0">

**Comment by GiladShoham** [comment]
please run `bit install` again.
i'm working on that issue right now.

**Comment by Mistrain-y-y** [comment]
But `bit install` can only run inside a bit workspace. 
I want to create a workspace first.

**Comment by GiladShoham** [comment]
ohhh ok, it's in the global scope.
you can run it again with `--log` so you will see the capsule path.
Then try to delete the capsule folder.

**Comment by Mistrain-y-y** [comment]
wow, it works.
I want to know what happened after I deleted the capsule folder, 
and what caused my error.

**Comment by itaymendel** [comment]
it's likely that the capsule for `teambit.react/react-env` was not created correctly (maybe you stopped the operation mid way, as this usually happens). this caused installation to not run there, and that dependency to not get resolved.
by deleting the capsules you forced bit to re-create it.

we are working to remove the coupling between `bit new` and capsules, which will solve this completely.
