### ISSUE TITLE
trying to delete a bitcloud component

### ISSUE THREAD

**Issue by Dricosta** [teambit/bit#7468]
### Describe the bug

i am trying to delete my component from the remote scope (bit cloud) with the following command: `bit remove company.design-system/components/form --hard`

then I get the message: successfully removed from the remote scope: company.design-system/components/form but when access my components in the bit cloud I realize that the form component still exists

- I'm trying to delete with an admin user
- I already tried clearing the browser cache and opening bit cloud in an incognito tab
- I tried accessing the tab https://new.bit.cloud

I talked about it with @benjgil in slack thread https://bit-dev-community.slack.com/archives/CCBF6L9KJ/p1684936148374419  

### Steps to Reproduce

bit remove company.design-system/components/form --hard

### Screenshots, exceptions and logs

![Screen Shot 2023-05-29 at 09 39 39](https://github.com/teambit/bit/assets/29208470/9a5a6f92-0e1b-42c4-bd18-1025aef31fa8)

![Screen Shot 2023-05-30 at 09 37 59](https://github.com/teambit/bit/assets/29208470/ab3f1626-8866-4535-ba85-916c9e27a335)

### Specifications

- Bit version: 0.1.48
- Workspace type: harmony
- Node version: v16.14.2
- npm / yarn version: npm 8.5.0 / yarn 1.22.17
- Platform: MacOS

**Comment by GiladShoham** [comment]
This is an issue with the cloud platform and not related to the OSS project, so I'm closing the issue here.
anyway, the team is working on it and it should be resolved soon.
