### ISSUE TITLE
`template "react" was not found` even for the latest version of bit

### ISSUE THREAD

**Issue by jiyiwohanxing** [teambit/bit#7488]
### Describe the bug

Running `bit create react component-name --scope scope-name --aspect aspect-name` in my workspace.
I get the following error template "react" was not found but running bit templates returns....
I found the same [issue](https://github.com/teambit/bit/issues/7158) happens here but my bit version is the latest, it doesn't work either.

### Expected Behavior

should create a new react component

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 0.1.52
- Workspace type: harmony
- Node version: v16.20.0
- yarn version: 3.5.0
- Platform: MacOS

**Comment by itaymendel** [comment]
hi, please provide the complete command you are trying to run, as the template should come from a specific aspect. so if you have a typo in your aspect, it'll be a reason for this issue.

**Comment by itaymendel** [comment]
closing the issue the author does not respond.
