### ISSUE TITLE
Error bulding typescript components

### ISSUE THREAD

**Issue by molandim** [teambit/bit#755]
## Expected Behavior
To have a live example of the component in the scope webpage

## Actual Behavior
There is no live view, only the content generated by the jsdocs from the component.

In the build output I am seeing this:
```
---------------------------Creating isolated environment---------------------------
objects
scope.json
tmp
---------------------------Running build and tests---------------------------------
builded Files:
src/components/button-styled-component/button-styled-component.js.map
src/components/button-styled-component/button-styled-component.js
(node:46) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
/bit-renderer/index.js:14
    if (err) throw new Error(err);
             ^
Error: ModuleNotFoundError: Module not found: Error: Can't resolve 'Component' in '/bit-renderer/dist/utils'
```

## Steps to Reproduce the Problem

  1. Create any simple component in react-typescript
  2.Add the componet
  3.Tag the component
  4.Export the component

## Specifications

  - Version: Using typescript 2.7 (Don't believe that is the issue)
  - Platform: Mac

**Comment by itaymendel** [comment]
hi @molandim 
the render feature is still in early stages of development, and not yet stable.
there are still some issues to resolve. I'll keep this task open until the feature is stable, and close it then, so you get notified. i believe that it will be available later next week.

at any case, this does not affect your component build task, as it runs separately (but uses the same log). so the same build outcome that you get locally using the build env will be generated by the server. as the 'render' task runs as a [separate extension](https://docs.bitsrc.io/docs/ext-developing-extensions.html).

**Comment by molandim** [comment]
Thanks @itaymendel !

Is this error related with the fact there is no live preview of my component in the scope?

**Comment by itaymendel** [comment]
yes. it relates to the extension we are currently developing...

**Comment by itaymendel** [comment]
issue resolved, as the feature is properly deployed and usable.
see docs here - https://docs.bitsrc.io/docs/rendering-components.html
