### ISSUE TITLE
missing breaklines in output

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#764]
## Expected Behavior

when listing missing packages/dependencies/etc, each list should have its own line

## Actual Behavior

<img width="1265" alt="screenshot 2018-02-13 12 58 48" src="https://user-images.githubusercontent.com/4623056/36146582-cf9ea3e0-10bd-11e8-9f2e-88ce08a68277.png">

## Steps to Reproduce the Problem

  1. import component
  1. modify component
  1. run `bit status`

## Specifications

  - Version: 0.12.5
  - Platform: macOS

**Comment by GiladShoham** [comment]
solved
