### ISSUE TITLE
Support pnpm

### ISSUE THREAD

**Issue by vjpr** [teambit/bit#766]
[pnpm](https://github.com/pnpm/pnpm) is the fastest package manager out there. 

How difficult would it be to support it?

There is a command called `pnpm recursive install` and `pnpm recursive link` which can perform a similar function as Yarn's workspaces. The yarn workspaces issue is available here: https://github.com/pnpm/pnpm/issues/839.

**Comment by itaymendel** [comment]
hi @vjpr 
i had no idea pnpm can support that!

we have looked into supporting pnpm as another client for installing packages for components, and right now it is still in our backlog of tasks.

knowing now that it can support yarn-workspaces like feature is very interesting, so we will take a look at it and see how and when we can introduce supporting pnpm as a client.

i'm keeping this task open so you will get updates once we start working on it.
