### ISSUE TITLE
Watchpack Error (watcher): Error: EMFILE: too many open files, watch (with solution)

### ISSUE THREAD

**Issue by Nehemek** [teambit/bit#7675]
### Describe the bug

Seems that when working on MacOS and possibly specifically on ARM macs, when you set a custom local environment webpack fails.

### Steps to Reproduce

1. Use an ARM Mac
2. Run ``bit new hello-world my-hello-world --env teambit.community/starters/hello-world``
3. Run ``bit set envs hello-world-app envs/my-react-env`` to set the env of one of the default components to the example env.
4. Run ``bit start``and watch the compiling process get stuck (happened in a 16GB and 8GB RAM machines).

### Provisional or Actual Fix (?)

While researching we joined Bit's Slack server and found a comment from one of the devs from one month ago to set ``WATCHPACK_POLLING = true`` on the bash profile (or setting it in .zshrc did the trick) and that seems to fix the issue. The user reporting the problem is also using ARM Macs.

We looked around here in the Github Issues and StackOverflow and didn't see an open issue that matches the problem or mentions the solution, so, for visibility (since you need to register and search through the slack), we post it here.

### Expected Behavior

Bit dev server should start, compile and not hang/crash. The dev that suggested the fix mentioned possibly setting this flag as true by default on a future release.

### Specifications

- Bit version: 0.1.62
- Workspace type: (harmony/legacy)
- Node version: v18.16.0
- npm version: 9.5.1
- Platform: MacOS Ventura 13.4.1, M2 base chip and M1 Pro chip.

**Comment by benjgil** [comment]
Thanks for this :) 

Yes i can confirm that setting an env variable `WATCHPACK_POLLING = true` resolves this issue. 
And with that we can close this issue and leave it for anyone who needs it as a reference to come and see the solution

**Comment by GiladShoham** [comment]
Also the watch pack polling is now by default in the few latest versions

**Comment by Nehemek** [comment]
Thank you too.

**Comment by 9mm** [comment]
rebooted and it worked......... very curious what caused this on OSX with M2
