### ISSUE TITLE
Tailwindcss style won't work in nextjs project (Please help)

### ISSUE THREAD

**Issue by charismanapriandi** [teambit/bit#7692]
### Description

I try to use my bit component in next.js project, but the style is not working. 

this is what I do:
1. create a bit component with tailwindcss | [here](https://bit.dev/blog/integrating-tailwind-css-and-bit-for-component-styling-lgntqstt/)
2. publish to bit.cloud (it's working properly on the cloud)
3. [set a scoped using NPM registry](https://bit.dev/reference/packages/npmrc/#set-a-scoped-registry-using-npm-cli) 
4. install the component with yarn `yarn add @scope/component@version`
5. use components in the project

### Specifications

- Bit version: 0.1.74
- Node version: 19.0.0
- yarn version: 1.22.19
- Platform: macOS ventura 13.4
- Bit compiler (include version): unknown
- Bit tester (include version): unknown

### Context and additional information

`
// .bitmap
{
    "config/tailwind": {
        "scope": "charismanapriandi.untitled-ui",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "untitled-ui/config/tailwind"
    },
    "envs/my-react-env": {
        "scope": "charismanapriandi.untitled-ui",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "untitled-ui/envs/my-react-env"
    },
    "helper/remove-leading-zero": {
        "scope": "charismanapriandi.untitled-ui",
        "version": "0.0.1",
        "mainFile": "index.ts",
        "rootDir": "untitled-ui/helper/remove-leading-zero"
    },
    "ui/button": {
        "scope": "charismanapriandi.untitled-ui",
        "version": "0.0.3",
        "mainFile": "index.ts",
        "rootDir": "untitled-ui/ui/button"
    },
    "$schema-version": "15.0.0"
}
`

button dependencies 
![image](https://github.com/teambit/bit/assets/68155110/31fabc66-e720-43f5-92c1-4740ae9a65b0)

**Comment by itaymendel** [comment]
issue abandoned by the reporter. closing.
