### ISSUE TITLE
error: "@teambit.react/react-env" is invalid, component scope names can only contain alphanumeric, lowercase characters, and the following ["-", "_", "$", "!"]

### ISSUE THREAD

**Issue by gopendrajangir** [teambit/bit#7741]
I created a new workspace using the command:
bit new react-native reusable-components --env teambit.react/react-native-env --default-scope gopendra.react-native-components

After that i ran the command: bit templates

But it is giving me the error:
"@teambit.react/react-env" is invalid, component scope names can only contain alphanumeric, lowercase characters, and the following ["-", "_", "$", "!"]

Bit version: 0.2.14

**Comment by itaymendel** [comment]
seems like there's a small typo in the template. please open the `worksapce.jsonc` file, head down to line 62 and remove the `@` symbol.
