### ISSUE TITLE
Bit rename get error: Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by aliansyahFirdaus** [teambit/bit#7749]
### Describe the bug

I encountered an error when attempting to rename the component I created

### Steps to Reproduce

1. create component `bit create react-component atoms/paragraf`
2. rename component `bit rename atoms/paragraf atoms/paragraph --refactor`

### Expected Behavior

component successfully renamed

### Screenshots, exceptions and logs
![Screenshot 2023-08-06 at 23 51 10](https://github.com/teambit/bit/assets/74974463/7aa421cf-0e60-4204-aceb-54ab38ff1809)

### Specifications

- Bit version: 0.2.14
- Workspace type: (harmony)
- Node version: 18.16.0
- npm / yarn version: 1.22.19

**Comment by aliansyahFirdaus** [comment]
when I create a new bit project then I reproduce the error again, there is this error

![Screenshot 2023-08-07 at 10 50 33](https://github.com/teambit/bit/assets/74974463/2d1890a4-6d43-459a-be9d-5db622e26b26)

`Cannot read properties of undefined (reading 'text')`

**Comment by benjgil** [comment]
HI @aliansyahFirdaus 
Thanks for reporting.
This has been fixed and will be part of the next stable release.

**Comment by aliansyahFirdaus** [comment]
temporary solution, downgrade bit version to 0.1.74, and it works

**Comment by GiladShoham** [comment]
This should be fine with latest stable (0.2.24)
