### ISSUE TITLE
react-native-env template was not found + npm get not found

### ISSUE THREAD

**Issue by Neaxic** [teambit/bit#7843]
### Describe the bug

Setting up a new repo for bit component development, in a react-native envioment. Following your docs + this article.

https://bit.dev/blog/building-scalable-react-native-apps-with-independent-bit-components-lixj8lgq/ 
https://bit.dev/docs/react-native-env/set-up-your-env

All i have done this far is on a clean repo with nothing, did bit init successfully. Getting the environment set up like you describe in the article and docs seems to be unable

### Steps to Reproduce

1. Clean fresh codebase
2. Bit init

Either one gives error
- npm i @teambit/react.react-native-env
- bit new react-native-env my-workspace --env teambit.react/react-native-env --default-scope org.scope
- bit create teambit.react/react-native react-native-env

### Expected Behaviour

Well id expect it to go through, did the steps in docs & article. - copied the commands directly.

### Screenshots, exceptions and logs

![image](https://github.com/teambit/bit/assets/36155981/481dfbd8-bccc-49d0-b82b-b1b8b104f094)
![image](https://github.com/teambit/bit/assets/36155981/4c0c433f-566a-4cf3-b724-8a6b671916c1)

### Specifications

- Bvm version: 0.4.4
- Bit version: 0.2.24
- Workspace type: Unsure
- Node version: v16.15.1
- npm / yarn version: npm 8.18.0
- Platform: Windows

**Comment by GiladShoham** [comment]
@Neaxic you don't need the npm i command.
You might want to look on the official docs.
@NitsanCohen770 @giteden do we have a more up to date tutorial about it?

**Comment by Neaxic** [comment]
@GiladShoham Noted, however similar error persists when doing bit create & bit new, like the error report states.

**Comment by NitsanCohen770** [comment]
Hi @Neaxic, sorry for the inconvenience. This blog post is not updated.
Please follow the guide in the[ react native learn section](https://bit.dev/docs/react-native-intro).
`bit new` and `bit create` are also not up to date. There is a [big PR ](https://github.com/teambit/bit/pull/7804)that is waiting to get merged, and it will fix it. Good luck! Don't hesitate to contact me for further guidance.

**Comment by Neaxic** [comment]
@NitsanCohen770 Appreciate your kind and helpful response.
If bit new and bit create does not work though, and the docs you provided states that i should use those. What am i then supposed to do, if my intent is to setup a new react native env.

**Comment by NitsanCohen770** [comment]
@Neaxic My apologies for the confusion. I understand where the disconnect is happening.

To clarify:
- The `bit new` and `bit create` commands are functioning correctly.
- The templates you currently see when running `bit templates` are from the old environments, and they shouldn't be used. The PR I mentioned is intended to resolve this issue by removing these outdated templates.

Once that PR gets merged, you won't see those old templates anymore. If you follow the `bit new` and `bit create` commands as outlined in the official docs, they should work perfectly. The primary distinction is the usage of the `--aspect` flag, which loads the template from the environment.

Again, I'm sorry for the oversight and any inconvenience caused. Please let me know if you face any other issues or need further clarification.

**Comment by gokulkulkarni1987** [comment]
@Neaxic where u able to resolve the issue? I am facing similar issue.
