### ISSUE TITLE
 ERR_PNPM_REGISTRIES_MISMATCH  

### ISSUE THREAD

**Issue by piotrkulpinski** [teambit/bit#7871]
### Description

Hi, 
I'm trying to set up Bit components in my project (again), but I'm running into this issue, where I can't install any external packages after I run `bit install` due to the pnpm error: 

```
This modules directory was created using the following registries configuration: {"@bit":"https://node.bit.cloud/","default":"https://node.bit.cloud/"}. The current configuration is {"default":"https://registry.npmjs.org/","@bit":"https://node.bit.cloud/"}. To recreate the modules directory using the new settings, run "pnpm install".
```

Is there any way to fix this permanently so that I don't run into it every time I do `bit install` or `pnpm install`?

Thanks

### Specifications

- Bit version: 0.2.40
- Node version: 16.20.0
- Pnpm version: 8.7.1
- Platform: MacOS

**Comment by zkochan** [comment]
This should only happen if you changed your registry settings. `bit install` should fix it. It should not happen again.
