### ISSUE TITLE
Logging into bit cloud

### ISSUE THREAD

**Issue by JasonNotJson** [teambit/bit#7873]
### Description

I was trying to log in to bit cloud to manage the organization. I remember trying to login with GitHub. My memory could be wrong, but can no longer log in to bit cloud any more. 
Can anyone help me out?

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by kennichi83** [comment]
Our organization has the same issue, no github login anymore. When we tried to log in with the root account (email), the component & billing section are empty. Please check?

**Comment by JasonNotJson** [comment]
Kennichi83, I asked the devs on slack and got an answer.

After creating that password, you’ll be able to log in directly on bit.cloud with the email/password combination (edited)
back in the “profile page”, click on “change password” to get a password-reset email, that allows you to create a password for your account.
add your email address
> “emails” section or just directly to https://legacy.bit.cloud/settings/emails
go to https://legacy.bit.cloud/settings/profile
To set up an email/password login:
You can still login to legacy.bit.cloud with the existing social logins, and there you can create an email/password combination for the account to then be able to log in to the same account directly via bit.cloud.
With regards login, we have chosen to remove social logins from the cloud, i.e. Google or Github. So login is now only via email/password or SSO (Enterprises).
We’ll be publishing a newsletter with details of everything you can expect to find on the new site, including features such as Change Requests and Newsfeed, and you can of course start looking about the site to get familiar with it all in the meanwhile :slightly_smiling_face:

We are delighted to announce a complete refresh to [bit.cloud](https://bit.cloud/), with a completely re-designed UI and lots of new features!!

**Comment by JasonNotJson** [comment]
Closed. 
Refer to previous answer

**Comment by benjgil** [comment]
Thanks @JasonNotJson 
Firstly, great moniker... :)
Secondly, the answer you posted became a bit garbled, so i'm going to write it here again for posterity and anyone else who has the same issue.

New bit.cloud announcement, including details of login changes:

> We are delighted to announce a complete refresh to [bit.cloud](https://bit.cloud/), with a completely re-designed UI and lots of new features!!
> We’ll be publishing a newsletter with details of everything you can expect to find on the new site, including features such as Change Requests and Newsfeed, and you can of course start looking about the site to get familiar with it all in the meanwhile :slightly_smiling_face:

> ### With regards login, we have chosen to remove social logins from the cloud, i.e. Google or Github. So login is now only via email/password or SSO (Enterprises).

> You can still login to legacy.bit.cloud with the existing social logins, and there you can create an email/password combination for the account to then be able to log in to the same account directly via bit.cloud.
> ### To set up an email/password login:
> - go to https://legacy.bit.cloud/settings/profile
> - “emails” section or just directly to https://legacy.bit.cloud/settings/emails
> - add your email address
> - back in the “profile page”, click on “change password” to get a password-reset email, that allows you to create a password for your account.

> After creating that password, you’ll be able to log in directly on bit.cloud with the email/password combination

**One more note for users with legacy components**
You will not be able to see legacy components on the new bit.cloud, so to view your legacy components please go to https://legacy.bit.cloud
