### ISSUE TITLE
We're not able to see components & billing data in new UI

### ISSUE THREAD

**Issue by kennichi83** [teambit/bit#7876]
### Describe the bug

When we login to the new bit.cloud UI, the components & billing section are empty. However, when we use legacy.bit.cloud, everything is still there. Please advise?

**Comment by kennichi83** [comment]
<img width="1492" alt="Screenshot 2023-09-06 at 13 41 43" src="https://github.com/teambit/bit/assets/9892524/bdd307b3-f1e1-40ce-9b83-dd5e14af60ba">

**Comment by kennichi83** [comment]
<img width="1498" alt="Screenshot 2023-09-06 at 13 48 54" src="https://github.com/teambit/bit/assets/9892524/2259ef98-930a-40fb-ae64-dcf8fc067393">

**Comment by kennichi83** [comment]
How can we see the components in new UI?

**Comment by GiladShoham** [comment]
Please see @benjgil last reply here 

https://github.com/teambit/bit/issues/7873#issuecomment-1707780085

If you have legacy components you should go to
https://legacy.bit.cloud

**Comment by itaymendel** [comment]
also, for billing and private component hosting issues please reach out to support@bit.cloud
