### ISSUE TITLE
Bit Yarn - Cannot Find Module

### ISSUE THREAD

**Issue by pm-trey** [teambit/bit#7885]
### Describe the bug

5 days ago, we started receiving an error on our CI process related to Bit commands. We do not use Bit as our direct package manager via `bit install`, but instead do the three step process, `postinstall": "bit import && bit compile && bit link"`. This is due to still maintaining a forked package via Github.

This command now throws an error:

```
Cannot find module '@yarnpkg/plugin-pack'
Require stack:
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/yarn/node_modules/@yarnpkg/plugin-npm/lib/npmPublishUtils.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/yarn/node_modules/@yarnpkg/plugin-npm/lib/index.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/yarn/node_modules/@yarnpkg/cli/lib/tools/getPluginConfiguration.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/yarn/node_modules/@yarnpkg/cli/lib/index.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/yarn/dist/yarn.package-manager.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/yarn/dist/yarn.main.runtime.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/bit/dist/load-bit.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/bit/dist/app.js
- /Users/treymcmeans/.bvm/versions/0.2.43/bit-0.2.43/node_modules/@teambit/bit/bin/bit
```

I did notice that `@teambit/yarn` has had a few updates, but unsure if related.

### Steps to Reproduce

`bit install` or `bit import && bit compile && bit link`

### Expected Behavior

Command completes

### Screenshots, exceptions and logs

<img width="643" alt="image" src="https://github.com/teambit/bit/assets/127399938/06ef0590-0944-4283-a0ac-c35865c1abf1">

### Specifications

- Bit version: 0.2.40
- Workspace type: harmony
- Node version: 18.17.1
- npm / yarn version: 3.6.1 (Yarn)
- Platform: MacOS

**Comment by zkochan** [comment]
Thanks for reporting the issue. I am working on it.
