### ISSUE TITLE
Bit Install - @babel/runtime/helpers

### ISSUE THREAD

**Issue by pm-trey** [teambit/bit#7898]
### Describe the bug

bit commands will not succeed, neither in stable nor nightly builds. Have tried a number of resolutions, but continue to receive the error.

### Steps to Reproduce

1. `bit install`
2. `bit status`

### Expected Behavior

Commands succeed

### Screenshots, exceptions and logs

```
➜  PM-onboarding-react-app git:(develop) bit install
  Resolving component dependencies for workspace: 'my-workspace-name'
✔ importing components (completed in 1s)
  installing dependencies in workspace using yarn (teambit.dependencies/yarn)
Bit received an error loading teambit.node/node@1.0.7, due to the error:
"Cannot find module '@babel/runtime/helpers/interopRequireDefault'".
This is required for the component: unknown
Please use the '--log=error' flag for the full error.
try running "bit install" to fix this issue
```

### Specifications

- Bit version: 0.2.40 & Nightly
- Workspace type: harmony
- Node version: 18.17.1
- npm / yarn version: 3.6.1
- Platform: macOS

**Comment by pm-trey** [comment]
Resolved by changing env from teambit.node/node@1.0.7 to teambit.harmony/node

**Comment by GiladShoham** [comment]
This is not a great solution.
This caused usually by corrupted capsule.
So bit capsule delete --all
Usually solves this issue without moving to the old node env
