### ISSUE TITLE
lit bug

### ISSUE THREAD

**Issue by zandko** [teambit/bit#7910]
### Describe the bug

A clear and concise description of the issue.

### Steps to Reproduce

Module not found: Error: Can't resolve 'react-dom/client' in
'/Users/zand/Code/Work/ywhub/node_modules/.pnpm/@teambit+docs.docs-template@1.0.2_@types+react@18.2.
21_react-dom@17.0.2_react@18.2.0_typescript@5.2.2/node_modules/@teambit/docs.docs-template/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-dom/client' in
'/Users/zand/Code/Work/ywhub/node_modules/.pnpm/@teambit+docs.docs-template@1.0.2_@types+react@18.2.
21_react-dom@17.0.2_react@18.2.0_typescript@5.2.2/node_modules/@teambit/docs.docs-template/dist'
    at /Users/zand/Code/Work/ywhub/node_modules/.pnpm/registry.npmjs.org+webpack@5.84.1/node_modules
/webpack/lib/Compilation.js:2022:28
### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 0.2.51
- Workspace type: (harmony/legacy) 
- Node version: 18
- npm / yarn version:  1.22.19
- Platform:

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by GiladShoham** [comment]
can you please provide some steps to reproduce this?

**Comment by zandko** [comment]
1.bit create lit-env envs/my-lit-env --aspect teambit.web-components/lit

**Comment by zandko** [comment]
1.bit create lit-env envs/my-lit-env --aspect teambit.web-components/lit
2.bit install --add-missing-deps
3.bit create lit material/block/service-header --scope yw.hub --path component/block/service-header
4.bit start

**Comment by itaymendel** [comment]
after your first `bit create` please run `bit install`.

**Comment by itaymendel** [comment]
this is resolved as part of this - https://github.com/teambit/bit/pull/8151
