### ISSUE TITLE
An error occurred in the package

### ISSUE THREAD

**Issue by zandko** [teambit/bit#7939]
### Describe the bug

When I packed it, I found that an error occurred because I introduced other packages in the bit workspace.

### Steps to Reproduce

1.bit build package

### Screenshots, exceptions and logs

<img width="1127" alt="IMG-2023-09-21-16 07 49@2x" src="https://github.com/teambit/bit/assets/37948383/aa7f89c0-64d2-497a-9ccc-a81dfd1fcecd">

### Specifications

- Bit version: latest
- Node version: 18 
- Platform: mac

**Comment by sbland** [comment]
Try deleting node_modules and then running bit install

**Comment by zandko** [comment]
I tried it many times, but it didn't work.

**Comment by sbland** [comment]
Check the package is in your workspace.jsonc file too.

**Comment by itaymendel** [comment]
you don't need to `build` components specifically. just run `bit build` without anything after that.
Bit needs to build the dependents, but it will not, as you do not indicate to Bit to build them (you can pass multiple components to the command, but it's not required).

by default bit will build modified components and their affected dependents.
