### ISSUE TITLE
Ripple CI fails with build

### ISSUE THREAD

**Issue by pkawula** [teambit/bit#7949]
### Describe the bug

We have configured our CircleCI to build, tag and export all components to the Bit cloud but in the past couple of days Bit is running something called RippleCI which fails with our snapshots.

How can we opt out of RippleCI for the whole scope?
docs says you can set a config var but this doesn't work

**Comment by GiladShoham** [comment]
add `bit config set force_local_build true` in your ci pipeline before running the tag command

**Comment by itaymendel** [comment]
Hi,

First of all, if you can please share the build issues you have, this will help.
Secondly - you can follow the steps here - https://bit.dev/blog/bit-v10-upgrade-notes-lmq9ec18/
You have two options, either set `bit config set force_local_build true`, and then Bit knows to run the build pipeline on your system, or add the `--build` flag when you run `tag` or `snap`.

if your automation uses `bit tag --soft` and `bit tag --persist` you should not be affected by this.

**Comment by pkawula** [comment]
Hi, the issue is failing snapshot test, which does not happen locally or on our CI/CD.
As mentioned before we are using circle CI, here is the snippet responsible for tagging and exporting components (RippleCI does run after that)

![image](https://github.com/teambit/bit/assets/33988240/3fe1e186-a3e6-4b7b-88b3-9c9a02d3c5a8)

**Comment by itaymendel** [comment]
hi, the reason this does not fail on your ci is because you do `bit tag --skip-tests`. RippleCI does not let you skip tests. Which means you need to ensure `bit tag` runs fine locally with success to pass rippleCI
