### ISSUE TITLE
React custom env React version clashes with testing-library version

### ISSUE THREAD

**Issue by sbland** [teambit/bit#7971]
### Describe the bug

New custom React env's allow using both React 17 and 18 but also set `@testing-library/react` to version `^18.4.0` which has no support for React <= 17 (See issue here: https://stackoverflow.com/a/71716438/10259813).

This only seems to be an issue if there is a package in the dependencies that requires React 17 so `bit install` installs 17 instead of 18.

Resulting error during testing: 
```
Cannot find module 'react-dom/client' from 'node_modules/.pnpm/@testing-library+react@13.4.0_react-dom@17.0.2_react@17.0.2/node_modules/@testing-library/react/dist/pure.js'
```

### Specifications

- Bit version: `1.0.0`
- Workspace type: harmony
- Node version: 16
- npm / yarn version:(npm v8.19.4)
- Platform: ubuntu

**Comment by GiladShoham** [comment]
If you want to use react 17 please use this one
https://bit.cloud/teambit/react/v17/react-env
the other one (teambit.react/react-env) set components to support both, the dev env itself only supports 18.

**Comment by benjgil** [comment]
To expand on what @GiladShoham said
The default react-env environment sets the allowed peerDependencies of components to 17 || 18, but you need to make sure that your components are actually compatible with both. Bit won't enforce that, and if your components or their dependencies are limited to a specific version of react then you'll also need a different peerDependency range to be set on those components.

So like Gilad said, if it's a react-17-only component we have a react-17 env for that, or you can update the dependency of your component to a react-18-compatible version (as long as it's backward compatible too

**Comment by sbland** [comment]
Thanks @GiladShoham and @benjgil. Just to also clarify for anyone ending up here too. This environment will allow exported components to be used in React 17 applications but all dependencies of the environment components must be compatible with React 18.

Is there anyway for the environment to warn if there are dependencies that are not React 18 compatible?

# As an example

**This works...**

Custom Env A uses the new Bit React 18 env as a base

Component A is created externally has React dependency V17 l |18
Component B uses Custom Env and depends on Component A.
Application depends on Component B  and can be both React 17 or 18

**This doesn't work...**

Custom Env A uses the new Bit React 18 env as a base

Component A is created externally has React dependency V17  only
Component B uses Custom Env and depends on Component A.  At this point testing will fail because the environment is V18 but bit has installed V17.
Application depends on Component B  and so must be V17 due to upstream dependency Component A
