### ISSUE TITLE
Webpack issues with Websocket in tests

### ISSUE THREAD

**Issue by sbland** [teambit/bit#7972]
### Description

Since upgrading bit and my envs I now get an issue with `ws_1.WebSocketServer` being undefined. 

Relevant code:
``` js
import { WebSocket, RawData, WebSocketServer } from 'ws';

const wss: WebSocketServer = new WebSocketServer({
  port,
  server,
});

```

Seems to be related to this issue: https://github.com/websockets/ws/issues/1538 but no steps here resolve my setup. I've added the webpack overrides to my environment webpack transformers as below:

``` js

export const modifyOutputTransformer = (configMutator) => {
  const newWebpackConfig = {
    resolve: {
      mainFields: ['main', 'browser'],
    },
  };


  configMutator.merge([newWebpackConfig]);
  return configMutator;
};
...
 /**
  * generates the component previews during development and during build
  */
 preview(): EnvHandler<Preview> {
   /**
    * @see https://bit.dev/docs/react-env/component-previews
    */
   return ReactPreview.from({
     mounter: this.previewMounter,
     hostDependencies,
     transformers: [modifyOutputTransformer],
   });
 }
...
```
### Specifications

- Bit version: `1.0.0`
- Workspace type: harmony
- Node version: 16
- npm / yarn version:(npm v8.19.4)
- Platform: ubuntu

**Comment by GiladShoham** [comment]
Can you please `console.log(configMutator.raw)` and see that the final webpack config is as expected?
Also, I'm not sure how this config will affect other libraries used by the preview. it might break it completely.

**Comment by sbland** [comment]
I resolved this by cleaning up my environment assignment and clearing node_modules, lock files etc. I still had a similar issue with `react-use-websocket` where I had to use `(useWebSocket as any).default` instead of `useWebSocket`.
