### ISSUE TITLE
Confuse Documentation for npmrc

### ISSUE THREAD

**Issue by pabtab** [teambit/bit#7993]
### Describe the bug

For Private components, the .npmrc works with domain .dev instead of .cloud which is wrong at the documentation: https://bit.dev/reference/packages/npmrc/

### Steps to Reproduce

1. Add a private component
2. Add .npmrc using .cloud
`@my-bit-org-or-username:registry=https://node-registry.bit.cloud
@teambit:registry=https://node-registry.bit.cloud
//node-registry.bit.cloud/:_authToken=BIT_CLOUD_AUTH_TOKEN
always-auth=true`
3. Cannot find the component - 404 NOT FOUND - after `Yarn install` or `npm i`

### Expected Behavior

Add .npmrc with domain .dev
`@my-bit-org-or-username:registry=https://node-registry.bit.dev
@teambit:registry=https://node-registry.bit.dev
//node-registry.bit.cloud/:_authToken=BIT_CLOUD_AUTH_TOKEN
always-auth=true`

### Specifications

- Bit version: 1.1.0
- Workspace type: (harmony/legacy)
- Node version: 16.15.0
- npm / yarn version: 8.5.0/1.22.0
- Platform: Mac / Linux

**Comment by GiladShoham** [comment]
Cloud is the correct one. Dev is the old one.
If you have specific component that get 404 with cloud please mention its name so we can look into it and fix it.
@guysaar223 fyi

**Comment by pabtab** [comment]
Ohh got it, however, It doesn't work for me with cloud, the components are called: `@tmrw-ls/clinic.components.button-dynamic` and `@tmrw-ls/clinic.utils` which are private. Thank you

**Comment by itaymendel** [comment]
hi, you still get an error?
if so, what is the error and how does your current npmrc look like?
