### ISSUE TITLE
When exporting a component to the remote scope the overview is wrong

### ISSUE THREAD

**Issue by jonatan-blossom** [teambit/bit#7997]
### Describe the bug

When I ran locally the bit server the overview looks perfect like in the attached image, when I tag the component and export it to the remote self-host scope, the overview is not workin

### Steps to Reproduce

1. create new component
1.tag the new component
1.export to remote scope server

### Screenshots, exceptions and logs
Remote self-hosted server scope
<img width="1304" alt="image" src="https://github.com/teambit/bit/assets/79993534/028be88c-2add-41bc-a5c6-9ceb3b0bb9bd">

Local bit server
<img width="1302" alt="image" src="https://github.com/teambit/bit/assets/79993534/cc1f8320-0cb5-47e5-8612-9a1abe80b2b3">

### Specifications

- Bit version:
<img width="331" alt="image" src="https://github.com/teambit/bit/assets/79993534/dabfec56-f751-442d-92d9-1203491261a9">

**Comment by itaymendel** [comment]
hi,

you need to run `bit tag --build`, as per the major changes in Bit 1.0.0 - https://bit.dev/blog/bit-v10-upgrade-notes-lmq9ec18/

**Comment by jonatan-blossom** [comment]
yes, I do a `bit tag --build` but It doesn't work
<img width="416" alt="image" src="https://github.com/teambit/bit/assets/79993534/96c3ee6f-475b-404d-a775-12eb958c6e96">
