### ISSUE TITLE
Installed dependencies cannot be introduced correctly.

### ISSUE THREAD

**Issue by zandko** [teambit/bit#8009]
### Describe the bug

The installed dependencies cannot be introduced correctly. The node_modules have been repeatedly deleted and reinstalled, which is still useless. I'm sure it's not the display problem of ide, and I can't find the relevant dependencies when packaging.

### Screenshots, exceptions and logs

![IMG-2023-10-08-14 49 40@2x](https://github.com/teambit/bit/assets/37948383/729140fa-f1ab-4123-abed-b9ffe3de2701)

![IMG-2023-10-08-14 49 13@2x](https://github.com/teambit/bit/assets/37948383/5d9dd400-69d3-4370-b33a-8b0a1f79fbdf)

### Specifications

- Bit version: latest
- Node version: 18
- Platform: mac

**Comment by itaymendel** [comment]
hi, please describe what you are trying to achieve and how to reproduce the issue.
from your note it's hard to understand how to tackle the issue.

**Comment by itaymendel** [comment]
issue abandoned by the reporter. closing.
