### ISSUE TITLE
Have two teambit.preview tasks with same name, causing build issue

### ISSUE THREAD

**Issue by mcwade** [teambit/bit#8017]
### THE ISSUE

I was trying to debug an issue I was having with building exported react components after the GeneratePreview started throwing errors.  I made a mistake of trying to update the preview aspects, hoping to revert an odd change I noticed on the `teambit.preview leagacy-preview` config.  After running `aspect set team.bit/preview` I now have 2 configs under teambit.preview: 

1. preview
2. preview@1.0.20

Now when Bit is building an exported component I get the following error:

> Total 1 components to build
> task of teambit.react/react teambit.preview/preview:GenerateEnvTemplate is invalid, there are two or more tasks with the same name and aspectId in the same environment

**_NOTE:_**
I am still unsure about the initial error that I was trying to fix but I need to sort this one out first to then return to the initial one.  Initial error: I noticed that `teambit.preview leagacy-preview` config had changed: `includesEnvTemplate: false` is now `includesEnvTemplate: true`

### Steps to Reproduce

1. run `bit aspect update teambit.preview/preview`
2. run `bit status`
3. tag and export
4. Open Ripple CI interface to find build.  Notice the logs return the error above. 

### Expected Behavior

The expected behavior would be a successful build.  No error thrown for having 2 or more same named tasks.

### Screenshots, exceptions and logs

<img width="1400" alt="Screenshot 2023-10-09 at 1 06 15 PM" src="https://github.com/teambit/bit/assets/1139508/982439b6-6b68-4583-b4ce-421b9cc4c5a9">
<img width="1396" alt="Screenshot 2023-10-09 at 4 54 15 PM" src="https://github.com/teambit/bit/assets/1139508/80fc78ec-2608-41b2-b772-2a32de1df92b">

### Specifications

- Bit version: 0.2.51
- Workspace type: Harmony
- Node version: v18.16.0
- npm / yarn version:  yarn 1.22.19
- Platform: OSX

*for harmony workspace*
- relevant env: teambit.react/react
- relevant aspects:  teambit.preview/preview & teambit.preview/preview&1.0.20

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by benjgil** [comment]
HI 
Just run `bit aspect unset teambit.preview` and this should remove the duplicate preview aspect
And you should also update your version of bit, as we're now on 1.2.0 and this specific issue of duplicate aspects was recently dealt with.

Once you've resolve the duplicate aspect issue please then post the issue you were having with GeneratePreview

**Comment by benjgil** [comment]
And in general, you shouldn't ever have to set or unset a @teambit/* aspect on components, those are generally handled behind the scenes by bit
So if you're thinking of doing that sort of thing, you're probably barking up the wrong tree :P)

**Comment by itaymendel** [comment]
ticket left un-answered by the author. closing.
