### ISSUE TITLE
Cannot create react component - file or directory was not found error

### ISSUE THREAD

**Issue by filipmikes1** [teambit/bit#8019]
### Describe the bug

When I try to create new react component with this command: `bit create react test --scope company.ui-lib --env company.envs/company-react-env` I receive this error: `error: file or directory "ui-lib/test" was not found.` When I run `bit doctor` command everything have passed status.

### Steps to Reproduce

1. run bit create react test --scope company.ui-lib --env company.envs/company-react-env

### Expected Behavior

React component should be created without an issue.

### Screenshots, exceptions and logs

> got an error from command create: PathsNotExist
>     err: {
>       "type": "PathsNotExist",
>       "message": "",
>       "stack":
>           PathsNotExist
>               at AddComponents.add (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/tracker/dist/add-components.js:712:13)
>               at async TrackerMain.track (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/tracker/dist/tracker.main.runtime.js:85:20)
>               at async ComponentGenerator.generateOneComponent (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/generator/dist/component-generator.js:200:24)
>               at async /Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/generator/dist/component-generator.js:119:16
>               at async pMapSeries (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/p-map-series/index.js:9:15)
>               at async ComponentGenerator.generate (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/generator/dist/component-generator.js:109:29)
>               at async CreateCmd.report (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/generator/dist/create.cmd.js:55:21)
>               at async CommandRunner.runReportHandler (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/cli/dist/command-runner.js:157:20)
>               at async CommandRunner.runCommand (/Users/filip.mikes/.bvm/versions/1.0.0/bit-1.0.0/node_modules/@teambit/cli/dist/command-runner.js:98:16)
>       "isUserError": true,
>       "name": "PathsNotExist",
>       "paths": [
>         "ui-lib/icons/no-match"
>       ],
>       "showDoctorMessage": true
>     }

### Specifications

- Bit version: 1.0.0
- Workspace type: legacy
- Node version: v18.17.1
- npm / yarn version: 10.1.0
- Platform: darwin

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

### Additional context

This exact command works for my colleagues without an issue so it is probably something with my bit installation.

**Comment by benjgil** [comment]
@davidfirst 
It turns out that this was because the command was run from an internal directory inside the workspace, and not from the workspace root dir.

AFAIU that's still a bug right, and Bit commands should be run-able from anywhere in the workspace?

**Comment by itaymendel** [comment]
issue abandoned by the reporter. closing.
also, bug reported by @benjgil was resolved.
