### ISSUE TITLE
I had created bit components in the cloud 2 years ago and now they are DELETED

### ISSUE THREAD

**Issue by DimarDM** [teambit/bit#8030]
I logged in my bit cloud account and there are 0 components.
I had 4-5 components that im using in productions right now.
But i cant update my production because some bit components dont exist.

**Comment by GiladShoham** [comment]
Try using 
legacy.bit.cloud

**Comment by itaymendel** [comment]
Hi,
please reach out to support@bit.cloud for things related to the service. this repository is for submitting issues related to the Bit OSS tool.
