### ISSUE TITLE
Bit tag no longer running bit publish and manually publishing missing dist folder

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8069]
### Describe the bug

`bit tag` no longer runs bit publish and components published to npm with  `bit publish` are missing the dist folder when installed.

### Steps to Reproduce

1. `bit tag`

### Expected Behavior

During `bit tag` it should run the bit publish step and include dist folder.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: 1.0.0
- Workspace type: harmony
- Node version: using node v16.20.0
- npm / yarn version:(npm v8.19.4)
- Platform: Ubuntu 20

**Comment by itaymendel** [comment]
hi,

please see the release notes from bit 1.0.0 and the breaking changes
https://github.com/teambit/bit/releases/tag/v1.0.0

you need to add `--build` to your `tag` to run the build process, or use `--soft/--deprecate` combo in your automation.
