### ISSUE TITLE
Is Angular not yet supported?

### ISSUE THREAD

**Issue by Sir0xb** [teambit/bit#8073]
bit create ng-app apps/my-angular-app
> template "ng-app" was not found

bit create ng-module ui/my-button
> template "ng-module" was not found

I just followed Doc's demo copy command and cannot support Angular

**Comment by itaymendel** [comment]
you need to set up the angular plugin in your `workspace.jsonc`.

```
bit new angular my-workspace --aspect bitdev.angular/angular-env --default-scope my-org.my-scope
```

this example creates a pre-configured angular workpsace. you many need to change the `defaultScope` values here. but you should get the gist.
https://bit.dev/docs/angular-env/use-custom-env/

the angular intro suggests to start from this step, but i'll make sure to update the docs to make it more prominent.

**Comment by Sir0xb** [comment]
So, can a workspace only support one Env? I have added React, Angular Vue, and other env in the current workspace

**Comment by itaymendel** [comment]
you can add as many envs as you want. just ensure to `bit install @bitdev/angular.angular-env` and then add this to your `generators` array in `workspace.jsonc`.
