### ISSUE TITLE
CICD missing error logs

### ISSUE THREAD

**Issue by giuliano-abinbev** [teambit/bit#8082]
### Description

I'm currently testing Bit with a custom internal private registry, and using Github Actions to publish my packages via `bit tag`.

When testing locally, I get logs (like build, test, etc) as well as any logs from npm publish (either success or errors), but I don't get them in Github Actions (see screenshots)

<img width="304" alt="Screenshot 2023-11-01 at 10 12 00" src="https://github.com/teambit/bit/assets/144352874/79899e12-74d2-4c5e-9c36-b9da662d4404">

Is there a flag that I need to pass to display them?

### Specifications

- Bit version: 1.2.7
- Node version: 18
- npm / yarn version: 9.8.1
- Platform: Linux ubuntu
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi,

i am unsure where you got that script for your CI, but you can't run it like that.
you need to run `npx @teambit/bvm install` and then `bit tag --build` (no need to do `--all`).

i'd recommend looking into our docs and maybe using the pre-defined CI scripts from there.

**Comment by giuliano-abinbev** [comment]
Gotcha, i think the problem here is that Bit isn't detecting the provided `.npmrc` file which has the credentials to publish to the private registry. `npx @teambit/bvm install` and `bit tag --build` helped btw to get logs

**Comment by itaymendel** [comment]
Bit should detect that `.npmrc` file. can you reproduce the issue please? i tried it now and able to see it working as expected.

**Comment by giuliano-abinbev** [comment]
I ran two tests, one publishing locally and another in my CICD pipeline via github actions.

Locally it works, I can publish
<img width="1051" alt="Screenshot 2023-11-02 at 10 48 33" src="https://github.com/teambit/bit/assets/144352874/e17d8e3f-b132-4e67-9e30-15d712fc49fa">

In Github Actions, I create an `.npmrc`, either in the previous step or same step (tried both ways just in case), I did `cat .npmrc` to make sure it's present (values are hidden)
<img width="1317" alt="Screenshot 2023-11-02 at 13 52 18" src="https://github.com/teambit/bit/assets/144352874/2d344cc4-d107-4df5-9034-635a3383b6eb">

(I even tried hard-coding the tokens in case i wasn't being able to properly access to the secrets), and the publishing fails with auth error

<img width="1050" alt="Screenshot 2023-11-02 at 13 52 36" src="https://github.com/teambit/bit/assets/144352874/a0918725-7a7c-4d47-bbce-d96703376e89">

**Comment by giuliano-abinbev** [comment]
Another finding. Looks like Bit doesn't read the `.npmrc` from the project but instead from the home directory which is the global `.npmrc` in my local. After removing all credentials from `~/.npmrc` and only placing them into `.npmrc` at the project level, I was able to reproduce the issue (aka couldn't publish)
