### ISSUE TITLE
Cannot find base config file

### ISSUE THREAD

**Issue by giuliano-abinbev** [teambit/bit#8089]
### Description

Getting the following error

```
▲ [WARNING] Cannot find base config file "./node_modules/.cache/tsconfig.bit.26f937921592f6494559202c4c41a710f074f56b.json" [tsconfig.json]

    tsconfig.json:3:13:
      3 │   "extends": "./node_modules/.cache/tsconfig.bit.26f937921592f6494559202c4c41a710f074f56b.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

▲ [WARNING] Cannot find base config file "./node_modules/.cache/tsconfig.bit.26f937921592f6494559202c4c41a710f074f56b.json" [tsconfig.json]

    tsconfig.json:3:13:
      3 │   "extends": "./node_modules/.cache/tsconfig.bit.26f937921592f6494559202c4c41a710f074f56b.json",
        ╵              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

How can I rebuild the tsconfig? Should I commit files like `tsconfig.json`, `.eslintrc.json`, and `.prettierrc.cjs` that point to a file in the node modules cache?

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi, Bit generates these files automatically during various tasks (`bit install` for example). so if you don't commit, they will get generated.
there's a dedicated command to trigger it - `bit ws-config write`.

depending on the version of bit you have install, the auto-generate may be on or off... can you share your Bit version?

**Comment by giuliano-abinbev** [comment]
thanks, `bit ws-config write` solved the problem.

Here's my finding. When creating a workspace, the files are available in `node_modules/.cache`, but, deleting `node_modules` and running `bit install` does not create those files again. I also tried with different commands like `bit build`, `bit compile`, `bit tag`, etc, and none of them create the files.

Questions:
1. Is it safe to use `bit ws-config write` in production? the command it's EXPERIMENTAL
2. Should we commit these auto-generated files like `tsconfig.json`? it seems like these files should be ignored, by default, and auto-generated when running a command like `bit install`.

**Comment by itaymendel** [comment]
hi, since this chat we added several upgrades to the command and removed the "experimental" flag, also we ensure this runs during the `install` operation as well.
we recommend setting these files in `gitignore` (all future templates will do that).
