### ISSUE TITLE
Can not login bit.cloud

### ISSUE THREAD

**Issue by Sir0xb** [teambit/bit#8098]
I don't know why.
<img width="527" alt="image" src="https://github.com/teambit/bit/assets/2919748/b3d4845b-95e8-4c3a-ace6-6c15a11b1fc0">

I can't receive an email even after clicking on the forgotten password

**Comment by guysaar223** [comment]
try  to login without upper case with uppercase at the email:
Sir0xb@live.com => sir0xb@live.com

we will add support login with upper case
