### ISSUE TITLE
CSS/SCSS does not reload UI

### ISSUE THREAD

**Issue by giuliano-abinbev** [teambit/bit#8126]
### Describe the bug

Running the ui/development server via `bit start`, when making changes into a css file that's being imported by a component, the UI does not reload.

### Steps to Reproduce

1. Create a react component
1. Add css/scss and import it, either as plain css or css modules
1. Run `bit start`
1. Open the component in the UI
1. Make a change in css file
1. Terminal logs a rebuild from webpack
1. Check UI, changes are not being reflected even after refreshing the page. Only way to see the changes is by killing the process and running `bit start` again

### Expected Behavior

After making a change in a css/scss file, the UI should reload

### Specifications

- Bit version: 1.2.7
- Workspace type: harmony
- Node version: v18.18.2
- npm / yarn version: 9.8.1
- Platform: MacOS (M1)

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by benjgil** [comment]
@leimonio

**Comment by leimonio** [comment]
@giuliano-abinbev Usually this issue comes up because you need to run `bit install` after your component creation. Running `bit status` will give you some good guidance for such cases.

**Comment by giuliano-abinbev** [comment]
@leimonio I just did what you suggested and still having the issue. Here's what I did

1. Ran `bit install`
1. Ran `bit status`, all components are `OK`
1. Ran `bit doctor`, everything succeeded

### bit status
![Screenshot 2023-11-09 at 12 14 35](https://github.com/teambit/bit/assets/144352874/7c638782-dd99-42ff-90c1-b10513ac7328)

### bit doctor
![Screenshot 2023-11-09 at 12 14 56](https://github.com/teambit/bit/assets/144352874/c88e1880-548e-4374-bf31-5495d564a23b)

After running `bit install`, I ran `bit start`, opened the UI server on my browser, made a change in the CSS file, and changes were not reflected, even after refreshing the page. Webpack still reports a change on the terminal. Can't see change in both, the Overview page and Preview page.


Also, having the same issue with documentation, i have a `{componentName}.docs.md` file, made a change to it, Webpack reported a change, but can't see them in the UI.

Finally, it works if I make a change into the component, for example, any change performed in `{componentName}.tsx` are reflected in the UI

**Comment by leimonio** [comment]
That's really strange, can you please share with me your local workspace? I'd suggest you join us here over slack and share with me https://join.slack.com/t/bit-dev-community/shared_invite/zt-26ssl8l5w-3QUr19rMsMeu9o5d1FgVwg

**Comment by leimonio** [comment]
HMR issue is resolved after upgrading to latest bit `v1.3.21` and regenerating `.bit` folder.
