### ISSUE TITLE
Dead link in docs deploy-apps page

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8214]
Dead link here:
https://bit.dev/docs/getting-started/collaborate/deploy-apps/
"Learn more on [application plugins](https://bit.dev/reference/apps/app-plugins)."

Also the Docs issue report says:
Please file any Docs issues at: https://github.com/teambit/bit-dev
But that link is also dead!

**Comment by NitsanCohen770** [comment]
Fixed on this CR: https://bit.cloud/teambit/community/~change-requests/fix-app-plugins-link

**Comment by sbland** [comment]
Thanks! Another one on the same page is the Docker and Kubernetes links are pointing to the app deployment page.
