### ISSUE TITLE
Managing dependency chains

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8254]
Another Dependencies related issue I have came across is the following situation...

Component A(V1.0.0) depends on Component B(V1.0.0) which depends on component C(V1.0.0).

If component C has a braking change its version changes to V1.1.0. Bit would then automatically update Component A and B to V1.1.0. Any dependencies on Component A would then assume there is a braking change. But if the braking change is handled in Component B without any change to Component B's API then there is no braking change to Component A.

**Comment by itaymendel** [comment]
semver rules are semantic. always think about theh apis you expose to the outside.
in this example, C changed an API, later B adopted that change without a need to change its API, so for A there is no change in B's API layer.
so B is not a breaking change

in a sense, B created a barrier around C's changes, as the change only impacts B and not A (or other dependents).

this is why if you use components to also manage data-fetching and entities in your system, you can ensure you build laters that protect from breaking changes by adopting to them.
