### ISSUE TITLE
installation fail - npx @teambit/bvm install

### ISSUE THREAD

**Issue by raguramb** [teambit/bit#8261]
Describe the bug
When I try to install bit with this command: npx @teambit/bvm install                                                                                         I receive this error: Error: Command failed with exit code 1: tar -xf bit-1.5.13-win-x64.tar.gz

Command failed with exit code 1: tar -xf bit-1.5.13-win-x64.tar.gz
bit-1.5.13/node_modules/bufferutil/node_modules/.bin/node-gyp-build: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\bufferutil\\node_modules\\.bin\\node-gyp-build'
bit-1.5.13/node_modules/bufferutil/node_modules/.bin/node-gyp-build-optional: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\bufferutil\\node_modules\\.bin\\node-gyp-build-optional'
bit-1.5.13/node_modules/bufferutil/node_modules/.bin/node-gyp-build-test: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\bufferutil\\node_modules\\.bin\\node-gyp-build-test'
bit-1.5.13/node_modules/ssh2/lib/protocol/crypto/build/node_gyp_bins/python3: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\ssh2\\lib\\protocol\\crypto\\build\\node_gyp_bins\\python3'
bit-1.5.13/node_modules/utf-8-validate/node_modules/.bin/node-gyp-build: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\utf-8-validate\\node_modules\\.bin\\node-gyp-build'
bit-1.5.13/node_modules/utf-8-validate/node_modules/.bin/node-gyp-build-optional: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\utf-8-validate\\node_modules\\.bin\\node-gyp-build-optional'
bit-1.5.13/node_modules/utf-8-validate/node_modules/.bin/node-gyp-build-test: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\utf-8-validate\\node_modules\\.bin\\node-gyp-build-test'
bit-1.5.13/node_modules/cpu-features/build/node_gyp_bins/python3: Can't create '\\\\?\\C:\\Users\\XYZ\\AppData\\Local\\.bvm\\temp\\bit-1.5.13\\node_modules\\cpu-features\\build\\node_gyp_bins\\python3'tar: Error exit delayed from previous errors.

**Comment by GiladShoham** [comment]
what OS / machine are you using?
And also which terminal?

**Comment by raguramb** [comment]
Machine: Windows
Terminal: command prompt C:\Users\XYZ>

**Comment by raguramb** [comment]
> what OS / machine are you using? And also which terminal?

OS: Windows
Terminal: command prompt C:\Users\XYZ>

**Comment by GiladShoham** [comment]
which version of windows?

**Comment by raguramb** [comment]
> which version of windows?

Windows 10

**Comment by GiladShoham** [comment]
1. if you just run something like `tar -h` or `tar -v` in your terminal do you get an error about that it's not defined?
2. if you can do the following:
  a. install bvm globally `npm i -g @teambit/bvm` 
  b. run `bvm config set EXTRACT_METHOD default` 
  c. bvm install

**Comment by raguramb** [comment]
> 2\. `bvm config set EXTRACT_METHOD default`

PS C:\Users\XYZ\abc> npm i -g @teambit/bvm
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs

changed 592 packages in 7m

124 packages are looking for funding
  run `npm fund` for details   
     
PS C:\Users\XYZ\abc> bvm config set EXTRACT_METHOD default
>> 
set successfully

PS C:\Users\XYZ\abc> bvm install
EPERM: operation not permitted, lstat 'C:\Users\XYZ\AppData\Local\.bvm\temp\bit-1.5.13-win-x64.tar.gz'
Error: EPERM: operation not permitted, lstat 'C:\Users\XYZ\AppData\Local\.bvm\temp\bit-1.5.13-win-x64.tar.gz'
PS C:\Users\RaguramB\Vitrana>

**Comment by GiladShoham** [comment]
are you running the terminal with admin permission or not?

**Comment by raguramb** [comment]
> are you running the terminal with admin permission or not?

Thank you! Installation is is successful, but after  running command : bit new hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular" getting below error

=== Bit is not initialized - reverting to basic git command ===

git: 'new' is not a git command. See 'git --help'.

The most similar command is
        notes
![Uploading Screenshot (25).png…]()

**Comment by TGTGamer** [comment]
> "bit new hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular" 

Should be:

`"bit create hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular" `


----

> 1. if you just run something like `tar -h` or `tar -v` in your terminal do you get an error about that it's not defined?
> 2. if you can do the following:
>    a. install bvm globally `npm i -g @teambit/bvm`
>    b. run `bvm config set EXTRACT_METHOD default`
>    c. bvm install

`npx bvm install --extract-method default` also works. I would suggest this is added to the Troubleshooting pages as the above steps also worked for me except I reviewed the source code and google for hours to find this solution :)

**Comment by raguramb** [comment]
> "bit create hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular"

also giving the same issue

**Comment by TGTGamer** [comment]
> > "bit create hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular"
> 
> also throwing same error
> 
> === Bit is not initialized - reverting to basic git command ===
> 
> git: 'create' is not a git command. See 'git --help'.
> 
> The most similar command is notes

Apologies. My mistake. I thought you were at the phase of the creating component. 

When you do `bit templates, ` what do you get? Do you get the `hello-world-angular` show up?

I'm unsure if the workflow has changed slightly since the new version, but when I did it with node, I had to `bit init` and then could start importing components and creating. 

For me, when I tried `bit templates` on the latest version (1.5.13), I only got so couldn't init the hello-world-angular workspace:
```
teambit.generator/generator
    basic (a basic workspace)
```

**Comment by raguramb** [comment]
> > > "bit create hello-world-angular my-hello-world-angular --env teambit.community/starters/hello-world-angular"
> > 
> > 
> > also throwing same error
> > === Bit is not initialized - reverting to basic git command ===
> > git: 'create' is not a git command. See 'git --help'.
> > The most similar command is notes
> 
> Apologies. My mistake. I thought you were at the phase of the creating component.
> 
> When you do `bit templates`, what do you get? Do you get the `hello-world-angular` show up?
> 
> I'm unsure if the workflow has changed slightly since the new version, but when I did it with node, I had to `bit init` and then could start importing components and creating.
> 
> For me, when I tried `bit templates` on the latest version (1.5.13), I only got so couldn't init the hello-world-angular workspace:
> 
> ```
> teambit.generator/generator
>     basic (a basic workspace)
> ```

getting same error for all bit commands

**Comment by etino** [comment]
> `npx bvm install --extract-method default` also works. I would suggest this is added to the Troubleshooting pages as the above steps also worked for me except I reviewed the source code and google for hours to find this solution :)

Adding `--extract-method default` argument also worked for me with Windows 10.

**Comment by itaymendel** [comment]
added proper fallback to bvm installer to smooth this flow
