### ISSUE TITLE
NPM Project keep falling back to `node.bit.cloud` even though my `.npmrc` specifies `node-registry.bit.cloud` on Mac

### ISSUE THREAD

**Issue by Thomas-Boi** [teambit/bit#8274]
### Description

- Mac user can't install my package from Bit Cloud in a NPM project that worked before. 
- `npm install` complains: that package is not found
- I noticed that the Bit Cloud URL is mismatched
- The mismatched might have come from upgrading my `.npmrc` and changing `node.bit.cloud` to `node-registry.bit.cloud`.
- I'm on Windows 10 and the change worked for me.
- Mac User has a M1 chip.

### Specifications

- Bit version: 1.4.0 (on my Windows). On the Mac user's machine, he doesn't have Bit installed. He only use the Bit components in a NPM package.
- Node version: v20.10.0 (on my Windows), v20.1.0 (on his Mac)
- npm / yarn version: 10.2.3 (on my Windows), 9.6.2 (on his Mac)
- Platform: mine is Windows 10. His is Ventura 13.4, M1 chip
- Bit compiler (include version): don't know how to find
- Bit tester (include version): don't know how to find

### Context and additional information

I have a Bit project set up last year (great work guys, been loving Bit). At the time, I set up my `.npmrc` with the following values:

```
@teambit:registry=https://node.bit.cloud
@my-group:registry=https://node.bit.cloud
//node.bit.cloud/:_authToken=MY_TOKEN
```

Fast forward to now, I upgraded my Bit executable and exported (`bit export`) a few components, same as I always done. I ran into an error with `npm install` not working. Thus, I double checked [your `.npmrc` docs](https://bit.dev/reference/packages/npmrc/) and found that it has been updated. The example is now:

```
@my-bit-org-or-username:registry=https://node-registry.bit.cloud
@teambit:registry=https://node-registry.bit.cloud
//node-registry.bit.cloud/:_authToken=BIT_CLOUD_AUTH_TOKEN
always-auth=true
```

I went back to my `.npmrc` and changed everything from `node` to `node-registry`. `npm install` runs fine. 

When my coworker tries to do the same on his Mac (update `.npmrc` then `npm install` etc.), he couldn't install my packages. He ran into the following errors:

```
npm WARN registry URI: https://node-registry.bit.cloud/@my-group/my-package-2.15.0.tgz
npm WARN registry Scoped Registry Key: //node.bit.cloud/
npm WARN registry
npm WARN registry More info here: https://github.com/npm/cli/wiki/No-auth-for-URI,-but-auth-present-for-scoped-registry
npm ERR! code E404
npm ERR! 404 Not Found - GET https://node-registry.bit.cloud/@my-group/my-package-2.15.0.tgz - not found
npm ERR! 404
npm ERR! 404  '@hellopocketed/react-ui.widgets.tooltip@https://node-registry.bit.cloud/@my-group/my-package-2.15.0.tgz' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in: /Users/macuser/.npm/_logs/2023-12-15T20_33_17_830Z-debug-0.log
```

Note that the Scoped Registry Key is point to the old URL (`node.bit.cloud`) even though the component is hosted at `node-registry.bit.cloud`.

The even stranger thing is if we go back to the old `.npmrc` using `node.bit.cloud`, the URL changes. The warning becomes:

```
npm WARN registry URI: https://node.bit.cloud/@my-group/my-package-2.15.0.tgz
npm WARN registry Scoped Registry Key: //node-registry.bit.cloud/
```

The URLs switch places. I don't know why it's doing that, or why it's working on my machine and not his.

Things I've tried:
- Running `npm config list` to check that NPM configs are set -> they are
- Restarting the console/browser -> still doesn't work 
- `npm cache clean --force` -> still fails
- Delete `node_modules` and `package-lock.json` => still doesn't work
- Look up issues on here -> all are related to not setting the `.npmrc` in the first place or have been fixed.

Thank you, I appreciate your time and work.

**Comment by Thomas-Boi** [comment]
I finally found the solution:
- The `package-lock.json` hard codes the old URL (`node.bit.cloud`) and thus, it was causing issue.
- The solution was to:
  1. Delete `package-lock.json`
  2. Run `npm cache clean --force`
  3. Run `npm install --package-lock-only` to regenerate the `package-lock.json`
  4. Install the package that I need

I didn't try cleaning the cache before remaking the `package-lock.json`. Either way, thanks for making Bit and hope this helps others.

**Comment by riyakhandelwalABInbev** [comment]
I have tried all the steps mentioned but am still getting the same error.

npm ERR! code E404
npm ERR! 404 Not Found - GET https://node-registry.bit.cloud/@abi-labs-bit%2fhexa.ui.dropdown
npm ERR! 404
npm ERR! 404  '@abi-labs-bit/hexa.ui.dropdown@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by Thomas-Boi** [comment]
@riyakhandelwalABInbev your error looks different than mine. You should double check that your:
- package is present
- your Bit repo is set to public
- you have your Bit token set up in your `.npmrc`

* I'm not with Bit, just leaving a quick message to help. I won't do any in-depth debugging for you. Thanks 😄
