### ISSUE TITLE
Roadmap for supporting additional languages/runtimes

### ISSUE THREAD

**Issue by opensean** [teambit/bit#8295]
### Description

It has been awhile since the following issues https://github.com/teambit/bit/issues/6737  and https://github.com/teambit/bit/issues/137 were closed.  I would like to ask the same question.  Are there plans or an example to follow that shows how to add support for an additional language (e.g. python)?  

I have spent some time reading through the documentation and understand the [nodejs-runtime](https://bit.cloud/bitdev/harmony/runtimes/nodejs-runtime) is built by implementing some of the interfaces (e.g. the [Runtime interface](https://bit.cloud/bitdev/harmony/harmony-platform/~api-reference?selectedAPI=Runtime)) provided by the  [harmony platform](https://bit.cloud/bitdev/harmony/harmony-platform) .  Are there any examples of implementing a runtime in a different language?

### Additional context

Starting to use bit to develop and manage our application front ends (loving it), however, we interested in the possibility of extending bit to develop and manage our backend APIs (mostly written in python).

**Comment by itaymendel** [comment]
hi,

the runtimes used for Harmony Platform are unrelated to the languages Bit supports. Harmony is an external library for Bit. Supporting additional languages is in our roadmap, but this is still undecided on when.

The main problem in supporting additional languages is their dependency management system. in js eco-system we have the nodejs dependency resolution, which is very flexible and allowed tools like npm/pnpm/yarn to be the best package mangers possible.
Bit leads heavily on their capabilities. so supporting python/java/dotnet and more will mainly require work on dependency management.

at the moment we still have work to do in the JS eco-system, for example - ESM.

I am closing this issue, as this is a long term initiative and i can't provide with an answer for this. once we will have plans to expand Bit, we will make them available for all.


more details on Harmony -
The Harmony Platform you referred to is an SDK that allowed better composability for js-based systems, and runtime in harmony's context is actual runtime environment where you want your application to run. this is unrelated to Bit.
You will be able to build systems with Harmony even if you are not using Bit to manage it.

Documentation on Harmony is coming soon, we just opened this so we can start building examples for it in the open.
Harmony is what allows Bit to be implemented in a similar way to "aspect oriented architecture", and allow every aspect to provide functionality to various "runtimes" of an application (for example - `cli` and `browser` in the context of Bit, or `backend`, `browser` and `edge` in the context of bit.cloud).
