### ISSUE TITLE
Failed to create a new Vue project? Cannot create a new project following the Quick Start document 

### ISSUE THREAD

**Issue by forrany** [teambit/bit#8324]
### Describe the bug

<img width="1358" alt="image" src="https://github.com/teambit/bit/assets/29779326/f5973afd-f4b3-416b-a5df-524d18976339">

error occur when run this command

### Steps to Reproduce

1.  just flow the document 
2.  error occured
<img width="1262" alt="image" src="https://github.com/teambit/bit/assets/29779326/363b5750-7690-4fbc-bcfd-38f404f7fd6a">

error: component "teambit.vue/examples/my-dummy-wrapper" was not found
### Expected Behavior

I just want to try bit, found I even can't start it up

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Workspace type: (harmony/legacy)
- Node version:
- npm / yarn version:
- Platform:

*for harmony workspace*
- relevant env
- relevant aspects

*for leagacy*
- Bit compiler (include version):
- Bit tester (include version):

**Comment by GiladShoham** [comment]
@Jinjiang please have a look on this

**Comment by Jinjiang** [comment]
@forrany Sorry I can't reproduce it. May I have more information like:

Specifications
- Bit version:
- Node version:
- npm / yarn / pnpm version:
- Platform:

Thanks.

**Comment by forrany** [comment]
@Jinjiang Thank you, sorry this problem is caused by my setting of a custom npm registry, thank you for your attention and troubleshooting, happy new year, I think you can close the issue
