### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by yasniel1408** [teambit/bit#8330]
I have checked the documentation and nothing about environment variables.
What is the correct and definitive way to have environment variables in bit?

**Comment by sbland** [comment]
@yasniel1408 I've added my solution here: https://github.com/teambit/bit/issues/6278#issuecomment-1894476062

**Comment by Jagadishvg** [comment]
I want to add a environment variable can you help me by providing a simple step by step procedure.

**Comment by itaymendel** [comment]
closing, as solution proposed by @sbland
