### ISSUE TITLE
Do not force the component's main file to be listed as a tracked file

### ISSUE THREAD

**Issue by itaymendel** [teambit/bit#834]
## Expected Behavior

When I track a new component and add the main file to it, I expect it to be added to the component.

```bash
$ bit add content/tutorial/nav.yml content/tutorial/react-tutorial.md -m content/tutorial/index.js -i content/tutorial
```

## Actual Behavior

However, Bit wants me to specifically add the main file to the component.

```bash
$ bit add content/tutorial/nav.yml content/tutorial/react-tutorial.md -m content/tutorial/index.js -i content/tutorial
fatal: the main file content/tutorial/index.js was not found in the files list content/tutorial/nav.yml, content/tutorial/react-tutorial.md
```

## Steps to Reproduce the Problem

  1. Init Bit on a directory.
  1. Create 2 files within the directory.
  1. Add a component with one of the files as the main file, and the other as a regular tracked file.

## Specifications

  - Bit version: 0.12.7
  - Platform: macOS

**Comment by GiladShoham** [comment]
resolved as part of https://github.com/teambit/bit/pull/860
will be part of the next version (0.12.10)
