### ISSUE TITLE
Error: Minified React error #130 on bit.cloud

### ISSUE THREAD

**Issue by piotrkulpinski** [teambit/bit#8347]
Hi,
I have a problem hosting my components on bit.cloud. After exporting and successful build, I can't preview the compositions.

The preview area is empty and there's a minified React error in the console: 

![CleanShot 2024-01-02 at 17 06 22](https://github.com/teambit/bit/assets/358412/168930d0-6659-40c1-ab11-e7e56f8d0752)

Here's the full trace if if helps:

```bash
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at yh (VM74 317.3411833cdb8161f34f39.js:16:49370)
    at J (VM74 317.3411833cdb8161f34f39.js:14:17878)
    at Yi (VM74 317.3411833cdb8161f34f39.js:16:1483)
    at Wk (VM74 317.3411833cdb8161f34f39.js:16:44396)
    at Vk (VM74 317.3411833cdb8161f34f39.js:16:39732)
    at Uk (VM74 317.3411833cdb8161f34f39.js:16:39663)
    at Jk (VM74 317.3411833cdb8161f34f39.js:16:39523)
    at Ok (VM74 317.3411833cdb8161f34f39.js:16:35911)
    at Hk (VM74 317.3411833cdb8161f34f39.js:16:34865)
    at J (VM74 317.3411833cdb8161f34f39.js:32:1534)
```

The local development server is working correctly and preview is working as well. 
I've found the error is related to wrong imports, but checked everything and couldn't find anything. 

Is this a common issue? 
Any help would be appreciated. 

This is my third attempt at getting Bit to work, but I run into so many roadblocks...
Thanks!

### Specifications

- Bit version: 1.5.29
- Workspace type: (harmony/legacy) harmony
- Node version: 20.9.0
- pnpm version: 8.12.1
- Platform: MacOS

**Comment by GiladShoham** [comment]
Does your components public or private?

**Comment by piotrkulpinski** [comment]
Public, available at https://bit.cloud/curiousleaf/design

**Comment by piotrkulpinski** [comment]
Looks like the issue was caused by the fact that I've changed the default suffix for composition files from ".composition." to ".comp.". Reverting that seems to be fixing that issue.
