### ISSUE TITLE
Bit does not support flow type checking on the development phase of flow compiled components

### ISSUE THREAD

**Issue by ranyitz** [teambit/bit#84]
The flow compiler does strip the types, but we can't enjoy the benefits of the type checking if we can't configure flow (with .flowconfig for example).

In my use case, I worked on a project written without flow.
The bit component I was working on was written with flow type annotations,
I didn't receive any errors from Flow.
in order to receive type checking, I've created a `.flowconfig` file in the directory of the component.

I do realize that other contributors won't get this configuration.

I think bit should address this problem so we could really use flow/typescipt and share the configurations between users.

**Comment by itaymendel** [comment]
its now possible to add additional files to the component using the 'bit add' command. this means that the .flowconfig can be added to a component.
