### ISSUE TITLE
How to submit issues against components on bit cloud

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8411]
What is the best way to submit issues against components on bit.cloud? Components hosted on npmjs.com have a link to github which makes this simple.

**Comment by benjgil** [comment]
Hi @sbland 
We dont currently have per-component discussions, but there is a scope discussion, see the image below
To submit and issue, start a thread in the scope discussion about a specific component - you can reference the component via `$` and then the component name (you'll get suggestions to auto-complete).
