### ISSUE TITLE
Next.js hello world uses deprecated community starter

### ISSUE THREAD

**Issue by StephenSHorton** [teambit/bit#8420]
Following the tutorial for [Hello Next.js | Bit](https://bit.dev/docs/quick-start/hello-world-nextjs)

[This section](https://bit.dev/docs/quick-start/hello-world-nextjs#initialize-a-workspace) will cause an error in the terminal and prevent further tutorial progress because it is using [this deprecated starter](https://bit.cloud/teambit/community/starters/hello-world-nextjs).
![Screenshot 2024-01-18 at 10 56 23 AM](https://github.com/teambit/bit/assets/54323940/e7fa9cb3-b2df-4f86-8615-7299f058d36b)

Also the project generation command appears to use a different flag than what's show on the starter template
`--aspect` | `--env`
```bash
bit new hello-world-nextjs my-hello-world-nextjs --env teambit.community/starters/hello-world-nextjs
```
```bash
bit new hello-world-nextjs my-hello-world-nextjs --aspect teambit.community/starters/hello-world-nextjs
```

**Comment by leimonio** [comment]
This starter has been deprecated indeed. You can use instead the [new starter](https://bit.cloud/frontend/nextjs/templates/community-starters/hello-world-nextjs).

Run:

`bit new hello-world-nextjs my-hello-world-nextjs --env frontend.nextjs/templates/community-starters/hello-world-nextjs`

This should solve the issue. 

We'll update the docs to reflect this update. Thank you for reporting! 🙏
