### ISSUE TITLE
Having trouble with bit install

### ISSUE THREAD

**Issue by murm** [teambit/bit#8423]
### Describe the bug

In an already existing (next.js) application, I was about to add bit for all components to share them over other applications as well.

I get a 404 to several @teambit packages when doing `bit install` after adding react envs

`bit create react-env envs/react --aspect bitdev.react/react-env`

(from https://github.com/teambit/bit/issues/8277#issuecomment-1878200879)

```
❯ bit install
  Resolving component dependencies for workspace: 'studentapan-ui'
✔ importing components (completed in 27ms)
  installing dependencies in workspace using pnpm (teambit.dependencies/pnpm)
✔ linking components (completed in 1ms)
✔ deduping dependencies for installation
✔ running pre install subscribers
Progress: resolved 35, reused 34, downloaded 0, added 0
GET https://registry.npmjs.org/@teambit%2Freact.mounter: Not Found - 404

@teambit/react.mounter is not in the npm registry, or you have no permission to fetch it.

No authorization header was set for the request.

This error happened while installing a direct dependency of /Users/xxx/xxx/xxx
```

I'm also sent to a 404 npm page when trying to look at that package on npm https://npmjs.com/package/@teambit/react.mounter

### Steps to Reproduce

Follow this guide: https://bit.dev/reference/adopting-bit/nextjs
but replace second step with this command `bit create react-env envs/react --aspect bitdev.react/react-env`

If I don't, there will be a timeout and the process will completely hang until it crashes when node goes out of memory.

Side note! All this worked a few hours ago, but not now when I tried setup everything again. 

### Expected Behavior

Well, the dependecies should be installed without trouble. :)

### Screenshots, exceptions and logs

![Screenshot 2024-01-19 at 00 20 55](https://github.com/teambit/bit/assets/1172593/f3a5a684-4808-4bf3-af2b-a9c321def461)

### Specifications

- Bit version: 1.5.29
- Workspace type: Not sure... freshly installed latest?
- Node version: 20.10.0
- npm / yarn version: 10.2.3
- Platform: MacOS

**Comment by benjgil** [comment]
HI @murm 
It seems you dont have the npmrc config for installing @teambit packages.
Please run the following to add it:
npm config set '@teambit:registry' https://node-registry.bit.cloud

**Comment by artem-zaiko-yara** [comment]
bump

**Comment by artem-zaiko-yara** [comment]
Try to get auth token with `bit config get user.token`

and then set it in `.npmrc` 

```
//node-registry.bit.cloud/:_authToken=<token>
//node.bit.cloud/:_authToken=<token>
```

**Comment by NikitaRogozhyn** [comment]
Hi everyone

I'm facing the same issue right now.
I've tried to do these steps @benjgil @artem-zaiko-yara but it doesn't help. I've also recovered the approach from the official documentation https://bit.dev/reference/packages/npmrc but it doesn't work as well.

**Comment by albertovaccarella** [comment]
Same issue when deploying one of my apps to heroku, which I configured with an .npmrc as per docs (pointing to node-registry.bit.cloud). Then I deployed an older app, which I haven't updated in a bit and still has the old registry url (node.bit.cloud) and it worked: I then changed the first app's .npmrc to point to node.bit.cloud too and the build succeeded... 
In other words, it seems like the registry URL keeps changing back and forth from node-registry.bit.cloud to node.bit.cloud, or am I missing something?

**Comment by benjgil** [comment]
All these issues are almost certainly because your npmrc only contains a token for bit.cloud
Just adding an entry telling bit to look for scoped packages in node-registry.bit.cloud isnt enough, you need to also provide a token for that registry

Note to all - this will be managed better automatically by bit from the next stable version of bit, which will automatically set and update tokens for bit registries (as it used to do until around nov 23)

**Comment by itaymendel** [comment]
a valid `.npmrc` should look similar to this; it has a line for your organization as a scoped-registry and a line defining the token for authentication.
if you move from `node.bit.cloud` to `node-registry.bit.cloud`, please also delete your lock-file, as sometimes it contains references to the registry url, so it needs to be re-evaluated:

```
@bitdev:registry=https://node-registry.bit.cloud
@teambit:registry=https://node-registry.bit.cloud
@YOUR-ACCOUNT:registry=https://node-registry.bit.cloud
//node-registry.bit.cloud/:_authToken=TOKEN
```
