### ISSUE TITLE
Problem with installing bit globally

### ISSUE THREAD

**Issue by djkepa** [teambit/bit#8440]
### Description

When I want to install bit globally on my machine I get an error that this package does not exist for some reason, 
can you tell me what it is, I tried with multiple types of node versions, and still the same.

Thanks!

![image](https://github.com/teambit/bit/assets/45691844/da5321a1-931f-4af2-bf72-1d0bc630ded8)

### Specifications

- Bit version: 1.6.35
- Node version: 21.6.1
- npm / yarn version: 10.2.4
- Platform: Windows

**Comment by benjgil** [comment]
How are you trying to install bit?
Bit can only currently be installed via the bit version manager (bvm).
So you need to install bvm globally `npm i -g @teambit/bvm` and then use bvm to install bit `bvm install`

**Comment by djkepa** [comment]
Thanks for fast reply!
Yeah I did wrong with `npm i -g @teambit/bit`

Now I tried as you said with `bvm install` and still working, after almost 15 minutes of installation:

![image](https://github.com/teambit/bit/assets/45691844/7cd1b5ea-6d79-4b92-9ea4-b953ceac4e19)

This is normal?

**Comment by GiladShoham** [comment]
please try to run with `bvm install --extract-method=default`

**Comment by djkepa** [comment]
This works, thanks @GiladShoham

**Comment by GiladShoham** [comment]
Thanks for the update.
I'm going to try to catch this error internally and throw a proper error suggesting you use that flag.

**Comment by benjgil** [comment]
for anyone searching for the extract error, it's "child-process method failed".
This can sometimes happen when installing bit on windows machines - if you get that error see @GiladShoham's post above (hopefully we'll fix it before too many people experience it)
