### ISSUE TITLE
There is no way to configure compilers

### ISSUE THREAD

**Issue by ranyitz** [teambit/bit#85]
Babel compiler, for example, is extendable using plugins and presets.
Right now the compiler enables only one configuration for a certain component, which means we will need to create a different compiler component for each different configuration.
We also need to make the component configuration isolated is different developers have different project configurations (.babelrc on the root of the project).

We can maybe make the compiler reusable by enabling a .babelrc configuration file in the component directory.

**Comment by itaymendel** [comment]
resolved
