### ISSUE TITLE
Support for angular-cli tsconfig paths (@alias)

### ISSUE THREAD

**Issue by brunobertechini** [teambit/bit#852]
First of all, congratulations on amazing job at bit :)

## Expected Behavior
bit should be able to resolve dependencies (imports) with angular-cli @alias

## Actual Behavior
bit does not understand angular-cli alias (paths) imports

## Steps to Reproduce the Problem

  1.ng new bit-angular-cli
  2.cd bit-angular-cli
  3.bit init
  4.ng generate component hero
  5.bit add src\app\hero\* --id app/hero --main src\app\hero\hero.component.ts
  6.bit status (OK)
  7.ng generate component shared 
  8.edit tsconfig.json and add these to compilerOptions:
```
"baseUrl": "src",
"paths": {
            "@shared/*": [ "app/shared/*" ]
        },
```
  9.edit hero\hero.component.ts and add
`import { SharedComponent } from '@shared/shared.component';`
  10.ng build (OK)
  11.bit add src\app\shared\* --id app/shared --main src\app\shared\shared.component.ts
  12.bit status:
```
new components
     > app/shared ... ok
     > app/hero ...  missing dependencies
       missing packages dependencies:
          src\app\hero\hero.component.ts -> @shared/shared.component
```

## Specifications

  - Bit version: 0.12.9
  - Node version: 8.5.0
  - npm / yarn version: npm-5.6.0 / yarn-1.3.2
  - Platform: windows 10 x64 
  - Bit compiler (include version): 
  - Bit tester (include version):
  - Angular info (ng --version):
```
Angular CLI: 1.6.8
Node: 8.5.0
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.8
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.8
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by GiladShoham** [comment]
@brunobertechini Thanks for reporting this.
We will add this to our backlog and update the issue on any update.

**Comment by brunobertechini** [comment]
@GiladShoham Thanks a lot.

Is this a known issue ?

Are there any workaround I can use? I really would like to use this amazing project for my solution based on angular5.

Regards

**Comment by GiladShoham** [comment]
Hi,

Yes, it's a known issue we hope to address soon.
There is no easy workaround I can think of.

But you can achieve similar behavior using other features - 

Once you export bit component to a remote scope (or import a component from remote scope), you can require it using an absolute path without the need of anything else like tsconfig / NODE_PATH / webpack resolve and so on.

so you can change your requires to be relative, export your components, then change the requires to be absolute using bit/npm format.

I know it's not the best flow right now, but we are working to improve this flow and also to support tsconfig.

you can read more about it in our docs:
https://docs.bitsrc.io/docs/importing-components.html#bindings
https://docs.bitsrc.io/docs/importing-components.html#linking-components

If you have some time, we are always welcome PRs, here is some info regarding implementing this feature.
I think that supporting this (in the phase of detecting the dependencies should be pretty easy to achieve).
The relevant files are under the javascript driver project (bit-javascript).
some of the relevant files are:
https://github.com/teambit/bit-javascript/blob/master/src/dependency-builder/detectives/detective-typescript/index.js
and the files under this folder:
https://github.com/teambit/bit-javascript/tree/master/src/dependency-builder

The bit-javascript project exposes a CLI command called get-dependencies so you can run this command without even installing / setup bit's main project to see the result of the dependency calculation. 

Anyway, I'll keep this issue open and updated.

**Comment by itaymendel** [comment]
hi @brunobertechini , a new version of Bit is finally available, and supports configuring a custom module resolution.

more about it [here](https://docs.bitsrc.io/docs/troubleshooting-isolating.html)

**Comment by thomashibbard** [comment]
@itaymendel  That link is a 404

**Comment by GiladShoham** [comment]
@thomashibbard 
here is the [updated link](https://docs.bit.dev/docs/dependencies#custom-paths)
