### ISSUE TITLE
relativePaths

### ISSUE THREAD

**Issue by janprikryl1** [teambit/bit#8531]
unable to save Version object of <name>, the dependencies should not have relativePaths according to schema "2.0.0"
This error should have never happened. Please report this issue on Github https://github.com/teambit/bit/issues

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.

**Comment by GiladShoham** [comment]
What is your bit version?
Your os?
Which env are you using for your component?

**Comment by janprikryl1** [comment]
> What is your bit version? Your os? Which env are you using for your component?

Hello, I am using bit 1.6.52 on Windows 11 (23H2) for React

**Comment by davidfirst** [comment]
@janprikryl1 , any chance you created this component with the legacy version of bit (v14.x) and then continued working on it with the latest version?

**Comment by itaymendel** [comment]
issue abandoned by the reporter. closing.
