### ISSUE TITLE
TypeError: defaultExports is not a function

### ISSUE THREAD

**Issue by YanZiSen** [teambit/bit#8539]
### Specifications

- Bit version: 1.5.29
- Node version: 21.6.1
- npm / yarn version:  10.2.4 / 1.22.19
- Platform: macOS Monterey 12.3
- Bit compiler (include version): 
- Bit tester (include version):

### Context and additional information

I am a beginner user of Bit. When I tried to experience Bit, I encountered an issue.

When I accessed the service created by running 'bit start' locally, the 'overview' panel of the component remained in a loading state. Upon checking the console, I found the following error:

<img width="1501" alt="image" src="https://github.com/teambit/bit/assets/25051227/9311dba9-97b9-4907-bff5-3b128ddffe79">

My steps:

Created a new React workspace named 'test-workspace2' using the command 'bit new react test-workspace2 --aspect bitdev.react/react-env'.
Navigated to the directory 'test-workspace2'.
Accessed http://localhost:3000/ui/announcements

the UI:

<img width="1125" alt="image" src="https://github.com/teambit/bit/assets/25051227/909b68a8-3f61-4755-93b6-f332dfbe5876">

**Comment by giteden** [comment]
@YanZiSen, please update to Bit's latest version

**Comment by YanZiSen** [comment]
@giteden , thank's, update latest version 1.6.52  return to normal；
