### ISSUE TITLE
Backend intro issues and dead links

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8544]
### Describe the bug

Following the backend node guide here https://bit.dev/docs/backend-intro has some bad links and errors.

### Steps to Reproduce

1. `bit new node my-node-demo-app  --empty`
2. Gives following error:
```
template "node" was not found, please use --aspect flag to load from an env i.e --aspect teambit.react/react-env
 Learn more about component templates here: https://bit.dev/reference/generator/create-generator
```
3. The link is dead

### Expected Behavior

Should create the node workspace and link should not be dead.

### Specifications

- Bit version:1.6.62
- Workspace type: harmony
- Node version:18.19.1
- npm  version:10.2.4
- Platform: ubuntu

**Comment by ranm8** [comment]
Thanks for reporting! Issue is resolved on latest docs.
