### ISSUE TITLE
Add .npmrc file in bit playground

### ISSUE THREAD

**Issue by andreeatirgovatu** [teambit/bit#8571]
### Description

Hi, 
I tried to install a private npm package in a bit project with react. Locally, it worked because I added a .npmrc file on the project root, but when I tried to export the componets, I got 404 not found error for that private package in bit ripple CI because it is not in bit and it needs an auth token to install. 
The error :
<img width="521" alt="Screenshot 2024-02-25 at 10 25 12" src="https://github.com/teambit/bit/assets/33631519/1bd7455d-3836-4622-9465-60eb658434f6">
Project structure:
<img width="276" alt="Screenshot 2024-02-25 at 10 29 00" src="https://github.com/teambit/bit/assets/33631519/5fd5562a-0263-4322-abfa-cfdc8ae9f3e2">

Is there a way to do it? I checked the documentation and I could not find something related. 

Thank you,
Andreea

### Specifications

- Bit version:1.6.62
- Node version: 20.9.0                     
- npm / yarn version: 10.1.0
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi, if you use private packages there are three options for you:
1. Set up "remote registry" configuration for RippleCI (you can set this in your "organization settings" page).
2. Build the components on your CI with the provided CI script packages (https://bit.dev/blog/integrating-bit-with-your-existing-ci-lq55w51k/)
3. Build the components locally on your system before the export (by adding the `--build` flag, ie `bit tag -m "my version" --build`

**Comment by andreeatirgovatu** [comment]
After I tried to use `bit tag -m "my version" --build` , this command is trying to publish  the components as public, but my components should be private. Is there a way to change it?

**Comment by itaymendel** [comment]
the component can still be private, this is only related to building the component in an environment that has access to your private packages. the command will not mark the component as public. this is defined only in the scope settings.

as for the error you are getting, please run `bit checkout head` before you run `bit tag`.

**Comment by andreeatirgovatu** [comment]
Thank you so much for your answers @itaymendel !
