### ISSUE TITLE
Bit does not support linting for a component

### ISSUE THREAD

**Issue by ranyitz** [teambit/bit#86]
I'm currently working on a project with eslint-airbnb preset.

I'm modifying a bit component written in flow, therefore the linter is completely broken. (showing bad messages because it is a different syntax)

My solution was to create a .eslintrc file with the following configuration inside of the component located in the inline_components directory:

{
  "root": true,
  "extends": ["airbnb", "airbnb-flow"]
}

(I also needed to install the "airbnb-flow" npm dependency in the root of my project)
https://github.com/johnie/eslint-config-airbnb-flow

Every linter uses a different file for configuration, I think we should define a file for the linter in order to enable linting, as the users use it to enforce code style and quality.

**Comment by itaymendel** [comment]
.eslintrc can be added directly to the component using the 'bit add' command.
just like #84
