### ISSUE TITLE
module imports without dots are not resolved

### ISSUE THREAD

**Issue by sonaba** [teambit/bit#865]
if im using dependency pathnames without dots i get "missing packages dependencies" error on "bit status". 
u can find info about importing modules without dots: 
https://medium.com/@ktruong008/absolute-imports-with-create-react-app-4338fbca7e3d
https://jaketrent.com/post/import-js-module-without-dot-dot-slash/
https://stackoverflow.com/questions/45213279/how-to-avoid-using-relative-path-imports-redux-action-action1-in-cre

**Comment by GiladShoham** [comment]
Hi @sonaba 
Thanks for reporting this.
We already start working on support NODE_PATH variable, and we will release it in the near future.
I believe this will solve your issue, correct?

Also, it's worth to know, that once you export bit component to a remote scope (or import a component from remote scope), you can require it using an absolute path without the need of anything else like NODE_PATH / webpack resolve and so on.
you can read more about it here:
https://docs.bitsrc.io/docs/importing-components.html#bindings
https://docs.bitsrc.io/docs/importing-components.html#linking-components

Anyway, I'll keep this issue open and updated.

**Comment by sonaba** [comment]
thanks for the quick response. yes NODE_PATH support will be fine.

**Comment by James-E-Adams** [comment]
Any luck on the NODE_PATH support? :)

**Comment by GiladShoham** [comment]
Yes! We're going to provide an option to configure alias and resolve folders (in a similar way to webpack resolve) in the bit.json file, and we'll use that configuration to correctly detect the dependencies.
You can follow the PR #980 to get updates.
I believe it'll be merged this week.

**Comment by James-E-Adams** [comment]
Nice work! Really like what you guys are doing with bit. 
לא שמתי לב עד עכשיו שאתם חברה ישראלית! :)

**Comment by itaymendel** [comment]
a new version of Bit is available and supports this feature.

more details [here](https://docs.bitsrc.io/docs/isolating-and-tracking-components.html#tracking-a-component-with-a-custom-module-resolution).

**Comment by manufont** [comment]
Thank you @itaymendel 
The example in docs only shows how to define aliases for custom module resolution. Could you please show us an example using absolute paths with NODE_PATH ?

**Comment by itaymendel** [comment]
hi @manufont , i'll add a few more details and explanations around it... but basically this is what you want to configure - you need to add an array to 'resolvemodules' object in the `bit.json` file, and add an array of paths.

```js
 "resolveModules": {
        "modulesDirectories": ["src"]
    }
```

https://docs.bitsrc.io/docs/conf-bit-json.html#resolvemodules--object

**Comment by manufont** [comment]
I just figured it out. Thanks 🙂
