### ISSUE TITLE
Bit snap followed by bit reset clears the forkedFrom entry to the bitmap file

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8702]
### Describe the bug

Bit snap followed by bit reset clears the forkedFrom entry to the bitmap file

### Steps to Reproduce

1. Use `bit snap` on a forked component
2. Use `bit reset` on the component
3. The following part of the components json in .bitmap is cleared
```
"teambit.component/forking": {
                "forkedFrom": {
                    "scope": "myscope",
                    "name": "my-component",
                    "version": "0.0.3"
                }
            },
```

### Expected Behavior
Should keep the forkedFrom info

### Specifications

- Bit version: `1.6.62`
- Workspace type: harmony
- Node version:`v18.19.1`
- npm / yarn version:`10.2.4`
- Platform: `ubuntu`

**Comment by GiladShoham** [comment]
Thanks, we will check it
@davidfirst FYI

**Comment by davidfirst** [comment]
I'm unable to reproduce. See screenshot attached.

<img width="1056" alt="Screenshot 2024-04-29 at 10 44 47 AM" src="https://github.com/teambit/bit/assets/1963573/c2a2147a-df78-428f-8fff-fd60e35814dd">
