### ISSUE TITLE
Typo in docs/intro

### ISSUE THREAD

**Issue by CodeLikeAGirl29** [teambit/bit#8766]
I found a typo in the README.md file.

URL: [bit.dev/docs/intro](http://bit.dev/docs/intro)
Line: 13
Typo: Make sure to **[create your scope on the Bit platform](https://bit.cloud/singup)** and use the right org and project name. After running the command, Bit is initialized on the chosen directory, and ready to be used via Bit commands, [your editor](https://bit.dev/docs/getting-started/installing-bit/editor-setup) or the Bit UI!
Corrected Text: Make sure to [create your scope on the Bit platform](https://bit.cloud/signup) and use the right org and project name. After running the command, Bit is initialized on the chosen directory, and ready to be used via Bit commands, [your editor](https://bit.dev/docs/getting-started/installing-bit/editor-setup) or the Bit UI!

Thank u!

**Comment by davidfirst** [comment]
@CodeLikeAGirl29 , I was reading it 5 times and even put them in an online diff, the original text and the "Corrected Text" are identical :)

**Comment by CodeLikeAGirl29** [comment]
it was actually the link that was bad!

**Comment by roschaefer** [comment]
@davidfirst I ran into this just now. The link is broken. When I click on `create your scope on the Bit platform` it links to https://bit.cloud/singup when it should link to https://bit.cloud/signup.

Please reopen.

This is such a silly mistake. I would expect to see the documentation checked into source, so I can just go ahead and fix it myself. But I can't find the introduction section in this repository: https://github.com/search?q=repo%3Ateambit%2Fbit+Welcome+to+the+Bit+documentation.&type=code

It seems as if the documentation is not part of this repository :sob:

I googled "bit.dev documentation source code" and found https://github.com/teambit/docs which is archived. Where is the source for the documentation website?

I found at least two more typos:
1. https://bit.cloud/teambit/documenter it is "documentation" not "documantation"
2. https://bit.dev/docs/getting-started/composing/dev-environments#compose-your-own-dev-environment button "typescript" links to https://bit.dev/docs/node-components/node-modules which gives 404
