### ISSUE TITLE
Reinitializing Component throws already in use Error

### ISSUE THREAD

**Issue by Ahakke** [teambit/bit#879]
## Expected Behavior
When removing a component from my Scope i should be able to push a new component with the same folder again.

## Actual Behavior
throws warning and exits:
warning: files src/models/ask/index.js,...... already used by component: xxx.xx/src/models@0.0.1

## Steps to Reproduce the Problem

  1.add a component from a folder
  1.remove the component
  1.add the same component again

## Specifications

  - Bit version: 0.12.10
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by Ahakke** [comment]
i think the error came from me removing the component from a command line which was not in my project root. therefore the bit versioning f my project root thinks the Component is still online..

A "bit sync with web" command would be nice to fix this misstake

**Comment by GiladShoham** [comment]
Thanks for reporting @Ahakke .
Removing from an inner folder or from the root should make the same result.
I'll check this and fix it.

**Comment by Ahakke** [comment]
It was a cmd which was not in my project at all..

**Comment by davidfirst** [comment]
If I understand the issue correctly, 'bit remove' basically removed the remote component and not the local one, and then when the component is re-added it shows a warning saying the component is already tracked.

It was indeed very confusing and therefore we changed the command to remove only from the local, unless "--remote" flag is added. 

@Ahakke please re-open if you think it's still an issue.
