### ISSUE TITLE
import is fetching an old version of the component after it's been updated.

### ISSUE THREAD

**Issue by ranyitz** [teambit/bit#88]
I had a bug with one of the testers in bit-js project, so I needed to modify it from a different project. I opened a new project (` $ mkdir new-project $ bit init `) and modified `bit.envs/testers/mocha`.

```bash
$ bit modify bit.envs/testers/mocha
```
**It was at version 5**
I've modified it, committed and export it back to the scope

```
$ bit commit testers/mocha "remove bit-js from bit.json
$ bit export @this/testers/mocha bit.envs
```
After I got back to my original project (bit-js) I tried to import the latest version ( **version 6** )
```
$ bit import bit.envs/testers/mocha
```

but instead of getting the version 6 I got version 5 and the bug occurred again.

After few retries I realized that it's not going to work and tried to import the version 6 directly, then I got an error that the version 6 does not exist.

<img width="981" alt="import_error" src="https://cloud.githubusercontent.com/assets/11733036/23864904/a865eb62-081c-11e7-9aad-c873f813d10e.png">

Technical explanation:
Bit uses cache, and there is no way to remove it.
The bug occurred because the component-object (cached) had only 5 versions.
Bit should go and check the latest version in the remote scope before deciding to use the latest version specified in the cached component-object.

Right now, once you've imported a component, the current versions of this component stay cached and you can never update until you remove it.

A workaround would be to delete the .bit/objects directory.

**Comment by itaymendel** [comment]
resolved a few months ago, but forgot to close issue in time.
