### ISSUE TITLE
Export Error

### ISSUE THREAD

**Issue by RafaelC2000** [teambit/bit#8807]
### Description

Im trying to export a component to cloud, put to execute "bit export rafaelc2000.rafaelc2000" bit want a username and password, im using the keys with im log on the bit web, but bit return the next text:

$ bit export rafaelc2000.rafaelc2000
username:  rafaelc2000
password:                                                             
authentication failed. see troubleshooting at https://docs.bit.dev/docs/setup-authentication#autentication-issues.html

The following strategies were failed
[-] failed to authenticate with user token. generate a new token by running `bit logout && bit login`.
[-] unable to get SSH keys from ssh-agent to. perhaps service is down or disabled.
[-] error connecting with private ssh key. in case passphrase is used, use ssh-agent.
[-] unable to connect using provided username and password combination.

run 'bit doctor' to get detailed workspace diagnosis and issue resolution.

with bit doctor send all ok

### Specifications

- Bit version: 14.8.8
- Node version: v20.3.1
- npm / yarn version: 9.6.7 / 1.22.19
- Platform: win32
- Bit compiler (include version):  ####
- Bit tester (include version): ####

### Context and additional information

I´m change the password, and dont work and  in cloud Authentication mark 0 logins, altought i was logout and login a lot of chances, and with bit config i can see the token login

**Comment by itaymendel** [comment]
hi, it seems you installed a very old version of Bit (14.8.8, which is "legacy bit").
please use the install instruction as noted in the docs:

```
npx @teambit/bvm install
```

Before installing it, ensure you completely remove the instance of Bit you have installed before.
