### ISSUE TITLE
Very slow to install bit

### ISSUE THREAD

**Issue by MatthD** [teambit/bit#8823]
### Describe the bug

Installing bit inside Dockerfile to be able to install deps, it take >1mn to download/install
This is not related to my connexion , apt update is fast. ~600mbps
It literally take  2 mn 🙃 (~50s to download and 39s to extract , using `child_process` took 11seconds of uncompress), not really acceptable in a CI for eg

### Steps to Reproduce

1. In a DockerFile just run `RUN npx @teambit/bvm install`

### Expected Behavior

Download binary and install should be fast 🙃

### Screenshots, exceptions and logs

```bash
27 [tests deps_dev  9/12] RUN npx @teambit/bvm install
#27 0.742 npm WARN exec The following package was not found and will be installed: @teambit/bvm@1.0.3
#27 16.20 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
#27 70.16 ✔ downloading version 1.6.140 in 48.948 seconds
#27 109.4 ✔ extracting version 1.6.140 in 39.193 seconds
#27 109.4 - removing /home/node/.bvm/temp/bit-1.6.140-linux-arm64.tar.gz
#27 109.5 ✔ removing /home/node/.bvm/temp/bit-1.6.140-linux-arm64.tar.gz in 141 milliseconds
#27 109.5 - moving from temp folder to final location
#27 109.5 ✔ moving from temp folder to final location in 4 milliseconds
#27 109.5 - downloading Node.js 20.11.1
#27 111.9 ✔ downloading Node.js 20.11.1
#27 111.9 version 1.6.140 installed on /home/node/.bvm/versions/1.6.140 in 1 minute, 31.347 seconds
#27 111.9 Couldn't update the system PATH because failed to detect the active shell.
#27 111.9 You can either set the SHELL env variable to your shell name (e.g., "SHELL=bash bvm install")
#27 111.9 or add the following to your bash/zsh profile then re-open the terminal:
#27 111.9 export PATH=$HOME/bin:$PATH
#27 111.9 for more information read here - https://bit.dev/reference/reference/using-bvm#troubleshooting
#27 111.9 npm notice
#27 111.9 npm notice New minor version of npm available! 10.2.4 -> 10.5.2
#27 111.9 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.2>
#27 111.9 npm notice Run `npm install -g npm@10.5.2` to update!
#27 111.9 npm notice
#27 DONE 113.5s
```

### Specifications

- Bit version: 1.6.126
- Node version: 20.11.0
- npm / yarn version: 10.2.4
- Platform: Mac0s 14.4.1 arm M2
- Bit compiler (include version): pnpm

**Comment by itaymendel** [comment]
hi, we do ship a container with Bit pre-installed.
```
docker pull bitsrc/stable:latest
```

you can find it here - https://github.com/bit-tasks/bit-docker-image

please use this to speed up your CI.

regardless, we are working to get the installation to be much faster. currently it's a huge tarball that gets extracted to many small files. in the coming weeks it will be replaces with a far more efficient and small single bundle.
so file that gets downloaded will be much smaller, and extracting it will be much faster. it should be efficient enough to potentially skip the `bvm` tool completely.

**Comment by GiladShoham** [comment]
Thanks for reporting.
We are aware of this and working on it.
Meanwhile you can use one of our base images.
We build base image for each version of bit.

**Comment by MatthD** [comment]
So great to hear, thanks !!
