### ISSUE TITLE
Not possible to add remote bit scope

### ISSUE THREAD

**Issue by scrodrig** [teambit/bit#8825]
### Describe the bug

When trying to add a remote in the last BIt version `v1.6.140`, it gives an error `fetch failed` with no further details.
However, this errror is not happening in previous version `v1.6.126`

### Steps to Reproduce

1. `bvm install 1.6.140`
2.  `bit init --default-scope my-org.my_scope`
3. `bit remote add https://{private_host}`

### Expected Behavior

Add successfully a remote scope

### Specifications

- Bit version: `1.6.140`
- Workspace type: harmony
- Node version: `v20.12.0`
- npm / yarn version: `10.5.0`
- Platform: Windows 10

*for harmony workspace*
- relevant env

|               |               |
|------------------|----------------------------------------|
| env              | teambit.node/node@1.0.54               |
| dev dependencies | @teambit/node.node@1.0.54- (component) |

- relevant aspects

| aspects |                                         |
| ------- | --------------------------------------- |
|         | teambit.component/dev-files             |
|         | teambit.compositions/compositions       |
|         | teambit.dependencies/dependency-resolve |
|         | teambit.docs/docs                       |
|         | teambit.envs/envs                       |
|         | teambit.harmony/application             |
|         | teambit.pkg/pkg                         |
|         | teambit.preview/preview                 |
|         | teambit.semantics/schema                |

**Comment by GiladShoham** [comment]
Please attach the debug.log 
You can find it by running bit globals command

**Comment by scrodrig** [comment]
I closed since I lost access to the specific logs
