### ISSUE TITLE
New workspace env not found error

### ISSUE THREAD

**Issue by sbland** [teambit/bit#8856]
### Describe the bug

Running `bit new react my-project --env bitdev.react/react-env --default-scope my-org.my-project` results in the error `could not load extension: bitdev.react/react-env@2.0.2 with error: EnvNotFound: environment with ID: bitdev.general/envs/bit-env@1.0.1 configured on component bitdev.react/react-env@2.0.2 was not found`

### Specifications

- Bit version: 1.6.62
- Workspace type: harmony
- Node version: v16.20.2
- npm / yarn version:
- Platform: WSL 2

**Comment by GiladShoham** [comment]
This happen on the first time because the bit-env at this point is not loaded yet.
Your can ignore it for now.
Everything should work just fine.
I'll fix it so the error won't be presented.

**Comment by sbland** [comment]
Thanks I also updated bit and it seems to be working now
