### ISSUE TITLE
Where to download file bin to install ?

### ISSUE THREAD

**Issue by MatthD** [teambit/bit#8942]
### Description

Regarding the time it take ATM to install bit/bvm via npm I am looking for a way to download it on server that could be faster ? 
https://github.com/teambit/bit/issues/8823

I saw an options on the bvm to install bit from a file `-f` but where can I dowload it first ?

**Comment by GiladShoham** [comment]
also want to let you know that I'm working on bundling bit and hope to make it around 50mb (maybe even less) instead of 1gb that it's now.
but it's a very complicated task so it will take some time to complete. 
once done, it will take seconds to download and extract.

**Comment by MatthD** [comment]
Thanks for those precision ! 

Maybe a quick win could be to add higher compression to the tar pointed ?
Just tried myself so compress it with a higher level, we gain much and it's not taking too much more time to uncompress

![Capture d’écran 2024-06-07 à 09 25 20](https://github.com/teambit/bit/assets/7901366/dc1c6c2a-60c7-444d-a3f7-6354fbe809e3)
