### ISSUE TITLE
Deployed self hosted Docker, but access failed.

### ISSUE THREAD

**Issue by XQY279** [teambit/bit#8948]
After remote-scope runs successfully, but access fails:

1. I pulled the bit-cli and bare-scope images, and both were successful.
2. Executing docker run -it -p 3000 bitcli/bit-server:latest was successful and output was generated.

<img width="1452" alt="image" src="https://github.com/teambit/bit/assets/45452939/53847be9-b260-48f8-923d-6074bd0b32a1">

However, the access failed.
<img width="1458" alt="image" src="https://github.com/teambit/bit/assets/45452939/e740d177-b641-4e6a-8cea-635386dc66da">

**Comment by GiladShoham** [comment]
What is the full error?
