### ISSUE TITLE
Can I use vite for ui component build and preview

### ISSUE THREAD

**Issue by StarHosea** [teambit/bit#8955]
### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Bit compiler (include version):
- Bit tester (include version):

**Comment by itaymendel** [comment]
hi, at the moment bit only supports webpack for component previews.
This does not impact on how the consuming apps will use or render the component and is strictly for building the docs and previews for the component, as used by Bit.

having said that, we are working to introduce a vite plugin to handle previews. eta for it is still TBD.

once vite is supported we will publish an announcement.

**Comment by GiladShoham** [comment]
we are also actively working on support for `rspack` for components preview as well

**Comment by StarHosea** [comment]
Thank you for your response. I'm looking forward to it!
