### ISSUE TITLE
Automating components release into a self created remote scope using Docker image.

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#8957]
How can I automate my components release to a docker hoisted remote scope? Please explain it step by step. 

I have setup a remote scope using a docker image created using the following Dockerfile.

![image](https://github.com/teambit/bit/assets/42240148/a15b38cd-895f-417f-a814-94212b854bd0)

**Comment by itaymendel** [comment]
You can find all relevant steps in the documentation portal. i recommend starting here - https://bit.dev/reference/reference/scope/creating-scopes

**Comment by subham25997** [comment]
Thank you for your quick response. But I didn't get what I am looking for in this link. Let me explain you:

- I have hoisted a remote scope using my own docker image.
- Now I want to automate the process of releasing my components to remote scope from my Gitlab repo. 

**My queries:**

1. Do I need to follow the steps defined on [Bit doc page](https://bit.dev/blog/integrating-bit-with-your-existing-ci-lq55w51k/) ?
2. Will I use the **automating-component-releases.zip** for my own remote server or it'll only work for Bit.cloud?
