### ISSUE TITLE
Cannot find module 'Dimensions' from 'react-native-implementation.js'

### ISSUE THREAD

**Issue by fedegl** [teambit/bit#898]
## Expected Behavior
I am able to run `bit test rounded-button` without having to mock `react-native`

## Actual Behavior
I get cannot find module `X`. X being any react-native provided module.
```
rounded-button
tests failed
file: RoundedButton/RoundedButton.test.js
total duration - 0ms


❌   Test suite failed to run - 0ms
      ● Test suite failed to run

    Cannot find module 'Dimensions' from 'react-native-implementation.js'

    > 1 | 'use strict';
      2 | 
      3 | Object.defineProperty(exports, "__esModule", {
      4 |   value: true

      at Resolver.resolveModule (../../../../node_modules/jest-resolve/build/index.js:169:17)
      at Object.get Dimensions [as Dimensions] (../../../../node_modules/react-native/Libraries/react-native/react-native-implementation.js:80:29)
      at Object.<anonymous> (../../Themes/Metrics.js:1:233)
```

## Steps to Reproduce the Problem

  1. Implement any React component which has depends on a module from the `react-native` package. Like the following repository: https://github.com/littlebitselectronics/rounded_button
  2. run `bit test rounded-button`

## Specifications

  - Bit version: bit-bin@0.12.10
  - Node version: v8.6.0
  - npm / yarn version: yarn v1.5.1
  - Platform: macOS 10.13.3
  - Bit compiler (include version): react@0.0.13
  - Bit tester (include version): jest@0.0.32

**Comment by itaymendel** [comment]
hi @fedegl sorry for the long response time.
there is an issue with the jest tester and react-native, this is not the first time it happens.
the next release of Bit contains major refactors to how envs work, and will allow to use the configurations from the original project of the component. this should sovle the issue.
i'm keeping this issue open for reference, and to update once the new env is up and running.

**Comment by itaymendel** [comment]
ok, i'm closing this issue, but just to clarify on it matter of dependencies for component specs.

right now all testers have a predefined configuration. in order to modify it, and create a config for a specific project, you need to import one of the testers and change its config accordingly.

we're stabilizing a set of APIs that will allow passing env's configs to the env, thus making the flow of forking an env redundant.
