### ISSUE TITLE
bit import error: permission to scope hub.bit.dev:loanmarket.share was denied

### ISSUE THREAD

**Issue by juztinlazaro** [teambit/bit#8980]
after the legacy im having an issue in bit import 

```
bit import
error: permission to scope hub.bit.dev:loanmarket.share was denied
```

**Comment by itaymendel** [comment]
Hi I don't fully understand the issue. Can you please elaborate so we can try and reproduce it?

**Comment by gefernandez-blume** [comment]
Facing the same issue in legacy bit. Getting the below error
error: permission to scope hub.bit.dev:  was denied

**Comment by itaymendel** [comment]
issue found and resolved. SSH agent updated.

Note, if you are using legacy-bit, it is recommended to migrate to Harmony.

**Comment by gefernandez-blume** [comment]
Did a bit logout and logged in again. Tried import and getting the same issue.

Your browser has been opened to visit:
https://bit.dev/bit-login?port=8085&clientId=55ae2c09-6b74-42e0-b038-0e4f9f7cd647&responseType=token&deviceName=botooles-MacBook-Pro-7.local&os=darwin

successfully added @bit as a scoped registry at /Users/geraldfernandez/.npmrc
success! logged in as *******

error: permission to scope ********* was denied

**Comment by gefernandez-blume** [comment]
Tried via ssh authentication and its working fine now.
