### ISSUE TITLE
Add --logs flag to Bit CLI Reference documentation

### ISSUE THREAD

**Issue by harinlee0803** [teambit/bit#9030]
Please include the --logs flag in the documentation for the Bit CLI Reference, specifically for commands such as bit snap and bit export. This flag is crucial for debugging purposes. Currently, it is not mentioned in the official documentation, and I had to search through other GitHub issues to discover its existence. Including it in the official documentation would greatly aid users in troubleshooting and improve the overall user experience.

Thank you!

**Comment by davidfirst** [comment]
@harinlee0803 , this flag is a global flag. Meaning all commands have it, that's why it doesn't show in the docs per command. The easiest way to find the flags is by running `bit your-command -h`.
