### ISSUE TITLE
Unable to install components from my local remote scope

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9044]
### Description

- I have hoisted a remote scope in my local and exported an app component to it.

![image](https://github.com/user-attachments/assets/8717964d-c9c1-492c-9dd9-3f2e0d2cfb56)

- Also, I have configured my .npmrc file like this: 

"'@app1-scope:registry'"=http://localhost:5000

When I use the cmd **bit install @app1-scope/apps.app@0.0.1** in my vue app, I am getting following error.

![image](https://github.com/user-attachments/assets/29313b5d-40ad-4faf-9cf9-7208aaa3e3ae)

### Specifications

- Bit version: 1.7.3
- Node version: v16.17.0
- npm version: 8.15.0

**Comment by GiladShoham** [comment]
A self-remote scope is not a registry, you need to setup your components to be published to an npm registry.
please see more details [here](https://bit.dev/reference/reference/scope/running-a-scope-server#publish-component-packages-to-npm-registry)
