### ISSUE TITLE
Is it possible to use Gitlab container registry to make Bit components installable as packages? 

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9051]
I have hoisted a remote scope using Docker, but I am unable to install them as packages because it's not a registry. 

Is it possible to use Gitlab container registry to make Bit components installable as packages? If yes, please explain each and every step. I tried your documentation, but couldn't get much.

**Comment by itaymendel** [comment]
While I do not have any past experience with GitLab registry, if it works like any other package registry you can publish packages to, you can do that.

The documentation explain how to publish components as packages to any type of npm-registry
https://bit.dev/reference/packages/publishing-components-to-commonjs-registries#publish-your-components-to-other-registries
