### ISSUE TITLE
Importing bit vue component to a NUXT project gives error

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9068]
- Created a NUXT project
- Imported ButtonComponent and run the following commands
   1. bit install --add-missing-deps
   2. bit build

-  Imported and used the ButtonComponent as in the image below

![image](https://github.com/user-attachments/assets/fa945892-2002-47e3-9f9c-0080f7cee854)

Getting following error:
![image](https://github.com/user-attachments/assets/1478a73b-73bb-4c8f-854f-e8e4fe097df5)

- Bit version: 1.7.3
- Node version: 16.17.0
- npm : 8.15.0

**Comment by Jinjiang** [comment]
May I know what you would get if you run `bit status` and `bit envs` in your workspace? Then I can take some further debugging. Thanks.

**Comment by subham25997** [comment]
It was due to version mismatch of Vue.
