### ISSUE TITLE
Vuetify not working with bit component when I import and use it in NUXT project

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9071]
**My Workspace**
- Created a Button Component in my workspace as follow:
![image](https://github.com/user-attachments/assets/d3b1949e-6c46-42d6-9c93-73c6e1ef3936)

- Setup vuetify as dependency:
 **bit deps set ui/button-component vuetify --peer**
- Tagged and exported the component to remote scope.

**NUXT APP**
- Created a NUXT app with Vue 3 and Vuetify 3
- Initialized it as a bit workspace using **bit init**
- Imported the Button Component and used it as follow:
![image](https://github.com/user-attachments/assets/46c029a8-e8b4-4601-9227-f16886d4ca5a)

- It doesn't apply vuetify. (It works with other normal component but not on Bit component.)
![image](https://github.com/user-attachments/assets/fcb03aa5-ad9b-4a76-a4fc-4b3c1dccf49d)

**Getting error:**
![image](https://github.com/user-attachments/assets/2b22b30c-9cdc-4409-881e-5f70b34cd31c)

### Specifications

- Bit version: 1.7.3
- Node version: v16.17.0
- npm version: 8.15.0

**Comment by Jinjiang** [comment]
I suggest:

1. if you set vuetify as a peer dep, you have to ensure it's well-installed where you consume your components. Here that means the new workspace you have created.
2. the `v-btn` is usually registered by an auto-import plugin like https://www.npmjs.com/package/vite-plugin-vuetify or https://www.npmjs.com/package/webpack-plugin-vuetify. I guess it's not well-configured in your workspace. Another way to make it works is explicitly import it in your app like:
    ```vue
    <script setup>
    import { VBtn } from 'vuetify/components'
    </script>

    <template>
      <v-btn>...</v-btn>
    </template>
    ```

**Comment by subham25997** [comment]
Thank you! It worked.
