### ISSUE TITLE
The CJS build of Vite's Node API is deprecated for new workspace with custom react environment

### ISSUE THREAD

**Issue by sbland** [teambit/bit#9074]
### Describe the bug

I get the following warning for a new workspace with custom react env 
`The CJS build of Vite's Node API is deprecated`

### Steps to Reproduce

1. `bit init`
2. `bit create react-env envs/my-react-env --aspect bitdev.react/react-env`
3. `bit create react demo-component --env envs/my-react-env`
4. `bit test`

### Specifications

- Bit version: 1.7.48
- Workspace type: (harmony/legacy)
- Node version: v18.19.1

*for harmony workspace*
- relevant env `bitdev.react/react-env`

**Comment by Jinjiang** [comment]
@sbland No worries. It's totally fine to proceed. The removal of Vite CJS build won't happen in a short moment.

And BTW, the warning message was actually caught by some core Vite plugins in Vite community. So it definitely works except Vite want to break their own world. 😉 

Anyway, we are keeping an eye on that and will update accordingly once the relevant core plugins are updated.

**Comment by itaymendel** [comment]
fix shipped for this. there was an issue with the component that loads ESM modules to CJS (https://bit.cloud/bitdev/node/modules/load-esm-module/~api-reference). to update run `bit env update && bit update "@teambit/**,@bitdev/**` to update all deps and rerun the test/build commands.
