### ISSUE TITLE
Bit received an error loading teambit.vue/vue@0.1.39, due to the error: "Cannot find module '@teambit/legacy/dist/consumer/component/dependencies/files-dependency-builder/detectives/detective-es6'"

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9086]
I tried creating a workspace with following command:
**bit new vue app2-workspace --env teambit.vue/vue --default-scope app2-scope**

But got following error:

![image](https://github.com/user-attachments/assets/dc75fd4d-f749-4d9f-93b8-bce3181e1453)

### Specifications

- Bit version: 1.8.20
- Node version: v20.16.0
- npm version: 10.8.1

**Comment by Jinjiang** [comment]
Reproduced. We are checking it. Thanks.

**Comment by Jinjiang** [comment]
BTW, you can use another vue env `bitdev.vue/vue` instead. That's the latest one we are maintaining.

```bash
bit new vue app2-workspace --env bitdev.vue/vue-env --default-scope app2-scope
```

**Comment by Jinjiang** [comment]
@subham25997 `teambit.vue/vue` just got updated to v0.1.40. the issue has been fixed. feel free to try it again. Thanks.
