### ISSUE TITLE
ERROR  [nuxt] [request error] [unhandled] [500] Unexpected token '<'

### ISSUE THREAD

**Issue by subham25997** [teambit/bit#9102]
- Create a workspace using following cmd:
   **bit new vue app2-workspace --env  bitdev.vue/vue-env --default-scope app2-scope**
- Create a view component using following:
   **bit create vue core/custom-button**
- Exported the component to remote scope.
- Created a NUXT3 app using following cmd:
   **npx nuxi@latest init nuxt-bit-app**
- Initialized it as bit repo and added remote scope:
   **bit init --default-scope app2-scope**
   **bit remote add http://localhost:5001**
- Imported the custom-button component from remote scope and used it:
  
![image](https://github.com/user-attachments/assets/830f13fb-90e0-45c6-a313-f038aad2af79)
- Performed **bit install --add-missing-deps** and served the app using **npm run dev**

- Got following issue:
 
![image](https://github.com/user-attachments/assets/652aa51a-010e-414f-a90b-f66fb2e19725)
![image](https://github.com/user-attachments/assets/5eb95458-70ab-4361-9195-42a150e9e8d6)

**If I create a normal vue component in the app and use it, it works fine.**

### Specifications

- Bit version: 1.8.20
- Node version: 20.16.0
- npm version: 10.8.1

**Comment by Jinjiang** [comment]
Seems like the Vue files weren't correctly compiled. Would you mind running `bit status` and check the output? And please also try to run `bit compile` one more time if nothing suspicious in the output.

Thanks.

**Comment by Jinjiang** [comment]
And may I know how you exported the component to remote scope, please?

**Comment by subham25997** [comment]
I tagged the component using **bit tag -m "message"** and then exported it using **bit export**

**Comment by subham25997** [comment]
On running bit status, I got this
![image](https://github.com/user-attachments/assets/49fa1cea-8222-4ffe-a513-0832f8e4ce65)

**Comment by subham25997** [comment]
After **bit compile**, when I serve the app using **npm run serve**, I got following:

![image](https://github.com/user-attachments/assets/33b4971f-7449-4a6d-81aa-c57fdd20472b)

**Comment by Jinjiang** [comment]
I see. I understand after bit compile the original error disappeared but the .css request error came, right?

I'll take a look at what happened.

**Comment by Jinjiang** [comment]
I think the latest issue is a known one in Nuxt
https://github.com/nuxt/nuxt/issues/15321#issuecomment-1489039998

try to set the `build.transpile` according to your component scope

**Comment by subham25997** [comment]
I added **build.transpile** in nuxt.config.ts as follow and it worked (suite360 is scope name):

![image](https://github.com/user-attachments/assets/2343e254-d1b8-4347-a4b5-94d3b0ca6f80)
