### ISSUE TITLE
Add more parameters to bit init to configure bit.json

### ISSUE THREAD

**Issue by kcampion** [teambit/bit#913]
## Expected Behavior

It could be great to edit some configurations from the initialization like that:
`$ bit init --componentsDefaultDirectory="{namespace}/{name}" --packageManager="yarn"`

## Actual Behavior

After a `$ bit init` we must edit the bit.json to update these values.

## Specifications

  - Bit version: 0.12.11
  - Node version: 9.2.1
  - Platform: osx

**Comment by GiladShoham** [comment]
@kcampion That's a great idea, we will add it to our backlog

**Comment by cristinallamas** [comment]
yes please!

**Comment by GiladShoham** [comment]
Update: I've started to work on this feature (along with some other cool features for bit init) in this branch: https://github.com/teambit/bit/tree/feature/interactive-init
