### ISSUE TITLE
Next.js Quickstart not working

### ISSUE THREAD

**Issue by angel-luis** [teambit/bit#9146]
```
bit new hello-world-nextjs my-hello-world-nextjs --aspect teambit.community/starters/hello-world-nextjs
```
Borrowed from:  https://bit.dev/docs/quick-start/hello-world-nextjs
```
error: component "bitdev.nextjs/examples/my-nextjs-env" was not found
```
```
bit --version
1.8.20
macOS Version:
- Product Name: Mac OS X
- Product Version: 10.15.7
- Build Version: 19H2026
Hardware Overview:
- Model Name: MacBook Pro
- Model Identifier: MacBookPro10,1
```

**Comment by leimonio** [comment]
Hey @angel-luis we have recently changed and deprecated some of our workspace generators. 

Please use `bit new hello-world-nextjs my-hello-world-nextjs --env frontend.nextjs/templates/community-starters/hello-world-nextjs` instead.  A docs update is about to be released as well.
