### ISSUE TITLE
Vue Vite Tailwind Preview

### ISSUE THREAD

**Issue by harinlee0803** [teambit/bit#9148]
I am migrating my webpack [vue-classic-env](https://bit.cloud/bitdev/vue/envs/vue-classic-env) to the vite [vue-modern-env](https://bit.cloud/bitdev/vue/envs/vue-modern-env). For my classic vue env, I had followed this [bit blog](https://bit.dev/blog/integrating-tailwind-css-and-bit-for-component-styling-lgntqstt/) to integrate tailwind CSS into my docs and previews. Is there any documentation available for using tailwind in the vite env?

**Comment by Jinjiang** [comment]
Not yet. I think we will have an example soon. Before that if you are interested to try on your own, just follow this:

1. get the postcss config of tailwind through this guide https://tailwindcss.com/docs/guides/vite
2. pass the postcss config into `./config/vite.config.mjs` via this option: https://vitejs.dev/config/shared-options.html#css-postcss

Thanks.

**Comment by harinlee0803** [comment]
Ok documenting my attempt. Here is what I've tried but am unable to get tailwind to show in the previews.

1. Run `bit install tailwindcss postcss autoprefixer`
2. Run `npx tailwindcss init -p` to generate `tailwind.config.js` and `postcss.config.js` files in the config directory of [modern-vue-env](https://bit.cloud/bitdev/vue/envs/vue-modern-env)
3. Run `bit install @learnbit/styling.config.tailwind `
4. Add `import '@learnbit/styling.config.tailwind/globals.tailwind.css';` into my composition file
5. Run `bit start` but unable to see tailwind classes.


**vite.config.mjs**
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  css: {
    postcss: "./postcss.config.js"
  }
})
```

**my-test.composition.ts**
```
import BasicMyTest from "./my-test-basic.fixture.vue";
import '@learnbit/styling.config.tailwind/globals.tailwind.css';

export { BasicMyTest };

```

@Jinjiang Anything missing here?

**Comment by harinlee0803** [comment]
Ok figured it out after some poking around.

postcss.config.js
```
export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
```
tailwind.config.js
```
// tailwind.config.js
import { globSync } from 'glob';
// get the TSX and JSX files from the project without using the built-in glob matcher of tailwind
// to reduce the number of files Tailwind will try to scan
const content = globSync(['**/*.{vue,jsx,tsx}'], {
  ignore: ['**/node_modules/**'],
});

/** @type {import('tailwindcss').Config} */
export default {
  content: content,
  theme: {
    extend: {},
  },
  plugins: [],
};
```

vite.config.mjs
```
// vite.config.js
import { defineConfig } from 'vite';
import tailwindcss from 'tailwindcss';
import tailwindConfig from './tailwind.config.js';
import autoprefixer from 'autoprefixer';

export default defineConfig({
  css: {
    postcss: {
      plugins: [
        tailwindcss(tailwindConfig),
        autoprefixer(),
      ],
    },
  },
});

```

Closing the issue.
