### ISSUE TITLE
ssh-agent and ssh-add automatically

### ISSUE THREAD

**Issue by kcampion** [teambit/bit#916]
## Expected Behavior

To use `$ bit export`, we must do a ssh-agent and ssh-add before at the first time we open a new terminal. Is it possible to execute these commands automatically if "bit" detects `permission to scope hub.bitsrc.io:me.scope was denied`?

## Specifications

  - Bit version: 0.12.11
  - Node version: 9.2.1
  - Platform: osx

**Comment by GiladShoham** [comment]
Thanks for reporting @kcampion 

In the next release, we will add a new ‘bit login’ command which will provide a stable and easy to use authentication solution.

Ssh keys will still be supported.

You can follow this PR https://github.com/teambit/bit/pull/920

**Comment by itaymendel** [comment]
irrelevant, as bit automates an authentication process using `bit login`.
