### ISSUE TITLE
renaming a scope (not only its components)

### ISSUE THREAD

**Issue by iham** [teambit/bit#9191]
I use docker and based on your bit-server image I want to change/set the name of that scope already initiated inside the container.

that scope is created, as documented ```bit init --bare``` - which is done on image creation (build time)
```bit scope rename <current-scope-name> <new-scope-name>``` is mentioned, but can only be run in a workspace:
"This command can only be run inside a bit workspace. Please check that you are inside a bit workspace and then re-run (to initialize a new workspace please use bit init)"

well, I don't want a workspace; just a scope (remote) server. with a useful name, as I run multiple in one project.
the need to create a separate docker image for each scope seems to be a big overhead for just a name.

why not make renaming a scope a thing of a scope, instead of a workspace?

**Comment by GiladShoham** [comment]
I believe we can do it.
But you don't have to wait for us
1. There is a build arg with a scope name that you can provide.
2. The scope name is determined by the folder name by default so you can change it.
3. There is a scope.json file inside which contains the scope name. You can just change it.

**Comment by iham** [comment]
as mentioned
1. I understood the build time argument (SCOPE_PATH). -> but don't want to build a separate image just for a name.
2. I also got, that the name is derived from the folder bit init is run in. -> I don't want to set different folder names and again, don't want to build a separate image just for a name.
3. I managed to replace the name property in scope.json based on an ENV variable I use.

you can take a look here: https://github.com/iham/bit/blob/main/server/entrypoint.sh

I am really looking forward being able to rename scopes for that use case.
would be handy to have a ```bit scope rename <current-name> <new-name>``` command, which is not bound to a workspace and works on bare scope servers too.

**Comment by iham** [comment]
as bits docs make it impossible to distinguish between old/new/deprecated and best practise on current development or plainly  examples, that don't work at all, I ditched it and moved away from using bit any further.

**Comment by GiladShoham** [comment]
I would love to get your feedback about the docs so we can improve it further. 
what do you mean by `old/new/deprecated and best practise`
