### ISSUE TITLE
Using AND in a bit pattern with $modified and $env does not work

### ISSUE THREAD

**Issue by sbland** [teambit/bit#9232]
### Describe the bug

Using bit pattern with `$modified AND $env:teambit.react/react` returns 0 components despite using them seperately without `AND` returning components that are modified and in the selected env.

### Steps to Reproduce

1. Run `$modified AND $env:teambit.react/react` 0 components
2. Run `$env:teambit.react/react` returns modified components
3. Run `$modified` returns components in the above env.

### Expected Behavior

Should return modified components in the above env.

### Specifications

- Bit version: 1.8.68
- Workspace type: harmony
- Node version:v18.19.1
- npm / yarn version:10.2.4
- Platform: Ubuntu

**Comment by GiladShoham** [comment]
Thanks, we will look into it
