### ISSUE TITLE
Hide the prompt for the command "remove --force"

### ISSUE THREAD

**Issue by kcampion** [teambit/bit#949]
## Expected Behavior

Bit always displays a prompt when we use `$ bit remove foo/bar --force`. This behaviour generates some problems if we try to execute Bit by a shell command from nodejs by example.

## Specifications

  - Bit version: 0.12.11

**Comment by GiladShoham** [comment]
Thanks for the feedback @kcampion 
You can use the -s / --silent flag which skips the confirmation prompt.
I see this flag missing from our docs, we will make sure to add it.
closing this, if there is still a problem feel free to reopen.
