### ISSUE TITLE
No command to change files in a component (can't edit .bitmap

### ISSUE THREAD

**Issue by claudeduguay** [teambit/bit#962]
## Expected Behavior

There should be a way to remove a file from inclusion in a give id.

Note that it's also not possible to specify a file as a test file without editing .bitmap directly.

Also some specification of what's permissible in .bitmap would be useful, even if it has a warning that any messing with the file can cause failures. (the reported bug was not caused by hand-editing but I had edited in a previous/separate projects/experiment).

## Actual Behavior

bit add --exclude ...

Fails if --exclude and --id are the only parameters.

bit remove

Removes the entire component

## Steps to Reproduce the Problem

  1. Given an exiting tracked component 
  2. bit add --id namespace/componentname --exclude <file to exclude>
  3. error!

## Specifications

  - Bit version: 0.12.12
  - Node version: v8.9.1
  - npm / yarn version: npm v6.0.0
  - Platform: Windows
  - Bit compiler (include version): bit.envs/compilers/typescript@0.0.3
  - Bit tester (include version): bit.envs/testers/jest@0.0.32

**Comment by claudeduguay** [comment]
How does one exclude a file that was already included in tracking without editing .bitmap?

**Comment by davidfirst** [comment]
@claudeduguay, sorry for the late response. I can think of two ways to achieve this.
1. use `bit untrack` command to remove the current component from .bitmap. Notice that this command works only for non-exported components. Once a component is exported, it won't work.
2. use `bit add` with `--override` flag. This flag removes the current list of the files from .bitmap and replaces them with the specified files. 
Notice that in the case you have described above, you will need to specify the files you would like to add along with what files to exclude.

Regarding the specification of the .bitmap file, it is intended to be internal, you can see however the related code here: https://github.com/teambit/bit/blob/master/src/consumer/bit-map/component-map.js

**Comment by itaymendel** [comment]
this was probably due to a past bug that was fixed.
closing this issue.
please see this section in the docs about [removing files from components](https://docs.bit.dev/docs/manage-component-files.html#removing-files-from-components).
