### ISSUE TITLE
compilers/babel fails to build valid .ts files

### ISSUE THREAD

**Issue by claudeduguay** [teambit/bit#963]
## Expected Behavior

Dropping a valid .ts file (and possibly a tsconfig.json file) into a bit project with the following configuration should work:

"env": {
        "compiler": "bit.envs/compilers/babel@0.0.20",
...

## Actual Behavior

Produces SyntaxError: unknown: Unexpected token, expected

## Steps to Reproduce the Problem

  1. Clone a project that uses bit.envs/compilers/babel@0.0.20
  2. Build it with bit build to be sure everything is working
  3. Add a valid .ts file to the source directory.
  4.Try building again

Produces:
SyntaxError: unknown: Unexpected token, expected

Note that the TypeScript compiler is not listed as a dependency in bit.envs/compilers/babel@0.0.20 and probably should be. 

Also, if .ts files are included, then .tsx files should also be included.

## Specifications

  - Bit version: 0.12.12
  - Node version: v8.9.1
  - npm / yarn version: npm 6.0.0
  - Platform: Windows
  - Bit compiler (include version): bit.envs/compilers/babel@0.0.20
  - Bit tester (include version): none

**Comment by claudeduguay** [comment]
Is this supposed to work.?

Documentation readme says: "Compiles js, jsx and ts files."

I see a lot of downloads. Has anyone else tried using a TS file is this simply not supported? If not, the docs need to be fixed.

**Comment by itaymendel** [comment]
hi @claudeduguay , right now this is impossible, as the process of 'npm install' for the component is happening in an isolated version that is removed right after the process of bundling the component.

we need to add a feature to grab all logs, and include them into the 'console output' tab.

**Comment by itaymendel** [comment]
hi @claudeduguay ,
sorry for the very long response time.
do you have an example for a project that this will fail for?

**Comment by itaymendel** [comment]
stale issue, closing.
