### ISSUE TITLE
Components not shown on bitsrc, and cannot be imported through registry

### ISSUE THREAD

**Issue by rkkautsar** [teambit/bit#966]
## Expected Behavior

Components can be shown at bitsrc, i.e. https://bitsrc.io/rkkautsar/test, and can be imported through npm, i.e. `npm install @bit/rkkautsar.test.lib.components`.

## Actual Behavior

https://bitsrc.io/rkkautsar/test shown as empty. And `npm install` returns E404. Note that I can import other bits, for instance, @bit/bit.movie-app.components.item just fine. And `bit list rkkautsar.test` show my components correctly.

## Steps to Reproduce the Problem

  1. Following the tutorial on publishing react component
  1. Importing the component through npm

## Specifications

  - Bit version: 0.12.12
  - Node version: v9.9.0
  - npm / yarn version: npm 5.6.0
  - Platform: OS X 10.13.4
  - Bit compiler (include version): bit.envs/bundlers/webpack@0.0.11
  - Bit tester (include version): -

**Comment by GiladShoham** [comment]
Hi @rkkautsar 

When you exported components to that scope we had a slight hiccup in communication between the platform's services due to issues with the hosting provider.
I ran a re-sync for the Scope, so now you should see the components.

Sorry for the inconvenience.

**Comment by rkkautsar** [comment]
Actually, I have a private scope with the same problem. Is there any way to do a re-sync myself?

**Comment by rkkautsar** [comment]
Just tried deleting the scope and reexporting the components, but the problem still occur
