### ISSUE TITLE
Support access to log files for preview failures

### ISSUE THREAD

**Issue by claudeduguay** [teambit/bit#969]
## Expected Behavior

Example error log should be accessible, assuming there are more details

  npm ERR!     /root/.npm/_logs/2018-05-08T00_13_07_961Z-debug.log

Else, failure details should be available. 

It may be help to clearly define what happens when this code is triggered from @example comments. For example, if I have a Bootstrap react component, how do I ensure that Bootstrap css is accessible at rendering time?

## Actual Behavior

Error: Command failed: npm pack @bit/claudeduguay.react.components.listgroup@0.0.6
npm ERR! code E500
npm ERR! 500 Internal Server Error: @bit/claudeduguay.react.components.listgroup@0.0.6

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-05-08T00_13_07_961Z-debug.log

Impossible to reach /root/.npm/_logs/2018-05-08T00_13_07_961Z-debug.log

## Steps to Reproduce the Problem

  1. Build a component and upload it
  2. Assume a failure and look for details
  3. Log is not accessible for diagnosis and documentation clarifies nothing

## Specifications

  - Bit version: 0.12.12
  - Node version: v8.9.1
  - npm / yarn version: 6.0.0
  - Platform: Windows
  - Bit compiler (include version): bit.envs/compilers/babel@0.0.20
  - Bit tester (include version):

**Comment by claudeduguay** [comment]
How are errors to be diagnosed when they occur as a result of @example annotations?

**Comment by itaymendel** [comment]
hi @claudeduguay , right now this is impossible, as the process of 'npm install' for the component is happening in an isolated version that is removed right after the process of bundling the component.

we need to add a feature to grab all logs, and include them into the 'console output' tab.

after the next release of Bit, we plan to implement more improvements to the rendering feature. I'll make sure this is a part fo it.

**Comment by itaymendel** [comment]
this is relevant to bitsrc.io and we've taken it to heart.
closing this issue from github, and moving it to be handled internally.
