### ISSUE TITLE
on website -> create scope screen, no error message for scope title too long

### ISSUE THREAD

**Issue by nmrshll** [teambit/bit#975]
## Expected Behavior
give an error message to explain why i can't click the create button

## Actual Behavior
create button is simply disabled without further explanation

## Steps to Reproduce the Problem

  1. go to create scope screen
  1. type loooooong scope name
  1. create button is now disabled, but i don't know why

## Specifications

  - Bit version: website (as of 2018-05-08)
  - Node version:
  - npm / yarn version:
  - Platform:
  - Bit compiler (include version):
  - Bit tester (include version):

**Comment by KutnerUri** [comment]
Thanks for pointing this out. Seems easy to fix, we'll handle it :)

**Comment by itaymendel** [comment]
resolved

**Comment by KutnerUri** [comment]
Will now show errors live! 😃

**Comment by nmrshll** [comment]
Nice work, thanks for taking feedback in account !
