### ISSUE TITLE
Publish packages to NPM

### ISSUE THREAD

**Issue by calebeby** [teambit/bit#986]
Hi, would it be possible to actually upload the packages to npm, instead of using your own registry? That way, people could install the packages without setting up your registry on their computer, and I could reference the component as `@pigmice/components/button` instead of `@bit/pigmice/components/button`. Would this be possible?

I'm sure you already thought about this, but I'd like to know the limitations/thoughts that went into that decision.

Thanks

**Comment by calebeby** [comment]
Awesome, thanks for explaining, I will look into that!

**Comment by itaymendel** [comment]
closing this issue.

it is something that should be done by an extension, and not a feature in bit.

**Comment by markolofsen** [comment]
It's really easy if are you using special tool for publications.
It's works in your browser, without any special dependencies.

Try this library for that https://github.com/markolofsen/how_to_upload_package_to_npm

**Comment by gogoyqj** [comment]
@markolofsen 
not work for me...
invalid command

**Comment by gogoyqj** [comment]
@GiladShoham i tried bit@14.7.0 and it didn't work

both `npm i @bit/bit.extensions.npm.pack` and `bit import bit.extensions/npm/pack [--extension]` tried but still `warning: 'npm-pack' is not a valid command.`

docs https://docs.bit.dev/docs/ext-using-extensions.html#storage said `Imported extensions are stored in .bit/components/extensions directory.`, but actually stored in `.git/bit/components/`.

make me confused 😭

**Comment by GiladShoham** [comment]
@gogoyqj This extension is meant to run on bit server and not on the client. it can be installed on the client, but might not work exactly as expected. 
It also prepares the packages dependencies with @bit prefix. so it might not work well if you plan to publish components to the npmjs registry.
I would like to hear more about your needs.
Feel free to send me an email to gilad@bit.dev
