### ISSUE TITLE
Trying to resolve *.d.ts (typescript type definition file) as a js file

### ISSUE THREAD

**Issue by Maximaximum** [teambit/bit#997]
In Typescript, we often import only a type definition, which does not get converted into actual js code. E.g., `import { HttpObserve } from '@angular/common/http/src/client';`. When we install `@angular/common` via npm, the `http/src/client` folder contains only the type definitions. However, when we run `bit status`, bit is trying to resolve the path and find the `angular/common/http/src/client`.

## Expected Behavior
`ok` message in front of the component

## Actual Behavior
`missing packages dependencies (use your package manager to make sure all package dependencies are installed)` error.

## Steps to Reproduce the Problem

  1. Run `npm i --save @angular/common`
  1. In a typescript file, add a line `import { HttpObserve } from '@angular/common/http/src/client';`
  1. run `bit add` on the folder containing the file
  1. run `bit status`

## Specifications

  - Bit version: 0.12.13
  - Node version: 8.9.4
  - npm / yarn version: 5.6.0
  - Platform: Windows 8.1 64
  - Bit compiler (include version): typescript@0.0.3
  - Bit tester (include version): -

**Comment by davidfirst** [comment]
@Maximaximum , I tried to reproduce the issue and I do get the error 'missing packages dependencies', but as soon as I npm install '@angular/common', it works fine.
I understand that the d.ts file is needed only for the type checking and not for the actual implementation, but nevertheless, I would expect to have @angular/common as a dependency to my component because I require it in the code.

Do you see a case where this component is imported and @angular/common is not installed?

**Comment by Maximaximum** [comment]
@davidfirst well, it's weird that you managed to get rid of the error by simply running `npm install`. In my case, all the packages are installed, and `npm install` does not change anything - the issue persists.

**Comment by davidfirst** [comment]
@Maximaximum , I tried according to the description and still, I don't get an error.
I tried also on a Windows machine, but no error.
Attached a screenshot, maybe I'm missing something.

<img width="520" alt="screen shot 2018-06-05 at 7 14 13 pm" src="https://user-images.githubusercontent.com/1963573/41007631-be66fc96-68f4-11e8-9bc1-6ade6075e1d7.png">

**Comment by itaymendel** [comment]
stale issue. closing.
